table Diabetes
	lineageTag: b13326cb-8f8c-489f-9257-e7c66dfddf9c

	column Id
		dataType: int64
		formatString: 0
		lineageTag: f0931047-3ee5-476d-b728-0c9d9bb26c34
		summarizeBy: count
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Pregnancies
		dataType: int64
		formatString: 0
		lineageTag: a1e58e49-8d56-4a6a-8e12-4bc6d6fbdd12
		summarizeBy: sum
		sourceColumn: Pregnancies

		annotation SummarizationSetBy = Automatic

	column Glucose
		dataType: int64
		formatString: 0
		lineageTag: 9ef06563-9794-49f7-994f-47a73a9dd580
		summarizeBy: sum
		sourceColumn: Glucose

		annotation SummarizationSetBy = Automatic

	column BloodPressure
		dataType: int64
		formatString: 0
		lineageTag: 29b24d22-a3fb-4e3a-9c9c-5e17cfd9a56b
		summarizeBy: sum
		sourceColumn: BloodPressure

		annotation SummarizationSetBy = Automatic

	column SkinThickness
		dataType: int64
		formatString: 0
		lineageTag: 645774e8-dae5-4fee-93ce-56f73ea2d384
		summarizeBy: sum
		sourceColumn: SkinThickness

		annotation SummarizationSetBy = Automatic

	column Insulin
		dataType: int64
		formatString: 0
		lineageTag: 530f67e8-772c-49fe-8fd5-02821c5611fe
		summarizeBy: sum
		sourceColumn: Insulin

		annotation SummarizationSetBy = Automatic

	column BMI
		dataType: double
		lineageTag: e58ea45a-9f3c-41f5-bc34-3ef0b16b4e93
		summarizeBy: sum
		sourceColumn: BMI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DiabetesPedigreeFunction
		dataType: double
		lineageTag: 4f28bd8c-ef11-4b10-8b70-3968ec46c610
		summarizeBy: sum
		sourceColumn: DiabetesPedigreeFunction

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 4601efd3-359c-43a2-8452-166c73680d2e
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Outcome
		dataType: int64
		formatString: 0
		lineageTag: cc654319-f122-47b5-9c60-ee99534af6c6
		summarizeBy: sum
		sourceColumn: Outcome

		annotation SummarizationSetBy = Automatic

	partition Diabetes = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://repoz-my.sharepoint.com/personal/karthikrajan_repoz_ai/Documents/SaaS%20testing%20files/Domain%20Datasets%20-%20Remote%20inters/Healthcare%20files/Diabetes%204/health%20care%20diabetes%204.xlsx"), null, true),
				    #"Healthcare-Diabetes(1)_Sheet" = Source{[Item="Healthcare-Diabetes(1)",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Healthcare-Diabetes(1)_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Id", Int64.Type}, {"Pregnancies", Int64.Type}, {"Glucose", Int64.Type}, {"BloodPressure", Int64.Type}, {"SkinThickness", Int64.Type}, {"Insulin", Int64.Type}, {"BMI", type number}, {"DiabetesPedigreeFunction", type number}, {"Age", Int64.Type}, {"Outcome", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

