table 'Returns_Orders+ (Sample - Superstore)'
	lineageTag: 609e4af0-fda9-4a89-a0a4-fa8bdd686cdb

	column 'Order ID'
		dataType: string
		lineageTag: 2572b981-67ad-4b2a-8aaa-3f1e22214af8
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column Returned
		dataType: string
		lineageTag: ac3b190b-9f20-4b68-b9a7-34b8e2279eb5
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	partition 'Returns_Orders+ (Sample - Superstore)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Order ID" = 8573, #"Returned" = "certification"],
					        [#"Order ID" = 6534, #"Returned" = "completion"],
					        [#"Order ID" = 2260, #"Returned" = "model"],
					        [#"Order ID" = 7658, #"Returned" = "extreme"],
					        [#"Order ID" = 1203, #"Returned" = "depending"],
					        [#"Order ID" = 7848, #"Returned" = "loading"],
					        [#"Order ID" = 3730, #"Returned" = "apple"],
					        [#"Order ID" = 3184, #"Returned" = "bar"],
					        [#"Order ID" = 1610, #"Returned" = "individual"],
					        [#"Order ID" = 5323, #"Returned" = "guest"],
					        [#"Order ID" = 9648, #"Returned" = "checkout"],
					        [#"Order ID" = 3402, #"Returned" = "government"],
					        [#"Order ID" = 5183, #"Returned" = "blocks"],
					        [#"Order ID" = 4358, #"Returned" = "description"],
					        [#"Order ID" = 2221, #"Returned" = "wrote"],
					        [#"Order ID" = 2790, #"Returned" = "margaret"],
					        [#"Order ID" = 3315, #"Returned" = "appear"],
					        [#"Order ID" = 5303, #"Returned" = "cherry"],
					        [#"Order ID" = 5619, #"Returned" = "gender"],
					        [#"Order ID" = 3789, #"Returned" = "connector"],
					        [#"Order ID" = 5204, #"Returned" = "wedding"],
					        [#"Order ID" = 3946, #"Returned" = "resolved"],
					        [#"Order ID" = 4713, #"Returned" = "by"],
					        [#"Order ID" = 1547, #"Returned" = "pace"],
					        [#"Order ID" = 6348, #"Returned" = "street"],
					        [#"Order ID" = 3939, #"Returned" = "com"],
					        [#"Order ID" = 1816, #"Returned" = "img"],
					        [#"Order ID" = 3866, #"Returned" = "factors"],
					        [#"Order ID" = 2702, #"Returned" = "repair"],
					        [#"Order ID" = 5495, #"Returned" = "ground"],
					        [#"Order ID" = 6724, #"Returned" = "revolution"],
					        [#"Order ID" = 4344, #"Returned" = "robin"],
					        [#"Order ID" = 7428, #"Returned" = "meters"],
					        [#"Order ID" = 1894, #"Returned" = "performed"],
					        [#"Order ID" = 4219, #"Returned" = "sterling"],
					        [#"Order ID" = 9946, #"Returned" = "policies"],
					        [#"Order ID" = 2947, #"Returned" = "instrument"],
					        [#"Order ID" = 6729, #"Returned" = "madison"],
					        [#"Order ID" = 3301, #"Returned" = "nashville"],
					        [#"Order ID" = 3238, #"Returned" = "decrease"],
					        [#"Order ID" = 6478, #"Returned" = "intelligent"],
					        [#"Order ID" = 8977, #"Returned" = "humor"],
					        [#"Order ID" = 8391, #"Returned" = "character"],
					        [#"Order ID" = 7233, #"Returned" = "jp"],
					        [#"Order ID" = 9133, #"Returned" = "impossible"],
					        [#"Order ID" = 6053, #"Returned" = "damages"],
					        [#"Order ID" = 2175, #"Returned" = "judicial"],
					        [#"Order ID" = 7721, #"Returned" = "significant"],
					        [#"Order ID" = 9177, #"Returned" = "bunch"],
					        [#"Order ID" = 7327, #"Returned" = "bulletin"],
					        [#"Order ID" = 4442, #"Returned" = "reservations"],
					        [#"Order ID" = 4775, #"Returned" = "removal"],
					        [#"Order ID" = 9673, #"Returned" = "housing"],
					        [#"Order ID" = 6627, #"Returned" = "ads"],
					        [#"Order ID" = 6105, #"Returned" = "fiscal"],
					        [#"Order ID" = 9060, #"Returned" = "fuel"],
					        [#"Order ID" = 2528, #"Returned" = "filter"],
					        [#"Order ID" = 6045, #"Returned" = "sessions"],
					        [#"Order ID" = 9414, #"Returned" = "adjustment"],
					        [#"Order ID" = 3263, #"Returned" = "ideal"],
					        [#"Order ID" = 6632, #"Returned" = "golf"],
					        [#"Order ID" = 8284, #"Returned" = "destinations"],
					        [#"Order ID" = 5732, #"Returned" = "minor"],
					        [#"Order ID" = 3781, #"Returned" = "july"],
					        [#"Order ID" = 3516, #"Returned" = "email"],
					        [#"Order ID" = 5757, #"Returned" = "strap"],
					        [#"Order ID" = 6466, #"Returned" = "increases"],
					        [#"Order ID" = 6341, #"Returned" = "otherwise"],
					        [#"Order ID" = 5147, #"Returned" = "dave"],
					        [#"Order ID" = 8434, #"Returned" = "framed"],
					        [#"Order ID" = 5825, #"Returned" = "operating"],
					        [#"Order ID" = 7053, #"Returned" = "functionality"],
					        [#"Order ID" = 4422, #"Returned" = "must"],
					        [#"Order ID" = 8985, #"Returned" = "suitable"],
					        [#"Order ID" = 3255, #"Returned" = "manga"],
					        [#"Order ID" = 9069, #"Returned" = "requirement"],
					        [#"Order ID" = 4729, #"Returned" = "tin"],
					        [#"Order ID" = 3083, #"Returned" = "knew"],
					        [#"Order ID" = 7023, #"Returned" = "cream"],
					        [#"Order ID" = 7329, #"Returned" = "phoenix"],
					        [#"Order ID" = 7755, #"Returned" = "argentina"],
					        [#"Order ID" = 5116, #"Returned" = "example"],
					        [#"Order ID" = 8904, #"Returned" = "discovery"],
					        [#"Order ID" = 9957, #"Returned" = "euro"],
					        [#"Order ID" = 1009, #"Returned" = "photograph"],
					        [#"Order ID" = 9020, #"Returned" = "broadcasting"],
					        [#"Order ID" = 8808, #"Returned" = "passing"],
					        [#"Order ID" = 8265, #"Returned" = "dev"],
					        [#"Order ID" = 1757, #"Returned" = "philadelphia"],
					        [#"Order ID" = 3665, #"Returned" = "pain"],
					        [#"Order ID" = 8467, #"Returned" = "thursday"],
					        [#"Order ID" = 2100, #"Returned" = "tampa"],
					        [#"Order ID" = 9375, #"Returned" = "customers"],
					        [#"Order ID" = 8879, #"Returned" = "tennis"],
					        [#"Order ID" = 8112, #"Returned" = "convenience"],
					        [#"Order ID" = 8030, #"Returned" = "transactions"],
					        [#"Order ID" = 7530, #"Returned" = "university"],
					        [#"Order ID" = 5851, #"Returned" = "three"],
					        [#"Order ID" = 1171, #"Returned" = "ford"],
					        [#"Order ID" = 6002, #"Returned" = "wizard"],
					        [#"Order ID" = 4778, #"Returned" = "merchandise"],
					        [#"Order ID" = 3578, #"Returned" = "was"],
					        [#"Order ID" = 8495, #"Returned" = "logo"],
					        [#"Order ID" = 2154, #"Returned" = "networking"],
					        [#"Order ID" = 3660, #"Returned" = "answer"],
					        [#"Order ID" = 7435, #"Returned" = "inch"],
					        [#"Order ID" = 9439, #"Returned" = "math"],
					        [#"Order ID" = 9275, #"Returned" = "twice"],
					        [#"Order ID" = 7614, #"Returned" = "exposed"],
					        [#"Order ID" = 3482, #"Returned" = "objects"],
					        [#"Order ID" = 4184, #"Returned" = "hobbies"],
					        [#"Order ID" = 3219, #"Returned" = "carried"],
					        [#"Order ID" = 2685, #"Returned" = "kent"],
					        [#"Order ID" = 1527, #"Returned" = "wrap"],
					        [#"Order ID" = 7629, #"Returned" = "drives"],
					        [#"Order ID" = 9490, #"Returned" = "alive"],
					        [#"Order ID" = 9015, #"Returned" = "scholarship"],
					        [#"Order ID" = 7775, #"Returned" = "jelsoft"],
					        [#"Order ID" = 9273, #"Returned" = "mc"],
					        [#"Order ID" = 7057, #"Returned" = "reservation"],
					        [#"Order ID" = 2466, #"Returned" = "man"],
					        [#"Order ID" = 3276, #"Returned" = "funny"],
					        [#"Order ID" = 1307, #"Returned" = "starting"],
					        [#"Order ID" = 7072, #"Returned" = "guides"],
					        [#"Order ID" = 3416, #"Returned" = "add"],
					        [#"Order ID" = 9531, #"Returned" = "av"],
					        [#"Order ID" = 6076, #"Returned" = "mark"],
					        [#"Order ID" = 8064, #"Returned" = "plc"],
					        [#"Order ID" = 6807, #"Returned" = "qualifications"],
					        [#"Order ID" = 7940, #"Returned" = "surprise"],
					        [#"Order ID" = 1035, #"Returned" = "grow"],
					        [#"Order ID" = 8865, #"Returned" = "eg"],
					        [#"Order ID" = 9493, #"Returned" = "vacuum"],
					        [#"Order ID" = 6586, #"Returned" = "mo"],
					        [#"Order ID" = 8551, #"Returned" = "country"],
					        [#"Order ID" = 5701, #"Returned" = "cup"],
					        [#"Order ID" = 8507, #"Returned" = "thanks"],
					        [#"Order ID" = 8999, #"Returned" = "significantly"],
					        [#"Order ID" = 7036, #"Returned" = "family"],
					        [#"Order ID" = 2038, #"Returned" = "maria"],
					        [#"Order ID" = 3165, #"Returned" = "correctly"],
					        [#"Order ID" = 5161, #"Returned" = "monitors"],
					        [#"Order ID" = 4752, #"Returned" = "sponsored"],
					        [#"Order ID" = 4272, #"Returned" = "collect"],
					        [#"Order ID" = 9986, #"Returned" = "ho"],
					        [#"Order ID" = 4234, #"Returned" = "table"],
					        [#"Order ID" = 1720, #"Returned" = "missed"],
					        [#"Order ID" = 6180, #"Returned" = "parallel"],
					        [#"Order ID" = 9023, #"Returned" = "closely"],
					        [#"Order ID" = 2408, #"Returned" = "australia"],
					        [#"Order ID" = 9703, #"Returned" = "tool"],
					        [#"Order ID" = 9768, #"Returned" = "harvard"],
					        [#"Order ID" = 6130, #"Returned" = "anything"],
					        [#"Order ID" = 3600, #"Returned" = "di"],
					        [#"Order ID" = 7464, #"Returned" = "gloves"],
					        [#"Order ID" = 9075, #"Returned" = "diversity"],
					        [#"Order ID" = 9427, #"Returned" = "retired"],
					        [#"Order ID" = 2506, #"Returned" = "gold"],
					        [#"Order ID" = 4533, #"Returned" = "modified"],
					        [#"Order ID" = 1025, #"Returned" = "prayer"],
					        [#"Order ID" = 6226, #"Returned" = "mix"],
					        [#"Order ID" = 3826, #"Returned" = "visited"],
					        [#"Order ID" = 5917, #"Returned" = "image"],
					        [#"Order ID" = 1200, #"Returned" = "server"],
					        [#"Order ID" = 8422, #"Returned" = "campus"],
					        [#"Order ID" = 7750, #"Returned" = "teen"],
					        [#"Order ID" = 3953, #"Returned" = "suitable"],
					        [#"Order ID" = 2473, #"Returned" = "va"],
					        [#"Order ID" = 6555, #"Returned" = "discovered"],
					        [#"Order ID" = 8857, #"Returned" = "form"],
					        [#"Order ID" = 5816, #"Returned" = "due"],
					        [#"Order ID" = 8814, #"Returned" = "contain"],
					        [#"Order ID" = 4077, #"Returned" = "conference"],
					        [#"Order ID" = 7624, #"Returned" = "workshops"],
					        [#"Order ID" = 4174, #"Returned" = "carefully"],
					        [#"Order ID" = 9791, #"Returned" = "both"],
					        [#"Order ID" = 9870, #"Returned" = "optimization"],
					        [#"Order ID" = 6692, #"Returned" = "stroke"],
					        [#"Order ID" = 7803, #"Returned" = "currently"],
					        [#"Order ID" = 1863, #"Returned" = "because"],
					        [#"Order ID" = 7673, #"Returned" = "couples"],
					        [#"Order ID" = 5620, #"Returned" = "generation"],
					        [#"Order ID" = 7989, #"Returned" = "jewelry"],
					        [#"Order ID" = 9578, #"Returned" = "editorial"],
					        [#"Order ID" = 5437, #"Returned" = "sd"],
					        [#"Order ID" = 1296, #"Returned" = "changed"],
					        [#"Order ID" = 3197, #"Returned" = "merchants"],
					        [#"Order ID" = 7827, #"Returned" = "same"],
					        [#"Order ID" = 5805, #"Returned" = "filter"],
					        [#"Order ID" = 8443, #"Returned" = "reed"],
					        [#"Order ID" = 7454, #"Returned" = "ski"],
					        [#"Order ID" = 8135, #"Returned" = "actually"],
					        [#"Order ID" = 4368, #"Returned" = "protect"],
					        [#"Order ID" = 3004, #"Returned" = "actions"],
					        [#"Order ID" = 1250, #"Returned" = "ok"],
					        [#"Order ID" = 2280, #"Returned" = "artwork"],
					        [#"Order ID" = 7633, #"Returned" = "equipped"],
					        [#"Order ID" = 3193, #"Returned" = "properly"],
					        [#"Order ID" = 5739, #"Returned" = "community"],
					        [#"Order ID" = 6236, #"Returned" = "echo"],
					        [#"Order ID" = 3204, #"Returned" = "hotel"],
					        [#"Order ID" = 7098, #"Returned" = "same"],
					        [#"Order ID" = 9107, #"Returned" = "loose"],
					        [#"Order ID" = 6120, #"Returned" = "se"],
					        [#"Order ID" = 7662, #"Returned" = "grades"],
					        [#"Order ID" = 4525, #"Returned" = "layer"],
					        [#"Order ID" = 9287, #"Returned" = "pipeline"],
					        [#"Order ID" = 3086, #"Returned" = "dr"],
					        [#"Order ID" = 5009, #"Returned" = "ethnic"],
					        [#"Order ID" = 3091, #"Returned" = "lakes"],
					        [#"Order ID" = 7714, #"Returned" = "roll"],
					        [#"Order ID" = 6348, #"Returned" = "watch"],
					        [#"Order ID" = 9313, #"Returned" = "vendor"],
					        [#"Order ID" = 3640, #"Returned" = "emotional"],
					        [#"Order ID" = 1115, #"Returned" = "installed"],
					        [#"Order ID" = 6105, #"Returned" = "arkansas"],
					        [#"Order ID" = 3309, #"Returned" = "sporting"],
					        [#"Order ID" = 1873, #"Returned" = "attractive"],
					        [#"Order ID" = 9415, #"Returned" = "truck"],
					        [#"Order ID" = 7685, #"Returned" = "cleaner"],
					        [#"Order ID" = 1739, #"Returned" = "experiment"],
					        [#"Order ID" = 4941, #"Returned" = "bids"],
					        [#"Order ID" = 9801, #"Returned" = "enlarge"],
					        [#"Order ID" = 5501, #"Returned" = "might"],
					        [#"Order ID" = 2225, #"Returned" = "policies"],
					        [#"Order ID" = 1450, #"Returned" = "thou"],
					        [#"Order ID" = 7691, #"Returned" = "wv"],
					        [#"Order ID" = 8749, #"Returned" = "naked"],
					        [#"Order ID" = 7262, #"Returned" = "reducing"],
					        [#"Order ID" = 3381, #"Returned" = "nevada"],
					        [#"Order ID" = 7664, #"Returned" = "smoke"],
					        [#"Order ID" = 6807, #"Returned" = "cleaning"],
					        [#"Order ID" = 5604, #"Returned" = "boy"],
					        [#"Order ID" = 6117, #"Returned" = "peace"],
					        [#"Order ID" = 2469, #"Returned" = "work"],
					        [#"Order ID" = 8317, #"Returned" = "documentation"],
					        [#"Order ID" = 8960, #"Returned" = "kate"],
					        [#"Order ID" = 7235, #"Returned" = "flat"],
					        [#"Order ID" = 1858, #"Returned" = "photographer"],
					        [#"Order ID" = 2527, #"Returned" = "tv"],
					        [#"Order ID" = 9912, #"Returned" = "store"],
					        [#"Order ID" = 8971, #"Returned" = "reed"],
					        [#"Order ID" = 6759, #"Returned" = "conducted"],
					        [#"Order ID" = 6085, #"Returned" = "verification"],
					        [#"Order ID" = 7489, #"Returned" = "years"],
					        [#"Order ID" = 7011, #"Returned" = "golf"],
					        [#"Order ID" = 4630, #"Returned" = "exp"],
					        [#"Order ID" = 8301, #"Returned" = "talking"],
					        [#"Order ID" = 6393, #"Returned" = "supply"],
					        [#"Order ID" = 1174, #"Returned" = "biology"],
					        [#"Order ID" = 6946, #"Returned" = "truth"],
					        [#"Order ID" = 4886, #"Returned" = "tops"],
					        [#"Order ID" = 8726, #"Returned" = "figure"],
					        [#"Order ID" = 1024, #"Returned" = "yes"],
					        [#"Order ID" = 6525, #"Returned" = "taught"],
					        [#"Order ID" = 7081, #"Returned" = "ss"],
					        [#"Order ID" = 5327, #"Returned" = "af"],
					        [#"Order ID" = 8696, #"Returned" = "poor"],
					        [#"Order ID" = 8439, #"Returned" = "indonesia"],
					        [#"Order ID" = 7808, #"Returned" = "triple"],
					        [#"Order ID" = 8281, #"Returned" = "buttons"],
					        [#"Order ID" = 4958, #"Returned" = "however"],
					        [#"Order ID" = 5577, #"Returned" = "drug"],
					        [#"Order ID" = 1702, #"Returned" = "king"],
					        [#"Order ID" = 6127, #"Returned" = "ed"],
					        [#"Order ID" = 5062, #"Returned" = "failure"],
					        [#"Order ID" = 4181, #"Returned" = "accurate"],
					        [#"Order ID" = 2322, #"Returned" = "variety"],
					        [#"Order ID" = 5276, #"Returned" = "turkish"],
					        [#"Order ID" = 5908, #"Returned" = "cassette"],
					        [#"Order ID" = 4193, #"Returned" = "automatic"],
					        [#"Order ID" = 9250, #"Returned" = "em"],
					        [#"Order ID" = 5443, #"Returned" = "utilities"],
					        [#"Order ID" = 5125, #"Returned" = "pointed"],
					        [#"Order ID" = 2659, #"Returned" = "char"],
					        [#"Order ID" = 3846, #"Returned" = "medication"],
					        [#"Order ID" = 2120, #"Returned" = "respect"],
					        [#"Order ID" = 7038, #"Returned" = "presentations"],
					        [#"Order ID" = 3412, #"Returned" = "locate"],
					        [#"Order ID" = 1139, #"Returned" = "larry"],
					        [#"Order ID" = 6373, #"Returned" = "policy"],
					        [#"Order ID" = 9855, #"Returned" = "lecture"],
					        [#"Order ID" = 3491, #"Returned" = "contributions"],
					        [#"Order ID" = 5150, #"Returned" = "herein"],
					        [#"Order ID" = 7240, #"Returned" = "search"],
					        [#"Order ID" = 1277, #"Returned" = "anything"],
					        [#"Order ID" = 4712, #"Returned" = "nj"],
					        [#"Order ID" = 2314, #"Returned" = "apart"],
					        [#"Order ID" = 5724, #"Returned" = "wrong"],
					        [#"Order ID" = 6844, #"Returned" = "trans"],
					        [#"Order ID" = 4464, #"Returned" = "canyon"],
					        [#"Order ID" = 3269, #"Returned" = "senate"],
					        [#"Order ID" = 1229, #"Returned" = "lowest"],
					        [#"Order ID" = 3885, #"Returned" = "drama"],
					        [#"Order ID" = 8224, #"Returned" = "wild"],
					        [#"Order ID" = 9366, #"Returned" = "indian"],
					        [#"Order ID" = 2861, #"Returned" = "listen"],
					        [#"Order ID" = 8679, #"Returned" = "all"],
					        [#"Order ID" = 6499, #"Returned" = "movies"],
					        [#"Order ID" = 1057, #"Returned" = "sl"],
					        [#"Order ID" = 9643, #"Returned" = "boost"],
					        [#"Order ID" = 5033, #"Returned" = "lifetime"],
					        [#"Order ID" = 2145, #"Returned" = "yield"],
					        [#"Order ID" = 2245, #"Returned" = "removal"],
					        [#"Order ID" = 1582, #"Returned" = "bridge"],
					        [#"Order ID" = 7826, #"Returned" = "masters"],
					        [#"Order ID" = 2631, #"Returned" = "affiliates"],
					        [#"Order ID" = 8061, #"Returned" = "look"],
					        [#"Order ID" = 7192, #"Returned" = "code"],
					        [#"Order ID" = 8999, #"Returned" = "can"],
					        [#"Order ID" = 7044, #"Returned" = "bluetooth"],
					        [#"Order ID" = 3353, #"Returned" = "street"],
					        [#"Order ID" = 2034, #"Returned" = "issued"],
					        [#"Order ID" = 1424, #"Returned" = "meeting"],
					        [#"Order ID" = 3119, #"Returned" = "ge"],
					        [#"Order ID" = 7856, #"Returned" = "locked"],
					        [#"Order ID" = 6688, #"Returned" = "african"],
					        [#"Order ID" = 2213, #"Returned" = "feedback"],
					        [#"Order ID" = 8081, #"Returned" = "cod"],
					        [#"Order ID" = 4183, #"Returned" = "reproduction"],
					        [#"Order ID" = 5896, #"Returned" = "pension"],
					        [#"Order ID" = 9563, #"Returned" = "via"],
					        [#"Order ID" = 5232, #"Returned" = "animated"],
					        [#"Order ID" = 8770, #"Returned" = "drinking"],
					        [#"Order ID" = 3615, #"Returned" = "dates"],
					        [#"Order ID" = 2788, #"Returned" = "months"],
					        [#"Order ID" = 5551, #"Returned" = "room"],
					        [#"Order ID" = 7143, #"Returned" = "connect"],
					        [#"Order ID" = 7332, #"Returned" = "extent"],
					        [#"Order ID" = 2218, #"Returned" = "democratic"],
					        [#"Order ID" = 5005, #"Returned" = "administrative"],
					        [#"Order ID" = 3177, #"Returned" = "step"],
					        [#"Order ID" = 6316, #"Returned" = "null"],
					        [#"Order ID" = 9355, #"Returned" = "diversity"],
					        [#"Order ID" = 1310, #"Returned" = "medium"],
					        [#"Order ID" = 5149, #"Returned" = "compression"],
					        [#"Order ID" = 8672, #"Returned" = "babes"],
					        [#"Order ID" = 2002, #"Returned" = "inter"],
					        [#"Order ID" = 7098, #"Returned" = "operation"],
					        [#"Order ID" = 5978, #"Returned" = "mounted"],
					        [#"Order ID" = 9418, #"Returned" = "shoot"],
					        [#"Order ID" = 7672, #"Returned" = "size"],
					        [#"Order ID" = 8439, #"Returned" = "shipping"],
					        [#"Order ID" = 1412, #"Returned" = "hunter"],
					        [#"Order ID" = 5491, #"Returned" = "suggests"],
					        [#"Order ID" = 7426, #"Returned" = "nike"],
					        [#"Order ID" = 3822, #"Returned" = "notice"],
					        [#"Order ID" = 6489, #"Returned" = "himself"],
					        [#"Order ID" = 7102, #"Returned" = "mi"],
					        [#"Order ID" = 8945, #"Returned" = "corporation"],
					        [#"Order ID" = 7394, #"Returned" = "counters"],
					        [#"Order ID" = 6618, #"Returned" = "relating"],
					        [#"Order ID" = 5015, #"Returned" = "determination"],
					        [#"Order ID" = 6611, #"Returned" = "environments"],
					        [#"Order ID" = 8052, #"Returned" = "www"],
					        [#"Order ID" = 3327, #"Returned" = "wizard"],
					        [#"Order ID" = 2302, #"Returned" = "anniversary"],
					        [#"Order ID" = 8784, #"Returned" = "yorkshire"],
					        [#"Order ID" = 7949, #"Returned" = "manager"],
					        [#"Order ID" = 8041, #"Returned" = "view"],
					        [#"Order ID" = 8556, #"Returned" = "francis"],
					        [#"Order ID" = 6420, #"Returned" = "hampshire"],
					        [#"Order ID" = 4449, #"Returned" = "commissioner"],
					        [#"Order ID" = 2145, #"Returned" = "via"],
					        [#"Order ID" = 4899, #"Returned" = "consideration"],
					        [#"Order ID" = 6463, #"Returned" = "gross"],
					        [#"Order ID" = 3571, #"Returned" = "handbook"],
					        [#"Order ID" = 6733, #"Returned" = "partnership"],
					        [#"Order ID" = 2478, #"Returned" = "median"],
					        [#"Order ID" = 6216, #"Returned" = "consistent"],
					        [#"Order ID" = 7957, #"Returned" = "journal"],
					        [#"Order ID" = 1980, #"Returned" = "temple"],
					        [#"Order ID" = 4988, #"Returned" = "does"],
					        [#"Order ID" = 5578, #"Returned" = "your"],
					        [#"Order ID" = 9644, #"Returned" = "ottawa"],
					        [#"Order ID" = 9305, #"Returned" = "natural"],
					        [#"Order ID" = 4624, #"Returned" = "participate"],
					        [#"Order ID" = 1804, #"Returned" = "growth"],
					        [#"Order ID" = 9728, #"Returned" = "elizabeth"],
					        [#"Order ID" = 5899, #"Returned" = "politics"],
					        [#"Order ID" = 9028, #"Returned" = "grass"],
					        [#"Order ID" = 9630, #"Returned" = "ralph"],
					        [#"Order ID" = 7841, #"Returned" = "robot"],
					        [#"Order ID" = 5644, #"Returned" = "mercedes"],
					        [#"Order ID" = 5230, #"Returned" = "far"],
					        [#"Order ID" = 5963, #"Returned" = "repair"],
					        [#"Order ID" = 8424, #"Returned" = "glass"],
					        [#"Order ID" = 7602, #"Returned" = "characteristics"],
					        [#"Order ID" = 7905, #"Returned" = "walker"],
					        [#"Order ID" = 3995, #"Returned" = "quarter"],
					        [#"Order ID" = 1306, #"Returned" = "print"],
					        [#"Order ID" = 8794, #"Returned" = "weekend"],
					        [#"Order ID" = 2424, #"Returned" = "totally"],
					        [#"Order ID" = 7799, #"Returned" = "pr"],
					        [#"Order ID" = 2953, #"Returned" = "ceo"],
					        [#"Order ID" = 6470, #"Returned" = "integrated"],
					        [#"Order ID" = 2035, #"Returned" = "chinese"],
					        [#"Order ID" = 6076, #"Returned" = "stopped"],
					        [#"Order ID" = 5208, #"Returned" = "boxes"],
					        [#"Order ID" = 6668, #"Returned" = "contests"],
					        [#"Order ID" = 3571, #"Returned" = "lol"],
					        [#"Order ID" = 5126, #"Returned" = "matches"],
					        [#"Order ID" = 5069, #"Returned" = "kevin"],
					        [#"Order ID" = 9887, #"Returned" = "over"],
					        [#"Order ID" = 5659, #"Returned" = "zdnet"],
					        [#"Order ID" = 8410, #"Returned" = "policy"],
					        [#"Order ID" = 9740, #"Returned" = "warehouse"],
					        [#"Order ID" = 4175, #"Returned" = "destruction"],
					        [#"Order ID" = 4492, #"Returned" = "webmaster"],
					        [#"Order ID" = 4148, #"Returned" = "jack"],
					        [#"Order ID" = 2376, #"Returned" = "churches"],
					        [#"Order ID" = 5459, #"Returned" = "community"],
					        [#"Order ID" = 4078, #"Returned" = "ends"],
					        [#"Order ID" = 5309, #"Returned" = "ensure"],
					        [#"Order ID" = 3653, #"Returned" = "directories"],
					        [#"Order ID" = 6187, #"Returned" = "remember"],
					        [#"Order ID" = 1602, #"Returned" = "reverse"],
					        [#"Order ID" = 2988, #"Returned" = "since"],
					        [#"Order ID" = 1996, #"Returned" = "lesson"],
					        [#"Order ID" = 1743, #"Returned" = "stewart"],
					        [#"Order ID" = 6645, #"Returned" = "slot"],
					        [#"Order ID" = 1102, #"Returned" = "thirty"],
					        [#"Order ID" = 5096, #"Returned" = "louisiana"],
					        [#"Order ID" = 9406, #"Returned" = "how"],
					        [#"Order ID" = 1121, #"Returned" = "in"],
					        [#"Order ID" = 9784, #"Returned" = "newly"],
					        [#"Order ID" = 3836, #"Returned" = "universal"],
					        [#"Order ID" = 6065, #"Returned" = "wins"],
					        [#"Order ID" = 8762, #"Returned" = "ds"],
					        [#"Order ID" = 5520, #"Returned" = "operate"],
					        [#"Order ID" = 8632, #"Returned" = "control"],
					        [#"Order ID" = 1082, #"Returned" = "questions"],
					        [#"Order ID" = 6218, #"Returned" = "stadium"],
					        [#"Order ID" = 6402, #"Returned" = "cafe"],
					        [#"Order ID" = 2210, #"Returned" = "progress"],
					        [#"Order ID" = 4984, #"Returned" = "notice"],
					        [#"Order ID" = 7187, #"Returned" = "houses"],
					        [#"Order ID" = 5096, #"Returned" = "heat"],
					        [#"Order ID" = 5746, #"Returned" = "escape"],
					        [#"Order ID" = 3282, #"Returned" = "northeast"],
					        [#"Order ID" = 9561, #"Returned" = "biggest"],
					        [#"Order ID" = 9787, #"Returned" = "medicine"],
					        [#"Order ID" = 6516, #"Returned" = "image"],
					        [#"Order ID" = 2502, #"Returned" = "gnome"],
					        [#"Order ID" = 8059, #"Returned" = "extended"],
					        [#"Order ID" = 7221, #"Returned" = "resolved"],
					        [#"Order ID" = 1356, #"Returned" = "broadband"],
					        [#"Order ID" = 2681, #"Returned" = "largest"],
					        [#"Order ID" = 9703, #"Returned" = "modification"],
					        [#"Order ID" = 8907, #"Returned" = "washington"],
					        [#"Order ID" = 6338, #"Returned" = "police"],
					        [#"Order ID" = 6321, #"Returned" = "courtesy"],
					        [#"Order ID" = 1713, #"Returned" = "cemetery"],
					        [#"Order ID" = 9538, #"Returned" = "link"],
					        [#"Order ID" = 5606, #"Returned" = "mom"],
					        [#"Order ID" = 8529, #"Returned" = "evening"],
					        [#"Order ID" = 6370, #"Returned" = "betting"],
					        [#"Order ID" = 4329, #"Returned" = "consists"],
					        [#"Order ID" = 4715, #"Returned" = "grid"],
					        [#"Order ID" = 1135, #"Returned" = "themselves"],
					        [#"Order ID" = 9149, #"Returned" = "ie"],
					        [#"Order ID" = 6202, #"Returned" = "asking"],
					        [#"Order ID" = 2690, #"Returned" = "primary"],
					        [#"Order ID" = 8485, #"Returned" = "plc"],
					        [#"Order ID" = 2247, #"Returned" = "ut"],
					        [#"Order ID" = 1707, #"Returned" = "regardless"],
					        [#"Order ID" = 1889, #"Returned" = "marc"],
					        [#"Order ID" = 9490, #"Returned" = "quebec"],
					        [#"Order ID" = 8145, #"Returned" = "promise"],
					        [#"Order ID" = 2073, #"Returned" = "source"],
					        [#"Order ID" = 3711, #"Returned" = "taught"],
					        [#"Order ID" = 8111, #"Returned" = "employed"],
					        [#"Order ID" = 2627, #"Returned" = "can"],
					        [#"Order ID" = 4369, #"Returned" = "ideal"],
					        [#"Order ID" = 5703, #"Returned" = "package"],
					        [#"Order ID" = 5905, #"Returned" = "rm"],
					        [#"Order ID" = 4360, #"Returned" = "cheats"],
					        [#"Order ID" = 2039, #"Returned" = "emerging"],
					        [#"Order ID" = 1490, #"Returned" = "participants"],
					        [#"Order ID" = 5786, #"Returned" = "increases"],
					        [#"Order ID" = 2621, #"Returned" = "registry"],
					        [#"Order ID" = 1415, #"Returned" = "inventory"],
					        [#"Order ID" = 1994, #"Returned" = "evolution"],
					        [#"Order ID" = 7592, #"Returned" = "subjects"],
					        [#"Order ID" = 1200, #"Returned" = "restore"],
					        [#"Order ID" = 2629, #"Returned" = "believes"],
					        [#"Order ID" = 9690, #"Returned" = "archived"],
					        [#"Order ID" = 7570, #"Returned" = "sand"],
					        [#"Order ID" = 8966, #"Returned" = "women"],
					        [#"Order ID" = 9260, #"Returned" = "coordination"],
					        [#"Order ID" = 9978, #"Returned" = "integration"],
					        [#"Order ID" = 9874, #"Returned" = "rob"],
					        [#"Order ID" = 5382, #"Returned" = "portfolio"],
					        [#"Order ID" = 2341, #"Returned" = "same"],
					        [#"Order ID" = 5599, #"Returned" = "created"],
					        [#"Order ID" = 6790, #"Returned" = "sleeping"],
					        [#"Order ID" = 1839, #"Returned" = "hewlett"],
					        [#"Order ID" = 4390, #"Returned" = "awards"],
					        [#"Order ID" = 8331, #"Returned" = "dec"],
					        [#"Order ID" = 3332, #"Returned" = "meetings"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Order ID", type text},
					        {"Returned", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table