table 'Highlight Parameter'
	lineageTag: f6badc65-cca0-44b3-885f-9547e991e0fa

	measure 'Highlight Parameter Value' = SELECTEDVALUE('Highlight Parameter'[Highlight Parameter], 1.0)
		lineageTag: a0ac8ad8-9a3f-4f9b-863b-7bb001c28950

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Highlight Parameter'
		dataType: double
		formatString: 0
		lineageTag: 143d4110-fc35-4571-9c63-f1f1a2f2e9b6
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Highlight Parameter' = calculated
		mode: import
		source = GENERATESERIES(1.0, 5.0, 1.0)

	annotation PBI_Id = fa76f100e12f499b81460af7505d76ce

