table 'Parameter 2'
	lineageTag: 0bc27c58-ef73-416f-a87d-a01d0cfe32ca

	measure 'Parameter 2 Value' = SELECTEDVALUE('Parameter 2'[Parameter 2], 1.0)
		lineageTag: cf39400f-dc89-41d2-8919-55b3c3792f5b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Parameter 2'
		dataType: double
		formatString: 0
		lineageTag: 483ebd42-7451-47e5-a765-a9d6afcd22d8
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Parameter 2' = calculated
		mode: import
		source = GENERATESERIES(1.0, 10.0, 1.0)

	annotation PBI_Id = 618778691b2b4e83b3c7eeed38707dab

