table 'Top Customers'
	lineageTag: bdb29820-2307-4eee-a134-d7f2d952c97f

	measure 'Top Customers Value' = SELECTEDVALUE('Top Customers'[Top Customers], 5)
		lineageTag: 7af0af62-ba2d-4d0c-8adc-23f34150a272

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Top Customers'
		dataType: double
		formatString: 0
		lineageTag: 7d61ca45-a5c0-4e79-aa3b-af1cd47650ac
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Top Customers' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_Id = eab80534c19e4fa6a7a4d2815c108575

