table 'Orders+ (Sample - Superstore)'
	lineageTag: 9f51f324-b0bf-4dcc-aaf7-2d170f021b95

	measure 'Previous year' = VAR SelectedDate = SELECTEDVALUE('Select date'[Display As]) VAR PrevYearDate = DATE(YEAR(SelectedDate) - 1, MONTH(SelectedDate), DAY(SelectedDate)) VAR LowerBound = IF( MONTH(SelectedDate) <= 3, DATE(YEAR(SelectedDate) - 2, 4, 1), IF( MONTH(SelectedDate) >= 4 && YEAR(SelectedDate) - 1 = YEAR('Orders+ (Sample - Superstore)'[Order Date]), DATE(YEAR(SelectedDate) - 1, 4, 1), BLANK() ) ) RETURN IF( 'Orders+ (Sample - Superstore)'[Order Date] <= PrevYearDate && 'Orders+ (Sample - Superstore)'[Order Date] >= LowerBound, 'Orders+ (Sample - Superstore)'[Sales], BLANK() )
		formatString: 0
		lineageTag: 1bf43ee9-4713-40bf-a880-96acb1acde1a

	measure Calculation1 = NOT(ISBLANK(SUM('Orders+ (Sample - Superstore)'[Current year]))) || NOT(ISBLANK(SUM('Orders+ (Sample - Superstore)'[Previous year])))
		lineageTag: 4ebd23f8-ab30-40bd-86ba-b5588caa15f6

	measure MTD = VAR sel = SELECTEDVALUE('Select date'[Display As]) RETURN IF( 'Orders+ (Sample - Superstore)'[Order Date] <= sel && MONTH('Orders+ (Sample - Superstore)'[Order Date]) = MONTH(sel) && YEAR('Orders+ (Sample - Superstore)'[Order Date]) = YEAR(sel), TRUE(), FALSE() )
		lineageTag: 2123bf44-9245-4178-8c31-f9eb30103eb9

	measure 'Dynamic Measure values with YTD/MTD/QTD' = VAR selPeriod = SELECTEDVALUE('Select Period'[Display As]) VAR selDate = SELECTEDVALUE('Select date'[Display As]) VAR startDate = IF( MONTH(selDate) <= 3, DATE(YEAR(selDate) - 1, 4, 1), IF( MONTH(selDate) >= 4 && YEAR(selDate) = YEAR('Orders+ (Sample - Superstore)'[Order Date]), DATE(YEAR(selDate), 4, 1), BLANK() ) ) RETURN SWITCH( TRUE(), selPeriod = 1, 'Orders+ (Sample - Superstore)'[Order Date] <= selDate && 'Orders+ (Sample - Superstore)'[Order Date] >= startDate, selPeriod = 2, 'Orders+ (Sample - Superstore)'[MTD], selPeriod = 3, 'Orders+ (Sample - Superstore)'[QTD], BLANK() )
		lineageTag: 0b8d808d-2fe9-499a-837a-496722370ecd

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 031acd8c-da0c-4862-83ab-b2680fc54595
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 2ba49e0d-6a04-4b1f-8215-28e88008c1c5
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: datetime
		lineageTag: dd3edd8e-9964-45b8-8679-2bc455a1894d
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: datetime
		lineageTag: 759ca1fc-cd8f-4471-9b62-7a6903dca37d
		summarizeBy: none
		sourceColumn: 'Ship Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 976a95b9-4d9d-40cd-a8c8-d04a102b6e3c
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: d12b0086-5a83-4d1e-a5fb-9616232240db
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 346c4e5b-d88c-460a-909a-a482fcb7ad6c
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 584cb154-ef89-4bd1-b435-f0632b672620
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Country/Region'
		dataType: string
		lineageTag: 90602079-c534-4be4-bc55-a58033f8b041
		summarizeBy: none
		sourceColumn: 'Country/Region'

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 11127e30-6a03-420e-84f6-2b3bdfcf66c2
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: f7a008bb-2adf-4656-bf0b-41fea77fb246
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: b032ce5a-754c-4228-a3da-d34a66136603
		summarizeBy: sum
		sourceColumn: 'Postal Code'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 13e9d9d3-6fc1-4665-b16d-b2b128084e95
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: cd0b3a97-0c47-49ca-8644-9e1061576946
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 56ec650e-91a2-480a-b8b7-797136b5648d
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: 728bab23-c44b-4952-b4f7-f067b8023034
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 300646cf-03e7-4b4d-89ee-37e4e0fab9af
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: General Number
		lineageTag: 06d5d4ee-93b6-47e0-ab0d-4ed183cf752a
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 318ae58c-a857-4aa6-b0a8-1622a2069ccb
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: General Number
		lineageTag: 8331b4b8-c070-48a7-90ba-c12f5063aae9
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		formatString: General Number
		lineageTag: 3163199d-6f6f-4beb-ac5b-d0a7876a1473
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QTD = 'Orders+ (Sample - Superstore)'[Order Date] <= 'Orders+ (Sample - Superstore)'[Dynamic years] && QUARTER('Orders+ (Sample - Superstore)'[Order Date]) = QUARTER('Orders+ (Sample - Superstore)'[Dynamic years]) && YEAR('Orders+ (Sample - Superstore)'[Order Date]) = YEAR('Orders+ (Sample - Superstore)'[Dynamic years])
		lineageTag: b6569372-2e44-48c4-8470-ced33d5bc2d3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Current year' = IF( 'Orders+ (Sample - Superstore)'[Dynamic Measure values with YTD/MTD/QTD], 'Orders+ (Sample - Superstore)'[Sales], BLANK() )
		lineageTag: 10252f89-a627-4580-bc3b-d63966d99d21
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Orders+ (Sample - Superstore)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Row ID" = 5281, #"Order ID" = 5178, #"Order Date" = #date(2024, 6, 15), #"Ship Date" = #date(2020, 4, 13), #"Ship Mode" = "162.27.1.198", #"Customer ID" = 8446, #"Customer Name" = "Juliane Downs", #"Segment" = "legend", #"Country/Region" = "New Jersey", #"City" = "Houston", #"State" = "Idaho", #"Postal Code" = 504, #"Region" = "New Jersey", #"Product ID" = 1147, #"Category" = "fields", #"Sub-Category" = "equation", #"Product Name" = "Vallie Gomez", #"Sales" = 183.75, #"Quantity" = 8, #"Discount" = 869.05, #"Profit" = 62.8],
					        [#"Row ID" = 2719, #"Order ID" = 6379, #"Order Date" = #date(2023, 5, 27), #"Ship Date" = #date(2024, 5, 9), #"Ship Mode" = "245.142.240.248", #"Customer ID" = 7014, #"Customer Name" = "Lauralee Chang", #"Segment" = "profit", #"Country/Region" = "Mississippi", #"City" = "Ottawa", #"State" = "Idaho", #"Postal Code" = 824, #"Region" = "Mississippi", #"Product ID" = 9507, #"Category" = "cotton", #"Sub-Category" = "relatively", #"Product Name" = "Myron Stephens", #"Sales" = 575.79, #"Quantity" = 93, #"Discount" = 201.63, #"Profit" = 320.02],
					        [#"Row ID" = 9368, #"Order ID" = 9320, #"Order Date" = #date(2022, 3, 27), #"Ship Date" = #date(2023, 3, 6), #"Ship Mode" = "95.136.133.13", #"Customer ID" = 2406, #"Customer Name" = "Oswaldo Vincent", #"Segment" = "bargain", #"Country/Region" = "Rhode Island", #"City" = "Pueblo", #"State" = "Georgia", #"Postal Code" = 343, #"Region" = "California", #"Product ID" = 9363, #"Category" = "czech", #"Sub-Category" = "any", #"Product Name" = "Benjamin Hardy", #"Sales" = 803.45, #"Quantity" = 855, #"Discount" = 527.35, #"Profit" = 756.42],
					        [#"Row ID" = 988, #"Order ID" = 8424, #"Order Date" = #date(2022, 1, 3), #"Ship Date" = #date(2020, 1, 8), #"Ship Mode" = "34.39.165.99", #"Customer ID" = 7210, #"Customer Name" = "Marivel Lopez", #"Segment" = "salt", #"Country/Region" = "Vermont", #"City" = "Warren", #"State" = "Texas", #"Postal Code" = 237, #"Region" = "Ohio", #"Product ID" = 2355, #"Category" = "css", #"Sub-Category" = "teenage", #"Product Name" = "Lavonna Abbott", #"Sales" = 958.2, #"Quantity" = 505, #"Discount" = 796.57, #"Profit" = 602.66],
					        [#"Row ID" = 831, #"Order ID" = 7626, #"Order Date" = #date(2024, 10, 14), #"Ship Date" = #date(2021, 1, 18), #"Ship Mode" = "78.84.102.142", #"Customer ID" = 5275, #"Customer Name" = "Robbi Abbott", #"Segment" = "portrait", #"Country/Region" = "Alabama", #"City" = "Round Rock", #"State" = "New Mexico", #"Postal Code" = 509, #"Region" = "Louisiana", #"Product ID" = 3639, #"Category" = "ae", #"Sub-Category" = "bus", #"Product Name" = "Terica Bush", #"Sales" = 148.43, #"Quantity" = 325, #"Discount" = 461.38, #"Profit" = 597.04]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Row ID", Int64.Type},
					        {"Order ID", type text},
					        {"Order Date", type date},
					        {"Ship Date", type date},
					        {"Ship Mode", type text},
					        {"Customer ID", type text},
					        {"Customer Name", type text},
					        {"Segment", type text},
					        {"Country/Region", type text},
					        {"City", type text},
					        {"State", type text},
					        {"Postal Code", Int64.Type},
					        {"Region", type text},
					        {"Product ID", type text},
					        {"Category", type text},
					        {"Sub-Category", type text},
					        {"Product Name", type text},
					        {"Sales", type number},
					        {"Quantity", Int64.Type},
					        {"Discount", type number},
					        {"Profit", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table