table 'Orders+ (Sample - Superstore)_People'
	lineageTag: 0406ee0b-9efe-422e-97a8-4be0c6193155

	column 'Regional Manager'
		dataType: string
		lineageTag: d2a674ac-044b-40f5-bdac-0ae4541f74be
		summarizeBy: none
		sourceColumn: 'Regional Manager'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 1c3b951d-6a64-47de-81a5-2999972606dd
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition 'Orders+ (Sample - Superstore)_People' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Regional Manager" = "Michigan", #"Region" = "Wisconsin"],
					        [#"Regional Manager" = "New Jersey", #"Region" = "West Virginia"],
					        [#"Regional Manager" = "Indiana", #"Region" = "Ohio"],
					        [#"Regional Manager" = "Kentucky", #"Region" = "Missouri"],
					        [#"Regional Manager" = "Illinois", #"Region" = "Minnesota"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Regional Manager", type text},
					        {"Region", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table