table 'Orders+ (Sample - Superstore)_Returns'
	lineageTag: 00575d68-cec7-4014-8208-fbc16e935b23

	column Returned
		dataType: string
		lineageTag: ebd15d2f-1a67-4807-8edb-660937fd8269
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 24a16d87-8017-42f8-a7d6-12b82e721d11
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	partition 'Orders+ (Sample - Superstore)_Returns' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Returned" = "ssl", #"Order ID" = 6447],
					        [#"Returned" = "parameters", #"Order ID" = 3812],
					        [#"Returned" = "learning", #"Order ID" = 7346],
					        [#"Returned" = "review", #"Order ID" = 2043],
					        [#"Returned" = "formats", #"Order ID" = 3545]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Returned", type text},
					        {"Order ID", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table