table 'Minimum Hours Threshold'
	lineageTag: 9ecbb035-bd79-4320-b60f-f9453eeff6ba

	measure 'Minimum Hours Threshold Value' = SELECTEDVALUE('Minimum Hours Threshold'[Minimum Hours Threshold], 0)
		lineageTag: 83dc4303-0ae6-4972-b34a-593d6c638aeb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Minimum Hours Threshold'
		dataType: double
		formatString: 0
		lineageTag: f2537b37-e45d-4df7-a348-5f567d111bb6
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Minimum Hours Threshold' = calculated
		mode: import
		source = GENERATESERIES(0, 12, 1)

	annotation PBI_Id = a617bdc9dd2746efa3184814e65df1d7

