table 'Target Threshold'
	lineageTag: b1950143-c43c-4bbf-b714-4774f6c6f7ad

	measure 'Target Threshold Value' = SELECTEDVALUE('Target Threshold'[Target Threshold], 0.0)
		lineageTag: 57090712-f7f6-4af0-ac5c-3efe0734eb70

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Target Threshold'
		dataType: double
		formatString: 0
		lineageTag: a0b08a03-1594-432f-ab44-60d3a9df549d
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Target Threshold' = calculated
		mode: import
		source = GENERATESERIES(0.0, 100.0, 0.5)

	annotation PBI_Id = 8cb6f93145a94b23b87216bdfb704114

