table 'Sample - Superstore (2)_People'
	lineageTag: 21dd9d37-6048-4ef5-bb5e-19a386f9e449

	column 'Regional Manager'
		dataType: string
		lineageTag: 7873bcea-c6d3-4276-8007-9f29e0ad2e87
		summarizeBy: none
		sourceColumn: 'Regional Manager'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 4ad756f7-b6d9-4c28-a93a-d7f93fa5f20d
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition 'Sample - Superstore (2)_People' = m
		mode: import
		source =
				let
					    Source = Csv.Document(
					        File.Contents("https://saastestlatest.blob.core.windows.net/saas-test-reports/Sample%20-%20Superstore%20%282%29_People.csv?se=2025-11-03T10%3A46%3A01Z&sp=r&sv=2025-11-05&sr=b&sig=y/6ErKgp5LD%2BTfORvZ4o0ZDLI7Sj/WOlyGmYDg2i%2BSg%3D"),
					        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
					    ),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Regional Manager", type text}, {"Region", type text}})
					in
					    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table