table 'Sample - Superstore_Returns'
	lineageTag: 61689880-0040-4436-99d1-056606e19a50

	column Returned
		dataType: string
		lineageTag: 7a477d81-860b-4aff-a66a-bcaa733109e9
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 6cc8fc7e-c7b4-42eb-9c5d-f2a933d10b52
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	partition 'Sample - Superstore_Returns' = m
		mode: import
		source =
				let
					    Source = Csv.Document(
					        File.Contents("https://saastestlatest.blob.core.windows.net/saas-test-reports/Sample%20-%20Superstore_Returns.csv?se=2025-11-03T10%3A46%3A05Z&sp=r&sv=2025-11-05&sr=b&sig=5vOhK26R0S/g/dpSjphHu7lhKBOMJps7kCqw9%2BVLTXA%3D"),
					        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
					    ),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Returned", type text}, {"Order ID", type text}})
					in
					    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table