table 'Sample - Superstore (2)_Returns'
	lineageTag: 6053d60e-bf35-453b-b69a-7e1666a75f7f

	column Returned
		dataType: string
		lineageTag: 48433c7c-e499-4fdf-8fe8-39486696f182
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 0e89ae3c-faa8-4cd2-91c3-88bed2e810a5
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	partition 'Sample - Superstore (2)_Returns' = m
		mode: import
		source =
				let
					    Source = Csv.Document(
					        File.Contents("https://saastestlatest.blob.core.windows.net/saas-test-reports/Sample%20-%20Superstore%20%282%29_Returns.csv?se=2025-11-03T10%3A46%3A02Z&sp=r&sv=2025-11-05&sr=b&sig=tqPHmHop44WWDkC%2B7%2BhSbEPWSYTZBB40xEiA6WYzH/E%3D"),
					        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
					    ),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Returned", type text}, {"Order ID", type text}})
					in
					    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table