table 'Top Customers'
	lineageTag: 70cc0308-7d23-4cec-833e-430eb77ad565

	measure 'Top Customers Value' = SELECTEDVALUE('Top Customers'[Top Customers], 5)
		lineageTag: 4ffef371-4501-4670-b7e8-522715dc9228

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Top Customers'
		dataType: double
		formatString: 0
		lineageTag: 9dab1cf4-d7ed-44fb-a824-dcbafea642c2
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Top Customers' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_Id = 2d71a06155b744fcabfc06d483905cbc

