table 'health care diabetes'
	lineageTag: 96e882e0-3ce8-4173-b3ff-088a0f3c40a2

	column Id
		dataType: int64
		formatString: 0
		lineageTag: a11f52d4-8ee7-4fab-9ad0-4c5d4941325f
		summarizeBy: count
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Pregnancies
		dataType: int64
		formatString: 0
		lineageTag: ee05eaf0-2eb4-441e-beff-88abcbcc9540
		summarizeBy: sum
		sourceColumn: Pregnancies

		annotation SummarizationSetBy = Automatic

	column Glucose
		dataType: int64
		formatString: 0
		lineageTag: 8fbae63c-bdd8-4389-a0ce-ae4f1465d255
		summarizeBy: sum
		sourceColumn: Glucose

		annotation SummarizationSetBy = Automatic

	column BloodPressure
		dataType: int64
		formatString: 0
		lineageTag: 411bbea9-ce36-4502-840c-c3e0aed79576
		summarizeBy: sum
		sourceColumn: BloodPressure

		annotation SummarizationSetBy = Automatic

	column SkinThickness
		dataType: int64
		formatString: 0
		lineageTag: f1f5dfed-477d-4623-bea1-a91b3a21ce8d
		summarizeBy: sum
		sourceColumn: SkinThickness

		annotation SummarizationSetBy = Automatic

	column Insulin
		dataType: int64
		formatString: 0
		lineageTag: f7156d52-f3cd-4fd3-9c3e-9a5ad0a9fc9d
		summarizeBy: sum
		sourceColumn: Insulin

		annotation SummarizationSetBy = Automatic

	column BMI
		dataType: double
		lineageTag: 84df13aa-8b7c-4ac5-b2c5-c7c449f9f0f5
		summarizeBy: sum
		sourceColumn: BMI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DiabetesPedigreeFunction
		dataType: double
		lineageTag: 37d986cf-315c-486e-bd02-b990d8278e8e
		summarizeBy: sum
		sourceColumn: DiabetesPedigreeFunction

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Age
		dataType: int64
		formatString: 0
		lineageTag: e0446239-fba8-4c60-8e69-ef80d2e0b3c8
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Outcome
		dataType: int64
		formatString: 0
		lineageTag: a62d2ef4-cb24-45f7-a8b8-bdb58158349f
		summarizeBy: sum
		sourceColumn: Outcome

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"health care diabetes","TableItemName":"Outcome (bins)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 'Outcome (bins)' =
			IF(
				ISBLANK('health care diabetes'[Outcome]),
				BLANK(),
				INT('health care diabetes'[Outcome])
			)
		formatString: 0
		lineageTag: 967a10bb-552c-43e4-a6d0-3ce2708a8991
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "health care diabetes"
				          }
				        },
				        "Property": "Outcome"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 1.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"h","Entity":"health care diabetes"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"h"}},"Property":"Outcome"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"h"}},"Property":"Outcome"}},"Size":1.0}}}}

		annotation SummarizationSetBy = Automatic

	partition 'health care diabetes' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://repoz-my.sharepoint.com/personal/karthikrajan_repoz_ai/Documents/SaaS%20testing%20files/Domain%20Datasets%20-%20Remote%20inters/Healthcare%20files/Diabetes%203/health%20care%20diabetes%203.xlsx"), null, true),
				    #"Healthcare-Diabetes(1)_Sheet" = Source{[Item="Healthcare-Diabetes(1)",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Healthcare-Diabetes(1)_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Id", Int64.Type}, {"Pregnancies", Int64.Type}, {"Glucose", Int64.Type}, {"BloodPressure", Int64.Type}, {"SkinThickness", Int64.Type}, {"Insulin", Int64.Type}, {"BMI", type number}, {"DiabetesPedigreeFunction", type number}, {"Age", Int64.Type}, {"Outcome", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

