table 'Orders+ (Sample - Superstore)_Returns'
	lineageTag: ecef52b0-3635-4b59-9579-50fee97d70cd

	column 'Order ID'
		dataType: string
		lineageTag: 201fac20-067a-4a04-83db-545878e2395f
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column Returned
		dataType: string
		lineageTag: 9e36e93d-dda2-499c-92aa-eab1a88cb7f0
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	partition 'Orders+ (Sample - Superstore)_Returns' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Order ID" = 4384, #"Returned" = "victims"],
					        [#"Order ID" = 1886, #"Returned" = "lets"],
					        [#"Order ID" = 9795, #"Returned" = "de"],
					        [#"Order ID" = 7949, #"Returned" = "examined"],
					        [#"Order ID" = 7194, #"Returned" = "compiled"],
					        [#"Order ID" = 6023, #"Returned" = "larger"],
					        [#"Order ID" = 3939, #"Returned" = "blind"],
					        [#"Order ID" = 1643, #"Returned" = "bids"],
					        [#"Order ID" = 9299, #"Returned" = "posters"],
					        [#"Order ID" = 7141, #"Returned" = "good"],
					        [#"Order ID" = 6501, #"Returned" = "cheap"],
					        [#"Order ID" = 1872, #"Returned" = "constraints"],
					        [#"Order ID" = 8835, #"Returned" = "ml"],
					        [#"Order ID" = 4557, #"Returned" = "noise"],
					        [#"Order ID" = 7257, #"Returned" = "calculator"],
					        [#"Order ID" = 9244, #"Returned" = "tags"],
					        [#"Order ID" = 6345, #"Returned" = "no"],
					        [#"Order ID" = 5354, #"Returned" = "most"],
					        [#"Order ID" = 5827, #"Returned" = "skip"],
					        [#"Order ID" = 2606, #"Returned" = "radiation"],
					        [#"Order ID" = 8214, #"Returned" = "exhibition"],
					        [#"Order ID" = 3398, #"Returned" = "engagement"],
					        [#"Order ID" = 3354, #"Returned" = "objectives"],
					        [#"Order ID" = 1615, #"Returned" = "definitely"],
					        [#"Order ID" = 9756, #"Returned" = "assistant"],
					        [#"Order ID" = 6801, #"Returned" = "cast"],
					        [#"Order ID" = 5005, #"Returned" = "announces"],
					        [#"Order ID" = 8055, #"Returned" = "rob"],
					        [#"Order ID" = 9008, #"Returned" = "deutsch"],
					        [#"Order ID" = 1610, #"Returned" = "definitely"],
					        [#"Order ID" = 7022, #"Returned" = "accuracy"],
					        [#"Order ID" = 5641, #"Returned" = "johnson"],
					        [#"Order ID" = 5861, #"Returned" = "picture"],
					        [#"Order ID" = 3255, #"Returned" = "approach"],
					        [#"Order ID" = 1082, #"Returned" = "crm"],
					        [#"Order ID" = 5243, #"Returned" = "studio"],
					        [#"Order ID" = 6288, #"Returned" = "sing"],
					        [#"Order ID" = 3813, #"Returned" = "alerts"],
					        [#"Order ID" = 3868, #"Returned" = "fleet"],
					        [#"Order ID" = 3327, #"Returned" = "rev"],
					        [#"Order ID" = 9429, #"Returned" = "ohio"],
					        [#"Order ID" = 4130, #"Returned" = "november"],
					        [#"Order ID" = 5081, #"Returned" = "billion"],
					        [#"Order ID" = 2644, #"Returned" = "fire"],
					        [#"Order ID" = 6442, #"Returned" = "rhode"],
					        [#"Order ID" = 7357, #"Returned" = "memorabilia"],
					        [#"Order ID" = 7817, #"Returned" = "check"],
					        [#"Order ID" = 4947, #"Returned" = "equation"],
					        [#"Order ID" = 2216, #"Returned" = "focused"],
					        [#"Order ID" = 7271, #"Returned" = "afghanistan"],
					        [#"Order ID" = 7945, #"Returned" = "th"],
					        [#"Order ID" = 5779, #"Returned" = "checking"],
					        [#"Order ID" = 4053, #"Returned" = "carpet"],
					        [#"Order ID" = 3088, #"Returned" = "draw"],
					        [#"Order ID" = 8008, #"Returned" = "floor"],
					        [#"Order ID" = 6317, #"Returned" = "prime"],
					        [#"Order ID" = 3955, #"Returned" = "funny"],
					        [#"Order ID" = 6865, #"Returned" = "occurs"],
					        [#"Order ID" = 6736, #"Returned" = "mysql"],
					        [#"Order ID" = 9866, #"Returned" = "hood"],
					        [#"Order ID" = 1417, #"Returned" = "plus"],
					        [#"Order ID" = 7376, #"Returned" = "addition"],
					        [#"Order ID" = 5025, #"Returned" = "netscape"],
					        [#"Order ID" = 9393, #"Returned" = "pottery"],
					        [#"Order ID" = 4867, #"Returned" = "certain"],
					        [#"Order ID" = 4167, #"Returned" = "north"],
					        [#"Order ID" = 9541, #"Returned" = "labor"],
					        [#"Order ID" = 2370, #"Returned" = "storm"],
					        [#"Order ID" = 3979, #"Returned" = "max"],
					        [#"Order ID" = 8875, #"Returned" = "drew"],
					        [#"Order ID" = 2392, #"Returned" = "permits"],
					        [#"Order ID" = 9922, #"Returned" = "restaurant"],
					        [#"Order ID" = 1655, #"Returned" = "improve"],
					        [#"Order ID" = 3644, #"Returned" = "built"],
					        [#"Order ID" = 1830, #"Returned" = "fall"],
					        [#"Order ID" = 6481, #"Returned" = "swing"],
					        [#"Order ID" = 7074, #"Returned" = "task"],
					        [#"Order ID" = 5922, #"Returned" = "playstation"],
					        [#"Order ID" = 9911, #"Returned" = "codes"],
					        [#"Order ID" = 6237, #"Returned" = "te"],
					        [#"Order ID" = 2012, #"Returned" = "ease"],
					        [#"Order ID" = 2277, #"Returned" = "holdings"],
					        [#"Order ID" = 5276, #"Returned" = "considering"],
					        [#"Order ID" = 5152, #"Returned" = "training"],
					        [#"Order ID" = 8205, #"Returned" = "pay"],
					        [#"Order ID" = 5328, #"Returned" = "regularly"],
					        [#"Order ID" = 3161, #"Returned" = "views"],
					        [#"Order ID" = 7610, #"Returned" = "engineers"],
					        [#"Order ID" = 8449, #"Returned" = "stainless"],
					        [#"Order ID" = 4166, #"Returned" = "cartoons"],
					        [#"Order ID" = 6721, #"Returned" = "showtimes"],
					        [#"Order ID" = 4427, #"Returned" = "inspired"],
					        [#"Order ID" = 9674, #"Returned" = "enterprise"],
					        [#"Order ID" = 9319, #"Returned" = "hip"],
					        [#"Order ID" = 6491, #"Returned" = "hospitality"],
					        [#"Order ID" = 5215, #"Returned" = "test"],
					        [#"Order ID" = 7630, #"Returned" = "san"],
					        [#"Order ID" = 1493, #"Returned" = "cotton"],
					        [#"Order ID" = 4421, #"Returned" = "extensions"],
					        [#"Order ID" = 5306, #"Returned" = "diary"],
					        [#"Order ID" = 8015, #"Returned" = "output"],
					        [#"Order ID" = 8305, #"Returned" = "noticed"],
					        [#"Order ID" = 9257, #"Returned" = "opinion"],
					        [#"Order ID" = 1045, #"Returned" = "romania"],
					        [#"Order ID" = 2522, #"Returned" = "uniform"],
					        [#"Order ID" = 2624, #"Returned" = "ss"],
					        [#"Order ID" = 9355, #"Returned" = "special"],
					        [#"Order ID" = 6963, #"Returned" = "acts"],
					        [#"Order ID" = 3868, #"Returned" = "prev"],
					        [#"Order ID" = 7122, #"Returned" = "unable"],
					        [#"Order ID" = 7113, #"Returned" = "corn"],
					        [#"Order ID" = 3923, #"Returned" = "last"],
					        [#"Order ID" = 7531, #"Returned" = "recovery"],
					        [#"Order ID" = 3549, #"Returned" = "couples"],
					        [#"Order ID" = 7954, #"Returned" = "silver"],
					        [#"Order ID" = 9839, #"Returned" = "stainless"],
					        [#"Order ID" = 2829, #"Returned" = "historic"],
					        [#"Order ID" = 4975, #"Returned" = "ml"],
					        [#"Order ID" = 1445, #"Returned" = "iraqi"],
					        [#"Order ID" = 2062, #"Returned" = "author"],
					        [#"Order ID" = 7546, #"Returned" = "transfers"],
					        [#"Order ID" = 6343, #"Returned" = "theft"],
					        [#"Order ID" = 6665, #"Returned" = "eventually"],
					        [#"Order ID" = 7483, #"Returned" = "patient"],
					        [#"Order ID" = 7358, #"Returned" = "los"],
					        [#"Order ID" = 2211, #"Returned" = "expand"],
					        [#"Order ID" = 7508, #"Returned" = "jews"],
					        [#"Order ID" = 7037, #"Returned" = "nor"],
					        [#"Order ID" = 4535, #"Returned" = "farm"],
					        [#"Order ID" = 9699, #"Returned" = "amateur"],
					        [#"Order ID" = 2970, #"Returned" = "double"],
					        [#"Order ID" = 5785, #"Returned" = "sleeping"],
					        [#"Order ID" = 5558, #"Returned" = "covers"],
					        [#"Order ID" = 6921, #"Returned" = "cinema"],
					        [#"Order ID" = 1279, #"Returned" = "acc"],
					        [#"Order ID" = 8827, #"Returned" = "wed"],
					        [#"Order ID" = 9586, #"Returned" = "auctions"],
					        [#"Order ID" = 9108, #"Returned" = "rough"],
					        [#"Order ID" = 5142, #"Returned" = "sources"],
					        [#"Order ID" = 7180, #"Returned" = "brian"],
					        [#"Order ID" = 7322, #"Returned" = "hats"],
					        [#"Order ID" = 6157, #"Returned" = "iso"],
					        [#"Order ID" = 1140, #"Returned" = "charm"],
					        [#"Order ID" = 8728, #"Returned" = "professionals"],
					        [#"Order ID" = 9244, #"Returned" = "archives"],
					        [#"Order ID" = 2113, #"Returned" = "tight"],
					        [#"Order ID" = 1094, #"Returned" = "had"],
					        [#"Order ID" = 5876, #"Returned" = "bureau"],
					        [#"Order ID" = 2210, #"Returned" = "specific"],
					        [#"Order ID" = 2955, #"Returned" = "governments"],
					        [#"Order ID" = 7389, #"Returned" = "cause"],
					        [#"Order ID" = 6074, #"Returned" = "loose"],
					        [#"Order ID" = 5712, #"Returned" = "catering"],
					        [#"Order ID" = 1224, #"Returned" = "org"],
					        [#"Order ID" = 9982, #"Returned" = "pill"],
					        [#"Order ID" = 1200, #"Returned" = "explains"],
					        [#"Order ID" = 3712, #"Returned" = "rod"],
					        [#"Order ID" = 5034, #"Returned" = "knew"],
					        [#"Order ID" = 1693, #"Returned" = "living"],
					        [#"Order ID" = 8964, #"Returned" = "treatment"],
					        [#"Order ID" = 2907, #"Returned" = "finger"],
					        [#"Order ID" = 8968, #"Returned" = "up"],
					        [#"Order ID" = 2503, #"Returned" = "incorporated"],
					        [#"Order ID" = 5393, #"Returned" = "slave"],
					        [#"Order ID" = 5855, #"Returned" = "shorts"],
					        [#"Order ID" = 8816, #"Returned" = "lottery"],
					        [#"Order ID" = 4288, #"Returned" = "possibility"],
					        [#"Order ID" = 3018, #"Returned" = "extremely"],
					        [#"Order ID" = 3126, #"Returned" = "smart"],
					        [#"Order ID" = 9283, #"Returned" = "aware"],
					        [#"Order ID" = 3750, #"Returned" = "itself"],
					        [#"Order ID" = 7946, #"Returned" = "choice"],
					        [#"Order ID" = 4433, #"Returned" = "personals"],
					        [#"Order ID" = 5558, #"Returned" = "professional"],
					        [#"Order ID" = 4605, #"Returned" = "choices"],
					        [#"Order ID" = 2574, #"Returned" = "subscription"],
					        [#"Order ID" = 4358, #"Returned" = "multi"],
					        [#"Order ID" = 7517, #"Returned" = "pearl"],
					        [#"Order ID" = 9047, #"Returned" = "links"],
					        [#"Order ID" = 7025, #"Returned" = "exposure"],
					        [#"Order ID" = 6536, #"Returned" = "issued"],
					        [#"Order ID" = 5736, #"Returned" = "jamaica"],
					        [#"Order ID" = 5949, #"Returned" = "balance"],
					        [#"Order ID" = 5968, #"Returned" = "somewhat"],
					        [#"Order ID" = 7073, #"Returned" = "hits"],
					        [#"Order ID" = 2627, #"Returned" = "difficult"],
					        [#"Order ID" = 3546, #"Returned" = "potentially"],
					        [#"Order ID" = 6008, #"Returned" = "toronto"],
					        [#"Order ID" = 5964, #"Returned" = "developer"],
					        [#"Order ID" = 5865, #"Returned" = "licensing"],
					        [#"Order ID" = 5069, #"Returned" = "cutting"],
					        [#"Order ID" = 4126, #"Returned" = "course"],
					        [#"Order ID" = 1200, #"Returned" = "receive"],
					        [#"Order ID" = 1850, #"Returned" = "presidential"],
					        [#"Order ID" = 4102, #"Returned" = "claimed"],
					        [#"Order ID" = 5418, #"Returned" = "cvs"],
					        [#"Order ID" = 8998, #"Returned" = "press"],
					        [#"Order ID" = 1111, #"Returned" = "discs"],
					        [#"Order ID" = 4790, #"Returned" = "pants"],
					        [#"Order ID" = 9901, #"Returned" = "karen"],
					        [#"Order ID" = 9027, #"Returned" = "corp"],
					        [#"Order ID" = 5155, #"Returned" = "folk"],
					        [#"Order ID" = 2174, #"Returned" = "maintain"],
					        [#"Order ID" = 3939, #"Returned" = "press"],
					        [#"Order ID" = 8001, #"Returned" = "jews"],
					        [#"Order ID" = 7128, #"Returned" = "diary"],
					        [#"Order ID" = 3611, #"Returned" = "shaped"],
					        [#"Order ID" = 6135, #"Returned" = "indicates"],
					        [#"Order ID" = 1938, #"Returned" = "subsection"],
					        [#"Order ID" = 5784, #"Returned" = "halloween"],
					        [#"Order ID" = 6605, #"Returned" = "mall"],
					        [#"Order ID" = 7697, #"Returned" = "diverse"],
					        [#"Order ID" = 4694, #"Returned" = "visitor"],
					        [#"Order ID" = 8712, #"Returned" = "spa"],
					        [#"Order ID" = 2870, #"Returned" = "laboratory"],
					        [#"Order ID" = 2582, #"Returned" = "enables"],
					        [#"Order ID" = 4523, #"Returned" = "brothers"],
					        [#"Order ID" = 3633, #"Returned" = "shirt"],
					        [#"Order ID" = 8288, #"Returned" = "assist"],
					        [#"Order ID" = 5581, #"Returned" = "trained"],
					        [#"Order ID" = 8787, #"Returned" = "rainbow"],
					        [#"Order ID" = 8650, #"Returned" = "multi"],
					        [#"Order ID" = 2990, #"Returned" = "advertising"],
					        [#"Order ID" = 5693, #"Returned" = "hundred"],
					        [#"Order ID" = 9427, #"Returned" = "bet"],
					        [#"Order ID" = 3574, #"Returned" = "reader"],
					        [#"Order ID" = 8820, #"Returned" = "painted"],
					        [#"Order ID" = 5980, #"Returned" = "cancel"],
					        [#"Order ID" = 5308, #"Returned" = "points"],
					        [#"Order ID" = 7869, #"Returned" = "customize"],
					        [#"Order ID" = 8420, #"Returned" = "alexander"],
					        [#"Order ID" = 2668, #"Returned" = "kitchen"],
					        [#"Order ID" = 2145, #"Returned" = "nylon"],
					        [#"Order ID" = 5678, #"Returned" = "recreation"],
					        [#"Order ID" = 6116, #"Returned" = "physician"],
					        [#"Order ID" = 3856, #"Returned" = "pets"],
					        [#"Order ID" = 9440, #"Returned" = "xbox"],
					        [#"Order ID" = 5397, #"Returned" = "integration"],
					        [#"Order ID" = 1956, #"Returned" = "get"],
					        [#"Order ID" = 1962, #"Returned" = "rate"],
					        [#"Order ID" = 5693, #"Returned" = "zip"],
					        [#"Order ID" = 7368, #"Returned" = "better"],
					        [#"Order ID" = 3632, #"Returned" = "texts"],
					        [#"Order ID" = 8059, #"Returned" = "specialty"],
					        [#"Order ID" = 2310, #"Returned" = "seven"],
					        [#"Order ID" = 6955, #"Returned" = "teach"],
					        [#"Order ID" = 4447, #"Returned" = "automobile"],
					        [#"Order ID" = 5500, #"Returned" = "percent"],
					        [#"Order ID" = 8902, #"Returned" = "performed"],
					        [#"Order ID" = 9125, #"Returned" = "trim"],
					        [#"Order ID" = 2752, #"Returned" = "connector"],
					        [#"Order ID" = 8663, #"Returned" = "cheats"],
					        [#"Order ID" = 9984, #"Returned" = "scheme"],
					        [#"Order ID" = 4304, #"Returned" = "boston"],
					        [#"Order ID" = 7658, #"Returned" = "planning"],
					        [#"Order ID" = 4495, #"Returned" = "container"],
					        [#"Order ID" = 5281, #"Returned" = "intended"],
					        [#"Order ID" = 4200, #"Returned" = "asia"],
					        [#"Order ID" = 8699, #"Returned" = "antique"],
					        [#"Order ID" = 7798, #"Returned" = "scott"],
					        [#"Order ID" = 6550, #"Returned" = "hamilton"],
					        [#"Order ID" = 4759, #"Returned" = "offices"],
					        [#"Order ID" = 8821, #"Returned" = "zoom"],
					        [#"Order ID" = 6495, #"Returned" = "mars"],
					        [#"Order ID" = 5601, #"Returned" = "soup"],
					        [#"Order ID" = 2536, #"Returned" = "foods"],
					        [#"Order ID" = 3866, #"Returned" = "put"],
					        [#"Order ID" = 5169, #"Returned" = "tion"],
					        [#"Order ID" = 7324, #"Returned" = "cent"],
					        [#"Order ID" = 5530, #"Returned" = "char"],
					        [#"Order ID" = 1006, #"Returned" = "organic"],
					        [#"Order ID" = 2022, #"Returned" = "post"],
					        [#"Order ID" = 2844, #"Returned" = "proposal"],
					        [#"Order ID" = 4897, #"Returned" = "info"],
					        [#"Order ID" = 9645, #"Returned" = "offset"],
					        [#"Order ID" = 6499, #"Returned" = "accurate"],
					        [#"Order ID" = 6768, #"Returned" = "transport"],
					        [#"Order ID" = 3114, #"Returned" = "executive"],
					        [#"Order ID" = 4914, #"Returned" = "writing"],
					        [#"Order ID" = 8825, #"Returned" = "implementing"],
					        [#"Order ID" = 4342, #"Returned" = "birmingham"],
					        [#"Order ID" = 7286, #"Returned" = "avenue"],
					        [#"Order ID" = 8071, #"Returned" = "potentially"],
					        [#"Order ID" = 8219, #"Returned" = "modification"],
					        [#"Order ID" = 3190, #"Returned" = "leadership"],
					        [#"Order ID" = 9998, #"Returned" = "headset"],
					        [#"Order ID" = 3335, #"Returned" = "cities"],
					        [#"Order ID" = 6419, #"Returned" = "tutorials"],
					        [#"Order ID" = 9626, #"Returned" = "burning"],
					        [#"Order ID" = 6423, #"Returned" = "womens"],
					        [#"Order ID" = 1932, #"Returned" = "beds"],
					        [#"Order ID" = 9294, #"Returned" = "punk"],
					        [#"Order ID" = 2658, #"Returned" = "harbor"],
					        [#"Order ID" = 1814, #"Returned" = "advantage"],
					        [#"Order ID" = 3611, #"Returned" = "nurse"],
					        [#"Order ID" = 9473, #"Returned" = "essays"],
					        [#"Order ID" = 8740, #"Returned" = "highway"],
					        [#"Order ID" = 7203, #"Returned" = "parents"],
					        [#"Order ID" = 3534, #"Returned" = "chance"],
					        [#"Order ID" = 5363, #"Returned" = "ann"],
					        [#"Order ID" = 5129, #"Returned" = "lady"],
					        [#"Order ID" = 2666, #"Returned" = "researchers"],
					        [#"Order ID" = 7864, #"Returned" = "run"],
					        [#"Order ID" = 8327, #"Returned" = "guard"],
					        [#"Order ID" = 6378, #"Returned" = "flashing"],
					        [#"Order ID" = 6070, #"Returned" = "preferred"],
					        [#"Order ID" = 9490, #"Returned" = "acceptance"],
					        [#"Order ID" = 4367, #"Returned" = "upgrade"],
					        [#"Order ID" = 7177, #"Returned" = "diamond"],
					        [#"Order ID" = 4013, #"Returned" = "respectively"],
					        [#"Order ID" = 4508, #"Returned" = "wiki"],
					        [#"Order ID" = 3697, #"Returned" = "applies"],
					        [#"Order ID" = 7913, #"Returned" = "check"],
					        [#"Order ID" = 5222, #"Returned" = "selected"],
					        [#"Order ID" = 5743, #"Returned" = "individuals"],
					        [#"Order ID" = 7028, #"Returned" = "bulgaria"],
					        [#"Order ID" = 2536, #"Returned" = "domain"],
					        [#"Order ID" = 7020, #"Returned" = "corp"],
					        [#"Order ID" = 2926, #"Returned" = "ranking"],
					        [#"Order ID" = 9956, #"Returned" = "army"],
					        [#"Order ID" = 7010, #"Returned" = "com"],
					        [#"Order ID" = 7652, #"Returned" = "encyclopedia"],
					        [#"Order ID" = 7762, #"Returned" = "navigation"],
					        [#"Order ID" = 9485, #"Returned" = "thu"],
					        [#"Order ID" = 6437, #"Returned" = "settlement"],
					        [#"Order ID" = 6408, #"Returned" = "casino"],
					        [#"Order ID" = 2640, #"Returned" = "illness"],
					        [#"Order ID" = 5886, #"Returned" = "plant"],
					        [#"Order ID" = 3140, #"Returned" = "listings"],
					        [#"Order ID" = 4181, #"Returned" = "armed"],
					        [#"Order ID" = 8789, #"Returned" = "roof"],
					        [#"Order ID" = 8451, #"Returned" = "share"],
					        [#"Order ID" = 1615, #"Returned" = "continued"],
					        [#"Order ID" = 1887, #"Returned" = "steel"],
					        [#"Order ID" = 3009, #"Returned" = "calculated"],
					        [#"Order ID" = 6522, #"Returned" = "mens"],
					        [#"Order ID" = 9820, #"Returned" = "law"],
					        [#"Order ID" = 6095, #"Returned" = "interested"],
					        [#"Order ID" = 9661, #"Returned" = "instruments"],
					        [#"Order ID" = 6940, #"Returned" = "gloves"],
					        [#"Order ID" = 4897, #"Returned" = "depth"],
					        [#"Order ID" = 4778, #"Returned" = "sorted"],
					        [#"Order ID" = 5296, #"Returned" = "hilton"],
					        [#"Order ID" = 9791, #"Returned" = "dedicated"],
					        [#"Order ID" = 7336, #"Returned" = "python"],
					        [#"Order ID" = 1637, #"Returned" = "interactions"],
					        [#"Order ID" = 5515, #"Returned" = "returning"],
					        [#"Order ID" = 2044, #"Returned" = "sold"],
					        [#"Order ID" = 4591, #"Returned" = "now"],
					        [#"Order ID" = 2606, #"Returned" = "expanded"],
					        [#"Order ID" = 8226, #"Returned" = "era"],
					        [#"Order ID" = 4876, #"Returned" = "machinery"],
					        [#"Order ID" = 6014, #"Returned" = "font"],
					        [#"Order ID" = 4995, #"Returned" = "mentioned"],
					        [#"Order ID" = 7378, #"Returned" = "advanced"],
					        [#"Order ID" = 2421, #"Returned" = "safety"],
					        [#"Order ID" = 4910, #"Returned" = "committed"],
					        [#"Order ID" = 8672, #"Returned" = "taught"],
					        [#"Order ID" = 7858, #"Returned" = "properties"],
					        [#"Order ID" = 4902, #"Returned" = "international"],
					        [#"Order ID" = 3656, #"Returned" = "cookies"],
					        [#"Order ID" = 2198, #"Returned" = "blue"],
					        [#"Order ID" = 5346, #"Returned" = "paid"],
					        [#"Order ID" = 1834, #"Returned" = "frequency"],
					        [#"Order ID" = 2252, #"Returned" = "installed"],
					        [#"Order ID" = 9910, #"Returned" = "jordan"],
					        [#"Order ID" = 5808, #"Returned" = "corresponding"],
					        [#"Order ID" = 4192, #"Returned" = "course"],
					        [#"Order ID" = 6748, #"Returned" = "directions"],
					        [#"Order ID" = 6553, #"Returned" = "certainly"],
					        [#"Order ID" = 4359, #"Returned" = "making"],
					        [#"Order ID" = 7663, #"Returned" = "baltimore"],
					        [#"Order ID" = 8875, #"Returned" = "knife"],
					        [#"Order ID" = 5553, #"Returned" = "basketball"],
					        [#"Order ID" = 5389, #"Returned" = "re"],
					        [#"Order ID" = 9025, #"Returned" = "crime"],
					        [#"Order ID" = 8983, #"Returned" = "edward"],
					        [#"Order ID" = 5914, #"Returned" = "lowest"],
					        [#"Order ID" = 1755, #"Returned" = "main"],
					        [#"Order ID" = 5087, #"Returned" = "terror"],
					        [#"Order ID" = 6182, #"Returned" = "historic"],
					        [#"Order ID" = 2117, #"Returned" = "facial"],
					        [#"Order ID" = 9035, #"Returned" = "indian"],
					        [#"Order ID" = 3116, #"Returned" = "raised"],
					        [#"Order ID" = 9330, #"Returned" = "online"],
					        [#"Order ID" = 5357, #"Returned" = "judges"],
					        [#"Order ID" = 4001, #"Returned" = "covers"],
					        [#"Order ID" = 3949, #"Returned" = "antique"],
					        [#"Order ID" = 1391, #"Returned" = "supplied"],
					        [#"Order ID" = 6055, #"Returned" = "notice"],
					        [#"Order ID" = 6331, #"Returned" = "trying"],
					        [#"Order ID" = 6358, #"Returned" = "zip"],
					        [#"Order ID" = 3752, #"Returned" = "win"],
					        [#"Order ID" = 3630, #"Returned" = "legacy"],
					        [#"Order ID" = 2346, #"Returned" = "hide"],
					        [#"Order ID" = 7227, #"Returned" = "arrive"],
					        [#"Order ID" = 5718, #"Returned" = "daily"],
					        [#"Order ID" = 1985, #"Returned" = "bottom"],
					        [#"Order ID" = 1495, #"Returned" = "nine"],
					        [#"Order ID" = 1995, #"Returned" = "highest"],
					        [#"Order ID" = 1806, #"Returned" = "thus"],
					        [#"Order ID" = 7271, #"Returned" = "divided"],
					        [#"Order ID" = 1228, #"Returned" = "hit"],
					        [#"Order ID" = 4726, #"Returned" = "sports"],
					        [#"Order ID" = 2806, #"Returned" = "francis"],
					        [#"Order ID" = 6904, #"Returned" = "excerpt"],
					        [#"Order ID" = 8403, #"Returned" = "sick"],
					        [#"Order ID" = 1342, #"Returned" = "representing"],
					        [#"Order ID" = 7833, #"Returned" = "productivity"],
					        [#"Order ID" = 2083, #"Returned" = "para"],
					        [#"Order ID" = 3372, #"Returned" = "malaysia"],
					        [#"Order ID" = 7818, #"Returned" = "ongoing"],
					        [#"Order ID" = 5253, #"Returned" = "seem"],
					        [#"Order ID" = 1519, #"Returned" = "slip"],
					        [#"Order ID" = 6434, #"Returned" = "danger"],
					        [#"Order ID" = 5152, #"Returned" = "student"],
					        [#"Order ID" = 6514, #"Returned" = "settlement"],
					        [#"Order ID" = 7373, #"Returned" = "lingerie"],
					        [#"Order ID" = 1441, #"Returned" = "seen"],
					        [#"Order ID" = 5461, #"Returned" = "involve"],
					        [#"Order ID" = 2231, #"Returned" = "portion"],
					        [#"Order ID" = 5461, #"Returned" = "cell"],
					        [#"Order ID" = 2954, #"Returned" = "finding"],
					        [#"Order ID" = 5508, #"Returned" = "compaq"],
					        [#"Order ID" = 9074, #"Returned" = "jewish"],
					        [#"Order ID" = 8939, #"Returned" = "done"],
					        [#"Order ID" = 2741, #"Returned" = "position"],
					        [#"Order ID" = 1283, #"Returned" = "financing"],
					        [#"Order ID" = 7354, #"Returned" = "scale"],
					        [#"Order ID" = 4722, #"Returned" = "costs"],
					        [#"Order ID" = 1250, #"Returned" = "direct"],
					        [#"Order ID" = 9539, #"Returned" = "migration"],
					        [#"Order ID" = 4159, #"Returned" = "indoor"],
					        [#"Order ID" = 3159, #"Returned" = "motors"],
					        [#"Order ID" = 4808, #"Returned" = "consistent"],
					        [#"Order ID" = 1991, #"Returned" = "chair"],
					        [#"Order ID" = 7294, #"Returned" = "processor"],
					        [#"Order ID" = 9777, #"Returned" = "rest"],
					        [#"Order ID" = 4805, #"Returned" = "adjusted"],
					        [#"Order ID" = 3349, #"Returned" = "twice"],
					        [#"Order ID" = 5830, #"Returned" = "kept"],
					        [#"Order ID" = 9290, #"Returned" = "another"],
					        [#"Order ID" = 8151, #"Returned" = "shall"],
					        [#"Order ID" = 7730, #"Returned" = "theft"],
					        [#"Order ID" = 2787, #"Returned" = "firewall"],
					        [#"Order ID" = 8939, #"Returned" = "chance"],
					        [#"Order ID" = 4814, #"Returned" = "high"],
					        [#"Order ID" = 7074, #"Returned" = "recruitment"],
					        [#"Order ID" = 1738, #"Returned" = "mars"],
					        [#"Order ID" = 4648, #"Returned" = "archived"],
					        [#"Order ID" = 5803, #"Returned" = "strike"],
					        [#"Order ID" = 3323, #"Returned" = "review"],
					        [#"Order ID" = 4300, #"Returned" = "include"],
					        [#"Order ID" = 7789, #"Returned" = "bracelet"],
					        [#"Order ID" = 8902, #"Returned" = "parks"],
					        [#"Order ID" = 7718, #"Returned" = "cp"],
					        [#"Order ID" = 3509, #"Returned" = "terminal"],
					        [#"Order ID" = 7506, #"Returned" = "lung"],
					        [#"Order ID" = 6138, #"Returned" = "break"],
					        [#"Order ID" = 2611, #"Returned" = "minutes"],
					        [#"Order ID" = 6403, #"Returned" = "tools"],
					        [#"Order ID" = 5284, #"Returned" = "generally"],
					        [#"Order ID" = 5913, #"Returned" = "twin"],
					        [#"Order ID" = 3183, #"Returned" = "operational"],
					        [#"Order ID" = 1519, #"Returned" = "headquarters"],
					        [#"Order ID" = 8467, #"Returned" = "improvements"],
					        [#"Order ID" = 6405, #"Returned" = "shots"],
					        [#"Order ID" = 6849, #"Returned" = "pee"],
					        [#"Order ID" = 3233, #"Returned" = "happened"],
					        [#"Order ID" = 7879, #"Returned" = "calculate"],
					        [#"Order ID" = 4816, #"Returned" = "counters"],
					        [#"Order ID" = 8520, #"Returned" = "first"],
					        [#"Order ID" = 6824, #"Returned" = "situations"],
					        [#"Order ID" = 6668, #"Returned" = "jacket"],
					        [#"Order ID" = 4729, #"Returned" = "similar"],
					        [#"Order ID" = 8055, #"Returned" = "tank"],
					        [#"Order ID" = 6244, #"Returned" = "hilton"],
					        [#"Order ID" = 4589, #"Returned" = "jazz"],
					        [#"Order ID" = 9053, #"Returned" = "gamecube"],
					        [#"Order ID" = 4176, #"Returned" = "passes"],
					        [#"Order ID" = 9397, #"Returned" = "xhtml"],
					        [#"Order ID" = 4830, #"Returned" = "alphabetical"],
					        [#"Order ID" = 2444, #"Returned" = "around"],
					        [#"Order ID" = 5341, #"Returned" = "cream"],
					        [#"Order ID" = 1570, #"Returned" = "lamps"],
					        [#"Order ID" = 4540, #"Returned" = "by"],
					        [#"Order ID" = 1925, #"Returned" = "lan"],
					        [#"Order ID" = 9762, #"Returned" = "naked"],
					        [#"Order ID" = 6313, #"Returned" = "median"],
					        [#"Order ID" = 9907, #"Returned" = "rating"],
					        [#"Order ID" = 5381, #"Returned" = "plenty"],
					        [#"Order ID" = 8275, #"Returned" = "combo"],
					        [#"Order ID" = 9406, #"Returned" = "liberty"],
					        [#"Order ID" = 1543, #"Returned" = "consideration"],
					        [#"Order ID" = 2458, #"Returned" = "result"],
					        [#"Order ID" = 5197, #"Returned" = "manhattan"],
					        [#"Order ID" = 7142, #"Returned" = "despite"],
					        [#"Order ID" = 6158, #"Returned" = "personality"],
					        [#"Order ID" = 2203, #"Returned" = "eight"],
					        [#"Order ID" = 3951, #"Returned" = "tn"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Order ID", type text},
					        {"Returned", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table