table 'Highlight Parameter'
	lineageTag: 8454f588-a2fd-4a95-bbdb-b9128c41f662

	measure 'Highlight Parameter Value' = SELECTEDVALUE('Highlight Parameter'[Highlight Parameter], 1.0)
		lineageTag: 01ce65a2-c378-4bb6-924e-b7896095992b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Highlight Parameter'
		dataType: double
		formatString: 0
		lineageTag: 343263d7-71dd-43c4-95b0-64c43e1cff6c
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Highlight Parameter' = calculated
		mode: import
		source = GENERATESERIES(1.0, 5.0, 1.0)

	annotation PBI_Id = 7b18331d375340299286c36ba385bc07

