table 'Parameter 2'
	lineageTag: 31686950-bbd5-4410-9df3-d88ff5f8efa9

	measure 'Parameter 2 Value' = SELECTEDVALUE('Parameter 2'[Parameter 2], 1.0)
		lineageTag: 9a7a1c92-8434-45b9-a57f-19cf21455e57

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Parameter 2'
		dataType: double
		formatString: 0
		lineageTag: 5a1f4fb9-d30f-4b23-be78-5182b2eb5092
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Parameter 2' = calculated
		mode: import
		source = GENERATESERIES(1.0, 10.0, 1.0)

	annotation PBI_Id = 852d81d6bc2a4ce1996100267e6f2c2a

