table 'HR Dataset'
	lineageTag: ee8281ee-197b-483a-abfb-d438c83a07e7

	measure 'dep calc 3' = SUM('HR Dataset'[dep calc 2])
		formatString: 0
		lineageTag: 9d661e14-0e7c-472a-b116-a515196b3291

	column Employee_Name
		dataType: string
		lineageTag: 81e0806f-5592-4f34-86e7-e0e36b78b3b7
		summarizeBy: none
		sourceColumn: Employee_Name

		annotation SummarizationSetBy = Automatic

	column EmpID
		dataType: int64
		formatString: 0
		lineageTag: b29dfe97-1b65-4013-83b0-127c22732850
		summarizeBy: sum
		sourceColumn: EmpID

		annotation SummarizationSetBy = Automatic

	column MarriedID
		dataType: int64
		formatString: 0
		lineageTag: cae9cef1-3ec7-46a3-b403-cc870bfa695b
		summarizeBy: sum
		sourceColumn: MarriedID

		annotation SummarizationSetBy = Automatic

	column MaritalStatusID
		dataType: int64
		formatString: 0
		lineageTag: 4be75a9c-027f-43ba-b4ee-5025ced339b4
		summarizeBy: sum
		sourceColumn: MaritalStatusID

		annotation SummarizationSetBy = Automatic

	column GenderID
		dataType: int64
		formatString: 0
		lineageTag: 180afeb0-59eb-4432-9ca6-5e94e0fccfbd
		summarizeBy: sum
		sourceColumn: GenderID

		annotation SummarizationSetBy = Automatic

	column EmpStatusID
		dataType: int64
		formatString: 0
		lineageTag: d45b223b-27ba-4dfa-bb2c-882b441f9b86
		summarizeBy: sum
		sourceColumn: EmpStatusID

		annotation SummarizationSetBy = Automatic

	column DeptID
		dataType: int64
		formatString: 0
		lineageTag: 60665124-3267-4cd9-af55-b98cd07c577a
		summarizeBy: sum
		sourceColumn: DeptID

		annotation SummarizationSetBy = Automatic

	column PerfScoreID
		dataType: int64
		formatString: 0
		lineageTag: 2224501a-01a8-427d-b156-f37b883989d0
		summarizeBy: sum
		sourceColumn: PerfScoreID

		annotation SummarizationSetBy = Automatic

	column FromDiversityJobFairID
		dataType: int64
		formatString: 0
		lineageTag: d7818123-cc00-4c44-ba72-b82ac2fe2eba
		summarizeBy: sum
		sourceColumn: FromDiversityJobFairID

		annotation SummarizationSetBy = Automatic

	column Salary
		dataType: int64
		formatString: 0
		lineageTag: 3b1c1d87-b49c-4430-9309-e9b1fe2a66fa
		summarizeBy: sum
		sourceColumn: Salary

		annotation SummarizationSetBy = Automatic

	column Termd
		dataType: int64
		formatString: 0
		lineageTag: dae0d853-ce2f-4762-9ac1-9bff938c3872
		summarizeBy: sum
		sourceColumn: Termd

		annotation SummarizationSetBy = Automatic

	column PositionID
		dataType: int64
		formatString: 0
		lineageTag: d2341601-4cd9-4fc2-931d-638338e9ec91
		summarizeBy: sum
		sourceColumn: PositionID

		annotation SummarizationSetBy = Automatic

	column Position
		dataType: string
		lineageTag: 69f81a09-ff1d-43ad-831c-c298794ac5ec
		summarizeBy: none
		sourceColumn: Position

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 18f8c9c0-c5c6-437b-bc75-96aed2d1f702
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Zip
		dataType: int64
		formatString: 0
		lineageTag: b2f27386-192e-4600-9021-c23aa5fd4099
		summarizeBy: sum
		sourceColumn: Zip

		annotation SummarizationSetBy = Automatic

	column DOB
		dataType: datetime
		lineageTag: 7aec3f5e-f4a8-4234-a33c-9bb70756c140
		summarizeBy: none
		sourceColumn: DOB

		annotation SummarizationSetBy = Automatic

	column Sex
		dataType: string
		lineageTag: bca16780-8a3d-454e-ac0a-478c690649a6
		summarizeBy: none
		sourceColumn: Sex

		annotation SummarizationSetBy = Automatic

	column MaritalDesc
		dataType: string
		lineageTag: 197f779e-2136-4c86-a7e7-dbf765b2b4f1
		summarizeBy: none
		sourceColumn: MaritalDesc

		annotation SummarizationSetBy = Automatic

	column CitizenDesc
		dataType: string
		lineageTag: dd1a48b5-fbc3-4614-8a27-1ec32d753b7b
		summarizeBy: none
		sourceColumn: CitizenDesc

		annotation SummarizationSetBy = Automatic

	column HispanicLatino
		dataType: string
		lineageTag: f98eab18-3afc-4c30-96e1-9f58564348bd
		summarizeBy: none
		sourceColumn: HispanicLatino

		annotation SummarizationSetBy = Automatic

	column RaceDesc
		dataType: string
		lineageTag: ffc17c17-a9d0-46a4-9582-16053dd3e43d
		summarizeBy: none
		sourceColumn: RaceDesc

		annotation SummarizationSetBy = Automatic

	column DateofHire
		dataType: datetime
		lineageTag: 36bf465d-45c4-459d-99be-e345b81dadb4
		summarizeBy: none
		sourceColumn: DateofHire

		annotation SummarizationSetBy = Automatic

	column DateofTermination
		dataType: datetime
		lineageTag: 075cd2b9-084a-41d7-a2f2-dc00f556ddae
		summarizeBy: none
		sourceColumn: DateofTermination

		annotation SummarizationSetBy = Automatic

	column TermReason
		dataType: string
		lineageTag: 6e01f105-c46e-43f7-ac6f-6d43d80e5c01
		summarizeBy: none
		sourceColumn: TermReason

		annotation SummarizationSetBy = Automatic

	column EmploymentStatus
		dataType: string
		lineageTag: 4c1da697-10e9-4fad-b6cf-7b6a9bea0d48
		summarizeBy: none
		sourceColumn: EmploymentStatus

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: 06249e96-a21a-4743-9e8d-4974a7e594db
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column ManagerName
		dataType: string
		lineageTag: b0df34d5-fe21-4168-94be-96be2d094279
		summarizeBy: none
		sourceColumn: ManagerName

		annotation SummarizationSetBy = Automatic

	column ManagerID
		dataType: int64
		formatString: 0
		lineageTag: 75635c50-9bc1-488a-beb9-1fd841548449
		summarizeBy: sum
		sourceColumn: ManagerID

		annotation SummarizationSetBy = Automatic

	column RecruitmentSource
		dataType: string
		lineageTag: 49798a0f-07f9-4591-8b3f-3b4a48eb732f
		summarizeBy: none
		sourceColumn: RecruitmentSource

		annotation SummarizationSetBy = Automatic

	column PerformanceScore
		dataType: string
		lineageTag: 0aaba6d4-dd67-4918-b438-183cc90ab2a5
		summarizeBy: none
		sourceColumn: PerformanceScore

		annotation SummarizationSetBy = Automatic

	column EngagementSurvey
		dataType: double
		formatString: General Number
		lineageTag: 4458addc-973b-42ef-b463-6da0db1bc7f8
		summarizeBy: sum
		sourceColumn: EngagementSurvey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EmpSatisfaction
		dataType: int64
		formatString: 0
		lineageTag: 577d9252-3b1f-4aae-b633-5c18c64ef302
		summarizeBy: sum
		sourceColumn: EmpSatisfaction

		annotation SummarizationSetBy = Automatic

	column SpecialProjectsCount
		dataType: int64
		formatString: 0
		lineageTag: c29cf1d8-95a7-4ce1-903f-85509164289b
		summarizeBy: sum
		sourceColumn: SpecialProjectsCount

		annotation SummarizationSetBy = Automatic

	column LastPerformanceReview_Date
		dataType: datetime
		lineageTag: 8a5e45d9-0efe-4ad3-8f34-6527cb716dff
		summarizeBy: none
		sourceColumn: LastPerformanceReview_Date

		annotation SummarizationSetBy = Automatic

	column DaysLateLast30
		dataType: int64
		formatString: 0
		lineageTag: 4811afc0-6baf-48fd-98d6-c3ad011e727e
		summarizeBy: sum
		sourceColumn: DaysLateLast30

		annotation SummarizationSetBy = Automatic

	column Absences
		dataType: int64
		formatString: 0
		lineageTag: c794265d-0515-41aa-b260-13cf1b6db2b4
		summarizeBy: sum
		sourceColumn: Absences

		annotation SummarizationSetBy = Automatic

	column Calculation3 = 'HR Dataset'[TermReason] & FORMAT('HR Dataset'[Termd], "0")
		lineageTag: cb38b0d0-c9eb-4b4e-8220-5993628b7710
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column calculation3 = "abc"
		lineageTag: 18c0aa9a-cc4b-4884-a259-428ed9a2feb4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column C_Employee_Status = 'HR Dataset'[EmploymentStatus]
		lineageTag: 4563eceb-eef6-4289-aabf-5f303d8dab3a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Calculation1 = 'HR Dataset'[DeptID] + 'HR Dataset'[GenderID]
		formatString: 0
		lineageTag: 0629d2af-f6ab-49f6-bd8c-ddb1adc48498
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Calculation2 = 'HR Dataset'[Termd] * 'HR Dataset'[Salary] * 'HR Dataset'[EngagementSurvey]
		lineageTag: 259c6c76-cf64-44d6-b835-bd8a5ee2179c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'dep calc 1' = 'HR Dataset'[DeptID]
		formatString: 0
		lineageTag: fcf8cc17-5cc7-4b7b-9607-b0122f6165a0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'dep calc 2' = 'HR Dataset'[dep calc 1] * 'HR Dataset'[MarriedID]
		formatString: 0
		lineageTag: 1196a423-e360-4d3d-a444-4629aa57d5f3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'HR Dataset' = m
		mode: import
		source =
				let
					    Source = Csv.Document(
					        File.Contents("https://saastestlatest.blob.core.windows.net/saas-test-reports/HR%20Dataset.csv?se=2025-11-05T10%3A16%3A21Z&sp=r&sv=2025-11-05&sr=b&sig=4Ct4p1APeZPtCi7%2B4nhx3pdiVtFVICHcAqZbmjr1YqM%3D"),
					        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
					    ),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Employee_Name", type text}, {"EmpID", Int64.Type}, {"MarriedID", Int64.Type}, {"MaritalStatusID", Int64.Type}, {"GenderID", Int64.Type}, {"EmpStatusID", Int64.Type}, {"DeptID", Int64.Type}, {"PerfScoreID", Int64.Type}, {"FromDiversityJobFairID", Int64.Type}, {"Salary", Int64.Type}, {"Termd", Int64.Type}, {"PositionID", Int64.Type}, {"Position", type text}, {"State", type text}, {"Zip", Int64.Type}, {"DOB", type date}, {"Sex", type text}, {"MaritalDesc", type text}, {"CitizenDesc", type text}, {"HispanicLatino", type text}, {"RaceDesc", type text}, {"DateofHire", type date}, {"DateofTermination", type date}, {"TermReason", type text}, {"EmploymentStatus", type text}, {"Department", type text}, {"ManagerName", type text}, {"ManagerID", Int64.Type}, {"RecruitmentSource", type text}, {"PerformanceScore", type text}, {"EngagementSurvey", type number}, {"EmpSatisfaction", Int64.Type}, {"SpecialProjectsCount", Int64.Type}, {"LastPerformanceReview_Date", type date}, {"DaysLateLast30", Int64.Type}, {"Absences", Int64.Type}})
					in
					    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table