table 'Top Customers'
	lineageTag: 371e17c8-2671-4927-bc1b-aa63b3148ba4

	measure 'Top Customers Value' = SELECTEDVALUE('Top Customers'[Top Customers], 5)
		lineageTag: a40fb5a9-a019-405d-a97f-b496f3376d55

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Top Customers'
		dataType: double
		formatString: 0
		lineageTag: 41ec5ffd-1e76-445f-8568-5ec5ebc6a4c1
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Top Customers' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_Id = ec810159179644a9afeefa497c8c474b

