table 'Profit Bin Size'
	lineageTag: b6393de5-1d5c-4068-83d5-3aace292516d

	measure 'Profit Bin Size Value' = SELECTEDVALUE('Profit Bin Size'[Profit Bin Size], 50)
		lineageTag: fb8231a4-0245-466d-92bb-7f48b4e4855a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Profit Bin Size'
		dataType: double
		formatString: 0
		lineageTag: 17bb9693-5f3e-4cf4-85a9-30659bedc6ee
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Profit Bin Size' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_Id = 0d37dda399884785a00fc49ed278bfa9

