table 'Top Customers'
	lineageTag: 141c1288-d98b-4e46-9998-fd6f2d59491c

	measure 'Top Customers Value' = SELECTEDVALUE('Top Customers'[Top Customers], 5)
		lineageTag: c1f99064-dcec-4858-8f33-b5f544a8bd31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Top Customers'
		dataType: double
		formatString: 0
		lineageTag: 16d08b5b-98fd-46cf-aa71-1dd9e2e8751a
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Top Customers' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_Id = 4038af6433704988bd008a13f3e6e375

