table 'BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)'
	lineageTag: e73adda0-2955-42cc-913b-a3fef05d1f48

	column POLICY_NAME
		dataType: string
		lineageTag: 15455cc5-8fc2-4c32-a2f8-e52b3caf4f81
		summarizeBy: none
		sourceColumn: POLICY_NAME

		annotation SummarizationSetBy = Automatic

	column POLICY_ID
		dataType: int64
		formatString: 0
		lineageTag: dd6a1fdb-4ed8-4a62-b2a0-b602fcb5f481
		summarizeBy: sum
		sourceColumn: POLICY_ID

		annotation SummarizationSetBy = Automatic

	column POLICY_SCHEMA
		dataType: string
		lineageTag: 5fe81702-c40c-4c95-8bd8-a4d47813275c
		summarizeBy: none
		sourceColumn: POLICY_SCHEMA

		annotation SummarizationSetBy = Automatic

	column POLICY_DATABASE
		dataType: string
		lineageTag: 1dce29a4-7355-427b-a1c1-c169035d7a81
		summarizeBy: none
		sourceColumn: POLICY_DATABASE

		annotation SummarizationSetBy = Automatic

	column POLICY_BODY
		dataType: string
		lineageTag: a824fc8c-550c-4369-8acb-fcc75d944d59
		summarizeBy: none
		sourceColumn: POLICY_BODY

		annotation SummarizationSetBy = Automatic

	column COLUMN_NAME
		dataType: string
		lineageTag: 5a4c6953-cc85-446e-989f-3747e8e59446
		summarizeBy: none
		sourceColumn: COLUMN_NAME

		annotation SummarizationSetBy = Automatic

	column TABLE_NAME
		dataType: string
		lineageTag: 2fbb62af-058b-4f62-9e70-f9f35bb3437e
		summarizeBy: none
		sourceColumn: TABLE_NAME

		annotation SummarizationSetBy = Automatic

	column TABLE_ID
		dataType: int64
		formatString: 0
		lineageTag: 1aa5c345-354f-4003-9850-55011c872e4b
		summarizeBy: sum
		sourceColumn: TABLE_ID

		annotation SummarizationSetBy = Automatic

	column TABLE_SCHEMA
		dataType: string
		lineageTag: 26b40781-2652-4f18-850f-d51178bb7759
		summarizeBy: none
		sourceColumn: TABLE_SCHEMA

		annotation SummarizationSetBy = Automatic

	column TABLE_DATABASE
		dataType: string
		lineageTag: c1a5ddf1-d0b3-44c4-822a-df6045f514d3
		summarizeBy: none
		sourceColumn: TABLE_DATABASE

		annotation SummarizationSetBy = Automatic

	column REASON
		dataType: string
		lineageTag: 28bbf24f-9cf2-46a3-8070-5448d24167da
		summarizeBy: none
		sourceColumn: REASON

		annotation SummarizationSetBy = Automatic

	column track_id
		dataType: int64
		formatString: 0
		lineageTag: 1dd5c667-27ec-4ea2-b3cb-1a43b2e9cf11
		summarizeBy: sum
		sourceColumn: track_id

		annotation SummarizationSetBy = Automatic

	column track_title
		dataType: string
		lineageTag: 8b066b6b-46f4-4931-b813-bf0c19abbb7f
		summarizeBy: none
		sourceColumn: track_title

		annotation SummarizationSetBy = Automatic

	column is_career
		dataType: string
		lineageTag: ea407c9d-ff71-4ace-9dbe-0503e4dc3883
		summarizeBy: none
		sourceColumn: is_career

		annotation SummarizationSetBy = Automatic

	column course_count
		dataType: int64
		formatString: 0
		lineageTag: 614f5f88-5d2f-408b-8f05-ee01971ce4e8
		summarizeBy: sum
		sourceColumn: course_count

		annotation SummarizationSetBy = Automatic

	column total_chapters
		dataType: int64
		formatString: 0
		lineageTag: d46bba81-4a9d-4a30-86a3-8a54e4d3300d
		summarizeBy: sum
		sourceColumn: total_chapters

		annotation SummarizationSetBy = Automatic

	column total_exercises
		dataType: int64
		formatString: 0
		lineageTag: c4759f8f-b6de-4f00-8a7f-b09089225eb6
		summarizeBy: sum
		sourceColumn: total_exercises

		annotation SummarizationSetBy = Automatic

	column total_videos
		dataType: int64
		formatString: 0
		lineageTag: 198f5e30-5906-4ea9-bf75-16568a75c313
		summarizeBy: sum
		sourceColumn: total_videos

		annotation SummarizationSetBy = Automatic

	column total_xp
		dataType: double
		formatString: General Number
		lineageTag: 22b140ba-7681-4083-8133-0f0240123f25
		summarizeBy: sum
		sourceColumn: total_xp

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_xp_per_course
		dataType: double
		formatString: General Number
		lineageTag: 0ee456d7-6884-48c1-bb3e-4cc040ba5b6d
		summarizeBy: sum
		sourceColumn: avg_xp_per_course

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_time_hours
		dataType: double
		formatString: General Number
		lineageTag: d3b928e5-cbea-4163-beaa-46b6e59aec38
		summarizeBy: sum
		sourceColumn: avg_time_hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_duration_hours
		dataType: double
		formatString: General Number
		lineageTag: 3e1e18f1-542f-4742-8e6b-04b7a7cdb33c
		summarizeBy: sum
		sourceColumn: total_duration_hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column datasets_count
		dataType: int64
		formatString: 0
		lineageTag: bab858b1-3302-43dd-bef4-35001cbcc7ef
		summarizeBy: sum
		sourceColumn: datasets_count

		annotation SummarizationSetBy = Automatic

	column programming_languages
		dataType: string
		lineageTag: 8a1e4c19-2517-478a-b8d8-526988747449
		summarizeBy: none
		sourceColumn: programming_languages

		annotation SummarizationSetBy = Automatic

	column course_difficulty_levels
		dataType: string
		lineageTag: 24f28f16-8837-4f90-bf2b-15e6b36866e4
		summarizeBy: none
		sourceColumn: course_difficulty_levels

		annotation SummarizationSetBy = Automatic

	column predominant_difficulty
		dataType: int64
		formatString: 0
		lineageTag: b3e655f0-329e-4304-be17-64ba7c8b5573
		summarizeBy: sum
		sourceColumn: predominant_difficulty

		annotation SummarizationSetBy = Automatic

	column course_titles
		dataType: string
		lineageTag: 29b477bb-8700-4787-b2a5-4797d02d3103
		summarizeBy: none
		sourceColumn: course_titles

		annotation SummarizationSetBy = Automatic

	column instructors
		dataType: string
		lineageTag: 75224a94-dfcd-461e-a331-7737059634d3
		summarizeBy: none
		sourceColumn: instructors

		annotation SummarizationSetBy = Automatic

	column participant_count
		dataType: int64
		formatString: 0
		lineageTag: ee1a4332-5fc8-452a-814f-443ff59e49ba
		summarizeBy: sum
		sourceColumn: participant_count

		annotation SummarizationSetBy = Automatic

	column id
		dataType: int64
		formatString: 0
		lineageTag: 530eec98-6276-4a31-afb6-c1029dbfcb9a
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column title
		dataType: string
		lineageTag: 8a4d433c-41ac-4d0a-9d68-0c94c7d60f7c
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: ed5f7127-882f-4ab7-a065-f02f65eedb7a
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column short_description
		dataType: string
		lineageTag: 1ae07aea-2d83-47ea-9a9c-03095f578061
		summarizeBy: none
		sourceColumn: short_description

		annotation SummarizationSetBy = Automatic

	column programming_language
		dataType: string
		lineageTag: 2f339c9e-9b0c-4737-8b70-f042ab8b661f
		summarizeBy: none
		sourceColumn: programming_language

		annotation SummarizationSetBy = Automatic

	column difficulty_level
		dataType: int64
		formatString: 0
		lineageTag: 115cf1db-7052-4782-a3c8-16cf9b95cab4
		summarizeBy: sum
		sourceColumn: difficulty_level

		annotation SummarizationSetBy = Automatic

	column xp
		dataType: int64
		formatString: 0
		lineageTag: d14868e9-d2e0-4451-b072-cdde64ff173d
		summarizeBy: sum
		sourceColumn: xp

		annotation SummarizationSetBy = Automatic

	column time_needed_in_hours
		dataType: int64
		formatString: 0
		lineageTag: f9038216-a17c-4140-a7b8-e6dfd3d9052d
		summarizeBy: sum
		sourceColumn: time_needed_in_hours

		annotation SummarizationSetBy = Automatic

	column topic_id
		dataType: double
		formatString: General Number
		lineageTag: dcf303d1-a9aa-4e38-8411-ffc8b3fcff07
		summarizeBy: sum
		sourceColumn: topic_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column technology_id
		dataType: int64
		formatString: 0
		lineageTag: 86218580-d1fc-4858-965a-3c7d26cdd60c
		summarizeBy: sum
		sourceColumn: technology_id

		annotation SummarizationSetBy = Automatic

	column content_area
		dataType: string
		lineageTag: 40dc39f9-6a6d-4424-bfe9-9b823dd73b2c
		summarizeBy: none
		sourceColumn: content_area

		annotation SummarizationSetBy = Automatic

	column link
		dataType: string
		lineageTag: bcda22d3-1296-4aaf-b03d-ecfe38298577
		summarizeBy: none
		sourceColumn: link

		annotation SummarizationSetBy = Automatic

	column image_url
		dataType: string
		lineageTag: 0b8b464f-4b22-42eb-8376-7e746cc2de58
		summarizeBy: none
		sourceColumn: image_url

		annotation SummarizationSetBy = Automatic

	column last_updated_on
		dataType: datetime
		lineageTag: ffe5aec0-69f6-4652-b383-014c0b3fa13c
		summarizeBy: none
		sourceColumn: last_updated_on

		annotation SummarizationSetBy = Automatic

	column nb_of_subscriptions
		dataType: int64
		formatString: 0
		lineageTag: 8138f211-561c-4b2c-898f-c3ea3b2619cf
		summarizeBy: sum
		sourceColumn: nb_of_subscriptions

		annotation SummarizationSetBy = Automatic

	column num_chapters
		dataType: int64
		formatString: 0
		lineageTag: 10b73295-5f2e-4cfb-be19-28ad2c8036f7
		summarizeBy: sum
		sourceColumn: num_chapters

		annotation SummarizationSetBy = Automatic

	column num_exercises
		dataType: int64
		formatString: 0
		lineageTag: 14f72952-84d5-4255-b61a-8d02b42e1e99
		summarizeBy: sum
		sourceColumn: num_exercises

		annotation SummarizationSetBy = Automatic

	column num_videos
		dataType: int64
		formatString: 0
		lineageTag: 18591471-69c2-4a48-8c10-4bb9758e4191
		summarizeBy: sum
		sourceColumn: num_videos

		annotation SummarizationSetBy = Automatic

	column 'datasets_count 1'
		dataType: int64
		formatString: 0
		lineageTag: f1b28edd-8d4f-417b-b772-d2ea2d078e1d
		summarizeBy: sum
		sourceColumn: 'datasets_count 1'

		annotation SummarizationSetBy = Automatic

	column instructors_names
		dataType: string
		lineageTag: c2509b3a-df3e-4dbd-8f5b-d867c93a9b19
		summarizeBy: none
		sourceColumn: instructors_names

		annotation SummarizationSetBy = Automatic

	column collaborators_names
		dataType: string
		lineageTag: 48d41882-6b09-49f8-9cee-b0bd90104358
		summarizeBy: none
		sourceColumn: collaborators_names

		annotation SummarizationSetBy = Automatic

	column tracks_titles
		dataType: string
		lineageTag: d342986a-b379-41e9-a760-0adf10d8d014
		summarizeBy: none
		sourceColumn: tracks_titles

		annotation SummarizationSetBy = Automatic

	column prerequisites_titles
		dataType: string
		lineageTag: 8ce90f42-74ec-432b-bee4-64690e8b928d
		summarizeBy: none
		sourceColumn: prerequisites_titles

		annotation SummarizationSetBy = Automatic

	column 'technology_id 2'
		dataType: int64
		formatString: 0
		lineageTag: e55114b3-9b07-4aac-b039-4a5b75ee2624
		summarizeBy: sum
		sourceColumn: 'technology_id 2'

		annotation SummarizationSetBy = Automatic

	column 'technology_name 1'
		dataType: string
		lineageTag: 4678c186-747f-418c-b5d8-a0646f51f267
		summarizeBy: none
		sourceColumn: 'technology_name 1'

		annotation SummarizationSetBy = Automatic

	column 'topic_id 1'
		dataType: int64
		formatString: 0
		lineageTag: 89e398f2-b5fe-414f-9270-4e5f7d976445
		summarizeBy: sum
		sourceColumn: 'topic_id 1'

		annotation SummarizationSetBy = Automatic

	column topic_name
		dataType: string
		lineageTag: 85f7047a-99e5-431a-82e5-b9331c270e8b
		summarizeBy: none
		sourceColumn: topic_name

		annotation SummarizationSetBy = Automatic

	partition 'BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)' = m
		mode: import
		source =
				let 
					#"Source0" = Table.NestedJoin(#"BCR_2022_07_DDM_ROLLOUT_BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)", {"POLICY_ID"}, #"all_tracks.csv_BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)", {"track_id"}, "all_tracks.csv_BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)", JoinKind.Inner),
					#"Expand0" = Table.ExpandTableColumn(#"Source0", "all_tracks.csv_BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)", {"track_id", "track_title", "is_career", "course_count", "total_chapters", "total_exercises", "total_videos", "total_xp", "avg_xp_per_course", "avg_time_hours", "total_duration_hours", "datasets_count", "programming_languages", "course_difficulty_levels", "predominant_difficulty", "course_titles", "instructors", "participant_count"}, {"track_id", "track_title", "is_career", "course_count", "total_chapters", "total_exercises", "total_videos", "total_xp", "avg_xp_per_course", "avg_time_hours", "total_duration_hours", "datasets_count", "programming_languages", "course_difficulty_levels", "predominant_difficulty", "course_titles", "instructors", "participant_count"}),
					#"Source1" = Table.NestedJoin(#"Expand0", {"datasets_count"}, #"courses.csv1_BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)", {"datasets_count"}, "courses.csv1_BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)", JoinKind.RightOuter),
					#"Expand1" = Table.ExpandTableColumn(#"Source1", "courses.csv1_BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)", {"id", "title", "description", "short_description", "programming_language", "difficulty_level", "xp", "time_needed_in_hours", "topic_id", "technology_id", "content_area", "link", "image_url", "last_updated_on", "nb_of_subscriptions", "num_chapters", "num_exercises", "num_videos", "datasets_count", "instructors_names", "collaborators_names", "tracks_titles", "prerequisites_titles"}, {"id", "title", "description", "short_description", "programming_language", "difficulty_level", "xp", "time_needed_in_hours", "topic_id", "technology_id", "content_area", "link", "image_url", "last_updated_on", "nb_of_subscriptions", "num_chapters", "num_exercises", "num_videos", "datasets_count 1", "instructors_names", "collaborators_names", "tracks_titles", "prerequisites_titles"}),
					#"Source2" = Table.NestedJoin(#"Expand1", {"technology_id"}, #"technology_mapping.csv_BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)", {"technology_id"}, "technology_mapping.csv_BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)", JoinKind.FullOuter),
					#"Expand2" = Table.ExpandTableColumn(#"Source2", "technology_mapping.csv_BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)", {"technology_id", "technology_name"}, {"technology_id 2", "technology_name 1"}),
					#"Source3" = Table.NestedJoin(#"Expand2", {"POLICY_ID"}, #"topic_mapping.csv_BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)", {"topic_id"}, "topic_mapping.csv_BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)", JoinKind.LeftOuter),
					#"Expand3" = Table.ExpandTableColumn(#"Source3", "topic_mapping.csv_BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)", {"topic_id", "topic_name"}, {"topic_id 1", "topic_name"}),
					#"Source4" = Table.NestedJoin(#"Expand3", {"TABLE_ID"}, #"BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)_BCR_2022_07_DDM_ROLLOUT", {"id"}, "BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)_BCR_2022_07_DDM_ROLLOUT", JoinKind.Inner),
					#"Expand4" = Table.ExpandTableColumn(#"Source4", "BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)_BCR_2022_07_DDM_ROLLOUT", {"track_id", "track_title", "is_career", "course_count", "total_chapters", "total_exercises", "total_videos", "total_xp", "avg_xp_per_course", "avg_time_hours", "total_duration_hours", "datasets_count", "programming_languages", "course_difficulty_levels", "predominant_difficulty", "course_titles", "instructors", "participant_count"}, {"track_id 1", "track_title 1", "is_career 1", "course_count 1", "total_chapters 1", "total_exercises 1", "total_videos 1", "total_xp 1", "avg_xp_per_course 1", "avg_time_hours 1", "total_duration_hours 1", "datasets_count 2", "programming_languages 1", "course_difficulty_levels 1", "predominant_difficulty 1", "course_titles 1", "instructors 1", "participant_count 1"})
					in #"Expand4"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table