table 'technology_mapping.csv_BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)'
	lineageTag: 0b635102-3a39-4e98-b954-41c825a0d77b

	column technology_id
		dataType: int64
		formatString: 0
		lineageTag: c7ae645c-4f33-4f7f-9c1b-a61c10d94491
		summarizeBy: sum
		sourceColumn: technology_id

		annotation SummarizationSetBy = Automatic

	column technology_name
		dataType: string
		lineageTag: ab868f66-ad14-4125-a925-4149054002e5
		summarizeBy: none
		sourceColumn: technology_name

		annotation SummarizationSetBy = Automatic

	partition 'technology_mapping.csv_BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"technology_id" = 9824, #"technology_name" = "Cammie Marsh"],
					        [#"technology_id" = 1148, #"technology_name" = "Maragret Steele"],
					        [#"technology_id" = 1837, #"technology_name" = "Blair Potts"],
					        [#"technology_id" = 9778, #"technology_name" = "Jeremy Russell"],
					        [#"technology_id" = 9516, #"technology_name" = "Nickolas Ochoa"],
					        [#"technology_id" = 4177, #"technology_name" = "Wonda Jacobson"],
					        [#"technology_id" = 9031, #"technology_name" = "Mandie Thompson"],
					        [#"technology_id" = 7763, #"technology_name" = "Zandra Blankenship"],
					        [#"technology_id" = 715, #"technology_name" = "Wyatt Mcpherson"],
					        [#"technology_id" = 7465, #"technology_name" = "Chung O'brien"],
					        [#"technology_id" = 780, #"technology_name" = "Lauryn Cruz"],
					        [#"technology_id" = 2757, #"technology_name" = "Curtis Roy"],
					        [#"technology_id" = 6852, #"technology_name" = "Lonna Harrison"],
					        [#"technology_id" = 8360, #"technology_name" = "Orville Mcguire"],
					        [#"technology_id" = 2516, #"technology_name" = "Mario Serrano"],
					        [#"technology_id" = 8442, #"technology_name" = "Myung Patton"],
					        [#"technology_id" = 7503, #"technology_name" = "Donald Calhoun"],
					        [#"technology_id" = 8162, #"technology_name" = "Izola Blanchard"],
					        [#"technology_id" = 9499, #"technology_name" = "Edmond Fletcher"],
					        [#"technology_id" = 9595, #"technology_name" = "Bernie Kline"],
					        [#"technology_id" = 5898, #"technology_name" = "Maryln Durham"],
					        [#"technology_id" = 5670, #"technology_name" = "Brant Sharp"],
					        [#"technology_id" = 6270, #"technology_name" = "Wilford Sullivan"],
					        [#"technology_id" = 4341, #"technology_name" = "Keneth Macdonald"],
					        [#"technology_id" = 3659, #"technology_name" = "Lelah Norman"],
					        [#"technology_id" = 5343, #"technology_name" = "Eveline Slater"],
					        [#"technology_id" = 8500, #"technology_name" = "Melida Johns"],
					        [#"technology_id" = 1749, #"technology_name" = "Taneka Haley"],
					        [#"technology_id" = 524, #"technology_name" = "Clement Shepard"],
					        [#"technology_id" = 293, #"technology_name" = "Shayne Livingston"],
					        [#"technology_id" = 8990, #"technology_name" = "Theodore Bush"],
					        [#"technology_id" = 4176, #"technology_name" = "Denis Livingston"],
					        [#"technology_id" = 6664, #"technology_name" = "Stanton Willis"],
					        [#"technology_id" = 8752, #"technology_name" = "Milton Walter"],
					        [#"technology_id" = 5647, #"technology_name" = "Jefferey Lowery"],
					        [#"technology_id" = 3280, #"technology_name" = "Elodia Hawkins"],
					        [#"technology_id" = 1615, #"technology_name" = "Roberto Medina"],
					        [#"technology_id" = 7728, #"technology_name" = "Jene Horn"],
					        [#"technology_id" = 8181, #"technology_name" = "Cornell Palmer"],
					        [#"technology_id" = 8673, #"technology_name" = "Karma Franks"],
					        [#"technology_id" = 8683, #"technology_name" = "Clelia Golden"],
					        [#"technology_id" = 2246, #"technology_name" = "Numbers Durham"],
					        [#"technology_id" = 6328, #"technology_name" = "Tameika Burnett"],
					        [#"technology_id" = 2555, #"technology_name" = "Nigel Browning"],
					        [#"technology_id" = 637, #"technology_name" = "Makeda Padilla"],
					        [#"technology_id" = 3807, #"technology_name" = "Lamont House"],
					        [#"technology_id" = 5352, #"technology_name" = "Dong Guthrie"],
					        [#"technology_id" = 6530, #"technology_name" = "Johnathan Gross"],
					        [#"technology_id" = 4752, #"technology_name" = "Joseph Baxter"],
					        [#"technology_id" = 6755, #"technology_name" = "Ligia Adams"],
					        [#"technology_id" = 8273, #"technology_name" = "Carmelo Kennedy"],
					        [#"technology_id" = 770, #"technology_name" = "Juan Nunez"],
					        [#"technology_id" = 3714, #"technology_name" = "Laree Gross"],
					        [#"technology_id" = 7519, #"technology_name" = "Coleman Gilbert"],
					        [#"technology_id" = 6864, #"technology_name" = "Kirby Sparks"],
					        [#"technology_id" = 5199, #"technology_name" = "Bradley Carr"],
					        [#"technology_id" = 4289, #"technology_name" = "Mckinley Gentry"],
					        [#"technology_id" = 3842, #"technology_name" = "Nicolas Moon"],
					        [#"technology_id" = 5048, #"technology_name" = "Kyle Love"],
					        [#"technology_id" = 960, #"technology_name" = "Jospeh Booker"],
					        [#"technology_id" = 7181, #"technology_name" = "Raymond Romero"],
					        [#"technology_id" = 7854, #"technology_name" = "Luna Tucker"],
					        [#"technology_id" = 6045, #"technology_name" = "Gaynelle Booth"],
					        [#"technology_id" = 3055, #"technology_name" = "Gabriel Travis"],
					        [#"technology_id" = 1935, #"technology_name" = "Simon Pickett"],
					        [#"technology_id" = 3145, #"technology_name" = "Echo Adkins"],
					        [#"technology_id" = 8799, #"technology_name" = "Gino Wilkinson"],
					        [#"technology_id" = 6988, #"technology_name" = "Vanita Lyons"],
					        [#"technology_id" = 7485, #"technology_name" = "Lakiesha Macdonald"],
					        [#"technology_id" = 8314, #"technology_name" = "Sandy Benjamin"],
					        [#"technology_id" = 9928, #"technology_name" = "Tory Petersen"],
					        [#"technology_id" = 155, #"technology_name" = "Margarett Lewis"],
					        [#"technology_id" = 5520, #"technology_name" = "Terrance Carpenter"],
					        [#"technology_id" = 9060, #"technology_name" = "Jim Weber"],
					        [#"technology_id" = 86, #"technology_name" = "Karl French"],
					        [#"technology_id" = 997, #"technology_name" = "Jess Tillman"],
					        [#"technology_id" = 8769, #"technology_name" = "Elliot Wall"],
					        [#"technology_id" = 7987, #"technology_name" = "Krystina Colon"],
					        [#"technology_id" = 4626, #"technology_name" = "Sachiko Shannon"],
					        [#"technology_id" = 2369, #"technology_name" = "Ivan Pacheco"],
					        [#"technology_id" = 546, #"technology_name" = "Ha Atkins"],
					        [#"technology_id" = 3387, #"technology_name" = "Dillon Bernard"],
					        [#"technology_id" = 6120, #"technology_name" = "Stewart Dunn"],
					        [#"technology_id" = 3018, #"technology_name" = "Simon Valencia"],
					        [#"technology_id" = 9665, #"technology_name" = "Nigel Herman"],
					        [#"technology_id" = 181, #"technology_name" = "Darrick Smith"],
					        [#"technology_id" = 4914, #"technology_name" = "Belkis Wheeler"],
					        [#"technology_id" = 2157, #"technology_name" = "Billy Morales"],
					        [#"technology_id" = 7942, #"technology_name" = "Quentin Williamson"],
					        [#"technology_id" = 8083, #"technology_name" = "Sari Ruiz"],
					        [#"technology_id" = 9353, #"technology_name" = "Magaret Hewitt"],
					        [#"technology_id" = 1943, #"technology_name" = "Setsuko Ward"],
					        [#"technology_id" = 4729, #"technology_name" = "Lorilee Joseph"],
					        [#"technology_id" = 8594, #"technology_name" = "Joslyn Allison"],
					        [#"technology_id" = 1305, #"technology_name" = "Chassidy Johnston"],
					        [#"technology_id" = 8025, #"technology_name" = "Augustus Byers"],
					        [#"technology_id" = 1135, #"technology_name" = "Cody Huffman"],
					        [#"technology_id" = 6923, #"technology_name" = "Ha Pacheco"],
					        [#"technology_id" = 7302, #"technology_name" = "Joan O'neil"],
					        [#"technology_id" = 7902, #"technology_name" = "Kasey Compton"],
					        [#"technology_id" = 2463, #"technology_name" = "Zana Santana"],
					        [#"technology_id" = 523, #"technology_name" = "Arie Livingston"],
					        [#"technology_id" = 1715, #"technology_name" = "Izola Dennis"],
					        [#"technology_id" = 8989, #"technology_name" = "Joi Holmes"],
					        [#"technology_id" = 8120, #"technology_name" = "Wilford Vega"],
					        [#"technology_id" = 1391, #"technology_name" = "Ulysses Townsend"],
					        [#"technology_id" = 2335, #"technology_name" = "Tyson Love"],
					        [#"technology_id" = 1968, #"technology_name" = "Joette Rivas"],
					        [#"technology_id" = 9764, #"technology_name" = "Yee Mercado"],
					        [#"technology_id" = 8774, #"technology_name" = "Damian Chandler"],
					        [#"technology_id" = 3097, #"technology_name" = "Billy O'brien"],
					        [#"technology_id" = 4255, #"technology_name" = "Alline Gilliam"],
					        [#"technology_id" = 1700, #"technology_name" = "Celena Clayton"],
					        [#"technology_id" = 5638, #"technology_name" = "Jerald Shepard"],
					        [#"technology_id" = 8943, #"technology_name" = "Ellsworth Foley"],
					        [#"technology_id" = 4714, #"technology_name" = "Marcos Christian"],
					        [#"technology_id" = 3215, #"technology_name" = "Rubie Meyers"],
					        [#"technology_id" = 3424, #"technology_name" = "Jeramy Zamora"],
					        [#"technology_id" = 3196, #"technology_name" = "Adan Walls"],
					        [#"technology_id" = 576, #"technology_name" = "Florencia Petty"],
					        [#"technology_id" = 3321, #"technology_name" = "Coralee Brewer"],
					        [#"technology_id" = 9450, #"technology_name" = "Ema Stephens"],
					        [#"technology_id" = 8966, #"technology_name" = "Jarod Barlow"],
					        [#"technology_id" = 7628, #"technology_name" = "Rickey Sanford"],
					        [#"technology_id" = 9662, #"technology_name" = "Oswaldo Allen"],
					        [#"technology_id" = 9771, #"technology_name" = "Jame Miles"],
					        [#"technology_id" = 8326, #"technology_name" = "Marcellus Holder"],
					        [#"technology_id" = 6426, #"technology_name" = "Willis Schultz"],
					        [#"technology_id" = 6165, #"technology_name" = "Levi Hurst"],
					        [#"technology_id" = 7449, #"technology_name" = "Alejandro Reese"],
					        [#"technology_id" = 7963, #"technology_name" = "Esteban Albert"],
					        [#"technology_id" = 1383, #"technology_name" = "Jessie Olson"],
					        [#"technology_id" = 4721, #"technology_name" = "Sylvester Valentine"],
					        [#"technology_id" = 7728, #"technology_name" = "Casey Bentley"],
					        [#"technology_id" = 637, #"technology_name" = "Tora Poole"],
					        [#"technology_id" = 7836, #"technology_name" = "Laronda Levy"],
					        [#"technology_id" = 8288, #"technology_name" = "Milford Gutierrez"],
					        [#"technology_id" = 7841, #"technology_name" = "Grazyna Hess"],
					        [#"technology_id" = 8878, #"technology_name" = "Stevie Barry"],
					        [#"technology_id" = 7310, #"technology_name" = "Londa Miranda"],
					        [#"technology_id" = 2564, #"technology_name" = "Luigi Arnold"],
					        [#"technology_id" = 9746, #"technology_name" = "Chu Frank"],
					        [#"technology_id" = 4124, #"technology_name" = "Scot Baird"],
					        [#"technology_id" = 2931, #"technology_name" = "Laree Bowers"],
					        [#"technology_id" = 6378, #"technology_name" = "Faustina Olsen"],
					        [#"technology_id" = 9562, #"technology_name" = "Ilda Hodge"],
					        [#"technology_id" = 5121, #"technology_name" = "Walton Conner"],
					        [#"technology_id" = 7771, #"technology_name" = "Orville Moss"],
					        [#"technology_id" = 5728, #"technology_name" = "Deadra Larson"],
					        [#"technology_id" = 7135, #"technology_name" = "Breana Chandler"],
					        [#"technology_id" = 1546, #"technology_name" = "Luigi Love"],
					        [#"technology_id" = 9331, #"technology_name" = "Donella Walters"],
					        [#"technology_id" = 8560, #"technology_name" = "Sanford Melton"],
					        [#"technology_id" = 9562, #"technology_name" = "Alberto Tran"],
					        [#"technology_id" = 5299, #"technology_name" = "Blondell Weeks"],
					        [#"technology_id" = 929, #"technology_name" = "Gilberto Ayers"],
					        [#"technology_id" = 8691, #"technology_name" = "Foster Cherry"],
					        [#"technology_id" = 4779, #"technology_name" = "Guadalupe Vargas"],
					        [#"technology_id" = 9086, #"technology_name" = "Ronald Klein"],
					        [#"technology_id" = 7667, #"technology_name" = "Sandie Maynard"],
					        [#"technology_id" = 1360, #"technology_name" = "Markus Mercer"],
					        [#"technology_id" = 9876, #"technology_name" = "Solange Moss"],
					        [#"technology_id" = 639, #"technology_name" = "Jospeh Nielsen"],
					        [#"technology_id" = 4232, #"technology_name" = "Florance Bentley"],
					        [#"technology_id" = 761, #"technology_name" = "Wallace Malone"],
					        [#"technology_id" = 8802, #"technology_name" = "Sharie Harrison"],
					        [#"technology_id" = 5170, #"technology_name" = "Walter Vaughn"],
					        [#"technology_id" = 5417, #"technology_name" = "John Molina"],
					        [#"technology_id" = 1343, #"technology_name" = "Dwain Lawrence"],
					        [#"technology_id" = 5179, #"technology_name" = "Cedrick Ware"],
					        [#"technology_id" = 904, #"technology_name" = "Aundrea Stephenson"],
					        [#"technology_id" = 8152, #"technology_name" = "Brad Hammond"],
					        [#"technology_id" = 4166, #"technology_name" = "Angelika Morris"],
					        [#"technology_id" = 7197, #"technology_name" = "Numbers Elliott"],
					        [#"technology_id" = 6530, #"technology_name" = "Scarlet Ramirez"],
					        [#"technology_id" = 516, #"technology_name" = "Maximo Stewart"],
					        [#"technology_id" = 6310, #"technology_name" = "Eusebia Cote"],
					        [#"technology_id" = 97, #"technology_name" = "Randy Ashley"],
					        [#"technology_id" = 2762, #"technology_name" = "Keith Rivera"],
					        [#"technology_id" = 6113, #"technology_name" = "Elke Boyle"],
					        [#"technology_id" = 9036, #"technology_name" = "Maxwell Miranda"],
					        [#"technology_id" = 8338, #"technology_name" = "Daryl Murphy"],
					        [#"technology_id" = 2170, #"technology_name" = "Dillon Hayden"],
					        [#"technology_id" = 2352, #"technology_name" = "Vannesa Maxwell"],
					        [#"technology_id" = 8328, #"technology_name" = "Rossie Reid"],
					        [#"technology_id" = 4961, #"technology_name" = "Gerard Ashley"],
					        [#"technology_id" = 2863, #"technology_name" = "Elliott Farley"],
					        [#"technology_id" = 4021, #"technology_name" = "Laurence Hopkins"],
					        [#"technology_id" = 5988, #"technology_name" = "Reena Cummings"],
					        [#"technology_id" = 3829, #"technology_name" = "Moshe Stevens"],
					        [#"technology_id" = 5540, #"technology_name" = "Tiera Hodge"],
					        [#"technology_id" = 5030, #"technology_name" = "Dewayne Chambers"],
					        [#"technology_id" = 6830, #"technology_name" = "Chasidy Stein"],
					        [#"technology_id" = 2719, #"technology_name" = "Jona Parker"],
					        [#"technology_id" = 4191, #"technology_name" = "Billye Simmons"],
					        [#"technology_id" = 8526, #"technology_name" = "Micah Mccullough"],
					        [#"technology_id" = 6670, #"technology_name" = "Joane Kemp"],
					        [#"technology_id" = 2514, #"technology_name" = "Loriann Meyer"],
					        [#"technology_id" = 2666, #"technology_name" = "Rupert Sanders"],
					        [#"technology_id" = 7916, #"technology_name" = "Mitsue Moses"],
					        [#"technology_id" = 4246, #"technology_name" = "Napoleon Baldwin"],
					        [#"technology_id" = 6296, #"technology_name" = "Zulma Ballard"],
					        [#"technology_id" = 8261, #"technology_name" = "Darwin Glass"],
					        [#"technology_id" = 1840, #"technology_name" = "Phil Nunez"],
					        [#"technology_id" = 846, #"technology_name" = "Ellsworth Reese"],
					        [#"technology_id" = 945, #"technology_name" = "Soila Mason"],
					        [#"technology_id" = 3555, #"technology_name" = "Florentina Tran"],
					        [#"technology_id" = 4563, #"technology_name" = "Catarina Mcintyre"],
					        [#"technology_id" = 2674, #"technology_name" = "Sam Alston"],
					        [#"technology_id" = 7818, #"technology_name" = "Allena Durham"],
					        [#"technology_id" = 8911, #"technology_name" = "Anibal Hopper"],
					        [#"technology_id" = 55, #"technology_name" = "Dotty Gay"],
					        [#"technology_id" = 9330, #"technology_name" = "Maye Mcmahon"],
					        [#"technology_id" = 9537, #"technology_name" = "Kimberli Chavez"],
					        [#"technology_id" = 3020, #"technology_name" = "Porter Underwood"],
					        [#"technology_id" = 2230, #"technology_name" = "Harris Collins"],
					        [#"technology_id" = 3474, #"technology_name" = "Stephnie Dudley"],
					        [#"technology_id" = 5212, #"technology_name" = "Minh Reid"],
					        [#"technology_id" = 8485, #"technology_name" = "Earnest Atkinson"],
					        [#"technology_id" = 3381, #"technology_name" = "Nichol Reid"],
					        [#"technology_id" = 7732, #"technology_name" = "Napoleon Mathews"],
					        [#"technology_id" = 6608, #"technology_name" = "Ricardo Newton"],
					        [#"technology_id" = 9249, #"technology_name" = "Joaquina Puckett"],
					        [#"technology_id" = 4362, #"technology_name" = "Geraldo Knight"],
					        [#"technology_id" = 7324, #"technology_name" = "Salena Mathis"],
					        [#"technology_id" = 462, #"technology_name" = "Maximo Keith"],
					        [#"technology_id" = 6730, #"technology_name" = "Horacio Cochran"],
					        [#"technology_id" = 2938, #"technology_name" = "Keneth Barker"],
					        [#"technology_id" = 9954, #"technology_name" = "Ema Hill"],
					        [#"technology_id" = 5774, #"technology_name" = "Milford Bates"],
					        [#"technology_id" = 4673, #"technology_name" = "Dana Bass"],
					        [#"technology_id" = 1587, #"technology_name" = "Regine Workman"],
					        [#"technology_id" = 6963, #"technology_name" = "Garrett Allison"],
					        [#"technology_id" = 8639, #"technology_name" = "Treena Stafford"],
					        [#"technology_id" = 3387, #"technology_name" = "Eldon Bradford"],
					        [#"technology_id" = 7731, #"technology_name" = "Joannie Edwards"],
					        [#"technology_id" = 2610, #"technology_name" = "Claudio O'neill"],
					        [#"technology_id" = 4663, #"technology_name" = "Dwight Serrano"],
					        [#"technology_id" = 9153, #"technology_name" = "Deshawn Fisher"],
					        [#"technology_id" = 4337, #"technology_name" = "Danyel Little"],
					        [#"technology_id" = 6222, #"technology_name" = "Iesha Stein"],
					        [#"technology_id" = 18, #"technology_name" = "Leonila Hull"],
					        [#"technology_id" = 7157, #"technology_name" = "Willodean Washington"],
					        [#"technology_id" = 1917, #"technology_name" = "Randy Flores"],
					        [#"technology_id" = 8867, #"technology_name" = "Alysha Jackson"],
					        [#"technology_id" = 7813, #"technology_name" = "Domitila Sweeney"],
					        [#"technology_id" = 2491, #"technology_name" = "Chad Kramer"],
					        [#"technology_id" = 4708, #"technology_name" = "Donn Hendrix"],
					        [#"technology_id" = 1047, #"technology_name" = "Olin Ware"],
					        [#"technology_id" = 5003, #"technology_name" = "Rupert Albert"],
					        [#"technology_id" = 1989, #"technology_name" = "Raina Howe"],
					        [#"technology_id" = 2980, #"technology_name" = "Tayna Weber"],
					        [#"technology_id" = 4951, #"technology_name" = "Doreatha Durham"],
					        [#"technology_id" = 6655, #"technology_name" = "Omer Webb"],
					        [#"technology_id" = 6017, #"technology_name" = "Eddy Mercado"],
					        [#"technology_id" = 590, #"technology_name" = "Vince Ortega"],
					        [#"technology_id" = 5507, #"technology_name" = "Claudie Whitney"],
					        [#"technology_id" = 2725, #"technology_name" = "Antwan Lott"],
					        [#"technology_id" = 9774, #"technology_name" = "Russ Doyle"],
					        [#"technology_id" = 4939, #"technology_name" = "Marni Lowe"],
					        [#"technology_id" = 3126, #"technology_name" = "Abe Fitzpatrick"],
					        [#"technology_id" = 3201, #"technology_name" = "Andrew Gutierrez"],
					        [#"technology_id" = 3127, #"technology_name" = "Florentina Fry"],
					        [#"technology_id" = 1508, #"technology_name" = "Earle Woodard"],
					        [#"technology_id" = 9099, #"technology_name" = "Alfred Walter"],
					        [#"technology_id" = 4626, #"technology_name" = "Josefine Jarvis"],
					        [#"technology_id" = 3588, #"technology_name" = "Elliot Wolfe"],
					        [#"technology_id" = 8729, #"technology_name" = "Kasandra Charles"],
					        [#"technology_id" = 8607, #"technology_name" = "Laurice Haley"],
					        [#"technology_id" = 8781, #"technology_name" = "Noe Mayer"],
					        [#"technology_id" = 4340, #"technology_name" = "Bo Mckay"],
					        [#"technology_id" = 2023, #"technology_name" = "Toby Williams"],
					        [#"technology_id" = 5705, #"technology_name" = "Dani Miranda"],
					        [#"technology_id" = 3232, #"technology_name" = "Maximina Weiss"],
					        [#"technology_id" = 7082, #"technology_name" = "Waldo Chan"],
					        [#"technology_id" = 9299, #"technology_name" = "Sari Bradford"],
					        [#"technology_id" = 6223, #"technology_name" = "Josiah Summers"],
					        [#"technology_id" = 7941, #"technology_name" = "Erik Robbins"],
					        [#"technology_id" = 5677, #"technology_name" = "Delicia Knapp"],
					        [#"technology_id" = 7159, #"technology_name" = "Tomika Le"],
					        [#"technology_id" = 3954, #"technology_name" = "Karoline Glenn"],
					        [#"technology_id" = 149, #"technology_name" = "Nakita Buck"],
					        [#"technology_id" = 3492, #"technology_name" = "Armando Delacruz"],
					        [#"technology_id" = 1556, #"technology_name" = "Corliss Benjamin"],
					        [#"technology_id" = 660, #"technology_name" = "Wendie Everett"],
					        [#"technology_id" = 2652, #"technology_name" = "Lorenzo Meadows"],
					        [#"technology_id" = 9506, #"technology_name" = "Tonette Salinas"],
					        [#"technology_id" = 8184, #"technology_name" = "Nancey Scott"],
					        [#"technology_id" = 5100, #"technology_name" = "Adrian Dillard"],
					        [#"technology_id" = 9992, #"technology_name" = "Lucius Camacho"],
					        [#"technology_id" = 1375, #"technology_name" = "Elbert Mckenzie"],
					        [#"technology_id" = 6494, #"technology_name" = "Herbert Kirk"],
					        [#"technology_id" = 4509, #"technology_name" = "Laurene Suarez"],
					        [#"technology_id" = 4358, #"technology_name" = "Justa Armstrong"],
					        [#"technology_id" = 3667, #"technology_name" = "Porsche Holman"],
					        [#"technology_id" = 6727, #"technology_name" = "Burton Dean"],
					        [#"technology_id" = 5895, #"technology_name" = "Otha Alexander"],
					        [#"technology_id" = 65, #"technology_name" = "Antione Cobb"],
					        [#"technology_id" = 5810, #"technology_name" = "Curtis Snider"],
					        [#"technology_id" = 8214, #"technology_name" = "Keith Morris"],
					        [#"technology_id" = 2096, #"technology_name" = "Laci Roberts"],
					        [#"technology_id" = 6482, #"technology_name" = "Vincent Bonner"],
					        [#"technology_id" = 4557, #"technology_name" = "Alonso Carney"],
					        [#"technology_id" = 2146, #"technology_name" = "Adan Ballard"],
					        [#"technology_id" = 1848, #"technology_name" = "Carlo Knight"],
					        [#"technology_id" = 7005, #"technology_name" = "Leonida Pruitt"],
					        [#"technology_id" = 200, #"technology_name" = "Ayanna Jacobson"],
					        [#"technology_id" = 7680, #"technology_name" = "Eusebia Santiago"],
					        [#"technology_id" = 1322, #"technology_name" = "Kymberly Browning"],
					        [#"technology_id" = 1373, #"technology_name" = "Kelvin Skinner"],
					        [#"technology_id" = 8861, #"technology_name" = "Olin Stone"],
					        [#"technology_id" = 7706, #"technology_name" = "Rossana Finley"],
					        [#"technology_id" = 7389, #"technology_name" = "Idell Gaines"],
					        [#"technology_id" = 59, #"technology_name" = "Cletus Potter"],
					        [#"technology_id" = 5770, #"technology_name" = "Luba Berger"],
					        [#"technology_id" = 6540, #"technology_name" = "Venice Pennington"],
					        [#"technology_id" = 2479, #"technology_name" = "Faustina Jacobs"],
					        [#"technology_id" = 6082, #"technology_name" = "Shizuko York"],
					        [#"technology_id" = 2475, #"technology_name" = "Katelin Wood"],
					        [#"technology_id" = 4992, #"technology_name" = "Ricarda Webster"],
					        [#"technology_id" = 557, #"technology_name" = "Yuriko Dixon"],
					        [#"technology_id" = 641, #"technology_name" = "Darron Monroe"],
					        [#"technology_id" = 5973, #"technology_name" = "Jeremy Walls"],
					        [#"technology_id" = 2992, #"technology_name" = "Robbyn Morales"],
					        [#"technology_id" = 7758, #"technology_name" = "Lekisha Sweeney"],
					        [#"technology_id" = 8551, #"technology_name" = "France Decker"],
					        [#"technology_id" = 4062, #"technology_name" = "Tashina Giles"],
					        [#"technology_id" = 6861, #"technology_name" = "Clelia Merrill"],
					        [#"technology_id" = 1547, #"technology_name" = "Boyd Lane"],
					        [#"technology_id" = 2262, #"technology_name" = "Theressa Maxwell"],
					        [#"technology_id" = 4168, #"technology_name" = "Scott Burris"],
					        [#"technology_id" = 83, #"technology_name" = "Vito Rodgers"],
					        [#"technology_id" = 405, #"technology_name" = "Raina Fitzpatrick"],
					        [#"technology_id" = 3318, #"technology_name" = "Jerrold Espinoza"],
					        [#"technology_id" = 30, #"technology_name" = "Hassan Mclaughlin"],
					        [#"technology_id" = 9580, #"technology_name" = "Hisako Flowers"],
					        [#"technology_id" = 9579, #"technology_name" = "Jules Bauer"],
					        [#"technology_id" = 2933, #"technology_name" = "Anibal Nielsen"],
					        [#"technology_id" = 8412, #"technology_name" = "Librada Rivers"],
					        [#"technology_id" = 9005, #"technology_name" = "Silas Waller"],
					        [#"technology_id" = 7929, #"technology_name" = "Tory Hayes"],
					        [#"technology_id" = 6856, #"technology_name" = "Cathern Vega"],
					        [#"technology_id" = 6066, #"technology_name" = "Johnathan Ford"],
					        [#"technology_id" = 7569, #"technology_name" = "Booker Payne"],
					        [#"technology_id" = 6069, #"technology_name" = "Nelida Flowers"],
					        [#"technology_id" = 7465, #"technology_name" = "Maynard O'connor"],
					        [#"technology_id" = 1557, #"technology_name" = "Toney Lucas"],
					        [#"technology_id" = 7501, #"technology_name" = "Claude Kaufman"],
					        [#"technology_id" = 5034, #"technology_name" = "Linsey Gallegos"],
					        [#"technology_id" = 2641, #"technology_name" = "Kamala Pitts"],
					        [#"technology_id" = 6963, #"technology_name" = "Rusty Cannon"],
					        [#"technology_id" = 5146, #"technology_name" = "Everett Salas"],
					        [#"technology_id" = 4057, #"technology_name" = "January Burke"],
					        [#"technology_id" = 6719, #"technology_name" = "Arden Carroll"],
					        [#"technology_id" = 1529, #"technology_name" = "Wenona Cooley"],
					        [#"technology_id" = 7016, #"technology_name" = "Bertram Dyer"],
					        [#"technology_id" = 8306, #"technology_name" = "Lawrence Manning"],
					        [#"technology_id" = 143, #"technology_name" = "Billie Spence"],
					        [#"technology_id" = 43, #"technology_name" = "Kortney Middleton"],
					        [#"technology_id" = 2298, #"technology_name" = "Theodore Carey"],
					        [#"technology_id" = 7175, #"technology_name" = "Glennis Rhodes"],
					        [#"technology_id" = 663, #"technology_name" = "Arlen Baldwin"],
					        [#"technology_id" = 4306, #"technology_name" = "Caprice Fisher"],
					        [#"technology_id" = 4845, #"technology_name" = "Paris Hickman"],
					        [#"technology_id" = 6818, #"technology_name" = "Deon Hayes"],
					        [#"technology_id" = 8482, #"technology_name" = "Edra Hopkins"],
					        [#"technology_id" = 4493, #"technology_name" = "Tory Floyd"],
					        [#"technology_id" = 4806, #"technology_name" = "Halina Fleming"],
					        [#"technology_id" = 2171, #"technology_name" = "Assunta Levy"],
					        [#"technology_id" = 2512, #"technology_name" = "Ulysses Morris"],
					        [#"technology_id" = 8170, #"technology_name" = "Kacy Bryan"],
					        [#"technology_id" = 8980, #"technology_name" = "Libbie Summers"],
					        [#"technology_id" = 9281, #"technology_name" = "Trinh Phelps"],
					        [#"technology_id" = 447, #"technology_name" = "Maris Holloway"],
					        [#"technology_id" = 4743, #"technology_name" = "Zack Holcomb"],
					        [#"technology_id" = 7754, #"technology_name" = "Madlyn Leach"],
					        [#"technology_id" = 4358, #"technology_name" = "Danilo Harrington"],
					        [#"technology_id" = 9973, #"technology_name" = "Casimira Melton"],
					        [#"technology_id" = 4100, #"technology_name" = "Amos Adams"],
					        [#"technology_id" = 7914, #"technology_name" = "Timika Horne"],
					        [#"technology_id" = 4670, #"technology_name" = "Micki Rocha"],
					        [#"technology_id" = 3241, #"technology_name" = "Florentino Craft"],
					        [#"technology_id" = 3234, #"technology_name" = "Shanelle Guerra"],
					        [#"technology_id" = 8659, #"technology_name" = "Cedrick Drake"],
					        [#"technology_id" = 5968, #"technology_name" = "Michale Forbes"],
					        [#"technology_id" = 2129, #"technology_name" = "Raisa Benton"],
					        [#"technology_id" = 4589, #"technology_name" = "Elfrieda Faulkner"],
					        [#"technology_id" = 3374, #"technology_name" = "Sheldon Mercer"],
					        [#"technology_id" = 4334, #"technology_name" = "Eli Howard"],
					        [#"technology_id" = 2164, #"technology_name" = "Despina Mccullough"],
					        [#"technology_id" = 7852, #"technology_name" = "Jacquie Tate"],
					        [#"technology_id" = 9552, #"technology_name" = "Sarai Mckee"],
					        [#"technology_id" = 2758, #"technology_name" = "Tracy Sanders"],
					        [#"technology_id" = 7986, #"technology_name" = "Tonette Shelton"],
					        [#"technology_id" = 4098, #"technology_name" = "Coy Morin"],
					        [#"technology_id" = 5987, #"technology_name" = "Buford Delgado"],
					        [#"technology_id" = 6429, #"technology_name" = "Felicidad Albert"],
					        [#"technology_id" = 4774, #"technology_name" = "Sharri Suarez"],
					        [#"technology_id" = 8282, #"technology_name" = "Nick Mccarty"],
					        [#"technology_id" = 1820, #"technology_name" = "Fabian Hoover"],
					        [#"technology_id" = 3239, #"technology_name" = "Israel Hopkins"],
					        [#"technology_id" = 1504, #"technology_name" = "Marcus Whitehead"],
					        [#"technology_id" = 4226, #"technology_name" = "Tobi Madden"],
					        [#"technology_id" = 2024, #"technology_name" = "Isreal Mosley"],
					        [#"technology_id" = 7041, #"technology_name" = "Emmitt Cochran"],
					        [#"technology_id" = 6001, #"technology_name" = "Celesta Bennett"],
					        [#"technology_id" = 2178, #"technology_name" = "Jackqueline Francis"],
					        [#"technology_id" = 4393, #"technology_name" = "Cammie Cooper"],
					        [#"technology_id" = 6597, #"technology_name" = "Clarence Robinson"],
					        [#"technology_id" = 2217, #"technology_name" = "Gonzalo Clark"],
					        [#"technology_id" = 4377, #"technology_name" = "Xenia Spears"],
					        [#"technology_id" = 748, #"technology_name" = "Wilton Barton"],
					        [#"technology_id" = 6563, #"technology_name" = "Blondell Salas"],
					        [#"technology_id" = 9657, #"technology_name" = "Blaine Donovan"],
					        [#"technology_id" = 2700, #"technology_name" = "Pablo Dixon"],
					        [#"technology_id" = 2520, #"technology_name" = "Rudy Buckley"],
					        [#"technology_id" = 8376, #"technology_name" = "Kelley Fox"],
					        [#"technology_id" = 9329, #"technology_name" = "Kortney Mendoza"],
					        [#"technology_id" = 683, #"technology_name" = "Sergio Emerson"],
					        [#"technology_id" = 7336, #"technology_name" = "Rodger Frye"],
					        [#"technology_id" = 1164, #"technology_name" = "Veronique Stephens"],
					        [#"technology_id" = 5650, #"technology_name" = "Kazuko Medina"],
					        [#"technology_id" = 7669, #"technology_name" = "Wallace Coffey"],
					        [#"technology_id" = 3044, #"technology_name" = "Hassie Golden"],
					        [#"technology_id" = 3419, #"technology_name" = "Bart Conway"],
					        [#"technology_id" = 8972, #"technology_name" = "Pablo Daniels"],
					        [#"technology_id" = 4385, #"technology_name" = "Matthew Neal"],
					        [#"technology_id" = 9981, #"technology_name" = "Michal O'donnell"],
					        [#"technology_id" = 4675, #"technology_name" = "Wesley Gilbert"],
					        [#"technology_id" = 6151, #"technology_name" = "Brenton Simon"],
					        [#"technology_id" = 9072, #"technology_name" = "Dann Brennan"],
					        [#"technology_id" = 818, #"technology_name" = "Bo Riggs"],
					        [#"technology_id" = 8767, #"technology_name" = "Pandora Mckay"],
					        [#"technology_id" = 5297, #"technology_name" = "Emmett Levy"],
					        [#"technology_id" = 8552, #"technology_name" = "Joseph Hardin"],
					        [#"technology_id" = 8215, #"technology_name" = "Lorenzo Gould"],
					        [#"technology_id" = 529, #"technology_name" = "Lurlene Sweet"],
					        [#"technology_id" = 8550, #"technology_name" = "Krystin Henderson"],
					        [#"technology_id" = 5362, #"technology_name" = "Lael Soto"],
					        [#"technology_id" = 8563, #"technology_name" = "Chia Walsh"],
					        [#"technology_id" = 9278, #"technology_name" = "Basil Workman"],
					        [#"technology_id" = 4123, #"technology_name" = "Pamella Chapman"],
					        [#"technology_id" = 1192, #"technology_name" = "Gabriele Wilkerson"],
					        [#"technology_id" = 5113, #"technology_name" = "Britt Alvarado"],
					        [#"technology_id" = 2403, #"technology_name" = "Perry Nieves"],
					        [#"technology_id" = 4926, #"technology_name" = "Odell Rojas"],
					        [#"technology_id" = 7724, #"technology_name" = "Terence Anderson"],
					        [#"technology_id" = 5302, #"technology_name" = "Maple Key"],
					        [#"technology_id" = 5166, #"technology_name" = "Edward Leon"],
					        [#"technology_id" = 5877, #"technology_name" = "Pearlene Copeland"],
					        [#"technology_id" = 3735, #"technology_name" = "Loren Gonzalez"],
					        [#"technology_id" = 5957, #"technology_name" = "Alfredo Olsen"],
					        [#"technology_id" = 3382, #"technology_name" = "Nubia Rojas"],
					        [#"technology_id" = 5275, #"technology_name" = "Eliana Mcdonald"],
					        [#"technology_id" = 9104, #"technology_name" = "Vince Mcleod"],
					        [#"technology_id" = 8910, #"technology_name" = "Jeromy Roach"],
					        [#"technology_id" = 2698, #"technology_name" = "Georgeann Acevedo"],
					        [#"technology_id" = 6032, #"technology_name" = "Twana Robles"],
					        [#"technology_id" = 9075, #"technology_name" = "See Howe"],
					        [#"technology_id" = 8938, #"technology_name" = "Larry Donovan"],
					        [#"technology_id" = 5594, #"technology_name" = "Faviola Burt"],
					        [#"technology_id" = 26, #"technology_name" = "Marceline Navarro"],
					        [#"technology_id" = 2715, #"technology_name" = "Apryl Mclaughlin"],
					        [#"technology_id" = 283, #"technology_name" = "Fredda Sosa"],
					        [#"technology_id" = 3378, #"technology_name" = "Jerrod Price"],
					        [#"technology_id" = 5933, #"technology_name" = "Jennine Maynard"],
					        [#"technology_id" = 715, #"technology_name" = "Erik Prince"],
					        [#"technology_id" = 4346, #"technology_name" = "Shad Lewis"],
					        [#"technology_id" = 8738, #"technology_name" = "Mistie Byrd"],
					        [#"technology_id" = 6674, #"technology_name" = "Marg Owen"],
					        [#"technology_id" = 8325, #"technology_name" = "Charlie Barrera"],
					        [#"technology_id" = 8064, #"technology_name" = "Lucina Ellis"],
					        [#"technology_id" = 8021, #"technology_name" = "Saul Stokes"],
					        [#"technology_id" = 6323, #"technology_name" = "Carlos Kane"],
					        [#"technology_id" = 545, #"technology_name" = "Maris Rivers"],
					        [#"technology_id" = 6758, #"technology_name" = "Keira Mejia"],
					        [#"technology_id" = 2827, #"technology_name" = "Raul Hess"],
					        [#"technology_id" = 1967, #"technology_name" = "Fredricka Padilla"],
					        [#"technology_id" = 7852, #"technology_name" = "Teodora Nielsen"],
					        [#"technology_id" = 9841, #"technology_name" = "Marion Diaz"],
					        [#"technology_id" = 4666, #"technology_name" = "Maryalice Langley"],
					        [#"technology_id" = 5928, #"technology_name" = "Frank Morris"],
					        [#"technology_id" = 9502, #"technology_name" = "Allan Leblanc"],
					        [#"technology_id" = 3968, #"technology_name" = "Queenie Tanner"],
					        [#"technology_id" = 1948, #"technology_name" = "Soraya Bryan"],
					        [#"technology_id" = 3841, #"technology_name" = "Dewitt Medina"],
					        [#"technology_id" = 1751, #"technology_name" = "Casey Mclean"],
					        [#"technology_id" = 1425, #"technology_name" = "Kenneth Greene"],
					        [#"technology_id" = 1612, #"technology_name" = "Lashawnda Cross"],
					        [#"technology_id" = 9878, #"technology_name" = "Cedrick Stanton"],
					        [#"technology_id" = 129, #"technology_name" = "Darron Alvarez"],
					        [#"technology_id" = 2609, #"technology_name" = "Stephen Cantrell"],
					        [#"technology_id" = 4261, #"technology_name" = "Rickie Allison"],
					        [#"technology_id" = 1845, #"technology_name" = "Kevin Sanchez"],
					        [#"technology_id" = 76, #"technology_name" = "Consuela Key"],
					        [#"technology_id" = 6190, #"technology_name" = "Haywood Stafford"],
					        [#"technology_id" = 199, #"technology_name" = "Rogelio Curry"],
					        [#"technology_id" = 9701, #"technology_name" = "Daphine Clemons"],
					        [#"technology_id" = 7919, #"technology_name" = "Manie Delacruz"],
					        [#"technology_id" = 8411, #"technology_name" = "Alvaro Rasmussen"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"technology_id", Int64.Type},
					        {"technology_name", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table