table 'technology_mapping.csv1_BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)'
	lineageTag: 89cef535-c0be-4c3b-a294-4b5ae94050f8

	column technology_id
		dataType: int64
		formatString: 0
		lineageTag: f25568c5-19fa-4700-9a10-df8264822c26
		summarizeBy: sum
		sourceColumn: technology_id

		annotation SummarizationSetBy = Automatic

	column technology_name
		dataType: string
		lineageTag: 1aceb90f-4180-483f-b289-760197e95ab5
		summarizeBy: none
		sourceColumn: technology_name

		annotation SummarizationSetBy = Automatic

	partition 'technology_mapping.csv1_BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"technology_id" = 3611, #"technology_name" = "Mahalia Barr"],
					        [#"technology_id" = 6404, #"technology_name" = "Christopher Short"],
					        [#"technology_id" = 982, #"technology_name" = "Alphonso Jensen"],
					        [#"technology_id" = 9796, #"technology_name" = "Byron Odom"],
					        [#"technology_id" = 9120, #"technology_name" = "Kendrick Chase"],
					        [#"technology_id" = 5526, #"technology_name" = "Sherilyn Whitney"],
					        [#"technology_id" = 8314, #"technology_name" = "Rivka Bird"],
					        [#"technology_id" = 5423, #"technology_name" = "Gavin Gray"],
					        [#"technology_id" = 6788, #"technology_name" = "Zana Mooney"],
					        [#"technology_id" = 5578, #"technology_name" = "Chance York"],
					        [#"technology_id" = 1851, #"technology_name" = "Leonore Walsh"],
					        [#"technology_id" = 5875, #"technology_name" = "Blaine Brennan"],
					        [#"technology_id" = 4741, #"technology_name" = "Carmelia Morales"],
					        [#"technology_id" = 7853, #"technology_name" = "Micah Sparks"],
					        [#"technology_id" = 4499, #"technology_name" = "Mignon Macias"],
					        [#"technology_id" = 8569, #"technology_name" = "Layla Wilkinson"],
					        [#"technology_id" = 5592, #"technology_name" = "Rickie Cameron"],
					        [#"technology_id" = 2204, #"technology_name" = "Jayson Lamb"],
					        [#"technology_id" = 6283, #"technology_name" = "Caroll Robles"],
					        [#"technology_id" = 8199, #"technology_name" = "Benjamin Marshall"],
					        [#"technology_id" = 4841, #"technology_name" = "Isa Barrera"],
					        [#"technology_id" = 6182, #"technology_name" = "Marleen Madden"],
					        [#"technology_id" = 8467, #"technology_name" = "Mitzie Blake"],
					        [#"technology_id" = 9030, #"technology_name" = "Dallas Mays"],
					        [#"technology_id" = 2516, #"technology_name" = "Terica Albert"],
					        [#"technology_id" = 8368, #"technology_name" = "Elden Erickson"],
					        [#"technology_id" = 9443, #"technology_name" = "Jann Hart"],
					        [#"technology_id" = 7842, #"technology_name" = "Eli Delgado"],
					        [#"technology_id" = 6776, #"technology_name" = "Shondra Banks"],
					        [#"technology_id" = 3123, #"technology_name" = "Woodrow George"],
					        [#"technology_id" = 5400, #"technology_name" = "Dewitt Savage"],
					        [#"technology_id" = 2459, #"technology_name" = "Ollie Newman"],
					        [#"technology_id" = 625, #"technology_name" = "Marline Parrish"],
					        [#"technology_id" = 7628, #"technology_name" = "Kenda Simon"],
					        [#"technology_id" = 2482, #"technology_name" = "Dion Fischer"],
					        [#"technology_id" = 7405, #"technology_name" = "Lindsey Sharp"],
					        [#"technology_id" = 2875, #"technology_name" = "Miesha Vazquez"],
					        [#"technology_id" = 4023, #"technology_name" = "Olimpia Stewart"],
					        [#"technology_id" = 478, #"technology_name" = "Clinton Cooke"],
					        [#"technology_id" = 4928, #"technology_name" = "Mao Powell"],
					        [#"technology_id" = 7071, #"technology_name" = "Pamula James"],
					        [#"technology_id" = 9160, #"technology_name" = "Ashley Baird"],
					        [#"technology_id" = 1279, #"technology_name" = "Chan Curtis"],
					        [#"technology_id" = 5425, #"technology_name" = "Rodrick Anthony"],
					        [#"technology_id" = 9373, #"technology_name" = "Clemente Foley"],
					        [#"technology_id" = 7863, #"technology_name" = "Loreta Hines"],
					        [#"technology_id" = 8662, #"technology_name" = "Sharee Contreras"],
					        [#"technology_id" = 9105, #"technology_name" = "Quinn Crane"],
					        [#"technology_id" = 2059, #"technology_name" = "Asley Greene"],
					        [#"technology_id" = 6452, #"technology_name" = "Malik Bernard"],
					        [#"technology_id" = 6827, #"technology_name" = "Man Lloyd"],
					        [#"technology_id" = 6233, #"technology_name" = "Augustine Gomez"],
					        [#"technology_id" = 8256, #"technology_name" = "Russ Park"],
					        [#"technology_id" = 2498, #"technology_name" = "Burton Le"],
					        [#"technology_id" = 1311, #"technology_name" = "Efrain Becker"],
					        [#"technology_id" = 7274, #"technology_name" = "Bruno Warner"],
					        [#"technology_id" = 5937, #"technology_name" = "Silva Cross"],
					        [#"technology_id" = 1780, #"technology_name" = "Juan Vazquez"],
					        [#"technology_id" = 5764, #"technology_name" = "Marylyn Brown"],
					        [#"technology_id" = 1030, #"technology_name" = "Franklin Tate"],
					        [#"technology_id" = 7027, #"technology_name" = "Tyrone Parks"],
					        [#"technology_id" = 320, #"technology_name" = "Huey Skinner"],
					        [#"technology_id" = 1083, #"technology_name" = "Mary Bernard"],
					        [#"technology_id" = 1421, #"technology_name" = "Kurtis Alvarez"],
					        [#"technology_id" = 7980, #"technology_name" = "Song Conrad"],
					        [#"technology_id" = 5248, #"technology_name" = "Edmond Best"],
					        [#"technology_id" = 2952, #"technology_name" = "Danny Arnold"],
					        [#"technology_id" = 8675, #"technology_name" = "Saul Lambert"],
					        [#"technology_id" = 2779, #"technology_name" = "Candie Montoya"],
					        [#"technology_id" = 9203, #"technology_name" = "Micheline Colon"],
					        [#"technology_id" = 9018, #"technology_name" = "Christeen Mercer"],
					        [#"technology_id" = 1611, #"technology_name" = "Shelby Hutchinson"],
					        [#"technology_id" = 2888, #"technology_name" = "Tameika Butler"],
					        [#"technology_id" = 2780, #"technology_name" = "Kayleigh Barlow"],
					        [#"technology_id" = 3176, #"technology_name" = "Samual Walter"],
					        [#"technology_id" = 5611, #"technology_name" = "Oralee Morin"],
					        [#"technology_id" = 9734, #"technology_name" = "Paulita Ellison"],
					        [#"technology_id" = 1200, #"technology_name" = "Jackie Beasley"],
					        [#"technology_id" = 1180, #"technology_name" = "Freeman Beach"],
					        [#"technology_id" = 5403, #"technology_name" = "Trang Barker"],
					        [#"technology_id" = 5610, #"technology_name" = "Laurice Hoffman"],
					        [#"technology_id" = 1937, #"technology_name" = "Latarsha Mitchell"],
					        [#"technology_id" = 8702, #"technology_name" = "Tanner Lara"],
					        [#"technology_id" = 9798, #"technology_name" = "Kevin Williamson"],
					        [#"technology_id" = 3387, #"technology_name" = "Malik Holloway"],
					        [#"technology_id" = 318, #"technology_name" = "Dayle Frederick"],
					        [#"technology_id" = 9888, #"technology_name" = "Ezequiel Branch"],
					        [#"technology_id" = 5156, #"technology_name" = "Domonique Reid"],
					        [#"technology_id" = 5737, #"technology_name" = "Dann Manning"],
					        [#"technology_id" = 1074, #"technology_name" = "Shanel Hubbard"],
					        [#"technology_id" = 9270, #"technology_name" = "Melani Kinney"],
					        [#"technology_id" = 4037, #"technology_name" = "Scotty Frederick"],
					        [#"technology_id" = 2331, #"technology_name" = "Emely Booker"],
					        [#"technology_id" = 7337, #"technology_name" = "Lamont Miles"],
					        [#"technology_id" = 639, #"technology_name" = "Theodore Mullins"],
					        [#"technology_id" = 3054, #"technology_name" = "Roseline Riggs"],
					        [#"technology_id" = 328, #"technology_name" = "Jessika Buckley"],
					        [#"technology_id" = 8493, #"technology_name" = "Garry Thomas"],
					        [#"technology_id" = 1272, #"technology_name" = "Mignon Steele"],
					        [#"technology_id" = 9184, #"technology_name" = "Merrilee Garza"],
					        [#"technology_id" = 4404, #"technology_name" = "Lurlene Mitchell"],
					        [#"technology_id" = 1433, #"technology_name" = "Aubrey Eaton"],
					        [#"technology_id" = 9331, #"technology_name" = "Venetta Franklin"],
					        [#"technology_id" = 5800, #"technology_name" = "Bob Dickerson"],
					        [#"technology_id" = 6275, #"technology_name" = "Doretta Mcfarland"],
					        [#"technology_id" = 3620, #"technology_name" = "Lorriane Brock"],
					        [#"technology_id" = 8195, #"technology_name" = "Merilyn Cervantes"],
					        [#"technology_id" = 9437, #"technology_name" = "Bao Clarke"],
					        [#"technology_id" = 4515, #"technology_name" = "Ike Frederick"],
					        [#"technology_id" = 5325, #"technology_name" = "Ara Hyde"],
					        [#"technology_id" = 1488, #"technology_name" = "Yevette Ortega"],
					        [#"technology_id" = 8287, #"technology_name" = "Reginia Forbes"],
					        [#"technology_id" = 2155, #"technology_name" = "Colby Perry"],
					        [#"technology_id" = 121, #"technology_name" = "Joshua Finley"],
					        [#"technology_id" = 4489, #"technology_name" = "Adrian George"],
					        [#"technology_id" = 4452, #"technology_name" = "Ignacio Carson"],
					        [#"technology_id" = 1691, #"technology_name" = "Ignacio Cross"],
					        [#"technology_id" = 2128, #"technology_name" = "Ebonie Spence"],
					        [#"technology_id" = 7, #"technology_name" = "Stephan Lucas"],
					        [#"technology_id" = 5769, #"technology_name" = "Eloy Anthony"],
					        [#"technology_id" = 7279, #"technology_name" = "Cinderella Moody"],
					        [#"technology_id" = 6687, #"technology_name" = "Jamaal Clarke"],
					        [#"technology_id" = 7152, #"technology_name" = "Nida Peck"],
					        [#"technology_id" = 616, #"technology_name" = "Devin Holman"],
					        [#"technology_id" = 4701, #"technology_name" = "Rossana Ward"],
					        [#"technology_id" = 4497, #"technology_name" = "Terrell Hawkins"],
					        [#"technology_id" = 7611, #"technology_name" = "Chieko Oliver"],
					        [#"technology_id" = 3216, #"technology_name" = "Jessika Small"],
					        [#"technology_id" = 8167, #"technology_name" = "Altha Mendez"],
					        [#"technology_id" = 8462, #"technology_name" = "Noma Torres"],
					        [#"technology_id" = 2975, #"technology_name" = "Lynetta Whitley"],
					        [#"technology_id" = 9419, #"technology_name" = "Regan Dennis"],
					        [#"technology_id" = 2973, #"technology_name" = "Glenn Fry"],
					        [#"technology_id" = 6927, #"technology_name" = "Kieth English"],
					        [#"technology_id" = 8634, #"technology_name" = "Lazaro Myers"],
					        [#"technology_id" = 1789, #"technology_name" = "Jesus Morin"],
					        [#"technology_id" = 4381, #"technology_name" = "Cinderella Sharpe"],
					        [#"technology_id" = 2465, #"technology_name" = "Bert Moran"],
					        [#"technology_id" = 3011, #"technology_name" = "Cassey Pierce"],
					        [#"technology_id" = 1983, #"technology_name" = "Eliz Bruce"],
					        [#"technology_id" = 8155, #"technology_name" = "Cletus Duke"],
					        [#"technology_id" = 1583, #"technology_name" = "Ludivina Ford"],
					        [#"technology_id" = 9877, #"technology_name" = "Mariko Rhodes"],
					        [#"technology_id" = 3912, #"technology_name" = "Minh Palmer"],
					        [#"technology_id" = 5488, #"technology_name" = "Phillip Heath"],
					        [#"technology_id" = 9147, #"technology_name" = "Jeanmarie Miles"],
					        [#"technology_id" = 9191, #"technology_name" = "Glennie Santiago"],
					        [#"technology_id" = 9092, #"technology_name" = "Bryanna Singleton"],
					        [#"technology_id" = 1089, #"technology_name" = "Venetta Miranda"],
					        [#"technology_id" = 3273, #"technology_name" = "Kerstin Ballard"],
					        [#"technology_id" = 3283, #"technology_name" = "Gayle Vargas"],
					        [#"technology_id" = 3511, #"technology_name" = "Donovan Haney"],
					        [#"technology_id" = 1174, #"technology_name" = "Jacquelyne Carver"],
					        [#"technology_id" = 6371, #"technology_name" = "Antonina Velasquez"],
					        [#"technology_id" = 9196, #"technology_name" = "Malka Howell"],
					        [#"technology_id" = 4117, #"technology_name" = "Wiley Petersen"],
					        [#"technology_id" = 5084, #"technology_name" = "Wilber Shaffer"],
					        [#"technology_id" = 3739, #"technology_name" = "Edison Kane"],
					        [#"technology_id" = 4930, #"technology_name" = "Nolan Gordon"],
					        [#"technology_id" = 222, #"technology_name" = "Aldo Sharp"],
					        [#"technology_id" = 4361, #"technology_name" = "Haywood Robertson"],
					        [#"technology_id" = 4052, #"technology_name" = "Robin Figueroa"],
					        [#"technology_id" = 3071, #"technology_name" = "Heide Davis"],
					        [#"technology_id" = 5134, #"technology_name" = "Wei Bradshaw"],
					        [#"technology_id" = 1673, #"technology_name" = "Gino Gutierrez"],
					        [#"technology_id" = 1849, #"technology_name" = "Nolan Brady"],
					        [#"technology_id" = 6733, #"technology_name" = "Willis Brady"],
					        [#"technology_id" = 237, #"technology_name" = "Dani Branch"],
					        [#"technology_id" = 4568, #"technology_name" = "Aja Berry"],
					        [#"technology_id" = 8575, #"technology_name" = "Merle Boyle"],
					        [#"technology_id" = 4428, #"technology_name" = "Cherryl Bernard"],
					        [#"technology_id" = 7465, #"technology_name" = "Tory Mcguire"],
					        [#"technology_id" = 128, #"technology_name" = "Hoyt Roberson"],
					        [#"technology_id" = 794, #"technology_name" = "Ron Huff"],
					        [#"technology_id" = 2705, #"technology_name" = "Scotty Hawkins"],
					        [#"technology_id" = 7959, #"technology_name" = "Oneida Simmons"],
					        [#"technology_id" = 4944, #"technology_name" = "Doreatha Thornton"],
					        [#"technology_id" = 4667, #"technology_name" = "Elton Parks"],
					        [#"technology_id" = 7810, #"technology_name" = "Franklyn Buckley"],
					        [#"technology_id" = 808, #"technology_name" = "Jake Salinas"],
					        [#"technology_id" = 7719, #"technology_name" = "Apolonia Kidd"],
					        [#"technology_id" = 7300, #"technology_name" = "Efrain Decker"],
					        [#"technology_id" = 9611, #"technology_name" = "Dannette Frank"],
					        [#"technology_id" = 2077, #"technology_name" = "Mathew Barrett"],
					        [#"technology_id" = 8221, #"technology_name" = "Kevin Bryan"],
					        [#"technology_id" = 5667, #"technology_name" = "Darwin Lowe"],
					        [#"technology_id" = 4726, #"technology_name" = "Joe Brady"],
					        [#"technology_id" = 7136, #"technology_name" = "Stephania Mckay"],
					        [#"technology_id" = 7068, #"technology_name" = "Alyse Peck"],
					        [#"technology_id" = 4404, #"technology_name" = "Vanesa Kennedy"],
					        [#"technology_id" = 2939, #"technology_name" = "Tula Flowers"],
					        [#"technology_id" = 2058, #"technology_name" = "Breana Colon"],
					        [#"technology_id" = 601, #"technology_name" = "Scott Avery"],
					        [#"technology_id" = 4168, #"technology_name" = "Tyron Franks"],
					        [#"technology_id" = 3862, #"technology_name" = "Truman Jarvis"],
					        [#"technology_id" = 2508, #"technology_name" = "Karyl Bridges"],
					        [#"technology_id" = 7575, #"technology_name" = "January Rodriquez"],
					        [#"technology_id" = 6249, #"technology_name" = "Katerine Valentine"],
					        [#"technology_id" = 5468, #"technology_name" = "Jay Puckett"],
					        [#"technology_id" = 8796, #"technology_name" = "Emmitt Burch"],
					        [#"technology_id" = 4232, #"technology_name" = "Donn Haney"],
					        [#"technology_id" = 6152, #"technology_name" = "Maragret Richmond"],
					        [#"technology_id" = 2987, #"technology_name" = "Hans Burke"],
					        [#"technology_id" = 3156, #"technology_name" = "Gerry Martin"],
					        [#"technology_id" = 270, #"technology_name" = "Lorenzo Myers"],
					        [#"technology_id" = 8787, #"technology_name" = "Verlie Garza"],
					        [#"technology_id" = 9132, #"technology_name" = "Scottie Hanson"],
					        [#"technology_id" = 2242, #"technology_name" = "Rudy Neal"],
					        [#"technology_id" = 5947, #"technology_name" = "Mitchell Wallace"],
					        [#"technology_id" = 140, #"technology_name" = "Garry Guthrie"],
					        [#"technology_id" = 1918, #"technology_name" = "Garrett Herring"],
					        [#"technology_id" = 2729, #"technology_name" = "Veta Morrison"],
					        [#"technology_id" = 9680, #"technology_name" = "Nick Richardson"],
					        [#"technology_id" = 1170, #"technology_name" = "Cathern Stone"],
					        [#"technology_id" = 750, #"technology_name" = "Darwin Weber"],
					        [#"technology_id" = 4371, #"technology_name" = "Florencio O'donnell"],
					        [#"technology_id" = 1754, #"technology_name" = "Jenae Holman"],
					        [#"technology_id" = 1753, #"technology_name" = "Elwood Hines"],
					        [#"technology_id" = 2757, #"technology_name" = "Diego Leon"],
					        [#"technology_id" = 2113, #"technology_name" = "Benny Santiago"],
					        [#"technology_id" = 7484, #"technology_name" = "Tova Myers"],
					        [#"technology_id" = 9045, #"technology_name" = "Angelic Patton"],
					        [#"technology_id" = 8898, #"technology_name" = "Jess Campos"],
					        [#"technology_id" = 9695, #"technology_name" = "Dulcie Langley"],
					        [#"technology_id" = 3172, #"technology_name" = "Antonina Cash"],
					        [#"technology_id" = 6103, #"technology_name" = "Nichelle Weiss"],
					        [#"technology_id" = 7404, #"technology_name" = "Carisa Rasmussen"],
					        [#"technology_id" = 4310, #"technology_name" = "Maddie Massey"],
					        [#"technology_id" = 7878, #"technology_name" = "Domitila Pope"],
					        [#"technology_id" = 8264, #"technology_name" = "Roberto Lambert"],
					        [#"technology_id" = 4901, #"technology_name" = "Vertie Calderon"],
					        [#"technology_id" = 9512, #"technology_name" = "Leandro Mccall"],
					        [#"technology_id" = 3870, #"technology_name" = "Amos Lee"],
					        [#"technology_id" = 9189, #"technology_name" = "Devona Stewart"],
					        [#"technology_id" = 8362, #"technology_name" = "Colby Mueller"],
					        [#"technology_id" = 4904, #"technology_name" = "Janay Hodge"],
					        [#"technology_id" = 1238, #"technology_name" = "Mathew Burton"],
					        [#"technology_id" = 2151, #"technology_name" = "Ty Mcintosh"],
					        [#"technology_id" = 5881, #"technology_name" = "Elroy Levy"],
					        [#"technology_id" = 4454, #"technology_name" = "Ernesto Lane"],
					        [#"technology_id" = 6690, #"technology_name" = "Laronda Fox"],
					        [#"technology_id" = 215, #"technology_name" = "Temika Rodriquez"],
					        [#"technology_id" = 358, #"technology_name" = "Carola Morin"],
					        [#"technology_id" = 4492, #"technology_name" = "Azucena Russell"],
					        [#"technology_id" = 2657, #"technology_name" = "Nancee Soto"],
					        [#"technology_id" = 5985, #"technology_name" = "Carmina Harrell"],
					        [#"technology_id" = 7839, #"technology_name" = "Roger Hensley"],
					        [#"technology_id" = 3612, #"technology_name" = "Mitzie Silva"],
					        [#"technology_id" = 6583, #"technology_name" = "Wen Noble"],
					        [#"technology_id" = 6623, #"technology_name" = "Dionna Fulton"],
					        [#"technology_id" = 5238, #"technology_name" = "Jeanelle Banks"],
					        [#"technology_id" = 7304, #"technology_name" = "Cassaundra Peterson"],
					        [#"technology_id" = 2149, #"technology_name" = "Lyle Dudley"],
					        [#"technology_id" = 5802, #"technology_name" = "China Haney"],
					        [#"technology_id" = 7260, #"technology_name" = "Terence Daniel"],
					        [#"technology_id" = 4387, #"technology_name" = "Tiera Bryan"],
					        [#"technology_id" = 9699, #"technology_name" = "Nam Watts"],
					        [#"technology_id" = 8593, #"technology_name" = "Ernie Mendez"],
					        [#"technology_id" = 3908, #"technology_name" = "Casimira Weeks"],
					        [#"technology_id" = 741, #"technology_name" = "Arlie Slater"],
					        [#"technology_id" = 4444, #"technology_name" = "Jewell Morse"],
					        [#"technology_id" = 1446, #"technology_name" = "Wilber Garner"],
					        [#"technology_id" = 6698, #"technology_name" = "Rhett Osborne"],
					        [#"technology_id" = 6293, #"technology_name" = "Cesar Cherry"],
					        [#"technology_id" = 174, #"technology_name" = "Jack Mays"],
					        [#"technology_id" = 6698, #"technology_name" = "Brendan Rocha"],
					        [#"technology_id" = 8471, #"technology_name" = "Javier Phillips"],
					        [#"technology_id" = 7759, #"technology_name" = "Maryrose Gomez"],
					        [#"technology_id" = 7637, #"technology_name" = "Deandre Robertson"],
					        [#"technology_id" = 6837, #"technology_name" = "Woodrow Lancaster"],
					        [#"technology_id" = 9754, #"technology_name" = "Neta Morse"],
					        [#"technology_id" = 2974, #"technology_name" = "Kurtis Love"],
					        [#"technology_id" = 6975, #"technology_name" = "Kaleigh Taylor"],
					        [#"technology_id" = 4001, #"technology_name" = "Salvatore Pearson"],
					        [#"technology_id" = 7249, #"technology_name" = "Florentina Christensen"],
					        [#"technology_id" = 7873, #"technology_name" = "Tommie Clarke"],
					        [#"technology_id" = 1322, #"technology_name" = "Dillon Heath"],
					        [#"technology_id" = 8979, #"technology_name" = "Darron Horn"],
					        [#"technology_id" = 8663, #"technology_name" = "Sharika Mejia"],
					        [#"technology_id" = 8674, #"technology_name" = "Nelia Morgan"],
					        [#"technology_id" = 2899, #"technology_name" = "Herman Mcpherson"],
					        [#"technology_id" = 5494, #"technology_name" = "Lael Porter"],
					        [#"technology_id" = 3743, #"technology_name" = "Teddy Saunders"],
					        [#"technology_id" = 2532, #"technology_name" = "Adolfo Shepherd"],
					        [#"technology_id" = 6263, #"technology_name" = "Rubin Juarez"],
					        [#"technology_id" = 4768, #"technology_name" = "Colby Carver"],
					        [#"technology_id" = 642, #"technology_name" = "Cruz Mathews"],
					        [#"technology_id" = 952, #"technology_name" = "Rudy Simon"],
					        [#"technology_id" = 6035, #"technology_name" = "Kraig Dejesus"],
					        [#"technology_id" = 8195, #"technology_name" = "Willia Rush"],
					        [#"technology_id" = 4443, #"technology_name" = "Adam Tucker"],
					        [#"technology_id" = 9748, #"technology_name" = "Shawanna Knight"],
					        [#"technology_id" = 1926, #"technology_name" = "Stacey Fulton"],
					        [#"technology_id" = 6175, #"technology_name" = "Caleb Farrell"],
					        [#"technology_id" = 9701, #"technology_name" = "Heath Heath"],
					        [#"technology_id" = 4620, #"technology_name" = "Roman Roy"],
					        [#"technology_id" = 8396, #"technology_name" = "Dewitt Warren"],
					        [#"technology_id" = 7085, #"technology_name" = "Armanda Shaffer"],
					        [#"technology_id" = 9072, #"technology_name" = "Britteny Willis"],
					        [#"technology_id" = 1015, #"technology_name" = "Barney Holcomb"],
					        [#"technology_id" = 7407, #"technology_name" = "Steffanie Walters"],
					        [#"technology_id" = 6647, #"technology_name" = "Sherell Waller"],
					        [#"technology_id" = 998, #"technology_name" = "Thurman Larsen"],
					        [#"technology_id" = 149, #"technology_name" = "Clarita Lindsay"],
					        [#"technology_id" = 2057, #"technology_name" = "Amberly Joyner"],
					        [#"technology_id" = 1407, #"technology_name" = "Marylynn Estrada"],
					        [#"technology_id" = 2978, #"technology_name" = "Raisa Albert"],
					        [#"technology_id" = 9847, #"technology_name" = "Merle Ball"],
					        [#"technology_id" = 582, #"technology_name" = "Damion Sanders"],
					        [#"technology_id" = 7072, #"technology_name" = "Yajaira Jackson"],
					        [#"technology_id" = 7130, #"technology_name" = "Tyrone Reynolds"],
					        [#"technology_id" = 4135, #"technology_name" = "Anisa Montgomery"],
					        [#"technology_id" = 6537, #"technology_name" = "Alverta Clay"],
					        [#"technology_id" = 1966, #"technology_name" = "Sook Reynolds"],
					        [#"technology_id" = 1467, #"technology_name" = "Lesia Lamb"],
					        [#"technology_id" = 4764, #"technology_name" = "Akiko Mclean"],
					        [#"technology_id" = 1651, #"technology_name" = "Carmelo Harvey"],
					        [#"technology_id" = 9537, #"technology_name" = "Otha Watson"],
					        [#"technology_id" = 550, #"technology_name" = "Breann Carson"],
					        [#"technology_id" = 5421, #"technology_name" = "Francis Watson"],
					        [#"technology_id" = 7921, #"technology_name" = "Lavera Villarreal"],
					        [#"technology_id" = 6118, #"technology_name" = "Moshe Robbins"],
					        [#"technology_id" = 3462, #"technology_name" = "Cortez Grimes"],
					        [#"technology_id" = 5080, #"technology_name" = "Brittny Faulkner"],
					        [#"technology_id" = 4290, #"technology_name" = "Lance Jenkins"],
					        [#"technology_id" = 9179, #"technology_name" = "Merna Dodson"],
					        [#"technology_id" = 9010, #"technology_name" = "Jalisa Shepard"],
					        [#"technology_id" = 982, #"technology_name" = "Micah Barry"],
					        [#"technology_id" = 6509, #"technology_name" = "Becki Burgess"],
					        [#"technology_id" = 1331, #"technology_name" = "Otha Rollins"],
					        [#"technology_id" = 5620, #"technology_name" = "Santina Gilbert"],
					        [#"technology_id" = 8726, #"technology_name" = "Naida Savage"],
					        [#"technology_id" = 2801, #"technology_name" = "Sharen Juarez"],
					        [#"technology_id" = 6479, #"technology_name" = "Tarah Chavez"],
					        [#"technology_id" = 9687, #"technology_name" = "Chantell Harrington"],
					        [#"technology_id" = 9247, #"technology_name" = "Jeanene Mason"],
					        [#"technology_id" = 8049, #"technology_name" = "Hilaria Bolton"],
					        [#"technology_id" = 2649, #"technology_name" = "Darron Cox"],
					        [#"technology_id" = 2175, #"technology_name" = "Ross Hebert"],
					        [#"technology_id" = 2501, #"technology_name" = "Kaci Herman"],
					        [#"technology_id" = 2217, #"technology_name" = "Karl Blevins"],
					        [#"technology_id" = 7108, #"technology_name" = "Nathan Livingston"],
					        [#"technology_id" = 5791, #"technology_name" = "Aaron White"],
					        [#"technology_id" = 6682, #"technology_name" = "Carline Benton"],
					        [#"technology_id" = 2852, #"technology_name" = "Kelvin Kaufman"],
					        [#"technology_id" = 3660, #"technology_name" = "Rickie Harding"],
					        [#"technology_id" = 7978, #"technology_name" = "Loree Glenn"],
					        [#"technology_id" = 6547, #"technology_name" = "Isidra Leblanc"],
					        [#"technology_id" = 9573, #"technology_name" = "Everett Buckley"],
					        [#"technology_id" = 6539, #"technology_name" = "Gertha Clarke"],
					        [#"technology_id" = 8052, #"technology_name" = "Doreatha Bowen"],
					        [#"technology_id" = 8292, #"technology_name" = "Lewis Terry"],
					        [#"technology_id" = 9010, #"technology_name" = "Joel Justice"],
					        [#"technology_id" = 9765, #"technology_name" = "Yolande Andrews"],
					        [#"technology_id" = 239, #"technology_name" = "Trent Rojas"],
					        [#"technology_id" = 5667, #"technology_name" = "Tobias Craft"],
					        [#"technology_id" = 5946, #"technology_name" = "Hee Schneider"],
					        [#"technology_id" = 7759, #"technology_name" = "Lizzette Wilson"],
					        [#"technology_id" = 9069, #"technology_name" = "Samual Mays"],
					        [#"technology_id" = 6758, #"technology_name" = "Shona Jackson"],
					        [#"technology_id" = 1910, #"technology_name" = "Bernardo Cotton"],
					        [#"technology_id" = 7467, #"technology_name" = "Delmar Herrera"],
					        [#"technology_id" = 3829, #"technology_name" = "Quinn Sharp"],
					        [#"technology_id" = 1204, #"technology_name" = "Johnny Mckay"],
					        [#"technology_id" = 818, #"technology_name" = "Margarito Warren"],
					        [#"technology_id" = 9223, #"technology_name" = "Classie Graves"],
					        [#"technology_id" = 5082, #"technology_name" = "Dalila Stanley"],
					        [#"technology_id" = 4084, #"technology_name" = "Buck Haney"],
					        [#"technology_id" = 5271, #"technology_name" = "Domingo Mcmahon"],
					        [#"technology_id" = 2257, #"technology_name" = "Nickolas Mccoy"],
					        [#"technology_id" = 4256, #"technology_name" = "Tona Serrano"],
					        [#"technology_id" = 801, #"technology_name" = "Tameika Cabrera"],
					        [#"technology_id" = 6342, #"technology_name" = "Annika Oliver"],
					        [#"technology_id" = 6577, #"technology_name" = "Lucius Golden"],
					        [#"technology_id" = 4122, #"technology_name" = "Jestine Glenn"],
					        [#"technology_id" = 3773, #"technology_name" = "Burt Oliver"],
					        [#"technology_id" = 3196, #"technology_name" = "Ming Dillon"],
					        [#"technology_id" = 8599, #"technology_name" = "Darell Nunez"],
					        [#"technology_id" = 6464, #"technology_name" = "Marcellus Livingston"],
					        [#"technology_id" = 7746, #"technology_name" = "Keena Nunez"],
					        [#"technology_id" = 2212, #"technology_name" = "Cortez Houston"],
					        [#"technology_id" = 4, #"technology_name" = "Reda Perez"],
					        [#"technology_id" = 423, #"technology_name" = "Claude Fitzgerald"],
					        [#"technology_id" = 3037, #"technology_name" = "Blake Moore"],
					        [#"technology_id" = 4789, #"technology_name" = "Andy Cervantes"],
					        [#"technology_id" = 691, #"technology_name" = "Maddie Edwards"],
					        [#"technology_id" = 9268, #"technology_name" = "Benito Sanders"],
					        [#"technology_id" = 3735, #"technology_name" = "Karry Clayton"],
					        [#"technology_id" = 806, #"technology_name" = "Katharyn Robles"],
					        [#"technology_id" = 7995, #"technology_name" = "Andera Goff"],
					        [#"technology_id" = 6229, #"technology_name" = "Darron William"],
					        [#"technology_id" = 5500, #"technology_name" = "Martin Mack"],
					        [#"technology_id" = 9578, #"technology_name" = "Kip Levine"],
					        [#"technology_id" = 8169, #"technology_name" = "Nevada Calderon"],
					        [#"technology_id" = 5760, #"technology_name" = "Graig Daugherty"],
					        [#"technology_id" = 4327, #"technology_name" = "Aracelis Mccall"],
					        [#"technology_id" = 5544, #"technology_name" = "Noah Mcguire"],
					        [#"technology_id" = 2999, #"technology_name" = "Chang Salas"],
					        [#"technology_id" = 2309, #"technology_name" = "Isidro Bird"],
					        [#"technology_id" = 3089, #"technology_name" = "Major Terrell"],
					        [#"technology_id" = 8388, #"technology_name" = "Sherice Odom"],
					        [#"technology_id" = 823, #"technology_name" = "Carolin Steele"],
					        [#"technology_id" = 1950, #"technology_name" = "Kermit Ortega"],
					        [#"technology_id" = 5454, #"technology_name" = "Leandro England"],
					        [#"technology_id" = 3949, #"technology_name" = "Lieselotte Potts"],
					        [#"technology_id" = 9051, #"technology_name" = "Bethann Booth"],
					        [#"technology_id" = 6190, #"technology_name" = "Noah Sanford"],
					        [#"technology_id" = 1953, #"technology_name" = "Mercedez Patel"],
					        [#"technology_id" = 916, #"technology_name" = "Sharolyn Conner"],
					        [#"technology_id" = 6563, #"technology_name" = "Burl Stephens"],
					        [#"technology_id" = 8249, #"technology_name" = "Ladawn Whitley"],
					        [#"technology_id" = 4253, #"technology_name" = "Cyril Meyers"],
					        [#"technology_id" = 5794, #"technology_name" = "Dannie Buckley"],
					        [#"technology_id" = 2306, #"technology_name" = "Shenika Barlow"],
					        [#"technology_id" = 4645, #"technology_name" = "Jerold West"],
					        [#"technology_id" = 8351, #"technology_name" = "Nathaniel Weber"],
					        [#"technology_id" = 3396, #"technology_name" = "Willia Mclaughlin"],
					        [#"technology_id" = 1460, #"technology_name" = "Genie Brown"],
					        [#"technology_id" = 2755, #"technology_name" = "Lewis May"],
					        [#"technology_id" = 4321, #"technology_name" = "Lavern Irwin"],
					        [#"technology_id" = 1859, #"technology_name" = "Harris Lowe"],
					        [#"technology_id" = 2631, #"technology_name" = "Peg Mooney"],
					        [#"technology_id" = 5684, #"technology_name" = "Guadalupe Fulton"],
					        [#"technology_id" = 1352, #"technology_name" = "Masako Bray"],
					        [#"technology_id" = 1930, #"technology_name" = "Garfield Mckinney"],
					        [#"technology_id" = 6033, #"technology_name" = "Mireille Richardson"],
					        [#"technology_id" = 4367, #"technology_name" = "Russ Sykes"],
					        [#"technology_id" = 1290, #"technology_name" = "Sheldon Ortiz"],
					        [#"technology_id" = 7933, #"technology_name" = "Sona Blanchard"],
					        [#"technology_id" = 2319, #"technology_name" = "Fausto Rodgers"],
					        [#"technology_id" = 6517, #"technology_name" = "Romeo Mcintosh"],
					        [#"technology_id" = 1249, #"technology_name" = "Lorina Velez"],
					        [#"technology_id" = 660, #"technology_name" = "Nyla Henry"],
					        [#"technology_id" = 5086, #"technology_name" = "Van Zamora"],
					        [#"technology_id" = 4985, #"technology_name" = "Kimbra Vaughn"],
					        [#"technology_id" = 3167, #"technology_name" = "Kristopher Keller"],
					        [#"technology_id" = 5407, #"technology_name" = "Elidia Duncan"],
					        [#"technology_id" = 8931, #"technology_name" = "Loyd Wright"],
					        [#"technology_id" = 7077, #"technology_name" = "Anthony Fitzgerald"],
					        [#"technology_id" = 3122, #"technology_name" = "Micah Noel"],
					        [#"technology_id" = 9266, #"technology_name" = "Hassan Lewis"],
					        [#"technology_id" = 4784, #"technology_name" = "Hung Kim"],
					        [#"technology_id" = 3689, #"technology_name" = "Gerry Foster"],
					        [#"technology_id" = 918, #"technology_name" = "Avril George"],
					        [#"technology_id" = 1948, #"technology_name" = "Malcom Bishop"],
					        [#"technology_id" = 983, #"technology_name" = "Merissa Spears"],
					        [#"technology_id" = 4560, #"technology_name" = "Glenn Cherry"],
					        [#"technology_id" = 6851, #"technology_name" = "Rozella Guthrie"],
					        [#"technology_id" = 9249, #"technology_name" = "Hipolito Matthews"],
					        [#"technology_id" = 9055, #"technology_name" = "Deane Hayden"],
					        [#"technology_id" = 4597, #"technology_name" = "Bud Noble"],
					        [#"technology_id" = 6888, #"technology_name" = "Luigi Rowland"],
					        [#"technology_id" = 2498, #"technology_name" = "Laurene Ball"],
					        [#"technology_id" = 1649, #"technology_name" = "Tad Joyce"],
					        [#"technology_id" = 3888, #"technology_name" = "Shawn Rogers"],
					        [#"technology_id" = 7961, #"technology_name" = "Kanisha Lane"],
					        [#"technology_id" = 5835, #"technology_name" = "Jacquelyne Anderson"],
					        [#"technology_id" = 9614, #"technology_name" = "Aja Blankenship"],
					        [#"technology_id" = 5924, #"technology_name" = "Ardelia Summers"],
					        [#"technology_id" = 3596, #"technology_name" = "Buford Rodriguez"],
					        [#"technology_id" = 2199, #"technology_name" = "Sammy Mcclain"],
					        [#"technology_id" = 7854, #"technology_name" = "Herschel Wagner"],
					        [#"technology_id" = 2744, #"technology_name" = "Debbra Kramer"],
					        [#"technology_id" = 6674, #"technology_name" = "Dennis Garrison"],
					        [#"technology_id" = 976, #"technology_name" = "Anamaria Armstrong"],
					        [#"technology_id" = 8874, #"technology_name" = "Shala Cole"],
					        [#"technology_id" = 2830, #"technology_name" = "Rosamond Glass"],
					        [#"technology_id" = 4377, #"technology_name" = "Francoise Alexander"],
					        [#"technology_id" = 9280, #"technology_name" = "Fredric Wilder"],
					        [#"technology_id" = 7725, #"technology_name" = "Ginette Combs"],
					        [#"technology_id" = 3496, #"technology_name" = "Tomika Brewer"],
					        [#"technology_id" = 9998, #"technology_name" = "Zane Arnold"],
					        [#"technology_id" = 6243, #"technology_name" = "Stevie Wooten"],
					        [#"technology_id" = 1822, #"technology_name" = "Nida Finley"],
					        [#"technology_id" = 7842, #"technology_name" = "Vashti Wells"],
					        [#"technology_id" = 1018, #"technology_name" = "Leana Hudson"],
					        [#"technology_id" = 6286, #"technology_name" = "Candyce Mcclain"],
					        [#"technology_id" = 1264, #"technology_name" = "Waneta Shields"],
					        [#"technology_id" = 7184, #"technology_name" = "Kaila Perry"],
					        [#"technology_id" = 5918, #"technology_name" = "Leena Logan"],
					        [#"technology_id" = 3562, #"technology_name" = "Hayden Rojas"],
					        [#"technology_id" = 9883, #"technology_name" = "Margurite Irwin"],
					        [#"technology_id" = 4968, #"technology_name" = "Shella Miles"],
					        [#"technology_id" = 5021, #"technology_name" = "Toi Harding"],
					        [#"technology_id" = 1244, #"technology_name" = "Cyrstal Humphrey"],
					        [#"technology_id" = 2423, #"technology_name" = "Eugene Wall"],
					        [#"technology_id" = 4803, #"technology_name" = "Apryl Beard"],
					        [#"technology_id" = 7412, #"technology_name" = "Jamel Alston"],
					        [#"technology_id" = 6460, #"technology_name" = "Erich Turner"],
					        [#"technology_id" = 9732, #"technology_name" = "Eveline Petersen"],
					        [#"technology_id" = 2856, #"technology_name" = "Sammie Wallace"],
					        [#"technology_id" = 6667, #"technology_name" = "Miesha Sandoval"],
					        [#"technology_id" = 6547, #"technology_name" = "Mack Patrick"],
					        [#"technology_id" = 4749, #"technology_name" = "Earnest Anderson"],
					        [#"technology_id" = 4630, #"technology_name" = "Kindra Merritt"],
					        [#"technology_id" = 5767, #"technology_name" = "Eusebio Hardin"],
					        [#"technology_id" = 429, #"technology_name" = "Ayesha Butler"],
					        [#"technology_id" = 8394, #"technology_name" = "Terina Ferguson"],
					        [#"technology_id" = 8004, #"technology_name" = "Edmund Dunlap"],
					        [#"technology_id" = 9191, #"technology_name" = "Debroah Dotson"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"technology_id", Int64.Type},
					        {"technology_name", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table