table 'topic_mapping.csv_BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)'
	lineageTag: d7b8b1d4-65b0-4c40-8d1d-4d07ea944a38

	column topic_id
		dataType: int64
		formatString: 0
		lineageTag: d292391c-db1d-4e34-b7e9-e06824f0c9ba
		summarizeBy: sum
		sourceColumn: topic_id

		annotation SummarizationSetBy = Automatic

	column topic_name
		dataType: string
		lineageTag: 7e4e47d8-6efe-4c0a-aa20-1a72306ad389
		summarizeBy: none
		sourceColumn: topic_name

		annotation SummarizationSetBy = Automatic

	partition 'topic_mapping.csv_BCR_2022_07_DDM_ROLLOUT+ (Multiple Connections)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"topic_id" = 1432, #"topic_name" = "Ian Ford"],
					        [#"topic_id" = 640, #"topic_name" = "Ardella Holman"],
					        [#"topic_id" = 9882, #"topic_name" = "Zada Blevins"],
					        [#"topic_id" = 3722, #"topic_name" = "Derick Chapman"],
					        [#"topic_id" = 1578, #"topic_name" = "James Kline"],
					        [#"topic_id" = 4710, #"topic_name" = "Patrina Barlow"],
					        [#"topic_id" = 8179, #"topic_name" = "Jutta Patterson"],
					        [#"topic_id" = 5818, #"topic_name" = "Vincenzo Patel"],
					        [#"topic_id" = 7093, #"topic_name" = "Luis Hooper"],
					        [#"topic_id" = 1211, #"topic_name" = "Gerald Bird"],
					        [#"topic_id" = 9434, #"topic_name" = "Tracy Owens"],
					        [#"topic_id" = 4120, #"topic_name" = "Shirely Suarez"],
					        [#"topic_id" = 3847, #"topic_name" = "Chantell Ford"],
					        [#"topic_id" = 1324, #"topic_name" = "Carisa Rodriquez"],
					        [#"topic_id" = 8891, #"topic_name" = "Kaycee May"],
					        [#"topic_id" = 8639, #"topic_name" = "Andre Rodriquez"],
					        [#"topic_id" = 9018, #"topic_name" = "Sammy Slater"],
					        [#"topic_id" = 4022, #"topic_name" = "Gabriel Benton"],
					        [#"topic_id" = 7167, #"topic_name" = "Thurman Atkinson"],
					        [#"topic_id" = 4073, #"topic_name" = "Kennith Hyde"],
					        [#"topic_id" = 5071, #"topic_name" = "Virgilio Maxwell"],
					        [#"topic_id" = 7975, #"topic_name" = "Edmundo Brewer"],
					        [#"topic_id" = 377, #"topic_name" = "Efrain Clayton"],
					        [#"topic_id" = 2710, #"topic_name" = "Denny Owens"],
					        [#"topic_id" = 7074, #"topic_name" = "Melvin Harrison"],
					        [#"topic_id" = 8955, #"topic_name" = "Loreta Burks"],
					        [#"topic_id" = 4775, #"topic_name" = "Violette England"],
					        [#"topic_id" = 9312, #"topic_name" = "Jewell Benton"],
					        [#"topic_id" = 7676, #"topic_name" = "Hong Porter"],
					        [#"topic_id" = 5927, #"topic_name" = "Son Brooks"],
					        [#"topic_id" = 8320, #"topic_name" = "Lavinia Haney"],
					        [#"topic_id" = 8017, #"topic_name" = "Ervin Meadows"],
					        [#"topic_id" = 1539, #"topic_name" = "Grazyna O'connor"],
					        [#"topic_id" = 6942, #"topic_name" = "Kennith Goff"],
					        [#"topic_id" = 1968, #"topic_name" = "Lashawna Wiggins"],
					        [#"topic_id" = 7042, #"topic_name" = "Elois Burns"],
					        [#"topic_id" = 5711, #"topic_name" = "Kallie Herring"],
					        [#"topic_id" = 3540, #"topic_name" = "Morris Walsh"],
					        [#"topic_id" = 3491, #"topic_name" = "Orville Smith"],
					        [#"topic_id" = 9562, #"topic_name" = "Tajuana Owen"],
					        [#"topic_id" = 5217, #"topic_name" = "Ariel Cleveland"],
					        [#"topic_id" = 136, #"topic_name" = "Daron Jacobson"],
					        [#"topic_id" = 1942, #"topic_name" = "Ayako Harmon"],
					        [#"topic_id" = 7500, #"topic_name" = "Winston Hernandez"],
					        [#"topic_id" = 3776, #"topic_name" = "Annika Barron"],
					        [#"topic_id" = 7863, #"topic_name" = "Enda Terry"],
					        [#"topic_id" = 2260, #"topic_name" = "Elfrieda Cantrell"],
					        [#"topic_id" = 2223, #"topic_name" = "Gianna Chavez"],
					        [#"topic_id" = 8398, #"topic_name" = "Bulah Lindsay"],
					        [#"topic_id" = 6239, #"topic_name" = "Roberto Wilkins"],
					        [#"topic_id" = 9062, #"topic_name" = "Charita Sharp"],
					        [#"topic_id" = 176, #"topic_name" = "Tyrell Delacruz"],
					        [#"topic_id" = 920, #"topic_name" = "Issac Byers"],
					        [#"topic_id" = 9565, #"topic_name" = "Herbert Macias"],
					        [#"topic_id" = 271, #"topic_name" = "Jimmie Finley"],
					        [#"topic_id" = 1679, #"topic_name" = "Saul Roberson"],
					        [#"topic_id" = 4664, #"topic_name" = "Margy Carr"],
					        [#"topic_id" = 2102, #"topic_name" = "Evia Mckenzie"],
					        [#"topic_id" = 1185, #"topic_name" = "Lashell Roach"],
					        [#"topic_id" = 395, #"topic_name" = "Florentina Ratliff"],
					        [#"topic_id" = 8757, #"topic_name" = "Ginette Massey"],
					        [#"topic_id" = 278, #"topic_name" = "Lynelle Wilkinson"],
					        [#"topic_id" = 3789, #"topic_name" = "Bryan Riley"],
					        [#"topic_id" = 9590, #"topic_name" = "Brenton Aguirre"],
					        [#"topic_id" = 7219, #"topic_name" = "Neal Joseph"],
					        [#"topic_id" = 7376, #"topic_name" = "Livia Roman"],
					        [#"topic_id" = 151, #"topic_name" = "Arnulfo Craft"],
					        [#"topic_id" = 5265, #"topic_name" = "Rex Greene"],
					        [#"topic_id" = 1091, #"topic_name" = "Gordon Huffman"],
					        [#"topic_id" = 4300, #"topic_name" = "Fredda West"],
					        [#"topic_id" = 3153, #"topic_name" = "Idell Campos"],
					        [#"topic_id" = 6199, #"topic_name" = "Libbie Garrison"],
					        [#"topic_id" = 903, #"topic_name" = "Sang Nieves"],
					        [#"topic_id" = 8447, #"topic_name" = "Ute Keith"],
					        [#"topic_id" = 3467, #"topic_name" = "Derick Valencia"],
					        [#"topic_id" = 7143, #"topic_name" = "Terrilyn Garrison"],
					        [#"topic_id" = 290, #"topic_name" = "Emmy Norris"],
					        [#"topic_id" = 6549, #"topic_name" = "Emilio Wolf"],
					        [#"topic_id" = 553, #"topic_name" = "Hilma Finley"],
					        [#"topic_id" = 6532, #"topic_name" = "Randolph Kane"],
					        [#"topic_id" = 7908, #"topic_name" = "Sherlene Bean"],
					        [#"topic_id" = 133, #"topic_name" = "Irina Mclean"],
					        [#"topic_id" = 1342, #"topic_name" = "Harry Medina"],
					        [#"topic_id" = 3049, #"topic_name" = "Domonique Rice"],
					        [#"topic_id" = 7374, #"topic_name" = "Sean Walker"],
					        [#"topic_id" = 1765, #"topic_name" = "Royce Alford"],
					        [#"topic_id" = 1481, #"topic_name" = "Tiny Knox"],
					        [#"topic_id" = 1184, #"topic_name" = "Columbus Brock"],
					        [#"topic_id" = 9331, #"topic_name" = "Leeanne Mcdowell"],
					        [#"topic_id" = 6658, #"topic_name" = "Joan Pacheco"],
					        [#"topic_id" = 2997, #"topic_name" = "Talisha Hansen"],
					        [#"topic_id" = 8821, #"topic_name" = "Charlesetta Davidson"],
					        [#"topic_id" = 3279, #"topic_name" = "Lane Good"],
					        [#"topic_id" = 8616, #"topic_name" = "Lazaro Hopkins"],
					        [#"topic_id" = 5537, #"topic_name" = "Tarah Shaw"],
					        [#"topic_id" = 9383, #"topic_name" = "Harold Roberts"],
					        [#"topic_id" = 8805, #"topic_name" = "Malka Weaver"],
					        [#"topic_id" = 5312, #"topic_name" = "Brendan Madden"],
					        [#"topic_id" = 4010, #"topic_name" = "Barbera Lee"],
					        [#"topic_id" = 1275, #"topic_name" = "Rosario Dunn"],
					        [#"topic_id" = 9277, #"topic_name" = "Glendora Benson"],
					        [#"topic_id" = 8082, #"topic_name" = "Bo Humphrey"],
					        [#"topic_id" = 1833, #"topic_name" = "Gaynelle Andrews"],
					        [#"topic_id" = 422, #"topic_name" = "Jackeline Mercado"],
					        [#"topic_id" = 4586, #"topic_name" = "Micha Mcleod"],
					        [#"topic_id" = 9681, #"topic_name" = "Rolf Weeks"],
					        [#"topic_id" = 8079, #"topic_name" = "Shayne Simpson"],
					        [#"topic_id" = 8965, #"topic_name" = "Robbi Hyde"],
					        [#"topic_id" = 4600, #"topic_name" = "Alvin Cleveland"],
					        [#"topic_id" = 9833, #"topic_name" = "Lizzette Carr"],
					        [#"topic_id" = 1824, #"topic_name" = "Hue Montgomery"],
					        [#"topic_id" = 1930, #"topic_name" = "Carter Bridges"],
					        [#"topic_id" = 141, #"topic_name" = "Shona Spears"],
					        [#"topic_id" = 5938, #"topic_name" = "Onita O'neil"],
					        [#"topic_id" = 6248, #"topic_name" = "Claud Clayton"],
					        [#"topic_id" = 1721, #"topic_name" = "Larry Knapp"],
					        [#"topic_id" = 5439, #"topic_name" = "Zulema Patterson"],
					        [#"topic_id" = 9380, #"topic_name" = "Scott Soto"],
					        [#"topic_id" = 8781, #"topic_name" = "Britt Chandler"],
					        [#"topic_id" = 123, #"topic_name" = "Norman Morton"],
					        [#"topic_id" = 272, #"topic_name" = "Ellyn Strong"],
					        [#"topic_id" = 6546, #"topic_name" = "Lahoma Ballard"],
					        [#"topic_id" = 1289, #"topic_name" = "Enrique Butler"],
					        [#"topic_id" = 987, #"topic_name" = "Jacqualine Lambert"],
					        [#"topic_id" = 884, #"topic_name" = "Patricia Lee"],
					        [#"topic_id" = 7289, #"topic_name" = "Irwin Green"],
					        [#"topic_id" = 440, #"topic_name" = "Noriko Wise"],
					        [#"topic_id" = 1945, #"topic_name" = "Shavon Glass"],
					        [#"topic_id" = 8558, #"topic_name" = "Russell Sims"],
					        [#"topic_id" = 994, #"topic_name" = "Alphonse Thomas"],
					        [#"topic_id" = 7933, #"topic_name" = "Lavette Wagner"],
					        [#"topic_id" = 1717, #"topic_name" = "Enoch Hatfield"],
					        [#"topic_id" = 4519, #"topic_name" = "Kalyn Mason"],
					        [#"topic_id" = 6130, #"topic_name" = "Pasquale Osborn"],
					        [#"topic_id" = 7891, #"topic_name" = "Dominque Richard"],
					        [#"topic_id" = 1018, #"topic_name" = "Edelmira Sanchez"],
					        [#"topic_id" = 4718, #"topic_name" = "Sebrina Woods"],
					        [#"topic_id" = 1924, #"topic_name" = "Carry Adkins"],
					        [#"topic_id" = 7176, #"topic_name" = "Derek Hubbard"],
					        [#"topic_id" = 9183, #"topic_name" = "Laurinda Kane"],
					        [#"topic_id" = 2386, #"topic_name" = "Dion Kennedy"],
					        [#"topic_id" = 9182, #"topic_name" = "Dannette Hendrix"],
					        [#"topic_id" = 2996, #"topic_name" = "Christoper Norton"],
					        [#"topic_id" = 2236, #"topic_name" = "Linsey Brooks"],
					        [#"topic_id" = 7032, #"topic_name" = "Hue Vaughan"],
					        [#"topic_id" = 1378, #"topic_name" = "Edmond Osborne"],
					        [#"topic_id" = 519, #"topic_name" = "Kelly Martinez"],
					        [#"topic_id" = 6300, #"topic_name" = "Maryalice Norman"],
					        [#"topic_id" = 4021, #"topic_name" = "Candra Nolan"],
					        [#"topic_id" = 84, #"topic_name" = "Silas Bullock"],
					        [#"topic_id" = 2625, #"topic_name" = "Diamond Guthrie"],
					        [#"topic_id" = 8680, #"topic_name" = "Corrinne Langley"],
					        [#"topic_id" = 6079, #"topic_name" = "Denver Huff"],
					        [#"topic_id" = 1038, #"topic_name" = "Thomas Lane"],
					        [#"topic_id" = 3948, #"topic_name" = "Barton Mcintosh"],
					        [#"topic_id" = 7024, #"topic_name" = "Brinda Steele"],
					        [#"topic_id" = 9879, #"topic_name" = "Malka Owen"],
					        [#"topic_id" = 7012, #"topic_name" = "Clarisa Buchanan"],
					        [#"topic_id" = 3485, #"topic_name" = "Joesph Rutledge"],
					        [#"topic_id" = 6737, #"topic_name" = "Blaine Houston"],
					        [#"topic_id" = 4885, #"topic_name" = "Tyrell Downs"],
					        [#"topic_id" = 4441, #"topic_name" = "Ramon Haney"],
					        [#"topic_id" = 390, #"topic_name" = "Allen Herrera"],
					        [#"topic_id" = 4307, #"topic_name" = "Onie Roth"],
					        [#"topic_id" = 3802, #"topic_name" = "Lanny Austin"],
					        [#"topic_id" = 1890, #"topic_name" = "Arlie Payne"],
					        [#"topic_id" = 6665, #"topic_name" = "Rebecka Rosales"],
					        [#"topic_id" = 4543, #"topic_name" = "Zofia Henson"],
					        [#"topic_id" = 4063, #"topic_name" = "Anibal Mcclure"],
					        [#"topic_id" = 6740, #"topic_name" = "Domonique Serrano"],
					        [#"topic_id" = 6169, #"topic_name" = "Wyatt Pearson"],
					        [#"topic_id" = 1653, #"topic_name" = "Vince Pruitt"],
					        [#"topic_id" = 7099, #"topic_name" = "Chia Duffy"],
					        [#"topic_id" = 3996, #"topic_name" = "Geraldo Mcgee"],
					        [#"topic_id" = 9711, #"topic_name" = "Neil Gonzalez"],
					        [#"topic_id" = 3500, #"topic_name" = "Roxy Reed"],
					        [#"topic_id" = 6097, #"topic_name" = "Justin Holman"],
					        [#"topic_id" = 826, #"topic_name" = "Randolph Frazier"],
					        [#"topic_id" = 5782, #"topic_name" = "Willie Buchanan"],
					        [#"topic_id" = 2452, #"topic_name" = "Nestor Ray"],
					        [#"topic_id" = 9257, #"topic_name" = "August Alvarez"],
					        [#"topic_id" = 3649, #"topic_name" = "Ronald Flowers"],
					        [#"topic_id" = 7456, #"topic_name" = "Kelley Foster"],
					        [#"topic_id" = 7421, #"topic_name" = "Alfonzo Albert"],
					        [#"topic_id" = 5100, #"topic_name" = "Armand Sharp"],
					        [#"topic_id" = 2782, #"topic_name" = "Alyse Poole"],
					        [#"topic_id" = 5056, #"topic_name" = "Burl Herman"],
					        [#"topic_id" = 8076, #"topic_name" = "Reed Harding"],
					        [#"topic_id" = 2871, #"topic_name" = "Raisa Mcneil"],
					        [#"topic_id" = 2955, #"topic_name" = "Angelika Rose"],
					        [#"topic_id" = 6620, #"topic_name" = "Ed Macdonald"],
					        [#"topic_id" = 9856, #"topic_name" = "Hassan Caldwell"],
					        [#"topic_id" = 6808, #"topic_name" = "Neville Mejia"],
					        [#"topic_id" = 4045, #"topic_name" = "Jason Butler"],
					        [#"topic_id" = 6977, #"topic_name" = "Haywood Burton"],
					        [#"topic_id" = 4161, #"topic_name" = "Sylvester Madden"],
					        [#"topic_id" = 1057, #"topic_name" = "Forest Kemp"],
					        [#"topic_id" = 3299, #"topic_name" = "Fidel Hunter"],
					        [#"topic_id" = 1725, #"topic_name" = "Lashaun Morales"],
					        [#"topic_id" = 9958, #"topic_name" = "Romana Flores"],
					        [#"topic_id" = 898, #"topic_name" = "Risa Kemp"],
					        [#"topic_id" = 5381, #"topic_name" = "Sheilah Morse"],
					        [#"topic_id" = 4145, #"topic_name" = "Lee Hudson"],
					        [#"topic_id" = 6415, #"topic_name" = "Tereasa Evans"],
					        [#"topic_id" = 661, #"topic_name" = "Lee Nolan"],
					        [#"topic_id" = 7958, #"topic_name" = "Babara Mcknight"],
					        [#"topic_id" = 7224, #"topic_name" = "Lawrence Cook"],
					        [#"topic_id" = 3877, #"topic_name" = "Rhett Barnett"],
					        [#"topic_id" = 7030, #"topic_name" = "Kina Wong"],
					        [#"topic_id" = 1355, #"topic_name" = "Roseline Lopez"],
					        [#"topic_id" = 2959, #"topic_name" = "Chong Vazquez"],
					        [#"topic_id" = 3710, #"topic_name" = "Malisa England"],
					        [#"topic_id" = 3386, #"topic_name" = "Jake Lowery"],
					        [#"topic_id" = 5683, #"topic_name" = "Danika David"],
					        [#"topic_id" = 4965, #"topic_name" = "Carlena Cantrell"],
					        [#"topic_id" = 4516, #"topic_name" = "Olen Guerra"],
					        [#"topic_id" = 6425, #"topic_name" = "Providencia Moreno"],
					        [#"topic_id" = 7101, #"topic_name" = "Zane Walker"],
					        [#"topic_id" = 9161, #"topic_name" = "Stefan Mcmahon"],
					        [#"topic_id" = 8923, #"topic_name" = "Tracey Fisher"],
					        [#"topic_id" = 8020, #"topic_name" = "Hsiu Newman"],
					        [#"topic_id" = 9132, #"topic_name" = "Halley Mitchell"],
					        [#"topic_id" = 3839, #"topic_name" = "Basilia Chan"],
					        [#"topic_id" = 3699, #"topic_name" = "Gia Young"],
					        [#"topic_id" = 6080, #"topic_name" = "Darron Turner"],
					        [#"topic_id" = 1466, #"topic_name" = "David Phelps"],
					        [#"topic_id" = 6274, #"topic_name" = "Vance Kent"],
					        [#"topic_id" = 6068, #"topic_name" = "Lamonica Langley"],
					        [#"topic_id" = 5444, #"topic_name" = "Ammie Turner"],
					        [#"topic_id" = 3803, #"topic_name" = "Jeanmarie Tyson"],
					        [#"topic_id" = 6888, #"topic_name" = "Jefferson Forbes"],
					        [#"topic_id" = 6520, #"topic_name" = "Marya David"],
					        [#"topic_id" = 7267, #"topic_name" = "Lionel Hunt"],
					        [#"topic_id" = 4222, #"topic_name" = "Mckenzie Stanley"],
					        [#"topic_id" = 7726, #"topic_name" = "Garry Wilder"],
					        [#"topic_id" = 387, #"topic_name" = "Cleveland Sears"],
					        [#"topic_id" = 2979, #"topic_name" = "Jay Knight"],
					        [#"topic_id" = 3030, #"topic_name" = "Reinaldo Alford"],
					        [#"topic_id" = 3196, #"topic_name" = "Deloras Mccormick"],
					        [#"topic_id" = 2571, #"topic_name" = "Sidney Stafford"],
					        [#"topic_id" = 8079, #"topic_name" = "Ethelene Pope"],
					        [#"topic_id" = 1063, #"topic_name" = "Felton Hodges"],
					        [#"topic_id" = 6276, #"topic_name" = "Everette Donaldson"],
					        [#"topic_id" = 5556, #"topic_name" = "Darrick Peck"],
					        [#"topic_id" = 637, #"topic_name" = "Ethelene Dominguez"],
					        [#"topic_id" = 3730, #"topic_name" = "Annice Leon"],
					        [#"topic_id" = 3612, #"topic_name" = "Deonna Aguilar"],
					        [#"topic_id" = 3371, #"topic_name" = "Leonard Stark"],
					        [#"topic_id" = 3659, #"topic_name" = "Merrill Hyde"],
					        [#"topic_id" = 2133, #"topic_name" = "Maurice Martinez"],
					        [#"topic_id" = 7421, #"topic_name" = "Jamal Sanchez"],
					        [#"topic_id" = 3520, #"topic_name" = "Lindsy Frost"],
					        [#"topic_id" = 9535, #"topic_name" = "Vance Benton"],
					        [#"topic_id" = 4469, #"topic_name" = "Joselyn Owens"],
					        [#"topic_id" = 5470, #"topic_name" = "Cecila Fischer"],
					        [#"topic_id" = 2261, #"topic_name" = "Felton Hopkins"],
					        [#"topic_id" = 1188, #"topic_name" = "Fabian Small"],
					        [#"topic_id" = 1980, #"topic_name" = "Kenny Whitaker"],
					        [#"topic_id" = 7690, #"topic_name" = "Shalanda Watson"],
					        [#"topic_id" = 4998, #"topic_name" = "Bradly Smith"],
					        [#"topic_id" = 8985, #"topic_name" = "Annita Noble"],
					        [#"topic_id" = 9015, #"topic_name" = "Trey Wheeler"],
					        [#"topic_id" = 6598, #"topic_name" = "Todd Valenzuela"],
					        [#"topic_id" = 5350, #"topic_name" = "Daphine Glass"],
					        [#"topic_id" = 1567, #"topic_name" = "Theron Stout"],
					        [#"topic_id" = 5955, #"topic_name" = "Siu Stafford"],
					        [#"topic_id" = 6397, #"topic_name" = "Jerrica Mosley"],
					        [#"topic_id" = 1493, #"topic_name" = "Maryalice Compton"],
					        [#"topic_id" = 336, #"topic_name" = "Katelynn Barnes"],
					        [#"topic_id" = 5930, #"topic_name" = "Brian Chaney"],
					        [#"topic_id" = 6843, #"topic_name" = "Esteban England"],
					        [#"topic_id" = 8682, #"topic_name" = "Sol Stewart"],
					        [#"topic_id" = 4126, #"topic_name" = "Lonnie Nelson"],
					        [#"topic_id" = 6513, #"topic_name" = "Gene Blankenship"],
					        [#"topic_id" = 8281, #"topic_name" = "Tony Rogers"],
					        [#"topic_id" = 9944, #"topic_name" = "Fae Hatfield"],
					        [#"topic_id" = 2591, #"topic_name" = "Lilla Hunt"],
					        [#"topic_id" = 6470, #"topic_name" = "Sherlyn Downs"],
					        [#"topic_id" = 2479, #"topic_name" = "Nguyet Mcguire"],
					        [#"topic_id" = 6194, #"topic_name" = "Angle Glover"],
					        [#"topic_id" = 8499, #"topic_name" = "Julietta Gentry"],
					        [#"topic_id" = 2580, #"topic_name" = "Beula Martinez"],
					        [#"topic_id" = 7601, #"topic_name" = "Rhett Fleming"],
					        [#"topic_id" = 7820, #"topic_name" = "Consuela Hayes"],
					        [#"topic_id" = 275, #"topic_name" = "Katherina Berry"],
					        [#"topic_id" = 669, #"topic_name" = "Avery Alvarado"],
					        [#"topic_id" = 7394, #"topic_name" = "Crystle Hughes"],
					        [#"topic_id" = 4556, #"topic_name" = "Kimi Cash"],
					        [#"topic_id" = 5835, #"topic_name" = "Yahaira Matthews"],
					        [#"topic_id" = 2738, #"topic_name" = "Rolf Miles"],
					        [#"topic_id" = 1645, #"topic_name" = "Yolando Burris"],
					        [#"topic_id" = 2271, #"topic_name" = "Domitila Mccray"],
					        [#"topic_id" = 9335, #"topic_name" = "Chau Ferrell"],
					        [#"topic_id" = 3838, #"topic_name" = "Kazuko Conley"],
					        [#"topic_id" = 4437, #"topic_name" = "Raymundo Dejesus"],
					        [#"topic_id" = 5744, #"topic_name" = "Omega Kramer"],
					        [#"topic_id" = 8878, #"topic_name" = "Eldon Lewis"],
					        [#"topic_id" = 1329, #"topic_name" = "Leeanna Kemp"],
					        [#"topic_id" = 1994, #"topic_name" = "Andre Downs"],
					        [#"topic_id" = 1867, #"topic_name" = "Jamel Hardy"],
					        [#"topic_id" = 7454, #"topic_name" = "Francina Bridges"],
					        [#"topic_id" = 4890, #"topic_name" = "Lawrence Stein"],
					        [#"topic_id" = 1428, #"topic_name" = "Gerald Huber"],
					        [#"topic_id" = 6415, #"topic_name" = "Haywood Cole"],
					        [#"topic_id" = 4035, #"topic_name" = "Willena Mullen"],
					        [#"topic_id" = 9685, #"topic_name" = "Emmaline Walter"],
					        [#"topic_id" = 4924, #"topic_name" = "Pandora Freeman"],
					        [#"topic_id" = 5219, #"topic_name" = "Melany Moses"],
					        [#"topic_id" = 6512, #"topic_name" = "Lauralee Lara"],
					        [#"topic_id" = 8982, #"topic_name" = "Magdalen Levine"],
					        [#"topic_id" = 5916, #"topic_name" = "Elvie Ingram"],
					        [#"topic_id" = 1158, #"topic_name" = "Darrel Burris"],
					        [#"topic_id" = 5206, #"topic_name" = "Hector Vargas"],
					        [#"topic_id" = 2082, #"topic_name" = "Mason Baxter"],
					        [#"topic_id" = 3536, #"topic_name" = "Shad Odom"],
					        [#"topic_id" = 2475, #"topic_name" = "Curtis Drake"],
					        [#"topic_id" = 202, #"topic_name" = "Alona Green"],
					        [#"topic_id" = 3424, #"topic_name" = "Latrisha Jacobson"],
					        [#"topic_id" = 2187, #"topic_name" = "Karey Harvey"],
					        [#"topic_id" = 8039, #"topic_name" = "Leonarda Grimes"],
					        [#"topic_id" = 7379, #"topic_name" = "Eduardo Shaffer"],
					        [#"topic_id" = 4460, #"topic_name" = "Miguelina Harrison"],
					        [#"topic_id" = 8081, #"topic_name" = "Basilia Hahn"],
					        [#"topic_id" = 6892, #"topic_name" = "Jenae Benjamin"],
					        [#"topic_id" = 194, #"topic_name" = "Arturo Hobbs"],
					        [#"topic_id" = 841, #"topic_name" = "Grady Macdonald"],
					        [#"topic_id" = 1994, #"topic_name" = "Jae Brennan"],
					        [#"topic_id" = 421, #"topic_name" = "Ayanna Cash"],
					        [#"topic_id" = 1355, #"topic_name" = "Carry Hodges"],
					        [#"topic_id" = 5783, #"topic_name" = "Quyen Monroe"],
					        [#"topic_id" = 245, #"topic_name" = "Angelika Black"],
					        [#"topic_id" = 9769, #"topic_name" = "Norman Buck"],
					        [#"topic_id" = 1734, #"topic_name" = "Minh Hester"],
					        [#"topic_id" = 5839, #"topic_name" = "Hollis Shepherd"],
					        [#"topic_id" = 7199, #"topic_name" = "Mikel Todd"],
					        [#"topic_id" = 1956, #"topic_name" = "Marceline Santiago"],
					        [#"topic_id" = 3780, #"topic_name" = "Krystina Underwood"],
					        [#"topic_id" = 4645, #"topic_name" = "Mafalda Mcmahon"],
					        [#"topic_id" = 4648, #"topic_name" = "Julio Fleming"],
					        [#"topic_id" = 4567, #"topic_name" = "Myles Wooten"],
					        [#"topic_id" = 37, #"topic_name" = "Setsuko Lewis"],
					        [#"topic_id" = 4898, #"topic_name" = "Houston Henderson"],
					        [#"topic_id" = 3929, #"topic_name" = "Humberto Landry"],
					        [#"topic_id" = 7368, #"topic_name" = "Virgil Mays"],
					        [#"topic_id" = 222, #"topic_name" = "Kent Horn"],
					        [#"topic_id" = 153, #"topic_name" = "Russel Dodson"],
					        [#"topic_id" = 7320, #"topic_name" = "Jonie Faulkner"],
					        [#"topic_id" = 355, #"topic_name" = "Winford Dale"],
					        [#"topic_id" = 9243, #"topic_name" = "Arthur Garner"],
					        [#"topic_id" = 8188, #"topic_name" = "Kareen Padilla"],
					        [#"topic_id" = 3436, #"topic_name" = "Jennine Steele"],
					        [#"topic_id" = 7023, #"topic_name" = "Greg Donaldson"],
					        [#"topic_id" = 1655, #"topic_name" = "Orville Stevenson"],
					        [#"topic_id" = 7651, #"topic_name" = "Timika Goff"],
					        [#"topic_id" = 291, #"topic_name" = "Bryce Bryant"],
					        [#"topic_id" = 2750, #"topic_name" = "Henry Joyce"],
					        [#"topic_id" = 4936, #"topic_name" = "Patrick Chan"],
					        [#"topic_id" = 9173, #"topic_name" = "Steven Jacobson"],
					        [#"topic_id" = 9561, #"topic_name" = "Shan Blanchard"],
					        [#"topic_id" = 5613, #"topic_name" = "Quincy Larsen"],
					        [#"topic_id" = 5966, #"topic_name" = "Jon Peck"],
					        [#"topic_id" = 1552, #"topic_name" = "Gino Frye"],
					        [#"topic_id" = 4673, #"topic_name" = "Ossie Lloyd"],
					        [#"topic_id" = 4443, #"topic_name" = "Leif Lewis"],
					        [#"topic_id" = 5178, #"topic_name" = "Dwain Howell"],
					        [#"topic_id" = 892, #"topic_name" = "Sadye Everett"],
					        [#"topic_id" = 4626, #"topic_name" = "Londa Smith"],
					        [#"topic_id" = 2080, #"topic_name" = "Kendrick Riggs"],
					        [#"topic_id" = 7964, #"topic_name" = "Calvin Garcia"],
					        [#"topic_id" = 4222, #"topic_name" = "Malcolm Morgan"],
					        [#"topic_id" = 7319, #"topic_name" = "Donnell Rhodes"],
					        [#"topic_id" = 8740, #"topic_name" = "Nathan Delaney"],
					        [#"topic_id" = 189, #"topic_name" = "Johnie Price"],
					        [#"topic_id" = 3829, #"topic_name" = "Teodoro Potts"],
					        [#"topic_id" = 8712, #"topic_name" = "Otha Atkinson"],
					        [#"topic_id" = 7806, #"topic_name" = "Lynsey Sykes"],
					        [#"topic_id" = 9198, #"topic_name" = "Cristie Jacobson"],
					        [#"topic_id" = 4476, #"topic_name" = "Brandon Vaughn"],
					        [#"topic_id" = 6824, #"topic_name" = "Robin Carlson"],
					        [#"topic_id" = 7108, #"topic_name" = "Jamel Higgins"],
					        [#"topic_id" = 6214, #"topic_name" = "Xavier Clarke"],
					        [#"topic_id" = 2673, #"topic_name" = "Kristopher Frederick"],
					        [#"topic_id" = 4155, #"topic_name" = "Augustine Frederick"],
					        [#"topic_id" = 1484, #"topic_name" = "Michal Little"],
					        [#"topic_id" = 9977, #"topic_name" = "Collene Savage"],
					        [#"topic_id" = 2749, #"topic_name" = "Lazaro Vega"],
					        [#"topic_id" = 2954, #"topic_name" = "Andre Andrews"],
					        [#"topic_id" = 4519, #"topic_name" = "Isaias Craft"],
					        [#"topic_id" = 2157, #"topic_name" = "Erick Solis"],
					        [#"topic_id" = 9766, #"topic_name" = "Edra Kaufman"],
					        [#"topic_id" = 6137, #"topic_name" = "Ethan Pickett"],
					        [#"topic_id" = 375, #"topic_name" = "Annalee Wells"],
					        [#"topic_id" = 5730, #"topic_name" = "Jess Garner"],
					        [#"topic_id" = 520, #"topic_name" = "Lizeth Coffey"],
					        [#"topic_id" = 7955, #"topic_name" = "Carlo Albert"],
					        [#"topic_id" = 2772, #"topic_name" = "Izetta Pugh"],
					        [#"topic_id" = 3527, #"topic_name" = "Reinaldo David"],
					        [#"topic_id" = 1084, #"topic_name" = "Hyo Mcclain"],
					        [#"topic_id" = 2163, #"topic_name" = "Joaquin Hubbard"],
					        [#"topic_id" = 8276, #"topic_name" = "Alton Simpson"],
					        [#"topic_id" = 4068, #"topic_name" = "Erasmo Rocha"],
					        [#"topic_id" = 6734, #"topic_name" = "Lilli Marquez"],
					        [#"topic_id" = 4710, #"topic_name" = "Shin Barr"],
					        [#"topic_id" = 8507, #"topic_name" = "Barry Craig"],
					        [#"topic_id" = 3827, #"topic_name" = "Kymberly Waters"],
					        [#"topic_id" = 2776, #"topic_name" = "Chae Hayes"],
					        [#"topic_id" = 784, #"topic_name" = "Nathanael Tyler"],
					        [#"topic_id" = 2419, #"topic_name" = "Bo Bowman"],
					        [#"topic_id" = 4386, #"topic_name" = "George Larsen"],
					        [#"topic_id" = 4991, #"topic_name" = "Mac Jackson"],
					        [#"topic_id" = 4931, #"topic_name" = "Tim Porter"],
					        [#"topic_id" = 6131, #"topic_name" = "Glady Ratliff"],
					        [#"topic_id" = 6021, #"topic_name" = "Khalilah Miller"],
					        [#"topic_id" = 7596, #"topic_name" = "Eli Brown"],
					        [#"topic_id" = 2273, #"topic_name" = "Euna Cardenas"],
					        [#"topic_id" = 5203, #"topic_name" = "Verdell O'brien"],
					        [#"topic_id" = 8815, #"topic_name" = "Willene Dawson"],
					        [#"topic_id" = 9729, #"topic_name" = "Chanell Randolph"],
					        [#"topic_id" = 339, #"topic_name" = "Renay Mclaughlin"],
					        [#"topic_id" = 8145, #"topic_name" = "Eneida Henderson"],
					        [#"topic_id" = 3775, #"topic_name" = "Fausto Mcknight"],
					        [#"topic_id" = 4254, #"topic_name" = "Leo Rojas"],
					        [#"topic_id" = 5155, #"topic_name" = "Domingo Wright"],
					        [#"topic_id" = 7054, #"topic_name" = "Luther Fry"],
					        [#"topic_id" = 4753, #"topic_name" = "Marica Ingram"],
					        [#"topic_id" = 3269, #"topic_name" = "Francesco Powell"],
					        [#"topic_id" = 3970, #"topic_name" = "Billye Hill"],
					        [#"topic_id" = 2342, #"topic_name" = "Lashay Gross"],
					        [#"topic_id" = 468, #"topic_name" = "Elizbeth Clayton"],
					        [#"topic_id" = 3738, #"topic_name" = "Shon Palmer"],
					        [#"topic_id" = 1084, #"topic_name" = "Harry Cross"],
					        [#"topic_id" = 5438, #"topic_name" = "Tiffaney Cox"],
					        [#"topic_id" = 5461, #"topic_name" = "Queenie Hart"],
					        [#"topic_id" = 8609, #"topic_name" = "Roderick Dean"],
					        [#"topic_id" = 9134, #"topic_name" = "Maurice Burris"],
					        [#"topic_id" = 5150, #"topic_name" = "Glenn Fry"],
					        [#"topic_id" = 7865, #"topic_name" = "Shaun Watts"],
					        [#"topic_id" = 6952, #"topic_name" = "Dalton Parks"],
					        [#"topic_id" = 4623, #"topic_name" = "Angila Vincent"],
					        [#"topic_id" = 9697, #"topic_name" = "Jetta Wall"],
					        [#"topic_id" = 9289, #"topic_name" = "Marcel Harrell"],
					        [#"topic_id" = 6491, #"topic_name" = "Ronald Short"],
					        [#"topic_id" = 4393, #"topic_name" = "Renay Hall"],
					        [#"topic_id" = 2799, #"topic_name" = "Darnell Mays"],
					        [#"topic_id" = 260, #"topic_name" = "Alphonso Grimes"],
					        [#"topic_id" = 4467, #"topic_name" = "Kiana Gamble"],
					        [#"topic_id" = 2255, #"topic_name" = "Eduardo Foster"],
					        [#"topic_id" = 8463, #"topic_name" = "Damon Howe"],
					        [#"topic_id" = 1906, #"topic_name" = "Hubert Taylor"],
					        [#"topic_id" = 2105, #"topic_name" = "Rachell Fletcher"],
					        [#"topic_id" = 2649, #"topic_name" = "Giovanni Paul"],
					        [#"topic_id" = 7625, #"topic_name" = "Geraldo Compton"],
					        [#"topic_id" = 3648, #"topic_name" = "Jared Pittman"],
					        [#"topic_id" = 5954, #"topic_name" = "Boyce Herring"],
					        [#"topic_id" = 1820, #"topic_name" = "Trent Hayden"],
					        [#"topic_id" = 1232, #"topic_name" = "Chaya Ramsey"],
					        [#"topic_id" = 9197, #"topic_name" = "Max White"],
					        [#"topic_id" = 5358, #"topic_name" = "Mckinley Sanchez"],
					        [#"topic_id" = 9034, #"topic_name" = "Franklyn Santana"],
					        [#"topic_id" = 3459, #"topic_name" = "Damon Hensley"],
					        [#"topic_id" = 6351, #"topic_name" = "Shad Garner"],
					        [#"topic_id" = 3522, #"topic_name" = "Naida Kerr"],
					        [#"topic_id" = 1124, #"topic_name" = "Adolph Whitehead"],
					        [#"topic_id" = 273, #"topic_name" = "Francisco Langley"],
					        [#"topic_id" = 1296, #"topic_name" = "Mickie Santana"],
					        [#"topic_id" = 8600, #"topic_name" = "Man Massey"],
					        [#"topic_id" = 4433, #"topic_name" = "Diego Fitzpatrick"],
					        [#"topic_id" = 1952, #"topic_name" = "Cornelius Holmes"],
					        [#"topic_id" = 8523, #"topic_name" = "Larisa Montoya"],
					        [#"topic_id" = 3627, #"topic_name" = "Alayna Kennedy"],
					        [#"topic_id" = 6411, #"topic_name" = "Avery Walton"],
					        [#"topic_id" = 5119, #"topic_name" = "Burl Russo"],
					        [#"topic_id" = 8892, #"topic_name" = "Norberto Vega"],
					        [#"topic_id" = 5863, #"topic_name" = "Jerrell Mosley"],
					        [#"topic_id" = 2708, #"topic_name" = "Wilfred Medina"],
					        [#"topic_id" = 8875, #"topic_name" = "Kelsi Ingram"],
					        [#"topic_id" = 8231, #"topic_name" = "Yong Rosales"],
					        [#"topic_id" = 3602, #"topic_name" = "Pierre Sampson"],
					        [#"topic_id" = 4089, #"topic_name" = "Daniel Drake"],
					        [#"topic_id" = 7609, #"topic_name" = "Gene Allison"],
					        [#"topic_id" = 586, #"topic_name" = "Harlan Montgomery"],
					        [#"topic_id" = 7451, #"topic_name" = "Mariel Lancaster"],
					        [#"topic_id" = 7776, #"topic_name" = "Wilfredo Tyler"],
					        [#"topic_id" = 1401, #"topic_name" = "Collene Chambers"],
					        [#"topic_id" = 4588, #"topic_name" = "Elvin Bates"],
					        [#"topic_id" = 4315, #"topic_name" = "Rubi Webster"],
					        [#"topic_id" = 8604, #"topic_name" = "Darius Gilmore"],
					        [#"topic_id" = 7411, #"topic_name" = "Aracelis Calderon"],
					        [#"topic_id" = 2571, #"topic_name" = "Milagro Russo"],
					        [#"topic_id" = 4177, #"topic_name" = "Rosio Mccormick"],
					        [#"topic_id" = 4825, #"topic_name" = "Lynwood Vasquez"],
					        [#"topic_id" = 8958, #"topic_name" = "Enola Turner"],
					        [#"topic_id" = 8932, #"topic_name" = "Raisa Rosario"],
					        [#"topic_id" = 5829, #"topic_name" = "Steven Livingston"],
					        [#"topic_id" = 3186, #"topic_name" = "Jeremy Carr"],
					        [#"topic_id" = 4701, #"topic_name" = "Janyce Patton"],
					        [#"topic_id" = 2530, #"topic_name" = "Alvera Fleming"],
					        [#"topic_id" = 2037, #"topic_name" = "Remedios Buckner"],
					        [#"topic_id" = 2922, #"topic_name" = "Irmgard Hunter"],
					        [#"topic_id" = 1122, #"topic_name" = "Chin Mercado"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"topic_id", Int64.Type},
					        {"topic_name", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table