table 'Orders (Sample - Superstore (1))'
	lineageTag: 1f09ef4b-2363-4cd6-9268-16d85d25f570

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 7f21183e-3c8a-4168-b94e-c3e3f3856cf4
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: a98240a7-13e3-4dce-ace8-fc0577e63e82
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: datetime
		lineageTag: 25ff8c4a-6766-44d8-b9ad-84136a1e5b30
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: datetime
		lineageTag: 958b6954-f6d2-4d24-badc-69a5421fe3c8
		summarizeBy: none
		sourceColumn: 'Ship Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 75bcbd2a-aa7b-439c-8171-2b657162aa76
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 6d62813d-5a8a-46b1-b514-4209d7138786
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 77633245-e413-4a2c-8d3c-eec3afc6b669
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: bb27b9f0-cff4-4648-bf51-07dc260a0e03
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: b87d80f5-63f6-4e28-bb21-bc3d30ff614a
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: d0042198-4913-49dd-ace0-f25775a35f2f
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: c25b8755-2c2e-4d90-89d3-44337f283f45
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 7d8e5f82-9fbc-4125-a7f2-15c939fc8304
		summarizeBy: sum
		sourceColumn: 'Postal Code'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 290649f4-fc48-4e01-8110-b2607a210a43
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: d52b7659-65f7-477e-b67d-d134e2f7d440
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 13d7ea35-8a62-49ac-8ee6-9f3acb696f32
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: 8916f909-caf4-4708-a56a-5fa2c6aaf508
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 8aa5d118-9149-48eb-9cf8-7baed7fe275b
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: General Number
		lineageTag: 5a45852b-ebc8-4b01-92f9-3389a3d5b11f
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 2994ebdb-1968-4a71-9e74-059af0dde91b
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: General Number
		lineageTag: ff997943-1361-4990-8671-2b4cd05db95a
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		formatString: General Number
		lineageTag: 1907e578-2563-4bda-832a-d169afa82a72
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Calculation1 = SWITCH('Orders (Sample - Superstore (1))'[Category], \"Furniture\", \"furniture\", \"Office Supplies\", \"office supplier\", \"Technology\", \"technology\", 'Orders (Sample - Superstore (1))'[Category])
		lineageTag: 15f0c77b-8249-47df-95a2-7c9c4940d8ac
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Orders (Sample - Superstore (1))' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Row ID" = 6525, #"Order ID" = 1983, #"Order Date" = #date(2023, 6, 21), #"Ship Date" = #date(2023, 7, 22), #"Ship Mode" = "93.151.70.212", #"Customer ID" = 2145, #"Customer Name" = "Yelena Gaines", #"Segment" = "bridge", #"Country" = "Vatican City", #"City" = "San Juan", #"State" = "Ohio", #"Postal Code" = 797, #"Region" = "Delaware", #"Product ID" = 5213, #"Category" = "fast", #"Sub-Category" = "stream", #"Product Name" = "Marhta Carpenter", #"Sales" = 223.68, #"Quantity" = 607, #"Discount" = 566.02, #"Profit" = 409.21],
					        [#"Row ID" = 3708, #"Order ID" = 2162, #"Order Date" = #date(2023, 11, 28), #"Ship Date" = #date(2024, 12, 2), #"Ship Mode" = "174.179.13.201", #"Customer ID" = 6688, #"Customer Name" = "Nga Hahn", #"Segment" = "item", #"Country" = "Belarus", #"City" = "Simpsonville", #"State" = "Missouri", #"Postal Code" = 880, #"Region" = "Minnesota", #"Product ID" = 1142, #"Category" = "cold", #"Sub-Category" = "housing", #"Product Name" = "Billie Mcfadden", #"Sales" = 923.93, #"Quantity" = 385, #"Discount" = 752.27, #"Profit" = 927.44],
					        [#"Row ID" = 7959, #"Order ID" = 4047, #"Order Date" = #date(2024, 6, 18), #"Ship Date" = #date(2020, 10, 22), #"Ship Mode" = "147.88.252.119", #"Customer ID" = 5733, #"Customer Name" = "Gia Carpenter", #"Segment" = "expensive", #"Country" = "Laos", #"City" = "Wyandotte", #"State" = "West Virginia", #"Postal Code" = 265, #"Region" = "Kansas", #"Product ID" = 5794, #"Category" = "montreal", #"Sub-Category" = "revised", #"Product Name" = "Faustino Duke", #"Sales" = 261.81, #"Quantity" = 31, #"Discount" = 559.96, #"Profit" = 726.31],
					        [#"Row ID" = 626, #"Order ID" = 6250, #"Order Date" = #date(2022, 1, 28), #"Ship Date" = #date(2022, 8, 25), #"Ship Mode" = "21.92.37.12", #"Customer ID" = 7134, #"Customer Name" = "Christia Alexander", #"Segment" = "winner", #"Country" = "Senegal", #"City" = "Buffalo", #"State" = "California", #"Postal Code" = 776, #"Region" = "South Carolina", #"Product ID" = 5527, #"Category" = "comic", #"Sub-Category" = "purposes", #"Product Name" = "Jerica Campos", #"Sales" = 304.45, #"Quantity" = 454, #"Discount" = 8.39, #"Profit" = 359.26],
					        [#"Row ID" = 5665, #"Order ID" = 8042, #"Order Date" = #date(2021, 11, 5), #"Ship Date" = #date(2021, 9, 13), #"Ship Mode" = "55.26.84.11", #"Customer ID" = 6518, #"Customer Name" = "Lakenya Montgomery", #"Segment" = "winners", #"Country" = "Argentina", #"City" = "Cleveland Heights", #"State" = "Missouri", #"Postal Code" = 569, #"Region" = "Utah", #"Product ID" = 2609, #"Category" = "address", #"Sub-Category" = "ah", #"Product Name" = "Maye Shelton", #"Sales" = 787.75, #"Quantity" = 626, #"Discount" = 755.52, #"Profit" = 815.56]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Row ID", Int64.Type},
					        {"Order ID", type text},
					        {"Order Date", type date},
					        {"Ship Date", type date},
					        {"Ship Mode", type text},
					        {"Customer ID", type text},
					        {"Customer Name", type text},
					        {"Segment", type text},
					        {"Country", type text},
					        {"City", type text},
					        {"State", type text},
					        {"Postal Code", Int64.Type},
					        {"Region", type text},
					        {"Product ID", type text},
					        {"Category", type text},
					        {"Sub-Category", type text},
					        {"Product Name", type text},
					        {"Sales", type number},
					        {"Quantity", Int64.Type},
					        {"Discount", type number},
					        {"Profit", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table