table 'Sample - Superstore_Returns'
	lineageTag: 347ad967-5645-4f21-82c1-3589d78abb49

	column Returned
		dataType: string
		lineageTag: 8b4c8b88-0d77-45c0-9264-40333b7a92e3
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: bf4269c1-7949-4b6e-8f8d-ec722b44e3b4
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	partition 'Sample - Superstore_Returns' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Returned" = "figures", #"Order ID" = 8153],
					        [#"Returned" = "raising", #"Order ID" = 6237],
					        [#"Returned" = "oz", #"Order ID" = 9742],
					        [#"Returned" = "diameter", #"Order ID" = 6344],
					        [#"Returned" = "hs", #"Order ID" = 4043],
					        [#"Returned" = "ri", #"Order ID" = 3608],
					        [#"Returned" = "blogger", #"Order ID" = 4424],
					        [#"Returned" = "due", #"Order ID" = 1529],
					        [#"Returned" = "responsibility", #"Order ID" = 5010],
					        [#"Returned" = "found", #"Order ID" = 7692],
					        [#"Returned" = "agree", #"Order ID" = 9820],
					        [#"Returned" = "facilitate", #"Order ID" = 3857],
					        [#"Returned" = "article", #"Order ID" = 6877],
					        [#"Returned" = "appendix", #"Order ID" = 5683],
					        [#"Returned" = "electronic", #"Order ID" = 6389],
					        [#"Returned" = "special", #"Order ID" = 6695],
					        [#"Returned" = "racing", #"Order ID" = 3239],
					        [#"Returned" = "trees", #"Order ID" = 3232],
					        [#"Returned" = "appeals", #"Order ID" = 1242],
					        [#"Returned" = "zone", #"Order ID" = 4898],
					        [#"Returned" = "content", #"Order ID" = 8723],
					        [#"Returned" = "mm", #"Order ID" = 5526],
					        [#"Returned" = "zip", #"Order ID" = 6763],
					        [#"Returned" = "affordable", #"Order ID" = 1263],
					        [#"Returned" = "selected", #"Order ID" = 2344],
					        [#"Returned" = "rain", #"Order ID" = 3077],
					        [#"Returned" = "serial", #"Order ID" = 5856],
					        [#"Returned" = "scott", #"Order ID" = 3116],
					        [#"Returned" = "director", #"Order ID" = 1537],
					        [#"Returned" = "putting", #"Order ID" = 2638],
					        [#"Returned" = "subscribe", #"Order ID" = 7480],
					        [#"Returned" = "used", #"Order ID" = 1171],
					        [#"Returned" = "creative", #"Order ID" = 3556],
					        [#"Returned" = "roy", #"Order ID" = 3377],
					        [#"Returned" = "forgotten", #"Order ID" = 4314],
					        [#"Returned" = "earned", #"Order ID" = 6935],
					        [#"Returned" = "fan", #"Order ID" = 2875],
					        [#"Returned" = "ep", #"Order ID" = 8525],
					        [#"Returned" = "consumer", #"Order ID" = 8302],
					        [#"Returned" = "chicken", #"Order ID" = 1480],
					        [#"Returned" = "rome", #"Order ID" = 7130],
					        [#"Returned" = "frequency", #"Order ID" = 9180],
					        [#"Returned" = "support", #"Order ID" = 6756],
					        [#"Returned" = "scene", #"Order ID" = 3355],
					        [#"Returned" = "drop", #"Order ID" = 6507],
					        [#"Returned" = "statistics", #"Order ID" = 4856],
					        [#"Returned" = "treat", #"Order ID" = 4974],
					        [#"Returned" = "delta", #"Order ID" = 5266],
					        [#"Returned" = "earth", #"Order ID" = 2086],
					        [#"Returned" = "reason", #"Order ID" = 2479],
					        [#"Returned" = "warehouse", #"Order ID" = 2294],
					        [#"Returned" = "attention", #"Order ID" = 3590],
					        [#"Returned" = "spanish", #"Order ID" = 9339],
					        [#"Returned" = "trial", #"Order ID" = 1183],
					        [#"Returned" = "barry", #"Order ID" = 9948],
					        [#"Returned" = "draft", #"Order ID" = 1954],
					        [#"Returned" = "use", #"Order ID" = 9755],
					        [#"Returned" = "cooperative", #"Order ID" = 8193],
					        [#"Returned" = "fruit", #"Order ID" = 8528],
					        [#"Returned" = "stones", #"Order ID" = 5345],
					        [#"Returned" = "sec", #"Order ID" = 1455],
					        [#"Returned" = "mins", #"Order ID" = 4848],
					        [#"Returned" = "acceptable", #"Order ID" = 9402],
					        [#"Returned" = "taste", #"Order ID" = 4175],
					        [#"Returned" = "archived", #"Order ID" = 7817],
					        [#"Returned" = "bestsellers", #"Order ID" = 7964],
					        [#"Returned" = "bag", #"Order ID" = 5363],
					        [#"Returned" = "girl", #"Order ID" = 2424],
					        [#"Returned" = "family", #"Order ID" = 9401],
					        [#"Returned" = "aged", #"Order ID" = 1117],
					        [#"Returned" = "devel", #"Order ID" = 1342],
					        [#"Returned" = "grey", #"Order ID" = 3531],
					        [#"Returned" = "feeds", #"Order ID" = 3887],
					        [#"Returned" = "seat", #"Order ID" = 9527],
					        [#"Returned" = "graham", #"Order ID" = 2119],
					        [#"Returned" = "interviews", #"Order ID" = 3282],
					        [#"Returned" = "welfare", #"Order ID" = 6848],
					        [#"Returned" = "area", #"Order ID" = 8473],
					        [#"Returned" = "study", #"Order ID" = 5269],
					        [#"Returned" = "tramadol", #"Order ID" = 8173],
					        [#"Returned" = "commissioner", #"Order ID" = 8680],
					        [#"Returned" = "december", #"Order ID" = 2471],
					        [#"Returned" = "concept", #"Order ID" = 8202],
					        [#"Returned" = "symbols", #"Order ID" = 9779],
					        [#"Returned" = "av", #"Order ID" = 5982],
					        [#"Returned" = "est", #"Order ID" = 5243],
					        [#"Returned" = "these", #"Order ID" = 4450],
					        [#"Returned" = "hungary", #"Order ID" = 8304],
					        [#"Returned" = "lincoln", #"Order ID" = 6271],
					        [#"Returned" = "project", #"Order ID" = 3520],
					        [#"Returned" = "afternoon", #"Order ID" = 6805],
					        [#"Returned" = "exceed", #"Order ID" = 9193],
					        [#"Returned" = "go", #"Order ID" = 6236],
					        [#"Returned" = "ssl", #"Order ID" = 4698],
					        [#"Returned" = "independence", #"Order ID" = 9033],
					        [#"Returned" = "parent", #"Order ID" = 2940],
					        [#"Returned" = "least", #"Order ID" = 5766],
					        [#"Returned" = "finland", #"Order ID" = 8050],
					        [#"Returned" = "organizational", #"Order ID" = 4520],
					        [#"Returned" = "zus", #"Order ID" = 2719],
					        [#"Returned" = "wall", #"Order ID" = 4111],
					        [#"Returned" = "final", #"Order ID" = 5911],
					        [#"Returned" = "charged", #"Order ID" = 9164],
					        [#"Returned" = "curve", #"Order ID" = 8679],
					        [#"Returned" = "figure", #"Order ID" = 5032],
					        [#"Returned" = "keith", #"Order ID" = 1599],
					        [#"Returned" = "investments", #"Order ID" = 2231],
					        [#"Returned" = "age", #"Order ID" = 5144],
					        [#"Returned" = "cnet", #"Order ID" = 8866],
					        [#"Returned" = "close", #"Order ID" = 1371],
					        [#"Returned" = "initiative", #"Order ID" = 8307],
					        [#"Returned" = "switch", #"Order ID" = 2503],
					        [#"Returned" = "ships", #"Order ID" = 3736],
					        [#"Returned" = "cotton", #"Order ID" = 3152],
					        [#"Returned" = "pay", #"Order ID" = 8534],
					        [#"Returned" = "engaged", #"Order ID" = 8627],
					        [#"Returned" = "bands", #"Order ID" = 1942],
					        [#"Returned" = "mens", #"Order ID" = 7556],
					        [#"Returned" = "cd", #"Order ID" = 9704],
					        [#"Returned" = "sporting", #"Order ID" = 2636],
					        [#"Returned" = "baker", #"Order ID" = 6512],
					        [#"Returned" = "operation", #"Order ID" = 3424],
					        [#"Returned" = "playstation", #"Order ID" = 3044],
					        [#"Returned" = "binding", #"Order ID" = 8424],
					        [#"Returned" = "draft", #"Order ID" = 5947],
					        [#"Returned" = "spaces", #"Order ID" = 1884],
					        [#"Returned" = "heat", #"Order ID" = 4474],
					        [#"Returned" = "next", #"Order ID" = 4956],
					        [#"Returned" = "eur", #"Order ID" = 5028],
					        [#"Returned" = "studios", #"Order ID" = 2083],
					        [#"Returned" = "election", #"Order ID" = 9162],
					        [#"Returned" = "technical", #"Order ID" = 7414],
					        [#"Returned" = "romance", #"Order ID" = 1181],
					        [#"Returned" = "pretty", #"Order ID" = 9101],
					        [#"Returned" = "look", #"Order ID" = 1703],
					        [#"Returned" = "bell", #"Order ID" = 2779],
					        [#"Returned" = "symbols", #"Order ID" = 7331],
					        [#"Returned" = "organized", #"Order ID" = 6447],
					        [#"Returned" = "lib", #"Order ID" = 3932],
					        [#"Returned" = "distributed", #"Order ID" = 1643],
					        [#"Returned" = "approximately", #"Order ID" = 3545],
					        [#"Returned" = "discs", #"Order ID" = 9538],
					        [#"Returned" = "web", #"Order ID" = 1432],
					        [#"Returned" = "devices", #"Order ID" = 1092],
					        [#"Returned" = "bars", #"Order ID" = 2862],
					        [#"Returned" = "developers", #"Order ID" = 3803],
					        [#"Returned" = "tc", #"Order ID" = 6219],
					        [#"Returned" = "voltage", #"Order ID" = 7200],
					        [#"Returned" = "yards", #"Order ID" = 1359],
					        [#"Returned" = "bowl", #"Order ID" = 5686],
					        [#"Returned" = "train", #"Order ID" = 9830],
					        [#"Returned" = "mixed", #"Order ID" = 8372],
					        [#"Returned" = "proven", #"Order ID" = 2808],
					        [#"Returned" = "welfare", #"Order ID" = 6712],
					        [#"Returned" = "builders", #"Order ID" = 9337],
					        [#"Returned" = "dvds", #"Order ID" = 7407],
					        [#"Returned" = "hearts", #"Order ID" = 3753],
					        [#"Returned" = "tree", #"Order ID" = 4398],
					        [#"Returned" = "lbs", #"Order ID" = 4332],
					        [#"Returned" = "bush", #"Order ID" = 7328],
					        [#"Returned" = "platinum", #"Order ID" = 8736],
					        [#"Returned" = "access", #"Order ID" = 8418],
					        [#"Returned" = "paperback", #"Order ID" = 1000],
					        [#"Returned" = "spears", #"Order ID" = 1505],
					        [#"Returned" = "frames", #"Order ID" = 5055],
					        [#"Returned" = "during", #"Order ID" = 5928],
					        [#"Returned" = "grove", #"Order ID" = 4402],
					        [#"Returned" = "monitors", #"Order ID" = 6722],
					        [#"Returned" = "arab", #"Order ID" = 2727],
					        [#"Returned" = "recorder", #"Order ID" = 5029],
					        [#"Returned" = "beyond", #"Order ID" = 6159],
					        [#"Returned" = "patient", #"Order ID" = 8465],
					        [#"Returned" = "burn", #"Order ID" = 6183],
					        [#"Returned" = "albums", #"Order ID" = 2026],
					        [#"Returned" = "dot", #"Order ID" = 3585],
					        [#"Returned" = "ontario", #"Order ID" = 8405],
					        [#"Returned" = "therefore", #"Order ID" = 6549],
					        [#"Returned" = "far", #"Order ID" = 3404],
					        [#"Returned" = "trademarks", #"Order ID" = 4747],
					        [#"Returned" = "offices", #"Order ID" = 9022],
					        [#"Returned" = "fashion", #"Order ID" = 4752],
					        [#"Returned" = "des", #"Order ID" = 8461],
					        [#"Returned" = "associate", #"Order ID" = 9356],
					        [#"Returned" = "style", #"Order ID" = 5971],
					        [#"Returned" = "liberty", #"Order ID" = 8817],
					        [#"Returned" = "weekend", #"Order ID" = 8420],
					        [#"Returned" = "foot", #"Order ID" = 3663],
					        [#"Returned" = "lessons", #"Order ID" = 2392],
					        [#"Returned" = "pc", #"Order ID" = 2452],
					        [#"Returned" = "linda", #"Order ID" = 2130],
					        [#"Returned" = "dog", #"Order ID" = 3847],
					        [#"Returned" = "property", #"Order ID" = 5727],
					        [#"Returned" = "coverage", #"Order ID" = 3847],
					        [#"Returned" = "margaret", #"Order ID" = 8646],
					        [#"Returned" = "adverse", #"Order ID" = 3476],
					        [#"Returned" = "revenues", #"Order ID" = 7978],
					        [#"Returned" = "markets", #"Order ID" = 5641],
					        [#"Returned" = "somewhere", #"Order ID" = 2205],
					        [#"Returned" = "utc", #"Order ID" = 3202],
					        [#"Returned" = "manage", #"Order ID" = 3587],
					        [#"Returned" = "worst", #"Order ID" = 6537],
					        [#"Returned" = "clock", #"Order ID" = 9929],
					        [#"Returned" = "ones", #"Order ID" = 3060],
					        [#"Returned" = "contracts", #"Order ID" = 6581],
					        [#"Returned" = "spectacular", #"Order ID" = 2322],
					        [#"Returned" = "phentermine", #"Order ID" = 9616],
					        [#"Returned" = "carrying", #"Order ID" = 6032],
					        [#"Returned" = "china", #"Order ID" = 8609],
					        [#"Returned" = "amount", #"Order ID" = 2548],
					        [#"Returned" = "johnson", #"Order ID" = 8201],
					        [#"Returned" = "associate", #"Order ID" = 9723],
					        [#"Returned" = "medication", #"Order ID" = 5140],
					        [#"Returned" = "max", #"Order ID" = 7838],
					        [#"Returned" = "purpose", #"Order ID" = 3881],
					        [#"Returned" = "gonna", #"Order ID" = 1957],
					        [#"Returned" = "spy", #"Order ID" = 7200],
					        [#"Returned" = "electrical", #"Order ID" = 8363],
					        [#"Returned" = "possibly", #"Order ID" = 8220],
					        [#"Returned" = "crack", #"Order ID" = 6596],
					        [#"Returned" = "betting", #"Order ID" = 1275],
					        [#"Returned" = "ordinary", #"Order ID" = 8324],
					        [#"Returned" = "charlotte", #"Order ID" = 4147],
					        [#"Returned" = "looks", #"Order ID" = 4846],
					        [#"Returned" = "those", #"Order ID" = 2556],
					        [#"Returned" = "layer", #"Order ID" = 1318],
					        [#"Returned" = "der", #"Order ID" = 3574],
					        [#"Returned" = "fluid", #"Order ID" = 1195],
					        [#"Returned" = "only", #"Order ID" = 5468],
					        [#"Returned" = "chinese", #"Order ID" = 9102],
					        [#"Returned" = "melbourne", #"Order ID" = 9195],
					        [#"Returned" = "caribbean", #"Order ID" = 4977],
					        [#"Returned" = "delivered", #"Order ID" = 8445],
					        [#"Returned" = "gt", #"Order ID" = 4418],
					        [#"Returned" = "estimated", #"Order ID" = 4458],
					        [#"Returned" = "events", #"Order ID" = 6704],
					        [#"Returned" = "fire", #"Order ID" = 1990],
					        [#"Returned" = "actors", #"Order ID" = 4231],
					        [#"Returned" = "head", #"Order ID" = 5978],
					        [#"Returned" = "basically", #"Order ID" = 8605],
					        [#"Returned" = "saving", #"Order ID" = 3032],
					        [#"Returned" = "text", #"Order ID" = 6487],
					        [#"Returned" = "creating", #"Order ID" = 9968],
					        [#"Returned" = "island", #"Order ID" = 7189],
					        [#"Returned" = "interracial", #"Order ID" = 4709],
					        [#"Returned" = "same", #"Order ID" = 8831],
					        [#"Returned" = "international", #"Order ID" = 4385],
					        [#"Returned" = "singing", #"Order ID" = 1163],
					        [#"Returned" = "forward", #"Order ID" = 1814],
					        [#"Returned" = "suddenly", #"Order ID" = 6735],
					        [#"Returned" = "possible", #"Order ID" = 1943],
					        [#"Returned" = "tells", #"Order ID" = 2606],
					        [#"Returned" = "back", #"Order ID" = 6385],
					        [#"Returned" = "freedom", #"Order ID" = 5855],
					        [#"Returned" = "playing", #"Order ID" = 6953],
					        [#"Returned" = "unique", #"Order ID" = 7540],
					        [#"Returned" = "rule", #"Order ID" = 1798],
					        [#"Returned" = "structural", #"Order ID" = 3537],
					        [#"Returned" = "wednesday", #"Order ID" = 3489],
					        [#"Returned" = "though", #"Order ID" = 8998],
					        [#"Returned" = "raise", #"Order ID" = 2259],
					        [#"Returned" = "hands", #"Order ID" = 2897],
					        [#"Returned" = "hands", #"Order ID" = 7772],
					        [#"Returned" = "bringing", #"Order ID" = 3106],
					        [#"Returned" = "diameter", #"Order ID" = 4569],
					        [#"Returned" = "deluxe", #"Order ID" = 8064],
					        [#"Returned" = "age", #"Order ID" = 1798],
					        [#"Returned" = "thursday", #"Order ID" = 5914],
					        [#"Returned" = "subjects", #"Order ID" = 9722],
					        [#"Returned" = "jose", #"Order ID" = 5390],
					        [#"Returned" = "rest", #"Order ID" = 4632],
					        [#"Returned" = "vermont", #"Order ID" = 6919],
					        [#"Returned" = "relationships", #"Order ID" = 5386],
					        [#"Returned" = "facial", #"Order ID" = 3733],
					        [#"Returned" = "proven", #"Order ID" = 1531],
					        [#"Returned" = "principle", #"Order ID" = 9138],
					        [#"Returned" = "capability", #"Order ID" = 4127],
					        [#"Returned" = "connections", #"Order ID" = 2044],
					        [#"Returned" = "di", #"Order ID" = 9643],
					        [#"Returned" = "requirement", #"Order ID" = 9557],
					        [#"Returned" = "framework", #"Order ID" = 3390],
					        [#"Returned" = "precision", #"Order ID" = 4012],
					        [#"Returned" = "austria", #"Order ID" = 8553],
					        [#"Returned" = "bob", #"Order ID" = 4985],
					        [#"Returned" = "concepts", #"Order ID" = 6636],
					        [#"Returned" = "plasma", #"Order ID" = 6358],
					        [#"Returned" = "ongoing", #"Order ID" = 1688],
					        [#"Returned" = "sl", #"Order ID" = 9325],
					        [#"Returned" = "arc", #"Order ID" = 5676],
					        [#"Returned" = "rings", #"Order ID" = 3359],
					        [#"Returned" = "inkjet", #"Order ID" = 1990],
					        [#"Returned" = "animals", #"Order ID" = 4208],
					        [#"Returned" = "represent", #"Order ID" = 3085],
					        [#"Returned" = "representing", #"Order ID" = 1970],
					        [#"Returned" = "dean", #"Order ID" = 9541],
					        [#"Returned" = "eng", #"Order ID" = 6440],
					        [#"Returned" = "household", #"Order ID" = 2236],
					        [#"Returned" = "bigger", #"Order ID" = 4758],
					        [#"Returned" = "oxygen", #"Order ID" = 1228],
					        [#"Returned" = "authority", #"Order ID" = 2040],
					        [#"Returned" = "structural", #"Order ID" = 9822],
					        [#"Returned" = "stretch", #"Order ID" = 6057],
					        [#"Returned" = "gamma", #"Order ID" = 1553],
					        [#"Returned" = "rings", #"Order ID" = 7395],
					        [#"Returned" = "saint", #"Order ID" = 1448],
					        [#"Returned" = "workshop", #"Order ID" = 5019],
					        [#"Returned" = "normally", #"Order ID" = 5822],
					        [#"Returned" = "franchise", #"Order ID" = 6900],
					        [#"Returned" = "supported", #"Order ID" = 9394],
					        [#"Returned" = "pieces", #"Order ID" = 4425],
					        [#"Returned" = "respectively", #"Order ID" = 2266],
					        [#"Returned" = "winning", #"Order ID" = 5292],
					        [#"Returned" = "tourist", #"Order ID" = 5494],
					        [#"Returned" = "funds", #"Order ID" = 9762],
					        [#"Returned" = "vhs", #"Order ID" = 9046],
					        [#"Returned" = "pound", #"Order ID" = 7966],
					        [#"Returned" = "right", #"Order ID" = 9165],
					        [#"Returned" = "computing", #"Order ID" = 6691],
					        [#"Returned" = "division", #"Order ID" = 4296],
					        [#"Returned" = "both", #"Order ID" = 1111],
					        [#"Returned" = "ref", #"Order ID" = 6311],
					        [#"Returned" = "crown", #"Order ID" = 4692],
					        [#"Returned" = "webmaster", #"Order ID" = 2388],
					        [#"Returned" = "halloween", #"Order ID" = 8019],
					        [#"Returned" = "response", #"Order ID" = 1329],
					        [#"Returned" = "eat", #"Order ID" = 2839],
					        [#"Returned" = "extreme", #"Order ID" = 5934],
					        [#"Returned" = "tin", #"Order ID" = 4239],
					        [#"Returned" = "approval", #"Order ID" = 3571],
					        [#"Returned" = "supplement", #"Order ID" = 9319],
					        [#"Returned" = "popularity", #"Order ID" = 8036],
					        [#"Returned" = "ha", #"Order ID" = 9022],
					        [#"Returned" = "communities", #"Order ID" = 5918],
					        [#"Returned" = "seriously", #"Order ID" = 1362],
					        [#"Returned" = "nike", #"Order ID" = 7082],
					        [#"Returned" = "forced", #"Order ID" = 6841],
					        [#"Returned" = "minor", #"Order ID" = 4545],
					        [#"Returned" = "vector", #"Order ID" = 6842],
					        [#"Returned" = "seems", #"Order ID" = 5453],
					        [#"Returned" = "jpg", #"Order ID" = 5175],
					        [#"Returned" = "ticket", #"Order ID" = 8025],
					        [#"Returned" = "lists", #"Order ID" = 7472],
					        [#"Returned" = "agricultural", #"Order ID" = 4923],
					        [#"Returned" = "thailand", #"Order ID" = 2044],
					        [#"Returned" = "via", #"Order ID" = 7577],
					        [#"Returned" = "eve", #"Order ID" = 9444],
					        [#"Returned" = "suggests", #"Order ID" = 5914],
					        [#"Returned" = "someone", #"Order ID" = 6092],
					        [#"Returned" = "sunset", #"Order ID" = 3796],
					        [#"Returned" = "greece", #"Order ID" = 1145],
					        [#"Returned" = "added", #"Order ID" = 3929],
					        [#"Returned" = "wealth", #"Order ID" = 5712],
					        [#"Returned" = "services", #"Order ID" = 9435],
					        [#"Returned" = "responsible", #"Order ID" = 5098],
					        [#"Returned" = "head", #"Order ID" = 8438],
					        [#"Returned" = "enforcement", #"Order ID" = 3231],
					        [#"Returned" = "vhs", #"Order ID" = 8570],
					        [#"Returned" = "lewis", #"Order ID" = 4597],
					        [#"Returned" = "olympic", #"Order ID" = 1487],
					        [#"Returned" = "panasonic", #"Order ID" = 2279],
					        [#"Returned" = "soil", #"Order ID" = 9970],
					        [#"Returned" = "superior", #"Order ID" = 2402],
					        [#"Returned" = "dvds", #"Order ID" = 1596],
					        [#"Returned" = "hrs", #"Order ID" = 8258],
					        [#"Returned" = "skiing", #"Order ID" = 3580],
					        [#"Returned" = "content", #"Order ID" = 5110],
					        [#"Returned" = "addressed", #"Order ID" = 8885],
					        [#"Returned" = "overnight", #"Order ID" = 3358],
					        [#"Returned" = "towards", #"Order ID" = 3931],
					        [#"Returned" = "walk", #"Order ID" = 9933],
					        [#"Returned" = "happy", #"Order ID" = 2784],
					        [#"Returned" = "their", #"Order ID" = 6431],
					        [#"Returned" = "transition", #"Order ID" = 8014],
					        [#"Returned" = "sizes", #"Order ID" = 1022],
					        [#"Returned" = "dvd", #"Order ID" = 2303],
					        [#"Returned" = "aka", #"Order ID" = 9045],
					        [#"Returned" = "ability", #"Order ID" = 8371],
					        [#"Returned" = "cricket", #"Order ID" = 4428],
					        [#"Returned" = "constitutional", #"Order ID" = 4560],
					        [#"Returned" = "odd", #"Order ID" = 6379],
					        [#"Returned" = "adjusted", #"Order ID" = 8092],
					        [#"Returned" = "skip", #"Order ID" = 7743],
					        [#"Returned" = "announced", #"Order ID" = 8937],
					        [#"Returned" = "rich", #"Order ID" = 3810],
					        [#"Returned" = "generate", #"Order ID" = 8378],
					        [#"Returned" = "culture", #"Order ID" = 1325],
					        [#"Returned" = "oak", #"Order ID" = 4566],
					        [#"Returned" = "variables", #"Order ID" = 5599],
					        [#"Returned" = "minneapolis", #"Order ID" = 6913],
					        [#"Returned" = "game", #"Order ID" = 1370],
					        [#"Returned" = "contractors", #"Order ID" = 1663],
					        [#"Returned" = "genre", #"Order ID" = 1908],
					        [#"Returned" = "dream", #"Order ID" = 3776],
					        [#"Returned" = "td", #"Order ID" = 7031],
					        [#"Returned" = "hb", #"Order ID" = 2445],
					        [#"Returned" = "proteins", #"Order ID" = 8930],
					        [#"Returned" = "acc", #"Order ID" = 4710],
					        [#"Returned" = "electric", #"Order ID" = 5778],
					        [#"Returned" = "team", #"Order ID" = 5493],
					        [#"Returned" = "saint", #"Order ID" = 1239],
					        [#"Returned" = "modem", #"Order ID" = 3761],
					        [#"Returned" = "coupon", #"Order ID" = 5325],
					        [#"Returned" = "doing", #"Order ID" = 1660],
					        [#"Returned" = "utc", #"Order ID" = 2838],
					        [#"Returned" = "oral", #"Order ID" = 5176],
					        [#"Returned" = "jamaica", #"Order ID" = 6973],
					        [#"Returned" = "empty", #"Order ID" = 3455],
					        [#"Returned" = "babies", #"Order ID" = 4157],
					        [#"Returned" = "diabetes", #"Order ID" = 2104],
					        [#"Returned" = "school", #"Order ID" = 7652],
					        [#"Returned" = "zus", #"Order ID" = 3366],
					        [#"Returned" = "cellular", #"Order ID" = 5840],
					        [#"Returned" = "nt", #"Order ID" = 5647],
					        [#"Returned" = "committee", #"Order ID" = 3185],
					        [#"Returned" = "weather", #"Order ID" = 9325],
					        [#"Returned" = "flights", #"Order ID" = 9236],
					        [#"Returned" = "priority", #"Order ID" = 9923],
					        [#"Returned" = "great", #"Order ID" = 3178],
					        [#"Returned" = "range", #"Order ID" = 7782],
					        [#"Returned" = "idaho", #"Order ID" = 9856],
					        [#"Returned" = "que", #"Order ID" = 5067],
					        [#"Returned" = "mall", #"Order ID" = 2658],
					        [#"Returned" = "rich", #"Order ID" = 1512],
					        [#"Returned" = "refer", #"Order ID" = 4410],
					        [#"Returned" = "efficient", #"Order ID" = 3475],
					        [#"Returned" = "relationships", #"Order ID" = 4006],
					        [#"Returned" = "land", #"Order ID" = 7065],
					        [#"Returned" = "declared", #"Order ID" = 9119],
					        [#"Returned" = "remained", #"Order ID" = 1138],
					        [#"Returned" = "vector", #"Order ID" = 5470],
					        [#"Returned" = "achievement", #"Order ID" = 5646],
					        [#"Returned" = "plant", #"Order ID" = 9609],
					        [#"Returned" = "night", #"Order ID" = 1588],
					        [#"Returned" = "turned", #"Order ID" = 3124],
					        [#"Returned" = "jersey", #"Order ID" = 8831],
					        [#"Returned" = "san", #"Order ID" = 4036],
					        [#"Returned" = "gate", #"Order ID" = 8795],
					        [#"Returned" = "packard", #"Order ID" = 2942],
					        [#"Returned" = "xl", #"Order ID" = 3277],
					        [#"Returned" = "jesus", #"Order ID" = 7362],
					        [#"Returned" = "vat", #"Order ID" = 8097],
					        [#"Returned" = "relation", #"Order ID" = 9322],
					        [#"Returned" = "announcements", #"Order ID" = 7780],
					        [#"Returned" = "roads", #"Order ID" = 2515],
					        [#"Returned" = "framed", #"Order ID" = 4935],
					        [#"Returned" = "act", #"Order ID" = 6594],
					        [#"Returned" = "andrew", #"Order ID" = 7872],
					        [#"Returned" = "bar", #"Order ID" = 9948],
					        [#"Returned" = "empty", #"Order ID" = 2404],
					        [#"Returned" = "little", #"Order ID" = 4626],
					        [#"Returned" = "used", #"Order ID" = 9844],
					        [#"Returned" = "cisco", #"Order ID" = 5969],
					        [#"Returned" = "quickly", #"Order ID" = 5572],
					        [#"Returned" = "york", #"Order ID" = 6806],
					        [#"Returned" = "coverage", #"Order ID" = 6241],
					        [#"Returned" = "happen", #"Order ID" = 5634],
					        [#"Returned" = "addresses", #"Order ID" = 8881],
					        [#"Returned" = "rose", #"Order ID" = 7947],
					        [#"Returned" = "product", #"Order ID" = 8386],
					        [#"Returned" = "limit", #"Order ID" = 8767],
					        [#"Returned" = "remained", #"Order ID" = 4023],
					        [#"Returned" = "attributes", #"Order ID" = 9982],
					        [#"Returned" = "enhanced", #"Order ID" = 8652],
					        [#"Returned" = "seeking", #"Order ID" = 2166],
					        [#"Returned" = "athletics", #"Order ID" = 9805],
					        [#"Returned" = "pittsburgh", #"Order ID" = 8962],
					        [#"Returned" = "davis", #"Order ID" = 7907],
					        [#"Returned" = "hd", #"Order ID" = 9599],
					        [#"Returned" = "ray", #"Order ID" = 6733],
					        [#"Returned" = "pollution", #"Order ID" = 9017],
					        [#"Returned" = "palestinian", #"Order ID" = 6669],
					        [#"Returned" = "query", #"Order ID" = 4016],
					        [#"Returned" = "discharge", #"Order ID" = 7780],
					        [#"Returned" = "grey", #"Order ID" = 8246],
					        [#"Returned" = "commercial", #"Order ID" = 1234],
					        [#"Returned" = "brochure", #"Order ID" = 9535],
					        [#"Returned" = "oriented", #"Order ID" = 3431],
					        [#"Returned" = "self", #"Order ID" = 1621],
					        [#"Returned" = "silver", #"Order ID" = 1909],
					        [#"Returned" = "gave", #"Order ID" = 4233],
					        [#"Returned" = "complexity", #"Order ID" = 6436],
					        [#"Returned" = "mins", #"Order ID" = 7947],
					        [#"Returned" = "includes", #"Order ID" = 2209],
					        [#"Returned" = "treated", #"Order ID" = 2987],
					        [#"Returned" = "install", #"Order ID" = 5340],
					        [#"Returned" = "democracy", #"Order ID" = 6658],
					        [#"Returned" = "basically", #"Order ID" = 1098],
					        [#"Returned" = "campbell", #"Order ID" = 7150],
					        [#"Returned" = "diving", #"Order ID" = 1007],
					        [#"Returned" = "chamber", #"Order ID" = 3295],
					        [#"Returned" = "suitable", #"Order ID" = 9315],
					        [#"Returned" = "herald", #"Order ID" = 3127],
					        [#"Returned" = "home", #"Order ID" = 5637],
					        [#"Returned" = "respectively", #"Order ID" = 3046],
					        [#"Returned" = "electronic", #"Order ID" = 3701],
					        [#"Returned" = "schedules", #"Order ID" = 3954],
					        [#"Returned" = "outsourcing", #"Order ID" = 1574],
					        [#"Returned" = "shopping", #"Order ID" = 8500],
					        [#"Returned" = "mod", #"Order ID" = 4581],
					        [#"Returned" = "motorola", #"Order ID" = 1488],
					        [#"Returned" = "ref", #"Order ID" = 4788]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Returned", type text},
					        {"Order ID", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table