table 'Profit Bin Size'
	lineageTag: effb4326-afbc-4872-be95-b21d3a6d7ff2

	measure 'Profit Bin Size Value' = SELECTEDVALUE('Profit Bin Size'[Profit Bin Size], 50)
		lineageTag: 1afd4ca2-e86b-4efb-bb4c-15654f3e4f49

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Profit Bin Size'
		dataType: double
		formatString: 0
		lineageTag: dbc1d3a5-4ee4-436d-b164-8014baea0188
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Profit Bin Size' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_Id = cf6e738ba09d4a5cbc60227bdc0ba0ee

