table 'Sample - Superstore_Returns'
	lineageTag: 85aa3ea7-23ac-4b11-876b-2af72a2e1664

	column 'Order ID'
		dataType: string
		lineageTag: 17483827-3a15-40cc-afb1-438a683cc538
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column Returned
		dataType: string
		lineageTag: 269ade84-5b1d-43a9-825b-50ea059a5683
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	partition 'Sample - Superstore_Returns' = m
		mode: import
		source =
				let
					    Source = Csv.Document(
					        File.Contents("https://saastestlatest.blob.core.windows.net/saas-test-reports/Sample%20-%20Superstore_Returns.csv?se=2025-11-03T18%3A10%3A19Z&sp=r&sv=2025-11-05&sr=b&sig=iPlNWkZh4uWA3oo7GC9TmDUrXz6U4fnnnR/Po3EMzoY%3D"),
					        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
					    ),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Order ID", type text}, {"Returned", type text}})
					in
					    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table