table 'Highlight Parameter'
	lineageTag: 2d7c0f81-1b06-47d4-ba02-0cea130c6787

	measure 'Highlight Parameter Value' = SELECTEDVALUE('Highlight Parameter'[Highlight Parameter], 1.0)
		lineageTag: 1e9d7b5d-cb2b-46f9-b743-ea60a9d03b73

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Highlight Parameter'
		dataType: double
		formatString: 0
		lineageTag: 471f0692-cb14-406f-ad0d-71ddcdc97e1b
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Highlight Parameter' = calculated
		mode: import
		source = GENERATESERIES(1.0, 5.0, 1.0)

	annotation PBI_Id = 27c1b9889783471aa2906dbcf0882177

