table 'Profit Bin Size'
	lineageTag: 11e71faf-274f-4a92-8293-7ba8773a943e

	measure 'Profit Bin Size Value' = SELECTEDVALUE('Profit Bin Size'[Profit Bin Size], 50)
		lineageTag: dfcf18be-9256-430f-96ec-8e97cf10d9f2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Profit Bin Size'
		dataType: double
		formatString: 0
		lineageTag: e4b3a8b3-f969-462b-86ee-bcf360592a78
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Profit Bin Size' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_Id = debf4b5087294922a372188d1d93d7bf

