table 'Product-Sales-Region'
	lineageTag: 4726870c-ef9f-4de5-9ff6-48f840e105fc

	column Date
		dataType: datetime
		lineageTag: 28625581-49c3-4c31-9193-cd266e40321f
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 493f6783-61a2-4798-af9d-8767133b653f
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 9b48e420-9d6c-47ea-a522-418cf09b7fef
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: ef2f4b83-8833-46e1-bdd4-723b25481aa3
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		formatString: General Number
		lineageTag: a339da34-c43e-4611-b2ca-798a31166d3a
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column StoreLocation
		dataType: string
		lineageTag: 71355ea5-1f09-4d93-bb51-b41a689fa423
		summarizeBy: none
		sourceColumn: StoreLocation

		annotation SummarizationSetBy = Automatic

	column CustomerType
		dataType: string
		lineageTag: b691b16b-ba47-4caa-83ed-10e285391cf0
		summarizeBy: none
		sourceColumn: CustomerType

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: General Number
		lineageTag: 5e1b3265-f72c-4f39-bb9f-be69a604f548
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Salesperson
		dataType: string
		lineageTag: c6547df3-d665-4c10-a6fa-6635e8d5a496
		summarizeBy: none
		sourceColumn: Salesperson

		annotation SummarizationSetBy = Automatic

	column TotalPrice
		dataType: double
		formatString: General Number
		lineageTag: ff41b33e-4208-4b36-9235-bc16793f99f0
		summarizeBy: sum
		sourceColumn: TotalPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PaymentMethod
		dataType: string
		lineageTag: 32ddcb73-d0e7-4fd3-8f37-7b959ffd24ce
		summarizeBy: none
		sourceColumn: PaymentMethod

		annotation SummarizationSetBy = Automatic

	column Promotion
		dataType: string
		lineageTag: 7e5cf9fb-5f5e-40ff-a7d3-10ce866bae45
		summarizeBy: none
		sourceColumn: Promotion

		annotation SummarizationSetBy = Automatic

	column Returned
		dataType: int64
		formatString: 0
		lineageTag: 52e24e13-912b-41e5-b19d-4c94bbce3440
		summarizeBy: sum
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column OrderID
		dataType: string
		lineageTag: a096fc3d-157c-41ef-b0ff-afb9dae5f44f
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: 90c471fb-8c1c-4cde-abc6-ea65d1486b65
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column ShippingCost
		dataType: double
		formatString: General Number
		lineageTag: 6e4de57d-c2a8-47d8-8708-3d172c689dee
		summarizeBy: sum
		sourceColumn: ShippingCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderDate
		dataType: datetime
		lineageTag: a633a525-cf37-4e03-898a-79aa830e39b1
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

	column DeliveryDate
		dataType: datetime
		lineageTag: 9e1fc119-1267-409d-bb85-d1401a95cb18
		summarizeBy: none
		sourceColumn: DeliveryDate

		annotation SummarizationSetBy = Automatic

	column RegionManager
		dataType: string
		lineageTag: 0a683106-3ec3-42ad-828a-15b00abd6793
		summarizeBy: none
		sourceColumn: RegionManager

		annotation SummarizationSetBy = Automatic

	column 'New Cust Name' = 'Product-Sales-Region'[CustomerName]
		lineageTag: b1944f60-fb2c-4d40-b014-7d8397bd61e1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Date of Delivery' = 'Product-Sales-Region'[DeliveryDate]
		lineageTag: c04351a2-34b3-42de-b745-a9706a09dae3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Quantity vs Returned' = 'Product-Sales-Region'[Quantity] - 'Product-Sales-Region'[Returned]
		formatString: 0
		lineageTag: fae6354f-fb2b-480a-908d-944bb74f0c5d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Product-Sales-Region' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Date" = #date(2022, 7, 19), #"Region" = "Kentucky", #"Product" = "sh", #"Quantity" = 58, #"UnitPrice" = 973652.42, #"StoreLocation" = "dont", #"CustomerType" = "remains", #"Discount" = 658.93, #"Salesperson" = "prescription", #"TotalPrice" = 863798.81, #"PaymentMethod" = "furthermore", #"Promotion" = "tradition", #"Returned" = 867, #"OrderID" = 1247, #"CustomerName" = "Daniell Mendoza", #"ShippingCost" = 202671.51, #"OrderDate" = #date(2023, 8, 30), #"DeliveryDate" = #date(2024, 7, 28), #"RegionManager" = "New York"],
					        [#"Date" = #date(2024, 5, 22), #"Region" = "California", #"Product" = "isbn", #"Quantity" = 921, #"UnitPrice" = 187437.7, #"StoreLocation" = "represented", #"CustomerType" = "seem", #"Discount" = 441.93, #"Salesperson" = "his", #"TotalPrice" = 520559.67, #"PaymentMethod" = "settings", #"Promotion" = "sized", #"Returned" = 690, #"OrderID" = 4955, #"CustomerName" = "Cedrick Klein", #"ShippingCost" = 47564.81, #"OrderDate" = #date(2023, 7, 17), #"DeliveryDate" = #date(2021, 7, 17), #"RegionManager" = "Florida"],
					        [#"Date" = #date(2021, 5, 26), #"Region" = "Illinois", #"Product" = "successfully", #"Quantity" = 55, #"UnitPrice" = 818390.63, #"StoreLocation" = "bugs", #"CustomerType" = "spring", #"Discount" = 24.83, #"Salesperson" = "proper", #"TotalPrice" = 867041.73, #"PaymentMethod" = "circumstances", #"Promotion" = "aol", #"Returned" = 651, #"OrderID" = 1125, #"CustomerName" = "Wava Coffey", #"ShippingCost" = 262382.02, #"OrderDate" = #date(2020, 9, 29), #"DeliveryDate" = #date(2022, 7, 22), #"RegionManager" = "Alaska"],
					        [#"Date" = #date(2023, 4, 14), #"Region" = "Wyoming", #"Product" = "wales", #"Quantity" = 28, #"UnitPrice" = 574530.57, #"StoreLocation" = "ca", #"CustomerType" = "during", #"Discount" = 565.72, #"Salesperson" = "eu", #"TotalPrice" = 364105.94, #"PaymentMethod" = "increased", #"Promotion" = "coordination", #"Returned" = 362, #"OrderID" = 9300, #"CustomerName" = "Branda Acevedo", #"ShippingCost" = 148917.56, #"OrderDate" = #date(2022, 7, 27), #"DeliveryDate" = #date(2020, 8, 16), #"RegionManager" = "Montana"],
					        [#"Date" = #date(2024, 6, 9), #"Region" = "Kentucky", #"Product" = "speech", #"Quantity" = 820, #"UnitPrice" = 618006.22, #"StoreLocation" = "lowest", #"CustomerType" = "update", #"Discount" = 966.69, #"Salesperson" = "phase", #"TotalPrice" = 666878.28, #"PaymentMethod" = "potentially", #"Promotion" = "engagement", #"Returned" = 308, #"OrderID" = 6992, #"CustomerName" = "Taylor Nash", #"ShippingCost" = 697366.57, #"OrderDate" = #date(2021, 12, 18), #"DeliveryDate" = #date(2023, 8, 23), #"RegionManager" = "Rhode Island"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Date", type date},
					        {"Region", type text},
					        {"Product", type text},
					        {"Quantity", Int64.Type},
					        {"UnitPrice", type number},
					        {"StoreLocation", type text},
					        {"CustomerType", type text},
					        {"Discount", type number},
					        {"Salesperson", type text},
					        {"TotalPrice", type number},
					        {"PaymentMethod", type text},
					        {"Promotion", type text},
					        {"Returned", Int64.Type},
					        {"OrderID", type text},
					        {"CustomerName", type text},
					        {"ShippingCost", type number},
					        {"OrderDate", type date},
					        {"DeliveryDate", type date},
					        {"RegionManager", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table