table 'Linkedin | Demographic Data'
	lineageTag: dc835bba-5e71-4354-9071-b7e5b9fea490

	column 'Top Demographics'
		dataType: string
		lineageTag: 4a35bb6e-9d02-4c18-909a-381cc7002372
		summarizeBy: none
		sourceColumn: 'Top Demographics'

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: string
		lineageTag: d204c200-cff3-4d07-9afb-65baf6e66488
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Percentage
		dataType: double
		formatString: General Number
		lineageTag: 937f53c3-bcea-4551-bbbf-d0b996edd1bd
		summarizeBy: sum
		sourceColumn: Percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Linkedin | Demographic Data' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Top Demographics" = "entirely", #"Value" = "modem", #"Percentage" = 75.44],
					        [#"Top Demographics" = "prepare", #"Value" = "dental", #"Percentage" = 62.58],
					        [#"Top Demographics" = "change", #"Value" = "del", #"Percentage" = 74.23],
					        [#"Top Demographics" = "valuable", #"Value" = "blue", #"Percentage" = 36.73],
					        [#"Top Demographics" = "viewed", #"Value" = "notebook", #"Percentage" = 12.92],
					        [#"Top Demographics" = "hundreds", #"Value" = "tuesday", #"Percentage" = 51.23],
					        [#"Top Demographics" = "consistent", #"Value" = "external", #"Percentage" = 16.64],
					        [#"Top Demographics" = "contribute", #"Value" = "rental", #"Percentage" = 64.08],
					        [#"Top Demographics" = "driver", #"Value" = "daniel", #"Percentage" = 77.27],
					        [#"Top Demographics" = "assurance", #"Value" = "oil", #"Percentage" = 56.96],
					        [#"Top Demographics" = "vast", #"Value" = "contracts", #"Percentage" = 37.97],
					        [#"Top Demographics" = "muslim", #"Value" = "mine", #"Percentage" = 48.5],
					        [#"Top Demographics" = "toner", #"Value" = "receiver", #"Percentage" = 42.2],
					        [#"Top Demographics" = "adult", #"Value" = "overall", #"Percentage" = 76.92],
					        [#"Top Demographics" = "string", #"Value" = "universities", #"Percentage" = 87.14],
					        [#"Top Demographics" = "fund", #"Value" = "agriculture", #"Percentage" = 61.42],
					        [#"Top Demographics" = "odd", #"Value" = "none", #"Percentage" = 4.79],
					        [#"Top Demographics" = "adopt", #"Value" = "offers", #"Percentage" = 93.26],
					        [#"Top Demographics" = "panama", #"Value" = "killer", #"Percentage" = 40.76],
					        [#"Top Demographics" = "liability", #"Value" = "hr", #"Percentage" = 70.49],
					        [#"Top Demographics" = "bank", #"Value" = "adobe", #"Percentage" = 5.21],
					        [#"Top Demographics" = "cables", #"Value" = "activity", #"Percentage" = 77.49],
					        [#"Top Demographics" = "degree", #"Value" = "par", #"Percentage" = 53.93],
					        [#"Top Demographics" = "requires", #"Value" = "latinas", #"Percentage" = 96.99],
					        [#"Top Demographics" = "venezuela", #"Value" = "teach", #"Percentage" = 74.68],
					        [#"Top Demographics" = "accessories", #"Value" = "explained", #"Percentage" = 75.95],
					        [#"Top Demographics" = "loose", #"Value" = "attacks", #"Percentage" = 72.68],
					        [#"Top Demographics" = "aa", #"Value" = "connection", #"Percentage" = 87.73],
					        [#"Top Demographics" = "ahead", #"Value" = "furthermore", #"Percentage" = 83.97],
					        [#"Top Demographics" = "bring", #"Value" = "several", #"Percentage" = 30.23],
					        [#"Top Demographics" = "des", #"Value" = "producing", #"Percentage" = 0.36],
					        [#"Top Demographics" = "refinance", #"Value" = "ph", #"Percentage" = 8.38],
					        [#"Top Demographics" = "forums", #"Value" = "yours", #"Percentage" = 3.11],
					        [#"Top Demographics" = "http", #"Value" = "gardening", #"Percentage" = 63.23],
					        [#"Top Demographics" = "disk", #"Value" = "eggs", #"Percentage" = 95.21],
					        [#"Top Demographics" = "bankruptcy", #"Value" = "bluetooth", #"Percentage" = 0.55],
					        [#"Top Demographics" = "friday", #"Value" = "organized", #"Percentage" = 45.43],
					        [#"Top Demographics" = "shareware", #"Value" = "full", #"Percentage" = 52.65],
					        [#"Top Demographics" = "men", #"Value" = "plays", #"Percentage" = 22.03],
					        [#"Top Demographics" = "theoretical", #"Value" = "messenger", #"Percentage" = 12.74],
					        [#"Top Demographics" = "properties", #"Value" = "pictures", #"Percentage" = 59.17],
					        [#"Top Demographics" = "de", #"Value" = "questions", #"Percentage" = 6.0],
					        [#"Top Demographics" = "parameter", #"Value" = "sciences", #"Percentage" = 68.08],
					        [#"Top Demographics" = "supplied", #"Value" = "participation", #"Percentage" = 77.15],
					        [#"Top Demographics" = "religious", #"Value" = "matching", #"Percentage" = 38.06],
					        [#"Top Demographics" = "con", #"Value" = "kings", #"Percentage" = 24.78],
					        [#"Top Demographics" = "recommendations", #"Value" = "hardcover", #"Percentage" = 5.12],
					        [#"Top Demographics" = "professor", #"Value" = "austria", #"Percentage" = 14.49],
					        [#"Top Demographics" = "oldest", #"Value" = "walking", #"Percentage" = 97.32],
					        [#"Top Demographics" = "pubmed", #"Value" = "independence", #"Percentage" = 50.98],
					        [#"Top Demographics" = "workshop", #"Value" = "compaq", #"Percentage" = 13.57],
					        [#"Top Demographics" = "reply", #"Value" = "sold", #"Percentage" = 56.8],
					        [#"Top Demographics" = "efficient", #"Value" = "use", #"Percentage" = 21.44],
					        [#"Top Demographics" = "attention", #"Value" = "alan", #"Percentage" = 42.99],
					        [#"Top Demographics" = "driver", #"Value" = "laptop", #"Percentage" = 67.36],
					        [#"Top Demographics" = "bc", #"Value" = "overseas", #"Percentage" = 21.58],
					        [#"Top Demographics" = "brings", #"Value" = "wheels", #"Percentage" = 87.55],
					        [#"Top Demographics" = "locked", #"Value" = "efforts", #"Percentage" = 48.47],
					        [#"Top Demographics" = "particularly", #"Value" = "employed", #"Percentage" = 10.74],
					        [#"Top Demographics" = "look", #"Value" = "acute", #"Percentage" = 76.88],
					        [#"Top Demographics" = "outside", #"Value" = "beads", #"Percentage" = 20.87],
					        [#"Top Demographics" = "payable", #"Value" = "everyone", #"Percentage" = 80.4],
					        [#"Top Demographics" = "membership", #"Value" = "involving", #"Percentage" = 88.03],
					        [#"Top Demographics" = "clay", #"Value" = "spray", #"Percentage" = 25.56],
					        [#"Top Demographics" = "kiss", #"Value" = "sequence", #"Percentage" = 66.25],
					        [#"Top Demographics" = "solo", #"Value" = "tel", #"Percentage" = 33.57],
					        [#"Top Demographics" = "entities", #"Value" = "holder", #"Percentage" = 45.71],
					        [#"Top Demographics" = "decor", #"Value" = "fiber", #"Percentage" = 98.82],
					        [#"Top Demographics" = "treated", #"Value" = "led", #"Percentage" = 50.02],
					        [#"Top Demographics" = "murray", #"Value" = "intent", #"Percentage" = 47.77],
					        [#"Top Demographics" = "spy", #"Value" = "mother", #"Percentage" = 17.13],
					        [#"Top Demographics" = "florist", #"Value" = "bb", #"Percentage" = 76.63],
					        [#"Top Demographics" = "outer", #"Value" = "island", #"Percentage" = 60.12],
					        [#"Top Demographics" = "century", #"Value" = "podcast", #"Percentage" = 76.2],
					        [#"Top Demographics" = "self", #"Value" = "expression", #"Percentage" = 96.05],
					        [#"Top Demographics" = "royal", #"Value" = "throat", #"Percentage" = 89.49],
					        [#"Top Demographics" = "proxy", #"Value" = "wife", #"Percentage" = 42.14],
					        [#"Top Demographics" = "denver", #"Value" = "viewing", #"Percentage" = 86.42],
					        [#"Top Demographics" = "therapy", #"Value" = "cancer", #"Percentage" = 2.05],
					        [#"Top Demographics" = "tee", #"Value" = "navigation", #"Percentage" = 96.62],
					        [#"Top Demographics" = "least", #"Value" = "shooting", #"Percentage" = 90.36],
					        [#"Top Demographics" = "derived", #"Value" = "beauty", #"Percentage" = 34.83],
					        [#"Top Demographics" = "supreme", #"Value" = "iowa", #"Percentage" = 70.08],
					        [#"Top Demographics" = "said", #"Value" = "pour", #"Percentage" = 75.24],
					        [#"Top Demographics" = "precision", #"Value" = "legislation", #"Percentage" = 37.86],
					        [#"Top Demographics" = "disposal", #"Value" = "having", #"Percentage" = 19.43],
					        [#"Top Demographics" = "flashing", #"Value" = "newspaper", #"Percentage" = 5.92],
					        [#"Top Demographics" = "gamecube", #"Value" = "someone", #"Percentage" = 18.6],
					        [#"Top Demographics" = "policy", #"Value" = "various", #"Percentage" = 82.14],
					        [#"Top Demographics" = "outer", #"Value" = "monitoring", #"Percentage" = 9.24],
					        [#"Top Demographics" = "goods", #"Value" = "cottage", #"Percentage" = 76.54],
					        [#"Top Demographics" = "charlie", #"Value" = "suggestions", #"Percentage" = 7.63],
					        [#"Top Demographics" = "donate", #"Value" = "ministry", #"Percentage" = 80.52],
					        [#"Top Demographics" = "adventure", #"Value" = "personality", #"Percentage" = 84.5],
					        [#"Top Demographics" = "justice", #"Value" = "producers", #"Percentage" = 49.21],
					        [#"Top Demographics" = "angel", #"Value" = "offers", #"Percentage" = 18.32],
					        [#"Top Demographics" = "jay", #"Value" = "ordinary", #"Percentage" = 92.93],
					        [#"Top Demographics" = "research", #"Value" = "approved", #"Percentage" = 79.64],
					        [#"Top Demographics" = "street", #"Value" = "fred", #"Percentage" = 77.23],
					        [#"Top Demographics" = "probably", #"Value" = "hurricane", #"Percentage" = 33.4],
					        [#"Top Demographics" = "assurance", #"Value" = "davis", #"Percentage" = 64.93],
					        [#"Top Demographics" = "text", #"Value" = "vital", #"Percentage" = 20.1],
					        [#"Top Demographics" = "ask", #"Value" = "junior", #"Percentage" = 31.62],
					        [#"Top Demographics" = "arc", #"Value" = "wooden", #"Percentage" = 13.35],
					        [#"Top Demographics" = "anime", #"Value" = "based", #"Percentage" = 81.17],
					        [#"Top Demographics" = "determine", #"Value" = "centres", #"Percentage" = 81.89],
					        [#"Top Demographics" = "specific", #"Value" = "specialist", #"Percentage" = 32.99],
					        [#"Top Demographics" = "ft", #"Value" = "goals", #"Percentage" = 39.13],
					        [#"Top Demographics" = "situation", #"Value" = "stephen", #"Percentage" = 88.5],
					        [#"Top Demographics" = "checkout", #"Value" = "oil", #"Percentage" = 75.97],
					        [#"Top Demographics" = "resulted", #"Value" = "scene", #"Percentage" = 71.83],
					        [#"Top Demographics" = "lessons", #"Value" = "study", #"Percentage" = 20.65],
					        [#"Top Demographics" = "austria", #"Value" = "username", #"Percentage" = 21.61],
					        [#"Top Demographics" = "mc", #"Value" = "bag", #"Percentage" = 80.84],
					        [#"Top Demographics" = "plug", #"Value" = "growing", #"Percentage" = 42.4],
					        [#"Top Demographics" = "used", #"Value" = "one", #"Percentage" = 8.23],
					        [#"Top Demographics" = "fat", #"Value" = "toyota", #"Percentage" = 69.06],
					        [#"Top Demographics" = "printable", #"Value" = "region", #"Percentage" = 66.69],
					        [#"Top Demographics" = "union", #"Value" = "feeds", #"Percentage" = 77.52],
					        [#"Top Demographics" = "processes", #"Value" = "decades", #"Percentage" = 85.01],
					        [#"Top Demographics" = "emphasis", #"Value" = "occupation", #"Percentage" = 71.97],
					        [#"Top Demographics" = "nearly", #"Value" = "noticed", #"Percentage" = 14.74],
					        [#"Top Demographics" = "falling", #"Value" = "network", #"Percentage" = 44.48],
					        [#"Top Demographics" = "consumption", #"Value" = "hope", #"Percentage" = 63.88],
					        [#"Top Demographics" = "georgia", #"Value" = "collector", #"Percentage" = 69.11],
					        [#"Top Demographics" = "winds", #"Value" = "kansas", #"Percentage" = 72.68],
					        [#"Top Demographics" = "monitor", #"Value" = "kong", #"Percentage" = 82.37],
					        [#"Top Demographics" = "knowledge", #"Value" = "industries", #"Percentage" = 86.87],
					        [#"Top Demographics" = "english", #"Value" = "urban", #"Percentage" = 49.13],
					        [#"Top Demographics" = "group", #"Value" = "feet", #"Percentage" = 83.49],
					        [#"Top Demographics" = "distributor", #"Value" = "allocation", #"Percentage" = 79.19],
					        [#"Top Demographics" = "bankruptcy", #"Value" = "judges", #"Percentage" = 9.56],
					        [#"Top Demographics" = "onto", #"Value" = "taylor", #"Percentage" = 94.44],
					        [#"Top Demographics" = "period", #"Value" = "distance", #"Percentage" = 4.88],
					        [#"Top Demographics" = "employers", #"Value" = "glass", #"Percentage" = 46.91],
					        [#"Top Demographics" = "leg", #"Value" = "llc", #"Percentage" = 76.65],
					        [#"Top Demographics" = "yoga", #"Value" = "fabric", #"Percentage" = 37.01],
					        [#"Top Demographics" = "opposition", #"Value" = "non", #"Percentage" = 76.24],
					        [#"Top Demographics" = "agencies", #"Value" = "stock", #"Percentage" = 18.65],
					        [#"Top Demographics" = "comparison", #"Value" = "complete", #"Percentage" = 1.85],
					        [#"Top Demographics" = "plus", #"Value" = "medical", #"Percentage" = 22.46],
					        [#"Top Demographics" = "senate", #"Value" = "kennedy", #"Percentage" = 32.91],
					        [#"Top Demographics" = "group", #"Value" = "counsel", #"Percentage" = 33.82],
					        [#"Top Demographics" = "highlight", #"Value" = "amsterdam", #"Percentage" = 25.41],
					        [#"Top Demographics" = "outer", #"Value" = "specials", #"Percentage" = 66.55],
					        [#"Top Demographics" = "indianapolis", #"Value" = "fairly", #"Percentage" = 30.26],
					        [#"Top Demographics" = "typically", #"Value" = "gnu", #"Percentage" = 71.53],
					        [#"Top Demographics" = "sd", #"Value" = "experience", #"Percentage" = 36.66],
					        [#"Top Demographics" = "masters", #"Value" = "automation", #"Percentage" = 42.4],
					        [#"Top Demographics" = "disabilities", #"Value" = "joe", #"Percentage" = 1.32],
					        [#"Top Demographics" = "october", #"Value" = "pioneer", #"Percentage" = 68.93],
					        [#"Top Demographics" = "tracks", #"Value" = "two", #"Percentage" = 28.1],
					        [#"Top Demographics" = "binding", #"Value" = "subscription", #"Percentage" = 54.58],
					        [#"Top Demographics" = "hall", #"Value" = "melissa", #"Percentage" = 78.12],
					        [#"Top Demographics" = "tip", #"Value" = "ski", #"Percentage" = 69.96],
					        [#"Top Demographics" = "messaging", #"Value" = "appliances", #"Percentage" = 92.7],
					        [#"Top Demographics" = "not", #"Value" = "oak", #"Percentage" = 27.01],
					        [#"Top Demographics" = "prize", #"Value" = "caught", #"Percentage" = 22.35],
					        [#"Top Demographics" = "push", #"Value" = "handbook", #"Percentage" = 17.62],
					        [#"Top Demographics" = "annual", #"Value" = "python", #"Percentage" = 93.03],
					        [#"Top Demographics" = "theoretical", #"Value" = "pp", #"Percentage" = 2.41],
					        [#"Top Demographics" = "bright", #"Value" = "manhattan", #"Percentage" = 4.18],
					        [#"Top Demographics" = "living", #"Value" = "principal", #"Percentage" = 79.6],
					        [#"Top Demographics" = "kept", #"Value" = "broker", #"Percentage" = 51.44],
					        [#"Top Demographics" = "heroes", #"Value" = "written", #"Percentage" = 28.99],
					        [#"Top Demographics" = "actor", #"Value" = "regulation", #"Percentage" = 91.8],
					        [#"Top Demographics" = "reg", #"Value" = "order", #"Percentage" = 2.19],
					        [#"Top Demographics" = "careers", #"Value" = "epa", #"Percentage" = 21.35],
					        [#"Top Demographics" = "historic", #"Value" = "vi", #"Percentage" = 47.02],
					        [#"Top Demographics" = "cs", #"Value" = "things", #"Percentage" = 8.75],
					        [#"Top Demographics" = "chemicals", #"Value" = "tabs", #"Percentage" = 10.32],
					        [#"Top Demographics" = "francis", #"Value" = "us", #"Percentage" = 26.57],
					        [#"Top Demographics" = "mood", #"Value" = "ask", #"Percentage" = 87.24],
					        [#"Top Demographics" = "extreme", #"Value" = "walker", #"Percentage" = 4.41],
					        [#"Top Demographics" = "contribution", #"Value" = "practical", #"Percentage" = 82.83],
					        [#"Top Demographics" = "tutorial", #"Value" = "pcs", #"Percentage" = 56.07],
					        [#"Top Demographics" = "estate", #"Value" = "anyway", #"Percentage" = 91.43],
					        [#"Top Demographics" = "patient", #"Value" = "commit", #"Percentage" = 73.53],
					        [#"Top Demographics" = "acres", #"Value" = "basin", #"Percentage" = 75.86],
					        [#"Top Demographics" = "graphic", #"Value" = "gaming", #"Percentage" = 46.11],
					        [#"Top Demographics" = "ways", #"Value" = "ideal", #"Percentage" = 90.97],
					        [#"Top Demographics" = "reading", #"Value" = "pink", #"Percentage" = 18.46],
					        [#"Top Demographics" = "arrangements", #"Value" = "palestinian", #"Percentage" = 80.12],
					        [#"Top Demographics" = "pipe", #"Value" = "charges", #"Percentage" = 2.76],
					        [#"Top Demographics" = "oil", #"Value" = "lie", #"Percentage" = 54.11],
					        [#"Top Demographics" = "policy", #"Value" = "checked", #"Percentage" = 5.27],
					        [#"Top Demographics" = "cake", #"Value" = "cap", #"Percentage" = 65.74],
					        [#"Top Demographics" = "market", #"Value" = "beds", #"Percentage" = 95.78],
					        [#"Top Demographics" = "awareness", #"Value" = "legend", #"Percentage" = 14.39],
					        [#"Top Demographics" = "diseases", #"Value" = "council", #"Percentage" = 95.41],
					        [#"Top Demographics" = "drawing", #"Value" = "makes", #"Percentage" = 64.18],
					        [#"Top Demographics" = "surveys", #"Value" = "ford", #"Percentage" = 77.48],
					        [#"Top Demographics" = "corresponding", #"Value" = "bc", #"Percentage" = 31.01],
					        [#"Top Demographics" = "drinking", #"Value" = "bidder", #"Percentage" = 40.41],
					        [#"Top Demographics" = "yours", #"Value" = "john", #"Percentage" = 96.53],
					        [#"Top Demographics" = "properly", #"Value" = "situation", #"Percentage" = 16.17],
					        [#"Top Demographics" = "transformation", #"Value" = "kenya", #"Percentage" = 96.14],
					        [#"Top Demographics" = "afternoon", #"Value" = "academy", #"Percentage" = 46.72],
					        [#"Top Demographics" = "account", #"Value" = "suitable", #"Percentage" = 84.41],
					        [#"Top Demographics" = "applies", #"Value" = "finding", #"Percentage" = 89.9],
					        [#"Top Demographics" = "fighting", #"Value" = "producing", #"Percentage" = 34.79],
					        [#"Top Demographics" = "witness", #"Value" = "part", #"Percentage" = 98.22],
					        [#"Top Demographics" = "earth", #"Value" = "designated", #"Percentage" = 29.24],
					        [#"Top Demographics" = "dynamics", #"Value" = "principles", #"Percentage" = 41.56],
					        [#"Top Demographics" = "diamonds", #"Value" = "replacement", #"Percentage" = 4.73],
					        [#"Top Demographics" = "alcohol", #"Value" = "bidder", #"Percentage" = 69.89],
					        [#"Top Demographics" = "toe", #"Value" = "proxy", #"Percentage" = 90.07],
					        [#"Top Demographics" = "el", #"Value" = "postposted", #"Percentage" = 14.63],
					        [#"Top Demographics" = "queen", #"Value" = "donate", #"Percentage" = 11.76],
					        [#"Top Demographics" = "stages", #"Value" = "dinner", #"Percentage" = 54.2],
					        [#"Top Demographics" = "built", #"Value" = "ne", #"Percentage" = 39.57],
					        [#"Top Demographics" = "breakfast", #"Value" = "herein", #"Percentage" = 33.8],
					        [#"Top Demographics" = "busy", #"Value" = "exhibition", #"Percentage" = 44.24],
					        [#"Top Demographics" = "gifts", #"Value" = "commentary", #"Percentage" = 65.34],
					        [#"Top Demographics" = "sellers", #"Value" = "successful", #"Percentage" = 5.14],
					        [#"Top Demographics" = "follows", #"Value" = "sponsored", #"Percentage" = 23.91],
					        [#"Top Demographics" = "automatic", #"Value" = "industry", #"Percentage" = 45.9],
					        [#"Top Demographics" = "represented", #"Value" = "networking", #"Percentage" = 76.79],
					        [#"Top Demographics" = "colorado", #"Value" = "rice", #"Percentage" = 47.72],
					        [#"Top Demographics" = "milk", #"Value" = "applies", #"Percentage" = 0.15],
					        [#"Top Demographics" = "page", #"Value" = "goals", #"Percentage" = 17.44],
					        [#"Top Demographics" = "constitutional", #"Value" = "formation", #"Percentage" = 16.01],
					        [#"Top Demographics" = "resort", #"Value" = "has", #"Percentage" = 41.28],
					        [#"Top Demographics" = "resulted", #"Value" = "kick", #"Percentage" = 91.95],
					        [#"Top Demographics" = "refund", #"Value" = "challenges", #"Percentage" = 57.21],
					        [#"Top Demographics" = "brochure", #"Value" = "involving", #"Percentage" = 18.37],
					        [#"Top Demographics" = "emphasis", #"Value" = "total", #"Percentage" = 84.54],
					        [#"Top Demographics" = "can", #"Value" = "referred", #"Percentage" = 30.88],
					        [#"Top Demographics" = "tried", #"Value" = "ericsson", #"Percentage" = 53.07],
					        [#"Top Demographics" = "wars", #"Value" = "listen", #"Percentage" = 45.03],
					        [#"Top Demographics" = "sectors", #"Value" = "convenient", #"Percentage" = 82.66],
					        [#"Top Demographics" = "devices", #"Value" = "explains", #"Percentage" = 49.68],
					        [#"Top Demographics" = "listing", #"Value" = "becoming", #"Percentage" = 84.02],
					        [#"Top Demographics" = "ha", #"Value" = "chris", #"Percentage" = 20.32],
					        [#"Top Demographics" = "accuracy", #"Value" = "pdt", #"Percentage" = 30.58],
					        [#"Top Demographics" = "appearance", #"Value" = "person", #"Percentage" = 14.67],
					        [#"Top Demographics" = "senior", #"Value" = "avenue", #"Percentage" = 98.84],
					        [#"Top Demographics" = "answer", #"Value" = "feel", #"Percentage" = 96.29],
					        [#"Top Demographics" = "disc", #"Value" = "sky", #"Percentage" = 46.18],
					        [#"Top Demographics" = "ourselves", #"Value" = "young", #"Percentage" = 95.6],
					        [#"Top Demographics" = "when", #"Value" = "career", #"Percentage" = 94.55],
					        [#"Top Demographics" = "happened", #"Value" = "examples", #"Percentage" = 3.65],
					        [#"Top Demographics" = "clay", #"Value" = "documents", #"Percentage" = 61.01],
					        [#"Top Demographics" = "lewis", #"Value" = "tx", #"Percentage" = 84.59],
					        [#"Top Demographics" = "newspaper", #"Value" = "pantyhose", #"Percentage" = 79.87],
					        [#"Top Demographics" = "zimbabwe", #"Value" = "union", #"Percentage" = 26.91],
					        [#"Top Demographics" = "menu", #"Value" = "oral", #"Percentage" = 0.33],
					        [#"Top Demographics" = "possible", #"Value" = "whom", #"Percentage" = 17.61],
					        [#"Top Demographics" = "voluntary", #"Value" = "topics", #"Percentage" = 92.35],
					        [#"Top Demographics" = "draw", #"Value" = "seconds", #"Percentage" = 40.12],
					        [#"Top Demographics" = "sur", #"Value" = "band", #"Percentage" = 79.04],
					        [#"Top Demographics" = "tips", #"Value" = "populations", #"Percentage" = 27.68],
					        [#"Top Demographics" = "bids", #"Value" = "convenience", #"Percentage" = 97.21],
					        [#"Top Demographics" = "diagnosis", #"Value" = "arab", #"Percentage" = 59.34],
					        [#"Top Demographics" = "success", #"Value" = "trademark", #"Percentage" = 52.75],
					        [#"Top Demographics" = "bidding", #"Value" = "ins", #"Percentage" = 83.29],
					        [#"Top Demographics" = "goal", #"Value" = "eligibility", #"Percentage" = 79.87],
					        [#"Top Demographics" = "response", #"Value" = "melissa", #"Percentage" = 6.1],
					        [#"Top Demographics" = "selection", #"Value" = "antiques", #"Percentage" = 11.99],
					        [#"Top Demographics" = "removal", #"Value" = "antique", #"Percentage" = 48.61],
					        [#"Top Demographics" = "master", #"Value" = "held", #"Percentage" = 43.38],
					        [#"Top Demographics" = "moreover", #"Value" = "replaced", #"Percentage" = 9.91],
					        [#"Top Demographics" = "statement", #"Value" = "ingredients", #"Percentage" = 48.53],
					        [#"Top Demographics" = "concepts", #"Value" = "sat", #"Percentage" = 6.19],
					        [#"Top Demographics" = "guestbook", #"Value" = "poll", #"Percentage" = 12.58],
					        [#"Top Demographics" = "called", #"Value" = "sweden", #"Percentage" = 70.89],
					        [#"Top Demographics" = "client", #"Value" = "void", #"Percentage" = 88.29],
					        [#"Top Demographics" = "philosophy", #"Value" = "error", #"Percentage" = 1.44],
					        [#"Top Demographics" = "busy", #"Value" = "mhz", #"Percentage" = 19.88],
					        [#"Top Demographics" = "priority", #"Value" = "received", #"Percentage" = 78.72],
					        [#"Top Demographics" = "rates", #"Value" = "wells", #"Percentage" = 61.13],
					        [#"Top Demographics" = "certified", #"Value" = "murder", #"Percentage" = 37.23],
					        [#"Top Demographics" = "cream", #"Value" = "canon", #"Percentage" = 87.55],
					        [#"Top Demographics" = "of", #"Value" = "test", #"Percentage" = 62.97],
					        [#"Top Demographics" = "ordinary", #"Value" = "searches", #"Percentage" = 56.21],
					        [#"Top Demographics" = "ing", #"Value" = "bag", #"Percentage" = 34.51],
					        [#"Top Demographics" = "awesome", #"Value" = "empire", #"Percentage" = 15.55],
					        [#"Top Demographics" = "transaction", #"Value" = "roulette", #"Percentage" = 50.0],
					        [#"Top Demographics" = "college", #"Value" = "depends", #"Percentage" = 88.61],
					        [#"Top Demographics" = "columbia", #"Value" = "tagged", #"Percentage" = 5.68],
					        [#"Top Demographics" = "albums", #"Value" = "heat", #"Percentage" = 59.12],
					        [#"Top Demographics" = "transportation", #"Value" = "heavy", #"Percentage" = 10.99],
					        [#"Top Demographics" = "partly", #"Value" = "goals", #"Percentage" = 86.45],
					        [#"Top Demographics" = "russia", #"Value" = "vacuum", #"Percentage" = 11.43],
					        [#"Top Demographics" = "provision", #"Value" = "contents", #"Percentage" = 76.76],
					        [#"Top Demographics" = "distance", #"Value" = "delta", #"Percentage" = 90.04],
					        [#"Top Demographics" = "serial", #"Value" = "court", #"Percentage" = 5.2],
					        [#"Top Demographics" = "voice", #"Value" = "tried", #"Percentage" = 95.45],
					        [#"Top Demographics" = "flower", #"Value" = "grid", #"Percentage" = 56.96],
					        [#"Top Demographics" = "acrobat", #"Value" = "mitchell", #"Percentage" = 75.01],
					        [#"Top Demographics" = "birth", #"Value" = "ill", #"Percentage" = 25.63],
					        [#"Top Demographics" = "enhanced", #"Value" = "tree", #"Percentage" = 6.09],
					        [#"Top Demographics" = "msg", #"Value" = "estimate", #"Percentage" = 8.54],
					        [#"Top Demographics" = "save", #"Value" = "falls", #"Percentage" = 44.63],
					        [#"Top Demographics" = "story", #"Value" = "ex", #"Percentage" = 99.28],
					        [#"Top Demographics" = "phones", #"Value" = "migration", #"Percentage" = 81.43],
					        [#"Top Demographics" = "golf", #"Value" = "scientists", #"Percentage" = 74.81],
					        [#"Top Demographics" = "thus", #"Value" = "consent", #"Percentage" = 99.87],
					        [#"Top Demographics" = "feed", #"Value" = "wood", #"Percentage" = 13.98],
					        [#"Top Demographics" = "hotels", #"Value" = "mini", #"Percentage" = 99.17],
					        [#"Top Demographics" = "quarterly", #"Value" = "pleased", #"Percentage" = 31.81],
					        [#"Top Demographics" = "visual", #"Value" = "videos", #"Percentage" = 71.25],
					        [#"Top Demographics" = "baltimore", #"Value" = "games", #"Percentage" = 66.89],
					        [#"Top Demographics" = "heads", #"Value" = "consistent", #"Percentage" = 9.34],
					        [#"Top Demographics" = "width", #"Value" = "daughter", #"Percentage" = 71.03],
					        [#"Top Demographics" = "moral", #"Value" = "wright", #"Percentage" = 86.9],
					        [#"Top Demographics" = "applications", #"Value" = "populations", #"Percentage" = 31.95],
					        [#"Top Demographics" = "can", #"Value" = "sponsored", #"Percentage" = 88.26],
					        [#"Top Demographics" = "toy", #"Value" = "serious", #"Percentage" = 2.01],
					        [#"Top Demographics" = "gambling", #"Value" = "practice", #"Percentage" = 3.24],
					        [#"Top Demographics" = "overnight", #"Value" = "steven", #"Percentage" = 76.92],
					        [#"Top Demographics" = "glad", #"Value" = "lie", #"Percentage" = 99.04],
					        [#"Top Demographics" = "states", #"Value" = "musical", #"Percentage" = 63.21],
					        [#"Top Demographics" = "hub", #"Value" = "barbara", #"Percentage" = 58.35],
					        [#"Top Demographics" = "enjoyed", #"Value" = "intelligence", #"Percentage" = 38.05],
					        [#"Top Demographics" = "achievement", #"Value" = "new", #"Percentage" = 59.48],
					        [#"Top Demographics" = "vhs", #"Value" = "classroom", #"Percentage" = 67.91],
					        [#"Top Demographics" = "tt", #"Value" = "protected", #"Percentage" = 53.55],
					        [#"Top Demographics" = "producers", #"Value" = "gnome", #"Percentage" = 37.38],
					        [#"Top Demographics" = "crimes", #"Value" = "has", #"Percentage" = 67.91],
					        [#"Top Demographics" = "ma", #"Value" = "jennifer", #"Percentage" = 90.74],
					        [#"Top Demographics" = "performed", #"Value" = "want", #"Percentage" = 93.21],
					        [#"Top Demographics" = "sitemap", #"Value" = "expectations", #"Percentage" = 9.58],
					        [#"Top Demographics" = "servers", #"Value" = "reviewer", #"Percentage" = 18.77],
					        [#"Top Demographics" = "cb", #"Value" = "useful", #"Percentage" = 79.49],
					        [#"Top Demographics" = "horror", #"Value" = "surrounding", #"Percentage" = 25.72],
					        [#"Top Demographics" = "parent", #"Value" = "fm", #"Percentage" = 93.12],
					        [#"Top Demographics" = "sigma", #"Value" = "project", #"Percentage" = 58.53],
					        [#"Top Demographics" = "charity", #"Value" = "printable", #"Percentage" = 65.18],
					        [#"Top Demographics" = "reed", #"Value" = "receives", #"Percentage" = 73.92],
					        [#"Top Demographics" = "speaker", #"Value" = "korea", #"Percentage" = 14.29],
					        [#"Top Demographics" = "marked", #"Value" = "ladies", #"Percentage" = 98.15],
					        [#"Top Demographics" = "retail", #"Value" = "soccer", #"Percentage" = 96.15],
					        [#"Top Demographics" = "update", #"Value" = "factory", #"Percentage" = 12.26],
					        [#"Top Demographics" = "eve", #"Value" = "taking", #"Percentage" = 41.24],
					        [#"Top Demographics" = "eating", #"Value" = "french", #"Percentage" = 0.96],
					        [#"Top Demographics" = "editor", #"Value" = "alan", #"Percentage" = 17.58],
					        [#"Top Demographics" = "voluntary", #"Value" = "pad", #"Percentage" = 89.81],
					        [#"Top Demographics" = "identifying", #"Value" = "sequence", #"Percentage" = 31.96],
					        [#"Top Demographics" = "those", #"Value" = "silk", #"Percentage" = 82.48],
					        [#"Top Demographics" = "sporting", #"Value" = "shopper", #"Percentage" = 78.65],
					        [#"Top Demographics" = "regular", #"Value" = "asian", #"Percentage" = 73.97],
					        [#"Top Demographics" = "music", #"Value" = "consultation", #"Percentage" = 96.15],
					        [#"Top Demographics" = "warren", #"Value" = "rights", #"Percentage" = 64.56],
					        [#"Top Demographics" = "sequences", #"Value" = "court", #"Percentage" = 40.3],
					        [#"Top Demographics" = "existing", #"Value" = "explorer", #"Percentage" = 37.41],
					        [#"Top Demographics" = "resolution", #"Value" = "worry", #"Percentage" = 11.79],
					        [#"Top Demographics" = "examine", #"Value" = "entertainment", #"Percentage" = 52.59],
					        [#"Top Demographics" = "mention", #"Value" = "maintain", #"Percentage" = 81.74],
					        [#"Top Demographics" = "exists", #"Value" = "promise", #"Percentage" = 63.25],
					        [#"Top Demographics" = "nashville", #"Value" = "devel", #"Percentage" = 98.75],
					        [#"Top Demographics" = "tape", #"Value" = "priced", #"Percentage" = 47.96],
					        [#"Top Demographics" = "tripadvisor", #"Value" = "myself", #"Percentage" = 75.24],
					        [#"Top Demographics" = "tree", #"Value" = "seminars", #"Percentage" = 14.87],
					        [#"Top Demographics" = "chinese", #"Value" = "editors", #"Percentage" = 90.39],
					        [#"Top Demographics" = "exciting", #"Value" = "insurance", #"Percentage" = 32.41],
					        [#"Top Demographics" = "partnerships", #"Value" = "definitely", #"Percentage" = 45.15],
					        [#"Top Demographics" = "broadcasting", #"Value" = "motors", #"Percentage" = 36.58],
					        [#"Top Demographics" = "dangerous", #"Value" = "subjects", #"Percentage" = 73.11],
					        [#"Top Demographics" = "disabilities", #"Value" = "unable", #"Percentage" = 62.37],
					        [#"Top Demographics" = "ac", #"Value" = "happen", #"Percentage" = 24.6],
					        [#"Top Demographics" = "german", #"Value" = "cleaner", #"Percentage" = 71.77],
					        [#"Top Demographics" = "worldwide", #"Value" = "kevin", #"Percentage" = 46.82],
					        [#"Top Demographics" = "density", #"Value" = "dawn", #"Percentage" = 25.59],
					        [#"Top Demographics" = "pennsylvania", #"Value" = "suffering", #"Percentage" = 55.66],
					        [#"Top Demographics" = "chi", #"Value" = "alliance", #"Percentage" = 29.59],
					        [#"Top Demographics" = "archived", #"Value" = "entire", #"Percentage" = 57.98],
					        [#"Top Demographics" = "aspect", #"Value" = "columbia", #"Percentage" = 25.55],
					        [#"Top Demographics" = "webcam", #"Value" = "excel", #"Percentage" = 92.02],
					        [#"Top Demographics" = "confirm", #"Value" = "context", #"Percentage" = 24.4],
					        [#"Top Demographics" = "pursuant", #"Value" = "commissioner", #"Percentage" = 28.59],
					        [#"Top Demographics" = "serve", #"Value" = "display", #"Percentage" = 70.81],
					        [#"Top Demographics" = "choices", #"Value" = "province", #"Percentage" = 33.8],
					        [#"Top Demographics" = "subscribe", #"Value" = "christmas", #"Percentage" = 7.76],
					        [#"Top Demographics" = "adam", #"Value" = "explore", #"Percentage" = 79.06],
					        [#"Top Demographics" = "optical", #"Value" = "quite", #"Percentage" = 99.07],
					        [#"Top Demographics" = "vancouver", #"Value" = "arizona", #"Percentage" = 78.55],
					        [#"Top Demographics" = "winds", #"Value" = "ct", #"Percentage" = 32.65],
					        [#"Top Demographics" = "busy", #"Value" = "reviewer", #"Percentage" = 86.02],
					        [#"Top Demographics" = "ultimately", #"Value" = "documentation", #"Percentage" = 60.83],
					        [#"Top Demographics" = "ads", #"Value" = "errors", #"Percentage" = 20.19],
					        [#"Top Demographics" = "tradition", #"Value" = "hazardous", #"Percentage" = 47.74],
					        [#"Top Demographics" = "increasingly", #"Value" = "delete", #"Percentage" = 53.17],
					        [#"Top Demographics" = "straight", #"Value" = "monitors", #"Percentage" = 31.43],
					        [#"Top Demographics" = "stated", #"Value" = "presentations", #"Percentage" = 96.66],
					        [#"Top Demographics" = "roger", #"Value" = "surrounding", #"Percentage" = 83.13],
					        [#"Top Demographics" = "automatic", #"Value" = "commercial", #"Percentage" = 35.38],
					        [#"Top Demographics" = "palace", #"Value" = "activation", #"Percentage" = 53.55],
					        [#"Top Demographics" = "temporary", #"Value" = "permalink", #"Percentage" = 82.22],
					        [#"Top Demographics" = "back", #"Value" = "emergency", #"Percentage" = 44.5],
					        [#"Top Demographics" = "adapter", #"Value" = "jefferson", #"Percentage" = 15.41],
					        [#"Top Demographics" = "maintain", #"Value" = "wv", #"Percentage" = 18.87],
					        [#"Top Demographics" = "pet", #"Value" = "talk", #"Percentage" = 95.75],
					        [#"Top Demographics" = "sight", #"Value" = "explains", #"Percentage" = 3.03],
					        [#"Top Demographics" = "locator", #"Value" = "energy", #"Percentage" = 62.68],
					        [#"Top Demographics" = "never", #"Value" = "goals", #"Percentage" = 91.64],
					        [#"Top Demographics" = "excellent", #"Value" = "employment", #"Percentage" = 38.04],
					        [#"Top Demographics" = "match", #"Value" = "interviews", #"Percentage" = 43.9],
					        [#"Top Demographics" = "products", #"Value" = "controlled", #"Percentage" = 61.12],
					        [#"Top Demographics" = "german", #"Value" = "hats", #"Percentage" = 12.08],
					        [#"Top Demographics" = "menu", #"Value" = "albums", #"Percentage" = 27.22],
					        [#"Top Demographics" = "chocolate", #"Value" = "fe", #"Percentage" = 58.34],
					        [#"Top Demographics" = "pin", #"Value" = "requirement", #"Percentage" = 43.37],
					        [#"Top Demographics" = "placement", #"Value" = "commitment", #"Percentage" = 76.19],
					        [#"Top Demographics" = "eliminate", #"Value" = "development", #"Percentage" = 36.81],
					        [#"Top Demographics" = "true", #"Value" = "acquisition", #"Percentage" = 0.8],
					        [#"Top Demographics" = "become", #"Value" = "wars", #"Percentage" = 4.81],
					        [#"Top Demographics" = "prior", #"Value" = "injuries", #"Percentage" = 66.02],
					        [#"Top Demographics" = "thomas", #"Value" = "bigger", #"Percentage" = 73.25],
					        [#"Top Demographics" = "estimated", #"Value" = "melbourne", #"Percentage" = 25.32],
					        [#"Top Demographics" = "afford", #"Value" = "words", #"Percentage" = 34.92],
					        [#"Top Demographics" = "guardian", #"Value" = "baltimore", #"Percentage" = 24.78],
					        [#"Top Demographics" = "beyond", #"Value" = "college", #"Percentage" = 52.59],
					        [#"Top Demographics" = "rental", #"Value" = "scanner", #"Percentage" = 77.46],
					        [#"Top Demographics" = "resolve", #"Value" = "eric", #"Percentage" = 71.76],
					        [#"Top Demographics" = "bottle", #"Value" = "creator", #"Percentage" = 71.18],
					        [#"Top Demographics" = "by", #"Value" = "fully", #"Percentage" = 54.19],
					        [#"Top Demographics" = "bidder", #"Value" = "portal", #"Percentage" = 65.93],
					        [#"Top Demographics" = "lands", #"Value" = "responsibilities", #"Percentage" = 12.58],
					        [#"Top Demographics" = "jamaica", #"Value" = "specialized", #"Percentage" = 22.91],
					        [#"Top Demographics" = "accident", #"Value" = "advisor", #"Percentage" = 42.01],
					        [#"Top Demographics" = "wrote", #"Value" = "designed", #"Percentage" = 99.71],
					        [#"Top Demographics" = "existence", #"Value" = "animals", #"Percentage" = 0.25],
					        [#"Top Demographics" = "mm", #"Value" = "railway", #"Percentage" = 83.11],
					        [#"Top Demographics" = "indian", #"Value" = "limits", #"Percentage" = 7.79],
					        [#"Top Demographics" = "strategies", #"Value" = "fee", #"Percentage" = 5.53],
					        [#"Top Demographics" = "identify", #"Value" = "genetics", #"Percentage" = 36.54],
					        [#"Top Demographics" = "functions", #"Value" = "stand", #"Percentage" = 66.25],
					        [#"Top Demographics" = "tall", #"Value" = "township", #"Percentage" = 58.82],
					        [#"Top Demographics" = "brings", #"Value" = "holdings", #"Percentage" = 84.48],
					        [#"Top Demographics" = "associated", #"Value" = "eng", #"Percentage" = 46.93],
					        [#"Top Demographics" = "ear", #"Value" = "sacramento", #"Percentage" = 69.96],
					        [#"Top Demographics" = "names", #"Value" = "bring", #"Percentage" = 10.32],
					        [#"Top Demographics" = "top", #"Value" = "father", #"Percentage" = 93.37],
					        [#"Top Demographics" = "font", #"Value" = "companies", #"Percentage" = 71.08],
					        [#"Top Demographics" = "valley", #"Value" = "herein", #"Percentage" = 29.77],
					        [#"Top Demographics" = "units", #"Value" = "supplied", #"Percentage" = 58.49],
					        [#"Top Demographics" = "latinas", #"Value" = "robinson", #"Percentage" = 94.06],
					        [#"Top Demographics" = "subsequent", #"Value" = "principles", #"Percentage" = 16.56],
					        [#"Top Demographics" = "flash", #"Value" = "weekly", #"Percentage" = 45.86],
					        [#"Top Demographics" = "notification", #"Value" = "alphabetical", #"Percentage" = 24.4],
					        [#"Top Demographics" = "trips", #"Value" = "previously", #"Percentage" = 90.89],
					        [#"Top Demographics" = "publish", #"Value" = "citizen", #"Percentage" = 77.18],
					        [#"Top Demographics" = "condition", #"Value" = "items", #"Percentage" = 11.49],
					        [#"Top Demographics" = "perform", #"Value" = "window", #"Percentage" = 2.58],
					        [#"Top Demographics" = "shut", #"Value" = "smile", #"Percentage" = 89.82],
					        [#"Top Demographics" = "fix", #"Value" = "partner", #"Percentage" = 67.25],
					        [#"Top Demographics" = "vision", #"Value" = "ericsson", #"Percentage" = 64.51],
					        [#"Top Demographics" = "ext", #"Value" = "joe", #"Percentage" = 37.12],
					        [#"Top Demographics" = "bid", #"Value" = "comes", #"Percentage" = 61.18],
					        [#"Top Demographics" = "brothers", #"Value" = "it", #"Percentage" = 77.27],
					        [#"Top Demographics" = "broadcast", #"Value" = "boxes", #"Percentage" = 24.0],
					        [#"Top Demographics" = "liquid", #"Value" = "ukraine", #"Percentage" = 24.34],
					        [#"Top Demographics" = "name", #"Value" = "official", #"Percentage" = 42.37],
					        [#"Top Demographics" = "core", #"Value" = "baskets", #"Percentage" = 24.26],
					        [#"Top Demographics" = "stereo", #"Value" = "measurements", #"Percentage" = 13.38],
					        [#"Top Demographics" = "parties", #"Value" = "artificial", #"Percentage" = 80.27],
					        [#"Top Demographics" = "centres", #"Value" = "pdt", #"Percentage" = 12.23],
					        [#"Top Demographics" = "particular", #"Value" = "enter", #"Percentage" = 86.11],
					        [#"Top Demographics" = "lay", #"Value" = "crew", #"Percentage" = 82.55],
					        [#"Top Demographics" = "estate", #"Value" = "present", #"Percentage" = 72.21],
					        [#"Top Demographics" = "hill", #"Value" = "expect", #"Percentage" = 66.98],
					        [#"Top Demographics" = "practical", #"Value" = "zoom", #"Percentage" = 89.08],
					        [#"Top Demographics" = "plants", #"Value" = "personally", #"Percentage" = 91.02],
					        [#"Top Demographics" = "lie", #"Value" = "promote", #"Percentage" = 61.3],
					        [#"Top Demographics" = "languages", #"Value" = "simulation", #"Percentage" = 40.17],
					        [#"Top Demographics" = "arcade", #"Value" = "members", #"Percentage" = 60.92],
					        [#"Top Demographics" = "found", #"Value" = "informed", #"Percentage" = 0.83],
					        [#"Top Demographics" = "joe", #"Value" = "homes", #"Percentage" = 7.75],
					        [#"Top Demographics" = "carefully", #"Value" = "trees", #"Percentage" = 78.71],
					        [#"Top Demographics" = "brief", #"Value" = "steps", #"Percentage" = 12.51],
					        [#"Top Demographics" = "beads", #"Value" = "missing", #"Percentage" = 60.84],
					        [#"Top Demographics" = "agreement", #"Value" = "resolution", #"Percentage" = 34.23],
					        [#"Top Demographics" = "worse", #"Value" = "examined", #"Percentage" = 19.83],
					        [#"Top Demographics" = "display", #"Value" = "applicable", #"Percentage" = 8.94],
					        [#"Top Demographics" = "definition", #"Value" = "marketing", #"Percentage" = 54.38],
					        [#"Top Demographics" = "proven", #"Value" = "moderate", #"Percentage" = 87.69],
					        [#"Top Demographics" = "needs", #"Value" = "coordination", #"Percentage" = 54.59],
					        [#"Top Demographics" = "eventually", #"Value" = "db", #"Percentage" = 88.63],
					        [#"Top Demographics" = "coverage", #"Value" = "income", #"Percentage" = 48.98],
					        [#"Top Demographics" = "measurement", #"Value" = "roof", #"Percentage" = 95.17],
					        [#"Top Demographics" = "nv", #"Value" = "toolbar", #"Percentage" = 23.34],
					        [#"Top Demographics" = "gardening", #"Value" = "usd", #"Percentage" = 49.1],
					        [#"Top Demographics" = "upper", #"Value" = "progress", #"Percentage" = 67.17],
					        [#"Top Demographics" = "registration", #"Value" = "accessories", #"Percentage" = 73.39],
					        [#"Top Demographics" = "acute", #"Value" = "ways", #"Percentage" = 44.69],
					        [#"Top Demographics" = "launch", #"Value" = "lanka", #"Percentage" = 88.46],
					        [#"Top Demographics" = "calculator", #"Value" = "parish", #"Percentage" = 46.39],
					        [#"Top Demographics" = "make", #"Value" = "train", #"Percentage" = 69.5],
					        [#"Top Demographics" = "odd", #"Value" = "rise", #"Percentage" = 0.56],
					        [#"Top Demographics" = "antiques", #"Value" = "forecast", #"Percentage" = 94.32],
					        [#"Top Demographics" = "occurs", #"Value" = "drugs", #"Percentage" = 70.22],
					        [#"Top Demographics" = "union", #"Value" = "hosted", #"Percentage" = 34.36],
					        [#"Top Demographics" = "leisure", #"Value" = "come", #"Percentage" = 45.31],
					        [#"Top Demographics" = "attendance", #"Value" = "instead", #"Percentage" = 9.25],
					        [#"Top Demographics" = "files", #"Value" = "shops", #"Percentage" = 13.64],
					        [#"Top Demographics" = "sigma", #"Value" = "examined", #"Percentage" = 28.54],
					        [#"Top Demographics" = "fonts", #"Value" = "released", #"Percentage" = 17.21],
					        [#"Top Demographics" = "daniel", #"Value" = "evil", #"Percentage" = 60.83],
					        [#"Top Demographics" = "affiliates", #"Value" = "customers", #"Percentage" = 37.28]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Top Demographics", type text},
					        {"Value", type text},
					        {"Percentage", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table