table 'Orders (Sample - Superstore (1))'
	lineageTag: f97524e7-fbfe-4cbf-8ed0-20c42443fd06

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 573f60fd-b922-42ca-908d-aa3d9a36a7b7
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 52bfc1d8-3013-45af-919e-c036239a62fd
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: datetime
		lineageTag: 25f5205e-0268-495c-9abc-c7e14694f999
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: datetime
		lineageTag: 04def4c7-27f4-4161-9458-2def60618fa3
		summarizeBy: none
		sourceColumn: 'Ship Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 12a6f088-1f40-4be2-8c33-269c41aa5438
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 144aaf39-ac0c-4db2-918e-98ac6afe4e53
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 081f19e0-d9c9-4957-a313-e103b3b48dce
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 99995816-1b54-4f82-bab8-cc43bb36ee70
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: e65c5461-1e82-4f63-9f02-c3b592a6a98e
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: d5f88da9-4ba1-4d57-b04d-2a408a4a7352
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 7e4cfabd-87d5-4f4d-8ea9-6e3f9be69bbb
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 08612972-c297-4461-aff1-96d6ab408871
		summarizeBy: sum
		sourceColumn: 'Postal Code'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 1e3e4ad1-8170-4bca-bfbe-747803ef2ee0
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: dacf2966-3f7a-49a1-b2dd-4e85baa892aa
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 2f298bdf-bcf7-4b16-9a68-dfb34d7b5e9d
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: 25f9b098-ddd2-4ff0-8ef0-0e77119586be
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 244f3cc8-f27d-4cff-a3bf-e7e362cc2564
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: General Number
		lineageTag: 341ca9ae-a33a-4722-bd7d-d9aa7d198982
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: cce8ce03-4864-42a5-88cb-8817899b9a88
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: General Number
		lineageTag: 1aa4d6c9-08a6-4e94-baff-669b7edeb17d
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		formatString: General Number
		lineageTag: 2fdbb3ac-2254-4cad-b2f6-0e04032466e7
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Calculation1 = SWITCH(TRUE(), 'Orders (Sample - Superstore (1))'[Category] = "Furniture", "furniture", 'Orders (Sample - Superstore (1))'[Category] = "Office Supplies", "office supplier", 'Orders (Sample - Superstore (1))'[Category] = "Technology", "technology", 'Orders (Sample - Superstore (1))'[Category] )
		lineageTag: 61bd09a3-9ec3-4e90-a990-0b526b4f2a5d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Orders (Sample - Superstore (1))' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Row ID" = 8119, #"Order ID" = 1373, #"Order Date" = #date(2022, 12, 7), #"Ship Date" = #date(2022, 6, 6), #"Ship Mode" = "63.212.154.248", #"Customer ID" = 7471, #"Customer Name" = "Charlesetta Velez", #"Segment" = "act", #"Country" = "Costa Rica", #"City" = "Hawthorne", #"State" = "Florida", #"Postal Code" = 922, #"Region" = "New Mexico", #"Product ID" = 2358, #"Category" = "revealed", #"Sub-Category" = "severe", #"Product Name" = "Hayden Morgan", #"Sales" = 748.01, #"Quantity" = 331, #"Discount" = 584.38, #"Profit" = 536.37],
					        [#"Row ID" = 9427, #"Order ID" = 4434, #"Order Date" = #date(2024, 11, 3), #"Ship Date" = #date(2021, 4, 12), #"Ship Mode" = "4.58.178.205", #"Customer ID" = 2102, #"Customer Name" = "Harlan Murphy", #"Segment" = "of", #"Country" = "Seychelles", #"City" = "Hot Springs", #"State" = "Idaho", #"Postal Code" = 426, #"Region" = "Kansas", #"Product ID" = 9364, #"Category" = "checks", #"Sub-Category" = "automatic", #"Product Name" = "Hedy Shields", #"Sales" = 530.72, #"Quantity" = 841, #"Discount" = 974.96, #"Profit" = 98.23],
					        [#"Row ID" = 4444, #"Order ID" = 3728, #"Order Date" = #date(2020, 8, 10), #"Ship Date" = #date(2022, 3, 3), #"Ship Mode" = "33.241.81.240", #"Customer ID" = 9864, #"Customer Name" = "Mckinley Daniels", #"Segment" = "tu", #"Country" = "Fiji", #"City" = "Orange", #"State" = "Montana", #"Postal Code" = 625, #"Region" = "Mississippi", #"Product ID" = 2222, #"Category" = "chest", #"Sub-Category" = "tables", #"Product Name" = "Ardelia Robbins", #"Sales" = 286.68, #"Quantity" = 76, #"Discount" = 964.37, #"Profit" = 750.37],
					        [#"Row ID" = 3311, #"Order ID" = 3984, #"Order Date" = #date(2023, 3, 5), #"Ship Date" = #date(2024, 6, 9), #"Ship Mode" = "122.37.205.78", #"Customer ID" = 2039, #"Customer Name" = "Sherlene Johnston", #"Segment" = "allow", #"Country" = "Colombia", #"City" = "Jacksonville", #"State" = "Delaware", #"Postal Code" = 277, #"Region" = "Nebraska", #"Product ID" = 3077, #"Category" = "electrical", #"Sub-Category" = "environment", #"Product Name" = "Sook Fuller", #"Sales" = 427.94, #"Quantity" = 975, #"Discount" = 80.12, #"Profit" = 52.79],
					        [#"Row ID" = 701, #"Order ID" = 9658, #"Order Date" = #date(2021, 5, 24), #"Ship Date" = #date(2023, 10, 16), #"Ship Mode" = "225.155.131.53", #"Customer ID" = 7211, #"Customer Name" = "Morris Sanders", #"Segment" = "ms", #"Country" = "Russia", #"City" = "Hurst", #"State" = "New Jersey", #"Postal Code" = 571, #"Region" = "Maine", #"Product ID" = 9136, #"Category" = "ordering", #"Sub-Category" = "accounts", #"Product Name" = "Luis Figueroa", #"Sales" = 858.36, #"Quantity" = 803, #"Discount" = 113.94, #"Profit" = 339.74]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Row ID", Int64.Type},
					        {"Order ID", type text},
					        {"Order Date", type date},
					        {"Ship Date", type date},
					        {"Ship Mode", type text},
					        {"Customer ID", type text},
					        {"Customer Name", type text},
					        {"Segment", type text},
					        {"Country", type text},
					        {"City", type text},
					        {"State", type text},
					        {"Postal Code", Int64.Type},
					        {"Region", type text},
					        {"Product ID", type text},
					        {"Category", type text},
					        {"Sub-Category", type text},
					        {"Product Name", type text},
					        {"Sales", type number},
					        {"Quantity", Int64.Type},
					        {"Discount", type number},
					        {"Profit", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table