table 'AgeGroupDetails.csv_AgeGroupDetails'
	lineageTag: eac6d9cc-9908-40cd-8ca6-ab9774df78a7

	column Sno
		dataType: int64
		formatString: 0
		lineageTag: 3826ec5f-e099-49ef-9dd4-b2f52e8802a1
		summarizeBy: sum
		sourceColumn: Sno

		annotation SummarizationSetBy = Automatic

	column AgeGroup
		dataType: string
		lineageTag: e7b7466b-97f6-49d1-b8f1-3689735320f2
		summarizeBy: none
		sourceColumn: AgeGroup

		annotation SummarizationSetBy = Automatic

	column TotalCases
		dataType: int64
		formatString: 0
		lineageTag: d5c3229f-4ff6-4d06-8919-c4e153177f3c
		summarizeBy: sum
		sourceColumn: TotalCases

		annotation SummarizationSetBy = Automatic

	column Percentage
		dataType: double
		formatString: General Number
		lineageTag: aaa0d141-753c-40a3-9710-d31def738f7e
		summarizeBy: sum
		sourceColumn: Percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'AgeGroupDetails.csv_AgeGroupDetails' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Sno" = 552, #"AgeGroup" = 53, #"TotalCases" = 310, #"Percentage" = 90.06],
					        [#"Sno" = 517, #"AgeGroup" = 39, #"TotalCases" = 460, #"Percentage" = 15.59],
					        [#"Sno" = 389, #"AgeGroup" = 61, #"TotalCases" = 545, #"Percentage" = 55.29],
					        [#"Sno" = 541, #"AgeGroup" = 38, #"TotalCases" = 249, #"Percentage" = 0.89],
					        [#"Sno" = 953, #"AgeGroup" = 80, #"TotalCases" = 49, #"Percentage" = 50.76],
					        [#"Sno" = 378, #"AgeGroup" = 32, #"TotalCases" = 529, #"Percentage" = 79.79],
					        [#"Sno" = 483, #"AgeGroup" = 72, #"TotalCases" = 632, #"Percentage" = 71.97],
					        [#"Sno" = 378, #"AgeGroup" = 48, #"TotalCases" = 835, #"Percentage" = 21.14],
					        [#"Sno" = 468, #"AgeGroup" = 66, #"TotalCases" = 831, #"Percentage" = 1.76],
					        [#"Sno" = 863, #"AgeGroup" = 68, #"TotalCases" = 82, #"Percentage" = 20.94],
					        [#"Sno" = 725, #"AgeGroup" = 76, #"TotalCases" = 237, #"Percentage" = 20.76],
					        [#"Sno" = 972, #"AgeGroup" = 62, #"TotalCases" = 386, #"Percentage" = 11.38],
					        [#"Sno" = 175, #"AgeGroup" = 42, #"TotalCases" = 253, #"Percentage" = 23.4],
					        [#"Sno" = 5, #"AgeGroup" = 62, #"TotalCases" = 300, #"Percentage" = 6.3],
					        [#"Sno" = 952, #"AgeGroup" = 27, #"TotalCases" = 102, #"Percentage" = 31.96],
					        [#"Sno" = 208, #"AgeGroup" = 55, #"TotalCases" = 597, #"Percentage" = 79.54],
					        [#"Sno" = 398, #"AgeGroup" = 22, #"TotalCases" = 408, #"Percentage" = 3.24],
					        [#"Sno" = 332, #"AgeGroup" = 69, #"TotalCases" = 711, #"Percentage" = 16.92],
					        [#"Sno" = 304, #"AgeGroup" = 77, #"TotalCases" = 134, #"Percentage" = 95.4],
					        [#"Sno" = 61, #"AgeGroup" = 39, #"TotalCases" = 113, #"Percentage" = 2.64],
					        [#"Sno" = 189, #"AgeGroup" = 69, #"TotalCases" = 148, #"Percentage" = 30.88],
					        [#"Sno" = 395, #"AgeGroup" = 49, #"TotalCases" = 35, #"Percentage" = 70.37],
					        [#"Sno" = 336, #"AgeGroup" = 24, #"TotalCases" = 301, #"Percentage" = 64.34],
					        [#"Sno" = 869, #"AgeGroup" = 55, #"TotalCases" = 615, #"Percentage" = 70.49],
					        [#"Sno" = 680, #"AgeGroup" = 35, #"TotalCases" = 712, #"Percentage" = 92.52],
					        [#"Sno" = 712, #"AgeGroup" = 51, #"TotalCases" = 977, #"Percentage" = 20.54],
					        [#"Sno" = 919, #"AgeGroup" = 79, #"TotalCases" = 363, #"Percentage" = 36.38],
					        [#"Sno" = 379, #"AgeGroup" = 40, #"TotalCases" = 674, #"Percentage" = 10.81],
					        [#"Sno" = 439, #"AgeGroup" = 54, #"TotalCases" = 230, #"Percentage" = 41.73],
					        [#"Sno" = 934, #"AgeGroup" = 40, #"TotalCases" = 131, #"Percentage" = 34.34],
					        [#"Sno" = 427, #"AgeGroup" = 29, #"TotalCases" = 652, #"Percentage" = 87.56],
					        [#"Sno" = 187, #"AgeGroup" = 32, #"TotalCases" = 715, #"Percentage" = 92.5],
					        [#"Sno" = 394, #"AgeGroup" = 58, #"TotalCases" = 449, #"Percentage" = 22.85],
					        [#"Sno" = 536, #"AgeGroup" = 79, #"TotalCases" = 945, #"Percentage" = 96.41],
					        [#"Sno" = 915, #"AgeGroup" = 23, #"TotalCases" = 600, #"Percentage" = 94.62],
					        [#"Sno" = 478, #"AgeGroup" = 25, #"TotalCases" = 330, #"Percentage" = 26.21],
					        [#"Sno" = 591, #"AgeGroup" = 68, #"TotalCases" = 676, #"Percentage" = 21.07],
					        [#"Sno" = 886, #"AgeGroup" = 33, #"TotalCases" = 345, #"Percentage" = 63.37],
					        [#"Sno" = 190, #"AgeGroup" = 61, #"TotalCases" = 470, #"Percentage" = 71.94],
					        [#"Sno" = 197, #"AgeGroup" = 37, #"TotalCases" = 296, #"Percentage" = 26.78],
					        [#"Sno" = 378, #"AgeGroup" = 74, #"TotalCases" = 560, #"Percentage" = 31.85],
					        [#"Sno" = 288, #"AgeGroup" = 34, #"TotalCases" = 577, #"Percentage" = 26.02],
					        [#"Sno" = 267, #"AgeGroup" = 76, #"TotalCases" = 47, #"Percentage" = 26.68],
					        [#"Sno" = 168, #"AgeGroup" = 60, #"TotalCases" = 816, #"Percentage" = 4.11],
					        [#"Sno" = 802, #"AgeGroup" = 78, #"TotalCases" = 880, #"Percentage" = 50.52],
					        [#"Sno" = 791, #"AgeGroup" = 72, #"TotalCases" = 943, #"Percentage" = 73.15],
					        [#"Sno" = 83, #"AgeGroup" = 74, #"TotalCases" = 759, #"Percentage" = 22.74],
					        [#"Sno" = 959, #"AgeGroup" = 56, #"TotalCases" = 530, #"Percentage" = 27.94],
					        [#"Sno" = 113, #"AgeGroup" = 58, #"TotalCases" = 787, #"Percentage" = 6.06],
					        [#"Sno" = 670, #"AgeGroup" = 47, #"TotalCases" = 147, #"Percentage" = 84.28],
					        [#"Sno" = 766, #"AgeGroup" = 29, #"TotalCases" = 50, #"Percentage" = 26.88],
					        [#"Sno" = 187, #"AgeGroup" = 61, #"TotalCases" = 495, #"Percentage" = 91.02],
					        [#"Sno" = 983, #"AgeGroup" = 56, #"TotalCases" = 677, #"Percentage" = 36.41],
					        [#"Sno" = 796, #"AgeGroup" = 67, #"TotalCases" = 210, #"Percentage" = 90.96],
					        [#"Sno" = 651, #"AgeGroup" = 30, #"TotalCases" = 546, #"Percentage" = 58.47],
					        [#"Sno" = 477, #"AgeGroup" = 66, #"TotalCases" = 816, #"Percentage" = 29.35],
					        [#"Sno" = 980, #"AgeGroup" = 29, #"TotalCases" = 857, #"Percentage" = 77.07],
					        [#"Sno" = 854, #"AgeGroup" = 20, #"TotalCases" = 277, #"Percentage" = 54.96],
					        [#"Sno" = 164, #"AgeGroup" = 38, #"TotalCases" = 101, #"Percentage" = 13.8],
					        [#"Sno" = 347, #"AgeGroup" = 70, #"TotalCases" = 665, #"Percentage" = 87.67],
					        [#"Sno" = 528, #"AgeGroup" = 72, #"TotalCases" = 679, #"Percentage" = 63.51],
					        [#"Sno" = 330, #"AgeGroup" = 46, #"TotalCases" = 593, #"Percentage" = 9.34],
					        [#"Sno" = 583, #"AgeGroup" = 60, #"TotalCases" = 442, #"Percentage" = 10.52],
					        [#"Sno" = 77, #"AgeGroup" = 35, #"TotalCases" = 254, #"Percentage" = 55.71],
					        [#"Sno" = 957, #"AgeGroup" = 67, #"TotalCases" = 45, #"Percentage" = 86.41],
					        [#"Sno" = 578, #"AgeGroup" = 65, #"TotalCases" = 977, #"Percentage" = 18.34],
					        [#"Sno" = 540, #"AgeGroup" = 77, #"TotalCases" = 316, #"Percentage" = 35.78],
					        [#"Sno" = 679, #"AgeGroup" = 45, #"TotalCases" = 852, #"Percentage" = 87.4],
					        [#"Sno" = 655, #"AgeGroup" = 57, #"TotalCases" = 380, #"Percentage" = 15.57],
					        [#"Sno" = 83, #"AgeGroup" = 45, #"TotalCases" = 126, #"Percentage" = 61.21],
					        [#"Sno" = 325, #"AgeGroup" = 61, #"TotalCases" = 694, #"Percentage" = 4.2],
					        [#"Sno" = 728, #"AgeGroup" = 39, #"TotalCases" = 420, #"Percentage" = 61.44],
					        [#"Sno" = 371, #"AgeGroup" = 37, #"TotalCases" = 929, #"Percentage" = 32.77],
					        [#"Sno" = 498, #"AgeGroup" = 19, #"TotalCases" = 132, #"Percentage" = 38.28],
					        [#"Sno" = 59, #"AgeGroup" = 66, #"TotalCases" = 245, #"Percentage" = 60.72],
					        [#"Sno" = 449, #"AgeGroup" = 65, #"TotalCases" = 188, #"Percentage" = 9.45],
					        [#"Sno" = 136, #"AgeGroup" = 48, #"TotalCases" = 649, #"Percentage" = 54.06],
					        [#"Sno" = 934, #"AgeGroup" = 26, #"TotalCases" = 465, #"Percentage" = 29.81],
					        [#"Sno" = 724, #"AgeGroup" = 54, #"TotalCases" = 59, #"Percentage" = 74.17],
					        [#"Sno" = 796, #"AgeGroup" = 25, #"TotalCases" = 991, #"Percentage" = 28.46],
					        [#"Sno" = 157, #"AgeGroup" = 45, #"TotalCases" = 883, #"Percentage" = 25.86],
					        [#"Sno" = 528, #"AgeGroup" = 68, #"TotalCases" = 228, #"Percentage" = 54.29],
					        [#"Sno" = 420, #"AgeGroup" = 43, #"TotalCases" = 736, #"Percentage" = 51.92],
					        [#"Sno" = 177, #"AgeGroup" = 73, #"TotalCases" = 947, #"Percentage" = 77.72],
					        [#"Sno" = 185, #"AgeGroup" = 56, #"TotalCases" = 548, #"Percentage" = 93.35],
					        [#"Sno" = 370, #"AgeGroup" = 55, #"TotalCases" = 634, #"Percentage" = 50.45],
					        [#"Sno" = 870, #"AgeGroup" = 43, #"TotalCases" = 595, #"Percentage" = 12.92],
					        [#"Sno" = 239, #"AgeGroup" = 80, #"TotalCases" = 724, #"Percentage" = 64.89],
					        [#"Sno" = 419, #"AgeGroup" = 73, #"TotalCases" = 380, #"Percentage" = 57.64],
					        [#"Sno" = 371, #"AgeGroup" = 73, #"TotalCases" = 142, #"Percentage" = 17.77],
					        [#"Sno" = 286, #"AgeGroup" = 39, #"TotalCases" = 1, #"Percentage" = 91.74],
					        [#"Sno" = 34, #"AgeGroup" = 57, #"TotalCases" = 720, #"Percentage" = 33.5],
					        [#"Sno" = 813, #"AgeGroup" = 43, #"TotalCases" = 959, #"Percentage" = 11.72],
					        [#"Sno" = 5, #"AgeGroup" = 35, #"TotalCases" = 303, #"Percentage" = 65.02],
					        [#"Sno" = 208, #"AgeGroup" = 18, #"TotalCases" = 883, #"Percentage" = 86.18],
					        [#"Sno" = 18, #"AgeGroup" = 27, #"TotalCases" = 390, #"Percentage" = 21.26],
					        [#"Sno" = 702, #"AgeGroup" = 18, #"TotalCases" = 143, #"Percentage" = 52.11],
					        [#"Sno" = 322, #"AgeGroup" = 36, #"TotalCases" = 218, #"Percentage" = 4.93],
					        [#"Sno" = 433, #"AgeGroup" = 68, #"TotalCases" = 874, #"Percentage" = 57.3],
					        [#"Sno" = 641, #"AgeGroup" = 23, #"TotalCases" = 89, #"Percentage" = 42.47],
					        [#"Sno" = 156, #"AgeGroup" = 47, #"TotalCases" = 563, #"Percentage" = 36.42],
					        [#"Sno" = 375, #"AgeGroup" = 72, #"TotalCases" = 864, #"Percentage" = 75.83],
					        [#"Sno" = 51, #"AgeGroup" = 39, #"TotalCases" = 893, #"Percentage" = 49.79],
					        [#"Sno" = 890, #"AgeGroup" = 63, #"TotalCases" = 773, #"Percentage" = 60.37],
					        [#"Sno" = 922, #"AgeGroup" = 32, #"TotalCases" = 798, #"Percentage" = 55.6],
					        [#"Sno" = 909, #"AgeGroup" = 36, #"TotalCases" = 376, #"Percentage" = 18.34],
					        [#"Sno" = 519, #"AgeGroup" = 76, #"TotalCases" = 397, #"Percentage" = 51.46],
					        [#"Sno" = 429, #"AgeGroup" = 22, #"TotalCases" = 736, #"Percentage" = 46.7],
					        [#"Sno" = 976, #"AgeGroup" = 60, #"TotalCases" = 28, #"Percentage" = 49.29],
					        [#"Sno" = 944, #"AgeGroup" = 53, #"TotalCases" = 974, #"Percentage" = 17.34],
					        [#"Sno" = 756, #"AgeGroup" = 50, #"TotalCases" = 262, #"Percentage" = 33.63],
					        [#"Sno" = 663, #"AgeGroup" = 78, #"TotalCases" = 910, #"Percentage" = 10.09],
					        [#"Sno" = 353, #"AgeGroup" = 80, #"TotalCases" = 309, #"Percentage" = 49.54],
					        [#"Sno" = 41, #"AgeGroup" = 28, #"TotalCases" = 328, #"Percentage" = 42.51],
					        [#"Sno" = 205, #"AgeGroup" = 40, #"TotalCases" = 18, #"Percentage" = 75.42],
					        [#"Sno" = 760, #"AgeGroup" = 65, #"TotalCases" = 7, #"Percentage" = 99.96],
					        [#"Sno" = 474, #"AgeGroup" = 62, #"TotalCases" = 806, #"Percentage" = 87.73],
					        [#"Sno" = 187, #"AgeGroup" = 19, #"TotalCases" = 123, #"Percentage" = 20.56],
					        [#"Sno" = 267, #"AgeGroup" = 21, #"TotalCases" = 706, #"Percentage" = 34.58],
					        [#"Sno" = 345, #"AgeGroup" = 37, #"TotalCases" = 176, #"Percentage" = 41.89],
					        [#"Sno" = 339, #"AgeGroup" = 18, #"TotalCases" = 488, #"Percentage" = 98.91],
					        [#"Sno" = 197, #"AgeGroup" = 46, #"TotalCases" = 901, #"Percentage" = 25.69],
					        [#"Sno" = 378, #"AgeGroup" = 27, #"TotalCases" = 282, #"Percentage" = 42.97],
					        [#"Sno" = 289, #"AgeGroup" = 75, #"TotalCases" = 922, #"Percentage" = 11.3],
					        [#"Sno" = 245, #"AgeGroup" = 66, #"TotalCases" = 84, #"Percentage" = 13.71],
					        [#"Sno" = 210, #"AgeGroup" = 69, #"TotalCases" = 176, #"Percentage" = 55.67],
					        [#"Sno" = 624, #"AgeGroup" = 74, #"TotalCases" = 803, #"Percentage" = 2.68],
					        [#"Sno" = 302, #"AgeGroup" = 68, #"TotalCases" = 778, #"Percentage" = 20.86],
					        [#"Sno" = 752, #"AgeGroup" = 23, #"TotalCases" = 349, #"Percentage" = 79.47],
					        [#"Sno" = 65, #"AgeGroup" = 73, #"TotalCases" = 48, #"Percentage" = 67.06],
					        [#"Sno" = 853, #"AgeGroup" = 32, #"TotalCases" = 566, #"Percentage" = 42.75],
					        [#"Sno" = 244, #"AgeGroup" = 49, #"TotalCases" = 260, #"Percentage" = 3.22],
					        [#"Sno" = 950, #"AgeGroup" = 32, #"TotalCases" = 915, #"Percentage" = 35.69],
					        [#"Sno" = 301, #"AgeGroup" = 44, #"TotalCases" = 583, #"Percentage" = 96.56],
					        [#"Sno" = 686, #"AgeGroup" = 50, #"TotalCases" = 453, #"Percentage" = 27.75],
					        [#"Sno" = 585, #"AgeGroup" = 50, #"TotalCases" = 321, #"Percentage" = 63.85],
					        [#"Sno" = 230, #"AgeGroup" = 39, #"TotalCases" = 557, #"Percentage" = 31.5],
					        [#"Sno" = 631, #"AgeGroup" = 66, #"TotalCases" = 512, #"Percentage" = 91.27],
					        [#"Sno" = 142, #"AgeGroup" = 42, #"TotalCases" = 394, #"Percentage" = 13.75],
					        [#"Sno" = 392, #"AgeGroup" = 32, #"TotalCases" = 455, #"Percentage" = 84.06],
					        [#"Sno" = 502, #"AgeGroup" = 57, #"TotalCases" = 339, #"Percentage" = 97.89],
					        [#"Sno" = 789, #"AgeGroup" = 45, #"TotalCases" = 589, #"Percentage" = 58.18],
					        [#"Sno" = 649, #"AgeGroup" = 54, #"TotalCases" = 84, #"Percentage" = 59.34],
					        [#"Sno" = 704, #"AgeGroup" = 57, #"TotalCases" = 51, #"Percentage" = 45.46],
					        [#"Sno" = 356, #"AgeGroup" = 67, #"TotalCases" = 28, #"Percentage" = 51.46],
					        [#"Sno" = 705, #"AgeGroup" = 77, #"TotalCases" = 136, #"Percentage" = 90.34],
					        [#"Sno" = 46, #"AgeGroup" = 68, #"TotalCases" = 163, #"Percentage" = 51.22],
					        [#"Sno" = 879, #"AgeGroup" = 67, #"TotalCases" = 906, #"Percentage" = 95.58],
					        [#"Sno" = 268, #"AgeGroup" = 70, #"TotalCases" = 92, #"Percentage" = 93.13],
					        [#"Sno" = 390, #"AgeGroup" = 75, #"TotalCases" = 688, #"Percentage" = 52.0],
					        [#"Sno" = 25, #"AgeGroup" = 29, #"TotalCases" = 259, #"Percentage" = 64.46],
					        [#"Sno" = 772, #"AgeGroup" = 26, #"TotalCases" = 521, #"Percentage" = 43.29],
					        [#"Sno" = 501, #"AgeGroup" = 18, #"TotalCases" = 86, #"Percentage" = 64.24],
					        [#"Sno" = 298, #"AgeGroup" = 45, #"TotalCases" = 306, #"Percentage" = 77.58],
					        [#"Sno" = 947, #"AgeGroup" = 55, #"TotalCases" = 985, #"Percentage" = 55.13],
					        [#"Sno" = 177, #"AgeGroup" = 50, #"TotalCases" = 967, #"Percentage" = 12.49],
					        [#"Sno" = 234, #"AgeGroup" = 56, #"TotalCases" = 271, #"Percentage" = 28.67],
					        [#"Sno" = 69, #"AgeGroup" = 30, #"TotalCases" = 9, #"Percentage" = 44.37],
					        [#"Sno" = 771, #"AgeGroup" = 57, #"TotalCases" = 313, #"Percentage" = 58.95],
					        [#"Sno" = 776, #"AgeGroup" = 27, #"TotalCases" = 702, #"Percentage" = 24.21],
					        [#"Sno" = 193, #"AgeGroup" = 39, #"TotalCases" = 70, #"Percentage" = 57.69],
					        [#"Sno" = 616, #"AgeGroup" = 22, #"TotalCases" = 152, #"Percentage" = 27.28],
					        [#"Sno" = 502, #"AgeGroup" = 62, #"TotalCases" = 239, #"Percentage" = 72.89],
					        [#"Sno" = 542, #"AgeGroup" = 35, #"TotalCases" = 997, #"Percentage" = 28.23],
					        [#"Sno" = 352, #"AgeGroup" = 39, #"TotalCases" = 279, #"Percentage" = 48.18],
					        [#"Sno" = 959, #"AgeGroup" = 58, #"TotalCases" = 331, #"Percentage" = 85.67],
					        [#"Sno" = 992, #"AgeGroup" = 77, #"TotalCases" = 643, #"Percentage" = 95.64],
					        [#"Sno" = 836, #"AgeGroup" = 79, #"TotalCases" = 36, #"Percentage" = 20.02],
					        [#"Sno" = 348, #"AgeGroup" = 38, #"TotalCases" = 842, #"Percentage" = 54.45],
					        [#"Sno" = 314, #"AgeGroup" = 24, #"TotalCases" = 34, #"Percentage" = 66.46],
					        [#"Sno" = 95, #"AgeGroup" = 40, #"TotalCases" = 776, #"Percentage" = 78.4],
					        [#"Sno" = 146, #"AgeGroup" = 24, #"TotalCases" = 809, #"Percentage" = 68.85],
					        [#"Sno" = 609, #"AgeGroup" = 40, #"TotalCases" = 745, #"Percentage" = 49.78],
					        [#"Sno" = 46, #"AgeGroup" = 50, #"TotalCases" = 965, #"Percentage" = 60.85],
					        [#"Sno" = 5, #"AgeGroup" = 29, #"TotalCases" = 65, #"Percentage" = 86.19],
					        [#"Sno" = 865, #"AgeGroup" = 23, #"TotalCases" = 165, #"Percentage" = 69.94],
					        [#"Sno" = 447, #"AgeGroup" = 22, #"TotalCases" = 300, #"Percentage" = 65.22],
					        [#"Sno" = 498, #"AgeGroup" = 24, #"TotalCases" = 698, #"Percentage" = 58.8],
					        [#"Sno" = 407, #"AgeGroup" = 31, #"TotalCases" = 591, #"Percentage" = 73.81],
					        [#"Sno" = 626, #"AgeGroup" = 35, #"TotalCases" = 879, #"Percentage" = 36.54],
					        [#"Sno" = 823, #"AgeGroup" = 43, #"TotalCases" = 954, #"Percentage" = 49.11],
					        [#"Sno" = 503, #"AgeGroup" = 73, #"TotalCases" = 152, #"Percentage" = 96.8],
					        [#"Sno" = 256, #"AgeGroup" = 71, #"TotalCases" = 868, #"Percentage" = 47.63],
					        [#"Sno" = 135, #"AgeGroup" = 18, #"TotalCases" = 294, #"Percentage" = 44.89],
					        [#"Sno" = 818, #"AgeGroup" = 35, #"TotalCases" = 626, #"Percentage" = 39.34],
					        [#"Sno" = 357, #"AgeGroup" = 55, #"TotalCases" = 421, #"Percentage" = 31.42],
					        [#"Sno" = 984, #"AgeGroup" = 61, #"TotalCases" = 127, #"Percentage" = 9.94],
					        [#"Sno" = 664, #"AgeGroup" = 40, #"TotalCases" = 709, #"Percentage" = 36.44],
					        [#"Sno" = 868, #"AgeGroup" = 39, #"TotalCases" = 774, #"Percentage" = 94.62],
					        [#"Sno" = 318, #"AgeGroup" = 27, #"TotalCases" = 129, #"Percentage" = 84.34],
					        [#"Sno" = 469, #"AgeGroup" = 26, #"TotalCases" = 160, #"Percentage" = 39.63],
					        [#"Sno" = 986, #"AgeGroup" = 57, #"TotalCases" = 502, #"Percentage" = 52.8],
					        [#"Sno" = 111, #"AgeGroup" = 25, #"TotalCases" = 549, #"Percentage" = 99.75],
					        [#"Sno" = 908, #"AgeGroup" = 45, #"TotalCases" = 474, #"Percentage" = 27.07],
					        [#"Sno" = 111, #"AgeGroup" = 70, #"TotalCases" = 422, #"Percentage" = 47.91],
					        [#"Sno" = 449, #"AgeGroup" = 63, #"TotalCases" = 680, #"Percentage" = 64.51],
					        [#"Sno" = 758, #"AgeGroup" = 25, #"TotalCases" = 322, #"Percentage" = 63.23],
					        [#"Sno" = 952, #"AgeGroup" = 78, #"TotalCases" = 566, #"Percentage" = 57.84],
					        [#"Sno" = 619, #"AgeGroup" = 60, #"TotalCases" = 483, #"Percentage" = 71.65],
					        [#"Sno" = 465, #"AgeGroup" = 69, #"TotalCases" = 399, #"Percentage" = 70.77],
					        [#"Sno" = 95, #"AgeGroup" = 64, #"TotalCases" = 899, #"Percentage" = 61.57],
					        [#"Sno" = 890, #"AgeGroup" = 25, #"TotalCases" = 703, #"Percentage" = 94.31],
					        [#"Sno" = 199, #"AgeGroup" = 79, #"TotalCases" = 24, #"Percentage" = 12.69],
					        [#"Sno" = 117, #"AgeGroup" = 31, #"TotalCases" = 643, #"Percentage" = 27.18],
					        [#"Sno" = 398, #"AgeGroup" = 67, #"TotalCases" = 390, #"Percentage" = 3.66],
					        [#"Sno" = 336, #"AgeGroup" = 21, #"TotalCases" = 277, #"Percentage" = 70.56],
					        [#"Sno" = 450, #"AgeGroup" = 37, #"TotalCases" = 866, #"Percentage" = 95.62],
					        [#"Sno" = 5, #"AgeGroup" = 44, #"TotalCases" = 657, #"Percentage" = 91.35],
					        [#"Sno" = 616, #"AgeGroup" = 42, #"TotalCases" = 518, #"Percentage" = 67.53],
					        [#"Sno" = 342, #"AgeGroup" = 24, #"TotalCases" = 599, #"Percentage" = 12.94],
					        [#"Sno" = 764, #"AgeGroup" = 44, #"TotalCases" = 869, #"Percentage" = 99.06],
					        [#"Sno" = 155, #"AgeGroup" = 75, #"TotalCases" = 378, #"Percentage" = 22.88],
					        [#"Sno" = 898, #"AgeGroup" = 43, #"TotalCases" = 515, #"Percentage" = 64.1],
					        [#"Sno" = 838, #"AgeGroup" = 65, #"TotalCases" = 351, #"Percentage" = 82.6],
					        [#"Sno" = 366, #"AgeGroup" = 65, #"TotalCases" = 615, #"Percentage" = 21.79],
					        [#"Sno" = 638, #"AgeGroup" = 36, #"TotalCases" = 67, #"Percentage" = 32.89],
					        [#"Sno" = 786, #"AgeGroup" = 42, #"TotalCases" = 782, #"Percentage" = 38.94],
					        [#"Sno" = 180, #"AgeGroup" = 32, #"TotalCases" = 118, #"Percentage" = 29.73],
					        [#"Sno" = 374, #"AgeGroup" = 67, #"TotalCases" = 589, #"Percentage" = 64.75],
					        [#"Sno" = 914, #"AgeGroup" = 52, #"TotalCases" = 474, #"Percentage" = 80.44],
					        [#"Sno" = 198, #"AgeGroup" = 52, #"TotalCases" = 620, #"Percentage" = 32.4],
					        [#"Sno" = 744, #"AgeGroup" = 47, #"TotalCases" = 155, #"Percentage" = 58.43],
					        [#"Sno" = 912, #"AgeGroup" = 76, #"TotalCases" = 798, #"Percentage" = 94.3],
					        [#"Sno" = 25, #"AgeGroup" = 41, #"TotalCases" = 924, #"Percentage" = 44.79],
					        [#"Sno" = 506, #"AgeGroup" = 77, #"TotalCases" = 590, #"Percentage" = 44.89],
					        [#"Sno" = 710, #"AgeGroup" = 42, #"TotalCases" = 4, #"Percentage" = 2.74],
					        [#"Sno" = 800, #"AgeGroup" = 19, #"TotalCases" = 933, #"Percentage" = 73.32],
					        [#"Sno" = 945, #"AgeGroup" = 19, #"TotalCases" = 321, #"Percentage" = 6.32],
					        [#"Sno" = 743, #"AgeGroup" = 24, #"TotalCases" = 870, #"Percentage" = 30.6],
					        [#"Sno" = 369, #"AgeGroup" = 28, #"TotalCases" = 657, #"Percentage" = 46.77],
					        [#"Sno" = 518, #"AgeGroup" = 27, #"TotalCases" = 502, #"Percentage" = 3.06],
					        [#"Sno" = 262, #"AgeGroup" = 80, #"TotalCases" = 462, #"Percentage" = 91.38],
					        [#"Sno" = 751, #"AgeGroup" = 27, #"TotalCases" = 947, #"Percentage" = 79.73],
					        [#"Sno" = 711, #"AgeGroup" = 38, #"TotalCases" = 859, #"Percentage" = 33.08],
					        [#"Sno" = 330, #"AgeGroup" = 74, #"TotalCases" = 821, #"Percentage" = 65.58],
					        [#"Sno" = 408, #"AgeGroup" = 18, #"TotalCases" = 432, #"Percentage" = 73.24],
					        [#"Sno" = 594, #"AgeGroup" = 59, #"TotalCases" = 630, #"Percentage" = 46.69],
					        [#"Sno" = 516, #"AgeGroup" = 31, #"TotalCases" = 275, #"Percentage" = 22.86],
					        [#"Sno" = 314, #"AgeGroup" = 61, #"TotalCases" = 892, #"Percentage" = 75.36],
					        [#"Sno" = 428, #"AgeGroup" = 30, #"TotalCases" = 289, #"Percentage" = 84.15],
					        [#"Sno" = 55, #"AgeGroup" = 61, #"TotalCases" = 85, #"Percentage" = 37.59],
					        [#"Sno" = 900, #"AgeGroup" = 43, #"TotalCases" = 656, #"Percentage" = 61.55],
					        [#"Sno" = 302, #"AgeGroup" = 37, #"TotalCases" = 581, #"Percentage" = 65.69],
					        [#"Sno" = 731, #"AgeGroup" = 30, #"TotalCases" = 977, #"Percentage" = 90.72],
					        [#"Sno" = 383, #"AgeGroup" = 23, #"TotalCases" = 971, #"Percentage" = 49.77],
					        [#"Sno" = 717, #"AgeGroup" = 42, #"TotalCases" = 736, #"Percentage" = 77.63],
					        [#"Sno" = 78, #"AgeGroup" = 43, #"TotalCases" = 11, #"Percentage" = 15.64],
					        [#"Sno" = 683, #"AgeGroup" = 26, #"TotalCases" = 571, #"Percentage" = 65.27],
					        [#"Sno" = 391, #"AgeGroup" = 48, #"TotalCases" = 419, #"Percentage" = 20.45],
					        [#"Sno" = 932, #"AgeGroup" = 43, #"TotalCases" = 918, #"Percentage" = 40.67],
					        [#"Sno" = 589, #"AgeGroup" = 41, #"TotalCases" = 300, #"Percentage" = 30.24],
					        [#"Sno" = 550, #"AgeGroup" = 23, #"TotalCases" = 289, #"Percentage" = 30.49],
					        [#"Sno" = 57, #"AgeGroup" = 52, #"TotalCases" = 915, #"Percentage" = 38.47],
					        [#"Sno" = 902, #"AgeGroup" = 76, #"TotalCases" = 869, #"Percentage" = 73.79],
					        [#"Sno" = 730, #"AgeGroup" = 38, #"TotalCases" = 561, #"Percentage" = 1.81],
					        [#"Sno" = 931, #"AgeGroup" = 63, #"TotalCases" = 699, #"Percentage" = 30.96],
					        [#"Sno" = 313, #"AgeGroup" = 70, #"TotalCases" = 521, #"Percentage" = 65.45],
					        [#"Sno" = 737, #"AgeGroup" = 33, #"TotalCases" = 319, #"Percentage" = 20.01],
					        [#"Sno" = 362, #"AgeGroup" = 76, #"TotalCases" = 891, #"Percentage" = 98.73],
					        [#"Sno" = 469, #"AgeGroup" = 80, #"TotalCases" = 208, #"Percentage" = 56.49],
					        [#"Sno" = 78, #"AgeGroup" = 31, #"TotalCases" = 705, #"Percentage" = 5.28],
					        [#"Sno" = 224, #"AgeGroup" = 52, #"TotalCases" = 350, #"Percentage" = 14.21],
					        [#"Sno" = 739, #"AgeGroup" = 53, #"TotalCases" = 68, #"Percentage" = 50.57],
					        [#"Sno" = 456, #"AgeGroup" = 28, #"TotalCases" = 821, #"Percentage" = 73.51],
					        [#"Sno" = 743, #"AgeGroup" = 44, #"TotalCases" = 86, #"Percentage" = 47.23],
					        [#"Sno" = 738, #"AgeGroup" = 38, #"TotalCases" = 486, #"Percentage" = 48.42],
					        [#"Sno" = 322, #"AgeGroup" = 47, #"TotalCases" = 246, #"Percentage" = 17.08],
					        [#"Sno" = 651, #"AgeGroup" = 50, #"TotalCases" = 563, #"Percentage" = 16.17],
					        [#"Sno" = 610, #"AgeGroup" = 80, #"TotalCases" = 60, #"Percentage" = 54.5],
					        [#"Sno" = 854, #"AgeGroup" = 43, #"TotalCases" = 425, #"Percentage" = 86.75],
					        [#"Sno" = 992, #"AgeGroup" = 76, #"TotalCases" = 611, #"Percentage" = 14.4],
					        [#"Sno" = 198, #"AgeGroup" = 50, #"TotalCases" = 225, #"Percentage" = 45.47],
					        [#"Sno" = 875, #"AgeGroup" = 26, #"TotalCases" = 755, #"Percentage" = 22.5],
					        [#"Sno" = 213, #"AgeGroup" = 73, #"TotalCases" = 969, #"Percentage" = 58.18],
					        [#"Sno" = 114, #"AgeGroup" = 29, #"TotalCases" = 159, #"Percentage" = 25.33],
					        [#"Sno" = 723, #"AgeGroup" = 44, #"TotalCases" = 341, #"Percentage" = 88.86],
					        [#"Sno" = 76, #"AgeGroup" = 22, #"TotalCases" = 670, #"Percentage" = 5.18],
					        [#"Sno" = 797, #"AgeGroup" = 44, #"TotalCases" = 526, #"Percentage" = 60.39],
					        [#"Sno" = 908, #"AgeGroup" = 79, #"TotalCases" = 708, #"Percentage" = 71.0],
					        [#"Sno" = 284, #"AgeGroup" = 67, #"TotalCases" = 537, #"Percentage" = 84.39],
					        [#"Sno" = 552, #"AgeGroup" = 70, #"TotalCases" = 991, #"Percentage" = 80.81],
					        [#"Sno" = 71, #"AgeGroup" = 66, #"TotalCases" = 505, #"Percentage" = 74.65],
					        [#"Sno" = 493, #"AgeGroup" = 18, #"TotalCases" = 30, #"Percentage" = 49.07],
					        [#"Sno" = 598, #"AgeGroup" = 40, #"TotalCases" = 21, #"Percentage" = 88.31],
					        [#"Sno" = 188, #"AgeGroup" = 63, #"TotalCases" = 512, #"Percentage" = 62.22],
					        [#"Sno" = 915, #"AgeGroup" = 31, #"TotalCases" = 664, #"Percentage" = 68.84],
					        [#"Sno" = 83, #"AgeGroup" = 77, #"TotalCases" = 430, #"Percentage" = 2.31],
					        [#"Sno" = 143, #"AgeGroup" = 71, #"TotalCases" = 717, #"Percentage" = 78.51],
					        [#"Sno" = 379, #"AgeGroup" = 48, #"TotalCases" = 636, #"Percentage" = 43.54],
					        [#"Sno" = 93, #"AgeGroup" = 35, #"TotalCases" = 641, #"Percentage" = 83.43],
					        [#"Sno" = 429, #"AgeGroup" = 61, #"TotalCases" = 916, #"Percentage" = 71.22],
					        [#"Sno" = 756, #"AgeGroup" = 37, #"TotalCases" = 272, #"Percentage" = 25.55],
					        [#"Sno" = 296, #"AgeGroup" = 51, #"TotalCases" = 8, #"Percentage" = 40.95],
					        [#"Sno" = 564, #"AgeGroup" = 65, #"TotalCases" = 998, #"Percentage" = 97.22],
					        [#"Sno" = 270, #"AgeGroup" = 31, #"TotalCases" = 147, #"Percentage" = 81.69],
					        [#"Sno" = 79, #"AgeGroup" = 77, #"TotalCases" = 517, #"Percentage" = 25.48],
					        [#"Sno" = 153, #"AgeGroup" = 59, #"TotalCases" = 294, #"Percentage" = 70.88],
					        [#"Sno" = 721, #"AgeGroup" = 23, #"TotalCases" = 535, #"Percentage" = 4.3],
					        [#"Sno" = 391, #"AgeGroup" = 39, #"TotalCases" = 913, #"Percentage" = 21.56],
					        [#"Sno" = 382, #"AgeGroup" = 65, #"TotalCases" = 498, #"Percentage" = 87.69],
					        [#"Sno" = 644, #"AgeGroup" = 21, #"TotalCases" = 790, #"Percentage" = 32.26],
					        [#"Sno" = 26, #"AgeGroup" = 50, #"TotalCases" = 450, #"Percentage" = 5.63],
					        [#"Sno" = 588, #"AgeGroup" = 22, #"TotalCases" = 550, #"Percentage" = 88.86],
					        [#"Sno" = 435, #"AgeGroup" = 31, #"TotalCases" = 522, #"Percentage" = 74.24],
					        [#"Sno" = 414, #"AgeGroup" = 61, #"TotalCases" = 717, #"Percentage" = 71.56],
					        [#"Sno" = 337, #"AgeGroup" = 34, #"TotalCases" = 139, #"Percentage" = 30.47],
					        [#"Sno" = 687, #"AgeGroup" = 46, #"TotalCases" = 837, #"Percentage" = 34.9],
					        [#"Sno" = 306, #"AgeGroup" = 53, #"TotalCases" = 356, #"Percentage" = 82.72],
					        [#"Sno" = 717, #"AgeGroup" = 76, #"TotalCases" = 114, #"Percentage" = 72.89],
					        [#"Sno" = 579, #"AgeGroup" = 39, #"TotalCases" = 561, #"Percentage" = 19.22],
					        [#"Sno" = 862, #"AgeGroup" = 70, #"TotalCases" = 867, #"Percentage" = 35.13],
					        [#"Sno" = 756, #"AgeGroup" = 18, #"TotalCases" = 944, #"Percentage" = 17.25],
					        [#"Sno" = 86, #"AgeGroup" = 67, #"TotalCases" = 337, #"Percentage" = 90.36],
					        [#"Sno" = 831, #"AgeGroup" = 49, #"TotalCases" = 582, #"Percentage" = 20.87],
					        [#"Sno" = 885, #"AgeGroup" = 31, #"TotalCases" = 905, #"Percentage" = 48.51],
					        [#"Sno" = 625, #"AgeGroup" = 77, #"TotalCases" = 617, #"Percentage" = 69.15],
					        [#"Sno" = 686, #"AgeGroup" = 31, #"TotalCases" = 136, #"Percentage" = 93.62],
					        [#"Sno" = 260, #"AgeGroup" = 66, #"TotalCases" = 291, #"Percentage" = 60.62],
					        [#"Sno" = 194, #"AgeGroup" = 62, #"TotalCases" = 705, #"Percentage" = 96.0],
					        [#"Sno" = 766, #"AgeGroup" = 20, #"TotalCases" = 661, #"Percentage" = 12.09],
					        [#"Sno" = 748, #"AgeGroup" = 26, #"TotalCases" = 188, #"Percentage" = 85.37],
					        [#"Sno" = 609, #"AgeGroup" = 26, #"TotalCases" = 818, #"Percentage" = 77.93],
					        [#"Sno" = 134, #"AgeGroup" = 37, #"TotalCases" = 760, #"Percentage" = 82.42],
					        [#"Sno" = 66, #"AgeGroup" = 74, #"TotalCases" = 588, #"Percentage" = 25.69],
					        [#"Sno" = 159, #"AgeGroup" = 33, #"TotalCases" = 923, #"Percentage" = 33.05],
					        [#"Sno" = 770, #"AgeGroup" = 45, #"TotalCases" = 944, #"Percentage" = 32.24],
					        [#"Sno" = 167, #"AgeGroup" = 31, #"TotalCases" = 612, #"Percentage" = 52.6],
					        [#"Sno" = 505, #"AgeGroup" = 38, #"TotalCases" = 295, #"Percentage" = 65.52],
					        [#"Sno" = 988, #"AgeGroup" = 77, #"TotalCases" = 963, #"Percentage" = 30.25],
					        [#"Sno" = 920, #"AgeGroup" = 30, #"TotalCases" = 881, #"Percentage" = 62.44],
					        [#"Sno" = 200, #"AgeGroup" = 46, #"TotalCases" = 730, #"Percentage" = 16.89],
					        [#"Sno" = 998, #"AgeGroup" = 46, #"TotalCases" = 192, #"Percentage" = 7.28],
					        [#"Sno" = 746, #"AgeGroup" = 50, #"TotalCases" = 806, #"Percentage" = 20.47],
					        [#"Sno" = 34, #"AgeGroup" = 38, #"TotalCases" = 487, #"Percentage" = 16.93],
					        [#"Sno" = 92, #"AgeGroup" = 68, #"TotalCases" = 288, #"Percentage" = 4.64],
					        [#"Sno" = 909, #"AgeGroup" = 49, #"TotalCases" = 649, #"Percentage" = 72.35],
					        [#"Sno" = 650, #"AgeGroup" = 57, #"TotalCases" = 746, #"Percentage" = 78.89],
					        [#"Sno" = 612, #"AgeGroup" = 57, #"TotalCases" = 615, #"Percentage" = 91.26],
					        [#"Sno" = 635, #"AgeGroup" = 29, #"TotalCases" = 683, #"Percentage" = 68.47],
					        [#"Sno" = 949, #"AgeGroup" = 38, #"TotalCases" = 38, #"Percentage" = 13.55],
					        [#"Sno" = 375, #"AgeGroup" = 54, #"TotalCases" = 950, #"Percentage" = 55.48],
					        [#"Sno" = 802, #"AgeGroup" = 77, #"TotalCases" = 755, #"Percentage" = 18.96],
					        [#"Sno" = 253, #"AgeGroup" = 35, #"TotalCases" = 129, #"Percentage" = 20.64],
					        [#"Sno" = 775, #"AgeGroup" = 29, #"TotalCases" = 78, #"Percentage" = 96.81],
					        [#"Sno" = 327, #"AgeGroup" = 28, #"TotalCases" = 733, #"Percentage" = 57.75],
					        [#"Sno" = 713, #"AgeGroup" = 61, #"TotalCases" = 121, #"Percentage" = 12.87],
					        [#"Sno" = 789, #"AgeGroup" = 31, #"TotalCases" = 188, #"Percentage" = 61.99],
					        [#"Sno" = 598, #"AgeGroup" = 79, #"TotalCases" = 616, #"Percentage" = 88.75],
					        [#"Sno" = 881, #"AgeGroup" = 25, #"TotalCases" = 563, #"Percentage" = 88.98],
					        [#"Sno" = 686, #"AgeGroup" = 47, #"TotalCases" = 587, #"Percentage" = 90.27],
					        [#"Sno" = 694, #"AgeGroup" = 48, #"TotalCases" = 860, #"Percentage" = 80.58],
					        [#"Sno" = 673, #"AgeGroup" = 32, #"TotalCases" = 368, #"Percentage" = 7.67],
					        [#"Sno" = 407, #"AgeGroup" = 46, #"TotalCases" = 325, #"Percentage" = 69.02],
					        [#"Sno" = 393, #"AgeGroup" = 78, #"TotalCases" = 701, #"Percentage" = 71.29],
					        [#"Sno" = 816, #"AgeGroup" = 69, #"TotalCases" = 75, #"Percentage" = 31.45],
					        [#"Sno" = 721, #"AgeGroup" = 69, #"TotalCases" = 181, #"Percentage" = 0.82],
					        [#"Sno" = 560, #"AgeGroup" = 21, #"TotalCases" = 648, #"Percentage" = 99.13],
					        [#"Sno" = 842, #"AgeGroup" = 32, #"TotalCases" = 591, #"Percentage" = 50.3],
					        [#"Sno" = 398, #"AgeGroup" = 31, #"TotalCases" = 348, #"Percentage" = 80.89],
					        [#"Sno" = 337, #"AgeGroup" = 49, #"TotalCases" = 67, #"Percentage" = 36.11],
					        [#"Sno" = 589, #"AgeGroup" = 32, #"TotalCases" = 505, #"Percentage" = 14.67],
					        [#"Sno" = 941, #"AgeGroup" = 66, #"TotalCases" = 392, #"Percentage" = 29.67],
					        [#"Sno" = 888, #"AgeGroup" = 60, #"TotalCases" = 912, #"Percentage" = 33.71],
					        [#"Sno" = 979, #"AgeGroup" = 29, #"TotalCases" = 30, #"Percentage" = 98.18],
					        [#"Sno" = 422, #"AgeGroup" = 18, #"TotalCases" = 612, #"Percentage" = 22.75],
					        [#"Sno" = 308, #"AgeGroup" = 40, #"TotalCases" = 67, #"Percentage" = 65.86],
					        [#"Sno" = 731, #"AgeGroup" = 78, #"TotalCases" = 12, #"Percentage" = 15.9],
					        [#"Sno" = 380, #"AgeGroup" = 28, #"TotalCases" = 945, #"Percentage" = 38.75],
					        [#"Sno" = 548, #"AgeGroup" = 49, #"TotalCases" = 762, #"Percentage" = 75.99],
					        [#"Sno" = 140, #"AgeGroup" = 59, #"TotalCases" = 574, #"Percentage" = 8.91],
					        [#"Sno" = 269, #"AgeGroup" = 64, #"TotalCases" = 232, #"Percentage" = 59.51],
					        [#"Sno" = 320, #"AgeGroup" = 38, #"TotalCases" = 795, #"Percentage" = 48.3],
					        [#"Sno" = 62, #"AgeGroup" = 55, #"TotalCases" = 346, #"Percentage" = 26.71],
					        [#"Sno" = 298, #"AgeGroup" = 39, #"TotalCases" = 14, #"Percentage" = 75.32],
					        [#"Sno" = 56, #"AgeGroup" = 78, #"TotalCases" = 605, #"Percentage" = 64.41],
					        [#"Sno" = 713, #"AgeGroup" = 67, #"TotalCases" = 673, #"Percentage" = 44.71],
					        [#"Sno" = 968, #"AgeGroup" = 58, #"TotalCases" = 437, #"Percentage" = 86.75],
					        [#"Sno" = 277, #"AgeGroup" = 22, #"TotalCases" = 685, #"Percentage" = 15.88],
					        [#"Sno" = 591, #"AgeGroup" = 26, #"TotalCases" = 652, #"Percentage" = 47.56],
					        [#"Sno" = 717, #"AgeGroup" = 41, #"TotalCases" = 534, #"Percentage" = 75.32],
					        [#"Sno" = 143, #"AgeGroup" = 73, #"TotalCases" = 510, #"Percentage" = 79.31],
					        [#"Sno" = 572, #"AgeGroup" = 55, #"TotalCases" = 314, #"Percentage" = 69.4],
					        [#"Sno" = 222, #"AgeGroup" = 45, #"TotalCases" = 534, #"Percentage" = 2.46],
					        [#"Sno" = 850, #"AgeGroup" = 37, #"TotalCases" = 512, #"Percentage" = 75.64],
					        [#"Sno" = 674, #"AgeGroup" = 21, #"TotalCases" = 89, #"Percentage" = 53.3],
					        [#"Sno" = 561, #"AgeGroup" = 74, #"TotalCases" = 83, #"Percentage" = 24.33],
					        [#"Sno" = 171, #"AgeGroup" = 66, #"TotalCases" = 997, #"Percentage" = 75.38],
					        [#"Sno" = 33, #"AgeGroup" = 65, #"TotalCases" = 204, #"Percentage" = 45.31],
					        [#"Sno" = 963, #"AgeGroup" = 62, #"TotalCases" = 22, #"Percentage" = 40.84],
					        [#"Sno" = 304, #"AgeGroup" = 37, #"TotalCases" = 990, #"Percentage" = 24.74],
					        [#"Sno" = 673, #"AgeGroup" = 58, #"TotalCases" = 39, #"Percentage" = 85.15],
					        [#"Sno" = 91, #"AgeGroup" = 26, #"TotalCases" = 533, #"Percentage" = 71.2],
					        [#"Sno" = 583, #"AgeGroup" = 30, #"TotalCases" = 577, #"Percentage" = 93.96],
					        [#"Sno" = 407, #"AgeGroup" = 20, #"TotalCases" = 335, #"Percentage" = 85.57],
					        [#"Sno" = 774, #"AgeGroup" = 47, #"TotalCases" = 109, #"Percentage" = 54.76],
					        [#"Sno" = 345, #"AgeGroup" = 34, #"TotalCases" = 465, #"Percentage" = 79.63],
					        [#"Sno" = 484, #"AgeGroup" = 58, #"TotalCases" = 492, #"Percentage" = 24.33],
					        [#"Sno" = 4, #"AgeGroup" = 49, #"TotalCases" = 148, #"Percentage" = 98.6],
					        [#"Sno" = 965, #"AgeGroup" = 78, #"TotalCases" = 898, #"Percentage" = 31.11],
					        [#"Sno" = 688, #"AgeGroup" = 57, #"TotalCases" = 502, #"Percentage" = 64.9],
					        [#"Sno" = 203, #"AgeGroup" = 64, #"TotalCases" = 841, #"Percentage" = 64.17],
					        [#"Sno" = 706, #"AgeGroup" = 53, #"TotalCases" = 310, #"Percentage" = 27.23],
					        [#"Sno" = 636, #"AgeGroup" = 72, #"TotalCases" = 426, #"Percentage" = 65.99],
					        [#"Sno" = 16, #"AgeGroup" = 31, #"TotalCases" = 96, #"Percentage" = 29.25],
					        [#"Sno" = 256, #"AgeGroup" = 75, #"TotalCases" = 791, #"Percentage" = 38.58],
					        [#"Sno" = 320, #"AgeGroup" = 55, #"TotalCases" = 603, #"Percentage" = 42.57],
					        [#"Sno" = 774, #"AgeGroup" = 67, #"TotalCases" = 395, #"Percentage" = 23.48],
					        [#"Sno" = 126, #"AgeGroup" = 52, #"TotalCases" = 63, #"Percentage" = 29.3],
					        [#"Sno" = 337, #"AgeGroup" = 69, #"TotalCases" = 512, #"Percentage" = 78.24],
					        [#"Sno" = 519, #"AgeGroup" = 59, #"TotalCases" = 203, #"Percentage" = 70.57],
					        [#"Sno" = 243, #"AgeGroup" = 28, #"TotalCases" = 754, #"Percentage" = 86.44],
					        [#"Sno" = 766, #"AgeGroup" = 36, #"TotalCases" = 611, #"Percentage" = 54.72],
					        [#"Sno" = 580, #"AgeGroup" = 33, #"TotalCases" = 764, #"Percentage" = 26.35],
					        [#"Sno" = 424, #"AgeGroup" = 62, #"TotalCases" = 831, #"Percentage" = 89.25],
					        [#"Sno" = 357, #"AgeGroup" = 37, #"TotalCases" = 927, #"Percentage" = 99.03],
					        [#"Sno" = 509, #"AgeGroup" = 75, #"TotalCases" = 224, #"Percentage" = 72.64],
					        [#"Sno" = 818, #"AgeGroup" = 27, #"TotalCases" = 424, #"Percentage" = 51.19],
					        [#"Sno" = 570, #"AgeGroup" = 63, #"TotalCases" = 876, #"Percentage" = 2.11],
					        [#"Sno" = 990, #"AgeGroup" = 34, #"TotalCases" = 641, #"Percentage" = 74.5],
					        [#"Sno" = 40, #"AgeGroup" = 63, #"TotalCases" = 253, #"Percentage" = 52.15],
					        [#"Sno" = 56, #"AgeGroup" = 73, #"TotalCases" = 348, #"Percentage" = 58.46],
					        [#"Sno" = 852, #"AgeGroup" = 21, #"TotalCases" = 849, #"Percentage" = 44.42],
					        [#"Sno" = 333, #"AgeGroup" = 25, #"TotalCases" = 535, #"Percentage" = 76.88],
					        [#"Sno" = 114, #"AgeGroup" = 75, #"TotalCases" = 153, #"Percentage" = 28.33],
					        [#"Sno" = 78, #"AgeGroup" = 72, #"TotalCases" = 361, #"Percentage" = 34.54],
					        [#"Sno" = 400, #"AgeGroup" = 63, #"TotalCases" = 917, #"Percentage" = 8.11],
					        [#"Sno" = 49, #"AgeGroup" = 34, #"TotalCases" = 153, #"Percentage" = 49.49],
					        [#"Sno" = 417, #"AgeGroup" = 65, #"TotalCases" = 593, #"Percentage" = 75.58],
					        [#"Sno" = 546, #"AgeGroup" = 67, #"TotalCases" = 243, #"Percentage" = 26.43],
					        [#"Sno" = 4, #"AgeGroup" = 72, #"TotalCases" = 641, #"Percentage" = 3.53],
					        [#"Sno" = 270, #"AgeGroup" = 36, #"TotalCases" = 215, #"Percentage" = 18.58],
					        [#"Sno" = 651, #"AgeGroup" = 38, #"TotalCases" = 61, #"Percentage" = 37.52],
					        [#"Sno" = 218, #"AgeGroup" = 57, #"TotalCases" = 634, #"Percentage" = 17.22],
					        [#"Sno" = 379, #"AgeGroup" = 28, #"TotalCases" = 170, #"Percentage" = 28.71],
					        [#"Sno" = 738, #"AgeGroup" = 32, #"TotalCases" = 133, #"Percentage" = 22.66],
					        [#"Sno" = 108, #"AgeGroup" = 65, #"TotalCases" = 1000, #"Percentage" = 94.95],
					        [#"Sno" = 764, #"AgeGroup" = 21, #"TotalCases" = 226, #"Percentage" = 14.87],
					        [#"Sno" = 843, #"AgeGroup" = 52, #"TotalCases" = 708, #"Percentage" = 60.98],
					        [#"Sno" = 175, #"AgeGroup" = 53, #"TotalCases" = 391, #"Percentage" = 73.36],
					        [#"Sno" = 978, #"AgeGroup" = 58, #"TotalCases" = 243, #"Percentage" = 63.49],
					        [#"Sno" = 423, #"AgeGroup" = 38, #"TotalCases" = 959, #"Percentage" = 96.4],
					        [#"Sno" = 594, #"AgeGroup" = 63, #"TotalCases" = 294, #"Percentage" = 11.29],
					        [#"Sno" = 523, #"AgeGroup" = 74, #"TotalCases" = 872, #"Percentage" = 77.35],
					        [#"Sno" = 811, #"AgeGroup" = 51, #"TotalCases" = 114, #"Percentage" = 13.03],
					        [#"Sno" = 738, #"AgeGroup" = 21, #"TotalCases" = 778, #"Percentage" = 34.06],
					        [#"Sno" = 92, #"AgeGroup" = 59, #"TotalCases" = 24, #"Percentage" = 8.83],
					        [#"Sno" = 969, #"AgeGroup" = 51, #"TotalCases" = 212, #"Percentage" = 76.91],
					        [#"Sno" = 82, #"AgeGroup" = 18, #"TotalCases" = 314, #"Percentage" = 72.35],
					        [#"Sno" = 454, #"AgeGroup" = 58, #"TotalCases" = 242, #"Percentage" = 52.57],
					        [#"Sno" = 524, #"AgeGroup" = 23, #"TotalCases" = 646, #"Percentage" = 59.54],
					        [#"Sno" = 949, #"AgeGroup" = 67, #"TotalCases" = 830, #"Percentage" = 29.42],
					        [#"Sno" = 531, #"AgeGroup" = 69, #"TotalCases" = 418, #"Percentage" = 56.85],
					        [#"Sno" = 225, #"AgeGroup" = 23, #"TotalCases" = 591, #"Percentage" = 83.32],
					        [#"Sno" = 557, #"AgeGroup" = 79, #"TotalCases" = 709, #"Percentage" = 35.22],
					        [#"Sno" = 985, #"AgeGroup" = 65, #"TotalCases" = 13, #"Percentage" = 17.58],
					        [#"Sno" = 887, #"AgeGroup" = 41, #"TotalCases" = 858, #"Percentage" = 91.74],
					        [#"Sno" = 634, #"AgeGroup" = 49, #"TotalCases" = 572, #"Percentage" = 51.0],
					        [#"Sno" = 612, #"AgeGroup" = 40, #"TotalCases" = 237, #"Percentage" = 37.6],
					        [#"Sno" = 654, #"AgeGroup" = 40, #"TotalCases" = 112, #"Percentage" = 68.98],
					        [#"Sno" = 325, #"AgeGroup" = 19, #"TotalCases" = 326, #"Percentage" = 17.82],
					        [#"Sno" = 322, #"AgeGroup" = 71, #"TotalCases" = 233, #"Percentage" = 23.78],
					        [#"Sno" = 285, #"AgeGroup" = 33, #"TotalCases" = 327, #"Percentage" = 31.45],
					        [#"Sno" = 80, #"AgeGroup" = 20, #"TotalCases" = 866, #"Percentage" = 11.43],
					        [#"Sno" = 308, #"AgeGroup" = 54, #"TotalCases" = 294, #"Percentage" = 56.58],
					        [#"Sno" = 968, #"AgeGroup" = 77, #"TotalCases" = 615, #"Percentage" = 79.53],
					        [#"Sno" = 121, #"AgeGroup" = 28, #"TotalCases" = 479, #"Percentage" = 81.17],
					        [#"Sno" = 555, #"AgeGroup" = 57, #"TotalCases" = 188, #"Percentage" = 16.62],
					        [#"Sno" = 922, #"AgeGroup" = 68, #"TotalCases" = 597, #"Percentage" = 26.79],
					        [#"Sno" = 81, #"AgeGroup" = 42, #"TotalCases" = 845, #"Percentage" = 96.3],
					        [#"Sno" = 643, #"AgeGroup" = 53, #"TotalCases" = 251, #"Percentage" = 71.37],
					        [#"Sno" = 688, #"AgeGroup" = 72, #"TotalCases" = 928, #"Percentage" = 9.3],
					        [#"Sno" = 360, #"AgeGroup" = 21, #"TotalCases" = 860, #"Percentage" = 36.77],
					        [#"Sno" = 243, #"AgeGroup" = 74, #"TotalCases" = 442, #"Percentage" = 33.9],
					        [#"Sno" = 850, #"AgeGroup" = 44, #"TotalCases" = 298, #"Percentage" = 91.3],
					        [#"Sno" = 893, #"AgeGroup" = 52, #"TotalCases" = 947, #"Percentage" = 26.3],
					        [#"Sno" = 479, #"AgeGroup" = 74, #"TotalCases" = 231, #"Percentage" = 99.5],
					        [#"Sno" = 959, #"AgeGroup" = 49, #"TotalCases" = 895, #"Percentage" = 2.99],
					        [#"Sno" = 178, #"AgeGroup" = 77, #"TotalCases" = 128, #"Percentage" = 29.13],
					        [#"Sno" = 972, #"AgeGroup" = 28, #"TotalCases" = 482, #"Percentage" = 73.89],
					        [#"Sno" = 888, #"AgeGroup" = 30, #"TotalCases" = 647, #"Percentage" = 62.14],
					        [#"Sno" = 460, #"AgeGroup" = 63, #"TotalCases" = 928, #"Percentage" = 45.6],
					        [#"Sno" = 906, #"AgeGroup" = 75, #"TotalCases" = 81, #"Percentage" = 4.14],
					        [#"Sno" = 612, #"AgeGroup" = 59, #"TotalCases" = 669, #"Percentage" = 88.28],
					        [#"Sno" = 411, #"AgeGroup" = 70, #"TotalCases" = 272, #"Percentage" = 58.23],
					        [#"Sno" = 605, #"AgeGroup" = 55, #"TotalCases" = 119, #"Percentage" = 24.05],
					        [#"Sno" = 289, #"AgeGroup" = 27, #"TotalCases" = 491, #"Percentage" = 66.43],
					        [#"Sno" = 424, #"AgeGroup" = 75, #"TotalCases" = 357, #"Percentage" = 13.39],
					        [#"Sno" = 118, #"AgeGroup" = 74, #"TotalCases" = 434, #"Percentage" = 75.54],
					        [#"Sno" = 650, #"AgeGroup" = 68, #"TotalCases" = 3, #"Percentage" = 30.34],
					        [#"Sno" = 95, #"AgeGroup" = 74, #"TotalCases" = 109, #"Percentage" = 7.6],
					        [#"Sno" = 539, #"AgeGroup" = 72, #"TotalCases" = 887, #"Percentage" = 11.12],
					        [#"Sno" = 174, #"AgeGroup" = 59, #"TotalCases" = 373, #"Percentage" = 98.11],
					        [#"Sno" = 584, #"AgeGroup" = 39, #"TotalCases" = 42, #"Percentage" = 8.94],
					        [#"Sno" = 608, #"AgeGroup" = 40, #"TotalCases" = 245, #"Percentage" = 10.79],
					        [#"Sno" = 642, #"AgeGroup" = 42, #"TotalCases" = 451, #"Percentage" = 57.23],
					        [#"Sno" = 584, #"AgeGroup" = 53, #"TotalCases" = 522, #"Percentage" = 36.4],
					        [#"Sno" = 525, #"AgeGroup" = 70, #"TotalCases" = 273, #"Percentage" = 16.94],
					        [#"Sno" = 311, #"AgeGroup" = 75, #"TotalCases" = 541, #"Percentage" = 19.02],
					        [#"Sno" = 424, #"AgeGroup" = 29, #"TotalCases" = 657, #"Percentage" = 40.27],
					        [#"Sno" = 620, #"AgeGroup" = 78, #"TotalCases" = 160, #"Percentage" = 96.62]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Sno", Int64.Type},
					        {"AgeGroup", type text},
					        {"TotalCases", Int64.Type},
					        {"Percentage", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table