table Extract_AgeGroupDetails
	lineageTag: e483d903-e68f-4b8c-80a1-62d440819d44

	column Sno
		dataType: int64
		formatString: 0
		lineageTag: 161eb2b9-1935-4877-b471-36348e16f918
		summarizeBy: sum
		sourceColumn: Sno

		annotation SummarizationSetBy = Automatic

	column AgeGroup
		dataType: string
		lineageTag: f329abcc-606f-4b00-84ff-abdb95c27d81
		summarizeBy: none
		sourceColumn: AgeGroup

		annotation SummarizationSetBy = Automatic

	column TotalCases
		dataType: int64
		formatString: 0
		lineageTag: d6999b1c-cef1-4391-922d-7943e74b10bb
		summarizeBy: sum
		sourceColumn: TotalCases

		annotation SummarizationSetBy = Automatic

	column Percentage
		dataType: double
		formatString: General Number
		lineageTag: 8cbaa6da-4080-4629-aec2-ba0b08792a3a
		summarizeBy: sum
		sourceColumn: Percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Extract_AgeGroupDetails = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Sno" = 717, #"AgeGroup" = 23, #"TotalCases" = 248, #"Percentage" = 14.86],
					        [#"Sno" = 496, #"AgeGroup" = 80, #"TotalCases" = 371, #"Percentage" = 73.73],
					        [#"Sno" = 840, #"AgeGroup" = 51, #"TotalCases" = 182, #"Percentage" = 52.28],
					        [#"Sno" = 43, #"AgeGroup" = 80, #"TotalCases" = 120, #"Percentage" = 77.59],
					        [#"Sno" = 428, #"AgeGroup" = 69, #"TotalCases" = 174, #"Percentage" = 66.81],
					        [#"Sno" = 855, #"AgeGroup" = 24, #"TotalCases" = 798, #"Percentage" = 31.81],
					        [#"Sno" = 175, #"AgeGroup" = 21, #"TotalCases" = 434, #"Percentage" = 32.91],
					        [#"Sno" = 979, #"AgeGroup" = 49, #"TotalCases" = 574, #"Percentage" = 72.0],
					        [#"Sno" = 168, #"AgeGroup" = 21, #"TotalCases" = 617, #"Percentage" = 61.4],
					        [#"Sno" = 634, #"AgeGroup" = 62, #"TotalCases" = 684, #"Percentage" = 0.87],
					        [#"Sno" = 93, #"AgeGroup" = 50, #"TotalCases" = 476, #"Percentage" = 10.91],
					        [#"Sno" = 907, #"AgeGroup" = 35, #"TotalCases" = 425, #"Percentage" = 29.42],
					        [#"Sno" = 505, #"AgeGroup" = 44, #"TotalCases" = 880, #"Percentage" = 34.23],
					        [#"Sno" = 300, #"AgeGroup" = 73, #"TotalCases" = 513, #"Percentage" = 49.32],
					        [#"Sno" = 136, #"AgeGroup" = 21, #"TotalCases" = 551, #"Percentage" = 17.32],
					        [#"Sno" = 270, #"AgeGroup" = 34, #"TotalCases" = 601, #"Percentage" = 52.42],
					        [#"Sno" = 691, #"AgeGroup" = 52, #"TotalCases" = 824, #"Percentage" = 26.67],
					        [#"Sno" = 91, #"AgeGroup" = 65, #"TotalCases" = 618, #"Percentage" = 35.27],
					        [#"Sno" = 658, #"AgeGroup" = 28, #"TotalCases" = 410, #"Percentage" = 63.59],
					        [#"Sno" = 317, #"AgeGroup" = 28, #"TotalCases" = 680, #"Percentage" = 98.52],
					        [#"Sno" = 953, #"AgeGroup" = 24, #"TotalCases" = 136, #"Percentage" = 68.84],
					        [#"Sno" = 322, #"AgeGroup" = 21, #"TotalCases" = 182, #"Percentage" = 24.67],
					        [#"Sno" = 673, #"AgeGroup" = 53, #"TotalCases" = 368, #"Percentage" = 85.49],
					        [#"Sno" = 175, #"AgeGroup" = 46, #"TotalCases" = 724, #"Percentage" = 72.76],
					        [#"Sno" = 612, #"AgeGroup" = 42, #"TotalCases" = 633, #"Percentage" = 26.99],
					        [#"Sno" = 170, #"AgeGroup" = 39, #"TotalCases" = 128, #"Percentage" = 38.9],
					        [#"Sno" = 818, #"AgeGroup" = 55, #"TotalCases" = 730, #"Percentage" = 48.88],
					        [#"Sno" = 383, #"AgeGroup" = 70, #"TotalCases" = 898, #"Percentage" = 94.14],
					        [#"Sno" = 291, #"AgeGroup" = 72, #"TotalCases" = 891, #"Percentage" = 39.27],
					        [#"Sno" = 340, #"AgeGroup" = 24, #"TotalCases" = 152, #"Percentage" = 59.07],
					        [#"Sno" = 862, #"AgeGroup" = 29, #"TotalCases" = 886, #"Percentage" = 93.31],
					        [#"Sno" = 826, #"AgeGroup" = 72, #"TotalCases" = 132, #"Percentage" = 93.77],
					        [#"Sno" = 839, #"AgeGroup" = 76, #"TotalCases" = 781, #"Percentage" = 34.67],
					        [#"Sno" = 926, #"AgeGroup" = 52, #"TotalCases" = 55, #"Percentage" = 24.94],
					        [#"Sno" = 27, #"AgeGroup" = 63, #"TotalCases" = 828, #"Percentage" = 52.65],
					        [#"Sno" = 75, #"AgeGroup" = 45, #"TotalCases" = 594, #"Percentage" = 21.3],
					        [#"Sno" = 168, #"AgeGroup" = 78, #"TotalCases" = 884, #"Percentage" = 42.67],
					        [#"Sno" = 875, #"AgeGroup" = 64, #"TotalCases" = 267, #"Percentage" = 26.09],
					        [#"Sno" = 157, #"AgeGroup" = 42, #"TotalCases" = 294, #"Percentage" = 82.03],
					        [#"Sno" = 391, #"AgeGroup" = 73, #"TotalCases" = 299, #"Percentage" = 76.81],
					        [#"Sno" = 948, #"AgeGroup" = 36, #"TotalCases" = 964, #"Percentage" = 48.3],
					        [#"Sno" = 561, #"AgeGroup" = 80, #"TotalCases" = 528, #"Percentage" = 27.57],
					        [#"Sno" = 220, #"AgeGroup" = 36, #"TotalCases" = 97, #"Percentage" = 79.41],
					        [#"Sno" = 617, #"AgeGroup" = 74, #"TotalCases" = 898, #"Percentage" = 52.77],
					        [#"Sno" = 93, #"AgeGroup" = 58, #"TotalCases" = 796, #"Percentage" = 9.27],
					        [#"Sno" = 7, #"AgeGroup" = 69, #"TotalCases" = 275, #"Percentage" = 37.23],
					        [#"Sno" = 302, #"AgeGroup" = 57, #"TotalCases" = 725, #"Percentage" = 96.73],
					        [#"Sno" = 401, #"AgeGroup" = 23, #"TotalCases" = 950, #"Percentage" = 81.52],
					        [#"Sno" = 854, #"AgeGroup" = 44, #"TotalCases" = 642, #"Percentage" = 96.25],
					        [#"Sno" = 461, #"AgeGroup" = 52, #"TotalCases" = 401, #"Percentage" = 60.36],
					        [#"Sno" = 646, #"AgeGroup" = 61, #"TotalCases" = 675, #"Percentage" = 19.36],
					        [#"Sno" = 566, #"AgeGroup" = 46, #"TotalCases" = 982, #"Percentage" = 40.28],
					        [#"Sno" = 884, #"AgeGroup" = 76, #"TotalCases" = 783, #"Percentage" = 91.1],
					        [#"Sno" = 507, #"AgeGroup" = 40, #"TotalCases" = 783, #"Percentage" = 62.86],
					        [#"Sno" = 571, #"AgeGroup" = 59, #"TotalCases" = 717, #"Percentage" = 12.53],
					        [#"Sno" = 132, #"AgeGroup" = 68, #"TotalCases" = 362, #"Percentage" = 95.01],
					        [#"Sno" = 724, #"AgeGroup" = 53, #"TotalCases" = 112, #"Percentage" = 58.54],
					        [#"Sno" = 73, #"AgeGroup" = 59, #"TotalCases" = 187, #"Percentage" = 33.39],
					        [#"Sno" = 58, #"AgeGroup" = 29, #"TotalCases" = 881, #"Percentage" = 89.26],
					        [#"Sno" = 515, #"AgeGroup" = 73, #"TotalCases" = 738, #"Percentage" = 78.42],
					        [#"Sno" = 664, #"AgeGroup" = 23, #"TotalCases" = 276, #"Percentage" = 28.04],
					        [#"Sno" = 379, #"AgeGroup" = 26, #"TotalCases" = 958, #"Percentage" = 40.75],
					        [#"Sno" = 171, #"AgeGroup" = 78, #"TotalCases" = 856, #"Percentage" = 12.62],
					        [#"Sno" = 87, #"AgeGroup" = 47, #"TotalCases" = 683, #"Percentage" = 44.38],
					        [#"Sno" = 463, #"AgeGroup" = 67, #"TotalCases" = 28, #"Percentage" = 52.74],
					        [#"Sno" = 596, #"AgeGroup" = 69, #"TotalCases" = 360, #"Percentage" = 79.6],
					        [#"Sno" = 939, #"AgeGroup" = 32, #"TotalCases" = 579, #"Percentage" = 26.13],
					        [#"Sno" = 448, #"AgeGroup" = 34, #"TotalCases" = 465, #"Percentage" = 26.45],
					        [#"Sno" = 398, #"AgeGroup" = 22, #"TotalCases" = 176, #"Percentage" = 32.55],
					        [#"Sno" = 440, #"AgeGroup" = 60, #"TotalCases" = 136, #"Percentage" = 57.96],
					        [#"Sno" = 365, #"AgeGroup" = 25, #"TotalCases" = 879, #"Percentage" = 30.38],
					        [#"Sno" = 225, #"AgeGroup" = 46, #"TotalCases" = 503, #"Percentage" = 92.27],
					        [#"Sno" = 287, #"AgeGroup" = 20, #"TotalCases" = 291, #"Percentage" = 55.99],
					        [#"Sno" = 688, #"AgeGroup" = 34, #"TotalCases" = 222, #"Percentage" = 43.82],
					        [#"Sno" = 703, #"AgeGroup" = 48, #"TotalCases" = 790, #"Percentage" = 37.38],
					        [#"Sno" = 81, #"AgeGroup" = 35, #"TotalCases" = 31, #"Percentage" = 37.33],
					        [#"Sno" = 303, #"AgeGroup" = 21, #"TotalCases" = 903, #"Percentage" = 33.56],
					        [#"Sno" = 890, #"AgeGroup" = 35, #"TotalCases" = 9, #"Percentage" = 51.61],
					        [#"Sno" = 748, #"AgeGroup" = 30, #"TotalCases" = 436, #"Percentage" = 93.66],
					        [#"Sno" = 255, #"AgeGroup" = 27, #"TotalCases" = 617, #"Percentage" = 13.35],
					        [#"Sno" = 894, #"AgeGroup" = 45, #"TotalCases" = 83, #"Percentage" = 10.53],
					        [#"Sno" = 498, #"AgeGroup" = 61, #"TotalCases" = 319, #"Percentage" = 85.77],
					        [#"Sno" = 426, #"AgeGroup" = 77, #"TotalCases" = 994, #"Percentage" = 8.31],
					        [#"Sno" = 983, #"AgeGroup" = 42, #"TotalCases" = 469, #"Percentage" = 41.45],
					        [#"Sno" = 89, #"AgeGroup" = 80, #"TotalCases" = 380, #"Percentage" = 52.94],
					        [#"Sno" = 350, #"AgeGroup" = 35, #"TotalCases" = 335, #"Percentage" = 57.87],
					        [#"Sno" = 995, #"AgeGroup" = 31, #"TotalCases" = 261, #"Percentage" = 81.89],
					        [#"Sno" = 801, #"AgeGroup" = 58, #"TotalCases" = 646, #"Percentage" = 31.16],
					        [#"Sno" = 391, #"AgeGroup" = 42, #"TotalCases" = 522, #"Percentage" = 34.54],
					        [#"Sno" = 155, #"AgeGroup" = 65, #"TotalCases" = 323, #"Percentage" = 55.0],
					        [#"Sno" = 19, #"AgeGroup" = 59, #"TotalCases" = 926, #"Percentage" = 97.99],
					        [#"Sno" = 502, #"AgeGroup" = 45, #"TotalCases" = 69, #"Percentage" = 24.84],
					        [#"Sno" = 953, #"AgeGroup" = 76, #"TotalCases" = 954, #"Percentage" = 98.65],
					        [#"Sno" = 340, #"AgeGroup" = 51, #"TotalCases" = 538, #"Percentage" = 54.42],
					        [#"Sno" = 299, #"AgeGroup" = 55, #"TotalCases" = 771, #"Percentage" = 11.44],
					        [#"Sno" = 866, #"AgeGroup" = 66, #"TotalCases" = 314, #"Percentage" = 41.61],
					        [#"Sno" = 237, #"AgeGroup" = 42, #"TotalCases" = 74, #"Percentage" = 34.19],
					        [#"Sno" = 553, #"AgeGroup" = 51, #"TotalCases" = 629, #"Percentage" = 54.84],
					        [#"Sno" = 274, #"AgeGroup" = 32, #"TotalCases" = 154, #"Percentage" = 40.2],
					        [#"Sno" = 714, #"AgeGroup" = 53, #"TotalCases" = 1000, #"Percentage" = 91.23],
					        [#"Sno" = 975, #"AgeGroup" = 41, #"TotalCases" = 464, #"Percentage" = 36.3],
					        [#"Sno" = 256, #"AgeGroup" = 59, #"TotalCases" = 263, #"Percentage" = 59.0],
					        [#"Sno" = 923, #"AgeGroup" = 64, #"TotalCases" = 816, #"Percentage" = 69.55],
					        [#"Sno" = 361, #"AgeGroup" = 74, #"TotalCases" = 337, #"Percentage" = 27.3],
					        [#"Sno" = 614, #"AgeGroup" = 45, #"TotalCases" = 904, #"Percentage" = 76.0],
					        [#"Sno" = 715, #"AgeGroup" = 50, #"TotalCases" = 960, #"Percentage" = 78.32],
					        [#"Sno" = 595, #"AgeGroup" = 32, #"TotalCases" = 599, #"Percentage" = 7.9],
					        [#"Sno" = 395, #"AgeGroup" = 74, #"TotalCases" = 231, #"Percentage" = 11.87],
					        [#"Sno" = 736, #"AgeGroup" = 79, #"TotalCases" = 116, #"Percentage" = 82.59],
					        [#"Sno" = 447, #"AgeGroup" = 52, #"TotalCases" = 269, #"Percentage" = 90.63],
					        [#"Sno" = 678, #"AgeGroup" = 65, #"TotalCases" = 415, #"Percentage" = 55.39],
					        [#"Sno" = 357, #"AgeGroup" = 46, #"TotalCases" = 23, #"Percentage" = 68.49],
					        [#"Sno" = 4, #"AgeGroup" = 23, #"TotalCases" = 612, #"Percentage" = 15.93],
					        [#"Sno" = 861, #"AgeGroup" = 43, #"TotalCases" = 854, #"Percentage" = 97.27],
					        [#"Sno" = 132, #"AgeGroup" = 55, #"TotalCases" = 586, #"Percentage" = 91.85],
					        [#"Sno" = 280, #"AgeGroup" = 21, #"TotalCases" = 941, #"Percentage" = 20.8],
					        [#"Sno" = 15, #"AgeGroup" = 54, #"TotalCases" = 588, #"Percentage" = 29.18],
					        [#"Sno" = 426, #"AgeGroup" = 58, #"TotalCases" = 175, #"Percentage" = 96.3],
					        [#"Sno" = 747, #"AgeGroup" = 42, #"TotalCases" = 103, #"Percentage" = 12.22],
					        [#"Sno" = 437, #"AgeGroup" = 26, #"TotalCases" = 451, #"Percentage" = 41.56],
					        [#"Sno" = 73, #"AgeGroup" = 19, #"TotalCases" = 860, #"Percentage" = 16.14],
					        [#"Sno" = 216, #"AgeGroup" = 38, #"TotalCases" = 269, #"Percentage" = 29.18],
					        [#"Sno" = 873, #"AgeGroup" = 69, #"TotalCases" = 679, #"Percentage" = 44.35],
					        [#"Sno" = 90, #"AgeGroup" = 68, #"TotalCases" = 203, #"Percentage" = 50.22],
					        [#"Sno" = 694, #"AgeGroup" = 75, #"TotalCases" = 737, #"Percentage" = 86.07],
					        [#"Sno" = 9, #"AgeGroup" = 77, #"TotalCases" = 262, #"Percentage" = 96.8],
					        [#"Sno" = 471, #"AgeGroup" = 75, #"TotalCases" = 249, #"Percentage" = 8.49],
					        [#"Sno" = 672, #"AgeGroup" = 30, #"TotalCases" = 812, #"Percentage" = 67.86],
					        [#"Sno" = 825, #"AgeGroup" = 73, #"TotalCases" = 720, #"Percentage" = 89.02],
					        [#"Sno" = 742, #"AgeGroup" = 38, #"TotalCases" = 877, #"Percentage" = 84.88],
					        [#"Sno" = 893, #"AgeGroup" = 62, #"TotalCases" = 827, #"Percentage" = 4.68],
					        [#"Sno" = 971, #"AgeGroup" = 21, #"TotalCases" = 995, #"Percentage" = 42.05],
					        [#"Sno" = 775, #"AgeGroup" = 18, #"TotalCases" = 285, #"Percentage" = 42.07],
					        [#"Sno" = 382, #"AgeGroup" = 63, #"TotalCases" = 709, #"Percentage" = 8.26],
					        [#"Sno" = 421, #"AgeGroup" = 20, #"TotalCases" = 861, #"Percentage" = 72.42],
					        [#"Sno" = 517, #"AgeGroup" = 27, #"TotalCases" = 819, #"Percentage" = 96.55],
					        [#"Sno" = 964, #"AgeGroup" = 66, #"TotalCases" = 507, #"Percentage" = 64.65],
					        [#"Sno" = 729, #"AgeGroup" = 69, #"TotalCases" = 131, #"Percentage" = 65.67],
					        [#"Sno" = 794, #"AgeGroup" = 26, #"TotalCases" = 259, #"Percentage" = 50.87],
					        [#"Sno" = 236, #"AgeGroup" = 68, #"TotalCases" = 211, #"Percentage" = 10.65],
					        [#"Sno" = 785, #"AgeGroup" = 19, #"TotalCases" = 400, #"Percentage" = 1.77],
					        [#"Sno" = 961, #"AgeGroup" = 60, #"TotalCases" = 994, #"Percentage" = 5.1],
					        [#"Sno" = 929, #"AgeGroup" = 27, #"TotalCases" = 683, #"Percentage" = 72.67],
					        [#"Sno" = 354, #"AgeGroup" = 31, #"TotalCases" = 399, #"Percentage" = 17.65],
					        [#"Sno" = 778, #"AgeGroup" = 73, #"TotalCases" = 404, #"Percentage" = 74.95],
					        [#"Sno" = 479, #"AgeGroup" = 27, #"TotalCases" = 530, #"Percentage" = 49.59],
					        [#"Sno" = 752, #"AgeGroup" = 76, #"TotalCases" = 431, #"Percentage" = 25.3],
					        [#"Sno" = 541, #"AgeGroup" = 30, #"TotalCases" = 896, #"Percentage" = 72.54],
					        [#"Sno" = 710, #"AgeGroup" = 73, #"TotalCases" = 780, #"Percentage" = 24.98],
					        [#"Sno" = 264, #"AgeGroup" = 55, #"TotalCases" = 925, #"Percentage" = 32.21],
					        [#"Sno" = 474, #"AgeGroup" = 52, #"TotalCases" = 516, #"Percentage" = 41.38],
					        [#"Sno" = 954, #"AgeGroup" = 80, #"TotalCases" = 811, #"Percentage" = 26.83],
					        [#"Sno" = 253, #"AgeGroup" = 45, #"TotalCases" = 247, #"Percentage" = 77.92],
					        [#"Sno" = 409, #"AgeGroup" = 45, #"TotalCases" = 721, #"Percentage" = 0.95],
					        [#"Sno" = 4, #"AgeGroup" = 23, #"TotalCases" = 264, #"Percentage" = 62.73],
					        [#"Sno" = 502, #"AgeGroup" = 73, #"TotalCases" = 514, #"Percentage" = 49.33],
					        [#"Sno" = 310, #"AgeGroup" = 46, #"TotalCases" = 540, #"Percentage" = 28.89],
					        [#"Sno" = 705, #"AgeGroup" = 79, #"TotalCases" = 241, #"Percentage" = 37.81],
					        [#"Sno" = 561, #"AgeGroup" = 50, #"TotalCases" = 376, #"Percentage" = 72.91],
					        [#"Sno" = 744, #"AgeGroup" = 37, #"TotalCases" = 970, #"Percentage" = 75.44],
					        [#"Sno" = 527, #"AgeGroup" = 73, #"TotalCases" = 847, #"Percentage" = 46.87],
					        [#"Sno" = 631, #"AgeGroup" = 62, #"TotalCases" = 208, #"Percentage" = 68.72],
					        [#"Sno" = 575, #"AgeGroup" = 49, #"TotalCases" = 837, #"Percentage" = 12.12],
					        [#"Sno" = 695, #"AgeGroup" = 34, #"TotalCases" = 206, #"Percentage" = 77.67],
					        [#"Sno" = 448, #"AgeGroup" = 48, #"TotalCases" = 340, #"Percentage" = 53.56],
					        [#"Sno" = 785, #"AgeGroup" = 54, #"TotalCases" = 757, #"Percentage" = 93.01],
					        [#"Sno" = 216, #"AgeGroup" = 46, #"TotalCases" = 708, #"Percentage" = 86.18],
					        [#"Sno" = 721, #"AgeGroup" = 61, #"TotalCases" = 952, #"Percentage" = 66.47],
					        [#"Sno" = 585, #"AgeGroup" = 63, #"TotalCases" = 432, #"Percentage" = 35.22],
					        [#"Sno" = 600, #"AgeGroup" = 59, #"TotalCases" = 604, #"Percentage" = 38.84],
					        [#"Sno" = 797, #"AgeGroup" = 30, #"TotalCases" = 401, #"Percentage" = 72.73],
					        [#"Sno" = 180, #"AgeGroup" = 27, #"TotalCases" = 955, #"Percentage" = 6.89],
					        [#"Sno" = 654, #"AgeGroup" = 52, #"TotalCases" = 258, #"Percentage" = 97.89],
					        [#"Sno" = 960, #"AgeGroup" = 61, #"TotalCases" = 192, #"Percentage" = 41.12],
					        [#"Sno" = 712, #"AgeGroup" = 21, #"TotalCases" = 100, #"Percentage" = 20.86],
					        [#"Sno" = 704, #"AgeGroup" = 41, #"TotalCases" = 65, #"Percentage" = 95.66],
					        [#"Sno" = 712, #"AgeGroup" = 62, #"TotalCases" = 780, #"Percentage" = 69.5],
					        [#"Sno" = 286, #"AgeGroup" = 50, #"TotalCases" = 822, #"Percentage" = 21.36],
					        [#"Sno" = 10, #"AgeGroup" = 80, #"TotalCases" = 547, #"Percentage" = 40.57],
					        [#"Sno" = 395, #"AgeGroup" = 20, #"TotalCases" = 939, #"Percentage" = 44.99],
					        [#"Sno" = 206, #"AgeGroup" = 28, #"TotalCases" = 532, #"Percentage" = 42.71],
					        [#"Sno" = 53, #"AgeGroup" = 53, #"TotalCases" = 473, #"Percentage" = 27.45],
					        [#"Sno" = 615, #"AgeGroup" = 78, #"TotalCases" = 189, #"Percentage" = 76.78],
					        [#"Sno" = 569, #"AgeGroup" = 52, #"TotalCases" = 35, #"Percentage" = 90.57],
					        [#"Sno" = 875, #"AgeGroup" = 72, #"TotalCases" = 860, #"Percentage" = 55.22],
					        [#"Sno" = 535, #"AgeGroup" = 47, #"TotalCases" = 875, #"Percentage" = 84.06],
					        [#"Sno" = 253, #"AgeGroup" = 41, #"TotalCases" = 571, #"Percentage" = 42.49],
					        [#"Sno" = 684, #"AgeGroup" = 29, #"TotalCases" = 43, #"Percentage" = 96.0],
					        [#"Sno" = 467, #"AgeGroup" = 56, #"TotalCases" = 690, #"Percentage" = 9.2],
					        [#"Sno" = 792, #"AgeGroup" = 41, #"TotalCases" = 35, #"Percentage" = 15.97],
					        [#"Sno" = 609, #"AgeGroup" = 43, #"TotalCases" = 535, #"Percentage" = 45.76],
					        [#"Sno" = 358, #"AgeGroup" = 44, #"TotalCases" = 530, #"Percentage" = 9.81],
					        [#"Sno" = 287, #"AgeGroup" = 74, #"TotalCases" = 331, #"Percentage" = 17.92],
					        [#"Sno" = 712, #"AgeGroup" = 34, #"TotalCases" = 631, #"Percentage" = 86.77],
					        [#"Sno" = 752, #"AgeGroup" = 62, #"TotalCases" = 885, #"Percentage" = 6.36],
					        [#"Sno" = 323, #"AgeGroup" = 78, #"TotalCases" = 632, #"Percentage" = 17.27],
					        [#"Sno" = 874, #"AgeGroup" = 79, #"TotalCases" = 189, #"Percentage" = 89.2],
					        [#"Sno" = 893, #"AgeGroup" = 65, #"TotalCases" = 269, #"Percentage" = 70.67],
					        [#"Sno" = 879, #"AgeGroup" = 39, #"TotalCases" = 403, #"Percentage" = 63.15],
					        [#"Sno" = 852, #"AgeGroup" = 75, #"TotalCases" = 826, #"Percentage" = 87.29],
					        [#"Sno" = 399, #"AgeGroup" = 37, #"TotalCases" = 479, #"Percentage" = 8.48],
					        [#"Sno" = 339, #"AgeGroup" = 63, #"TotalCases" = 610, #"Percentage" = 32.57],
					        [#"Sno" = 759, #"AgeGroup" = 50, #"TotalCases" = 299, #"Percentage" = 82.42],
					        [#"Sno" = 402, #"AgeGroup" = 42, #"TotalCases" = 454, #"Percentage" = 23.49],
					        [#"Sno" = 555, #"AgeGroup" = 67, #"TotalCases" = 87, #"Percentage" = 89.21],
					        [#"Sno" = 177, #"AgeGroup" = 65, #"TotalCases" = 379, #"Percentage" = 27.95],
					        [#"Sno" = 664, #"AgeGroup" = 42, #"TotalCases" = 941, #"Percentage" = 57.98],
					        [#"Sno" = 644, #"AgeGroup" = 27, #"TotalCases" = 439, #"Percentage" = 99.85],
					        [#"Sno" = 245, #"AgeGroup" = 56, #"TotalCases" = 395, #"Percentage" = 39.13],
					        [#"Sno" = 727, #"AgeGroup" = 48, #"TotalCases" = 10, #"Percentage" = 93.83],
					        [#"Sno" = 935, #"AgeGroup" = 50, #"TotalCases" = 841, #"Percentage" = 32.42],
					        [#"Sno" = 190, #"AgeGroup" = 31, #"TotalCases" = 685, #"Percentage" = 89.62],
					        [#"Sno" = 279, #"AgeGroup" = 50, #"TotalCases" = 954, #"Percentage" = 84.65],
					        [#"Sno" = 443, #"AgeGroup" = 54, #"TotalCases" = 953, #"Percentage" = 74.53],
					        [#"Sno" = 376, #"AgeGroup" = 74, #"TotalCases" = 463, #"Percentage" = 77.86],
					        [#"Sno" = 142, #"AgeGroup" = 57, #"TotalCases" = 942, #"Percentage" = 59.7],
					        [#"Sno" = 244, #"AgeGroup" = 39, #"TotalCases" = 980, #"Percentage" = 46.88],
					        [#"Sno" = 240, #"AgeGroup" = 61, #"TotalCases" = 455, #"Percentage" = 77.2],
					        [#"Sno" = 757, #"AgeGroup" = 57, #"TotalCases" = 217, #"Percentage" = 22.26],
					        [#"Sno" = 160, #"AgeGroup" = 25, #"TotalCases" = 528, #"Percentage" = 36.55],
					        [#"Sno" = 460, #"AgeGroup" = 25, #"TotalCases" = 995, #"Percentage" = 51.33],
					        [#"Sno" = 310, #"AgeGroup" = 28, #"TotalCases" = 597, #"Percentage" = 75.3],
					        [#"Sno" = 955, #"AgeGroup" = 44, #"TotalCases" = 114, #"Percentage" = 2.89],
					        [#"Sno" = 458, #"AgeGroup" = 73, #"TotalCases" = 842, #"Percentage" = 33.08],
					        [#"Sno" = 565, #"AgeGroup" = 25, #"TotalCases" = 400, #"Percentage" = 9.71],
					        [#"Sno" = 374, #"AgeGroup" = 22, #"TotalCases" = 458, #"Percentage" = 68.26],
					        [#"Sno" = 730, #"AgeGroup" = 34, #"TotalCases" = 719, #"Percentage" = 5.42],
					        [#"Sno" = 766, #"AgeGroup" = 73, #"TotalCases" = 186, #"Percentage" = 72.3],
					        [#"Sno" = 93, #"AgeGroup" = 50, #"TotalCases" = 373, #"Percentage" = 58.39],
					        [#"Sno" = 312, #"AgeGroup" = 73, #"TotalCases" = 249, #"Percentage" = 67.53],
					        [#"Sno" = 16, #"AgeGroup" = 33, #"TotalCases" = 916, #"Percentage" = 12.52],
					        [#"Sno" = 593, #"AgeGroup" = 39, #"TotalCases" = 10, #"Percentage" = 2.68],
					        [#"Sno" = 887, #"AgeGroup" = 34, #"TotalCases" = 953, #"Percentage" = 66.19],
					        [#"Sno" = 635, #"AgeGroup" = 33, #"TotalCases" = 33, #"Percentage" = 19.76],
					        [#"Sno" = 862, #"AgeGroup" = 41, #"TotalCases" = 76, #"Percentage" = 7.2],
					        [#"Sno" = 571, #"AgeGroup" = 57, #"TotalCases" = 795, #"Percentage" = 97.93],
					        [#"Sno" = 147, #"AgeGroup" = 80, #"TotalCases" = 553, #"Percentage" = 94.79],
					        [#"Sno" = 696, #"AgeGroup" = 50, #"TotalCases" = 923, #"Percentage" = 84.88],
					        [#"Sno" = 885, #"AgeGroup" = 26, #"TotalCases" = 390, #"Percentage" = 37.12],
					        [#"Sno" = 712, #"AgeGroup" = 66, #"TotalCases" = 761, #"Percentage" = 17.52],
					        [#"Sno" = 949, #"AgeGroup" = 76, #"TotalCases" = 423, #"Percentage" = 43.89],
					        [#"Sno" = 63, #"AgeGroup" = 73, #"TotalCases" = 130, #"Percentage" = 66.17],
					        [#"Sno" = 443, #"AgeGroup" = 37, #"TotalCases" = 503, #"Percentage" = 15.93],
					        [#"Sno" = 801, #"AgeGroup" = 19, #"TotalCases" = 422, #"Percentage" = 19.81],
					        [#"Sno" = 104, #"AgeGroup" = 68, #"TotalCases" = 993, #"Percentage" = 65.08],
					        [#"Sno" = 830, #"AgeGroup" = 63, #"TotalCases" = 842, #"Percentage" = 40.07],
					        [#"Sno" = 39, #"AgeGroup" = 49, #"TotalCases" = 186, #"Percentage" = 66.66],
					        [#"Sno" = 235, #"AgeGroup" = 54, #"TotalCases" = 116, #"Percentage" = 40.68],
					        [#"Sno" = 892, #"AgeGroup" = 76, #"TotalCases" = 818, #"Percentage" = 56.43],
					        [#"Sno" = 458, #"AgeGroup" = 45, #"TotalCases" = 1000, #"Percentage" = 27.81],
					        [#"Sno" = 784, #"AgeGroup" = 52, #"TotalCases" = 826, #"Percentage" = 74.82],
					        [#"Sno" = 583, #"AgeGroup" = 63, #"TotalCases" = 46, #"Percentage" = 73.02],
					        [#"Sno" = 120, #"AgeGroup" = 40, #"TotalCases" = 999, #"Percentage" = 78.49],
					        [#"Sno" = 756, #"AgeGroup" = 66, #"TotalCases" = 334, #"Percentage" = 6.45],
					        [#"Sno" = 838, #"AgeGroup" = 72, #"TotalCases" = 600, #"Percentage" = 28.01],
					        [#"Sno" = 773, #"AgeGroup" = 54, #"TotalCases" = 59, #"Percentage" = 45.82],
					        [#"Sno" = 553, #"AgeGroup" = 31, #"TotalCases" = 978, #"Percentage" = 31.81],
					        [#"Sno" = 958, #"AgeGroup" = 59, #"TotalCases" = 409, #"Percentage" = 6.96],
					        [#"Sno" = 435, #"AgeGroup" = 60, #"TotalCases" = 459, #"Percentage" = 60.58],
					        [#"Sno" = 159, #"AgeGroup" = 30, #"TotalCases" = 658, #"Percentage" = 73.03],
					        [#"Sno" = 671, #"AgeGroup" = 37, #"TotalCases" = 128, #"Percentage" = 62.21],
					        [#"Sno" = 862, #"AgeGroup" = 79, #"TotalCases" = 628, #"Percentage" = 0.92],
					        [#"Sno" = 381, #"AgeGroup" = 42, #"TotalCases" = 756, #"Percentage" = 61.26],
					        [#"Sno" = 246, #"AgeGroup" = 36, #"TotalCases" = 700, #"Percentage" = 18.23],
					        [#"Sno" = 63, #"AgeGroup" = 21, #"TotalCases" = 840, #"Percentage" = 53.42],
					        [#"Sno" = 429, #"AgeGroup" = 19, #"TotalCases" = 921, #"Percentage" = 20.83],
					        [#"Sno" = 15, #"AgeGroup" = 26, #"TotalCases" = 113, #"Percentage" = 8.3],
					        [#"Sno" = 422, #"AgeGroup" = 75, #"TotalCases" = 504, #"Percentage" = 32.68],
					        [#"Sno" = 946, #"AgeGroup" = 54, #"TotalCases" = 170, #"Percentage" = 9.79],
					        [#"Sno" = 945, #"AgeGroup" = 70, #"TotalCases" = 919, #"Percentage" = 60.81],
					        [#"Sno" = 561, #"AgeGroup" = 30, #"TotalCases" = 524, #"Percentage" = 91.54],
					        [#"Sno" = 82, #"AgeGroup" = 49, #"TotalCases" = 995, #"Percentage" = 59.19],
					        [#"Sno" = 679, #"AgeGroup" = 70, #"TotalCases" = 5, #"Percentage" = 14.27],
					        [#"Sno" = 978, #"AgeGroup" = 69, #"TotalCases" = 914, #"Percentage" = 3.17],
					        [#"Sno" = 396, #"AgeGroup" = 71, #"TotalCases" = 102, #"Percentage" = 75.48],
					        [#"Sno" = 706, #"AgeGroup" = 46, #"TotalCases" = 404, #"Percentage" = 65.59],
					        [#"Sno" = 649, #"AgeGroup" = 21, #"TotalCases" = 259, #"Percentage" = 4.72],
					        [#"Sno" = 669, #"AgeGroup" = 68, #"TotalCases" = 372, #"Percentage" = 42.19],
					        [#"Sno" = 46, #"AgeGroup" = 49, #"TotalCases" = 585, #"Percentage" = 98.68],
					        [#"Sno" = 164, #"AgeGroup" = 41, #"TotalCases" = 547, #"Percentage" = 77.98],
					        [#"Sno" = 407, #"AgeGroup" = 67, #"TotalCases" = 72, #"Percentage" = 92.58],
					        [#"Sno" = 345, #"AgeGroup" = 43, #"TotalCases" = 291, #"Percentage" = 48.19],
					        [#"Sno" = 926, #"AgeGroup" = 26, #"TotalCases" = 476, #"Percentage" = 78.72],
					        [#"Sno" = 322, #"AgeGroup" = 73, #"TotalCases" = 945, #"Percentage" = 98.58],
					        [#"Sno" = 367, #"AgeGroup" = 72, #"TotalCases" = 58, #"Percentage" = 61.61],
					        [#"Sno" = 726, #"AgeGroup" = 74, #"TotalCases" = 454, #"Percentage" = 92.95],
					        [#"Sno" = 630, #"AgeGroup" = 63, #"TotalCases" = 241, #"Percentage" = 8.73],
					        [#"Sno" = 475, #"AgeGroup" = 40, #"TotalCases" = 840, #"Percentage" = 76.33],
					        [#"Sno" = 767, #"AgeGroup" = 62, #"TotalCases" = 145, #"Percentage" = 7.25],
					        [#"Sno" = 305, #"AgeGroup" = 41, #"TotalCases" = 457, #"Percentage" = 11.4],
					        [#"Sno" = 862, #"AgeGroup" = 66, #"TotalCases" = 82, #"Percentage" = 49.63],
					        [#"Sno" = 251, #"AgeGroup" = 49, #"TotalCases" = 398, #"Percentage" = 6.47],
					        [#"Sno" = 210, #"AgeGroup" = 23, #"TotalCases" = 744, #"Percentage" = 16.49],
					        [#"Sno" = 796, #"AgeGroup" = 52, #"TotalCases" = 46, #"Percentage" = 41.74],
					        [#"Sno" = 801, #"AgeGroup" = 42, #"TotalCases" = 457, #"Percentage" = 61.92],
					        [#"Sno" = 680, #"AgeGroup" = 79, #"TotalCases" = 336, #"Percentage" = 97.63],
					        [#"Sno" = 874, #"AgeGroup" = 38, #"TotalCases" = 716, #"Percentage" = 32.51],
					        [#"Sno" = 385, #"AgeGroup" = 60, #"TotalCases" = 646, #"Percentage" = 59.38],
					        [#"Sno" = 913, #"AgeGroup" = 64, #"TotalCases" = 628, #"Percentage" = 67.23],
					        [#"Sno" = 149, #"AgeGroup" = 58, #"TotalCases" = 51, #"Percentage" = 2.14],
					        [#"Sno" = 911, #"AgeGroup" = 45, #"TotalCases" = 237, #"Percentage" = 43.84],
					        [#"Sno" = 318, #"AgeGroup" = 35, #"TotalCases" = 319, #"Percentage" = 27.87],
					        [#"Sno" = 21, #"AgeGroup" = 27, #"TotalCases" = 352, #"Percentage" = 42.27],
					        [#"Sno" = 179, #"AgeGroup" = 80, #"TotalCases" = 660, #"Percentage" = 0.26],
					        [#"Sno" = 586, #"AgeGroup" = 38, #"TotalCases" = 390, #"Percentage" = 18.18],
					        [#"Sno" = 139, #"AgeGroup" = 26, #"TotalCases" = 382, #"Percentage" = 66.87],
					        [#"Sno" = 121, #"AgeGroup" = 28, #"TotalCases" = 481, #"Percentage" = 34.97],
					        [#"Sno" = 232, #"AgeGroup" = 32, #"TotalCases" = 354, #"Percentage" = 19.23],
					        [#"Sno" = 827, #"AgeGroup" = 40, #"TotalCases" = 339, #"Percentage" = 3.91],
					        [#"Sno" = 900, #"AgeGroup" = 23, #"TotalCases" = 404, #"Percentage" = 27.48],
					        [#"Sno" = 178, #"AgeGroup" = 24, #"TotalCases" = 921, #"Percentage" = 35.42],
					        [#"Sno" = 516, #"AgeGroup" = 57, #"TotalCases" = 211, #"Percentage" = 39.18],
					        [#"Sno" = 923, #"AgeGroup" = 37, #"TotalCases" = 594, #"Percentage" = 59.52],
					        [#"Sno" = 234, #"AgeGroup" = 50, #"TotalCases" = 707, #"Percentage" = 34.95],
					        [#"Sno" = 842, #"AgeGroup" = 36, #"TotalCases" = 881, #"Percentage" = 19.84],
					        [#"Sno" = 339, #"AgeGroup" = 39, #"TotalCases" = 894, #"Percentage" = 43.36],
					        [#"Sno" = 708, #"AgeGroup" = 28, #"TotalCases" = 269, #"Percentage" = 36.55],
					        [#"Sno" = 113, #"AgeGroup" = 51, #"TotalCases" = 53, #"Percentage" = 80.93],
					        [#"Sno" = 477, #"AgeGroup" = 34, #"TotalCases" = 371, #"Percentage" = 67.6],
					        [#"Sno" = 871, #"AgeGroup" = 75, #"TotalCases" = 338, #"Percentage" = 57.52],
					        [#"Sno" = 478, #"AgeGroup" = 24, #"TotalCases" = 975, #"Percentage" = 11.41],
					        [#"Sno" = 554, #"AgeGroup" = 41, #"TotalCases" = 685, #"Percentage" = 11.19],
					        [#"Sno" = 435, #"AgeGroup" = 76, #"TotalCases" = 550, #"Percentage" = 26.43],
					        [#"Sno" = 193, #"AgeGroup" = 29, #"TotalCases" = 476, #"Percentage" = 5.08],
					        [#"Sno" = 632, #"AgeGroup" = 68, #"TotalCases" = 440, #"Percentage" = 66.21],
					        [#"Sno" = 724, #"AgeGroup" = 55, #"TotalCases" = 402, #"Percentage" = 36.64],
					        [#"Sno" = 31, #"AgeGroup" = 24, #"TotalCases" = 740, #"Percentage" = 51.21],
					        [#"Sno" = 782, #"AgeGroup" = 76, #"TotalCases" = 927, #"Percentage" = 41.75],
					        [#"Sno" = 852, #"AgeGroup" = 60, #"TotalCases" = 581, #"Percentage" = 27.03],
					        [#"Sno" = 428, #"AgeGroup" = 46, #"TotalCases" = 703, #"Percentage" = 84.93],
					        [#"Sno" = 763, #"AgeGroup" = 64, #"TotalCases" = 315, #"Percentage" = 19.94],
					        [#"Sno" = 235, #"AgeGroup" = 58, #"TotalCases" = 180, #"Percentage" = 2.94],
					        [#"Sno" = 519, #"AgeGroup" = 79, #"TotalCases" = 473, #"Percentage" = 19.51],
					        [#"Sno" = 420, #"AgeGroup" = 58, #"TotalCases" = 622, #"Percentage" = 88.53],
					        [#"Sno" = 866, #"AgeGroup" = 39, #"TotalCases" = 948, #"Percentage" = 2.24],
					        [#"Sno" = 986, #"AgeGroup" = 26, #"TotalCases" = 237, #"Percentage" = 60.83],
					        [#"Sno" = 855, #"AgeGroup" = 40, #"TotalCases" = 773, #"Percentage" = 58.53],
					        [#"Sno" = 190, #"AgeGroup" = 22, #"TotalCases" = 893, #"Percentage" = 48.76],
					        [#"Sno" = 409, #"AgeGroup" = 67, #"TotalCases" = 36, #"Percentage" = 15.6],
					        [#"Sno" = 220, #"AgeGroup" = 52, #"TotalCases" = 629, #"Percentage" = 83.94],
					        [#"Sno" = 88, #"AgeGroup" = 42, #"TotalCases" = 465, #"Percentage" = 86.18],
					        [#"Sno" = 261, #"AgeGroup" = 58, #"TotalCases" = 838, #"Percentage" = 68.89],
					        [#"Sno" = 229, #"AgeGroup" = 60, #"TotalCases" = 223, #"Percentage" = 98.25],
					        [#"Sno" = 184, #"AgeGroup" = 20, #"TotalCases" = 28, #"Percentage" = 79.7],
					        [#"Sno" = 596, #"AgeGroup" = 63, #"TotalCases" = 391, #"Percentage" = 91.28],
					        [#"Sno" = 468, #"AgeGroup" = 33, #"TotalCases" = 691, #"Percentage" = 33.55],
					        [#"Sno" = 598, #"AgeGroup" = 71, #"TotalCases" = 185, #"Percentage" = 98.23],
					        [#"Sno" = 962, #"AgeGroup" = 49, #"TotalCases" = 215, #"Percentage" = 47.55],
					        [#"Sno" = 496, #"AgeGroup" = 33, #"TotalCases" = 537, #"Percentage" = 12.22],
					        [#"Sno" = 393, #"AgeGroup" = 68, #"TotalCases" = 923, #"Percentage" = 40.31],
					        [#"Sno" = 422, #"AgeGroup" = 31, #"TotalCases" = 721, #"Percentage" = 38.42],
					        [#"Sno" = 433, #"AgeGroup" = 37, #"TotalCases" = 506, #"Percentage" = 48.82],
					        [#"Sno" = 322, #"AgeGroup" = 69, #"TotalCases" = 431, #"Percentage" = 4.25],
					        [#"Sno" = 879, #"AgeGroup" = 33, #"TotalCases" = 313, #"Percentage" = 46.01],
					        [#"Sno" = 66, #"AgeGroup" = 21, #"TotalCases" = 242, #"Percentage" = 1.94],
					        [#"Sno" = 779, #"AgeGroup" = 76, #"TotalCases" = 1, #"Percentage" = 47.55],
					        [#"Sno" = 656, #"AgeGroup" = 27, #"TotalCases" = 575, #"Percentage" = 80.57],
					        [#"Sno" = 620, #"AgeGroup" = 69, #"TotalCases" = 430, #"Percentage" = 53.58],
					        [#"Sno" = 184, #"AgeGroup" = 43, #"TotalCases" = 862, #"Percentage" = 37.56],
					        [#"Sno" = 970, #"AgeGroup" = 25, #"TotalCases" = 809, #"Percentage" = 30.73],
					        [#"Sno" = 212, #"AgeGroup" = 45, #"TotalCases" = 429, #"Percentage" = 47.44],
					        [#"Sno" = 406, #"AgeGroup" = 33, #"TotalCases" = 710, #"Percentage" = 57.42],
					        [#"Sno" = 948, #"AgeGroup" = 65, #"TotalCases" = 619, #"Percentage" = 30.74],
					        [#"Sno" = 114, #"AgeGroup" = 33, #"TotalCases" = 42, #"Percentage" = 44.52],
					        [#"Sno" = 841, #"AgeGroup" = 58, #"TotalCases" = 826, #"Percentage" = 44.22],
					        [#"Sno" = 20, #"AgeGroup" = 27, #"TotalCases" = 777, #"Percentage" = 55.29],
					        [#"Sno" = 293, #"AgeGroup" = 67, #"TotalCases" = 68, #"Percentage" = 68.6],
					        [#"Sno" = 726, #"AgeGroup" = 80, #"TotalCases" = 88, #"Percentage" = 70.04],
					        [#"Sno" = 168, #"AgeGroup" = 46, #"TotalCases" = 111, #"Percentage" = 63.15],
					        [#"Sno" = 732, #"AgeGroup" = 37, #"TotalCases" = 389, #"Percentage" = 67.98],
					        [#"Sno" = 968, #"AgeGroup" = 69, #"TotalCases" = 293, #"Percentage" = 33.76],
					        [#"Sno" = 41, #"AgeGroup" = 18, #"TotalCases" = 562, #"Percentage" = 68.13],
					        [#"Sno" = 188, #"AgeGroup" = 44, #"TotalCases" = 127, #"Percentage" = 74.9],
					        [#"Sno" = 727, #"AgeGroup" = 41, #"TotalCases" = 724, #"Percentage" = 73.51],
					        [#"Sno" = 243, #"AgeGroup" = 75, #"TotalCases" = 859, #"Percentage" = 74.04],
					        [#"Sno" = 144, #"AgeGroup" = 45, #"TotalCases" = 850, #"Percentage" = 67.31],
					        [#"Sno" = 811, #"AgeGroup" = 21, #"TotalCases" = 945, #"Percentage" = 90.87],
					        [#"Sno" = 89, #"AgeGroup" = 40, #"TotalCases" = 188, #"Percentage" = 10.63],
					        [#"Sno" = 833, #"AgeGroup" = 71, #"TotalCases" = 970, #"Percentage" = 12.48],
					        [#"Sno" = 20, #"AgeGroup" = 52, #"TotalCases" = 597, #"Percentage" = 71.78],
					        [#"Sno" = 382, #"AgeGroup" = 53, #"TotalCases" = 83, #"Percentage" = 80.43],
					        [#"Sno" = 173, #"AgeGroup" = 71, #"TotalCases" = 858, #"Percentage" = 12.34],
					        [#"Sno" = 289, #"AgeGroup" = 70, #"TotalCases" = 896, #"Percentage" = 59.76],
					        [#"Sno" = 383, #"AgeGroup" = 53, #"TotalCases" = 819, #"Percentage" = 45.07],
					        [#"Sno" = 969, #"AgeGroup" = 36, #"TotalCases" = 226, #"Percentage" = 73.09],
					        [#"Sno" = 491, #"AgeGroup" = 49, #"TotalCases" = 802, #"Percentage" = 18.56],
					        [#"Sno" = 623, #"AgeGroup" = 26, #"TotalCases" = 577, #"Percentage" = 24.25],
					        [#"Sno" = 2, #"AgeGroup" = 78, #"TotalCases" = 919, #"Percentage" = 89.65],
					        [#"Sno" = 3, #"AgeGroup" = 68, #"TotalCases" = 79, #"Percentage" = 1.07],
					        [#"Sno" = 146, #"AgeGroup" = 22, #"TotalCases" = 218, #"Percentage" = 75.19],
					        [#"Sno" = 25, #"AgeGroup" = 51, #"TotalCases" = 578, #"Percentage" = 10.55],
					        [#"Sno" = 474, #"AgeGroup" = 43, #"TotalCases" = 447, #"Percentage" = 28.18],
					        [#"Sno" = 807, #"AgeGroup" = 57, #"TotalCases" = 745, #"Percentage" = 72.07],
					        [#"Sno" = 993, #"AgeGroup" = 41, #"TotalCases" = 530, #"Percentage" = 91.32],
					        [#"Sno" = 620, #"AgeGroup" = 62, #"TotalCases" = 571, #"Percentage" = 40.89],
					        [#"Sno" = 967, #"AgeGroup" = 63, #"TotalCases" = 720, #"Percentage" = 77.56],
					        [#"Sno" = 83, #"AgeGroup" = 68, #"TotalCases" = 712, #"Percentage" = 19.86],
					        [#"Sno" = 782, #"AgeGroup" = 25, #"TotalCases" = 276, #"Percentage" = 11.21],
					        [#"Sno" = 432, #"AgeGroup" = 60, #"TotalCases" = 105, #"Percentage" = 98.29],
					        [#"Sno" = 196, #"AgeGroup" = 60, #"TotalCases" = 751, #"Percentage" = 95.59],
					        [#"Sno" = 979, #"AgeGroup" = 80, #"TotalCases" = 180, #"Percentage" = 17.55],
					        [#"Sno" = 274, #"AgeGroup" = 51, #"TotalCases" = 581, #"Percentage" = 31.03],
					        [#"Sno" = 97, #"AgeGroup" = 48, #"TotalCases" = 343, #"Percentage" = 62.69],
					        [#"Sno" = 178, #"AgeGroup" = 28, #"TotalCases" = 307, #"Percentage" = 89.66],
					        [#"Sno" = 406, #"AgeGroup" = 62, #"TotalCases" = 717, #"Percentage" = 65.33],
					        [#"Sno" = 524, #"AgeGroup" = 35, #"TotalCases" = 799, #"Percentage" = 80.98],
					        [#"Sno" = 217, #"AgeGroup" = 79, #"TotalCases" = 116, #"Percentage" = 77.36],
					        [#"Sno" = 362, #"AgeGroup" = 58, #"TotalCases" = 191, #"Percentage" = 44.97],
					        [#"Sno" = 905, #"AgeGroup" = 35, #"TotalCases" = 654, #"Percentage" = 48.81],
					        [#"Sno" = 27, #"AgeGroup" = 22, #"TotalCases" = 119, #"Percentage" = 24.42],
					        [#"Sno" = 981, #"AgeGroup" = 44, #"TotalCases" = 683, #"Percentage" = 94.51],
					        [#"Sno" = 205, #"AgeGroup" = 37, #"TotalCases" = 194, #"Percentage" = 43.32],
					        [#"Sno" = 953, #"AgeGroup" = 48, #"TotalCases" = 508, #"Percentage" = 33.08],
					        [#"Sno" = 794, #"AgeGroup" = 32, #"TotalCases" = 761, #"Percentage" = 79.08],
					        [#"Sno" = 56, #"AgeGroup" = 76, #"TotalCases" = 205, #"Percentage" = 50.56],
					        [#"Sno" = 13, #"AgeGroup" = 55, #"TotalCases" = 49, #"Percentage" = 96.95],
					        [#"Sno" = 331, #"AgeGroup" = 25, #"TotalCases" = 696, #"Percentage" = 37.96],
					        [#"Sno" = 259, #"AgeGroup" = 69, #"TotalCases" = 762, #"Percentage" = 7.31],
					        [#"Sno" = 692, #"AgeGroup" = 45, #"TotalCases" = 643, #"Percentage" = 16.19],
					        [#"Sno" = 668, #"AgeGroup" = 76, #"TotalCases" = 138, #"Percentage" = 64.09],
					        [#"Sno" = 596, #"AgeGroup" = 58, #"TotalCases" = 492, #"Percentage" = 90.41],
					        [#"Sno" = 311, #"AgeGroup" = 57, #"TotalCases" = 702, #"Percentage" = 46.09],
					        [#"Sno" = 343, #"AgeGroup" = 69, #"TotalCases" = 84, #"Percentage" = 4.45],
					        [#"Sno" = 35, #"AgeGroup" = 27, #"TotalCases" = 876, #"Percentage" = 25.65],
					        [#"Sno" = 409, #"AgeGroup" = 35, #"TotalCases" = 887, #"Percentage" = 16.07],
					        [#"Sno" = 714, #"AgeGroup" = 65, #"TotalCases" = 376, #"Percentage" = 78.09],
					        [#"Sno" = 732, #"AgeGroup" = 39, #"TotalCases" = 952, #"Percentage" = 75.93],
					        [#"Sno" = 683, #"AgeGroup" = 30, #"TotalCases" = 879, #"Percentage" = 63.14],
					        [#"Sno" = 754, #"AgeGroup" = 62, #"TotalCases" = 985, #"Percentage" = 47.69],
					        [#"Sno" = 465, #"AgeGroup" = 27, #"TotalCases" = 349, #"Percentage" = 9.51],
					        [#"Sno" = 864, #"AgeGroup" = 38, #"TotalCases" = 915, #"Percentage" = 8.91],
					        [#"Sno" = 170, #"AgeGroup" = 42, #"TotalCases" = 631, #"Percentage" = 6.43],
					        [#"Sno" = 984, #"AgeGroup" = 57, #"TotalCases" = 673, #"Percentage" = 90.43],
					        [#"Sno" = 289, #"AgeGroup" = 72, #"TotalCases" = 188, #"Percentage" = 93.85],
					        [#"Sno" = 20, #"AgeGroup" = 77, #"TotalCases" = 413, #"Percentage" = 38.11],
					        [#"Sno" = 199, #"AgeGroup" = 63, #"TotalCases" = 373, #"Percentage" = 27.03],
					        [#"Sno" = 505, #"AgeGroup" = 66, #"TotalCases" = 327, #"Percentage" = 27.38],
					        [#"Sno" = 747, #"AgeGroup" = 38, #"TotalCases" = 447, #"Percentage" = 96.99],
					        [#"Sno" = 605, #"AgeGroup" = 30, #"TotalCases" = 291, #"Percentage" = 38.36],
					        [#"Sno" = 710, #"AgeGroup" = 60, #"TotalCases" = 907, #"Percentage" = 94.2],
					        [#"Sno" = 600, #"AgeGroup" = 51, #"TotalCases" = 490, #"Percentage" = 63.49],
					        [#"Sno" = 635, #"AgeGroup" = 80, #"TotalCases" = 555, #"Percentage" = 6.63],
					        [#"Sno" = 589, #"AgeGroup" = 34, #"TotalCases" = 828, #"Percentage" = 65.54],
					        [#"Sno" = 920, #"AgeGroup" = 72, #"TotalCases" = 778, #"Percentage" = 15.0],
					        [#"Sno" = 983, #"AgeGroup" = 25, #"TotalCases" = 944, #"Percentage" = 0.2],
					        [#"Sno" = 24, #"AgeGroup" = 30, #"TotalCases" = 5, #"Percentage" = 9.84],
					        [#"Sno" = 36, #"AgeGroup" = 54, #"TotalCases" = 715, #"Percentage" = 21.62],
					        [#"Sno" = 500, #"AgeGroup" = 70, #"TotalCases" = 35, #"Percentage" = 43.75],
					        [#"Sno" = 561, #"AgeGroup" = 77, #"TotalCases" = 41, #"Percentage" = 83.06],
					        [#"Sno" = 457, #"AgeGroup" = 57, #"TotalCases" = 62, #"Percentage" = 45.29],
					        [#"Sno" = 613, #"AgeGroup" = 40, #"TotalCases" = 236, #"Percentage" = 21.58],
					        [#"Sno" = 609, #"AgeGroup" = 19, #"TotalCases" = 720, #"Percentage" = 67.27],
					        [#"Sno" = 21, #"AgeGroup" = 78, #"TotalCases" = 3, #"Percentage" = 20.81],
					        [#"Sno" = 868, #"AgeGroup" = 38, #"TotalCases" = 435, #"Percentage" = 10.3],
					        [#"Sno" = 28, #"AgeGroup" = 44, #"TotalCases" = 177, #"Percentage" = 40.0],
					        [#"Sno" = 405, #"AgeGroup" = 74, #"TotalCases" = 963, #"Percentage" = 39.73],
					        [#"Sno" = 204, #"AgeGroup" = 63, #"TotalCases" = 613, #"Percentage" = 5.66],
					        [#"Sno" = 941, #"AgeGroup" = 55, #"TotalCases" = 886, #"Percentage" = 32.0],
					        [#"Sno" = 767, #"AgeGroup" = 80, #"TotalCases" = 905, #"Percentage" = 11.09],
					        [#"Sno" = 252, #"AgeGroup" = 33, #"TotalCases" = 687, #"Percentage" = 88.37],
					        [#"Sno" = 245, #"AgeGroup" = 69, #"TotalCases" = 989, #"Percentage" = 24.24],
					        [#"Sno" = 569, #"AgeGroup" = 76, #"TotalCases" = 183, #"Percentage" = 8.8],
					        [#"Sno" = 519, #"AgeGroup" = 75, #"TotalCases" = 524, #"Percentage" = 77.23],
					        [#"Sno" = 879, #"AgeGroup" = 44, #"TotalCases" = 759, #"Percentage" = 42.44],
					        [#"Sno" = 239, #"AgeGroup" = 45, #"TotalCases" = 515, #"Percentage" = 47.78],
					        [#"Sno" = 738, #"AgeGroup" = 56, #"TotalCases" = 805, #"Percentage" = 28.89],
					        [#"Sno" = 271, #"AgeGroup" = 43, #"TotalCases" = 329, #"Percentage" = 30.41],
					        [#"Sno" = 633, #"AgeGroup" = 66, #"TotalCases" = 411, #"Percentage" = 30.71],
					        [#"Sno" = 487, #"AgeGroup" = 19, #"TotalCases" = 318, #"Percentage" = 25.21],
					        [#"Sno" = 291, #"AgeGroup" = 71, #"TotalCases" = 225, #"Percentage" = 62.62],
					        [#"Sno" = 944, #"AgeGroup" = 54, #"TotalCases" = 445, #"Percentage" = 82.66],
					        [#"Sno" = 411, #"AgeGroup" = 23, #"TotalCases" = 490, #"Percentage" = 22.7],
					        [#"Sno" = 142, #"AgeGroup" = 56, #"TotalCases" = 304, #"Percentage" = 20.83],
					        [#"Sno" = 909, #"AgeGroup" = 67, #"TotalCases" = 784, #"Percentage" = 31.77],
					        [#"Sno" = 757, #"AgeGroup" = 18, #"TotalCases" = 592, #"Percentage" = 17.65],
					        [#"Sno" = 34, #"AgeGroup" = 70, #"TotalCases" = 582, #"Percentage" = 32.38],
					        [#"Sno" = 12, #"AgeGroup" = 76, #"TotalCases" = 751, #"Percentage" = 61.46],
					        [#"Sno" = 52, #"AgeGroup" = 46, #"TotalCases" = 295, #"Percentage" = 50.86],
					        [#"Sno" = 64, #"AgeGroup" = 33, #"TotalCases" = 581, #"Percentage" = 68.11],
					        [#"Sno" = 425, #"AgeGroup" = 41, #"TotalCases" = 207, #"Percentage" = 37.8],
					        [#"Sno" = 85, #"AgeGroup" = 40, #"TotalCases" = 287, #"Percentage" = 92.95],
					        [#"Sno" = 348, #"AgeGroup" = 70, #"TotalCases" = 457, #"Percentage" = 59.29],
					        [#"Sno" = 407, #"AgeGroup" = 63, #"TotalCases" = 420, #"Percentage" = 33.55],
					        [#"Sno" = 782, #"AgeGroup" = 47, #"TotalCases" = 415, #"Percentage" = 29.62],
					        [#"Sno" = 91, #"AgeGroup" = 30, #"TotalCases" = 466, #"Percentage" = 24.32],
					        [#"Sno" = 614, #"AgeGroup" = 24, #"TotalCases" = 837, #"Percentage" = 76.9],
					        [#"Sno" = 231, #"AgeGroup" = 44, #"TotalCases" = 514, #"Percentage" = 95.02],
					        [#"Sno" = 930, #"AgeGroup" = 40, #"TotalCases" = 539, #"Percentage" = 20.57],
					        [#"Sno" = 572, #"AgeGroup" = 26, #"TotalCases" = 496, #"Percentage" = 22.13],
					        [#"Sno" = 170, #"AgeGroup" = 28, #"TotalCases" = 720, #"Percentage" = 66.07],
					        [#"Sno" = 642, #"AgeGroup" = 69, #"TotalCases" = 510, #"Percentage" = 10.92],
					        [#"Sno" = 543, #"AgeGroup" = 21, #"TotalCases" = 355, #"Percentage" = 78.96],
					        [#"Sno" = 711, #"AgeGroup" = 61, #"TotalCases" = 530, #"Percentage" = 63.63],
					        [#"Sno" = 364, #"AgeGroup" = 49, #"TotalCases" = 920, #"Percentage" = 36.8],
					        [#"Sno" = 458, #"AgeGroup" = 29, #"TotalCases" = 595, #"Percentage" = 99.32],
					        [#"Sno" = 412, #"AgeGroup" = 58, #"TotalCases" = 882, #"Percentage" = 87.34],
					        [#"Sno" = 283, #"AgeGroup" = 41, #"TotalCases" = 527, #"Percentage" = 85.15],
					        [#"Sno" = 679, #"AgeGroup" = 21, #"TotalCases" = 449, #"Percentage" = 83.83],
					        [#"Sno" = 488, #"AgeGroup" = 19, #"TotalCases" = 163, #"Percentage" = 23.92],
					        [#"Sno" = 14, #"AgeGroup" = 53, #"TotalCases" = 499, #"Percentage" = 94.72]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Sno", Int64.Type},
					        {"AgeGroup", type text},
					        {"TotalCases", Int64.Type},
					        {"Percentage", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table