table 'Profit Bin Size'
	lineageTag: c801ce30-d252-4b23-821b-a9b0bc57048b

	measure 'Profit Bin Size Value' = SELECTEDVALUE('Profit Bin Size'[Profit Bin Size], 50)
		lineageTag: 7eda9163-ee3f-4d00-b0b3-a3e179d37d64

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Profit Bin Size'
		dataType: double
		formatString: 0
		lineageTag: 582bf64e-271e-47b1-9282-2baf952c7f88
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Profit Bin Size' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_Id = 53f89815ca6345ab97caba987678a812

