table 'Profit Bin Size'
	lineageTag: 494e6a18-e401-4e6c-b14d-aed57baf7a44

	measure 'Profit Bin Size Value' = SELECTEDVALUE('Profit Bin Size'[Profit Bin Size], 50)
		lineageTag: f31d198c-f57a-4109-a18c-8646e91dcd81

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Profit Bin Size'
		dataType: double
		formatString: 0
		lineageTag: f7258228-da61-4a62-8cf0-9b80dc2bda2e
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Profit Bin Size' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_Id = bd24664455654652a2297e6284974890

