table 'Sample - Superstore_People'
	lineageTag: 05b93a7d-eace-454c-9d7e-91b4b3a96a79

	column 'Regional Manager'
		dataType: string
		lineageTag: 91174a60-e1f6-43cf-bb8f-56eab3243ab1
		summarizeBy: none
		sourceColumn: 'Regional Manager'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 4bac6812-687e-4aea-ad66-2afd0e0cae40
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition 'Sample - Superstore_People' = m
		mode: import
		source =
				let
					    Source = Csv.Document(
					        File.Contents("https://saastestlatest.blob.core.windows.net/saas-test-reports/Sample%20-%20Superstore_People.csv?se=2025-11-05T06%3A55%3A53Z&sp=r&sv=2025-11-05&sr=b&sig=qai1vmN719QNbCcce3uLGeojCaI35lu7BWUivb57HKg%3D"),
					        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
					    ),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Regional Manager", type text}, {"Region", type text}})
					in
					    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table