table 'Top Customers'
	lineageTag: a8aa7f11-55c8-406d-a582-77ea42a0bd7c

	measure 'Top Customers Value' = SELECTEDVALUE('Top Customers'[Top Customers], 5)
		lineageTag: 9ba53321-b12d-4d1e-b092-4b96d6a8f17c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Top Customers'
		dataType: double
		formatString: 0
		lineageTag: 024837da-05dc-4ef6-a993-b4656caaae98
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Top Customers' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_Id = 5c49eb5bea3046199a0319e053736700

