table 'health care diabetes'
	lineageTag: 8bdacd56-c8bd-40c5-8b6e-1e874b38d8ce

	column Id
		dataType: int64
		formatString: 0
		lineageTag: 36fd6540-4655-4ba4-922a-dfc0481187e9
		summarizeBy: count
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Pregnancies
		dataType: int64
		formatString: 0
		lineageTag: bfa7711d-1f1d-4258-840c-c2af80f82d98
		summarizeBy: sum
		sourceColumn: Pregnancies

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"health care diabetes","TableItemName":"Pregnancies (bin)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column Glucose
		dataType: int64
		formatString: 0
		lineageTag: 273b1bfe-b08c-47e9-9c69-5c15564748c9
		summarizeBy: sum
		sourceColumn: Glucose

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"health care diabetes","TableItemName":"Glucose (bins)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column BloodPressure
		dataType: int64
		formatString: 0
		lineageTag: ca48a637-07f2-4880-ac4e-f1e2125941a8
		summarizeBy: sum
		sourceColumn: BloodPressure

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"health care diabetes","TableItemName":"Blood Pressure (bin)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column SkinThickness
		dataType: int64
		formatString: 0
		lineageTag: c0ae7f0b-9dcc-4fee-bcca-eb45cd239570
		summarizeBy: sum
		sourceColumn: SkinThickness

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"health care diabetes","TableItemName":"Skin Thickness (bin)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column Insulin
		dataType: int64
		formatString: 0
		lineageTag: bc1e357f-b512-4744-bd6d-003c93529ad1
		summarizeBy: none
		sourceColumn: Insulin

		annotation SummarizationSetBy = User

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"health care diabetes","TableItemName":"Insulin (bin)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column BMI
		dataType: double
		lineageTag: 5f07e126-2796-47a9-bf75-ad2a8ac1b318
		summarizeBy: sum
		sourceColumn: BMI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"health care diabetes","TableItemName":"BMI (bin)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column DiabetesPedigreeFunction
		dataType: double
		lineageTag: 3675baf0-bf1c-42bc-a938-469f0d2e10bd
		summarizeBy: sum
		sourceColumn: DiabetesPedigreeFunction

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"health care diabetes","TableItemName":"Diabetes Pedigree Function (bin)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column Age
		dataType: int64
		formatString: 0
		lineageTag: f795edbd-3ccf-44ec-9517-b02b7f9b6fe9
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"health care diabetes","TableItemName":"Age (bin)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column Outcome
		dataType: int64
		formatString: 0
		lineageTag: a2b6ff5b-5e87-4d9b-b944-7d20bed2aad5
		summarizeBy: sum
		sourceColumn: Outcome

		annotation SummarizationSetBy = Automatic

	column 'Blood Pressure (bin)' =
			IF(
				ISBLANK('health care diabetes'[BloodPressure]),
				BLANK(),
				INT('health care diabetes'[BloodPressure] / 10) * 10
			)
		formatString: 0
		lineageTag: f770416f-1ee4-44c4-b4e3-523f6c20748e
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "health care diabetes"
				          }
				        },
				        "Property": "BloodPressure"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 10.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"h","Entity":"health care diabetes"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"h"}},"Property":"BloodPressure"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"h"}},"Property":"BloodPressure"}},"Size":10.0}}}}

		annotation SummarizationSetBy = Automatic

	column 'BMI (bin)' =
			IF(
				ISBLANK('health care diabetes'[BMI]),
				BLANK(),
				IF(
					'health care diabetes'[BMI] >= 0,
					ROUNDDOWN('health care diabetes'[BMI] / 3.04, 0) * 3.04,
					ROUNDUP('health care diabetes'[BMI] / 3.04, 0) * 3.04
				)
			)
		lineageTag: e31ae9fb-132d-4708-8d4b-5a46cd955ec7
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "health care diabetes"
				          }
				        },
				        "Property": "BMI"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 3.04,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"h","Entity":"health care diabetes"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"h"}},"Property":"BMI"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"h"}},"Property":"BMI"}},"Size":3.04}}}}

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Insulin (bin)' =
			IF(
				ISBLANK('health care diabetes'[Insulin]),
				BLANK(),
				INT('health care diabetes'[Insulin] / 42) * 42
			)
		formatString: 0
		lineageTag: d873889b-a585-4118-bcf3-3220f164df44
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "health care diabetes"
				          }
				        },
				        "Property": "Insulin"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 42.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"h","Entity":"health care diabetes"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"h"}},"Property":"Insulin"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"h"}},"Property":"Insulin"}},"Size":42.0}}}}

		annotation SummarizationSetBy = Automatic

	column 'Skin Thickness (bin)' =
			IF(
				ISBLANK('health care diabetes'[SkinThickness]),
				BLANK(),
				INT('health care diabetes'[SkinThickness] / 8) * 8
			)
		formatString: 0
		lineageTag: e3500c89-4ef8-4d05-bc5d-c6ef55f861b8
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "health care diabetes"
				          }
				        },
				        "Property": "SkinThickness"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 8.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"h","Entity":"health care diabetes"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"h"}},"Property":"SkinThickness"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"h"}},"Property":"SkinThickness"}},"Size":8.0}}}}

		annotation SummarizationSetBy = Automatic

	column 'Age (bin)' =
			IF(
				ISBLANK('health care diabetes'[Age]),
				BLANK(),
				INT('health care diabetes'[Age] / 5) * 5
			)
		formatString: 0
		lineageTag: 6953c589-9680-4029-9417-353a348d7c8b
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "health care diabetes"
				          }
				        },
				        "Property": "Age"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 5.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"h","Entity":"health care diabetes"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"h"}},"Property":"Age"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"h"}},"Property":"Age"}},"Size":5.0}}}}

		annotation SummarizationSetBy = Automatic

	column 'Glucose (bins)' =
			IF(
				ISBLANK('health care diabetes'[Glucose]),
				BLANK(),
				INT('health care diabetes'[Glucose] / 11) * 11
			)
		formatString: 0
		lineageTag: 2674726f-39b8-460a-b338-b35242b25a5e
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "health care diabetes"
				          }
				        },
				        "Property": "Glucose"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 11.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"h","Entity":"health care diabetes"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"h"}},"Property":"Glucose"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"h"}},"Property":"Glucose"}},"Size":11.0}}}}

		annotation SummarizationSetBy = Automatic

	column 'Diabetes Pedigree Function (bin)' =
			IF(
				ISBLANK('health care diabetes'[DiabetesPedigreeFunction]),
				BLANK(),
				IF(
					'health care diabetes'[DiabetesPedigreeFunction] >= 0,
					ROUNDDOWN('health care diabetes'[DiabetesPedigreeFunction] / 0.080758620689655169, 0) * 0.080758620689655169,
					ROUNDUP('health care diabetes'[DiabetesPedigreeFunction] / 0.080758620689655169, 0) * 0.080758620689655169
				)
			)
		lineageTag: 4a295992-0407-4223-8704-0c82c963b5cb
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "health care diabetes"
				          }
				        },
				        "Property": "DiabetesPedigreeFunction"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 0.080758620689655169,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"h","Entity":"health care diabetes"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"h"}},"Property":"DiabetesPedigreeFunction"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"h"}},"Property":"DiabetesPedigreeFunction"}},"Size":0.080758620689655169}}}}

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pregnancies (bin)' =
			IF(
				ISBLANK('health care diabetes'[Pregnancies]),
				BLANK(),
				INT('health care diabetes'[Pregnancies] / 2) * 2
			)
		formatString: 0
		lineageTag: e33fc420-95f3-4d35-9d6e-a335d39f4507
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "health care diabetes"
				          }
				        },
				        "Property": "Pregnancies"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 2.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"h","Entity":"health care diabetes"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"h"}},"Property":"Pregnancies"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"h"}},"Property":"Pregnancies"}},"Size":2.0}}}}

		annotation SummarizationSetBy = Automatic

	partition 'health care diabetes' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://repoz-my.sharepoint.com/personal/karthikrajan_repoz_ai/Documents/SaaS%20testing%20files/Domain%20Datasets%20-%20Remote%20inters/Healthcare%20files/Diabetes%202/health%20care%20diabetes.xlsx"), null, true),
				    #"Healthcare-Diabetes(1)_Sheet" = Source{[Item="Healthcare-Diabetes(1)",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Healthcare-Diabetes(1)_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Id", Int64.Type}, {"Pregnancies", Int64.Type}, {"Glucose", Int64.Type}, {"BloodPressure", Int64.Type}, {"SkinThickness", Int64.Type}, {"Insulin", Int64.Type}, {"BMI", type number}, {"DiabetesPedigreeFunction", type number}, {"Age", Int64.Type}, {"Outcome", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

