table 'AE Benchmarks (FINAL Consolidated Dashboard Data with Charts 5_6_19)'
	lineageTag: 0cf9a82f-436c-4657-b934-62aae2aa24f6

	column F1
		dataType: string
		lineageTag: 6a3c8b62-9fef-4e34-a5a2-960f83702d84
		summarizeBy: none
		sourceColumn: F1

		annotation SummarizationSetBy = Automatic

	column F2
		dataType: string
		lineageTag: 0eb63ba8-537d-42cc-b4fa-79679e712c76
		summarizeBy: none
		sourceColumn: F2

		annotation SummarizationSetBy = Automatic

	column F3
		dataType: double
		formatString: General Number
		lineageTag: bda91124-6610-4838-aa3a-ba011915cd19
		summarizeBy: sum
		sourceColumn: F3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BATCH = 1
		lineageTag: 5b357a15-f743-4774-9c5e-5056af8b3f69
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'AE Benchmarks (FINAL Consolidated Dashboard Data with Charts 5_6_19)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"F1" = "cool", #"F2" = "interracial", #"F3" = 530.7],
					        [#"F1" = "hair", #"F2" = "none", #"F3" = 150.61],
					        [#"F1" = "response", #"F2" = "strategic", #"F3" = 341.8],
					        [#"F1" = "situations", #"F2" = "automobile", #"F3" = 29.5],
					        [#"F1" = "tune", #"F2" = "indianapolis", #"F3" = 130.41],
					        [#"F1" = "bad", #"F2" = "professionals", #"F3" = 429.01],
					        [#"F1" = "merchants", #"F2" = "cleveland", #"F3" = 776.44],
					        [#"F1" = "targeted", #"F2" = "mention", #"F3" = 422.15],
					        [#"F1" = "matching", #"F2" = "wins", #"F3" = 70.82],
					        [#"F1" = "tool", #"F2" = "personalized", #"F3" = 374.15],
					        [#"F1" = "loop", #"F2" = "sin", #"F3" = 287.49],
					        [#"F1" = "ah", #"F2" = "method", #"F3" = 525.73],
					        [#"F1" = "when", #"F2" = "woods", #"F3" = 392.01],
					        [#"F1" = "quantum", #"F2" = "capacity", #"F3" = 888.63],
					        [#"F1" = "oem", #"F2" = "law", #"F3" = 727.54],
					        [#"F1" = "table", #"F2" = "president", #"F3" = 230.14],
					        [#"F1" = "employees", #"F2" = "box", #"F3" = 747.35],
					        [#"F1" = "reception", #"F2" = "democrats", #"F3" = 706.13],
					        [#"F1" = "announcements", #"F2" = "ia", #"F3" = 874.38],
					        [#"F1" = "los", #"F2" = "fields", #"F3" = 250.06],
					        [#"F1" = "consideration", #"F2" = "tales", #"F3" = 365.84],
					        [#"F1" = "satellite", #"F2" = "displaying", #"F3" = 447.64],
					        [#"F1" = "protected", #"F2" = "tea", #"F3" = 108.54],
					        [#"F1" = "church", #"F2" = "within", #"F3" = 76.31],
					        [#"F1" = "smoke", #"F2" = "app", #"F3" = 890.82],
					        [#"F1" = "password", #"F2" = "superior", #"F3" = 467.88],
					        [#"F1" = "poetry", #"F2" = "purposes", #"F3" = 145.68],
					        [#"F1" = "employed", #"F2" = "factory", #"F3" = 290.91],
					        [#"F1" = "cats", #"F2" = "budget", #"F3" = 172.23],
					        [#"F1" = "force", #"F2" = "resulted", #"F3" = 948.13],
					        [#"F1" = "thought", #"F2" = "matter", #"F3" = 292.84],
					        [#"F1" = "fish", #"F2" = "delivered", #"F3" = 346.48],
					        [#"F1" = "blogging", #"F2" = "lay", #"F3" = 33.76],
					        [#"F1" = "enabled", #"F2" = "cable", #"F3" = 960.98],
					        [#"F1" = "candidate", #"F2" = "mysql", #"F3" = 936.07],
					        [#"F1" = "plastic", #"F2" = "visits", #"F3" = 962.62],
					        [#"F1" = "transport", #"F2" = "forgot", #"F3" = 549.19],
					        [#"F1" = "dimensional", #"F2" = "daniel", #"F3" = 836.92],
					        [#"F1" = "dealers", #"F2" = "users", #"F3" = 931.47],
					        [#"F1" = "discounts", #"F2" = "apr", #"F3" = 997.66],
					        [#"F1" = "outside", #"F2" = "involves", #"F3" = 176.77],
					        [#"F1" = "return", #"F2" = "concerns", #"F3" = 424.07],
					        [#"F1" = "mentioned", #"F2" = "extensive", #"F3" = 633.32],
					        [#"F1" = "power", #"F2" = "chips", #"F3" = 387.55],
					        [#"F1" = "covered", #"F2" = "education", #"F3" = 674.07],
					        [#"F1" = "imaging", #"F2" = "registered", #"F3" = 955.21],
					        [#"F1" = "steven", #"F2" = "regulatory", #"F3" = 31.82],
					        [#"F1" = "photo", #"F2" = "locator", #"F3" = 464.82],
					        [#"F1" = "desire", #"F2" = "mineral", #"F3" = 214.58],
					        [#"F1" = "remain", #"F2" = "flags", #"F3" = 926.4],
					        [#"F1" = "arizona", #"F2" = "documentation", #"F3" = 313.0],
					        [#"F1" = "medication", #"F2" = "officers", #"F3" = 528.59],
					        [#"F1" = "position", #"F2" = "bond", #"F3" = 46.59],
					        [#"F1" = "extensions", #"F2" = "gourmet", #"F3" = 473.76],
					        [#"F1" = "base", #"F2" = "independence", #"F3" = 901.97],
					        [#"F1" = "recording", #"F2" = "ideas", #"F3" = 716.03],
					        [#"F1" = "skills", #"F2" = "conversion", #"F3" = 907.45],
					        [#"F1" = "sense", #"F2" = "ii", #"F3" = 634.83],
					        [#"F1" = "magazine", #"F2" = "villa", #"F3" = 773.79],
					        [#"F1" = "independent", #"F2" = "activities", #"F3" = 30.17],
					        [#"F1" = "own", #"F2" = "printing", #"F3" = 304.15],
					        [#"F1" = "biography", #"F2" = "secretary", #"F3" = 673.84],
					        [#"F1" = "virus", #"F2" = "management", #"F3" = 747.33],
					        [#"F1" = "babes", #"F2" = "leather", #"F3" = 890.82],
					        [#"F1" = "dancing", #"F2" = "drugs", #"F3" = 885.47],
					        [#"F1" = "outdoor", #"F2" = "moderate", #"F3" = 236.15],
					        [#"F1" = "le", #"F2" = "michelle", #"F3" = 601.41],
					        [#"F1" = "inn", #"F2" = "hence", #"F3" = 219.2],
					        [#"F1" = "cellular", #"F2" = "informed", #"F3" = 14.54],
					        [#"F1" = "strategic", #"F2" = "finding", #"F3" = 780.27],
					        [#"F1" = "av", #"F2" = "commentary", #"F3" = 174.76],
					        [#"F1" = "neck", #"F2" = "copyright", #"F3" = 472.28],
					        [#"F1" = "win", #"F2" = "efficient", #"F3" = 97.97],
					        [#"F1" = "ladies", #"F2" = "angels", #"F3" = 338.65],
					        [#"F1" = "orchestra", #"F2" = "christian", #"F3" = 133.74],
					        [#"F1" = "hills", #"F2" = "vision", #"F3" = 808.36],
					        [#"F1" = "hands", #"F2" = "husband", #"F3" = 598.3],
					        [#"F1" = "spa", #"F2" = "attractions", #"F3" = 55.53],
					        [#"F1" = "approaches", #"F2" = "seconds", #"F3" = 514.32],
					        [#"F1" = "restoration", #"F2" = "examined", #"F3" = 309.14],
					        [#"F1" = "export", #"F2" = "photos", #"F3" = 999.02],
					        [#"F1" = "null", #"F2" = "proxy", #"F3" = 289.63],
					        [#"F1" = "conflict", #"F2" = "abroad", #"F3" = 135.49],
					        [#"F1" = "housing", #"F2" = "ticket", #"F3" = 957.53],
					        [#"F1" = "personality", #"F2" = "quality", #"F3" = 927.99],
					        [#"F1" = "chemistry", #"F2" = "coat", #"F3" = 360.45],
					        [#"F1" = "elizabeth", #"F2" = "affiliated", #"F3" = 462.58],
					        [#"F1" = "massage", #"F2" = "anniversary", #"F3" = 419.68],
					        [#"F1" = "ports", #"F2" = "ongoing", #"F3" = 812.13],
					        [#"F1" = "stay", #"F2" = "jurisdiction", #"F3" = 704.14],
					        [#"F1" = "pad", #"F2" = "eye", #"F3" = 238.21],
					        [#"F1" = "switches", #"F2" = "attacks", #"F3" = 569.35],
					        [#"F1" = "contribute", #"F2" = "ga", #"F3" = 771.41],
					        [#"F1" = "journal", #"F2" = "there", #"F3" = 911.17],
					        [#"F1" = "lbs", #"F2" = "coming", #"F3" = 95.21],
					        [#"F1" = "no", #"F2" = "reviewer", #"F3" = 703.98],
					        [#"F1" = "thermal", #"F2" = "cars", #"F3" = 865.78],
					        [#"F1" = "iraqi", #"F2" = "dancing", #"F3" = 329.47],
					        [#"F1" = "street", #"F2" = "landscape", #"F3" = 679.81],
					        [#"F1" = "su", #"F2" = "vat", #"F3" = 575.75],
					        [#"F1" = "protein", #"F2" = "speech", #"F3" = 67.38],
					        [#"F1" = "price", #"F2" = "un", #"F3" = 825.61],
					        [#"F1" = "sides", #"F2" = "analysis", #"F3" = 260.22],
					        [#"F1" = "even", #"F2" = "fact", #"F3" = 122.28],
					        [#"F1" = "front", #"F2" = "ending", #"F3" = 473.78],
					        [#"F1" = "combo", #"F2" = "martin", #"F3" = 624.06],
					        [#"F1" = "ion", #"F2" = "prohibited", #"F3" = 169.62],
					        [#"F1" = "stages", #"F2" = "pennsylvania", #"F3" = 490.43],
					        [#"F1" = "tripadvisor", #"F2" = "close", #"F3" = 796.71],
					        [#"F1" = "experiment", #"F2" = "apr", #"F3" = 714.98],
					        [#"F1" = "concerned", #"F2" = "discharge", #"F3" = 360.76],
					        [#"F1" = "attended", #"F2" = "hp", #"F3" = 958.49],
					        [#"F1" = "german", #"F2" = "processed", #"F3" = 639.62],
					        [#"F1" = "failed", #"F2" = "chi", #"F3" = 918.5],
					        [#"F1" = "forgotten", #"F2" = "theoretical", #"F3" = 587.34],
					        [#"F1" = "electric", #"F2" = "agency", #"F3" = 383.95],
					        [#"F1" = "dish", #"F2" = "ago", #"F3" = 994.81],
					        [#"F1" = "sheet", #"F2" = "mass", #"F3" = 312.66],
					        [#"F1" = "mitchell", #"F2" = "nt", #"F3" = 579.84],
					        [#"F1" = "internal", #"F2" = "certified", #"F3" = 441.47],
					        [#"F1" = "browsing", #"F2" = "results", #"F3" = 638.87],
					        [#"F1" = "population", #"F2" = "contributed", #"F3" = 424.34],
					        [#"F1" = "venue", #"F2" = "wedding", #"F3" = 372.31],
					        [#"F1" = "builders", #"F2" = "treated", #"F3" = 765.82],
					        [#"F1" = "october", #"F2" = "meat", #"F3" = 782.55],
					        [#"F1" = "sign", #"F2" = "flashing", #"F3" = 728.88],
					        [#"F1" = "paint", #"F2" = "recruitment", #"F3" = 528.84],
					        [#"F1" = "living", #"F2" = "believe", #"F3" = 162.86],
					        [#"F1" = "defense", #"F2" = "lost", #"F3" = 725.77],
					        [#"F1" = "innovation", #"F2" = "hospitality", #"F3" = 703.37],
					        [#"F1" = "unknown", #"F2" = "processors", #"F3" = 275.98],
					        [#"F1" = "master", #"F2" = "core", #"F3" = 747.09],
					        [#"F1" = "intermediate", #"F2" = "yr", #"F3" = 672.8],
					        [#"F1" = "ar", #"F2" = "formats", #"F3" = 552.64],
					        [#"F1" = "saudi", #"F2" = "help", #"F3" = 209.54],
					        [#"F1" = "effective", #"F2" = "tiger", #"F3" = 705.71],
					        [#"F1" = "slip", #"F2" = "enough", #"F3" = 646.8],
					        [#"F1" = "eight", #"F2" = "interviews", #"F3" = 879.86],
					        [#"F1" = "br", #"F2" = "loaded", #"F3" = 357.89],
					        [#"F1" = "liberal", #"F2" = "establishment", #"F3" = 294.54],
					        [#"F1" = "seattle", #"F2" = "till", #"F3" = 626.14],
					        [#"F1" = "packages", #"F2" = "england", #"F3" = 285.67],
					        [#"F1" = "plain", #"F2" = "traveler", #"F3" = 610.01],
					        [#"F1" = "secretary", #"F2" = "initiative", #"F3" = 952.86],
					        [#"F1" = "funding", #"F2" = "appearance", #"F3" = 997.91],
					        [#"F1" = "isbn", #"F2" = "sql", #"F3" = 123.48],
					        [#"F1" = "mercedes", #"F2" = "passage", #"F3" = 45.5],
					        [#"F1" = "number", #"F2" = "inkjet", #"F3" = 182.82],
					        [#"F1" = "ireland", #"F2" = "chairman", #"F3" = 760.88],
					        [#"F1" = "observation", #"F2" = "option", #"F3" = 840.51],
					        [#"F1" = "covering", #"F2" = "theft", #"F3" = 14.54],
					        [#"F1" = "education", #"F2" = "bedroom", #"F3" = 151.16],
					        [#"F1" = "lounge", #"F2" = "probably", #"F3" = 773.07],
					        [#"F1" = "browse", #"F2" = "diary", #"F3" = 573.62],
					        [#"F1" = "opt", #"F2" = "hop", #"F3" = 449.1],
					        [#"F1" = "nd", #"F2" = "educational", #"F3" = 881.65],
					        [#"F1" = "zero", #"F2" = "donald", #"F3" = 111.99],
					        [#"F1" = "action", #"F2" = "began", #"F3" = 270.85],
					        [#"F1" = "carol", #"F2" = "prove", #"F3" = 917.2],
					        [#"F1" = "lack", #"F2" = "quality", #"F3" = 314.43],
					        [#"F1" = "scotland", #"F2" = "ta", #"F3" = 532.52],
					        [#"F1" = "official", #"F2" = "locate", #"F3" = 787.92],
					        [#"F1" = "employment", #"F2" = "banner", #"F3" = 319.79],
					        [#"F1" = "seasons", #"F2" = "pm", #"F3" = 957.4],
					        [#"F1" = "mechanisms", #"F2" = "blackjack", #"F3" = 14.48],
					        [#"F1" = "holding", #"F2" = "teacher", #"F3" = 190.88],
					        [#"F1" = "explained", #"F2" = "programs", #"F3" = 419.32],
					        [#"F1" = "plane", #"F2" = "islam", #"F3" = 618.35],
					        [#"F1" = "mother", #"F2" = "locations", #"F3" = 799.48],
					        [#"F1" = "icons", #"F2" = "central", #"F3" = 309.3],
					        [#"F1" = "takes", #"F2" = "certificates", #"F3" = 437.66],
					        [#"F1" = "army", #"F2" = "arthur", #"F3" = 718.51],
					        [#"F1" = "resulting", #"F2" = "yard", #"F3" = 510.13],
					        [#"F1" = "button", #"F2" = "stock", #"F3" = 725.29],
					        [#"F1" = "bush", #"F2" = "sending", #"F3" = 440.41],
					        [#"F1" = "mpeg", #"F2" = "midnight", #"F3" = 656.57],
					        [#"F1" = "ok", #"F2" = "independent", #"F3" = 972.66],
					        [#"F1" = "knife", #"F2" = "spray", #"F3" = 692.83],
					        [#"F1" = "wilson", #"F2" = "nj", #"F3" = 773.43],
					        [#"F1" = "holdem", #"F2" = "martin", #"F3" = 606.08],
					        [#"F1" = "booking", #"F2" = "wednesday", #"F3" = 196.26],
					        [#"F1" = "fish", #"F2" = "concerned", #"F3" = 55.61],
					        [#"F1" = "blogger", #"F2" = "face", #"F3" = 493.46],
					        [#"F1" = "stack", #"F2" = "organisations", #"F3" = 825.62],
					        [#"F1" = "physics", #"F2" = "wear", #"F3" = 147.67],
					        [#"F1" = "refinance", #"F2" = "diff", #"F3" = 304.28],
					        [#"F1" = "hundred", #"F2" = "duty", #"F3" = 334.04],
					        [#"F1" = "literary", #"F2" = "interests", #"F3" = 290.21],
					        [#"F1" = "mine", #"F2" = "fell", #"F3" = 535.2],
					        [#"F1" = "radar", #"F2" = "titles", #"F3" = 945.23],
					        [#"F1" = "miami", #"F2" = "finder", #"F3" = 385.12],
					        [#"F1" = "diagnostic", #"F2" = "ryan", #"F3" = 812.3],
					        [#"F1" = "intent", #"F2" = "andy", #"F3" = 510.7],
					        [#"F1" = "procurement", #"F2" = "alternative", #"F3" = 65.75],
					        [#"F1" = "dates", #"F2" = "scanner", #"F3" = 312.37],
					        [#"F1" = "nike", #"F2" = "hard", #"F3" = 885.33],
					        [#"F1" = "partnership", #"F2" = "object", #"F3" = 838.25],
					        [#"F1" = "bulk", #"F2" = "lands", #"F3" = 611.46],
					        [#"F1" = "at", #"F2" = "democratic", #"F3" = 71.93],
					        [#"F1" = "nikon", #"F2" = "category", #"F3" = 762.71],
					        [#"F1" = "give", #"F2" = "appliances", #"F3" = 997.14],
					        [#"F1" = "broad", #"F2" = "lives", #"F3" = 697.53],
					        [#"F1" = "saw", #"F2" = "selection", #"F3" = 292.15],
					        [#"F1" = "mb", #"F2" = "hey", #"F3" = 3.27],
					        [#"F1" = "luxury", #"F2" = "grass", #"F3" = 925.55],
					        [#"F1" = "wild", #"F2" = "remain", #"F3" = 551.61],
					        [#"F1" = "pantyhose", #"F2" = "meet", #"F3" = 965.86],
					        [#"F1" = "stored", #"F2" = "entrance", #"F3" = 942.87],
					        [#"F1" = "arts", #"F2" = "enemy", #"F3" = 584.67],
					        [#"F1" = "handling", #"F2" = "faculty", #"F3" = 927.89],
					        [#"F1" = "jury", #"F2" = "mention", #"F3" = 396.44],
					        [#"F1" = "collected", #"F2" = "polls", #"F3" = 299.18],
					        [#"F1" = "website", #"F2" = "navigation", #"F3" = 454.84],
					        [#"F1" = "grey", #"F2" = "username", #"F3" = 808.92],
					        [#"F1" = "comment", #"F2" = "short", #"F3" = 133.09],
					        [#"F1" = "receive", #"F2" = "fast", #"F3" = 747.77],
					        [#"F1" = "formed", #"F2" = "gain", #"F3" = 334.56],
					        [#"F1" = "former", #"F2" = "measures", #"F3" = 195.73],
					        [#"F1" = "suicide", #"F2" = "crop", #"F3" = 722.1],
					        [#"F1" = "blonde", #"F2" = "carter", #"F3" = 796.42],
					        [#"F1" = "milwaukee", #"F2" = "entirely", #"F3" = 912.79],
					        [#"F1" = "remote", #"F2" = "sources", #"F3" = 380.28],
					        [#"F1" = "follow", #"F2" = "premier", #"F3" = 794.71],
					        [#"F1" = "http", #"F2" = "around", #"F3" = 164.19],
					        [#"F1" = "beauty", #"F2" = "impossible", #"F3" = 306.35],
					        [#"F1" = "gen", #"F2" = "identified", #"F3" = 898.25],
					        [#"F1" = "pics", #"F2" = "therapy", #"F3" = 477.66],
					        [#"F1" = "voltage", #"F2" = "rio", #"F3" = 685.79],
					        [#"F1" = "enterprise", #"F2" = "major", #"F3" = 132.41],
					        [#"F1" = "mid", #"F2" = "sir", #"F3" = 92.76],
					        [#"F1" = "slow", #"F2" = "outstanding", #"F3" = 165.87],
					        [#"F1" = "position", #"F2" = "thou", #"F3" = 47.48],
					        [#"F1" = "tall", #"F2" = "voice", #"F3" = 130.64],
					        [#"F1" = "temple", #"F2" = "leaves", #"F3" = 631.1],
					        [#"F1" = "graph", #"F2" = "holdem", #"F3" = 198.73],
					        [#"F1" = "functionality", #"F2" = "croatia", #"F3" = 335.7],
					        [#"F1" = "bid", #"F2" = "seems", #"F3" = 951.16],
					        [#"F1" = "walter", #"F2" = "tea", #"F3" = 759.06],
					        [#"F1" = "blogs", #"F2" = "find", #"F3" = 337.92],
					        [#"F1" = "fig", #"F2" = "painting", #"F3" = 720.88],
					        [#"F1" = "exit", #"F2" = "crystal", #"F3" = 383.0],
					        [#"F1" = "ask", #"F2" = "declaration", #"F3" = 42.02],
					        [#"F1" = "moral", #"F2" = "distinct", #"F3" = 452.98],
					        [#"F1" = "securities", #"F2" = "francis", #"F3" = 348.01],
					        [#"F1" = "assess", #"F2" = "contractor", #"F3" = 169.83],
					        [#"F1" = "touch", #"F2" = "directly", #"F3" = 346.82],
					        [#"F1" = "planner", #"F2" = "walked", #"F3" = 573.13],
					        [#"F1" = "preferences", #"F2" = "mayor", #"F3" = 306.89],
					        [#"F1" = "worker", #"F2" = "spirit", #"F3" = 734.05],
					        [#"F1" = "dining", #"F2" = "platforms", #"F3" = 457.18],
					        [#"F1" = "midnight", #"F2" = "cooperative", #"F3" = 905.37],
					        [#"F1" = "discovery", #"F2" = "crisis", #"F3" = 28.08],
					        [#"F1" = "mounted", #"F2" = "luxury", #"F3" = 187.13],
					        [#"F1" = "reaction", #"F2" = "loved", #"F3" = 16.07],
					        [#"F1" = "showed", #"F2" = "disabled", #"F3" = 756.88],
					        [#"F1" = "electrical", #"F2" = "right", #"F3" = 722.55],
					        [#"F1" = "colorado", #"F2" = "responsibility", #"F3" = 339.57],
					        [#"F1" = "laptops", #"F2" = "substances", #"F3" = 802.95],
					        [#"F1" = "equipped", #"F2" = "mb", #"F3" = 269.9],
					        [#"F1" = "mc", #"F2" = "directed", #"F3" = 721.97],
					        [#"F1" = "detailed", #"F2" = "org", #"F3" = 294.01],
					        [#"F1" = "junior", #"F2" = "phil", #"F3" = 466.22],
					        [#"F1" = "mean", #"F2" = "after", #"F3" = 513.35],
					        [#"F1" = "nurses", #"F2" = "broke", #"F3" = 271.09],
					        [#"F1" = "embedded", #"F2" = "ups", #"F3" = 230.49],
					        [#"F1" = "indicator", #"F2" = "freeware", #"F3" = 714.08],
					        [#"F1" = "raising", #"F2" = "after", #"F3" = 952.63],
					        [#"F1" = "fifth", #"F2" = "person", #"F3" = 158.81],
					        [#"F1" = "explains", #"F2" = "philippines", #"F3" = 802.49],
					        [#"F1" = "ink", #"F2" = "elected", #"F3" = 536.52],
					        [#"F1" = "alternative", #"F2" = "nyc", #"F3" = 986.72],
					        [#"F1" = "felt", #"F2" = "foundation", #"F3" = 911.19],
					        [#"F1" = "afghanistan", #"F2" = "boy", #"F3" = 325.15],
					        [#"F1" = "checking", #"F2" = "eminem", #"F3" = 182.41],
					        [#"F1" = "leave", #"F2" = "playstation", #"F3" = 271.6],
					        [#"F1" = "capital", #"F2" = "happened", #"F3" = 788.07],
					        [#"F1" = "partnerships", #"F2" = "scholarship", #"F3" = 106.32],
					        [#"F1" = "created", #"F2" = "mode", #"F3" = 624.77],
					        [#"F1" = "gap", #"F2" = "downtown", #"F3" = 584.43],
					        [#"F1" = "nutrition", #"F2" = "even", #"F3" = 92.21],
					        [#"F1" = "eu", #"F2" = "episode", #"F3" = 262.12],
					        [#"F1" = "baltimore", #"F2" = "derived", #"F3" = 426.06],
					        [#"F1" = "scientists", #"F2" = "jeans", #"F3" = 324.21],
					        [#"F1" = "talks", #"F2" = "databases", #"F3" = 620.34],
					        [#"F1" = "know", #"F2" = "pee", #"F3" = 396.73],
					        [#"F1" = "difficulty", #"F2" = "img", #"F3" = 796.75],
					        [#"F1" = "toshiba", #"F2" = "belgium", #"F3" = 294.64],
					        [#"F1" = "greg", #"F2" = "software", #"F3" = 67.63],
					        [#"F1" = "letters", #"F2" = "thumbnail", #"F3" = 654.67],
					        [#"F1" = "copyright", #"F2" = "crash", #"F3" = 265.84],
					        [#"F1" = "devel", #"F2" = "continental", #"F3" = 345.21],
					        [#"F1" = "enemy", #"F2" = "existence", #"F3" = 7.15],
					        [#"F1" = "objects", #"F2" = "performing", #"F3" = 26.18],
					        [#"F1" = "start", #"F2" = "greatest", #"F3" = 376.83],
					        [#"F1" = "science", #"F2" = "keith", #"F3" = 192.54],
					        [#"F1" = "eliminate", #"F2" = "attachment", #"F3" = 944.67],
					        [#"F1" = "facilities", #"F2" = "forms", #"F3" = 601.58],
					        [#"F1" = "laptops", #"F2" = "airline", #"F3" = 659.42],
					        [#"F1" = "volunteers", #"F2" = "ringtone", #"F3" = 479.09],
					        [#"F1" = "head", #"F2" = "hurt", #"F3" = 217.28],
					        [#"F1" = "titans", #"F2" = "wave", #"F3" = 103.46],
					        [#"F1" = "custom", #"F2" = "player", #"F3" = 638.49],
					        [#"F1" = "implementing", #"F2" = "becoming", #"F3" = 756.41],
					        [#"F1" = "examined", #"F2" = "soil", #"F3" = 283.77],
					        [#"F1" = "oklahoma", #"F2" = "trip", #"F3" = 231.2],
					        [#"F1" = "casino", #"F2" = "vice", #"F3" = 749.23],
					        [#"F1" = "workshops", #"F2" = "prescription", #"F3" = 914.69],
					        [#"F1" = "sponsor", #"F2" = "radio", #"F3" = 361.44],
					        [#"F1" = "depending", #"F2" = "applicable", #"F3" = 699.47],
					        [#"F1" = "wrong", #"F2" = "subscriber", #"F3" = 883.65],
					        [#"F1" = "phd", #"F2" = "vegas", #"F3" = 45.99],
					        [#"F1" = "transaction", #"F2" = "processor", #"F3" = 583.93],
					        [#"F1" = "comfort", #"F2" = "edwards", #"F3" = 288.28],
					        [#"F1" = "fear", #"F2" = "arthur", #"F3" = 484.01],
					        [#"F1" = "herself", #"F2" = "preview", #"F3" = 67.68],
					        [#"F1" = "unfortunately", #"F2" = "bruce", #"F3" = 306.39],
					        [#"F1" = "subscribe", #"F2" = "removed", #"F3" = 921.18],
					        [#"F1" = "interview", #"F2" = "threads", #"F3" = 359.76],
					        [#"F1" = "audio", #"F2" = "fantasy", #"F3" = 301.3],
					        [#"F1" = "mile", #"F2" = "expression", #"F3" = 895.44],
					        [#"F1" = "boards", #"F2" = "ads", #"F3" = 231.34],
					        [#"F1" = "lies", #"F2" = "zone", #"F3" = 183.91],
					        [#"F1" = "for", #"F2" = "fleet", #"F3" = 90.63],
					        [#"F1" = "ukraine", #"F2" = "anniversary", #"F3" = 756.61],
					        [#"F1" = "head", #"F2" = "dealers", #"F3" = 825.51],
					        [#"F1" = "interpretation", #"F2" = "anonymous", #"F3" = 345.56],
					        [#"F1" = "serious", #"F2" = "theoretical", #"F3" = 754.74],
					        [#"F1" = "ingredients", #"F2" = "furniture", #"F3" = 936.99],
					        [#"F1" = "discharge", #"F2" = "cry", #"F3" = 132.58],
					        [#"F1" = "clicking", #"F2" = "component", #"F3" = 479.76],
					        [#"F1" = "constraints", #"F2" = "reserves", #"F3" = 621.72],
					        [#"F1" = "boats", #"F2" = "finally", #"F3" = 395.83],
					        [#"F1" = "dimension", #"F2" = "era", #"F3" = 857.99],
					        [#"F1" = "printing", #"F2" = "thesis", #"F3" = 792.09],
					        [#"F1" = "fr", #"F2" = "mountain", #"F3" = 897.21],
					        [#"F1" = "tools", #"F2" = "along", #"F3" = 772.02],
					        [#"F1" = "buildings", #"F2" = "woman", #"F3" = 667.18],
					        [#"F1" = "ltd", #"F2" = "frank", #"F3" = 131.1],
					        [#"F1" = "attachment", #"F2" = "experience", #"F3" = 211.45],
					        [#"F1" = "saturday", #"F2" = "steering", #"F3" = 796.2],
					        [#"F1" = "closed", #"F2" = "engineering", #"F3" = 64.03],
					        [#"F1" = "di", #"F2" = "listings", #"F3" = 353.02],
					        [#"F1" = "holds", #"F2" = "inside", #"F3" = 38.28],
					        [#"F1" = "back", #"F2" = "rated", #"F3" = 976.6],
					        [#"F1" = "voip", #"F2" = "shipping", #"F3" = 874.51],
					        [#"F1" = "never", #"F2" = "rf", #"F3" = 1.21],
					        [#"F1" = "matthew", #"F2" = "roger", #"F3" = 228.77],
					        [#"F1" = "worldwide", #"F2" = "hand", #"F3" = 384.18],
					        [#"F1" = "breast", #"F2" = "warning", #"F3" = 361.92],
					        [#"F1" = "dennis", #"F2" = "in", #"F3" = 126.06],
					        [#"F1" = "order", #"F2" = "editing", #"F3" = 647.82],
					        [#"F1" = "bank", #"F2" = "approval", #"F3" = 754.56],
					        [#"F1" = "authors", #"F2" = "review", #"F3" = 358.42],
					        [#"F1" = "teenage", #"F2" = "originally", #"F3" = 600.41],
					        [#"F1" = "square", #"F2" = "waves", #"F3" = 710.89],
					        [#"F1" = "provisions", #"F2" = "usually", #"F3" = 186.64],
					        [#"F1" = "men", #"F2" = "joy", #"F3" = 583.73],
					        [#"F1" = "health", #"F2" = "collectibles", #"F3" = 595.0],
					        [#"F1" = "tips", #"F2" = "rings", #"F3" = 596.66],
					        [#"F1" = "corn", #"F2" = "islands", #"F3" = 126.07],
					        [#"F1" = "mayor", #"F2" = "bags", #"F3" = 922.61],
					        [#"F1" = "ending", #"F2" = "romance", #"F3" = 48.08],
					        [#"F1" = "rs", #"F2" = "john", #"F3" = 407.06],
					        [#"F1" = "city", #"F2" = "math", #"F3" = 388.63],
					        [#"F1" = "pocket", #"F2" = "campbell", #"F3" = 711.76],
					        [#"F1" = "swedish", #"F2" = "specialized", #"F3" = 330.28],
					        [#"F1" = "picks", #"F2" = "capture", #"F3" = 270.17],
					        [#"F1" = "attention", #"F2" = "race", #"F3" = 637.1],
					        [#"F1" = "growth", #"F2" = "brought", #"F3" = 685.06],
					        [#"F1" = "pages", #"F2" = "rank", #"F3" = 326.92],
					        [#"F1" = "adult", #"F2" = "creation", #"F3" = 45.48],
					        [#"F1" = "nl", #"F2" = "faculty", #"F3" = 156.97],
					        [#"F1" = "warm", #"F2" = "telling", #"F3" = 105.89],
					        [#"F1" = "index", #"F2" = "hours", #"F3" = 92.22],
					        [#"F1" = "ended", #"F2" = "val", #"F3" = 267.56],
					        [#"F1" = "clock", #"F2" = "laptop", #"F3" = 7.06],
					        [#"F1" = "sister", #"F2" = "jonathan", #"F3" = 239.53],
					        [#"F1" = "pdf", #"F2" = "earn", #"F3" = 886.77],
					        [#"F1" = "flat", #"F2" = "haven", #"F3" = 311.22],
					        [#"F1" = "map", #"F2" = "ml", #"F3" = 351.68],
					        [#"F1" = "hat", #"F2" = "rates", #"F3" = 749.26],
					        [#"F1" = "financing", #"F2" = "fantasy", #"F3" = 357.71],
					        [#"F1" = "statistical", #"F2" = "balance", #"F3" = 965.85],
					        [#"F1" = "respective", #"F2" = "rom", #"F3" = 632.68],
					        [#"F1" = "threat", #"F2" = "system", #"F3" = 575.0],
					        [#"F1" = "unix", #"F2" = "underwear", #"F3" = 406.13],
					        [#"F1" = "hearing", #"F2" = "fantasy", #"F3" = 628.31],
					        [#"F1" = "assist", #"F2" = "worry", #"F3" = 192.68],
					        [#"F1" = "coalition", #"F2" = "resorts", #"F3" = 887.49],
					        [#"F1" = "preferred", #"F2" = "revolution", #"F3" = 700.78],
					        [#"F1" = "expect", #"F2" = "views", #"F3" = 326.4],
					        [#"F1" = "images", #"F2" = "consumer", #"F3" = 781.33],
					        [#"F1" = "regulatory", #"F2" = "canon", #"F3" = 554.54],
					        [#"F1" = "disclaimer", #"F2" = "earth", #"F3" = 585.68],
					        [#"F1" = "horror", #"F2" = "frame", #"F3" = 105.03],
					        [#"F1" = "queries", #"F2" = "miami", #"F3" = 4.36],
					        [#"F1" = "former", #"F2" = "desktops", #"F3" = 866.1],
					        [#"F1" = "representatives", #"F2" = "meter", #"F3" = 982.29],
					        [#"F1" = "define", #"F2" = "west", #"F3" = 359.1],
					        [#"F1" = "fortune", #"F2" = "apparently", #"F3" = 740.63],
					        [#"F1" = "eye", #"F2" = "power", #"F3" = 382.22],
					        [#"F1" = "marriage", #"F2" = "statistical", #"F3" = 97.01],
					        [#"F1" = "website", #"F2" = "alternate", #"F3" = 592.73],
					        [#"F1" = "di", #"F2" = "se", #"F3" = 654.33],
					        [#"F1" = "de", #"F2" = "film", #"F3" = 848.1],
					        [#"F1" = "till", #"F2" = "field", #"F3" = 587.25],
					        [#"F1" = "requires", #"F2" = "clinic", #"F3" = 205.43],
					        [#"F1" = "available", #"F2" = "programming", #"F3" = 489.44],
					        [#"F1" = "keith", #"F2" = "basket", #"F3" = 181.56],
					        [#"F1" = "thursday", #"F2" = "kingdom", #"F3" = 40.52],
					        [#"F1" = "trials", #"F2" = "previous", #"F3" = 111.5],
					        [#"F1" = "destinations", #"F2" = "aspects", #"F3" = 306.11],
					        [#"F1" = "half", #"F2" = "walter", #"F3" = 845.25],
					        [#"F1" = "optical", #"F2" = "classes", #"F3" = 529.79],
					        [#"F1" = "wood", #"F2" = "san", #"F3" = 630.26],
					        [#"F1" = "concentration", #"F2" = "affected", #"F3" = 379.57],
					        [#"F1" = "transferred", #"F2" = "dad", #"F3" = 997.11],
					        [#"F1" = "anytime", #"F2" = "technical", #"F3" = 797.94],
					        [#"F1" = "tone", #"F2" = "microsoft", #"F3" = 205.08],
					        [#"F1" = "guarantee", #"F2" = "locations", #"F3" = 823.01],
					        [#"F1" = "egg", #"F2" = "wife", #"F3" = 698.89],
					        [#"F1" = "consolidation", #"F2" = "hilton", #"F3" = 225.76],
					        [#"F1" = "families", #"F2" = "oem", #"F3" = 973.63],
					        [#"F1" = "while", #"F2" = "employer", #"F3" = 842.88],
					        [#"F1" = "remained", #"F2" = "copper", #"F3" = 276.06],
					        [#"F1" = "geography", #"F2" = "india", #"F3" = 886.31],
					        [#"F1" = "tape", #"F2" = "may", #"F3" = 756.43],
					        [#"F1" = "downtown", #"F2" = "fund", #"F3" = 410.05],
					        [#"F1" = "dispute", #"F2" = "soldiers", #"F3" = 113.4],
					        [#"F1" = "blank", #"F2" = "exploration", #"F3" = 602.65],
					        [#"F1" = "methodology", #"F2" = "ethics", #"F3" = 574.63],
					        [#"F1" = "wonderful", #"F2" = "how", #"F3" = 59.06],
					        [#"F1" = "kim", #"F2" = "utility", #"F3" = 330.58],
					        [#"F1" = "programs", #"F2" = "hi", #"F3" = 527.58],
					        [#"F1" = "storage", #"F2" = "jeans", #"F3" = 692.62],
					        [#"F1" = "dna", #"F2" = "injury", #"F3" = 704.42],
					        [#"F1" = "recovery", #"F2" = "pentium", #"F3" = 892.77],
					        [#"F1" = "application", #"F2" = "flat", #"F3" = 828.4],
					        [#"F1" = "chapter", #"F2" = "productivity", #"F3" = 223.81],
					        [#"F1" = "source", #"F2" = "builder", #"F3" = 853.55],
					        [#"F1" = "writer", #"F2" = "arab", #"F3" = 864.83],
					        [#"F1" = "confirmation", #"F2" = "hub", #"F3" = 962.07],
					        [#"F1" = "recall", #"F2" = "gr", #"F3" = 820.22],
					        [#"F1" = "manchester", #"F2" = "nearby", #"F3" = 940.73],
					        [#"F1" = "attorney", #"F2" = "artists", #"F3" = 591.06],
					        [#"F1" = "shift", #"F2" = "along", #"F3" = 62.9],
					        [#"F1" = "opposition", #"F2" = "highest", #"F3" = 677.01],
					        [#"F1" = "wildlife", #"F2" = "vt", #"F3" = 585.72],
					        [#"F1" = "iowa", #"F2" = "priced", #"F3" = 900.24],
					        [#"F1" = "decided", #"F2" = "perhaps", #"F3" = 248.7],
					        [#"F1" = "hundred", #"F2" = "issue", #"F3" = 200.63],
					        [#"F1" = "shared", #"F2" = "opportunities", #"F3" = 10.03],
					        [#"F1" = "voip", #"F2" = "accommodation", #"F3" = 312.6],
					        [#"F1" = "steven", #"F2" = "certificates", #"F3" = 489.52],
					        [#"F1" = "targets", #"F2" = "dial", #"F3" = 654.45],
					        [#"F1" = "apparently", #"F2" = "probably", #"F3" = 856.77],
					        [#"F1" = "craft", #"F2" = "harvard", #"F3" = 971.81],
					        [#"F1" = "men", #"F2" = "four", #"F3" = 65.32],
					        [#"F1" = "highway", #"F2" = "nikon", #"F3" = 746.73],
					        [#"F1" = "platinum", #"F2" = "female", #"F3" = 310.77],
					        [#"F1" = "protein", #"F2" = "instant", #"F3" = 431.42],
					        [#"F1" = "faces", #"F2" = "harbor", #"F3" = 822.37],
					        [#"F1" = "philips", #"F2" = "convenience", #"F3" = 538.29],
					        [#"F1" = "maria", #"F2" = "new", #"F3" = 32.82],
					        [#"F1" = "reached", #"F2" = "serves", #"F3" = 766.24],
					        [#"F1" = "adam", #"F2" = "diseases", #"F3" = 278.6],
					        [#"F1" = "tonight", #"F2" = "dakota", #"F3" = 2.98],
					        [#"F1" = "favorites", #"F2" = "otherwise", #"F3" = 369.21],
					        [#"F1" = "tracking", #"F2" = "material", #"F3" = 947.88],
					        [#"F1" = "alphabetical", #"F2" = "driver", #"F3" = 745.01],
					        [#"F1" = "voice", #"F2" = "nsw", #"F3" = 100.7],
					        [#"F1" = "scores", #"F2" = "inches", #"F3" = 741.19],
					        [#"F1" = "sports", #"F2" = "voltage", #"F3" = 171.74],
					        [#"F1" = "applicants", #"F2" = "jacket", #"F3" = 261.29],
					        [#"F1" = "info", #"F2" = "consult", #"F3" = 464.66],
					        [#"F1" = "introduce", #"F2" = "replace", #"F3" = 783.02],
					        [#"F1" = "festival", #"F2" = "highest", #"F3" = 513.07],
					        [#"F1" = "kind", #"F2" = "conferences", #"F3" = 864.63],
					        [#"F1" = "remaining", #"F2" = "but", #"F3" = 957.26],
					        [#"F1" = "wrestling", #"F2" = "brings", #"F3" = 90.83],
					        [#"F1" = "element", #"F2" = "screening", #"F3" = 743.27],
					        [#"F1" = "market", #"F2" = "letter", #"F3" = 293.35],
					        [#"F1" = "methods", #"F2" = "reports", #"F3" = 881.88],
					        [#"F1" = "midnight", #"F2" = "arguments", #"F3" = 423.61],
					        [#"F1" = "edit", #"F2" = "successful", #"F3" = 537.77],
					        [#"F1" = "calculate", #"F2" = "sharp", #"F3" = 148.33],
					        [#"F1" = "know", #"F2" = "programmes", #"F3" = 164.87],
					        [#"F1" = "keith", #"F2" = "scale", #"F3" = 730.63],
					        [#"F1" = "le", #"F2" = "sir", #"F3" = 647.49],
					        [#"F1" = "area", #"F2" = "silver", #"F3" = 678.62],
					        [#"F1" = "hidden", #"F2" = "mathematics", #"F3" = 579.41],
					        [#"F1" = "de", #"F2" = "gear", #"F3" = 489.92],
					        [#"F1" = "likely", #"F2" = "edt", #"F3" = 782.73],
					        [#"F1" = "columbus", #"F2" = "moved", #"F3" = 992.2],
					        [#"F1" = "aluminum", #"F2" = "became", #"F3" = 548.36],
					        [#"F1" = "witness", #"F2" = "average", #"F3" = 816.98],
					        [#"F1" = "consequences", #"F2" = "steps", #"F3" = 98.77],
					        [#"F1" = "mayor", #"F2" = "votes", #"F3" = 502.36],
					        [#"F1" = "destinations", #"F2" = "besides", #"F3" = 0.68],
					        [#"F1" = "listing", #"F2" = "housewares", #"F3" = 911.44]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"F1", type text},
					        {"F2", type text},
					        {"F3", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table