table 'AE Benchmarks (FINAL Consolidated Dashboard Data with Charts 5_6_19)_AE Ed gains'
	lineageTag: 655b7493-528b-4f49-95ce-9ed073d398b4

	column F1
		dataType: string
		lineageTag: a0445c1c-37c2-48c1-a8ff-a4549931d53a
		summarizeBy: none
		sourceColumn: F1

		annotation SummarizationSetBy = Automatic

	column F2
		dataType: string
		lineageTag: c6571013-30c2-4883-b692-694b78bd6b25
		summarizeBy: none
		sourceColumn: F2

		annotation SummarizationSetBy = Automatic

	column F3
		dataType: double
		formatString: General Number
		lineageTag: bfe5e233-2341-4ca5-8b04-2c6c7026cd65
		summarizeBy: sum
		sourceColumn: F3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'AE Benchmarks (FINAL Consolidated Dashboard Data with Charts 5_6_19)_AE Ed gains' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"F1" = "thongs", #"F2" = "pm", #"F3" = 65.22],
					        [#"F1" = "compared", #"F2" = "platform", #"F3" = 516.19],
					        [#"F1" = "birthday", #"F2" = "recipes", #"F3" = 133.51],
					        [#"F1" = "usr", #"F2" = "du", #"F3" = 588.6],
					        [#"F1" = "measures", #"F2" = "glasgow", #"F3" = 442.35],
					        [#"F1" = "matrix", #"F2" = "basic", #"F3" = 147.85],
					        [#"F1" = "alarm", #"F2" = "applicants", #"F3" = 429.26],
					        [#"F1" = "northern", #"F2" = "golf", #"F3" = 323.36],
					        [#"F1" = "distance", #"F2" = "indicate", #"F3" = 90.1],
					        [#"F1" = "relationships", #"F2" = "wheels", #"F3" = 232.78],
					        [#"F1" = "species", #"F2" = "watches", #"F3" = 591.99],
					        [#"F1" = "thumbs", #"F2" = "covers", #"F3" = 877.44],
					        [#"F1" = "copies", #"F2" = "temple", #"F3" = 638.97],
					        [#"F1" = "happened", #"F2" = "version", #"F3" = 598.92],
					        [#"F1" = "administrator", #"F2" = "forms", #"F3" = 803.53],
					        [#"F1" = "railway", #"F2" = "server", #"F3" = 775.34],
					        [#"F1" = "determination", #"F2" = "soap", #"F3" = 808.99],
					        [#"F1" = "corner", #"F2" = "understanding", #"F3" = 354.92],
					        [#"F1" = "growth", #"F2" = "lot", #"F3" = 429.5],
					        [#"F1" = "script", #"F2" = "tablet", #"F3" = 850.69],
					        [#"F1" = "ion", #"F2" = "ins", #"F3" = 653.84],
					        [#"F1" = "odds", #"F2" = "portfolio", #"F3" = 98.55],
					        [#"F1" = "monitor", #"F2" = "michigan", #"F3" = 521.88],
					        [#"F1" = "tie", #"F2" = "possibly", #"F3" = 214.36],
					        [#"F1" = "europe", #"F2" = "mo", #"F3" = 582.07],
					        [#"F1" = "certification", #"F2" = "children", #"F3" = 73.24],
					        [#"F1" = "agreements", #"F2" = "petition", #"F3" = 940.3],
					        [#"F1" = "receiver", #"F2" = "models", #"F3" = 458.62],
					        [#"F1" = "education", #"F2" = "users", #"F3" = 150.26],
					        [#"F1" = "sony", #"F2" = "recognized", #"F3" = 660.78],
					        [#"F1" = "albany", #"F2" = "miller", #"F3" = 163.61],
					        [#"F1" = "mounted", #"F2" = "takes", #"F3" = 750.6],
					        [#"F1" = "pump", #"F2" = "paragraph", #"F3" = 323.58],
					        [#"F1" = "whom", #"F2" = "foundation", #"F3" = 341.53],
					        [#"F1" = "posts", #"F2" = "recipient", #"F3" = 454.73],
					        [#"F1" = "south", #"F2" = "wrote", #"F3" = 228.03],
					        [#"F1" = "aim", #"F2" = "ways", #"F3" = 913.13],
					        [#"F1" = "provide", #"F2" = "either", #"F3" = 252.09],
					        [#"F1" = "grown", #"F2" = "actor", #"F3" = 239.3],
					        [#"F1" = "beautiful", #"F2" = "beef", #"F3" = 401.16],
					        [#"F1" = "networking", #"F2" = "shall", #"F3" = 864.74],
					        [#"F1" = "relationships", #"F2" = "funny", #"F3" = 533.12],
					        [#"F1" = "onto", #"F2" = "beer", #"F3" = 890.38],
					        [#"F1" = "adoption", #"F2" = "victoria", #"F3" = 388.03],
					        [#"F1" = "study", #"F2" = "sporting", #"F3" = 727.33],
					        [#"F1" = "boat", #"F2" = "suppliers", #"F3" = 906.38],
					        [#"F1" = "sure", #"F2" = "rehabilitation", #"F3" = 702.12],
					        [#"F1" = "portable", #"F2" = "jason", #"F3" = 558.23],
					        [#"F1" = "kennedy", #"F2" = "targeted", #"F3" = 116.53],
					        [#"F1" = "anna", #"F2" = "action", #"F3" = 600.57],
					        [#"F1" = "point", #"F2" = "possibly", #"F3" = 807.32],
					        [#"F1" = "reporter", #"F2" = "mistake", #"F3" = 160.85],
					        [#"F1" = "fill", #"F2" = "navigate", #"F3" = 923.46],
					        [#"F1" = "aircraft", #"F2" = "lawrence", #"F3" = 189.73],
					        [#"F1" = "pack", #"F2" = "frequency", #"F3" = 852.31],
					        [#"F1" = "successful", #"F2" = "south", #"F3" = 336.91],
					        [#"F1" = "smooth", #"F2" = "comics", #"F3" = 57.69],
					        [#"F1" = "apple", #"F2" = "signals", #"F3" = 260.51],
					        [#"F1" = "requests", #"F2" = "cruise", #"F3" = 761.88],
					        [#"F1" = "details", #"F2" = "boot", #"F3" = 708.9],
					        [#"F1" = "boot", #"F2" = "investment", #"F3" = 126.51],
					        [#"F1" = "trends", #"F2" = "lingerie", #"F3" = 357.1],
					        [#"F1" = "devel", #"F2" = "if", #"F3" = 668.25],
					        [#"F1" = "cuba", #"F2" = "funds", #"F3" = 840.86],
					        [#"F1" = "operators", #"F2" = "create", #"F3" = 493.69],
					        [#"F1" = "camps", #"F2" = "studio", #"F3" = 788.51],
					        [#"F1" = "invite", #"F2" = "discuss", #"F3" = 206.08],
					        [#"F1" = "that", #"F2" = "browse", #"F3" = 920.47],
					        [#"F1" = "troops", #"F2" = "mlb", #"F3" = 654.28],
					        [#"F1" = "ones", #"F2" = "lee", #"F3" = 98.16],
					        [#"F1" = "in", #"F2" = "walking", #"F3" = 814.08],
					        [#"F1" = "hence", #"F2" = "cyprus", #"F3" = 473.91],
					        [#"F1" = "encourage", #"F2" = "roman", #"F3" = 965.91],
					        [#"F1" = "licence", #"F2" = "mind", #"F3" = 925.52],
					        [#"F1" = "stephen", #"F2" = "related", #"F3" = 656.42],
					        [#"F1" = "reputation", #"F2" = "conversation", #"F3" = 828.57],
					        [#"F1" = "ne", #"F2" = "owned", #"F3" = 326.35],
					        [#"F1" = "rev", #"F2" = "animated", #"F3" = 549.63],
					        [#"F1" = "register", #"F2" = "beads", #"F3" = 968.83],
					        [#"F1" = "heritage", #"F2" = "andrew", #"F3" = 816.5],
					        [#"F1" = "submissions", #"F2" = "swimming", #"F3" = 51.72],
					        [#"F1" = "css", #"F2" = "proven", #"F3" = 850.26],
					        [#"F1" = "neil", #"F2" = "volume", #"F3" = 267.03],
					        [#"F1" = "threads", #"F2" = "nelson", #"F3" = 206.95],
					        [#"F1" = "emphasis", #"F2" = "ebay", #"F3" = 846.98],
					        [#"F1" = "relations", #"F2" = "learn", #"F3" = 977.89],
					        [#"F1" = "placement", #"F2" = "representative", #"F3" = 828.0],
					        [#"F1" = "reproduction", #"F2" = "wow", #"F3" = 378.41],
					        [#"F1" = "hearts", #"F2" = "threat", #"F3" = 368.52],
					        [#"F1" = "ins", #"F2" = "violent", #"F3" = 149.71],
					        [#"F1" = "img", #"F2" = "developments", #"F3" = 855.71],
					        [#"F1" = "sectors", #"F2" = "wow", #"F3" = 850.41],
					        [#"F1" = "richard", #"F2" = "thought", #"F3" = 627.04],
					        [#"F1" = "contests", #"F2" = "alaska", #"F3" = 155.57],
					        [#"F1" = "accordance", #"F2" = "tend", #"F3" = 35.42],
					        [#"F1" = "kids", #"F2" = "collectibles", #"F3" = 464.06],
					        [#"F1" = "opening", #"F2" = "source", #"F3" = 928.39],
					        [#"F1" = "outlook", #"F2" = "heritage", #"F3" = 185.74],
					        [#"F1" = "band", #"F2" = "robin", #"F3" = 692.3],
					        [#"F1" = "matches", #"F2" = "logo", #"F3" = 795.3],
					        [#"F1" = "prison", #"F2" = "pot", #"F3" = 854.97],
					        [#"F1" = "rent", #"F2" = "land", #"F3" = 30.87],
					        [#"F1" = "edition", #"F2" = "builders", #"F3" = 376.88],
					        [#"F1" = "clark", #"F2" = "arizona", #"F3" = 500.11],
					        [#"F1" = "government", #"F2" = "hybrid", #"F3" = 681.86],
					        [#"F1" = "entering", #"F2" = "microsoft", #"F3" = 671.93],
					        [#"F1" = "showing", #"F2" = "hist", #"F3" = 325.88],
					        [#"F1" = "results", #"F2" = "once", #"F3" = 820.27],
					        [#"F1" = "group", #"F2" = "damage", #"F3" = 575.42],
					        [#"F1" = "signed", #"F2" = "blonde", #"F3" = 511.3],
					        [#"F1" = "shipped", #"F2" = "regulation", #"F3" = 175.92],
					        [#"F1" = "unique", #"F2" = "foto", #"F3" = 840.67],
					        [#"F1" = "cd", #"F2" = "keeping", #"F3" = 244.84],
					        [#"F1" = "met", #"F2" = "connection", #"F3" = 563.79],
					        [#"F1" = "testing", #"F2" = "moderate", #"F3" = 45.97],
					        [#"F1" = "rob", #"F2" = "proven", #"F3" = 276.53],
					        [#"F1" = "adopt", #"F2" = "walls", #"F3" = 644.51],
					        [#"F1" = "reverse", #"F2" = "playing", #"F3" = 977.5],
					        [#"F1" = "plenty", #"F2" = "formats", #"F3" = 447.5],
					        [#"F1" = "yeah", #"F2" = "warren", #"F3" = 44.79],
					        [#"F1" = "artificial", #"F2" = "spanking", #"F3" = 218.86],
					        [#"F1" = "orlando", #"F2" = "signature", #"F3" = 182.14],
					        [#"F1" = "motorcycle", #"F2" = "peak", #"F3" = 525.19],
					        [#"F1" = "br", #"F2" = "rpm", #"F3" = 59.05],
					        [#"F1" = "alabama", #"F2" = "holdem", #"F3" = 472.41],
					        [#"F1" = "presence", #"F2" = "situations", #"F3" = 511.7],
					        [#"F1" = "plain", #"F2" = "supplies", #"F3" = 345.46],
					        [#"F1" = "closely", #"F2" = "scan", #"F3" = 268.11],
					        [#"F1" = "bestsellers", #"F2" = "suicide", #"F3" = 729.14],
					        [#"F1" = "mpeg", #"F2" = "affairs", #"F3" = 12.65],
					        [#"F1" = "changes", #"F2" = "commentary", #"F3" = 167.23],
					        [#"F1" = "eg", #"F2" = "required", #"F3" = 593.49],
					        [#"F1" = "dvds", #"F2" = "ride", #"F3" = 254.88],
					        [#"F1" = "sense", #"F2" = "jose", #"F3" = 723.72],
					        [#"F1" = "cause", #"F2" = "payment", #"F3" = 994.21],
					        [#"F1" = "rooms", #"F2" = "hire", #"F3" = 946.69],
					        [#"F1" = "clothing", #"F2" = "unix", #"F3" = 867.23],
					        [#"F1" = "capacity", #"F2" = "book", #"F3" = 891.28],
					        [#"F1" = "describes", #"F2" = "gold", #"F3" = 969.45],
					        [#"F1" = "or", #"F2" = "notify", #"F3" = 50.07],
					        [#"F1" = "playstation", #"F2" = "still", #"F3" = 212.83],
					        [#"F1" = "never", #"F2" = "participate", #"F3" = 972.36],
					        [#"F1" = "museum", #"F2" = "designated", #"F3" = 430.04],
					        [#"F1" = "substance", #"F2" = "efforts", #"F3" = 739.44],
					        [#"F1" = "cold", #"F2" = "clubs", #"F3" = 360.15],
					        [#"F1" = "tx", #"F2" = "bags", #"F3" = 975.06],
					        [#"F1" = "efficient", #"F2" = "massachusetts", #"F3" = 321.58],
					        [#"F1" = "save", #"F2" = "weekend", #"F3" = 691.22],
					        [#"F1" = "soul", #"F2" = "warren", #"F3" = 115.02],
					        [#"F1" = "decade", #"F2" = "noise", #"F3" = 541.03],
					        [#"F1" = "berkeley", #"F2" = "constant", #"F3" = 311.98],
					        [#"F1" = "success", #"F2" = "gadgets", #"F3" = 781.81],
					        [#"F1" = "parameters", #"F2" = "poverty", #"F3" = 53.46],
					        [#"F1" = "los", #"F2" = "portuguese", #"F3" = 600.36],
					        [#"F1" = "sport", #"F2" = "en", #"F3" = 853.77],
					        [#"F1" = "handbook", #"F2" = "break", #"F3" = 98.24],
					        [#"F1" = "imaging", #"F2" = "everyday", #"F3" = 406.0],
					        [#"F1" = "records", #"F2" = "charm", #"F3" = 920.37],
					        [#"F1" = "reasons", #"F2" = "bruce", #"F3" = 770.39],
					        [#"F1" = "watching", #"F2" = "bottle", #"F3" = 491.64],
					        [#"F1" = "sony", #"F2" = "brand", #"F3" = 838.38],
					        [#"F1" = "bill", #"F2" = "rf", #"F3" = 643.05],
					        [#"F1" = "sharon", #"F2" = "trials", #"F3" = 751.59],
					        [#"F1" = "late", #"F2" = "parties", #"F3" = 287.78],
					        [#"F1" = "avenue", #"F2" = "large", #"F3" = 883.79],
					        [#"F1" = "concrete", #"F2" = "kings", #"F3" = 342.42],
					        [#"F1" = "petition", #"F2" = "able", #"F3" = 912.85],
					        [#"F1" = "literacy", #"F2" = "sick", #"F3" = 670.17],
					        [#"F1" = "behalf", #"F2" = "immigration", #"F3" = 839.23],
					        [#"F1" = "clearance", #"F2" = "stone", #"F3" = 947.14],
					        [#"F1" = "come", #"F2" = "weekend", #"F3" = 474.41],
					        [#"F1" = "clay", #"F2" = "them", #"F3" = 881.83],
					        [#"F1" = "commissioner", #"F2" = "jul", #"F3" = 547.64],
					        [#"F1" = "convenient", #"F2" = "elections", #"F3" = 376.05],
					        [#"F1" = "rooms", #"F2" = "inform", #"F3" = 370.15],
					        [#"F1" = "spread", #"F2" = "economics", #"F3" = 444.28],
					        [#"F1" = "entertainment", #"F2" = "bear", #"F3" = 372.48],
					        [#"F1" = "cart", #"F2" = "usd", #"F3" = 476.86],
					        [#"F1" = "winds", #"F2" = "facilitate", #"F3" = 590.86],
					        [#"F1" = "panama", #"F2" = "ongoing", #"F3" = 391.52],
					        [#"F1" = "trucks", #"F2" = "sad", #"F3" = 46.92],
					        [#"F1" = "watches", #"F2" = "otherwise", #"F3" = 113.7],
					        [#"F1" = "surveys", #"F2" = "sorted", #"F3" = 534.65],
					        [#"F1" = "industry", #"F2" = "additional", #"F3" = 769.4],
					        [#"F1" = "tuesday", #"F2" = "after", #"F3" = 588.62],
					        [#"F1" = "press", #"F2" = "news", #"F3" = 185.82],
					        [#"F1" = "themselves", #"F2" = "describes", #"F3" = 217.9],
					        [#"F1" = "album", #"F2" = "measured", #"F3" = 540.08],
					        [#"F1" = "deals", #"F2" = "loved", #"F3" = 866.42],
					        [#"F1" = "chain", #"F2" = "spy", #"F3" = 123.77],
					        [#"F1" = "obligation", #"F2" = "fit", #"F3" = 520.53],
					        [#"F1" = "masters", #"F2" = "colombia", #"F3" = 738.69],
					        [#"F1" = "reflect", #"F2" = "hobbies", #"F3" = 383.17],
					        [#"F1" = "atmosphere", #"F2" = "order", #"F3" = 965.09],
					        [#"F1" = "antonio", #"F2" = "hall", #"F3" = 424.72],
					        [#"F1" = "five", #"F2" = "provided", #"F3" = 575.29],
					        [#"F1" = "haven", #"F2" = "laser", #"F3" = 411.46],
					        [#"F1" = "memorial", #"F2" = "functionality", #"F3" = 498.51],
					        [#"F1" = "toner", #"F2" = "then", #"F3" = 729.81],
					        [#"F1" = "allocation", #"F2" = "shirt", #"F3" = 423.83],
					        [#"F1" = "environments", #"F2" = "eve", #"F3" = 668.93],
					        [#"F1" = "cycling", #"F2" = "ethics", #"F3" = 446.27],
					        [#"F1" = "advertising", #"F2" = "nebraska", #"F3" = 845.59],
					        [#"F1" = "directed", #"F2" = "nebraska", #"F3" = 956.29],
					        [#"F1" = "counties", #"F2" = "postposted", #"F3" = 627.66],
					        [#"F1" = "inspection", #"F2" = "caused", #"F3" = 46.02],
					        [#"F1" = "fed", #"F2" = "next", #"F3" = 82.38],
					        [#"F1" = "gets", #"F2" = "icons", #"F3" = 987.72],
					        [#"F1" = "diamond", #"F2" = "assignment", #"F3" = 249.8],
					        [#"F1" = "infrastructure", #"F2" = "lbs", #"F3" = 698.69],
					        [#"F1" = "named", #"F2" = "majority", #"F3" = 674.47],
					        [#"F1" = "telephone", #"F2" = "ohio", #"F3" = 407.77],
					        [#"F1" = "provision", #"F2" = "heard", #"F3" = 932.48],
					        [#"F1" = "vegas", #"F2" = "offset", #"F3" = 524.77],
					        [#"F1" = "gifts", #"F2" = "knife", #"F3" = 32.79],
					        [#"F1" = "freedom", #"F2" = "aspect", #"F3" = 772.12],
					        [#"F1" = "stated", #"F2" = "lake", #"F3" = 321.54],
					        [#"F1" = "political", #"F2" = "second", #"F3" = 281.11],
					        [#"F1" = "tag", #"F2" = "computing", #"F3" = 206.56],
					        [#"F1" = "roy", #"F2" = "promotional", #"F3" = 25.65],
					        [#"F1" = "ontario", #"F2" = "south", #"F3" = 228.52],
					        [#"F1" = "poverty", #"F2" = "natural", #"F3" = 328.33],
					        [#"F1" = "instructor", #"F2" = "generic", #"F3" = 79.13],
					        [#"F1" = "philips", #"F2" = "gray", #"F3" = 198.7],
					        [#"F1" = "federation", #"F2" = "nation", #"F3" = 623.1],
					        [#"F1" = "bond", #"F2" = "canon", #"F3" = 506.98],
					        [#"F1" = "wave", #"F2" = "rent", #"F3" = 403.49],
					        [#"F1" = "pet", #"F2" = "connection", #"F3" = 176.04],
					        [#"F1" = "fails", #"F2" = "judicial", #"F3" = 342.37],
					        [#"F1" = "buyer", #"F2" = "progress", #"F3" = 755.35],
					        [#"F1" = "woods", #"F2" = "options", #"F3" = 560.11],
					        [#"F1" = "tank", #"F2" = "kong", #"F3" = 134.05],
					        [#"F1" = "source", #"F2" = "tue", #"F3" = 484.73],
					        [#"F1" = "principle", #"F2" = "contact", #"F3" = 715.79],
					        [#"F1" = "reproduction", #"F2" = "instant", #"F3" = 117.28],
					        [#"F1" = "fee", #"F2" = "acts", #"F3" = 783.67],
					        [#"F1" = "implemented", #"F2" = "again", #"F3" = 675.8],
					        [#"F1" = "type", #"F2" = "detection", #"F3" = 213.45],
					        [#"F1" = "verzeichnis", #"F2" = "mechanical", #"F3" = 299.31],
					        [#"F1" = "short", #"F2" = "specifically", #"F3" = 901.43],
					        [#"F1" = "belief", #"F2" = "degrees", #"F3" = 791.96],
					        [#"F1" = "cad", #"F2" = "trademark", #"F3" = 365.16],
					        [#"F1" = "disney", #"F2" = "voices", #"F3" = 597.03],
					        [#"F1" = "pregnant", #"F2" = "later", #"F3" = 163.78],
					        [#"F1" = "plan", #"F2" = "counsel", #"F3" = 252.84],
					        [#"F1" = "eagle", #"F2" = "stone", #"F3" = 680.99],
					        [#"F1" = "animals", #"F2" = "gospel", #"F3" = 72.75],
					        [#"F1" = "certified", #"F2" = "drunk", #"F3" = 685.32],
					        [#"F1" = "des", #"F2" = "formed", #"F3" = 406.26],
					        [#"F1" = "hair", #"F2" = "joint", #"F3" = 440.85],
					        [#"F1" = "dan", #"F2" = "preferences", #"F3" = 212.28],
					        [#"F1" = "seminar", #"F2" = "absolutely", #"F3" = 654.17],
					        [#"F1" = "co", #"F2" = "countries", #"F3" = 96.04],
					        [#"F1" = "donate", #"F2" = "register", #"F3" = 406.47],
					        [#"F1" = "where", #"F2" = "chemistry", #"F3" = 224.14],
					        [#"F1" = "try", #"F2" = "service", #"F3" = 962.03],
					        [#"F1" = "beds", #"F2" = "proof", #"F3" = 443.35],
					        [#"F1" = "veterans", #"F2" = "crimes", #"F3" = 61.38],
					        [#"F1" = "pi", #"F2" = "determination", #"F3" = 323.03],
					        [#"F1" = "influence", #"F2" = "achievement", #"F3" = 739.61],
					        [#"F1" = "framework", #"F2" = "pt", #"F3" = 494.31],
					        [#"F1" = "hour", #"F2" = "key", #"F3" = 656.6],
					        [#"F1" = "notebook", #"F2" = "rapid", #"F3" = 993.73],
					        [#"F1" = "miss", #"F2" = "suite", #"F3" = 317.99],
					        [#"F1" = "podcast", #"F2" = "necessary", #"F3" = 51.73],
					        [#"F1" = "curve", #"F2" = "hosted", #"F3" = 190.37],
					        [#"F1" = "swing", #"F2" = "began", #"F3" = 745.86],
					        [#"F1" = "naked", #"F2" = "accuracy", #"F3" = 444.21],
					        [#"F1" = "round", #"F2" = "much", #"F3" = 688.51],
					        [#"F1" = "instruments", #"F2" = "roses", #"F3" = 506.1],
					        [#"F1" = "cellular", #"F2" = "mit", #"F3" = 998.41],
					        [#"F1" = "powder", #"F2" = "cartridge", #"F3" = 612.2],
					        [#"F1" = "rr", #"F2" = "scripts", #"F3" = 287.23],
					        [#"F1" = "consult", #"F2" = "alert", #"F3" = 824.59],
					        [#"F1" = "sound", #"F2" = "routine", #"F3" = 883.53],
					        [#"F1" = "tickets", #"F2" = "lift", #"F3" = 152.02],
					        [#"F1" = "fixed", #"F2" = "exist", #"F3" = 743.49],
					        [#"F1" = "golden", #"F2" = "choosing", #"F3" = 77.77],
					        [#"F1" = "brain", #"F2" = "continue", #"F3" = 608.39],
					        [#"F1" = "judgment", #"F2" = "corporation", #"F3" = 198.23],
					        [#"F1" = "pain", #"F2" = "highlights", #"F3" = 519.5],
					        [#"F1" = "ft", #"F2" = "play", #"F3" = 734.52],
					        [#"F1" = "numerous", #"F2" = "flights", #"F3" = 455.04],
					        [#"F1" = "breasts", #"F2" = "consulting", #"F3" = 54.32],
					        [#"F1" = "money", #"F2" = "broadcasting", #"F3" = 283.9],
					        [#"F1" = "lodge", #"F2" = "completed", #"F3" = 857.85],
					        [#"F1" = "attack", #"F2" = "serving", #"F3" = 334.68],
					        [#"F1" = "explained", #"F2" = "flexibility", #"F3" = 199.83],
					        [#"F1" = "started", #"F2" = "status", #"F3" = 708.05],
					        [#"F1" = "warm", #"F2" = "adjustable", #"F3" = 275.73],
					        [#"F1" = "nj", #"F2" = "throat", #"F3" = 473.6],
					        [#"F1" = "kit", #"F2" = "alabama", #"F3" = 525.32],
					        [#"F1" = "watches", #"F2" = "pi", #"F3" = 968.43],
					        [#"F1" = "scott", #"F2" = "power", #"F3" = 664.65],
					        [#"F1" = "gary", #"F2" = "manual", #"F3" = 546.31],
					        [#"F1" = "spoke", #"F2" = "les", #"F3" = 951.07],
					        [#"F1" = "sound", #"F2" = "that", #"F3" = 67.89],
					        [#"F1" = "sl", #"F2" = "roots", #"F3" = 100.72],
					        [#"F1" = "motorcycle", #"F2" = "stewart", #"F3" = 592.19],
					        [#"F1" = "olympic", #"F2" = "ba", #"F3" = 538.16],
					        [#"F1" = "evaluate", #"F2" = "health", #"F3" = 522.49],
					        [#"F1" = "everywhere", #"F2" = "community", #"F3" = 452.0],
					        [#"F1" = "marketing", #"F2" = "recommend", #"F3" = 477.65],
					        [#"F1" = "chair", #"F2" = "crossing", #"F3" = 895.37],
					        [#"F1" = "laptop", #"F2" = "failure", #"F3" = 770.71],
					        [#"F1" = "hill", #"F2" = "managed", #"F3" = 887.43],
					        [#"F1" = "vary", #"F2" = "think", #"F3" = 923.25],
					        [#"F1" = "sa", #"F2" = "platinum", #"F3" = 52.8],
					        [#"F1" = "lb", #"F2" = "screening", #"F3" = 759.04],
					        [#"F1" = "until", #"F2" = "covering", #"F3" = 106.99],
					        [#"F1" = "mountains", #"F2" = "initiative", #"F3" = 977.63],
					        [#"F1" = "unable", #"F2" = "halloween", #"F3" = 308.91],
					        [#"F1" = "error", #"F2" = "shoot", #"F3" = 111.43],
					        [#"F1" = "retail", #"F2" = "plenty", #"F3" = 369.96],
					        [#"F1" = "attributes", #"F2" = "syntax", #"F3" = 530.14],
					        [#"F1" = "weekly", #"F2" = "teams", #"F3" = 209.63],
					        [#"F1" = "site", #"F2" = "criteria", #"F3" = 831.51],
					        [#"F1" = "oregon", #"F2" = "price", #"F3" = 117.79],
					        [#"F1" = "anti", #"F2" = "ok", #"F3" = 419.11],
					        [#"F1" = "gets", #"F2" = "global", #"F3" = 208.08],
					        [#"F1" = "quantum", #"F2" = "screening", #"F3" = 948.49],
					        [#"F1" = "camp", #"F2" = "take", #"F3" = 93.42],
					        [#"F1" = "aside", #"F2" = "diagnosis", #"F3" = 361.57],
					        [#"F1" = "sublime", #"F2" = "relatively", #"F3" = 718.37],
					        [#"F1" = "acid", #"F2" = "leaving", #"F3" = 9.47],
					        [#"F1" = "hear", #"F2" = "based", #"F3" = 454.46],
					        [#"F1" = "bring", #"F2" = "provide", #"F3" = 268.67],
					        [#"F1" = "opportunities", #"F2" = "first", #"F3" = 550.31],
					        [#"F1" = "student", #"F2" = "forecast", #"F3" = 875.15],
					        [#"F1" = "fleet", #"F2" = "happen", #"F3" = 957.71],
					        [#"F1" = "outer", #"F2" = "existence", #"F3" = 766.52],
					        [#"F1" = "care", #"F2" = "mile", #"F3" = 657.37],
					        [#"F1" = "independent", #"F2" = "glasgow", #"F3" = 645.12],
					        [#"F1" = "showing", #"F2" = "equally", #"F3" = 34.28],
					        [#"F1" = "violation", #"F2" = "cheap", #"F3" = 589.83],
					        [#"F1" = "sometimes", #"F2" = "grounds", #"F3" = 232.17],
					        [#"F1" = "women", #"F2" = "ssl", #"F3" = 472.13],
					        [#"F1" = "facilitate", #"F2" = "movie", #"F3" = 669.2],
					        [#"F1" = "temp", #"F2" = "exactly", #"F3" = 436.52],
					        [#"F1" = "technique", #"F2" = "rules", #"F3" = 627.8],
					        [#"F1" = "games", #"F2" = "sequence", #"F3" = 525.53],
					        [#"F1" = "applied", #"F2" = "spanking", #"F3" = 503.97],
					        [#"F1" = "regular", #"F2" = "rat", #"F3" = 932.01],
					        [#"F1" = "trying", #"F2" = "everything", #"F3" = 450.73],
					        [#"F1" = "henry", #"F2" = "response", #"F3" = 440.21],
					        [#"F1" = "jpg", #"F2" = "determine", #"F3" = 302.22],
					        [#"F1" = "prospective", #"F2" = "expense", #"F3" = 593.19],
					        [#"F1" = "police", #"F2" = "meal", #"F3" = 401.8],
					        [#"F1" = "oakland", #"F2" = "informational", #"F3" = 932.46],
					        [#"F1" = "available", #"F2" = "marine", #"F3" = 17.16],
					        [#"F1" = "bmw", #"F2" = "program", #"F3" = 137.09],
					        [#"F1" = "dragon", #"F2" = "calls", #"F3" = 620.57],
					        [#"F1" = "buyer", #"F2" = "iron", #"F3" = 126.46],
					        [#"F1" = "juvenile", #"F2" = "strike", #"F3" = 698.03],
					        [#"F1" = "neighborhood", #"F2" = "counseling", #"F3" = 536.89],
					        [#"F1" = "twiki", #"F2" = "initial", #"F3" = 600.03],
					        [#"F1" = "interactive", #"F2" = "processing", #"F3" = 181.58],
					        [#"F1" = "statutory", #"F2" = "equal", #"F3" = 63.69],
					        [#"F1" = "expensive", #"F2" = "shoe", #"F3" = 957.24],
					        [#"F1" = "reflect", #"F2" = "oracle", #"F3" = 822.47],
					        [#"F1" = "competitive", #"F2" = "cookie", #"F3" = 434.14],
					        [#"F1" = "matrix", #"F2" = "gm", #"F3" = 30.63],
					        [#"F1" = "laboratory", #"F2" = "still", #"F3" = 50.16],
					        [#"F1" = "engaged", #"F2" = "dna", #"F3" = 612.09],
					        [#"F1" = "look", #"F2" = "driven", #"F3" = 125.14],
					        [#"F1" = "agreed", #"F2" = "smart", #"F3" = 371.96],
					        [#"F1" = "moved", #"F2" = "efficient", #"F3" = 766.36],
					        [#"F1" = "better", #"F2" = "fantastic", #"F3" = 338.03],
					        [#"F1" = "bids", #"F2" = "given", #"F3" = 740.74],
					        [#"F1" = "commit", #"F2" = "tin", #"F3" = 667.82],
					        [#"F1" = "sf", #"F2" = "bedding", #"F3" = 39.67],
					        [#"F1" = "intent", #"F2" = "everybody", #"F3" = 118.17],
					        [#"F1" = "date", #"F2" = "numbers", #"F3" = 315.2],
					        [#"F1" = "directory", #"F2" = "casual", #"F3" = 890.84],
					        [#"F1" = "standing", #"F2" = "defense", #"F3" = 687.76],
					        [#"F1" = "thinking", #"F2" = "raw", #"F3" = 436.07],
					        [#"F1" = "rare", #"F2" = "donations", #"F3" = 811.69],
					        [#"F1" = "clause", #"F2" = "art", #"F3" = 547.77],
					        [#"F1" = "useful", #"F2" = "paris", #"F3" = 461.49],
					        [#"F1" = "mills", #"F2" = "christopher", #"F3" = 602.28],
					        [#"F1" = "lounge", #"F2" = "tn", #"F3" = 854.26],
					        [#"F1" = "happens", #"F2" = "birthday", #"F3" = 327.88],
					        [#"F1" = "announced", #"F2" = "lab", #"F3" = 973.59],
					        [#"F1" = "pmid", #"F2" = "mississippi", #"F3" = 775.41],
					        [#"F1" = "powder", #"F2" = "dublin", #"F3" = 386.49],
					        [#"F1" = "ignore", #"F2" = "cute", #"F3" = 133.11],
					        [#"F1" = "collectibles", #"F2" = "needs", #"F3" = 244.93],
					        [#"F1" = "mutual", #"F2" = "governments", #"F3" = 673.93],
					        [#"F1" = "opposition", #"F2" = "compression", #"F3" = 925.76],
					        [#"F1" = "into", #"F2" = "reliable", #"F3" = 541.7],
					        [#"F1" = "chase", #"F2" = "tue", #"F3" = 761.42],
					        [#"F1" = "powers", #"F2" = "hamilton", #"F3" = 997.98],
					        [#"F1" = "cables", #"F2" = "module", #"F3" = 48.25],
					        [#"F1" = "amd", #"F2" = "instruction", #"F3" = 409.38],
					        [#"F1" = "school", #"F2" = "desired", #"F3" = 594.74],
					        [#"F1" = "anymore", #"F2" = "serial", #"F3" = 108.57],
					        [#"F1" = "constitutes", #"F2" = "deputy", #"F3" = 607.87],
					        [#"F1" = "gonna", #"F2" = "outcome", #"F3" = 610.63],
					        [#"F1" = "standing", #"F2" = "austin", #"F3" = 796.07],
					        [#"F1" = "specialist", #"F2" = "eventually", #"F3" = 485.67],
					        [#"F1" = "virginia", #"F2" = "wayne", #"F3" = 470.51],
					        [#"F1" = "meta", #"F2" = "strategic", #"F3" = 582.51],
					        [#"F1" = "meal", #"F2" = "intended", #"F3" = 916.61],
					        [#"F1" = "before", #"F2" = "msg", #"F3" = 177.61],
					        [#"F1" = "union", #"F2" = "habitat", #"F3" = 762.68],
					        [#"F1" = "code", #"F2" = "hd", #"F3" = 448.9],
					        [#"F1" = "grand", #"F2" = "missing", #"F3" = 683.27],
					        [#"F1" = "denmark", #"F2" = "fill", #"F3" = 890.22],
					        [#"F1" = "electronics", #"F2" = "kitchen", #"F3" = 645.51],
					        [#"F1" = "freedom", #"F2" = "states", #"F3" = 612.2],
					        [#"F1" = "ii", #"F2" = "their", #"F3" = 344.87],
					        [#"F1" = "permanent", #"F2" = "payments", #"F3" = 219.26],
					        [#"F1" = "int", #"F2" = "radiation", #"F3" = 131.87],
					        [#"F1" = "marked", #"F2" = "practices", #"F3" = 716.86],
					        [#"F1" = "pearl", #"F2" = "shareware", #"F3" = 545.09],
					        [#"F1" = "league", #"F2" = "per", #"F3" = 169.94],
					        [#"F1" = "labor", #"F2" = "sacramento", #"F3" = 789.33],
					        [#"F1" = "advertising", #"F2" = "really", #"F3" = 263.13],
					        [#"F1" = "compact", #"F2" = "installed", #"F3" = 944.7],
					        [#"F1" = "meaning", #"F2" = "template", #"F3" = 152.31],
					        [#"F1" = "ford", #"F2" = "fault", #"F3" = 980.85],
					        [#"F1" = "john", #"F2" = "benefits", #"F3" = 829.01],
					        [#"F1" = "spirit", #"F2" = "switch", #"F3" = 987.4],
					        [#"F1" = "pupils", #"F2" = "verification", #"F3" = 60.53],
					        [#"F1" = "knowing", #"F2" = "sector", #"F3" = 98.87],
					        [#"F1" = "classic", #"F2" = "cruise", #"F3" = 947.81],
					        [#"F1" = "companies", #"F2" = "three", #"F3" = 332.53],
					        [#"F1" = "absolutely", #"F2" = "pay", #"F3" = 322.1],
					        [#"F1" = "usr", #"F2" = "wow", #"F3" = 558.06],
					        [#"F1" = "prevent", #"F2" = "trademarks", #"F3" = 148.77],
					        [#"F1" = "iii", #"F2" = "bureau", #"F3" = 63.04],
					        [#"F1" = "hosted", #"F2" = "guilty", #"F3" = 39.62],
					        [#"F1" = "rugby", #"F2" = "catalogue", #"F3" = 778.05],
					        [#"F1" = "texts", #"F2" = "under", #"F3" = 751.3],
					        [#"F1" = "kernel", #"F2" = "workforce", #"F3" = 379.04],
					        [#"F1" = "organizations", #"F2" = "directions", #"F3" = 50.78],
					        [#"F1" = "download", #"F2" = "thumbs", #"F3" = 869.41],
					        [#"F1" = "access", #"F2" = "secure", #"F3" = 805.37],
					        [#"F1" = "reduction", #"F2" = "love", #"F3" = 431.39],
					        [#"F1" = "symptoms", #"F2" = "espn", #"F3" = 53.38],
					        [#"F1" = "residence", #"F2" = "poker", #"F3" = 889.51],
					        [#"F1" = "adjusted", #"F2" = "referral", #"F3" = 596.3],
					        [#"F1" = "crossing", #"F2" = "prev", #"F3" = 665.25],
					        [#"F1" = "destruction", #"F2" = "avg", #"F3" = 589.54],
					        [#"F1" = "text", #"F2" = "te", #"F3" = 824.75],
					        [#"F1" = "yellow", #"F2" = "feelings", #"F3" = 937.42],
					        [#"F1" = "wednesday", #"F2" = "tank", #"F3" = 675.9],
					        [#"F1" = "delivered", #"F2" = "concert", #"F3" = 19.97],
					        [#"F1" = "clause", #"F2" = "african", #"F3" = 426.58],
					        [#"F1" = "alternatives", #"F2" = "definitely", #"F3" = 174.61],
					        [#"F1" = "signed", #"F2" = "nigeria", #"F3" = 644.59],
					        [#"F1" = "cause", #"F2" = "sounds", #"F3" = 281.69],
					        [#"F1" = "ordinary", #"F2" = "cincinnati", #"F3" = 862.0],
					        [#"F1" = "courts", #"F2" = "obtained", #"F3" = 217.98],
					        [#"F1" = "jeans", #"F2" = "serious", #"F3" = 464.33],
					        [#"F1" = "fair", #"F2" = "que", #"F3" = 439.16],
					        [#"F1" = "target", #"F2" = "trailers", #"F3" = 103.09],
					        [#"F1" = "guaranteed", #"F2" = "flights", #"F3" = 942.11],
					        [#"F1" = "hilton", #"F2" = "cap", #"F3" = 45.92],
					        [#"F1" = "directions", #"F2" = "consultant", #"F3" = 771.24],
					        [#"F1" = "frequency", #"F2" = "crash", #"F3" = 301.58],
					        [#"F1" = "usb", #"F2" = "relation", #"F3" = 903.49],
					        [#"F1" = "addressed", #"F2" = "hotels", #"F3" = 212.14],
					        [#"F1" = "certified", #"F2" = "relative", #"F3" = 521.88],
					        [#"F1" = "argentina", #"F2" = "bookmark", #"F3" = 240.6],
					        [#"F1" = "topic", #"F2" = "clerk", #"F3" = 279.39],
					        [#"F1" = "excess", #"F2" = "ent", #"F3" = 159.86],
					        [#"F1" = "thomas", #"F2" = "killer", #"F3" = 382.38],
					        [#"F1" = "tracker", #"F2" = "automatically", #"F3" = 16.7],
					        [#"F1" = "sharing", #"F2" = "ontario", #"F3" = 698.1],
					        [#"F1" = "is", #"F2" = "headset", #"F3" = 6.84],
					        [#"F1" = "ordering", #"F2" = "ecommerce", #"F3" = 816.81],
					        [#"F1" = "launch", #"F2" = "jr", #"F3" = 919.57],
					        [#"F1" = "lifestyle", #"F2" = "slot", #"F3" = 623.51],
					        [#"F1" = "arena", #"F2" = "permalink", #"F3" = 41.97],
					        [#"F1" = "latter", #"F2" = "explore", #"F3" = 416.71],
					        [#"F1" = "small", #"F2" = "objective", #"F3" = 986.37],
					        [#"F1" = "businesses", #"F2" = "infection", #"F3" = 546.27],
					        [#"F1" = "stations", #"F2" = "sunglasses", #"F3" = 99.91],
					        [#"F1" = "york", #"F2" = "nights", #"F3" = 626.12],
					        [#"F1" = "sunset", #"F2" = "technical", #"F3" = 445.62],
					        [#"F1" = "choose", #"F2" = "versus", #"F3" = 697.03],
					        [#"F1" = "we", #"F2" = "symbol", #"F3" = 853.11],
					        [#"F1" = "currency", #"F2" = "kernel", #"F3" = 658.97],
					        [#"F1" = "tracking", #"F2" = "enforcement", #"F3" = 132.46],
					        [#"F1" = "helping", #"F2" = "pupils", #"F3" = 580.23],
					        [#"F1" = "counties", #"F2" = "chief", #"F3" = 670.07],
					        [#"F1" = "world", #"F2" = "yesterday", #"F3" = 408.56],
					        [#"F1" = "social", #"F2" = "completely", #"F3" = 704.28],
					        [#"F1" = "totals", #"F2" = "developed", #"F3" = 29.58],
					        [#"F1" = "catalogue", #"F2" = "tiny", #"F3" = 186.62],
					        [#"F1" = "del", #"F2" = "facility", #"F3" = 23.39],
					        [#"F1" = "premium", #"F2" = "wireless", #"F3" = 579.98],
					        [#"F1" = "illegal", #"F2" = "regular", #"F3" = 880.91],
					        [#"F1" = "careers", #"F2" = "extend", #"F3" = 569.35],
					        [#"F1" = "everybody", #"F2" = "attractive", #"F3" = 254.05],
					        [#"F1" = "run", #"F2" = "vehicles", #"F3" = 854.78],
					        [#"F1" = "silk", #"F2" = "filter", #"F3" = 633.91],
					        [#"F1" = "minimum", #"F2" = "characteristics", #"F3" = 515.63],
					        [#"F1" = "contained", #"F2" = "finance", #"F3" = 250.5]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"F1", type text},
					        {"F2", type text},
					        {"F3", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table