table 'AE Benchmarks (FINAL Consolidated Dashboard Data with Charts 5_6_19)_AE GED 4'
	lineageTag: 53bc36ba-89e6-4fb1-bfe3-11e83f70e155

	column 'Passing all four GED® sections'
		dataType: double
		formatString: General Number
		lineageTag: 7f2aaa1b-7106-4797-9117-24678fb99d7c
		summarizeBy: sum
		sourceColumn: 'Passing all four GED® sections'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column F2
		dataType: string
		lineageTag: df2aad2c-cdfa-46e9-bc6e-4b76964db5f5
		summarizeBy: none
		sourceColumn: F2

		annotation SummarizationSetBy = Automatic

	column F3
		dataType: int64
		formatString: 0
		lineageTag: e7fb7914-69c8-4bd6-a7a0-e486d6cad557
		summarizeBy: sum
		sourceColumn: F3

		annotation SummarizationSetBy = Automatic

	partition 'AE Benchmarks (FINAL Consolidated Dashboard Data with Charts 5_6_19)_AE GED 4' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Passing all four GED® sections" = 358.82, #"F2" = "existing", #"F3" = 31],
					        [#"Passing all four GED® sections" = 913.05, #"F2" = "portuguese", #"F3" = 589],
					        [#"Passing all four GED® sections" = 794.57, #"F2" = "in", #"F3" = 646],
					        [#"Passing all four GED® sections" = 886.0, #"F2" = "announcement", #"F3" = 133],
					        [#"Passing all four GED® sections" = 741.52, #"F2" = "restricted", #"F3" = 292],
					        [#"Passing all four GED® sections" = 848.81, #"F2" = "toe", #"F3" = 685],
					        [#"Passing all four GED® sections" = 751.47, #"F2" = "fair", #"F3" = 15],
					        [#"Passing all four GED® sections" = 805.2, #"F2" = "lewis", #"F3" = 368],
					        [#"Passing all four GED® sections" = 853.05, #"F2" = "equity", #"F3" = 528],
					        [#"Passing all four GED® sections" = 408.08, #"F2" = "maintained", #"F3" = 965],
					        [#"Passing all four GED® sections" = 958.14, #"F2" = "combine", #"F3" = 504],
					        [#"Passing all four GED® sections" = 385.38, #"F2" = "identify", #"F3" = 659],
					        [#"Passing all four GED® sections" = 107.16, #"F2" = "litigation", #"F3" = 451],
					        [#"Passing all four GED® sections" = 758.6, #"F2" = "attribute", #"F3" = 930],
					        [#"Passing all four GED® sections" = 0.02, #"F2" = "stability", #"F3" = 756],
					        [#"Passing all four GED® sections" = 415.11, #"F2" = "fix", #"F3" = 279],
					        [#"Passing all four GED® sections" = 777.61, #"F2" = "operate", #"F3" = 95],
					        [#"Passing all four GED® sections" = 56.79, #"F2" = "issued", #"F3" = 598],
					        [#"Passing all four GED® sections" = 156.51, #"F2" = "classic", #"F3" = 582],
					        [#"Passing all four GED® sections" = 553.84, #"F2" = "tuesday", #"F3" = 968],
					        [#"Passing all four GED® sections" = 956.73, #"F2" = "rehabilitation", #"F3" = 608],
					        [#"Passing all four GED® sections" = 432.6, #"F2" = "tight", #"F3" = 225],
					        [#"Passing all four GED® sections" = 823.87, #"F2" = "legislative", #"F3" = 228],
					        [#"Passing all four GED® sections" = 141.1, #"F2" = "issued", #"F3" = 647],
					        [#"Passing all four GED® sections" = 368.4, #"F2" = "ct", #"F3" = 816],
					        [#"Passing all four GED® sections" = 790.27, #"F2" = "silk", #"F3" = 835],
					        [#"Passing all four GED® sections" = 654.49, #"F2" = "posts", #"F3" = 421],
					        [#"Passing all four GED® sections" = 295.28, #"F2" = "configure", #"F3" = 451],
					        [#"Passing all four GED® sections" = 33.64, #"F2" = "technique", #"F3" = 257],
					        [#"Passing all four GED® sections" = 723.64, #"F2" = "famous", #"F3" = 822],
					        [#"Passing all four GED® sections" = 424.74, #"F2" = "using", #"F3" = 837],
					        [#"Passing all four GED® sections" = 110.16, #"F2" = "postposted", #"F3" = 567],
					        [#"Passing all four GED® sections" = 435.61, #"F2" = "lb", #"F3" = 2],
					        [#"Passing all four GED® sections" = 171.49, #"F2" = "nelson", #"F3" = 945],
					        [#"Passing all four GED® sections" = 229.98, #"F2" = "tickets", #"F3" = 958],
					        [#"Passing all four GED® sections" = 854.35, #"F2" = "philippines", #"F3" = 865],
					        [#"Passing all four GED® sections" = 143.35, #"F2" = "registry", #"F3" = 153],
					        [#"Passing all four GED® sections" = 82.92, #"F2" = "cabinet", #"F3" = 148],
					        [#"Passing all four GED® sections" = 795.35, #"F2" = "customs", #"F3" = 466],
					        [#"Passing all four GED® sections" = 545.51, #"F2" = "reduced", #"F3" = 539],
					        [#"Passing all four GED® sections" = 696.64, #"F2" = "landscape", #"F3" = 400],
					        [#"Passing all four GED® sections" = 725.31, #"F2" = "brings", #"F3" = 741],
					        [#"Passing all four GED® sections" = 921.85, #"F2" = "witness", #"F3" = 104],
					        [#"Passing all four GED® sections" = 733.06, #"F2" = "show", #"F3" = 923],
					        [#"Passing all four GED® sections" = 370.85, #"F2" = "season", #"F3" = 444],
					        [#"Passing all four GED® sections" = 302.07, #"F2" = "studio", #"F3" = 256],
					        [#"Passing all four GED® sections" = 517.87, #"F2" = "samsung", #"F3" = 541],
					        [#"Passing all four GED® sections" = 551.48, #"F2" = "authors", #"F3" = 452],
					        [#"Passing all four GED® sections" = 466.7, #"F2" = "phil", #"F3" = 657],
					        [#"Passing all four GED® sections" = 31.0, #"F2" = "shown", #"F3" = 2],
					        [#"Passing all four GED® sections" = 798.13, #"F2" = "consumer", #"F3" = 815],
					        [#"Passing all four GED® sections" = 378.73, #"F2" = "column", #"F3" = 490],
					        [#"Passing all four GED® sections" = 382.43, #"F2" = "actors", #"F3" = 382],
					        [#"Passing all four GED® sections" = 954.76, #"F2" = "vacations", #"F3" = 936],
					        [#"Passing all four GED® sections" = 942.65, #"F2" = "warehouse", #"F3" = 466],
					        [#"Passing all four GED® sections" = 650.46, #"F2" = "dispatched", #"F3" = 761],
					        [#"Passing all four GED® sections" = 929.06, #"F2" = "purchasing", #"F3" = 123],
					        [#"Passing all four GED® sections" = 67.29, #"F2" = "thermal", #"F3" = 599],
					        [#"Passing all four GED® sections" = 285.2, #"F2" = "concept", #"F3" = 588],
					        [#"Passing all four GED® sections" = 997.64, #"F2" = "harris", #"F3" = 11],
					        [#"Passing all four GED® sections" = 731.85, #"F2" = "stage", #"F3" = 405],
					        [#"Passing all four GED® sections" = 821.78, #"F2" = "pop", #"F3" = 482],
					        [#"Passing all four GED® sections" = 147.65, #"F2" = "storage", #"F3" = 474],
					        [#"Passing all four GED® sections" = 839.99, #"F2" = "offer", #"F3" = 719],
					        [#"Passing all four GED® sections" = 749.39, #"F2" = "flexibility", #"F3" = 651],
					        [#"Passing all four GED® sections" = 271.12, #"F2" = "places", #"F3" = 648],
					        [#"Passing all four GED® sections" = 493.68, #"F2" = "anarchist", #"F3" = 849],
					        [#"Passing all four GED® sections" = 618.56, #"F2" = "users", #"F3" = 510],
					        [#"Passing all four GED® sections" = 578.52, #"F2" = "via", #"F3" = 42],
					        [#"Passing all four GED® sections" = 674.17, #"F2" = "spectacular", #"F3" = 795],
					        [#"Passing all four GED® sections" = 834.3, #"F2" = "wholesale", #"F3" = 98],
					        [#"Passing all four GED® sections" = 985.92, #"F2" = "map", #"F3" = 43],
					        [#"Passing all four GED® sections" = 49.87, #"F2" = "powerful", #"F3" = 834],
					        [#"Passing all four GED® sections" = 342.71, #"F2" = "anne", #"F3" = 43],
					        [#"Passing all four GED® sections" = 878.43, #"F2" = "ee", #"F3" = 854],
					        [#"Passing all four GED® sections" = 120.0, #"F2" = "compare", #"F3" = 420],
					        [#"Passing all four GED® sections" = 349.59, #"F2" = "ap", #"F3" = 163],
					        [#"Passing all four GED® sections" = 164.36, #"F2" = "interviews", #"F3" = 353],
					        [#"Passing all four GED® sections" = 830.76, #"F2" = "columbia", #"F3" = 616],
					        [#"Passing all four GED® sections" = 745.19, #"F2" = "items", #"F3" = 299],
					        [#"Passing all four GED® sections" = 656.36, #"F2" = "theory", #"F3" = 82],
					        [#"Passing all four GED® sections" = 511.31, #"F2" = "himself", #"F3" = 459],
					        [#"Passing all four GED® sections" = 459.65, #"F2" = "aware", #"F3" = 201],
					        [#"Passing all four GED® sections" = 572.15, #"F2" = "finish", #"F3" = 999],
					        [#"Passing all four GED® sections" = 813.7, #"F2" = "epinions", #"F3" = 622],
					        [#"Passing all four GED® sections" = 150.85, #"F2" = "trace", #"F3" = 356],
					        [#"Passing all four GED® sections" = 400.54, #"F2" = "assets", #"F3" = 919],
					        [#"Passing all four GED® sections" = 522.37, #"F2" = "gnome", #"F3" = 458],
					        [#"Passing all four GED® sections" = 470.73, #"F2" = "question", #"F3" = 128],
					        [#"Passing all four GED® sections" = 501.39, #"F2" = "certificate", #"F3" = 568],
					        [#"Passing all four GED® sections" = 471.89, #"F2" = "kings", #"F3" = 750],
					        [#"Passing all four GED® sections" = 874.21, #"F2" = "regardless", #"F3" = 586],
					        [#"Passing all four GED® sections" = 964.26, #"F2" = "java", #"F3" = 680],
					        [#"Passing all four GED® sections" = 16.98, #"F2" = "vacations", #"F3" = 883],
					        [#"Passing all four GED® sections" = 745.86, #"F2" = "lucky", #"F3" = 583],
					        [#"Passing all four GED® sections" = 29.48, #"F2" = "disclaimer", #"F3" = 251],
					        [#"Passing all four GED® sections" = 366.29, #"F2" = "comic", #"F3" = 739],
					        [#"Passing all four GED® sections" = 672.8, #"F2" = "ha", #"F3" = 852],
					        [#"Passing all four GED® sections" = 772.12, #"F2" = "equivalent", #"F3" = 917],
					        [#"Passing all four GED® sections" = 188.49, #"F2" = "pro", #"F3" = 629],
					        [#"Passing all four GED® sections" = 580.54, #"F2" = "factor", #"F3" = 842],
					        [#"Passing all four GED® sections" = 524.17, #"F2" = "ch", #"F3" = 104],
					        [#"Passing all four GED® sections" = 179.39, #"F2" = "bold", #"F3" = 858],
					        [#"Passing all four GED® sections" = 533.97, #"F2" = "continental", #"F3" = 922],
					        [#"Passing all four GED® sections" = 312.04, #"F2" = "takes", #"F3" = 840],
					        [#"Passing all four GED® sections" = 31.11, #"F2" = "grace", #"F3" = 322],
					        [#"Passing all four GED® sections" = 328.43, #"F2" = "tion", #"F3" = 396],
					        [#"Passing all four GED® sections" = 25.82, #"F2" = "rr", #"F3" = 413],
					        [#"Passing all four GED® sections" = 957.41, #"F2" = "fl", #"F3" = 291],
					        [#"Passing all four GED® sections" = 983.14, #"F2" = "productions", #"F3" = 283],
					        [#"Passing all four GED® sections" = 33.55, #"F2" = "northern", #"F3" = 537],
					        [#"Passing all four GED® sections" = 651.18, #"F2" = "look", #"F3" = 201],
					        [#"Passing all four GED® sections" = 948.28, #"F2" = "torture", #"F3" = 1000],
					        [#"Passing all four GED® sections" = 795.9, #"F2" = "called", #"F3" = 689],
					        [#"Passing all four GED® sections" = 872.83, #"F2" = "murray", #"F3" = 144],
					        [#"Passing all four GED® sections" = 955.75, #"F2" = "younger", #"F3" = 485],
					        [#"Passing all four GED® sections" = 182.98, #"F2" = "charge", #"F3" = 203],
					        [#"Passing all four GED® sections" = 666.15, #"F2" = "applicants", #"F3" = 346],
					        [#"Passing all four GED® sections" = 845.63, #"F2" = "award", #"F3" = 857],
					        [#"Passing all four GED® sections" = 829.82, #"F2" = "arguments", #"F3" = 509],
					        [#"Passing all four GED® sections" = 178.64, #"F2" = "potential", #"F3" = 285],
					        [#"Passing all four GED® sections" = 341.38, #"F2" = "lies", #"F3" = 273],
					        [#"Passing all four GED® sections" = 672.34, #"F2" = "mobility", #"F3" = 739],
					        [#"Passing all four GED® sections" = 519.81, #"F2" = "production", #"F3" = 947],
					        [#"Passing all four GED® sections" = 968.6, #"F2" = "motorcycle", #"F3" = 937],
					        [#"Passing all four GED® sections" = 41.52, #"F2" = "warren", #"F3" = 995],
					        [#"Passing all four GED® sections" = 741.81, #"F2" = "webcam", #"F3" = 861],
					        [#"Passing all four GED® sections" = 13.35, #"F2" = "discovered", #"F3" = 879],
					        [#"Passing all four GED® sections" = 357.24, #"F2" = "producers", #"F3" = 210],
					        [#"Passing all four GED® sections" = 830.16, #"F2" = "workshops", #"F3" = 415],
					        [#"Passing all four GED® sections" = 642.92, #"F2" = "wins", #"F3" = 679],
					        [#"Passing all four GED® sections" = 578.62, #"F2" = "paypal", #"F3" = 22],
					        [#"Passing all four GED® sections" = 264.53, #"F2" = "custom", #"F3" = 212],
					        [#"Passing all four GED® sections" = 21.41, #"F2" = "obtain", #"F3" = 1000],
					        [#"Passing all four GED® sections" = 188.45, #"F2" = "seasonal", #"F3" = 457],
					        [#"Passing all four GED® sections" = 782.14, #"F2" = "fundamental", #"F3" = 396],
					        [#"Passing all four GED® sections" = 132.07, #"F2" = "okay", #"F3" = 165],
					        [#"Passing all four GED® sections" = 51.09, #"F2" = "learn", #"F3" = 27],
					        [#"Passing all four GED® sections" = 699.66, #"F2" = "their", #"F3" = 509],
					        [#"Passing all four GED® sections" = 440.29, #"F2" = "regarding", #"F3" = 590],
					        [#"Passing all four GED® sections" = 148.74, #"F2" = "structural", #"F3" = 968],
					        [#"Passing all four GED® sections" = 496.49, #"F2" = "accordance", #"F3" = 361],
					        [#"Passing all four GED® sections" = 421.58, #"F2" = "baltimore", #"F3" = 967],
					        [#"Passing all four GED® sections" = 732.23, #"F2" = "voluntary", #"F3" = 361],
					        [#"Passing all four GED® sections" = 509.47, #"F2" = "level", #"F3" = 350],
					        [#"Passing all four GED® sections" = 502.27, #"F2" = "photography", #"F3" = 323],
					        [#"Passing all four GED® sections" = 534.06, #"F2" = "aim", #"F3" = 313],
					        [#"Passing all four GED® sections" = 79.77, #"F2" = "bag", #"F3" = 348],
					        [#"Passing all four GED® sections" = 50.16, #"F2" = "crafts", #"F3" = 461],
					        [#"Passing all four GED® sections" = 862.92, #"F2" = "tips", #"F3" = 794],
					        [#"Passing all four GED® sections" = 636.59, #"F2" = "mistake", #"F3" = 508],
					        [#"Passing all four GED® sections" = 449.71, #"F2" = "payment", #"F3" = 465],
					        [#"Passing all four GED® sections" = 507.16, #"F2" = "transferred", #"F3" = 423],
					        [#"Passing all four GED® sections" = 939.4, #"F2" = "cooperation", #"F3" = 1000],
					        [#"Passing all four GED® sections" = 711.49, #"F2" = "stability", #"F3" = 722],
					        [#"Passing all four GED® sections" = 897.43, #"F2" = "deutsch", #"F3" = 211],
					        [#"Passing all four GED® sections" = 537.68, #"F2" = "role", #"F3" = 984],
					        [#"Passing all four GED® sections" = 71.7, #"F2" = "cpu", #"F3" = 516],
					        [#"Passing all four GED® sections" = 547.16, #"F2" = "however", #"F3" = 926],
					        [#"Passing all four GED® sections" = 428.02, #"F2" = "these", #"F3" = 521],
					        [#"Passing all four GED® sections" = 390.99, #"F2" = "drive", #"F3" = 576],
					        [#"Passing all four GED® sections" = 680.14, #"F2" = "chile", #"F3" = 316],
					        [#"Passing all four GED® sections" = 538.02, #"F2" = "due", #"F3" = 575],
					        [#"Passing all four GED® sections" = 373.33, #"F2" = "axis", #"F3" = 441],
					        [#"Passing all four GED® sections" = 798.78, #"F2" = "wikipedia", #"F3" = 213],
					        [#"Passing all four GED® sections" = 407.2, #"F2" = "featured", #"F3" = 334],
					        [#"Passing all four GED® sections" = 532.0, #"F2" = "noted", #"F3" = 467],
					        [#"Passing all four GED® sections" = 382.26, #"F2" = "ng", #"F3" = 504],
					        [#"Passing all four GED® sections" = 891.95, #"F2" = "allows", #"F3" = 579],
					        [#"Passing all four GED® sections" = 398.26, #"F2" = "affiliates", #"F3" = 374],
					        [#"Passing all four GED® sections" = 574.07, #"F2" = "cyprus", #"F3" = 196],
					        [#"Passing all four GED® sections" = 331.55, #"F2" = "principle", #"F3" = 923],
					        [#"Passing all four GED® sections" = 544.8, #"F2" = "fails", #"F3" = 803],
					        [#"Passing all four GED® sections" = 618.04, #"F2" = "automatic", #"F3" = 620],
					        [#"Passing all four GED® sections" = 332.76, #"F2" = "nylon", #"F3" = 898],
					        [#"Passing all four GED® sections" = 945.4, #"F2" = "diesel", #"F3" = 313],
					        [#"Passing all four GED® sections" = 255.76, #"F2" = "outer", #"F3" = 11],
					        [#"Passing all four GED® sections" = 865.96, #"F2" = "systems", #"F3" = 420],
					        [#"Passing all four GED® sections" = 184.53, #"F2" = "glory", #"F3" = 9],
					        [#"Passing all four GED® sections" = 470.0, #"F2" = "venue", #"F3" = 516],
					        [#"Passing all four GED® sections" = 455.99, #"F2" = "walking", #"F3" = 186],
					        [#"Passing all four GED® sections" = 279.12, #"F2" = "scheme", #"F3" = 843],
					        [#"Passing all four GED® sections" = 368.72, #"F2" = "worked", #"F3" = 632],
					        [#"Passing all four GED® sections" = 867.38, #"F2" = "deals", #"F3" = 733],
					        [#"Passing all four GED® sections" = 455.3, #"F2" = "doctor", #"F3" = 9],
					        [#"Passing all four GED® sections" = 435.87, #"F2" = "burn", #"F3" = 118],
					        [#"Passing all four GED® sections" = 226.17, #"F2" = "illegal", #"F3" = 432],
					        [#"Passing all four GED® sections" = 431.77, #"F2" = "const", #"F3" = 620],
					        [#"Passing all four GED® sections" = 941.66, #"F2" = "operational", #"F3" = 562],
					        [#"Passing all four GED® sections" = 588.32, #"F2" = "matrix", #"F3" = 236],
					        [#"Passing all four GED® sections" = 261.73, #"F2" = "soccer", #"F3" = 645],
					        [#"Passing all four GED® sections" = 68.91, #"F2" = "sold", #"F3" = 420],
					        [#"Passing all four GED® sections" = 204.04, #"F2" = "naturally", #"F3" = 477],
					        [#"Passing all four GED® sections" = 270.38, #"F2" = "logic", #"F3" = 380],
					        [#"Passing all four GED® sections" = 395.43, #"F2" = "park", #"F3" = 359],
					        [#"Passing all four GED® sections" = 36.91, #"F2" = "demonstrated", #"F3" = 305],
					        [#"Passing all four GED® sections" = 789.88, #"F2" = "modem", #"F3" = 373],
					        [#"Passing all four GED® sections" = 635.81, #"F2" = "areas", #"F3" = 585],
					        [#"Passing all four GED® sections" = 364.78, #"F2" = "bible", #"F3" = 119],
					        [#"Passing all four GED® sections" = 780.14, #"F2" = "carry", #"F3" = 479],
					        [#"Passing all four GED® sections" = 635.71, #"F2" = "copper", #"F3" = 60],
					        [#"Passing all four GED® sections" = 437.22, #"F2" = "courses", #"F3" = 181],
					        [#"Passing all four GED® sections" = 555.15, #"F2" = "quest", #"F3" = 511],
					        [#"Passing all four GED® sections" = 445.55, #"F2" = "communities", #"F3" = 713],
					        [#"Passing all four GED® sections" = 483.53, #"F2" = "juice", #"F3" = 829],
					        [#"Passing all four GED® sections" = 980.45, #"F2" = "illegal", #"F3" = 525],
					        [#"Passing all four GED® sections" = 214.46, #"F2" = "federal", #"F3" = 702],
					        [#"Passing all four GED® sections" = 666.26, #"F2" = "gm", #"F3" = 490],
					        [#"Passing all four GED® sections" = 238.43, #"F2" = "monster", #"F3" = 359],
					        [#"Passing all four GED® sections" = 919.74, #"F2" = "hazardous", #"F3" = 830],
					        [#"Passing all four GED® sections" = 379.56, #"F2" = "discount", #"F3" = 845],
					        [#"Passing all four GED® sections" = 809.23, #"F2" = "maria", #"F3" = 656],
					        [#"Passing all four GED® sections" = 267.86, #"F2" = "obviously", #"F3" = 201],
					        [#"Passing all four GED® sections" = 132.44, #"F2" = "failure", #"F3" = 944],
					        [#"Passing all four GED® sections" = 27.78, #"F2" = "motorcycle", #"F3" = 414],
					        [#"Passing all four GED® sections" = 591.17, #"F2" = "ensure", #"F3" = 996],
					        [#"Passing all four GED® sections" = 231.03, #"F2" = "poland", #"F3" = 170],
					        [#"Passing all four GED® sections" = 561.57, #"F2" = "packet", #"F3" = 613],
					        [#"Passing all four GED® sections" = 425.51, #"F2" = "loop", #"F3" = 233],
					        [#"Passing all four GED® sections" = 23.74, #"F2" = "massive", #"F3" = 86],
					        [#"Passing all four GED® sections" = 450.71, #"F2" = "visitor", #"F3" = 55],
					        [#"Passing all four GED® sections" = 332.7, #"F2" = "pot", #"F3" = 250],
					        [#"Passing all four GED® sections" = 344.71, #"F2" = "kb", #"F3" = 946],
					        [#"Passing all four GED® sections" = 142.39, #"F2" = "senator", #"F3" = 520],
					        [#"Passing all four GED® sections" = 807.42, #"F2" = "holder", #"F3" = 452],
					        [#"Passing all four GED® sections" = 342.96, #"F2" = "merchandise", #"F3" = 729],
					        [#"Passing all four GED® sections" = 749.05, #"F2" = "clicking", #"F3" = 600],
					        [#"Passing all four GED® sections" = 599.2, #"F2" = "styles", #"F3" = 271],
					        [#"Passing all four GED® sections" = 642.23, #"F2" = "discover", #"F3" = 52],
					        [#"Passing all four GED® sections" = 130.39, #"F2" = "information", #"F3" = 720],
					        [#"Passing all four GED® sections" = 122.15, #"F2" = "experiences", #"F3" = 816],
					        [#"Passing all four GED® sections" = 967.82, #"F2" = "asset", #"F3" = 14],
					        [#"Passing all four GED® sections" = 366.91, #"F2" = "dual", #"F3" = 32],
					        [#"Passing all four GED® sections" = 141.31, #"F2" = "regular", #"F3" = 494],
					        [#"Passing all four GED® sections" = 517.59, #"F2" = "talent", #"F3" = 277],
					        [#"Passing all four GED® sections" = 141.52, #"F2" = "statistical", #"F3" = 443],
					        [#"Passing all four GED® sections" = 73.52, #"F2" = "mi", #"F3" = 943],
					        [#"Passing all four GED® sections" = 923.86, #"F2" = "loose", #"F3" = 350],
					        [#"Passing all four GED® sections" = 675.61, #"F2" = "absence", #"F3" = 955],
					        [#"Passing all four GED® sections" = 724.79, #"F2" = "increase", #"F3" = 637],
					        [#"Passing all four GED® sections" = 98.63, #"F2" = "verify", #"F3" = 957],
					        [#"Passing all four GED® sections" = 40.76, #"F2" = "thursday", #"F3" = 104],
					        [#"Passing all four GED® sections" = 383.16, #"F2" = "detroit", #"F3" = 309],
					        [#"Passing all four GED® sections" = 928.26, #"F2" = "item", #"F3" = 101],
					        [#"Passing all four GED® sections" = 542.56, #"F2" = "earned", #"F3" = 225],
					        [#"Passing all four GED® sections" = 901.09, #"F2" = "farmer", #"F3" = 865],
					        [#"Passing all four GED® sections" = 441.41, #"F2" = "disposal", #"F3" = 12],
					        [#"Passing all four GED® sections" = 9.21, #"F2" = "cl", #"F3" = 639],
					        [#"Passing all four GED® sections" = 219.75, #"F2" = "china", #"F3" = 706],
					        [#"Passing all four GED® sections" = 931.61, #"F2" = "detailed", #"F3" = 201],
					        [#"Passing all four GED® sections" = 354.88, #"F2" = "languages", #"F3" = 122],
					        [#"Passing all four GED® sections" = 887.58, #"F2" = "output", #"F3" = 474],
					        [#"Passing all four GED® sections" = 683.76, #"F2" = "centre", #"F3" = 584],
					        [#"Passing all four GED® sections" = 217.47, #"F2" = "fed", #"F3" = 48],
					        [#"Passing all four GED® sections" = 633.54, #"F2" = "hewlett", #"F3" = 949],
					        [#"Passing all four GED® sections" = 208.05, #"F2" = "mary", #"F3" = 480],
					        [#"Passing all four GED® sections" = 541.56, #"F2" = "polish", #"F3" = 335],
					        [#"Passing all four GED® sections" = 801.17, #"F2" = "showed", #"F3" = 471],
					        [#"Passing all four GED® sections" = 183.51, #"F2" = "combine", #"F3" = 336],
					        [#"Passing all four GED® sections" = 659.79, #"F2" = "realized", #"F3" = 770],
					        [#"Passing all four GED® sections" = 838.1, #"F2" = "dropped", #"F3" = 973],
					        [#"Passing all four GED® sections" = 591.92, #"F2" = "creek", #"F3" = 27],
					        [#"Passing all four GED® sections" = 549.38, #"F2" = "shows", #"F3" = 979],
					        [#"Passing all four GED® sections" = 20.36, #"F2" = "nikon", #"F3" = 45],
					        [#"Passing all four GED® sections" = 489.41, #"F2" = "relation", #"F3" = 339],
					        [#"Passing all four GED® sections" = 644.89, #"F2" = "convention", #"F3" = 574],
					        [#"Passing all four GED® sections" = 220.61, #"F2" = "producer", #"F3" = 568],
					        [#"Passing all four GED® sections" = 510.04, #"F2" = "represent", #"F3" = 129],
					        [#"Passing all four GED® sections" = 454.89, #"F2" = "fleet", #"F3" = 445],
					        [#"Passing all four GED® sections" = 812.22, #"F2" = "republic", #"F3" = 527],
					        [#"Passing all four GED® sections" = 986.1, #"F2" = "switches", #"F3" = 585],
					        [#"Passing all four GED® sections" = 869.73, #"F2" = "cleaner", #"F3" = 40],
					        [#"Passing all four GED® sections" = 692.08, #"F2" = "read", #"F3" = 514],
					        [#"Passing all four GED® sections" = 796.86, #"F2" = "oklahoma", #"F3" = 552],
					        [#"Passing all four GED® sections" = 259.7, #"F2" = "delaware", #"F3" = 635],
					        [#"Passing all four GED® sections" = 74.21, #"F2" = "boxes", #"F3" = 829],
					        [#"Passing all four GED® sections" = 594.29, #"F2" = "performing", #"F3" = 58],
					        [#"Passing all four GED® sections" = 338.92, #"F2" = "tom", #"F3" = 434],
					        [#"Passing all four GED® sections" = 137.93, #"F2" = "tx", #"F3" = 241],
					        [#"Passing all four GED® sections" = 360.57, #"F2" = "correction", #"F3" = 406],
					        [#"Passing all four GED® sections" = 570.69, #"F2" = "trailer", #"F3" = 28],
					        [#"Passing all four GED® sections" = 64.63, #"F2" = "committee", #"F3" = 545],
					        [#"Passing all four GED® sections" = 147.13, #"F2" = "hits", #"F3" = 560],
					        [#"Passing all four GED® sections" = 100.98, #"F2" = "verification", #"F3" = 36],
					        [#"Passing all four GED® sections" = 674.62, #"F2" = "geographic", #"F3" = 832],
					        [#"Passing all four GED® sections" = 553.44, #"F2" = "chicago", #"F3" = 66],
					        [#"Passing all four GED® sections" = 157.49, #"F2" = "workforce", #"F3" = 423],
					        [#"Passing all four GED® sections" = 85.94, #"F2" = "root", #"F3" = 401],
					        [#"Passing all four GED® sections" = 371.99, #"F2" = "fantastic", #"F3" = 964],
					        [#"Passing all four GED® sections" = 881.19, #"F2" = "districts", #"F3" = 103],
					        [#"Passing all four GED® sections" = 523.95, #"F2" = "exclusive", #"F3" = 908],
					        [#"Passing all four GED® sections" = 553.78, #"F2" = "cricket", #"F3" = 195],
					        [#"Passing all four GED® sections" = 127.05, #"F2" = "louisiana", #"F3" = 523],
					        [#"Passing all four GED® sections" = 559.4, #"F2" = "beast", #"F3" = 861],
					        [#"Passing all four GED® sections" = 651.33, #"F2" = "moved", #"F3" = 450],
					        [#"Passing all four GED® sections" = 967.37, #"F2" = "causes", #"F3" = 508],
					        [#"Passing all four GED® sections" = 442.51, #"F2" = "production", #"F3" = 10],
					        [#"Passing all four GED® sections" = 922.16, #"F2" = "lift", #"F3" = 461],
					        [#"Passing all four GED® sections" = 381.66, #"F2" = "sort", #"F3" = 205],
					        [#"Passing all four GED® sections" = 550.81, #"F2" = "park", #"F3" = 290],
					        [#"Passing all four GED® sections" = 63.42, #"F2" = "climate", #"F3" = 436],
					        [#"Passing all four GED® sections" = 185.97, #"F2" = "vietnam", #"F3" = 549],
					        [#"Passing all four GED® sections" = 758.91, #"F2" = "south", #"F3" = 929],
					        [#"Passing all four GED® sections" = 901.3, #"F2" = "carol", #"F3" = 531],
					        [#"Passing all four GED® sections" = 145.09, #"F2" = "third", #"F3" = 818],
					        [#"Passing all four GED® sections" = 404.38, #"F2" = "politics", #"F3" = 219],
					        [#"Passing all four GED® sections" = 433.43, #"F2" = "identifying", #"F3" = 569],
					        [#"Passing all four GED® sections" = 270.68, #"F2" = "fr", #"F3" = 424],
					        [#"Passing all four GED® sections" = 824.59, #"F2" = "symbols", #"F3" = 69],
					        [#"Passing all four GED® sections" = 623.15, #"F2" = "draw", #"F3" = 952],
					        [#"Passing all four GED® sections" = 446.55, #"F2" = "foreign", #"F3" = 75],
					        [#"Passing all four GED® sections" = 809.5, #"F2" = "map", #"F3" = 804],
					        [#"Passing all four GED® sections" = 519.1, #"F2" = "restaurants", #"F3" = 733],
					        [#"Passing all four GED® sections" = 219.3, #"F2" = "blackjack", #"F3" = 415],
					        [#"Passing all four GED® sections" = 702.45, #"F2" = "eat", #"F3" = 613],
					        [#"Passing all four GED® sections" = 307.3, #"F2" = "missouri", #"F3" = 105],
					        [#"Passing all four GED® sections" = 496.73, #"F2" = "submissions", #"F3" = 363],
					        [#"Passing all four GED® sections" = 328.71, #"F2" = "immediately", #"F3" = 446],
					        [#"Passing all four GED® sections" = 367.38, #"F2" = "jul", #"F3" = 311],
					        [#"Passing all four GED® sections" = 987.54, #"F2" = "programmes", #"F3" = 682],
					        [#"Passing all four GED® sections" = 713.02, #"F2" = "bandwidth", #"F3" = 598],
					        [#"Passing all four GED® sections" = 112.54, #"F2" = "app", #"F3" = 270],
					        [#"Passing all four GED® sections" = 822.51, #"F2" = "theatre", #"F3" = 335],
					        [#"Passing all four GED® sections" = 148.0, #"F2" = "models", #"F3" = 238],
					        [#"Passing all four GED® sections" = 871.87, #"F2" = "extract", #"F3" = 641],
					        [#"Passing all four GED® sections" = 375.51, #"F2" = "grace", #"F3" = 454],
					        [#"Passing all four GED® sections" = 163.64, #"F2" = "idaho", #"F3" = 463],
					        [#"Passing all four GED® sections" = 728.26, #"F2" = "responsibility", #"F3" = 954],
					        [#"Passing all four GED® sections" = 537.14, #"F2" = "presentation", #"F3" = 966],
					        [#"Passing all four GED® sections" = 806.85, #"F2" = "investing", #"F3" = 89],
					        [#"Passing all four GED® sections" = 650.77, #"F2" = "core", #"F3" = 341],
					        [#"Passing all four GED® sections" = 959.02, #"F2" = "interaction", #"F3" = 849],
					        [#"Passing all four GED® sections" = 15.29, #"F2" = "rc", #"F3" = 143],
					        [#"Passing all four GED® sections" = 525.83, #"F2" = "act", #"F3" = 901],
					        [#"Passing all four GED® sections" = 674.53, #"F2" = "nylon", #"F3" = 582],
					        [#"Passing all four GED® sections" = 430.39, #"F2" = "academy", #"F3" = 604],
					        [#"Passing all four GED® sections" = 7.39, #"F2" = "devil", #"F3" = 355],
					        [#"Passing all four GED® sections" = 247.13, #"F2" = "voice", #"F3" = 264],
					        [#"Passing all four GED® sections" = 704.06, #"F2" = "cooking", #"F3" = 508],
					        [#"Passing all four GED® sections" = 205.87, #"F2" = "either", #"F3" = 626],
					        [#"Passing all four GED® sections" = 506.59, #"F2" = "despite", #"F3" = 207],
					        [#"Passing all four GED® sections" = 957.19, #"F2" = "structural", #"F3" = 62],
					        [#"Passing all four GED® sections" = 400.87, #"F2" = "games", #"F3" = 204],
					        [#"Passing all four GED® sections" = 874.59, #"F2" = "standards", #"F3" = 921],
					        [#"Passing all four GED® sections" = 96.41, #"F2" = "reed", #"F3" = 925],
					        [#"Passing all four GED® sections" = 799.64, #"F2" = "rehabilitation", #"F3" = 400],
					        [#"Passing all four GED® sections" = 164.76, #"F2" = "message", #"F3" = 157],
					        [#"Passing all four GED® sections" = 608.0, #"F2" = "phase", #"F3" = 582],
					        [#"Passing all four GED® sections" = 176.11, #"F2" = "resulted", #"F3" = 107],
					        [#"Passing all four GED® sections" = 416.99, #"F2" = "cv", #"F3" = 480],
					        [#"Passing all four GED® sections" = 821.8, #"F2" = "cc", #"F3" = 965],
					        [#"Passing all four GED® sections" = 178.87, #"F2" = "bird", #"F3" = 927],
					        [#"Passing all four GED® sections" = 790.64, #"F2" = "outlet", #"F3" = 493],
					        [#"Passing all four GED® sections" = 824.25, #"F2" = "ethnic", #"F3" = 858],
					        [#"Passing all four GED® sections" = 634.94, #"F2" = "kent", #"F3" = 138],
					        [#"Passing all four GED® sections" = 869.01, #"F2" = "hd", #"F3" = 71],
					        [#"Passing all four GED® sections" = 531.43, #"F2" = "attachments", #"F3" = 316],
					        [#"Passing all four GED® sections" = 245.88, #"F2" = "selecting", #"F3" = 76],
					        [#"Passing all four GED® sections" = 852.93, #"F2" = "exam", #"F3" = 60],
					        [#"Passing all four GED® sections" = 149.54, #"F2" = "harbor", #"F3" = 790],
					        [#"Passing all four GED® sections" = 615.48, #"F2" = "rights", #"F3" = 697],
					        [#"Passing all four GED® sections" = 334.2, #"F2" = "phones", #"F3" = 686],
					        [#"Passing all four GED® sections" = 70.35, #"F2" = "california", #"F3" = 524],
					        [#"Passing all four GED® sections" = 764.16, #"F2" = "profits", #"F3" = 761],
					        [#"Passing all four GED® sections" = 889.55, #"F2" = "ta", #"F3" = 592],
					        [#"Passing all four GED® sections" = 567.57, #"F2" = "exposure", #"F3" = 450],
					        [#"Passing all four GED® sections" = 944.53, #"F2" = "customs", #"F3" = 937],
					        [#"Passing all four GED® sections" = 246.39, #"F2" = "conclusion", #"F3" = 753],
					        [#"Passing all four GED® sections" = 799.07, #"F2" = "respective", #"F3" = 757],
					        [#"Passing all four GED® sections" = 923.33, #"F2" = "damage", #"F3" = 665],
					        [#"Passing all four GED® sections" = 906.77, #"F2" = "expensive", #"F3" = 173],
					        [#"Passing all four GED® sections" = 132.54, #"F2" = "kent", #"F3" = 726],
					        [#"Passing all four GED® sections" = 375.07, #"F2" = "apr", #"F3" = 605],
					        [#"Passing all four GED® sections" = 715.88, #"F2" = "remained", #"F3" = 217],
					        [#"Passing all four GED® sections" = 672.71, #"F2" = "trans", #"F3" = 395],
					        [#"Passing all four GED® sections" = 698.87, #"F2" = "fabric", #"F3" = 202],
					        [#"Passing all four GED® sections" = 20.01, #"F2" = "rescue", #"F3" = 239],
					        [#"Passing all four GED® sections" = 630.26, #"F2" = "extension", #"F3" = 907],
					        [#"Passing all four GED® sections" = 499.89, #"F2" = "recordings", #"F3" = 712],
					        [#"Passing all four GED® sections" = 143.03, #"F2" = "numerous", #"F3" = 310],
					        [#"Passing all four GED® sections" = 280.43, #"F2" = "parallel", #"F3" = 107],
					        [#"Passing all four GED® sections" = 406.74, #"F2" = "property", #"F3" = 271],
					        [#"Passing all four GED® sections" = 999.26, #"F2" = "resolved", #"F3" = 475],
					        [#"Passing all four GED® sections" = 827.5, #"F2" = "sources", #"F3" = 275],
					        [#"Passing all four GED® sections" = 585.69, #"F2" = "yr", #"F3" = 358],
					        [#"Passing all four GED® sections" = 494.98, #"F2" = "man", #"F3" = 808],
					        [#"Passing all four GED® sections" = 832.1, #"F2" = "further", #"F3" = 356],
					        [#"Passing all four GED® sections" = 102.24, #"F2" = "customized", #"F3" = 484],
					        [#"Passing all four GED® sections" = 732.94, #"F2" = "processed", #"F3" = 995],
					        [#"Passing all four GED® sections" = 65.23, #"F2" = "leader", #"F3" = 6],
					        [#"Passing all four GED® sections" = 218.4, #"F2" = "exists", #"F3" = 273],
					        [#"Passing all four GED® sections" = 76.52, #"F2" = "duty", #"F3" = 335],
					        [#"Passing all four GED® sections" = 944.68, #"F2" = "send", #"F3" = 870],
					        [#"Passing all four GED® sections" = 146.4, #"F2" = "pharmacy", #"F3" = 714],
					        [#"Passing all four GED® sections" = 189.31, #"F2" = "milk", #"F3" = 486],
					        [#"Passing all four GED® sections" = 92.09, #"F2" = "wow", #"F3" = 203],
					        [#"Passing all four GED® sections" = 700.99, #"F2" = "pdt", #"F3" = 25],
					        [#"Passing all four GED® sections" = 973.17, #"F2" = "essential", #"F3" = 108],
					        [#"Passing all four GED® sections" = 713.81, #"F2" = "pda", #"F3" = 857],
					        [#"Passing all four GED® sections" = 397.52, #"F2" = "majority", #"F3" = 378],
					        [#"Passing all four GED® sections" = 328.51, #"F2" = "cellular", #"F3" = 231],
					        [#"Passing all four GED® sections" = 620.72, #"F2" = "also", #"F3" = 729],
					        [#"Passing all four GED® sections" = 518.39, #"F2" = "bonds", #"F3" = 65],
					        [#"Passing all four GED® sections" = 624.6, #"F2" = "option", #"F3" = 295],
					        [#"Passing all four GED® sections" = 655.82, #"F2" = "announcement", #"F3" = 11],
					        [#"Passing all four GED® sections" = 296.45, #"F2" = "sue", #"F3" = 684],
					        [#"Passing all four GED® sections" = 83.3, #"F2" = "africa", #"F3" = 162],
					        [#"Passing all four GED® sections" = 411.8, #"F2" = "lat", #"F3" = 920],
					        [#"Passing all four GED® sections" = 43.45, #"F2" = "characters", #"F3" = 917],
					        [#"Passing all four GED® sections" = 908.71, #"F2" = "doll", #"F3" = 69],
					        [#"Passing all four GED® sections" = 807.95, #"F2" = "correct", #"F3" = 120],
					        [#"Passing all four GED® sections" = 87.51, #"F2" = "move", #"F3" = 751],
					        [#"Passing all four GED® sections" = 108.71, #"F2" = "associated", #"F3" = 682],
					        [#"Passing all four GED® sections" = 865.53, #"F2" = "museum", #"F3" = 642],
					        [#"Passing all four GED® sections" = 135.09, #"F2" = "rings", #"F3" = 202],
					        [#"Passing all four GED® sections" = 818.64, #"F2" = "shoulder", #"F3" = 28],
					        [#"Passing all four GED® sections" = 934.27, #"F2" = "constructed", #"F3" = 973],
					        [#"Passing all four GED® sections" = 93.79, #"F2" = "cameras", #"F3" = 847],
					        [#"Passing all four GED® sections" = 268.46, #"F2" = "lines", #"F3" = 844],
					        [#"Passing all four GED® sections" = 197.56, #"F2" = "ho", #"F3" = 508],
					        [#"Passing all four GED® sections" = 953.64, #"F2" = "wheels", #"F3" = 488],
					        [#"Passing all four GED® sections" = 781.22, #"F2" = "lose", #"F3" = 241],
					        [#"Passing all four GED® sections" = 582.97, #"F2" = "shore", #"F3" = 95],
					        [#"Passing all four GED® sections" = 924.16, #"F2" = "verify", #"F3" = 22],
					        [#"Passing all four GED® sections" = 549.05, #"F2" = "entries", #"F3" = 911],
					        [#"Passing all four GED® sections" = 911.21, #"F2" = "mobile", #"F3" = 600],
					        [#"Passing all four GED® sections" = 14.26, #"F2" = "feeds", #"F3" = 289],
					        [#"Passing all four GED® sections" = 402.49, #"F2" = "maine", #"F3" = 162],
					        [#"Passing all four GED® sections" = 294.61, #"F2" = "amy", #"F3" = 667],
					        [#"Passing all four GED® sections" = 253.79, #"F2" = "jul", #"F3" = 425],
					        [#"Passing all four GED® sections" = 877.07, #"F2" = "lanka", #"F3" = 874],
					        [#"Passing all four GED® sections" = 992.69, #"F2" = "mississippi", #"F3" = 498],
					        [#"Passing all four GED® sections" = 70.64, #"F2" = "cafe", #"F3" = 458],
					        [#"Passing all four GED® sections" = 470.71, #"F2" = "sand", #"F3" = 368],
					        [#"Passing all four GED® sections" = 496.26, #"F2" = "sea", #"F3" = 529],
					        [#"Passing all four GED® sections" = 882.51, #"F2" = "mutual", #"F3" = 219],
					        [#"Passing all four GED® sections" = 456.88, #"F2" = "cisco", #"F3" = 588],
					        [#"Passing all four GED® sections" = 565.17, #"F2" = "joe", #"F3" = 236],
					        [#"Passing all four GED® sections" = 584.97, #"F2" = "examples", #"F3" = 645],
					        [#"Passing all four GED® sections" = 364.29, #"F2" = "records", #"F3" = 926],
					        [#"Passing all four GED® sections" = 165.0, #"F2" = "physician", #"F3" = 598],
					        [#"Passing all four GED® sections" = 929.29, #"F2" = "arena", #"F3" = 317],
					        [#"Passing all four GED® sections" = 572.51, #"F2" = "named", #"F3" = 992],
					        [#"Passing all four GED® sections" = 894.08, #"F2" = "dogs", #"F3" = 704],
					        [#"Passing all four GED® sections" = 300.54, #"F2" = "highlights", #"F3" = 738],
					        [#"Passing all four GED® sections" = 799.12, #"F2" = "clubs", #"F3" = 868],
					        [#"Passing all four GED® sections" = 711.87, #"F2" = "legal", #"F3" = 200],
					        [#"Passing all four GED® sections" = 218.28, #"F2" = "photo", #"F3" = 200],
					        [#"Passing all four GED® sections" = 743.64, #"F2" = "academy", #"F3" = 598],
					        [#"Passing all four GED® sections" = 236.98, #"F2" = "entry", #"F3" = 371],
					        [#"Passing all four GED® sections" = 316.14, #"F2" = "measurement", #"F3" = 470],
					        [#"Passing all four GED® sections" = 138.3, #"F2" = "dot", #"F3" = 848],
					        [#"Passing all four GED® sections" = 348.28, #"F2" = "references", #"F3" = 422],
					        [#"Passing all four GED® sections" = 23.42, #"F2" = "noted", #"F3" = 141],
					        [#"Passing all four GED® sections" = 858.86, #"F2" = "wild", #"F3" = 177],
					        [#"Passing all four GED® sections" = 784.78, #"F2" = "bringing", #"F3" = 635],
					        [#"Passing all four GED® sections" = 808.91, #"F2" = "produce", #"F3" = 226],
					        [#"Passing all four GED® sections" = 941.48, #"F2" = "for", #"F3" = 729],
					        [#"Passing all four GED® sections" = 237.32, #"F2" = "home", #"F3" = 430],
					        [#"Passing all four GED® sections" = 768.44, #"F2" = "apart", #"F3" = 740],
					        [#"Passing all four GED® sections" = 818.53, #"F2" = "soft", #"F3" = 31],
					        [#"Passing all four GED® sections" = 42.89, #"F2" = "moral", #"F3" = 916],
					        [#"Passing all four GED® sections" = 774.99, #"F2" = "spears", #"F3" = 31],
					        [#"Passing all four GED® sections" = 440.62, #"F2" = "mining", #"F3" = 725],
					        [#"Passing all four GED® sections" = 58.63, #"F2" = "declaration", #"F3" = 363],
					        [#"Passing all four GED® sections" = 423.78, #"F2" = "appearing", #"F3" = 583],
					        [#"Passing all four GED® sections" = 982.31, #"F2" = "portion", #"F3" = 747],
					        [#"Passing all four GED® sections" = 31.25, #"F2" = "panama", #"F3" = 355],
					        [#"Passing all four GED® sections" = 83.18, #"F2" = "highlights", #"F3" = 223],
					        [#"Passing all four GED® sections" = 623.11, #"F2" = "nodes", #"F3" = 293],
					        [#"Passing all four GED® sections" = 568.44, #"F2" = "pine", #"F3" = 438],
					        [#"Passing all four GED® sections" = 122.26, #"F2" = "elected", #"F3" = 276],
					        [#"Passing all four GED® sections" = 758.61, #"F2" = "grow", #"F3" = 271],
					        [#"Passing all four GED® sections" = 118.37, #"F2" = "mechanisms", #"F3" = 326],
					        [#"Passing all four GED® sections" = 991.23, #"F2" = "looked", #"F3" = 905],
					        [#"Passing all four GED® sections" = 304.75, #"F2" = "applicants", #"F3" = 663],
					        [#"Passing all four GED® sections" = 353.85, #"F2" = "championship", #"F3" = 150],
					        [#"Passing all four GED® sections" = 54.58, #"F2" = "initially", #"F3" = 590],
					        [#"Passing all four GED® sections" = 825.77, #"F2" = "disney", #"F3" = 285],
					        [#"Passing all four GED® sections" = 889.61, #"F2" = "execution", #"F3" = 374],
					        [#"Passing all four GED® sections" = 547.93, #"F2" = "car", #"F3" = 63],
					        [#"Passing all four GED® sections" = 365.71, #"F2" = "technologies", #"F3" = 717],
					        [#"Passing all four GED® sections" = 528.81, #"F2" = "diagnosis", #"F3" = 839],
					        [#"Passing all four GED® sections" = 398.36, #"F2" = "compilation", #"F3" = 107],
					        [#"Passing all four GED® sections" = 357.07, #"F2" = "totals", #"F3" = 791],
					        [#"Passing all four GED® sections" = 887.0, #"F2" = "reserves", #"F3" = 756],
					        [#"Passing all four GED® sections" = 77.46, #"F2" = "narrow", #"F3" = 142],
					        [#"Passing all four GED® sections" = 834.13, #"F2" = "phil", #"F3" = 963],
					        [#"Passing all four GED® sections" = 708.95, #"F2" = "rankings", #"F3" = 349],
					        [#"Passing all four GED® sections" = 777.29, #"F2" = "departments", #"F3" = 317],
					        [#"Passing all four GED® sections" = 421.45, #"F2" = "memorial", #"F3" = 631],
					        [#"Passing all four GED® sections" = 900.21, #"F2" = "molecular", #"F3" = 517],
					        [#"Passing all four GED® sections" = 489.18, #"F2" = "barry", #"F3" = 884],
					        [#"Passing all four GED® sections" = 586.86, #"F2" = "gain", #"F3" = 177],
					        [#"Passing all four GED® sections" = 369.54, #"F2" = "working", #"F3" = 274],
					        [#"Passing all four GED® sections" = 140.27, #"F2" = "certificate", #"F3" = 181],
					        [#"Passing all four GED® sections" = 433.39, #"F2" = "shower", #"F3" = 832],
					        [#"Passing all four GED® sections" = 504.79, #"F2" = "ever", #"F3" = 406],
					        [#"Passing all four GED® sections" = 136.89, #"F2" = "hilton", #"F3" = 359],
					        [#"Passing all four GED® sections" = 246.33, #"F2" = "antonio", #"F3" = 944]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Passing all four GED® sections", type number},
					        {"F2", type text},
					        {"F3", Int64.Type}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table