table 'Population by age group and sex'
	lineageTag: 06587515-dbc8-4f0d-849c-554bd92d88ab

	column Age
		dataType: string
		lineageTag: 527b65b3-b59d-4fcd-90e8-d93dc7506b1a
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Sex
		dataType: string
		lineageTag: 0ee1efb5-a3ad-4a3a-9b59-4bd7be424ef4
		summarizeBy: none
		sourceColumn: Sex

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 7022c8ca-188f-45a3-9961-123f55db6e6e
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Population
		dataType: int64
		formatString: 0
		lineageTag: 4f054612-8b3c-4215-898b-d7e82d7a9364
		summarizeBy: sum
		sourceColumn: Population

		annotation SummarizationSetBy = Automatic

	partition 'Population by age group and sex' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Age" = 40, #"Sex" = "opera", #"Year" = 2017, #"Population" = 220],
					        [#"Age" = 74, #"Sex" = "sick", #"Year" = 2024, #"Population" = 532],
					        [#"Age" = 32, #"Sex" = "layer", #"Year" = 2002, #"Population" = 879],
					        [#"Age" = 78, #"Sex" = "waves", #"Year" = 2012, #"Population" = 428],
					        [#"Age" = 62, #"Sex" = "scientific", #"Year" = 2005, #"Population" = 752],
					        [#"Age" = 60, #"Sex" = "missouri", #"Year" = 2018, #"Population" = 472],
					        [#"Age" = 31, #"Sex" = "excerpt", #"Year" = 2011, #"Population" = 735],
					        [#"Age" = 44, #"Sex" = "alan", #"Year" = 2012, #"Population" = 799],
					        [#"Age" = 25, #"Sex" = "indicates", #"Year" = 2003, #"Population" = 120],
					        [#"Age" = 46, #"Sex" = "contributed", #"Year" = 2013, #"Population" = 186],
					        [#"Age" = 64, #"Sex" = "magic", #"Year" = 2005, #"Population" = 837],
					        [#"Age" = 34, #"Sex" = "kits", #"Year" = 2005, #"Population" = 354],
					        [#"Age" = 73, #"Sex" = "vancouver", #"Year" = 2017, #"Population" = 766],
					        [#"Age" = 22, #"Sex" = "corps", #"Year" = 2001, #"Population" = 11],
					        [#"Age" = 43, #"Sex" = "organizations", #"Year" = 2004, #"Population" = 698],
					        [#"Age" = 64, #"Sex" = "minneapolis", #"Year" = 2020, #"Population" = 712],
					        [#"Age" = 58, #"Sex" = "issues", #"Year" = 2014, #"Population" = 813],
					        [#"Age" = 29, #"Sex" = "extended", #"Year" = 2018, #"Population" = 796],
					        [#"Age" = 30, #"Sex" = "brothers", #"Year" = 2019, #"Population" = 672],
					        [#"Age" = 67, #"Sex" = "substance", #"Year" = 2011, #"Population" = 932],
					        [#"Age" = 50, #"Sex" = "procurement", #"Year" = 2015, #"Population" = 264],
					        [#"Age" = 73, #"Sex" = "felt", #"Year" = 2024, #"Population" = 192],
					        [#"Age" = 36, #"Sex" = "coins", #"Year" = 2016, #"Population" = 775],
					        [#"Age" = 60, #"Sex" = "targeted", #"Year" = 2004, #"Population" = 638],
					        [#"Age" = 80, #"Sex" = "usb", #"Year" = 2009, #"Population" = 548],
					        [#"Age" = 74, #"Sex" = "continuing", #"Year" = 2003, #"Population" = 945],
					        [#"Age" = 26, #"Sex" = "sw", #"Year" = 2001, #"Population" = 727],
					        [#"Age" = 30, #"Sex" = "ads", #"Year" = 2003, #"Population" = 16],
					        [#"Age" = 45, #"Sex" = "ge", #"Year" = 2008, #"Population" = 257],
					        [#"Age" = 51, #"Sex" = "moore", #"Year" = 2007, #"Population" = 370],
					        [#"Age" = 39, #"Sex" = "auto", #"Year" = 2001, #"Population" = 980],
					        [#"Age" = 20, #"Sex" = "william", #"Year" = 2011, #"Population" = 482],
					        [#"Age" = 27, #"Sex" = "kept", #"Year" = 2019, #"Population" = 659],
					        [#"Age" = 30, #"Sex" = "statements", #"Year" = 2019, #"Population" = 35],
					        [#"Age" = 69, #"Sex" = "manner", #"Year" = 2017, #"Population" = 941],
					        [#"Age" = 46, #"Sex" = "nigeria", #"Year" = 2002, #"Population" = 499],
					        [#"Age" = 66, #"Sex" = "wrestling", #"Year" = 2016, #"Population" = 475],
					        [#"Age" = 62, #"Sex" = "sales", #"Year" = 2003, #"Population" = 607],
					        [#"Age" = 57, #"Sex" = "columns", #"Year" = 2005, #"Population" = 2],
					        [#"Age" = 30, #"Sex" = "oem", #"Year" = 2023, #"Population" = 464],
					        [#"Age" = 22, #"Sex" = "calendar", #"Year" = 2010, #"Population" = 340],
					        [#"Age" = 20, #"Sex" = "census", #"Year" = 2014, #"Population" = 951],
					        [#"Age" = 38, #"Sex" = "motorcycle", #"Year" = 2016, #"Population" = 299],
					        [#"Age" = 30, #"Sex" = "top", #"Year" = 2002, #"Population" = 518],
					        [#"Age" = 69, #"Sex" = "clearance", #"Year" = 2023, #"Population" = 310],
					        [#"Age" = 22, #"Sex" = "adjustable", #"Year" = 2011, #"Population" = 823],
					        [#"Age" = 78, #"Sex" = "academy", #"Year" = 2013, #"Population" = 322],
					        [#"Age" = 24, #"Sex" = "sat", #"Year" = 2018, #"Population" = 662],
					        [#"Age" = 34, #"Sex" = "continues", #"Year" = 2005, #"Population" = 538],
					        [#"Age" = 40, #"Sex" = "article", #"Year" = 2019, #"Population" = 97],
					        [#"Age" = 21, #"Sex" = "sciences", #"Year" = 2013, #"Population" = 239],
					        [#"Age" = 31, #"Sex" = "speaking", #"Year" = 2020, #"Population" = 704],
					        [#"Age" = 18, #"Sex" = "enough", #"Year" = 2018, #"Population" = 789],
					        [#"Age" = 48, #"Sex" = "advance", #"Year" = 2012, #"Population" = 795],
					        [#"Age" = 52, #"Sex" = "italy", #"Year" = 2012, #"Population" = 265],
					        [#"Age" = 47, #"Sex" = "accepted", #"Year" = 2018, #"Population" = 859],
					        [#"Age" = 30, #"Sex" = "payday", #"Year" = 2007, #"Population" = 601],
					        [#"Age" = 68, #"Sex" = "becomes", #"Year" = 2019, #"Population" = 908],
					        [#"Age" = 60, #"Sex" = "cincinnati", #"Year" = 2010, #"Population" = 573],
					        [#"Age" = 31, #"Sex" = "ice", #"Year" = 2003, #"Population" = 539],
					        [#"Age" = 38, #"Sex" = "construction", #"Year" = 2011, #"Population" = 711],
					        [#"Age" = 79, #"Sex" = "coal", #"Year" = 2009, #"Population" = 807],
					        [#"Age" = 75, #"Sex" = "racing", #"Year" = 2011, #"Population" = 727],
					        [#"Age" = 40, #"Sex" = "determining", #"Year" = 2004, #"Population" = 860],
					        [#"Age" = 67, #"Sex" = "algorithm", #"Year" = 2014, #"Population" = 713],
					        [#"Age" = 76, #"Sex" = "terror", #"Year" = 2009, #"Population" = 589],
					        [#"Age" = 45, #"Sex" = "login", #"Year" = 2004, #"Population" = 325],
					        [#"Age" = 24, #"Sex" = "fan", #"Year" = 2023, #"Population" = 743],
					        [#"Age" = 51, #"Sex" = "thick", #"Year" = 2018, #"Population" = 901],
					        [#"Age" = 21, #"Sex" = "race", #"Year" = 2008, #"Population" = 938],
					        [#"Age" = 66, #"Sex" = "avenue", #"Year" = 2005, #"Population" = 969],
					        [#"Age" = 79, #"Sex" = "checked", #"Year" = 2016, #"Population" = 9],
					        [#"Age" = 68, #"Sex" = "college", #"Year" = 2009, #"Population" = 600],
					        [#"Age" = 54, #"Sex" = "investigation", #"Year" = 2018, #"Population" = 639],
					        [#"Age" = 40, #"Sex" = "texts", #"Year" = 2017, #"Population" = 928],
					        [#"Age" = 20, #"Sex" = "vendor", #"Year" = 2012, #"Population" = 505],
					        [#"Age" = 33, #"Sex" = "refine", #"Year" = 2004, #"Population" = 6],
					        [#"Age" = 66, #"Sex" = "collections", #"Year" = 2013, #"Population" = 673],
					        [#"Age" = 60, #"Sex" = "frequent", #"Year" = 2015, #"Population" = 916],
					        [#"Age" = 47, #"Sex" = "involve", #"Year" = 2013, #"Population" = 482],
					        [#"Age" = 48, #"Sex" = "dc", #"Year" = 2007, #"Population" = 309],
					        [#"Age" = 27, #"Sex" = "connecticut", #"Year" = 2017, #"Population" = 4],
					        [#"Age" = 37, #"Sex" = "machine", #"Year" = 2010, #"Population" = 400],
					        [#"Age" = 26, #"Sex" = "survival", #"Year" = 2015, #"Population" = 245],
					        [#"Age" = 56, #"Sex" = "sometimes", #"Year" = 2001, #"Population" = 117],
					        [#"Age" = 61, #"Sex" = "successful", #"Year" = 2002, #"Population" = 803],
					        [#"Age" = 35, #"Sex" = "bag", #"Year" = 2019, #"Population" = 909],
					        [#"Age" = 60, #"Sex" = "pants", #"Year" = 2006, #"Population" = 761],
					        [#"Age" = 52, #"Sex" = "honor", #"Year" = 2021, #"Population" = 199],
					        [#"Age" = 56, #"Sex" = "harris", #"Year" = 2011, #"Population" = 297],
					        [#"Age" = 27, #"Sex" = "rapid", #"Year" = 2020, #"Population" = 232],
					        [#"Age" = 79, #"Sex" = "maker", #"Year" = 2019, #"Population" = 14],
					        [#"Age" = 44, #"Sex" = "lycos", #"Year" = 2014, #"Population" = 183],
					        [#"Age" = 34, #"Sex" = "attorneys", #"Year" = 2011, #"Population" = 225],
					        [#"Age" = 78, #"Sex" = "hood", #"Year" = 2019, #"Population" = 803],
					        [#"Age" = 46, #"Sex" = "transactions", #"Year" = 2005, #"Population" = 431],
					        [#"Age" = 66, #"Sex" = "guess", #"Year" = 2023, #"Population" = 360],
					        [#"Age" = 21, #"Sex" = "remember", #"Year" = 2012, #"Population" = 448],
					        [#"Age" = 28, #"Sex" = "speech", #"Year" = 2016, #"Population" = 303],
					        [#"Age" = 41, #"Sex" = "houses", #"Year" = 2012, #"Population" = 831],
					        [#"Age" = 76, #"Sex" = "nd", #"Year" = 2002, #"Population" = 123],
					        [#"Age" = 50, #"Sex" = "bargain", #"Year" = 2019, #"Population" = 991],
					        [#"Age" = 72, #"Sex" = "indicate", #"Year" = 2010, #"Population" = 594],
					        [#"Age" = 80, #"Sex" = "informed", #"Year" = 2019, #"Population" = 337],
					        [#"Age" = 40, #"Sex" = "stopped", #"Year" = 2002, #"Population" = 959],
					        [#"Age" = 46, #"Sex" = "platforms", #"Year" = 2024, #"Population" = 823],
					        [#"Age" = 53, #"Sex" = "carry", #"Year" = 2004, #"Population" = 317],
					        [#"Age" = 18, #"Sex" = "fails", #"Year" = 2008, #"Population" = 398],
					        [#"Age" = 25, #"Sex" = "rubber", #"Year" = 2006, #"Population" = 162],
					        [#"Age" = 68, #"Sex" = "see", #"Year" = 2005, #"Population" = 189],
					        [#"Age" = 55, #"Sex" = "juvenile", #"Year" = 2005, #"Population" = 817],
					        [#"Age" = 53, #"Sex" = "submission", #"Year" = 2003, #"Population" = 256],
					        [#"Age" = 56, #"Sex" = "blogs", #"Year" = 2023, #"Population" = 334],
					        [#"Age" = 74, #"Sex" = "console", #"Year" = 2020, #"Population" = 315],
					        [#"Age" = 46, #"Sex" = "buyer", #"Year" = 2007, #"Population" = 393],
					        [#"Age" = 69, #"Sex" = "medicine", #"Year" = 2022, #"Population" = 732],
					        [#"Age" = 68, #"Sex" = "greater", #"Year" = 2021, #"Population" = 178],
					        [#"Age" = 78, #"Sex" = "hell", #"Year" = 2000, #"Population" = 328],
					        [#"Age" = 32, #"Sex" = "comics", #"Year" = 2010, #"Population" = 401],
					        [#"Age" = 57, #"Sex" = "solar", #"Year" = 2002, #"Population" = 141],
					        [#"Age" = 75, #"Sex" = "figures", #"Year" = 2015, #"Population" = 572],
					        [#"Age" = 38, #"Sex" = "horses", #"Year" = 2011, #"Population" = 161],
					        [#"Age" = 40, #"Sex" = "folks", #"Year" = 2010, #"Population" = 546],
					        [#"Age" = 40, #"Sex" = "shooting", #"Year" = 2024, #"Population" = 293],
					        [#"Age" = 57, #"Sex" = "format", #"Year" = 2015, #"Population" = 195],
					        [#"Age" = 58, #"Sex" = "ia", #"Year" = 2001, #"Population" = 31],
					        [#"Age" = 18, #"Sex" = "identification", #"Year" = 2021, #"Population" = 374],
					        [#"Age" = 32, #"Sex" = "entire", #"Year" = 2002, #"Population" = 449],
					        [#"Age" = 77, #"Sex" = "direct", #"Year" = 2010, #"Population" = 146],
					        [#"Age" = 29, #"Sex" = "cry", #"Year" = 2016, #"Population" = 88],
					        [#"Age" = 71, #"Sex" = "den", #"Year" = 2017, #"Population" = 527],
					        [#"Age" = 72, #"Sex" = "ratio", #"Year" = 2014, #"Population" = 727],
					        [#"Age" = 64, #"Sex" = "separate", #"Year" = 2005, #"Population" = 915],
					        [#"Age" = 68, #"Sex" = "favorites", #"Year" = 2013, #"Population" = 427],
					        [#"Age" = 25, #"Sex" = "entire", #"Year" = 2013, #"Population" = 990],
					        [#"Age" = 46, #"Sex" = "packard", #"Year" = 2008, #"Population" = 629],
					        [#"Age" = 66, #"Sex" = "extended", #"Year" = 2013, #"Population" = 66],
					        [#"Age" = 45, #"Sex" = "blues", #"Year" = 2008, #"Population" = 84],
					        [#"Age" = 37, #"Sex" = "priorities", #"Year" = 2009, #"Population" = 611],
					        [#"Age" = 66, #"Sex" = "ot", #"Year" = 2019, #"Population" = 653],
					        [#"Age" = 44, #"Sex" = "control", #"Year" = 2020, #"Population" = 912],
					        [#"Age" = 79, #"Sex" = "javascript", #"Year" = 2004, #"Population" = 836],
					        [#"Age" = 47, #"Sex" = "nokia", #"Year" = 2022, #"Population" = 919],
					        [#"Age" = 68, #"Sex" = "gps", #"Year" = 2017, #"Population" = 178],
					        [#"Age" = 40, #"Sex" = "organic", #"Year" = 2014, #"Population" = 790],
					        [#"Age" = 25, #"Sex" = "chairs", #"Year" = 2006, #"Population" = 861],
					        [#"Age" = 71, #"Sex" = "polls", #"Year" = 2002, #"Population" = 443],
					        [#"Age" = 57, #"Sex" = "completion", #"Year" = 2010, #"Population" = 966],
					        [#"Age" = 38, #"Sex" = "ebony", #"Year" = 2004, #"Population" = 691],
					        [#"Age" = 60, #"Sex" = "whose", #"Year" = 2002, #"Population" = 80],
					        [#"Age" = 34, #"Sex" = "requirement", #"Year" = 2000, #"Population" = 830],
					        [#"Age" = 22, #"Sex" = "capital", #"Year" = 2022, #"Population" = 468],
					        [#"Age" = 70, #"Sex" = "friends", #"Year" = 2021, #"Population" = 254],
					        [#"Age" = 75, #"Sex" = "formed", #"Year" = 2001, #"Population" = 528],
					        [#"Age" = 62, #"Sex" = "pocket", #"Year" = 2002, #"Population" = 499],
					        [#"Age" = 40, #"Sex" = "man", #"Year" = 2005, #"Population" = 482],
					        [#"Age" = 65, #"Sex" = "complaints", #"Year" = 2011, #"Population" = 667],
					        [#"Age" = 47, #"Sex" = "stainless", #"Year" = 2000, #"Population" = 51],
					        [#"Age" = 40, #"Sex" = "level", #"Year" = 2005, #"Population" = 985],
					        [#"Age" = 67, #"Sex" = "javascript", #"Year" = 2000, #"Population" = 362],
					        [#"Age" = 61, #"Sex" = "receive", #"Year" = 2019, #"Population" = 47],
					        [#"Age" = 59, #"Sex" = "discounts", #"Year" = 2018, #"Population" = 435],
					        [#"Age" = 76, #"Sex" = "assess", #"Year" = 2011, #"Population" = 792],
					        [#"Age" = 50, #"Sex" = "celebrity", #"Year" = 2003, #"Population" = 211],
					        [#"Age" = 67, #"Sex" = "dvd", #"Year" = 2004, #"Population" = 389],
					        [#"Age" = 27, #"Sex" = "away", #"Year" = 2010, #"Population" = 914],
					        [#"Age" = 77, #"Sex" = "walker", #"Year" = 2014, #"Population" = 150],
					        [#"Age" = 70, #"Sex" = "influence", #"Year" = 2012, #"Population" = 692],
					        [#"Age" = 58, #"Sex" = "parents", #"Year" = 2020, #"Population" = 223],
					        [#"Age" = 44, #"Sex" = "memorial", #"Year" = 2008, #"Population" = 121],
					        [#"Age" = 61, #"Sex" = "currency", #"Year" = 2011, #"Population" = 222],
					        [#"Age" = 35, #"Sex" = "subsection", #"Year" = 2018, #"Population" = 548],
					        [#"Age" = 57, #"Sex" = "kansas", #"Year" = 2009, #"Population" = 804],
					        [#"Age" = 76, #"Sex" = "applications", #"Year" = 2022, #"Population" = 394],
					        [#"Age" = 23, #"Sex" = "england", #"Year" = 2011, #"Population" = 747],
					        [#"Age" = 54, #"Sex" = "forces", #"Year" = 2006, #"Population" = 339],
					        [#"Age" = 32, #"Sex" = "draft", #"Year" = 2004, #"Population" = 61],
					        [#"Age" = 32, #"Sex" = "sweden", #"Year" = 2013, #"Population" = 388],
					        [#"Age" = 63, #"Sex" = "detection", #"Year" = 2017, #"Population" = 644],
					        [#"Age" = 56, #"Sex" = "there", #"Year" = 2014, #"Population" = 283],
					        [#"Age" = 31, #"Sex" = "murder", #"Year" = 2022, #"Population" = 328],
					        [#"Age" = 27, #"Sex" = "them", #"Year" = 2000, #"Population" = 670],
					        [#"Age" = 45, #"Sex" = "effect", #"Year" = 2011, #"Population" = 542],
					        [#"Age" = 57, #"Sex" = "involvement", #"Year" = 2023, #"Population" = 704],
					        [#"Age" = 77, #"Sex" = "pp", #"Year" = 2018, #"Population" = 537],
					        [#"Age" = 55, #"Sex" = "zimbabwe", #"Year" = 2017, #"Population" = 427],
					        [#"Age" = 34, #"Sex" = "crisis", #"Year" = 2011, #"Population" = 625],
					        [#"Age" = 23, #"Sex" = "performance", #"Year" = 2004, #"Population" = 207],
					        [#"Age" = 48, #"Sex" = "player", #"Year" = 2015, #"Population" = 927],
					        [#"Age" = 77, #"Sex" = "virgin", #"Year" = 2023, #"Population" = 743],
					        [#"Age" = 18, #"Sex" = "sale", #"Year" = 2022, #"Population" = 781],
					        [#"Age" = 22, #"Sex" = "curriculum", #"Year" = 2015, #"Population" = 532],
					        [#"Age" = 66, #"Sex" = "seconds", #"Year" = 2014, #"Population" = 623],
					        [#"Age" = 26, #"Sex" = "brothers", #"Year" = 2024, #"Population" = 648],
					        [#"Age" = 57, #"Sex" = "adjustment", #"Year" = 2004, #"Population" = 907],
					        [#"Age" = 54, #"Sex" = "sad", #"Year" = 2009, #"Population" = 451],
					        [#"Age" = 75, #"Sex" = "break", #"Year" = 2015, #"Population" = 99],
					        [#"Age" = 31, #"Sex" = "hills", #"Year" = 2023, #"Population" = 661],
					        [#"Age" = 72, #"Sex" = "fundamental", #"Year" = 2009, #"Population" = 49],
					        [#"Age" = 80, #"Sex" = "exchange", #"Year" = 2011, #"Population" = 818],
					        [#"Age" = 76, #"Sex" = "called", #"Year" = 2017, #"Population" = 718],
					        [#"Age" = 57, #"Sex" = "properly", #"Year" = 2000, #"Population" = 560],
					        [#"Age" = 32, #"Sex" = "require", #"Year" = 2006, #"Population" = 774],
					        [#"Age" = 69, #"Sex" = "offset", #"Year" = 2022, #"Population" = 820],
					        [#"Age" = 65, #"Sex" = "founder", #"Year" = 2022, #"Population" = 376],
					        [#"Age" = 78, #"Sex" = "swedish", #"Year" = 2006, #"Population" = 56],
					        [#"Age" = 71, #"Sex" = "discounts", #"Year" = 2003, #"Population" = 756],
					        [#"Age" = 53, #"Sex" = "ecommerce", #"Year" = 2016, #"Population" = 811],
					        [#"Age" = 33, #"Sex" = "stadium", #"Year" = 2005, #"Population" = 367],
					        [#"Age" = 31, #"Sex" = "towns", #"Year" = 2009, #"Population" = 667],
					        [#"Age" = 55, #"Sex" = "demands", #"Year" = 2012, #"Population" = 509],
					        [#"Age" = 39, #"Sex" = "productivity", #"Year" = 2023, #"Population" = 334],
					        [#"Age" = 43, #"Sex" = "wearing", #"Year" = 2012, #"Population" = 299],
					        [#"Age" = 55, #"Sex" = "stainless", #"Year" = 2000, #"Population" = 790],
					        [#"Age" = 64, #"Sex" = "signature", #"Year" = 2002, #"Population" = 893],
					        [#"Age" = 75, #"Sex" = "printers", #"Year" = 2011, #"Population" = 868],
					        [#"Age" = 57, #"Sex" = "signals", #"Year" = 2006, #"Population" = 44],
					        [#"Age" = 26, #"Sex" = "regional", #"Year" = 2002, #"Population" = 795],
					        [#"Age" = 19, #"Sex" = "leave", #"Year" = 2007, #"Population" = 846],
					        [#"Age" = 21, #"Sex" = "theater", #"Year" = 2009, #"Population" = 836],
					        [#"Age" = 39, #"Sex" = "alpha", #"Year" = 2008, #"Population" = 910],
					        [#"Age" = 76, #"Sex" = "resort", #"Year" = 2012, #"Population" = 106],
					        [#"Age" = 69, #"Sex" = "churches", #"Year" = 2015, #"Population" = 551],
					        [#"Age" = 25, #"Sex" = "mailing", #"Year" = 2003, #"Population" = 855],
					        [#"Age" = 44, #"Sex" = "american", #"Year" = 2022, #"Population" = 202],
					        [#"Age" = 32, #"Sex" = "louisiana", #"Year" = 2010, #"Population" = 831],
					        [#"Age" = 47, #"Sex" = "slow", #"Year" = 2005, #"Population" = 79],
					        [#"Age" = 58, #"Sex" = "training", #"Year" = 2009, #"Population" = 865],
					        [#"Age" = 36, #"Sex" = "requirement", #"Year" = 2000, #"Population" = 503],
					        [#"Age" = 66, #"Sex" = "warner", #"Year" = 2017, #"Population" = 843],
					        [#"Age" = 64, #"Sex" = "noble", #"Year" = 2010, #"Population" = 844],
					        [#"Age" = 74, #"Sex" = "pearl", #"Year" = 2002, #"Population" = 216],
					        [#"Age" = 36, #"Sex" = "kitchen", #"Year" = 2020, #"Population" = 209],
					        [#"Age" = 80, #"Sex" = "recovery", #"Year" = 2012, #"Population" = 794],
					        [#"Age" = 45, #"Sex" = "paint", #"Year" = 2004, #"Population" = 137],
					        [#"Age" = 48, #"Sex" = "nec", #"Year" = 2010, #"Population" = 228],
					        [#"Age" = 77, #"Sex" = "heading", #"Year" = 2000, #"Population" = 655],
					        [#"Age" = 43, #"Sex" = "promotion", #"Year" = 2024, #"Population" = 858],
					        [#"Age" = 36, #"Sex" = "providing", #"Year" = 2001, #"Population" = 607],
					        [#"Age" = 34, #"Sex" = "lake", #"Year" = 2011, #"Population" = 638],
					        [#"Age" = 71, #"Sex" = "representative", #"Year" = 2012, #"Population" = 490],
					        [#"Age" = 50, #"Sex" = "rank", #"Year" = 2004, #"Population" = 257],
					        [#"Age" = 38, #"Sex" = "ec", #"Year" = 2009, #"Population" = 593],
					        [#"Age" = 75, #"Sex" = "establish", #"Year" = 2003, #"Population" = 572],
					        [#"Age" = 31, #"Sex" = "und", #"Year" = 2015, #"Population" = 596],
					        [#"Age" = 33, #"Sex" = "enables", #"Year" = 2016, #"Population" = 573],
					        [#"Age" = 66, #"Sex" = "photos", #"Year" = 2019, #"Population" = 918],
					        [#"Age" = 18, #"Sex" = "utilities", #"Year" = 2010, #"Population" = 438],
					        [#"Age" = 27, #"Sex" = "os", #"Year" = 2020, #"Population" = 974],
					        [#"Age" = 78, #"Sex" = "mayor", #"Year" = 2002, #"Population" = 499],
					        [#"Age" = 55, #"Sex" = "latinas", #"Year" = 2005, #"Population" = 253],
					        [#"Age" = 37, #"Sex" = "elementary", #"Year" = 2012, #"Population" = 229],
					        [#"Age" = 50, #"Sex" = "elsewhere", #"Year" = 2019, #"Population" = 366],
					        [#"Age" = 60, #"Sex" = "thu", #"Year" = 2017, #"Population" = 791],
					        [#"Age" = 76, #"Sex" = "tells", #"Year" = 2020, #"Population" = 190],
					        [#"Age" = 51, #"Sex" = "initially", #"Year" = 2024, #"Population" = 764],
					        [#"Age" = 52, #"Sex" = "ford", #"Year" = 2018, #"Population" = 420],
					        [#"Age" = 68, #"Sex" = "gt", #"Year" = 2012, #"Population" = 93],
					        [#"Age" = 58, #"Sex" = "blank", #"Year" = 2023, #"Population" = 545],
					        [#"Age" = 37, #"Sex" = "route", #"Year" = 2008, #"Population" = 550],
					        [#"Age" = 34, #"Sex" = "portfolio", #"Year" = 2024, #"Population" = 75],
					        [#"Age" = 61, #"Sex" = "steve", #"Year" = 2022, #"Population" = 304],
					        [#"Age" = 80, #"Sex" = "how", #"Year" = 2007, #"Population" = 551],
					        [#"Age" = 80, #"Sex" = "assembly", #"Year" = 2003, #"Population" = 37],
					        [#"Age" = 73, #"Sex" = "visual", #"Year" = 2012, #"Population" = 416],
					        [#"Age" = 39, #"Sex" = "assignment", #"Year" = 2020, #"Population" = 790],
					        [#"Age" = 25, #"Sex" = "jump", #"Year" = 2009, #"Population" = 395],
					        [#"Age" = 29, #"Sex" = "within", #"Year" = 2005, #"Population" = 325],
					        [#"Age" = 75, #"Sex" = "execution", #"Year" = 2001, #"Population" = 874],
					        [#"Age" = 32, #"Sex" = "latter", #"Year" = 2023, #"Population" = 447],
					        [#"Age" = 43, #"Sex" = "acts", #"Year" = 2022, #"Population" = 146],
					        [#"Age" = 36, #"Sex" = "those", #"Year" = 2007, #"Population" = 401],
					        [#"Age" = 52, #"Sex" = "cst", #"Year" = 2014, #"Population" = 120],
					        [#"Age" = 70, #"Sex" = "screen", #"Year" = 2000, #"Population" = 461],
					        [#"Age" = 38, #"Sex" = "robert", #"Year" = 2004, #"Population" = 330],
					        [#"Age" = 71, #"Sex" = "styles", #"Year" = 2002, #"Population" = 478],
					        [#"Age" = 56, #"Sex" = "seniors", #"Year" = 2017, #"Population" = 700],
					        [#"Age" = 21, #"Sex" = "broken", #"Year" = 2008, #"Population" = 268],
					        [#"Age" = 76, #"Sex" = "poor", #"Year" = 2014, #"Population" = 647],
					        [#"Age" = 70, #"Sex" = "consistent", #"Year" = 2024, #"Population" = 162],
					        [#"Age" = 61, #"Sex" = "ba", #"Year" = 2024, #"Population" = 196],
					        [#"Age" = 63, #"Sex" = "popular", #"Year" = 2009, #"Population" = 410],
					        [#"Age" = 52, #"Sex" = "trend", #"Year" = 2000, #"Population" = 31],
					        [#"Age" = 62, #"Sex" = "statistics", #"Year" = 2018, #"Population" = 811],
					        [#"Age" = 60, #"Sex" = "failure", #"Year" = 2017, #"Population" = 165],
					        [#"Age" = 28, #"Sex" = "northwest", #"Year" = 2007, #"Population" = 620],
					        [#"Age" = 18, #"Sex" = "creek", #"Year" = 2019, #"Population" = 364],
					        [#"Age" = 58, #"Sex" = "grove", #"Year" = 2001, #"Population" = 863],
					        [#"Age" = 21, #"Sex" = "columbus", #"Year" = 2007, #"Population" = 762],
					        [#"Age" = 20, #"Sex" = "edge", #"Year" = 2022, #"Population" = 114],
					        [#"Age" = 25, #"Sex" = "lo", #"Year" = 2011, #"Population" = 266],
					        [#"Age" = 32, #"Sex" = "evidence", #"Year" = 2019, #"Population" = 512],
					        [#"Age" = 29, #"Sex" = "dawn", #"Year" = 2004, #"Population" = 340],
					        [#"Age" = 27, #"Sex" = "valley", #"Year" = 2019, #"Population" = 746],
					        [#"Age" = 69, #"Sex" = "newspaper", #"Year" = 2017, #"Population" = 506],
					        [#"Age" = 57, #"Sex" = "databases", #"Year" = 2009, #"Population" = 640],
					        [#"Age" = 38, #"Sex" = "lanka", #"Year" = 2020, #"Population" = 424],
					        [#"Age" = 70, #"Sex" = "betting", #"Year" = 2016, #"Population" = 28],
					        [#"Age" = 47, #"Sex" = "antique", #"Year" = 2017, #"Population" = 446],
					        [#"Age" = 20, #"Sex" = "comparison", #"Year" = 2019, #"Population" = 165],
					        [#"Age" = 45, #"Sex" = "scottish", #"Year" = 2023, #"Population" = 308],
					        [#"Age" = 20, #"Sex" = "housing", #"Year" = 2023, #"Population" = 538],
					        [#"Age" = 75, #"Sex" = "positions", #"Year" = 2016, #"Population" = 976],
					        [#"Age" = 74, #"Sex" = "definitely", #"Year" = 2017, #"Population" = 408],
					        [#"Age" = 77, #"Sex" = "temple", #"Year" = 2011, #"Population" = 140],
					        [#"Age" = 32, #"Sex" = "anarchist", #"Year" = 2018, #"Population" = 900],
					        [#"Age" = 62, #"Sex" = "native", #"Year" = 2023, #"Population" = 698],
					        [#"Age" = 31, #"Sex" = "holidays", #"Year" = 2002, #"Population" = 510],
					        [#"Age" = 75, #"Sex" = "center", #"Year" = 2016, #"Population" = 307],
					        [#"Age" = 28, #"Sex" = "skill", #"Year" = 2010, #"Population" = 690],
					        [#"Age" = 61, #"Sex" = "connection", #"Year" = 2003, #"Population" = 986],
					        [#"Age" = 60, #"Sex" = "consumers", #"Year" = 2006, #"Population" = 432],
					        [#"Age" = 73, #"Sex" = "organized", #"Year" = 2010, #"Population" = 820],
					        [#"Age" = 46, #"Sex" = "showtimes", #"Year" = 2009, #"Population" = 479],
					        [#"Age" = 57, #"Sex" = "ne", #"Year" = 2004, #"Population" = 840],
					        [#"Age" = 40, #"Sex" = "shopper", #"Year" = 2010, #"Population" = 574],
					        [#"Age" = 19, #"Sex" = "destinations", #"Year" = 2013, #"Population" = 723],
					        [#"Age" = 41, #"Sex" = "farmer", #"Year" = 2001, #"Population" = 384],
					        [#"Age" = 23, #"Sex" = "kennedy", #"Year" = 2008, #"Population" = 411],
					        [#"Age" = 35, #"Sex" = "specify", #"Year" = 2011, #"Population" = 592],
					        [#"Age" = 52, #"Sex" = "score", #"Year" = 2007, #"Population" = 283],
					        [#"Age" = 28, #"Sex" = "fine", #"Year" = 2023, #"Population" = 642],
					        [#"Age" = 25, #"Sex" = "delaware", #"Year" = 2000, #"Population" = 556],
					        [#"Age" = 39, #"Sex" = "muslim", #"Year" = 2014, #"Population" = 172],
					        [#"Age" = 74, #"Sex" = "gaming", #"Year" = 2001, #"Population" = 390],
					        [#"Age" = 77, #"Sex" = "any", #"Year" = 2006, #"Population" = 562],
					        [#"Age" = 31, #"Sex" = "nh", #"Year" = 2011, #"Population" = 789],
					        [#"Age" = 55, #"Sex" = "reserve", #"Year" = 2020, #"Population" = 866],
					        [#"Age" = 55, #"Sex" = "pollution", #"Year" = 2024, #"Population" = 464],
					        [#"Age" = 49, #"Sex" = "site", #"Year" = 2004, #"Population" = 418],
					        [#"Age" = 77, #"Sex" = "yahoo", #"Year" = 2015, #"Population" = 327],
					        [#"Age" = 75, #"Sex" = "happen", #"Year" = 2011, #"Population" = 883],
					        [#"Age" = 67, #"Sex" = "tomorrow", #"Year" = 2016, #"Population" = 844],
					        [#"Age" = 69, #"Sex" = "zone", #"Year" = 2020, #"Population" = 158],
					        [#"Age" = 37, #"Sex" = "diseases", #"Year" = 2021, #"Population" = 982],
					        [#"Age" = 74, #"Sex" = "standing", #"Year" = 2011, #"Population" = 531],
					        [#"Age" = 63, #"Sex" = "accommodation", #"Year" = 2019, #"Population" = 947],
					        [#"Age" = 56, #"Sex" = "queen", #"Year" = 2007, #"Population" = 320],
					        [#"Age" = 73, #"Sex" = "neck", #"Year" = 2003, #"Population" = 611],
					        [#"Age" = 55, #"Sex" = "surf", #"Year" = 2016, #"Population" = 579],
					        [#"Age" = 25, #"Sex" = "happening", #"Year" = 2020, #"Population" = 524],
					        [#"Age" = 70, #"Sex" = "level", #"Year" = 2024, #"Population" = 394],
					        [#"Age" = 36, #"Sex" = "license", #"Year" = 2018, #"Population" = 304],
					        [#"Age" = 21, #"Sex" = "portland", #"Year" = 2016, #"Population" = 538],
					        [#"Age" = 47, #"Sex" = "advertisers", #"Year" = 2015, #"Population" = 719],
					        [#"Age" = 74, #"Sex" = "either", #"Year" = 2000, #"Population" = 592],
					        [#"Age" = 49, #"Sex" = "raised", #"Year" = 2024, #"Population" = 605],
					        [#"Age" = 39, #"Sex" = "pm", #"Year" = 2023, #"Population" = 426],
					        [#"Age" = 49, #"Sex" = "mar", #"Year" = 2016, #"Population" = 461],
					        [#"Age" = 53, #"Sex" = "podcast", #"Year" = 2010, #"Population" = 651],
					        [#"Age" = 29, #"Sex" = "improved", #"Year" = 2006, #"Population" = 705],
					        [#"Age" = 29, #"Sex" = "kick", #"Year" = 2016, #"Population" = 705],
					        [#"Age" = 29, #"Sex" = "fourth", #"Year" = 2003, #"Population" = 563],
					        [#"Age" = 52, #"Sex" = "recently", #"Year" = 2012, #"Population" = 819],
					        [#"Age" = 51, #"Sex" = "civil", #"Year" = 2017, #"Population" = 226],
					        [#"Age" = 35, #"Sex" = "column", #"Year" = 2003, #"Population" = 759],
					        [#"Age" = 23, #"Sex" = "collection", #"Year" = 2012, #"Population" = 22],
					        [#"Age" = 80, #"Sex" = "demands", #"Year" = 2010, #"Population" = 321],
					        [#"Age" = 24, #"Sex" = "forecast", #"Year" = 2002, #"Population" = 926],
					        [#"Age" = 70, #"Sex" = "prince", #"Year" = 2010, #"Population" = 123],
					        [#"Age" = 54, #"Sex" = "measurements", #"Year" = 2007, #"Population" = 306],
					        [#"Age" = 75, #"Sex" = "regard", #"Year" = 2009, #"Population" = 999],
					        [#"Age" = 47, #"Sex" = "scenes", #"Year" = 2010, #"Population" = 356],
					        [#"Age" = 42, #"Sex" = "odd", #"Year" = 2023, #"Population" = 34],
					        [#"Age" = 39, #"Sex" = "efficiency", #"Year" = 2013, #"Population" = 458],
					        [#"Age" = 66, #"Sex" = "dog", #"Year" = 2013, #"Population" = 418],
					        [#"Age" = 48, #"Sex" = "athens", #"Year" = 2023, #"Population" = 899],
					        [#"Age" = 65, #"Sex" = "runs", #"Year" = 2005, #"Population" = 118],
					        [#"Age" = 67, #"Sex" = "pc", #"Year" = 2024, #"Population" = 411],
					        [#"Age" = 66, #"Sex" = "resort", #"Year" = 2013, #"Population" = 983],
					        [#"Age" = 76, #"Sex" = "france", #"Year" = 2006, #"Population" = 62],
					        [#"Age" = 78, #"Sex" = "ones", #"Year" = 2012, #"Population" = 642],
					        [#"Age" = 67, #"Sex" = "global", #"Year" = 2010, #"Population" = 361],
					        [#"Age" = 33, #"Sex" = "private", #"Year" = 2014, #"Population" = 540],
					        [#"Age" = 60, #"Sex" = "options", #"Year" = 2001, #"Population" = 36],
					        [#"Age" = 21, #"Sex" = "artificial", #"Year" = 2020, #"Population" = 847],
					        [#"Age" = 25, #"Sex" = "patches", #"Year" = 2003, #"Population" = 42],
					        [#"Age" = 78, #"Sex" = "rainbow", #"Year" = 2024, #"Population" = 612],
					        [#"Age" = 27, #"Sex" = "rescue", #"Year" = 2014, #"Population" = 135],
					        [#"Age" = 29, #"Sex" = "industries", #"Year" = 2001, #"Population" = 907],
					        [#"Age" = 20, #"Sex" = "recent", #"Year" = 2019, #"Population" = 907],
					        [#"Age" = 43, #"Sex" = "kick", #"Year" = 2013, #"Population" = 135],
					        [#"Age" = 80, #"Sex" = "sounds", #"Year" = 2010, #"Population" = 442],
					        [#"Age" = 75, #"Sex" = "secure", #"Year" = 2019, #"Population" = 837],
					        [#"Age" = 46, #"Sex" = "antonio", #"Year" = 2018, #"Population" = 893],
					        [#"Age" = 20, #"Sex" = "pre", #"Year" = 2007, #"Population" = 695],
					        [#"Age" = 71, #"Sex" = "speak", #"Year" = 2016, #"Population" = 469],
					        [#"Age" = 19, #"Sex" = "miles", #"Year" = 2007, #"Population" = 973],
					        [#"Age" = 73, #"Sex" = "classification", #"Year" = 2014, #"Population" = 996],
					        [#"Age" = 31, #"Sex" = "cultures", #"Year" = 2002, #"Population" = 794],
					        [#"Age" = 75, #"Sex" = "jewelry", #"Year" = 2006, #"Population" = 612],
					        [#"Age" = 22, #"Sex" = "mathematical", #"Year" = 2018, #"Population" = 943],
					        [#"Age" = 38, #"Sex" = "rugby", #"Year" = 2012, #"Population" = 927],
					        [#"Age" = 69, #"Sex" = "engaged", #"Year" = 2016, #"Population" = 369],
					        [#"Age" = 57, #"Sex" = "rack", #"Year" = 2024, #"Population" = 167],
					        [#"Age" = 19, #"Sex" = "printers", #"Year" = 2001, #"Population" = 699],
					        [#"Age" = 30, #"Sex" = "smart", #"Year" = 2003, #"Population" = 318],
					        [#"Age" = 74, #"Sex" = "memorial", #"Year" = 2002, #"Population" = 125],
					        [#"Age" = 56, #"Sex" = "arena", #"Year" = 2013, #"Population" = 581],
					        [#"Age" = 33, #"Sex" = "mask", #"Year" = 2006, #"Population" = 789],
					        [#"Age" = 46, #"Sex" = "lead", #"Year" = 2020, #"Population" = 621],
					        [#"Age" = 40, #"Sex" = "expert", #"Year" = 2012, #"Population" = 978],
					        [#"Age" = 69, #"Sex" = "latina", #"Year" = 2009, #"Population" = 595],
					        [#"Age" = 71, #"Sex" = "designer", #"Year" = 2017, #"Population" = 787],
					        [#"Age" = 29, #"Sex" = "joining", #"Year" = 2023, #"Population" = 21],
					        [#"Age" = 32, #"Sex" = "saying", #"Year" = 2011, #"Population" = 996],
					        [#"Age" = 79, #"Sex" = "ban", #"Year" = 2006, #"Population" = 207],
					        [#"Age" = 51, #"Sex" = "craft", #"Year" = 2000, #"Population" = 524],
					        [#"Age" = 38, #"Sex" = "nv", #"Year" = 2010, #"Population" = 303],
					        [#"Age" = 28, #"Sex" = "lan", #"Year" = 2001, #"Population" = 656],
					        [#"Age" = 70, #"Sex" = "aircraft", #"Year" = 2002, #"Population" = 400],
					        [#"Age" = 19, #"Sex" = "relatively", #"Year" = 2015, #"Population" = 777],
					        [#"Age" = 57, #"Sex" = "bay", #"Year" = 2020, #"Population" = 513],
					        [#"Age" = 35, #"Sex" = "schemes", #"Year" = 2001, #"Population" = 746],
					        [#"Age" = 39, #"Sex" = "last", #"Year" = 2011, #"Population" = 602],
					        [#"Age" = 35, #"Sex" = "becomes", #"Year" = 2012, #"Population" = 639],
					        [#"Age" = 71, #"Sex" = "them", #"Year" = 2006, #"Population" = 404],
					        [#"Age" = 19, #"Sex" = "sounds", #"Year" = 2011, #"Population" = 807],
					        [#"Age" = 38, #"Sex" = "wine", #"Year" = 2015, #"Population" = 597],
					        [#"Age" = 77, #"Sex" = "broken", #"Year" = 2020, #"Population" = 514],
					        [#"Age" = 59, #"Sex" = "flag", #"Year" = 2016, #"Population" = 113],
					        [#"Age" = 38, #"Sex" = "bone", #"Year" = 2010, #"Population" = 912],
					        [#"Age" = 49, #"Sex" = "peer", #"Year" = 2019, #"Population" = 758],
					        [#"Age" = 70, #"Sex" = "participation", #"Year" = 2003, #"Population" = 122],
					        [#"Age" = 43, #"Sex" = "debate", #"Year" = 2024, #"Population" = 78],
					        [#"Age" = 36, #"Sex" = "binding", #"Year" = 2004, #"Population" = 881],
					        [#"Age" = 54, #"Sex" = "stability", #"Year" = 2013, #"Population" = 122],
					        [#"Age" = 45, #"Sex" = "say", #"Year" = 2013, #"Population" = 693],
					        [#"Age" = 76, #"Sex" = "none", #"Year" = 2004, #"Population" = 312],
					        [#"Age" = 46, #"Sex" = "however", #"Year" = 2005, #"Population" = 59],
					        [#"Age" = 68, #"Sex" = "providers", #"Year" = 2019, #"Population" = 290],
					        [#"Age" = 21, #"Sex" = "member", #"Year" = 2020, #"Population" = 131],
					        [#"Age" = 31, #"Sex" = "these", #"Year" = 2023, #"Population" = 105],
					        [#"Age" = 76, #"Sex" = "consent", #"Year" = 2015, #"Population" = 174],
					        [#"Age" = 40, #"Sex" = "boost", #"Year" = 2004, #"Population" = 540],
					        [#"Age" = 67, #"Sex" = "customers", #"Year" = 2018, #"Population" = 676],
					        [#"Age" = 40, #"Sex" = "final", #"Year" = 2019, #"Population" = 865],
					        [#"Age" = 69, #"Sex" = "classical", #"Year" = 2013, #"Population" = 329],
					        [#"Age" = 21, #"Sex" = "midnight", #"Year" = 2002, #"Population" = 273],
					        [#"Age" = 70, #"Sex" = "royal", #"Year" = 2019, #"Population" = 724],
					        [#"Age" = 46, #"Sex" = "province", #"Year" = 2002, #"Population" = 678],
					        [#"Age" = 55, #"Sex" = "stereo", #"Year" = 2013, #"Population" = 288],
					        [#"Age" = 21, #"Sex" = "donate", #"Year" = 2011, #"Population" = 674],
					        [#"Age" = 51, #"Sex" = "mexican", #"Year" = 2004, #"Population" = 14],
					        [#"Age" = 52, #"Sex" = "discipline", #"Year" = 2022, #"Population" = 215],
					        [#"Age" = 73, #"Sex" = "weekend", #"Year" = 2010, #"Population" = 448],
					        [#"Age" = 39, #"Sex" = "consent", #"Year" = 2023, #"Population" = 100],
					        [#"Age" = 73, #"Sex" = "ip", #"Year" = 2013, #"Population" = 918],
					        [#"Age" = 79, #"Sex" = "related", #"Year" = 2021, #"Population" = 117],
					        [#"Age" = 37, #"Sex" = "reports", #"Year" = 2006, #"Population" = 639],
					        [#"Age" = 40, #"Sex" = "coupon", #"Year" = 2010, #"Population" = 539],
					        [#"Age" = 43, #"Sex" = "importance", #"Year" = 2013, #"Population" = 314],
					        [#"Age" = 58, #"Sex" = "personally", #"Year" = 2021, #"Population" = 353],
					        [#"Age" = 63, #"Sex" = "approval", #"Year" = 2004, #"Population" = 87],
					        [#"Age" = 67, #"Sex" = "nh", #"Year" = 2004, #"Population" = 360],
					        [#"Age" = 52, #"Sex" = "authors", #"Year" = 2022, #"Population" = 47],
					        [#"Age" = 43, #"Sex" = "install", #"Year" = 2001, #"Population" = 600],
					        [#"Age" = 58, #"Sex" = "mention", #"Year" = 2007, #"Population" = 198],
					        [#"Age" = 19, #"Sex" = "competition", #"Year" = 2022, #"Population" = 833],
					        [#"Age" = 35, #"Sex" = "aids", #"Year" = 2002, #"Population" = 968],
					        [#"Age" = 74, #"Sex" = "inter", #"Year" = 2014, #"Population" = 223],
					        [#"Age" = 54, #"Sex" = "basically", #"Year" = 2002, #"Population" = 427],
					        [#"Age" = 56, #"Sex" = "fitness", #"Year" = 2023, #"Population" = 641],
					        [#"Age" = 27, #"Sex" = "refine", #"Year" = 2022, #"Population" = 20],
					        [#"Age" = 68, #"Sex" = "requests", #"Year" = 2021, #"Population" = 60],
					        [#"Age" = 21, #"Sex" = "crew", #"Year" = 2011, #"Population" = 779],
					        [#"Age" = 72, #"Sex" = "nigeria", #"Year" = 2017, #"Population" = 217],
					        [#"Age" = 33, #"Sex" = "operations", #"Year" = 2022, #"Population" = 683],
					        [#"Age" = 62, #"Sex" = "alan", #"Year" = 2022, #"Population" = 43],
					        [#"Age" = 26, #"Sex" = "berkeley", #"Year" = 2023, #"Population" = 331],
					        [#"Age" = 79, #"Sex" = "opening", #"Year" = 2001, #"Population" = 316],
					        [#"Age" = 78, #"Sex" = "main", #"Year" = 2008, #"Population" = 226],
					        [#"Age" = 64, #"Sex" = "summit", #"Year" = 2013, #"Population" = 943],
					        [#"Age" = 56, #"Sex" = "turn", #"Year" = 2000, #"Population" = 265],
					        [#"Age" = 22, #"Sex" = "depth", #"Year" = 2000, #"Population" = 777],
					        [#"Age" = 23, #"Sex" = "grant", #"Year" = 2020, #"Population" = 222],
					        [#"Age" = 66, #"Sex" = "tm", #"Year" = 2017, #"Population" = 435],
					        [#"Age" = 74, #"Sex" = "heaven", #"Year" = 2004, #"Population" = 401],
					        [#"Age" = 58, #"Sex" = "payable", #"Year" = 2022, #"Population" = 760],
					        [#"Age" = 70, #"Sex" = "stored", #"Year" = 2021, #"Population" = 554],
					        [#"Age" = 25, #"Sex" = "street", #"Year" = 2003, #"Population" = 359],
					        [#"Age" = 79, #"Sex" = "lock", #"Year" = 2009, #"Population" = 1000],
					        [#"Age" = 53, #"Sex" = "wash", #"Year" = 2005, #"Population" = 765],
					        [#"Age" = 39, #"Sex" = "paragraph", #"Year" = 2019, #"Population" = 917],
					        [#"Age" = 25, #"Sex" = "advice", #"Year" = 2005, #"Population" = 69],
					        [#"Age" = 70, #"Sex" = "adventures", #"Year" = 2016, #"Population" = 99],
					        [#"Age" = 75, #"Sex" = "terror", #"Year" = 2021, #"Population" = 1000],
					        [#"Age" = 20, #"Sex" = "mary", #"Year" = 2006, #"Population" = 625],
					        [#"Age" = 19, #"Sex" = "spoke", #"Year" = 2006, #"Population" = 259],
					        [#"Age" = 78, #"Sex" = "spam", #"Year" = 2003, #"Population" = 587],
					        [#"Age" = 23, #"Sex" = "noble", #"Year" = 2009, #"Population" = 38],
					        [#"Age" = 80, #"Sex" = "czech", #"Year" = 2009, #"Population" = 167],
					        [#"Age" = 20, #"Sex" = "generator", #"Year" = 2024, #"Population" = 156],
					        [#"Age" = 64, #"Sex" = "led", #"Year" = 2003, #"Population" = 129],
					        [#"Age" = 41, #"Sex" = "cause", #"Year" = 2014, #"Population" = 151],
					        [#"Age" = 28, #"Sex" = "miller", #"Year" = 2024, #"Population" = 306],
					        [#"Age" = 44, #"Sex" = "subsection", #"Year" = 2001, #"Population" = 638],
					        [#"Age" = 43, #"Sex" = "ensure", #"Year" = 2006, #"Population" = 351],
					        [#"Age" = 52, #"Sex" = "camcorders", #"Year" = 2023, #"Population" = 788],
					        [#"Age" = 74, #"Sex" = "integrated", #"Year" = 2011, #"Population" = 430]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Age", type text},
					        {"Sex", type text},
					        {"Year", Int64.Type},
					        {"Population", Int64.Type}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table