table 'Population by ethnic group'
	lineageTag: 467c245f-8d4c-494a-aa17-1707711c7a46

	column 'Ethnic geoup'
		dataType: string
		lineageTag: 61fd16ce-6e92-486b-b3c4-5f61ac22d667
		summarizeBy: none
		sourceColumn: 'Ethnic geoup'

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 66411d7c-b907-4d5d-a95a-3454319a4064
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Population
		dataType: int64
		formatString: 0
		lineageTag: 21498555-06d0-4a18-b9ac-a7f35d116297
		summarizeBy: sum
		sourceColumn: Population

		annotation SummarizationSetBy = Automatic

	partition 'Population by ethnic group' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Ethnic geoup" = "-75.477382, 135.796861", #"Year" = 2012, #"Population" = 561],
					        [#"Ethnic geoup" = "-8.664579, -0.132509", #"Year" = 2018, #"Population" = 370],
					        [#"Ethnic geoup" = "-16.2179, 157.269773", #"Year" = 2012, #"Population" = 792],
					        [#"Ethnic geoup" = "-35.11332, 20.131804", #"Year" = 2016, #"Population" = 646],
					        [#"Ethnic geoup" = "25.132915, 34.871419", #"Year" = 2020, #"Population" = 705],
					        [#"Ethnic geoup" = "-73.252406, -1.020764", #"Year" = 2024, #"Population" = 676],
					        [#"Ethnic geoup" = "-4.320405, 15.021835", #"Year" = 2004, #"Population" = 472],
					        [#"Ethnic geoup" = "27.325107, 121.826629", #"Year" = 2010, #"Population" = 301],
					        [#"Ethnic geoup" = "-53.311437, 172.735219", #"Year" = 2008, #"Population" = 609],
					        [#"Ethnic geoup" = "51.77531, -35.812422", #"Year" = 2011, #"Population" = 548],
					        [#"Ethnic geoup" = "-82.914921, -90.089429", #"Year" = 2017, #"Population" = 54],
					        [#"Ethnic geoup" = "-42.577336, -103.09532", #"Year" = 2002, #"Population" = 659],
					        [#"Ethnic geoup" = "-2.157344, -81.38897", #"Year" = 2006, #"Population" = 715],
					        [#"Ethnic geoup" = "14.34226, 63.276307", #"Year" = 2009, #"Population" = 616],
					        [#"Ethnic geoup" = "13.990566, 53.480858", #"Year" = 2002, #"Population" = 374],
					        [#"Ethnic geoup" = "43.999973, 68.405676", #"Year" = 2008, #"Population" = 413],
					        [#"Ethnic geoup" = "87.148333, -50.445073", #"Year" = 2024, #"Population" = 768],
					        [#"Ethnic geoup" = "18.225211, 159.693952", #"Year" = 2003, #"Population" = 339],
					        [#"Ethnic geoup" = "-12.222815, -48.533838", #"Year" = 2021, #"Population" = 464],
					        [#"Ethnic geoup" = "-76.314352, 27.597525", #"Year" = 2003, #"Population" = 182],
					        [#"Ethnic geoup" = "80.988038, -154.58061", #"Year" = 2002, #"Population" = 439],
					        [#"Ethnic geoup" = "3.416356, 4.16003", #"Year" = 2009, #"Population" = 719],
					        [#"Ethnic geoup" = "-22.838507, -56.687536", #"Year" = 2011, #"Population" = 136],
					        [#"Ethnic geoup" = "-67.47884, 115.023619", #"Year" = 2010, #"Population" = 535],
					        [#"Ethnic geoup" = "26.769545, -175.160618", #"Year" = 2005, #"Population" = 397],
					        [#"Ethnic geoup" = "-54.356005, 50.031322", #"Year" = 2013, #"Population" = 75],
					        [#"Ethnic geoup" = "-27.080987, 173.940716", #"Year" = 2024, #"Population" = 603],
					        [#"Ethnic geoup" = "-26.282511, -54.597006", #"Year" = 2020, #"Population" = 793],
					        [#"Ethnic geoup" = "-20.786244, 149.026799", #"Year" = 2016, #"Population" = 284],
					        [#"Ethnic geoup" = "2.900264, 52.042809", #"Year" = 2007, #"Population" = 373],
					        [#"Ethnic geoup" = "-82.766304, -156.425693", #"Year" = 2000, #"Population" = 103],
					        [#"Ethnic geoup" = "-22.912329, -114.452867", #"Year" = 2011, #"Population" = 322],
					        [#"Ethnic geoup" = "65.109196, 22.763579", #"Year" = 2017, #"Population" = 596],
					        [#"Ethnic geoup" = "-19.401407, 111.593882", #"Year" = 2022, #"Population" = 515],
					        [#"Ethnic geoup" = "74.488415, -124.724258", #"Year" = 2019, #"Population" = 70],
					        [#"Ethnic geoup" = "-45.575466, 160.127486", #"Year" = 2021, #"Population" = 310],
					        [#"Ethnic geoup" = "-76.754059, -41.164565", #"Year" = 2008, #"Population" = 878],
					        [#"Ethnic geoup" = "-40.412099, 8.218146", #"Year" = 2003, #"Population" = 891],
					        [#"Ethnic geoup" = "-12.758495, 127.048896", #"Year" = 2004, #"Population" = 699],
					        [#"Ethnic geoup" = "82.050768, 99.222102", #"Year" = 2003, #"Population" = 545],
					        [#"Ethnic geoup" = "48.358034, 125.862126", #"Year" = 2011, #"Population" = 671],
					        [#"Ethnic geoup" = "35.367564, -88.221156", #"Year" = 2007, #"Population" = 755],
					        [#"Ethnic geoup" = "65.786289, -13.32977", #"Year" = 2010, #"Population" = 915],
					        [#"Ethnic geoup" = "-5.958683, -9.248545", #"Year" = 2022, #"Population" = 928],
					        [#"Ethnic geoup" = "30.355307, 32.241743", #"Year" = 2024, #"Population" = 162],
					        [#"Ethnic geoup" = "74.365628, -153.780036", #"Year" = 2012, #"Population" = 933],
					        [#"Ethnic geoup" = "-57.041254, -27.258555", #"Year" = 2008, #"Population" = 200],
					        [#"Ethnic geoup" = "-23.899702, 49.024543", #"Year" = 2004, #"Population" = 90],
					        [#"Ethnic geoup" = "89.387433, -7.719426", #"Year" = 2015, #"Population" = 731],
					        [#"Ethnic geoup" = "-80.376368, 151.496999", #"Year" = 2019, #"Population" = 775],
					        [#"Ethnic geoup" = "60.365437, 2.170371", #"Year" = 2002, #"Population" = 444],
					        [#"Ethnic geoup" = "33.075679, -40.687394", #"Year" = 2007, #"Population" = 714],
					        [#"Ethnic geoup" = "-39.054344, 126.14423", #"Year" = 2006, #"Population" = 557],
					        [#"Ethnic geoup" = "-29.154902, -178.44099", #"Year" = 2020, #"Population" = 38],
					        [#"Ethnic geoup" = "73.3955, 125.589232", #"Year" = 2009, #"Population" = 490],
					        [#"Ethnic geoup" = "56.961803, -134.862315", #"Year" = 2003, #"Population" = 965],
					        [#"Ethnic geoup" = "-35.25719, -77.587077", #"Year" = 2008, #"Population" = 11],
					        [#"Ethnic geoup" = "-43.547922, -72.577978", #"Year" = 2005, #"Population" = 638],
					        [#"Ethnic geoup" = "-59.110104, -25.675876", #"Year" = 2020, #"Population" = 858],
					        [#"Ethnic geoup" = "72.129166, 47.413416", #"Year" = 2022, #"Population" = 388],
					        [#"Ethnic geoup" = "-34.558988, -84.012278", #"Year" = 2020, #"Population" = 702],
					        [#"Ethnic geoup" = "-57.694238, -86.691272", #"Year" = 2024, #"Population" = 469],
					        [#"Ethnic geoup" = "-66.963419, -111.290783", #"Year" = 2010, #"Population" = 706],
					        [#"Ethnic geoup" = "-59.865307, -33.013555", #"Year" = 2023, #"Population" = 59],
					        [#"Ethnic geoup" = "28.330806, -100.674096", #"Year" = 2021, #"Population" = 24],
					        [#"Ethnic geoup" = "38.607296, 3.99464", #"Year" = 2008, #"Population" = 284],
					        [#"Ethnic geoup" = "51.805302, -109.822187", #"Year" = 2020, #"Population" = 185],
					        [#"Ethnic geoup" = "-13.374385, -7.049536", #"Year" = 2003, #"Population" = 561],
					        [#"Ethnic geoup" = "66.339256, -96.893417", #"Year" = 2002, #"Population" = 122],
					        [#"Ethnic geoup" = "-8.193245, 146.870389", #"Year" = 2014, #"Population" = 967],
					        [#"Ethnic geoup" = "-87.823977, 55.559518", #"Year" = 2014, #"Population" = 820],
					        [#"Ethnic geoup" = "-50.46251, 172.25055", #"Year" = 2022, #"Population" = 84],
					        [#"Ethnic geoup" = "89.569416, -136.412667", #"Year" = 2023, #"Population" = 184],
					        [#"Ethnic geoup" = "46.256857, -2.344122", #"Year" = 2019, #"Population" = 583],
					        [#"Ethnic geoup" = "-64.611538, -44.704238", #"Year" = 2021, #"Population" = 855],
					        [#"Ethnic geoup" = "3.149441, 30.192868", #"Year" = 2002, #"Population" = 469],
					        [#"Ethnic geoup" = "-80.121182, 17.460142", #"Year" = 2019, #"Population" = 107],
					        [#"Ethnic geoup" = "-1.278602, -169.473762", #"Year" = 2005, #"Population" = 732],
					        [#"Ethnic geoup" = "-12.931498, -174.573393", #"Year" = 2023, #"Population" = 893],
					        [#"Ethnic geoup" = "-53.618094, -160.027939", #"Year" = 2003, #"Population" = 813],
					        [#"Ethnic geoup" = "88.105976, -6.337363", #"Year" = 2020, #"Population" = 994],
					        [#"Ethnic geoup" = "-74.65126, 63.408749", #"Year" = 2004, #"Population" = 681],
					        [#"Ethnic geoup" = "53.386712, -100.746756", #"Year" = 2005, #"Population" = 1],
					        [#"Ethnic geoup" = "-17.452429, 119.044241", #"Year" = 2013, #"Population" = 204],
					        [#"Ethnic geoup" = "86.246278, -119.963693", #"Year" = 2003, #"Population" = 460],
					        [#"Ethnic geoup" = "13.688464, 162.998786", #"Year" = 2008, #"Population" = 642],
					        [#"Ethnic geoup" = "26.432633, 166.920684", #"Year" = 2024, #"Population" = 585],
					        [#"Ethnic geoup" = "75.156369, -128.420185", #"Year" = 2016, #"Population" = 995],
					        [#"Ethnic geoup" = "39.010007, 78.373047", #"Year" = 2018, #"Population" = 457],
					        [#"Ethnic geoup" = "-64.142046, 55.198175", #"Year" = 2013, #"Population" = 7],
					        [#"Ethnic geoup" = "-44.152417, 40.360054", #"Year" = 2019, #"Population" = 292],
					        [#"Ethnic geoup" = "41.716496, 116.718534", #"Year" = 2017, #"Population" = 130],
					        [#"Ethnic geoup" = "55.471494, -40.160715", #"Year" = 2007, #"Population" = 238],
					        [#"Ethnic geoup" = "2.433141, 147.245099", #"Year" = 2009, #"Population" = 723],
					        [#"Ethnic geoup" = "75.034997, -23.838119", #"Year" = 2003, #"Population" = 311],
					        [#"Ethnic geoup" = "-70.865602, -30.056389", #"Year" = 2021, #"Population" = 235],
					        [#"Ethnic geoup" = "-68.138789, -151.360264", #"Year" = 2018, #"Population" = 426],
					        [#"Ethnic geoup" = "-15.233753, -166.860077", #"Year" = 2003, #"Population" = 242],
					        [#"Ethnic geoup" = "-5.22875, -173.793968", #"Year" = 2007, #"Population" = 756],
					        [#"Ethnic geoup" = "29.890127, 172.644372", #"Year" = 2006, #"Population" = 122],
					        [#"Ethnic geoup" = "-58.323773, -166.871494", #"Year" = 2013, #"Population" = 401],
					        [#"Ethnic geoup" = "20.138808, 40.771386", #"Year" = 2015, #"Population" = 628],
					        [#"Ethnic geoup" = "64.07804, -128.820887", #"Year" = 2007, #"Population" = 896],
					        [#"Ethnic geoup" = "69.502265, -100.971335", #"Year" = 2005, #"Population" = 401],
					        [#"Ethnic geoup" = "55.720279, 177.192213", #"Year" = 2022, #"Population" = 401],
					        [#"Ethnic geoup" = "56.339366, -166.241882", #"Year" = 2004, #"Population" = 570],
					        [#"Ethnic geoup" = "29.048054, 122.098474", #"Year" = 2003, #"Population" = 379],
					        [#"Ethnic geoup" = "17.565868, -74.556089", #"Year" = 2014, #"Population" = 33],
					        [#"Ethnic geoup" = "23.320954, 2.912361", #"Year" = 2011, #"Population" = 675],
					        [#"Ethnic geoup" = "32.695712, -85.546246", #"Year" = 2019, #"Population" = 871],
					        [#"Ethnic geoup" = "-12.364802, 150.471031", #"Year" = 2024, #"Population" = 916],
					        [#"Ethnic geoup" = "57.417405, -168.930786", #"Year" = 2006, #"Population" = 520],
					        [#"Ethnic geoup" = "-88.956215, 102.160172", #"Year" = 2005, #"Population" = 74],
					        [#"Ethnic geoup" = "-55.112969, 9.861401", #"Year" = 2013, #"Population" = 925],
					        [#"Ethnic geoup" = "-39.525926, -129.146716", #"Year" = 2009, #"Population" = 928],
					        [#"Ethnic geoup" = "82.846916, 78.393855", #"Year" = 2013, #"Population" = 461],
					        [#"Ethnic geoup" = "-35.046859, 122.05841", #"Year" = 2004, #"Population" = 836],
					        [#"Ethnic geoup" = "-79.071875, -94.371886", #"Year" = 2007, #"Population" = 276],
					        [#"Ethnic geoup" = "62.84751, 87.635083", #"Year" = 2017, #"Population" = 615],
					        [#"Ethnic geoup" = "29.302329, -136.567699", #"Year" = 2010, #"Population" = 574],
					        [#"Ethnic geoup" = "-38.14508, -135.745217", #"Year" = 2024, #"Population" = 652],
					        [#"Ethnic geoup" = "66.495519, 173.652192", #"Year" = 2000, #"Population" = 128],
					        [#"Ethnic geoup" = "-86.859837, 101.302732", #"Year" = 2017, #"Population" = 628],
					        [#"Ethnic geoup" = "-44.613915, -89.275569", #"Year" = 2010, #"Population" = 901],
					        [#"Ethnic geoup" = "-31.34356, -148.13801", #"Year" = 2010, #"Population" = 368],
					        [#"Ethnic geoup" = "81.771907, -83.878784", #"Year" = 2016, #"Population" = 23],
					        [#"Ethnic geoup" = "-53.478564, -27.949158", #"Year" = 2016, #"Population" = 444],
					        [#"Ethnic geoup" = "-14.821512, 61.005346", #"Year" = 2024, #"Population" = 746],
					        [#"Ethnic geoup" = "-56.910194, 168.996287", #"Year" = 2012, #"Population" = 407],
					        [#"Ethnic geoup" = "-65.805596, 78.901307", #"Year" = 2000, #"Population" = 597],
					        [#"Ethnic geoup" = "37.540572, 174.258619", #"Year" = 2001, #"Population" = 481],
					        [#"Ethnic geoup" = "-59.88071, -28.058262", #"Year" = 2007, #"Population" = 79],
					        [#"Ethnic geoup" = "84.03985, 34.048534", #"Year" = 2016, #"Population" = 876],
					        [#"Ethnic geoup" = "-11.193577, 13.454952", #"Year" = 2005, #"Population" = 645],
					        [#"Ethnic geoup" = "54.755551, -44.339124", #"Year" = 2002, #"Population" = 545],
					        [#"Ethnic geoup" = "20.379398, 103.341885", #"Year" = 2015, #"Population" = 304],
					        [#"Ethnic geoup" = "26.711563, -17.717385", #"Year" = 2021, #"Population" = 356],
					        [#"Ethnic geoup" = "1.461917, -63.358571", #"Year" = 2007, #"Population" = 763],
					        [#"Ethnic geoup" = "66.942651, -50.109005", #"Year" = 2015, #"Population" = 732],
					        [#"Ethnic geoup" = "38.587768, 150.844078", #"Year" = 2003, #"Population" = 384],
					        [#"Ethnic geoup" = "89.549885, -173.821013", #"Year" = 2002, #"Population" = 126],
					        [#"Ethnic geoup" = "-31.934397, 23.37723", #"Year" = 2002, #"Population" = 750],
					        [#"Ethnic geoup" = "-85.6275, -52.822984", #"Year" = 2009, #"Population" = 176],
					        [#"Ethnic geoup" = "-81.378483, -20.099201", #"Year" = 2005, #"Population" = 414],
					        [#"Ethnic geoup" = "18.70903, 27.572859", #"Year" = 2014, #"Population" = 501],
					        [#"Ethnic geoup" = "89.661974, -149.950784", #"Year" = 2021, #"Population" = 65],
					        [#"Ethnic geoup" = "-55.239873, 126.425504", #"Year" = 2005, #"Population" = 508],
					        [#"Ethnic geoup" = "-48.125855, 29.642451", #"Year" = 2000, #"Population" = 299],
					        [#"Ethnic geoup" = "-36.925783, 61.39353", #"Year" = 2006, #"Population" = 719],
					        [#"Ethnic geoup" = "-6.89228, 0.676174", #"Year" = 2015, #"Population" = 515],
					        [#"Ethnic geoup" = "-47.540832, 3.59752", #"Year" = 2024, #"Population" = 899],
					        [#"Ethnic geoup" = "-17.616342, 135.022756", #"Year" = 2020, #"Population" = 92],
					        [#"Ethnic geoup" = "58.075509, 97.522719", #"Year" = 2019, #"Population" = 822],
					        [#"Ethnic geoup" = "49.706001, 15.461375", #"Year" = 2002, #"Population" = 326],
					        [#"Ethnic geoup" = "-75.768749, 71.100354", #"Year" = 2024, #"Population" = 160],
					        [#"Ethnic geoup" = "-85.708743, 34.118007", #"Year" = 2014, #"Population" = 719],
					        [#"Ethnic geoup" = "88.742795, 165.225182", #"Year" = 2007, #"Population" = 485],
					        [#"Ethnic geoup" = "87.581377, 115.604747", #"Year" = 2003, #"Population" = 182],
					        [#"Ethnic geoup" = "75.545143, 109.108924", #"Year" = 2022, #"Population" = 964],
					        [#"Ethnic geoup" = "79.423572, -41.265384", #"Year" = 2000, #"Population" = 360],
					        [#"Ethnic geoup" = "-89.224866, 155.200383", #"Year" = 2015, #"Population" = 482],
					        [#"Ethnic geoup" = "-38.983928, 0.442405", #"Year" = 2019, #"Population" = 308],
					        [#"Ethnic geoup" = "17.268906, -10.164702", #"Year" = 2010, #"Population" = 463],
					        [#"Ethnic geoup" = "-52.314528, 7.989519", #"Year" = 2001, #"Population" = 723],
					        [#"Ethnic geoup" = "-14.673689, 15.532949", #"Year" = 2011, #"Population" = 566],
					        [#"Ethnic geoup" = "14.30809, 6.910882", #"Year" = 2011, #"Population" = 162],
					        [#"Ethnic geoup" = "65.364965, -106.870001", #"Year" = 2018, #"Population" = 298],
					        [#"Ethnic geoup" = "-32.364259, 83.952577", #"Year" = 2012, #"Population" = 815],
					        [#"Ethnic geoup" = "-4.523878, 34.435823", #"Year" = 2001, #"Population" = 941],
					        [#"Ethnic geoup" = "44.141963, 75.052181", #"Year" = 2017, #"Population" = 322],
					        [#"Ethnic geoup" = "32.033431, -0.812403", #"Year" = 2000, #"Population" = 583],
					        [#"Ethnic geoup" = "-2.327843, 63.808314", #"Year" = 2012, #"Population" = 810],
					        [#"Ethnic geoup" = "18.619436, -76.217267", #"Year" = 2020, #"Population" = 621],
					        [#"Ethnic geoup" = "-77.685915, 66.684213", #"Year" = 2014, #"Population" = 56],
					        [#"Ethnic geoup" = "-84.104524, 91.242563", #"Year" = 2017, #"Population" = 821],
					        [#"Ethnic geoup" = "-67.698847, 26.220659", #"Year" = 2016, #"Population" = 737],
					        [#"Ethnic geoup" = "30.607031, 130.262315", #"Year" = 2005, #"Population" = 152],
					        [#"Ethnic geoup" = "-51.106286, -3.904749", #"Year" = 2008, #"Population" = 58],
					        [#"Ethnic geoup" = "70.503305, 111.179978", #"Year" = 2004, #"Population" = 62],
					        [#"Ethnic geoup" = "-68.447652, 106.177799", #"Year" = 2002, #"Population" = 267],
					        [#"Ethnic geoup" = "74.103356, 10.213564", #"Year" = 2007, #"Population" = 432],
					        [#"Ethnic geoup" = "-86.035536, -41.263647", #"Year" = 2005, #"Population" = 735],
					        [#"Ethnic geoup" = "-71.876099, 5.763143", #"Year" = 2002, #"Population" = 782],
					        [#"Ethnic geoup" = "-23.303148, -26.082796", #"Year" = 2005, #"Population" = 126],
					        [#"Ethnic geoup" = "70.05111, 67.300905", #"Year" = 2021, #"Population" = 765],
					        [#"Ethnic geoup" = "44.653669, -4.294825", #"Year" = 2005, #"Population" = 393],
					        [#"Ethnic geoup" = "-64.936546, 173.054071", #"Year" = 2001, #"Population" = 39],
					        [#"Ethnic geoup" = "-6.939869, -85.038167", #"Year" = 2022, #"Population" = 942],
					        [#"Ethnic geoup" = "-39.724355, 134.272682", #"Year" = 2023, #"Population" = 564],
					        [#"Ethnic geoup" = "-12.199566, -113.717565", #"Year" = 2019, #"Population" = 979],
					        [#"Ethnic geoup" = "27.538509, -86.632078", #"Year" = 2015, #"Population" = 536],
					        [#"Ethnic geoup" = "-88.545374, 78.762116", #"Year" = 2004, #"Population" = 220],
					        [#"Ethnic geoup" = "-23.399925, 112.878023", #"Year" = 2024, #"Population" = 253],
					        [#"Ethnic geoup" = "23.577901, 132.862986", #"Year" = 2014, #"Population" = 449],
					        [#"Ethnic geoup" = "70.266414, -23.232566", #"Year" = 2019, #"Population" = 801],
					        [#"Ethnic geoup" = "-30.604271, 41.577668", #"Year" = 2001, #"Population" = 845],
					        [#"Ethnic geoup" = "70.916608, 56.689183", #"Year" = 2011, #"Population" = 172],
					        [#"Ethnic geoup" = "-10.72324, -119.073239", #"Year" = 2004, #"Population" = 288],
					        [#"Ethnic geoup" = "17.354617, -3.707268", #"Year" = 2019, #"Population" = 604],
					        [#"Ethnic geoup" = "40.039973, -19.661951", #"Year" = 2019, #"Population" = 641],
					        [#"Ethnic geoup" = "86.035191, -53.648067", #"Year" = 2017, #"Population" = 104],
					        [#"Ethnic geoup" = "-41.396586, -51.391455", #"Year" = 2009, #"Population" = 234],
					        [#"Ethnic geoup" = "-61.835545, 33.50202", #"Year" = 2018, #"Population" = 82],
					        [#"Ethnic geoup" = "54.647276, 177.415532", #"Year" = 2011, #"Population" = 327],
					        [#"Ethnic geoup" = "61.22855, -15.950765", #"Year" = 2021, #"Population" = 816],
					        [#"Ethnic geoup" = "67.41111, -143.035968", #"Year" = 2014, #"Population" = 304],
					        [#"Ethnic geoup" = "82.457401, 115.099916", #"Year" = 2016, #"Population" = 844],
					        [#"Ethnic geoup" = "-75.773141, -38.054395", #"Year" = 2010, #"Population" = 414],
					        [#"Ethnic geoup" = "-43.780365, 103.688111", #"Year" = 2011, #"Population" = 913],
					        [#"Ethnic geoup" = "-88.909107, -32.396727", #"Year" = 2021, #"Population" = 237],
					        [#"Ethnic geoup" = "-25.843402, -171.70715", #"Year" = 2016, #"Population" = 272],
					        [#"Ethnic geoup" = "-44.969776, -174.679167", #"Year" = 2015, #"Population" = 896],
					        [#"Ethnic geoup" = "23.665546, -74.663655", #"Year" = 2019, #"Population" = 490],
					        [#"Ethnic geoup" = "-85.881644, -37.57385", #"Year" = 2005, #"Population" = 94],
					        [#"Ethnic geoup" = "-47.434318, 41.079634", #"Year" = 2015, #"Population" = 610],
					        [#"Ethnic geoup" = "-63.875553, -151.458602", #"Year" = 2020, #"Population" = 878],
					        [#"Ethnic geoup" = "-87.994704, 87.966504", #"Year" = 2004, #"Population" = 782],
					        [#"Ethnic geoup" = "-57.301899, 106.344878", #"Year" = 2018, #"Population" = 944],
					        [#"Ethnic geoup" = "-38.896105, -178.444874", #"Year" = 2023, #"Population" = 983],
					        [#"Ethnic geoup" = "62.687908, 4.242114", #"Year" = 2012, #"Population" = 434],
					        [#"Ethnic geoup" = "53.718222, 8.931303", #"Year" = 2020, #"Population" = 140],
					        [#"Ethnic geoup" = "-54.098691, -2.475209", #"Year" = 2001, #"Population" = 980],
					        [#"Ethnic geoup" = "-9.303264, -149.992173", #"Year" = 2000, #"Population" = 570],
					        [#"Ethnic geoup" = "51.177865, -64.567541", #"Year" = 2002, #"Population" = 13],
					        [#"Ethnic geoup" = "-25.435949, -26.725226", #"Year" = 2017, #"Population" = 784],
					        [#"Ethnic geoup" = "56.458088, -147.930985", #"Year" = 2024, #"Population" = 921],
					        [#"Ethnic geoup" = "-68.441453, 168.326103", #"Year" = 2004, #"Population" = 482],
					        [#"Ethnic geoup" = "73.642735, -9.146749", #"Year" = 2001, #"Population" = 820],
					        [#"Ethnic geoup" = "19.102734, -152.549364", #"Year" = 2010, #"Population" = 287],
					        [#"Ethnic geoup" = "-59.468067, 146.546084", #"Year" = 2002, #"Population" = 582],
					        [#"Ethnic geoup" = "14.119981, -42.096152", #"Year" = 2015, #"Population" = 166],
					        [#"Ethnic geoup" = "-73.958852, 158.134634", #"Year" = 2009, #"Population" = 205],
					        [#"Ethnic geoup" = "44.598305, 157.007732", #"Year" = 2001, #"Population" = 128],
					        [#"Ethnic geoup" = "-15.514298, -139.732188", #"Year" = 2007, #"Population" = 899],
					        [#"Ethnic geoup" = "52.008288, 1.83696", #"Year" = 2005, #"Population" = 577],
					        [#"Ethnic geoup" = "87.802735, -22.278279", #"Year" = 2003, #"Population" = 455],
					        [#"Ethnic geoup" = "59.067541, 149.384999", #"Year" = 2020, #"Population" = 175],
					        [#"Ethnic geoup" = "-77.545869, -124.839317", #"Year" = 2014, #"Population" = 636],
					        [#"Ethnic geoup" = "21.844148, -139.509458", #"Year" = 2021, #"Population" = 722],
					        [#"Ethnic geoup" = "-54.5741, 140.119174", #"Year" = 2007, #"Population" = 511],
					        [#"Ethnic geoup" = "38.962729, 68.529703", #"Year" = 2014, #"Population" = 201],
					        [#"Ethnic geoup" = "17.370601, -51.390073", #"Year" = 2000, #"Population" = 51],
					        [#"Ethnic geoup" = "67.214679, -61.020286", #"Year" = 2012, #"Population" = 14],
					        [#"Ethnic geoup" = "-50.698556, -65.248878", #"Year" = 2002, #"Population" = 504],
					        [#"Ethnic geoup" = "15.410332, -140.655442", #"Year" = 2019, #"Population" = 428],
					        [#"Ethnic geoup" = "59.568099, -166.434011", #"Year" = 2014, #"Population" = 985],
					        [#"Ethnic geoup" = "-49.430762, 27.53699", #"Year" = 2020, #"Population" = 523],
					        [#"Ethnic geoup" = "-37.684777, -137.850555", #"Year" = 2008, #"Population" = 680],
					        [#"Ethnic geoup" = "27.77123, 26.669092", #"Year" = 2024, #"Population" = 171],
					        [#"Ethnic geoup" = "-87.133812, -152.584822", #"Year" = 2011, #"Population" = 491],
					        [#"Ethnic geoup" = "88.634269, -14.841864", #"Year" = 2024, #"Population" = 990],
					        [#"Ethnic geoup" = "43.815357, 7.036332", #"Year" = 2008, #"Population" = 948],
					        [#"Ethnic geoup" = "-32.979787, 105.969588", #"Year" = 2007, #"Population" = 295],
					        [#"Ethnic geoup" = "-80.806602, 148.625545", #"Year" = 2022, #"Population" = 925],
					        [#"Ethnic geoup" = "64.243609, 109.39693", #"Year" = 2021, #"Population" = 671],
					        [#"Ethnic geoup" = "7.92109, 61.480767", #"Year" = 2010, #"Population" = 428],
					        [#"Ethnic geoup" = "6.546799, 67.365592", #"Year" = 2021, #"Population" = 914],
					        [#"Ethnic geoup" = "-78.146429, -86.148236", #"Year" = 2019, #"Population" = 722],
					        [#"Ethnic geoup" = "82.742449, -113.7156", #"Year" = 2005, #"Population" = 118],
					        [#"Ethnic geoup" = "9.41682, 107.155689", #"Year" = 2022, #"Population" = 461],
					        [#"Ethnic geoup" = "47.823996, -6.049749", #"Year" = 2010, #"Population" = 694],
					        [#"Ethnic geoup" = "78.567288, -80.656977", #"Year" = 2024, #"Population" = 676],
					        [#"Ethnic geoup" = "3.943536, -107.443911", #"Year" = 2002, #"Population" = 116],
					        [#"Ethnic geoup" = "-22.032067, -126.696072", #"Year" = 2006, #"Population" = 252],
					        [#"Ethnic geoup" = "-32.228197, -128.948191", #"Year" = 2012, #"Population" = 28],
					        [#"Ethnic geoup" = "82.036248, -61.12844", #"Year" = 2003, #"Population" = 121],
					        [#"Ethnic geoup" = "-49.96061, -61.575975", #"Year" = 2014, #"Population" = 690],
					        [#"Ethnic geoup" = "24.029665, -22.539941", #"Year" = 2024, #"Population" = 494],
					        [#"Ethnic geoup" = "50.557306, 156.139103", #"Year" = 2001, #"Population" = 522],
					        [#"Ethnic geoup" = "14.514856, -41.212188", #"Year" = 2009, #"Population" = 298],
					        [#"Ethnic geoup" = "-84.797126, -96.661788", #"Year" = 2014, #"Population" = 943],
					        [#"Ethnic geoup" = "22.172069, 172.712341", #"Year" = 2021, #"Population" = 872],
					        [#"Ethnic geoup" = "-54.672164, 172.058187", #"Year" = 2016, #"Population" = 811],
					        [#"Ethnic geoup" = "10.291673, -41.067163", #"Year" = 2000, #"Population" = 22],
					        [#"Ethnic geoup" = "-84.835211, -80.956799", #"Year" = 2016, #"Population" = 981],
					        [#"Ethnic geoup" = "57.254281, -84.931207", #"Year" = 2009, #"Population" = 196],
					        [#"Ethnic geoup" = "20.523132, -92.031893", #"Year" = 2003, #"Population" = 195],
					        [#"Ethnic geoup" = "53.940025, 0.68892", #"Year" = 2019, #"Population" = 801],
					        [#"Ethnic geoup" = "-86.885379, -1.61482", #"Year" = 2020, #"Population" = 568],
					        [#"Ethnic geoup" = "-37.260257, -55.192538", #"Year" = 2012, #"Population" = 670],
					        [#"Ethnic geoup" = "3.885411, 104.722641", #"Year" = 2016, #"Population" = 2],
					        [#"Ethnic geoup" = "-88.377944, -99.756082", #"Year" = 2020, #"Population" = 712],
					        [#"Ethnic geoup" = "81.510089, 58.280363", #"Year" = 2005, #"Population" = 262],
					        [#"Ethnic geoup" = "-58.259247, -131.402973", #"Year" = 2007, #"Population" = 610],
					        [#"Ethnic geoup" = "75.066629, -30.950339", #"Year" = 2007, #"Population" = 104],
					        [#"Ethnic geoup" = "51.729626, 73.777445", #"Year" = 2012, #"Population" = 225],
					        [#"Ethnic geoup" = "-85.311279, -89.134361", #"Year" = 2012, #"Population" = 155],
					        [#"Ethnic geoup" = "-23.767326, 170.108424", #"Year" = 2008, #"Population" = 495],
					        [#"Ethnic geoup" = "-35.739587, 118.62297", #"Year" = 2017, #"Population" = 938],
					        [#"Ethnic geoup" = "-87.447609, 97.278763", #"Year" = 2015, #"Population" = 976],
					        [#"Ethnic geoup" = "-6.662844, 139.731759", #"Year" = 2000, #"Population" = 649],
					        [#"Ethnic geoup" = "29.056993, -0.613484", #"Year" = 2023, #"Population" = 388],
					        [#"Ethnic geoup" = "-10.987236, -58.101456", #"Year" = 2012, #"Population" = 558],
					        [#"Ethnic geoup" = "18.297962, -167.431579", #"Year" = 2016, #"Population" = 34],
					        [#"Ethnic geoup" = "-47.348663, -179.347115", #"Year" = 2003, #"Population" = 667],
					        [#"Ethnic geoup" = "-83.474942, -175.486561", #"Year" = 2015, #"Population" = 72],
					        [#"Ethnic geoup" = "85.472652, 5.612847", #"Year" = 2006, #"Population" = 376],
					        [#"Ethnic geoup" = "-87.946239, 131.906527", #"Year" = 2000, #"Population" = 263],
					        [#"Ethnic geoup" = "-62.557529, 134.023001", #"Year" = 2009, #"Population" = 536],
					        [#"Ethnic geoup" = "-41.637425, -73.358186", #"Year" = 2007, #"Population" = 372],
					        [#"Ethnic geoup" = "76.206059, 78.815706", #"Year" = 2021, #"Population" = 847],
					        [#"Ethnic geoup" = "-12.151601, -147.584019", #"Year" = 2005, #"Population" = 698],
					        [#"Ethnic geoup" = "-6.322886, 27.753014", #"Year" = 2010, #"Population" = 413],
					        [#"Ethnic geoup" = "-51.326636, 172.641869", #"Year" = 2024, #"Population" = 445],
					        [#"Ethnic geoup" = "-44.702, 164.113882", #"Year" = 2012, #"Population" = 932],
					        [#"Ethnic geoup" = "4.392969, 58.802425", #"Year" = 2018, #"Population" = 592],
					        [#"Ethnic geoup" = "20.972394, 126.872332", #"Year" = 2013, #"Population" = 779],
					        [#"Ethnic geoup" = "-58.777623, 20.137137", #"Year" = 2001, #"Population" = 997],
					        [#"Ethnic geoup" = "28.36044, -132.978217", #"Year" = 2016, #"Population" = 949],
					        [#"Ethnic geoup" = "-55.149996, 102.221877", #"Year" = 2014, #"Population" = 805],
					        [#"Ethnic geoup" = "-73.483337, -145.314686", #"Year" = 2018, #"Population" = 379],
					        [#"Ethnic geoup" = "69.217292, -32.807394", #"Year" = 2008, #"Population" = 758],
					        [#"Ethnic geoup" = "-73.509289, 165.050375", #"Year" = 2007, #"Population" = 821],
					        [#"Ethnic geoup" = "34.877304, -10.289977", #"Year" = 2023, #"Population" = 58],
					        [#"Ethnic geoup" = "80.844352, -151.726624", #"Year" = 2004, #"Population" = 210],
					        [#"Ethnic geoup" = "-18.980769, 88.523975", #"Year" = 2010, #"Population" = 478],
					        [#"Ethnic geoup" = "-52.580097, 57.229261", #"Year" = 2011, #"Population" = 96],
					        [#"Ethnic geoup" = "-72.186451, 17.186806", #"Year" = 2017, #"Population" = 871],
					        [#"Ethnic geoup" = "-22.233138, 167.672568", #"Year" = 2002, #"Population" = 142],
					        [#"Ethnic geoup" = "-80.850667, -127.100699", #"Year" = 2010, #"Population" = 935],
					        [#"Ethnic geoup" = "-55.271557, 60.329202", #"Year" = 2019, #"Population" = 346],
					        [#"Ethnic geoup" = "67.530116, 147.030551", #"Year" = 2006, #"Population" = 191],
					        [#"Ethnic geoup" = "38.577579, -45.740872", #"Year" = 2001, #"Population" = 884],
					        [#"Ethnic geoup" = "-61.219225, -16.744459", #"Year" = 2010, #"Population" = 765],
					        [#"Ethnic geoup" = "34.548332, 69.465239", #"Year" = 2018, #"Population" = 733],
					        [#"Ethnic geoup" = "-85.887726, -113.783643", #"Year" = 2023, #"Population" = 1000],
					        [#"Ethnic geoup" = "-2.06107, -40.061131", #"Year" = 2010, #"Population" = 113],
					        [#"Ethnic geoup" = "82.514828, -113.099537", #"Year" = 2019, #"Population" = 648],
					        [#"Ethnic geoup" = "-48.350661, 33.906935", #"Year" = 2021, #"Population" = 76],
					        [#"Ethnic geoup" = "-21.534948, 70.747836", #"Year" = 2004, #"Population" = 619],
					        [#"Ethnic geoup" = "-61.414731, -105.370119", #"Year" = 2002, #"Population" = 328],
					        [#"Ethnic geoup" = "85.568438, 72.641873", #"Year" = 2003, #"Population" = 164],
					        [#"Ethnic geoup" = "86.701288, 19.423093", #"Year" = 2017, #"Population" = 11],
					        [#"Ethnic geoup" = "-21.345366, 60.126857", #"Year" = 2001, #"Population" = 113],
					        [#"Ethnic geoup" = "-29.379967, 119.444861", #"Year" = 2008, #"Population" = 627],
					        [#"Ethnic geoup" = "-5.398015, 97.165341", #"Year" = 2022, #"Population" = 154],
					        [#"Ethnic geoup" = "-41.323726, 134.046647", #"Year" = 2003, #"Population" = 533],
					        [#"Ethnic geoup" = "-66.058229, 32.744163", #"Year" = 2023, #"Population" = 126],
					        [#"Ethnic geoup" = "79.938885, -161.568414", #"Year" = 2007, #"Population" = 733],
					        [#"Ethnic geoup" = "89.983339, 149.688639", #"Year" = 2001, #"Population" = 871],
					        [#"Ethnic geoup" = "-69.966175, -22.547616", #"Year" = 2011, #"Population" = 51],
					        [#"Ethnic geoup" = "83.012972, -9.111198", #"Year" = 2015, #"Population" = 78],
					        [#"Ethnic geoup" = "23.47291, -10.004438", #"Year" = 2009, #"Population" = 498],
					        [#"Ethnic geoup" = "-55.122383, 81.452813", #"Year" = 2017, #"Population" = 531],
					        [#"Ethnic geoup" = "33.61034, -158.787202", #"Year" = 2021, #"Population" = 566],
					        [#"Ethnic geoup" = "-83.999467, 66.906501", #"Year" = 2009, #"Population" = 948],
					        [#"Ethnic geoup" = "-43.406612, -71.965003", #"Year" = 2010, #"Population" = 950],
					        [#"Ethnic geoup" = "-69.614792, -82.244303", #"Year" = 2012, #"Population" = 189],
					        [#"Ethnic geoup" = "-4.996626, 111.110342", #"Year" = 2006, #"Population" = 336],
					        [#"Ethnic geoup" = "34.408991, -119.66816", #"Year" = 2009, #"Population" = 967],
					        [#"Ethnic geoup" = "-35.161779, -145.26258", #"Year" = 2007, #"Population" = 538],
					        [#"Ethnic geoup" = "3.163198, 145.079992", #"Year" = 2005, #"Population" = 473],
					        [#"Ethnic geoup" = "77.898181, -116.984864", #"Year" = 2004, #"Population" = 279],
					        [#"Ethnic geoup" = "-75.40689, 105.040059", #"Year" = 2020, #"Population" = 62],
					        [#"Ethnic geoup" = "72.105922, 11.062498", #"Year" = 2022, #"Population" = 247],
					        [#"Ethnic geoup" = "-23.111141, 129.087141", #"Year" = 2010, #"Population" = 286],
					        [#"Ethnic geoup" = "30.529996, -62.454216", #"Year" = 2022, #"Population" = 385],
					        [#"Ethnic geoup" = "19.549909, 73.253104", #"Year" = 2009, #"Population" = 102],
					        [#"Ethnic geoup" = "39.769049, -37.146468", #"Year" = 2010, #"Population" = 805],
					        [#"Ethnic geoup" = "-58.47756, 36.089235", #"Year" = 2000, #"Population" = 835],
					        [#"Ethnic geoup" = "57.955235, -97.18314", #"Year" = 2014, #"Population" = 870],
					        [#"Ethnic geoup" = "89.586318, 69.057181", #"Year" = 2011, #"Population" = 533],
					        [#"Ethnic geoup" = "-33.257335, 36.883792", #"Year" = 2001, #"Population" = 134],
					        [#"Ethnic geoup" = "5.569274, -50.270372", #"Year" = 2023, #"Population" = 820],
					        [#"Ethnic geoup" = "-10.9266, -8.818969", #"Year" = 2022, #"Population" = 413],
					        [#"Ethnic geoup" = "17.720493, -33.860339", #"Year" = 2008, #"Population" = 576],
					        [#"Ethnic geoup" = "-71.394156, -67.544201", #"Year" = 2010, #"Population" = 385],
					        [#"Ethnic geoup" = "-52.671717, -87.297334", #"Year" = 2002, #"Population" = 958],
					        [#"Ethnic geoup" = "33.600988, 115.304309", #"Year" = 2021, #"Population" = 889],
					        [#"Ethnic geoup" = "66.933619, -157.139575", #"Year" = 2022, #"Population" = 856],
					        [#"Ethnic geoup" = "28.475662, 89.577858", #"Year" = 2011, #"Population" = 826],
					        [#"Ethnic geoup" = "81.299672, 59.029864", #"Year" = 2009, #"Population" = 727],
					        [#"Ethnic geoup" = "-42.813939, 139.782209", #"Year" = 2015, #"Population" = 747],
					        [#"Ethnic geoup" = "4.76698, 9.630874", #"Year" = 2003, #"Population" = 495],
					        [#"Ethnic geoup" = "59.744508, 104.31585", #"Year" = 2004, #"Population" = 551],
					        [#"Ethnic geoup" = "-70.558984, -135.385846", #"Year" = 2018, #"Population" = 511],
					        [#"Ethnic geoup" = "-82.295145, 44.732073", #"Year" = 2022, #"Population" = 1],
					        [#"Ethnic geoup" = "30.654704, 137.675816", #"Year" = 2014, #"Population" = 621],
					        [#"Ethnic geoup" = "44.33059, -176.216855", #"Year" = 2015, #"Population" = 128],
					        [#"Ethnic geoup" = "30.013171, 28.694097", #"Year" = 2005, #"Population" = 770],
					        [#"Ethnic geoup" = "-22.3119, 24.750099", #"Year" = 2005, #"Population" = 511],
					        [#"Ethnic geoup" = "30.804643, -78.048708", #"Year" = 2001, #"Population" = 951],
					        [#"Ethnic geoup" = "0.804967, -13.603492", #"Year" = 2017, #"Population" = 336],
					        [#"Ethnic geoup" = "-14.607488, 6.271439", #"Year" = 2011, #"Population" = 915],
					        [#"Ethnic geoup" = "26.969554, -132.943954", #"Year" = 2001, #"Population" = 401],
					        [#"Ethnic geoup" = "-82.314436, -138.189591", #"Year" = 2006, #"Population" = 843],
					        [#"Ethnic geoup" = "-73.513002, 120.036456", #"Year" = 2016, #"Population" = 699],
					        [#"Ethnic geoup" = "45.640867, -98.370141", #"Year" = 2018, #"Population" = 985],
					        [#"Ethnic geoup" = "52.716849, 118.41975", #"Year" = 2024, #"Population" = 301],
					        [#"Ethnic geoup" = "34.353102, -128.016012", #"Year" = 2009, #"Population" = 198],
					        [#"Ethnic geoup" = "69.054833, -69.875729", #"Year" = 2021, #"Population" = 17],
					        [#"Ethnic geoup" = "37.423723, 98.552013", #"Year" = 2003, #"Population" = 820],
					        [#"Ethnic geoup" = "-83.723749, 126.770195", #"Year" = 2006, #"Population" = 717],
					        [#"Ethnic geoup" = "69.728136, -77.070807", #"Year" = 2000, #"Population" = 683],
					        [#"Ethnic geoup" = "-28.574267, 66.528217", #"Year" = 2000, #"Population" = 393],
					        [#"Ethnic geoup" = "-11.499357, -13.960843", #"Year" = 2005, #"Population" = 451],
					        [#"Ethnic geoup" = "79.272135, 14.089857", #"Year" = 2023, #"Population" = 105],
					        [#"Ethnic geoup" = "-84.163245, -161.794623", #"Year" = 2013, #"Population" = 920],
					        [#"Ethnic geoup" = "-38.307873, 9.819518", #"Year" = 2012, #"Population" = 638],
					        [#"Ethnic geoup" = "-11.901506, 169.884109", #"Year" = 2002, #"Population" = 315],
					        [#"Ethnic geoup" = "56.140113, -25.103785", #"Year" = 2019, #"Population" = 3],
					        [#"Ethnic geoup" = "-21.187491, -110.636837", #"Year" = 2018, #"Population" = 364],
					        [#"Ethnic geoup" = "-85.696779, -150.350846", #"Year" = 2009, #"Population" = 306],
					        [#"Ethnic geoup" = "-14.702238, -163.892063", #"Year" = 2015, #"Population" = 48],
					        [#"Ethnic geoup" = "-85.481291, 114.994886", #"Year" = 2008, #"Population" = 279],
					        [#"Ethnic geoup" = "22.103701, -93.528191", #"Year" = 2006, #"Population" = 858],
					        [#"Ethnic geoup" = "46.034874, -153.859229", #"Year" = 2005, #"Population" = 399],
					        [#"Ethnic geoup" = "-62.316984, -148.599722", #"Year" = 2006, #"Population" = 130],
					        [#"Ethnic geoup" = "-10.731607, 22.873263", #"Year" = 2021, #"Population" = 641],
					        [#"Ethnic geoup" = "5.00529, -97.425101", #"Year" = 2000, #"Population" = 874],
					        [#"Ethnic geoup" = "60.357194, 124.50975", #"Year" = 2001, #"Population" = 418],
					        [#"Ethnic geoup" = "8.155717, 27.234472", #"Year" = 2012, #"Population" = 921],
					        [#"Ethnic geoup" = "-15.445613, -110.541462", #"Year" = 2017, #"Population" = 562],
					        [#"Ethnic geoup" = "27.099012, 162.18604", #"Year" = 2008, #"Population" = 883],
					        [#"Ethnic geoup" = "21.768773, -121.989601", #"Year" = 2021, #"Population" = 128],
					        [#"Ethnic geoup" = "-40.540608, 137.191086", #"Year" = 2016, #"Population" = 411],
					        [#"Ethnic geoup" = "-4.225524, -169.927389", #"Year" = 2019, #"Population" = 268],
					        [#"Ethnic geoup" = "24.161702, 63.860967", #"Year" = 2003, #"Population" = 612],
					        [#"Ethnic geoup" = "-38.045265, -121.072751", #"Year" = 2004, #"Population" = 681],
					        [#"Ethnic geoup" = "74.417746, -44.879858", #"Year" = 2011, #"Population" = 887],
					        [#"Ethnic geoup" = "6.23458, -90.944866", #"Year" = 2011, #"Population" = 833],
					        [#"Ethnic geoup" = "-68.379471, -112.997978", #"Year" = 2014, #"Population" = 406],
					        [#"Ethnic geoup" = "-6.297004, -68.484767", #"Year" = 2014, #"Population" = 434],
					        [#"Ethnic geoup" = "47.644042, -137.55834", #"Year" = 2005, #"Population" = 96],
					        [#"Ethnic geoup" = "-86.606691, 179.76541", #"Year" = 2012, #"Population" = 374],
					        [#"Ethnic geoup" = "28.120149, -69.95807", #"Year" = 2006, #"Population" = 80],
					        [#"Ethnic geoup" = "-59.092454, -78.228729", #"Year" = 2023, #"Population" = 752],
					        [#"Ethnic geoup" = "-0.119419, -149.77747", #"Year" = 2020, #"Population" = 775],
					        [#"Ethnic geoup" = "85.821427, 67.098048", #"Year" = 2023, #"Population" = 782],
					        [#"Ethnic geoup" = "-13.076087, -80.04282", #"Year" = 2018, #"Population" = 572],
					        [#"Ethnic geoup" = "-70.223939, -174.76617", #"Year" = 2009, #"Population" = 784],
					        [#"Ethnic geoup" = "-2.762209, -126.50888", #"Year" = 2007, #"Population" = 840],
					        [#"Ethnic geoup" = "2.601856, -161.518496", #"Year" = 2017, #"Population" = 542],
					        [#"Ethnic geoup" = "82.915191, -22.75604", #"Year" = 2012, #"Population" = 218],
					        [#"Ethnic geoup" = "5.53495, 62.147546", #"Year" = 2024, #"Population" = 939],
					        [#"Ethnic geoup" = "33.236764, -98.597974", #"Year" = 2002, #"Population" = 459],
					        [#"Ethnic geoup" = "-31.444465, -161.210415", #"Year" = 2021, #"Population" = 879],
					        [#"Ethnic geoup" = "-56.762878, -79.145068", #"Year" = 2013, #"Population" = 969],
					        [#"Ethnic geoup" = "-74.127027, -109.302391", #"Year" = 2002, #"Population" = 209],
					        [#"Ethnic geoup" = "-25.709026, -165.204315", #"Year" = 2018, #"Population" = 797],
					        [#"Ethnic geoup" = "74.620773, 114.442071", #"Year" = 2017, #"Population" = 714],
					        [#"Ethnic geoup" = "-46.635635, -126.222678", #"Year" = 2008, #"Population" = 409],
					        [#"Ethnic geoup" = "-1.48516, -76.820127", #"Year" = 2010, #"Population" = 557],
					        [#"Ethnic geoup" = "-2.071208, -105.799866", #"Year" = 2002, #"Population" = 660],
					        [#"Ethnic geoup" = "-19.956195, -55.719753", #"Year" = 2004, #"Population" = 31],
					        [#"Ethnic geoup" = "-20.26522, -95.386356", #"Year" = 2017, #"Population" = 281],
					        [#"Ethnic geoup" = "-12.512187, 44.743885", #"Year" = 2016, #"Population" = 229],
					        [#"Ethnic geoup" = "78.352277, -149.542843", #"Year" = 2017, #"Population" = 786],
					        [#"Ethnic geoup" = "-67.894576, 137.150861", #"Year" = 2021, #"Population" = 824],
					        [#"Ethnic geoup" = "-23.889225, 40.785402", #"Year" = 2012, #"Population" = 188],
					        [#"Ethnic geoup" = "-6.396361, -80.912086", #"Year" = 2007, #"Population" = 627],
					        [#"Ethnic geoup" = "7.75486, 144.875499", #"Year" = 2023, #"Population" = 616],
					        [#"Ethnic geoup" = "2.741144, 67.748421", #"Year" = 2017, #"Population" = 913],
					        [#"Ethnic geoup" = "-34.819816, -162.122598", #"Year" = 2020, #"Population" = 22],
					        [#"Ethnic geoup" = "68.143043, 88.780368", #"Year" = 2008, #"Population" = 31],
					        [#"Ethnic geoup" = "-42.875419, -75.481863", #"Year" = 2024, #"Population" = 523],
					        [#"Ethnic geoup" = "87.228762, -74.768831", #"Year" = 2021, #"Population" = 775],
					        [#"Ethnic geoup" = "52.382889, -122.904172", #"Year" = 2010, #"Population" = 167],
					        [#"Ethnic geoup" = "49.310829, -47.352114", #"Year" = 2004, #"Population" = 141],
					        [#"Ethnic geoup" = "42.973499, 91.127389", #"Year" = 2000, #"Population" = 891],
					        [#"Ethnic geoup" = "5.062275, 99.642301", #"Year" = 2002, #"Population" = 582],
					        [#"Ethnic geoup" = "55.067163, -70.205932", #"Year" = 2008, #"Population" = 903],
					        [#"Ethnic geoup" = "-14.914566, 109.518557", #"Year" = 2022, #"Population" = 593],
					        [#"Ethnic geoup" = "-84.043251, 59.398334", #"Year" = 2015, #"Population" = 383],
					        [#"Ethnic geoup" = "83.264478, 113.128809", #"Year" = 2015, #"Population" = 575],
					        [#"Ethnic geoup" = "-27.5342, 119.99024", #"Year" = 2004, #"Population" = 737],
					        [#"Ethnic geoup" = "56.627314, 29.549196", #"Year" = 2001, #"Population" = 886],
					        [#"Ethnic geoup" = "59.857715, 95.781358", #"Year" = 2014, #"Population" = 682],
					        [#"Ethnic geoup" = "-62.893356, 86.826687", #"Year" = 2017, #"Population" = 826],
					        [#"Ethnic geoup" = "-49.368089, -24.996204", #"Year" = 2023, #"Population" = 528],
					        [#"Ethnic geoup" = "29.291873, -63.610277", #"Year" = 2020, #"Population" = 949],
					        [#"Ethnic geoup" = "-19.922323, 39.76468", #"Year" = 2024, #"Population" = 211],
					        [#"Ethnic geoup" = "60.657757, 80.650969", #"Year" = 2015, #"Population" = 596],
					        [#"Ethnic geoup" = "44.062387, -146.733775", #"Year" = 2005, #"Population" = 349],
					        [#"Ethnic geoup" = "-63.455933, 153.752484", #"Year" = 2023, #"Population" = 27],
					        [#"Ethnic geoup" = "43.362917, -26.061665", #"Year" = 2011, #"Population" = 226],
					        [#"Ethnic geoup" = "72.709131, -154.79458", #"Year" = 2017, #"Population" = 526],
					        [#"Ethnic geoup" = "-12.278329, 176.906737", #"Year" = 2003, #"Population" = 61],
					        [#"Ethnic geoup" = "-40.080988, -125.431631", #"Year" = 2022, #"Population" = 205],
					        [#"Ethnic geoup" = "34.517047, -7.357733", #"Year" = 2015, #"Population" = 658],
					        [#"Ethnic geoup" = "-53.081782, 96.942252", #"Year" = 2019, #"Population" = 650],
					        [#"Ethnic geoup" = "-29.202394, -132.660826", #"Year" = 2020, #"Population" = 379],
					        [#"Ethnic geoup" = "-59.590533, 117.181953", #"Year" = 2003, #"Population" = 864],
					        [#"Ethnic geoup" = "-88.158495, 4.244363", #"Year" = 2012, #"Population" = 644],
					        [#"Ethnic geoup" = "-81.245784, -172.600758", #"Year" = 2013, #"Population" = 346],
					        [#"Ethnic geoup" = "-74.920641, -108.016802", #"Year" = 2009, #"Population" = 26],
					        [#"Ethnic geoup" = "80.454486, -46.308358", #"Year" = 2012, #"Population" = 936],
					        [#"Ethnic geoup" = "-77.903869, 103.156948", #"Year" = 2017, #"Population" = 91],
					        [#"Ethnic geoup" = "10.991036, 48.550201", #"Year" = 2015, #"Population" = 332],
					        [#"Ethnic geoup" = "14.675603, 15.828043", #"Year" = 2002, #"Population" = 334],
					        [#"Ethnic geoup" = "-35.65356, 67.248018", #"Year" = 2012, #"Population" = 808],
					        [#"Ethnic geoup" = "-33.570223, 10.961761", #"Year" = 2019, #"Population" = 934],
					        [#"Ethnic geoup" = "63.834724, 48.685499", #"Year" = 2024, #"Population" = 346],
					        [#"Ethnic geoup" = "-4.888443, -163.197572", #"Year" = 2003, #"Population" = 428],
					        [#"Ethnic geoup" = "71.082364, -88.624174", #"Year" = 2024, #"Population" = 4],
					        [#"Ethnic geoup" = "-41.154017, 3.825304", #"Year" = 2020, #"Population" = 946],
					        [#"Ethnic geoup" = "-81.410345, -42.778184", #"Year" = 2003, #"Population" = 755],
					        [#"Ethnic geoup" = "-40.419751, 55.585968", #"Year" = 2014, #"Population" = 218],
					        [#"Ethnic geoup" = "69.449621, -143.086203", #"Year" = 2020, #"Population" = 271],
					        [#"Ethnic geoup" = "-7.61123, -81.11013", #"Year" = 2005, #"Population" = 803]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Ethnic geoup", type text},
					        {"Year", Int64.Type},
					        {"Population", Int64.Type}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table