table 'Population by religion'
	lineageTag: c75fccbd-2c45-4a94-b72d-0dc4a8d9eb2f

	column Religion
		dataType: string
		lineageTag: 4ac92168-1ff4-4e3f-848c-224a3da5396c
		summarizeBy: none
		sourceColumn: Religion

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 28bd9802-d856-4bfa-bda9-6292d042edea
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Population
		dataType: int64
		formatString: 0
		lineageTag: 22f1fa98-7d9b-4f9e-9b7c-b3e6eb3c4228
		summarizeBy: sum
		sourceColumn: Population

		annotation SummarizationSetBy = Automatic

	partition 'Population by religion' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Religion" = "says", #"Year" = 2000, #"Population" = 577],
					        [#"Religion" = "teenage", #"Year" = 2015, #"Population" = 75],
					        [#"Religion" = "operated", #"Year" = 2019, #"Population" = 762],
					        [#"Religion" = "reserves", #"Year" = 2002, #"Population" = 75],
					        [#"Religion" = "massive", #"Year" = 2014, #"Population" = 732],
					        [#"Religion" = "breakfast", #"Year" = 2021, #"Population" = 978],
					        [#"Religion" = "mon", #"Year" = 2018, #"Population" = 784],
					        [#"Religion" = "poster", #"Year" = 2014, #"Population" = 192],
					        [#"Religion" = "ups", #"Year" = 2012, #"Population" = 96],
					        [#"Religion" = "something", #"Year" = 2022, #"Population" = 398],
					        [#"Religion" = "links", #"Year" = 2000, #"Population" = 670],
					        [#"Religion" = "hundreds", #"Year" = 2010, #"Population" = 445],
					        [#"Religion" = "license", #"Year" = 2020, #"Population" = 150],
					        [#"Religion" = "postposted", #"Year" = 2001, #"Population" = 599],
					        [#"Religion" = "rent", #"Year" = 2013, #"Population" = 553],
					        [#"Religion" = "authors", #"Year" = 2003, #"Population" = 885],
					        [#"Religion" = "subscriber", #"Year" = 2008, #"Population" = 574],
					        [#"Religion" = "larry", #"Year" = 2022, #"Population" = 271],
					        [#"Religion" = "registry", #"Year" = 2013, #"Population" = 407],
					        [#"Religion" = "reference", #"Year" = 2012, #"Population" = 123],
					        [#"Religion" = "tube", #"Year" = 2014, #"Population" = 725],
					        [#"Religion" = "lighting", #"Year" = 2006, #"Population" = 474],
					        [#"Religion" = "farmers", #"Year" = 2011, #"Population" = 322],
					        [#"Religion" = "workshop", #"Year" = 2022, #"Population" = 409],
					        [#"Religion" = "decline", #"Year" = 2019, #"Population" = 941],
					        [#"Religion" = "continued", #"Year" = 2021, #"Population" = 410],
					        [#"Religion" = "senior", #"Year" = 2014, #"Population" = 589],
					        [#"Religion" = "dsl", #"Year" = 2011, #"Population" = 954],
					        [#"Religion" = "evaluate", #"Year" = 2008, #"Population" = 49],
					        [#"Religion" = "zum", #"Year" = 2005, #"Population" = 564],
					        [#"Religion" = "max", #"Year" = 2021, #"Population" = 124],
					        [#"Religion" = "liquid", #"Year" = 2017, #"Population" = 403],
					        [#"Religion" = "ch", #"Year" = 2018, #"Population" = 16],
					        [#"Religion" = "changes", #"Year" = 2018, #"Population" = 912],
					        [#"Religion" = "remarks", #"Year" = 2012, #"Population" = 938],
					        [#"Religion" = "dust", #"Year" = 2011, #"Population" = 489],
					        [#"Religion" = "characteristics", #"Year" = 2000, #"Population" = 717],
					        [#"Religion" = "obviously", #"Year" = 2010, #"Population" = 5],
					        [#"Religion" = "assignment", #"Year" = 2018, #"Population" = 777],
					        [#"Religion" = "conversation", #"Year" = 2024, #"Population" = 489],
					        [#"Religion" = "formation", #"Year" = 2024, #"Population" = 917],
					        [#"Religion" = "hurricane", #"Year" = 2017, #"Population" = 819],
					        [#"Religion" = "msg", #"Year" = 2017, #"Population" = 295],
					        [#"Religion" = "days", #"Year" = 2004, #"Population" = 447],
					        [#"Religion" = "designers", #"Year" = 2024, #"Population" = 155],
					        [#"Religion" = "uses", #"Year" = 2023, #"Population" = 590],
					        [#"Religion" = "reservations", #"Year" = 2012, #"Population" = 908],
					        [#"Religion" = "finger", #"Year" = 2023, #"Population" = 93],
					        [#"Religion" = "pride", #"Year" = 2012, #"Population" = 505],
					        [#"Religion" = "remember", #"Year" = 2000, #"Population" = 771],
					        [#"Religion" = "actor", #"Year" = 2013, #"Population" = 728],
					        [#"Religion" = "poker", #"Year" = 2002, #"Population" = 164],
					        [#"Religion" = "kill", #"Year" = 2005, #"Population" = 306],
					        [#"Religion" = "wide", #"Year" = 2004, #"Population" = 210],
					        [#"Religion" = "applicant", #"Year" = 2012, #"Population" = 507],
					        [#"Religion" = "queries", #"Year" = 2000, #"Population" = 660],
					        [#"Religion" = "implement", #"Year" = 2003, #"Population" = 773],
					        [#"Religion" = "teachers", #"Year" = 2014, #"Population" = 798],
					        [#"Religion" = "plan", #"Year" = 2004, #"Population" = 860],
					        [#"Religion" = "efficient", #"Year" = 2000, #"Population" = 26],
					        [#"Religion" = "earnings", #"Year" = 2010, #"Population" = 863],
					        [#"Religion" = "ratio", #"Year" = 2002, #"Population" = 164],
					        [#"Religion" = "scenes", #"Year" = 2022, #"Population" = 119],
					        [#"Religion" = "filled", #"Year" = 2021, #"Population" = 519],
					        [#"Religion" = "audience", #"Year" = 2009, #"Population" = 896],
					        [#"Religion" = "authors", #"Year" = 2012, #"Population" = 867],
					        [#"Religion" = "iowa", #"Year" = 2023, #"Population" = 903],
					        [#"Religion" = "teen", #"Year" = 2014, #"Population" = 451],
					        [#"Religion" = "latest", #"Year" = 2006, #"Population" = 430],
					        [#"Religion" = "trend", #"Year" = 2000, #"Population" = 197],
					        [#"Religion" = "practice", #"Year" = 2014, #"Population" = 477],
					        [#"Religion" = "monster", #"Year" = 2023, #"Population" = 853],
					        [#"Religion" = "union", #"Year" = 2017, #"Population" = 414],
					        [#"Religion" = "updates", #"Year" = 2013, #"Population" = 387],
					        [#"Religion" = "athletics", #"Year" = 2000, #"Population" = 288],
					        [#"Religion" = "impacts", #"Year" = 2005, #"Population" = 45],
					        [#"Religion" = "guess", #"Year" = 2018, #"Population" = 765],
					        [#"Religion" = "terminal", #"Year" = 2006, #"Population" = 685],
					        [#"Religion" = "lives", #"Year" = 2023, #"Population" = 340],
					        [#"Religion" = "injection", #"Year" = 2008, #"Population" = 344],
					        [#"Religion" = "cheese", #"Year" = 2000, #"Population" = 247],
					        [#"Religion" = "newspapers", #"Year" = 2016, #"Population" = 917],
					        [#"Religion" = "expert", #"Year" = 2016, #"Population" = 910],
					        [#"Religion" = "sing", #"Year" = 2014, #"Population" = 230],
					        [#"Religion" = "displays", #"Year" = 2024, #"Population" = 405],
					        [#"Religion" = "safe", #"Year" = 2006, #"Population" = 487],
					        [#"Religion" = "meat", #"Year" = 2005, #"Population" = 546],
					        [#"Religion" = "software", #"Year" = 2005, #"Population" = 323],
					        [#"Religion" = "cast", #"Year" = 2021, #"Population" = 209],
					        [#"Religion" = "chase", #"Year" = 2023, #"Population" = 95],
					        [#"Religion" = "cap", #"Year" = 2008, #"Population" = 870],
					        [#"Religion" = "inches", #"Year" = 2024, #"Population" = 227],
					        [#"Religion" = "cemetery", #"Year" = 2005, #"Population" = 247],
					        [#"Religion" = "formal", #"Year" = 2016, #"Population" = 453],
					        [#"Religion" = "syndrome", #"Year" = 2002, #"Population" = 299],
					        [#"Religion" = "ai", #"Year" = 2005, #"Population" = 287],
					        [#"Religion" = "drive", #"Year" = 2024, #"Population" = 214],
					        [#"Religion" = "left", #"Year" = 2009, #"Population" = 854],
					        [#"Religion" = "industrial", #"Year" = 2009, #"Population" = 631],
					        [#"Religion" = "owned", #"Year" = 2000, #"Population" = 109],
					        [#"Religion" = "dimensional", #"Year" = 2018, #"Population" = 445],
					        [#"Religion" = "usr", #"Year" = 2005, #"Population" = 659],
					        [#"Religion" = "boxes", #"Year" = 2013, #"Population" = 629],
					        [#"Religion" = "jpg", #"Year" = 2011, #"Population" = 456],
					        [#"Religion" = "educational", #"Year" = 2009, #"Population" = 76],
					        [#"Religion" = "br", #"Year" = 2022, #"Population" = 292],
					        [#"Religion" = "contribution", #"Year" = 2016, #"Population" = 907],
					        [#"Religion" = "been", #"Year" = 2004, #"Population" = 588],
					        [#"Religion" = "selling", #"Year" = 2007, #"Population" = 414],
					        [#"Religion" = "advantages", #"Year" = 2000, #"Population" = 908],
					        [#"Religion" = "clicking", #"Year" = 2020, #"Population" = 323],
					        [#"Religion" = "username", #"Year" = 2010, #"Population" = 233],
					        [#"Religion" = "rule", #"Year" = 2020, #"Population" = 55],
					        [#"Religion" = "yellow", #"Year" = 2021, #"Population" = 531],
					        [#"Religion" = "fonts", #"Year" = 2011, #"Population" = 494],
					        [#"Religion" = "broad", #"Year" = 2018, #"Population" = 621],
					        [#"Religion" = "fed", #"Year" = 2001, #"Population" = 685],
					        [#"Religion" = "cod", #"Year" = 2004, #"Population" = 390],
					        [#"Religion" = "requires", #"Year" = 2005, #"Population" = 718],
					        [#"Religion" = "may", #"Year" = 2016, #"Population" = 18],
					        [#"Religion" = "isbn", #"Year" = 2021, #"Population" = 144],
					        [#"Religion" = "jul", #"Year" = 2014, #"Population" = 40],
					        [#"Religion" = "que", #"Year" = 2005, #"Population" = 511],
					        [#"Religion" = "conclusions", #"Year" = 2004, #"Population" = 284],
					        [#"Religion" = "resort", #"Year" = 2020, #"Population" = 430],
					        [#"Religion" = "convention", #"Year" = 2016, #"Population" = 205],
					        [#"Religion" = "ends", #"Year" = 2012, #"Population" = 802],
					        [#"Religion" = "reply", #"Year" = 2000, #"Population" = 104],
					        [#"Religion" = "settlement", #"Year" = 2001, #"Population" = 93],
					        [#"Religion" = "ds", #"Year" = 2001, #"Population" = 624],
					        [#"Religion" = "consultation", #"Year" = 2016, #"Population" = 895],
					        [#"Religion" = "increase", #"Year" = 2012, #"Population" = 600],
					        [#"Religion" = "huge", #"Year" = 2017, #"Population" = 569],
					        [#"Religion" = "heard", #"Year" = 2007, #"Population" = 407],
					        [#"Religion" = "walter", #"Year" = 2024, #"Population" = 122],
					        [#"Religion" = "small", #"Year" = 2006, #"Population" = 632],
					        [#"Religion" = "motorola", #"Year" = 2021, #"Population" = 311],
					        [#"Religion" = "currency", #"Year" = 2023, #"Population" = 35],
					        [#"Religion" = "change", #"Year" = 2017, #"Population" = 460],
					        [#"Religion" = "those", #"Year" = 2017, #"Population" = 123],
					        [#"Religion" = "art", #"Year" = 2006, #"Population" = 284],
					        [#"Religion" = "affairs", #"Year" = 2002, #"Population" = 529],
					        [#"Religion" = "tell", #"Year" = 2022, #"Population" = 46],
					        [#"Religion" = "wv", #"Year" = 2005, #"Population" = 466],
					        [#"Religion" = "engineer", #"Year" = 2018, #"Population" = 922],
					        [#"Religion" = "newsletter", #"Year" = 2015, #"Population" = 308],
					        [#"Religion" = "portugal", #"Year" = 2015, #"Population" = 111],
					        [#"Religion" = "combo", #"Year" = 2020, #"Population" = 248],
					        [#"Religion" = "ave", #"Year" = 2006, #"Population" = 556],
					        [#"Religion" = "salary", #"Year" = 2000, #"Population" = 755],
					        [#"Religion" = "manchester", #"Year" = 2000, #"Population" = 646],
					        [#"Religion" = "nursing", #"Year" = 2019, #"Population" = 830],
					        [#"Religion" = "poor", #"Year" = 2014, #"Population" = 569],
					        [#"Religion" = "violence", #"Year" = 2005, #"Population" = 141],
					        [#"Religion" = "skype", #"Year" = 2014, #"Population" = 571],
					        [#"Religion" = "instruction", #"Year" = 2006, #"Population" = 666],
					        [#"Religion" = "boundary", #"Year" = 2022, #"Population" = 858],
					        [#"Religion" = "agreed", #"Year" = 2018, #"Population" = 496],
					        [#"Religion" = "large", #"Year" = 2014, #"Population" = 568],
					        [#"Religion" = "pair", #"Year" = 2010, #"Population" = 451],
					        [#"Religion" = "skill", #"Year" = 2007, #"Population" = 207],
					        [#"Religion" = "implementation", #"Year" = 2024, #"Population" = 442],
					        [#"Religion" = "felt", #"Year" = 2020, #"Population" = 789],
					        [#"Religion" = "executive", #"Year" = 2001, #"Population" = 459],
					        [#"Religion" = "ya", #"Year" = 2009, #"Population" = 921],
					        [#"Religion" = "increasing", #"Year" = 2014, #"Population" = 42],
					        [#"Religion" = "sheets", #"Year" = 2015, #"Population" = 74],
					        [#"Religion" = "premier", #"Year" = 2000, #"Population" = 817],
					        [#"Religion" = "cards", #"Year" = 2013, #"Population" = 658],
					        [#"Religion" = "words", #"Year" = 2019, #"Population" = 91],
					        [#"Religion" = "wire", #"Year" = 2017, #"Population" = 592],
					        [#"Religion" = "lot", #"Year" = 2007, #"Population" = 848],
					        [#"Religion" = "effect", #"Year" = 2015, #"Population" = 541],
					        [#"Religion" = "split", #"Year" = 2022, #"Population" = 429],
					        [#"Religion" = "yards", #"Year" = 2004, #"Population" = 101],
					        [#"Religion" = "garage", #"Year" = 2016, #"Population" = 560],
					        [#"Religion" = "dated", #"Year" = 2009, #"Population" = 534],
					        [#"Religion" = "strings", #"Year" = 2010, #"Population" = 468],
					        [#"Religion" = "pipe", #"Year" = 2008, #"Population" = 396],
					        [#"Religion" = "gm", #"Year" = 2009, #"Population" = 816],
					        [#"Religion" = "society", #"Year" = 2019, #"Population" = 750],
					        [#"Religion" = "baskets", #"Year" = 2017, #"Population" = 751],
					        [#"Religion" = "farm", #"Year" = 2009, #"Population" = 929],
					        [#"Religion" = "generation", #"Year" = 2011, #"Population" = 498],
					        [#"Religion" = "bracelet", #"Year" = 2009, #"Population" = 820],
					        [#"Religion" = "recommendation", #"Year" = 2021, #"Population" = 731],
					        [#"Religion" = "nh", #"Year" = 2004, #"Population" = 758],
					        [#"Religion" = "host", #"Year" = 2002, #"Population" = 633],
					        [#"Religion" = "liable", #"Year" = 2024, #"Population" = 612],
					        [#"Religion" = "suffering", #"Year" = 2005, #"Population" = 40],
					        [#"Religion" = "window", #"Year" = 2006, #"Population" = 661],
					        [#"Religion" = "surf", #"Year" = 2005, #"Population" = 166],
					        [#"Religion" = "licensed", #"Year" = 2019, #"Population" = 286],
					        [#"Religion" = "country", #"Year" = 2019, #"Population" = 722],
					        [#"Religion" = "ext", #"Year" = 2015, #"Population" = 232],
					        [#"Religion" = "items", #"Year" = 2001, #"Population" = 320],
					        [#"Religion" = "wisconsin", #"Year" = 2012, #"Population" = 637],
					        [#"Religion" = "absolute", #"Year" = 2007, #"Population" = 254],
					        [#"Religion" = "responses", #"Year" = 2022, #"Population" = 20],
					        [#"Religion" = "mentioned", #"Year" = 2007, #"Population" = 412],
					        [#"Religion" = "billing", #"Year" = 2017, #"Population" = 256],
					        [#"Religion" = "mrs", #"Year" = 2009, #"Population" = 684],
					        [#"Religion" = "return", #"Year" = 2019, #"Population" = 829],
					        [#"Religion" = "popular", #"Year" = 2017, #"Population" = 463],
					        [#"Religion" = "doing", #"Year" = 2009, #"Population" = 85],
					        [#"Religion" = "truth", #"Year" = 2010, #"Population" = 396],
					        [#"Religion" = "regulatory", #"Year" = 2010, #"Population" = 216],
					        [#"Religion" = "roots", #"Year" = 2014, #"Population" = 833],
					        [#"Religion" = "agenda", #"Year" = 2012, #"Population" = 634],
					        [#"Religion" = "tv", #"Year" = 2005, #"Population" = 121],
					        [#"Religion" = "cpu", #"Year" = 2014, #"Population" = 390],
					        [#"Religion" = "promotion", #"Year" = 2006, #"Population" = 16],
					        [#"Religion" = "used", #"Year" = 2000, #"Population" = 73],
					        [#"Religion" = "prevent", #"Year" = 2006, #"Population" = 651],
					        [#"Religion" = "residents", #"Year" = 2016, #"Population" = 45],
					        [#"Religion" = "steve", #"Year" = 2002, #"Population" = 908],
					        [#"Religion" = "michelle", #"Year" = 2022, #"Population" = 971],
					        [#"Religion" = "charger", #"Year" = 2005, #"Population" = 14],
					        [#"Religion" = "empire", #"Year" = 2001, #"Population" = 845],
					        [#"Religion" = "ph", #"Year" = 2023, #"Population" = 513],
					        [#"Religion" = "explains", #"Year" = 2011, #"Population" = 309],
					        [#"Religion" = "february", #"Year" = 2004, #"Population" = 140],
					        [#"Religion" = "trade", #"Year" = 2000, #"Population" = 374],
					        [#"Religion" = "wrap", #"Year" = 2023, #"Population" = 793],
					        [#"Religion" = "tv", #"Year" = 2017, #"Population" = 446],
					        [#"Religion" = "beat", #"Year" = 2021, #"Population" = 925],
					        [#"Religion" = "mobile", #"Year" = 2005, #"Population" = 804],
					        [#"Religion" = "extent", #"Year" = 2023, #"Population" = 461],
					        [#"Religion" = "eminem", #"Year" = 2023, #"Population" = 947],
					        [#"Religion" = "attack", #"Year" = 2015, #"Population" = 305],
					        [#"Religion" = "stocks", #"Year" = 2014, #"Population" = 820],
					        [#"Religion" = "singles", #"Year" = 2005, #"Population" = 168],
					        [#"Religion" = "finish", #"Year" = 2006, #"Population" = 880],
					        [#"Religion" = "serves", #"Year" = 2005, #"Population" = 922],
					        [#"Religion" = "agreed", #"Year" = 2020, #"Population" = 689],
					        [#"Religion" = "axis", #"Year" = 2007, #"Population" = 245],
					        [#"Religion" = "improve", #"Year" = 2008, #"Population" = 821],
					        [#"Religion" = "distance", #"Year" = 2020, #"Population" = 586],
					        [#"Religion" = "margaret", #"Year" = 2019, #"Population" = 227],
					        [#"Religion" = "mood", #"Year" = 2000, #"Population" = 866],
					        [#"Religion" = "jewish", #"Year" = 2006, #"Population" = 140],
					        [#"Religion" = "phones", #"Year" = 2004, #"Population" = 224],
					        [#"Religion" = "clearance", #"Year" = 2020, #"Population" = 31],
					        [#"Religion" = "noticed", #"Year" = 2021, #"Population" = 768],
					        [#"Religion" = "constructed", #"Year" = 2008, #"Population" = 93],
					        [#"Religion" = "owners", #"Year" = 2010, #"Population" = 756],
					        [#"Religion" = "comply", #"Year" = 2001, #"Population" = 844],
					        [#"Religion" = "previous", #"Year" = 2001, #"Population" = 953],
					        [#"Religion" = "auctions", #"Year" = 2006, #"Population" = 536],
					        [#"Religion" = "term", #"Year" = 2022, #"Population" = 760],
					        [#"Religion" = "kenya", #"Year" = 2003, #"Population" = 275],
					        [#"Religion" = "assistant", #"Year" = 2019, #"Population" = 203],
					        [#"Religion" = "pee", #"Year" = 2014, #"Population" = 672],
					        [#"Religion" = "def", #"Year" = 2006, #"Population" = 599],
					        [#"Religion" = "conclusions", #"Year" = 2005, #"Population" = 528],
					        [#"Religion" = "carry", #"Year" = 2016, #"Population" = 300],
					        [#"Religion" = "wow", #"Year" = 2016, #"Population" = 501],
					        [#"Religion" = "characters", #"Year" = 2014, #"Population" = 375],
					        [#"Religion" = "conclusion", #"Year" = 2003, #"Population" = 373],
					        [#"Religion" = "def", #"Year" = 2021, #"Population" = 611],
					        [#"Religion" = "motion", #"Year" = 2014, #"Population" = 136],
					        [#"Religion" = "increased", #"Year" = 2000, #"Population" = 835],
					        [#"Religion" = "pass", #"Year" = 2000, #"Population" = 368],
					        [#"Religion" = "independence", #"Year" = 2013, #"Population" = 604],
					        [#"Religion" = "stamps", #"Year" = 2010, #"Population" = 401],
					        [#"Religion" = "javascript", #"Year" = 2011, #"Population" = 864],
					        [#"Religion" = "fax", #"Year" = 2007, #"Population" = 258],
					        [#"Religion" = "discussed", #"Year" = 2013, #"Population" = 734],
					        [#"Religion" = "estimated", #"Year" = 2016, #"Population" = 817],
					        [#"Religion" = "linked", #"Year" = 2020, #"Population" = 530],
					        [#"Religion" = "variation", #"Year" = 2013, #"Population" = 660],
					        [#"Religion" = "stores", #"Year" = 2003, #"Population" = 987],
					        [#"Religion" = "transformation", #"Year" = 2011, #"Population" = 31],
					        [#"Religion" = "policy", #"Year" = 2000, #"Population" = 898],
					        [#"Religion" = "old", #"Year" = 2015, #"Population" = 220],
					        [#"Religion" = "keeps", #"Year" = 2010, #"Population" = 668],
					        [#"Religion" = "radiation", #"Year" = 2020, #"Population" = 53],
					        [#"Religion" = "smoking", #"Year" = 2008, #"Population" = 381],
					        [#"Religion" = "dependent", #"Year" = 2024, #"Population" = 68],
					        [#"Religion" = "domains", #"Year" = 2015, #"Population" = 747],
					        [#"Religion" = "motor", #"Year" = 2000, #"Population" = 384],
					        [#"Religion" = "jason", #"Year" = 2002, #"Population" = 209],
					        [#"Religion" = "genuine", #"Year" = 2001, #"Population" = 706],
					        [#"Religion" = "county", #"Year" = 2004, #"Population" = 137],
					        [#"Religion" = "variable", #"Year" = 2022, #"Population" = 427],
					        [#"Religion" = "western", #"Year" = 2006, #"Population" = 701],
					        [#"Religion" = "meters", #"Year" = 2004, #"Population" = 331],
					        [#"Religion" = "let", #"Year" = 2019, #"Population" = 771],
					        [#"Religion" = "edward", #"Year" = 2001, #"Population" = 42],
					        [#"Religion" = "bikes", #"Year" = 2003, #"Population" = 611],
					        [#"Religion" = "worse", #"Year" = 2005, #"Population" = 595],
					        [#"Religion" = "alternate", #"Year" = 2003, #"Population" = 305],
					        [#"Religion" = "request", #"Year" = 2020, #"Population" = 485],
					        [#"Religion" = "drug", #"Year" = 2004, #"Population" = 21],
					        [#"Religion" = "worship", #"Year" = 2023, #"Population" = 885],
					        [#"Religion" = "underground", #"Year" = 2020, #"Population" = 587],
					        [#"Religion" = "suddenly", #"Year" = 2007, #"Population" = 303],
					        [#"Religion" = "who", #"Year" = 2006, #"Population" = 67],
					        [#"Religion" = "shoes", #"Year" = 2001, #"Population" = 161],
					        [#"Religion" = "administrators", #"Year" = 2024, #"Population" = 970],
					        [#"Religion" = "grass", #"Year" = 2009, #"Population" = 467],
					        [#"Religion" = "tx", #"Year" = 2005, #"Population" = 168],
					        [#"Religion" = "vietnam", #"Year" = 2017, #"Population" = 129],
					        [#"Religion" = "excellent", #"Year" = 2010, #"Population" = 129],
					        [#"Religion" = "hewlett", #"Year" = 2024, #"Population" = 975],
					        [#"Religion" = "bridge", #"Year" = 2002, #"Population" = 331],
					        [#"Religion" = "area", #"Year" = 2023, #"Population" = 279],
					        [#"Religion" = "consider", #"Year" = 2023, #"Population" = 623],
					        [#"Religion" = "changing", #"Year" = 2022, #"Population" = 983],
					        [#"Religion" = "researchers", #"Year" = 2009, #"Population" = 804],
					        [#"Religion" = "jp", #"Year" = 2015, #"Population" = 298],
					        [#"Religion" = "error", #"Year" = 2020, #"Population" = 373],
					        [#"Religion" = "displays", #"Year" = 2015, #"Population" = 439],
					        [#"Religion" = "campaign", #"Year" = 2017, #"Population" = 626],
					        [#"Religion" = "rica", #"Year" = 2020, #"Population" = 674],
					        [#"Religion" = "hear", #"Year" = 2019, #"Population" = 450],
					        [#"Religion" = "ea", #"Year" = 2008, #"Population" = 417],
					        [#"Religion" = "junior", #"Year" = 2009, #"Population" = 817],
					        [#"Religion" = "comfortable", #"Year" = 2013, #"Population" = 163],
					        [#"Religion" = "circuit", #"Year" = 2018, #"Population" = 700],
					        [#"Religion" = "rw", #"Year" = 2002, #"Population" = 899],
					        [#"Religion" = "techniques", #"Year" = 2000, #"Population" = 28],
					        [#"Religion" = "carried", #"Year" = 2024, #"Population" = 177],
					        [#"Religion" = "extensions", #"Year" = 2002, #"Population" = 708],
					        [#"Religion" = "highest", #"Year" = 2006, #"Population" = 163],
					        [#"Religion" = "pin", #"Year" = 2019, #"Population" = 774],
					        [#"Religion" = "bunch", #"Year" = 2014, #"Population" = 789],
					        [#"Religion" = "facility", #"Year" = 2010, #"Population" = 856],
					        [#"Religion" = "orchestra", #"Year" = 2005, #"Population" = 836],
					        [#"Religion" = "cassette", #"Year" = 2024, #"Population" = 996],
					        [#"Religion" = "client", #"Year" = 2016, #"Population" = 173],
					        [#"Religion" = "classic", #"Year" = 2000, #"Population" = 932],
					        [#"Religion" = "rpm", #"Year" = 2021, #"Population" = 389],
					        [#"Religion" = "evening", #"Year" = 2022, #"Population" = 321],
					        [#"Religion" = "fed", #"Year" = 2014, #"Population" = 61],
					        [#"Religion" = "cinema", #"Year" = 2019, #"Population" = 204],
					        [#"Religion" = "decision", #"Year" = 2014, #"Population" = 414],
					        [#"Religion" = "seem", #"Year" = 2007, #"Population" = 841],
					        [#"Religion" = "send", #"Year" = 2011, #"Population" = 267],
					        [#"Religion" = "detected", #"Year" = 2018, #"Population" = 985],
					        [#"Religion" = "creates", #"Year" = 2014, #"Population" = 603],
					        [#"Religion" = "great", #"Year" = 2009, #"Population" = 438],
					        [#"Religion" = "organic", #"Year" = 2009, #"Population" = 175],
					        [#"Religion" = "instantly", #"Year" = 2020, #"Population" = 941],
					        [#"Religion" = "sql", #"Year" = 2018, #"Population" = 865],
					        [#"Religion" = "attacks", #"Year" = 2016, #"Population" = 460],
					        [#"Religion" = "largely", #"Year" = 2023, #"Population" = 974],
					        [#"Religion" = "songs", #"Year" = 2004, #"Population" = 751],
					        [#"Religion" = "pics", #"Year" = 2001, #"Population" = 992],
					        [#"Religion" = "news", #"Year" = 2009, #"Population" = 875],
					        [#"Religion" = "protective", #"Year" = 2000, #"Population" = 725],
					        [#"Religion" = "entry", #"Year" = 2006, #"Population" = 141],
					        [#"Religion" = "systems", #"Year" = 2003, #"Population" = 886],
					        [#"Religion" = "grade", #"Year" = 2009, #"Population" = 358],
					        [#"Religion" = "battle", #"Year" = 2000, #"Population" = 10],
					        [#"Religion" = "relationships", #"Year" = 2017, #"Population" = 399],
					        [#"Religion" = "sin", #"Year" = 2013, #"Population" = 401],
					        [#"Religion" = "blade", #"Year" = 2000, #"Population" = 754],
					        [#"Religion" = "due", #"Year" = 2002, #"Population" = 876],
					        [#"Religion" = "final", #"Year" = 2003, #"Population" = 100],
					        [#"Religion" = "if", #"Year" = 2015, #"Population" = 187],
					        [#"Religion" = "hockey", #"Year" = 2022, #"Population" = 868],
					        [#"Religion" = "window", #"Year" = 2004, #"Population" = 325],
					        [#"Religion" = "hs", #"Year" = 2021, #"Population" = 820],
					        [#"Religion" = "crisis", #"Year" = 2024, #"Population" = 331],
					        [#"Religion" = "adobe", #"Year" = 2011, #"Population" = 150],
					        [#"Religion" = "descriptions", #"Year" = 2005, #"Population" = 685],
					        [#"Religion" = "hell", #"Year" = 2002, #"Population" = 361],
					        [#"Religion" = "proceedings", #"Year" = 2008, #"Population" = 773],
					        [#"Religion" = "south", #"Year" = 2024, #"Population" = 508],
					        [#"Religion" = "cartoons", #"Year" = 2010, #"Population" = 69],
					        [#"Religion" = "thoughts", #"Year" = 2009, #"Population" = 834],
					        [#"Religion" = "bikini", #"Year" = 2017, #"Population" = 935],
					        [#"Religion" = "content", #"Year" = 2023, #"Population" = 782],
					        [#"Religion" = "torture", #"Year" = 2002, #"Population" = 192],
					        [#"Religion" = "risks", #"Year" = 2005, #"Population" = 780],
					        [#"Religion" = "simply", #"Year" = 2017, #"Population" = 454],
					        [#"Religion" = "reserves", #"Year" = 2006, #"Population" = 927],
					        [#"Religion" = "disability", #"Year" = 2013, #"Population" = 398],
					        [#"Religion" = "mix", #"Year" = 2006, #"Population" = 414],
					        [#"Religion" = "donald", #"Year" = 2019, #"Population" = 467],
					        [#"Religion" = "broker", #"Year" = 2013, #"Population" = 981],
					        [#"Religion" = "stability", #"Year" = 2023, #"Population" = 403],
					        [#"Religion" = "conditioning", #"Year" = 2003, #"Population" = 71],
					        [#"Religion" = "junior", #"Year" = 2000, #"Population" = 39],
					        [#"Religion" = "barbara", #"Year" = 2020, #"Population" = 412],
					        [#"Religion" = "cars", #"Year" = 2013, #"Population" = 906],
					        [#"Religion" = "bidder", #"Year" = 2005, #"Population" = 867],
					        [#"Religion" = "votes", #"Year" = 2023, #"Population" = 638],
					        [#"Religion" = "whether", #"Year" = 2004, #"Population" = 950],
					        [#"Religion" = "david", #"Year" = 2017, #"Population" = 85],
					        [#"Religion" = "earn", #"Year" = 2012, #"Population" = 302],
					        [#"Religion" = "familiar", #"Year" = 2019, #"Population" = 598],
					        [#"Religion" = "knight", #"Year" = 2009, #"Population" = 841],
					        [#"Religion" = "savings", #"Year" = 2002, #"Population" = 941],
					        [#"Religion" = "named", #"Year" = 2001, #"Population" = 651],
					        [#"Religion" = "thomas", #"Year" = 2005, #"Population" = 305],
					        [#"Religion" = "texts", #"Year" = 2005, #"Population" = 509],
					        [#"Religion" = "angels", #"Year" = 2018, #"Population" = 131],
					        [#"Religion" = "policy", #"Year" = 2006, #"Population" = 994],
					        [#"Religion" = "month", #"Year" = 2006, #"Population" = 736],
					        [#"Religion" = "buying", #"Year" = 2011, #"Population" = 260],
					        [#"Religion" = "room", #"Year" = 2008, #"Population" = 586],
					        [#"Religion" = "directors", #"Year" = 2000, #"Population" = 759],
					        [#"Religion" = "replies", #"Year" = 2016, #"Population" = 845],
					        [#"Religion" = "sl", #"Year" = 2016, #"Population" = 645],
					        [#"Religion" = "grow", #"Year" = 2005, #"Population" = 286],
					        [#"Religion" = "mexico", #"Year" = 2022, #"Population" = 436],
					        [#"Religion" = "coupons", #"Year" = 2021, #"Population" = 478],
					        [#"Religion" = "checks", #"Year" = 2016, #"Population" = 816],
					        [#"Religion" = "list", #"Year" = 2002, #"Population" = 187],
					        [#"Religion" = "preferred", #"Year" = 2011, #"Population" = 10],
					        [#"Religion" = "sampling", #"Year" = 2014, #"Population" = 719],
					        [#"Religion" = "raise", #"Year" = 2024, #"Population" = 512],
					        [#"Religion" = "frank", #"Year" = 2004, #"Population" = 639],
					        [#"Religion" = "wi", #"Year" = 2012, #"Population" = 47],
					        [#"Religion" = "pizza", #"Year" = 2019, #"Population" = 659],
					        [#"Religion" = "country", #"Year" = 2014, #"Population" = 514],
					        [#"Religion" = "cleveland", #"Year" = 2014, #"Population" = 788],
					        [#"Religion" = "artwork", #"Year" = 2021, #"Population" = 480],
					        [#"Religion" = "bound", #"Year" = 2002, #"Population" = 492],
					        [#"Religion" = "of", #"Year" = 2018, #"Population" = 702],
					        [#"Religion" = "regions", #"Year" = 2010, #"Population" = 498],
					        [#"Religion" = "shared", #"Year" = 2003, #"Population" = 233],
					        [#"Religion" = "sports", #"Year" = 2007, #"Population" = 929],
					        [#"Religion" = "survey", #"Year" = 2024, #"Population" = 699],
					        [#"Religion" = "utc", #"Year" = 2000, #"Population" = 90],
					        [#"Religion" = "tvs", #"Year" = 2013, #"Population" = 572],
					        [#"Religion" = "illinois", #"Year" = 2018, #"Population" = 239],
					        [#"Religion" = "wage", #"Year" = 2007, #"Population" = 991],
					        [#"Religion" = "inside", #"Year" = 2018, #"Population" = 554],
					        [#"Religion" = "attraction", #"Year" = 2012, #"Population" = 318],
					        [#"Religion" = "paris", #"Year" = 2001, #"Population" = 648],
					        [#"Religion" = "notebook", #"Year" = 2008, #"Population" = 233],
					        [#"Religion" = "gender", #"Year" = 2009, #"Population" = 33],
					        [#"Religion" = "proceed", #"Year" = 2018, #"Population" = 898],
					        [#"Religion" = "arc", #"Year" = 2016, #"Population" = 400],
					        [#"Religion" = "korea", #"Year" = 2016, #"Population" = 872],
					        [#"Religion" = "paintings", #"Year" = 2011, #"Population" = 370],
					        [#"Religion" = "zone", #"Year" = 2016, #"Population" = 195],
					        [#"Religion" = "covered", #"Year" = 2021, #"Population" = 786],
					        [#"Religion" = "drop", #"Year" = 2015, #"Population" = 210],
					        [#"Religion" = "register", #"Year" = 2008, #"Population" = 19],
					        [#"Religion" = "prepare", #"Year" = 2002, #"Population" = 565],
					        [#"Religion" = "vermont", #"Year" = 2004, #"Population" = 471],
					        [#"Religion" = "garage", #"Year" = 2004, #"Population" = 240],
					        [#"Religion" = "performing", #"Year" = 2012, #"Population" = 674],
					        [#"Religion" = "liquid", #"Year" = 2001, #"Population" = 560],
					        [#"Religion" = "begins", #"Year" = 2024, #"Population" = 157],
					        [#"Religion" = "router", #"Year" = 2023, #"Population" = 114],
					        [#"Religion" = "success", #"Year" = 2001, #"Population" = 947],
					        [#"Religion" = "parents", #"Year" = 2017, #"Population" = 432],
					        [#"Religion" = "plays", #"Year" = 2001, #"Population" = 794],
					        [#"Religion" = "walking", #"Year" = 2013, #"Population" = 874],
					        [#"Religion" = "atom", #"Year" = 2015, #"Population" = 21],
					        [#"Religion" = "dean", #"Year" = 2014, #"Population" = 596],
					        [#"Religion" = "hope", #"Year" = 2003, #"Population" = 207],
					        [#"Religion" = "steve", #"Year" = 2008, #"Population" = 529],
					        [#"Religion" = "upgrade", #"Year" = 2003, #"Population" = 835],
					        [#"Religion" = "son", #"Year" = 2002, #"Population" = 689],
					        [#"Religion" = "milk", #"Year" = 2012, #"Population" = 757],
					        [#"Religion" = "russian", #"Year" = 2011, #"Population" = 221],
					        [#"Religion" = "matching", #"Year" = 2018, #"Population" = 759],
					        [#"Religion" = "site", #"Year" = 2000, #"Population" = 477],
					        [#"Religion" = "mit", #"Year" = 2019, #"Population" = 6],
					        [#"Religion" = "liked", #"Year" = 2006, #"Population" = 855],
					        [#"Religion" = "federation", #"Year" = 2005, #"Population" = 338],
					        [#"Religion" = "founded", #"Year" = 2008, #"Population" = 100],
					        [#"Religion" = "passion", #"Year" = 2021, #"Population" = 170],
					        [#"Religion" = "note", #"Year" = 2016, #"Population" = 298],
					        [#"Religion" = "electrical", #"Year" = 2022, #"Population" = 939],
					        [#"Religion" = "feeding", #"Year" = 2017, #"Population" = 770],
					        [#"Religion" = "attitude", #"Year" = 2020, #"Population" = 428],
					        [#"Religion" = "amazing", #"Year" = 2006, #"Population" = 257],
					        [#"Religion" = "geographic", #"Year" = 2021, #"Population" = 795],
					        [#"Religion" = "motion", #"Year" = 2017, #"Population" = 875],
					        [#"Religion" = "bedrooms", #"Year" = 2013, #"Population" = 471],
					        [#"Religion" = "made", #"Year" = 2001, #"Population" = 671],
					        [#"Religion" = "stability", #"Year" = 2002, #"Population" = 540],
					        [#"Religion" = "behind", #"Year" = 2010, #"Population" = 530],
					        [#"Religion" = "stage", #"Year" = 2005, #"Population" = 592],
					        [#"Religion" = "cd", #"Year" = 2016, #"Population" = 440],
					        [#"Religion" = "fe", #"Year" = 2004, #"Population" = 608],
					        [#"Religion" = "conclusion", #"Year" = 2004, #"Population" = 312],
					        [#"Religion" = "holes", #"Year" = 2010, #"Population" = 652],
					        [#"Religion" = "which", #"Year" = 2000, #"Population" = 720],
					        [#"Religion" = "our", #"Year" = 2024, #"Population" = 95],
					        [#"Religion" = "remained", #"Year" = 2005, #"Population" = 885],
					        [#"Religion" = "sat", #"Year" = 2016, #"Population" = 796],
					        [#"Religion" = "gateway", #"Year" = 2014, #"Population" = 197],
					        [#"Religion" = "phentermine", #"Year" = 2024, #"Population" = 165],
					        [#"Religion" = "trailers", #"Year" = 2022, #"Population" = 704],
					        [#"Religion" = "princess", #"Year" = 2009, #"Population" = 475],
					        [#"Religion" = "getting", #"Year" = 2005, #"Population" = 549],
					        [#"Religion" = "ae", #"Year" = 2002, #"Population" = 156],
					        [#"Religion" = "ff", #"Year" = 2013, #"Population" = 632],
					        [#"Religion" = "capable", #"Year" = 2008, #"Population" = 537],
					        [#"Religion" = "question", #"Year" = 2021, #"Population" = 27],
					        [#"Religion" = "municipal", #"Year" = 2022, #"Population" = 328],
					        [#"Religion" = "tags", #"Year" = 2023, #"Population" = 861]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Religion", type text},
					        {"Year", Int64.Type},
					        {"Population", Int64.Type}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table