table 'Orders+ (Sample - Superstore)'
	lineageTag: e41af8fb-c591-411e-921a-5213799ee2bb

	measure 'Previous year' = Previous year = VAR paramDate = SELECTEDVALUE('Select date'[Display As]) VAR cutoffDate = IF( NOT(ISBLANK(paramDate)), DATE(YEAR(paramDate) - 1, MONTH(paramDate), DAY(paramDate)), BLANK() ) VAR lowerBound = IF( NOT(ISBLANK(paramDate)), IF( MONTH(paramDate) <= 3, DATE(YEAR(paramDate) - 2, 4, 1), BLANK() ), BLANK() ) RETURN IF( NOT(ISBLANK(paramDate)) && NOT(ISBLANK(lowerBound)), CALCULATE( SUM('Orders+ (Sample - Superstore)'[Sales]), 'Orders+ (Sample - Superstore)'[Order Date] <= cutoffDate, 'Orders+ (Sample - Superstore)'[Order Date] >= lowerBound ), BLANK() )
		formatString: 0
		lineageTag: 07370d3f-ce44-4a99-96b9-c6f8187b77fa

	measure Calculation1 = Calculation1 = VAR hasCY = NOT(ISBLANK('Orders+ (Sample - Superstore)'[Current year])) VAR hasPY = NOT(ISBLANK('Orders+ (Sample - Superstore)'[Previous year])) RETURN hasCY || hasPY
		lineageTag: af3a59fc-1b9a-4ad6-9784-706c4524bbb4

	measure 'Current year' = Current year = VAR flag = 'Orders+ (Sample - Superstore)'[Dynamic Measure values with YTD/MTD/QTD] RETURN IF(flag, SUM('Orders+ (Sample - Superstore)'[Sales]))
		formatString: 0
		lineageTag: ec54e819-a2f5-4cd4-9263-95b7ee09d7b0

	measure 'Dynamic years' = Dynamic years = SELECTEDVALUE('Select date'[Display As])
		lineageTag: a3601158-39bd-4336-81c5-64fde90f023d

	measure MTD = VAR orderDate = SELECTEDVALUE('Orders+ (Sample - Superstore)'[Order Date]) VAR selDate = SELECTEDVALUE('Select date'[Display As]) RETURN orderDate <= selDate && MONTH(orderDate) = MONTH(selDate) && YEAR(orderDate) = YEAR(selDate)
		lineageTag: db28d9af-67bf-477c-807e-d72448e7aefd

	measure 'Dynamic Measure values with YTD/MTD/QTD' = VAR selPeriod = SELECTEDVALUE('Select Period'[Display As]) VAR selDate = SELECTEDVALUE('Select date'[Display As]) VAR orderDate = SELECTEDVALUE('Orders+ (Sample - Superstore)'[Order Date]) VAR startDate = IF( MONTH(selDate) <= 3, DATE(YEAR(selDate) - 1, 4, 1), IF( MONTH(selDate) >= 4 && YEAR(selDate) = YEAR(orderDate), DATE(YEAR(selDate), 4, 1), BLANK() ) ) VAR isYTDWindow = orderDate <= selDate && NOT(ISBLANK(startDate)) && orderDate >= startDate RETURN SWITCH( TRUE(), selPeriod = 1, isYTDWindow, selPeriod = 2, [MTD], selPeriod = 3, 'Orders+ (Sample - Superstore)'[QTD], BLANK() )
		lineageTag: aaadf981-63d5-4391-8018-ab394c1f20bf

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 930e6fcc-dbfa-43f7-bb11-f5b151b228c0
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: a968c105-4170-4a3a-9635-811a3a418093
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: datetime
		lineageTag: 49b18612-9236-4d87-abd2-7232f39ea6c9
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: datetime
		lineageTag: e6329cb8-74e8-4260-99aa-fe8544daae59
		summarizeBy: none
		sourceColumn: 'Ship Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 777aa1a0-30f9-4ea4-b735-082a17d81f98
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 21a93937-bf8e-4fe6-bc2f-60efe142ed40
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 3ecf6082-4e72-4843-8683-debdf5a13495
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: bd994653-6b39-42a7-b486-c913577f0d1d
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Country/Region'
		dataType: string
		lineageTag: 4145af58-f960-4eaa-89ce-21fc2bd2f0f2
		summarizeBy: none
		sourceColumn: 'Country/Region'

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 567d6a4d-1a9f-4f1c-b4ef-e0515b6d7a11
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 50dfa7b1-e069-486b-830e-136994aa4901
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 56f35ad3-f327-47cc-9afa-e9dd7c603428
		summarizeBy: sum
		sourceColumn: 'Postal Code'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: d5cd3852-1c4e-4e26-81cb-bb3ae607e6b4
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 82568f5b-6be8-4e8a-905c-72d694ca4cc0
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 2d633014-6d41-48b5-a0ea-a5edf45a1bf2
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: 5a459d4e-82f2-401c-b3bb-c3378f510ca4
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: ea105c81-9610-41de-afb6-4fc1446237d8
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: General Number
		lineageTag: d47dffb8-5236-46c9-ab2f-65ed315decd9
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 2d9eae21-d98e-4375-b833-935f533cc5d2
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: General Number
		lineageTag: 7f65f55d-f589-48a6-bb83-54980770a315
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		formatString: General Number
		lineageTag: bd70623a-fdee-4235-83fe-f13e64260f71
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QTD = VAR orderDate = 'Orders+ (Sample - Superstore)'[Order Date] VAR dynDate = 'Orders+ (Sample - Superstore)'[Dynamic years] RETURN orderDate <= dynDate && QUARTER(orderDate) = QUARTER(dynDate) && YEAR(orderDate) = YEAR(dynDate)
		lineageTag: 4b140892-9a89-4afb-83b2-38c363a17e72
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Orders+ (Sample - Superstore)' = m
		mode: import
		source =
				let
					    Source = Csv.Document(
					        File.Contents("/"),
					        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
					    ),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
					in
					    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table