table 'Top N Country'
	lineageTag: a75b71c9-96cd-4239-8a9c-89a4df6dac3d

	measure 'Top N Country Value' = SELECTEDVALUE('Top N Country'[Top N Country], 1)
		lineageTag: 1cacb8d9-62bc-44dc-af9b-2f79434d41fb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Top N Country'
		dataType: double
		formatString: 0
		lineageTag: 2217c881-2b78-43c5-abc4-d7f7ca152cfb
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Top N Country' = calculated
		mode: import
		source = GENERATESERIES(1, 50)

	annotation PBI_Id = d74578add078438cab3494ce196bff10

