table 'Customer ID (Excel-to-Tableau-Data)'
	lineageTag: 32e1bae3-2ee1-4371-bfa1-83c32a919202

	column 'Customer ID'
		dataType: string
		lineageTag: b1a2bb72-6e37-4f80-b88c-90e2fbf9c95b
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 4bcc93f1-7ce8-4126-8dc4-32a07ff3bcb6
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: string
		lineageTag: 077e080a-73e1-4e42-a438-5b0313eec138
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 7ef31a3b-15d3-4625-a5c7-8f0145d696d5
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	partition 'Customer ID (Excel-to-Tableau-Data)' = m
		mode: import
		source =
				let
					    Source = Csv.Document(
					        File.Contents("https://saastestlatest.blob.core.windows.net/saas-test-reports/Customer%20ID%20%28Excel-to-Tableau-Data%29.csv?se=2025-10-31T22%3A15%3A19Z&sp=r&sv=2025-11-05&sr=b&sig=P9CgS5GVS8q2EjE8o6qiY%2B9LRP27C%2B6u8Q9NRo4olr0%3D"),
					        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
					    ),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer ID", type text}, {"Gender", type text}, {"Age", type text}, {"State", type text}})
					in
					    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

