table 'Top Customers'
	lineageTag: 01aef9d5-56bf-425f-b8de-362f79f39594

	measure 'Top Customers Value' = SELECTEDVALUE('Top Customers'[Top Customers], 5)
		lineageTag: 5e1e8a4c-606e-4c96-bb0d-4b61f3aa5f4b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Top Customers'
		dataType: double
		formatString: 0
		lineageTag: 62a63d30-8bc7-4229-a492-aebf3fc37373
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Top Customers' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_Id = 8ed6bf0a5b8d436b97e5cc2943853b2f

