table 'Min Sales Threshold'
	lineageTag: 2d21462c-435b-4009-bce9-be31ad3b5ec4

	measure 'Min Sales Threshold Value' = SELECTEDVALUE('Min Sales Threshold'[Min Sales Threshold], 0.0)
		lineageTag: bac0c344-0bea-43bf-a47e-052394a30006

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Min Sales Threshold'
		dataType: double
		formatString: 0
		lineageTag: 7e38c44f-b6d0-4255-8e07-3581f11b67eb
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Min Sales Threshold' = calculated
		mode: import
		source = GENERATESERIES(0.0, 200000.0, 100.0)

	annotation PBI_Id = 512e3b4753644ec4bb4cab416df30f26

