table 'order_items+'
	lineageTag: c67d80e3-6e0b-4f42-a944-6e921284ad83

	measure 'Profit Margin (%)' = VAR totalLineTotal = SUM('order_items+'[LineTotal]) VAR totalLineCost = SUM('order_items+'[LineCost]) RETURN IF(totalLineTotal = 0, 0, (totalLineTotal - totalLineCost) / totalLineTotal)
		formatString: 0
		lineageTag: a3f5292a-d6d5-4c0d-9b13-b358145f9d60

	measure 'Order Count' = DISTINCTCOUNT('order_items+'[OrderID])
		formatString: 0
		lineageTag: 92bb4615-dc54-46de-9039-2e60ea7a6ae1

	measure 'Average Order Value (AOV)' = SUM('order_items+'[LineTotal]) / DISTINCTCOUNT('order_items+'[OrderID])
		formatString: 0
		lineageTag: aabfd493-5402-4365-8f78-4db05cbe5e85

	measure 'Sales after Discount' = SUM('order_items+'[LineTotal])
		formatString: 0
		lineageTag: 7308afaf-9e24-493c-8c55-284ef4d0565b

	measure Customer_Lifetime_Sales = CALCULATE( SUM('order_items+'[LineTotal]), ALLEXCEPT('order_items+', 'order_items+'[CustomerID]) )
		formatString: 0
		lineageTag: 9ba8bbf8-7359-4f82-9dcd-59137b50cbf9

	measure 'Top N Products Flag' = VAR RankValue = RANKX(ALLSELECTED('order_items+'), CALCULATE(SUM('order_items+'[LineTotal])), , DESC) RETURN RankValue <= SELECTEDVALUE('Top N Products'[Display As])
		lineageTag: f4c68866-0fb5-4b53-bea9-fbcbf7a794f4

	measure 'Selected Year Filter' = YEAR('order_items+'[OrderDate]) = SELECTEDVALUE('Select Year'[Display As])
		lineageTag: 5118fd24-584d-430b-9c79-39382e8b09ea

	measure 'Products Above Threshold' = VAR FixedProductSales = CALCULATE( SUM('order_items+'[LineTotal]), ALLEXCEPT('order_items+', 'order_items+'[ProductID]) ) VAR Threshold = SELECTEDVALUE('Min Sales Threshold'[Display As]) RETURN FixedProductSales >= Threshold
		lineageTag: ef42d465-46ca-4efa-8da6-ce2fc25285d3

	measure 'High Discount Items' = 'order_items+'[DiscountPct] >= SELECTEDVALUE('Discount Threshold %'[Display As])
		lineageTag: f1ab1383-c688-4b1c-a745-126e73d03a95

	column OrderID
		dataType: string
		lineageTag: eefdef09-e07f-4c72-abae-b2e5091e1562
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: string
		lineageTag: 0c7a1d4c-4c97-413e-bd3c-3ddf424f1ccf
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: datetime
		lineageTag: 5132471a-99eb-412b-a0bf-1aafdff69697
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

	column OrderStatus
		dataType: string
		lineageTag: 3afea34e-632e-43a5-9024-acd14af4ad88
		summarizeBy: none
		sourceColumn: OrderStatus

		annotation SummarizationSetBy = Automatic

	column CouponCode
		dataType: string
		lineageTag: 15c53a00-ada1-4332-8da8-f7e3a9e2386f
		summarizeBy: none
		sourceColumn: CouponCode

		annotation SummarizationSetBy = Automatic

	column 'ProductID 1'
		dataType: string
		lineageTag: 739a7cdd-7fca-419f-9b09-039324d13629
		summarizeBy: none
		sourceColumn: 'ProductID 1'

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 8e1409a8-72ef-4d6f-8a33-8559bc438976
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: cff2262a-4fa5-4b27-8876-690fabc8d95e
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column BasePrice
		dataType: double
		formatString: General Number
		lineageTag: d8943225-1faa-4d99-a812-4a178be4a706
		summarizeBy: sum
		sourceColumn: BasePrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cost
		dataType: double
		formatString: General Number
		lineageTag: 0b1b530b-88ff-41e2-be03-1f786bb59a12
		summarizeBy: sum
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ShipmentID
		dataType: string
		lineageTag: bca005e0-ccc8-45ea-b608-e574e37a34b8
		summarizeBy: none
		sourceColumn: ShipmentID

		annotation SummarizationSetBy = Automatic

	column 'OrderID 2'
		dataType: string
		lineageTag: 1fda9595-45fa-4e24-94eb-b3688e6d9de8
		summarizeBy: none
		sourceColumn: 'OrderID 2'

		annotation SummarizationSetBy = Automatic

	column ShipDate
		dataType: datetime
		lineageTag: 1f09ba77-a1da-49b9-b36c-652c39b53c18
		summarizeBy: none
		sourceColumn: ShipDate

		annotation SummarizationSetBy = Automatic

	column DaysToShip
		dataType: int64
		formatString: 0
		lineageTag: ebe1957f-d2ca-421a-a044-9c3e2e0ece30
		summarizeBy: sum
		sourceColumn: DaysToShip

		annotation SummarizationSetBy = Automatic

	column Carrier
		dataType: string
		lineageTag: 206c8b39-678a-44c4-9f1b-36fe9a363a0b
		summarizeBy: none
		sourceColumn: Carrier

		annotation SummarizationSetBy = Automatic

	column 'CustomerID 1'
		dataType: string
		lineageTag: c7c2c5f9-5306-4c33-8578-692717e76094
		summarizeBy: none
		sourceColumn: 'CustomerID 1'

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 6a199295-6425-4dac-81cf-4826827f3e5c
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 2c511dfa-a3d0-4e80-888c-dd46b51ec437
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 38f83bc1-9f4c-42db-a577-91070e5176d0
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 00522275-e427-437a-a927-6e7601ea79d5
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column CustomerSince
		dataType: datetime
		lineageTag: faf5793b-a815-4014-be41-d1c2fb45f8d0
		summarizeBy: none
		sourceColumn: CustomerSince

		annotation SummarizationSetBy = Automatic

	column IsReturnCustomer
		dataType: int64
		formatString: 0
		lineageTag: f1661fb3-67ed-42df-9395-e732553b4041
		summarizeBy: sum
		sourceColumn: IsReturnCustomer

		annotation SummarizationSetBy = Automatic

	column 'OrderID 1'
		dataType: string
		lineageTag: 946a03fe-ed3d-439b-a5c5-0e8897b88885
		summarizeBy: none
		sourceColumn: 'OrderID 1'

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: string
		lineageTag: 2d4afcb8-da32-4a70-8ed0-9aba62224144
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column 'Order year' = YEAR('order_items+'[OrderDate])
		formatString: 0
		lineageTag: 69491a02-8d9e-47e9-86a5-fdd3768bbd95
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Total Sales (Line-level)' = 'order_items+'[LineTotal]
		lineageTag: e8f6c469-7469-4c61-8ea6-2b5d69aa6f56
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Cost (Line-level)' = 'order_items+'[LineCost]
		lineageTag: ac427055-348d-473f-9d31-6d552f6b00ad
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Gross Profit (line)' = 'order_items+'[LineTotal] - 'order_items+'[LineCost]
		lineageTag: ebdd9d71-5253-4045-9a0a-82773bd9e5e9
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Discount Amount' = ('order_items+'[UnitPrice] * 'order_items+'[Quantity]) * ('order_items+'[DiscountPct] / 100)
		lineageTag: b7cb5f7b-fef3-4f2d-9b57-7a6302a3f743
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Days to Ship' = DATEDIFF('order_items+'[OrderDate], 'order_items+'[ShipDate], DAY)
		formatString: 0
		lineageTag: edeb4777-4c2b-4e1d-ba07-2751f6a9413b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'order_items+' = m
		mode: import
		source =
				let 
					#"Source0" = Table.NestedJoin(#"order_items.csv_order_items+", {"OrderID"}, #"order_items+_orders.csv", {"OrderID"}, "order_items+_orders.csv", JoinKind.Inner),
					#"Expand0" = Table.ExpandTableColumn(#"Source0", "order_items+_orders.csv", {"OrderID", "CustomerID", "OrderDate", "OrderStatus", "CouponCode"}, {"OrderID 1", "CustomerID", "OrderDate", "OrderStatus", "CouponCode"}),
					#"Source1" = Table.NestedJoin(#"Expand0", {"ProductID"}, #"order_items+_products.csv", {"ProductID"}, "order_items+_products.csv", JoinKind.LeftOuter),
					#"Expand1" = Table.ExpandTableColumn(#"Source1", "order_items+_products.csv", {"ProductID", "ProductName", "Category", "BasePrice", "Cost"}, {"ProductID 1", "ProductName", "Category", "BasePrice", "Cost"}),
					#"Source2" = Table.NestedJoin(#"Expand1", {"OrderID"}, #"order_items+_shipments.csv", {"OrderID"}, "order_items+_shipments.csv", JoinKind.RightOuter),
					#"Expand2" = Table.ExpandTableColumn(#"Source2", "order_items+_shipments.csv", {"ShipmentID", "OrderID", "ShipDate", "DaysToShip", "Carrier"}, {"ShipmentID", "OrderID 2", "ShipDate", "DaysToShip", "Carrier"}),
					#"Source3" = Table.NestedJoin(#"Expand2", {"CustomerID"}, #"order_items+_customers.csv", {"CustomerID"}, "order_items+_customers.csv", JoinKind.FullOuter),
					#"Expand3" = Table.ExpandTableColumn(#"Source3", "order_items+_customers.csv", {"CustomerID", "FirstName", "LastName", "Email", "City", "CustomerSince", "IsReturnCustomer"}, {"CustomerID 1", "FirstName", "LastName", "Email", "City", "CustomerSince", "IsReturnCustomer"})
					in #"Expand3"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table