table 'Top N Products'
	lineageTag: 7610794b-cf44-4cc9-bb8a-dd56d9713fca

	measure 'Top N Products Value' = SELECTEDVALUE('Top N Products'[Top N Products], 1)
		lineageTag: 5b99dc2a-a756-4a08-bfb4-a30926deb763

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Top N Products'
		dataType: double
		formatString: 0
		lineageTag: 7e8ace3c-52fc-49ed-9647-183be2f9f02c
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Top N Products' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_Id = 690df3d7ff014fdab6ba0bb6829800b2

