table 'Discount Threshold'
	lineageTag: af11a8ae-ea75-4af5-a355-5f9f60e3b805

	measure 'Discount Threshold Value' = SELECTEDVALUE('Discount Threshold'[Discount Threshold], 0.0)
		lineageTag: dbd86f79-664d-482e-8b09-d49842130e59

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Discount Threshold'
		dataType: double
		formatString: 0
		lineageTag: 3bbabc55-612e-4716-b6ad-bc685f0bcffe
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Discount Threshold' = calculated
		mode: import
		source = GENERATESERIES(0.0, 0.5)

	annotation PBI_Id = b35ba50eb5234ad29636919a42661938

