table 'Orders+ (Sample - Superstore)'
	lineageTag: c1ae7675-2dea-4969-bc15-48cb47fc37ba

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 1be8912a-f118-491e-a532-94da9153ad42
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: e34076a9-cab5-46e6-9743-57ec2fd0205f
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: datetime
		lineageTag: 85ae25cd-3978-4edb-8470-b078b809f634
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: datetime
		lineageTag: fd8ce45f-688a-4935-91bb-34c818521e77
		summarizeBy: none
		sourceColumn: 'Ship Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 7757ca4d-b7bd-4033-80e6-af8a8369cbfa
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: d9578e15-afcd-4caa-aebd-a82ccc5e6f91
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 720db2ac-cc9b-4ab7-9ab8-d4e19fffb716
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 096e5fbc-0913-4e29-9b66-f1f99cc90951
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Country/Region'
		dataType: string
		lineageTag: 16b3581d-0204-4961-a0ae-15c971d97dba
		summarizeBy: none
		sourceColumn: 'Country/Region'

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: eef56b0c-804a-4ace-b972-b814957daf86
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: ecd72214-a536-4d88-835a-f960cf4aff45
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: d441bfe6-c7c2-43c4-bd7e-e5c7afeddddc
		summarizeBy: sum
		sourceColumn: 'Postal Code'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: b388a792-1416-49ea-8476-b0171e1903d7
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 631c4e51-4048-4d57-919e-028c77d8260f
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: b95e565c-bd9d-4bea-8624-12add30e2cfc
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: f9844622-4c8d-42eb-bd54-32d180f7dd6d
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 1d760c39-29a2-49cf-baed-5c489b61b2ee
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: General Number
		lineageTag: ef25e1f5-81d0-4c07-9f54-15dbcad3f4a5
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: c2766d88-a57f-40f1-9bef-bb570b4af59e
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: General Number
		lineageTag: 772ad544-8519-43dc-adae-b7a77bf890f3
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		formatString: General Number
		lineageTag: fbd5fff1-0f76-481d-b27c-28079529acef
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Person
		dataType: string
		lineageTag: 7d5c5c69-5d24-4b3d-9bc8-4bd3a4fbb047
		summarizeBy: none
		sourceColumn: Person

		annotation SummarizationSetBy = Automatic

	column 'Region 1'
		dataType: string
		lineageTag: faa37d46-6bc7-440c-a52e-a0e74829f6a3
		summarizeBy: none
		sourceColumn: 'Region 1'

		annotation SummarizationSetBy = Automatic

	column Returned
		dataType: string
		lineageTag: 0fd31146-7f91-4ea1-8734-692e43bee29a
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID 1'
		dataType: string
		lineageTag: bc696b99-d81e-46f3-aea0-373e789732d2
		summarizeBy: none
		sourceColumn: 'Order ID 1'

		annotation SummarizationSetBy = Automatic

	partition 'Orders+ (Sample - Superstore)' = m
		mode: import
		source =
				let 
					#"Source0" = Table.NestedJoin(#"Orders_Orders+ (Sample - Superstore)", {"Region"}, #"People_Orders+ (Sample - Superstore)", {"Region"}, "People_Orders+ (Sample - Superstore)", JoinKind.Inner),
					#"Expand0" = Table.ExpandTableColumn(#"Source0", "People_Orders+ (Sample - Superstore)", {"Person", "Region"}, {"Person", "Region 1"}),
					#"Source1" = Table.NestedJoin(#"Expand0", {"Order ID"}, #"Returns_Orders+ (Sample - Superstore)", {"Order ID"}, "Returns_Orders+ (Sample - Superstore)", JoinKind.Inner),
					#"Expand1" = Table.ExpandTableColumn(#"Source1", "Returns_Orders+ (Sample - Superstore)", {"Returned", "Order ID"}, {"Returned", "Order ID 1"})
					in #"Expand1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table