table 'Minimum Hours Threshold'
	lineageTag: 0833aa78-78f6-4234-a990-7f49e059de79

	measure 'Minimum Hours Threshold Value' = SELECTEDVALUE('Minimum Hours Threshold'[Minimum Hours Threshold], 0)
		lineageTag: 15c166cf-9d4d-4d0f-a0fb-8927053f879d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Minimum Hours Threshold'
		dataType: double
		formatString: 0
		lineageTag: bcf88a23-8ea2-4fe9-abd1-2684315dacdf
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Minimum Hours Threshold' = calculated
		mode: import
		source = GENERATESERIES(0, 12, 1)

	annotation PBI_Id = aca3a16fd60a46a4a6ca012941c00a04

