table 'Target Threshold'
	lineageTag: 88626c32-a8da-4dc1-9321-2d76e7ae368e

	measure 'Target Threshold Value' = SELECTEDVALUE('Target Threshold'[Target Threshold], 0.0)
		lineageTag: b4578a70-ea93-47c9-86ff-66f6fa42e7f6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Target Threshold'
		dataType: double
		formatString: 0
		lineageTag: ef44c446-6c31-4265-906b-02eeed7eb34d
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Target Threshold' = calculated
		mode: import
		source = GENERATESERIES(0.0, 100.0, 0.5)

	annotation PBI_Id = c5a62c3f453b401697b9deff1197a8a0

