table Walmart
	lineageTag: 6e819175-7e41-4457-9994-3b562972fd2f

	column User_ID
		dataType: int64
		formatString: 0
		lineageTag: 91c8e346-7a21-4d9d-abfa-ba33ac029a9a
		summarizeBy: count
		sourceColumn: User_ID

		annotation SummarizationSetBy = Automatic

	column Product_ID
		dataType: string
		lineageTag: 1664aae8-d65c-4cfb-aba0-7c346be4c332
		summarizeBy: none
		sourceColumn: Product_ID

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 9d496a62-d5d8-477c-8f0e-b1040359f2c9
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: string
		lineageTag: 80758bb1-1a9b-447f-9bd3-25d8a284c2c2
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Occupation
		dataType: int64
		formatString: #,0
		lineageTag: 59b2a7bb-0231-4095-b633-9fc3f7871daa
		summarizeBy: sum
		sourceColumn: Occupation

		annotation SummarizationSetBy = Automatic

	column City_Category
		dataType: string
		lineageTag: a6fcc420-3ea2-4db1-9377-acbccdf2df88
		summarizeBy: none
		sourceColumn: City_Category

		annotation SummarizationSetBy = Automatic

	column Stay_In_Current_City_Years
		dataType: int64
		formatString: 0
		lineageTag: bb16c843-6919-493e-84bc-3794738b20a9
		summarizeBy: sum
		sourceColumn: Stay_In_Current_City_Years

		annotation SummarizationSetBy = Automatic

	column Marital_Status
		dataType: int64
		formatString: 0
		lineageTag: 0622f37e-2c54-4157-9d0b-3805ae22f185
		summarizeBy: sum
		sourceColumn: Marital_Status

		annotation SummarizationSetBy = Automatic

	column Product_Category
		dataType: int64
		formatString: 0
		lineageTag: 4f56fcea-87fa-47d8-9e5e-621871b8f7ec
		summarizeBy: sum
		sourceColumn: Product_Category

		annotation SummarizationSetBy = Automatic

	column Purchase
		dataType: int64
		lineageTag: db3814cb-47f6-4d91-828d-ff2ca477e138
		summarizeBy: sum
		sourceColumn: Purchase

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Walmart = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://repoz-my.sharepoint.com/personal/karthikrajan_repoz_ai/Documents/SaaS%20testing%20files/Domain%20Datasets%20-%20Remote%20inters/E-Commerce/Walmart%20Ecommerce%20interactive/Walmart.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"User_ID", Int64.Type}, {"Product_ID", type text}, {"Gender", type text}, {"Age", type text}, {"Occupation", Int64.Type}, {"City_Category", type text}, {"Stay_In_Current_City_Years", Int64.Type}, {"Marital_Status", Int64.Type}, {"Product_Category", Int64.Type}, {"Purchase", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

