table 'Insurance Policies'
	lineageTag: 549d7e13-60f5-4aaa-b593-d54eed576eac

	column 'Customer ID'
		dataType: string
		lineageTag: 32338dc2-725a-4dc5-94ac-1c4b7da10faf
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 36cd31ec-d017-4036-968a-ee6a928b5dbb
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: c10a0144-1d82-4365-a319-217dfca0b4b4
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: f828585b-5235-4c66-b3ff-a60920d942e0
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: eaa29861-a02a-4e70-a4d3-9a1a32a199ed
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Policy ID'
		dataType: string
		lineageTag: 8994112c-0005-4da6-8354-54fbcd64587b
		summarizeBy: none
		sourceColumn: Policy ID

		annotation SummarizationSetBy = Automatic

	column 'Policy Type'
		dataType: string
		lineageTag: 9199d88a-8a3b-4c65-8c67-efa1b014a802
		summarizeBy: none
		sourceColumn: Policy Type

		annotation SummarizationSetBy = Automatic

	column 'Coverage Amount'
		dataType: int64
		formatString: 0
		lineageTag: 1f65304b-797a-420f-a46b-238c07a58943
		summarizeBy: sum
		sourceColumn: Coverage Amount

		annotation SummarizationSetBy = Automatic

	column 'Annual Premium'
		dataType: int64
		formatString: 0
		lineageTag: 284140ad-6583-4b38-8c23-21fbdbfcc490
		summarizeBy: sum
		sourceColumn: Annual Premium

		annotation SummarizationSetBy = Automatic

	column 'Policy Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1cdc2a1d-4f13-4895-97b7-998d10b7c605
		summarizeBy: none
		sourceColumn: Policy Start Date

		variation Variation
			isDefault
			relationship: 88f370ca-e3f7-4270-a146-6a9397da33e6
			defaultHierarchy: LocalDateTable_b8dd9cc8-0d49-4ae4-afb0-322c0ee93f2f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Policy End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 37c2f069-8ec6-4b0c-abf5-5075f67ebe8a
		summarizeBy: none
		sourceColumn: Policy End Date

		variation Variation
			isDefault
			relationship: 98249acc-5074-41a3-b3d1-3decfcaa9b28
			defaultHierarchy: LocalDateTable_e74b75bb-069f-4734-bfda-499bbf37f54a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Payment Frequency'
		dataType: string
		lineageTag: 7eba54b0-45c7-4031-934d-b2f242128284
		summarizeBy: none
		sourceColumn: Payment Frequency

		annotation SummarizationSetBy = Automatic

	column 'Claim ID'
		dataType: string
		lineageTag: 476dce38-794b-41d2-bd71-dd9af5ca8dfb
		summarizeBy: none
		sourceColumn: Claim ID

		annotation SummarizationSetBy = Automatic

	column 'Claim Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6f0c9c05-45c4-476d-9e92-bd5850a32214
		summarizeBy: none
		sourceColumn: Claim Date

		variation Variation
			isDefault
			relationship: d602fb4e-abf3-47bc-8f76-35d935f7ad71
			defaultHierarchy: LocalDateTable_e9ecc925-c59c-41ea-9559-e87b3e24f6d7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Claim Amount'
		dataType: int64
		formatString: 0
		lineageTag: f6969861-27dc-4d78-974a-2d99a1cdc46b
		summarizeBy: sum
		sourceColumn: Claim Amount

		annotation SummarizationSetBy = Automatic

	column 'Claim Status'
		dataType: string
		lineageTag: 5faed50a-fc6a-4389-9c14-c3866cb0255f
		summarizeBy: none
		sourceColumn: Claim Status

		annotation SummarizationSetBy = Automatic

	column 'Claim Settlement Days'
		dataType: int64
		formatString: 0
		lineageTag: 06d3bc4f-a31c-4711-a07f-5cdfbec2b36a
		summarizeBy: sum
		sourceColumn: Claim Settlement Days

		annotation SummarizationSetBy = Automatic

	column 'Claim Reason'
		dataType: string
		lineageTag: 2023ffcf-b133-40c5-bb6b-017109fc68bf
		summarizeBy: none
		sourceColumn: Claim Reason

		annotation SummarizationSetBy = Automatic

	column 'Hospital Name'
		dataType: string
		lineageTag: 5e3da031-f687-49a1-9d98-7abd9ffa655a
		summarizeBy: none
		sourceColumn: Hospital Name

		annotation SummarizationSetBy = Automatic

	column 'Hospital Location'
		dataType: string
		lineageTag: 8420c99b-9fad-4247-9bde-f01241cdce8a
		summarizeBy: none
		sourceColumn: Hospital Location

		annotation SummarizationSetBy = Automatic

	column 'Satisfaction Score'
		dataType: int64
		formatString: 0
		lineageTag: b32a6a53-77d0-4a25-98d3-78ff3b686882
		summarizeBy: sum
		sourceColumn: Satisfaction Score

		annotation SummarizationSetBy = Automatic

	column BMI
		dataType: double
		lineageTag: 3737f466-a6a3-4951-b593-52eef06406fa
		summarizeBy: sum
		sourceColumn: BMI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Smoking Status'
		dataType: string
		lineageTag: 225387c4-f450-4b0f-a094-c8b08badc08f
		summarizeBy: none
		sourceColumn: Smoking Status

		annotation SummarizationSetBy = Automatic

	column 'Risk Score'
		dataType: int64
		formatString: 0
		lineageTag: 63e28687-15a3-44c1-a740-f315a504d0e8
		summarizeBy: sum
		sourceColumn: Risk Score

		annotation SummarizationSetBy = Automatic

	column 'Total Premiums Collected'
		dataType: int64
		formatString: 0
		lineageTag: e11230cb-a093-4fe3-a9f6-8b53cc102617
		summarizeBy: sum
		sourceColumn: Total Premiums Collected

		annotation SummarizationSetBy = Automatic

	column 'Total Claims Paid'
		dataType: int64
		formatString: 0
		lineageTag: 8cdebd9d-7509-425a-9175-21f074769371
		summarizeBy: sum
		sourceColumn: Total Claims Paid

		annotation SummarizationSetBy = Automatic

	column Profit/Loss
		dataType: int64
		formatString: 0
		lineageTag: b653fb99-00a9-4b51-b829-6cf41bb47f05
		summarizeBy: sum
		sourceColumn: Profit/Loss

		annotation SummarizationSetBy = Automatic

	column 'Claim Ratio'
		dataType: double
		lineageTag: 5677edc6-446f-4c35-922f-e285dc9b3020
		summarizeBy: sum
		sourceColumn: Claim Ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Insurance Policies' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://repoz-my.sharepoint.com/personal/karthikrajan_repoz_ai/Documents/SaaS%20testing%20files/Domain%20Datasets%20-%20Remote%20inters/Insurances%20Domain/Car%20Insurance%20Dashboard/Car%20Insurance%20Dashboard.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer ID", type text}, {"Name", type text}, {"Age", Int64.Type}, {"Gender", type text}, {"Region", type text}, {"Policy ID", type text}, {"Policy Type", type text}, {"Coverage Amount", Int64.Type}, {"Annual Premium", Int64.Type}, {"Policy Start Date", type date}, {"Policy End Date", type date}, {"Payment Frequency", type text}, {"Claim ID", type text}, {"Claim Date", type date}, {"Claim Amount", Int64.Type}, {"Claim Status", type text}, {"Claim Settlement Days", Int64.Type}, {"Claim Reason", type text}, {"Hospital Name", type text}, {"Hospital Location", type text}, {"Satisfaction Score", Int64.Type}, {"BMI", type number}, {"Smoking Status", type text}, {"Risk Score", Int64.Type}, {"Total Premiums Collected", Int64.Type}, {"Total Claims Paid", Int64.Type}, {"Profit/Loss", Int64.Type}, {"Claim Ratio", type number}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

