table 'Top N Customers'
	lineageTag: c6a90b63-c1a6-49a8-af98-3ccdc889899d

	measure 'Top N Customers Value' = SELECTEDVALUE('Top N Customers'[Top N Customers], 1)
		lineageTag: e9b8c737-112d-4494-9620-4160af28ca45

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Top N Customers'
		dataType: double
		formatString: 0
		lineageTag: 539433d5-dbbd-4b95-a2f1-ff5164968b4e
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Top N Customers' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_Id = 1402e226adef4367983524d51cdfb45b

