table 'Orders+ (Sample - Superstore)'
	lineageTag: a173b7ce-3a74-4ae5-bd70-b1ba70bad8d6

	measure 'Previous year' = VAR selDate = SELECTEDVALUE('Parameters'[Select date]) VAR lowerBound = IF(MONTH(selDate) <= 3, DATE(YEAR(selDate) - 2, 4, 1), IF(MONTH(selDate) >= 4 && YEAR(selDate) - 1 = YEAR('Orders+ (Sample - Superstore)'[Order Date]), DATE(YEAR(selDate) - 1, 4, 1), BLANK())) RETURN IF('Orders+ (Sample - Superstore)'[Order Date] <= EDATE(selDate, -12) && 'Orders+ (Sample - Superstore)'[Order Date] >= lowerBound, 'Orders+ (Sample - Superstore)'[Sales], BLANK())
		formatString: 0
		lineageTag: 8188bfba-e00b-4d5a-bd0b-56614a3814c6

	measure Calculation1 = NOT(ISBLANK('Orders+ (Sample - Superstore)'[Current year])) || NOT(ISBLANK('Orders+ (Sample - Superstore)'[Previous year]))
		lineageTag: 991e8f43-081c-4d75-afbd-d802d8b59cf4

	measure 'Dynamic years' = SELECTEDVALUE('Parameters'[Select date])
		lineageTag: d083a3d7-9b28-4b19-882c-e601704ceccd

	measure MTD = VAR selDate = SELECTEDVALUE('Select date'[Display As]) RETURN 'Orders+ (Sample - Superstore)'[Order Date] <= selDate && 'Orders+ (Sample - Superstore)'[Order Date] >= IF(MONTH(selDate) <= 3, DATE(YEAR(selDate) - 1, 4, 1), IF(MONTH(selDate) >= 4 && YEAR(selDate) = YEAR('Orders+ (Sample - Superstore)'[Order Date]), DATE(YEAR(selDate), 4, 1), BLANK()))
		lineageTag: 1bca56ad-6a19-4210-96ec-47dc48b50b71

	measure 'Dynamic Measure values with YTD/MTD/QTD' = VAR period = SELECTEDVALUE('Select Period'[Display As]) VAR selDate = SELECTEDVALUE('Select date'[Display As]) VAR lowerBound = IF(MONTH(selDate) <= 3, DATE(YEAR(selDate) - 1, 4, 1), IF(MONTH(selDate) >= 4 && YEAR(selDate) = YEAR('Orders+ (Sample - Superstore)'[Order Date]), DATE(YEAR(selDate), 4, 1), BLANK())) RETURN SWITCH(TRUE(), period = 1, 'Orders+ (Sample - Superstore)'[Order Date] <= selDate && 'Orders+ (Sample - Superstore)'[Order Date] >= lowerBound, period = 2, [MTD], period = 3, [QTD], BLANK())
		lineageTag: 5580c3e8-b229-422f-9186-7e8b46cb3da1

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 29468e72-0966-48f0-910e-755ad922a162
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 2486c76c-2f2c-4870-b2e5-826a2e1d1120
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: datetime
		lineageTag: 7a3bf854-bf27-4bfb-b66a-4ee1223cc002
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: datetime
		lineageTag: cd7170d2-9bb5-4652-82cf-cc55f1d18529
		summarizeBy: none
		sourceColumn: 'Ship Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: b8d58114-fab4-4e13-a9ce-0979e6734b07
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 3620fc94-a252-4435-8abb-1745a7b3cb4b
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 150a2bda-b4a8-4493-8e71-c6cccb080e8d
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 29e9c366-79c3-4216-b7ed-939bb84152a9
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Country/Region'
		dataType: string
		lineageTag: 5989f200-bc3e-4b79-9692-2e03439b21a4
		summarizeBy: none
		sourceColumn: 'Country/Region'

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 63e1a751-e5a2-4040-aa25-004a46fbce24
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 453328ef-ff91-44f6-a856-8d3b6cedbe68
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 96541ddd-e5f6-4d21-87d5-b298ca3b0f02
		summarizeBy: sum
		sourceColumn: 'Postal Code'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 6605909f-58e6-4f3b-a37d-42f09647fee2
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 9edd2e99-fe83-4727-896d-19591907dfa5
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 966b664f-906d-4c5d-a0a1-53e3fc883317
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: f78feafe-bc80-43b6-a48d-1c1e67db9770
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 92797a83-7877-42cc-a45e-fbdede8f4d9d
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: General Number
		lineageTag: 21976309-a058-4e01-ad3e-34d1c094a62c
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: cd56ef02-73b9-4da1-8c6d-2bc9a9de2637
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: General Number
		lineageTag: 71835832-3c38-490c-87e7-28df9f170179
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		formatString: General Number
		lineageTag: 507227c0-9406-4e89-b80b-b8498f03d60e
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QTD = 'Orders+ (Sample - Superstore)'[Order Date] <= 'Orders+ (Sample - Superstore)'[Dynamic years] && QUARTER('Orders+ (Sample - Superstore)'[Order Date]) = QUARTER('Orders+ (Sample - Superstore)'[Dynamic years]) && YEAR('Orders+ (Sample - Superstore)'[Order Date]) = YEAR('Orders+ (Sample - Superstore)'[Dynamic years])
		lineageTag: d74260fa-27e8-413c-a13e-540d521207d8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column None = DATE(YEAR('Orders+ (Sample - Superstore)'[Order Date]), MONTH('Orders+ (Sample - Superstore)'[Order Date]), 1)
		lineageTag: 9e5694d1-4559-4307-8cd0-cc5372546b04
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Current year' = IF([Dynamic Measure values with YTD/MTD/QTD], 'Orders+ (Sample - Superstore)'[Sales], BLANK())
		lineageTag: 28ebd6e9-1f03-4804-9e24-20dfbaec714e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Orders+ (Sample - Superstore)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Row ID" = 2975, #"Order ID" = 4709, #"Order Date" = #date(2020, 6, 13), #"Ship Date" = #date(2021, 9, 2), #"Ship Mode" = "167.174.102.44", #"Customer ID" = 5714, #"Customer Name" = "Rafael Paul", #"Segment" = "study", #"Country/Region" = "Missouri", #"City" = "Murfreesboro", #"State" = "Utah", #"Postal Code" = 857, #"Region" = "Hawaii", #"Product ID" = 4209, #"Category" = "found", #"Sub-Category" = "confirmation", #"Product Name" = "Dorathy Miller", #"Sales" = 596.84, #"Quantity" = 756, #"Discount" = 642.64, #"Profit" = 647.72],
					        [#"Row ID" = 8258, #"Order ID" = 4292, #"Order Date" = #date(2020, 11, 23), #"Ship Date" = #date(2020, 1, 17), #"Ship Mode" = "48.232.20.35", #"Customer ID" = 4251, #"Customer Name" = "Eric Leon", #"Segment" = "dogs", #"Country/Region" = "West Virginia", #"City" = "Elyria", #"State" = "Iowa", #"Postal Code" = 296, #"Region" = "New Hampshire", #"Product ID" = 3260, #"Category" = "lesson", #"Sub-Category" = "el", #"Product Name" = "Otha Blair", #"Sales" = 624.66, #"Quantity" = 506, #"Discount" = 21.39, #"Profit" = 306.21],
					        [#"Row ID" = 4756, #"Order ID" = 7189, #"Order Date" = #date(2023, 11, 13), #"Ship Date" = #date(2021, 10, 11), #"Ship Mode" = "157.190.181.189", #"Customer ID" = 1640, #"Customer Name" = "Shu Dawson", #"Segment" = "contracts", #"Country/Region" = "New Jersey", #"City" = "Hemet", #"State" = "South Dakota", #"Postal Code" = 813, #"Region" = "South Dakota", #"Product ID" = 3370, #"Category" = "sciences", #"Sub-Category" = "stopped", #"Product Name" = "Aron Cooke", #"Sales" = 839.28, #"Quantity" = 309, #"Discount" = 546.95, #"Profit" = 159.05],
					        [#"Row ID" = 9960, #"Order ID" = 5639, #"Order Date" = #date(2022, 6, 24), #"Ship Date" = #date(2024, 8, 9), #"Ship Mode" = "196.175.153.193", #"Customer ID" = 5133, #"Customer Name" = "Jamey Graves", #"Segment" = "resort", #"Country/Region" = "Tennessee", #"City" = "Port Orange", #"State" = "Oklahoma", #"Postal Code" = 999, #"Region" = "Alabama", #"Product ID" = 1209, #"Category" = "highest", #"Sub-Category" = "deposit", #"Product Name" = "Sheldon Roach", #"Sales" = 803.23, #"Quantity" = 104, #"Discount" = 693.38, #"Profit" = 911.91],
					        [#"Row ID" = 2612, #"Order ID" = 7666, #"Order Date" = #date(2021, 2, 27), #"Ship Date" = #date(2023, 5, 14), #"Ship Mode" = "75.32.73.127", #"Customer ID" = 4003, #"Customer Name" = "Von Burke", #"Segment" = "suggested", #"Country/Region" = "New Hampshire", #"City" = "Summit", #"State" = "Rhode Island", #"Postal Code" = 982, #"Region" = "Wisconsin", #"Product ID" = 6664, #"Category" = "few", #"Sub-Category" = "automation", #"Product Name" = "Madalyn Gardner", #"Sales" = 921.99, #"Quantity" = 382, #"Discount" = 355.07, #"Profit" = 810.99]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Row ID", Int64.Type},
					        {"Order ID", type text},
					        {"Order Date", type date},
					        {"Ship Date", type date},
					        {"Ship Mode", type text},
					        {"Customer ID", type text},
					        {"Customer Name", type text},
					        {"Segment", type text},
					        {"Country/Region", type text},
					        {"City", type text},
					        {"State", type text},
					        {"Postal Code", Int64.Type},
					        {"Region", type text},
					        {"Product ID", type text},
					        {"Category", type text},
					        {"Sub-Category", type text},
					        {"Product Name", type text},
					        {"Sales", type number},
					        {"Quantity", Int64.Type},
					        {"Discount", type number},
					        {"Profit", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table