table 'Orders+ (Sample - Superstore)_People'
	lineageTag: 0dc9729e-8ec5-4d0d-837f-e79e784a5347

	column 'Regional Manager'
		dataType: string
		lineageTag: d349d78d-5485-4f4e-a953-d7466a5bb77a
		summarizeBy: none
		sourceColumn: 'Regional Manager'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 178e9f13-e668-4451-871f-7660cb662c55
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition 'Orders+ (Sample - Superstore)_People' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Regional Manager" = "Maryland", #"Region" = "Louisiana"],
					        [#"Regional Manager" = "Vermont", #"Region" = "Wyoming"],
					        [#"Regional Manager" = "Alaska", #"Region" = "Kansas"],
					        [#"Regional Manager" = "Missouri", #"Region" = "Hawaii"],
					        [#"Regional Manager" = "Virginia", #"Region" = "West Virginia"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Regional Manager", type text},
					        {"Region", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table