table 'customer_cases+'
	lineageTag: 472fc638-d716-4eea-9e25-e0efb08bfc6d

	column F1
		dataType: int64
		formatString: 0
		lineageTag: d90dbb57-0330-4397-9c8d-63143b985645
		summarizeBy: sum
		sourceColumn: F1

		annotation SummarizationSetBy = Automatic

	column case_id
		dataType: string
		lineageTag: 583b8550-c9d9-49de-a78a-d0a19c8e8bcc
		summarizeBy: none
		sourceColumn: case_id

		annotation SummarizationSetBy = Automatic

	column date_time
		dataType: datetime
		lineageTag: 69d5fdd0-9f1a-44a1-bf53-9d01c193facf
		summarizeBy: none
		sourceColumn: date_time

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: 88026c0d-b994-4e29-ad07-3035c5c5f852
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: e765d4df-6f22-4f8f-8cba-69427f3e2fb7
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column reason
		dataType: string
		lineageTag: 0fd8164c-1c31-46f2-887a-1b4f6aa34388
		summarizeBy: none
		sourceColumn: reason

		annotation SummarizationSetBy = Automatic

	column 'F1 1'
		dataType: int64
		formatString: 0
		lineageTag: 196d89dc-9b7c-445b-9bdf-a4bbf0ac756b
		summarizeBy: sum
		sourceColumn: 'F1 1'

		annotation SummarizationSetBy = Automatic

	column 'customer_id 1'
		dataType: string
		lineageTag: c037a969-97cf-445a-bb9c-3c4949a493a8
		summarizeBy: none
		sourceColumn: 'customer_id 1'

		annotation SummarizationSetBy = Automatic

	column product
		dataType: string
		lineageTag: 653acdbf-87f7-4d2f-8e42-c304a0576aff
		summarizeBy: none
		sourceColumn: product

		annotation SummarizationSetBy = Automatic

	column signup_date_time
		dataType: datetime
		lineageTag: d6accf07-c233-4419-ba45-ef91e04a5859
		summarizeBy: none
		sourceColumn: signup_date_time

		annotation SummarizationSetBy = Automatic

	column cancel_date_time
		dataType: string
		lineageTag: 7d1293af-15dd-4941-a08d-46a1744a816f
		summarizeBy: none
		sourceColumn: cancel_date_time

		annotation SummarizationSetBy = Automatic

	column 'F1 2'
		dataType: int64
		formatString: 0
		lineageTag: 7777f49b-1ac2-4f5c-8cda-b8ebbb593f6b
		summarizeBy: sum
		sourceColumn: 'F1 2'

		annotation SummarizationSetBy = Automatic

	column 'customer_id 2'
		dataType: string
		lineageTag: 30358e4d-c848-4cf5-ae16-c9d83ca948e1
		summarizeBy: none
		sourceColumn: 'customer_id 2'

		annotation SummarizationSetBy = Automatic

	column age
		dataType: int64
		formatString: 0
		lineageTag: 2868b02f-4c2b-463f-9fe8-902b850df4d6
		summarizeBy: sum
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: a09ec13d-35bf-452b-8f3c-364649cee566
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: 03440d9c-2028-49bc-90ee-6de83e8b3348
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 0795284e-8aa1-4222-a4d3-0f39c4c523d1
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column price
		dataType: int64
		formatString: 0
		lineageTag: 3ad06148-d7bd-4aac-9022-be83f96bebed
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

	column billing_cycle
		dataType: int64
		formatString: 0
		lineageTag: c0258737-0c52-4a28-820a-a365a2a8aefb
		summarizeBy: sum
		sourceColumn: billing_cycle

		annotation SummarizationSetBy = Automatic

	partition 'customer_cases+' = m
		mode: import
		source =
				let 
					#"Source0" = Table.NestedJoin(#"customer_cases.csv_customer_cases+", {"F1"}, #"customer_product.csv_customer_cases+", {"F1"}, "customer_product.csv_customer_cases+", JoinKind.FullOuter),
					#"Expand0" = Table.ExpandTableColumn(#"Source0", "customer_product.csv_customer_cases+", {"F1", "customer_id", "product", "signup_date_time", "cancel_date_time"}, {"F1 1", "customer_id 1", "product", "signup_date_time", "cancel_date_time"}),
					#"Source1" = Table.NestedJoin(#"Expand0", {"F1"}, #"customer_info.csv_customer_cases+", {"F1"}, "customer_info.csv_customer_cases+", JoinKind.LeftOuter),
					#"Expand1" = Table.ExpandTableColumn(#"Source1", "customer_info.csv_customer_cases+", {"F1", "customer_id", "age", "gender"}, {"F1 2", "customer_id 2", "age", "gender"}),
					#"Source2" = Table.NestedJoin(#"Expand1", {"case_id"}, #"product_info.csv_customer_cases+", {"product_id"}, "product_info.csv_customer_cases+", JoinKind.Inner),
					#"Expand2" = Table.ExpandTableColumn(#"Source2", "product_info.csv_customer_cases+", {"product_id", "name", "price", "billing_cycle"}, {"product_id", "name", "price", "billing_cycle"})
					in #"Expand2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table