table 'customer_info.csv_customer_cases+'
	lineageTag: a1a4b619-305e-475d-a72b-e0bdd70441c4

	column F1
		dataType: int64
		formatString: 0
		lineageTag: e62c2e72-65aa-4ac8-a141-ef68cad2c6b9
		summarizeBy: sum
		sourceColumn: F1

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: 8ebf65be-9bc1-4cc5-9276-a91b01ad53dd
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column age
		dataType: int64
		formatString: 0
		lineageTag: 44975051-7d28-46ca-82b6-1815ec88b6cb
		summarizeBy: sum
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: bc1612ec-7c44-4b7f-9cb2-95885bf98918
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	partition 'customer_info.csv_customer_cases+' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"F1" = 92, #"customer_id" = 4969, #"age" = 68, #"gender" = "establishing"],
					        [#"F1" = 698, #"customer_id" = 8022, #"age" = 44, #"gender" = "bin"],
					        [#"F1" = 587, #"customer_id" = 6240, #"age" = 41, #"gender" = "fruit"],
					        [#"F1" = 421, #"customer_id" = 4081, #"age" = 31, #"gender" = "gave"],
					        [#"F1" = 494, #"customer_id" = 2410, #"age" = 44, #"gender" = "betting"],
					        [#"F1" = 810, #"customer_id" = 5289, #"age" = 41, #"gender" = "gardens"],
					        [#"F1" = 716, #"customer_id" = 6491, #"age" = 72, #"gender" = "wilson"],
					        [#"F1" = 613, #"customer_id" = 9228, #"age" = 35, #"gender" = "associate"],
					        [#"F1" = 740, #"customer_id" = 4984, #"age" = 82, #"gender" = "of"],
					        [#"F1" = 187, #"customer_id" = 1134, #"age" = 37, #"gender" = "operations"],
					        [#"F1" = 559, #"customer_id" = 4468, #"age" = 69, #"gender" = "blank"],
					        [#"F1" = 667, #"customer_id" = 9948, #"age" = 51, #"gender" = "amazing"],
					        [#"F1" = 466, #"customer_id" = 5373, #"age" = 64, #"gender" = "asp"],
					        [#"F1" = 690, #"customer_id" = 2888, #"age" = 54, #"gender" = "glad"],
					        [#"F1" = 982, #"customer_id" = 9210, #"age" = 74, #"gender" = "grace"],
					        [#"F1" = 678, #"customer_id" = 8050, #"age" = 58, #"gender" = "wildlife"],
					        [#"F1" = 33, #"customer_id" = 4094, #"age" = 46, #"gender" = "further"],
					        [#"F1" = 749, #"customer_id" = 8165, #"age" = 35, #"gender" = "launched"],
					        [#"F1" = 627, #"customer_id" = 4348, #"age" = 86, #"gender" = "palace"],
					        [#"F1" = 831, #"customer_id" = 3967, #"age" = 77, #"gender" = "newest"],
					        [#"F1" = 879, #"customer_id" = 3999, #"age" = 86, #"gender" = "specific"],
					        [#"F1" = 200, #"customer_id" = 2380, #"age" = 78, #"gender" = "viewing"],
					        [#"F1" = 472, #"customer_id" = 8575, #"age" = 38, #"gender" = "assets"],
					        [#"F1" = 311, #"customer_id" = 1840, #"age" = 98, #"gender" = "participants"],
					        [#"F1" = 395, #"customer_id" = 4174, #"age" = 21, #"gender" = "remaining"],
					        [#"F1" = 41, #"customer_id" = 2257, #"age" = 36, #"gender" = "experiences"],
					        [#"F1" = 599, #"customer_id" = 7846, #"age" = 84, #"gender" = "mirror"],
					        [#"F1" = 582, #"customer_id" = 1168, #"age" = 20, #"gender" = "holdem"],
					        [#"F1" = 790, #"customer_id" = 1796, #"age" = 50, #"gender" = "hb"],
					        [#"F1" = 793, #"customer_id" = 3101, #"age" = 67, #"gender" = "ban"],
					        [#"F1" = 555, #"customer_id" = 7037, #"age" = 50, #"gender" = "diversity"],
					        [#"F1" = 312, #"customer_id" = 4674, #"age" = 75, #"gender" = "linda"],
					        [#"F1" = 230, #"customer_id" = 6416, #"age" = 56, #"gender" = "hybrid"],
					        [#"F1" = 129, #"customer_id" = 4109, #"age" = 86, #"gender" = "below"],
					        [#"F1" = 667, #"customer_id" = 1814, #"age" = 80, #"gender" = "andrew"],
					        [#"F1" = 471, #"customer_id" = 9401, #"age" = 92, #"gender" = "ideas"],
					        [#"F1" = 171, #"customer_id" = 8541, #"age" = 81, #"gender" = "tv"],
					        [#"F1" = 368, #"customer_id" = 8329, #"age" = 64, #"gender" = "fame"],
					        [#"F1" = 653, #"customer_id" = 9398, #"age" = 93, #"gender" = "consumers"],
					        [#"F1" = 851, #"customer_id" = 3310, #"age" = 28, #"gender" = "quiz"],
					        [#"F1" = 259, #"customer_id" = 2070, #"age" = 33, #"gender" = "cheese"],
					        [#"F1" = 431, #"customer_id" = 5497, #"age" = 84, #"gender" = "fish"],
					        [#"F1" = 148, #"customer_id" = 5095, #"age" = 68, #"gender" = "again"],
					        [#"F1" = 267, #"customer_id" = 9002, #"age" = 49, #"gender" = "cisco"],
					        [#"F1" = 567, #"customer_id" = 6221, #"age" = 30, #"gender" = "phone"],
					        [#"F1" = 817, #"customer_id" = 3464, #"age" = 19, #"gender" = "done"],
					        [#"F1" = 178, #"customer_id" = 7673, #"age" = 52, #"gender" = "upgrade"],
					        [#"F1" = 321, #"customer_id" = 4566, #"age" = 44, #"gender" = "jeff"],
					        [#"F1" = 953, #"customer_id" = 7135, #"age" = 62, #"gender" = "tony"],
					        [#"F1" = 641, #"customer_id" = 5426, #"age" = 32, #"gender" = "acquisition"],
					        [#"F1" = 237, #"customer_id" = 1960, #"age" = 71, #"gender" = "farmers"],
					        [#"F1" = 852, #"customer_id" = 5642, #"age" = 80, #"gender" = "gi"],
					        [#"F1" = 88, #"customer_id" = 3997, #"age" = 66, #"gender" = "visited"],
					        [#"F1" = 472, #"customer_id" = 9398, #"age" = 86, #"gender" = "adjusted"],
					        [#"F1" = 874, #"customer_id" = 8833, #"age" = 37, #"gender" = "occupational"],
					        [#"F1" = 791, #"customer_id" = 3774, #"age" = 63, #"gender" = "huge"],
					        [#"F1" = 677, #"customer_id" = 9604, #"age" = 96, #"gender" = "mistake"],
					        [#"F1" = 671, #"customer_id" = 5305, #"age" = 27, #"gender" = "structural"],
					        [#"F1" = 46, #"customer_id" = 4132, #"age" = 96, #"gender" = "pdt"],
					        [#"F1" = 688, #"customer_id" = 8731, #"age" = 66, #"gender" = "stock"],
					        [#"F1" = 333, #"customer_id" = 7953, #"age" = 75, #"gender" = "sep"],
					        [#"F1" = 961, #"customer_id" = 7363, #"age" = 69, #"gender" = "special"],
					        [#"F1" = 362, #"customer_id" = 8476, #"age" = 85, #"gender" = "meeting"],
					        [#"F1" = 940, #"customer_id" = 5194, #"age" = 73, #"gender" = "inn"],
					        [#"F1" = 863, #"customer_id" = 7015, #"age" = 24, #"gender" = "ex"],
					        [#"F1" = 407, #"customer_id" = 3489, #"age" = 33, #"gender" = "camera"],
					        [#"F1" = 853, #"customer_id" = 7194, #"age" = 30, #"gender" = "jerry"],
					        [#"F1" = 263, #"customer_id" = 2075, #"age" = 49, #"gender" = "entirely"],
					        [#"F1" = 62, #"customer_id" = 6673, #"age" = 78, #"gender" = "sale"],
					        [#"F1" = 489, #"customer_id" = 5720, #"age" = 69, #"gender" = "move"],
					        [#"F1" = 104, #"customer_id" = 1265, #"age" = 24, #"gender" = "researchers"],
					        [#"F1" = 527, #"customer_id" = 7229, #"age" = 30, #"gender" = "pretty"],
					        [#"F1" = 594, #"customer_id" = 6813, #"age" = 71, #"gender" = "kits"],
					        [#"F1" = 821, #"customer_id" = 1746, #"age" = 79, #"gender" = "ap"],
					        [#"F1" = 171, #"customer_id" = 9791, #"age" = 66, #"gender" = "gnu"],
					        [#"F1" = 649, #"customer_id" = 5378, #"age" = 66, #"gender" = "trembl"],
					        [#"F1" = 885, #"customer_id" = 3809, #"age" = 40, #"gender" = "codes"],
					        [#"F1" = 581, #"customer_id" = 8517, #"age" = 83, #"gender" = "responses"],
					        [#"F1" = 445, #"customer_id" = 2181, #"age" = 28, #"gender" = "known"],
					        [#"F1" = 154, #"customer_id" = 3411, #"age" = 34, #"gender" = "earned"],
					        [#"F1" = 658, #"customer_id" = 1296, #"age" = 18, #"gender" = "folks"],
					        [#"F1" = 380, #"customer_id" = 6805, #"age" = 22, #"gender" = "doubt"],
					        [#"F1" = 694, #"customer_id" = 8656, #"age" = 91, #"gender" = "virgin"],
					        [#"F1" = 211, #"customer_id" = 3976, #"age" = 52, #"gender" = "representative"],
					        [#"F1" = 267, #"customer_id" = 1582, #"age" = 59, #"gender" = "holder"],
					        [#"F1" = 781, #"customer_id" = 4183, #"age" = 58, #"gender" = "part"],
					        [#"F1" = 764, #"customer_id" = 9383, #"age" = 92, #"gender" = "athens"],
					        [#"F1" = 918, #"customer_id" = 3165, #"age" = 22, #"gender" = "japanese"],
					        [#"F1" = 542, #"customer_id" = 1502, #"age" = 45, #"gender" = "hampshire"],
					        [#"F1" = 502, #"customer_id" = 6772, #"age" = 30, #"gender" = "aid"],
					        [#"F1" = 146, #"customer_id" = 6730, #"age" = 100, #"gender" = "walls"],
					        [#"F1" = 553, #"customer_id" = 9301, #"age" = 99, #"gender" = "arab"],
					        [#"F1" = 281, #"customer_id" = 8519, #"age" = 38, #"gender" = "rankings"],
					        [#"F1" = 528, #"customer_id" = 7486, #"age" = 82, #"gender" = "funny"],
					        [#"F1" = 714, #"customer_id" = 2018, #"age" = 31, #"gender" = "injuries"],
					        [#"F1" = 244, #"customer_id" = 8089, #"age" = 93, #"gender" = "outline"],
					        [#"F1" = 946, #"customer_id" = 6627, #"age" = 58, #"gender" = "austria"],
					        [#"F1" = 109, #"customer_id" = 2314, #"age" = 78, #"gender" = "rather"],
					        [#"F1" = 592, #"customer_id" = 9970, #"age" = 59, #"gender" = "dealing"],
					        [#"F1" = 800, #"customer_id" = 3984, #"age" = 58, #"gender" = "faster"],
					        [#"F1" = 727, #"customer_id" = 2220, #"age" = 92, #"gender" = "developing"],
					        [#"F1" = 660, #"customer_id" = 3142, #"age" = 38, #"gender" = "continue"],
					        [#"F1" = 424, #"customer_id" = 7513, #"age" = 53, #"gender" = "master"],
					        [#"F1" = 956, #"customer_id" = 2785, #"age" = 78, #"gender" = "michigan"],
					        [#"F1" = 904, #"customer_id" = 1504, #"age" = 43, #"gender" = "bone"],
					        [#"F1" = 225, #"customer_id" = 3639, #"age" = 92, #"gender" = "windows"],
					        [#"F1" = 974, #"customer_id" = 6470, #"age" = 98, #"gender" = "gulf"],
					        [#"F1" = 157, #"customer_id" = 4531, #"age" = 62, #"gender" = "coach"],
					        [#"F1" = 362, #"customer_id" = 9792, #"age" = 48, #"gender" = "cisco"],
					        [#"F1" = 325, #"customer_id" = 6833, #"age" = 61, #"gender" = "considered"],
					        [#"F1" = 594, #"customer_id" = 6777, #"age" = 23, #"gender" = "angel"],
					        [#"F1" = 521, #"customer_id" = 4395, #"age" = 23, #"gender" = "craft"],
					        [#"F1" = 41, #"customer_id" = 2444, #"age" = 42, #"gender" = "oil"],
					        [#"F1" = 186, #"customer_id" = 4077, #"age" = 61, #"gender" = "overnight"],
					        [#"F1" = 851, #"customer_id" = 3255, #"age" = 57, #"gender" = "applies"],
					        [#"F1" = 267, #"customer_id" = 7952, #"age" = 23, #"gender" = "plays"],
					        [#"F1" = 587, #"customer_id" = 8381, #"age" = 28, #"gender" = "operations"],
					        [#"F1" = 361, #"customer_id" = 5431, #"age" = 84, #"gender" = "easily"],
					        [#"F1" = 885, #"customer_id" = 4319, #"age" = 36, #"gender" = "advice"],
					        [#"F1" = 441, #"customer_id" = 5637, #"age" = 30, #"gender" = "benefit"],
					        [#"F1" = 271, #"customer_id" = 2766, #"age" = 64, #"gender" = "without"],
					        [#"F1" = 314, #"customer_id" = 9586, #"age" = 33, #"gender" = "britney"],
					        [#"F1" = 581, #"customer_id" = 9136, #"age" = 29, #"gender" = "have"],
					        [#"F1" = 351, #"customer_id" = 7926, #"age" = 18, #"gender" = "anarchist"],
					        [#"F1" = 683, #"customer_id" = 1705, #"age" = 33, #"gender" = "announcements"],
					        [#"F1" = 92, #"customer_id" = 6492, #"age" = 86, #"gender" = "causes"],
					        [#"F1" = 683, #"customer_id" = 6973, #"age" = 24, #"gender" = "his"],
					        [#"F1" = 709, #"customer_id" = 2783, #"age" = 28, #"gender" = "cv"],
					        [#"F1" = 713, #"customer_id" = 2495, #"age" = 75, #"gender" = "instrument"],
					        [#"F1" = 500, #"customer_id" = 4969, #"age" = 53, #"gender" = "birds"],
					        [#"F1" = 82, #"customer_id" = 7540, #"age" = 23, #"gender" = "polish"],
					        [#"F1" = 819, #"customer_id" = 5073, #"age" = 35, #"gender" = "william"],
					        [#"F1" = 660, #"customer_id" = 8626, #"age" = 96, #"gender" = "ralph"],
					        [#"F1" = 237, #"customer_id" = 1045, #"age" = 74, #"gender" = "women"],
					        [#"F1" = 49, #"customer_id" = 2766, #"age" = 93, #"gender" = "wet"],
					        [#"F1" = 601, #"customer_id" = 4850, #"age" = 97, #"gender" = "founded"],
					        [#"F1" = 640, #"customer_id" = 5151, #"age" = 27, #"gender" = "shop"],
					        [#"F1" = 662, #"customer_id" = 7895, #"age" = 69, #"gender" = "junior"],
					        [#"F1" = 552, #"customer_id" = 8854, #"age" = 73, #"gender" = "just"],
					        [#"F1" = 596, #"customer_id" = 5736, #"age" = 75, #"gender" = "potter"],
					        [#"F1" = 662, #"customer_id" = 3708, #"age" = 65, #"gender" = "maine"],
					        [#"F1" = 599, #"customer_id" = 2431, #"age" = 30, #"gender" = "logic"],
					        [#"F1" = 467, #"customer_id" = 6114, #"age" = 80, #"gender" = "files"],
					        [#"F1" = 309, #"customer_id" = 4414, #"age" = 32, #"gender" = "colleges"],
					        [#"F1" = 682, #"customer_id" = 4883, #"age" = 37, #"gender" = "acting"],
					        [#"F1" = 926, #"customer_id" = 1901, #"age" = 49, #"gender" = "north"],
					        [#"F1" = 842, #"customer_id" = 1939, #"age" = 76, #"gender" = "committee"],
					        [#"F1" = 780, #"customer_id" = 1648, #"age" = 49, #"gender" = "welcome"],
					        [#"F1" = 217, #"customer_id" = 6576, #"age" = 28, #"gender" = "interactions"],
					        [#"F1" = 587, #"customer_id" = 2552, #"age" = 68, #"gender" = "und"],
					        [#"F1" = 18, #"customer_id" = 2944, #"age" = 70, #"gender" = "picks"],
					        [#"F1" = 486, #"customer_id" = 2347, #"age" = 39, #"gender" = "flags"],
					        [#"F1" = 552, #"customer_id" = 1006, #"age" = 23, #"gender" = "pregnant"],
					        [#"F1" = 753, #"customer_id" = 1873, #"age" = 24, #"gender" = "but"],
					        [#"F1" = 167, #"customer_id" = 3875, #"age" = 41, #"gender" = "finland"],
					        [#"F1" = 225, #"customer_id" = 3795, #"age" = 57, #"gender" = "ut"],
					        [#"F1" = 844, #"customer_id" = 8169, #"age" = 85, #"gender" = "pg"],
					        [#"F1" = 932, #"customer_id" = 4340, #"age" = 83, #"gender" = "verify"],
					        [#"F1" = 651, #"customer_id" = 7275, #"age" = 25, #"gender" = "box"],
					        [#"F1" = 186, #"customer_id" = 7779, #"age" = 60, #"gender" = "shock"],
					        [#"F1" = 523, #"customer_id" = 5018, #"age" = 92, #"gender" = "october"],
					        [#"F1" = 607, #"customer_id" = 1866, #"age" = 26, #"gender" = "cat"],
					        [#"F1" = 838, #"customer_id" = 8269, #"age" = 84, #"gender" = "nissan"],
					        [#"F1" = 379, #"customer_id" = 3913, #"age" = 41, #"gender" = "cricket"],
					        [#"F1" = 381, #"customer_id" = 7936, #"age" = 100, #"gender" = "ratings"],
					        [#"F1" = 281, #"customer_id" = 2830, #"age" = 48, #"gender" = "sons"],
					        [#"F1" = 178, #"customer_id" = 8253, #"age" = 60, #"gender" = "passing"],
					        [#"F1" = 826, #"customer_id" = 3772, #"age" = 74, #"gender" = "suddenly"],
					        [#"F1" = 655, #"customer_id" = 3741, #"age" = 26, #"gender" = "standards"],
					        [#"F1" = 215, #"customer_id" = 7939, #"age" = 47, #"gender" = "lessons"],
					        [#"F1" = 60, #"customer_id" = 9008, #"age" = 23, #"gender" = "neither"],
					        [#"F1" = 165, #"customer_id" = 8227, #"age" = 24, #"gender" = "progress"],
					        [#"F1" = 816, #"customer_id" = 6753, #"age" = 69, #"gender" = "illness"],
					        [#"F1" = 35, #"customer_id" = 7448, #"age" = 83, #"gender" = "makers"],
					        [#"F1" = 693, #"customer_id" = 1325, #"age" = 52, #"gender" = "rise"],
					        [#"F1" = 492, #"customer_id" = 1567, #"age" = 73, #"gender" = "hairy"],
					        [#"F1" = 592, #"customer_id" = 7924, #"age" = 83, #"gender" = "status"],
					        [#"F1" = 224, #"customer_id" = 6934, #"age" = 74, #"gender" = "immigration"],
					        [#"F1" = 478, #"customer_id" = 4176, #"age" = 41, #"gender" = "recovery"],
					        [#"F1" = 809, #"customer_id" = 2312, #"age" = 99, #"gender" = "reaction"],
					        [#"F1" = 668, #"customer_id" = 1072, #"age" = 70, #"gender" = "priorities"],
					        [#"F1" = 906, #"customer_id" = 6726, #"age" = 32, #"gender" = "machines"],
					        [#"F1" = 941, #"customer_id" = 3656, #"age" = 60, #"gender" = "behind"],
					        [#"F1" = 747, #"customer_id" = 3011, #"age" = 77, #"gender" = "primary"],
					        [#"F1" = 715, #"customer_id" = 4368, #"age" = 59, #"gender" = "horizontal"],
					        [#"F1" = 864, #"customer_id" = 6804, #"age" = 90, #"gender" = "delay"],
					        [#"F1" = 504, #"customer_id" = 9273, #"age" = 60, #"gender" = "held"],
					        [#"F1" = 339, #"customer_id" = 7360, #"age" = 72, #"gender" = "audit"],
					        [#"F1" = 128, #"customer_id" = 9570, #"age" = 78, #"gender" = "heart"],
					        [#"F1" = 402, #"customer_id" = 5077, #"age" = 100, #"gender" = "man"],
					        [#"F1" = 924, #"customer_id" = 6753, #"age" = 18, #"gender" = "bargains"],
					        [#"F1" = 225, #"customer_id" = 9051, #"age" = 25, #"gender" = "deposit"],
					        [#"F1" = 955, #"customer_id" = 5818, #"age" = 23, #"gender" = "mortgages"],
					        [#"F1" = 314, #"customer_id" = 7996, #"age" = 71, #"gender" = "practices"],
					        [#"F1" = 599, #"customer_id" = 7651, #"age" = 75, #"gender" = "destinations"],
					        [#"F1" = 535, #"customer_id" = 6282, #"age" = 63, #"gender" = "literature"],
					        [#"F1" = 748, #"customer_id" = 1799, #"age" = 21, #"gender" = "resume"],
					        [#"F1" = 961, #"customer_id" = 1515, #"age" = 76, #"gender" = "activities"],
					        [#"F1" = 447, #"customer_id" = 4188, #"age" = 81, #"gender" = "marks"],
					        [#"F1" = 596, #"customer_id" = 6924, #"age" = 94, #"gender" = "knowledge"],
					        [#"F1" = 728, #"customer_id" = 6674, #"age" = 92, #"gender" = "regarding"],
					        [#"F1" = 12, #"customer_id" = 6536, #"age" = 76, #"gender" = "interactions"],
					        [#"F1" = 114, #"customer_id" = 6976, #"age" = 33, #"gender" = "iowa"],
					        [#"F1" = 216, #"customer_id" = 2541, #"age" = 70, #"gender" = "downloaded"],
					        [#"F1" = 606, #"customer_id" = 8823, #"age" = 65, #"gender" = "electric"],
					        [#"F1" = 603, #"customer_id" = 1201, #"age" = 36, #"gender" = "patent"],
					        [#"F1" = 605, #"customer_id" = 5533, #"age" = 97, #"gender" = "killing"],
					        [#"F1" = 312, #"customer_id" = 4755, #"age" = 18, #"gender" = "development"],
					        [#"F1" = 902, #"customer_id" = 1759, #"age" = 82, #"gender" = "st"],
					        [#"F1" = 570, #"customer_id" = 8744, #"age" = 92, #"gender" = "icons"],
					        [#"F1" = 596, #"customer_id" = 4107, #"age" = 83, #"gender" = "manhattan"],
					        [#"F1" = 993, #"customer_id" = 6983, #"age" = 32, #"gender" = "mostly"],
					        [#"F1" = 506, #"customer_id" = 2500, #"age" = 76, #"gender" = "universal"],
					        [#"F1" = 274, #"customer_id" = 6887, #"age" = 77, #"gender" = "constructed"],
					        [#"F1" = 804, #"customer_id" = 5261, #"age" = 84, #"gender" = "accounting"],
					        [#"F1" = 446, #"customer_id" = 5497, #"age" = 24, #"gender" = "jokes"],
					        [#"F1" = 105, #"customer_id" = 6905, #"age" = 25, #"gender" = "kick"],
					        [#"F1" = 977, #"customer_id" = 2010, #"age" = 97, #"gender" = "micro"],
					        [#"F1" = 247, #"customer_id" = 6547, #"age" = 96, #"gender" = "conclusion"],
					        [#"F1" = 51, #"customer_id" = 6602, #"age" = 26, #"gender" = "honda"],
					        [#"F1" = 242, #"customer_id" = 3958, #"age" = 27, #"gender" = "liquid"],
					        [#"F1" = 371, #"customer_id" = 4677, #"age" = 81, #"gender" = "thai"],
					        [#"F1" = 349, #"customer_id" = 4698, #"age" = 90, #"gender" = "your"],
					        [#"F1" = 79, #"customer_id" = 9351, #"age" = 99, #"gender" = "defendant"],
					        [#"F1" = 765, #"customer_id" = 7219, #"age" = 90, #"gender" = "adjustment"],
					        [#"F1" = 774, #"customer_id" = 9704, #"age" = 90, #"gender" = "suicide"],
					        [#"F1" = 581, #"customer_id" = 6006, #"age" = 22, #"gender" = "into"],
					        [#"F1" = 69, #"customer_id" = 1283, #"age" = 42, #"gender" = "truck"],
					        [#"F1" = 995, #"customer_id" = 5121, #"age" = 73, #"gender" = "tune"],
					        [#"F1" = 929, #"customer_id" = 8754, #"age" = 90, #"gender" = "efforts"],
					        [#"F1" = 91, #"customer_id" = 3502, #"age" = 85, #"gender" = "scene"],
					        [#"F1" = 304, #"customer_id" = 4847, #"age" = 33, #"gender" = "expanded"],
					        [#"F1" = 403, #"customer_id" = 7836, #"age" = 25, #"gender" = "cleveland"],
					        [#"F1" = 561, #"customer_id" = 2867, #"age" = 84, #"gender" = "train"],
					        [#"F1" = 70, #"customer_id" = 2801, #"age" = 44, #"gender" = "messaging"],
					        [#"F1" = 494, #"customer_id" = 9777, #"age" = 68, #"gender" = "cross"],
					        [#"F1" = 928, #"customer_id" = 1578, #"age" = 47, #"gender" = "reach"],
					        [#"F1" = 956, #"customer_id" = 3900, #"age" = 23, #"gender" = "comedy"],
					        [#"F1" = 420, #"customer_id" = 6626, #"age" = 78, #"gender" = "programming"],
					        [#"F1" = 674, #"customer_id" = 5019, #"age" = 75, #"gender" = "that"],
					        [#"F1" = 881, #"customer_id" = 9191, #"age" = 94, #"gender" = "inter"],
					        [#"F1" = 616, #"customer_id" = 2258, #"age" = 96, #"gender" = "leg"],
					        [#"F1" = 194, #"customer_id" = 4269, #"age" = 55, #"gender" = "chocolate"],
					        [#"F1" = 952, #"customer_id" = 4217, #"age" = 42, #"gender" = "jacksonville"],
					        [#"F1" = 527, #"customer_id" = 3890, #"age" = 69, #"gender" = "import"],
					        [#"F1" = 572, #"customer_id" = 3192, #"age" = 64, #"gender" = "currency"],
					        [#"F1" = 579, #"customer_id" = 6622, #"age" = 53, #"gender" = "population"],
					        [#"F1" = 98, #"customer_id" = 1019, #"age" = 79, #"gender" = "posting"],
					        [#"F1" = 509, #"customer_id" = 2664, #"age" = 50, #"gender" = "closely"],
					        [#"F1" = 80, #"customer_id" = 3506, #"age" = 91, #"gender" = "tom"],
					        [#"F1" = 633, #"customer_id" = 1806, #"age" = 35, #"gender" = "kg"],
					        [#"F1" = 812, #"customer_id" = 2639, #"age" = 38, #"gender" = "vermont"],
					        [#"F1" = 219, #"customer_id" = 9603, #"age" = 41, #"gender" = "features"],
					        [#"F1" = 570, #"customer_id" = 3910, #"age" = 23, #"gender" = "open"],
					        [#"F1" = 364, #"customer_id" = 8940, #"age" = 49, #"gender" = "ghz"],
					        [#"F1" = 72, #"customer_id" = 6206, #"age" = 39, #"gender" = "engine"],
					        [#"F1" = 847, #"customer_id" = 2445, #"age" = 33, #"gender" = "offered"],
					        [#"F1" = 821, #"customer_id" = 5489, #"age" = 36, #"gender" = "tracking"],
					        [#"F1" = 980, #"customer_id" = 4811, #"age" = 33, #"gender" = "hills"],
					        [#"F1" = 845, #"customer_id" = 3427, #"age" = 90, #"gender" = "sr"],
					        [#"F1" = 599, #"customer_id" = 3983, #"age" = 36, #"gender" = "shot"],
					        [#"F1" = 492, #"customer_id" = 4834, #"age" = 49, #"gender" = "fm"],
					        [#"F1" = 79, #"customer_id" = 1073, #"age" = 53, #"gender" = "initiative"],
					        [#"F1" = 606, #"customer_id" = 4016, #"age" = 41, #"gender" = "assigned"],
					        [#"F1" = 707, #"customer_id" = 6397, #"age" = 85, #"gender" = "metabolism"],
					        [#"F1" = 78, #"customer_id" = 2649, #"age" = 81, #"gender" = "shopping"],
					        [#"F1" = 742, #"customer_id" = 5255, #"age" = 56, #"gender" = "positive"],
					        [#"F1" = 769, #"customer_id" = 3662, #"age" = 22, #"gender" = "surveys"],
					        [#"F1" = 876, #"customer_id" = 8391, #"age" = 26, #"gender" = "utilities"],
					        [#"F1" = 712, #"customer_id" = 2300, #"age" = 63, #"gender" = "catholic"],
					        [#"F1" = 253, #"customer_id" = 7201, #"age" = 70, #"gender" = "imaging"],
					        [#"F1" = 109, #"customer_id" = 9248, #"age" = 98, #"gender" = "severe"],
					        [#"F1" = 610, #"customer_id" = 6490, #"age" = 57, #"gender" = "seek"],
					        [#"F1" = 877, #"customer_id" = 6220, #"age" = 23, #"gender" = "literary"],
					        [#"F1" = 221, #"customer_id" = 1538, #"age" = 92, #"gender" = "purple"],
					        [#"F1" = 455, #"customer_id" = 5697, #"age" = 67, #"gender" = "worker"],
					        [#"F1" = 929, #"customer_id" = 2298, #"age" = 62, #"gender" = "panel"],
					        [#"F1" = 653, #"customer_id" = 6564, #"age" = 64, #"gender" = "exclusive"],
					        [#"F1" = 20, #"customer_id" = 9105, #"age" = 93, #"gender" = "findings"],
					        [#"F1" = 7, #"customer_id" = 5246, #"age" = 48, #"gender" = "contains"],
					        [#"F1" = 562, #"customer_id" = 2983, #"age" = 42, #"gender" = "melissa"],
					        [#"F1" = 690, #"customer_id" = 7906, #"age" = 26, #"gender" = "gospel"],
					        [#"F1" = 924, #"customer_id" = 6376, #"age" = 71, #"gender" = "visiting"],
					        [#"F1" = 763, #"customer_id" = 8651, #"age" = 59, #"gender" = "money"],
					        [#"F1" = 161, #"customer_id" = 6552, #"age" = 89, #"gender" = "sold"],
					        [#"F1" = 899, #"customer_id" = 6254, #"age" = 36, #"gender" = "martin"],
					        [#"F1" = 542, #"customer_id" = 5071, #"age" = 43, #"gender" = "busy"],
					        [#"F1" = 790, #"customer_id" = 2438, #"age" = 89, #"gender" = "owned"],
					        [#"F1" = 879, #"customer_id" = 3831, #"age" = 88, #"gender" = "jimmy"],
					        [#"F1" = 673, #"customer_id" = 8391, #"age" = 100, #"gender" = "classified"],
					        [#"F1" = 855, #"customer_id" = 7834, #"age" = 55, #"gender" = "gets"],
					        [#"F1" = 50, #"customer_id" = 3786, #"age" = 36, #"gender" = "ft"],
					        [#"F1" = 994, #"customer_id" = 6752, #"age" = 81, #"gender" = "draw"],
					        [#"F1" = 639, #"customer_id" = 1990, #"age" = 61, #"gender" = "su"],
					        [#"F1" = 143, #"customer_id" = 1634, #"age" = 89, #"gender" = "arrangement"],
					        [#"F1" = 953, #"customer_id" = 8638, #"age" = 71, #"gender" = "posts"],
					        [#"F1" = 614, #"customer_id" = 9528, #"age" = 58, #"gender" = "lessons"],
					        [#"F1" = 726, #"customer_id" = 9878, #"age" = 72, #"gender" = "cover"],
					        [#"F1" = 204, #"customer_id" = 4555, #"age" = 55, #"gender" = "cherry"],
					        [#"F1" = 637, #"customer_id" = 1741, #"age" = 67, #"gender" = "originally"],
					        [#"F1" = 706, #"customer_id" = 4497, #"age" = 20, #"gender" = "resistant"],
					        [#"F1" = 279, #"customer_id" = 2448, #"age" = 63, #"gender" = "denmark"],
					        [#"F1" = 109, #"customer_id" = 8974, #"age" = 87, #"gender" = "symptoms"],
					        [#"F1" = 133, #"customer_id" = 1094, #"age" = 23, #"gender" = "quarter"],
					        [#"F1" = 33, #"customer_id" = 7168, #"age" = 52, #"gender" = "newly"],
					        [#"F1" = 573, #"customer_id" = 4337, #"age" = 56, #"gender" = "assurance"],
					        [#"F1" = 957, #"customer_id" = 3446, #"age" = 32, #"gender" = "arizona"],
					        [#"F1" = 492, #"customer_id" = 1266, #"age" = 44, #"gender" = "examined"],
					        [#"F1" = 75, #"customer_id" = 1274, #"age" = 83, #"gender" = "rank"],
					        [#"F1" = 160, #"customer_id" = 4283, #"age" = 86, #"gender" = "nissan"],
					        [#"F1" = 216, #"customer_id" = 2556, #"age" = 61, #"gender" = "south"],
					        [#"F1" = 718, #"customer_id" = 5756, #"age" = 56, #"gender" = "bond"],
					        [#"F1" = 632, #"customer_id" = 2307, #"age" = 30, #"gender" = "wealth"],
					        [#"F1" = 25, #"customer_id" = 9603, #"age" = 76, #"gender" = "powder"],
					        [#"F1" = 558, #"customer_id" = 3891, #"age" = 56, #"gender" = "swedish"],
					        [#"F1" = 631, #"customer_id" = 1133, #"age" = 25, #"gender" = "medline"],
					        [#"F1" = 925, #"customer_id" = 8825, #"age" = 65, #"gender" = "packs"],
					        [#"F1" = 990, #"customer_id" = 3974, #"age" = 36, #"gender" = "beauty"],
					        [#"F1" = 141, #"customer_id" = 6037, #"age" = 18, #"gender" = "conventional"],
					        [#"F1" = 309, #"customer_id" = 5712, #"age" = 78, #"gender" = "relation"],
					        [#"F1" = 812, #"customer_id" = 6078, #"age" = 27, #"gender" = "publisher"],
					        [#"F1" = 155, #"customer_id" = 2258, #"age" = 98, #"gender" = "feedback"],
					        [#"F1" = 953, #"customer_id" = 1236, #"age" = 57, #"gender" = "satellite"],
					        [#"F1" = 820, #"customer_id" = 3195, #"age" = 82, #"gender" = "browsing"],
					        [#"F1" = 561, #"customer_id" = 9382, #"age" = 98, #"gender" = "expectations"],
					        [#"F1" = 752, #"customer_id" = 2737, #"age" = 72, #"gender" = "guard"],
					        [#"F1" = 702, #"customer_id" = 5394, #"age" = 66, #"gender" = "disney"],
					        [#"F1" = 187, #"customer_id" = 9288, #"age" = 22, #"gender" = "adventure"],
					        [#"F1" = 220, #"customer_id" = 7126, #"age" = 24, #"gender" = "linda"],
					        [#"F1" = 360, #"customer_id" = 8056, #"age" = 93, #"gender" = "corresponding"],
					        [#"F1" = 226, #"customer_id" = 7301, #"age" = 41, #"gender" = "removed"],
					        [#"F1" = 604, #"customer_id" = 1879, #"age" = 83, #"gender" = "lib"],
					        [#"F1" = 196, #"customer_id" = 2123, #"age" = 69, #"gender" = "transformation"],
					        [#"F1" = 878, #"customer_id" = 4416, #"age" = 37, #"gender" = "split"],
					        [#"F1" = 206, #"customer_id" = 6100, #"age" = 32, #"gender" = "care"],
					        [#"F1" = 808, #"customer_id" = 2294, #"age" = 91, #"gender" = "seeking"],
					        [#"F1" = 405, #"customer_id" = 3258, #"age" = 80, #"gender" = "moore"],
					        [#"F1" = 352, #"customer_id" = 1506, #"age" = 51, #"gender" = "winner"],
					        [#"F1" = 298, #"customer_id" = 8600, #"age" = 67, #"gender" = "sciences"],
					        [#"F1" = 195, #"customer_id" = 9346, #"age" = 73, #"gender" = "ethical"],
					        [#"F1" = 354, #"customer_id" = 2319, #"age" = 87, #"gender" = "began"],
					        [#"F1" = 754, #"customer_id" = 6817, #"age" = 99, #"gender" = "tiny"],
					        [#"F1" = 23, #"customer_id" = 3490, #"age" = 92, #"gender" = "downloaded"],
					        [#"F1" = 201, #"customer_id" = 7120, #"age" = 75, #"gender" = "mice"],
					        [#"F1" = 321, #"customer_id" = 9760, #"age" = 55, #"gender" = "cited"],
					        [#"F1" = 100, #"customer_id" = 7631, #"age" = 82, #"gender" = "theme"],
					        [#"F1" = 654, #"customer_id" = 2128, #"age" = 78, #"gender" = "trial"],
					        [#"F1" = 833, #"customer_id" = 3624, #"age" = 63, #"gender" = "tags"],
					        [#"F1" = 500, #"customer_id" = 1265, #"age" = 23, #"gender" = "crown"],
					        [#"F1" = 129, #"customer_id" = 4818, #"age" = 81, #"gender" = "again"],
					        [#"F1" = 452, #"customer_id" = 5805, #"age" = 83, #"gender" = "votes"],
					        [#"F1" = 296, #"customer_id" = 1663, #"age" = 40, #"gender" = "mayor"],
					        [#"F1" = 681, #"customer_id" = 9940, #"age" = 18, #"gender" = "posted"],
					        [#"F1" = 662, #"customer_id" = 8842, #"age" = 88, #"gender" = "open"],
					        [#"F1" = 537, #"customer_id" = 3425, #"age" = 67, #"gender" = "who"],
					        [#"F1" = 742, #"customer_id" = 2350, #"age" = 77, #"gender" = "pounds"],
					        [#"F1" = 260, #"customer_id" = 5170, #"age" = 56, #"gender" = "household"],
					        [#"F1" = 70, #"customer_id" = 3232, #"age" = 86, #"gender" = "robot"],
					        [#"F1" = 322, #"customer_id" = 1967, #"age" = 44, #"gender" = "chairs"],
					        [#"F1" = 553, #"customer_id" = 1255, #"age" = 70, #"gender" = "declaration"],
					        [#"F1" = 333, #"customer_id" = 3246, #"age" = 83, #"gender" = "sectors"],
					        [#"F1" = 686, #"customer_id" = 4899, #"age" = 64, #"gender" = "curve"],
					        [#"F1" = 825, #"customer_id" = 6043, #"age" = 38, #"gender" = "like"],
					        [#"F1" = 304, #"customer_id" = 2148, #"age" = 89, #"gender" = "pharmacy"],
					        [#"F1" = 935, #"customer_id" = 6546, #"age" = 55, #"gender" = "epinions"],
					        [#"F1" = 102, #"customer_id" = 6487, #"age" = 63, #"gender" = "bit"],
					        [#"F1" = 358, #"customer_id" = 5852, #"age" = 43, #"gender" = "holds"],
					        [#"F1" = 508, #"customer_id" = 8469, #"age" = 26, #"gender" = "rm"],
					        [#"F1" = 25, #"customer_id" = 9065, #"age" = 34, #"gender" = "probability"],
					        [#"F1" = 360, #"customer_id" = 6494, #"age" = 26, #"gender" = "loved"],
					        [#"F1" = 793, #"customer_id" = 2065, #"age" = 25, #"gender" = "blogs"],
					        [#"F1" = 791, #"customer_id" = 7167, #"age" = 93, #"gender" = "carter"],
					        [#"F1" = 212, #"customer_id" = 1550, #"age" = 88, #"gender" = "app"],
					        [#"F1" = 875, #"customer_id" = 5372, #"age" = 24, #"gender" = "variables"],
					        [#"F1" = 750, #"customer_id" = 8382, #"age" = 71, #"gender" = "tropical"],
					        [#"F1" = 767, #"customer_id" = 6872, #"age" = 37, #"gender" = "horizontal"],
					        [#"F1" = 390, #"customer_id" = 8479, #"age" = 40, #"gender" = "submit"],
					        [#"F1" = 246, #"customer_id" = 6588, #"age" = 55, #"gender" = "type"],
					        [#"F1" = 717, #"customer_id" = 6144, #"age" = 97, #"gender" = "melbourne"],
					        [#"F1" = 568, #"customer_id" = 3709, #"age" = 64, #"gender" = "unlike"],
					        [#"F1" = 229, #"customer_id" = 5074, #"age" = 99, #"gender" = "event"],
					        [#"F1" = 55, #"customer_id" = 3635, #"age" = 93, #"gender" = "quantity"],
					        [#"F1" = 214, #"customer_id" = 8751, #"age" = 69, #"gender" = "sunday"],
					        [#"F1" = 149, #"customer_id" = 4089, #"age" = 78, #"gender" = "horse"],
					        [#"F1" = 510, #"customer_id" = 6313, #"age" = 69, #"gender" = "delaware"],
					        [#"F1" = 792, #"customer_id" = 3123, #"age" = 62, #"gender" = "murder"],
					        [#"F1" = 399, #"customer_id" = 4701, #"age" = 63, #"gender" = "privacy"],
					        [#"F1" = 459, #"customer_id" = 8304, #"age" = 96, #"gender" = "wheels"],
					        [#"F1" = 224, #"customer_id" = 3361, #"age" = 20, #"gender" = "everyone"],
					        [#"F1" = 467, #"customer_id" = 1858, #"age" = 57, #"gender" = "wife"],
					        [#"F1" = 54, #"customer_id" = 9678, #"age" = 24, #"gender" = "regard"],
					        [#"F1" = 245, #"customer_id" = 6604, #"age" = 41, #"gender" = "lite"],
					        [#"F1" = 651, #"customer_id" = 7990, #"age" = 93, #"gender" = "contractor"],
					        [#"F1" = 416, #"customer_id" = 6107, #"age" = 66, #"gender" = "hope"],
					        [#"F1" = 562, #"customer_id" = 5814, #"age" = 32, #"gender" = "let"],
					        [#"F1" = 66, #"customer_id" = 2821, #"age" = 56, #"gender" = "approval"],
					        [#"F1" = 348, #"customer_id" = 1988, #"age" = 52, #"gender" = "title"],
					        [#"F1" = 53, #"customer_id" = 5619, #"age" = 60, #"gender" = "content"],
					        [#"F1" = 312, #"customer_id" = 9052, #"age" = 31, #"gender" = "deputy"],
					        [#"F1" = 568, #"customer_id" = 8591, #"age" = 45, #"gender" = "bibliography"],
					        [#"F1" = 204, #"customer_id" = 8592, #"age" = 39, #"gender" = "deep"],
					        [#"F1" = 247, #"customer_id" = 8541, #"age" = 37, #"gender" = "select"],
					        [#"F1" = 93, #"customer_id" = 9394, #"age" = 38, #"gender" = "later"],
					        [#"F1" = 884, #"customer_id" = 8007, #"age" = 35, #"gender" = "needed"],
					        [#"F1" = 476, #"customer_id" = 4023, #"age" = 35, #"gender" = "subject"],
					        [#"F1" = 886, #"customer_id" = 3177, #"age" = 58, #"gender" = "portfolio"],
					        [#"F1" = 2, #"customer_id" = 2684, #"age" = 97, #"gender" = "shared"],
					        [#"F1" = 270, #"customer_id" = 1042, #"age" = 91, #"gender" = "participate"],
					        [#"F1" = 541, #"customer_id" = 6230, #"age" = 78, #"gender" = "lots"],
					        [#"F1" = 767, #"customer_id" = 4811, #"age" = 54, #"gender" = "construction"],
					        [#"F1" = 282, #"customer_id" = 8255, #"age" = 94, #"gender" = "died"],
					        [#"F1" = 800, #"customer_id" = 5126, #"age" = 34, #"gender" = "after"],
					        [#"F1" = 404, #"customer_id" = 7861, #"age" = 21, #"gender" = "prove"],
					        [#"F1" = 493, #"customer_id" = 2546, #"age" = 93, #"gender" = "raw"],
					        [#"F1" = 350, #"customer_id" = 7298, #"age" = 30, #"gender" = "dont"],
					        [#"F1" = 330, #"customer_id" = 6477, #"age" = 38, #"gender" = "rss"],
					        [#"F1" = 534, #"customer_id" = 4944, #"age" = 41, #"gender" = "karen"],
					        [#"F1" = 774, #"customer_id" = 5865, #"age" = 94, #"gender" = "bulletin"],
					        [#"F1" = 282, #"customer_id" = 1048, #"age" = 26, #"gender" = "military"],
					        [#"F1" = 167, #"customer_id" = 4008, #"age" = 61, #"gender" = "emails"],
					        [#"F1" = 650, #"customer_id" = 1135, #"age" = 81, #"gender" = "packard"],
					        [#"F1" = 174, #"customer_id" = 8338, #"age" = 97, #"gender" = "stand"],
					        [#"F1" = 378, #"customer_id" = 6360, #"age" = 40, #"gender" = "arts"],
					        [#"F1" = 841, #"customer_id" = 5654, #"age" = 91, #"gender" = "eye"],
					        [#"F1" = 856, #"customer_id" = 1074, #"age" = 52, #"gender" = "findings"],
					        [#"F1" = 346, #"customer_id" = 9245, #"age" = 37, #"gender" = "blow"],
					        [#"F1" = 124, #"customer_id" = 6887, #"age" = 39, #"gender" = "pad"],
					        [#"F1" = 594, #"customer_id" = 8174, #"age" = 78, #"gender" = "codes"],
					        [#"F1" = 304, #"customer_id" = 4444, #"age" = 63, #"gender" = "amateur"],
					        [#"F1" = 873, #"customer_id" = 9217, #"age" = 35, #"gender" = "characters"],
					        [#"F1" = 521, #"customer_id" = 1656, #"age" = 71, #"gender" = "pictures"],
					        [#"F1" = 94, #"customer_id" = 8523, #"age" = 89, #"gender" = "toe"],
					        [#"F1" = 698, #"customer_id" = 8575, #"age" = 40, #"gender" = "features"],
					        [#"F1" = 905, #"customer_id" = 8336, #"age" = 52, #"gender" = "architecture"],
					        [#"F1" = 44, #"customer_id" = 8747, #"age" = 22, #"gender" = "took"],
					        [#"F1" = 483, #"customer_id" = 8275, #"age" = 37, #"gender" = "reserve"],
					        [#"F1" = 17, #"customer_id" = 1323, #"age" = 91, #"gender" = "confirmed"],
					        [#"F1" = 2, #"customer_id" = 9324, #"age" = 59, #"gender" = "knife"],
					        [#"F1" = 291, #"customer_id" = 7894, #"age" = 79, #"gender" = "charged"],
					        [#"F1" = 129, #"customer_id" = 9742, #"age" = 39, #"gender" = "possible"],
					        [#"F1" = 418, #"customer_id" = 1477, #"age" = 85, #"gender" = "anytime"],
					        [#"F1" = 245, #"customer_id" = 5929, #"age" = 81, #"gender" = "healing"],
					        [#"F1" = 574, #"customer_id" = 8449, #"age" = 65, #"gender" = "gmt"],
					        [#"F1" = 411, #"customer_id" = 7771, #"age" = 41, #"gender" = "statement"],
					        [#"F1" = 22, #"customer_id" = 3412, #"age" = 80, #"gender" = "crisis"],
					        [#"F1" = 761, #"customer_id" = 8662, #"age" = 30, #"gender" = "include"],
					        [#"F1" = 256, #"customer_id" = 3645, #"age" = 21, #"gender" = "usually"],
					        [#"F1" = 627, #"customer_id" = 3903, #"age" = 30, #"gender" = "leads"],
					        [#"F1" = 174, #"customer_id" = 4267, #"age" = 91, #"gender" = "look"],
					        [#"F1" = 210, #"customer_id" = 8374, #"age" = 46, #"gender" = "teaching"],
					        [#"F1" = 477, #"customer_id" = 4394, #"age" = 46, #"gender" = "zero"],
					        [#"F1" = 182, #"customer_id" = 3498, #"age" = 44, #"gender" = "nfl"],
					        [#"F1" = 684, #"customer_id" = 8704, #"age" = 30, #"gender" = "wednesday"],
					        [#"F1" = 627, #"customer_id" = 2571, #"age" = 35, #"gender" = "bad"],
					        [#"F1" = 148, #"customer_id" = 4862, #"age" = 43, #"gender" = "swiss"],
					        [#"F1" = 642, #"customer_id" = 1495, #"age" = 97, #"gender" = "institution"],
					        [#"F1" = 284, #"customer_id" = 6761, #"age" = 27, #"gender" = "organisation"],
					        [#"F1" = 732, #"customer_id" = 9425, #"age" = 21, #"gender" = "william"],
					        [#"F1" = 769, #"customer_id" = 8774, #"age" = 25, #"gender" = "brands"],
					        [#"F1" = 329, #"customer_id" = 8052, #"age" = 32, #"gender" = "trading"],
					        [#"F1" = 806, #"customer_id" = 4864, #"age" = 18, #"gender" = "appliances"],
					        [#"F1" = 442, #"customer_id" = 1049, #"age" = 78, #"gender" = "david"],
					        [#"F1" = 513, #"customer_id" = 2720, #"age" = 82, #"gender" = "provider"],
					        [#"F1" = 535, #"customer_id" = 9783, #"age" = 40, #"gender" = "outsourcing"],
					        [#"F1" = 993, #"customer_id" = 5743, #"age" = 88, #"gender" = "halloween"],
					        [#"F1" = 118, #"customer_id" = 1828, #"age" = 29, #"gender" = "seat"],
					        [#"F1" = 885, #"customer_id" = 8447, #"age" = 65, #"gender" = "told"],
					        [#"F1" = 349, #"customer_id" = 5237, #"age" = 51, #"gender" = "temple"],
					        [#"F1" = 59, #"customer_id" = 1000, #"age" = 49, #"gender" = "located"],
					        [#"F1" = 532, #"customer_id" = 8988, #"age" = 96, #"gender" = "insight"],
					        [#"F1" = 966, #"customer_id" = 1641, #"age" = 22, #"gender" = "eyes"],
					        [#"F1" = 626, #"customer_id" = 4248, #"age" = 83, #"gender" = "justice"],
					        [#"F1" = 22, #"customer_id" = 7066, #"age" = 83, #"gender" = "lib"],
					        [#"F1" = 139, #"customer_id" = 1317, #"age" = 49, #"gender" = "corporations"],
					        [#"F1" = 878, #"customer_id" = 6675, #"age" = 83, #"gender" = "slip"],
					        [#"F1" = 346, #"customer_id" = 3706, #"age" = 24, #"gender" = "billion"],
					        [#"F1" = 217, #"customer_id" = 5168, #"age" = 32, #"gender" = "promoting"],
					        [#"F1" = 974, #"customer_id" = 8230, #"age" = 55, #"gender" = "frequently"],
					        [#"F1" = 554, #"customer_id" = 4653, #"age" = 81, #"gender" = "ha"],
					        [#"F1" = 441, #"customer_id" = 4986, #"age" = 31, #"gender" = "opinion"],
					        [#"F1" = 686, #"customer_id" = 6508, #"age" = 74, #"gender" = "screen"],
					        [#"F1" = 325, #"customer_id" = 6701, #"age" = 79, #"gender" = "worst"],
					        [#"F1" = 206, #"customer_id" = 5765, #"age" = 45, #"gender" = "awarded"],
					        [#"F1" = 58, #"customer_id" = 4814, #"age" = 28, #"gender" = "consider"],
					        [#"F1" = 70, #"customer_id" = 6881, #"age" = 64, #"gender" = "ph"],
					        [#"F1" = 134, #"customer_id" = 9817, #"age" = 63, #"gender" = "requested"],
					        [#"F1" = 112, #"customer_id" = 9143, #"age" = 26, #"gender" = "personally"],
					        [#"F1" = 282, #"customer_id" = 8066, #"age" = 26, #"gender" = "carried"],
					        [#"F1" = 461, #"customer_id" = 1329, #"age" = 84, #"gender" = "box"],
					        [#"F1" = 829, #"customer_id" = 4019, #"age" = 60, #"gender" = "books"],
					        [#"F1" = 956, #"customer_id" = 8169, #"age" = 28, #"gender" = "failure"],
					        [#"F1" = 704, #"customer_id" = 3561, #"age" = 69, #"gender" = "pupils"],
					        [#"F1" = 703, #"customer_id" = 6225, #"age" = 83, #"gender" = "un"],
					        [#"F1" = 460, #"customer_id" = 1088, #"age" = 73, #"gender" = "conclusions"],
					        [#"F1" = 306, #"customer_id" = 6452, #"age" = 85, #"gender" = "posters"],
					        [#"F1" = 903, #"customer_id" = 9463, #"age" = 38, #"gender" = "speakers"],
					        [#"F1" = 66, #"customer_id" = 1149, #"age" = 84, #"gender" = "immigration"],
					        [#"F1" = 159, #"customer_id" = 8204, #"age" = 98, #"gender" = "adams"],
					        [#"F1" = 502, #"customer_id" = 7977, #"age" = 36, #"gender" = "buildings"],
					        [#"F1" = 11, #"customer_id" = 4336, #"age" = 48, #"gender" = "agent"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"F1", Int64.Type},
					        {"customer_id", type text},
					        {"age", Int64.Type},
					        {"gender", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table