table 'Profit Bin Size'
	lineageTag: cba20fb6-56d3-4db7-8b08-02f62c85c8e0

	measure 'Profit Bin Size Value' = SELECTEDVALUE('Profit Bin Size'[Profit Bin Size], 50)
		lineageTag: 353b1402-c281-4ca2-8127-4830ea0fb773

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Profit Bin Size'
		dataType: double
		formatString: 0
		lineageTag: 4f2831c7-ed2f-4d04-bd54-06a9acc30c88
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Profit Bin Size' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_Id = 2e089f6ece5b41858a9ccb2a7e99c925

