table 'Sample - Superstore'
	lineageTag: dddab367-6ba6-49c5-8ec2-352122ea0038

	measure 'Metric Swap Calc (CY)' = VAR metric = SELECTEDVALUE('Metric Swap Param'[Display As]) RETURN SWITCH( metric, "Sales", SUM('Sample - Superstore'[Sales CY]), "Profit", SUM('Sample - Superstore'[Profit CY]), "Orders", 'Sample - Superstore'[Total Orders CY] )
		formatString: 0
		lineageTag: 531bf602-1c16-4253-a6d6-53ae801c4152

	measure Orders = DISTINCTCOUNT('Sample - Superstore'[Order ID])
		formatString: 0
		lineageTag: 42d164eb-f107-4e17-a0b8-575b1a296ece

	measure 'Profit Ratio' = SUM('Sample - Superstore'[Profit]) / SUM('Sample - Superstore'[Sales])
		formatString: 0
		lineageTag: b52438c7-a9e1-45fb-8167-0cced34efdc3

	measure 'Year for Label' = SELECTEDVALUE('Year'[Display As])
		formatString: 0
		lineageTag: b5499706-04d3-4e1f-9380-d4b9c2fed8b9

	measure 'Sales CY' = VAR selYear = SELECTEDVALUE('Year'[Display As]) RETURN CALCULATE(SUM('Sample - Superstore'[Sales]), YEAR('Sample - Superstore'[Order Date]) = selYear)
		formatString: 0
		lineageTag: b2549248-8ca0-4afc-8021-53ba057a4eea

	measure 'Sales % Chg' = ( SUM('Sample - Superstore'[Sales CY]) - SUM('Sample - Superstore'[Sales PY]) ) / SUM('Sample - Superstore'[Sales PY])
		formatString: 0
		lineageTag: e2ea0ed8-74e3-406d-8e50-b11acd9cf3cc

	measure 'Prev Year (BANs)' = SELECTEDVALUE('Year'[Display As]) - 1
		formatString: 0
		lineageTag: 73419417-b713-48a9-a6ff-ba2d9c98b2eb

	measure 'Max Metric CY' = VAR current = MAX('Sample - Superstore'[Metric Swap Calc (CY)]) VAR maxMetric = CALCULATE(MAX('Sample - Superstore'[Metric Swap Calc (CY)]), ALLSELECTED('Sample - Superstore')) RETURN current = maxMetric
		lineageTag: bef919d5-a0c2-4534-9d2a-70d70e78e906

	measure 'Top N Filter (Customer)' = VAR topN = SELECTEDVALUE('Top Customers'[Display As]) VAR customerRank = RANKX( ALLSELECTED('Sample - Superstore'[Customer Name]), CALCULATE(SUM('Sample - Superstore'[Sales])), , DESC, DENSE ) RETURN customerRank <= topN
		lineageTag: 8cb2f4d7-b993-4573-b875-551eb4b1a61b

	measure 'Metric Swap Calc (Arrow NEG) (Label)' = VAR metric = SELECTEDVALUE('Metric Swap Param'[Display As]) RETURN SWITCH( metric, "Sales", 'Sample - Superstore'[Sales % Chg (Neg)], "Profit", 'Sample - Superstore'[Profit % Chg (Neg)], "Orders", 'Sample - Superstore'[Total Orders % Chg (Neg)], BLANK() )
		lineageTag: ec2694a2-3483-4412-a7e7-30bc030a7653

	measure 'Metric Swap Calc (Arrow POS) (Label)' = VAR metric = SELECTEDVALUE('Metric Swap Param'[Display As]) RETURN SWITCH( metric, "Sales", 'Sample - Superstore'[Sales % Chg (Pos)], "Profit", 'Sample - Superstore'[Profit % Chg (Pos)], "Orders", 'Sample - Superstore'[Total Orders % Chg (Pos)], BLANK() )
		lineageTag: f6e84ff4-98be-4925-a861-6db36008a2b7

	measure 'Metric Swap Calc (% Chg) (Label)' = VAR metric = SELECTEDVALUE('Metric Swap Param'[Display As]) RETURN SWITCH( metric, "Sales", FORMAT(ROUND('Sample - Superstore'[Sales % Chg] * 100, 1), "0.0") & "%", "Profit", FORMAT(ROUND('Sample - Superstore'[Profit % Chg] * 100, 1), "0.0") & "%", "Orders", FORMAT(ROUND('Sample - Superstore'[Total Orders % Chg] * 100, 1), "0.0") & "%", BLANK() )
		lineageTag: 4e1b7e8f-55fb-474c-aac5-4162dc6c6803

	measure 'Metric Swap Calc (PY) (Label)' = VAR metric = SELECTEDVALUE('Metric Swap Param'[Display As]) RETURN SWITCH( metric, "Sales", "$" & FORMAT(ROUND(SUM('Sample - Superstore'[Sales PY]) / 1000, 1), "0.0") & "K", "Profit", "$" & FORMAT(ROUND(SUM('Sample - Superstore'[Profit PY]) / 1000, 1), "0.0") & "K", "Orders", FORMAT('Sample - Superstore'[Total Orders PY], "0"), BLANK() )
		lineageTag: 4c5a2c2e-97a8-44f2-a6c6-14c4c1ba28cb

	measure 'Metric Swap Calc (PY)' = VAR metric = SELECTEDVALUE('Metric Swap Param'[Display As]) RETURN SWITCH( metric, "Sales", SUM('Sample - Superstore'[Sales PY]), "Profit", SUM('Sample - Superstore'[Profit PY]), "Orders", 'Sample - Superstore'[Total Orders PY], BLANK() )
		formatString: 0
		lineageTag: 21b4370d-3452-456e-898a-a4089d610955

	measure 'Metric Swap Calc (CY) (Label)' = VAR metric = SELECTEDVALUE('Metric Swap Param'[Display As]) RETURN SWITCH( metric, "Sales", "$" & FORMAT(ROUND(SUM('Sample - Superstore'[Sales CY]) / 1000, 1), "0.0") & "K", "Profit", "$" & FORMAT(ROUND(SUM('Sample - Superstore'[Profit CY]) / 1000, 1), "0.0") & "K", "Orders", FORMAT('Sample - Superstore'[Total Orders CY], "0"), BLANK() )
		lineageTag: af31f9e3-3998-4b27-b3e3-3eeb96271f02

	measure 'Total Customers % Chg (Neg)' = IF('Sample - Superstore'[Total Customers % Chg] < 0, "▼", BLANK())
		lineageTag: 7038be3f-b44f-48ac-8576-ea3362a1feed

	measure 'Profit % Chg (Neg)' = IF('Sample - Superstore'[Profit % Chg] < 0, "▼", BLANK())
		lineageTag: 2b08a192-7ab2-49ba-8ef6-775814d3acd8

	measure 'Total Customers % Chg (Pos)' = IF('Sample - Superstore'[Total Customers % Chg] > 0, "▲", BLANK())
		lineageTag: aeed195c-ac2f-46cf-a48b-1aa67e7b4059

	measure 'Profit % Chg (Pos)' = IF('Sample - Superstore'[Profit % Chg] > 0, "▲", BLANK())
		lineageTag: b89eea24-9116-47ac-a688-0fbde17f9518

	measure 'Profit Ratio (Filter)' = IF('Sample - Superstore'[Profit Ratio] < 0, TRUE(), FALSE())
		lineageTag: 8847b35f-7a5d-4c00-a471-4a9abc09e6e2

	measure 'Sales % Chg (Neg)' = IF('Sample - Superstore'[Sales % Chg] < 0, "▼", BLANK())
		lineageTag: 06c788b4-823c-4d13-b4f7-4354705f00a7

	measure 'Profit % Chg' = ( SUM('Sample - Superstore'[Profit CY]) - SUM('Sample - Superstore'[Profit PY]) ) / SUM('Sample - Superstore'[Profit PY])
		formatString: 0
		lineageTag: 47903ec8-43c5-4430-a6ef-02c30f5b886a

	measure 'Sales PY' = VAR _selYear = SELECTEDVALUE('Year'[Display As]) RETURN CALCULATE( SUM('Sample - Superstore'[Sales]), YEAR('Sample - Superstore'[Order Date]) = _selYear - 1 )
		formatString: 0
		lineageTag: 0708ab83-feb4-4ac0-ae63-b97e07066eb7

	measure 'Profit CY' = VAR _selYear = SELECTEDVALUE('Year'[Display As]) RETURN CALCULATE( SUM('Sample - Superstore'[Profit]), YEAR('Sample - Superstore'[Order Date]) = _selYear )
		formatString: 0
		lineageTag: 6af0cf99-1641-4609-938f-9e9eb7a70cd1

	measure 'Total Customers CY' = VAR _selYear = SELECTEDVALUE('Year'[Display As]) RETURN CALCULATE( DISTINCTCOUNT('Sample - Superstore'[Customer Name]), YEAR('Sample - Superstore'[Order Date]) = _selYear )
		formatString: 0
		lineageTag: d48e1627-547c-41ea-abf4-ccde85c4b23b

	measure 'Profit PY' = IF(YEAR('Sample - Superstore'[Order Date]) = SELECTEDVALUE('Year'[Display As]) - 1, 'Sample - Superstore'[Profit])
		formatString: 0
		lineageTag: dd27f26e-7899-45b6-987a-38bcc189a318

	measure 'Top N Filter (Manufacturer)' = VAR TopN = SELECTEDVALUE('Top Manufacturers'[Display As]) RETURN IF(RANKX(ALLSELECTED('Sample - Superstore'), 0, , ASC) <= TopN, TRUE(), FALSE())
		lineageTag: 94253627-3c0d-40a5-aa9f-f9bc383c417e

	measure 'Total Orders % Chg (Neg)' = IF('Sample - Superstore'[Total Orders % Chg] < 0, "▼")
		lineageTag: 13d80749-9e48-4cd4-b010-ba78b123992d

	measure 'Total Orders % Chg (Pos)' = IF('Sample - Superstore'[Total Orders % Chg] > 0, "▲")
		lineageTag: ec7bb979-bf29-4697-a76f-66831d3f8860

	measure 'Total Orders % Chg' = ('Sample - Superstore'[Total Orders CY] - 'Sample - Superstore'[Total Orders PY]) / 'Sample - Superstore'[Total Orders PY]
		formatString: 0
		lineageTag: ae68cc81-23c4-4c38-8006-d29740525f48

	measure 'Total Customers PY' = VAR selYear = SELECTEDVALUE('Year'[Display As]) RETURN CALCULATE( DISTINCTCOUNT('Sample - Superstore'[Customer Name]), FILTER('Sample - Superstore', YEAR('Sample - Superstore'[Order Date]) = selYear - 1) )
		formatString: 0
		lineageTag: 45cb0e6f-ce2c-4d9d-8d7a-a429255b08ab

	measure 'Total Orders CY' = VAR selYear = SELECTEDVALUE('Year'[Display As]) RETURN CALCULATE( DISTINCTCOUNT('Sample - Superstore'[Order ID]), FILTER( 'Sample - Superstore', YEAR('Sample - Superstore'[Order Date]) = selYear ) )
		formatString: 0
		lineageTag: 719a55a7-35c0-4112-af9b-04e6fba33714

	measure 'Total Orders PY' = VAR selYear = SELECTEDVALUE('Year'[Display As]) - 1 RETURN CALCULATE( DISTINCTCOUNT('Sample - Superstore'[Order ID]), FILTER( 'Sample - Superstore', YEAR('Sample - Superstore'[Order Date]) = selYear ) )
		formatString: 0
		lineageTag: 67f04c26-e495-40d7-ac84-1ed2564a81e7

	measure 'Selected Metric (Sales) Colour' = VAR sel = SELECTEDVALUE('Metric Swap Param'[Display As]) RETURN IF(sel = "Sales", TRUE(), FALSE())
		lineageTag: 449fb773-f429-4924-a0a5-fcaee238b63d

	measure 'Selected Year' = VAR sel = SELECTEDVALUE('Year'[Display As]) VAR rowYear = SELECTEDVALUE('Sample - Superstore'[Year]) RETURN sel = rowYear
		lineageTag: e5047b93-717d-4bc5-b2ab-c4decc3fa771

	measure Status = VAR currentOrder = SELECTEDVALUE('Sample - Superstore'[Order ID]) VAR shipMax = CALCULATE(MAX('Sample - Superstore'[Ship Date]), ALL('Sample - Superstore'), 'Sample - Superstore'[Order ID] = currentOrder) VAR maxOrderDate = [Max Order Date] RETURN IF(shipMax <= maxOrderDate, "Complete", "Pending")
		lineageTag: a7c3dd50-6d53-4b8b-a215-351a3caf537f

	measure 'Max Order Date' = VAR overallMaxOrderDate = CALCULATE(MAX('Sample - Superstore'[Order Date]), ALL('Sample - Superstore')) RETURN EDATE(overallMaxOrderDate, -6)
		lineageTag: 12c04027-8532-4442-bbec-1bf1b1f88476

	measure 'Selected Metric (Profit) Colour' = SELECTEDVALUE('Metric Swap Param'[Display As]) = "Profit"
		lineageTag: c21e35c7-6d76-46a6-ac18-e6093087f3a5

	measure 'Selected Metric (Orders) Colour' = SELECTEDVALUE('Metric Swap Param'[Display As]) = "Orders"
		lineageTag: cee54669-526a-4af7-a93d-2330d89f0076

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 289ae6d3-f828-4cce-99e3-5373fd4a5f64
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: fddc0abd-39a5-4d49-8218-6c2423d72a36
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: datetime
		lineageTag: 16c70217-ee98-4526-baaa-d1e6c63643ba
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: datetime
		lineageTag: bbe19305-05b8-4ba0-ba16-06f4227d54c4
		summarizeBy: none
		sourceColumn: 'Ship Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: c5571855-efda-478a-8605-ccffee462866
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: a1f1fe16-50b1-4ff3-a817-79b959798f1d
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 578f4ee2-52fd-4735-a442-957cd83c2bfd
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 0f0001a0-01d4-45a2-92ac-b3b9c6259efa
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Country/Region'
		dataType: string
		lineageTag: e9a61275-2328-4b4d-a8da-f33f9453aa3f
		summarizeBy: none
		sourceColumn: 'Country/Region'

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 5652129b-f37e-4ddd-bf81-f760cdb02388
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'State/Province'
		dataType: string
		lineageTag: fcec275e-962d-4a68-a793-cf5ae299d2b9
		summarizeBy: none
		sourceColumn: 'State/Province'

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: 61b2d5e5-f7ce-4473-81f4-db94851a80b2
		summarizeBy: none
		sourceColumn: 'Postal Code'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: a1250464-4417-4d2c-b3cc-9e544ee3e07b
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: abb827ef-7a7c-4fa3-a14c-70592869ba8a
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 5e06467a-6bdd-46e0-858d-5d0d9ce67cc0
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: be01cea2-7ff2-4510-9c31-233198b2cfd7
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 7230314a-a75b-405f-ae3d-0f42f397f148
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: General Number
		lineageTag: c50042f5-4ea4-4f27-b3ba-6261cf44a0a7
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: f2a27e3d-6cd5-499c-8784-18ef6b3a46c8
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: General Number
		lineageTag: bce780a5-6b63-4ccc-a4a0-bbd7c025d12b
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		formatString: General Number
		lineageTag: 6e7d5ccc-62e5-4a42-89da-463c757491a1
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Last updated' = TODAY()
		lineageTag: 34906b80-cb87-4916-a75c-db2773cfe582
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Dummy Highlight' = "Dummy"
		lineageTag: 7185846e-95e1-4777-ada5-099fc1d70cff
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Segments Abbrev' = IF('Sample - Superstore'[Segment] = "Consumer", "CON", IF('Sample - Superstore'[Segment] = "Corporate", "COR", "HO"))
		lineageTag: 7534def8-b874-4ce4-9d4f-f879179cfe58
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Profit (bin)' = 'Sample - Superstore'[Profit]
		formatString: 0
		lineageTag: a3c7ef66-c209-4721-b73d-e94cd5b50fd7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Year = YEAR('Sample - Superstore'[Order Date])
		formatString: 0
		lineageTag: 94bd5555-1a2b-4008-878d-7aeebeb0799b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 1 = 1
		formatString: 0
		lineageTag: fdaa5ad5-6af5-46cb-930c-304c1bfe2173
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Profit Ratio (Table Colour)' = 'Sample - Superstore'[Profit Ratio] > 0
		lineageTag: 5487600e-deb6-486a-b867-0f95c4ebc19a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Total Customers % Chg' = ('Sample - Superstore'[Total Customers CY] - 'Sample - Superstore'[Total Customers PY]) / 'Sample - Superstore'[Total Customers PY]
		lineageTag: d8e64cf2-c0d3-4a0c-b07f-a4aa235ba34d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sales % Chg (Pos)' = IF('Sample - Superstore'[Sales % Chg] > 0, "▲", BLANK())
		lineageTag: e6f7bb24-ba3f-460f-8e27-f9066b730be5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Sample - Superstore' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Row ID" = 3893, #"Order ID" = 5988, #"Order Date" = #date(2023, 11, 24), #"Ship Date" = #date(2022, 8, 23), #"Ship Mode" = "149.6.101.126", #"Customer ID" = 6289, #"Customer Name" = "Demetrice Clay", #"Segment" = "contain", #"Country/Region" = "Mississippi", #"City" = "Woodridge", #"State/Province" = "Utah", #"Postal Code" = "63164", #"Region" = "Arizona", #"Product ID" = 6179, #"Category" = "stable", #"Sub-Category" = "own", #"Product Name" = "Katelynn Lloyd", #"Sales" = 616.64, #"Quantity" = 164, #"Discount" = 290.34, #"Profit" = 214.15],
					        [#"Row ID" = 861, #"Order ID" = 7657, #"Order Date" = #date(2023, 3, 26), #"Ship Date" = #date(2020, 10, 24), #"Ship Mode" = "189.74.234.231", #"Customer ID" = 7550, #"Customer Name" = "Tasia Sutton", #"Segment" = "outdoors", #"Country/Region" = "Maryland", #"City" = "New Britain", #"State/Province" = "Arkansas", #"Postal Code" = "82745", #"Region" = "Maryland", #"Product ID" = 2069, #"Category" = "magnetic", #"Sub-Category" = "locations", #"Product Name" = "Lemuel Holt", #"Sales" = 721.4, #"Quantity" = 582, #"Discount" = 29.31, #"Profit" = 820.55],
					        [#"Row ID" = 7715, #"Order ID" = 7020, #"Order Date" = #date(2023, 12, 8), #"Ship Date" = #date(2024, 10, 23), #"Ship Mode" = "5.161.144.147", #"Customer ID" = 4474, #"Customer Name" = "Gabriel Head", #"Segment" = "yellow", #"Country/Region" = "Wisconsin", #"City" = "Sandusky", #"State/Province" = "North Carolina", #"Postal Code" = "99690", #"Region" = "Arkansas", #"Product ID" = 3395, #"Category" = "allow", #"Sub-Category" = "lived", #"Product Name" = "Reginald Dean", #"Sales" = 576.21, #"Quantity" = 640, #"Discount" = 893.45, #"Profit" = 45.03],
					        [#"Row ID" = 7159, #"Order ID" = 9574, #"Order Date" = #date(2024, 6, 12), #"Ship Date" = #date(2023, 12, 14), #"Ship Mode" = "47.211.16.188", #"Customer ID" = 3909, #"Customer Name" = "Gregory Carroll", #"Segment" = "thousand", #"Country/Region" = "West Virginia", #"City" = "Monterey", #"State/Province" = "Tennessee", #"Postal Code" = "28593", #"Region" = "Wyoming", #"Product ID" = 7890, #"Category" = "ask", #"Sub-Category" = "alphabetical", #"Product Name" = "Shemika Mcfarland", #"Sales" = 989.42, #"Quantity" = 947, #"Discount" = 645.61, #"Profit" = 923.74],
					        [#"Row ID" = 9731, #"Order ID" = 4333, #"Order Date" = #date(2020, 3, 15), #"Ship Date" = #date(2021, 2, 17), #"Ship Mode" = "183.177.43.29", #"Customer ID" = 2138, #"Customer Name" = "Lloyd Gillespie", #"Segment" = "wisdom", #"Country/Region" = "Oklahoma", #"City" = "Mill Creek", #"State/Province" = "Tennessee", #"Postal Code" = "56326", #"Region" = "Idaho", #"Product ID" = 2457, #"Category" = "employee", #"Sub-Category" = "this", #"Product Name" = "Micha James", #"Sales" = 268.98, #"Quantity" = 219, #"Discount" = 683.1, #"Profit" = 376.36]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Row ID", Int64.Type},
					        {"Order ID", type text},
					        {"Order Date", type date},
					        {"Ship Date", type date},
					        {"Ship Mode", type text},
					        {"Customer ID", type text},
					        {"Customer Name", type text},
					        {"Segment", type text},
					        {"Country/Region", type text},
					        {"City", type text},
					        {"State/Province", type text},
					        {"Postal Code", type text},
					        {"Region", type text},
					        {"Product ID", type text},
					        {"Category", type text},
					        {"Sub-Category", type text},
					        {"Product Name", type text},
					        {"Sales", type number},
					        {"Quantity", Int64.Type},
					        {"Discount", type number},
					        {"Profit", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table