table 'Discount Threshold'
	lineageTag: 70115ef6-d931-4f04-95ea-b41b9f5d455f

	measure 'Discount Threshold Value' = SELECTEDVALUE('Discount Threshold'[Discount Threshold], 0.0)
		lineageTag: 6bea4f89-e280-4908-8151-79edf47f93c7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Discount Threshold'
		dataType: double
		formatString: 0
		lineageTag: bdb956e2-8b49-4a89-bbac-9cb614656aa9
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Discount Threshold' = calculated
		mode: import
		source = GENERATESERIES(0.0, 0.5)

	annotation PBI_Id = f1cbf162095f4134812c68c170561975

