table 'Orders_Orders+ (Sample - Superstore)'
	lineageTag: 03befc7a-c6e7-475b-a97d-d33853cbd70c

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 1e5463d5-f7a4-454a-a24a-516057076372
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: ec8d8c74-0b5b-42aa-8558-7eb8b149e4fd
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: datetime
		lineageTag: a698c853-0b25-4bf1-9c31-2c407c7e1e54
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: datetime
		lineageTag: 0b56c78e-cd1d-4415-9bf6-b912cf51a9c6
		summarizeBy: none
		sourceColumn: 'Ship Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: d0a35319-c958-4b14-8aef-ede05718f146
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: f2315552-da1e-4ca1-8840-d5d3ee787f4f
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 2d068f1f-cb41-4be6-9891-84e9d8ae5662
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 74e6e652-03f1-4be5-b699-a52afb0f438a
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Country/Region'
		dataType: string
		lineageTag: d855782f-a49b-44d9-ab72-c619cbd5afbf
		summarizeBy: none
		sourceColumn: 'Country/Region'

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 06aaeb6c-e2d4-4f6f-9639-6a466be6ab05
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 01622c6e-2d52-4536-83a2-1a9595cd52d0
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 55ba049b-b73b-47c4-99f2-61dfe4a67306
		summarizeBy: sum
		sourceColumn: 'Postal Code'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 2610d98e-75f2-40a0-83eb-ccd4083fe217
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: f2ffdaca-fec2-4979-b2db-0c34f32995ce
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 3ea257dd-507f-4285-a9ad-2acdecde07a2
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: c0617907-baed-4700-b39d-d19b9c354576
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 3f70f66f-ba0f-4ffd-8102-3e150b830b16
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: General Number
		lineageTag: 96676fee-823c-457b-aa70-c2c3eca14229
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: be823bbd-37c7-4aef-ad79-fe7396760003
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: General Number
		lineageTag: 109e04cf-47f2-4ef1-9612-0b13d2add64e
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		formatString: General Number
		lineageTag: b30ce3c7-97b8-48c8-a85f-83f1ef483d83
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Orders_Orders+ (Sample - Superstore)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Row ID" = 4316, #"Order ID" = 9076, #"Order Date" = #date(2022, 9, 27), #"Ship Date" = #date(2020, 3, 28), #"Ship Mode" = "46.21.36.14", #"Customer ID" = 3029, #"Customer Name" = "Jay Barr", #"Segment" = "lib", #"Country/Region" = "Hawaii", #"City" = "McMinnville", #"State" = "Virginia", #"Postal Code" = 637, #"Region" = "West Virginia", #"Product ID" = 7977, #"Category" = "char", #"Sub-Category" = "chosen", #"Product Name" = "Reyes Good", #"Sales" = 532.98, #"Quantity" = 996, #"Discount" = 733.77, #"Profit" = 915.89],
					        [#"Row ID" = 1502, #"Order ID" = 1899, #"Order Date" = #date(2021, 8, 28), #"Ship Date" = #date(2024, 2, 7), #"Ship Mode" = "108.117.216.180", #"Customer ID" = 6537, #"Customer Name" = "Dewitt Moreno", #"Segment" = "returns", #"Country/Region" = "Illinois", #"City" = "Nacogdoches", #"State" = "South Dakota", #"Postal Code" = 717, #"Region" = "Idaho", #"Product ID" = 7762, #"Category" = "similar", #"Sub-Category" = "behind", #"Product Name" = "Stacy Murphy", #"Sales" = 845.17, #"Quantity" = 202, #"Discount" = 261.2, #"Profit" = 633.2],
					        [#"Row ID" = 9286, #"Order ID" = 2917, #"Order Date" = #date(2023, 5, 3), #"Ship Date" = #date(2020, 10, 1), #"Ship Mode" = "183.198.29.252", #"Customer ID" = 2518, #"Customer Name" = "Santos Rivas", #"Segment" = "distinct", #"Country/Region" = "Mississippi", #"City" = "West Lafayette", #"State" = "Delaware", #"Postal Code" = 86, #"Region" = "Washington", #"Product ID" = 1524, #"Category" = "downloads", #"Sub-Category" = "disabilities", #"Product Name" = "Rickey Collins", #"Sales" = 50.24, #"Quantity" = 297, #"Discount" = 458.74, #"Profit" = 92.51],
					        [#"Row ID" = 2634, #"Order ID" = 2494, #"Order Date" = #date(2023, 6, 16), #"Ship Date" = #date(2020, 4, 4), #"Ship Mode" = "200.58.23.190", #"Customer ID" = 8957, #"Customer Name" = "Karren Fischer", #"Segment" = "purpose", #"Country/Region" = "Missouri", #"City" = "East Ridge", #"State" = "North Dakota", #"Postal Code" = 331, #"Region" = "Florida", #"Product ID" = 2410, #"Category" = "dir", #"Sub-Category" = "nice", #"Product Name" = "Floretta Osborn", #"Sales" = 148.87, #"Quantity" = 296, #"Discount" = 482.16, #"Profit" = 751.7],
					        [#"Row ID" = 9572, #"Order ID" = 4884, #"Order Date" = #date(2022, 9, 6), #"Ship Date" = #date(2024, 5, 19), #"Ship Mode" = "56.140.31.42", #"Customer ID" = 1801, #"Customer Name" = "Bertram Witt", #"Segment" = "basic", #"Country/Region" = "Kansas", #"City" = "Moore", #"State" = "Mississippi", #"Postal Code" = 228, #"Region" = "Ohio", #"Product ID" = 3147, #"Category" = "restoration", #"Sub-Category" = "intel", #"Product Name" = "Bradford Hernandez", #"Sales" = 280.2, #"Quantity" = 239, #"Discount" = 33.33, #"Profit" = 935.05]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Row ID", Int64.Type},
					        {"Order ID", type text},
					        {"Order Date", type date},
					        {"Ship Date", type date},
					        {"Ship Mode", type text},
					        {"Customer ID", type text},
					        {"Customer Name", type text},
					        {"Segment", type text},
					        {"Country/Region", type text},
					        {"City", type text},
					        {"State", type text},
					        {"Postal Code", Int64.Type},
					        {"Region", type text},
					        {"Product ID", type text},
					        {"Category", type text},
					        {"Sub-Category", type text},
					        {"Product Name", type text},
					        {"Sales", type number},
					        {"Quantity", Int64.Type},
					        {"Discount", type number},
					        {"Profit", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table