table 'Orders+ (Sample - Superstore)'
	lineageTag: 131e75ce-4590-4658-b560-1a4b979e3dbd

	measure 'Profit Visibility' = IF(SUM('Orders+ (Sample - Superstore)'[Profit]) >= SELECTEDVALUE('Min Profit Display'[Display As]), "Show", "Hide")
		lineageTag: fc80a408-3bef-4897-8d44-d9b77e8da2ec

	measure 'Total Sales' = SUM('Orders+ (Sample - Superstore)'[Sales])
		formatString: 0
		lineageTag: c7d157c0-d343-44be-9d6a-e9a20568a3fe

	measure 'Total Profit' = SUM('Orders+ (Sample - Superstore)'[Profit])
		formatString: 0
		lineageTag: 107e59f0-3725-451c-9aa8-72a8bd75b7a2

	measure 'Profit Ratio' = SUM('Orders+ (Sample - Superstore)'[Profit]) / SUM('Orders+ (Sample - Superstore)'[Sales])
		formatString: 0
		lineageTag: 005a7f79-b039-4202-8504-172ba524f43c

	measure 'Normalized Profit Ratio (%)' = [Profit Ratio] * 100
		formatString: 0
		lineageTag: 84c030fc-5fff-4572-a6e1-858d2219c637

	measure 'Sales After Discount' = SUM('Orders+ (Sample - Superstore)'[Sales]) * (1 - AVERAGE('Orders+ (Sample - Superstore)'[Discount]))
		formatString: 0
		lineageTag: 323b1ef7-4f24-4609-a797-9a1f7c3477f5

	measure 'Customer Total Sales (LOD)' = VAR result = CALCULATE( SUM('Orders+ (Sample - Superstore)'[Sales]), ALLEXCEPT('Orders+ (Sample - Superstore)', 'Orders+ (Sample - Superstore)'[Customer ID]) ) RETURN result
		formatString: 0
		lineageTag: b567e4d2-24c5-4669-9df9-1bf8aaa44986

	measure 'Region Average Profit (LOD)' = VAR result = CALCULATE( AVERAGE('Orders+ (Sample - Superstore)'[Profit]), ALLEXCEPT('Orders+ (Sample - Superstore)', 'Orders+ (Sample - Superstore)'[Region]) ) RETURN result
		formatString: 0
		lineageTag: 74d09ea0-5027-402c-9a81-680fce9c5079

	measure 'Order Level Sales (LOD)' = CALCULATE( SUM('Orders+ (Sample - Superstore)'[Sales]), ALLEXCEPT( 'Orders+ (Sample - Superstore)', 'Orders+ (Sample - Superstore)'[Order ID] ) )
		formatString: 0
		lineageTag: 7271b35d-1e8d-4305-84ae-d8d2f415ddd3

	measure 'Running Sales' = VAR CurrentSales = SUM('Orders+ (Sample - Superstore)'[Sales]) RETURN CALCULATE( SUM('Orders+ (Sample - Superstore)'[Sales]), FILTER( ALLSELECTED('Orders+ (Sample - Superstore)'), SUM('Orders+ (Sample - Superstore)'[Sales]) <= CurrentSales ) )
		formatString: 0
		lineageTag: 58afcbb0-4d92-4064-a2f9-46a7ede5baf4

	measure '% of Total Sales' = DIVIDE( SUM('Orders+ (Sample - Superstore)'[Sales]), CALCULATE( SUM('Orders+ (Sample - Superstore)'[Sales]), ALLSELECTED('Orders+ (Sample - Superstore)') ), 0 )
		formatString: 0
		lineageTag: 26d9b801-9f7d-44d1-a040-ecc37a9c0583

	measure Calculation2 = CALCULATE( MINX( 'Orders+ (Sample - Superstore)', YEAR('Orders+ (Sample - Superstore)'[Order Date]) ), ALLEXCEPT( 'Orders+ (Sample - Superstore)', 'Orders+ (Sample - Superstore)'[Customer ID] ) )
		formatString: 0
		lineageTag: 356f251d-30d0-40e6-8409-8e6db4178c56

	measure Calculation3 = VAR CurrentSales = SUM('Orders+ (Sample - Superstore)'[Sales]) VAR WindowTable = FILTER( ALLSELECTED('Orders+ (Sample - Superstore)'), SUM('Orders+ (Sample - Superstore)'[Sales]) <= CurrentSales ) VAR WindowSum = CALCULATE(SUM('Orders+ (Sample - Superstore)'[Sales]), WindowTable) VAR WindowCount = COUNTROWS(WindowTable) RETURN DIVIDE(WindowSum, WindowCount, 0)
		formatString: 0
		lineageTag: 74dc3cae-d293-497b-b7bf-75506eb2ec3c

	measure Calculation4 = DIVIDE( CALCULATE( SUM('Orders+ (Sample - Superstore)'[Sales]), ALLEXCEPT('Orders+ (Sample - Superstore)', 'Orders+ (Sample - Superstore)'[Customer ID], 'Orders+ (Sample - Superstore)'[Category]) ), CALCULATE( SUM('Orders+ (Sample - Superstore)'[Sales]), ALLEXCEPT('Orders+ (Sample - Superstore)', 'Orders+ (Sample - Superstore)'[Customer ID]) ), 0 )
		formatString: 0
		lineageTag: 3457baf0-3806-4441-a5f4-5338d4f3f13e

	measure 'Discount Level' = VAR currentDiscount = SELECTEDVALUE('Orders+ (Sample - Superstore)'[Discount]) VAR threshold = SELECTEDVALUE('Discount Threshold'[Display As]) RETURN IF(currentDiscount > threshold, "High", "Low")
		lineageTag: 2e46ceef-103f-4ac1-83f8-45b42b79f062

	measure 'Selected Region Flag' = VAR currentRegion = SELECTEDVALUE('Orders+ (Sample - Superstore)'[Region]) VAR selected = SELECTEDVALUE('Select Region'[Display As]) RETURN IF(currentRegion = selected, "Selected", "Other")
		lineageTag: b692176c-506b-40d0-9668-65261ce96d34

	measure Calculation1 = VAR __cust = SELECTEDVALUE('Orders+ (Sample - Superstore)'[Customer ID]) VAR __minYear = MINX( FILTER( ALL('Orders+ (Sample - Superstore)'), 'Orders+ (Sample - Superstore)'[Customer ID] = __cust ), YEAR('Orders+ (Sample - Superstore)'[Order Date]) ) RETURN "Joined in " & FORMAT(__minYear, "0")
		lineageTag: c6b83802-3271-4794-98da-3821878a316c

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 68a42603-aeb5-41d1-ba31-2500f93dbcbb
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: d56801ca-6e97-4e9b-8ed8-46099fa1e5b9
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: datetime
		lineageTag: 5b3b7119-4143-439e-886e-d7c504c1ff54
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: datetime
		lineageTag: 60c66208-6fee-48db-bc46-36947cab8c6c
		summarizeBy: none
		sourceColumn: 'Ship Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: d438a819-97b1-4f3f-9f0d-bcba4eb908b8
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 25b20c3c-b6c5-49dd-967c-bf3113e639d5
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 0a5028df-61f5-4dcf-82a4-6faa22701052
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 6810af08-4056-408d-8450-d03ef31e9030
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Country/Region'
		dataType: string
		lineageTag: 91059d27-eccd-4850-a68f-c894c7619d2e
		summarizeBy: none
		sourceColumn: 'Country/Region'

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: ac1916ba-29f5-46eb-9e18-e51ba38b1372
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: b56c9a79-84e2-4f4e-86e8-4f3811fee6ac
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 3c9181ce-2e10-47a1-aa0b-3b0c608aef10
		summarizeBy: sum
		sourceColumn: 'Postal Code'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 9cf11548-70e7-47a9-a1b8-b7e883809ccb
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 79ffe2c0-c02a-4586-9755-c22da8d963c2
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 7eb540e7-4e54-4b44-8001-65569c8bf158
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: 55dd379d-a44b-4cfa-b88f-184dd2d290dd
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 3dc0af6d-65e9-4bda-9228-2d72f5b44bd6
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: General Number
		lineageTag: 5330acee-5b4c-4af1-bfea-84c4b92efaf0
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 7c43a9f4-c705-4278-91e3-6f0648e54af0
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: General Number
		lineageTag: fcd53428-c4a9-4e92-9ee6-47be1f840970
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		formatString: General Number
		lineageTag: cf21c3ac-47dd-472e-b2fb-5ba7beaff852
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Person
		dataType: string
		lineageTag: c6abffa2-b48b-4c68-85a4-6bb7b038c8de
		summarizeBy: none
		sourceColumn: Person

		annotation SummarizationSetBy = Automatic

	column 'Region 1'
		dataType: string
		lineageTag: 7e29ca25-dea7-4c9c-af0a-b0dd36bcf36e
		summarizeBy: none
		sourceColumn: 'Region 1'

		annotation SummarizationSetBy = Automatic

	column Returned
		dataType: string
		lineageTag: ae1d9d77-9ec8-4ef5-a1d9-83f690ae8b27
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID 1'
		dataType: string
		lineageTag: 8890d20e-0a2b-40d3-8449-737cdd3a0f36
		summarizeBy: none
		sourceColumn: 'Order ID 1'

		annotation SummarizationSetBy = Automatic

	column 'Order Month Name' = FORMAT('Orders+ (Sample - Superstore)'[Order Date], "MMMM")
		lineageTag: c5da1be9-3880-488b-ac94-62e25dc79a0a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Customer First Name' = VAR fullName = 'Orders+ (Sample - Superstore)'[Customer Name] VAR pos = SEARCH(" ", fullName, 1, 0) RETURN IF(pos = 0, fullName, LEFT(fullName, pos - 1))
		lineageTag: 7f8a1462-a892-422b-9073-190faa9ef36a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Customer Last Name' = VAR fullName = 'Orders+ (Sample - Superstore)'[Customer Name] VAR pos = SEARCH(" ", fullName, 1, 0) RETURN IF(pos = 0, "", TRIM(MID(fullName, pos + 1, LEN(fullName))))
		lineageTag: ab14760b-7862-4ae1-bcc9-d01e3bd17dbe
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Profit Band' = IF('Orders+ (Sample - Superstore)'[Profit] > 0, "Profit", "Loss")
		lineageTag: 40436755-2fe9-4970-91ca-ccc2ac8265e4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Category Group' = SWITCH( TRUE(), 'Orders+ (Sample - Superstore)'[Category] = "Furniture", "Home", 'Orders+ (Sample - Superstore)'[Category] = "Office Supplies", "Office", "Other" )
		lineageTag: e7f77f5e-359a-47d2-9abb-ff019e61c65f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Sales Performance Label' = IF( 'Orders+ (Sample - Superstore)'[Profit Band] = "Profit" && 'Orders+ (Sample - Superstore)'[Discount Level] = "High", "Profit with High Discount", 'Orders+ (Sample - Superstore)'[Profit Band] )
		lineageTag: d74ec58b-3c4e-49ce-8e04-5978935e2c2a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Order Year' = YEAR('Orders+ (Sample - Superstore)'[Order Date])
		formatString: 0
		lineageTag: 17ee16a6-70c3-4996-9231-110da4321c5c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Orders+ (Sample - Superstore)' = m
		mode: import
		source =
				let 
					#"Source0" = Table.NestedJoin(#"Orders_Orders+ (Sample - Superstore)", {"Region"}, #"People_Orders+ (Sample - Superstore)", {"Region"}, "People_Orders+ (Sample - Superstore)", JoinKind.Inner),
					#"Expand0" = Table.ExpandTableColumn(#"Source0", "People_Orders+ (Sample - Superstore)", {"Person", "Region"}, {"Person", "Region 1"}),
					#"Source1" = Table.NestedJoin(#"Expand0", {"Order ID"}, #"Returns_Orders+ (Sample - Superstore)", {"Order ID"}, "Returns_Orders+ (Sample - Superstore)", JoinKind.Inner),
					#"Expand1" = Table.ExpandTableColumn(#"Source1", "Returns_Orders+ (Sample - Superstore)", {"Returned", "Order ID"}, {"Returned", "Order ID 1"})
					in #"Expand1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table