table 'People_Orders+ (Sample - Superstore)'
	lineageTag: 58df06ea-5a21-4139-9601-3131b61eae41

	column Person
		dataType: string
		lineageTag: c3ad386a-6b59-4c82-8eb5-91a814526c4f
		summarizeBy: none
		sourceColumn: Person

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 7a236424-c242-4b0c-a9dd-9d27516b3bf5
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition 'People_Orders+ (Sample - Superstore)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Person" = "somewhere", #"Region" = "Virginia"],
					        [#"Person" = "achievement", #"Region" = "Rhode Island"],
					        [#"Person" = "betting", #"Region" = "Indiana"],
					        [#"Person" = "sign", #"Region" = "Tennessee"],
					        [#"Person" = "walter", #"Region" = "Washington"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Person", type text},
					        {"Region", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table