table 'accounts+'
	lineageTag: adeb4f14-729f-4252-9844-905e4eca65d2

	measure 'Net Flow' = CALCULATE(SUM('accounts+'[Amount]), 'accounts+'[TransactionType] = "Deposit") - CALCULATE(SUM('accounts+'[Amount]), 'accounts+'[TransactionType] = "Withdrawal")
		formatString: 0
		lineageTag: 5a71f223-f9f7-433b-b3ca-fc4770ae9652

	measure 'Average account balance' = AVERAGE('accounts+'[CurrentBalance])
		formatString: 0
		lineageTag: b625269e-1670-471f-a227-6852730f6de2

	measure 'Active Accounts Count' = DISTINCTCOUNT('accounts+'[AccountID])
		formatString: 0
		lineageTag: 7db35779-7f0f-4421-92de-ce3316d9dc3d

	measure 'Accounts Above Threshold' = VAR threshold = SELECTEDVALUE('Balance Threshold'[Display As]) RETURN IF( 'accounts+'[CurrentBalance] >= threshold, 'accounts+'[AccountID], BLANK() )
		lineageTag: a1c44807-8d5f-4b70-bfc3-3d1c7b3b0356

	measure 'Selected Year Filter' = VAR SelectedYear = SELECTEDVALUE('Select Year'[Display As]) RETURN YEAR('accounts+'[TransactionDate]) = SelectedYear
		lineageTag: 2f61d246-7f84-4fd1-8ac4-b5bbabffcc3a

	column AccountID
		dataType: string
		lineageTag: 6d828774-d2d0-414a-9927-be630ad9cef0
		summarizeBy: none
		sourceColumn: AccountID

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: string
		lineageTag: 8b607244-6749-4824-af1e-4063059c34c5
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column BranchID
		dataType: string
		lineageTag: bb9be2a0-fe1d-4245-8916-112109962b53
		summarizeBy: none
		sourceColumn: BranchID

		annotation SummarizationSetBy = Automatic

	column AccountType
		dataType: string
		lineageTag: ce0a1d06-6904-46f1-bcb8-8d8fd03735ac
		summarizeBy: none
		sourceColumn: AccountType

		annotation SummarizationSetBy = Automatic

	column OpenDate
		dataType: datetime
		lineageTag: c49656f8-3c79-4aa0-acf0-95c187c2a84e
		summarizeBy: none
		sourceColumn: OpenDate

		annotation SummarizationSetBy = Automatic

	column CurrentBalance
		dataType: double
		formatString: General Number
		lineageTag: a5b91766-fa73-44a1-8c5e-e951188ad641
		summarizeBy: sum
		sourceColumn: CurrentBalance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'BranchID 1'
		dataType: string
		lineageTag: beb2dc82-2a5c-4cc5-ad3d-5a7e2c58cf80
		summarizeBy: none
		sourceColumn: 'BranchID 1'

		annotation SummarizationSetBy = Automatic

	column BranchName
		dataType: string
		lineageTag: 73ca0c60-9fe5-413d-bfdb-34cc177fc22f
		summarizeBy: none
		sourceColumn: BranchName

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 6f44c9d8-982e-42da-b9eb-77f3ba111f30
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Manager
		dataType: string
		lineageTag: e03c0253-f96c-4578-b285-8bc4b8a767bb
		summarizeBy: none
		sourceColumn: Manager

		annotation SummarizationSetBy = Automatic

	column 'CustomerID 1'
		dataType: string
		lineageTag: 62d19c5f-c8e2-4a1f-8faa-d07861eecf69
		summarizeBy: none
		sourceColumn: 'CustomerID 1'

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 4ab12964-d41b-4ff1-a1f3-b40ea46ce4da
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: b086d189-769c-40fb-b660-7d7fd313b4c7
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 23997502-cda0-46cd-bf65-65a5838a01a3
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column DOB
		dataType: datetime
		lineageTag: a710cf64-85e1-4524-8536-0fd2b08f1710
		summarizeBy: none
		sourceColumn: DOB

		annotation SummarizationSetBy = Automatic

	column 'City 1'
		dataType: string
		lineageTag: 83080490-d947-4543-8340-a9906ffb20e9
		summarizeBy: none
		sourceColumn: 'City 1'

		annotation SummarizationSetBy = Automatic

	column CustomerSince
		dataType: datetime
		lineageTag: 09c2adc2-7bc9-429f-a203-94fdf1162f36
		summarizeBy: none
		sourceColumn: CustomerSince

		annotation SummarizationSetBy = Automatic

	column TransactionID
		dataType: string
		lineageTag: e28b77e5-4714-4987-bb65-bdfbc8aadb55
		summarizeBy: none
		sourceColumn: TransactionID

		annotation SummarizationSetBy = Automatic

	column 'AccountID 1'
		dataType: string
		lineageTag: d856d392-b541-474e-90f0-294171a38424
		summarizeBy: none
		sourceColumn: 'AccountID 1'

		annotation SummarizationSetBy = Automatic

	column 'BranchID 2'
		dataType: string
		lineageTag: 7b905c48-851f-4dd5-bc76-73dd619c3703
		summarizeBy: none
		sourceColumn: 'BranchID 2'

		annotation SummarizationSetBy = Automatic

	column TransactionDate
		dataType: datetime
		lineageTag: 6674d689-5c06-4fb3-b191-e3567ddff6d2
		summarizeBy: none
		sourceColumn: TransactionDate

		annotation SummarizationSetBy = Automatic

	column TransactionType
		dataType: string
		lineageTag: bd49d52c-f590-4b26-870a-7a0cf656f793
		summarizeBy: none
		sourceColumn: TransactionType

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 1970ac61-a7ea-4133-b208-62ca153f206f
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: double
		formatString: General Number
		lineageTag: fe6bd443-b31a-4497-9d34-7ef158b5e0b1
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Deposits' = IF('accounts+'[TransactionType] = "Deposit", 'accounts+'[Amount])
		lineageTag: 26330460-90a5-4550-a6fc-3c236f1efb12
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Withdrawals' = IF('accounts+'[TransactionType] = "Withdrawal", 'accounts+'[Amount], BLANK())
		lineageTag: 34ad6837-5892-4de7-bccf-387244b0c2f1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Deposit amount' = IF('accounts+'[TransactionType] = "Deposit", 'accounts+'[Amount])
		lineageTag: ac313550-5f09-4296-9eb5-ddbf32f015e9
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Withdrawal Amount' = IF('accounts+'[TransactionType] = "Withdrawal", 'accounts+'[Amount], BLANK())
		lineageTag: 1b2f4400-7a7c-4424-8c2d-bd3a8aa6d6f6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'accounts+' = m
		mode: import
		source =
				let 
					#"Source0" = Table.NestedJoin(#"accounts.csv_accounts+", {"BranchID"}, #"accounts+_branches.csv", {"BranchID"}, "accounts+_branches.csv", JoinKind.Inner),
					#"Expand0" = Table.ExpandTableColumn(#"Source0", "accounts+_branches.csv", {"BranchID", "BranchName", "City", "Manager"}, {"BranchID 1", "BranchName", "City", "Manager"}),
					#"Source1" = Table.NestedJoin(#"Expand0", {"CustomerID"}, #"accounts+_customers.csv", {"CustomerID"}, "accounts+_customers.csv", JoinKind.LeftOuter),
					#"Expand1" = Table.ExpandTableColumn(#"Source1", "accounts+_customers.csv", {"CustomerID", "FirstName", "LastName", "Gender", "DOB", "City", "CustomerSince"}, {"CustomerID 1", "FirstName", "LastName", "Gender", "DOB", "City 1", "CustomerSince"}),
					#"Source2" = Table.NestedJoin(#"Expand1", {"AccountID"}, #"accounts+_transactions.csv", {"AccountID"}, "accounts+_transactions.csv", JoinKind.RightOuter),
					#"Expand2" = Table.ExpandTableColumn(#"Source2", "accounts+_transactions.csv", {"TransactionID", "AccountID", "BranchID", "TransactionDate", "TransactionType", "Category", "Amount"}, {"TransactionID", "AccountID 1", "BranchID 2", "TransactionDate", "TransactionType", "Category", "Amount"})
					in #"Expand2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table