table Orders
	lineageTag: a970e906-deca-486f-a519-29803c68f905

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: eb8c6f0c-7e41-48ae-9352-bd90a22474f2
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: f473739a-0ae4-4f98-90cd-f0b0f3a61d2b
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: fab9fa8f-705f-4989-ae81-5a2c41c77a94
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: e7f4cbdb-5bdf-4bee-b24b-76451250be1a
			defaultHierarchy: LocalDateTable_82170241-bf89-474a-8038-f041d63976f9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 72e1d313-add2-4db9-b987-f15fdc9eba48
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: a44abf82-e85c-443c-be76-59d10864fb9a
			defaultHierarchy: LocalDateTable_00edaadb-7214-4576-8354-50df6ca06961.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: ccd0ed14-b181-4849-944a-020c77841c51
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: fbc40bac-5bab-4d69-9f2c-fbd899556cdf
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 4743508d-a6aa-4773-972b-92e546f7d9e9
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: da2361f5-40e3-459b-b2d4-122087b9acd5
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 7cf9cc4d-a1ac-4e35-857e-39af68192fe1
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 23f1e734-cca8-4547-a7af-4e90efe4972c
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 4a573893-3bbd-45fd-bbd3-95f80da09daf
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 35eecaeb-cc78-4e13-b54a-6a78927870b3
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: b6aac5b8-f045-474f-a9d7-f3971b5886a2
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 72e922a0-63e1-49aa-b8c6-a31cff3a6ffe
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: c7c33120-5683-49c7-b48d-c98bd90f89e0
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: b923ed72-4114-4e44-b752-0a6ed5725593
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 11714986-0b69-42aa-9fe2-83d81803feee
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 3e4617de-41c0-4d44-8379-d129abccb36e
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 3da2fac5-c871-407a-a162-8697377cffa9
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 9af03d37-a04d-44b2-8d7a-56504209e922
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 3b79b5be-49fb-4b61-ba6b-16559cda4718
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Sphyzee 01\Downloads\Sample - Superstore (1).xls"), null, true),
				    Orders1 = Source{[Name="Orders"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders1, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

