table 'Profit Bin Size'
	lineageTag: 96336fbb-1a23-4881-b5c8-9e9cc73014ea

	measure 'Profit Bin Size Value' = SELECTEDVALUE('Profit Bin Size'[Profit Bin Size], 50)
		lineageTag: 5787ed17-47ce-408a-a4d1-19323f8f5e98

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Profit Bin Size'
		dataType: double
		formatString: 0
		lineageTag: 35773d69-4461-4c0c-8a04-421ffb5c76b8
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Profit Bin Size' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_Id = 454eb57afe7946f9babee55c89330579

