table 'Top Customers'
	lineageTag: ee8b9d34-adc0-4d9e-856f-8cbe8a966111

	measure 'Top Customers Value' = SELECTEDVALUE('Top Customers'[Top Customers], 5)
		lineageTag: 795cbd47-fbd2-4152-b2eb-ade756ce91c3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Top Customers'
		dataType: double
		formatString: 0
		lineageTag: 0b938448-bd1f-434d-8949-44a3f84349ea
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Top Customers' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_Id = 105827eb21204acea437a19921d9316e

