table '_Migrated Data'
	lineageTag: f485867f-d5c2-47dd-9d9f-59bb82346195

	column id
		dataType: int64
		formatString: 0
		lineageTag: 64ee5e4c-1a1d-4de4-a061-bc42e22974fd
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column effective_date
		dataType: datetime
		lineageTag: 1e2159e2-a7d1-4212-b285-ee7fc1e9de50
		summarizeBy: none
		sourceColumn: effective_date

		annotation SummarizationSetBy = Automatic

	column position_id_position
		dataType: string
		lineageTag: 2c980d5b-85fd-429b-a8cf-7a136a696e44
		summarizeBy: none
		sourceColumn: position_id_position

		annotation SummarizationSetBy = Automatic

	column product
		dataType: string
		lineageTag: 6b1ad4b8-1154-479f-8b03-29a0d6d7b53a
		summarizeBy: none
		sourceColumn: product

		annotation SummarizationSetBy = Automatic

	column volcker_desk_id
		dataType: int64
		formatString: 0
		lineageTag: 05fba2cd-8a7f-4628-b3c5-8e6c3a69e693
		summarizeBy: sum
		sourceColumn: volcker_desk_id

		annotation SummarizationSetBy = Automatic

	column counterparty_name
		dataType: string
		lineageTag: 546efb9a-dca5-4970-8ff2-cc730d09c6b9
		summarizeBy: none
		sourceColumn: counterparty_name

		annotation SummarizationSetBy = Automatic

	column source_system
		dataType: string
		lineageTag: 59fffe6d-76eb-47c8-8c77-b5ac55952a53
		summarizeBy: none
		sourceColumn: source_system

		annotation SummarizationSetBy = Automatic

	column aging_report_value
		dataType: double
		formatString: General Number
		lineageTag: a12259bb-d85b-4605-8caa-3d77600e9c83
		summarizeBy: sum
		sourceColumn: aging_report_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column age_of_trade
		dataType: int64
		formatString: 0
		lineageTag: 876c601c-f765-4de2-afe9-ac6eee0b9aa2
		summarizeBy: sum
		sourceColumn: age_of_trade

		annotation SummarizationSetBy = Automatic

	column bucket
		dataType: string
		lineageTag: 19b41358-5502-497d-a4a5-6d2cea0d8a09
		summarizeBy: none
		sourceColumn: bucket

		annotation SummarizationSetBy = Automatic

	column classification
		dataType: string
		lineageTag: cb1b2461-9ae8-4aca-9515-66ffc3010b66
		summarizeBy: none
		sourceColumn: classification

		annotation SummarizationSetBy = Automatic

	column trade_id
		dataType: string
		lineageTag: 78a87dff-1ec3-43cb-ad3c-aaf84eb11499
		summarizeBy: none
		sourceColumn: trade_id

		annotation SummarizationSetBy = Automatic

	column aging_report_value_abs
		dataType: double
		formatString: General Number
		lineageTag: 92c39f17-75fb-40de-aa24-b3b41ea27b03
		summarizeBy: sum
		sourceColumn: aging_report_value_abs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column file_path
		dataType: string
		lineageTag: 7626c148-cec7-446a-917a-9e4d91bfed03
		summarizeBy: none
		sourceColumn: file_path

		annotation SummarizationSetBy = Automatic

	column created_date
		dataType: datetime
		lineageTag: 1bd9840a-9ecd-4ced-a170-eb1a0caa2928
		summarizeBy: none
		sourceColumn: created_date

		annotation SummarizationSetBy = Automatic

	column security_id_position
		dataType: string
		lineageTag: 8f48fee8-142e-4341-8ce7-b3cdce26e649
		summarizeBy: none
		sourceColumn: security_id_position

		annotation SummarizationSetBy = Automatic

	column source_book
		dataType: string
		lineageTag: 545ad0a8-3d60-4047-be39-ca8fcb0a9aa6
		summarizeBy: none
		sourceColumn: source_book

		annotation SummarizationSetBy = Automatic

	column book
		dataType: string
		lineageTag: 7908c86c-01e3-4c7e-8718-7c125c6106d3
		summarizeBy: none
		sourceColumn: book

		annotation SummarizationSetBy = Automatic

	column 'id 1'
		dataType: int64
		formatString: 0
		lineageTag: 5ed22c0e-cbe9-4bb0-a131-bcce77bac68c
		summarizeBy: sum
		sourceColumn: 'id 1'

		annotation SummarizationSetBy = Automatic

	column 'effective_date 1'
		dataType: datetime
		lineageTag: 49f41ae8-750a-4a68-8363-e7c13abd9764
		summarizeBy: none
		sourceColumn: 'effective_date 1'

		annotation SummarizationSetBy = Automatic

	column 'source_system 1'
		dataType: string
		lineageTag: ac513b82-14db-4204-8465-66864a94e054
		summarizeBy: none
		sourceColumn: 'source_system 1'

		annotation SummarizationSetBy = Automatic

	column security_id
		dataType: string
		lineageTag: f1add5f7-11bc-4896-b3af-1eec52b6d42e
		summarizeBy: none
		sourceColumn: security_id

		annotation SummarizationSetBy = Automatic

	column security_name
		dataType: string
		lineageTag: 59e370ba-bc3b-4e70-a260-6529f7cdd8bc
		summarizeBy: none
		sourceColumn: security_name

		annotation SummarizationSetBy = Automatic

	column 'created_date 1'
		dataType: datetime
		lineageTag: c1b7dce3-e337-476a-aaa6-be1343282210
		summarizeBy: none
		sourceColumn: 'created_date 1'

		annotation SummarizationSetBy = Automatic

	column snapshot_date
		dataType: datetime
		lineageTag: a17b6c38-f625-4461-91a4-c8d3bed233bb
		summarizeBy: none
		sourceColumn: snapshot_date

		annotation SummarizationSetBy = Automatic

	column 'id 2'
		dataType: int64
		formatString: 0
		lineageTag: f4ad6db9-f642-4402-9297-1dd27abc4f84
		summarizeBy: sum
		sourceColumn: 'id 2'

		annotation SummarizationSetBy = Automatic

	column desk_name
		dataType: string
		lineageTag: 087dbe4d-c903-4f10-a8eb-e70721868216
		summarizeBy: none
		sourceColumn: desk_name

		annotation SummarizationSetBy = Automatic

	column sub_desk
		dataType: string
		lineageTag: 3819952d-7d52-4db8-ae93-f53360cfb808
		summarizeBy: none
		sourceColumn: sub_desk

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 343d02f0-2ed9-4945-9936-5216f510818f
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column utilization_incl_all_products
		dataType: string
		lineageTag: 131e8af1-4dbe-4a38-bc7c-8553af13354a
		summarizeBy: none
		sourceColumn: utilization_incl_all_products

		annotation SummarizationSetBy = Automatic

	column 'created_date 2'
		dataType: datetime
		lineageTag: c6d70f1c-aa11-4e5d-a9f2-68c79ffb1a8b
		summarizeBy: none
		sourceColumn: 'created_date 2'

		annotation SummarizationSetBy = Automatic

	column modified_date
		dataType: datetime
		lineageTag: 133c8d96-871c-4b77-89ef-19f23e903ac4
		summarizeBy: none
		sourceColumn: modified_date

		annotation SummarizationSetBy = Automatic

	column fixed_client_ratio
		dataType: double
		formatString: General Number
		lineageTag: 52c2f034-ffa4-46d3-b606-c28e95c6c84c
		summarizeBy: sum
		sourceColumn: fixed_client_ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column report_group
		dataType: string
		lineageTag: 1ad19fe0-9a57-457a-83e3-c68ca0b5a3c9
		summarizeBy: none
		sourceColumn: report_group

		annotation SummarizationSetBy = Automatic

	column var_portfolio_id
		dataType: int64
		formatString: 0
		lineageTag: 13dfebb4-40b7-4ba8-a72e-c6b5a7807919
		summarizeBy: sum
		sourceColumn: var_portfolio_id

		annotation SummarizationSetBy = Automatic

	column last_edit_username
		dataType: string
		lineageTag: 6f9fdab4-8683-4ddf-b24a-21e77a3084d9
		summarizeBy: none
		sourceColumn: last_edit_username

		annotation SummarizationSetBy = Automatic

	column desk_description
		dataType: string
		lineageTag: 39d0dd1b-32fa-48e5-b8bb-2b4e52fee67b
		summarizeBy: none
		sourceColumn: desk_description

		annotation SummarizationSetBy = Automatic

	column 'EFFECTIVE_DATE 4'
		dataType: datetime
		lineageTag: 36bc334e-4c9c-4407-8e33-3fc4bf125b5c
		summarizeBy: none
		sourceColumn: 'EFFECTIVE_DATE 4'

		annotation SummarizationSetBy = Automatic

	column 'SECURITY_NAME 3'
		dataType: string
		lineageTag: 93b2a63f-5638-4373-a941-3c8d7c26e94f
		summarizeBy: none
		sourceColumn: 'SECURITY_NAME 3'

		annotation SummarizationSetBy = Automatic

	column 'MID_PRICE_INT 1'
		dataType: double
		formatString: General Number
		lineageTag: badfe1e6-85c2-4bfa-b0e5-99a9a964277d
		summarizeBy: sum
		sourceColumn: 'MID_PRICE_INT 1'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ASK_PRICE_INT 1'
		dataType: double
		formatString: General Number
		lineageTag: c7f48f32-35e5-426d-9a51-722440d09a47
		summarizeBy: sum
		sourceColumn: 'ASK_PRICE_INT 1'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'BID_PRICE_INT 1'
		dataType: double
		formatString: General Number
		lineageTag: 9beb45f5-1145-4009-8afb-36264ac74f9a
		summarizeBy: sum
		sourceColumn: 'BID_PRICE_INT 1'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'VOLCKER_DESK 1'
		dataType: string
		lineageTag: feec3374-04d1-47a4-8e91-c9ce8e5216ff
		summarizeBy: none
		sourceColumn: 'VOLCKER_DESK 1'

		annotation SummarizationSetBy = Automatic

	column 'SECURITY_ID 3'
		dataType: string
		lineageTag: 3cd5df24-e712-4eb2-8c7e-72f9308d6881
		summarizeBy: none
		sourceColumn: 'SECURITY_ID 3'

		annotation SummarizationSetBy = Automatic

	column 'SECURITY_MATURITY 1'
		dataType: datetime
		lineageTag: dc88bc8a-938a-44f9-946a-9ba6564f2c4c
		summarizeBy: none
		sourceColumn: 'SECURITY_MATURITY 1'

		annotation SummarizationSetBy = Automatic

	column 'CURRENCY 1'
		dataType: string
		lineageTag: da083239-4edb-4a81-8a87-9c4bd7990db9
		summarizeBy: none
		sourceColumn: 'CURRENCY 1'

		annotation SummarizationSetBy = Automatic

	column 'OBLIGOR_NAME 1'
		dataType: string
		lineageTag: 3bb8190a-2a2e-4a36-8e6c-a8a838b9b5f3
		summarizeBy: none
		sourceColumn: 'OBLIGOR_NAME 1'

		annotation SummarizationSetBy = Automatic

	column 'IS_CALLABLE 1'
		dataType: string
		lineageTag: 8d6b61eb-3f64-41ac-ad16-61a839b9ad6a
		summarizeBy: none
		sourceColumn: 'IS_CALLABLE 1'

		annotation SummarizationSetBy = Automatic

	column 'FX_CONV_MARKET_DATA_SRC_ID 1'
		dataType: int64
		formatString: 0
		lineageTag: 1f1794e5-578f-4dc4-b9c0-81adecba0a24
		summarizeBy: sum
		sourceColumn: 'FX_CONV_MARKET_DATA_SRC_ID 1'

		annotation SummarizationSetBy = Automatic

	column 'TO_USD 1'
		dataType: double
		formatString: General Number
		lineageTag: 10fa7c1c-3def-43c5-b775-39cb37310338
		summarizeBy: sum
		sourceColumn: 'TO_USD 1'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'TO_CAD 1'
		dataType: double
		formatString: General Number
		lineageTag: af74fa80-e1b4-432b-86f9-116dd2bfecdf
		summarizeBy: sum
		sourceColumn: 'TO_CAD 1'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'TO_EUR 1'
		dataType: double
		formatString: General Number
		lineageTag: 448cfe68-deef-4ce8-8d77-7390e7948de2
		summarizeBy: sum
		sourceColumn: 'TO_EUR 1'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'TO_GBP 1'
		dataType: double
		formatString: General Number
		lineageTag: 211a4354-09cc-4ae4-8ad3-9adec8a3cd0a
		summarizeBy: sum
		sourceColumn: 'TO_GBP 1'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SUM(QUANTITY) 1'
		dataType: double
		formatString: General Number
		lineageTag: 54fe72ee-cdd5-40ce-ac34-3c9e02528871
		summarizeBy: sum
		sourceColumn: 'SUM(QUANTITY) 1'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SUM(NOTIONAL_AMOUNT) 1'
		dataType: double
		formatString: General Number
		lineageTag: 882e0b4d-1b9b-4793-ac02-2b2e6a915071
		summarizeBy: sum
		sourceColumn: 'SUM(NOTIONAL_AMOUNT) 1'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition '_Migrated Data' = m
		mode: import
		source =
				let 
					#"Source0" = Table.NestedJoin(#"volcker_rpt_inventory_aging_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)", {"security_id_position", "source_system", "effective_date"}, #"volcker_rpt_security_mapping_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)", {"security_id", "source_system", "effective_date"}, "volcker_rpt_security_mapping_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)", JoinKind.LeftOuter),
					#"Expand0" = Table.ExpandTableColumn(#"Source0", "volcker_rpt_security_mapping_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)", {"id", "effective_date", "source_system", "security_id", "security_name", "created_date"}, {"id 1", "effective_date 1", "source_system 1", "security_id", "security_name", "created_date 1"}),
					#"Source1" = Table.NestedJoin(#"Expand0", {"volcker_desk_id", "effective_date"}, #"volcker_desk_snapshots_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)", {"id", "snapshot_date"}, "volcker_desk_snapshots_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)", JoinKind.Inner),
					#"Expand1" = Table.ExpandTableColumn(#"Source1", "volcker_desk_snapshots_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)", {"snapshot_date", "id", "desk_name", "sub_desk", "status", "utilization_incl_all_products", "created_date", "modified_date", "fixed_client_ratio", "report_group", "var_portfolio_id", "last_edit_username", "desk_description"}, {"snapshot_date", "id 2", "desk_name", "sub_desk", "status", "utilization_incl_all_products", "created_date 2", "modified_date", "fixed_client_ratio", "report_group", "var_portfolio_id", "last_edit_username", "desk_description"}),
					#"Source2" = Table.NestedJoin(#"Expand1", {"datetime([effective_date])", "security_id_position"}, #"Custom SQL Query_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)", {"EFFECTIVE_DATE", "SECURITY_ID"}, "Custom SQL Query_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)", JoinKind.LeftOuter),
					#"Expand2" = Table.ExpandTableColumn(#"Source2", "Custom SQL Query_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)", {"EFFECTIVE_DATE", "SECURITY_NAME", "MID_PRICE_INT", "ASK_PRICE_INT", "BID_PRICE_INT", "VOLCKER_DESK", "SECURITY_ID", "SECURITY_MATURITY", "CURRENCY", "OBLIGOR_NAME", "IS_CALLABLE", "FX_CONV_MARKET_DATA_SRC_ID", "TO_USD", "TO_CAD", "TO_EUR", "TO_GBP", "SUM(QUANTITY)", "SUM(NOTIONAL_AMOUNT)"}, {"EFFECTIVE_DATE 4", "SECURITY_NAME 3", "MID_PRICE_INT 1", "ASK_PRICE_INT 1", "BID_PRICE_INT 1", "VOLCKER_DESK 1", "SECURITY_ID 3", "SECURITY_MATURITY 1", "CURRENCY 1", "OBLIGOR_NAME 1", "IS_CALLABLE 1", "FX_CONV_MARKET_DATA_SRC_ID 1", "TO_USD 1", "TO_CAD 1", "TO_EUR 1", "TO_GBP 1", "SUM(QUANTITY) 1", "SUM(NOTIONAL_AMOUNT) 1"})
					in #"Expand2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table