table 'Custom SQL Query_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)'
	lineageTag: 36163dfe-fc26-4337-8318-a533067cb1ac

	column EFFECTIVE_DATE
		dataType: datetime
		lineageTag: a9c4c2e9-82ae-467b-b9fb-401dfdbacb3f
		summarizeBy: none
		sourceColumn: EFFECTIVE_DATE

		annotation SummarizationSetBy = Automatic

	column SECURITY_NAME
		dataType: string
		lineageTag: e4399fea-96da-4041-9785-9d7b748ed389
		summarizeBy: none
		sourceColumn: SECURITY_NAME

		annotation SummarizationSetBy = Automatic

	column MID_PRICE_INT
		dataType: double
		formatString: General Number
		lineageTag: 6b1c9c27-f095-48fd-aaf7-4cc48f1ba73c
		summarizeBy: sum
		sourceColumn: MID_PRICE_INT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ASK_PRICE_INT
		dataType: double
		formatString: General Number
		lineageTag: 9a564ad0-9219-48a9-b96e-93a362321f7a
		summarizeBy: sum
		sourceColumn: ASK_PRICE_INT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BID_PRICE_INT
		dataType: double
		formatString: General Number
		lineageTag: 5d6b3cc0-190f-4ae4-ae98-451a7dc0bd51
		summarizeBy: sum
		sourceColumn: BID_PRICE_INT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VOLCKER_DESK
		dataType: string
		lineageTag: f2943a2e-39b6-43b5-b7c8-fae87a78768d
		summarizeBy: none
		sourceColumn: VOLCKER_DESK

		annotation SummarizationSetBy = Automatic

	column SECURITY_ID
		dataType: string
		lineageTag: 148efb2d-8fa7-4c33-b47f-3942914dbc99
		summarizeBy: none
		sourceColumn: SECURITY_ID

		annotation SummarizationSetBy = Automatic

	column SECURITY_MATURITY
		dataType: datetime
		lineageTag: d50c682c-0b32-4de2-9715-2972635fed35
		summarizeBy: none
		sourceColumn: SECURITY_MATURITY

		annotation SummarizationSetBy = Automatic

	column CURRENCY
		dataType: string
		lineageTag: ce93de33-c187-4cd0-b1ed-4fbbee50f619
		summarizeBy: none
		sourceColumn: CURRENCY

		annotation SummarizationSetBy = Automatic

	column OBLIGOR_NAME
		dataType: string
		lineageTag: 4a8d6def-4976-4b30-a123-2709fa91941f
		summarizeBy: none
		sourceColumn: OBLIGOR_NAME

		annotation SummarizationSetBy = Automatic

	column IS_CALLABLE
		dataType: string
		lineageTag: 83da8f9f-bd09-4962-ab21-490665b21c21
		summarizeBy: none
		sourceColumn: IS_CALLABLE

		annotation SummarizationSetBy = Automatic

	column FX_CONV_MARKET_DATA_SRC_ID
		dataType: int64
		formatString: 0
		lineageTag: 792a463e-1a68-4aea-b943-78b5251c83c2
		summarizeBy: sum
		sourceColumn: FX_CONV_MARKET_DATA_SRC_ID

		annotation SummarizationSetBy = Automatic

	column TO_USD
		dataType: double
		formatString: General Number
		lineageTag: de8079b8-3916-4628-b387-0060851e23a7
		summarizeBy: sum
		sourceColumn: TO_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_CAD
		dataType: double
		formatString: General Number
		lineageTag: f5d96676-2242-4907-97a2-6fcc190023f1
		summarizeBy: sum
		sourceColumn: TO_CAD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_EUR
		dataType: double
		formatString: General Number
		lineageTag: 0f7b3f33-8b08-4923-87d2-ffc44901eb9b
		summarizeBy: sum
		sourceColumn: TO_EUR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_GBP
		dataType: double
		formatString: General Number
		lineageTag: 9f6cb8de-0a40-4460-ad8d-c18020e2c4a6
		summarizeBy: sum
		sourceColumn: TO_GBP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SUM(QUANTITY)'
		dataType: double
		formatString: General Number
		lineageTag: a24d22d8-2ea7-4018-ad32-1665aff4794f
		summarizeBy: sum
		sourceColumn: 'SUM(QUANTITY)'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SUM(NOTIONAL_AMOUNT)'
		dataType: double
		formatString: General Number
		lineageTag: cadf11cd-abfe-4c2f-8ab6-03d976f5d3df
		summarizeBy: sum
		sourceColumn: 'SUM(NOTIONAL_AMOUNT)'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Custom SQL Query_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [EFFECTIVE_DATE = #datetime(2024, 1, 1, 0, 0, 0), SECURITY_NAME = "Sample_SECURITY_NAME_1", MID_PRICE_INT = "Sample_MID_PRICE_INT_1", ASK_PRICE_INT = "Sample_ASK_PRICE_INT_1", BID_PRICE_INT = "Sample_BID_PRICE_INT_1", VOLCKER_DESK = "Sample_VOLCKER_DESK_1", SECURITY_ID = "Sample_SECURITY_ID_1", SECURITY_MATURITY = #datetime(2024, 1, 1, 0, 0, 0), CURRENCY = "Sample_CURRENCY_1", OBLIGOR_NAME = "Sample_OBLIGOR_NAME_1", IS_CALLABLE = "Sample_IS_CALLABLE_1", FX_CONV_MARKET_DATA_SRC_ID = 10, TO_USD = "Sample_TO_USD_1", TO_CAD = "Sample_TO_CAD_1", TO_EUR = "Sample_TO_EUR_1", TO_GBP = "Sample_TO_GBP_1", SUM(QUANTITY) = "Sample_SUM(QUANTITY)_1", SUM(NOTIONAL_AMOUNT) = "Sample_SUM(NOTIONAL_AMOUNT)_1"],
					        [EFFECTIVE_DATE = #datetime(2024, 1, 2, 0, 0, 0), SECURITY_NAME = "Sample_SECURITY_NAME_2", MID_PRICE_INT = "Sample_MID_PRICE_INT_2", ASK_PRICE_INT = "Sample_ASK_PRICE_INT_2", BID_PRICE_INT = "Sample_BID_PRICE_INT_2", VOLCKER_DESK = "Sample_VOLCKER_DESK_2", SECURITY_ID = "Sample_SECURITY_ID_2", SECURITY_MATURITY = #datetime(2024, 1, 2, 0, 0, 0), CURRENCY = "Sample_CURRENCY_2", OBLIGOR_NAME = "Sample_OBLIGOR_NAME_2", IS_CALLABLE = "Sample_IS_CALLABLE_2", FX_CONV_MARKET_DATA_SRC_ID = 20, TO_USD = "Sample_TO_USD_2", TO_CAD = "Sample_TO_CAD_2", TO_EUR = "Sample_TO_EUR_2", TO_GBP = "Sample_TO_GBP_2", SUM(QUANTITY) = "Sample_SUM(QUANTITY)_2", SUM(NOTIONAL_AMOUNT) = "Sample_SUM(NOTIONAL_AMOUNT)_2"],
					        [EFFECTIVE_DATE = #datetime(2024, 1, 3, 0, 0, 0), SECURITY_NAME = "Sample_SECURITY_NAME_3", MID_PRICE_INT = "Sample_MID_PRICE_INT_3", ASK_PRICE_INT = "Sample_ASK_PRICE_INT_3", BID_PRICE_INT = "Sample_BID_PRICE_INT_3", VOLCKER_DESK = "Sample_VOLCKER_DESK_3", SECURITY_ID = "Sample_SECURITY_ID_3", SECURITY_MATURITY = #datetime(2024, 1, 3, 0, 0, 0), CURRENCY = "Sample_CURRENCY_3", OBLIGOR_NAME = "Sample_OBLIGOR_NAME_3", IS_CALLABLE = "Sample_IS_CALLABLE_3", FX_CONV_MARKET_DATA_SRC_ID = 30, TO_USD = "Sample_TO_USD_3", TO_CAD = "Sample_TO_CAD_3", TO_EUR = "Sample_TO_EUR_3", TO_GBP = "Sample_TO_GBP_3", SUM(QUANTITY) = "Sample_SUM(QUANTITY)_3", SUM(NOTIONAL_AMOUNT) = "Sample_SUM(NOTIONAL_AMOUNT)_3"],
					        [EFFECTIVE_DATE = #datetime(2024, 1, 4, 0, 0, 0), SECURITY_NAME = "Sample_SECURITY_NAME_4", MID_PRICE_INT = "Sample_MID_PRICE_INT_4", ASK_PRICE_INT = "Sample_ASK_PRICE_INT_4", BID_PRICE_INT = "Sample_BID_PRICE_INT_4", VOLCKER_DESK = "Sample_VOLCKER_DESK_4", SECURITY_ID = "Sample_SECURITY_ID_4", SECURITY_MATURITY = #datetime(2024, 1, 4, 0, 0, 0), CURRENCY = "Sample_CURRENCY_4", OBLIGOR_NAME = "Sample_OBLIGOR_NAME_4", IS_CALLABLE = "Sample_IS_CALLABLE_4", FX_CONV_MARKET_DATA_SRC_ID = 40, TO_USD = "Sample_TO_USD_4", TO_CAD = "Sample_TO_CAD_4", TO_EUR = "Sample_TO_EUR_4", TO_GBP = "Sample_TO_GBP_4", SUM(QUANTITY) = "Sample_SUM(QUANTITY)_4", SUM(NOTIONAL_AMOUNT) = "Sample_SUM(NOTIONAL_AMOUNT)_4"],
					        [EFFECTIVE_DATE = #datetime(2024, 1, 5, 0, 0, 0), SECURITY_NAME = "Sample_SECURITY_NAME_5", MID_PRICE_INT = "Sample_MID_PRICE_INT_5", ASK_PRICE_INT = "Sample_ASK_PRICE_INT_5", BID_PRICE_INT = "Sample_BID_PRICE_INT_5", VOLCKER_DESK = "Sample_VOLCKER_DESK_5", SECURITY_ID = "Sample_SECURITY_ID_5", SECURITY_MATURITY = #datetime(2024, 1, 5, 0, 0, 0), CURRENCY = "Sample_CURRENCY_5", OBLIGOR_NAME = "Sample_OBLIGOR_NAME_5", IS_CALLABLE = "Sample_IS_CALLABLE_5", FX_CONV_MARKET_DATA_SRC_ID = 50, TO_USD = "Sample_TO_USD_5", TO_CAD = "Sample_TO_CAD_5", TO_EUR = "Sample_TO_EUR_5", TO_GBP = "Sample_TO_GBP_5", SUM(QUANTITY) = "Sample_SUM(QUANTITY)_5", SUM(NOTIONAL_AMOUNT) = "Sample_SUM(NOTIONAL_AMOUNT)_5"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"EFFECTIVE_DATE", type datetime},
					        {"SECURITY_NAME", type text},
					        {"MID_PRICE_INT", type number},
					        {"ASK_PRICE_INT", type number},
					        {"BID_PRICE_INT", type number},
					        {"VOLCKER_DESK", type text},
					        {"SECURITY_ID", type text},
					        {"SECURITY_MATURITY", type datetime},
					        {"CURRENCY", type text},
					        {"OBLIGOR_NAME", type text},
					        {"IS_CALLABLE", type text},
					        {"FX_CONV_MARKET_DATA_SRC_ID", Int64.Type},
					        {"TO_USD", type number},
					        {"TO_CAD", type number},
					        {"TO_EUR", type number},
					        {"TO_GBP", type number},
					        {"SUM(QUANTITY)", type number},
					        {"SUM(NOTIONAL_AMOUNT)", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table