table 'Extract_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)'
	lineageTag: 99255f9f-e5fd-4a3f-b960-c82ce464cc74

	column id
		dataType: int64
		formatString: 0
		lineageTag: 78dff0a5-a0f7-4a99-a29d-06caa08a3e60
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column effective_date
		dataType: datetime
		lineageTag: 6ad8f2fb-698b-4579-87d4-25d6544950ee
		summarizeBy: none
		sourceColumn: effective_date

		annotation SummarizationSetBy = Automatic

	column position_id_position
		dataType: string
		lineageTag: e02cd6dd-ad21-4bd0-8e03-2bd0dc3e872b
		summarizeBy: none
		sourceColumn: position_id_position

		annotation SummarizationSetBy = Automatic

	column product
		dataType: string
		lineageTag: 45e9f4d1-38ff-4323-ba92-1ee40183f3a3
		summarizeBy: none
		sourceColumn: product

		annotation SummarizationSetBy = Automatic

	column volcker_desk_id
		dataType: int64
		formatString: 0
		lineageTag: 00538241-2fbd-4e47-9900-944d2a78b054
		summarizeBy: sum
		sourceColumn: volcker_desk_id

		annotation SummarizationSetBy = Automatic

	column counterparty_name
		dataType: string
		lineageTag: 5c560526-167d-4936-b2b4-57a4a469de27
		summarizeBy: none
		sourceColumn: counterparty_name

		annotation SummarizationSetBy = Automatic

	column source_system
		dataType: string
		lineageTag: 6addbdcf-8168-4122-9445-a7124dd31679
		summarizeBy: none
		sourceColumn: source_system

		annotation SummarizationSetBy = Automatic

	column aging_report_value
		dataType: double
		formatString: General Number
		lineageTag: 61872edc-32c3-4f2c-9c0b-512951af0ab6
		summarizeBy: sum
		sourceColumn: aging_report_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column age_of_trade
		dataType: int64
		formatString: 0
		lineageTag: 7df10949-1f5b-495e-bb8e-093dd9c1a408
		summarizeBy: sum
		sourceColumn: age_of_trade

		annotation SummarizationSetBy = Automatic

	column bucket
		dataType: string
		lineageTag: 6c7c7585-5c22-4983-802d-7030d52ccfe4
		summarizeBy: none
		sourceColumn: bucket

		annotation SummarizationSetBy = Automatic

	column classification
		dataType: string
		lineageTag: fcc06d7d-0f4b-40e5-b404-4775e00165a1
		summarizeBy: none
		sourceColumn: classification

		annotation SummarizationSetBy = Automatic

	column trade_id
		dataType: string
		lineageTag: 531cea02-70c1-4686-940a-8b03e443ae50
		summarizeBy: none
		sourceColumn: trade_id

		annotation SummarizationSetBy = Automatic

	column aging_report_value_abs
		dataType: double
		formatString: General Number
		lineageTag: c3c81f6d-5875-40b3-8b7f-c709d0158346
		summarizeBy: sum
		sourceColumn: aging_report_value_abs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column file_path
		dataType: string
		lineageTag: 4594d501-7651-46e4-942b-9fa645684d0c
		summarizeBy: none
		sourceColumn: file_path

		annotation SummarizationSetBy = Automatic

	column created_date
		dataType: datetime
		lineageTag: 7c78d5c1-4c67-4e4f-bd9a-2350cfec36b1
		summarizeBy: none
		sourceColumn: created_date

		annotation SummarizationSetBy = Automatic

	column security_id_position
		dataType: string
		lineageTag: 4f9f9f73-2db1-4ced-8bd5-c3a40a825575
		summarizeBy: none
		sourceColumn: security_id_position

		annotation SummarizationSetBy = Automatic

	column source_book
		dataType: string
		lineageTag: 71b5d335-68d7-48e2-999d-68b5d3c28eaa
		summarizeBy: none
		sourceColumn: source_book

		annotation SummarizationSetBy = Automatic

	column book
		dataType: string
		lineageTag: 2d79a6f8-ac36-4ad5-ae10-78e6c617fe03
		summarizeBy: none
		sourceColumn: book

		annotation SummarizationSetBy = Automatic

	column security_id
		dataType: string
		lineageTag: 64fcb1b0-3272-4072-8fd0-4a732fb55e0f
		summarizeBy: none
		sourceColumn: security_id

		annotation SummarizationSetBy = Automatic

	column security_name
		dataType: string
		lineageTag: c8fcf027-2939-4cc6-b6c8-e8a7c8b6833a
		summarizeBy: none
		sourceColumn: security_name

		annotation SummarizationSetBy = Automatic

	column snapshot_date
		dataType: datetime
		lineageTag: ffd78335-dc3d-4734-899b-b51e09232301
		summarizeBy: none
		sourceColumn: snapshot_date

		annotation SummarizationSetBy = Automatic

	column desk_name
		dataType: string
		lineageTag: 6e8dc64a-42b5-459e-a77d-995ccb2b9833
		summarizeBy: none
		sourceColumn: desk_name

		annotation SummarizationSetBy = Automatic

	column sub_desk
		dataType: string
		lineageTag: 89cc5603-2a49-4504-b123-3f6b9eabc046
		summarizeBy: none
		sourceColumn: sub_desk

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: d50976eb-28ed-4902-aad7-5c017455789f
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column utilization_incl_all_products
		dataType: string
		lineageTag: 4a7ef6e4-5aa1-4440-a539-8189f09edc06
		summarizeBy: none
		sourceColumn: utilization_incl_all_products

		annotation SummarizationSetBy = Automatic

	column modified_date
		dataType: datetime
		lineageTag: 91b7717e-ee51-4720-95d4-346238fcc7cb
		summarizeBy: none
		sourceColumn: modified_date

		annotation SummarizationSetBy = Automatic

	column fixed_client_ratio
		dataType: double
		formatString: General Number
		lineageTag: 8a9d3316-e5a1-41a5-a3ad-03dc73edb8ec
		summarizeBy: sum
		sourceColumn: fixed_client_ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column report_group
		dataType: string
		lineageTag: 4f5a3f95-a90b-43a2-9567-bb9aa9c0ded8
		summarizeBy: none
		sourceColumn: report_group

		annotation SummarizationSetBy = Automatic

	column var_portfolio_id
		dataType: int64
		formatString: 0
		lineageTag: 9dd07e66-06a6-4b72-81fe-0fb9b4a44b05
		summarizeBy: sum
		sourceColumn: var_portfolio_id

		annotation SummarizationSetBy = Automatic

	column last_edit_username
		dataType: string
		lineageTag: f454e8d4-0388-4f73-94ef-8ed87cac760a
		summarizeBy: none
		sourceColumn: last_edit_username

		annotation SummarizationSetBy = Automatic

	column desk_description
		dataType: string
		lineageTag: bb3fc086-4c05-4ae9-8a67-697bd7c6a8a2
		summarizeBy: none
		sourceColumn: desk_description

		annotation SummarizationSetBy = Automatic

	column EFFECTIVE_DATE
		dataType: datetime
		lineageTag: 91cead5b-edf8-4ea5-80ce-780795efc0bf
		summarizeBy: none
		sourceColumn: EFFECTIVE_DATE

		annotation SummarizationSetBy = Automatic

	column SECURITY_NAME
		dataType: string
		lineageTag: d06cbaca-be23-4662-befb-81158f89487a
		summarizeBy: none
		sourceColumn: SECURITY_NAME

		annotation SummarizationSetBy = Automatic

	column MID_PRICE_INT
		dataType: double
		formatString: General Number
		lineageTag: 77487bae-273f-4964-b9a8-3ccf17c0f2c4
		summarizeBy: sum
		sourceColumn: MID_PRICE_INT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ASK_PRICE_INT
		dataType: double
		formatString: General Number
		lineageTag: 7c30f7f7-f312-4753-a874-3af168a3994e
		summarizeBy: sum
		sourceColumn: ASK_PRICE_INT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BID_PRICE_INT
		dataType: double
		formatString: General Number
		lineageTag: cce861f1-22d0-42f1-b35c-d776cc02d45c
		summarizeBy: sum
		sourceColumn: BID_PRICE_INT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VOLCKER_DESK
		dataType: string
		lineageTag: e2f5de07-8608-4fce-a9ee-1e10fed3fdf4
		summarizeBy: none
		sourceColumn: VOLCKER_DESK

		annotation SummarizationSetBy = Automatic

	column SECURITY_ID
		dataType: string
		lineageTag: ff736422-39f3-4d19-bd9f-c169448cf923
		summarizeBy: none
		sourceColumn: SECURITY_ID

		annotation SummarizationSetBy = Automatic

	column SECURITY_MATURITY
		dataType: datetime
		lineageTag: b8cf7d03-e18a-4312-9c0e-07f8a8c3d02c
		summarizeBy: none
		sourceColumn: SECURITY_MATURITY

		annotation SummarizationSetBy = Automatic

	column CURRENCY
		dataType: string
		lineageTag: 622c6f9c-0dfa-4c57-9eca-f3c22fdaf097
		summarizeBy: none
		sourceColumn: CURRENCY

		annotation SummarizationSetBy = Automatic

	column OBLIGOR_NAME
		dataType: string
		lineageTag: 3a14bbb3-98d4-43f6-a976-e0f5478e5fb0
		summarizeBy: none
		sourceColumn: OBLIGOR_NAME

		annotation SummarizationSetBy = Automatic

	column IS_CALLABLE
		dataType: string
		lineageTag: aa00960d-790c-4323-b80b-4514ea879846
		summarizeBy: none
		sourceColumn: IS_CALLABLE

		annotation SummarizationSetBy = Automatic

	column FX_CONV_MARKET_DATA_SRC_ID
		dataType: int64
		formatString: 0
		lineageTag: 6a8e6796-e776-4020-b860-ed36b14cc09c
		summarizeBy: sum
		sourceColumn: FX_CONV_MARKET_DATA_SRC_ID

		annotation SummarizationSetBy = Automatic

	column TO_USD
		dataType: double
		formatString: General Number
		lineageTag: 7c01b731-6d60-4666-9810-292efa831571
		summarizeBy: sum
		sourceColumn: TO_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_CAD
		dataType: double
		formatString: General Number
		lineageTag: 52881716-2520-463a-a5af-0b03ab180124
		summarizeBy: sum
		sourceColumn: TO_CAD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_EUR
		dataType: double
		formatString: General Number
		lineageTag: abbd8d8b-b225-489c-83cc-38cc0c90b658
		summarizeBy: sum
		sourceColumn: TO_EUR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_GBP
		dataType: double
		formatString: General Number
		lineageTag: 4647c0ff-17e3-4155-af6b-0ae8e7f57e70
		summarizeBy: sum
		sourceColumn: TO_GBP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SUM(QUANTITY)'
		dataType: double
		formatString: General Number
		lineageTag: 9cfec2a2-7e0c-47fa-9609-b1cb57ad0c6c
		summarizeBy: sum
		sourceColumn: 'SUM(QUANTITY)'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SUM(NOTIONAL_AMOUNT)'
		dataType: double
		formatString: General Number
		lineageTag: 04dd96a6-4375-4272-9fbb-7e878c9839fb
		summarizeBy: sum
		sourceColumn: 'SUM(NOTIONAL_AMOUNT)'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Extract_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [id = 10, effective_date = #date(2024, 1, 1), position_id_position = "Sample_position_id_position_1", product = "Sample_product_1", volcker_desk_id = 10, counterparty_name = "Sample_counterparty_name_1", source_system = "Sample_source_system_1", aging_report_value = "Sample_aging_report_value_1", age_of_trade = 10, bucket = "Sample_bucket_1", classification = "Sample_classification_1", trade_id = "Sample_trade_id_1", aging_report_value_abs = "Sample_aging_report_value_abs_1", file_path = "Sample_file_path_1", created_date = #date(2024, 1, 1), security_id_position = "Sample_security_id_position_1", source_book = "Sample_source_book_1", book = "Sample_book_1", security_id = "Sample_security_id_1", security_name = "Sample_security_name_1", snapshot_date = #date(2024, 1, 1), desk_name = "Sample_desk_name_1", sub_desk = "Sample_sub_desk_1", status = "Sample_status_1", utilization_incl_all_products = True, modified_date = #datetime(2024, 1, 1, 0, 0, 0), fixed_client_ratio = "Sample_fixed_client_ratio_1", report_group = "Sample_report_group_1", var_portfolio_id = 10, last_edit_username = "Sample_last_edit_username_1", desk_description = "Sample_desk_description_1", EFFECTIVE_DATE = #datetime(2024, 1, 1, 0, 0, 0), SECURITY_NAME = "Sample_SECURITY_NAME_1", MID_PRICE_INT = "Sample_MID_PRICE_INT_1", ASK_PRICE_INT = "Sample_ASK_PRICE_INT_1", BID_PRICE_INT = "Sample_BID_PRICE_INT_1", VOLCKER_DESK = "Sample_VOLCKER_DESK_1", SECURITY_ID = "Sample_SECURITY_ID_1", SECURITY_MATURITY = #datetime(2024, 1, 1, 0, 0, 0), CURRENCY = "Sample_CURRENCY_1", OBLIGOR_NAME = "Sample_OBLIGOR_NAME_1", IS_CALLABLE = "Sample_IS_CALLABLE_1", FX_CONV_MARKET_DATA_SRC_ID = 10, TO_USD = "Sample_TO_USD_1", TO_CAD = "Sample_TO_CAD_1", TO_EUR = "Sample_TO_EUR_1", TO_GBP = "Sample_TO_GBP_1", SUM(QUANTITY) = "Sample_SUM(QUANTITY)_1", SUM(NOTIONAL_AMOUNT) = "Sample_SUM(NOTIONAL_AMOUNT)_1"],
					        [id = 20, effective_date = #date(2024, 1, 2), position_id_position = "Sample_position_id_position_2", product = "Sample_product_2", volcker_desk_id = 20, counterparty_name = "Sample_counterparty_name_2", source_system = "Sample_source_system_2", aging_report_value = "Sample_aging_report_value_2", age_of_trade = 20, bucket = "Sample_bucket_2", classification = "Sample_classification_2", trade_id = "Sample_trade_id_2", aging_report_value_abs = "Sample_aging_report_value_abs_2", file_path = "Sample_file_path_2", created_date = #date(2024, 1, 2), security_id_position = "Sample_security_id_position_2", source_book = "Sample_source_book_2", book = "Sample_book_2", security_id = "Sample_security_id_2", security_name = "Sample_security_name_2", snapshot_date = #date(2024, 1, 2), desk_name = "Sample_desk_name_2", sub_desk = "Sample_sub_desk_2", status = "Sample_status_2", utilization_incl_all_products = False, modified_date = #datetime(2024, 1, 2, 0, 0, 0), fixed_client_ratio = "Sample_fixed_client_ratio_2", report_group = "Sample_report_group_2", var_portfolio_id = 20, last_edit_username = "Sample_last_edit_username_2", desk_description = "Sample_desk_description_2", EFFECTIVE_DATE = #datetime(2024, 1, 2, 0, 0, 0), SECURITY_NAME = "Sample_SECURITY_NAME_2", MID_PRICE_INT = "Sample_MID_PRICE_INT_2", ASK_PRICE_INT = "Sample_ASK_PRICE_INT_2", BID_PRICE_INT = "Sample_BID_PRICE_INT_2", VOLCKER_DESK = "Sample_VOLCKER_DESK_2", SECURITY_ID = "Sample_SECURITY_ID_2", SECURITY_MATURITY = #datetime(2024, 1, 2, 0, 0, 0), CURRENCY = "Sample_CURRENCY_2", OBLIGOR_NAME = "Sample_OBLIGOR_NAME_2", IS_CALLABLE = "Sample_IS_CALLABLE_2", FX_CONV_MARKET_DATA_SRC_ID = 20, TO_USD = "Sample_TO_USD_2", TO_CAD = "Sample_TO_CAD_2", TO_EUR = "Sample_TO_EUR_2", TO_GBP = "Sample_TO_GBP_2", SUM(QUANTITY) = "Sample_SUM(QUANTITY)_2", SUM(NOTIONAL_AMOUNT) = "Sample_SUM(NOTIONAL_AMOUNT)_2"],
					        [id = 30, effective_date = #date(2024, 1, 3), position_id_position = "Sample_position_id_position_3", product = "Sample_product_3", volcker_desk_id = 30, counterparty_name = "Sample_counterparty_name_3", source_system = "Sample_source_system_3", aging_report_value = "Sample_aging_report_value_3", age_of_trade = 30, bucket = "Sample_bucket_3", classification = "Sample_classification_3", trade_id = "Sample_trade_id_3", aging_report_value_abs = "Sample_aging_report_value_abs_3", file_path = "Sample_file_path_3", created_date = #date(2024, 1, 3), security_id_position = "Sample_security_id_position_3", source_book = "Sample_source_book_3", book = "Sample_book_3", security_id = "Sample_security_id_3", security_name = "Sample_security_name_3", snapshot_date = #date(2024, 1, 3), desk_name = "Sample_desk_name_3", sub_desk = "Sample_sub_desk_3", status = "Sample_status_3", utilization_incl_all_products = True, modified_date = #datetime(2024, 1, 3, 0, 0, 0), fixed_client_ratio = "Sample_fixed_client_ratio_3", report_group = "Sample_report_group_3", var_portfolio_id = 30, last_edit_username = "Sample_last_edit_username_3", desk_description = "Sample_desk_description_3", EFFECTIVE_DATE = #datetime(2024, 1, 3, 0, 0, 0), SECURITY_NAME = "Sample_SECURITY_NAME_3", MID_PRICE_INT = "Sample_MID_PRICE_INT_3", ASK_PRICE_INT = "Sample_ASK_PRICE_INT_3", BID_PRICE_INT = "Sample_BID_PRICE_INT_3", VOLCKER_DESK = "Sample_VOLCKER_DESK_3", SECURITY_ID = "Sample_SECURITY_ID_3", SECURITY_MATURITY = #datetime(2024, 1, 3, 0, 0, 0), CURRENCY = "Sample_CURRENCY_3", OBLIGOR_NAME = "Sample_OBLIGOR_NAME_3", IS_CALLABLE = "Sample_IS_CALLABLE_3", FX_CONV_MARKET_DATA_SRC_ID = 30, TO_USD = "Sample_TO_USD_3", TO_CAD = "Sample_TO_CAD_3", TO_EUR = "Sample_TO_EUR_3", TO_GBP = "Sample_TO_GBP_3", SUM(QUANTITY) = "Sample_SUM(QUANTITY)_3", SUM(NOTIONAL_AMOUNT) = "Sample_SUM(NOTIONAL_AMOUNT)_3"],
					        [id = 40, effective_date = #date(2024, 1, 4), position_id_position = "Sample_position_id_position_4", product = "Sample_product_4", volcker_desk_id = 40, counterparty_name = "Sample_counterparty_name_4", source_system = "Sample_source_system_4", aging_report_value = "Sample_aging_report_value_4", age_of_trade = 40, bucket = "Sample_bucket_4", classification = "Sample_classification_4", trade_id = "Sample_trade_id_4", aging_report_value_abs = "Sample_aging_report_value_abs_4", file_path = "Sample_file_path_4", created_date = #date(2024, 1, 4), security_id_position = "Sample_security_id_position_4", source_book = "Sample_source_book_4", book = "Sample_book_4", security_id = "Sample_security_id_4", security_name = "Sample_security_name_4", snapshot_date = #date(2024, 1, 4), desk_name = "Sample_desk_name_4", sub_desk = "Sample_sub_desk_4", status = "Sample_status_4", utilization_incl_all_products = False, modified_date = #datetime(2024, 1, 4, 0, 0, 0), fixed_client_ratio = "Sample_fixed_client_ratio_4", report_group = "Sample_report_group_4", var_portfolio_id = 40, last_edit_username = "Sample_last_edit_username_4", desk_description = "Sample_desk_description_4", EFFECTIVE_DATE = #datetime(2024, 1, 4, 0, 0, 0), SECURITY_NAME = "Sample_SECURITY_NAME_4", MID_PRICE_INT = "Sample_MID_PRICE_INT_4", ASK_PRICE_INT = "Sample_ASK_PRICE_INT_4", BID_PRICE_INT = "Sample_BID_PRICE_INT_4", VOLCKER_DESK = "Sample_VOLCKER_DESK_4", SECURITY_ID = "Sample_SECURITY_ID_4", SECURITY_MATURITY = #datetime(2024, 1, 4, 0, 0, 0), CURRENCY = "Sample_CURRENCY_4", OBLIGOR_NAME = "Sample_OBLIGOR_NAME_4", IS_CALLABLE = "Sample_IS_CALLABLE_4", FX_CONV_MARKET_DATA_SRC_ID = 40, TO_USD = "Sample_TO_USD_4", TO_CAD = "Sample_TO_CAD_4", TO_EUR = "Sample_TO_EUR_4", TO_GBP = "Sample_TO_GBP_4", SUM(QUANTITY) = "Sample_SUM(QUANTITY)_4", SUM(NOTIONAL_AMOUNT) = "Sample_SUM(NOTIONAL_AMOUNT)_4"],
					        [id = 50, effective_date = #date(2024, 1, 5), position_id_position = "Sample_position_id_position_5", product = "Sample_product_5", volcker_desk_id = 50, counterparty_name = "Sample_counterparty_name_5", source_system = "Sample_source_system_5", aging_report_value = "Sample_aging_report_value_5", age_of_trade = 50, bucket = "Sample_bucket_5", classification = "Sample_classification_5", trade_id = "Sample_trade_id_5", aging_report_value_abs = "Sample_aging_report_value_abs_5", file_path = "Sample_file_path_5", created_date = #date(2024, 1, 5), security_id_position = "Sample_security_id_position_5", source_book = "Sample_source_book_5", book = "Sample_book_5", security_id = "Sample_security_id_5", security_name = "Sample_security_name_5", snapshot_date = #date(2024, 1, 5), desk_name = "Sample_desk_name_5", sub_desk = "Sample_sub_desk_5", status = "Sample_status_5", utilization_incl_all_products = True, modified_date = #datetime(2024, 1, 5, 0, 0, 0), fixed_client_ratio = "Sample_fixed_client_ratio_5", report_group = "Sample_report_group_5", var_portfolio_id = 50, last_edit_username = "Sample_last_edit_username_5", desk_description = "Sample_desk_description_5", EFFECTIVE_DATE = #datetime(2024, 1, 5, 0, 0, 0), SECURITY_NAME = "Sample_SECURITY_NAME_5", MID_PRICE_INT = "Sample_MID_PRICE_INT_5", ASK_PRICE_INT = "Sample_ASK_PRICE_INT_5", BID_PRICE_INT = "Sample_BID_PRICE_INT_5", VOLCKER_DESK = "Sample_VOLCKER_DESK_5", SECURITY_ID = "Sample_SECURITY_ID_5", SECURITY_MATURITY = #datetime(2024, 1, 5, 0, 0, 0), CURRENCY = "Sample_CURRENCY_5", OBLIGOR_NAME = "Sample_OBLIGOR_NAME_5", IS_CALLABLE = "Sample_IS_CALLABLE_5", FX_CONV_MARKET_DATA_SRC_ID = 50, TO_USD = "Sample_TO_USD_5", TO_CAD = "Sample_TO_CAD_5", TO_EUR = "Sample_TO_EUR_5", TO_GBP = "Sample_TO_GBP_5", SUM(QUANTITY) = "Sample_SUM(QUANTITY)_5", SUM(NOTIONAL_AMOUNT) = "Sample_SUM(NOTIONAL_AMOUNT)_5"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"id", Int64.Type},
					        {"effective_date", type date},
					        {"position_id_position", type text},
					        {"product", type text},
					        {"volcker_desk_id", Int64.Type},
					        {"counterparty_name", type text},
					        {"source_system", type text},
					        {"aging_report_value", type number},
					        {"age_of_trade", Int64.Type},
					        {"bucket", type text},
					        {"classification", type text},
					        {"trade_id", type text},
					        {"aging_report_value_abs", type number},
					        {"file_path", type text},
					        {"created_date", type date},
					        {"security_id_position", type text},
					        {"source_book", type text},
					        {"book", type text},
					        {"security_id", type text},
					        {"security_name", type text},
					        {"snapshot_date", type date},
					        {"desk_name", type text},
					        {"sub_desk", type text},
					        {"status", type text},
					        {"utilization_incl_all_products", type logical},
					        {"modified_date", type datetime},
					        {"fixed_client_ratio", type number},
					        {"report_group", type text},
					        {"var_portfolio_id", Int64.Type},
					        {"last_edit_username", type text},
					        {"desk_description", type text},
					        {"EFFECTIVE_DATE", type datetime},
					        {"SECURITY_NAME", type text},
					        {"MID_PRICE_INT", type number},
					        {"ASK_PRICE_INT", type number},
					        {"BID_PRICE_INT", type number},
					        {"VOLCKER_DESK", type text},
					        {"SECURITY_ID", type text},
					        {"SECURITY_MATURITY", type datetime},
					        {"CURRENCY", type text},
					        {"OBLIGOR_NAME", type text},
					        {"IS_CALLABLE", type text},
					        {"FX_CONV_MARKET_DATA_SRC_ID", Int64.Type},
					        {"TO_USD", type number},
					        {"TO_CAD", type number},
					        {"TO_EUR", type number},
					        {"TO_GBP", type number},
					        {"SUM(QUANTITY)", type number},
					        {"SUM(NOTIONAL_AMOUNT)", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table