table 'volcker_desk_snapshots_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)'
	lineageTag: 1208a182-d64a-41bb-b7a5-6986c9a08f7c

	column snapshot_date
		dataType: datetime
		lineageTag: defee35b-fa8a-4fec-9be4-28a125215882
		summarizeBy: none
		sourceColumn: snapshot_date

		annotation SummarizationSetBy = Automatic

	column id
		dataType: int64
		formatString: 0
		lineageTag: 601c7495-8f00-4e85-b611-cde08c1f49db
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column desk_name
		dataType: string
		lineageTag: 979512cb-66fc-4288-a04d-55388feb1bb8
		summarizeBy: none
		sourceColumn: desk_name

		annotation SummarizationSetBy = Automatic

	column sub_desk
		dataType: string
		lineageTag: 1c34eaad-f272-4eac-a9a1-166dd76225d7
		summarizeBy: none
		sourceColumn: sub_desk

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 3df2081b-0fe8-4af6-aca2-f7fd17835d69
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column utilization_incl_all_products
		dataType: string
		lineageTag: e55143ff-3e54-405a-8976-c5bf9fa039e9
		summarizeBy: none
		sourceColumn: utilization_incl_all_products

		annotation SummarizationSetBy = Automatic

	column created_date
		dataType: datetime
		lineageTag: ee17b14b-55ac-4cf7-82d3-019566583193
		summarizeBy: none
		sourceColumn: created_date

		annotation SummarizationSetBy = Automatic

	column modified_date
		dataType: datetime
		lineageTag: 695ca61d-8fb5-4f4b-b1db-f9fdff20a4eb
		summarizeBy: none
		sourceColumn: modified_date

		annotation SummarizationSetBy = Automatic

	column fixed_client_ratio
		dataType: double
		formatString: General Number
		lineageTag: 6e1eea34-2508-4b8d-ae8b-5c482fd7acde
		summarizeBy: sum
		sourceColumn: fixed_client_ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column report_group
		dataType: string
		lineageTag: 56fcad70-9f7b-4b57-b366-cfaf8be0364d
		summarizeBy: none
		sourceColumn: report_group

		annotation SummarizationSetBy = Automatic

	column var_portfolio_id
		dataType: int64
		formatString: 0
		lineageTag: 6f51454f-9f28-43a3-9c65-53ef43f9c54d
		summarizeBy: sum
		sourceColumn: var_portfolio_id

		annotation SummarizationSetBy = Automatic

	column last_edit_username
		dataType: string
		lineageTag: da8d1d42-c094-49f7-9560-32e8877af186
		summarizeBy: none
		sourceColumn: last_edit_username

		annotation SummarizationSetBy = Automatic

	column desk_description
		dataType: string
		lineageTag: 09b38b10-9c0a-4bd9-8623-7ea8b6f07837
		summarizeBy: none
		sourceColumn: desk_description

		annotation SummarizationSetBy = Automatic

	partition 'volcker_desk_snapshots_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [snapshot_date = #date(2023, 2, 21), id = 7065, desk_name = "Leo Gill", sub_desk = "foods", status = False, utilization_incl_all_products = True, created_date = #date(2021, 2, 8), modified_date = #datetime(2024, 5, 11, 23, 58, 33), fixed_client_ratio = 555.22, report_group = "island", var_portfolio_id = 3176, last_edit_username = "Alvarez", desk_description = "192.165.182.77"],
					        [snapshot_date = #date(2024, 5, 21), id = 2753, desk_name = "Bryce Lowe", sub_desk = "spent", status = True, utilization_incl_all_products = True, created_date = #date(2020, 8, 23), modified_date = #datetime(2020, 3, 24, 16, 39, 52), fixed_client_ratio = 807.41, report_group = "growing", var_portfolio_id = 890, last_edit_username = "Thompson", desk_description = "234.172.240.57"],
					        [snapshot_date = #date(2020, 6, 25), id = 9045, desk_name = "Eloy Eaton", sub_desk = "produce", status = False, utilization_incl_all_products = True, created_date = #date(2020, 3, 13), modified_date = #datetime(2020, 1, 29, 21, 6, 48), fixed_client_ratio = 652.09, report_group = "destination", var_portfolio_id = 6570, last_edit_username = "Prince", desk_description = "186.36.196.175"],
					        [snapshot_date = #date(2022, 8, 31), id = 5486, desk_name = "Hubert Gonzalez", sub_desk = "turkish", status = False, utilization_incl_all_products = False, created_date = #date(2023, 8, 21), modified_date = #datetime(2021, 7, 17, 17, 59, 38), fixed_client_ratio = 90.85, report_group = "discharge", var_portfolio_id = 3827, last_edit_username = "Lott", desk_description = "61.241.136.100"],
					        [snapshot_date = #date(2021, 5, 17), id = 2811, desk_name = "Darell Rodgers", sub_desk = "gifts", status = False, utilization_incl_all_products = True, created_date = #date(2023, 10, 26), modified_date = #datetime(2021, 3, 17, 3, 12, 4), fixed_client_ratio = 524.66, report_group = "met", var_portfolio_id = 3826, last_edit_username = "Boyd", desk_description = "123.104.122.44"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"snapshot_date", type date},
					        {"id", Int64.Type},
					        {"desk_name", type text},
					        {"sub_desk", type text},
					        {"status", type text},
					        {"utilization_incl_all_products", type logical},
					        {"created_date", type date},
					        {"modified_date", type datetime},
					        {"fixed_client_ratio", type number},
					        {"report_group", type text},
					        {"var_portfolio_id", Int64.Type},
					        {"last_edit_username", type text},
					        {"desk_description", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table