table 'volcker_rpt_security_mapping_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)'
	lineageTag: 80fd047d-2a1d-4666-b207-8f05717861f9

	column id
		dataType: int64
		formatString: 0
		lineageTag: 0136041c-ad9f-41f7-b7a0-32cd76d3a408
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column effective_date
		dataType: datetime
		lineageTag: de7f0684-c85c-48bf-9489-30dc90399895
		summarizeBy: none
		sourceColumn: effective_date

		annotation SummarizationSetBy = Automatic

	column source_system
		dataType: string
		lineageTag: 9ef68bc0-533e-45de-a442-eb4179558ae4
		summarizeBy: none
		sourceColumn: source_system

		annotation SummarizationSetBy = Automatic

	column security_id
		dataType: string
		lineageTag: 815835ca-7127-4a67-868d-ea767b44f9f3
		summarizeBy: none
		sourceColumn: security_id

		annotation SummarizationSetBy = Automatic

	column security_name
		dataType: string
		lineageTag: 4fd175f3-d9e5-413b-b817-6f84849e2965
		summarizeBy: none
		sourceColumn: security_name

		annotation SummarizationSetBy = Automatic

	column created_date
		dataType: datetime
		lineageTag: decf31fb-c4df-4e86-b2ca-e390998d22f6
		summarizeBy: none
		sourceColumn: created_date

		annotation SummarizationSetBy = Automatic

	partition 'volcker_rpt_security_mapping_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [id = 1406, effective_date = #date(2022, 12, 13), source_system = "dimension", security_id = 8005, security_name = "Danyelle Hunter", created_date = #datetime(2021, 6, 12, 14, 51, 55)],
					        [id = 1151, effective_date = #date(2023, 12, 19), source_system = "shops", security_id = 6323, security_name = "Lajuana Blanchard", created_date = #datetime(2021, 6, 4, 17, 3, 2)],
					        [id = 3129, effective_date = #date(2021, 5, 15), source_system = "writing", security_id = 3970, security_name = "Ardell Yates", created_date = #datetime(2023, 7, 25, 0, 50, 44)],
					        [id = 2130, effective_date = #date(2020, 11, 12), source_system = "sad", security_id = 6857, security_name = "Daryl Strong", created_date = #datetime(2020, 1, 9, 21, 23, 59)],
					        [id = 90, effective_date = #date(2022, 1, 30), source_system = "linux", security_id = 2667, security_name = "Anjelica Bates", created_date = #datetime(2020, 10, 17, 10, 43, 36)]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"id", Int64.Type},
					        {"effective_date", type date},
					        {"source_system", type text},
					        {"security_id", type text},
					        {"security_name", type text},
					        {"created_date", type datetime}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table