table 'Balance Threshold'
	lineageTag: ef399cd5-2668-4a9a-9a73-cf3f48249bfa

	measure 'Balance Threshold Value' = SELECTEDVALUE('Balance Threshold'[Balance Threshold], 0.0)
		lineageTag: 50dd0c50-f5ce-4472-a311-ed652faa4c64

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Threshold'
		dataType: double
		formatString: 0
		lineageTag: 09cee0ba-8d4e-49a0-8995-2dfe252846cf
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Balance Threshold' = calculated
		mode: import
		source = GENERATESERIES(0.0, 500000.0, 5000.0)

	annotation PBI_Id = 70989270ea0d4d3bbfdfd749c05d892c

