table 'Highlight Parameter'
	lineageTag: e9f447c2-1fc7-49ef-aac2-c79cb91aca4e

	measure 'Highlight Parameter Value' = SELECTEDVALUE('Highlight Parameter'[Highlight Parameter], 1.0)
		lineageTag: 5f8ca3f4-5cc0-45c6-869c-042ecbfc23c9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Highlight Parameter'
		dataType: double
		formatString: 0
		lineageTag: da390d48-d5f2-4c4c-a10b-9173bb42c820
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Highlight Parameter' = calculated
		mode: import
		source = GENERATESERIES(1.0, 5.0, 1.0)

	annotation PBI_Id = 585727f827eb4ea28d3c1f0ba490b111

