table 'Orders - table'
	lineageTag: 15377ac5-5a2b-4fbb-8f63-722935dae9b9

	column Category
		dataType: string
		lineageTag: 2b0f8005-ca2f-4cd1-836b-9e53c8a13e1c
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 48ca7f40-f705-4167-9894-bf12171b4ade
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Country/Region
		dataType: string
		lineageTag: 309bff77-0391-45f6-ad38-949d1b8b17cf
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 6b22e808-5017-4dcf-aade-64ae0dc19e19
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ec7051f1-206b-4998-8cdc-891b0b96d63d
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: f924dcf9-2532-4d42-a335-69c954f6a335
			defaultHierarchy: LocalDateTable_30a56416-64bd-48f4-8ab6-d3657c7c948c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Order ID'
		dataType: string
		lineageTag: 81919a49-cd42-4910-b9a7-96456c97fa62
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: e49e2f16-0ce5-4e39-ab2e-278e46b54329
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 094c2d75-675d-4e89-8347-8f0d3204be84
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 88748098-a9b4-4743-82e1-a448a4f27b22
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 34639431-6218-43fe-986a-c88b201cd054
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: dba9385a-4490-4ea3-b40f-21368a43cd61
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: eb9a2cea-e8da-45b3-96b4-cdd8c675d691
			defaultHierarchy: LocalDateTable_febc3809-20d3-48d1-8ba5-a916e86a3df0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: 0c400391-5c93-44e1-898b-2cf066bb129e
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column State/Province
		dataType: string
		lineageTag: 9cdf601f-458c-42ea-8e14-a718595546d6
		summarizeBy: none
		sourceColumn: State/Province

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 392f4eb7-d360-400d-9468-be537c245503
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 09e3c144-9c6d-432d-9c81-18b05fdd0817
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 255a586f-b76d-4c3b-a4d4-15e4d50237c2
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 2b5985a2-5fd3-4e3b-a44e-cbf9aa05b3d0
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: d729ec28-b60b-49fc-8e1b-f37593436806
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Orders - table' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\LENOVO\Downloads\Sample - Superstore (1).xlsx"), null, true),
				    Orders_Sheet = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Category", type text}, {"City", type text}, {"Country/Region", type text}, {"Customer Name", type text}, {"Order Date", type date}, {"Order ID", type text}, {"Postal Code", type any}, {"Product Name", type text}, {"Region", type text}, {"Segment", type text}, {"Ship Date", type date}, {"Ship Mode", type text}, {"State/Province", type text}, {"Sub-Category", type text}, {"Discount", type number}, {"Profit", type number}, {"Quantity", Int64.Type}, {"Sales", type number}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

