table 'customers+'
	lineageTag: 2bd3b583-beae-4a1f-a907-d7a3b5edcdcf

	column CustomerID
		dataType: string
		lineageTag: 21462656-297f-4cb6-9bf6-eb910083a30e
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: ae909a18-f3c6-41a9-8138-baa71edad0ae
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: fc4d1a9e-8c15-4935-9e69-7f5574d3ad96
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 44f5d92d-ac8a-4a01-8320-3c843a64814f
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column DOB
		dataType: datetime
		lineageTag: 7f1afdae-e2be-43a6-9c70-d1d2a14177a1
		summarizeBy: none
		sourceColumn: DOB

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 90484415-22b3-4b69-85d0-2882a371458f
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column CustomerSince
		dataType: datetime
		lineageTag: 8780fb87-78f9-43a9-8cc5-7df95e6f7c5f
		summarizeBy: none
		sourceColumn: CustomerSince

		annotation SummarizationSetBy = Automatic

	column ClaimID
		dataType: string
		lineageTag: 3adea78a-3cd5-4eeb-b94e-923ba51ff508
		summarizeBy: none
		sourceColumn: ClaimID

		annotation SummarizationSetBy = Automatic

	column PolicyID
		dataType: string
		lineageTag: 44125577-dcd4-4201-964d-8cc99839cfdd
		summarizeBy: none
		sourceColumn: PolicyID

		annotation SummarizationSetBy = Automatic

	column 'CustomerID 1'
		dataType: string
		lineageTag: ce0ea9db-9a5f-407f-8755-aac6256351cd
		summarizeBy: none
		sourceColumn: 'CustomerID 1'

		annotation SummarizationSetBy = Automatic

	column ClaimDate
		dataType: datetime
		lineageTag: 94a9b6d7-a9fa-459c-86b6-aec2722fa64a
		summarizeBy: none
		sourceColumn: ClaimDate

		annotation SummarizationSetBy = Automatic

	column ClaimType
		dataType: string
		lineageTag: 552db4ac-3e93-4aaa-a94b-47ab73d28373
		summarizeBy: none
		sourceColumn: ClaimType

		annotation SummarizationSetBy = Automatic

	column Cause
		dataType: string
		lineageTag: 899a8aee-6a9d-4c00-badb-d351a5991a23
		summarizeBy: none
		sourceColumn: Cause

		annotation SummarizationSetBy = Automatic

	column ClaimStatus
		dataType: string
		lineageTag: fdf6ca21-d9b3-4f40-9bf8-dfb56fd2ba55
		summarizeBy: none
		sourceColumn: ClaimStatus

		annotation SummarizationSetBy = Automatic

	column ClaimAmount
		dataType: double
		formatString: General Number
		lineageTag: 90139db1-7c15-428e-bddc-596be3c62733
		summarizeBy: sum
		sourceColumn: ClaimAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PolicyID 1'
		dataType: string
		lineageTag: 1969a876-8169-4261-aed1-2d7832ece04f
		summarizeBy: none
		sourceColumn: 'PolicyID 1'

		annotation SummarizationSetBy = Automatic

	column 'CustomerID 2'
		dataType: string
		lineageTag: 4169d3f2-6cba-40c0-8dd1-30e6db814e11
		summarizeBy: none
		sourceColumn: 'CustomerID 2'

		annotation SummarizationSetBy = Automatic

	column PolicyType
		dataType: string
		lineageTag: 7881ecfd-f88b-4715-a08b-f8919c5ac2ec
		summarizeBy: none
		sourceColumn: PolicyType

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: datetime
		lineageTag: 48218980-821c-4145-824a-168163027a05
		summarizeBy: none
		sourceColumn: StartDate

		annotation SummarizationSetBy = Automatic

	column EndDate
		dataType: datetime
		lineageTag: b657c048-33e4-4bf6-8757-3b4cc19a2ae0
		summarizeBy: none
		sourceColumn: EndDate

		annotation SummarizationSetBy = Automatic

	column Premium
		dataType: double
		formatString: General Number
		lineageTag: 44f6da0b-709c-42b1-aa35-77c7edd4a587
		summarizeBy: sum
		sourceColumn: Premium

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SumInsured
		dataType: double
		formatString: General Number
		lineageTag: 903b19ee-4a4d-42d5-970f-fe61a0008f01
		summarizeBy: sum
		sourceColumn: SumInsured

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BranchID
		dataType: string
		lineageTag: 58721b3d-732e-4994-901e-4bca4afc5007
		summarizeBy: none
		sourceColumn: BranchID

		annotation SummarizationSetBy = Automatic

	partition 'customers+' = m
		mode: import
		source =
				let 
					#"Source0" = Table.NestedJoin(#"customers.csv_customers+", {"CustomerID"}, #"customers+_claims.csv", {"CustomerID"}, "customers+_claims.csv", JoinKind.RightOuter),
					#"Expand0" = Table.ExpandTableColumn(#"Source0", "customers+_claims.csv", {"ClaimID", "PolicyID", "CustomerID", "ClaimDate", "ClaimType", "Cause", "ClaimStatus", "ClaimAmount"}, {"ClaimID", "PolicyID", "CustomerID 1", "ClaimDate", "ClaimType", "Cause", "ClaimStatus", "ClaimAmount"}),
					#"Source1" = Table.NestedJoin(#"Expand0", {"CustomerID"}, #"customers+_policies.csv", {"CustomerID"}, "customers+_policies.csv", JoinKind.Inner),
					#"Expand1" = Table.ExpandTableColumn(#"Source1", "customers+_policies.csv", {"PolicyID", "CustomerID", "PolicyType", "StartDate", "EndDate", "Premium", "SumInsured", "BranchID"}, {"PolicyID 1", "CustomerID 2", "PolicyType", "StartDate", "EndDate", "Premium", "SumInsured", "BranchID"})
					in #"Expand1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table