table 'Top N Customers'
	lineageTag: 590c9b18-41ca-45d3-be29-0f847b211d4a

	measure 'Top N Customers Value' = SELECTEDVALUE('Top N Customers'[Top N Customers], 1)
		lineageTag: 9e67db6c-0728-4a7c-b94a-2db203a6eea0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Top N Customers'
		dataType: double
		formatString: 0
		lineageTag: d0bbd20c-8a3e-445d-a666-93f1be6094f9
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Top N Customers' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_Id = a0013b9ea80e4021b8b462f66201427d

