table 'Orders (Sample - Superstore)_Returns'
	lineageTag: fd77c013-967a-4397-8719-dbb9cfb32cba

	column Returned
		dataType: string
		lineageTag: e892310b-8386-4caf-8c43-55b65d259bc7
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: fa3851b3-744c-4186-b3bd-4bc75da628cf
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	partition 'Orders (Sample - Superstore)_Returns' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Returned" = "establishment", #"Order ID" = 5125],
					        [#"Returned" = "newsletter", #"Order ID" = 8146],
					        [#"Returned" = "nm", #"Order ID" = 9890],
					        [#"Returned" = "flight", #"Order ID" = 4181],
					        [#"Returned" = "memories", #"Order ID" = 1072],
					        [#"Returned" = "dont", #"Order ID" = 8381],
					        [#"Returned" = "goals", #"Order ID" = 2925],
					        [#"Returned" = "brothers", #"Order ID" = 7300],
					        [#"Returned" = "perfume", #"Order ID" = 9646],
					        [#"Returned" = "sublime", #"Order ID" = 1810],
					        [#"Returned" = "binding", #"Order ID" = 3371],
					        [#"Returned" = "cache", #"Order ID" = 8223],
					        [#"Returned" = "biz", #"Order ID" = 3523],
					        [#"Returned" = "truck", #"Order ID" = 4014],
					        [#"Returned" = "join", #"Order ID" = 1701],
					        [#"Returned" = "feelings", #"Order ID" = 8131],
					        [#"Returned" = "plus", #"Order ID" = 9774],
					        [#"Returned" = "talent", #"Order ID" = 4241],
					        [#"Returned" = "buddy", #"Order ID" = 2552],
					        [#"Returned" = "call", #"Order ID" = 6258],
					        [#"Returned" = "guy", #"Order ID" = 2226],
					        [#"Returned" = "textbooks", #"Order ID" = 3764],
					        [#"Returned" = "undergraduate", #"Order ID" = 8433],
					        [#"Returned" = "heating", #"Order ID" = 5311],
					        [#"Returned" = "jewellery", #"Order ID" = 5689],
					        [#"Returned" = "lib", #"Order ID" = 2221],
					        [#"Returned" = "receives", #"Order ID" = 6107],
					        [#"Returned" = "us", #"Order ID" = 6656],
					        [#"Returned" = "johnny", #"Order ID" = 5095],
					        [#"Returned" = "desktops", #"Order ID" = 2003],
					        [#"Returned" = "state", #"Order ID" = 2479],
					        [#"Returned" = "ruby", #"Order ID" = 7837],
					        [#"Returned" = "collections", #"Order ID" = 9505],
					        [#"Returned" = "surveillance", #"Order ID" = 5277],
					        [#"Returned" = "delaware", #"Order ID" = 3752],
					        [#"Returned" = "seat", #"Order ID" = 9229],
					        [#"Returned" = "educational", #"Order ID" = 5549],
					        [#"Returned" = "emergency", #"Order ID" = 4008],
					        [#"Returned" = "canvas", #"Order ID" = 3000],
					        [#"Returned" = "street", #"Order ID" = 1638],
					        [#"Returned" = "through", #"Order ID" = 3778],
					        [#"Returned" = "dallas", #"Order ID" = 6696],
					        [#"Returned" = "mobile", #"Order ID" = 1534],
					        [#"Returned" = "border", #"Order ID" = 4905],
					        [#"Returned" = "abc", #"Order ID" = 2619],
					        [#"Returned" = "prev", #"Order ID" = 6563],
					        [#"Returned" = "logged", #"Order ID" = 9375],
					        [#"Returned" = "activity", #"Order ID" = 1841],
					        [#"Returned" = "disorders", #"Order ID" = 1439],
					        [#"Returned" = "happen", #"Order ID" = 6725],
					        [#"Returned" = "mine", #"Order ID" = 8431],
					        [#"Returned" = "clinton", #"Order ID" = 3729],
					        [#"Returned" = "select", #"Order ID" = 9221],
					        [#"Returned" = "gmt", #"Order ID" = 1286],
					        [#"Returned" = "they", #"Order ID" = 9500],
					        [#"Returned" = "yard", #"Order ID" = 2935],
					        [#"Returned" = "inner", #"Order ID" = 2878],
					        [#"Returned" = "using", #"Order ID" = 9518],
					        [#"Returned" = "okay", #"Order ID" = 2462],
					        [#"Returned" = "indiana", #"Order ID" = 3428],
					        [#"Returned" = "tools", #"Order ID" = 4204],
					        [#"Returned" = "winners", #"Order ID" = 1708],
					        [#"Returned" = "rfc", #"Order ID" = 7927],
					        [#"Returned" = "alarm", #"Order ID" = 2393],
					        [#"Returned" = "steam", #"Order ID" = 3586],
					        [#"Returned" = "copies", #"Order ID" = 4190],
					        [#"Returned" = "chosen", #"Order ID" = 7532],
					        [#"Returned" = "ceo", #"Order ID" = 5965],
					        [#"Returned" = "traveler", #"Order ID" = 3774],
					        [#"Returned" = "adams", #"Order ID" = 1333],
					        [#"Returned" = "libraries", #"Order ID" = 4476],
					        [#"Returned" = "self", #"Order ID" = 4039],
					        [#"Returned" = "school", #"Order ID" = 8195],
					        [#"Returned" = "keep", #"Order ID" = 3154],
					        [#"Returned" = "progressive", #"Order ID" = 5884],
					        [#"Returned" = "rating", #"Order ID" = 7587],
					        [#"Returned" = "why", #"Order ID" = 4655],
					        [#"Returned" = "played", #"Order ID" = 8308],
					        [#"Returned" = "aid", #"Order ID" = 8680],
					        [#"Returned" = "pleasure", #"Order ID" = 5905],
					        [#"Returned" = "licensing", #"Order ID" = 5423],
					        [#"Returned" = "alumni", #"Order ID" = 8371],
					        [#"Returned" = "makes", #"Order ID" = 1145],
					        [#"Returned" = "afraid", #"Order ID" = 5739],
					        [#"Returned" = "nintendo", #"Order ID" = 6285],
					        [#"Returned" = "southwest", #"Order ID" = 5723],
					        [#"Returned" = "biological", #"Order ID" = 2906],
					        [#"Returned" = "agriculture", #"Order ID" = 4609],
					        [#"Returned" = "dna", #"Order ID" = 2370],
					        [#"Returned" = "environmental", #"Order ID" = 9262],
					        [#"Returned" = "secondary", #"Order ID" = 3865],
					        [#"Returned" = "prayer", #"Order ID" = 7102],
					        [#"Returned" = "cleveland", #"Order ID" = 5311],
					        [#"Returned" = "foods", #"Order ID" = 5524],
					        [#"Returned" = "challenge", #"Order ID" = 5091],
					        [#"Returned" = "born", #"Order ID" = 2120],
					        [#"Returned" = "minute", #"Order ID" = 8437],
					        [#"Returned" = "day", #"Order ID" = 4965],
					        [#"Returned" = "graduate", #"Order ID" = 6228],
					        [#"Returned" = "placement", #"Order ID" = 1540],
					        [#"Returned" = "charity", #"Order ID" = 9597],
					        [#"Returned" = "chris", #"Order ID" = 3470],
					        [#"Returned" = "kick", #"Order ID" = 8429],
					        [#"Returned" = "racing", #"Order ID" = 8367],
					        [#"Returned" = "happen", #"Order ID" = 1130],
					        [#"Returned" = "series", #"Order ID" = 5264],
					        [#"Returned" = "scenes", #"Order ID" = 3007],
					        [#"Returned" = "planned", #"Order ID" = 2940],
					        [#"Returned" = "surrounding", #"Order ID" = 3960],
					        [#"Returned" = "silent", #"Order ID" = 2741],
					        [#"Returned" = "agents", #"Order ID" = 9898],
					        [#"Returned" = "poverty", #"Order ID" = 5680],
					        [#"Returned" = "county", #"Order ID" = 5465],
					        [#"Returned" = "visitor", #"Order ID" = 7905],
					        [#"Returned" = "celebrity", #"Order ID" = 8878],
					        [#"Returned" = "detection", #"Order ID" = 4278],
					        [#"Returned" = "percentage", #"Order ID" = 9886],
					        [#"Returned" = "xl", #"Order ID" = 9823],
					        [#"Returned" = "confidence", #"Order ID" = 4920],
					        [#"Returned" = "section", #"Order ID" = 3508],
					        [#"Returned" = "britain", #"Order ID" = 2518],
					        [#"Returned" = "franchise", #"Order ID" = 7200],
					        [#"Returned" = "covers", #"Order ID" = 8099],
					        [#"Returned" = "tomorrow", #"Order ID" = 2237],
					        [#"Returned" = "makers", #"Order ID" = 4691],
					        [#"Returned" = "barcelona", #"Order ID" = 5408],
					        [#"Returned" = "intellectual", #"Order ID" = 4948],
					        [#"Returned" = "amp", #"Order ID" = 7672],
					        [#"Returned" = "nights", #"Order ID" = 5487],
					        [#"Returned" = "letters", #"Order ID" = 4948],
					        [#"Returned" = "level", #"Order ID" = 5542],
					        [#"Returned" = "hit", #"Order ID" = 9263],
					        [#"Returned" = "switches", #"Order ID" = 7521],
					        [#"Returned" = "costa", #"Order ID" = 4761],
					        [#"Returned" = "whatever", #"Order ID" = 8430],
					        [#"Returned" = "scotland", #"Order ID" = 9181],
					        [#"Returned" = "problems", #"Order ID" = 6696],
					        [#"Returned" = "best", #"Order ID" = 7273],
					        [#"Returned" = "of", #"Order ID" = 2710],
					        [#"Returned" = "blogger", #"Order ID" = 3965],
					        [#"Returned" = "user", #"Order ID" = 2405],
					        [#"Returned" = "printed", #"Order ID" = 1607],
					        [#"Returned" = "thinking", #"Order ID" = 7833],
					        [#"Returned" = "peter", #"Order ID" = 1852],
					        [#"Returned" = "signed", #"Order ID" = 7730],
					        [#"Returned" = "round", #"Order ID" = 4909],
					        [#"Returned" = "director", #"Order ID" = 6538],
					        [#"Returned" = "sterling", #"Order ID" = 8548],
					        [#"Returned" = "journals", #"Order ID" = 6436],
					        [#"Returned" = "favorites", #"Order ID" = 2702],
					        [#"Returned" = "hood", #"Order ID" = 5825],
					        [#"Returned" = "amazon", #"Order ID" = 9094],
					        [#"Returned" = "keys", #"Order ID" = 5392],
					        [#"Returned" = "jurisdiction", #"Order ID" = 2404],
					        [#"Returned" = "tests", #"Order ID" = 3010],
					        [#"Returned" = "allocated", #"Order ID" = 6660],
					        [#"Returned" = "tape", #"Order ID" = 1760],
					        [#"Returned" = "exp", #"Order ID" = 9574],
					        [#"Returned" = "disabilities", #"Order ID" = 2667],
					        [#"Returned" = "angeles", #"Order ID" = 4291],
					        [#"Returned" = "portuguese", #"Order ID" = 3779],
					        [#"Returned" = "election", #"Order ID" = 1704],
					        [#"Returned" = "judge", #"Order ID" = 6615],
					        [#"Returned" = "effectiveness", #"Order ID" = 3508],
					        [#"Returned" = "determined", #"Order ID" = 3985],
					        [#"Returned" = "therapy", #"Order ID" = 4624],
					        [#"Returned" = "murder", #"Order ID" = 6847],
					        [#"Returned" = "housewares", #"Order ID" = 6215],
					        [#"Returned" = "worker", #"Order ID" = 9815],
					        [#"Returned" = "spyware", #"Order ID" = 9404],
					        [#"Returned" = "jose", #"Order ID" = 4400],
					        [#"Returned" = "utilities", #"Order ID" = 8874],
					        [#"Returned" = "take", #"Order ID" = 4672],
					        [#"Returned" = "underground", #"Order ID" = 2543],
					        [#"Returned" = "selected", #"Order ID" = 9851],
					        [#"Returned" = "requires", #"Order ID" = 9807],
					        [#"Returned" = "template", #"Order ID" = 8686],
					        [#"Returned" = "ends", #"Order ID" = 7274],
					        [#"Returned" = "developed", #"Order ID" = 5514],
					        [#"Returned" = "specialist", #"Order ID" = 5107],
					        [#"Returned" = "solid", #"Order ID" = 7891],
					        [#"Returned" = "rail", #"Order ID" = 6387],
					        [#"Returned" = "accounts", #"Order ID" = 4298],
					        [#"Returned" = "walter", #"Order ID" = 7057],
					        [#"Returned" = "economy", #"Order ID" = 5466],
					        [#"Returned" = "notebooks", #"Order ID" = 3413],
					        [#"Returned" = "recognize", #"Order ID" = 1725],
					        [#"Returned" = "immediately", #"Order ID" = 7073],
					        [#"Returned" = "anderson", #"Order ID" = 5647],
					        [#"Returned" = "vary", #"Order ID" = 2110],
					        [#"Returned" = "accessibility", #"Order ID" = 9976],
					        [#"Returned" = "significant", #"Order ID" = 7449],
					        [#"Returned" = "operators", #"Order ID" = 6977],
					        [#"Returned" = "ed", #"Order ID" = 3900],
					        [#"Returned" = "country", #"Order ID" = 5479],
					        [#"Returned" = "seasons", #"Order ID" = 3022],
					        [#"Returned" = "alerts", #"Order ID" = 6818],
					        [#"Returned" = "fight", #"Order ID" = 4619],
					        [#"Returned" = "billy", #"Order ID" = 4588],
					        [#"Returned" = "disaster", #"Order ID" = 2280],
					        [#"Returned" = "procedure", #"Order ID" = 9309],
					        [#"Returned" = "mn", #"Order ID" = 6052],
					        [#"Returned" = "composition", #"Order ID" = 9727],
					        [#"Returned" = "security", #"Order ID" = 5866],
					        [#"Returned" = "associates", #"Order ID" = 6608],
					        [#"Returned" = "jimmy", #"Order ID" = 9712],
					        [#"Returned" = "swiss", #"Order ID" = 9908],
					        [#"Returned" = "still", #"Order ID" = 1551],
					        [#"Returned" = "exposure", #"Order ID" = 6837],
					        [#"Returned" = "montana", #"Order ID" = 7222],
					        [#"Returned" = "rs", #"Order ID" = 8963],
					        [#"Returned" = "official", #"Order ID" = 1886],
					        [#"Returned" = "sub", #"Order ID" = 7543],
					        [#"Returned" = "casinos", #"Order ID" = 8381],
					        [#"Returned" = "empire", #"Order ID" = 8415],
					        [#"Returned" = "settlement", #"Order ID" = 7058],
					        [#"Returned" = "environmental", #"Order ID" = 9759],
					        [#"Returned" = "weather", #"Order ID" = 1727],
					        [#"Returned" = "could", #"Order ID" = 3099],
					        [#"Returned" = "component", #"Order ID" = 6955],
					        [#"Returned" = "join", #"Order ID" = 3221],
					        [#"Returned" = "favor", #"Order ID" = 9345],
					        [#"Returned" = "bargain", #"Order ID" = 1362],
					        [#"Returned" = "rice", #"Order ID" = 9720],
					        [#"Returned" = "moral", #"Order ID" = 5994],
					        [#"Returned" = "bunch", #"Order ID" = 3834],
					        [#"Returned" = "indicated", #"Order ID" = 2899],
					        [#"Returned" = "record", #"Order ID" = 5422],
					        [#"Returned" = "recorder", #"Order ID" = 4612],
					        [#"Returned" = "cassette", #"Order ID" = 6631],
					        [#"Returned" = "sweden", #"Order ID" = 4943],
					        [#"Returned" = "effects", #"Order ID" = 8623],
					        [#"Returned" = "pension", #"Order ID" = 5499],
					        [#"Returned" = "arcade", #"Order ID" = 4392],
					        [#"Returned" = "babe", #"Order ID" = 9668],
					        [#"Returned" = "holiday", #"Order ID" = 6218],
					        [#"Returned" = "defined", #"Order ID" = 1298],
					        [#"Returned" = "dream", #"Order ID" = 9394],
					        [#"Returned" = "hear", #"Order ID" = 3724],
					        [#"Returned" = "tired", #"Order ID" = 5273],
					        [#"Returned" = "around", #"Order ID" = 4123],
					        [#"Returned" = "william", #"Order ID" = 1837],
					        [#"Returned" = "thomas", #"Order ID" = 1792],
					        [#"Returned" = "leather", #"Order ID" = 6934],
					        [#"Returned" = "russia", #"Order ID" = 9885],
					        [#"Returned" = "homepage", #"Order ID" = 1133],
					        [#"Returned" = "keywords", #"Order ID" = 9760],
					        [#"Returned" = "dad", #"Order ID" = 7104],
					        [#"Returned" = "ba", #"Order ID" = 8330],
					        [#"Returned" = "august", #"Order ID" = 6071],
					        [#"Returned" = "lose", #"Order ID" = 9192],
					        [#"Returned" = "fabric", #"Order ID" = 3705],
					        [#"Returned" = "pilot", #"Order ID" = 2310],
					        [#"Returned" = "nylon", #"Order ID" = 4157],
					        [#"Returned" = "massachusetts", #"Order ID" = 8205],
					        [#"Returned" = "opinions", #"Order ID" = 1503],
					        [#"Returned" = "spiritual", #"Order ID" = 3217],
					        [#"Returned" = "immigration", #"Order ID" = 5258],
					        [#"Returned" = "anyway", #"Order ID" = 8558],
					        [#"Returned" = "principal", #"Order ID" = 5723],
					        [#"Returned" = "actions", #"Order ID" = 3615],
					        [#"Returned" = "guilty", #"Order ID" = 4260],
					        [#"Returned" = "grant", #"Order ID" = 1551],
					        [#"Returned" = "cited", #"Order ID" = 3517],
					        [#"Returned" = "random", #"Order ID" = 3272],
					        [#"Returned" = "weddings", #"Order ID" = 7612],
					        [#"Returned" = "source", #"Order ID" = 8808],
					        [#"Returned" = "page", #"Order ID" = 9987],
					        [#"Returned" = "countries", #"Order ID" = 6582],
					        [#"Returned" = "factory", #"Order ID" = 3232],
					        [#"Returned" = "advisory", #"Order ID" = 1013],
					        [#"Returned" = "exchange", #"Order ID" = 8369],
					        [#"Returned" = "it", #"Order ID" = 4531],
					        [#"Returned" = "yoga", #"Order ID" = 5821],
					        [#"Returned" = "peru", #"Order ID" = 3249],
					        [#"Returned" = "overnight", #"Order ID" = 8144],
					        [#"Returned" = "attribute", #"Order ID" = 4214],
					        [#"Returned" = "spam", #"Order ID" = 9691],
					        [#"Returned" = "following", #"Order ID" = 9035],
					        [#"Returned" = "thread", #"Order ID" = 2864],
					        [#"Returned" = "sublime", #"Order ID" = 6502],
					        [#"Returned" = "vista", #"Order ID" = 2851],
					        [#"Returned" = "sectors", #"Order ID" = 8197],
					        [#"Returned" = "fame", #"Order ID" = 5683],
					        [#"Returned" = "enhanced", #"Order ID" = 2601],
					        [#"Returned" = "tiny", #"Order ID" = 6586],
					        [#"Returned" = "quit", #"Order ID" = 8233],
					        [#"Returned" = "association", #"Order ID" = 7872],
					        [#"Returned" = "entity", #"Order ID" = 5433],
					        [#"Returned" = "needs", #"Order ID" = 7060],
					        [#"Returned" = "portuguese", #"Order ID" = 1880],
					        [#"Returned" = "courtesy", #"Order ID" = 9688],
					        [#"Returned" = "mostly", #"Order ID" = 8146],
					        [#"Returned" = "nyc", #"Order ID" = 1348],
					        [#"Returned" = "edwards", #"Order ID" = 7937],
					        [#"Returned" = "today", #"Order ID" = 1921],
					        [#"Returned" = "hampshire", #"Order ID" = 4857],
					        [#"Returned" = "session", #"Order ID" = 1601],
					        [#"Returned" = "harris", #"Order ID" = 4576],
					        [#"Returned" = "licensing", #"Order ID" = 8809],
					        [#"Returned" = "score", #"Order ID" = 6632],
					        [#"Returned" = "reservation", #"Order ID" = 6003],
					        [#"Returned" = "stages", #"Order ID" = 4628],
					        [#"Returned" = "loss", #"Order ID" = 2562],
					        [#"Returned" = "slideshow", #"Order ID" = 3215],
					        [#"Returned" = "catch", #"Order ID" = 8025],
					        [#"Returned" = "expert", #"Order ID" = 4137],
					        [#"Returned" = "pop", #"Order ID" = 1887],
					        [#"Returned" = "event", #"Order ID" = 7763],
					        [#"Returned" = "sponsored", #"Order ID" = 8965],
					        [#"Returned" = "manager", #"Order ID" = 3201],
					        [#"Returned" = "joe", #"Order ID" = 8075],
					        [#"Returned" = "hope", #"Order ID" = 1815],
					        [#"Returned" = "views", #"Order ID" = 2687],
					        [#"Returned" = "tee", #"Order ID" = 1654],
					        [#"Returned" = "muslim", #"Order ID" = 1676],
					        [#"Returned" = "chinese", #"Order ID" = 2277],
					        [#"Returned" = "zero", #"Order ID" = 3014],
					        [#"Returned" = "trouble", #"Order ID" = 8582],
					        [#"Returned" = "private", #"Order ID" = 2650],
					        [#"Returned" = "never", #"Order ID" = 4032],
					        [#"Returned" = "holds", #"Order ID" = 7448],
					        [#"Returned" = "authorized", #"Order ID" = 1502],
					        [#"Returned" = "three", #"Order ID" = 7151],
					        [#"Returned" = "requires", #"Order ID" = 6749],
					        [#"Returned" = "chicken", #"Order ID" = 7393],
					        [#"Returned" = "ocean", #"Order ID" = 4926],
					        [#"Returned" = "sheets", #"Order ID" = 2465],
					        [#"Returned" = "associate", #"Order ID" = 9831],
					        [#"Returned" = "thermal", #"Order ID" = 7269],
					        [#"Returned" = "rise", #"Order ID" = 9105],
					        [#"Returned" = "ordering", #"Order ID" = 3271],
					        [#"Returned" = "passage", #"Order ID" = 2604],
					        [#"Returned" = "wales", #"Order ID" = 1204],
					        [#"Returned" = "else", #"Order ID" = 5923],
					        [#"Returned" = "providing", #"Order ID" = 7973],
					        [#"Returned" = "virginia", #"Order ID" = 1308],
					        [#"Returned" = "respond", #"Order ID" = 5884],
					        [#"Returned" = "serves", #"Order ID" = 4867],
					        [#"Returned" = "maps", #"Order ID" = 6389],
					        [#"Returned" = "depending", #"Order ID" = 1247],
					        [#"Returned" = "fisher", #"Order ID" = 6445],
					        [#"Returned" = "crack", #"Order ID" = 3023],
					        [#"Returned" = "guinea", #"Order ID" = 9006],
					        [#"Returned" = "estimates", #"Order ID" = 3167],
					        [#"Returned" = "trail", #"Order ID" = 2626],
					        [#"Returned" = "coach", #"Order ID" = 3944],
					        [#"Returned" = "calling", #"Order ID" = 9303],
					        [#"Returned" = "need", #"Order ID" = 7614],
					        [#"Returned" = "countries", #"Order ID" = 3671],
					        [#"Returned" = "truth", #"Order ID" = 4972],
					        [#"Returned" = "plaza", #"Order ID" = 5829],
					        [#"Returned" = "administrators", #"Order ID" = 3794],
					        [#"Returned" = "holland", #"Order ID" = 8232],
					        [#"Returned" = "user", #"Order ID" = 3988],
					        [#"Returned" = "phil", #"Order ID" = 5570],
					        [#"Returned" = "skill", #"Order ID" = 5795],
					        [#"Returned" = "elementary", #"Order ID" = 4608],
					        [#"Returned" = "pour", #"Order ID" = 3352],
					        [#"Returned" = "finland", #"Order ID" = 7016],
					        [#"Returned" = "seasons", #"Order ID" = 7596],
					        [#"Returned" = "ghost", #"Order ID" = 9365],
					        [#"Returned" = "tt", #"Order ID" = 3536],
					        [#"Returned" = "toys", #"Order ID" = 4629],
					        [#"Returned" = "depends", #"Order ID" = 8254],
					        [#"Returned" = "berlin", #"Order ID" = 6868],
					        [#"Returned" = "cartridge", #"Order ID" = 6959],
					        [#"Returned" = "theater", #"Order ID" = 6596],
					        [#"Returned" = "significantly", #"Order ID" = 3502],
					        [#"Returned" = "alumni", #"Order ID" = 3894],
					        [#"Returned" = "artificial", #"Order ID" = 5493],
					        [#"Returned" = "city", #"Order ID" = 5931],
					        [#"Returned" = "grew", #"Order ID" = 7746],
					        [#"Returned" = "paypal", #"Order ID" = 6062],
					        [#"Returned" = "pants", #"Order ID" = 3563],
					        [#"Returned" = "finding", #"Order ID" = 3989],
					        [#"Returned" = "longer", #"Order ID" = 4961],
					        [#"Returned" = "hook", #"Order ID" = 9756],
					        [#"Returned" = "travel", #"Order ID" = 6219],
					        [#"Returned" = "materials", #"Order ID" = 4755],
					        [#"Returned" = "nv", #"Order ID" = 1905],
					        [#"Returned" = "ie", #"Order ID" = 4963],
					        [#"Returned" = "echo", #"Order ID" = 3570],
					        [#"Returned" = "important", #"Order ID" = 6533],
					        [#"Returned" = "fotos", #"Order ID" = 7894],
					        [#"Returned" = "the", #"Order ID" = 8058],
					        [#"Returned" = "agricultural", #"Order ID" = 3697],
					        [#"Returned" = "congress", #"Order ID" = 1139],
					        [#"Returned" = "introduced", #"Order ID" = 1638],
					        [#"Returned" = "prove", #"Order ID" = 5677],
					        [#"Returned" = "consent", #"Order ID" = 7781],
					        [#"Returned" = "classes", #"Order ID" = 6659],
					        [#"Returned" = "passed", #"Order ID" = 1805],
					        [#"Returned" = "add", #"Order ID" = 3478],
					        [#"Returned" = "potentially", #"Order ID" = 6600],
					        [#"Returned" = "counsel", #"Order ID" = 6647],
					        [#"Returned" = "gm", #"Order ID" = 6161],
					        [#"Returned" = "coffee", #"Order ID" = 6754],
					        [#"Returned" = "shopper", #"Order ID" = 4248],
					        [#"Returned" = "jay", #"Order ID" = 4754],
					        [#"Returned" = "quotes", #"Order ID" = 3357],
					        [#"Returned" = "navy", #"Order ID" = 3506],
					        [#"Returned" = "harvard", #"Order ID" = 5103],
					        [#"Returned" = "turned", #"Order ID" = 7055],
					        [#"Returned" = "enhanced", #"Order ID" = 5655],
					        [#"Returned" = "estimated", #"Order ID" = 7962],
					        [#"Returned" = "package", #"Order ID" = 5398],
					        [#"Returned" = "variable", #"Order ID" = 2907],
					        [#"Returned" = "remains", #"Order ID" = 4846],
					        [#"Returned" = "collectibles", #"Order ID" = 2731],
					        [#"Returned" = "turkish", #"Order ID" = 5862],
					        [#"Returned" = "careful", #"Order ID" = 1887],
					        [#"Returned" = "lights", #"Order ID" = 6857],
					        [#"Returned" = "something", #"Order ID" = 8881],
					        [#"Returned" = "conducted", #"Order ID" = 7831],
					        [#"Returned" = "well", #"Order ID" = 1681],
					        [#"Returned" = "home", #"Order ID" = 2259],
					        [#"Returned" = "again", #"Order ID" = 2141],
					        [#"Returned" = "taken", #"Order ID" = 5887],
					        [#"Returned" = "lucky", #"Order ID" = 3637],
					        [#"Returned" = "win", #"Order ID" = 5774],
					        [#"Returned" = "sa", #"Order ID" = 2595],
					        [#"Returned" = "sentence", #"Order ID" = 4140],
					        [#"Returned" = "stereo", #"Order ID" = 9530],
					        [#"Returned" = "usage", #"Order ID" = 2339],
					        [#"Returned" = "survey", #"Order ID" = 4112],
					        [#"Returned" = "persons", #"Order ID" = 4353],
					        [#"Returned" = "environment", #"Order ID" = 4206],
					        [#"Returned" = "sorted", #"Order ID" = 1246],
					        [#"Returned" = "waiting", #"Order ID" = 9689],
					        [#"Returned" = "certification", #"Order ID" = 6233],
					        [#"Returned" = "bay", #"Order ID" = 3335],
					        [#"Returned" = "decline", #"Order ID" = 7920],
					        [#"Returned" = "find", #"Order ID" = 2603],
					        [#"Returned" = "estimate", #"Order ID" = 1950],
					        [#"Returned" = "basin", #"Order ID" = 1942],
					        [#"Returned" = "php", #"Order ID" = 4078],
					        [#"Returned" = "ford", #"Order ID" = 9675],
					        [#"Returned" = "console", #"Order ID" = 8796],
					        [#"Returned" = "systems", #"Order ID" = 4504],
					        [#"Returned" = "messenger", #"Order ID" = 9458],
					        [#"Returned" = "admissions", #"Order ID" = 5620],
					        [#"Returned" = "who", #"Order ID" = 9649],
					        [#"Returned" = "teaching", #"Order ID" = 1809],
					        [#"Returned" = "tape", #"Order ID" = 6450],
					        [#"Returned" = "dollar", #"Order ID" = 6626],
					        [#"Returned" = "worlds", #"Order ID" = 6824],
					        [#"Returned" = "bonds", #"Order ID" = 6155],
					        [#"Returned" = "schools", #"Order ID" = 6382],
					        [#"Returned" = "coins", #"Order ID" = 3067],
					        [#"Returned" = "willing", #"Order ID" = 7283],
					        [#"Returned" = "indicates", #"Order ID" = 1586],
					        [#"Returned" = "sitemap", #"Order ID" = 4690],
					        [#"Returned" = "protocol", #"Order ID" = 4334],
					        [#"Returned" = "northwest", #"Order ID" = 7507],
					        [#"Returned" = "stood", #"Order ID" = 4023],
					        [#"Returned" = "ross", #"Order ID" = 1744],
					        [#"Returned" = "gateway", #"Order ID" = 5912],
					        [#"Returned" = "prepare", #"Order ID" = 1844],
					        [#"Returned" = "experienced", #"Order ID" = 4686],
					        [#"Returned" = "contrast", #"Order ID" = 7097],
					        [#"Returned" = "extensive", #"Order ID" = 8114],
					        [#"Returned" = "another", #"Order ID" = 8786],
					        [#"Returned" = "since", #"Order ID" = 3407],
					        [#"Returned" = "clicking", #"Order ID" = 1893],
					        [#"Returned" = "constitutional", #"Order ID" = 9112],
					        [#"Returned" = "viewed", #"Order ID" = 6518],
					        [#"Returned" = "brass", #"Order ID" = 4927],
					        [#"Returned" = "certainly", #"Order ID" = 1082],
					        [#"Returned" = "onto", #"Order ID" = 8655],
					        [#"Returned" = "bulletin", #"Order ID" = 5695],
					        [#"Returned" = "gates", #"Order ID" = 5166],
					        [#"Returned" = "smoke", #"Order ID" = 5963],
					        [#"Returned" = "pearl", #"Order ID" = 3975],
					        [#"Returned" = "child", #"Order ID" = 3273],
					        [#"Returned" = "leather", #"Order ID" = 9098],
					        [#"Returned" = "coupons", #"Order ID" = 7449],
					        [#"Returned" = "cross", #"Order ID" = 9974],
					        [#"Returned" = "function", #"Order ID" = 1577],
					        [#"Returned" = "announcements", #"Order ID" = 2382],
					        [#"Returned" = "that", #"Order ID" = 2369],
					        [#"Returned" = "edition", #"Order ID" = 2766],
					        [#"Returned" = "jackson", #"Order ID" = 9819],
					        [#"Returned" = "oclc", #"Order ID" = 7491],
					        [#"Returned" = "pp", #"Order ID" = 6989],
					        [#"Returned" = "urw", #"Order ID" = 6255],
					        [#"Returned" = "totally", #"Order ID" = 9569],
					        [#"Returned" = "technical", #"Order ID" = 1442],
					        [#"Returned" = "la", #"Order ID" = 9127],
					        [#"Returned" = "object", #"Order ID" = 3720],
					        [#"Returned" = "trend", #"Order ID" = 5094],
					        [#"Returned" = "pointed", #"Order ID" = 2821],
					        [#"Returned" = "site", #"Order ID" = 7309],
					        [#"Returned" = "requires", #"Order ID" = 6955],
					        [#"Returned" = "slow", #"Order ID" = 2042],
					        [#"Returned" = "driver", #"Order ID" = 8058],
					        [#"Returned" = "president", #"Order ID" = 3236],
					        [#"Returned" = "deposit", #"Order ID" = 3525],
					        [#"Returned" = "cooperative", #"Order ID" = 4958],
					        [#"Returned" = "oral", #"Order ID" = 3852]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Returned", type text},
					        {"Order ID", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table