table 'Balance Threshold'
	lineageTag: ad7ef2e3-339d-408c-bc3c-975e3f63deaa

	measure 'Balance Threshold Value' = SELECTEDVALUE('Balance Threshold'[Balance Threshold], 0.0)
		lineageTag: 4be212f5-8a45-4b4b-96de-f980e61f6361

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Threshold'
		dataType: double
		formatString: 0
		lineageTag: 44b5bb64-3d0b-4efe-adfd-6dcfd5c2a43d
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Balance Threshold' = calculated
		mode: import
		source = GENERATESERIES(0.0, 500000.0, 5000.0)

	annotation PBI_Id = e7eb68de16bb49a0b5e8625d6468039c

