table 'FX_PIVOT_Risk_GFIRates_Reports_Excel_Rolling (local copy)'
	lineageTag: 5bbd1426-e433-4518-8f0b-ac9c9a92cc53

	column SLICE_DATE
		dataType: datetime
		lineageTag: ee89a2d0-7bb9-43be-b455-16dc3d7fd374
		summarizeBy: none
		sourceColumn: SLICE_DATE

		annotation SummarizationSetBy = Automatic

	column CURR_FROM
		dataType: string
		lineageTag: f9435203-b9d1-4ac5-88d9-4afb9473fb02
		summarizeBy: none
		sourceColumn: CURR_FROM

		annotation SummarizationSetBy = Automatic

	column TO_AUD
		dataType: double
		formatString: General Number
		lineageTag: 7f45963c-3533-4c13-9f98-589dcb756975
		summarizeBy: sum
		sourceColumn: TO_AUD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_CAD
		dataType: double
		formatString: General Number
		lineageTag: d9b939dc-0ccb-4f48-bb33-06861ad0b196
		summarizeBy: sum
		sourceColumn: TO_CAD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_CHF
		dataType: double
		formatString: General Number
		lineageTag: 2ada4cf0-8d52-4a00-a024-3e60ec5ad7f8
		summarizeBy: sum
		sourceColumn: TO_CHF

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_EUR
		dataType: double
		formatString: General Number
		lineageTag: 70bf7e6b-5e56-47b4-85f3-eb5404e0ff4d
		summarizeBy: sum
		sourceColumn: TO_EUR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_GBP
		dataType: double
		formatString: General Number
		lineageTag: 0b170dde-7011-4e7c-a61f-540efbb4dbd5
		summarizeBy: sum
		sourceColumn: TO_GBP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_HKD
		dataType: double
		formatString: General Number
		lineageTag: 3f13e695-751a-472a-a13a-4a7b084687d1
		summarizeBy: sum
		sourceColumn: TO_HKD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_JPY
		dataType: double
		formatString: General Number
		lineageTag: 517eca08-21bf-47f3-9260-e14b56dd8c15
		summarizeBy: sum
		sourceColumn: TO_JPY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_MXN
		dataType: double
		formatString: General Number
		lineageTag: 61d25b98-3096-46b5-ae1f-5c73b30917ac
		summarizeBy: sum
		sourceColumn: TO_MXN

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_NZD
		dataType: double
		formatString: General Number
		lineageTag: 2b04104c-425c-47cd-a616-4d4f3c63f940
		summarizeBy: sum
		sourceColumn: TO_NZD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_SEK
		dataType: double
		formatString: General Number
		lineageTag: bd1bd8cd-fd91-4a82-b704-3075d68a48aa
		summarizeBy: sum
		sourceColumn: TO_SEK

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_SGD
		dataType: double
		formatString: General Number
		lineageTag: c80b5274-2e7c-4849-96f5-cb925494e99c
		summarizeBy: sum
		sourceColumn: TO_SGD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_USD
		dataType: double
		formatString: General Number
		lineageTag: 8804717d-6cfd-4b29-a52a-65ec854c6b5b
		summarizeBy: sum
		sourceColumn: TO_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_MEX
		dataType: double
		formatString: General Number
		lineageTag: 0fa49fa2-cc8e-4196-9c28-dea4a3ca0ffd
		summarizeBy: sum
		sourceColumn: TO_MEX

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ADDED_DATE
		dataType: datetime
		lineageTag: c4ed7785-42a8-43e7-ae2e-60fdeee63f4c
		summarizeBy: none
		sourceColumn: ADDED_DATE

		annotation SummarizationSetBy = Automatic

	column ADDED_USER
		dataType: string
		lineageTag: 6fd74e75-4a7e-4d01-8915-d054677051d3
		summarizeBy: none
		sourceColumn: ADDED_USER

		annotation SummarizationSetBy = Automatic

	column TO_BRL
		dataType: double
		formatString: General Number
		lineageTag: 8500f698-cfef-4eaf-89e8-da86fa4650b3
		summarizeBy: sum
		sourceColumn: TO_BRL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_BRO
		dataType: double
		formatString: General Number
		lineageTag: d9d7bfe7-ac7c-4d67-a001-75ac82cbcaeb
		summarizeBy: sum
		sourceColumn: TO_BRO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_CLF
		dataType: double
		formatString: General Number
		lineageTag: 3136b20d-23a6-49ce-9777-f682a1f69e0a
		summarizeBy: sum
		sourceColumn: TO_CLF

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_CLP
		dataType: double
		formatString: General Number
		lineageTag: 446fe1fb-8bc7-45b7-9c2c-ccafb73f3fc2
		summarizeBy: sum
		sourceColumn: TO_CLP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_CNH
		dataType: double
		formatString: General Number
		lineageTag: 5d66585b-2052-4a5a-a2ce-1ffbf84a5d62
		summarizeBy: sum
		sourceColumn: TO_CNH

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_COP
		dataType: double
		formatString: General Number
		lineageTag: 96dc7ee0-e9ed-4443-a4f7-ef373eee2b44
		summarizeBy: sum
		sourceColumn: TO_COP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_CRC
		dataType: double
		formatString: General Number
		lineageTag: 84ecefb4-947c-4d37-ba83-17dc6e1adad8
		summarizeBy: sum
		sourceColumn: TO_CRC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_INR
		dataType: double
		formatString: General Number
		lineageTag: b760589f-9bfb-4d10-bead-91b957452d36
		summarizeBy: sum
		sourceColumn: TO_INR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_KRW
		dataType: double
		formatString: General Number
		lineageTag: 2309185b-4055-4cfd-8acf-db2e9469e4c1
		summarizeBy: sum
		sourceColumn: TO_KRW

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_MXC
		dataType: double
		formatString: General Number
		lineageTag: 4c4807a6-00bf-4218-b172-480d4f9419fc
		summarizeBy: sum
		sourceColumn: TO_MXC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_MYR
		dataType: double
		formatString: General Number
		lineageTag: fe5414fd-25dc-436f-9f87-3ffb9a125f19
		summarizeBy: sum
		sourceColumn: TO_MYR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_PEN
		dataType: double
		formatString: General Number
		lineageTag: ddebd1e3-5a51-420d-9424-1757fe0e802f
		summarizeBy: sum
		sourceColumn: TO_PEN

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_UVR
		dataType: double
		formatString: General Number
		lineageTag: c967cc0d-8feb-4f01-a527-cdbd3a3ee45c
		summarizeBy: sum
		sourceColumn: TO_UVR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_UYU
		dataType: double
		formatString: General Number
		lineageTag: 01371e58-978d-423b-bd6a-904eb02f7929
		summarizeBy: sum
		sourceColumn: TO_UYU

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MARKET_DATA_SOURCE_ID
		dataType: int64
		formatString: 0
		lineageTag: 91e9d071-4818-4006-9415-006edfe19101
		summarizeBy: sum
		sourceColumn: MARKET_DATA_SOURCE_ID

		annotation SummarizationSetBy = Automatic

	partition 'FX_PIVOT_Risk_GFIRates_Reports_Excel_Rolling (local copy)' = m
		mode: import
		source =
				let
					    Source = Csv.Document(
					        File.Contents("https://saastestlatest.blob.core.windows.net/saas-test-reports/FX_PIVOT_Risk_GFIRates_Reports_Excel_Rolling%20%28local%20copy%29.csv?se=2025-11-05T16%3A12%3A34Z&sp=r&sv=2025-11-05&sr=b&sig=VHsfHLdAKmGt1iX%2BYj3RC7ZRaU3Twr42Q/CwV40x2wo%3D"),
					        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
					    ),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SLICE_DATE", type datetime}, {"CURR_FROM", type text}, {"TO_AUD", type number}, {"TO_CAD", type number}, {"TO_CHF", type number}, {"TO_EUR", type number}, {"TO_GBP", type number}, {"TO_HKD", type number}, {"TO_JPY", type number}, {"TO_MXN", type number}, {"TO_NZD", type number}, {"TO_SEK", type number}, {"TO_SGD", type number}, {"TO_USD", type number}, {"TO_MEX", type number}, {"ADDED_DATE", type datetime}, {"ADDED_USER", type text}, {"TO_BRL", type number}, {"TO_BRO", type number}, {"TO_CLF", type number}, {"TO_CLP", type number}, {"TO_CNH", type number}, {"TO_COP", type number}, {"TO_CRC", type number}, {"TO_INR", type number}, {"TO_KRW", type number}, {"TO_MXC", type number}, {"TO_MYR", type number}, {"TO_PEN", type number}, {"TO_UVR", type number}, {"TO_UYU", type number}, {"MARKET_DATA_SOURCE_ID", Int64.Type}})
					in
					    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table