table 'RDV_SNAPSHOT_DAYS_LOG_Risk_GFIRates_Reports_Excel_Rolling (local copy)'
	lineageTag: 4c59e825-2b4f-401c-bfab-eecabcd1154d

	column RUN_NUMBER
		dataType: double
		formatString: General Number
		lineageTag: e08c0025-1cbc-45d1-bb8a-c71955fa4d34
		summarizeBy: sum
		sourceColumn: RUN_NUMBER

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RDV_DAYS_TYPE
		dataType: string
		lineageTag: bcf9b27e-cc38-41f7-aef5-a3c227834987
		summarizeBy: none
		sourceColumn: RDV_DAYS_TYPE

		annotation SummarizationSetBy = Automatic

	column EFFECTIVE_DATE
		dataType: datetime
		lineageTag: 7bdb5744-d5f7-47ab-bd8e-30576c31c4f7
		summarizeBy: none
		sourceColumn: EFFECTIVE_DATE

		annotation SummarizationSetBy = Automatic

	column SOURCE_ID
		dataType: int64
		formatString: 0
		lineageTag: 937cf37d-f2c5-43a5-955a-0561b08d4134
		summarizeBy: sum
		sourceColumn: SOURCE_ID

		annotation SummarizationSetBy = Automatic

	column EXEC_DURATION
		dataType: double
		formatString: General Number
		lineageTag: ed4e51d0-4d87-42f9-88ab-05879171d2d6
		summarizeBy: sum
		sourceColumn: EXEC_DURATION

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RECORD_COUNT
		dataType: double
		formatString: General Number
		lineageTag: 10381a6c-f760-42a4-9f51-138f41eaf090
		summarizeBy: sum
		sourceColumn: RECORD_COUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PROCESS_END_DTTM
		dataType: datetime
		lineageTag: 0642d8a1-2794-4a65-8c1b-8e006d8fa219
		summarizeBy: none
		sourceColumn: PROCESS_END_DTTM

		annotation SummarizationSetBy = Automatic

	column SOURCE_NAME
		dataType: string
		lineageTag: 169c793d-eac7-433e-8bb5-6233f43a9ac4
		summarizeBy: none
		sourceColumn: SOURCE_NAME

		annotation SummarizationSetBy = Automatic

	column PERFORMANCE_MEASURE
		dataType: double
		formatString: General Number
		lineageTag: bc324c7a-91fd-4578-a833-01a8891f4c8a
		summarizeBy: sum
		sourceColumn: PERFORMANCE_MEASURE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ALERT_TYPE
		dataType: string
		lineageTag: aef95297-224b-4069-8de8-d8dbe7c49f76
		summarizeBy: none
		sourceColumn: ALERT_TYPE

		annotation SummarizationSetBy = Automatic

	column RISK_LOAD_END_DTTM
		dataType: datetime
		lineageTag: e45e981f-958c-4726-a51a-f3391c6d3423
		summarizeBy: none
		sourceColumn: RISK_LOAD_END_DTTM

		annotation SummarizationSetBy = Automatic

	partition 'RDV_SNAPSHOT_DAYS_LOG_Risk_GFIRates_Reports_Excel_Rolling (local copy)' = m
		mode: import
		source =
				let
					    Source = Csv.Document(
					        File.Contents("https://saastestlatest.blob.core.windows.net/saas-test-reports/RDV_SNAPSHOT_DAYS_LOG_Risk_GFIRates_Reports_Excel_Rolling%20%28local%20copy%29.csv?se=2025-11-05T16%3A11%3A52Z&sp=r&sv=2025-11-05&sr=b&sig=sV/2Wb5F8leoCOfBkq8PhreuOJepl1cEUh79ljyfFb0%3D"),
					        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
					    ),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"RUN_NUMBER", type number}, {"RDV_DAYS_TYPE", type text}, {"EFFECTIVE_DATE", type datetime}, {"SOURCE_ID", Int64.Type}, {"EXEC_DURATION", type number}, {"RECORD_COUNT", type number}, {"PROCESS_END_DTTM", type datetime}, {"SOURCE_NAME", type text}, {"PERFORMANCE_MEASURE", type number}, {"ALERT_TYPE", type text}, {"RISK_LOAD_END_DTTM", type datetime}})
					in
					    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table