table 'Profit Bin Size'
	lineageTag: 0a625034-89cd-4912-80b5-a065c135a87f

	measure 'Profit Bin Size Value' = SELECTEDVALUE('Profit Bin Size'[Profit Bin Size], 50)
		lineageTag: 4e62fa4f-cc9f-48d8-b0e4-7a61eed93e82

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Profit Bin Size'
		dataType: double
		formatString: 0
		lineageTag: 60f7f9e4-843e-482c-8457-bfc2c6af6287
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Profit Bin Size' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_Id = 60290bd4a7ff4276ac82926a2dd8911c

