table 'CALL_CENTER+ (Multiple Connections)'
	lineageTag: 9c364b1a-a994-4b24-86bf-0cb88c2e0b06

	column CC_CALL_CENTER_SK
		dataType: int64
		formatString: 0
		lineageTag: f77398df-a7b0-4dc6-b5b5-4c9837e22074
		summarizeBy: sum
		sourceColumn: CC_CALL_CENTER_SK

		annotation SummarizationSetBy = Automatic

	column CC_CALL_CENTER_ID
		dataType: string
		lineageTag: db6642d5-be77-4b1f-9a9a-df0263cd096d
		summarizeBy: none
		sourceColumn: CC_CALL_CENTER_ID

		annotation SummarizationSetBy = Automatic

	column CC_REC_START_DATE
		dataType: datetime
		lineageTag: dbf20374-17ed-4691-82e3-a890137e53ae
		summarizeBy: none
		sourceColumn: CC_REC_START_DATE

		annotation SummarizationSetBy = Automatic

	column CC_REC_END_DATE
		dataType: datetime
		lineageTag: f327f099-373d-41d9-94ad-2f3f57483d20
		summarizeBy: none
		sourceColumn: CC_REC_END_DATE

		annotation SummarizationSetBy = Automatic

	column CC_CLOSED_DATE_SK
		dataType: int64
		formatString: 0
		lineageTag: 8eafaec9-ea5b-486a-8a88-5e248a399221
		summarizeBy: sum
		sourceColumn: CC_CLOSED_DATE_SK

		annotation SummarizationSetBy = Automatic

	column CC_OPEN_DATE_SK
		dataType: int64
		formatString: 0
		lineageTag: bfaa0dc0-1840-4342-baa7-e65000782353
		summarizeBy: sum
		sourceColumn: CC_OPEN_DATE_SK

		annotation SummarizationSetBy = Automatic

	column CC_NAME
		dataType: string
		lineageTag: 1591aaeb-ca57-403a-aaee-e87bba7e8517
		summarizeBy: none
		sourceColumn: CC_NAME

		annotation SummarizationSetBy = Automatic

	column CC_CLASS
		dataType: string
		lineageTag: ed2366bf-1848-472f-bb4a-11366005807a
		summarizeBy: none
		sourceColumn: CC_CLASS

		annotation SummarizationSetBy = Automatic

	column CC_EMPLOYEES
		dataType: int64
		formatString: 0
		lineageTag: 922414f7-d0bd-4df3-b0af-fcc3e823af9c
		summarizeBy: sum
		sourceColumn: CC_EMPLOYEES

		annotation SummarizationSetBy = Automatic

	column CC_SQ_FT
		dataType: int64
		formatString: 0
		lineageTag: 8f6d5f81-e809-423e-9824-509d62d9cfb3
		summarizeBy: sum
		sourceColumn: CC_SQ_FT

		annotation SummarizationSetBy = Automatic

	column CC_HOURS
		dataType: string
		lineageTag: adba7fd7-c223-434a-8358-ff4fea3f6b16
		summarizeBy: none
		sourceColumn: CC_HOURS

		annotation SummarizationSetBy = Automatic

	column CC_MANAGER
		dataType: string
		lineageTag: 9b84b4e9-a64d-4b58-a0a3-68b9064ca7a1
		summarizeBy: none
		sourceColumn: CC_MANAGER

		annotation SummarizationSetBy = Automatic

	column CC_MKT_ID
		dataType: int64
		formatString: 0
		lineageTag: 25c6c0b4-5263-417e-bd97-0814abea0b34
		summarizeBy: sum
		sourceColumn: CC_MKT_ID

		annotation SummarizationSetBy = Automatic

	column CC_MKT_CLASS
		dataType: string
		lineageTag: 9eca3867-8efa-495d-a95e-a6327c72362e
		summarizeBy: none
		sourceColumn: CC_MKT_CLASS

		annotation SummarizationSetBy = Automatic

	column CC_MKT_DESC
		dataType: string
		lineageTag: c709305a-ffa1-4880-b7a4-b4da600172df
		summarizeBy: none
		sourceColumn: CC_MKT_DESC

		annotation SummarizationSetBy = Automatic

	column CC_MARKET_MANAGER
		dataType: string
		lineageTag: c1ae3efa-4256-4cf3-815f-d61faad194d9
		summarizeBy: none
		sourceColumn: CC_MARKET_MANAGER

		annotation SummarizationSetBy = Automatic

	column CC_DIVISION
		dataType: int64
		formatString: 0
		lineageTag: fc81a64b-6efe-44d3-8981-f5183e7dee1b
		summarizeBy: sum
		sourceColumn: CC_DIVISION

		annotation SummarizationSetBy = Automatic

	column CC_DIVISION_NAME
		dataType: string
		lineageTag: 32c8ee1c-f527-43eb-bc38-4cefce8c8fff
		summarizeBy: none
		sourceColumn: CC_DIVISION_NAME

		annotation SummarizationSetBy = Automatic

	column CC_COMPANY
		dataType: int64
		formatString: 0
		lineageTag: 0572ea06-fde4-46a0-9121-b1d329e22149
		summarizeBy: sum
		sourceColumn: CC_COMPANY

		annotation SummarizationSetBy = Automatic

	column CC_COMPANY_NAME
		dataType: string
		lineageTag: 27aba2f3-1bb6-4e93-b871-28b8ace19ac7
		summarizeBy: none
		sourceColumn: CC_COMPANY_NAME

		annotation SummarizationSetBy = Automatic

	column CC_STREET_NUMBER
		dataType: string
		lineageTag: ee0df229-034c-4c63-9461-fd1c0da0ae93
		summarizeBy: none
		sourceColumn: CC_STREET_NUMBER

		annotation SummarizationSetBy = Automatic

	column CC_STREET_NAME
		dataType: string
		lineageTag: a29ffcc1-c83a-4094-80a8-8aa04a48e448
		summarizeBy: none
		sourceColumn: CC_STREET_NAME

		annotation SummarizationSetBy = Automatic

	column CC_STREET_TYPE
		dataType: string
		lineageTag: b82abecb-b60c-471e-b22d-ffb1dd06cb3b
		summarizeBy: none
		sourceColumn: CC_STREET_TYPE

		annotation SummarizationSetBy = Automatic

	column CC_SUITE_NUMBER
		dataType: string
		lineageTag: d006b5bf-8b6d-4f1f-8881-803e32b3242f
		summarizeBy: none
		sourceColumn: CC_SUITE_NUMBER

		annotation SummarizationSetBy = Automatic

	column CC_CITY
		dataType: string
		lineageTag: 5c366ff6-c8a8-41c2-859a-72992ec5eb5a
		summarizeBy: none
		sourceColumn: CC_CITY

		annotation SummarizationSetBy = Automatic

	column CC_COUNTY
		dataType: string
		lineageTag: 6bbf62bb-fbd3-4f3b-bb9a-37f337e3952a
		summarizeBy: none
		sourceColumn: CC_COUNTY

		annotation SummarizationSetBy = Automatic

	column CC_STATE
		dataType: string
		lineageTag: 8629fe5e-b312-49db-ac2e-f13779a4b18d
		summarizeBy: none
		sourceColumn: CC_STATE

		annotation SummarizationSetBy = Automatic

	column CC_ZIP
		dataType: string
		lineageTag: 88ca2c42-b46b-4676-877b-924b825606e3
		summarizeBy: none
		sourceColumn: CC_ZIP

		annotation SummarizationSetBy = Automatic

	column CC_COUNTRY
		dataType: string
		lineageTag: 5c6bc59f-7362-433c-9fa6-cefa38f00d8a
		summarizeBy: none
		sourceColumn: CC_COUNTRY

		annotation SummarizationSetBy = Automatic

	column CC_GMT_OFFSET
		dataType: double
		formatString: General Number
		lineageTag: 79be04a6-e85e-4323-802e-d11060371c07
		summarizeBy: sum
		sourceColumn: CC_GMT_OFFSET

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CC_TAX_PERCENTAGE
		dataType: double
		formatString: General Number
		lineageTag: 02f49f8f-00c1-43b8-8a48-fc6589341035
		summarizeBy: sum
		sourceColumn: CC_TAX_PERCENTAGE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CP_CATALOG_PAGE_SK
		dataType: int64
		formatString: 0
		lineageTag: 84c0adc6-ea1c-431b-acfb-cee17707f151
		summarizeBy: sum
		sourceColumn: CP_CATALOG_PAGE_SK

		annotation SummarizationSetBy = Automatic

	column CP_CATALOG_PAGE_ID
		dataType: string
		lineageTag: 6d0ab0e8-d627-4747-96bc-eed17a23ac1f
		summarizeBy: none
		sourceColumn: CP_CATALOG_PAGE_ID

		annotation SummarizationSetBy = Automatic

	column CP_START_DATE_SK
		dataType: int64
		formatString: 0
		lineageTag: edd25212-e24c-4e96-b1f1-b6053d5613dd
		summarizeBy: sum
		sourceColumn: CP_START_DATE_SK

		annotation SummarizationSetBy = Automatic

	column CP_END_DATE_SK
		dataType: int64
		formatString: 0
		lineageTag: c104242e-18a6-48ea-9d88-075b3e871dc8
		summarizeBy: sum
		sourceColumn: CP_END_DATE_SK

		annotation SummarizationSetBy = Automatic

	column CP_DEPARTMENT
		dataType: string
		lineageTag: eba36a91-1d2c-4b32-ac99-930036d8ef70
		summarizeBy: none
		sourceColumn: CP_DEPARTMENT

		annotation SummarizationSetBy = Automatic

	column CP_CATALOG_NUMBER
		dataType: int64
		formatString: 0
		lineageTag: f301d197-cecc-4819-a85a-2275680c4618
		summarizeBy: sum
		sourceColumn: CP_CATALOG_NUMBER

		annotation SummarizationSetBy = Automatic

	column CP_CATALOG_PAGE_NUMBER
		dataType: int64
		formatString: 0
		lineageTag: 5ca937ae-6b32-462f-ae38-5c64e9839a7a
		summarizeBy: sum
		sourceColumn: CP_CATALOG_PAGE_NUMBER

		annotation SummarizationSetBy = Automatic

	column CP_DESCRIPTION
		dataType: string
		lineageTag: 381ee86b-d6b9-41db-9cfb-185aad9bc663
		summarizeBy: none
		sourceColumn: CP_DESCRIPTION

		annotation SummarizationSetBy = Automatic

	column CP_TYPE
		dataType: string
		lineageTag: 1e03d96c-7e37-414d-b76a-fadf14feed1f
		summarizeBy: none
		sourceColumn: CP_TYPE

		annotation SummarizationSetBy = Automatic

	partition 'CALL_CENTER+ (Multiple Connections)' = m
		mode: import
		source =
				let 
					#"Source0" = Table.NestedJoin(#"CALL_CENTER_CALL_CENTER+ (Multiple Connections)", {"CC_CALL_CENTER_ID"}, #"CATALOG_PAGE_CALL_CENTER+ (Multiple Connections)", {"CP_CATALOG_PAGE_ID"}, "CATALOG_PAGE_CALL_CENTER+ (Multiple Connections)", JoinKind.Inner),
					#"Expand0" = Table.ExpandTableColumn(#"Source0", "CATALOG_PAGE_CALL_CENTER+ (Multiple Connections)", {"CP_CATALOG_PAGE_SK", "CP_CATALOG_PAGE_ID", "CP_START_DATE_SK", "CP_END_DATE_SK", "CP_DEPARTMENT", "CP_CATALOG_NUMBER", "CP_CATALOG_PAGE_NUMBER", "CP_DESCRIPTION", "CP_TYPE"}, {"CP_CATALOG_PAGE_SK", "CP_CATALOG_PAGE_ID", "CP_START_DATE_SK", "CP_END_DATE_SK", "CP_DEPARTMENT", "CP_CATALOG_NUMBER", "CP_CATALOG_PAGE_NUMBER", "CP_DESCRIPTION", "CP_TYPE"}),
					#"Source1" = Table.NestedJoin(#"Expand0", {"CC_CALL_CENTER_SK"}, #"CALL_CENTER+ (Multiple Connections)_CALL_CENTER", {"CR_CATALOG_PAGE_SK"}, "CALL_CENTER+ (Multiple Connections)_CALL_CENTER", JoinKind.LeftOuter),
					#"Expand1" = Table.ExpandTableColumn(#"Source1", "CALL_CENTER+ (Multiple Connections)_CALL_CENTER", {"CR_RETURNED_DATE_SK", "CR_RETURNED_TIME_SK", "CR_ITEM_SK", "CR_REFUNDED_CUSTOMER_SK", "CR_REFUNDED_CDEMO_SK", "CR_REFUNDED_HDEMO_SK", "CR_REFUNDED_ADDR_SK", "CR_RETURNING_CUSTOMER_SK", "CR_RETURNING_CDEMO_SK", "CR_RETURNING_HDEMO_SK", "CR_RETURNING_ADDR_SK", "CR_CALL_CENTER_SK", "CR_CATALOG_PAGE_SK", "CR_SHIP_MODE_SK", "CR_WAREHOUSE_SK", "CR_REASON_SK", "CR_ORDER_NUMBER", "CR_RETURN_QUANTITY", "CR_RETURN_AMOUNT", "CR_RETURN_TAX", "CR_RETURN_AMT_INC_TAX", "CR_FEE", "CR_RETURN_SHIP_COST", "CR_REFUNDED_CASH", "CR_REVERSED_CHARGE", "CR_STORE_CREDIT", "CR_NET_LOSS", "CS_SOLD_DATE_SK", "CS_SOLD_TIME_SK", "CS_SHIP_DATE_SK", "CS_BILL_CUSTOMER_SK", "CS_BILL_CDEMO_SK", "CS_BILL_HDEMO_SK", "CS_BILL_ADDR_SK", "CS_SHIP_CUSTOMER_SK", "CS_SHIP_CDEMO_SK", "CS_SHIP_HDEMO_SK", "CS_SHIP_ADDR_SK", "CS_CALL_CENTER_SK", "CS_CATALOG_PAGE_SK", "CS_SHIP_MODE_SK", "CS_WAREHOUSE_SK", "CS_ITEM_SK", "CS_PROMO_SK", "CS_ORDER_NUMBER", "CS_QUANTITY", "CS_WHOLESALE_COST", "CS_LIST_PRICE", "CS_SALES_PRICE", "CS_EXT_DISCOUNT_AMT", "CS_EXT_SALES_PRICE", "CS_EXT_WHOLESALE_COST", "CS_EXT_LIST_PRICE", "CS_EXT_TAX", "CS_COUPON_AMT", "CS_EXT_SHIP_COST", "CS_NET_PAID", "CS_NET_PAID_INC_TAX", "CS_NET_PAID_INC_SHIP", "CS_NET_PAID_INC_SHIP_TAX", "CS_NET_PROFIT", "Table Name"}, {"CR_RETURNED_DATE_SK", "CR_RETURNED_TIME_SK", "CR_ITEM_SK", "CR_REFUNDED_CUSTOMER_SK", "CR_REFUNDED_CDEMO_SK", "CR_REFUNDED_HDEMO_SK", "CR_REFUNDED_ADDR_SK", "CR_RETURNING_CUSTOMER_SK", "CR_RETURNING_CDEMO_SK", "CR_RETURNING_HDEMO_SK", "CR_RETURNING_ADDR_SK", "CR_CALL_CENTER_SK", "CR_CATALOG_PAGE_SK", "CR_SHIP_MODE_SK", "CR_WAREHOUSE_SK", "CR_REASON_SK", "CR_ORDER_NUMBER", "CR_RETURN_QUANTITY", "CR_RETURN_AMOUNT", "CR_RETURN_TAX", "CR_RETURN_AMT_INC_TAX", "CR_FEE", "CR_RETURN_SHIP_COST", "CR_REFUNDED_CASH", "CR_REVERSED_CHARGE", "CR_STORE_CREDIT", "CR_NET_LOSS", "CS_SOLD_DATE_SK", "CS_SOLD_TIME_SK", "CS_SHIP_DATE_SK", "CS_BILL_CUSTOMER_SK", "CS_BILL_CDEMO_SK", "CS_BILL_HDEMO_SK", "CS_BILL_ADDR_SK", "CS_SHIP_CUSTOMER_SK", "CS_SHIP_CDEMO_SK", "CS_SHIP_HDEMO_SK", "CS_SHIP_ADDR_SK", "CS_CALL_CENTER_SK", "CS_CATALOG_PAGE_SK", "CS_SHIP_MODE_SK", "CS_WAREHOUSE_SK", "CS_ITEM_SK", "CS_PROMO_SK", "CS_ORDER_NUMBER", "CS_QUANTITY", "CS_WHOLESALE_COST", "CS_LIST_PRICE", "CS_SALES_PRICE", "CS_EXT_DISCOUNT_AMT", "CS_EXT_SALES_PRICE", "CS_EXT_WHOLESALE_COST", "CS_EXT_LIST_PRICE", "CS_EXT_TAX", "CS_COUPON_AMT", "CS_EXT_SHIP_COST", "CS_NET_PAID", "CS_NET_PAID_INC_TAX", "CS_NET_PAID_INC_SHIP", "CS_NET_PAID_INC_SHIP_TAX", "CS_NET_PROFIT", "Table Name"})
					in #"Expand1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table