table 'Profit Bin Size'
	lineageTag: fbfc7ebc-01c7-4af5-8634-c798a9abbc19

	measure 'Profit Bin Size Value' = SELECTEDVALUE('Profit Bin Size'[Profit Bin Size], 50)
		lineageTag: fe5f2968-f0b1-473f-8730-1b898accd84b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Profit Bin Size'
		dataType: double
		formatString: 0
		lineageTag: d51782ce-fad8-4a78-af9f-3a3d67ae1249
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Profit Bin Size' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_Id = 5e55e345d9604b8f9f53641a0c48ebe5

