table 'Top Manufacturers'
	lineageTag: fb6d1543-b282-4cba-9b9f-ba9dfaf6e9f3

	measure 'Top Manufacturers Value' = SELECTEDVALUE('Top Manufacturers'[Top Manufacturers], 10)
		lineageTag: 484876c4-bd1d-4e27-a5f7-e9a68ed30d3f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Top Manufacturers'
		dataType: double
		formatString: 0
		lineageTag: 6f2ee1bf-b6a7-4141-9cad-3f45929b2218
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Top Manufacturers' = calculated
		mode: import
		source = GENERATESERIES(10, 50, 1)

	annotation PBI_Id = de09e76f16864003afcf65b1f345fee8

