table 'HR Dataset'
	lineageTag: 92a49479-59b9-4369-b02e-a78a6fd48b22

	measure 'dep calc 3' = SUM('HR Dataset'[dep calc 2])
		formatString: 0
		lineageTag: 02c6562c-7dfe-4be3-afa8-fc2f60288f28

	column Employee_Name
		dataType: string
		lineageTag: 80a96f01-f582-464f-ae4e-a4a7205c6816
		summarizeBy: none
		sourceColumn: Employee_Name

		annotation SummarizationSetBy = Automatic

	column EmpID
		dataType: int64
		formatString: 0
		lineageTag: 0499ebff-e7e2-437b-8d2f-63faecc4d69a
		summarizeBy: sum
		sourceColumn: EmpID

		annotation SummarizationSetBy = Automatic

	column MarriedID
		dataType: int64
		formatString: 0
		lineageTag: 357a35cf-d6d6-4d19-83fe-18f28ac6e337
		summarizeBy: sum
		sourceColumn: MarriedID

		annotation SummarizationSetBy = Automatic

	column MaritalStatusID
		dataType: int64
		formatString: 0
		lineageTag: 38886764-da97-4fac-b9be-c4f05a9e2d55
		summarizeBy: sum
		sourceColumn: MaritalStatusID

		annotation SummarizationSetBy = Automatic

	column GenderID
		dataType: int64
		formatString: 0
		lineageTag: 8c2e9d2b-1f7b-4018-8731-088aec5019cb
		summarizeBy: sum
		sourceColumn: GenderID

		annotation SummarizationSetBy = Automatic

	column EmpStatusID
		dataType: int64
		formatString: 0
		lineageTag: 0f3a2e4c-d6e7-481a-926d-2cada534edb7
		summarizeBy: sum
		sourceColumn: EmpStatusID

		annotation SummarizationSetBy = Automatic

	column DeptID
		dataType: int64
		formatString: 0
		lineageTag: 60f3f006-a00a-44a9-8f65-dc37f3f79998
		summarizeBy: sum
		sourceColumn: DeptID

		annotation SummarizationSetBy = Automatic

	column PerfScoreID
		dataType: int64
		formatString: 0
		lineageTag: 67097118-54f5-4b24-845f-c3fdc1dca6ee
		summarizeBy: sum
		sourceColumn: PerfScoreID

		annotation SummarizationSetBy = Automatic

	column FromDiversityJobFairID
		dataType: int64
		formatString: 0
		lineageTag: ca2b3044-f917-4b00-926a-bd082d0c76fa
		summarizeBy: sum
		sourceColumn: FromDiversityJobFairID

		annotation SummarizationSetBy = Automatic

	column Salary
		dataType: int64
		formatString: 0
		lineageTag: 0400efc4-03ca-4f43-975d-931e7e65e12f
		summarizeBy: sum
		sourceColumn: Salary

		annotation SummarizationSetBy = Automatic

	column Termd
		dataType: int64
		formatString: 0
		lineageTag: 680581d4-501c-4669-9a43-edb68b3f30d9
		summarizeBy: sum
		sourceColumn: Termd

		annotation SummarizationSetBy = Automatic

	column PositionID
		dataType: int64
		formatString: 0
		lineageTag: 83a1ddb7-a585-4b6a-beea-a92de33e83fb
		summarizeBy: sum
		sourceColumn: PositionID

		annotation SummarizationSetBy = Automatic

	column Position
		dataType: string
		lineageTag: 9bea3c83-fb84-43bb-8957-886a78c73c89
		summarizeBy: none
		sourceColumn: Position

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: b0200fc4-33d2-47e2-b844-45c7ac9618f4
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Zip
		dataType: int64
		formatString: 0
		lineageTag: ad3a5008-a557-445d-976e-ef4ec523bde0
		summarizeBy: sum
		sourceColumn: Zip

		annotation SummarizationSetBy = Automatic

	column DOB
		dataType: datetime
		lineageTag: ef426199-6f4f-4fb7-923c-eeb606a9f6a1
		summarizeBy: none
		sourceColumn: DOB

		annotation SummarizationSetBy = Automatic

	column Sex
		dataType: string
		lineageTag: 8c012d9b-c01e-45ae-82d2-adda2751f239
		summarizeBy: none
		sourceColumn: Sex

		annotation SummarizationSetBy = Automatic

	column MaritalDesc
		dataType: string
		lineageTag: 93740409-ecc0-4930-8d3c-ad8ab0acd032
		summarizeBy: none
		sourceColumn: MaritalDesc

		annotation SummarizationSetBy = Automatic

	column CitizenDesc
		dataType: string
		lineageTag: d4054efa-7078-476e-b545-7269e6085d4e
		summarizeBy: none
		sourceColumn: CitizenDesc

		annotation SummarizationSetBy = Automatic

	column HispanicLatino
		dataType: string
		lineageTag: 3fc640e5-c297-4180-a23e-77d6675ecdd0
		summarizeBy: none
		sourceColumn: HispanicLatino

		annotation SummarizationSetBy = Automatic

	column RaceDesc
		dataType: string
		lineageTag: 9db28809-a88a-40e2-8fb1-0be6fd9c71c3
		summarizeBy: none
		sourceColumn: RaceDesc

		annotation SummarizationSetBy = Automatic

	column DateofHire
		dataType: datetime
		lineageTag: 02ace54d-d8d9-46a5-b440-00665c66cc4c
		summarizeBy: none
		sourceColumn: DateofHire

		annotation SummarizationSetBy = Automatic

	column DateofTermination
		dataType: datetime
		lineageTag: 678b77cf-b4b1-434f-876e-c5e53d328add
		summarizeBy: none
		sourceColumn: DateofTermination

		annotation SummarizationSetBy = Automatic

	column TermReason
		dataType: string
		lineageTag: ad5ddc09-f3cf-4488-8b2a-ba885df8407e
		summarizeBy: none
		sourceColumn: TermReason

		annotation SummarizationSetBy = Automatic

	column EmploymentStatus
		dataType: string
		lineageTag: d892ffe0-d521-4dda-8c81-64ba5fa8a377
		summarizeBy: none
		sourceColumn: EmploymentStatus

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: e31f555f-9772-45ff-a749-96425d8522b1
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column ManagerName
		dataType: string
		lineageTag: 26461050-674c-433e-a63e-4d5499456793
		summarizeBy: none
		sourceColumn: ManagerName

		annotation SummarizationSetBy = Automatic

	column ManagerID
		dataType: int64
		formatString: 0
		lineageTag: 82a6b3b0-0cd2-4f4a-ba1e-b8c15980f75a
		summarizeBy: sum
		sourceColumn: ManagerID

		annotation SummarizationSetBy = Automatic

	column RecruitmentSource
		dataType: string
		lineageTag: 52ce97c0-4184-4195-bb49-8703e4067cd3
		summarizeBy: none
		sourceColumn: RecruitmentSource

		annotation SummarizationSetBy = Automatic

	column PerformanceScore
		dataType: string
		lineageTag: fbce83c3-dd68-43b6-90ea-7281a57a84b7
		summarizeBy: none
		sourceColumn: PerformanceScore

		annotation SummarizationSetBy = Automatic

	column EngagementSurvey
		dataType: double
		formatString: General Number
		lineageTag: b45c5324-7c62-4eb5-ab91-e86642f026b5
		summarizeBy: sum
		sourceColumn: EngagementSurvey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EmpSatisfaction
		dataType: int64
		formatString: 0
		lineageTag: cffb0e54-fd92-4ee2-a5be-53ffb619deca
		summarizeBy: sum
		sourceColumn: EmpSatisfaction

		annotation SummarizationSetBy = Automatic

	column SpecialProjectsCount
		dataType: int64
		formatString: 0
		lineageTag: edea4120-a9ac-4256-9d06-f6bcb81fd2a1
		summarizeBy: sum
		sourceColumn: SpecialProjectsCount

		annotation SummarizationSetBy = Automatic

	column LastPerformanceReview_Date
		dataType: datetime
		lineageTag: 27576ce8-acca-476e-a6ef-f168e303eea3
		summarizeBy: none
		sourceColumn: LastPerformanceReview_Date

		annotation SummarizationSetBy = Automatic

	column DaysLateLast30
		dataType: int64
		formatString: 0
		lineageTag: 8e3c4920-a0cf-4ddd-b79a-f8a62ab6e6f6
		summarizeBy: sum
		sourceColumn: DaysLateLast30

		annotation SummarizationSetBy = Automatic

	column Absences
		dataType: int64
		formatString: 0
		lineageTag: e9ae710a-547b-42b5-a585-6d02e0130484
		summarizeBy: sum
		sourceColumn: Absences

		annotation SummarizationSetBy = Automatic

	column Calculation3 = 'HR Dataset'[TermReason] & FORMAT('HR Dataset'[Termd], "0")
		lineageTag: 8f2a7206-07fc-4cc2-acbc-43ba41cc0437
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column calculation3 = "abc"
		lineageTag: e6fd6197-8659-4ca3-907d-3df2e4090e8a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column C_Employee_Status = 'HR Dataset'[EmploymentStatus]
		lineageTag: bfbaf0ed-5ebe-47eb-b036-c80a7d9fb44d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Calculation1 = 'HR Dataset'[DeptID] + 'HR Dataset'[GenderID]
		formatString: 0
		lineageTag: 4c7bdefa-5465-4ac5-9c06-10d0bab80343
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Calculation2 = 'HR Dataset'[Termd] * 'HR Dataset'[Salary] * 'HR Dataset'[EngagementSurvey]
		lineageTag: 0204777b-fa5e-400b-a8da-40f8d066add0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'dep calc 1' = 'HR Dataset'[DeptID]
		formatString: 0
		lineageTag: f751486d-a79e-4306-a94f-a55b7b32418a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'dep calc 2' = 'HR Dataset'[dep calc 1] * 'HR Dataset'[MarriedID]
		formatString: 0
		lineageTag: 35c00839-6821-4903-b11b-58ef0e38e113
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'HR Dataset' = m
		mode: import
		source =
				let
					    Source = Csv.Document(
					        File.Contents("https://saastestlatest.blob.core.windows.net/saas-test-reports/HR%20Dataset.csv?se=2025-11-04T18%3A27%3A56Z&sp=r&sv=2025-11-05&sr=b&sig=ArZ6Sh/cRj4vJMhh3BFjW/EEqs3xD1huEaWg0CWGpZU%3D"),
					        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
					    ),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Employee_Name", type text}, {"EmpID", Int64.Type}, {"MarriedID", Int64.Type}, {"MaritalStatusID", Int64.Type}, {"GenderID", Int64.Type}, {"EmpStatusID", Int64.Type}, {"DeptID", Int64.Type}, {"PerfScoreID", Int64.Type}, {"FromDiversityJobFairID", Int64.Type}, {"Salary", Int64.Type}, {"Termd", Int64.Type}, {"PositionID", Int64.Type}, {"Position", type text}, {"State", type text}, {"Zip", Int64.Type}, {"DOB", type date}, {"Sex", type text}, {"MaritalDesc", type text}, {"CitizenDesc", type text}, {"HispanicLatino", type text}, {"RaceDesc", type text}, {"DateofHire", type date}, {"DateofTermination", type date}, {"TermReason", type text}, {"EmploymentStatus", type text}, {"Department", type text}, {"ManagerName", type text}, {"ManagerID", Int64.Type}, {"RecruitmentSource", type text}, {"PerformanceScore", type text}, {"EngagementSurvey", type number}, {"EmpSatisfaction", Int64.Type}, {"SpecialProjectsCount", Int64.Type}, {"LastPerformanceReview_Date", type date}, {"DaysLateLast30", Int64.Type}, {"Absences", Int64.Type}})
					in
					    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table