table 'accounts+'
	lineageTag: 471da479-ac75-477e-a674-2de762522523

	measure 'Net Flow' = VAR Dep = CALCULATE(SUM('accounts+'[Amount]), 'accounts+'[TransactionType] = "Deposit") VAR Withd = CALCULATE(SUM('accounts+'[Amount]), 'accounts+'[TransactionType] = "Withdrawal") RETURN Dep - Withd
		formatString: 0
		lineageTag: 1ef49de3-88a0-4f90-81e7-9d14a374c886

	measure 'Average account balance' = AVERAGE('accounts+'[CurrentBalance])
		formatString: 0
		lineageTag: d0a6af00-368e-4adb-9774-8557b485df67

	measure 'Active Accounts Count' = DISTINCTCOUNT('accounts+'[AccountID])
		formatString: 0
		lineageTag: fc476eab-efc4-4928-a486-9e5dd230d97f

	measure 'Accounts Above Threshold' = IF( 'accounts+'[CurrentBalance] >= SELECTEDVALUE('Balance Threshold'[Display As]), 'accounts+'[AccountID], BLANK() )
		lineageTag: 291b5f11-ef1b-4c23-a0ad-262578780b0e

	measure 'Selected Year Filter' = YEAR('accounts+'[TransactionDate]) = SELECTEDVALUE('Select Year'[Display As])
		lineageTag: 71511dbf-8829-4a12-bb99-f3a22fd6840a

	column AccountID
		dataType: string
		lineageTag: 5c8d3f4b-ff0b-4188-8a8d-2f8febe1d64a
		summarizeBy: none
		sourceColumn: AccountID

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: string
		lineageTag: 8898cfb3-f4e7-4917-8394-b58a87356db4
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column BranchID
		dataType: string
		lineageTag: 17a3e6e6-6929-441c-bbbc-37dfb7e3aa68
		summarizeBy: none
		sourceColumn: BranchID

		annotation SummarizationSetBy = Automatic

	column AccountType
		dataType: string
		lineageTag: 5ee6e141-311c-4047-a341-6be9e2a72c59
		summarizeBy: none
		sourceColumn: AccountType

		annotation SummarizationSetBy = Automatic

	column OpenDate
		dataType: datetime
		lineageTag: 0a21947f-b4f9-48fc-91a7-24ec6c348e76
		summarizeBy: none
		sourceColumn: OpenDate

		annotation SummarizationSetBy = Automatic

	column CurrentBalance
		dataType: double
		formatString: General Number
		lineageTag: cb04477c-57e6-4716-8283-dc364d40e498
		summarizeBy: sum
		sourceColumn: CurrentBalance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'BranchID 1'
		dataType: string
		lineageTag: fc32b2f8-6572-48ba-bc6d-0e852ff43f72
		summarizeBy: none
		sourceColumn: 'BranchID 1'

		annotation SummarizationSetBy = Automatic

	column BranchName
		dataType: string
		lineageTag: 5239c2f2-81ac-4765-94e4-4894510050f3
		summarizeBy: none
		sourceColumn: BranchName

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: b904a23c-c7df-47ee-b72b-4367c5155688
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Manager
		dataType: string
		lineageTag: 753820b1-9b45-4c7d-a066-40cb4552dcdd
		summarizeBy: none
		sourceColumn: Manager

		annotation SummarizationSetBy = Automatic

	column 'CustomerID 1'
		dataType: string
		lineageTag: 1cbeaaf0-2a54-4c1d-8939-c331d06ddced
		summarizeBy: none
		sourceColumn: 'CustomerID 1'

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: edd4ca1d-76c7-4b5c-aec2-18c6617d5e9b
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 7fea5331-f8d6-427e-b4e7-3166263520ad
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: e8fc3788-6654-49e8-ba03-8b2fdf9cf55d
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column DOB
		dataType: datetime
		lineageTag: 2d410fef-030b-4dba-8b4e-477d2709f303
		summarizeBy: none
		sourceColumn: DOB

		annotation SummarizationSetBy = Automatic

	column 'City 1'
		dataType: string
		lineageTag: 33731862-f21f-458d-a527-26440f0a1d6d
		summarizeBy: none
		sourceColumn: 'City 1'

		annotation SummarizationSetBy = Automatic

	column CustomerSince
		dataType: datetime
		lineageTag: 2040135e-27b6-484f-ae85-99893f86649b
		summarizeBy: none
		sourceColumn: CustomerSince

		annotation SummarizationSetBy = Automatic

	column TransactionID
		dataType: string
		lineageTag: 7cf788e5-f12a-4df4-a5f9-901011ed14a1
		summarizeBy: none
		sourceColumn: TransactionID

		annotation SummarizationSetBy = Automatic

	column 'AccountID 1'
		dataType: string
		lineageTag: 4b4cb388-92ee-4ba0-abaa-b48988796eaa
		summarizeBy: none
		sourceColumn: 'AccountID 1'

		annotation SummarizationSetBy = Automatic

	column 'BranchID 2'
		dataType: string
		lineageTag: 51e91f04-80f1-4071-824a-1ea1c5668cfa
		summarizeBy: none
		sourceColumn: 'BranchID 2'

		annotation SummarizationSetBy = Automatic

	column TransactionDate
		dataType: datetime
		lineageTag: 0db4465b-f305-4b78-9016-19847ebf6bc8
		summarizeBy: none
		sourceColumn: TransactionDate

		annotation SummarizationSetBy = Automatic

	column TransactionType
		dataType: string
		lineageTag: e79f0454-48f6-4b93-92fe-0f3566001ca4
		summarizeBy: none
		sourceColumn: TransactionType

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: ed135df9-a5cf-4b28-9382-7127fa6b9b06
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: double
		formatString: General Number
		lineageTag: cb6ce253-2a48-4f6e-af29-b8591dbc9a79
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Deposits' = IF('accounts+'[TransactionType] = "Deposit", 'accounts+'[Amount])
		lineageTag: b2addbb7-4439-4d33-8047-0c527b181124
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Withdrawals' = IF('accounts+'[TransactionType] = "Withdrawal", 'accounts+'[Amount], BLANK())
		lineageTag: 98b3a853-ea75-4163-b17c-9f45a322e0bc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Deposit amount' = IF('accounts+'[TransactionType] = "Deposit", 'accounts+'[Amount])
		lineageTag: a3782a6e-3531-4369-a50f-4a6da911953f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Withdrawal Amount' = IF('accounts+'[TransactionType] = "Withdrawal", 'accounts+'[Amount], BLANK())
		lineageTag: fb4dee0b-97b7-4a80-9217-1cbaa8fe88f0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'accounts+' = m
		mode: import
		source =
				let 
					#"Source0" = Table.NestedJoin(#"accounts.csv_accounts+", {"BranchID"}, #"accounts+_branches.csv", {"BranchID"}, "accounts+_branches.csv", JoinKind.Inner),
					#"Expand0" = Table.ExpandTableColumn(#"Source0", "accounts+_branches.csv", {"BranchID", "BranchName", "City", "Manager"}, {"BranchID 1", "BranchName", "City", "Manager"}),
					#"Source1" = Table.NestedJoin(#"Expand0", {"CustomerID"}, #"accounts+_customers.csv", {"CustomerID"}, "accounts+_customers.csv", JoinKind.LeftOuter),
					#"Expand1" = Table.ExpandTableColumn(#"Source1", "accounts+_customers.csv", {"CustomerID", "FirstName", "LastName", "Gender", "DOB", "City", "CustomerSince"}, {"CustomerID 1", "FirstName", "LastName", "Gender", "DOB", "City 1", "CustomerSince"}),
					#"Source2" = Table.NestedJoin(#"Expand1", {"AccountID"}, #"accounts+_transactions.csv", {"AccountID"}, "accounts+_transactions.csv", JoinKind.RightOuter),
					#"Expand2" = Table.ExpandTableColumn(#"Source2", "accounts+_transactions.csv", {"TransactionID", "AccountID", "BranchID", "TransactionDate", "TransactionType", "Category", "Amount"}, {"TransactionID", "AccountID 1", "BranchID 2", "TransactionDate", "TransactionType", "Category", "Amount"})
					in #"Expand2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table