table 'Balance Threshold'
	lineageTag: 144d41d8-b2a8-410b-b1ca-06aaaf5f6355

	measure 'Balance Threshold Value' = SELECTEDVALUE('Balance Threshold'[Balance Threshold], 0.0)
		lineageTag: c672d313-620a-487e-b582-9a23d8d1a31a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Threshold'
		dataType: double
		formatString: 0
		lineageTag: 4ae6f82f-4685-41a2-9ed6-eab33704fe78
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Balance Threshold' = calculated
		mode: import
		source = GENERATESERIES(0.0, 500000.0, 5000.0)

	annotation PBI_Id = d494514f8f6f4d9b852e88d85afaf9d2

