table 'Highlight Parameter'
	lineageTag: c64e85c6-89c0-433d-bf14-60a0694ec3f1

	measure 'Highlight Parameter Value' = SELECTEDVALUE('Highlight Parameter'[Highlight Parameter], 1.0)
		lineageTag: 9860758c-4449-44dc-9611-857a3e7a6b6c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Highlight Parameter'
		dataType: double
		formatString: 0
		lineageTag: 0d309bdf-c99f-4ca5-81ce-00053cb43300
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Highlight Parameter' = calculated
		mode: import
		source = GENERATESERIES(1.0, 5.0, 1.0)

	annotation PBI_Id = ba0ff6da55a548098b9c847c0801c443

