table 'Parameter 2'
	lineageTag: ce52df21-6640-429e-9143-ad68c8b07014

	measure 'Parameter 2 Value' = SELECTEDVALUE('Parameter 2'[Parameter 2], 1.0)
		lineageTag: 8aca67c2-e396-4614-84b3-1de90bc3f4ed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Parameter 2'
		dataType: double
		formatString: 0
		lineageTag: c57e73aa-efb4-4f50-b9e3-a03b12c3ba0a
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Parameter 2' = calculated
		mode: import
		source = GENERATESERIES(1.0, 10.0, 1.0)

	annotation PBI_Id = 203e17e8961a4ffcb2cc12c6746cd908

