table 'Orders+ (Sample - Superstore)_People'
	lineageTag: 46806a47-d55f-4efc-823f-3b3dde5846ae

	column 'Regional Manager'
		dataType: string
		lineageTag: 86a038eb-4c0c-47bb-85b6-ca7190af327c
		summarizeBy: none
		sourceColumn: 'Regional Manager'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 3238cfca-2720-428b-85fb-75094b9c27f0
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition 'Orders+ (Sample - Superstore)_People' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Regional Manager" = "Alabama", #"Region" = "South Carolina"],
					        [#"Regional Manager" = "Arkansas", #"Region" = "Ohio"],
					        [#"Regional Manager" = "Mississippi", #"Region" = "West Virginia"],
					        [#"Regional Manager" = "Colorado", #"Region" = "Florida"],
					        [#"Regional Manager" = "Oklahoma", #"Region" = "Maine"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Regional Manager", type text},
					        {"Region", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table