table 'Orders+ (Sample - Superstore)'
	lineageTag: 6493d88e-36f0-4160-87eb-933a7ab39f9b

	measure 'Previous year' = VAR selDate = SELECTEDVALUE('Select date'[Display As]) VAR upperBound = DATE(YEAR(selDate) - 1, MONTH(selDate), DAY(selDate)) RETURN CALCULATE( SUM('Orders+ (Sample - Superstore)'[Sales]), FILTER( 'Orders+ (Sample - Superstore)', 'Orders+ (Sample - Superstore)'[Order Date] <= upperBound && 'Orders+ (Sample - Superstore)'[Order Date] >= IF( MONTH(selDate) <= 3, DATE(YEAR(selDate) - 2, 4, 1), IF( MONTH(selDate) >= 4 && YEAR(selDate) - 1 = YEAR('Orders+ (Sample - Superstore)'[Order Date]), DATE(YEAR(selDate) - 1, 4, 1), BLANK() ) ) ) )
		formatString: 0
		lineageTag: dbf34d8e-00b6-4c38-882a-2a4b346735ea

	measure Calculation1 = NOT(ISBLANK(SUM('Orders+ (Sample - Superstore)'[Current year]))) || NOT(ISBLANK(SUM('Orders+ (Sample - Superstore)'[Previous year])))
		lineageTag: d3173063-ea6c-48bc-ad64-4da7b62798ee

	measure 'Dynamic years' = SELECTEDVALUE('Select date'[Display As])
		lineageTag: 1793f770-a791-42e3-9590-19fb32dd1358

	measure MTD = VAR _selDate = SELECTEDVALUE('Select date'[Display As]) RETURN IF( NOT(ISBLANK(_selDate)), 'Orders+ (Sample - Superstore)'[Order Date] <= _selDate && MONTH('Orders+ (Sample - Superstore)'[Order Date]) = MONTH(_selDate) && YEAR('Orders+ (Sample - Superstore)'[Order Date]) = YEAR(_selDate), BLANK() )
		lineageTag: 25566c97-1e9e-4a08-87f1-7be8fe87ec5c

	measure 'Dynamic Measure values with YTD/MTD/QTD' = VAR _selPeriod = SELECTEDVALUE('Select Period'[Display As]) VAR _selDate = SELECTEDVALUE('Select date'[Display As]) VAR _startFY = IF( NOT(ISBLANK(_selDate)) && MONTH(_selDate) <= 3, DATE(YEAR(_selDate) - 1, 4, 1), IF( NOT(ISBLANK(_selDate)) && MONTH(_selDate) >= 4 && YEAR(_selDate) = YEAR('Orders+ (Sample - Superstore)'[Order Date]), DATE(YEAR(_selDate), 4, 1), BLANK() ) ) RETURN SWITCH( TRUE(), _selPeriod = 1 && NOT(ISBLANK(_selDate)), 'Orders+ (Sample - Superstore)'[Order Date] <= _selDate && 'Orders+ (Sample - Superstore)'[Order Date] >= _startFY, _selPeriod = 2, [MTD], _selPeriod = 3, 'Orders+ (Sample - Superstore)'[QTD], BLANK() )
		lineageTag: d168743d-7271-406b-953f-7ed378c52058

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 26b58f19-48af-4e93-9d4a-147ab89a5006
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: b5fe3585-962f-4420-b7a4-8e8723ff4835
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: datetime
		lineageTag: 7d094b05-e036-4d76-80fe-c44e0259af3c
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: datetime
		lineageTag: 64e730f2-f924-4089-b8df-f0e55041fc50
		summarizeBy: none
		sourceColumn: 'Ship Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 48c5fae3-c143-466e-9660-b1a9b58df0b3
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: bd479adf-0668-4418-a417-ea526e51b8b0
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 3740b0cb-c1d5-4be3-8403-743aa85dd146
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: d122189e-b14f-4cd7-b4ad-c35dcac229bb
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Country/Region'
		dataType: string
		lineageTag: 5c04f776-73e1-4b57-be80-36032fa37d2f
		summarizeBy: none
		sourceColumn: 'Country/Region'

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 49b06954-9799-491f-97cf-86a422ff8c0f
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 170b56c2-64a9-4727-8339-57b780f902b5
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 0ee9bc03-0a36-44c8-9142-ffae9c6f401f
		summarizeBy: sum
		sourceColumn: 'Postal Code'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 9dc102ac-ba5f-43b4-81f9-73bd085bf009
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: c156a3cf-0c9a-4f9a-b338-c6c3bbfa9e2b
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: ee6bf55e-8079-47e4-bef4-ac2cdaf5b669
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: 7b2a9de9-55bb-473e-9167-50ee2747f8b5
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 11c4bc91-a1e6-4b6f-9b9e-f9450bbffdc4
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: General Number
		lineageTag: cee424d3-e194-4c19-8535-09767f7838ba
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 554d546a-6daa-484a-ab46-b577ce250e8e
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: General Number
		lineageTag: be005c47-cece-46ed-9d24-97729b11e9d8
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		formatString: General Number
		lineageTag: 22c5cc2a-3325-46ae-a5fb-2fff59d7afe6
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QTD = 'Orders+ (Sample - Superstore)'[Order Date] <= 'Orders+ (Sample - Superstore)'[Dynamic years] && QUARTER('Orders+ (Sample - Superstore)'[Order Date]) = QUARTER('Orders+ (Sample - Superstore)'[Dynamic years]) && YEAR('Orders+ (Sample - Superstore)'[Order Date]) = YEAR('Orders+ (Sample - Superstore)'[Dynamic years])
		lineageTag: ea53b988-ee8f-44b3-9e79-3a6c7f1b8b91
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Current year' = IF( 'Orders+ (Sample - Superstore)'[Dynamic Measure values with YTD/MTD/QTD], 'Orders+ (Sample - Superstore)'[Sales], BLANK() )
		lineageTag: 7c24c83e-afe7-4915-a0aa-fb3a518faa96
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Orders+ (Sample - Superstore)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Row ID" = 249, #"Order ID" = 3601, #"Order Date" = #date(2020, 9, 20), #"Ship Date" = #date(2024, 8, 1), #"Ship Mode" = "136.130.10.171", #"Customer ID" = 3635, #"Customer Name" = "Naida Fox", #"Segment" = "phone", #"Country/Region" = "Maine", #"City" = "Merrillville", #"State" = "Idaho", #"Postal Code" = 945, #"Region" = "Missouri", #"Product ID" = 2933, #"Category" = "memorial", #"Sub-Category" = "dead", #"Product Name" = "Benedict Wynn", #"Sales" = 666.99, #"Quantity" = 983, #"Discount" = 940.5, #"Profit" = 749.42],
					        [#"Row ID" = 3110, #"Order ID" = 1614, #"Order Date" = #date(2024, 1, 6), #"Ship Date" = #date(2024, 11, 30), #"Ship Mode" = "7.7.239.43", #"Customer ID" = 9538, #"Customer Name" = "Amiee Haney", #"Segment" = "automatic", #"Country/Region" = "Tennessee", #"City" = "Melrose Park", #"State" = "Massachusetts", #"Postal Code" = 706, #"Region" = "North Dakota", #"Product ID" = 4768, #"Category" = "legacy", #"Sub-Category" = "newsletter", #"Product Name" = "Brady Stanton", #"Sales" = 632.84, #"Quantity" = 947, #"Discount" = 817.7, #"Profit" = 144.41],
					        [#"Row ID" = 8625, #"Order ID" = 2609, #"Order Date" = #date(2021, 4, 15), #"Ship Date" = #date(2022, 5, 14), #"Ship Mode" = "7.236.190.39", #"Customer ID" = 3412, #"Customer Name" = "Earle William", #"Segment" = "adults", #"Country/Region" = "West Virginia", #"City" = "Lynbrook", #"State" = "Alaska", #"Postal Code" = 573, #"Region" = "Ohio", #"Product ID" = 9351, #"Category" = "dave", #"Sub-Category" = "explains", #"Product Name" = "Gracia Zamora", #"Sales" = 834.22, #"Quantity" = 25, #"Discount" = 286.92, #"Profit" = 656.81],
					        [#"Row ID" = 1749, #"Order ID" = 7352, #"Order Date" = #date(2024, 7, 31), #"Ship Date" = #date(2024, 6, 2), #"Ship Mode" = "191.22.199.44", #"Customer ID" = 5489, #"Customer Name" = "Hugh Lowery", #"Segment" = "pg", #"Country/Region" = "Utah", #"City" = "Bakersfield", #"State" = "New Hampshire", #"Postal Code" = 710, #"Region" = "Vermont", #"Product ID" = 3439, #"Category" = "democracy", #"Sub-Category" = "festival", #"Product Name" = "Edward Avery", #"Sales" = 433.82, #"Quantity" = 149, #"Discount" = 118.23, #"Profit" = 121.94],
					        [#"Row ID" = 6535, #"Order ID" = 2254, #"Order Date" = #date(2022, 10, 28), #"Ship Date" = #date(2024, 5, 2), #"Ship Mode" = "37.87.177.247", #"Customer ID" = 3250, #"Customer Name" = "Mayola James", #"Segment" = "suicide", #"Country/Region" = "California", #"City" = "Mokena", #"State" = "Vermont", #"Postal Code" = 914, #"Region" = "Missouri", #"Product ID" = 5744, #"Category" = "cuts", #"Sub-Category" = "cluster", #"Product Name" = "Julene Wolfe", #"Sales" = 475.18, #"Quantity" = 750, #"Discount" = 330.58, #"Profit" = 676.66]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Row ID", Int64.Type},
					        {"Order ID", type text},
					        {"Order Date", type date},
					        {"Ship Date", type date},
					        {"Ship Mode", type text},
					        {"Customer ID", type text},
					        {"Customer Name", type text},
					        {"Segment", type text},
					        {"Country/Region", type text},
					        {"City", type text},
					        {"State", type text},
					        {"Postal Code", Int64.Type},
					        {"Region", type text},
					        {"Product ID", type text},
					        {"Category", type text},
					        {"Sub-Category", type text},
					        {"Product Name", type text},
					        {"Sales", type number},
					        {"Quantity", Int64.Type},
					        {"Discount", type number},
					        {"Profit", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table