table 'Orders+ (Sample - Superstore)_Returns'
	lineageTag: 3e265fc6-b40e-4ade-be7c-c7fc83e6148f

	column Returned
		dataType: string
		lineageTag: 88285486-cc4f-4bec-880d-527d48b80826
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: a53ffabd-bc20-4179-9618-d077c53b6583
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	partition 'Orders+ (Sample - Superstore)_Returns' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Returned" = "upload", #"Order ID" = 6502],
					        [#"Returned" = "title", #"Order ID" = 8230],
					        [#"Returned" = "yeah", #"Order ID" = 9024],
					        [#"Returned" = "complete", #"Order ID" = 9414],
					        [#"Returned" = "upcoming", #"Order ID" = 3566]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Returned", type text},
					        {"Order ID", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table