table 'Orders+ (Sample - Superstore)_Returns'
	lineageTag: 9a7c0244-831e-4391-afe5-ef94412e9269

	column Returned
		dataType: string
		lineageTag: 78302290-d661-4480-9bd1-f4f97cc3812f
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: f0530a10-97fc-4495-9aed-3d4aa103bc16
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	partition 'Orders+ (Sample - Superstore)_Returns' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Returned" = "contests", #"Order ID" = 4353],
					        [#"Returned" = "olympic", #"Order ID" = 1524],
					        [#"Returned" = "prepared", #"Order ID" = 2419],
					        [#"Returned" = "hunt", #"Order ID" = 2158],
					        [#"Returned" = "closing", #"Order ID" = 3036],
					        [#"Returned" = "honor", #"Order ID" = 5061],
					        [#"Returned" = "sector", #"Order ID" = 6182],
					        [#"Returned" = "underwear", #"Order ID" = 9974],
					        [#"Returned" = "explain", #"Order ID" = 2414],
					        [#"Returned" = "voices", #"Order ID" = 9972],
					        [#"Returned" = "pmid", #"Order ID" = 6043],
					        [#"Returned" = "spectrum", #"Order ID" = 2743],
					        [#"Returned" = "nation", #"Order ID" = 1847],
					        [#"Returned" = "ratings", #"Order ID" = 8523],
					        [#"Returned" = "arm", #"Order ID" = 4219],
					        [#"Returned" = "sacramento", #"Order ID" = 4036],
					        [#"Returned" = "guilty", #"Order ID" = 2408],
					        [#"Returned" = "tomorrow", #"Order ID" = 2841],
					        [#"Returned" = "will", #"Order ID" = 1100],
					        [#"Returned" = "asset", #"Order ID" = 8243],
					        [#"Returned" = "port", #"Order ID" = 6792],
					        [#"Returned" = "charity", #"Order ID" = 9125],
					        [#"Returned" = "merchant", #"Order ID" = 9225],
					        [#"Returned" = "netscape", #"Order ID" = 4682],
					        [#"Returned" = "plc", #"Order ID" = 6273],
					        [#"Returned" = "number", #"Order ID" = 9462],
					        [#"Returned" = "notebook", #"Order ID" = 9290],
					        [#"Returned" = "franklin", #"Order ID" = 4411],
					        [#"Returned" = "router", #"Order ID" = 7220],
					        [#"Returned" = "things", #"Order ID" = 2295],
					        [#"Returned" = "holiday", #"Order ID" = 6056],
					        [#"Returned" = "dental", #"Order ID" = 9692],
					        [#"Returned" = "host", #"Order ID" = 9462],
					        [#"Returned" = "boston", #"Order ID" = 9825],
					        [#"Returned" = "feeding", #"Order ID" = 5716],
					        [#"Returned" = "disorders", #"Order ID" = 8152],
					        [#"Returned" = "announced", #"Order ID" = 6197],
					        [#"Returned" = "ford", #"Order ID" = 9398],
					        [#"Returned" = "korea", #"Order ID" = 9023],
					        [#"Returned" = "interactive", #"Order ID" = 1110],
					        [#"Returned" = "release", #"Order ID" = 3860],
					        [#"Returned" = "modified", #"Order ID" = 1523],
					        [#"Returned" = "reservation", #"Order ID" = 5455],
					        [#"Returned" = "groups", #"Order ID" = 5753],
					        [#"Returned" = "end", #"Order ID" = 6349],
					        [#"Returned" = "located", #"Order ID" = 8904],
					        [#"Returned" = "door", #"Order ID" = 5508],
					        [#"Returned" = "awarded", #"Order ID" = 7166],
					        [#"Returned" = "announcements", #"Order ID" = 9055],
					        [#"Returned" = "ss", #"Order ID" = 8378],
					        [#"Returned" = "highlight", #"Order ID" = 5387],
					        [#"Returned" = "nurse", #"Order ID" = 2760],
					        [#"Returned" = "reported", #"Order ID" = 3566],
					        [#"Returned" = "mn", #"Order ID" = 1858],
					        [#"Returned" = "decline", #"Order ID" = 4620],
					        [#"Returned" = "english", #"Order ID" = 8661],
					        [#"Returned" = "dimension", #"Order ID" = 5105],
					        [#"Returned" = "hybrid", #"Order ID" = 6053],
					        [#"Returned" = "prints", #"Order ID" = 3566],
					        [#"Returned" = "outcome", #"Order ID" = 4767],
					        [#"Returned" = "california", #"Order ID" = 6506],
					        [#"Returned" = "margaret", #"Order ID" = 7751],
					        [#"Returned" = "babe", #"Order ID" = 6824],
					        [#"Returned" = "coupons", #"Order ID" = 1085],
					        [#"Returned" = "creation", #"Order ID" = 5045],
					        [#"Returned" = "military", #"Order ID" = 9609],
					        [#"Returned" = "better", #"Order ID" = 8008],
					        [#"Returned" = "ie", #"Order ID" = 9416],
					        [#"Returned" = "programming", #"Order ID" = 5060],
					        [#"Returned" = "finland", #"Order ID" = 6100],
					        [#"Returned" = "wall", #"Order ID" = 8302],
					        [#"Returned" = "suggests", #"Order ID" = 2824],
					        [#"Returned" = "cotton", #"Order ID" = 5964],
					        [#"Returned" = "employer", #"Order ID" = 1241],
					        [#"Returned" = "servers", #"Order ID" = 9991],
					        [#"Returned" = "buffalo", #"Order ID" = 4521],
					        [#"Returned" = "things", #"Order ID" = 1976],
					        [#"Returned" = "out", #"Order ID" = 3203],
					        [#"Returned" = "works", #"Order ID" = 3211],
					        [#"Returned" = "thompson", #"Order ID" = 6867],
					        [#"Returned" = "arrow", #"Order ID" = 9346],
					        [#"Returned" = "exception", #"Order ID" = 8750],
					        [#"Returned" = "prime", #"Order ID" = 3206],
					        [#"Returned" = "reference", #"Order ID" = 2710],
					        [#"Returned" = "summer", #"Order ID" = 2739],
					        [#"Returned" = "roberts", #"Order ID" = 4474],
					        [#"Returned" = "indicate", #"Order ID" = 1687],
					        [#"Returned" = "wholesale", #"Order ID" = 3417],
					        [#"Returned" = "parliament", #"Order ID" = 7567],
					        [#"Returned" = "analysis", #"Order ID" = 1159],
					        [#"Returned" = "secondary", #"Order ID" = 4984],
					        [#"Returned" = "desire", #"Order ID" = 5899],
					        [#"Returned" = "major", #"Order ID" = 5122],
					        [#"Returned" = "real", #"Order ID" = 9422],
					        [#"Returned" = "sorted", #"Order ID" = 2913],
					        [#"Returned" = "here", #"Order ID" = 5289],
					        [#"Returned" = "two", #"Order ID" = 8374],
					        [#"Returned" = "sought", #"Order ID" = 3917],
					        [#"Returned" = "drunk", #"Order ID" = 9056],
					        [#"Returned" = "document", #"Order ID" = 5317],
					        [#"Returned" = "study", #"Order ID" = 7940],
					        [#"Returned" = "mr", #"Order ID" = 1149],
					        [#"Returned" = "organic", #"Order ID" = 7775],
					        [#"Returned" = "according", #"Order ID" = 5265],
					        [#"Returned" = "menu", #"Order ID" = 3896],
					        [#"Returned" = "ghost", #"Order ID" = 1391],
					        [#"Returned" = "matter", #"Order ID" = 5236],
					        [#"Returned" = "entirely", #"Order ID" = 9720],
					        [#"Returned" = "proceed", #"Order ID" = 5335],
					        [#"Returned" = "par", #"Order ID" = 9124],
					        [#"Returned" = "higher", #"Order ID" = 2318],
					        [#"Returned" = "delivered", #"Order ID" = 1153],
					        [#"Returned" = "dental", #"Order ID" = 5307],
					        [#"Returned" = "split", #"Order ID" = 4115],
					        [#"Returned" = "mining", #"Order ID" = 6362],
					        [#"Returned" = "choose", #"Order ID" = 2592],
					        [#"Returned" = "health", #"Order ID" = 7696],
					        [#"Returned" = "credits", #"Order ID" = 4611],
					        [#"Returned" = "utilities", #"Order ID" = 3128],
					        [#"Returned" = "wire", #"Order ID" = 1543],
					        [#"Returned" = "slot", #"Order ID" = 6222],
					        [#"Returned" = "improve", #"Order ID" = 3454],
					        [#"Returned" = "cast", #"Order ID" = 7313],
					        [#"Returned" = "under", #"Order ID" = 6552],
					        [#"Returned" = "focused", #"Order ID" = 5315],
					        [#"Returned" = "personality", #"Order ID" = 6108],
					        [#"Returned" = "across", #"Order ID" = 6446],
					        [#"Returned" = "technical", #"Order ID" = 3526],
					        [#"Returned" = "lb", #"Order ID" = 8431],
					        [#"Returned" = "stocks", #"Order ID" = 3368],
					        [#"Returned" = "max", #"Order ID" = 2188],
					        [#"Returned" = "mins", #"Order ID" = 3744],
					        [#"Returned" = "fe", #"Order ID" = 9562],
					        [#"Returned" = "radar", #"Order ID" = 9050],
					        [#"Returned" = "reply", #"Order ID" = 4978],
					        [#"Returned" = "bt", #"Order ID" = 6719],
					        [#"Returned" = "clothing", #"Order ID" = 3773],
					        [#"Returned" = "participation", #"Order ID" = 4116],
					        [#"Returned" = "attacks", #"Order ID" = 5845],
					        [#"Returned" = "dna", #"Order ID" = 9029],
					        [#"Returned" = "member", #"Order ID" = 3611],
					        [#"Returned" = "added", #"Order ID" = 5511],
					        [#"Returned" = "sad", #"Order ID" = 5347],
					        [#"Returned" = "results", #"Order ID" = 1565],
					        [#"Returned" = "gbp", #"Order ID" = 7202],
					        [#"Returned" = "andrew", #"Order ID" = 4532],
					        [#"Returned" = "customer", #"Order ID" = 3712],
					        [#"Returned" = "massive", #"Order ID" = 2289],
					        [#"Returned" = "sequence", #"Order ID" = 1854],
					        [#"Returned" = "crystal", #"Order ID" = 8537],
					        [#"Returned" = "usual", #"Order ID" = 4466],
					        [#"Returned" = "gain", #"Order ID" = 3054],
					        [#"Returned" = "infant", #"Order ID" = 4459],
					        [#"Returned" = "sugar", #"Order ID" = 2461],
					        [#"Returned" = "miami", #"Order ID" = 2612],
					        [#"Returned" = "nhl", #"Order ID" = 6531],
					        [#"Returned" = "brands", #"Order ID" = 6634],
					        [#"Returned" = "burning", #"Order ID" = 1507],
					        [#"Returned" = "hurricane", #"Order ID" = 1549],
					        [#"Returned" = "evaluate", #"Order ID" = 9843],
					        [#"Returned" = "improvements", #"Order ID" = 7524],
					        [#"Returned" = "manchester", #"Order ID" = 6506],
					        [#"Returned" = "tim", #"Order ID" = 3314],
					        [#"Returned" = "filled", #"Order ID" = 7419],
					        [#"Returned" = "july", #"Order ID" = 8310],
					        [#"Returned" = "season", #"Order ID" = 4392],
					        [#"Returned" = "jury", #"Order ID" = 1060],
					        [#"Returned" = "analysis", #"Order ID" = 2483],
					        [#"Returned" = "videos", #"Order ID" = 2392],
					        [#"Returned" = "bought", #"Order ID" = 4158],
					        [#"Returned" = "progress", #"Order ID" = 7034],
					        [#"Returned" = "playstation", #"Order ID" = 3030],
					        [#"Returned" = "active", #"Order ID" = 2608],
					        [#"Returned" = "miss", #"Order ID" = 3530],
					        [#"Returned" = "dancing", #"Order ID" = 1351],
					        [#"Returned" = "advertising", #"Order ID" = 3793],
					        [#"Returned" = "spoke", #"Order ID" = 9190],
					        [#"Returned" = "battery", #"Order ID" = 4013],
					        [#"Returned" = "java", #"Order ID" = 6996],
					        [#"Returned" = "buy", #"Order ID" = 1240],
					        [#"Returned" = "bureau", #"Order ID" = 4000],
					        [#"Returned" = "generated", #"Order ID" = 4970],
					        [#"Returned" = "keywords", #"Order ID" = 1012],
					        [#"Returned" = "layer", #"Order ID" = 9890],
					        [#"Returned" = "priorities", #"Order ID" = 1260],
					        [#"Returned" = "apache", #"Order ID" = 1188],
					        [#"Returned" = "offered", #"Order ID" = 2310],
					        [#"Returned" = "jean", #"Order ID" = 2978],
					        [#"Returned" = "governments", #"Order ID" = 2917],
					        [#"Returned" = "warning", #"Order ID" = 1157],
					        [#"Returned" = "something", #"Order ID" = 1148],
					        [#"Returned" = "providers", #"Order ID" = 4722],
					        [#"Returned" = "ringtones", #"Order ID" = 9747],
					        [#"Returned" = "winter", #"Order ID" = 7088],
					        [#"Returned" = "authorities", #"Order ID" = 2583],
					        [#"Returned" = "tools", #"Order ID" = 3024],
					        [#"Returned" = "fewer", #"Order ID" = 9118],
					        [#"Returned" = "tx", #"Order ID" = 1670],
					        [#"Returned" = "charger", #"Order ID" = 7889],
					        [#"Returned" = "ak", #"Order ID" = 8619],
					        [#"Returned" = "obtained", #"Order ID" = 7096],
					        [#"Returned" = "estimates", #"Order ID" = 6404],
					        [#"Returned" = "continues", #"Order ID" = 9938],
					        [#"Returned" = "minority", #"Order ID" = 2498],
					        [#"Returned" = "knowing", #"Order ID" = 6313],
					        [#"Returned" = "choice", #"Order ID" = 5559],
					        [#"Returned" = "documents", #"Order ID" = 3406],
					        [#"Returned" = "solve", #"Order ID" = 3218],
					        [#"Returned" = "ann", #"Order ID" = 2892],
					        [#"Returned" = "query", #"Order ID" = 8939],
					        [#"Returned" = "sr", #"Order ID" = 3273],
					        [#"Returned" = "paris", #"Order ID" = 9701],
					        [#"Returned" = "document", #"Order ID" = 7302],
					        [#"Returned" = "issued", #"Order ID" = 3675],
					        [#"Returned" = "workers", #"Order ID" = 6017],
					        [#"Returned" = "steven", #"Order ID" = 2172],
					        [#"Returned" = "jacksonville", #"Order ID" = 3631],
					        [#"Returned" = "number", #"Order ID" = 5612],
					        [#"Returned" = "finally", #"Order ID" = 6158],
					        [#"Returned" = "rhode", #"Order ID" = 7441],
					        [#"Returned" = "campbell", #"Order ID" = 1242],
					        [#"Returned" = "direction", #"Order ID" = 6542],
					        [#"Returned" = "achieve", #"Order ID" = 8300],
					        [#"Returned" = "develop", #"Order ID" = 9447],
					        [#"Returned" = "scan", #"Order ID" = 9508],
					        [#"Returned" = "waste", #"Order ID" = 9929],
					        [#"Returned" = "methods", #"Order ID" = 9640],
					        [#"Returned" = "productivity", #"Order ID" = 7970],
					        [#"Returned" = "wales", #"Order ID" = 3194],
					        [#"Returned" = "forgot", #"Order ID" = 8561],
					        [#"Returned" = "protective", #"Order ID" = 5281],
					        [#"Returned" = "stats", #"Order ID" = 6077],
					        [#"Returned" = "default", #"Order ID" = 1552],
					        [#"Returned" = "mapping", #"Order ID" = 5369],
					        [#"Returned" = "reflect", #"Order ID" = 6444],
					        [#"Returned" = "prospective", #"Order ID" = 8602],
					        [#"Returned" = "stay", #"Order ID" = 1529],
					        [#"Returned" = "berkeley", #"Order ID" = 6188],
					        [#"Returned" = "vincent", #"Order ID" = 4090],
					        [#"Returned" = "surgery", #"Order ID" = 1516],
					        [#"Returned" = "sharing", #"Order ID" = 1223],
					        [#"Returned" = "viewing", #"Order ID" = 7179],
					        [#"Returned" = "england", #"Order ID" = 3526],
					        [#"Returned" = "resulting", #"Order ID" = 8568],
					        [#"Returned" = "continental", #"Order ID" = 8404],
					        [#"Returned" = "xml", #"Order ID" = 4525],
					        [#"Returned" = "zip", #"Order ID" = 2740],
					        [#"Returned" = "spiritual", #"Order ID" = 2710],
					        [#"Returned" = "affect", #"Order ID" = 7017],
					        [#"Returned" = "articles", #"Order ID" = 2310],
					        [#"Returned" = "building", #"Order ID" = 4462],
					        [#"Returned" = "plugin", #"Order ID" = 5378],
					        [#"Returned" = "survey", #"Order ID" = 8143],
					        [#"Returned" = "enjoyed", #"Order ID" = 5937],
					        [#"Returned" = "titles", #"Order ID" = 9977],
					        [#"Returned" = "registry", #"Order ID" = 8326],
					        [#"Returned" = "federal", #"Order ID" = 1042],
					        [#"Returned" = "teens", #"Order ID" = 5864],
					        [#"Returned" = "increased", #"Order ID" = 9072],
					        [#"Returned" = "ho", #"Order ID" = 1205],
					        [#"Returned" = "thus", #"Order ID" = 2772],
					        [#"Returned" = "alerts", #"Order ID" = 3725],
					        [#"Returned" = "son", #"Order ID" = 5119],
					        [#"Returned" = "structures", #"Order ID" = 6234],
					        [#"Returned" = "jazz", #"Order ID" = 1551],
					        [#"Returned" = "summit", #"Order ID" = 9614],
					        [#"Returned" = "common", #"Order ID" = 9107],
					        [#"Returned" = "logos", #"Order ID" = 2129],
					        [#"Returned" = "organized", #"Order ID" = 5049],
					        [#"Returned" = "tc", #"Order ID" = 4693],
					        [#"Returned" = "relation", #"Order ID" = 1414],
					        [#"Returned" = "option", #"Order ID" = 1987],
					        [#"Returned" = "expected", #"Order ID" = 4590],
					        [#"Returned" = "cleaner", #"Order ID" = 5513],
					        [#"Returned" = "cds", #"Order ID" = 6072],
					        [#"Returned" = "bulletin", #"Order ID" = 9158],
					        [#"Returned" = "da", #"Order ID" = 9813],
					        [#"Returned" = "vietnam", #"Order ID" = 7729],
					        [#"Returned" = "louisiana", #"Order ID" = 6833],
					        [#"Returned" = "consultant", #"Order ID" = 3424],
					        [#"Returned" = "index", #"Order ID" = 8184],
					        [#"Returned" = "protein", #"Order ID" = 8762],
					        [#"Returned" = "int", #"Order ID" = 5539],
					        [#"Returned" = "dir", #"Order ID" = 2230],
					        [#"Returned" = "contractors", #"Order ID" = 2810],
					        [#"Returned" = "scanner", #"Order ID" = 6295],
					        [#"Returned" = "inform", #"Order ID" = 1256],
					        [#"Returned" = "ee", #"Order ID" = 2823],
					        [#"Returned" = "advanced", #"Order ID" = 5181],
					        [#"Returned" = "simply", #"Order ID" = 5623],
					        [#"Returned" = "mi", #"Order ID" = 4124],
					        [#"Returned" = "extent", #"Order ID" = 9886],
					        [#"Returned" = "midnight", #"Order ID" = 1450],
					        [#"Returned" = "table", #"Order ID" = 7468],
					        [#"Returned" = "elected", #"Order ID" = 1205],
					        [#"Returned" = "resistant", #"Order ID" = 3563],
					        [#"Returned" = "matters", #"Order ID" = 7419],
					        [#"Returned" = "sessions", #"Order ID" = 1816],
					        [#"Returned" = "turkey", #"Order ID" = 1734],
					        [#"Returned" = "pages", #"Order ID" = 6881],
					        [#"Returned" = "islands", #"Order ID" = 5071],
					        [#"Returned" = "faith", #"Order ID" = 5397],
					        [#"Returned" = "artists", #"Order ID" = 5784],
					        [#"Returned" = "quarter", #"Order ID" = 1759],
					        [#"Returned" = "go", #"Order ID" = 1003],
					        [#"Returned" = "drinking", #"Order ID" = 1194],
					        [#"Returned" = "upgrade", #"Order ID" = 5409],
					        [#"Returned" = "sweet", #"Order ID" = 1877],
					        [#"Returned" = "experiences", #"Order ID" = 1614],
					        [#"Returned" = "attention", #"Order ID" = 5545],
					        [#"Returned" = "quotes", #"Order ID" = 4770],
					        [#"Returned" = "wars", #"Order ID" = 3419],
					        [#"Returned" = "components", #"Order ID" = 1645],
					        [#"Returned" = "medicare", #"Order ID" = 3298],
					        [#"Returned" = "resolution", #"Order ID" = 4510],
					        [#"Returned" = "museum", #"Order ID" = 4822],
					        [#"Returned" = "contribute", #"Order ID" = 5319],
					        [#"Returned" = "ph", #"Order ID" = 8943],
					        [#"Returned" = "drinks", #"Order ID" = 8794],
					        [#"Returned" = "islands", #"Order ID" = 4332],
					        [#"Returned" = "cp", #"Order ID" = 7994],
					        [#"Returned" = "miss", #"Order ID" = 4074],
					        [#"Returned" = "interviews", #"Order ID" = 5258],
					        [#"Returned" = "removal", #"Order ID" = 9139],
					        [#"Returned" = "issued", #"Order ID" = 2695],
					        [#"Returned" = "funding", #"Order ID" = 9573],
					        [#"Returned" = "uniform", #"Order ID" = 5520],
					        [#"Returned" = "physical", #"Order ID" = 5210],
					        [#"Returned" = "included", #"Order ID" = 8045],
					        [#"Returned" = "kinds", #"Order ID" = 3205],
					        [#"Returned" = "cameras", #"Order ID" = 2513],
					        [#"Returned" = "paid", #"Order ID" = 3144],
					        [#"Returned" = "southeast", #"Order ID" = 6250],
					        [#"Returned" = "supports", #"Order ID" = 6191],
					        [#"Returned" = "announces", #"Order ID" = 7219],
					        [#"Returned" = "induced", #"Order ID" = 3096],
					        [#"Returned" = "advertising", #"Order ID" = 6430],
					        [#"Returned" = "christian", #"Order ID" = 3123],
					        [#"Returned" = "extent", #"Order ID" = 8145],
					        [#"Returned" = "triple", #"Order ID" = 5418],
					        [#"Returned" = "editing", #"Order ID" = 2610],
					        [#"Returned" = "university", #"Order ID" = 4120],
					        [#"Returned" = "manual", #"Order ID" = 5358],
					        [#"Returned" = "essential", #"Order ID" = 2136],
					        [#"Returned" = "save", #"Order ID" = 1554],
					        [#"Returned" = "hall", #"Order ID" = 6929],
					        [#"Returned" = "plate", #"Order ID" = 2056],
					        [#"Returned" = "drinks", #"Order ID" = 9281],
					        [#"Returned" = "magnetic", #"Order ID" = 2244],
					        [#"Returned" = "my", #"Order ID" = 5709],
					        [#"Returned" = "donald", #"Order ID" = 7619],
					        [#"Returned" = "jul", #"Order ID" = 8400],
					        [#"Returned" = "databases", #"Order ID" = 8605],
					        [#"Returned" = "governments", #"Order ID" = 8776],
					        [#"Returned" = "occurred", #"Order ID" = 2954],
					        [#"Returned" = "lite", #"Order ID" = 1285],
					        [#"Returned" = "phentermine", #"Order ID" = 2764],
					        [#"Returned" = "specifically", #"Order ID" = 8566],
					        [#"Returned" = "ia", #"Order ID" = 9959],
					        [#"Returned" = "interest", #"Order ID" = 3599],
					        [#"Returned" = "router", #"Order ID" = 6815],
					        [#"Returned" = "attachments", #"Order ID" = 4737],
					        [#"Returned" = "significant", #"Order ID" = 9559],
					        [#"Returned" = "fm", #"Order ID" = 9303],
					        [#"Returned" = "flows", #"Order ID" = 4303],
					        [#"Returned" = "host", #"Order ID" = 1868],
					        [#"Returned" = "nm", #"Order ID" = 6255],
					        [#"Returned" = "suggests", #"Order ID" = 1467],
					        [#"Returned" = "fabric", #"Order ID" = 1816],
					        [#"Returned" = "grounds", #"Order ID" = 9417],
					        [#"Returned" = "accounting", #"Order ID" = 1147],
					        [#"Returned" = "hunt", #"Order ID" = 8379],
					        [#"Returned" = "delay", #"Order ID" = 6323],
					        [#"Returned" = "andrew", #"Order ID" = 7362],
					        [#"Returned" = "refers", #"Order ID" = 7106],
					        [#"Returned" = "episode", #"Order ID" = 9648],
					        [#"Returned" = "wire", #"Order ID" = 4347],
					        [#"Returned" = "summer", #"Order ID" = 5946],
					        [#"Returned" = "debate", #"Order ID" = 7455],
					        [#"Returned" = "buttons", #"Order ID" = 9014],
					        [#"Returned" = "caps", #"Order ID" = 9569],
					        [#"Returned" = "reg", #"Order ID" = 4805],
					        [#"Returned" = "wrap", #"Order ID" = 4997],
					        [#"Returned" = "concept", #"Order ID" = 4531],
					        [#"Returned" = "clear", #"Order ID" = 3024],
					        [#"Returned" = "seeds", #"Order ID" = 9722],
					        [#"Returned" = "appointed", #"Order ID" = 7161],
					        [#"Returned" = "partnerships", #"Order ID" = 5427],
					        [#"Returned" = "cases", #"Order ID" = 2732],
					        [#"Returned" = "new", #"Order ID" = 2689],
					        [#"Returned" = "aim", #"Order ID" = 7675],
					        [#"Returned" = "consult", #"Order ID" = 9693],
					        [#"Returned" = "pdt", #"Order ID" = 4189],
					        [#"Returned" = "birthday", #"Order ID" = 3891],
					        [#"Returned" = "destinations", #"Order ID" = 4292],
					        [#"Returned" = "resolve", #"Order ID" = 5125],
					        [#"Returned" = "lat", #"Order ID" = 7418],
					        [#"Returned" = "valid", #"Order ID" = 7040],
					        [#"Returned" = "appreciate", #"Order ID" = 6712],
					        [#"Returned" = "speech", #"Order ID" = 3963],
					        [#"Returned" = "identification", #"Order ID" = 2937],
					        [#"Returned" = "measure", #"Order ID" = 7277],
					        [#"Returned" = "bank", #"Order ID" = 5726],
					        [#"Returned" = "plaza", #"Order ID" = 2991],
					        [#"Returned" = "care", #"Order ID" = 2097],
					        [#"Returned" = "ages", #"Order ID" = 4065],
					        [#"Returned" = "isp", #"Order ID" = 3314],
					        [#"Returned" = "icons", #"Order ID" = 1895],
					        [#"Returned" = "log", #"Order ID" = 5517],
					        [#"Returned" = "worship", #"Order ID" = 7359],
					        [#"Returned" = "smile", #"Order ID" = 3467],
					        [#"Returned" = "casinos", #"Order ID" = 1417],
					        [#"Returned" = "usr", #"Order ID" = 6334],
					        [#"Returned" = "steven", #"Order ID" = 5198],
					        [#"Returned" = "mind", #"Order ID" = 6962],
					        [#"Returned" = "pick", #"Order ID" = 3961],
					        [#"Returned" = "couples", #"Order ID" = 8384],
					        [#"Returned" = "centers", #"Order ID" = 4277],
					        [#"Returned" = "window", #"Order ID" = 7404],
					        [#"Returned" = "able", #"Order ID" = 5514],
					        [#"Returned" = "servers", #"Order ID" = 7480],
					        [#"Returned" = "desire", #"Order ID" = 5607],
					        [#"Returned" = "supplements", #"Order ID" = 6097],
					        [#"Returned" = "cl", #"Order ID" = 3157],
					        [#"Returned" = "control", #"Order ID" = 7500],
					        [#"Returned" = "blackjack", #"Order ID" = 8296],
					        [#"Returned" = "highly", #"Order ID" = 1847],
					        [#"Returned" = "soft", #"Order ID" = 9186],
					        [#"Returned" = "nelson", #"Order ID" = 1861],
					        [#"Returned" = "contact", #"Order ID" = 3657],
					        [#"Returned" = "relation", #"Order ID" = 4847],
					        [#"Returned" = "awards", #"Order ID" = 4934],
					        [#"Returned" = "businesses", #"Order ID" = 9213],
					        [#"Returned" = "errors", #"Order ID" = 9978],
					        [#"Returned" = "vintage", #"Order ID" = 1004],
					        [#"Returned" = "iran", #"Order ID" = 2674],
					        [#"Returned" = "mountains", #"Order ID" = 5133],
					        [#"Returned" = "besides", #"Order ID" = 6151],
					        [#"Returned" = "gets", #"Order ID" = 2053],
					        [#"Returned" = "diesel", #"Order ID" = 5078],
					        [#"Returned" = "steam", #"Order ID" = 2732],
					        [#"Returned" = "measures", #"Order ID" = 4567],
					        [#"Returned" = "said", #"Order ID" = 7866],
					        [#"Returned" = "cells", #"Order ID" = 3457],
					        [#"Returned" = "solve", #"Order ID" = 3156],
					        [#"Returned" = "based", #"Order ID" = 3149],
					        [#"Returned" = "toner", #"Order ID" = 2582],
					        [#"Returned" = "disorders", #"Order ID" = 4533],
					        [#"Returned" = "emerging", #"Order ID" = 9598],
					        [#"Returned" = "women", #"Order ID" = 2580],
					        [#"Returned" = "fitness", #"Order ID" = 7586],
					        [#"Returned" = "la", #"Order ID" = 1449],
					        [#"Returned" = "rubber", #"Order ID" = 4410],
					        [#"Returned" = "somewhat", #"Order ID" = 5930],
					        [#"Returned" = "biology", #"Order ID" = 1436],
					        [#"Returned" = "artwork", #"Order ID" = 1969],
					        [#"Returned" = "affected", #"Order ID" = 1152],
					        [#"Returned" = "huge", #"Order ID" = 3896],
					        [#"Returned" = "refund", #"Order ID" = 7937],
					        [#"Returned" = "monthly", #"Order ID" = 1290],
					        [#"Returned" = "pretty", #"Order ID" = 2711],
					        [#"Returned" = "kim", #"Order ID" = 9435],
					        [#"Returned" = "troops", #"Order ID" = 6849],
					        [#"Returned" = "mrs", #"Order ID" = 9396],
					        [#"Returned" = "platinum", #"Order ID" = 2320],
					        [#"Returned" = "fame", #"Order ID" = 2149],
					        [#"Returned" = "participants", #"Order ID" = 5586],
					        [#"Returned" = "returns", #"Order ID" = 9308],
					        [#"Returned" = "excel", #"Order ID" = 3489],
					        [#"Returned" = "bags", #"Order ID" = 2561],
					        [#"Returned" = "was", #"Order ID" = 3948],
					        [#"Returned" = "pennsylvania", #"Order ID" = 5692],
					        [#"Returned" = "nurse", #"Order ID" = 3227],
					        [#"Returned" = "values", #"Order ID" = 8374],
					        [#"Returned" = "semi", #"Order ID" = 7576],
					        [#"Returned" = "parts", #"Order ID" = 1764],
					        [#"Returned" = "guns", #"Order ID" = 1000],
					        [#"Returned" = "pointed", #"Order ID" = 2678],
					        [#"Returned" = "glass", #"Order ID" = 7046],
					        [#"Returned" = "trade", #"Order ID" = 4320],
					        [#"Returned" = "chicago", #"Order ID" = 8144],
					        [#"Returned" = "dodge", #"Order ID" = 9525],
					        [#"Returned" = "garden", #"Order ID" = 9508],
					        [#"Returned" = "publishing", #"Order ID" = 8436],
					        [#"Returned" = "ff", #"Order ID" = 9525],
					        [#"Returned" = "usual", #"Order ID" = 2920],
					        [#"Returned" = "satisfied", #"Order ID" = 5916],
					        [#"Returned" = "lie", #"Order ID" = 9574],
					        [#"Returned" = "winning", #"Order ID" = 2311],
					        [#"Returned" = "together", #"Order ID" = 2250],
					        [#"Returned" = "made", #"Order ID" = 6333],
					        [#"Returned" = "appear", #"Order ID" = 9908],
					        [#"Returned" = "tank", #"Order ID" = 3544],
					        [#"Returned" = "started", #"Order ID" = 1456],
					        [#"Returned" = "strap", #"Order ID" = 3007],
					        [#"Returned" = "kids", #"Order ID" = 7481],
					        [#"Returned" = "spectrum", #"Order ID" = 9692],
					        [#"Returned" = "bands", #"Order ID" = 2058],
					        [#"Returned" = "positions", #"Order ID" = 4308],
					        [#"Returned" = "cross", #"Order ID" = 9020]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Returned", type text},
					        {"Order ID", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table