table 'Orders (Sample - Superstore (1))'
	lineageTag: 1e438b23-277f-4c51-97e6-0d1c8d2f540e

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 48786d03-cf27-46be-a716-a7dea99d7567
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 402b438f-9e2a-4078-9fc5-0da288d97348
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: datetime
		lineageTag: 0d16d7f5-f904-46e0-afe4-4ff30b0d73db
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: datetime
		lineageTag: a8ce5c0c-e270-4084-8093-89b2a4d803f3
		summarizeBy: none
		sourceColumn: 'Ship Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: d49cdfae-445c-4063-a44b-d9cb5be9cc10
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 9f73a3f4-ea11-4461-8487-dfac7d378d82
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 6778c000-a85a-45af-bd69-0935126bdac8
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: e786a809-9973-4c6e-9138-bbdbb87ccb9b
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 91a6b939-b570-401c-9482-9c8ef0c3c01a
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 31e0ed82-ea68-49b3-946d-94217de8e1ec
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: e6237e83-f93f-4c3d-a9ab-877a8d5f020a
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 4d00c368-8092-46eb-b911-209550fd5635
		summarizeBy: sum
		sourceColumn: 'Postal Code'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: b5e50eae-f109-4871-8f3e-e224f73253ed
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 014c1f5f-07a6-44a6-9df7-db0797c454ef
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: e3f486d0-4d9b-4c20-b50c-f76692a7adb6
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: d658abf6-7ab2-43d9-acdc-ee6968c2e0d9
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 503d07db-abf7-4a0c-b66b-6bfbea451c17
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: General Number
		lineageTag: 0224e2bb-a74c-40b2-adb5-3a9233cc9260
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 5643fd07-0c92-4fe9-a8f4-a5ef4ce2eba2
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: General Number
		lineageTag: e09a36d0-0dce-4069-8543-dc16bcb516aa
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		formatString: General Number
		lineageTag: 70dfa81a-eb61-4629-bc37-975b53edc0ab
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Calculation1 = IF('Orders (Sample - Superstore (1))'[Category] = "Furniture", "furniture", IF('Orders (Sample - Superstore (1))'[Category] = "Office Supplies", "office supplier", IF('Orders (Sample - Superstore (1))'[Category] = "Technology", "technology", 'Orders (Sample - Superstore (1))'[Category])))
		lineageTag: e2d8ce0d-d661-424c-be3e-d156131683bf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Orders (Sample - Superstore (1))' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [Row ID = 4492, Order ID = 5316, Order Date = #date(2021, 6, 16), Ship Date = #date(2021, 7, 1), Ship Mode = "37.23.231.103", Customer ID = 1647, Customer Name = "Meghann Carrillo", Segment = "computers", Country = "Serbia", City = "Denton", State = "Maine", Postal Code = 589, Region = "Louisiana", Product ID = 4500, Category = "packard", Sub-Category = "moving", Product Name = "Toney Hood", Sales = 8.14, Quantity = 505, Discount = 501.1, Profit = 40.35],
					        [Row ID = 537, Order ID = 9743, Order Date = #date(2020, 10, 2), Ship Date = #date(2022, 11, 20), Ship Mode = "42.193.47.245", Customer ID = 9011, Customer Name = "Faviola Wiggins", Segment = "southwest", Country = "Yemen", City = "Sandusky", State = "Alabama", Postal Code = 301, Region = "Arkansas", Product ID = 6073, Category = "unusual", Sub-Category = "cities", Product Name = "Eryn Patel", Sales = 697.44, Quantity = 716, Discount = 965.14, Profit = 258.21],
					        [Row ID = 6038, Order ID = 6262, Order Date = #date(2023, 4, 26), Ship Date = #date(2020, 8, 26), Ship Mode = "75.227.151.129", Customer ID = 3863, Customer Name = "Brice Robbins", Segment = "temporary", Country = "Serbia", City = "Warren", State = "Connecticut", Postal Code = 288, Region = "Texas", Product ID = 5551, Category = "off", Sub-Category = "adequate", Product Name = "Jacquelyne Calderon", Sales = 500.87, Quantity = 871, Discount = 367.8, Profit = 339.62],
					        [Row ID = 8198, Order ID = 6827, Order Date = #date(2023, 10, 9), Ship Date = #date(2022, 12, 29), Ship Mode = "100.194.251.12", Customer ID = 5758, Customer Name = "Russell Lowery", Segment = "veterans", Country = "Morocco", City = "Antioch", State = "Kansas", Postal Code = 477, Region = "Mississippi", Product ID = 2412, Category = "managing", Sub-Category = "formats", Product Name = "Leon Mueller", Sales = 871.96, Quantity = 618, Discount = 606.82, Profit = 159.25],
					        [Row ID = 7591, Order ID = 9731, Order Date = #date(2022, 12, 19), Ship Date = #date(2021, 1, 7), Ship Mode = "139.159.176.174", Customer ID = 2033, Customer Name = "Danilo Lopez", Segment = "networks", Country = "Bangladesh", City = "Plano", State = "Oklahoma", Postal Code = 736, Region = "North Dakota", Product ID = 4495, Category = "classical", Sub-Category = "anderson", Product Name = "Lynelle Delgado", Sales = 295.17, Quantity = 663, Discount = 710.5, Profit = 129.67]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Row ID", Int64.Type},
					        {"Order ID", type text},
					        {"Order Date", type date},
					        {"Ship Date", type date},
					        {"Ship Mode", type text},
					        {"Customer ID", type text},
					        {"Customer Name", type text},
					        {"Segment", type text},
					        {"Country", type text},
					        {"City", type text},
					        {"State", type text},
					        {"Postal Code", Int64.Type},
					        {"Region", type text},
					        {"Product ID", type text},
					        {"Category", type text},
					        {"Sub-Category", type text},
					        {"Product Name", type text},
					        {"Sales", type number},
					        {"Quantity", Int64.Type},
					        {"Discount", type number},
					        {"Profit", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table