table 'Campaigns+ (New Data)_Account Mapping'
	lineageTag: f01ffb45-6710-45da-948c-be31325436b0

	column 'Mapped Account ID'
		dataType: int64
		formatString: 0
		lineageTag: ca4b207f-1085-4895-846a-a48fc35e857f
		summarizeBy: sum
		sourceColumn: 'Mapped Account ID'

		annotation SummarizationSetBy = Automatic

	column 'Mapped Account List ID'
		dataType: int64
		formatString: 0
		lineageTag: edcea7d2-e289-4bd6-b370-41186ec471b2
		summarizeBy: sum
		sourceColumn: 'Mapped Account List ID'

		annotation SummarizationSetBy = Automatic

	partition 'Campaigns+ (New Data)_Account Mapping' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Mapped Account ID" = 6052, #"Mapped Account List ID" = 5909],
					        [#"Mapped Account ID" = 8473, #"Mapped Account List ID" = 6576],
					        [#"Mapped Account ID" = 5356, #"Mapped Account List ID" = 7833],
					        [#"Mapped Account ID" = 862, #"Mapped Account List ID" = 1874],
					        [#"Mapped Account ID" = 2241, #"Mapped Account List ID" = 8274],
					        [#"Mapped Account ID" = 473, #"Mapped Account List ID" = 1583],
					        [#"Mapped Account ID" = 2166, #"Mapped Account List ID" = 3343],
					        [#"Mapped Account ID" = 269, #"Mapped Account List ID" = 8594],
					        [#"Mapped Account ID" = 6406, #"Mapped Account List ID" = 5558],
					        [#"Mapped Account ID" = 8404, #"Mapped Account List ID" = 8634],
					        [#"Mapped Account ID" = 7679, #"Mapped Account List ID" = 1712],
					        [#"Mapped Account ID" = 807, #"Mapped Account List ID" = 788],
					        [#"Mapped Account ID" = 1435, #"Mapped Account List ID" = 5574],
					        [#"Mapped Account ID" = 1260, #"Mapped Account List ID" = 4987],
					        [#"Mapped Account ID" = 729, #"Mapped Account List ID" = 3044],
					        [#"Mapped Account ID" = 1408, #"Mapped Account List ID" = 6471],
					        [#"Mapped Account ID" = 1026, #"Mapped Account List ID" = 9719],
					        [#"Mapped Account ID" = 3598, #"Mapped Account List ID" = 2438],
					        [#"Mapped Account ID" = 825, #"Mapped Account List ID" = 459],
					        [#"Mapped Account ID" = 6947, #"Mapped Account List ID" = 6590],
					        [#"Mapped Account ID" = 8984, #"Mapped Account List ID" = 8133],
					        [#"Mapped Account ID" = 3746, #"Mapped Account List ID" = 6301],
					        [#"Mapped Account ID" = 761, #"Mapped Account List ID" = 2526],
					        [#"Mapped Account ID" = 6149, #"Mapped Account List ID" = 8227],
					        [#"Mapped Account ID" = 8872, #"Mapped Account List ID" = 8906],
					        [#"Mapped Account ID" = 1943, #"Mapped Account List ID" = 8095],
					        [#"Mapped Account ID" = 288, #"Mapped Account List ID" = 3995],
					        [#"Mapped Account ID" = 8133, #"Mapped Account List ID" = 3011],
					        [#"Mapped Account ID" = 1447, #"Mapped Account List ID" = 8244],
					        [#"Mapped Account ID" = 8284, #"Mapped Account List ID" = 9397],
					        [#"Mapped Account ID" = 9577, #"Mapped Account List ID" = 7973],
					        [#"Mapped Account ID" = 7674, #"Mapped Account List ID" = 7561],
					        [#"Mapped Account ID" = 5221, #"Mapped Account List ID" = 6523],
					        [#"Mapped Account ID" = 7755, #"Mapped Account List ID" = 290],
					        [#"Mapped Account ID" = 6074, #"Mapped Account List ID" = 6929],
					        [#"Mapped Account ID" = 6915, #"Mapped Account List ID" = 5762],
					        [#"Mapped Account ID" = 4286, #"Mapped Account List ID" = 5106],
					        [#"Mapped Account ID" = 7072, #"Mapped Account List ID" = 9233],
					        [#"Mapped Account ID" = 5143, #"Mapped Account List ID" = 5340],
					        [#"Mapped Account ID" = 565, #"Mapped Account List ID" = 7607],
					        [#"Mapped Account ID" = 9194, #"Mapped Account List ID" = 4499],
					        [#"Mapped Account ID" = 3095, #"Mapped Account List ID" = 1744],
					        [#"Mapped Account ID" = 2103, #"Mapped Account List ID" = 7185],
					        [#"Mapped Account ID" = 742, #"Mapped Account List ID" = 6632],
					        [#"Mapped Account ID" = 3182, #"Mapped Account List ID" = 42],
					        [#"Mapped Account ID" = 721, #"Mapped Account List ID" = 134],
					        [#"Mapped Account ID" = 7998, #"Mapped Account List ID" = 6249],
					        [#"Mapped Account ID" = 4617, #"Mapped Account List ID" = 4103],
					        [#"Mapped Account ID" = 1188, #"Mapped Account List ID" = 5316],
					        [#"Mapped Account ID" = 2734, #"Mapped Account List ID" = 3261],
					        [#"Mapped Account ID" = 6472, #"Mapped Account List ID" = 2979],
					        [#"Mapped Account ID" = 5812, #"Mapped Account List ID" = 9143],
					        [#"Mapped Account ID" = 2887, #"Mapped Account List ID" = 5946],
					        [#"Mapped Account ID" = 3820, #"Mapped Account List ID" = 8128],
					        [#"Mapped Account ID" = 3010, #"Mapped Account List ID" = 899],
					        [#"Mapped Account ID" = 3393, #"Mapped Account List ID" = 4212],
					        [#"Mapped Account ID" = 5821, #"Mapped Account List ID" = 1308],
					        [#"Mapped Account ID" = 4657, #"Mapped Account List ID" = 9019],
					        [#"Mapped Account ID" = 8471, #"Mapped Account List ID" = 2878],
					        [#"Mapped Account ID" = 5268, #"Mapped Account List ID" = 4903],
					        [#"Mapped Account ID" = 699, #"Mapped Account List ID" = 9526],
					        [#"Mapped Account ID" = 9508, #"Mapped Account List ID" = 4210],
					        [#"Mapped Account ID" = 4236, #"Mapped Account List ID" = 3377],
					        [#"Mapped Account ID" = 6687, #"Mapped Account List ID" = 6612],
					        [#"Mapped Account ID" = 1542, #"Mapped Account List ID" = 8127],
					        [#"Mapped Account ID" = 1918, #"Mapped Account List ID" = 3928],
					        [#"Mapped Account ID" = 809, #"Mapped Account List ID" = 5451],
					        [#"Mapped Account ID" = 3936, #"Mapped Account List ID" = 3579],
					        [#"Mapped Account ID" = 383, #"Mapped Account List ID" = 5959],
					        [#"Mapped Account ID" = 3093, #"Mapped Account List ID" = 2933],
					        [#"Mapped Account ID" = 1092, #"Mapped Account List ID" = 1608],
					        [#"Mapped Account ID" = 1366, #"Mapped Account List ID" = 6603],
					        [#"Mapped Account ID" = 8817, #"Mapped Account List ID" = 8429],
					        [#"Mapped Account ID" = 3763, #"Mapped Account List ID" = 2612],
					        [#"Mapped Account ID" = 7727, #"Mapped Account List ID" = 1306],
					        [#"Mapped Account ID" = 3765, #"Mapped Account List ID" = 6119],
					        [#"Mapped Account ID" = 1193, #"Mapped Account List ID" = 4901],
					        [#"Mapped Account ID" = 3459, #"Mapped Account List ID" = 9365],
					        [#"Mapped Account ID" = 4717, #"Mapped Account List ID" = 7509],
					        [#"Mapped Account ID" = 4712, #"Mapped Account List ID" = 8806],
					        [#"Mapped Account ID" = 14, #"Mapped Account List ID" = 2625],
					        [#"Mapped Account ID" = 5360, #"Mapped Account List ID" = 1117],
					        [#"Mapped Account ID" = 8061, #"Mapped Account List ID" = 4313],
					        [#"Mapped Account ID" = 3470, #"Mapped Account List ID" = 1863],
					        [#"Mapped Account ID" = 8885, #"Mapped Account List ID" = 5049],
					        [#"Mapped Account ID" = 7671, #"Mapped Account List ID" = 9591],
					        [#"Mapped Account ID" = 3326, #"Mapped Account List ID" = 81],
					        [#"Mapped Account ID" = 4476, #"Mapped Account List ID" = 9960],
					        [#"Mapped Account ID" = 4640, #"Mapped Account List ID" = 2793],
					        [#"Mapped Account ID" = 5, #"Mapped Account List ID" = 4857],
					        [#"Mapped Account ID" = 4689, #"Mapped Account List ID" = 4586],
					        [#"Mapped Account ID" = 1013, #"Mapped Account List ID" = 8933],
					        [#"Mapped Account ID" = 7909, #"Mapped Account List ID" = 318],
					        [#"Mapped Account ID" = 9923, #"Mapped Account List ID" = 9737],
					        [#"Mapped Account ID" = 226, #"Mapped Account List ID" = 5931],
					        [#"Mapped Account ID" = 6090, #"Mapped Account List ID" = 4085],
					        [#"Mapped Account ID" = 1803, #"Mapped Account List ID" = 8713],
					        [#"Mapped Account ID" = 8395, #"Mapped Account List ID" = 6180],
					        [#"Mapped Account ID" = 1488, #"Mapped Account List ID" = 7144],
					        [#"Mapped Account ID" = 2198, #"Mapped Account List ID" = 1703],
					        [#"Mapped Account ID" = 117, #"Mapped Account List ID" = 1055],
					        [#"Mapped Account ID" = 7528, #"Mapped Account List ID" = 1271],
					        [#"Mapped Account ID" = 7585, #"Mapped Account List ID" = 1376],
					        [#"Mapped Account ID" = 8837, #"Mapped Account List ID" = 5997],
					        [#"Mapped Account ID" = 2437, #"Mapped Account List ID" = 5644],
					        [#"Mapped Account ID" = 4239, #"Mapped Account List ID" = 6642],
					        [#"Mapped Account ID" = 526, #"Mapped Account List ID" = 1309],
					        [#"Mapped Account ID" = 915, #"Mapped Account List ID" = 6881],
					        [#"Mapped Account ID" = 6437, #"Mapped Account List ID" = 8123],
					        [#"Mapped Account ID" = 6653, #"Mapped Account List ID" = 4636],
					        [#"Mapped Account ID" = 5677, #"Mapped Account List ID" = 8587],
					        [#"Mapped Account ID" = 1925, #"Mapped Account List ID" = 4103],
					        [#"Mapped Account ID" = 3526, #"Mapped Account List ID" = 8940],
					        [#"Mapped Account ID" = 1320, #"Mapped Account List ID" = 9501],
					        [#"Mapped Account ID" = 9344, #"Mapped Account List ID" = 1415],
					        [#"Mapped Account ID" = 3235, #"Mapped Account List ID" = 9],
					        [#"Mapped Account ID" = 1733, #"Mapped Account List ID" = 5202],
					        [#"Mapped Account ID" = 494, #"Mapped Account List ID" = 1710],
					        [#"Mapped Account ID" = 5260, #"Mapped Account List ID" = 4460],
					        [#"Mapped Account ID" = 5738, #"Mapped Account List ID" = 3784],
					        [#"Mapped Account ID" = 2175, #"Mapped Account List ID" = 8748],
					        [#"Mapped Account ID" = 6603, #"Mapped Account List ID" = 3159],
					        [#"Mapped Account ID" = 9986, #"Mapped Account List ID" = 7606],
					        [#"Mapped Account ID" = 1684, #"Mapped Account List ID" = 6360],
					        [#"Mapped Account ID" = 8056, #"Mapped Account List ID" = 4267],
					        [#"Mapped Account ID" = 3994, #"Mapped Account List ID" = 3490],
					        [#"Mapped Account ID" = 6501, #"Mapped Account List ID" = 6676],
					        [#"Mapped Account ID" = 6037, #"Mapped Account List ID" = 1239],
					        [#"Mapped Account ID" = 7585, #"Mapped Account List ID" = 2381],
					        [#"Mapped Account ID" = 3840, #"Mapped Account List ID" = 6947],
					        [#"Mapped Account ID" = 9269, #"Mapped Account List ID" = 656],
					        [#"Mapped Account ID" = 3810, #"Mapped Account List ID" = 3829],
					        [#"Mapped Account ID" = 8193, #"Mapped Account List ID" = 5535],
					        [#"Mapped Account ID" = 7706, #"Mapped Account List ID" = 6089],
					        [#"Mapped Account ID" = 1342, #"Mapped Account List ID" = 5930],
					        [#"Mapped Account ID" = 1220, #"Mapped Account List ID" = 1589],
					        [#"Mapped Account ID" = 3625, #"Mapped Account List ID" = 4325],
					        [#"Mapped Account ID" = 5491, #"Mapped Account List ID" = 4551],
					        [#"Mapped Account ID" = 7697, #"Mapped Account List ID" = 8268],
					        [#"Mapped Account ID" = 5706, #"Mapped Account List ID" = 9231],
					        [#"Mapped Account ID" = 6836, #"Mapped Account List ID" = 9187],
					        [#"Mapped Account ID" = 3015, #"Mapped Account List ID" = 3643],
					        [#"Mapped Account ID" = 7360, #"Mapped Account List ID" = 2285],
					        [#"Mapped Account ID" = 1482, #"Mapped Account List ID" = 499],
					        [#"Mapped Account ID" = 231, #"Mapped Account List ID" = 8143],
					        [#"Mapped Account ID" = 1278, #"Mapped Account List ID" = 3771],
					        [#"Mapped Account ID" = 1271, #"Mapped Account List ID" = 977],
					        [#"Mapped Account ID" = 4437, #"Mapped Account List ID" = 9998],
					        [#"Mapped Account ID" = 4733, #"Mapped Account List ID" = 6170],
					        [#"Mapped Account ID" = 9560, #"Mapped Account List ID" = 707],
					        [#"Mapped Account ID" = 6085, #"Mapped Account List ID" = 3843],
					        [#"Mapped Account ID" = 6493, #"Mapped Account List ID" = 8484],
					        [#"Mapped Account ID" = 1534, #"Mapped Account List ID" = 6690],
					        [#"Mapped Account ID" = 3530, #"Mapped Account List ID" = 3488],
					        [#"Mapped Account ID" = 5238, #"Mapped Account List ID" = 7196],
					        [#"Mapped Account ID" = 1244, #"Mapped Account List ID" = 9436],
					        [#"Mapped Account ID" = 7357, #"Mapped Account List ID" = 382],
					        [#"Mapped Account ID" = 2754, #"Mapped Account List ID" = 1670],
					        [#"Mapped Account ID" = 234, #"Mapped Account List ID" = 1548],
					        [#"Mapped Account ID" = 2747, #"Mapped Account List ID" = 4020],
					        [#"Mapped Account ID" = 3198, #"Mapped Account List ID" = 8322],
					        [#"Mapped Account ID" = 5941, #"Mapped Account List ID" = 3490],
					        [#"Mapped Account ID" = 6313, #"Mapped Account List ID" = 2085],
					        [#"Mapped Account ID" = 8470, #"Mapped Account List ID" = 1065],
					        [#"Mapped Account ID" = 7150, #"Mapped Account List ID" = 2336],
					        [#"Mapped Account ID" = 3759, #"Mapped Account List ID" = 5146],
					        [#"Mapped Account ID" = 1361, #"Mapped Account List ID" = 2810],
					        [#"Mapped Account ID" = 7429, #"Mapped Account List ID" = 5223],
					        [#"Mapped Account ID" = 6040, #"Mapped Account List ID" = 6544],
					        [#"Mapped Account ID" = 1983, #"Mapped Account List ID" = 7741],
					        [#"Mapped Account ID" = 9010, #"Mapped Account List ID" = 1333],
					        [#"Mapped Account ID" = 5010, #"Mapped Account List ID" = 1798],
					        [#"Mapped Account ID" = 2031, #"Mapped Account List ID" = 5946],
					        [#"Mapped Account ID" = 3534, #"Mapped Account List ID" = 7351],
					        [#"Mapped Account ID" = 9048, #"Mapped Account List ID" = 1326],
					        [#"Mapped Account ID" = 9568, #"Mapped Account List ID" = 7164],
					        [#"Mapped Account ID" = 8300, #"Mapped Account List ID" = 6948],
					        [#"Mapped Account ID" = 9531, #"Mapped Account List ID" = 8491],
					        [#"Mapped Account ID" = 2768, #"Mapped Account List ID" = 2599],
					        [#"Mapped Account ID" = 4215, #"Mapped Account List ID" = 7043],
					        [#"Mapped Account ID" = 2903, #"Mapped Account List ID" = 1171],
					        [#"Mapped Account ID" = 1885, #"Mapped Account List ID" = 5365],
					        [#"Mapped Account ID" = 2078, #"Mapped Account List ID" = 1905],
					        [#"Mapped Account ID" = 6024, #"Mapped Account List ID" = 5395],
					        [#"Mapped Account ID" = 9548, #"Mapped Account List ID" = 6632],
					        [#"Mapped Account ID" = 9692, #"Mapped Account List ID" = 8524],
					        [#"Mapped Account ID" = 2056, #"Mapped Account List ID" = 5818],
					        [#"Mapped Account ID" = 5124, #"Mapped Account List ID" = 1215],
					        [#"Mapped Account ID" = 5281, #"Mapped Account List ID" = 8703],
					        [#"Mapped Account ID" = 6164, #"Mapped Account List ID" = 2523],
					        [#"Mapped Account ID" = 3281, #"Mapped Account List ID" = 2010],
					        [#"Mapped Account ID" = 9944, #"Mapped Account List ID" = 3375],
					        [#"Mapped Account ID" = 9483, #"Mapped Account List ID" = 9270],
					        [#"Mapped Account ID" = 2365, #"Mapped Account List ID" = 6541],
					        [#"Mapped Account ID" = 6940, #"Mapped Account List ID" = 262],
					        [#"Mapped Account ID" = 3615, #"Mapped Account List ID" = 9560],
					        [#"Mapped Account ID" = 8951, #"Mapped Account List ID" = 8937],
					        [#"Mapped Account ID" = 4110, #"Mapped Account List ID" = 3449],
					        [#"Mapped Account ID" = 9907, #"Mapped Account List ID" = 2532],
					        [#"Mapped Account ID" = 7849, #"Mapped Account List ID" = 9474],
					        [#"Mapped Account ID" = 8963, #"Mapped Account List ID" = 823],
					        [#"Mapped Account ID" = 243, #"Mapped Account List ID" = 9291],
					        [#"Mapped Account ID" = 5104, #"Mapped Account List ID" = 323],
					        [#"Mapped Account ID" = 1230, #"Mapped Account List ID" = 1097],
					        [#"Mapped Account ID" = 4889, #"Mapped Account List ID" = 1435],
					        [#"Mapped Account ID" = 6645, #"Mapped Account List ID" = 4826],
					        [#"Mapped Account ID" = 4125, #"Mapped Account List ID" = 2179],
					        [#"Mapped Account ID" = 6616, #"Mapped Account List ID" = 5201],
					        [#"Mapped Account ID" = 4056, #"Mapped Account List ID" = 3132],
					        [#"Mapped Account ID" = 4776, #"Mapped Account List ID" = 150],
					        [#"Mapped Account ID" = 8654, #"Mapped Account List ID" = 8303],
					        [#"Mapped Account ID" = 2230, #"Mapped Account List ID" = 4840],
					        [#"Mapped Account ID" = 8037, #"Mapped Account List ID" = 3049],
					        [#"Mapped Account ID" = 7420, #"Mapped Account List ID" = 1805],
					        [#"Mapped Account ID" = 8189, #"Mapped Account List ID" = 6619],
					        [#"Mapped Account ID" = 9190, #"Mapped Account List ID" = 8024],
					        [#"Mapped Account ID" = 956, #"Mapped Account List ID" = 3667],
					        [#"Mapped Account ID" = 6275, #"Mapped Account List ID" = 1056],
					        [#"Mapped Account ID" = 4246, #"Mapped Account List ID" = 9616],
					        [#"Mapped Account ID" = 4599, #"Mapped Account List ID" = 4258],
					        [#"Mapped Account ID" = 4744, #"Mapped Account List ID" = 484],
					        [#"Mapped Account ID" = 1160, #"Mapped Account List ID" = 2570],
					        [#"Mapped Account ID" = 4596, #"Mapped Account List ID" = 4555],
					        [#"Mapped Account ID" = 1797, #"Mapped Account List ID" = 1965],
					        [#"Mapped Account ID" = 6729, #"Mapped Account List ID" = 8712],
					        [#"Mapped Account ID" = 5863, #"Mapped Account List ID" = 4889],
					        [#"Mapped Account ID" = 8715, #"Mapped Account List ID" = 8173],
					        [#"Mapped Account ID" = 7335, #"Mapped Account List ID" = 3464],
					        [#"Mapped Account ID" = 1112, #"Mapped Account List ID" = 5723],
					        [#"Mapped Account ID" = 7763, #"Mapped Account List ID" = 996],
					        [#"Mapped Account ID" = 1248, #"Mapped Account List ID" = 7017],
					        [#"Mapped Account ID" = 1589, #"Mapped Account List ID" = 2201],
					        [#"Mapped Account ID" = 3468, #"Mapped Account List ID" = 4862],
					        [#"Mapped Account ID" = 2516, #"Mapped Account List ID" = 7363],
					        [#"Mapped Account ID" = 669, #"Mapped Account List ID" = 1454],
					        [#"Mapped Account ID" = 1715, #"Mapped Account List ID" = 3824],
					        [#"Mapped Account ID" = 5873, #"Mapped Account List ID" = 7473],
					        [#"Mapped Account ID" = 1885, #"Mapped Account List ID" = 5509],
					        [#"Mapped Account ID" = 6540, #"Mapped Account List ID" = 1526],
					        [#"Mapped Account ID" = 1667, #"Mapped Account List ID" = 2529],
					        [#"Mapped Account ID" = 6150, #"Mapped Account List ID" = 8173],
					        [#"Mapped Account ID" = 6912, #"Mapped Account List ID" = 1281],
					        [#"Mapped Account ID" = 2891, #"Mapped Account List ID" = 6613],
					        [#"Mapped Account ID" = 9183, #"Mapped Account List ID" = 6778],
					        [#"Mapped Account ID" = 9231, #"Mapped Account List ID" = 5362],
					        [#"Mapped Account ID" = 5850, #"Mapped Account List ID" = 3166],
					        [#"Mapped Account ID" = 6162, #"Mapped Account List ID" = 5156],
					        [#"Mapped Account ID" = 4785, #"Mapped Account List ID" = 9639],
					        [#"Mapped Account ID" = 3175, #"Mapped Account List ID" = 6182],
					        [#"Mapped Account ID" = 7019, #"Mapped Account List ID" = 2054],
					        [#"Mapped Account ID" = 6511, #"Mapped Account List ID" = 8597],
					        [#"Mapped Account ID" = 103, #"Mapped Account List ID" = 9122],
					        [#"Mapped Account ID" = 5177, #"Mapped Account List ID" = 7162],
					        [#"Mapped Account ID" = 6073, #"Mapped Account List ID" = 7912],
					        [#"Mapped Account ID" = 9325, #"Mapped Account List ID" = 6309],
					        [#"Mapped Account ID" = 6225, #"Mapped Account List ID" = 6149],
					        [#"Mapped Account ID" = 5581, #"Mapped Account List ID" = 2470],
					        [#"Mapped Account ID" = 5961, #"Mapped Account List ID" = 1319],
					        [#"Mapped Account ID" = 5399, #"Mapped Account List ID" = 5744],
					        [#"Mapped Account ID" = 5737, #"Mapped Account List ID" = 1867],
					        [#"Mapped Account ID" = 5901, #"Mapped Account List ID" = 1023],
					        [#"Mapped Account ID" = 8497, #"Mapped Account List ID" = 30],
					        [#"Mapped Account ID" = 5157, #"Mapped Account List ID" = 8897],
					        [#"Mapped Account ID" = 4952, #"Mapped Account List ID" = 4602],
					        [#"Mapped Account ID" = 2793, #"Mapped Account List ID" = 2066],
					        [#"Mapped Account ID" = 3618, #"Mapped Account List ID" = 5659],
					        [#"Mapped Account ID" = 7072, #"Mapped Account List ID" = 5567],
					        [#"Mapped Account ID" = 1536, #"Mapped Account List ID" = 9606],
					        [#"Mapped Account ID" = 679, #"Mapped Account List ID" = 7763],
					        [#"Mapped Account ID" = 5291, #"Mapped Account List ID" = 6787],
					        [#"Mapped Account ID" = 8419, #"Mapped Account List ID" = 2373],
					        [#"Mapped Account ID" = 5761, #"Mapped Account List ID" = 8005],
					        [#"Mapped Account ID" = 6890, #"Mapped Account List ID" = 4624],
					        [#"Mapped Account ID" = 8874, #"Mapped Account List ID" = 36],
					        [#"Mapped Account ID" = 4067, #"Mapped Account List ID" = 4306],
					        [#"Mapped Account ID" = 9490, #"Mapped Account List ID" = 3710],
					        [#"Mapped Account ID" = 2376, #"Mapped Account List ID" = 8318],
					        [#"Mapped Account ID" = 4054, #"Mapped Account List ID" = 2817],
					        [#"Mapped Account ID" = 574, #"Mapped Account List ID" = 2386],
					        [#"Mapped Account ID" = 1851, #"Mapped Account List ID" = 8192],
					        [#"Mapped Account ID" = 9532, #"Mapped Account List ID" = 9211],
					        [#"Mapped Account ID" = 5653, #"Mapped Account List ID" = 9547],
					        [#"Mapped Account ID" = 3708, #"Mapped Account List ID" = 5221],
					        [#"Mapped Account ID" = 7271, #"Mapped Account List ID" = 8118],
					        [#"Mapped Account ID" = 5632, #"Mapped Account List ID" = 2761],
					        [#"Mapped Account ID" = 4260, #"Mapped Account List ID" = 3227],
					        [#"Mapped Account ID" = 5117, #"Mapped Account List ID" = 1738],
					        [#"Mapped Account ID" = 14, #"Mapped Account List ID" = 2637],
					        [#"Mapped Account ID" = 5152, #"Mapped Account List ID" = 3077],
					        [#"Mapped Account ID" = 4160, #"Mapped Account List ID" = 1727],
					        [#"Mapped Account ID" = 3792, #"Mapped Account List ID" = 7875],
					        [#"Mapped Account ID" = 3788, #"Mapped Account List ID" = 9986],
					        [#"Mapped Account ID" = 7284, #"Mapped Account List ID" = 8140],
					        [#"Mapped Account ID" = 2467, #"Mapped Account List ID" = 2720],
					        [#"Mapped Account ID" = 4087, #"Mapped Account List ID" = 2956],
					        [#"Mapped Account ID" = 6363, #"Mapped Account List ID" = 8118],
					        [#"Mapped Account ID" = 3108, #"Mapped Account List ID" = 6658],
					        [#"Mapped Account ID" = 8213, #"Mapped Account List ID" = 3351],
					        [#"Mapped Account ID" = 4443, #"Mapped Account List ID" = 736],
					        [#"Mapped Account ID" = 9919, #"Mapped Account List ID" = 4201],
					        [#"Mapped Account ID" = 8578, #"Mapped Account List ID" = 8846],
					        [#"Mapped Account ID" = 3190, #"Mapped Account List ID" = 7886],
					        [#"Mapped Account ID" = 4457, #"Mapped Account List ID" = 4756],
					        [#"Mapped Account ID" = 6039, #"Mapped Account List ID" = 1826],
					        [#"Mapped Account ID" = 6887, #"Mapped Account List ID" = 9914],
					        [#"Mapped Account ID" = 3570, #"Mapped Account List ID" = 2],
					        [#"Mapped Account ID" = 7930, #"Mapped Account List ID" = 9487],
					        [#"Mapped Account ID" = 9192, #"Mapped Account List ID" = 8790],
					        [#"Mapped Account ID" = 1991, #"Mapped Account List ID" = 6660],
					        [#"Mapped Account ID" = 5069, #"Mapped Account List ID" = 9559],
					        [#"Mapped Account ID" = 548, #"Mapped Account List ID" = 1276],
					        [#"Mapped Account ID" = 7652, #"Mapped Account List ID" = 9834],
					        [#"Mapped Account ID" = 8834, #"Mapped Account List ID" = 1487],
					        [#"Mapped Account ID" = 8174, #"Mapped Account List ID" = 5732],
					        [#"Mapped Account ID" = 8084, #"Mapped Account List ID" = 926],
					        [#"Mapped Account ID" = 1185, #"Mapped Account List ID" = 8774],
					        [#"Mapped Account ID" = 6382, #"Mapped Account List ID" = 1382],
					        [#"Mapped Account ID" = 3696, #"Mapped Account List ID" = 9330],
					        [#"Mapped Account ID" = 8801, #"Mapped Account List ID" = 6724],
					        [#"Mapped Account ID" = 5817, #"Mapped Account List ID" = 9127],
					        [#"Mapped Account ID" = 7385, #"Mapped Account List ID" = 2906],
					        [#"Mapped Account ID" = 2015, #"Mapped Account List ID" = 6057],
					        [#"Mapped Account ID" = 940, #"Mapped Account List ID" = 3374],
					        [#"Mapped Account ID" = 592, #"Mapped Account List ID" = 1516],
					        [#"Mapped Account ID" = 7824, #"Mapped Account List ID" = 4363],
					        [#"Mapped Account ID" = 7467, #"Mapped Account List ID" = 3556],
					        [#"Mapped Account ID" = 4853, #"Mapped Account List ID" = 5700],
					        [#"Mapped Account ID" = 2335, #"Mapped Account List ID" = 6308],
					        [#"Mapped Account ID" = 9738, #"Mapped Account List ID" = 6154],
					        [#"Mapped Account ID" = 4091, #"Mapped Account List ID" = 1406],
					        [#"Mapped Account ID" = 1683, #"Mapped Account List ID" = 1504],
					        [#"Mapped Account ID" = 7879, #"Mapped Account List ID" = 609],
					        [#"Mapped Account ID" = 6176, #"Mapped Account List ID" = 5938],
					        [#"Mapped Account ID" = 4651, #"Mapped Account List ID" = 8183],
					        [#"Mapped Account ID" = 5165, #"Mapped Account List ID" = 7752],
					        [#"Mapped Account ID" = 1562, #"Mapped Account List ID" = 6388],
					        [#"Mapped Account ID" = 1045, #"Mapped Account List ID" = 2159],
					        [#"Mapped Account ID" = 434, #"Mapped Account List ID" = 917],
					        [#"Mapped Account ID" = 5196, #"Mapped Account List ID" = 8287],
					        [#"Mapped Account ID" = 8087, #"Mapped Account List ID" = 3966],
					        [#"Mapped Account ID" = 1442, #"Mapped Account List ID" = 7583],
					        [#"Mapped Account ID" = 9336, #"Mapped Account List ID" = 5275],
					        [#"Mapped Account ID" = 3475, #"Mapped Account List ID" = 9500],
					        [#"Mapped Account ID" = 8593, #"Mapped Account List ID" = 6698],
					        [#"Mapped Account ID" = 6580, #"Mapped Account List ID" = 5727],
					        [#"Mapped Account ID" = 6558, #"Mapped Account List ID" = 792],
					        [#"Mapped Account ID" = 3359, #"Mapped Account List ID" = 9568],
					        [#"Mapped Account ID" = 3362, #"Mapped Account List ID" = 9395],
					        [#"Mapped Account ID" = 3214, #"Mapped Account List ID" = 1117],
					        [#"Mapped Account ID" = 986, #"Mapped Account List ID" = 5338],
					        [#"Mapped Account ID" = 6651, #"Mapped Account List ID" = 7338],
					        [#"Mapped Account ID" = 8847, #"Mapped Account List ID" = 2140],
					        [#"Mapped Account ID" = 266, #"Mapped Account List ID" = 9559],
					        [#"Mapped Account ID" = 2750, #"Mapped Account List ID" = 6785],
					        [#"Mapped Account ID" = 7519, #"Mapped Account List ID" = 5368],
					        [#"Mapped Account ID" = 6126, #"Mapped Account List ID" = 897],
					        [#"Mapped Account ID" = 8522, #"Mapped Account List ID" = 3291],
					        [#"Mapped Account ID" = 5172, #"Mapped Account List ID" = 4737],
					        [#"Mapped Account ID" = 283, #"Mapped Account List ID" = 3557],
					        [#"Mapped Account ID" = 3851, #"Mapped Account List ID" = 1536],
					        [#"Mapped Account ID" = 3464, #"Mapped Account List ID" = 1177],
					        [#"Mapped Account ID" = 8422, #"Mapped Account List ID" = 2816],
					        [#"Mapped Account ID" = 3056, #"Mapped Account List ID" = 6915],
					        [#"Mapped Account ID" = 1263, #"Mapped Account List ID" = 3605],
					        [#"Mapped Account ID" = 8647, #"Mapped Account List ID" = 8941],
					        [#"Mapped Account ID" = 3476, #"Mapped Account List ID" = 7564],
					        [#"Mapped Account ID" = 8644, #"Mapped Account List ID" = 2100],
					        [#"Mapped Account ID" = 2714, #"Mapped Account List ID" = 5392],
					        [#"Mapped Account ID" = 8293, #"Mapped Account List ID" = 4832],
					        [#"Mapped Account ID" = 437, #"Mapped Account List ID" = 3500],
					        [#"Mapped Account ID" = 5186, #"Mapped Account List ID" = 7495],
					        [#"Mapped Account ID" = 8023, #"Mapped Account List ID" = 8512],
					        [#"Mapped Account ID" = 5625, #"Mapped Account List ID" = 5653],
					        [#"Mapped Account ID" = 4122, #"Mapped Account List ID" = 1704],
					        [#"Mapped Account ID" = 9289, #"Mapped Account List ID" = 5307],
					        [#"Mapped Account ID" = 2971, #"Mapped Account List ID" = 6485],
					        [#"Mapped Account ID" = 2712, #"Mapped Account List ID" = 4490],
					        [#"Mapped Account ID" = 4634, #"Mapped Account List ID" = 6916],
					        [#"Mapped Account ID" = 3235, #"Mapped Account List ID" = 7515],
					        [#"Mapped Account ID" = 5629, #"Mapped Account List ID" = 4929],
					        [#"Mapped Account ID" = 2612, #"Mapped Account List ID" = 6226],
					        [#"Mapped Account ID" = 9987, #"Mapped Account List ID" = 4965],
					        [#"Mapped Account ID" = 7862, #"Mapped Account List ID" = 958],
					        [#"Mapped Account ID" = 9137, #"Mapped Account List ID" = 4568],
					        [#"Mapped Account ID" = 320, #"Mapped Account List ID" = 2454],
					        [#"Mapped Account ID" = 8411, #"Mapped Account List ID" = 2454],
					        [#"Mapped Account ID" = 4796, #"Mapped Account List ID" = 3058],
					        [#"Mapped Account ID" = 4962, #"Mapped Account List ID" = 6664],
					        [#"Mapped Account ID" = 7009, #"Mapped Account List ID" = 4322],
					        [#"Mapped Account ID" = 2528, #"Mapped Account List ID" = 896],
					        [#"Mapped Account ID" = 1318, #"Mapped Account List ID" = 4902],
					        [#"Mapped Account ID" = 1, #"Mapped Account List ID" = 9066],
					        [#"Mapped Account ID" = 106, #"Mapped Account List ID" = 8142],
					        [#"Mapped Account ID" = 7888, #"Mapped Account List ID" = 3992],
					        [#"Mapped Account ID" = 6605, #"Mapped Account List ID" = 3433],
					        [#"Mapped Account ID" = 4727, #"Mapped Account List ID" = 1173],
					        [#"Mapped Account ID" = 8359, #"Mapped Account List ID" = 1444],
					        [#"Mapped Account ID" = 435, #"Mapped Account List ID" = 9331],
					        [#"Mapped Account ID" = 7555, #"Mapped Account List ID" = 3044],
					        [#"Mapped Account ID" = 7683, #"Mapped Account List ID" = 7214],
					        [#"Mapped Account ID" = 2004, #"Mapped Account List ID" = 1923],
					        [#"Mapped Account ID" = 4535, #"Mapped Account List ID" = 3314],
					        [#"Mapped Account ID" = 49, #"Mapped Account List ID" = 4504],
					        [#"Mapped Account ID" = 817, #"Mapped Account List ID" = 4733],
					        [#"Mapped Account ID" = 4331, #"Mapped Account List ID" = 10],
					        [#"Mapped Account ID" = 4649, #"Mapped Account List ID" = 2481],
					        [#"Mapped Account ID" = 3131, #"Mapped Account List ID" = 6246],
					        [#"Mapped Account ID" = 8909, #"Mapped Account List ID" = 9613],
					        [#"Mapped Account ID" = 8059, #"Mapped Account List ID" = 7265],
					        [#"Mapped Account ID" = 2517, #"Mapped Account List ID" = 9751],
					        [#"Mapped Account ID" = 8227, #"Mapped Account List ID" = 4814],
					        [#"Mapped Account ID" = 8200, #"Mapped Account List ID" = 7301],
					        [#"Mapped Account ID" = 5610, #"Mapped Account List ID" = 1504],
					        [#"Mapped Account ID" = 7331, #"Mapped Account List ID" = 6800],
					        [#"Mapped Account ID" = 1619, #"Mapped Account List ID" = 2337],
					        [#"Mapped Account ID" = 291, #"Mapped Account List ID" = 8285],
					        [#"Mapped Account ID" = 2971, #"Mapped Account List ID" = 78],
					        [#"Mapped Account ID" = 3937, #"Mapped Account List ID" = 2181],
					        [#"Mapped Account ID" = 3717, #"Mapped Account List ID" = 5748],
					        [#"Mapped Account ID" = 283, #"Mapped Account List ID" = 971],
					        [#"Mapped Account ID" = 1849, #"Mapped Account List ID" = 6032],
					        [#"Mapped Account ID" = 3952, #"Mapped Account List ID" = 7835],
					        [#"Mapped Account ID" = 3429, #"Mapped Account List ID" = 4979],
					        [#"Mapped Account ID" = 4698, #"Mapped Account List ID" = 4717],
					        [#"Mapped Account ID" = 7703, #"Mapped Account List ID" = 5495],
					        [#"Mapped Account ID" = 5302, #"Mapped Account List ID" = 2786],
					        [#"Mapped Account ID" = 3643, #"Mapped Account List ID" = 1744],
					        [#"Mapped Account ID" = 8546, #"Mapped Account List ID" = 5138],
					        [#"Mapped Account ID" = 956, #"Mapped Account List ID" = 7144],
					        [#"Mapped Account ID" = 3663, #"Mapped Account List ID" = 3789],
					        [#"Mapped Account ID" = 5558, #"Mapped Account List ID" = 3215],
					        [#"Mapped Account ID" = 6783, #"Mapped Account List ID" = 3551],
					        [#"Mapped Account ID" = 5005, #"Mapped Account List ID" = 4661],
					        [#"Mapped Account ID" = 3113, #"Mapped Account List ID" = 6043],
					        [#"Mapped Account ID" = 8450, #"Mapped Account List ID" = 629],
					        [#"Mapped Account ID" = 8438, #"Mapped Account List ID" = 5423],
					        [#"Mapped Account ID" = 8070, #"Mapped Account List ID" = 8964],
					        [#"Mapped Account ID" = 3121, #"Mapped Account List ID" = 3401],
					        [#"Mapped Account ID" = 2510, #"Mapped Account List ID" = 7223],
					        [#"Mapped Account ID" = 3087, #"Mapped Account List ID" = 5685],
					        [#"Mapped Account ID" = 2433, #"Mapped Account List ID" = 7940],
					        [#"Mapped Account ID" = 8201, #"Mapped Account List ID" = 4047],
					        [#"Mapped Account ID" = 600, #"Mapped Account List ID" = 7496],
					        [#"Mapped Account ID" = 7049, #"Mapped Account List ID" = 8369],
					        [#"Mapped Account ID" = 2238, #"Mapped Account List ID" = 6065],
					        [#"Mapped Account ID" = 6984, #"Mapped Account List ID" = 1976],
					        [#"Mapped Account ID" = 9544, #"Mapped Account List ID" = 8530],
					        [#"Mapped Account ID" = 8445, #"Mapped Account List ID" = 7965],
					        [#"Mapped Account ID" = 5856, #"Mapped Account List ID" = 8816],
					        [#"Mapped Account ID" = 6534, #"Mapped Account List ID" = 500],
					        [#"Mapped Account ID" = 2969, #"Mapped Account List ID" = 4023],
					        [#"Mapped Account ID" = 5315, #"Mapped Account List ID" = 8290],
					        [#"Mapped Account ID" = 1330, #"Mapped Account List ID" = 7992],
					        [#"Mapped Account ID" = 8218, #"Mapped Account List ID" = 1452],
					        [#"Mapped Account ID" = 5389, #"Mapped Account List ID" = 4700],
					        [#"Mapped Account ID" = 6908, #"Mapped Account List ID" = 8899],
					        [#"Mapped Account ID" = 2769, #"Mapped Account List ID" = 6699],
					        [#"Mapped Account ID" = 3240, #"Mapped Account List ID" = 1360],
					        [#"Mapped Account ID" = 9472, #"Mapped Account List ID" = 5725],
					        [#"Mapped Account ID" = 5767, #"Mapped Account List ID" = 2791],
					        [#"Mapped Account ID" = 4702, #"Mapped Account List ID" = 3360],
					        [#"Mapped Account ID" = 4898, #"Mapped Account List ID" = 3772],
					        [#"Mapped Account ID" = 1966, #"Mapped Account List ID" = 6005],
					        [#"Mapped Account ID" = 5740, #"Mapped Account List ID" = 42],
					        [#"Mapped Account ID" = 9910, #"Mapped Account List ID" = 5813],
					        [#"Mapped Account ID" = 8853, #"Mapped Account List ID" = 7445],
					        [#"Mapped Account ID" = 8853, #"Mapped Account List ID" = 5766],
					        [#"Mapped Account ID" = 3816, #"Mapped Account List ID" = 7286],
					        [#"Mapped Account ID" = 8407, #"Mapped Account List ID" = 4410],
					        [#"Mapped Account ID" = 4796, #"Mapped Account List ID" = 8662],
					        [#"Mapped Account ID" = 7087, #"Mapped Account List ID" = 9272],
					        [#"Mapped Account ID" = 5828, #"Mapped Account List ID" = 2554],
					        [#"Mapped Account ID" = 4824, #"Mapped Account List ID" = 3179],
					        [#"Mapped Account ID" = 5524, #"Mapped Account List ID" = 9566],
					        [#"Mapped Account ID" = 680, #"Mapped Account List ID" = 5488],
					        [#"Mapped Account ID" = 8853, #"Mapped Account List ID" = 6567],
					        [#"Mapped Account ID" = 8855, #"Mapped Account List ID" = 5551],
					        [#"Mapped Account ID" = 7130, #"Mapped Account List ID" = 6906],
					        [#"Mapped Account ID" = 4010, #"Mapped Account List ID" = 494],
					        [#"Mapped Account ID" = 7318, #"Mapped Account List ID" = 911],
					        [#"Mapped Account ID" = 2343, #"Mapped Account List ID" = 4840],
					        [#"Mapped Account ID" = 1903, #"Mapped Account List ID" = 8891],
					        [#"Mapped Account ID" = 297, #"Mapped Account List ID" = 2660],
					        [#"Mapped Account ID" = 1646, #"Mapped Account List ID" = 421],
					        [#"Mapped Account ID" = 5970, #"Mapped Account List ID" = 4256],
					        [#"Mapped Account ID" = 8275, #"Mapped Account List ID" = 3778],
					        [#"Mapped Account ID" = 1921, #"Mapped Account List ID" = 4070],
					        [#"Mapped Account ID" = 7601, #"Mapped Account List ID" = 61],
					        [#"Mapped Account ID" = 783, #"Mapped Account List ID" = 5110],
					        [#"Mapped Account ID" = 6382, #"Mapped Account List ID" = 8016],
					        [#"Mapped Account ID" = 4423, #"Mapped Account List ID" = 795],
					        [#"Mapped Account ID" = 6597, #"Mapped Account List ID" = 8853],
					        [#"Mapped Account ID" = 9503, #"Mapped Account List ID" = 3529],
					        [#"Mapped Account ID" = 1316, #"Mapped Account List ID" = 1500],
					        [#"Mapped Account ID" = 866, #"Mapped Account List ID" = 3481],
					        [#"Mapped Account ID" = 2209, #"Mapped Account List ID" = 7390],
					        [#"Mapped Account ID" = 8457, #"Mapped Account List ID" = 1486],
					        [#"Mapped Account ID" = 3312, #"Mapped Account List ID" = 6833],
					        [#"Mapped Account ID" = 9000, #"Mapped Account List ID" = 418],
					        [#"Mapped Account ID" = 6525, #"Mapped Account List ID" = 1921]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Mapped Account ID", Int64.Type},
					        {"Mapped Account List ID", Int64.Type}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table