table 'Sales DataSource_Customers.csv'
	lineageTag: 53ae4ff0-9c58-4582-8db4-a9c632b49b66

	column 'Customer ID'
		dataType: string
		lineageTag: 2b0c25f6-a29b-4a26-8cde-deaab767e7d8
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 971b3204-4fae-496d-bc50-ffc266342829
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	partition 'Sales DataSource_Customers.csv' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Customer ID" = 4908, #"Customer Name" = "Regine Kane"],
					        [#"Customer ID" = 8877, #"Customer Name" = "Darlena Houston"],
					        [#"Customer ID" = 9003, #"Customer Name" = "Heide Barrett"],
					        [#"Customer ID" = 8308, #"Customer Name" = "Danny Head"],
					        [#"Customer ID" = 1187, #"Customer Name" = "Harry Frazier"],
					        [#"Customer ID" = 5636, #"Customer Name" = "Claude Hawkins"],
					        [#"Customer ID" = 7770, #"Customer Name" = "Wilford Holman"],
					        [#"Customer ID" = 1077, #"Customer Name" = "Evelyne Clay"],
					        [#"Customer ID" = 2437, #"Customer Name" = "Glynda Blackburn"],
					        [#"Customer ID" = 9705, #"Customer Name" = "Randa Underwood"],
					        [#"Customer ID" = 5673, #"Customer Name" = "Isaac Bryan"],
					        [#"Customer ID" = 5186, #"Customer Name" = "Zachariah Jackson"],
					        [#"Customer ID" = 3844, #"Customer Name" = "Rudy Shaw"],
					        [#"Customer ID" = 6123, #"Customer Name" = "Dave Valencia"],
					        [#"Customer ID" = 7852, #"Customer Name" = "Tiffaney Pollard"],
					        [#"Customer ID" = 6204, #"Customer Name" = "Efrain Wilcox"],
					        [#"Customer ID" = 4876, #"Customer Name" = "Shantay Mack"],
					        [#"Customer ID" = 3218, #"Customer Name" = "Perry Stephenson"],
					        [#"Customer ID" = 3547, #"Customer Name" = "Rolando Slater"],
					        [#"Customer ID" = 2645, #"Customer Name" = "Earleen Hale"],
					        [#"Customer ID" = 7486, #"Customer Name" = "Dierdre Joyce"],
					        [#"Customer ID" = 7219, #"Customer Name" = "Pasquale Cobb"],
					        [#"Customer ID" = 2194, #"Customer Name" = "Caron Klein"],
					        [#"Customer ID" = 5551, #"Customer Name" = "Chester Browning"],
					        [#"Customer ID" = 4382, #"Customer Name" = "Despina Burris"],
					        [#"Customer ID" = 7128, #"Customer Name" = "Floretta Yang"],
					        [#"Customer ID" = 7708, #"Customer Name" = "Kina Reed"],
					        [#"Customer ID" = 2200, #"Customer Name" = "Jessika Wilson"],
					        [#"Customer ID" = 5173, #"Customer Name" = "Michale Newman"],
					        [#"Customer ID" = 5234, #"Customer Name" = "Art Burks"],
					        [#"Customer ID" = 4543, #"Customer Name" = "Lenard Adams"],
					        [#"Customer ID" = 2240, #"Customer Name" = "Anton Bennett"],
					        [#"Customer ID" = 1479, #"Customer Name" = "Augustine Lester"],
					        [#"Customer ID" = 3654, #"Customer Name" = "Madalyn Miller"],
					        [#"Customer ID" = 6893, #"Customer Name" = "Jason Mosley"],
					        [#"Customer ID" = 9580, #"Customer Name" = "Chi Mckee"],
					        [#"Customer ID" = 4134, #"Customer Name" = "Toshia Mcdowell"],
					        [#"Customer ID" = 3475, #"Customer Name" = "Herbert Osborn"],
					        [#"Customer ID" = 5558, #"Customer Name" = "Carolynn Pacheco"],
					        [#"Customer ID" = 7075, #"Customer Name" = "Stuart Salas"],
					        [#"Customer ID" = 5681, #"Customer Name" = "Micheal Randolph"],
					        [#"Customer ID" = 6135, #"Customer Name" = "Linwood Glass"],
					        [#"Customer ID" = 7591, #"Customer Name" = "Breann O'neil"],
					        [#"Customer ID" = 8941, #"Customer Name" = "Otis Pena"],
					        [#"Customer ID" = 5593, #"Customer Name" = "Kimberlie Buckley"],
					        [#"Customer ID" = 4842, #"Customer Name" = "Perry Becker"],
					        [#"Customer ID" = 6425, #"Customer Name" = "Harold Case"],
					        [#"Customer ID" = 6730, #"Customer Name" = "Larry Lane"],
					        [#"Customer ID" = 5695, #"Customer Name" = "Ilana Merritt"],
					        [#"Customer ID" = 6612, #"Customer Name" = "Yelena Gross"],
					        [#"Customer ID" = 3807, #"Customer Name" = "Teresia Howe"],
					        [#"Customer ID" = 3493, #"Customer Name" = "Ula Clements"],
					        [#"Customer ID" = 5713, #"Customer Name" = "Erwin Vang"],
					        [#"Customer ID" = 5440, #"Customer Name" = "Cesar Randall"],
					        [#"Customer ID" = 6034, #"Customer Name" = "Rana Castaneda"],
					        [#"Customer ID" = 8660, #"Customer Name" = "Buddy Austin"],
					        [#"Customer ID" = 7771, #"Customer Name" = "Seth Whitehead"],
					        [#"Customer ID" = 6570, #"Customer Name" = "Hassan Ewing"],
					        [#"Customer ID" = 2501, #"Customer Name" = "Leonel Erickson"],
					        [#"Customer ID" = 4679, #"Customer Name" = "Raelene Christian"],
					        [#"Customer ID" = 6404, #"Customer Name" = "Reinaldo Mcclain"],
					        [#"Customer ID" = 5762, #"Customer Name" = "Dusty Shields"],
					        [#"Customer ID" = 5296, #"Customer Name" = "Andree Anthony"],
					        [#"Customer ID" = 8656, #"Customer Name" = "Lane Velez"],
					        [#"Customer ID" = 8336, #"Customer Name" = "Eusebio Burgess"],
					        [#"Customer ID" = 5101, #"Customer Name" = "Hassan Romero"],
					        [#"Customer ID" = 9741, #"Customer Name" = "Suzann Mccall"],
					        [#"Customer ID" = 5904, #"Customer Name" = "Remona Barrera"],
					        [#"Customer ID" = 9824, #"Customer Name" = "Luigi Holder"],
					        [#"Customer ID" = 3543, #"Customer Name" = "Elanor Yates"],
					        [#"Customer ID" = 1060, #"Customer Name" = "Mathilde Kane"],
					        [#"Customer ID" = 9326, #"Customer Name" = "Julieann Salinas"],
					        [#"Customer ID" = 4929, #"Customer Name" = "Macy Holder"],
					        [#"Customer ID" = 3293, #"Customer Name" = "Tennie Harmon"],
					        [#"Customer ID" = 1645, #"Customer Name" = "Cicely Anderson"],
					        [#"Customer ID" = 9779, #"Customer Name" = "Marcelino Moore"],
					        [#"Customer ID" = 6257, #"Customer Name" = "Efren Simon"],
					        [#"Customer ID" = 3176, #"Customer Name" = "Kellee Contreras"],
					        [#"Customer ID" = 4153, #"Customer Name" = "Carletta Deleon"],
					        [#"Customer ID" = 3535, #"Customer Name" = "Britta Glover"],
					        [#"Customer ID" = 5632, #"Customer Name" = "Donald Riley"],
					        [#"Customer ID" = 1582, #"Customer Name" = "Melda Knowles"],
					        [#"Customer ID" = 2725, #"Customer Name" = "Ryann Kane"],
					        [#"Customer ID" = 5704, #"Customer Name" = "Bobette Lindsey"],
					        [#"Customer ID" = 3649, #"Customer Name" = "Shenika Fuller"],
					        [#"Customer ID" = 3981, #"Customer Name" = "Ching O'brien"],
					        [#"Customer ID" = 8629, #"Customer Name" = "Guy Rutledge"],
					        [#"Customer ID" = 1850, #"Customer Name" = "Jan Russo"],
					        [#"Customer ID" = 5060, #"Customer Name" = "Annamae Shepherd"],
					        [#"Customer ID" = 7268, #"Customer Name" = "Lachelle Douglas"],
					        [#"Customer ID" = 5761, #"Customer Name" = "Rod Mayo"],
					        [#"Customer ID" = 4887, #"Customer Name" = "Anneliese Miles"],
					        [#"Customer ID" = 7489, #"Customer Name" = "Viki Page"],
					        [#"Customer ID" = 9610, #"Customer Name" = "Alix Dickson"],
					        [#"Customer ID" = 9587, #"Customer Name" = "Virgen Rodriguez"],
					        [#"Customer ID" = 8991, #"Customer Name" = "Ute Witt"],
					        [#"Customer ID" = 9390, #"Customer Name" = "Joaquin Spence"],
					        [#"Customer ID" = 4553, #"Customer Name" = "Romaine Sanford"],
					        [#"Customer ID" = 4277, #"Customer Name" = "Brian Holt"],
					        [#"Customer ID" = 4998, #"Customer Name" = "Mario Roach"],
					        [#"Customer ID" = 9437, #"Customer Name" = "Jacinto Mccall"],
					        [#"Customer ID" = 9986, #"Customer Name" = "Jackelyn Dalton"],
					        [#"Customer ID" = 8534, #"Customer Name" = "Krystin Montoya"],
					        [#"Customer ID" = 5827, #"Customer Name" = "Frederica Carson"],
					        [#"Customer ID" = 6588, #"Customer Name" = "Keitha Cherry"],
					        [#"Customer ID" = 4345, #"Customer Name" = "Ashley Hicks"],
					        [#"Customer ID" = 4600, #"Customer Name" = "Nerissa Gordon"],
					        [#"Customer ID" = 7063, #"Customer Name" = "Jenee Wolf"],
					        [#"Customer ID" = 5210, #"Customer Name" = "Booker Huber"],
					        [#"Customer ID" = 6962, #"Customer Name" = "Martin Norman"],
					        [#"Customer ID" = 1066, #"Customer Name" = "Brian Whitney"],
					        [#"Customer ID" = 3146, #"Customer Name" = "Minh Mack"],
					        [#"Customer ID" = 3786, #"Customer Name" = "Rich Holcomb"],
					        [#"Customer ID" = 6072, #"Customer Name" = "Derrick Cain"],
					        [#"Customer ID" = 4387, #"Customer Name" = "Lenny Lane"],
					        [#"Customer ID" = 4498, #"Customer Name" = "Macy Banks"],
					        [#"Customer ID" = 2707, #"Customer Name" = "Shaquana Franco"],
					        [#"Customer ID" = 7878, #"Customer Name" = "Elza Wilkerson"],
					        [#"Customer ID" = 4285, #"Customer Name" = "Reda Bowen"],
					        [#"Customer ID" = 7615, #"Customer Name" = "Jodee Dickerson"],
					        [#"Customer ID" = 3911, #"Customer Name" = "Ellsworth Castaneda"],
					        [#"Customer ID" = 2401, #"Customer Name" = "Edgar Pate"],
					        [#"Customer ID" = 2089, #"Customer Name" = "Sindy Warren"],
					        [#"Customer ID" = 8093, #"Customer Name" = "Corey Waters"],
					        [#"Customer ID" = 2405, #"Customer Name" = "Gonzalo Knight"],
					        [#"Customer ID" = 2266, #"Customer Name" = "Adam Foster"],
					        [#"Customer ID" = 4050, #"Customer Name" = "Cedrick Edwards"],
					        [#"Customer ID" = 4882, #"Customer Name" = "Dario Lewis"],
					        [#"Customer ID" = 7818, #"Customer Name" = "Kiyoko Kemp"],
					        [#"Customer ID" = 7355, #"Customer Name" = "Reid Payne"],
					        [#"Customer ID" = 3334, #"Customer Name" = "Blair Short"],
					        [#"Customer ID" = 7134, #"Customer Name" = "Kacie Espinoza"],
					        [#"Customer ID" = 8675, #"Customer Name" = "Salvador Henson"],
					        [#"Customer ID" = 9977, #"Customer Name" = "Donnie Mercado"],
					        [#"Customer ID" = 5814, #"Customer Name" = "Melvin Forbes"],
					        [#"Customer ID" = 7119, #"Customer Name" = "Scot Church"],
					        [#"Customer ID" = 6129, #"Customer Name" = "September Morin"],
					        [#"Customer ID" = 9120, #"Customer Name" = "Aldo Pennington"],
					        [#"Customer ID" = 5482, #"Customer Name" = "Carlos Mcfadden"],
					        [#"Customer ID" = 8410, #"Customer Name" = "Diego Reed"],
					        [#"Customer ID" = 5200, #"Customer Name" = "Gerard Gentry"],
					        [#"Customer ID" = 5499, #"Customer Name" = "Lou Shaw"],
					        [#"Customer ID" = 7361, #"Customer Name" = "Tora Mayo"],
					        [#"Customer ID" = 3997, #"Customer Name" = "Oralee Santos"],
					        [#"Customer ID" = 2184, #"Customer Name" = "Rosia Nixon"],
					        [#"Customer ID" = 4586, #"Customer Name" = "Vania Travis"],
					        [#"Customer ID" = 3463, #"Customer Name" = "Lavone Leon"],
					        [#"Customer ID" = 5958, #"Customer Name" = "Terrence Battle"],
					        [#"Customer ID" = 7782, #"Customer Name" = "Gail Petersen"],
					        [#"Customer ID" = 9764, #"Customer Name" = "Jerrell Wagner"],
					        [#"Customer ID" = 3909, #"Customer Name" = "Michael Burch"],
					        [#"Customer ID" = 4269, #"Customer Name" = "Johnie Bowen"],
					        [#"Customer ID" = 8629, #"Customer Name" = "Dorsey Berg"],
					        [#"Customer ID" = 6131, #"Customer Name" = "Tomika Munoz"],
					        [#"Customer ID" = 6449, #"Customer Name" = "Celena Clemons"],
					        [#"Customer ID" = 7773, #"Customer Name" = "Regenia Kim"],
					        [#"Customer ID" = 2906, #"Customer Name" = "Carmelia Ellison"],
					        [#"Customer ID" = 3263, #"Customer Name" = "Brice Bird"],
					        [#"Customer ID" = 4877, #"Customer Name" = "Manual Vincent"],
					        [#"Customer ID" = 7531, #"Customer Name" = "Nestor Pitts"],
					        [#"Customer ID" = 6813, #"Customer Name" = "Bebe Reynolds"],
					        [#"Customer ID" = 2357, #"Customer Name" = "Crista Cummings"],
					        [#"Customer ID" = 3375, #"Customer Name" = "Marielle Maynard"],
					        [#"Customer ID" = 5830, #"Customer Name" = "Christopher Butler"],
					        [#"Customer ID" = 7568, #"Customer Name" = "Jacki Robertson"],
					        [#"Customer ID" = 7021, #"Customer Name" = "Fritz Massey"],
					        [#"Customer ID" = 3296, #"Customer Name" = "Delsie Bradford"],
					        [#"Customer ID" = 1813, #"Customer Name" = "Gema Mcclain"],
					        [#"Customer ID" = 4454, #"Customer Name" = "Julius Houston"],
					        [#"Customer ID" = 4041, #"Customer Name" = "Jeanice Donovan"],
					        [#"Customer ID" = 3938, #"Customer Name" = "Sol Bryant"],
					        [#"Customer ID" = 1387, #"Customer Name" = "Torrie Guerra"],
					        [#"Customer ID" = 4962, #"Customer Name" = "Delta Sanchez"],
					        [#"Customer ID" = 2462, #"Customer Name" = "Maurice Ruiz"],
					        [#"Customer ID" = 8400, #"Customer Name" = "Columbus Bright"],
					        [#"Customer ID" = 4724, #"Customer Name" = "Ricky Mcbride"],
					        [#"Customer ID" = 6505, #"Customer Name" = "Chere Norman"],
					        [#"Customer ID" = 9894, #"Customer Name" = "Dinorah Short"],
					        [#"Customer ID" = 6775, #"Customer Name" = "Rodger Justice"],
					        [#"Customer ID" = 6820, #"Customer Name" = "Kelley Fulton"],
					        [#"Customer ID" = 6660, #"Customer Name" = "Sona Ryan"],
					        [#"Customer ID" = 9377, #"Customer Name" = "Latrisha Davenport"],
					        [#"Customer ID" = 1582, #"Customer Name" = "Madison Hopkins"],
					        [#"Customer ID" = 9362, #"Customer Name" = "Jose Wagner"],
					        [#"Customer ID" = 1377, #"Customer Name" = "Hang Cantrell"],
					        [#"Customer ID" = 1982, #"Customer Name" = "Ira Mathews"],
					        [#"Customer ID" = 5160, #"Customer Name" = "Lloyd Knight"],
					        [#"Customer ID" = 1247, #"Customer Name" = "Byron Hutchinson"],
					        [#"Customer ID" = 9900, #"Customer Name" = "Emil Glover"],
					        [#"Customer ID" = 4329, #"Customer Name" = "Milton Waller"],
					        [#"Customer ID" = 7070, #"Customer Name" = "Kelly Copeland"],
					        [#"Customer ID" = 5828, #"Customer Name" = "Thaddeus Gallagher"],
					        [#"Customer ID" = 5547, #"Customer Name" = "Yulanda Atkins"],
					        [#"Customer ID" = 7172, #"Customer Name" = "Graig Stone"],
					        [#"Customer ID" = 6187, #"Customer Name" = "Eveline Massey"],
					        [#"Customer ID" = 4423, #"Customer Name" = "Jason David"],
					        [#"Customer ID" = 8791, #"Customer Name" = "Lesley Moran"],
					        [#"Customer ID" = 8528, #"Customer Name" = "Jamee Kinney"],
					        [#"Customer ID" = 7049, #"Customer Name" = "Laverna Bishop"],
					        [#"Customer ID" = 9690, #"Customer Name" = "Jackie Ingram"],
					        [#"Customer ID" = 9446, #"Customer Name" = "Robena Osborne"],
					        [#"Customer ID" = 3135, #"Customer Name" = "Emerson Valdez"],
					        [#"Customer ID" = 4468, #"Customer Name" = "Patrick Horne"],
					        [#"Customer ID" = 3611, #"Customer Name" = "Kory Petty"],
					        [#"Customer ID" = 6026, #"Customer Name" = "Shalon Gates"],
					        [#"Customer ID" = 2404, #"Customer Name" = "Kareem Nielsen"],
					        [#"Customer ID" = 7065, #"Customer Name" = "Brandon Gibson"],
					        [#"Customer ID" = 6441, #"Customer Name" = "Elvis Kirby"],
					        [#"Customer ID" = 9927, #"Customer Name" = "Octavio Hood"],
					        [#"Customer ID" = 6963, #"Customer Name" = "Taren Douglas"],
					        [#"Customer ID" = 4758, #"Customer Name" = "Natisha Foster"],
					        [#"Customer ID" = 2618, #"Customer Name" = "Silvana Wiley"],
					        [#"Customer ID" = 4895, #"Customer Name" = "Hal Mccall"],
					        [#"Customer ID" = 2319, #"Customer Name" = "Ezequiel Brennan"],
					        [#"Customer ID" = 1056, #"Customer Name" = "Verlie Koch"],
					        [#"Customer ID" = 3911, #"Customer Name" = "Emmitt Gaines"],
					        [#"Customer ID" = 8977, #"Customer Name" = "Marcelo Christensen"],
					        [#"Customer ID" = 4054, #"Customer Name" = "Kenton Raymond"],
					        [#"Customer ID" = 5234, #"Customer Name" = "Augustus Irwin"],
					        [#"Customer ID" = 1297, #"Customer Name" = "Joesph Carr"],
					        [#"Customer ID" = 6109, #"Customer Name" = "Sharyl Bowers"],
					        [#"Customer ID" = 3422, #"Customer Name" = "Travis Ford"],
					        [#"Customer ID" = 5059, #"Customer Name" = "Christopher Hopper"],
					        [#"Customer ID" = 3752, #"Customer Name" = "Bud Mcdowell"],
					        [#"Customer ID" = 3849, #"Customer Name" = "Neta Holcomb"],
					        [#"Customer ID" = 1321, #"Customer Name" = "Milford Jacobson"],
					        [#"Customer ID" = 2004, #"Customer Name" = "Stevie Hodge"],
					        [#"Customer ID" = 3524, #"Customer Name" = "Refugio Wade"],
					        [#"Customer ID" = 1915, #"Customer Name" = "Coy Wagner"],
					        [#"Customer ID" = 9627, #"Customer Name" = "Tomas Madden"],
					        [#"Customer ID" = 6294, #"Customer Name" = "Everett Downs"],
					        [#"Customer ID" = 1321, #"Customer Name" = "Roosevelt Tyson"],
					        [#"Customer ID" = 7708, #"Customer Name" = "Venice Cox"],
					        [#"Customer ID" = 6215, #"Customer Name" = "Galen Flowers"],
					        [#"Customer ID" = 2672, #"Customer Name" = "Lashaun Dennis"],
					        [#"Customer ID" = 5271, #"Customer Name" = "Alvaro Mason"],
					        [#"Customer ID" = 4109, #"Customer Name" = "Lekisha Daniels"],
					        [#"Customer ID" = 6360, #"Customer Name" = "Nenita Cline"],
					        [#"Customer ID" = 3317, #"Customer Name" = "Orlando Rose"],
					        [#"Customer ID" = 5223, #"Customer Name" = "Philip Riddle"],
					        [#"Customer ID" = 1796, #"Customer Name" = "Jason Donovan"],
					        [#"Customer ID" = 4442, #"Customer Name" = "Fausto Simpson"],
					        [#"Customer ID" = 3906, #"Customer Name" = "Elane Mckay"],
					        [#"Customer ID" = 2414, #"Customer Name" = "Hung Conley"],
					        [#"Customer ID" = 8245, #"Customer Name" = "Bryce Middleton"],
					        [#"Customer ID" = 8352, #"Customer Name" = "Suzann Arnold"],
					        [#"Customer ID" = 2377, #"Customer Name" = "Zetta O'neill"],
					        [#"Customer ID" = 5406, #"Customer Name" = "Hoyt Hobbs"],
					        [#"Customer ID" = 8398, #"Customer Name" = "Boyce Schneider"],
					        [#"Customer ID" = 8920, #"Customer Name" = "Ivan Burnett"],
					        [#"Customer ID" = 6331, #"Customer Name" = "Dahlia Walter"],
					        [#"Customer ID" = 8141, #"Customer Name" = "Marcel Baldwin"],
					        [#"Customer ID" = 8451, #"Customer Name" = "Bob Peterson"],
					        [#"Customer ID" = 6138, #"Customer Name" = "Danyell Hines"],
					        [#"Customer ID" = 6737, #"Customer Name" = "Kathline Stanley"],
					        [#"Customer ID" = 4943, #"Customer Name" = "Lizeth Alvarez"],
					        [#"Customer ID" = 5538, #"Customer Name" = "Jaye Mcknight"],
					        [#"Customer ID" = 7654, #"Customer Name" = "Dulcie Ramsey"],
					        [#"Customer ID" = 9210, #"Customer Name" = "Wiley Owens"],
					        [#"Customer ID" = 9097, #"Customer Name" = "Mendy Mcpherson"],
					        [#"Customer ID" = 9992, #"Customer Name" = "Dorthey O'neal"],
					        [#"Customer ID" = 2197, #"Customer Name" = "Chung Monroe"],
					        [#"Customer ID" = 8003, #"Customer Name" = "Jordon Zimmerman"],
					        [#"Customer ID" = 4179, #"Customer Name" = "Meri Medina"],
					        [#"Customer ID" = 2126, #"Customer Name" = "Chuck Nixon"],
					        [#"Customer ID" = 6203, #"Customer Name" = "Dee Berry"],
					        [#"Customer ID" = 7808, #"Customer Name" = "Heide Swanson"],
					        [#"Customer ID" = 8644, #"Customer Name" = "Irwin Moody"],
					        [#"Customer ID" = 7947, #"Customer Name" = "Jacquelynn Wolfe"],
					        [#"Customer ID" = 9074, #"Customer Name" = "Harmony Henry"],
					        [#"Customer ID" = 6102, #"Customer Name" = "Alise Torres"],
					        [#"Customer ID" = 4575, #"Customer Name" = "Carl Blackburn"],
					        [#"Customer ID" = 9836, #"Customer Name" = "Talisha Bright"],
					        [#"Customer ID" = 5207, #"Customer Name" = "Theresia Nelson"],
					        [#"Customer ID" = 7625, #"Customer Name" = "Tyler Day"],
					        [#"Customer ID" = 3752, #"Customer Name" = "Bud Jenkins"],
					        [#"Customer ID" = 1038, #"Customer Name" = "Shella Murphy"],
					        [#"Customer ID" = 1957, #"Customer Name" = "Elizabet Mcintyre"],
					        [#"Customer ID" = 2927, #"Customer Name" = "Jarred Johnson"],
					        [#"Customer ID" = 9681, #"Customer Name" = "Nelia Mejia"],
					        [#"Customer ID" = 8994, #"Customer Name" = "Kermit Mason"],
					        [#"Customer ID" = 5831, #"Customer Name" = "Akiko Oliver"],
					        [#"Customer ID" = 3564, #"Customer Name" = "Chery Nicholson"],
					        [#"Customer ID" = 4616, #"Customer Name" = "Irvin Griffin"],
					        [#"Customer ID" = 1694, #"Customer Name" = "Johna Griffin"],
					        [#"Customer ID" = 2934, #"Customer Name" = "Donald Guzman"],
					        [#"Customer ID" = 7330, #"Customer Name" = "Earnest Nichols"],
					        [#"Customer ID" = 8083, #"Customer Name" = "Adolfo Delaney"],
					        [#"Customer ID" = 3318, #"Customer Name" = "Kera Foley"],
					        [#"Customer ID" = 7373, #"Customer Name" = "Roman Clayton"],
					        [#"Customer ID" = 8457, #"Customer Name" = "Danilo Collier"],
					        [#"Customer ID" = 6870, #"Customer Name" = "Andrea Burke"],
					        [#"Customer ID" = 8845, #"Customer Name" = "Weldon Weiss"],
					        [#"Customer ID" = 4569, #"Customer Name" = "Tanner Christensen"],
					        [#"Customer ID" = 4433, #"Customer Name" = "Lavelle Brock"],
					        [#"Customer ID" = 5288, #"Customer Name" = "Owen Martinez"],
					        [#"Customer ID" = 9933, #"Customer Name" = "Brooks Eaton"],
					        [#"Customer ID" = 2579, #"Customer Name" = "Sol Vang"],
					        [#"Customer ID" = 2978, #"Customer Name" = "Janean Howard"],
					        [#"Customer ID" = 2534, #"Customer Name" = "Trey Rojas"],
					        [#"Customer ID" = 6278, #"Customer Name" = "Jaime Lara"],
					        [#"Customer ID" = 6148, #"Customer Name" = "Jenette Henry"],
					        [#"Customer ID" = 4346, #"Customer Name" = "Max Freeman"],
					        [#"Customer ID" = 1623, #"Customer Name" = "Gilberto Kim"],
					        [#"Customer ID" = 4381, #"Customer Name" = "Darrick Reynolds"],
					        [#"Customer ID" = 8464, #"Customer Name" = "Brittaney Velez"],
					        [#"Customer ID" = 1607, #"Customer Name" = "Keli Delacruz"],
					        [#"Customer ID" = 2018, #"Customer Name" = "Irwin Mayo"],
					        [#"Customer ID" = 3368, #"Customer Name" = "Berenice Blackwell"],
					        [#"Customer ID" = 9271, #"Customer Name" = "Winston Battle"],
					        [#"Customer ID" = 4690, #"Customer Name" = "Gabriel Rodriquez"],
					        [#"Customer ID" = 3532, #"Customer Name" = "Marlon English"],
					        [#"Customer ID" = 1295, #"Customer Name" = "Shala Reynolds"],
					        [#"Customer ID" = 4649, #"Customer Name" = "Amee Spears"],
					        [#"Customer ID" = 9415, #"Customer Name" = "Moon Newton"],
					        [#"Customer ID" = 6290, #"Customer Name" = "Irving Conrad"],
					        [#"Customer ID" = 1004, #"Customer Name" = "Dan Barrett"],
					        [#"Customer ID" = 8459, #"Customer Name" = "Mario Velez"],
					        [#"Customer ID" = 6617, #"Customer Name" = "Anthony Trevino"],
					        [#"Customer ID" = 4988, #"Customer Name" = "Chan Valenzuela"],
					        [#"Customer ID" = 7923, #"Customer Name" = "Roman Keith"],
					        [#"Customer ID" = 9949, #"Customer Name" = "Rickey Coleman"],
					        [#"Customer ID" = 2788, #"Customer Name" = "Gidget Nieves"],
					        [#"Customer ID" = 5577, #"Customer Name" = "Nick Gould"],
					        [#"Customer ID" = 1022, #"Customer Name" = "Maxwell Wallace"],
					        [#"Customer ID" = 2495, #"Customer Name" = "Shea Durham"],
					        [#"Customer ID" = 4023, #"Customer Name" = "Monet Mcdowell"],
					        [#"Customer ID" = 4897, #"Customer Name" = "Makeda Riley"],
					        [#"Customer ID" = 9030, #"Customer Name" = "Homer Hammond"],
					        [#"Customer ID" = 4064, #"Customer Name" = "Ara Dominguez"],
					        [#"Customer ID" = 4197, #"Customer Name" = "Gerry Morrow"],
					        [#"Customer ID" = 2776, #"Customer Name" = "Ray Middleton"],
					        [#"Customer ID" = 5683, #"Customer Name" = "Seymour Castaneda"],
					        [#"Customer ID" = 2787, #"Customer Name" = "Horace Wood"],
					        [#"Customer ID" = 4513, #"Customer Name" = "Leonardo Winters"],
					        [#"Customer ID" = 7056, #"Customer Name" = "Margrett Macias"],
					        [#"Customer ID" = 1687, #"Customer Name" = "Julius Booker"],
					        [#"Customer ID" = 7055, #"Customer Name" = "Valentin Santana"],
					        [#"Customer ID" = 3825, #"Customer Name" = "Corey Martin"],
					        [#"Customer ID" = 3193, #"Customer Name" = "Buena Preston"],
					        [#"Customer ID" = 5382, #"Customer Name" = "Vania Harmon"],
					        [#"Customer ID" = 5608, #"Customer Name" = "Dirk Stein"],
					        [#"Customer ID" = 4833, #"Customer Name" = "Douglass Meadows"],
					        [#"Customer ID" = 7784, #"Customer Name" = "Sima Mclaughlin"],
					        [#"Customer ID" = 2298, #"Customer Name" = "Jerold Copeland"],
					        [#"Customer ID" = 2763, #"Customer Name" = "Buck Wooten"],
					        [#"Customer ID" = 9257, #"Customer Name" = "Neda Hogan"],
					        [#"Customer ID" = 7427, #"Customer Name" = "Gianna Malone"],
					        [#"Customer ID" = 7197, #"Customer Name" = "Freddy Downs"],
					        [#"Customer ID" = 4822, #"Customer Name" = "Gwenn Ware"],
					        [#"Customer ID" = 4352, #"Customer Name" = "Jolyn Gray"],
					        [#"Customer ID" = 6193, #"Customer Name" = "Jamie Tyson"],
					        [#"Customer ID" = 2640, #"Customer Name" = "Jacob Ford"],
					        [#"Customer ID" = 7732, #"Customer Name" = "Minh Moore"],
					        [#"Customer ID" = 8269, #"Customer Name" = "Edwin Lamb"],
					        [#"Customer ID" = 2290, #"Customer Name" = "Quinn Potts"],
					        [#"Customer ID" = 2734, #"Customer Name" = "Joaquina Randolph"],
					        [#"Customer ID" = 4936, #"Customer Name" = "Delaine Sykes"],
					        [#"Customer ID" = 9020, #"Customer Name" = "Jeremiah Skinner"],
					        [#"Customer ID" = 6536, #"Customer Name" = "Nancey Williams"],
					        [#"Customer ID" = 7756, #"Customer Name" = "Wilber Singleton"],
					        [#"Customer ID" = 7273, #"Customer Name" = "Ming Brennan"],
					        [#"Customer ID" = 5169, #"Customer Name" = "Gilberto Tyson"],
					        [#"Customer ID" = 6881, #"Customer Name" = "Xiao Harvey"],
					        [#"Customer ID" = 4900, #"Customer Name" = "Trent Albert"],
					        [#"Customer ID" = 7419, #"Customer Name" = "Agustin Aguirre"],
					        [#"Customer ID" = 3069, #"Customer Name" = "Dino Robbins"],
					        [#"Customer ID" = 8834, #"Customer Name" = "Shirely Mason"],
					        [#"Customer ID" = 2760, #"Customer Name" = "Shawnna Carter"],
					        [#"Customer ID" = 3317, #"Customer Name" = "Edward Benton"],
					        [#"Customer ID" = 7294, #"Customer Name" = "Kati Brock"],
					        [#"Customer ID" = 2022, #"Customer Name" = "Douglas Wooten"],
					        [#"Customer ID" = 3542, #"Customer Name" = "Ken Mcdaniel"],
					        [#"Customer ID" = 8265, #"Customer Name" = "Jorge Rivas"],
					        [#"Customer ID" = 1035, #"Customer Name" = "Courtney Kaufman"],
					        [#"Customer ID" = 5722, #"Customer Name" = "Logan Santana"],
					        [#"Customer ID" = 1022, #"Customer Name" = "Paris Terry"],
					        [#"Customer ID" = 7808, #"Customer Name" = "Laurena Nunez"],
					        [#"Customer ID" = 4747, #"Customer Name" = "Ulysses Wilson"],
					        [#"Customer ID" = 7170, #"Customer Name" = "Merna Pierce"],
					        [#"Customer ID" = 6047, #"Customer Name" = "Chester Vance"],
					        [#"Customer ID" = 4631, #"Customer Name" = "Joeann Boyle"],
					        [#"Customer ID" = 7307, #"Customer Name" = "Elayne Harding"],
					        [#"Customer ID" = 1060, #"Customer Name" = "Linsey Dudley"],
					        [#"Customer ID" = 4117, #"Customer Name" = "Berry Grimes"],
					        [#"Customer ID" = 2290, #"Customer Name" = "Shea Gregory"],
					        [#"Customer ID" = 9052, #"Customer Name" = "Keesha Lane"],
					        [#"Customer ID" = 3942, #"Customer Name" = "Emmanuel Summers"],
					        [#"Customer ID" = 8196, #"Customer Name" = "Mui Mccarthy"],
					        [#"Customer ID" = 5411, #"Customer Name" = "Un Bright"],
					        [#"Customer ID" = 4249, #"Customer Name" = "Mandie Howe"],
					        [#"Customer ID" = 4194, #"Customer Name" = "Ruthanne Carey"],
					        [#"Customer ID" = 5737, #"Customer Name" = "Wenona Richardson"],
					        [#"Customer ID" = 8506, #"Customer Name" = "David Keith"],
					        [#"Customer ID" = 5947, #"Customer Name" = "Hobert Goodwin"],
					        [#"Customer ID" = 2591, #"Customer Name" = "Darron Nolan"],
					        [#"Customer ID" = 3110, #"Customer Name" = "Felisa Albert"],
					        [#"Customer ID" = 1488, #"Customer Name" = "Jesse Hebert"],
					        [#"Customer ID" = 3067, #"Customer Name" = "Lupe Leach"],
					        [#"Customer ID" = 7035, #"Customer Name" = "Herman Jones"],
					        [#"Customer ID" = 1074, #"Customer Name" = "Raisa Juarez"],
					        [#"Customer ID" = 2764, #"Customer Name" = "Fernando Mccormick"],
					        [#"Customer ID" = 7143, #"Customer Name" = "Allen Mercado"],
					        [#"Customer ID" = 6013, #"Customer Name" = "Keith Walsh"],
					        [#"Customer ID" = 4103, #"Customer Name" = "Lory Rowe"],
					        [#"Customer ID" = 9600, #"Customer Name" = "Edmundo Bowers"],
					        [#"Customer ID" = 6032, #"Customer Name" = "Desire Clayton"],
					        [#"Customer ID" = 8918, #"Customer Name" = "Clarisa Spears"],
					        [#"Customer ID" = 6989, #"Customer Name" = "Zachery Adkins"],
					        [#"Customer ID" = 7979, #"Customer Name" = "Bob Fitzpatrick"],
					        [#"Customer ID" = 3616, #"Customer Name" = "Luciano Forbes"],
					        [#"Customer ID" = 7006, #"Customer Name" = "Edmundo Mccray"],
					        [#"Customer ID" = 9031, #"Customer Name" = "Toshia Wade"],
					        [#"Customer ID" = 6090, #"Customer Name" = "Joesph Kirk"],
					        [#"Customer ID" = 7927, #"Customer Name" = "Tyrell Allison"],
					        [#"Customer ID" = 8820, #"Customer Name" = "Kali Mcgowan"],
					        [#"Customer ID" = 1806, #"Customer Name" = "Ulrike Slater"],
					        [#"Customer ID" = 7578, #"Customer Name" = "Hobert Lewis"],
					        [#"Customer ID" = 9097, #"Customer Name" = "Lorette Roberts"],
					        [#"Customer ID" = 7446, #"Customer Name" = "Demetrius Hubbard"],
					        [#"Customer ID" = 8659, #"Customer Name" = "Shanel Franco"],
					        [#"Customer ID" = 8543, #"Customer Name" = "Dalton Delaney"],
					        [#"Customer ID" = 8697, #"Customer Name" = "Donnell Alexander"],
					        [#"Customer ID" = 1009, #"Customer Name" = "Rickey Rich"],
					        [#"Customer ID" = 7323, #"Customer Name" = "Tequila Lowe"],
					        [#"Customer ID" = 6568, #"Customer Name" = "Lean Bauer"],
					        [#"Customer ID" = 5425, #"Customer Name" = "Elroy Sweeney"],
					        [#"Customer ID" = 9634, #"Customer Name" = "Jerold Merrill"],
					        [#"Customer ID" = 8607, #"Customer Name" = "Brenton Bates"],
					        [#"Customer ID" = 2334, #"Customer Name" = "Marlin Roach"],
					        [#"Customer ID" = 7686, #"Customer Name" = "Glen Ferguson"],
					        [#"Customer ID" = 8117, #"Customer Name" = "Dimple Kerr"],
					        [#"Customer ID" = 2797, #"Customer Name" = "Diego Finley"],
					        [#"Customer ID" = 5709, #"Customer Name" = "Kiesha Burch"],
					        [#"Customer ID" = 6885, #"Customer Name" = "Dede Berger"],
					        [#"Customer ID" = 9332, #"Customer Name" = "Seth Buckner"],
					        [#"Customer ID" = 9089, #"Customer Name" = "Candyce Dennis"],
					        [#"Customer ID" = 2357, #"Customer Name" = "Darell Cole"],
					        [#"Customer ID" = 3485, #"Customer Name" = "Torie Klein"],
					        [#"Customer ID" = 4237, #"Customer Name" = "Drusilla Lucas"],
					        [#"Customer ID" = 8309, #"Customer Name" = "Manual Walton"],
					        [#"Customer ID" = 8524, #"Customer Name" = "Maddie Whitley"],
					        [#"Customer ID" = 9849, #"Customer Name" = "Gerald Bryant"],
					        [#"Customer ID" = 9000, #"Customer Name" = "Scott Wilcox"],
					        [#"Customer ID" = 6766, #"Customer Name" = "Marcus Koch"],
					        [#"Customer ID" = 7563, #"Customer Name" = "Carol Langley"],
					        [#"Customer ID" = 5624, #"Customer Name" = "Nikia Hyde"],
					        [#"Customer ID" = 2524, #"Customer Name" = "Darren Roach"],
					        [#"Customer ID" = 9588, #"Customer Name" = "Madalyn Wiley"],
					        [#"Customer ID" = 4041, #"Customer Name" = "Drew Farley"],
					        [#"Customer ID" = 6597, #"Customer Name" = "Adrian Marquez"],
					        [#"Customer ID" = 7473, #"Customer Name" = "Lonna Bradshaw"],
					        [#"Customer ID" = 2685, #"Customer Name" = "Gudrun Riggs"],
					        [#"Customer ID" = 9273, #"Customer Name" = "Clifford Weiss"],
					        [#"Customer ID" = 8083, #"Customer Name" = "Antione Vance"],
					        [#"Customer ID" = 9192, #"Customer Name" = "Jonathan William"],
					        [#"Customer ID" = 1401, #"Customer Name" = "Buffy Shields"],
					        [#"Customer ID" = 7151, #"Customer Name" = "Tarah Cummings"],
					        [#"Customer ID" = 5839, #"Customer Name" = "Rebbeca Baker"],
					        [#"Customer ID" = 3437, #"Customer Name" = "Ivan Norris"],
					        [#"Customer ID" = 6297, #"Customer Name" = "Lakita Miles"],
					        [#"Customer ID" = 2330, #"Customer Name" = "Mitchell Decker"],
					        [#"Customer ID" = 3653, #"Customer Name" = "Waylon Grimes"],
					        [#"Customer ID" = 4474, #"Customer Name" = "Frederic Clayton"],
					        [#"Customer ID" = 8990, #"Customer Name" = "Raymonde Watts"],
					        [#"Customer ID" = 6980, #"Customer Name" = "Erasmo Gross"],
					        [#"Customer ID" = 7942, #"Customer Name" = "Nisha Booker"],
					        [#"Customer ID" = 7456, #"Customer Name" = "Mendy Curtis"],
					        [#"Customer ID" = 5251, #"Customer Name" = "Robt Pearson"],
					        [#"Customer ID" = 7833, #"Customer Name" = "Santiago Bradley"],
					        [#"Customer ID" = 8006, #"Customer Name" = "Mercedez Dalton"],
					        [#"Customer ID" = 2543, #"Customer Name" = "Alex Lawson"],
					        [#"Customer ID" = 3693, #"Customer Name" = "King Pacheco"],
					        [#"Customer ID" = 1502, #"Customer Name" = "Raina Crosby"],
					        [#"Customer ID" = 8771, #"Customer Name" = "Morris Stevenson"],
					        [#"Customer ID" = 5099, #"Customer Name" = "Devora Park"],
					        [#"Customer ID" = 8653, #"Customer Name" = "Josef Walls"],
					        [#"Customer ID" = 2745, #"Customer Name" = "Karena Nunez"],
					        [#"Customer ID" = 2709, #"Customer Name" = "Neal Barker"],
					        [#"Customer ID" = 5295, #"Customer Name" = "Eveline Craft"],
					        [#"Customer ID" = 3263, #"Customer Name" = "Becki Lang"],
					        [#"Customer ID" = 5703, #"Customer Name" = "Tiny Newman"],
					        [#"Customer ID" = 2992, #"Customer Name" = "Alton Willis"],
					        [#"Customer ID" = 8811, #"Customer Name" = "Ethan Mitchell"],
					        [#"Customer ID" = 8412, #"Customer Name" = "Nathan Terry"],
					        [#"Customer ID" = 1572, #"Customer Name" = "Shanel Sellers"],
					        [#"Customer ID" = 9644, #"Customer Name" = "Kiesha Poole"],
					        [#"Customer ID" = 2805, #"Customer Name" = "Margene Hull"],
					        [#"Customer ID" = 3490, #"Customer Name" = "Danille Ramos"],
					        [#"Customer ID" = 9537, #"Customer Name" = "Rickie Beach"],
					        [#"Customer ID" = 7785, #"Customer Name" = "Daniele Whitfield"],
					        [#"Customer ID" = 7635, #"Customer Name" = "Winston Reid"],
					        [#"Customer ID" = 8377, #"Customer Name" = "Johnson Day"],
					        [#"Customer ID" = 3822, #"Customer Name" = "Armando Miles"],
					        [#"Customer ID" = 3395, #"Customer Name" = "Reynaldo Kidd"],
					        [#"Customer ID" = 2441, #"Customer Name" = "Cory Padilla"],
					        [#"Customer ID" = 4709, #"Customer Name" = "Nga Gregory"],
					        [#"Customer ID" = 4579, #"Customer Name" = "Yen Whitney"],
					        [#"Customer ID" = 3154, #"Customer Name" = "Karey Ray"],
					        [#"Customer ID" = 7990, #"Customer Name" = "Magen Peck"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Customer ID", type text},
					        {"Customer Name", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table