table Query1
	lineageTag: c122e50e-d9cc-4226-afe7-e7e9c1bfc29f

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 8a4d8f59-a0d8-457b-89a6-7b6481419283
		summarizeBy: sum
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 9e225ae7-b82e-4e9b-a7f8-68aaa7f9695d
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Salary
		dataType: int64
		formatString: 0
		lineageTag: 84aa6468-35d7-444c-923e-8c03c647491e
		summarizeBy: sum
		sourceColumn: Salary

		annotation SummarizationSetBy = Automatic

	partition Query1 = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"ID" = 4661, #"Name" = "Eusebio Macdonald", #"Salary" = 509],
					        [#"ID" = 1311, #"Name" = "Clay Best", #"Salary" = 42],
					        [#"ID" = 2352, #"Name" = "Grover Atkins", #"Salary" = 327],
					        [#"ID" = 7142, #"Name" = "Christian Parker", #"Salary" = 70],
					        [#"ID" = 7661, #"Name" = "Hyman Dillard", #"Salary" = 485]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"ID", Int64.Type},
					        {"Name", type text},
					        {"Salary", Int64.Type}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table