table 'People_Orders+ (Sample - Superstore)'
	lineageTag: 84d7e7f4-2e40-4423-bbf1-0bfdd635cce4

	column Person
		dataType: string
		lineageTag: f78c72f7-b8fd-45c5-8b94-ebb27103c9b7
		summarizeBy: none
		sourceColumn: Person

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 32984792-0555-4079-a514-d52cb300fb07
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition 'People_Orders+ (Sample - Superstore)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Person" = "scholarship", #"Region" = "Connecticut"],
					        [#"Person" = "usage", #"Region" = "Montana"],
					        [#"Person" = "funny", #"Region" = "New Jersey"],
					        [#"Person" = "maintaining", #"Region" = "Rhode Island"],
					        [#"Person" = "ef", #"Region" = "Iowa"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Person", type text},
					        {"Region", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table