table 'Returns_Orders+ (Sample - Superstore)'
	lineageTag: fc7874c2-6e1b-44f5-a276-0929c24bb916

	column Returned
		dataType: string
		lineageTag: fd8d7dcd-cd53-4a93-867c-8e0ad367f0b9
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 9d825589-bceb-40fa-9a09-42bd4504560a
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	partition 'Returns_Orders+ (Sample - Superstore)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Returned" = "strong", #"Order ID" = 7551],
					        [#"Returned" = "supporting", #"Order ID" = 4513],
					        [#"Returned" = "indicators", #"Order ID" = 7206],
					        [#"Returned" = "skill", #"Order ID" = 8535],
					        [#"Returned" = "encouraged", #"Order ID" = 1813]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Returned", type text},
					        {"Order ID", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table