table 'Nutrition Summary+ (Multiple Connections)_Measurement (Kg)'
	lineageTag: 153b89c7-6ebc-46d5-9c9a-87fc0ff9235b

	column Date
		dataType: datetime
		lineageTag: 2d7e68e0-5618-4ff4-968d-6b48dd1fd3a2
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: dc91a8b6-d9e8-4ffd-8c01-0fdd295f16f8
			defaultHierarchy: LocalDateTable_f74fcad1-8680-4059-9bb2-f86dc3098dd6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Weight
		dataType: double
		formatString: General Number
		lineageTag: b148514a-1b15-4428-a934-bc06f1310ad9
		summarizeBy: sum
		sourceColumn: Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Nutrition Summary+ (Multiple Connections)_Measurement (Kg)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Date" = #date(2022, 12, 21), #"Weight" = 28.03],
					        [#"Date" = #date(2022, 12, 28), #"Weight" = 383.38],
					        [#"Date" = #date(2023, 5, 23), #"Weight" = 701.24],
					        [#"Date" = #date(2024, 5, 31), #"Weight" = 95.48],
					        [#"Date" = #date(2024, 1, 7), #"Weight" = 212.58],
					        [#"Date" = #date(2024, 9, 18), #"Weight" = 676.44],
					        [#"Date" = #date(2020, 1, 19), #"Weight" = 248.4],
					        [#"Date" = #date(2023, 2, 5), #"Weight" = 750.83],
					        [#"Date" = #date(2023, 11, 24), #"Weight" = 411.31],
					        [#"Date" = #date(2021, 9, 1), #"Weight" = 413.41],
					        [#"Date" = #date(2024, 4, 3), #"Weight" = 343.81],
					        [#"Date" = #date(2020, 1, 7), #"Weight" = 949.02],
					        [#"Date" = #date(2023, 10, 16), #"Weight" = 948.83],
					        [#"Date" = #date(2020, 4, 15), #"Weight" = 345.14],
					        [#"Date" = #date(2024, 5, 24), #"Weight" = 611.11],
					        [#"Date" = #date(2024, 5, 14), #"Weight" = 284.82],
					        [#"Date" = #date(2021, 6, 22), #"Weight" = 623.46],
					        [#"Date" = #date(2020, 6, 4), #"Weight" = 725.88],
					        [#"Date" = #date(2022, 3, 30), #"Weight" = 477.65],
					        [#"Date" = #date(2020, 12, 22), #"Weight" = 236.31],
					        [#"Date" = #date(2023, 12, 8), #"Weight" = 680.46],
					        [#"Date" = #date(2022, 5, 29), #"Weight" = 769.06],
					        [#"Date" = #date(2022, 2, 25), #"Weight" = 120.54],
					        [#"Date" = #date(2024, 5, 22), #"Weight" = 477.97],
					        [#"Date" = #date(2021, 6, 10), #"Weight" = 348.74],
					        [#"Date" = #date(2024, 10, 5), #"Weight" = 731.49],
					        [#"Date" = #date(2022, 10, 10), #"Weight" = 455.53],
					        [#"Date" = #date(2020, 3, 24), #"Weight" = 873.54],
					        [#"Date" = #date(2024, 8, 5), #"Weight" = 845.72],
					        [#"Date" = #date(2023, 2, 12), #"Weight" = 59.98],
					        [#"Date" = #date(2024, 3, 23), #"Weight" = 312.21],
					        [#"Date" = #date(2021, 9, 13), #"Weight" = 328.01],
					        [#"Date" = #date(2022, 10, 21), #"Weight" = 689.54],
					        [#"Date" = #date(2023, 9, 2), #"Weight" = 817.64],
					        [#"Date" = #date(2023, 7, 18), #"Weight" = 360.3],
					        [#"Date" = #date(2020, 2, 20), #"Weight" = 972.17],
					        [#"Date" = #date(2020, 11, 2), #"Weight" = 760.94],
					        [#"Date" = #date(2023, 5, 1), #"Weight" = 578.19],
					        [#"Date" = #date(2024, 12, 22), #"Weight" = 437.43],
					        [#"Date" = #date(2024, 5, 13), #"Weight" = 393.55],
					        [#"Date" = #date(2021, 12, 18), #"Weight" = 59.77],
					        [#"Date" = #date(2024, 11, 3), #"Weight" = 398.61],
					        [#"Date" = #date(2023, 10, 16), #"Weight" = 947.79],
					        [#"Date" = #date(2023, 12, 21), #"Weight" = 858.99],
					        [#"Date" = #date(2022, 10, 5), #"Weight" = 632.78],
					        [#"Date" = #date(2021, 11, 6), #"Weight" = 241.53],
					        [#"Date" = #date(2024, 12, 23), #"Weight" = 395.84],
					        [#"Date" = #date(2023, 6, 23), #"Weight" = 778.1],
					        [#"Date" = #date(2024, 5, 11), #"Weight" = 757.29],
					        [#"Date" = #date(2022, 9, 5), #"Weight" = 591.57],
					        [#"Date" = #date(2022, 11, 26), #"Weight" = 195.21],
					        [#"Date" = #date(2023, 6, 12), #"Weight" = 888.09],
					        [#"Date" = #date(2023, 10, 1), #"Weight" = 779.66],
					        [#"Date" = #date(2024, 9, 1), #"Weight" = 275.98],
					        [#"Date" = #date(2020, 2, 4), #"Weight" = 881.78],
					        [#"Date" = #date(2024, 5, 9), #"Weight" = 971.28],
					        [#"Date" = #date(2024, 11, 13), #"Weight" = 553.21],
					        [#"Date" = #date(2020, 2, 12), #"Weight" = 413.68],
					        [#"Date" = #date(2024, 2, 25), #"Weight" = 343.37],
					        [#"Date" = #date(2020, 5, 21), #"Weight" = 357.89],
					        [#"Date" = #date(2021, 6, 19), #"Weight" = 843.32],
					        [#"Date" = #date(2022, 11, 2), #"Weight" = 701.1],
					        [#"Date" = #date(2023, 11, 23), #"Weight" = 740.39],
					        [#"Date" = #date(2023, 11, 22), #"Weight" = 246.79],
					        [#"Date" = #date(2022, 8, 16), #"Weight" = 453.57],
					        [#"Date" = #date(2024, 11, 22), #"Weight" = 460.57],
					        [#"Date" = #date(2024, 9, 16), #"Weight" = 338.62],
					        [#"Date" = #date(2022, 7, 21), #"Weight" = 69.41],
					        [#"Date" = #date(2022, 7, 5), #"Weight" = 895.24],
					        [#"Date" = #date(2020, 6, 3), #"Weight" = 468.18],
					        [#"Date" = #date(2023, 1, 12), #"Weight" = 234.46],
					        [#"Date" = #date(2023, 5, 9), #"Weight" = 281.57],
					        [#"Date" = #date(2022, 7, 10), #"Weight" = 508.89],
					        [#"Date" = #date(2024, 11, 13), #"Weight" = 344.15],
					        [#"Date" = #date(2023, 12, 14), #"Weight" = 471.34],
					        [#"Date" = #date(2024, 9, 21), #"Weight" = 572.1],
					        [#"Date" = #date(2021, 3, 7), #"Weight" = 910.33],
					        [#"Date" = #date(2021, 11, 25), #"Weight" = 281.23],
					        [#"Date" = #date(2024, 3, 14), #"Weight" = 204.55],
					        [#"Date" = #date(2021, 9, 22), #"Weight" = 941.89],
					        [#"Date" = #date(2020, 3, 31), #"Weight" = 5.39],
					        [#"Date" = #date(2024, 6, 11), #"Weight" = 198.5],
					        [#"Date" = #date(2024, 2, 5), #"Weight" = 266.69],
					        [#"Date" = #date(2023, 4, 19), #"Weight" = 599.85],
					        [#"Date" = #date(2020, 12, 30), #"Weight" = 196.79],
					        [#"Date" = #date(2023, 12, 23), #"Weight" = 923.34],
					        [#"Date" = #date(2024, 9, 20), #"Weight" = 222.64],
					        [#"Date" = #date(2021, 7, 30), #"Weight" = 175.15],
					        [#"Date" = #date(2020, 3, 5), #"Weight" = 368.72],
					        [#"Date" = #date(2023, 10, 12), #"Weight" = 217.57],
					        [#"Date" = #date(2024, 9, 25), #"Weight" = 792.52],
					        [#"Date" = #date(2024, 6, 3), #"Weight" = 441.42],
					        [#"Date" = #date(2022, 2, 3), #"Weight" = 635.47],
					        [#"Date" = #date(2022, 10, 2), #"Weight" = 626.4],
					        [#"Date" = #date(2023, 1, 26), #"Weight" = 855.43],
					        [#"Date" = #date(2020, 8, 27), #"Weight" = 562.78],
					        [#"Date" = #date(2020, 7, 30), #"Weight" = 14.33],
					        [#"Date" = #date(2020, 5, 4), #"Weight" = 203.69],
					        [#"Date" = #date(2024, 2, 19), #"Weight" = 274.52],
					        [#"Date" = #date(2021, 4, 27), #"Weight" = 372.1],
					        [#"Date" = #date(2021, 12, 11), #"Weight" = 153.61],
					        [#"Date" = #date(2021, 9, 5), #"Weight" = 682.5],
					        [#"Date" = #date(2023, 10, 29), #"Weight" = 922.19],
					        [#"Date" = #date(2020, 2, 15), #"Weight" = 78.14],
					        [#"Date" = #date(2023, 3, 2), #"Weight" = 497.01],
					        [#"Date" = #date(2022, 11, 16), #"Weight" = 986.42],
					        [#"Date" = #date(2022, 4, 15), #"Weight" = 945.77],
					        [#"Date" = #date(2021, 10, 26), #"Weight" = 401.82],
					        [#"Date" = #date(2023, 7, 4), #"Weight" = 419.4],
					        [#"Date" = #date(2022, 1, 20), #"Weight" = 78.53],
					        [#"Date" = #date(2020, 10, 17), #"Weight" = 678.46],
					        [#"Date" = #date(2021, 3, 22), #"Weight" = 178.24],
					        [#"Date" = #date(2024, 3, 26), #"Weight" = 824.37],
					        [#"Date" = #date(2022, 8, 28), #"Weight" = 250.62],
					        [#"Date" = #date(2023, 12, 13), #"Weight" = 574.01],
					        [#"Date" = #date(2024, 12, 14), #"Weight" = 451.3],
					        [#"Date" = #date(2023, 7, 10), #"Weight" = 152.82],
					        [#"Date" = #date(2024, 1, 21), #"Weight" = 290.73],
					        [#"Date" = #date(2024, 4, 8), #"Weight" = 272.51],
					        [#"Date" = #date(2020, 7, 25), #"Weight" = 841.42],
					        [#"Date" = #date(2020, 4, 18), #"Weight" = 431.73],
					        [#"Date" = #date(2022, 9, 10), #"Weight" = 454.08],
					        [#"Date" = #date(2020, 5, 13), #"Weight" = 41.47],
					        [#"Date" = #date(2022, 11, 22), #"Weight" = 477.09],
					        [#"Date" = #date(2023, 11, 26), #"Weight" = 895.21],
					        [#"Date" = #date(2024, 4, 14), #"Weight" = 346.68],
					        [#"Date" = #date(2024, 4, 28), #"Weight" = 614.81],
					        [#"Date" = #date(2021, 3, 20), #"Weight" = 310.37],
					        [#"Date" = #date(2020, 7, 3), #"Weight" = 738.68],
					        [#"Date" = #date(2023, 11, 14), #"Weight" = 541.76],
					        [#"Date" = #date(2020, 10, 8), #"Weight" = 125.55],
					        [#"Date" = #date(2020, 10, 3), #"Weight" = 465.06],
					        [#"Date" = #date(2023, 2, 22), #"Weight" = 327.04],
					        [#"Date" = #date(2021, 3, 19), #"Weight" = 730.3],
					        [#"Date" = #date(2024, 8, 20), #"Weight" = 115.25],
					        [#"Date" = #date(2022, 2, 10), #"Weight" = 588.57],
					        [#"Date" = #date(2024, 8, 26), #"Weight" = 302.02],
					        [#"Date" = #date(2024, 1, 23), #"Weight" = 791.79],
					        [#"Date" = #date(2021, 3, 14), #"Weight" = 961.85],
					        [#"Date" = #date(2021, 10, 11), #"Weight" = 602.28],
					        [#"Date" = #date(2024, 12, 20), #"Weight" = 392.32],
					        [#"Date" = #date(2020, 3, 1), #"Weight" = 803.91],
					        [#"Date" = #date(2022, 10, 4), #"Weight" = 279.17],
					        [#"Date" = #date(2024, 4, 30), #"Weight" = 114.26],
					        [#"Date" = #date(2022, 10, 5), #"Weight" = 757.34],
					        [#"Date" = #date(2024, 12, 26), #"Weight" = 355.86],
					        [#"Date" = #date(2023, 10, 13), #"Weight" = 795.61],
					        [#"Date" = #date(2022, 5, 9), #"Weight" = 221.03],
					        [#"Date" = #date(2022, 6, 14), #"Weight" = 844.32],
					        [#"Date" = #date(2023, 11, 27), #"Weight" = 42.23],
					        [#"Date" = #date(2023, 9, 28), #"Weight" = 935.61],
					        [#"Date" = #date(2023, 9, 20), #"Weight" = 813.89],
					        [#"Date" = #date(2023, 4, 5), #"Weight" = 464.96],
					        [#"Date" = #date(2024, 1, 14), #"Weight" = 987.95],
					        [#"Date" = #date(2021, 8, 3), #"Weight" = 68.23],
					        [#"Date" = #date(2023, 2, 5), #"Weight" = 43.66],
					        [#"Date" = #date(2023, 7, 15), #"Weight" = 815.48],
					        [#"Date" = #date(2022, 5, 19), #"Weight" = 62.61],
					        [#"Date" = #date(2021, 12, 13), #"Weight" = 161.84],
					        [#"Date" = #date(2024, 11, 2), #"Weight" = 794.46],
					        [#"Date" = #date(2021, 11, 19), #"Weight" = 980.2],
					        [#"Date" = #date(2020, 8, 19), #"Weight" = 61.98],
					        [#"Date" = #date(2023, 6, 16), #"Weight" = 947.1],
					        [#"Date" = #date(2020, 11, 14), #"Weight" = 733.22],
					        [#"Date" = #date(2023, 3, 31), #"Weight" = 982.89],
					        [#"Date" = #date(2022, 4, 15), #"Weight" = 740.57],
					        [#"Date" = #date(2023, 1, 8), #"Weight" = 300.09],
					        [#"Date" = #date(2022, 12, 13), #"Weight" = 660.17],
					        [#"Date" = #date(2022, 7, 1), #"Weight" = 451.79],
					        [#"Date" = #date(2024, 1, 12), #"Weight" = 57.1],
					        [#"Date" = #date(2020, 6, 9), #"Weight" = 97.58],
					        [#"Date" = #date(2023, 3, 8), #"Weight" = 683.3],
					        [#"Date" = #date(2020, 9, 19), #"Weight" = 973.65],
					        [#"Date" = #date(2023, 2, 10), #"Weight" = 46.48],
					        [#"Date" = #date(2023, 2, 15), #"Weight" = 656.45],
					        [#"Date" = #date(2023, 10, 11), #"Weight" = 93.57],
					        [#"Date" = #date(2021, 12, 30), #"Weight" = 674.47],
					        [#"Date" = #date(2020, 9, 9), #"Weight" = 552.88],
					        [#"Date" = #date(2024, 8, 2), #"Weight" = 575.86],
					        [#"Date" = #date(2024, 4, 12), #"Weight" = 513.0],
					        [#"Date" = #date(2022, 5, 20), #"Weight" = 577.2],
					        [#"Date" = #date(2022, 2, 27), #"Weight" = 374.1],
					        [#"Date" = #date(2021, 1, 29), #"Weight" = 757.51],
					        [#"Date" = #date(2024, 9, 26), #"Weight" = 213.34],
					        [#"Date" = #date(2023, 6, 7), #"Weight" = 471.47],
					        [#"Date" = #date(2023, 10, 27), #"Weight" = 807.65],
					        [#"Date" = #date(2023, 11, 21), #"Weight" = 244.68],
					        [#"Date" = #date(2023, 6, 28), #"Weight" = 12.18],
					        [#"Date" = #date(2022, 3, 14), #"Weight" = 364.51],
					        [#"Date" = #date(2020, 9, 13), #"Weight" = 846.02],
					        [#"Date" = #date(2021, 5, 5), #"Weight" = 611.89],
					        [#"Date" = #date(2021, 11, 9), #"Weight" = 781.11],
					        [#"Date" = #date(2023, 5, 27), #"Weight" = 115.53],
					        [#"Date" = #date(2022, 9, 20), #"Weight" = 140.35],
					        [#"Date" = #date(2024, 6, 12), #"Weight" = 26.68],
					        [#"Date" = #date(2022, 12, 17), #"Weight" = 82.23],
					        [#"Date" = #date(2020, 1, 7), #"Weight" = 426.63],
					        [#"Date" = #date(2024, 1, 11), #"Weight" = 779.49],
					        [#"Date" = #date(2020, 7, 2), #"Weight" = 760.64],
					        [#"Date" = #date(2020, 9, 1), #"Weight" = 228.08],
					        [#"Date" = #date(2022, 6, 26), #"Weight" = 912.84],
					        [#"Date" = #date(2022, 6, 27), #"Weight" = 365.5],
					        [#"Date" = #date(2023, 5, 1), #"Weight" = 263.06],
					        [#"Date" = #date(2022, 8, 8), #"Weight" = 827.74],
					        [#"Date" = #date(2023, 2, 2), #"Weight" = 793.77],
					        [#"Date" = #date(2022, 4, 28), #"Weight" = 753.19],
					        [#"Date" = #date(2023, 4, 25), #"Weight" = 466.92],
					        [#"Date" = #date(2024, 6, 15), #"Weight" = 965.15],
					        [#"Date" = #date(2020, 10, 21), #"Weight" = 905.35],
					        [#"Date" = #date(2021, 11, 26), #"Weight" = 188.43],
					        [#"Date" = #date(2022, 3, 21), #"Weight" = 568.06],
					        [#"Date" = #date(2024, 12, 29), #"Weight" = 289.03],
					        [#"Date" = #date(2024, 12, 29), #"Weight" = 719.0],
					        [#"Date" = #date(2024, 7, 17), #"Weight" = 317.86],
					        [#"Date" = #date(2022, 2, 13), #"Weight" = 854.79],
					        [#"Date" = #date(2023, 10, 26), #"Weight" = 907.39],
					        [#"Date" = #date(2024, 2, 5), #"Weight" = 789.89],
					        [#"Date" = #date(2023, 9, 26), #"Weight" = 676.78],
					        [#"Date" = #date(2021, 6, 25), #"Weight" = 105.64],
					        [#"Date" = #date(2020, 6, 22), #"Weight" = 699.5],
					        [#"Date" = #date(2020, 3, 19), #"Weight" = 908.01],
					        [#"Date" = #date(2024, 5, 1), #"Weight" = 552.1],
					        [#"Date" = #date(2024, 7, 14), #"Weight" = 429.66],
					        [#"Date" = #date(2022, 12, 15), #"Weight" = 598.24],
					        [#"Date" = #date(2022, 9, 29), #"Weight" = 714.24],
					        [#"Date" = #date(2024, 4, 3), #"Weight" = 302.9],
					        [#"Date" = #date(2020, 9, 17), #"Weight" = 10.2],
					        [#"Date" = #date(2021, 11, 24), #"Weight" = 944.41],
					        [#"Date" = #date(2022, 2, 22), #"Weight" = 270.15],
					        [#"Date" = #date(2022, 1, 9), #"Weight" = 106.25],
					        [#"Date" = #date(2023, 2, 22), #"Weight" = 477.88],
					        [#"Date" = #date(2022, 8, 16), #"Weight" = 260.98],
					        [#"Date" = #date(2021, 4, 13), #"Weight" = 329.68],
					        [#"Date" = #date(2021, 1, 10), #"Weight" = 673.64],
					        [#"Date" = #date(2023, 1, 18), #"Weight" = 148.23],
					        [#"Date" = #date(2024, 11, 7), #"Weight" = 671.25],
					        [#"Date" = #date(2023, 11, 5), #"Weight" = 251.74],
					        [#"Date" = #date(2023, 2, 7), #"Weight" = 364.95],
					        [#"Date" = #date(2024, 12, 1), #"Weight" = 573.33],
					        [#"Date" = #date(2024, 10, 3), #"Weight" = 952.0],
					        [#"Date" = #date(2023, 5, 8), #"Weight" = 431.26],
					        [#"Date" = #date(2022, 4, 4), #"Weight" = 187.88],
					        [#"Date" = #date(2022, 7, 7), #"Weight" = 354.72],
					        [#"Date" = #date(2022, 12, 26), #"Weight" = 246.55],
					        [#"Date" = #date(2022, 1, 11), #"Weight" = 762.7],
					        [#"Date" = #date(2020, 12, 19), #"Weight" = 55.81],
					        [#"Date" = #date(2022, 9, 13), #"Weight" = 249.4],
					        [#"Date" = #date(2021, 10, 20), #"Weight" = 919.83],
					        [#"Date" = #date(2020, 1, 31), #"Weight" = 585.6],
					        [#"Date" = #date(2023, 6, 18), #"Weight" = 260.53],
					        [#"Date" = #date(2021, 4, 9), #"Weight" = 579.19],
					        [#"Date" = #date(2022, 5, 30), #"Weight" = 616.18],
					        [#"Date" = #date(2020, 1, 17), #"Weight" = 406.68],
					        [#"Date" = #date(2022, 1, 13), #"Weight" = 129.91],
					        [#"Date" = #date(2020, 8, 31), #"Weight" = 378.25],
					        [#"Date" = #date(2023, 4, 29), #"Weight" = 924.15],
					        [#"Date" = #date(2020, 3, 24), #"Weight" = 594.3],
					        [#"Date" = #date(2020, 11, 13), #"Weight" = 244.92],
					        [#"Date" = #date(2022, 1, 13), #"Weight" = 269.73],
					        [#"Date" = #date(2024, 9, 14), #"Weight" = 894.1],
					        [#"Date" = #date(2024, 12, 6), #"Weight" = 772.12],
					        [#"Date" = #date(2021, 8, 14), #"Weight" = 714.1],
					        [#"Date" = #date(2020, 3, 21), #"Weight" = 804.92],
					        [#"Date" = #date(2020, 1, 10), #"Weight" = 62.58],
					        [#"Date" = #date(2020, 3, 5), #"Weight" = 903.08],
					        [#"Date" = #date(2024, 7, 6), #"Weight" = 363.43],
					        [#"Date" = #date(2023, 9, 25), #"Weight" = 845.62],
					        [#"Date" = #date(2023, 4, 23), #"Weight" = 365.27],
					        [#"Date" = #date(2020, 4, 27), #"Weight" = 510.68],
					        [#"Date" = #date(2024, 7, 31), #"Weight" = 492.18],
					        [#"Date" = #date(2020, 8, 3), #"Weight" = 584.76],
					        [#"Date" = #date(2021, 7, 24), #"Weight" = 720.19],
					        [#"Date" = #date(2020, 5, 16), #"Weight" = 268.86],
					        [#"Date" = #date(2021, 8, 22), #"Weight" = 141.9],
					        [#"Date" = #date(2022, 5, 5), #"Weight" = 374.38],
					        [#"Date" = #date(2024, 9, 17), #"Weight" = 182.37],
					        [#"Date" = #date(2021, 11, 10), #"Weight" = 734.25],
					        [#"Date" = #date(2023, 3, 28), #"Weight" = 607.17],
					        [#"Date" = #date(2023, 3, 21), #"Weight" = 101.7],
					        [#"Date" = #date(2024, 2, 13), #"Weight" = 648.38],
					        [#"Date" = #date(2024, 9, 13), #"Weight" = 762.09],
					        [#"Date" = #date(2024, 9, 27), #"Weight" = 319.94],
					        [#"Date" = #date(2023, 7, 13), #"Weight" = 804.64],
					        [#"Date" = #date(2024, 7, 2), #"Weight" = 607.22],
					        [#"Date" = #date(2024, 7, 7), #"Weight" = 460.9],
					        [#"Date" = #date(2024, 6, 27), #"Weight" = 764.68],
					        [#"Date" = #date(2020, 10, 4), #"Weight" = 95.21],
					        [#"Date" = #date(2023, 2, 28), #"Weight" = 681.11],
					        [#"Date" = #date(2020, 2, 2), #"Weight" = 881.34],
					        [#"Date" = #date(2024, 2, 24), #"Weight" = 948.23],
					        [#"Date" = #date(2021, 6, 16), #"Weight" = 554.96],
					        [#"Date" = #date(2020, 7, 28), #"Weight" = 608.0],
					        [#"Date" = #date(2021, 1, 9), #"Weight" = 815.88],
					        [#"Date" = #date(2024, 11, 28), #"Weight" = 628.53],
					        [#"Date" = #date(2020, 2, 18), #"Weight" = 618.06],
					        [#"Date" = #date(2024, 9, 23), #"Weight" = 266.13],
					        [#"Date" = #date(2022, 4, 1), #"Weight" = 467.8],
					        [#"Date" = #date(2024, 4, 15), #"Weight" = 781.28],
					        [#"Date" = #date(2023, 3, 2), #"Weight" = 480.64],
					        [#"Date" = #date(2022, 8, 1), #"Weight" = 763.08],
					        [#"Date" = #date(2021, 11, 2), #"Weight" = 446.39],
					        [#"Date" = #date(2020, 2, 8), #"Weight" = 758.84],
					        [#"Date" = #date(2021, 4, 14), #"Weight" = 693.16],
					        [#"Date" = #date(2023, 3, 27), #"Weight" = 780.04],
					        [#"Date" = #date(2022, 4, 29), #"Weight" = 169.92],
					        [#"Date" = #date(2024, 1, 18), #"Weight" = 765.67],
					        [#"Date" = #date(2024, 6, 12), #"Weight" = 124.04],
					        [#"Date" = #date(2024, 8, 28), #"Weight" = 959.96],
					        [#"Date" = #date(2022, 11, 28), #"Weight" = 51.42],
					        [#"Date" = #date(2021, 2, 3), #"Weight" = 174.36],
					        [#"Date" = #date(2023, 11, 17), #"Weight" = 836.33],
					        [#"Date" = #date(2024, 6, 28), #"Weight" = 616.94],
					        [#"Date" = #date(2022, 10, 20), #"Weight" = 623.36],
					        [#"Date" = #date(2024, 11, 1), #"Weight" = 123.86],
					        [#"Date" = #date(2023, 9, 19), #"Weight" = 290.85],
					        [#"Date" = #date(2022, 8, 31), #"Weight" = 307.74],
					        [#"Date" = #date(2022, 1, 12), #"Weight" = 95.11],
					        [#"Date" = #date(2023, 10, 21), #"Weight" = 284.96],
					        [#"Date" = #date(2023, 12, 18), #"Weight" = 21.81],
					        [#"Date" = #date(2021, 10, 9), #"Weight" = 495.08],
					        [#"Date" = #date(2020, 3, 30), #"Weight" = 187.47],
					        [#"Date" = #date(2021, 7, 31), #"Weight" = 853.05],
					        [#"Date" = #date(2022, 12, 7), #"Weight" = 21.29],
					        [#"Date" = #date(2020, 6, 30), #"Weight" = 236.48],
					        [#"Date" = #date(2022, 11, 7), #"Weight" = 407.85],
					        [#"Date" = #date(2024, 7, 24), #"Weight" = 686.0],
					        [#"Date" = #date(2022, 10, 13), #"Weight" = 934.54],
					        [#"Date" = #date(2020, 10, 18), #"Weight" = 963.8],
					        [#"Date" = #date(2021, 7, 5), #"Weight" = 577.07],
					        [#"Date" = #date(2024, 12, 9), #"Weight" = 869.24],
					        [#"Date" = #date(2021, 8, 8), #"Weight" = 516.66],
					        [#"Date" = #date(2023, 8, 28), #"Weight" = 327.95],
					        [#"Date" = #date(2023, 3, 27), #"Weight" = 296.4],
					        [#"Date" = #date(2024, 9, 18), #"Weight" = 103.68],
					        [#"Date" = #date(2023, 12, 30), #"Weight" = 714.43],
					        [#"Date" = #date(2020, 9, 7), #"Weight" = 219.55],
					        [#"Date" = #date(2020, 3, 14), #"Weight" = 954.97],
					        [#"Date" = #date(2020, 11, 28), #"Weight" = 489.0],
					        [#"Date" = #date(2024, 10, 25), #"Weight" = 994.1],
					        [#"Date" = #date(2022, 12, 5), #"Weight" = 562.77],
					        [#"Date" = #date(2023, 5, 20), #"Weight" = 225.13],
					        [#"Date" = #date(2021, 2, 21), #"Weight" = 565.22],
					        [#"Date" = #date(2021, 11, 7), #"Weight" = 859.69],
					        [#"Date" = #date(2022, 3, 20), #"Weight" = 990.94],
					        [#"Date" = #date(2022, 3, 6), #"Weight" = 730.3],
					        [#"Date" = #date(2020, 5, 3), #"Weight" = 857.57],
					        [#"Date" = #date(2020, 8, 7), #"Weight" = 663.32],
					        [#"Date" = #date(2020, 4, 28), #"Weight" = 290.29],
					        [#"Date" = #date(2021, 3, 26), #"Weight" = 194.92],
					        [#"Date" = #date(2020, 5, 26), #"Weight" = 896.09],
					        [#"Date" = #date(2022, 9, 30), #"Weight" = 368.07],
					        [#"Date" = #date(2024, 9, 21), #"Weight" = 282.74],
					        [#"Date" = #date(2024, 11, 18), #"Weight" = 505.7],
					        [#"Date" = #date(2020, 12, 17), #"Weight" = 22.22],
					        [#"Date" = #date(2021, 4, 30), #"Weight" = 409.15],
					        [#"Date" = #date(2023, 5, 17), #"Weight" = 38.67],
					        [#"Date" = #date(2023, 2, 9), #"Weight" = 491.15],
					        [#"Date" = #date(2021, 5, 7), #"Weight" = 744.11],
					        [#"Date" = #date(2023, 1, 15), #"Weight" = 612.33],
					        [#"Date" = #date(2020, 5, 29), #"Weight" = 881.04],
					        [#"Date" = #date(2022, 9, 23), #"Weight" = 499.44],
					        [#"Date" = #date(2022, 5, 3), #"Weight" = 372.82],
					        [#"Date" = #date(2024, 10, 2), #"Weight" = 890.71],
					        [#"Date" = #date(2023, 2, 8), #"Weight" = 322.46],
					        [#"Date" = #date(2024, 3, 23), #"Weight" = 517.81],
					        [#"Date" = #date(2021, 7, 5), #"Weight" = 832.52],
					        [#"Date" = #date(2020, 11, 7), #"Weight" = 557.44],
					        [#"Date" = #date(2020, 8, 1), #"Weight" = 35.1],
					        [#"Date" = #date(2021, 4, 11), #"Weight" = 581.5],
					        [#"Date" = #date(2024, 2, 24), #"Weight" = 932.03],
					        [#"Date" = #date(2020, 12, 6), #"Weight" = 336.43],
					        [#"Date" = #date(2023, 7, 15), #"Weight" = 984.39],
					        [#"Date" = #date(2024, 11, 25), #"Weight" = 752.53],
					        [#"Date" = #date(2021, 3, 23), #"Weight" = 687.73],
					        [#"Date" = #date(2022, 7, 13), #"Weight" = 32.93],
					        [#"Date" = #date(2022, 4, 10), #"Weight" = 569.38],
					        [#"Date" = #date(2022, 9, 23), #"Weight" = 377.01],
					        [#"Date" = #date(2021, 4, 11), #"Weight" = 677.94],
					        [#"Date" = #date(2024, 12, 3), #"Weight" = 442.6],
					        [#"Date" = #date(2020, 10, 11), #"Weight" = 28.12],
					        [#"Date" = #date(2022, 1, 14), #"Weight" = 833.85],
					        [#"Date" = #date(2020, 10, 19), #"Weight" = 780.1],
					        [#"Date" = #date(2021, 1, 27), #"Weight" = 764.33],
					        [#"Date" = #date(2020, 7, 15), #"Weight" = 840.93],
					        [#"Date" = #date(2022, 1, 19), #"Weight" = 918.57],
					        [#"Date" = #date(2021, 1, 17), #"Weight" = 689.35],
					        [#"Date" = #date(2022, 10, 25), #"Weight" = 843.7],
					        [#"Date" = #date(2024, 7, 16), #"Weight" = 233.15],
					        [#"Date" = #date(2024, 2, 15), #"Weight" = 487.54],
					        [#"Date" = #date(2024, 12, 3), #"Weight" = 473.99],
					        [#"Date" = #date(2021, 2, 17), #"Weight" = 20.24],
					        [#"Date" = #date(2023, 7, 24), #"Weight" = 252.44],
					        [#"Date" = #date(2023, 4, 3), #"Weight" = 277.73],
					        [#"Date" = #date(2020, 9, 6), #"Weight" = 952.97],
					        [#"Date" = #date(2021, 3, 11), #"Weight" = 638.38],
					        [#"Date" = #date(2022, 11, 14), #"Weight" = 786.22],
					        [#"Date" = #date(2020, 5, 26), #"Weight" = 320.7],
					        [#"Date" = #date(2022, 2, 15), #"Weight" = 365.33],
					        [#"Date" = #date(2021, 3, 24), #"Weight" = 272.6],
					        [#"Date" = #date(2023, 3, 5), #"Weight" = 433.97],
					        [#"Date" = #date(2024, 12, 24), #"Weight" = 41.73],
					        [#"Date" = #date(2020, 3, 21), #"Weight" = 853.89],
					        [#"Date" = #date(2020, 6, 14), #"Weight" = 118.79],
					        [#"Date" = #date(2020, 5, 25), #"Weight" = 670.03],
					        [#"Date" = #date(2022, 4, 4), #"Weight" = 385.6],
					        [#"Date" = #date(2020, 12, 14), #"Weight" = 284.59],
					        [#"Date" = #date(2023, 10, 29), #"Weight" = 875.16],
					        [#"Date" = #date(2024, 7, 25), #"Weight" = 625.09],
					        [#"Date" = #date(2023, 4, 28), #"Weight" = 741.39],
					        [#"Date" = #date(2024, 3, 14), #"Weight" = 385.91],
					        [#"Date" = #date(2023, 3, 30), #"Weight" = 154.59],
					        [#"Date" = #date(2024, 5, 12), #"Weight" = 559.77],
					        [#"Date" = #date(2022, 3, 14), #"Weight" = 497.9],
					        [#"Date" = #date(2020, 5, 20), #"Weight" = 252.21],
					        [#"Date" = #date(2024, 10, 7), #"Weight" = 501.73],
					        [#"Date" = #date(2020, 5, 11), #"Weight" = 586.91],
					        [#"Date" = #date(2022, 7, 2), #"Weight" = 594.04],
					        [#"Date" = #date(2024, 6, 15), #"Weight" = 189.93],
					        [#"Date" = #date(2021, 4, 20), #"Weight" = 166.73],
					        [#"Date" = #date(2024, 4, 21), #"Weight" = 703.26],
					        [#"Date" = #date(2024, 7, 15), #"Weight" = 454.9],
					        [#"Date" = #date(2022, 5, 21), #"Weight" = 793.08],
					        [#"Date" = #date(2021, 3, 9), #"Weight" = 912.1],
					        [#"Date" = #date(2024, 4, 26), #"Weight" = 803.34],
					        [#"Date" = #date(2021, 10, 14), #"Weight" = 153.83],
					        [#"Date" = #date(2024, 2, 27), #"Weight" = 523.64],
					        [#"Date" = #date(2020, 9, 17), #"Weight" = 957.36],
					        [#"Date" = #date(2024, 2, 2), #"Weight" = 259.17],
					        [#"Date" = #date(2021, 3, 23), #"Weight" = 441.0],
					        [#"Date" = #date(2023, 9, 26), #"Weight" = 973.5],
					        [#"Date" = #date(2021, 3, 3), #"Weight" = 392.16],
					        [#"Date" = #date(2023, 5, 27), #"Weight" = 990.49],
					        [#"Date" = #date(2023, 11, 23), #"Weight" = 966.62],
					        [#"Date" = #date(2024, 5, 12), #"Weight" = 779.83],
					        [#"Date" = #date(2022, 12, 6), #"Weight" = 372.92],
					        [#"Date" = #date(2023, 9, 17), #"Weight" = 618.58],
					        [#"Date" = #date(2021, 10, 27), #"Weight" = 754.94],
					        [#"Date" = #date(2022, 7, 16), #"Weight" = 186.17],
					        [#"Date" = #date(2023, 7, 7), #"Weight" = 451.7],
					        [#"Date" = #date(2024, 10, 13), #"Weight" = 961.97],
					        [#"Date" = #date(2020, 7, 7), #"Weight" = 443.2],
					        [#"Date" = #date(2024, 2, 5), #"Weight" = 840.08],
					        [#"Date" = #date(2020, 1, 31), #"Weight" = 376.68],
					        [#"Date" = #date(2021, 6, 23), #"Weight" = 717.31],
					        [#"Date" = #date(2020, 6, 28), #"Weight" = 133.17],
					        [#"Date" = #date(2020, 1, 17), #"Weight" = 522.16],
					        [#"Date" = #date(2021, 11, 16), #"Weight" = 870.92],
					        [#"Date" = #date(2021, 11, 25), #"Weight" = 227.63],
					        [#"Date" = #date(2021, 9, 23), #"Weight" = 859.24],
					        [#"Date" = #date(2024, 7, 17), #"Weight" = 782.02],
					        [#"Date" = #date(2021, 12, 24), #"Weight" = 96.54],
					        [#"Date" = #date(2023, 3, 23), #"Weight" = 211.85],
					        [#"Date" = #date(2023, 11, 1), #"Weight" = 74.85],
					        [#"Date" = #date(2022, 3, 19), #"Weight" = 310.11],
					        [#"Date" = #date(2024, 12, 16), #"Weight" = 469.8],
					        [#"Date" = #date(2024, 8, 26), #"Weight" = 295.31],
					        [#"Date" = #date(2023, 7, 27), #"Weight" = 786.31],
					        [#"Date" = #date(2023, 10, 25), #"Weight" = 239.38],
					        [#"Date" = #date(2023, 6, 7), #"Weight" = 400.81],
					        [#"Date" = #date(2024, 8, 8), #"Weight" = 656.24],
					        [#"Date" = #date(2021, 2, 24), #"Weight" = 107.0],
					        [#"Date" = #date(2021, 7, 15), #"Weight" = 496.75],
					        [#"Date" = #date(2021, 1, 8), #"Weight" = 95.36],
					        [#"Date" = #date(2020, 3, 6), #"Weight" = 607.3],
					        [#"Date" = #date(2020, 3, 26), #"Weight" = 973.57],
					        [#"Date" = #date(2024, 3, 14), #"Weight" = 566.87],
					        [#"Date" = #date(2023, 7, 17), #"Weight" = 715.47],
					        [#"Date" = #date(2020, 3, 4), #"Weight" = 378.82],
					        [#"Date" = #date(2021, 7, 30), #"Weight" = 836.18],
					        [#"Date" = #date(2021, 1, 16), #"Weight" = 320.52],
					        [#"Date" = #date(2024, 11, 23), #"Weight" = 69.22],
					        [#"Date" = #date(2022, 8, 20), #"Weight" = 69.51],
					        [#"Date" = #date(2023, 10, 11), #"Weight" = 558.83],
					        [#"Date" = #date(2024, 12, 12), #"Weight" = 336.72],
					        [#"Date" = #date(2021, 2, 14), #"Weight" = 880.27],
					        [#"Date" = #date(2020, 4, 27), #"Weight" = 833.95],
					        [#"Date" = #date(2021, 1, 23), #"Weight" = 510.88],
					        [#"Date" = #date(2023, 9, 27), #"Weight" = 616.69],
					        [#"Date" = #date(2021, 11, 7), #"Weight" = 543.64],
					        [#"Date" = #date(2020, 6, 25), #"Weight" = 324.98],
					        [#"Date" = #date(2023, 12, 23), #"Weight" = 344.89],
					        [#"Date" = #date(2021, 8, 25), #"Weight" = 237.76],
					        [#"Date" = #date(2021, 2, 2), #"Weight" = 143.38],
					        [#"Date" = #date(2024, 4, 16), #"Weight" = 144.67],
					        [#"Date" = #date(2022, 10, 15), #"Weight" = 942.48],
					        [#"Date" = #date(2023, 7, 15), #"Weight" = 429.68],
					        [#"Date" = #date(2021, 12, 21), #"Weight" = 513.05],
					        [#"Date" = #date(2020, 4, 14), #"Weight" = 636.7],
					        [#"Date" = #date(2022, 3, 8), #"Weight" = 979.12],
					        [#"Date" = #date(2023, 10, 21), #"Weight" = 397.38],
					        [#"Date" = #date(2023, 2, 5), #"Weight" = 947.85],
					        [#"Date" = #date(2021, 7, 11), #"Weight" = 43.01],
					        [#"Date" = #date(2022, 8, 10), #"Weight" = 450.32],
					        [#"Date" = #date(2023, 3, 3), #"Weight" = 492.72],
					        [#"Date" = #date(2021, 6, 9), #"Weight" = 959.04],
					        [#"Date" = #date(2021, 11, 1), #"Weight" = 612.6],
					        [#"Date" = #date(2022, 3, 13), #"Weight" = 612.94],
					        [#"Date" = #date(2020, 9, 9), #"Weight" = 828.25],
					        [#"Date" = #date(2020, 8, 26), #"Weight" = 811.97],
					        [#"Date" = #date(2024, 7, 11), #"Weight" = 519.84]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Date", type date},
					        {"Weight", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table