table 'trulia_dataset_cleaned (trulia_dataset_cleanedTBL)'
	lineageTag: fd4df41f-dd0f-4d7c-87ec-02422df1dc18

	measure 'Median Sales Price National' = MEDIAN('trulia_dataset_cleaned (trulia_dataset_cleanedTBL)'[Price])
		formatString: 0
		lineageTag: 4d84c421-e75a-4a28-adbd-58d00f89b652

	measure 'Median Sales Price % Increase' = VAR medPrice = MEDIAN('trulia_dataset_cleaned (trulia_dataset_cleanedTBL)'[Price]) VAR medLastSold = MEDIAN('trulia_dataset_cleaned (trulia_dataset_cleanedTBL)'[Last Sold For]) RETURN ((medPrice - medLastSold) / medLastSold) * 100
		formatString: 0
		lineageTag: c8f93e56-be70-45da-980b-12f31c20e1da

	column Address
		dataType: string
		lineageTag: 42d64458-1ce2-4862-b85c-88fc684ade90
		summarizeBy: none
		sourceColumn: Address

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 54fb7e0c-ef4f-415d-b246-ea2b6527ff03
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 6546ee29-f91a-4067-9890-3efbe8d3bcad
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Zip code'
		dataType: int64
		formatString: 0
		lineageTag: e807df1f-d8d0-4efa-87bb-47a3b0c04f29
		summarizeBy: sum
		sourceColumn: 'Zip code'

		annotation SummarizationSetBy = Automatic

	column Price
		dataType: int64
		formatString: 0
		lineageTag: 371b3a1b-747c-4684-b614-a26b964ccfe1
		summarizeBy: sum
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

	column Style
		dataType: string
		lineageTag: c5c7c385-7679-4bbe-a16b-be8df67ccd9a
		summarizeBy: none
		sourceColumn: Style

		annotation SummarizationSetBy = Automatic

	column 'Sqr Ft'
		dataType: string
		lineageTag: 18de3fb7-1775-48a8-9fa4-ecbe707f4176
		summarizeBy: none
		sourceColumn: 'Sqr Ft'

		annotation SummarizationSetBy = Automatic

	column Longitude
		dataType: double
		formatString: General Number
		lineageTag: 37f77836-ab77-46a1-b502-55d6b692bc6e
		summarizeBy: sum
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Latitude
		dataType: double
		formatString: General Number
		lineageTag: 502d85a2-83ac-4deb-87f4-50762818efb3
		summarizeBy: sum
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Home Id'
		dataType: int64
		formatString: 0
		lineageTag: 9eb9a80a-6f96-4e3d-be9c-90b04b47e258
		summarizeBy: sum
		sourceColumn: 'Home Id'

		annotation SummarizationSetBy = Automatic

	column 'Lot Size'
		dataType: string
		lineageTag: 5d96ae97-9e33-4cbf-995d-79002de2171d
		summarizeBy: none
		sourceColumn: 'Lot Size'

		annotation SummarizationSetBy = Automatic

	column 'Lot Size 1'
		dataType: string
		lineageTag: 3cfafefc-de1e-49bf-85c4-f67eef7f6c29
		summarizeBy: none
		sourceColumn: 'Lot Size 1'

		annotation SummarizationSetBy = Automatic

	column Beds
		dataType: int64
		formatString: 0
		lineageTag: 0f2dc13e-dd59-499e-a471-58c8d14a7a0f
		summarizeBy: sum
		sourceColumn: Beds

		annotation SummarizationSetBy = Automatic

	column Bath
		dataType: double
		formatString: General Number
		lineageTag: 21bfd44d-1ac0-4671-b02e-29a35b515f26
		summarizeBy: sum
		sourceColumn: Bath

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Year Built'
		dataType: datetime
		lineageTag: 7e6d9889-e201-4819-9add-ded68ab15703
		summarizeBy: none
		sourceColumn: 'Year Built'

		annotation SummarizationSetBy = Automatic

	column 'Price Sqr Ft'
		dataType: int64
		formatString: 0
		lineageTag: a5f71bc8-abdf-4fdf-a358-f9c21048788b
		summarizeBy: sum
		sourceColumn: 'Price Sqr Ft'

		annotation SummarizationSetBy = Automatic

	column F17
		dataType: string
		lineageTag: d125c39a-70eb-4d7f-a5a7-533196786620
		summarizeBy: none
		sourceColumn: F17

		annotation SummarizationSetBy = Automatic

	column 'Property Type'
		dataType: string
		lineageTag: 3c44e2ec-1ef7-4ba4-bce5-e878825a1e7e
		summarizeBy: none
		sourceColumn: 'Property Type'

		annotation SummarizationSetBy = Automatic

	column 'Last Sold Year'
		dataType: datetime
		lineageTag: 5b9089b7-c436-4001-b06b-52934c951001
		summarizeBy: none
		sourceColumn: 'Last Sold Year'

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: int64
		formatString: 0
		lineageTag: 7bb1c959-110a-4ba0-a53c-c6ed8726f8d3
		summarizeBy: sum
		sourceColumn: 'Units Sold'

		annotation SummarizationSetBy = Automatic

	column 'Last Sold For'
		dataType: int64
		formatString: 0
		lineageTag: 434c50b9-3664-4eb4-a573-c2a83390f81d
		summarizeBy: sum
		sourceColumn: 'Last Sold For'

		annotation SummarizationSetBy = Automatic

	column 'Last Tax Assestment'
		dataType: int64
		formatString: 0
		lineageTag: bbcb9608-57dc-4d3a-89ac-cd06ac49bcb8
		summarizeBy: sum
		sourceColumn: 'Last Tax Assestment'

		annotation SummarizationSetBy = Automatic

	column 'Last Tax Year'
		dataType: datetime
		lineageTag: c74b5d1b-fcd8-49d6-9539-538c5847b37c
		summarizeBy: none
		sourceColumn: 'Last Tax Year'

		annotation SummarizationSetBy = Automatic

	column F24
		dataType: string
		lineageTag: 22303b72-cd8f-4866-9875-d465656477b3
		summarizeBy: none
		sourceColumn: F24

		annotation SummarizationSetBy = Automatic

	column F25
		dataType: string
		lineageTag: 7c4778b4-bfba-443c-8837-9e0b0a024fee
		summarizeBy: none
		sourceColumn: F25

		annotation SummarizationSetBy = Automatic

	column F26
		dataType: string
		lineageTag: 8c84b901-d415-4db0-b2fc-c6fba4a327c8
		summarizeBy: none
		sourceColumn: F26

		annotation SummarizationSetBy = Automatic

	column F27
		dataType: string
		lineageTag: 30f2b506-384f-452e-8fe0-fbc39b1bfa49
		summarizeBy: none
		sourceColumn: F27

		annotation SummarizationSetBy = Automatic

	column F28
		dataType: string
		lineageTag: 7592fe1b-78de-47b1-8c6f-f911513101f8
		summarizeBy: none
		sourceColumn: F28

		annotation SummarizationSetBy = Automatic

	column F29
		dataType: string
		lineageTag: d44fc59f-d413-484c-8984-b4e550f00599
		summarizeBy: none
		sourceColumn: F29

		annotation SummarizationSetBy = Automatic

	column F30
		dataType: string
		lineageTag: c32f2706-6503-40c5-8af7-f3783698710c
		summarizeBy: none
		sourceColumn: F30

		annotation SummarizationSetBy = Automatic

	column F31
		dataType: string
		lineageTag: bfcfd67e-593b-4836-8e63-7772653a89f0
		summarizeBy: none
		sourceColumn: F31

		annotation SummarizationSetBy = Automatic

	column F32
		dataType: string
		lineageTag: 1be5d2a0-d33b-4324-b381-10dac35880c6
		summarizeBy: none
		sourceColumn: F32

		annotation SummarizationSetBy = Automatic

	column F33
		dataType: string
		lineageTag: 39825bb0-abbe-411d-929f-bb087d549a74
		summarizeBy: none
		sourceColumn: F33

		annotation SummarizationSetBy = Automatic

	column F34
		dataType: string
		lineageTag: af8eb3a7-088b-43ae-8605-354b774111e1
		summarizeBy: none
		sourceColumn: F34

		annotation SummarizationSetBy = Automatic

	column F35
		dataType: string
		lineageTag: 3e54c522-adc1-47c0-b21e-f738707a4461
		summarizeBy: none
		sourceColumn: F35

		annotation SummarizationSetBy = Automatic

	column F36
		dataType: string
		lineageTag: 1b1bce5b-d516-4ae4-a270-0075a15ae6f3
		summarizeBy: none
		sourceColumn: F36

		annotation SummarizationSetBy = Automatic

	column F37
		dataType: string
		lineageTag: 2b3c83ba-dd72-4805-856a-180451a808b9
		summarizeBy: none
		sourceColumn: F37

		annotation SummarizationSetBy = Automatic

	column F38
		dataType: string
		lineageTag: cf894ab7-7026-4c69-a001-b5f64d20182e
		summarizeBy: none
		sourceColumn: F38

		annotation SummarizationSetBy = Automatic

	column F39
		dataType: string
		lineageTag: 5b4f77e0-37d0-4719-bc1c-8f96895b9574
		summarizeBy: none
		sourceColumn: F39

		annotation SummarizationSetBy = Automatic

	column F40
		dataType: string
		lineageTag: 6a3af760-4a58-4cf9-af32-f1fa05ecd521
		summarizeBy: none
		sourceColumn: F40

		annotation SummarizationSetBy = Automatic

	column F41
		dataType: double
		formatString: General Number
		lineageTag: 1b4ac138-f582-408e-8384-ea7f6be9394a
		summarizeBy: sum
		sourceColumn: F41

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column F42
		dataType: double
		formatString: General Number
		lineageTag: 539e3008-9063-4237-bd62-86d466cf41e4
		summarizeBy: sum
		sourceColumn: F42

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column F43
		dataType: double
		formatString: General Number
		lineageTag: 93069e7e-226d-492e-8fdf-f29f78fbcae5
		summarizeBy: sum
		sourceColumn: F43

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column F44
		dataType: double
		formatString: General Number
		lineageTag: 70b58800-4675-4e80-a0df-05c96d15fd73
		summarizeBy: sum
		sourceColumn: F44

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column F45
		dataType: double
		formatString: General Number
		lineageTag: e82781be-5566-482e-a24a-1312e342fd2e
		summarizeBy: sum
		sourceColumn: F45

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column F46
		dataType: double
		formatString: General Number
		lineageTag: 1586b858-2972-4e01-ab8f-2c453b871f48
		summarizeBy: sum
		sourceColumn: F46

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column F47
		dataType: double
		formatString: General Number
		lineageTag: a4e4f7ee-359f-4258-b8d4-887edb8f81ed
		summarizeBy: sum
		sourceColumn: F47

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column F48
		dataType: double
		formatString: General Number
		lineageTag: 0a280520-3cff-49a7-919a-8263d0cde344
		summarizeBy: sum
		sourceColumn: F48

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column F49
		dataType: double
		formatString: General Number
		lineageTag: 32405485-2677-411f-a931-8bccea2c583c
		summarizeBy: sum
		sourceColumn: F49

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column F50
		dataType: double
		formatString: General Number
		lineageTag: e92b7d4e-3d91-4b5f-b94b-0660f839668d
		summarizeBy: sum
		sourceColumn: F50

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'County Drill Down' = IF('trulia_dataset_cleaned (trulia_dataset_cleanedTBL)'[State Set], 'trulia_dataset_cleaned (trulia_dataset_cleanedTBL)'[COUNTYNAME], BLANK())
		lineageTag: b62649d4-0225-4188-a718-53b1f12a6479
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'trulia_dataset_cleaned (trulia_dataset_cleanedTBL)' = m
		mode: import
		source =
				let
					    Source = Csv.Document(
					        File.Contents("https://saastestlatest.blob.core.windows.net/saas-test-reports/trulia_dataset_cleaned%20%28trulia_dataset_cleanedTBL%29.csv?se=2025-11-03T18%3A39%3A10Z&sp=r&sv=2025-11-05&sr=b&sig=BKT37NBoXeqCkewfGjNqtzJHHhOCScg3h06tvDTK5rg%3D"),
					        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
					    ),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Address", type text}, {"City", type text}, {"State", type text}, {"Zip code", Int64.Type}, {"Price", Int64.Type}, {"Style", type text}, {"Sqr Ft", type text}, {"Longitude", type number}, {"Latitude", type number}, {"Home Id", Int64.Type}, {"Lot Size", type text}, {"Lot Size 1", type text}, {"Beds", Int64.Type}, {"Bath", type number}, {"Year Built", type date}, {"Price Sqr Ft", Int64.Type}, {"F17", type text}, {"Property Type", type text}, {"Last Sold Year", type date}, {"Units Sold", Int64.Type}, {"Last Sold For", Int64.Type}, {"Last Tax Assestment", Int64.Type}, {"Last Tax Year", type date}, {"F24", type text}, {"F25", type text}, {"F26", type text}, {"F27", type text}, {"F28", type text}, {"F29", type text}, {"F30", type text}, {"F31", type text}, {"F32", type text}, {"F33", type text}, {"F34", type text}, {"F35", type text}, {"F36", type text}, {"F37", type text}, {"F38", type text}, {"F39", type text}, {"F40", type text}, {"F41", type number}, {"F42", type number}, {"F43", type number}, {"F44", type number}, {"F45", type number}, {"F46", type number}, {"F47", type number}, {"F48", type number}, {"F49", type number}, {"F50", type number}})
					in
					    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table