table 'trulia_dataset_cleaned (trulia_dataset_cleanedTBL)_ZIP-COUNTY-FIPS_2017-06'
	lineageTag: f252c620-2ff1-4e27-826e-9ab6b7d404bc

	column ZIP
		dataType: int64
		formatString: 0
		lineageTag: 4fc5c65c-4420-4079-814a-7259a0d033d7
		summarizeBy: sum
		sourceColumn: ZIP

		annotation SummarizationSetBy = Automatic

	column COUNTYNAME
		dataType: string
		lineageTag: f8fa6246-3c0b-4fef-b7a5-5d15db86aa2b
		summarizeBy: none
		sourceColumn: COUNTYNAME

		annotation SummarizationSetBy = Automatic

	column STATE
		dataType: string
		lineageTag: 8ada8063-e3b1-4b7d-b375-86ea17d76d82
		summarizeBy: none
		sourceColumn: STATE

		annotation SummarizationSetBy = Automatic

	column STCOUNTYFP
		dataType: int64
		formatString: 0
		lineageTag: 7413094b-2fbe-42ab-ad49-e7c1451eec70
		summarizeBy: sum
		sourceColumn: STCOUNTYFP

		annotation SummarizationSetBy = Automatic

	partition 'trulia_dataset_cleaned (trulia_dataset_cleanedTBL)_ZIP-COUNTY-FIPS_2017-06' = m
		mode: import
		source =
				let
					    Source = Csv.Document(
					        File.Contents("https://saastestlatest.blob.core.windows.net/saas-test-reports/trulia_dataset_cleaned%20%28trulia_dataset_cleanedTBL%29_ZIP-COUNTY-FIPS_2017-06.csv?se=2025-11-03T18%3A37%3A58Z&sp=r&sv=2025-11-05&sr=b&sig=SzbS1u1SC52u/a9D8qBM5VMkSbN2PqKpvWcGqTfq6hc%3D"),
					        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
					    ),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ZIP", Int64.Type}, {"COUNTYNAME", type text}, {"STATE", type text}, {"STCOUNTYFP", Int64.Type}})
					in
					    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table