table 'Sample - Superstore_Returns'
	lineageTag: fc7f64e9-9fab-4ff2-892c-cb7ad6154c69

	column 'Order ID'
		dataType: string
		lineageTag: fc4022e7-5211-49e6-bfc5-66774b9295d0
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column Returned
		dataType: string
		lineageTag: 10c0a503-1b45-4df1-8dcf-2bcbf1f9671a
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	partition 'Sample - Superstore_Returns' = m
		mode: import
		source =
				let
					    Source = Csv.Document(
					        File.Contents("https://saastestlatest.blob.core.windows.net/saas-test-reports/Sample%20-%20Superstore_Returns.csv?se=2025-11-04T13%3A46%3A00Z&sp=r&sv=2025-11-05&sr=b&sig=8XnF8YwMeNcANd9iEbxPmoDm5Aa0HkpEWqbcNYfhyXU%3D"),
					        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
					    ),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Order ID", type text}, {"Returned", type text}})
					in
					    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table