table 'Sample - Superstore'
	lineageTag: 8dcfd874-24aa-4a39-b818-21b0ec908d2b

	measure 'Profit Ratio' = SUM('Sample - Superstore'[Profit]) / SUM('Sample - Superstore'[Sales])
		formatString: 0
		lineageTag: 2575bb89-5d67-4721-af93-3f1d04a3726a

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: d3f60f1b-ddb2-46f3-a31d-b6d03e2aa0ef
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 6eb12741-0cc6-42c8-977e-604f31d606ad
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: datetime
		lineageTag: cecc019d-2a8a-486e-aff4-6379fd2fabe5
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: datetime
		lineageTag: 63abffc4-700f-4bb4-8be5-ec503115278e
		summarizeBy: none
		sourceColumn: 'Ship Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: ddaa4e42-8291-4402-b5be-d40f81356c48
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: cce8e93f-7da9-4be1-bd2f-e5baafd22a78
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 62029318-0f16-4779-9808-a2e7c18170c5
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 4ccdaf7b-b1fc-475b-b7ec-519a6ea01b6b
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Country/Region'
		dataType: string
		lineageTag: f3028e61-f3e3-4e0c-81d3-c9da63242a7b
		summarizeBy: none
		sourceColumn: 'Country/Region'

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 9f1ed09d-9fa0-49d2-94bf-391337d30c9e
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'State/Province'
		dataType: string
		lineageTag: d400c6b4-51c2-49c8-8af3-72c29b4a9fa3
		summarizeBy: none
		sourceColumn: 'State/Province'

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: 5b7fb0b3-0d8b-4eee-a2bf-5a74a850109f
		summarizeBy: none
		sourceColumn: 'Postal Code'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 8a036b6d-7464-442d-aae8-73c58766d203
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 8c2cc7a8-0c0e-41ee-b2e9-ea04d4348fa5
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 6b036c69-7d1a-4a3b-bd71-3059356ebb34
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: c7ac0c56-3b37-450e-a0ba-70d3336967cf
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 96bc4b17-00e9-4014-8886-e5bd6b033ca5
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: General Number
		lineageTag: 290dc051-cec5-46e9-9710-3cf10627f14b
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: d70b07fc-a51f-42f8-9b94-8e5b4ebbeecb
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: General Number
		lineageTag: b14c4385-4e59-48c8-9c43-ee1e01818373
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		formatString: General Number
		lineageTag: e0d7e083-47d0-4340-8dc5-fabcccf1ac53
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Calculation1 = 'Sample - Superstore'[Ship Date]
		lineageTag: 7193b7e0-b8fb-4dfd-a331-f3fc5910f87c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Profit (bin)' = 'Sample - Superstore'[Profit]
		formatString: 0
		lineageTag: 61ca154c-2328-4990-9140-23d172f96458
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Calculation2 = 'Sample - Superstore'[Discount]
		lineageTag: 2c694734-df0d-4818-8b70-00d49619c8a9
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Sample - Superstore' = m
		mode: import
		source =
				let
					    Source = Csv.Document(
					        File.Contents("https://saastestlatest.blob.core.windows.net/saas-test-reports/Sample%20-%20Superstore.csv?se=2025-11-04T13%3A46%3A34Z&sp=r&sv=2025-11-05&sr=b&sig=%2Bx8VkwVRXXv1ChgKLbPyQX0JpYrlkxTLxbtH5mkYGtk%3D"),
					        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
					    ),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State/Province", type text}, {"Postal Code", type text}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
					in
					    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table