table 'Top Customers'
	lineageTag: 1433efe8-f658-422e-9172-c3ff63c3f706

	measure 'Top Customers Value' = SELECTEDVALUE('Top Customers'[Top Customers], 5)
		lineageTag: 0bbe912e-78cc-416a-ba1c-82c19c5f1fd8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Top Customers'
		dataType: double
		formatString: 0
		lineageTag: 6ad00a11-a473-4fb5-8560-2eaa1c698a00
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Top Customers' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_Id = 794be0a6a59d48e1b991a32c50b2acd1

