table bank_final
	lineageTag: b6686cff-c4b5-4e70-915e-7ab79ee08c4e

	column age
		dataType: int64
		formatString: 0
		lineageTag: 35830096-5370-45bd-ba02-33d57c303cf3
		summarizeBy: sum
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	column job
		dataType: string
		lineageTag: 9b69c52d-358f-4e99-8977-f92f9e47a031
		summarizeBy: none
		sourceColumn: job

		annotation SummarizationSetBy = Automatic

	column marital
		dataType: string
		lineageTag: 19817106-e4e3-4801-853c-c7713acc8d5c
		summarizeBy: none
		sourceColumn: marital

		annotation SummarizationSetBy = Automatic

	column education
		dataType: string
		lineageTag: e60da29a-a00e-46ca-b0c7-93e5e288e2be
		summarizeBy: none
		sourceColumn: education

		annotation SummarizationSetBy = Automatic

	column default
		dataType: string
		lineageTag: b5694e99-edbf-4570-9973-b756cb03b675
		summarizeBy: none
		sourceColumn: default

		annotation SummarizationSetBy = Automatic

	column balance
		dataType: int64
		formatString: 0
		lineageTag: 0fea1f05-5ae6-49b3-86e1-aa0edcf3124c
		summarizeBy: sum
		sourceColumn: balance

		annotation SummarizationSetBy = Automatic

	column housing
		dataType: string
		lineageTag: c9c5660b-afc3-4731-bab5-6743322fb4ec
		summarizeBy: none
		sourceColumn: housing

		annotation SummarizationSetBy = Automatic

	column loan
		dataType: string
		lineageTag: fc3dfac6-d803-4cc4-848c-5a12bf5728cf
		summarizeBy: none
		sourceColumn: loan

		annotation SummarizationSetBy = Automatic

	column contact
		dataType: string
		lineageTag: e570d075-dbad-4013-8580-c041be8a8e8c
		summarizeBy: none
		sourceColumn: contact

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: 8c6c16dc-c0ed-4c1c-850f-7d59a35e52c4
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column month
		dataType: string
		lineageTag: d7897012-d9dd-4ea5-a0e1-c9ede3bf782f
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column duration
		dataType: int64
		formatString: 0
		lineageTag: b61b17b2-bf6e-48eb-8507-d84c20eda7fe
		summarizeBy: sum
		sourceColumn: duration

		annotation SummarizationSetBy = Automatic

	column campaign
		dataType: int64
		formatString: 0
		lineageTag: ffbb9c8d-9660-4096-a0a7-4772ffa1a40e
		summarizeBy: sum
		sourceColumn: campaign

		annotation SummarizationSetBy = Automatic

	column pdays
		dataType: int64
		formatString: 0
		lineageTag: 625949c7-953d-41ec-82a1-633d1fa473dd
		summarizeBy: sum
		sourceColumn: pdays

		annotation SummarizationSetBy = Automatic

	column previous
		dataType: int64
		formatString: 0
		lineageTag: b8fa9446-2cc7-4b85-ba53-23928bd0e227
		summarizeBy: sum
		sourceColumn: previous

		annotation SummarizationSetBy = Automatic

	column poutcome
		dataType: string
		lineageTag: 2080a01e-d936-4c06-a69b-baea000d58af
		summarizeBy: none
		sourceColumn: poutcome

		annotation SummarizationSetBy = Automatic

	column deposit
		dataType: string
		lineageTag: 2d099b61-ca49-4a1d-8858-36111e796f04
		summarizeBy: none
		sourceColumn: deposit

		annotation SummarizationSetBy = Automatic

	partition bank_final = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://repoz-my.sharepoint.com/personal/karthikrajan_repoz_ai/Documents/SaaS%20testing%20files/Domain%20Datasets%20-%20Remote%20inters/Bank%20marketing/Bank%20marketing%20Compaign%20visualization%20(1)/Bank%20marketing%20Compaign%20visualization(1).csv"),[Delimiter=",", Columns=17, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"age", Int64.Type}, {"job", type text}, {"marital", type text}, {"education", type text}, {"default", type text}, {"balance", Int64.Type}, {"housing", type text}, {"loan", type text}, {"contact", type text}, {"day", Int64.Type}, {"month", type text}, {"duration", Int64.Type}, {"campaign", Int64.Type}, {"pdays", Int64.Type}, {"previous", Int64.Type}, {"poutcome", type text}, {"deposit", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

