table 'Sample - Superstore_Returns'
	lineageTag: 9d18bab5-e62b-47f3-9620-7697f15fd639

	column Returned
		dataType: string
		lineageTag: 3bbfb3b5-bbcb-4f25-90ad-598dd235e2e8
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 79a170c3-b991-4eef-8d1f-25a4442c8a9a
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	partition 'Sample - Superstore_Returns' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Returned" = "credit", #"Order ID" = 8512],
					        [#"Returned" = "dog", #"Order ID" = 7534],
					        [#"Returned" = "masters", #"Order ID" = 1458],
					        [#"Returned" = "reduction", #"Order ID" = 8241],
					        [#"Returned" = "portrait", #"Order ID" = 3093],
					        [#"Returned" = "gives", #"Order ID" = 7370],
					        [#"Returned" = "broke", #"Order ID" = 2718],
					        [#"Returned" = "outstanding", #"Order ID" = 5030],
					        [#"Returned" = "declared", #"Order ID" = 3543],
					        [#"Returned" = "tank", #"Order ID" = 9744],
					        [#"Returned" = "wooden", #"Order ID" = 6663],
					        [#"Returned" = "gulf", #"Order ID" = 2394],
					        [#"Returned" = "hey", #"Order ID" = 3426],
					        [#"Returned" = "displays", #"Order ID" = 9547],
					        [#"Returned" = "nj", #"Order ID" = 7118],
					        [#"Returned" = "shaved", #"Order ID" = 1380],
					        [#"Returned" = "yeah", #"Order ID" = 4993],
					        [#"Returned" = "literary", #"Order ID" = 3554],
					        [#"Returned" = "portions", #"Order ID" = 2348],
					        [#"Returned" = "catalogue", #"Order ID" = 6516],
					        [#"Returned" = "products", #"Order ID" = 4724],
					        [#"Returned" = "syndrome", #"Order ID" = 6996],
					        [#"Returned" = "indicators", #"Order ID" = 8309],
					        [#"Returned" = "glasgow", #"Order ID" = 1572],
					        [#"Returned" = "model", #"Order ID" = 2063],
					        [#"Returned" = "care", #"Order ID" = 6037],
					        [#"Returned" = "philippines", #"Order ID" = 4300],
					        [#"Returned" = "mail", #"Order ID" = 1716],
					        [#"Returned" = "equity", #"Order ID" = 2723],
					        [#"Returned" = "connecticut", #"Order ID" = 6638],
					        [#"Returned" = "china", #"Order ID" = 4084],
					        [#"Returned" = "licensed", #"Order ID" = 1032],
					        [#"Returned" = "shape", #"Order ID" = 5761],
					        [#"Returned" = "she", #"Order ID" = 8333],
					        [#"Returned" = "another", #"Order ID" = 6729],
					        [#"Returned" = "subscription", #"Order ID" = 7851],
					        [#"Returned" = "trained", #"Order ID" = 4667],
					        [#"Returned" = "operating", #"Order ID" = 7980],
					        [#"Returned" = "nature", #"Order ID" = 9047],
					        [#"Returned" = "shall", #"Order ID" = 7080],
					        [#"Returned" = "doc", #"Order ID" = 6441],
					        [#"Returned" = "february", #"Order ID" = 4773],
					        [#"Returned" = "pdt", #"Order ID" = 2471],
					        [#"Returned" = "dragon", #"Order ID" = 3575],
					        [#"Returned" = "feed", #"Order ID" = 1557],
					        [#"Returned" = "pentium", #"Order ID" = 5134],
					        [#"Returned" = "nature", #"Order ID" = 6607],
					        [#"Returned" = "minimal", #"Order ID" = 8933],
					        [#"Returned" = "sorted", #"Order ID" = 7981],
					        [#"Returned" = "trees", #"Order ID" = 9332],
					        [#"Returned" = "stick", #"Order ID" = 5763],
					        [#"Returned" = "execution", #"Order ID" = 4305],
					        [#"Returned" = "aid", #"Order ID" = 2517],
					        [#"Returned" = "collections", #"Order ID" = 8998],
					        [#"Returned" = "engineers", #"Order ID" = 4238],
					        [#"Returned" = "clip", #"Order ID" = 2789],
					        [#"Returned" = "edition", #"Order ID" = 5118],
					        [#"Returned" = "cp", #"Order ID" = 6101],
					        [#"Returned" = "faculty", #"Order ID" = 2203],
					        [#"Returned" = "ra", #"Order ID" = 5238],
					        [#"Returned" = "roses", #"Order ID" = 1126],
					        [#"Returned" = "patch", #"Order ID" = 3814],
					        [#"Returned" = "rf", #"Order ID" = 8386],
					        [#"Returned" = "biz", #"Order ID" = 4975],
					        [#"Returned" = "claimed", #"Order ID" = 8783],
					        [#"Returned" = "drawn", #"Order ID" = 4874],
					        [#"Returned" = "pocket", #"Order ID" = 4473],
					        [#"Returned" = "buy", #"Order ID" = 1988],
					        [#"Returned" = "oldest", #"Order ID" = 9060],
					        [#"Returned" = "larry", #"Order ID" = 4392],
					        [#"Returned" = "shower", #"Order ID" = 8779],
					        [#"Returned" = "israel", #"Order ID" = 1913],
					        [#"Returned" = "moved", #"Order ID" = 3536],
					        [#"Returned" = "lessons", #"Order ID" = 6052],
					        [#"Returned" = "great", #"Order ID" = 4316],
					        [#"Returned" = "variables", #"Order ID" = 7076],
					        [#"Returned" = "mine", #"Order ID" = 9604],
					        [#"Returned" = "cuba", #"Order ID" = 5197],
					        [#"Returned" = "assessment", #"Order ID" = 8820],
					        [#"Returned" = "accident", #"Order ID" = 6113],
					        [#"Returned" = "indexed", #"Order ID" = 9584],
					        [#"Returned" = "step", #"Order ID" = 2711],
					        [#"Returned" = "workplace", #"Order ID" = 9263],
					        [#"Returned" = "files", #"Order ID" = 7707],
					        [#"Returned" = "january", #"Order ID" = 7507],
					        [#"Returned" = "help", #"Order ID" = 7472],
					        [#"Returned" = "visible", #"Order ID" = 5297],
					        [#"Returned" = "cats", #"Order ID" = 1036],
					        [#"Returned" = "disney", #"Order ID" = 3390],
					        [#"Returned" = "pregnant", #"Order ID" = 8458],
					        [#"Returned" = "alice", #"Order ID" = 7569],
					        [#"Returned" = "authorized", #"Order ID" = 2082],
					        [#"Returned" = "edit", #"Order ID" = 3251],
					        [#"Returned" = "partnership", #"Order ID" = 7101],
					        [#"Returned" = "norton", #"Order ID" = 6132],
					        [#"Returned" = "sons", #"Order ID" = 9247],
					        [#"Returned" = "contained", #"Order ID" = 6421],
					        [#"Returned" = "agreement", #"Order ID" = 6520],
					        [#"Returned" = "charity", #"Order ID" = 3426],
					        [#"Returned" = "ne", #"Order ID" = 4509],
					        [#"Returned" = "jewish", #"Order ID" = 6547],
					        [#"Returned" = "marshall", #"Order ID" = 5920],
					        [#"Returned" = "fiber", #"Order ID" = 9405],
					        [#"Returned" = "eight", #"Order ID" = 4029],
					        [#"Returned" = "reporting", #"Order ID" = 4779],
					        [#"Returned" = "begins", #"Order ID" = 3384],
					        [#"Returned" = "capable", #"Order ID" = 7950],
					        [#"Returned" = "duty", #"Order ID" = 2548],
					        [#"Returned" = "morning", #"Order ID" = 9275],
					        [#"Returned" = "furniture", #"Order ID" = 7137],
					        [#"Returned" = "bread", #"Order ID" = 1479],
					        [#"Returned" = "wv", #"Order ID" = 2576],
					        [#"Returned" = "kb", #"Order ID" = 6321],
					        [#"Returned" = "partnership", #"Order ID" = 6948],
					        [#"Returned" = "body", #"Order ID" = 4869],
					        [#"Returned" = "securities", #"Order ID" = 7019],
					        [#"Returned" = "chamber", #"Order ID" = 8858],
					        [#"Returned" = "shoot", #"Order ID" = 5997],
					        [#"Returned" = "rf", #"Order ID" = 4811],
					        [#"Returned" = "php", #"Order ID" = 5594],
					        [#"Returned" = "lift", #"Order ID" = 4023],
					        [#"Returned" = "iowa", #"Order ID" = 9783],
					        [#"Returned" = "alien", #"Order ID" = 1757],
					        [#"Returned" = "practical", #"Order ID" = 5251],
					        [#"Returned" = "spend", #"Order ID" = 3252],
					        [#"Returned" = "pro", #"Order ID" = 5125],
					        [#"Returned" = "entry", #"Order ID" = 1758],
					        [#"Returned" = "cities", #"Order ID" = 2710],
					        [#"Returned" = "primarily", #"Order ID" = 1705],
					        [#"Returned" = "llc", #"Order ID" = 1606],
					        [#"Returned" = "objects", #"Order ID" = 5559],
					        [#"Returned" = "atmosphere", #"Order ID" = 7170],
					        [#"Returned" = "desert", #"Order ID" = 5602],
					        [#"Returned" = "minute", #"Order ID" = 1133],
					        [#"Returned" = "classes", #"Order ID" = 7261],
					        [#"Returned" = "crossing", #"Order ID" = 2391],
					        [#"Returned" = "percentage", #"Order ID" = 5291],
					        [#"Returned" = "national", #"Order ID" = 1801],
					        [#"Returned" = "combo", #"Order ID" = 1973],
					        [#"Returned" = "manager", #"Order ID" = 8508],
					        [#"Returned" = "highest", #"Order ID" = 2242],
					        [#"Returned" = "missed", #"Order ID" = 1902],
					        [#"Returned" = "ward", #"Order ID" = 1556],
					        [#"Returned" = "teen", #"Order ID" = 7694],
					        [#"Returned" = "tom", #"Order ID" = 8722],
					        [#"Returned" = "legislature", #"Order ID" = 1934],
					        [#"Returned" = "reputation", #"Order ID" = 2895],
					        [#"Returned" = "adds", #"Order ID" = 5075],
					        [#"Returned" = "mathematical", #"Order ID" = 6459],
					        [#"Returned" = "pool", #"Order ID" = 5530],
					        [#"Returned" = "thongs", #"Order ID" = 4900],
					        [#"Returned" = "cassette", #"Order ID" = 6151],
					        [#"Returned" = "supply", #"Order ID" = 3249],
					        [#"Returned" = "hampshire", #"Order ID" = 6072],
					        [#"Returned" = "covered", #"Order ID" = 2755],
					        [#"Returned" = "antonio", #"Order ID" = 4758],
					        [#"Returned" = "fiber", #"Order ID" = 6662],
					        [#"Returned" = "june", #"Order ID" = 2057],
					        [#"Returned" = "adams", #"Order ID" = 6406],
					        [#"Returned" = "classes", #"Order ID" = 1927],
					        [#"Returned" = "substances", #"Order ID" = 5083],
					        [#"Returned" = "syndrome", #"Order ID" = 1115],
					        [#"Returned" = "idea", #"Order ID" = 8752],
					        [#"Returned" = "believes", #"Order ID" = 8754],
					        [#"Returned" = "lines", #"Order ID" = 2858],
					        [#"Returned" = "ac", #"Order ID" = 4700],
					        [#"Returned" = "guess", #"Order ID" = 8641],
					        [#"Returned" = "constructed", #"Order ID" = 3601],
					        [#"Returned" = "glory", #"Order ID" = 8916],
					        [#"Returned" = "value", #"Order ID" = 5674],
					        [#"Returned" = "cards", #"Order ID" = 9574],
					        [#"Returned" = "deluxe", #"Order ID" = 7461],
					        [#"Returned" = "journey", #"Order ID" = 4124],
					        [#"Returned" = "charlotte", #"Order ID" = 8588],
					        [#"Returned" = "eye", #"Order ID" = 2407],
					        [#"Returned" = "speakers", #"Order ID" = 4599],
					        [#"Returned" = "operators", #"Order ID" = 6740],
					        [#"Returned" = "apply", #"Order ID" = 9908],
					        [#"Returned" = "drives", #"Order ID" = 7598],
					        [#"Returned" = "roger", #"Order ID" = 6723],
					        [#"Returned" = "shopping", #"Order ID" = 3729],
					        [#"Returned" = "semester", #"Order ID" = 5132],
					        [#"Returned" = "details", #"Order ID" = 4215],
					        [#"Returned" = "province", #"Order ID" = 9838],
					        [#"Returned" = "starring", #"Order ID" = 4772],
					        [#"Returned" = "desired", #"Order ID" = 2146],
					        [#"Returned" = "interview", #"Order ID" = 6911],
					        [#"Returned" = "concrete", #"Order ID" = 6130],
					        [#"Returned" = "frank", #"Order ID" = 6961],
					        [#"Returned" = "tickets", #"Order ID" = 6272],
					        [#"Returned" = "robinson", #"Order ID" = 4590],
					        [#"Returned" = "costs", #"Order ID" = 3084],
					        [#"Returned" = "rating", #"Order ID" = 5883],
					        [#"Returned" = "solutions", #"Order ID" = 2859],
					        [#"Returned" = "fresh", #"Order ID" = 6673],
					        [#"Returned" = "agriculture", #"Order ID" = 2635],
					        [#"Returned" = "michigan", #"Order ID" = 1784],
					        [#"Returned" = "theoretical", #"Order ID" = 8564],
					        [#"Returned" = "inspection", #"Order ID" = 2795],
					        [#"Returned" = "sri", #"Order ID" = 7020],
					        [#"Returned" = "tips", #"Order ID" = 9239],
					        [#"Returned" = "pieces", #"Order ID" = 3172],
					        [#"Returned" = "large", #"Order ID" = 2655],
					        [#"Returned" = "search", #"Order ID" = 3160],
					        [#"Returned" = "meaning", #"Order ID" = 1304],
					        [#"Returned" = "frames", #"Order ID" = 6488],
					        [#"Returned" = "chemistry", #"Order ID" = 2830],
					        [#"Returned" = "wisconsin", #"Order ID" = 2815],
					        [#"Returned" = "both", #"Order ID" = 6531],
					        [#"Returned" = "delay", #"Order ID" = 8188],
					        [#"Returned" = "however", #"Order ID" = 8274],
					        [#"Returned" = "mainly", #"Order ID" = 3100],
					        [#"Returned" = "amber", #"Order ID" = 8368],
					        [#"Returned" = "believed", #"Order ID" = 7199],
					        [#"Returned" = "unknown", #"Order ID" = 4625],
					        [#"Returned" = "terry", #"Order ID" = 8302],
					        [#"Returned" = "housewares", #"Order ID" = 5159],
					        [#"Returned" = "packard", #"Order ID" = 2928],
					        [#"Returned" = "vitamin", #"Order ID" = 3773],
					        [#"Returned" = "id", #"Order ID" = 9964],
					        [#"Returned" = "beads", #"Order ID" = 5012],
					        [#"Returned" = "yards", #"Order ID" = 5066],
					        [#"Returned" = "vital", #"Order ID" = 1920],
					        [#"Returned" = "dialogue", #"Order ID" = 1587],
					        [#"Returned" = "isp", #"Order ID" = 7856],
					        [#"Returned" = "matthew", #"Order ID" = 2503],
					        [#"Returned" = "rom", #"Order ID" = 5005],
					        [#"Returned" = "perhaps", #"Order ID" = 1541],
					        [#"Returned" = "red", #"Order ID" = 8118],
					        [#"Returned" = "gift", #"Order ID" = 5875],
					        [#"Returned" = "japanese", #"Order ID" = 3512],
					        [#"Returned" = "affiliate", #"Order ID" = 5799],
					        [#"Returned" = "overview", #"Order ID" = 5887],
					        [#"Returned" = "acceptable", #"Order ID" = 2231],
					        [#"Returned" = "burn", #"Order ID" = 3301],
					        [#"Returned" = "char", #"Order ID" = 8893],
					        [#"Returned" = "offers", #"Order ID" = 8022],
					        [#"Returned" = "king", #"Order ID" = 1729],
					        [#"Returned" = "graduate", #"Order ID" = 2708],
					        [#"Returned" = "families", #"Order ID" = 6921],
					        [#"Returned" = "infection", #"Order ID" = 9453],
					        [#"Returned" = "shirts", #"Order ID" = 8499],
					        [#"Returned" = "trademark", #"Order ID" = 1159],
					        [#"Returned" = "oh", #"Order ID" = 1323],
					        [#"Returned" = "meet", #"Order ID" = 2999],
					        [#"Returned" = "sole", #"Order ID" = 2996],
					        [#"Returned" = "status", #"Order ID" = 4868],
					        [#"Returned" = "dildos", #"Order ID" = 4707],
					        [#"Returned" = "air", #"Order ID" = 3264],
					        [#"Returned" = "mlb", #"Order ID" = 6144],
					        [#"Returned" = "shift", #"Order ID" = 1119],
					        [#"Returned" = "az", #"Order ID" = 7688],
					        [#"Returned" = "partnership", #"Order ID" = 4425],
					        [#"Returned" = "religion", #"Order ID" = 2213],
					        [#"Returned" = "done", #"Order ID" = 2239],
					        [#"Returned" = "allowing", #"Order ID" = 3931],
					        [#"Returned" = "experienced", #"Order ID" = 3170],
					        [#"Returned" = "applying", #"Order ID" = 3276],
					        [#"Returned" = "position", #"Order ID" = 7943],
					        [#"Returned" = "path", #"Order ID" = 3233],
					        [#"Returned" = "exp", #"Order ID" = 5447],
					        [#"Returned" = "loved", #"Order ID" = 6626],
					        [#"Returned" = "amp", #"Order ID" = 3783],
					        [#"Returned" = "rural", #"Order ID" = 2330],
					        [#"Returned" = "developments", #"Order ID" = 4971],
					        [#"Returned" = "questions", #"Order ID" = 9246],
					        [#"Returned" = "additions", #"Order ID" = 1150],
					        [#"Returned" = "classic", #"Order ID" = 5423],
					        [#"Returned" = "iran", #"Order ID" = 7465],
					        [#"Returned" = "remain", #"Order ID" = 5113],
					        [#"Returned" = "paul", #"Order ID" = 1195],
					        [#"Returned" = "inventory", #"Order ID" = 4124],
					        [#"Returned" = "schedules", #"Order ID" = 8854],
					        [#"Returned" = "color", #"Order ID" = 7254],
					        [#"Returned" = "charlotte", #"Order ID" = 4625],
					        [#"Returned" = "loan", #"Order ID" = 2553],
					        [#"Returned" = "evans", #"Order ID" = 6615],
					        [#"Returned" = "play", #"Order ID" = 1919],
					        [#"Returned" = "solutions", #"Order ID" = 6070],
					        [#"Returned" = "law", #"Order ID" = 6358],
					        [#"Returned" = "pick", #"Order ID" = 4898],
					        [#"Returned" = "heroes", #"Order ID" = 9328],
					        [#"Returned" = "czech", #"Order ID" = 2099],
					        [#"Returned" = "keys", #"Order ID" = 9698],
					        [#"Returned" = "caribbean", #"Order ID" = 1918],
					        [#"Returned" = "court", #"Order ID" = 2755],
					        [#"Returned" = "denied", #"Order ID" = 3320],
					        [#"Returned" = "administrator", #"Order ID" = 8741],
					        [#"Returned" = "banner", #"Order ID" = 8367],
					        [#"Returned" = "met", #"Order ID" = 1609],
					        [#"Returned" = "an", #"Order ID" = 9699],
					        [#"Returned" = "forward", #"Order ID" = 4807],
					        [#"Returned" = "edge", #"Order ID" = 8867],
					        [#"Returned" = "pointed", #"Order ID" = 7547],
					        [#"Returned" = "oak", #"Order ID" = 7197],
					        [#"Returned" = "concepts", #"Order ID" = 5507],
					        [#"Returned" = "individual", #"Order ID" = 5451],
					        [#"Returned" = "triple", #"Order ID" = 3684],
					        [#"Returned" = "young", #"Order ID" = 9178],
					        [#"Returned" = "certification", #"Order ID" = 3015],
					        [#"Returned" = "continued", #"Order ID" = 7268],
					        [#"Returned" = "error", #"Order ID" = 4247],
					        [#"Returned" = "header", #"Order ID" = 6169],
					        [#"Returned" = "boards", #"Order ID" = 4643],
					        [#"Returned" = "rio", #"Order ID" = 6991],
					        [#"Returned" = "bikes", #"Order ID" = 8292],
					        [#"Returned" = "care", #"Order ID" = 6236],
					        [#"Returned" = "caught", #"Order ID" = 1648],
					        [#"Returned" = "db", #"Order ID" = 9473],
					        [#"Returned" = "formed", #"Order ID" = 9561],
					        [#"Returned" = "increased", #"Order ID" = 2002],
					        [#"Returned" = "facing", #"Order ID" = 5871],
					        [#"Returned" = "prints", #"Order ID" = 8639],
					        [#"Returned" = "grass", #"Order ID" = 1330],
					        [#"Returned" = "ride", #"Order ID" = 7651],
					        [#"Returned" = "clinton", #"Order ID" = 5667],
					        [#"Returned" = "cup", #"Order ID" = 9414],
					        [#"Returned" = "completely", #"Order ID" = 3876],
					        [#"Returned" = "african", #"Order ID" = 6991],
					        [#"Returned" = "dogs", #"Order ID" = 7411],
					        [#"Returned" = "ending", #"Order ID" = 6287],
					        [#"Returned" = "covering", #"Order ID" = 6928],
					        [#"Returned" = "enrollment", #"Order ID" = 6950],
					        [#"Returned" = "names", #"Order ID" = 6828],
					        [#"Returned" = "irish", #"Order ID" = 3833],
					        [#"Returned" = "dj", #"Order ID" = 5921],
					        [#"Returned" = "decades", #"Order ID" = 3471],
					        [#"Returned" = "block", #"Order ID" = 6263],
					        [#"Returned" = "trained", #"Order ID" = 2954],
					        [#"Returned" = "picture", #"Order ID" = 5949],
					        [#"Returned" = "senior", #"Order ID" = 3388],
					        [#"Returned" = "musical", #"Order ID" = 7569],
					        [#"Returned" = "ai", #"Order ID" = 4599],
					        [#"Returned" = "farmer", #"Order ID" = 9125],
					        [#"Returned" = "inc", #"Order ID" = 6748],
					        [#"Returned" = "supply", #"Order ID" = 2900],
					        [#"Returned" = "cards", #"Order ID" = 9411],
					        [#"Returned" = "thousands", #"Order ID" = 2694],
					        [#"Returned" = "get", #"Order ID" = 7389],
					        [#"Returned" = "fl", #"Order ID" = 1805],
					        [#"Returned" = "newspapers", #"Order ID" = 7967],
					        [#"Returned" = "southern", #"Order ID" = 6300],
					        [#"Returned" = "burning", #"Order ID" = 4790],
					        [#"Returned" = "sponsor", #"Order ID" = 8958],
					        [#"Returned" = "steering", #"Order ID" = 4891],
					        [#"Returned" = "score", #"Order ID" = 4065],
					        [#"Returned" = "living", #"Order ID" = 5331],
					        [#"Returned" = "photos", #"Order ID" = 5163],
					        [#"Returned" = "immigration", #"Order ID" = 2791],
					        [#"Returned" = "jeff", #"Order ID" = 3966],
					        [#"Returned" = "transfers", #"Order ID" = 7167],
					        [#"Returned" = "peak", #"Order ID" = 7378],
					        [#"Returned" = "multi", #"Order ID" = 4333],
					        [#"Returned" = "disability", #"Order ID" = 1909],
					        [#"Returned" = "medium", #"Order ID" = 2891],
					        [#"Returned" = "age", #"Order ID" = 2227],
					        [#"Returned" = "blvd", #"Order ID" = 7544],
					        [#"Returned" = "drunk", #"Order ID" = 7295],
					        [#"Returned" = "mission", #"Order ID" = 8717],
					        [#"Returned" = "ross", #"Order ID" = 5781],
					        [#"Returned" = "burning", #"Order ID" = 6235],
					        [#"Returned" = "onto", #"Order ID" = 8271],
					        [#"Returned" = "odds", #"Order ID" = 4147],
					        [#"Returned" = "loan", #"Order ID" = 4548],
					        [#"Returned" = "decided", #"Order ID" = 2436],
					        [#"Returned" = "des", #"Order ID" = 4946],
					        [#"Returned" = "pierre", #"Order ID" = 7214],
					        [#"Returned" = "substantial", #"Order ID" = 7998],
					        [#"Returned" = "operational", #"Order ID" = 3830],
					        [#"Returned" = "ie", #"Order ID" = 7971],
					        [#"Returned" = "reserves", #"Order ID" = 2066],
					        [#"Returned" = "affect", #"Order ID" = 3987],
					        [#"Returned" = "ceo", #"Order ID" = 6673],
					        [#"Returned" = "flexibility", #"Order ID" = 7133],
					        [#"Returned" = "searches", #"Order ID" = 6615],
					        [#"Returned" = "implement", #"Order ID" = 3194],
					        [#"Returned" = "sensor", #"Order ID" = 7590],
					        [#"Returned" = "record", #"Order ID" = 8193],
					        [#"Returned" = "milwaukee", #"Order ID" = 9186],
					        [#"Returned" = "rice", #"Order ID" = 2127],
					        [#"Returned" = "thou", #"Order ID" = 9062],
					        [#"Returned" = "premium", #"Order ID" = 4040],
					        [#"Returned" = "residence", #"Order ID" = 3697],
					        [#"Returned" = "asset", #"Order ID" = 4148],
					        [#"Returned" = "rolling", #"Order ID" = 9955],
					        [#"Returned" = "finish", #"Order ID" = 6666],
					        [#"Returned" = "reality", #"Order ID" = 5782],
					        [#"Returned" = "questions", #"Order ID" = 5144],
					        [#"Returned" = "experience", #"Order ID" = 5583],
					        [#"Returned" = "font", #"Order ID" = 1874],
					        [#"Returned" = "require", #"Order ID" = 9419],
					        [#"Returned" = "professionals", #"Order ID" = 5780],
					        [#"Returned" = "teaching", #"Order ID" = 2457],
					        [#"Returned" = "mint", #"Order ID" = 5233],
					        [#"Returned" = "breaking", #"Order ID" = 2189],
					        [#"Returned" = "clinic", #"Order ID" = 6092],
					        [#"Returned" = "buyer", #"Order ID" = 8673],
					        [#"Returned" = "heavy", #"Order ID" = 9464],
					        [#"Returned" = "attractive", #"Order ID" = 2450],
					        [#"Returned" = "satisfied", #"Order ID" = 8276],
					        [#"Returned" = "outcomes", #"Order ID" = 7578],
					        [#"Returned" = "injuries", #"Order ID" = 3425],
					        [#"Returned" = "mins", #"Order ID" = 8487],
					        [#"Returned" = "irish", #"Order ID" = 5375],
					        [#"Returned" = "giant", #"Order ID" = 7279],
					        [#"Returned" = "allocated", #"Order ID" = 8641],
					        [#"Returned" = "array", #"Order ID" = 1262],
					        [#"Returned" = "somebody", #"Order ID" = 2101],
					        [#"Returned" = "covering", #"Order ID" = 2198],
					        [#"Returned" = "information", #"Order ID" = 1647],
					        [#"Returned" = "blog", #"Order ID" = 1950],
					        [#"Returned" = "lcd", #"Order ID" = 3930],
					        [#"Returned" = "five", #"Order ID" = 1367],
					        [#"Returned" = "consulting", #"Order ID" = 5878],
					        [#"Returned" = "population", #"Order ID" = 1962],
					        [#"Returned" = "su", #"Order ID" = 5378],
					        [#"Returned" = "voted", #"Order ID" = 5849],
					        [#"Returned" = "meet", #"Order ID" = 8382],
					        [#"Returned" = "comparison", #"Order ID" = 4972],
					        [#"Returned" = "bonus", #"Order ID" = 6993],
					        [#"Returned" = "opinions", #"Order ID" = 9679],
					        [#"Returned" = "pioneer", #"Order ID" = 5564],
					        [#"Returned" = "pour", #"Order ID" = 5280],
					        [#"Returned" = "submission", #"Order ID" = 3176],
					        [#"Returned" = "incredible", #"Order ID" = 4726],
					        [#"Returned" = "eminem", #"Order ID" = 8830],
					        [#"Returned" = "brother", #"Order ID" = 1234],
					        [#"Returned" = "sm", #"Order ID" = 4055],
					        [#"Returned" = "alive", #"Order ID" = 3706],
					        [#"Returned" = "true", #"Order ID" = 7844],
					        [#"Returned" = "ads", #"Order ID" = 2795],
					        [#"Returned" = "messages", #"Order ID" = 2505],
					        [#"Returned" = "ensuring", #"Order ID" = 4520],
					        [#"Returned" = "monday", #"Order ID" = 1559],
					        [#"Returned" = "run", #"Order ID" = 8516],
					        [#"Returned" = "outlook", #"Order ID" = 2437],
					        [#"Returned" = "shaved", #"Order ID" = 7552],
					        [#"Returned" = "resistant", #"Order ID" = 2246],
					        [#"Returned" = "reception", #"Order ID" = 1122],
					        [#"Returned" = "hill", #"Order ID" = 1770],
					        [#"Returned" = "adequate", #"Order ID" = 5826],
					        [#"Returned" = "affect", #"Order ID" = 4600],
					        [#"Returned" = "cosmetic", #"Order ID" = 2808],
					        [#"Returned" = "ceo", #"Order ID" = 2764],
					        [#"Returned" = "high", #"Order ID" = 3229],
					        [#"Returned" = "frames", #"Order ID" = 9071],
					        [#"Returned" = "fox", #"Order ID" = 6037],
					        [#"Returned" = "deliver", #"Order ID" = 1971],
					        [#"Returned" = "wooden", #"Order ID" = 5006],
					        [#"Returned" = "contacts", #"Order ID" = 9538],
					        [#"Returned" = "basis", #"Order ID" = 3490],
					        [#"Returned" = "oz", #"Order ID" = 5320],
					        [#"Returned" = "allows", #"Order ID" = 2633],
					        [#"Returned" = "cycle", #"Order ID" = 2191],
					        [#"Returned" = "pack", #"Order ID" = 5392],
					        [#"Returned" = "bluetooth", #"Order ID" = 2784],
					        [#"Returned" = "everyday", #"Order ID" = 1646],
					        [#"Returned" = "improvements", #"Order ID" = 2273],
					        [#"Returned" = "machine", #"Order ID" = 2216],
					        [#"Returned" = "loved", #"Order ID" = 6220],
					        [#"Returned" = "fell", #"Order ID" = 2102],
					        [#"Returned" = "safari", #"Order ID" = 7028],
					        [#"Returned" = "oclc", #"Order ID" = 4559],
					        [#"Returned" = "corn", #"Order ID" = 8156],
					        [#"Returned" = "flight", #"Order ID" = 3401],
					        [#"Returned" = "industry", #"Order ID" = 2693],
					        [#"Returned" = "recipe", #"Order ID" = 1355],
					        [#"Returned" = "actual", #"Order ID" = 2363],
					        [#"Returned" = "region", #"Order ID" = 6973],
					        [#"Returned" = "carol", #"Order ID" = 8540],
					        [#"Returned" = "same", #"Order ID" = 5432],
					        [#"Returned" = "wa", #"Order ID" = 2025],
					        [#"Returned" = "studies", #"Order ID" = 6971],
					        [#"Returned" = "pollution", #"Order ID" = 4572],
					        [#"Returned" = "nearby", #"Order ID" = 3431],
					        [#"Returned" = "sean", #"Order ID" = 9081],
					        [#"Returned" = "printers", #"Order ID" = 6753],
					        [#"Returned" = "stories", #"Order ID" = 7642],
					        [#"Returned" = "ghost", #"Order ID" = 4391],
					        [#"Returned" = "br", #"Order ID" = 3127],
					        [#"Returned" = "grounds", #"Order ID" = 2103],
					        [#"Returned" = "network", #"Order ID" = 2961],
					        [#"Returned" = "rating", #"Order ID" = 7651],
					        [#"Returned" = "rankings", #"Order ID" = 6827],
					        [#"Returned" = "sql", #"Order ID" = 8944],
					        [#"Returned" = "va", #"Order ID" = 9420],
					        [#"Returned" = "canada", #"Order ID" = 7701],
					        [#"Returned" = "herald", #"Order ID" = 5255],
					        [#"Returned" = "compliance", #"Order ID" = 2602],
					        [#"Returned" = "discussions", #"Order ID" = 5801],
					        [#"Returned" = "england", #"Order ID" = 6886],
					        [#"Returned" = "ordered", #"Order ID" = 8319],
					        [#"Returned" = "nearest", #"Order ID" = 7769],
					        [#"Returned" = "visible", #"Order ID" = 1724],
					        [#"Returned" = "fame", #"Order ID" = 2357],
					        [#"Returned" = "want", #"Order ID" = 3303],
					        [#"Returned" = "commonly", #"Order ID" = 3853],
					        [#"Returned" = "detail", #"Order ID" = 5580],
					        [#"Returned" = "wine", #"Order ID" = 6245],
					        [#"Returned" = "presentation", #"Order ID" = 7852]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Returned", type text},
					        {"Order ID", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table