table 'Sample - Superstore_People'
	lineageTag: c2d21c3e-f227-45b5-98bb-ffc6b5ba0f3a

	column Person
		dataType: string
		lineageTag: 02500439-7c1f-4e72-ac51-82b56b1685ec
		summarizeBy: none
		sourceColumn: Person

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 0f5d6cc1-4f8b-49e0-85ea-171209edda93
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition 'Sample - Superstore_People' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Person" = "sql", #"Region" = "Michigan"],
					        [#"Person" = "mary", #"Region" = "Tennessee"],
					        [#"Person" = "regarding", #"Region" = "New Mexico"],
					        [#"Person" = "factory", #"Region" = "Virginia"],
					        [#"Person" = "tough", #"Region" = "Kentucky"],
					        [#"Person" = "assigned", #"Region" = "Maryland"],
					        [#"Person" = "heights", #"Region" = "New Mexico"],
					        [#"Person" = "flu", #"Region" = "Arkansas"],
					        [#"Person" = "aud", #"Region" = "Washington"],
					        [#"Person" = "increase", #"Region" = "Hawaii"],
					        [#"Person" = "gospel", #"Region" = "Florida"],
					        [#"Person" = "successful", #"Region" = "South Carolina"],
					        [#"Person" = "recognize", #"Region" = "Iowa"],
					        [#"Person" = "builders", #"Region" = "Nevada"],
					        [#"Person" = "loved", #"Region" = "Louisiana"],
					        [#"Person" = "hey", #"Region" = "South Dakota"],
					        [#"Person" = "desktops", #"Region" = "Maine"],
					        [#"Person" = "opportunity", #"Region" = "Washington"],
					        [#"Person" = "dual", #"Region" = "Alaska"],
					        [#"Person" = "sons", #"Region" = "Wisconsin"],
					        [#"Person" = "funeral", #"Region" = "Texas"],
					        [#"Person" = "put", #"Region" = "New Jersey"],
					        [#"Person" = "bank", #"Region" = "Massachusetts"],
					        [#"Person" = "lighting", #"Region" = "Minnesota"],
					        [#"Person" = "balance", #"Region" = "Hawaii"],
					        [#"Person" = "zoo", #"Region" = "Tennessee"],
					        [#"Person" = "carriers", #"Region" = "West Virginia"],
					        [#"Person" = "otherwise", #"Region" = "Wyoming"],
					        [#"Person" = "formal", #"Region" = "North Carolina"],
					        [#"Person" = "lose", #"Region" = "Maryland"],
					        [#"Person" = "authentication", #"Region" = "Alabama"],
					        [#"Person" = "portions", #"Region" = "Alabama"],
					        [#"Person" = "panama", #"Region" = "Louisiana"],
					        [#"Person" = "maps", #"Region" = "Oregon"],
					        [#"Person" = "chemical", #"Region" = "Wisconsin"],
					        [#"Person" = "shorts", #"Region" = "Virginia"],
					        [#"Person" = "vacuum", #"Region" = "Virginia"],
					        [#"Person" = "ken", #"Region" = "South Dakota"],
					        [#"Person" = "maximum", #"Region" = "Arkansas"],
					        [#"Person" = "ea", #"Region" = "Connecticut"],
					        [#"Person" = "korea", #"Region" = "Massachusetts"],
					        [#"Person" = "trek", #"Region" = "Indiana"],
					        [#"Person" = "pleasure", #"Region" = "Nebraska"],
					        [#"Person" = "stop", #"Region" = "North Carolina"],
					        [#"Person" = "drinks", #"Region" = "Georgia"],
					        [#"Person" = "ga", #"Region" = "Georgia"],
					        [#"Person" = "week", #"Region" = "Hawaii"],
					        [#"Person" = "with", #"Region" = "Alaska"],
					        [#"Person" = "dependent", #"Region" = "Rhode Island"],
					        [#"Person" = "traveler", #"Region" = "Illinois"],
					        [#"Person" = "afford", #"Region" = "New Jersey"],
					        [#"Person" = "knew", #"Region" = "Iowa"],
					        [#"Person" = "di", #"Region" = "Arkansas"],
					        [#"Person" = "first", #"Region" = "West Virginia"],
					        [#"Person" = "southeast", #"Region" = "Arkansas"],
					        [#"Person" = "conclusion", #"Region" = "Montana"],
					        [#"Person" = "jewelry", #"Region" = "Alabama"],
					        [#"Person" = "syndrome", #"Region" = "Florida"],
					        [#"Person" = "likely", #"Region" = "Maryland"],
					        [#"Person" = "always", #"Region" = "Idaho"],
					        [#"Person" = "championship", #"Region" = "New Mexico"],
					        [#"Person" = "dallas", #"Region" = "Maryland"],
					        [#"Person" = "sc", #"Region" = "Delaware"],
					        [#"Person" = "starting", #"Region" = "Hawaii"],
					        [#"Person" = "cap", #"Region" = "Oklahoma"],
					        [#"Person" = "bag", #"Region" = "Maryland"],
					        [#"Person" = "annual", #"Region" = "New Jersey"],
					        [#"Person" = "xbox", #"Region" = "Idaho"],
					        [#"Person" = "facial", #"Region" = "Texas"],
					        [#"Person" = "return", #"Region" = "Virginia"],
					        [#"Person" = "emails", #"Region" = "Colorado"],
					        [#"Person" = "polyphonic", #"Region" = "West Virginia"],
					        [#"Person" = "bibliography", #"Region" = "Alabama"],
					        [#"Person" = "cooperation", #"Region" = "Delaware"],
					        [#"Person" = "roads", #"Region" = "South Dakota"],
					        [#"Person" = "end", #"Region" = "Arkansas"],
					        [#"Person" = "become", #"Region" = "Illinois"],
					        [#"Person" = "opposition", #"Region" = "Alabama"],
					        [#"Person" = "beginning", #"Region" = "Kentucky"],
					        [#"Person" = "hence", #"Region" = "Florida"],
					        [#"Person" = "toyota", #"Region" = "California"],
					        [#"Person" = "sold", #"Region" = "Washington"],
					        [#"Person" = "loans", #"Region" = "Washington"],
					        [#"Person" = "smile", #"Region" = "Virginia"],
					        [#"Person" = "processor", #"Region" = "New York"],
					        [#"Person" = "solution", #"Region" = "Montana"],
					        [#"Person" = "comfortable", #"Region" = "Indiana"],
					        [#"Person" = "scope", #"Region" = "Georgia"],
					        [#"Person" = "typical", #"Region" = "Ohio"],
					        [#"Person" = "bought", #"Region" = "Wyoming"],
					        [#"Person" = "automated", #"Region" = "Pennsylvania"],
					        [#"Person" = "statutory", #"Region" = "South Carolina"],
					        [#"Person" = "versus", #"Region" = "Texas"],
					        [#"Person" = "lee", #"Region" = "South Dakota"],
					        [#"Person" = "crew", #"Region" = "Georgia"],
					        [#"Person" = "ethernet", #"Region" = "Montana"],
					        [#"Person" = "intermediate", #"Region" = "North Carolina"],
					        [#"Person" = "maria", #"Region" = "South Dakota"],
					        [#"Person" = "humans", #"Region" = "Delaware"],
					        [#"Person" = "efficiency", #"Region" = "Michigan"],
					        [#"Person" = "acceptance", #"Region" = "Virginia"],
					        [#"Person" = "comfortable", #"Region" = "Pennsylvania"],
					        [#"Person" = "kb", #"Region" = "Massachusetts"],
					        [#"Person" = "excel", #"Region" = "Washington"],
					        [#"Person" = "signs", #"Region" = "New Hampshire"],
					        [#"Person" = "still", #"Region" = "Alabama"],
					        [#"Person" = "volume", #"Region" = "Wisconsin"],
					        [#"Person" = "lounge", #"Region" = "Nevada"],
					        [#"Person" = "manner", #"Region" = "Pennsylvania"],
					        [#"Person" = "husband", #"Region" = "Pennsylvania"],
					        [#"Person" = "larry", #"Region" = "Mississippi"],
					        [#"Person" = "diamonds", #"Region" = "Connecticut"],
					        [#"Person" = "southern", #"Region" = "Virginia"],
					        [#"Person" = "logic", #"Region" = "Oklahoma"],
					        [#"Person" = "melbourne", #"Region" = "Tennessee"],
					        [#"Person" = "support", #"Region" = "Illinois"],
					        [#"Person" = "counters", #"Region" = "Kentucky"],
					        [#"Person" = "tree", #"Region" = "Illinois"],
					        [#"Person" = "other", #"Region" = "New York"],
					        [#"Person" = "edition", #"Region" = "West Virginia"],
					        [#"Person" = "lamp", #"Region" = "South Dakota"],
					        [#"Person" = "regulatory", #"Region" = "Massachusetts"],
					        [#"Person" = "posts", #"Region" = "Nebraska"],
					        [#"Person" = "anywhere", #"Region" = "New Hampshire"],
					        [#"Person" = "flu", #"Region" = "Delaware"],
					        [#"Person" = "employee", #"Region" = "Idaho"],
					        [#"Person" = "real", #"Region" = "Georgia"],
					        [#"Person" = "domestic", #"Region" = "Missouri"],
					        [#"Person" = "hosted", #"Region" = "West Virginia"],
					        [#"Person" = "parks", #"Region" = "Pennsylvania"],
					        [#"Person" = "romance", #"Region" = "Ohio"],
					        [#"Person" = "cold", #"Region" = "Washington"],
					        [#"Person" = "holder", #"Region" = "Missouri"],
					        [#"Person" = "clubs", #"Region" = "South Dakota"],
					        [#"Person" = "interviews", #"Region" = "New York"],
					        [#"Person" = "hundreds", #"Region" = "North Carolina"],
					        [#"Person" = "sometimes", #"Region" = "Kansas"],
					        [#"Person" = "iraq", #"Region" = "Oregon"],
					        [#"Person" = "dc", #"Region" = "Mississippi"],
					        [#"Person" = "guaranteed", #"Region" = "Michigan"],
					        [#"Person" = "interest", #"Region" = "Vermont"],
					        [#"Person" = "bag", #"Region" = "Wisconsin"],
					        [#"Person" = "rocky", #"Region" = "Kansas"],
					        [#"Person" = "kinds", #"Region" = "Delaware"],
					        [#"Person" = "contract", #"Region" = "Nebraska"],
					        [#"Person" = "pending", #"Region" = "Rhode Island"],
					        [#"Person" = "baby", #"Region" = "Tennessee"],
					        [#"Person" = "kg", #"Region" = "West Virginia"],
					        [#"Person" = "dating", #"Region" = "Arkansas"],
					        [#"Person" = "rules", #"Region" = "Minnesota"],
					        [#"Person" = "for", #"Region" = "West Virginia"],
					        [#"Person" = "regarding", #"Region" = "Wyoming"],
					        [#"Person" = "however", #"Region" = "Wyoming"],
					        [#"Person" = "hong", #"Region" = "Louisiana"],
					        [#"Person" = "parts", #"Region" = "New Jersey"],
					        [#"Person" = "context", #"Region" = "Vermont"],
					        [#"Person" = "writes", #"Region" = "Wyoming"],
					        [#"Person" = "youth", #"Region" = "Rhode Island"],
					        [#"Person" = "na", #"Region" = "Vermont"],
					        [#"Person" = "wire", #"Region" = "Wisconsin"],
					        [#"Person" = "diseases", #"Region" = "California"],
					        [#"Person" = "cheese", #"Region" = "Maryland"],
					        [#"Person" = "beds", #"Region" = "Oregon"],
					        [#"Person" = "antique", #"Region" = "Minnesota"],
					        [#"Person" = "outcomes", #"Region" = "New Jersey"],
					        [#"Person" = "sponsor", #"Region" = "Nevada"],
					        [#"Person" = "cloudy", #"Region" = "Georgia"],
					        [#"Person" = "portion", #"Region" = "Hawaii"],
					        [#"Person" = "directions", #"Region" = "South Carolina"],
					        [#"Person" = "loss", #"Region" = "Texas"],
					        [#"Person" = "active", #"Region" = "Tennessee"],
					        [#"Person" = "unlike", #"Region" = "North Carolina"],
					        [#"Person" = "cad", #"Region" = "West Virginia"],
					        [#"Person" = "corrections", #"Region" = "Georgia"],
					        [#"Person" = "policies", #"Region" = "Vermont"],
					        [#"Person" = "computing", #"Region" = "Kansas"],
					        [#"Person" = "ph", #"Region" = "Arkansas"],
					        [#"Person" = "certificates", #"Region" = "Missouri"],
					        [#"Person" = "leisure", #"Region" = "Connecticut"],
					        [#"Person" = "sequence", #"Region" = "Oregon"],
					        [#"Person" = "various", #"Region" = "Nebraska"],
					        [#"Person" = "antique", #"Region" = "Connecticut"],
					        [#"Person" = "dark", #"Region" = "New Jersey"],
					        [#"Person" = "tab", #"Region" = "Arkansas"],
					        [#"Person" = "master", #"Region" = "Louisiana"],
					        [#"Person" = "walking", #"Region" = "Illinois"],
					        [#"Person" = "drawn", #"Region" = "Arkansas"],
					        [#"Person" = "drunk", #"Region" = "Iowa"],
					        [#"Person" = "ft", #"Region" = "Virginia"],
					        [#"Person" = "photographer", #"Region" = "New Mexico"],
					        [#"Person" = "fun", #"Region" = "Oregon"],
					        [#"Person" = "behavior", #"Region" = "North Carolina"],
					        [#"Person" = "serves", #"Region" = "New Hampshire"],
					        [#"Person" = "chip", #"Region" = "New Mexico"],
					        [#"Person" = "decide", #"Region" = "Ohio"],
					        [#"Person" = "potentially", #"Region" = "Kentucky"],
					        [#"Person" = "reservation", #"Region" = "Florida"],
					        [#"Person" = "effort", #"Region" = "Georgia"],
					        [#"Person" = "students", #"Region" = "Pennsylvania"],
					        [#"Person" = "soon", #"Region" = "Tennessee"],
					        [#"Person" = "lift", #"Region" = "Alaska"],
					        [#"Person" = "figure", #"Region" = "Wisconsin"],
					        [#"Person" = "compiled", #"Region" = "New Jersey"],
					        [#"Person" = "someone", #"Region" = "Indiana"],
					        [#"Person" = "move", #"Region" = "Kentucky"],
					        [#"Person" = "fine", #"Region" = "Pennsylvania"],
					        [#"Person" = "bay", #"Region" = "Washington"],
					        [#"Person" = "shirt", #"Region" = "Washington"],
					        [#"Person" = "cst", #"Region" = "Kentucky"],
					        [#"Person" = "xml", #"Region" = "Florida"],
					        [#"Person" = "huge", #"Region" = "Rhode Island"],
					        [#"Person" = "input", #"Region" = "New York"],
					        [#"Person" = "month", #"Region" = "Georgia"],
					        [#"Person" = "recently", #"Region" = "Oklahoma"],
					        [#"Person" = "ieee", #"Region" = "South Carolina"],
					        [#"Person" = "keith", #"Region" = "Maine"],
					        [#"Person" = "involves", #"Region" = "New Hampshire"],
					        [#"Person" = "donald", #"Region" = "Montana"],
					        [#"Person" = "whatever", #"Region" = "Connecticut"],
					        [#"Person" = "electrical", #"Region" = "Iowa"],
					        [#"Person" = "norton", #"Region" = "Louisiana"],
					        [#"Person" = "jonathan", #"Region" = "Florida"],
					        [#"Person" = "newsletter", #"Region" = "Idaho"],
					        [#"Person" = "syntax", #"Region" = "Oklahoma"],
					        [#"Person" = "unlimited", #"Region" = "Washington"],
					        [#"Person" = "big", #"Region" = "Tennessee"],
					        [#"Person" = "too", #"Region" = "Kansas"],
					        [#"Person" = "islam", #"Region" = "Minnesota"],
					        [#"Person" = "virginia", #"Region" = "Oklahoma"],
					        [#"Person" = "pci", #"Region" = "Iowa"],
					        [#"Person" = "opens", #"Region" = "Hawaii"],
					        [#"Person" = "devel", #"Region" = "Michigan"],
					        [#"Person" = "question", #"Region" = "Mississippi"],
					        [#"Person" = "streets", #"Region" = "Wyoming"],
					        [#"Person" = "ukraine", #"Region" = "Arkansas"],
					        [#"Person" = "audio", #"Region" = "Ohio"],
					        [#"Person" = "wire", #"Region" = "Virginia"],
					        [#"Person" = "developers", #"Region" = "Kansas"],
					        [#"Person" = "tube", #"Region" = "Oklahoma"],
					        [#"Person" = "avoid", #"Region" = "Ohio"],
					        [#"Person" = "css", #"Region" = "Georgia"],
					        [#"Person" = "who", #"Region" = "Oklahoma"],
					        [#"Person" = "situation", #"Region" = "Nevada"],
					        [#"Person" = "highlight", #"Region" = "Kansas"],
					        [#"Person" = "championship", #"Region" = "Iowa"],
					        [#"Person" = "suitable", #"Region" = "Wyoming"],
					        [#"Person" = "account", #"Region" = "Mississippi"],
					        [#"Person" = "array", #"Region" = "Mississippi"],
					        [#"Person" = "worth", #"Region" = "Oregon"],
					        [#"Person" = "dsl", #"Region" = "Indiana"],
					        [#"Person" = "lamp", #"Region" = "Texas"],
					        [#"Person" = "methods", #"Region" = "Virginia"],
					        [#"Person" = "film", #"Region" = "North Carolina"],
					        [#"Person" = "apply", #"Region" = "Montana"],
					        [#"Person" = "field", #"Region" = "Hawaii"],
					        [#"Person" = "primary", #"Region" = "Arizona"],
					        [#"Person" = "conventional", #"Region" = "Massachusetts"],
					        [#"Person" = "practices", #"Region" = "Oklahoma"],
					        [#"Person" = "unlimited", #"Region" = "Idaho"],
					        [#"Person" = "rivers", #"Region" = "Maryland"],
					        [#"Person" = "audience", #"Region" = "Mississippi"],
					        [#"Person" = "personality", #"Region" = "Delaware"],
					        [#"Person" = "while", #"Region" = "West Virginia"],
					        [#"Person" = "cad", #"Region" = "Colorado"],
					        [#"Person" = "emphasis", #"Region" = "Texas"],
					        [#"Person" = "twiki", #"Region" = "Hawaii"],
					        [#"Person" = "state", #"Region" = "Kansas"],
					        [#"Person" = "newspapers", #"Region" = "Idaho"],
					        [#"Person" = "himself", #"Region" = "Texas"],
					        [#"Person" = "tasks", #"Region" = "Louisiana"],
					        [#"Person" = "receives", #"Region" = "Iowa"],
					        [#"Person" = "presence", #"Region" = "Iowa"],
					        [#"Person" = "bug", #"Region" = "Arkansas"],
					        [#"Person" = "coins", #"Region" = "Arizona"],
					        [#"Person" = "robert", #"Region" = "Louisiana"],
					        [#"Person" = "roll", #"Region" = "Louisiana"],
					        [#"Person" = "san", #"Region" = "South Dakota"],
					        [#"Person" = "ns", #"Region" = "New York"],
					        [#"Person" = "green", #"Region" = "West Virginia"],
					        [#"Person" = "beach", #"Region" = "New York"],
					        [#"Person" = "sized", #"Region" = "Alabama"],
					        [#"Person" = "sales", #"Region" = "New Mexico"],
					        [#"Person" = "neil", #"Region" = "Missouri"],
					        [#"Person" = "cent", #"Region" = "Missouri"],
					        [#"Person" = "rapidly", #"Region" = "Maine"],
					        [#"Person" = "attempts", #"Region" = "New Hampshire"],
					        [#"Person" = "rental", #"Region" = "Wyoming"],
					        [#"Person" = "indianapolis", #"Region" = "Colorado"],
					        [#"Person" = "selection", #"Region" = "Louisiana"],
					        [#"Person" = "stick", #"Region" = "Ohio"],
					        [#"Person" = "dean", #"Region" = "Arizona"],
					        [#"Person" = "wilson", #"Region" = "Hawaii"],
					        [#"Person" = "arthur", #"Region" = "North Dakota"],
					        [#"Person" = "latina", #"Region" = "Montana"],
					        [#"Person" = "are", #"Region" = "Florida"],
					        [#"Person" = "still", #"Region" = "Massachusetts"],
					        [#"Person" = "question", #"Region" = "South Dakota"],
					        [#"Person" = "birth", #"Region" = "Montana"],
					        [#"Person" = "prepare", #"Region" = "Massachusetts"],
					        [#"Person" = "restoration", #"Region" = "Tennessee"],
					        [#"Person" = "loved", #"Region" = "Virginia"],
					        [#"Person" = "printed", #"Region" = "Connecticut"],
					        [#"Person" = "ltd", #"Region" = "Alaska"],
					        [#"Person" = "rs", #"Region" = "California"],
					        [#"Person" = "morning", #"Region" = "South Dakota"],
					        [#"Person" = "branch", #"Region" = "Arizona"],
					        [#"Person" = "michael", #"Region" = "Tennessee"],
					        [#"Person" = "productions", #"Region" = "Nebraska"],
					        [#"Person" = "view", #"Region" = "Wyoming"],
					        [#"Person" = "estimated", #"Region" = "Oregon"],
					        [#"Person" = "platinum", #"Region" = "North Dakota"],
					        [#"Person" = "commerce", #"Region" = "Kansas"],
					        [#"Person" = "prepare", #"Region" = "Tennessee"],
					        [#"Person" = "despite", #"Region" = "Delaware"],
					        [#"Person" = "raw", #"Region" = "West Virginia"],
					        [#"Person" = "mood", #"Region" = "Wisconsin"],
					        [#"Person" = "vancouver", #"Region" = "California"],
					        [#"Person" = "gender", #"Region" = "Alaska"],
					        [#"Person" = "merchant", #"Region" = "Georgia"],
					        [#"Person" = "february", #"Region" = "Nevada"],
					        [#"Person" = "deliver", #"Region" = "Hawaii"],
					        [#"Person" = "thank", #"Region" = "West Virginia"],
					        [#"Person" = "transaction", #"Region" = "New Jersey"],
					        [#"Person" = "nearby", #"Region" = "Washington"],
					        [#"Person" = "targeted", #"Region" = "New Jersey"],
					        [#"Person" = "composition", #"Region" = "New York"],
					        [#"Person" = "human", #"Region" = "Colorado"],
					        [#"Person" = "morgan", #"Region" = "Massachusetts"],
					        [#"Person" = "frank", #"Region" = "Indiana"],
					        [#"Person" = "roberts", #"Region" = "Alabama"],
					        [#"Person" = "politics", #"Region" = "Georgia"],
					        [#"Person" = "premier", #"Region" = "Kentucky"],
					        [#"Person" = "gifts", #"Region" = "Iowa"],
					        [#"Person" = "shadow", #"Region" = "California"],
					        [#"Person" = "billy", #"Region" = "Michigan"],
					        [#"Person" = "sad", #"Region" = "Rhode Island"],
					        [#"Person" = "td", #"Region" = "Colorado"],
					        [#"Person" = "sustainable", #"Region" = "Nebraska"],
					        [#"Person" = "night", #"Region" = "New York"],
					        [#"Person" = "spirit", #"Region" = "Idaho"],
					        [#"Person" = "kevin", #"Region" = "Arkansas"],
					        [#"Person" = "largely", #"Region" = "Alaska"],
					        [#"Person" = "signed", #"Region" = "Oklahoma"],
					        [#"Person" = "required", #"Region" = "Alabama"],
					        [#"Person" = "funded", #"Region" = "Maine"],
					        [#"Person" = "pet", #"Region" = "Pennsylvania"],
					        [#"Person" = "bio", #"Region" = "Tennessee"],
					        [#"Person" = "discounts", #"Region" = "Oklahoma"],
					        [#"Person" = "measured", #"Region" = "Texas"],
					        [#"Person" = "inspired", #"Region" = "California"],
					        [#"Person" = "grass", #"Region" = "Nebraska"],
					        [#"Person" = "lesson", #"Region" = "Iowa"],
					        [#"Person" = "areas", #"Region" = "California"],
					        [#"Person" = "south", #"Region" = "Alabama"],
					        [#"Person" = "infection", #"Region" = "Connecticut"],
					        [#"Person" = "clip", #"Region" = "Tennessee"],
					        [#"Person" = "pages", #"Region" = "New Mexico"],
					        [#"Person" = "essays", #"Region" = "Vermont"],
					        [#"Person" = "terms", #"Region" = "Kentucky"],
					        [#"Person" = "ground", #"Region" = "Georgia"],
					        [#"Person" = "carrier", #"Region" = "Wisconsin"],
					        [#"Person" = "nancy", #"Region" = "Vermont"],
					        [#"Person" = "associated", #"Region" = "Maryland"],
					        [#"Person" = "attempts", #"Region" = "Maryland"],
					        [#"Person" = "participating", #"Region" = "Maine"],
					        [#"Person" = "ensuring", #"Region" = "Pennsylvania"],
					        [#"Person" = "proof", #"Region" = "Louisiana"],
					        [#"Person" = "inspection", #"Region" = "Delaware"],
					        [#"Person" = "who", #"Region" = "Vermont"],
					        [#"Person" = "starts", #"Region" = "Minnesota"],
					        [#"Person" = "towns", #"Region" = "Pennsylvania"],
					        [#"Person" = "attended", #"Region" = "South Carolina"],
					        [#"Person" = "wireless", #"Region" = "Kentucky"],
					        [#"Person" = "information", #"Region" = "New York"],
					        [#"Person" = "along", #"Region" = "Wyoming"],
					        [#"Person" = "stadium", #"Region" = "Maine"],
					        [#"Person" = "gender", #"Region" = "New Mexico"],
					        [#"Person" = "were", #"Region" = "New Jersey"],
					        [#"Person" = "kenya", #"Region" = "California"],
					        [#"Person" = "anti", #"Region" = "Illinois"],
					        [#"Person" = "excess", #"Region" = "Kansas"],
					        [#"Person" = "grade", #"Region" = "Connecticut"],
					        [#"Person" = "beer", #"Region" = "Iowa"],
					        [#"Person" = "involving", #"Region" = "Kansas"],
					        [#"Person" = "guides", #"Region" = "Oregon"],
					        [#"Person" = "finished", #"Region" = "West Virginia"],
					        [#"Person" = "hell", #"Region" = "Mississippi"],
					        [#"Person" = "six", #"Region" = "Hawaii"],
					        [#"Person" = "shopper", #"Region" = "North Dakota"],
					        [#"Person" = "these", #"Region" = "Virginia"],
					        [#"Person" = "acrobat", #"Region" = "New Mexico"],
					        [#"Person" = "finance", #"Region" = "Idaho"],
					        [#"Person" = "stereo", #"Region" = "Nevada"],
					        [#"Person" = "recommend", #"Region" = "Tennessee"],
					        [#"Person" = "navigation", #"Region" = "Tennessee"],
					        [#"Person" = "nr", #"Region" = "New Jersey"],
					        [#"Person" = "if", #"Region" = "South Dakota"],
					        [#"Person" = "broker", #"Region" = "Maine"],
					        [#"Person" = "proceedings", #"Region" = "Utah"],
					        [#"Person" = "enlarge", #"Region" = "New Mexico"],
					        [#"Person" = "electronics", #"Region" = "West Virginia"],
					        [#"Person" = "per", #"Region" = "Tennessee"],
					        [#"Person" = "amazing", #"Region" = "Alabama"],
					        [#"Person" = "whether", #"Region" = "Missouri"],
					        [#"Person" = "faster", #"Region" = "North Carolina"],
					        [#"Person" = "until", #"Region" = "Connecticut"],
					        [#"Person" = "thing", #"Region" = "New Jersey"],
					        [#"Person" = "stability", #"Region" = "West Virginia"],
					        [#"Person" = "appendix", #"Region" = "Nebraska"],
					        [#"Person" = "sound", #"Region" = "New York"],
					        [#"Person" = "violent", #"Region" = "Nevada"],
					        [#"Person" = "carl", #"Region" = "North Dakota"],
					        [#"Person" = "lay", #"Region" = "Missouri"],
					        [#"Person" = "africa", #"Region" = "Arizona"],
					        [#"Person" = "kelly", #"Region" = "Nevada"],
					        [#"Person" = "clearly", #"Region" = "Kentucky"],
					        [#"Person" = "allocation", #"Region" = "Maryland"],
					        [#"Person" = "last", #"Region" = "Delaware"],
					        [#"Person" = "safari", #"Region" = "South Dakota"],
					        [#"Person" = "atlanta", #"Region" = "Nevada"],
					        [#"Person" = "protected", #"Region" = "Mississippi"],
					        [#"Person" = "motion", #"Region" = "Arkansas"],
					        [#"Person" = "fight", #"Region" = "Wisconsin"],
					        [#"Person" = "lesson", #"Region" = "North Dakota"],
					        [#"Person" = "continued", #"Region" = "Wisconsin"],
					        [#"Person" = "bears", #"Region" = "New Hampshire"],
					        [#"Person" = "saying", #"Region" = "Tennessee"],
					        [#"Person" = "corn", #"Region" = "Kansas"],
					        [#"Person" = "cafe", #"Region" = "Missouri"],
					        [#"Person" = "durham", #"Region" = "West Virginia"],
					        [#"Person" = "quote", #"Region" = "New York"],
					        [#"Person" = "interpretation", #"Region" = "Nebraska"],
					        [#"Person" = "answer", #"Region" = "Kentucky"],
					        [#"Person" = "protected", #"Region" = "Maryland"],
					        [#"Person" = "automobile", #"Region" = "New York"],
					        [#"Person" = "township", #"Region" = "Louisiana"],
					        [#"Person" = "find", #"Region" = "Oregon"],
					        [#"Person" = "ad", #"Region" = "Missouri"],
					        [#"Person" = "cf", #"Region" = "California"],
					        [#"Person" = "archives", #"Region" = "Missouri"],
					        [#"Person" = "diabetes", #"Region" = "Montana"],
					        [#"Person" = "stopped", #"Region" = "Nevada"],
					        [#"Person" = "row", #"Region" = "Hawaii"],
					        [#"Person" = "saved", #"Region" = "Kansas"],
					        [#"Person" = "pay", #"Region" = "South Carolina"],
					        [#"Person" = "local", #"Region" = "New Jersey"],
					        [#"Person" = "unit", #"Region" = "Tennessee"],
					        [#"Person" = "shopping", #"Region" = "North Dakota"],
					        [#"Person" = "forms", #"Region" = "Arkansas"],
					        [#"Person" = "within", #"Region" = "Louisiana"],
					        [#"Person" = "frequent", #"Region" = "Kansas"],
					        [#"Person" = "adjusted", #"Region" = "Oregon"],
					        [#"Person" = "vinyl", #"Region" = "Nebraska"],
					        [#"Person" = "intelligent", #"Region" = "New Jersey"],
					        [#"Person" = "cables", #"Region" = "Kansas"],
					        [#"Person" = "deadline", #"Region" = "Utah"],
					        [#"Person" = "syndrome", #"Region" = "Maryland"],
					        [#"Person" = "province", #"Region" = "Missouri"],
					        [#"Person" = "associations", #"Region" = "Virginia"],
					        [#"Person" = "supplied", #"Region" = "Georgia"],
					        [#"Person" = "write", #"Region" = "New Hampshire"],
					        [#"Person" = "trim", #"Region" = "Maine"],
					        [#"Person" = "extent", #"Region" = "New Mexico"],
					        [#"Person" = "remained", #"Region" = "Mississippi"],
					        [#"Person" = "dealtime", #"Region" = "Idaho"],
					        [#"Person" = "david", #"Region" = "South Dakota"],
					        [#"Person" = "option", #"Region" = "Massachusetts"],
					        [#"Person" = "thick", #"Region" = "Maryland"],
					        [#"Person" = "appeal", #"Region" = "Maine"],
					        [#"Person" = "fort", #"Region" = "Washington"],
					        [#"Person" = "less", #"Region" = "Colorado"],
					        [#"Person" = "comprehensive", #"Region" = "South Carolina"],
					        [#"Person" = "suggested", #"Region" = "Connecticut"],
					        [#"Person" = "thinking", #"Region" = "Minnesota"],
					        [#"Person" = "problems", #"Region" = "New Hampshire"],
					        [#"Person" = "promotion", #"Region" = "New Mexico"],
					        [#"Person" = "investing", #"Region" = "Connecticut"],
					        [#"Person" = "trends", #"Region" = "Nevada"],
					        [#"Person" = "call", #"Region" = "Rhode Island"],
					        [#"Person" = "military", #"Region" = "Rhode Island"],
					        [#"Person" = "employees", #"Region" = "Nevada"],
					        [#"Person" = "persons", #"Region" = "North Dakota"],
					        [#"Person" = "mainly", #"Region" = "Indiana"],
					        [#"Person" = "adequate", #"Region" = "Vermont"],
					        [#"Person" = "dates", #"Region" = "Mississippi"],
					        [#"Person" = "midnight", #"Region" = "Utah"],
					        [#"Person" = "subscription", #"Region" = "Delaware"],
					        [#"Person" = "tall", #"Region" = "Texas"],
					        [#"Person" = "explore", #"Region" = "Massachusetts"],
					        [#"Person" = "comparison", #"Region" = "North Carolina"],
					        [#"Person" = "folder", #"Region" = "Maryland"],
					        [#"Person" = "lamp", #"Region" = "Minnesota"],
					        [#"Person" = "bio", #"Region" = "Kentucky"],
					        [#"Person" = "individuals", #"Region" = "North Carolina"],
					        [#"Person" = "applicant", #"Region" = "North Dakota"],
					        [#"Person" = "sheet", #"Region" = "Nevada"],
					        [#"Person" = "mental", #"Region" = "Wyoming"],
					        [#"Person" = "advertising", #"Region" = "Missouri"],
					        [#"Person" = "asking", #"Region" = "Maine"],
					        [#"Person" = "happening", #"Region" = "Montana"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Person", type text},
					        {"Region", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table