table 'Orders (Sample - Superstore (1))'
	lineageTag: 33dfcf61-93ff-4fbe-83f7-9c84f9dc4b50

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 6c3db1af-a3da-43ed-8987-bf26a3e18e8d
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 2d3bd3cc-3245-451e-bfeb-a0dc4d952806
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: datetime
		lineageTag: 5aa8432c-eb72-4e28-a5fd-e769cfc32a0e
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: datetime
		lineageTag: 31b5b7cf-4e69-41e9-98ee-9c60b5466a46
		summarizeBy: none
		sourceColumn: 'Ship Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 62c71bc0-dbab-4fde-84f0-26843fe75fd2
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: cdb0c5ac-2a23-433b-9698-9c4aeeeaabc1
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 6289c432-907b-4c90-b001-e81168411e8a
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: b61243ae-cb31-40a8-84a8-474fc3c915a3
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: f6f1fe3f-2bd6-47f6-a390-2ef6bbc655fc
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: f2da46d4-9826-4bfd-8a6a-f1824a1f6e91
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: a7fa3098-28df-449c-b158-de7a62602c2c
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 57f716ad-128f-401b-b430-4ce992bcde13
		summarizeBy: sum
		sourceColumn: 'Postal Code'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: a28a4aa6-81d4-4862-89e7-14901c989ec3
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: a1f8af17-482a-448b-b953-4b87bd7addb3
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 544f610c-68aa-48c0-b2de-2e0c62d06ca9
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: bb348862-fc85-49cf-abd8-1257026f3adc
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 5c0203ed-9e3f-4aa4-b8b5-519286c1df76
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: General Number
		lineageTag: 0245e5df-16a8-4dd5-b02f-3d48c897ba9c
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 0c2289b9-644b-468e-a903-0e985872f9b7
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: General Number
		lineageTag: 223e8436-a737-48f6-90cd-d8257a979d21
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		formatString: General Number
		lineageTag: 4436d2a5-b8f5-4e7b-a735-3fd5dbb12bd2
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Calculation1 = SWITCH( TRUE(), 'Orders (Sample - Superstore (1))'[Category] = "Furniture", "furniture", 'Orders (Sample - Superstore (1))'[Category] = "Office Supplies", "office supplier", 'Orders (Sample - Superstore (1))'[Category] = "Technology", "technology", 'Orders (Sample - Superstore (1))'[Category] )
		lineageTag: a8efa4f8-9dad-4732-9bb7-d233a7cc7872
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Orders (Sample - Superstore (1))' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Row ID" = 4188, #"Order ID" = 8856, #"Order Date" = #date(2024, 5, 21), #"Ship Date" = #date(2020, 9, 15), #"Ship Mode" = "178.40.243.235", #"Customer ID" = 2644, #"Customer Name" = "Lashay Levy", #"Segment" = "improvement", #"Country" = "Thailand", #"City" = "Kettering", #"State" = "Iowa", #"Postal Code" = 569, #"Region" = "Oregon", #"Product ID" = 2181, #"Category" = "cards", #"Sub-Category" = "confirm", #"Product Name" = "Shala Thornton", #"Sales" = 427.53, #"Quantity" = 484, #"Discount" = 838.41, #"Profit" = 688.75],
					        [#"Row ID" = 3326, #"Order ID" = 4649, #"Order Date" = #date(2023, 3, 28), #"Ship Date" = #date(2024, 9, 19), #"Ship Mode" = "149.193.224.10", #"Customer ID" = 1805, #"Customer Name" = "Sirena Salinas", #"Segment" = "careful", #"Country" = "Philippines", #"City" = "Walnut Creek", #"State" = "Delaware", #"Postal Code" = 517, #"Region" = "Colorado", #"Product ID" = 3335, #"Category" = "recipes", #"Sub-Category" = "diameter", #"Product Name" = "Dan Hyde", #"Sales" = 827.74, #"Quantity" = 679, #"Discount" = 788.73, #"Profit" = 531.84],
					        [#"Row ID" = 9357, #"Order ID" = 6036, #"Order Date" = #date(2021, 8, 10), #"Ship Date" = #date(2021, 7, 11), #"Ship Mode" = "238.154.208.178", #"Customer ID" = 4582, #"Customer Name" = "Frankie Juarez", #"Segment" = "version", #"Country" = "Tokelau", #"City" = "Greenacres", #"State" = "Oregon", #"Postal Code" = 960, #"Region" = "West Virginia", #"Product ID" = 5807, #"Category" = "hip", #"Sub-Category" = "subscriber", #"Product Name" = "Brittni Prince", #"Sales" = 265.58, #"Quantity" = 309, #"Discount" = 47.98, #"Profit" = 682.45],
					        [#"Row ID" = 8075, #"Order ID" = 4427, #"Order Date" = #date(2021, 9, 4), #"Ship Date" = #date(2020, 10, 2), #"Ship Mode" = "110.165.10.176", #"Customer ID" = 4519, #"Customer Name" = "Lazaro Neal", #"Segment" = "density", #"Country" = "Dominica", #"City" = "Bellevue", #"State" = "Nevada", #"Postal Code" = 571, #"Region" = "California", #"Product ID" = 4777, #"Category" = "boat", #"Sub-Category" = "effect", #"Product Name" = "Audrie Williams", #"Sales" = 109.29, #"Quantity" = 156, #"Discount" = 631.86, #"Profit" = 87.24],
					        [#"Row ID" = 1892, #"Order ID" = 9863, #"Order Date" = #date(2021, 3, 2), #"Ship Date" = #date(2024, 8, 20), #"Ship Mode" = "228.98.15.157", #"Customer ID" = 8853, #"Customer Name" = "Bree Pacheco", #"Segment" = "sin", #"Country" = "Côte d’Ivoire", #"City" = "Russellville", #"State" = "South Dakota", #"Postal Code" = 846, #"Region" = "Nebraska", #"Product ID" = 7661, #"Category" = "terms", #"Sub-Category" = "soup", #"Product Name" = "Tobie Gray", #"Sales" = 138.96, #"Quantity" = 970, #"Discount" = 899.7, #"Profit" = 848.24]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Row ID", Int64.Type},
					        {"Order ID", type text},
					        {"Order Date", type date},
					        {"Ship Date", type date},
					        {"Ship Mode", type text},
					        {"Customer ID", type text},
					        {"Customer Name", type text},
					        {"Segment", type text},
					        {"Country", type text},
					        {"City", type text},
					        {"State", type text},
					        {"Postal Code", Int64.Type},
					        {"Region", type text},
					        {"Product ID", type text},
					        {"Category", type text},
					        {"Sub-Category", type text},
					        {"Product Name", type text},
					        {"Sales", type number},
					        {"Quantity", Int64.Type},
					        {"Discount", type number},
					        {"Profit", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table