table 'Profit Bin Size'
	lineageTag: d91984dc-9fe1-42f8-a7e7-8696293d25d3

	measure 'Profit Bin Size Value' = SELECTEDVALUE('Profit Bin Size'[Profit Bin Size], 50)
		lineageTag: 17cd45ae-b39d-4ec7-9289-d744c7372f2d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Profit Bin Size'
		dataType: double
		formatString: 0
		lineageTag: 8068e552-bab1-4527-9ed8-65cc7bb77ac0
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Profit Bin Size' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_Id = 7712d3f2c2934e9a84f28fd2ab0f0fef

