table 'Sample - Superstore_People'
	lineageTag: 5ccad2c6-aba0-4f3f-901a-e2e49e252ec1

	column 'Regional Manager'
		dataType: string
		lineageTag: 12843b79-f7d9-492c-ac9a-ccfa476ca40e
		summarizeBy: none
		sourceColumn: 'Regional Manager'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 9d940db0-dc29-41ad-888a-9be0f48d7f72
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition 'Sample - Superstore_People' = m
		mode: import
		source =
				let
					    Source = Csv.Document(
					        File.Contents("https://saastestlatest.blob.core.windows.net/saas-test-reports/Sample%20-%20Superstore_People.csv?se=2025-11-05T08%3A50%3A45Z&sp=r&sv=2025-11-05&sr=b&sig=BE5oHy8dmvsylyM7M1iMEuhWMiKpW62TDMKq2HaFJIU%3D"),
					        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
					    ),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Regional Manager", type text}, {"Region", type text}})
					in
					    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table