table 'Extract_Sheet1 (waffle template)'
	lineageTag: 5c1b13c5-f1e3-40c4-b084-1b5bc652aa8e

	column Row
		dataType: int64
		formatString: 0
		lineageTag: 7b58b1fd-d355-4d82-81ae-17a2b6e22561
		summarizeBy: sum
		sourceColumn: Row

		annotation SummarizationSetBy = Automatic

	column Column
		dataType: int64
		formatString: 0
		lineageTag: fa795706-743e-4e01-91f1-d60994eef5ed
		summarizeBy: sum
		sourceColumn: Column

		annotation SummarizationSetBy = Automatic

	column Percentage
		dataType: double
		formatString: General Number
		lineageTag: 5aaf618c-c382-45a0-a361-fdb7ccfc991f
		summarizeBy: sum
		sourceColumn: Percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Extract_Sheet1 (waffle template)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Row" = 367, #"Column" = 324, #"Percentage" = 82.58],
					        [#"Row" = 321, #"Column" = 237, #"Percentage" = 91.54],
					        [#"Row" = 992, #"Column" = 697, #"Percentage" = 5.04],
					        [#"Row" = 607, #"Column" = 414, #"Percentage" = 33.7],
					        [#"Row" = 385, #"Column" = 775, #"Percentage" = 93.42],
					        [#"Row" = 295, #"Column" = 760, #"Percentage" = 21.44],
					        [#"Row" = 732, #"Column" = 123, #"Percentage" = 86.47],
					        [#"Row" = 703, #"Column" = 528, #"Percentage" = 45.57],
					        [#"Row" = 289, #"Column" = 522, #"Percentage" = 1.29],
					        [#"Row" = 183, #"Column" = 714, #"Percentage" = 38.43],
					        [#"Row" = 14, #"Column" = 11, #"Percentage" = 22.06],
					        [#"Row" = 706, #"Column" = 940, #"Percentage" = 57.22],
					        [#"Row" = 981, #"Column" = 980, #"Percentage" = 53.88],
					        [#"Row" = 587, #"Column" = 153, #"Percentage" = 12.19],
					        [#"Row" = 911, #"Column" = 775, #"Percentage" = 83.38],
					        [#"Row" = 169, #"Column" = 709, #"Percentage" = 73.85],
					        [#"Row" = 397, #"Column" = 360, #"Percentage" = 12.81],
					        [#"Row" = 293, #"Column" = 155, #"Percentage" = 0.44],
					        [#"Row" = 393, #"Column" = 778, #"Percentage" = 64.17],
					        [#"Row" = 784, #"Column" = 847, #"Percentage" = 1.47],
					        [#"Row" = 228, #"Column" = 373, #"Percentage" = 79.24],
					        [#"Row" = 545, #"Column" = 252, #"Percentage" = 12.99],
					        [#"Row" = 237, #"Column" = 64, #"Percentage" = 76.96],
					        [#"Row" = 726, #"Column" = 298, #"Percentage" = 85.05],
					        [#"Row" = 936, #"Column" = 207, #"Percentage" = 47.27],
					        [#"Row" = 761, #"Column" = 98, #"Percentage" = 75.56],
					        [#"Row" = 444, #"Column" = 908, #"Percentage" = 44.95],
					        [#"Row" = 269, #"Column" = 939, #"Percentage" = 61.35],
					        [#"Row" = 553, #"Column" = 485, #"Percentage" = 21.77],
					        [#"Row" = 850, #"Column" = 584, #"Percentage" = 66.82],
					        [#"Row" = 819, #"Column" = 375, #"Percentage" = 99.22],
					        [#"Row" = 81, #"Column" = 679, #"Percentage" = 70.73],
					        [#"Row" = 460, #"Column" = 92, #"Percentage" = 27.36],
					        [#"Row" = 257, #"Column" = 582, #"Percentage" = 61.39],
					        [#"Row" = 811, #"Column" = 496, #"Percentage" = 69.64],
					        [#"Row" = 41, #"Column" = 664, #"Percentage" = 48.81],
					        [#"Row" = 633, #"Column" = 32, #"Percentage" = 84.67],
					        [#"Row" = 445, #"Column" = 302, #"Percentage" = 66.77],
					        [#"Row" = 170, #"Column" = 332, #"Percentage" = 14.86],
					        [#"Row" = 270, #"Column" = 685, #"Percentage" = 36.88],
					        [#"Row" = 879, #"Column" = 555, #"Percentage" = 78.83],
					        [#"Row" = 19, #"Column" = 391, #"Percentage" = 0.98],
					        [#"Row" = 421, #"Column" = 350, #"Percentage" = 45.1],
					        [#"Row" = 90, #"Column" = 596, #"Percentage" = 36.97],
					        [#"Row" = 33, #"Column" = 906, #"Percentage" = 1.2],
					        [#"Row" = 974, #"Column" = 531, #"Percentage" = 15.66],
					        [#"Row" = 539, #"Column" = 98, #"Percentage" = 16.7],
					        [#"Row" = 534, #"Column" = 565, #"Percentage" = 43.2],
					        [#"Row" = 628, #"Column" = 431, #"Percentage" = 24.93],
					        [#"Row" = 7, #"Column" = 368, #"Percentage" = 48.23],
					        [#"Row" = 680, #"Column" = 809, #"Percentage" = 44.48],
					        [#"Row" = 25, #"Column" = 401, #"Percentage" = 55.48],
					        [#"Row" = 444, #"Column" = 44, #"Percentage" = 61.02],
					        [#"Row" = 409, #"Column" = 963, #"Percentage" = 54.78],
					        [#"Row" = 354, #"Column" = 36, #"Percentage" = 17.17],
					        [#"Row" = 896, #"Column" = 751, #"Percentage" = 26.98],
					        [#"Row" = 986, #"Column" = 715, #"Percentage" = 58.14],
					        [#"Row" = 148, #"Column" = 448, #"Percentage" = 26.65],
					        [#"Row" = 637, #"Column" = 111, #"Percentage" = 37.86],
					        [#"Row" = 442, #"Column" = 696, #"Percentage" = 31.55],
					        [#"Row" = 406, #"Column" = 850, #"Percentage" = 37.48],
					        [#"Row" = 949, #"Column" = 13, #"Percentage" = 4.36],
					        [#"Row" = 875, #"Column" = 19, #"Percentage" = 29.84],
					        [#"Row" = 775, #"Column" = 37, #"Percentage" = 13.32],
					        [#"Row" = 269, #"Column" = 385, #"Percentage" = 73.51],
					        [#"Row" = 432, #"Column" = 65, #"Percentage" = 23.89],
					        [#"Row" = 496, #"Column" = 24, #"Percentage" = 64.29],
					        [#"Row" = 768, #"Column" = 569, #"Percentage" = 38.41],
					        [#"Row" = 701, #"Column" = 498, #"Percentage" = 52.45],
					        [#"Row" = 271, #"Column" = 573, #"Percentage" = 68.06],
					        [#"Row" = 406, #"Column" = 896, #"Percentage" = 80.31],
					        [#"Row" = 357, #"Column" = 719, #"Percentage" = 21.22],
					        [#"Row" = 367, #"Column" = 842, #"Percentage" = 13.49],
					        [#"Row" = 448, #"Column" = 478, #"Percentage" = 91.37],
					        [#"Row" = 153, #"Column" = 258, #"Percentage" = 9.39],
					        [#"Row" = 780, #"Column" = 233, #"Percentage" = 71.91],
					        [#"Row" = 993, #"Column" = 153, #"Percentage" = 3.6],
					        [#"Row" = 800, #"Column" = 812, #"Percentage" = 81.74],
					        [#"Row" = 823, #"Column" = 509, #"Percentage" = 42.73],
					        [#"Row" = 308, #"Column" = 65, #"Percentage" = 4.02],
					        [#"Row" = 439, #"Column" = 170, #"Percentage" = 46.95],
					        [#"Row" = 140, #"Column" = 936, #"Percentage" = 71.82],
					        [#"Row" = 871, #"Column" = 532, #"Percentage" = 37.7],
					        [#"Row" = 256, #"Column" = 769, #"Percentage" = 85.44],
					        [#"Row" = 901, #"Column" = 530, #"Percentage" = 58.21],
					        [#"Row" = 582, #"Column" = 162, #"Percentage" = 74.15],
					        [#"Row" = 534, #"Column" = 406, #"Percentage" = 94.02],
					        [#"Row" = 612, #"Column" = 321, #"Percentage" = 18.1],
					        [#"Row" = 406, #"Column" = 623, #"Percentage" = 40.32],
					        [#"Row" = 907, #"Column" = 425, #"Percentage" = 68.49],
					        [#"Row" = 754, #"Column" = 624, #"Percentage" = 98.31],
					        [#"Row" = 183, #"Column" = 742, #"Percentage" = 96.81],
					        [#"Row" = 148, #"Column" = 742, #"Percentage" = 15.46],
					        [#"Row" = 763, #"Column" = 276, #"Percentage" = 0.34],
					        [#"Row" = 400, #"Column" = 653, #"Percentage" = 8.8],
					        [#"Row" = 374, #"Column" = 283, #"Percentage" = 17.52],
					        [#"Row" = 891, #"Column" = 597, #"Percentage" = 42.21],
					        [#"Row" = 471, #"Column" = 254, #"Percentage" = 67.18],
					        [#"Row" = 838, #"Column" = 849, #"Percentage" = 12.84],
					        [#"Row" = 696, #"Column" = 212, #"Percentage" = 62.31],
					        [#"Row" = 480, #"Column" = 752, #"Percentage" = 37.8],
					        [#"Row" = 934, #"Column" = 550, #"Percentage" = 53.77],
					        [#"Row" = 475, #"Column" = 291, #"Percentage" = 28.11],
					        [#"Row" = 692, #"Column" = 378, #"Percentage" = 29.15],
					        [#"Row" = 280, #"Column" = 447, #"Percentage" = 74.32],
					        [#"Row" = 320, #"Column" = 979, #"Percentage" = 94.3],
					        [#"Row" = 991, #"Column" = 568, #"Percentage" = 21.29],
					        [#"Row" = 383, #"Column" = 124, #"Percentage" = 77.03],
					        [#"Row" = 331, #"Column" = 500, #"Percentage" = 62.65],
					        [#"Row" = 673, #"Column" = 669, #"Percentage" = 82.99],
					        [#"Row" = 590, #"Column" = 670, #"Percentage" = 76.56],
					        [#"Row" = 959, #"Column" = 390, #"Percentage" = 40.92],
					        [#"Row" = 688, #"Column" = 890, #"Percentage" = 57.54],
					        [#"Row" = 915, #"Column" = 58, #"Percentage" = 31.44],
					        [#"Row" = 451, #"Column" = 629, #"Percentage" = 44.46],
					        [#"Row" = 566, #"Column" = 566, #"Percentage" = 68.31],
					        [#"Row" = 269, #"Column" = 540, #"Percentage" = 1.69],
					        [#"Row" = 786, #"Column" = 182, #"Percentage" = 84.16],
					        [#"Row" = 901, #"Column" = 711, #"Percentage" = 27.97],
					        [#"Row" = 251, #"Column" = 721, #"Percentage" = 42.86],
					        [#"Row" = 264, #"Column" = 144, #"Percentage" = 26.5],
					        [#"Row" = 662, #"Column" = 44, #"Percentage" = 75.23],
					        [#"Row" = 361, #"Column" = 947, #"Percentage" = 97.23],
					        [#"Row" = 834, #"Column" = 943, #"Percentage" = 52.47],
					        [#"Row" = 672, #"Column" = 192, #"Percentage" = 18.19],
					        [#"Row" = 327, #"Column" = 117, #"Percentage" = 78.94],
					        [#"Row" = 262, #"Column" = 681, #"Percentage" = 87.51],
					        [#"Row" = 818, #"Column" = 959, #"Percentage" = 5.47],
					        [#"Row" = 782, #"Column" = 227, #"Percentage" = 92.19],
					        [#"Row" = 187, #"Column" = 78, #"Percentage" = 6.79],
					        [#"Row" = 504, #"Column" = 121, #"Percentage" = 12.08],
					        [#"Row" = 914, #"Column" = 863, #"Percentage" = 45.04],
					        [#"Row" = 375, #"Column" = 649, #"Percentage" = 87.65],
					        [#"Row" = 299, #"Column" = 892, #"Percentage" = 15.45],
					        [#"Row" = 152, #"Column" = 238, #"Percentage" = 30.82],
					        [#"Row" = 309, #"Column" = 9, #"Percentage" = 3.21],
					        [#"Row" = 310, #"Column" = 273, #"Percentage" = 99.82],
					        [#"Row" = 646, #"Column" = 352, #"Percentage" = 71.02],
					        [#"Row" = 24, #"Column" = 186, #"Percentage" = 62.61],
					        [#"Row" = 243, #"Column" = 118, #"Percentage" = 21.36],
					        [#"Row" = 959, #"Column" = 351, #"Percentage" = 41.15],
					        [#"Row" = 932, #"Column" = 720, #"Percentage" = 8.29],
					        [#"Row" = 344, #"Column" = 506, #"Percentage" = 69.64],
					        [#"Row" = 76, #"Column" = 103, #"Percentage" = 87.86],
					        [#"Row" = 564, #"Column" = 479, #"Percentage" = 59.27],
					        [#"Row" = 209, #"Column" = 684, #"Percentage" = 4.04],
					        [#"Row" = 489, #"Column" = 983, #"Percentage" = 89.59],
					        [#"Row" = 582, #"Column" = 376, #"Percentage" = 33.89],
					        [#"Row" = 140, #"Column" = 245, #"Percentage" = 32.12],
					        [#"Row" = 986, #"Column" = 649, #"Percentage" = 35.18],
					        [#"Row" = 746, #"Column" = 645, #"Percentage" = 62.15],
					        [#"Row" = 432, #"Column" = 402, #"Percentage" = 40.62],
					        [#"Row" = 777, #"Column" = 447, #"Percentage" = 25.9],
					        [#"Row" = 982, #"Column" = 55, #"Percentage" = 87.22],
					        [#"Row" = 405, #"Column" = 258, #"Percentage" = 92.34],
					        [#"Row" = 282, #"Column" = 639, #"Percentage" = 33.82],
					        [#"Row" = 929, #"Column" = 267, #"Percentage" = 26.17],
					        [#"Row" = 904, #"Column" = 991, #"Percentage" = 34.12],
					        [#"Row" = 577, #"Column" = 388, #"Percentage" = 99.59],
					        [#"Row" = 26, #"Column" = 31, #"Percentage" = 92.0],
					        [#"Row" = 631, #"Column" = 141, #"Percentage" = 1.76],
					        [#"Row" = 222, #"Column" = 621, #"Percentage" = 64.28],
					        [#"Row" = 858, #"Column" = 326, #"Percentage" = 19.92],
					        [#"Row" = 58, #"Column" = 351, #"Percentage" = 50.16],
					        [#"Row" = 660, #"Column" = 530, #"Percentage" = 26.53],
					        [#"Row" = 883, #"Column" = 154, #"Percentage" = 37.28],
					        [#"Row" = 931, #"Column" = 419, #"Percentage" = 16.46],
					        [#"Row" = 35, #"Column" = 203, #"Percentage" = 72.25],
					        [#"Row" = 33, #"Column" = 694, #"Percentage" = 26.22],
					        [#"Row" = 956, #"Column" = 875, #"Percentage" = 79.52],
					        [#"Row" = 987, #"Column" = 142, #"Percentage" = 82.56],
					        [#"Row" = 164, #"Column" = 880, #"Percentage" = 86.96],
					        [#"Row" = 509, #"Column" = 336, #"Percentage" = 48.09],
					        [#"Row" = 971, #"Column" = 639, #"Percentage" = 14.87],
					        [#"Row" = 487, #"Column" = 672, #"Percentage" = 42.71],
					        [#"Row" = 692, #"Column" = 411, #"Percentage" = 88.58],
					        [#"Row" = 46, #"Column" = 259, #"Percentage" = 15.74],
					        [#"Row" = 314, #"Column" = 427, #"Percentage" = 8.89],
					        [#"Row" = 413, #"Column" = 564, #"Percentage" = 7.84],
					        [#"Row" = 712, #"Column" = 77, #"Percentage" = 3.92],
					        [#"Row" = 501, #"Column" = 634, #"Percentage" = 43.15],
					        [#"Row" = 250, #"Column" = 176, #"Percentage" = 11.64],
					        [#"Row" = 424, #"Column" = 671, #"Percentage" = 59.25],
					        [#"Row" = 913, #"Column" = 785, #"Percentage" = 7.03],
					        [#"Row" = 524, #"Column" = 288, #"Percentage" = 23.4],
					        [#"Row" = 435, #"Column" = 18, #"Percentage" = 36.78],
					        [#"Row" = 485, #"Column" = 835, #"Percentage" = 44.92],
					        [#"Row" = 987, #"Column" = 493, #"Percentage" = 70.55],
					        [#"Row" = 336, #"Column" = 711, #"Percentage" = 11.55],
					        [#"Row" = 624, #"Column" = 69, #"Percentage" = 90.84],
					        [#"Row" = 118, #"Column" = 624, #"Percentage" = 61.88],
					        [#"Row" = 693, #"Column" = 867, #"Percentage" = 54.39],
					        [#"Row" = 78, #"Column" = 959, #"Percentage" = 99.35],
					        [#"Row" = 467, #"Column" = 458, #"Percentage" = 49.86],
					        [#"Row" = 850, #"Column" = 385, #"Percentage" = 68.84],
					        [#"Row" = 466, #"Column" = 9, #"Percentage" = 35.62],
					        [#"Row" = 620, #"Column" = 798, #"Percentage" = 78.95],
					        [#"Row" = 129, #"Column" = 395, #"Percentage" = 99.35],
					        [#"Row" = 153, #"Column" = 388, #"Percentage" = 66.79],
					        [#"Row" = 609, #"Column" = 158, #"Percentage" = 42.85],
					        [#"Row" = 137, #"Column" = 858, #"Percentage" = 89.46],
					        [#"Row" = 732, #"Column" = 300, #"Percentage" = 18.93],
					        [#"Row" = 560, #"Column" = 281, #"Percentage" = 54.64],
					        [#"Row" = 862, #"Column" = 616, #"Percentage" = 89.39],
					        [#"Row" = 313, #"Column" = 338, #"Percentage" = 69.13],
					        [#"Row" = 341, #"Column" = 996, #"Percentage" = 82.91],
					        [#"Row" = 547, #"Column" = 486, #"Percentage" = 52.89],
					        [#"Row" = 906, #"Column" = 127, #"Percentage" = 99.43],
					        [#"Row" = 761, #"Column" = 926, #"Percentage" = 99.35],
					        [#"Row" = 7, #"Column" = 3, #"Percentage" = 31.73],
					        [#"Row" = 448, #"Column" = 149, #"Percentage" = 75.09],
					        [#"Row" = 381, #"Column" = 344, #"Percentage" = 66.67],
					        [#"Row" = 379, #"Column" = 775, #"Percentage" = 93.8],
					        [#"Row" = 571, #"Column" = 513, #"Percentage" = 59.82],
					        [#"Row" = 554, #"Column" = 891, #"Percentage" = 24.16],
					        [#"Row" = 429, #"Column" = 965, #"Percentage" = 21.26],
					        [#"Row" = 914, #"Column" = 285, #"Percentage" = 41.67],
					        [#"Row" = 256, #"Column" = 610, #"Percentage" = 79.3],
					        [#"Row" = 949, #"Column" = 916, #"Percentage" = 22.13],
					        [#"Row" = 418, #"Column" = 216, #"Percentage" = 26.95],
					        [#"Row" = 765, #"Column" = 869, #"Percentage" = 66.09],
					        [#"Row" = 172, #"Column" = 462, #"Percentage" = 97.37],
					        [#"Row" = 245, #"Column" = 338, #"Percentage" = 5.51],
					        [#"Row" = 200, #"Column" = 501, #"Percentage" = 68.95],
					        [#"Row" = 536, #"Column" = 411, #"Percentage" = 73.23],
					        [#"Row" = 711, #"Column" = 980, #"Percentage" = 61.23],
					        [#"Row" = 404, #"Column" = 449, #"Percentage" = 90.26],
					        [#"Row" = 472, #"Column" = 734, #"Percentage" = 27.51],
					        [#"Row" = 500, #"Column" = 807, #"Percentage" = 85.19],
					        [#"Row" = 467, #"Column" = 563, #"Percentage" = 28.43],
					        [#"Row" = 253, #"Column" = 539, #"Percentage" = 73.55],
					        [#"Row" = 608, #"Column" = 559, #"Percentage" = 37.82],
					        [#"Row" = 236, #"Column" = 418, #"Percentage" = 79.34],
					        [#"Row" = 752, #"Column" = 327, #"Percentage" = 62.28],
					        [#"Row" = 238, #"Column" = 157, #"Percentage" = 20.55],
					        [#"Row" = 818, #"Column" = 621, #"Percentage" = 81.62],
					        [#"Row" = 461, #"Column" = 991, #"Percentage" = 39.07],
					        [#"Row" = 194, #"Column" = 637, #"Percentage" = 62.05],
					        [#"Row" = 56, #"Column" = 552, #"Percentage" = 2.53],
					        [#"Row" = 388, #"Column" = 476, #"Percentage" = 25.98],
					        [#"Row" = 925, #"Column" = 830, #"Percentage" = 68.94],
					        [#"Row" = 58, #"Column" = 172, #"Percentage" = 31.92],
					        [#"Row" = 523, #"Column" = 395, #"Percentage" = 77.84],
					        [#"Row" = 190, #"Column" = 377, #"Percentage" = 90.26],
					        [#"Row" = 507, #"Column" = 477, #"Percentage" = 52.0],
					        [#"Row" = 80, #"Column" = 240, #"Percentage" = 83.52],
					        [#"Row" = 68, #"Column" = 10, #"Percentage" = 69.45],
					        [#"Row" = 900, #"Column" = 178, #"Percentage" = 18.88],
					        [#"Row" = 56, #"Column" = 960, #"Percentage" = 63.61],
					        [#"Row" = 283, #"Column" = 539, #"Percentage" = 14.29],
					        [#"Row" = 266, #"Column" = 278, #"Percentage" = 83.32],
					        [#"Row" = 796, #"Column" = 570, #"Percentage" = 46.99],
					        [#"Row" = 712, #"Column" = 761, #"Percentage" = 53.65],
					        [#"Row" = 326, #"Column" = 840, #"Percentage" = 55.44],
					        [#"Row" = 1000, #"Column" = 439, #"Percentage" = 96.98],
					        [#"Row" = 462, #"Column" = 980, #"Percentage" = 57.32],
					        [#"Row" = 132, #"Column" = 359, #"Percentage" = 70.1],
					        [#"Row" = 340, #"Column" = 336, #"Percentage" = 47.28],
					        [#"Row" = 562, #"Column" = 380, #"Percentage" = 56.49],
					        [#"Row" = 205, #"Column" = 58, #"Percentage" = 73.0],
					        [#"Row" = 700, #"Column" = 699, #"Percentage" = 30.18],
					        [#"Row" = 442, #"Column" = 599, #"Percentage" = 94.15],
					        [#"Row" = 545, #"Column" = 958, #"Percentage" = 45.58],
					        [#"Row" = 543, #"Column" = 57, #"Percentage" = 51.23],
					        [#"Row" = 319, #"Column" = 111, #"Percentage" = 59.82],
					        [#"Row" = 199, #"Column" = 901, #"Percentage" = 22.73],
					        [#"Row" = 986, #"Column" = 996, #"Percentage" = 15.0],
					        [#"Row" = 69, #"Column" = 119, #"Percentage" = 23.09],
					        [#"Row" = 792, #"Column" = 161, #"Percentage" = 49.57],
					        [#"Row" = 651, #"Column" = 464, #"Percentage" = 2.62],
					        [#"Row" = 731, #"Column" = 252, #"Percentage" = 43.7],
					        [#"Row" = 783, #"Column" = 102, #"Percentage" = 65.6],
					        [#"Row" = 872, #"Column" = 585, #"Percentage" = 67.47],
					        [#"Row" = 940, #"Column" = 455, #"Percentage" = 57.06],
					        [#"Row" = 727, #"Column" = 733, #"Percentage" = 49.12],
					        [#"Row" = 125, #"Column" = 606, #"Percentage" = 6.74],
					        [#"Row" = 476, #"Column" = 34, #"Percentage" = 51.45],
					        [#"Row" = 384, #"Column" = 886, #"Percentage" = 13.66],
					        [#"Row" = 257, #"Column" = 314, #"Percentage" = 72.07],
					        [#"Row" = 815, #"Column" = 711, #"Percentage" = 72.75],
					        [#"Row" = 313, #"Column" = 941, #"Percentage" = 39.06],
					        [#"Row" = 84, #"Column" = 866, #"Percentage" = 57.49],
					        [#"Row" = 358, #"Column" = 306, #"Percentage" = 16.65],
					        [#"Row" = 120, #"Column" = 911, #"Percentage" = 84.34],
					        [#"Row" = 840, #"Column" = 180, #"Percentage" = 21.61],
					        [#"Row" = 148, #"Column" = 56, #"Percentage" = 29.3],
					        [#"Row" = 481, #"Column" = 50, #"Percentage" = 74.27],
					        [#"Row" = 978, #"Column" = 822, #"Percentage" = 16.59],
					        [#"Row" = 788, #"Column" = 254, #"Percentage" = 54.13],
					        [#"Row" = 783, #"Column" = 943, #"Percentage" = 31.21],
					        [#"Row" = 235, #"Column" = 406, #"Percentage" = 41.7],
					        [#"Row" = 724, #"Column" = 614, #"Percentage" = 98.47],
					        [#"Row" = 186, #"Column" = 170, #"Percentage" = 15.09],
					        [#"Row" = 981, #"Column" = 485, #"Percentage" = 30.94],
					        [#"Row" = 184, #"Column" = 912, #"Percentage" = 11.54],
					        [#"Row" = 918, #"Column" = 8, #"Percentage" = 48.52],
					        [#"Row" = 116, #"Column" = 554, #"Percentage" = 10.53],
					        [#"Row" = 512, #"Column" = 919, #"Percentage" = 15.94],
					        [#"Row" = 400, #"Column" = 115, #"Percentage" = 57.79],
					        [#"Row" = 134, #"Column" = 912, #"Percentage" = 96.77],
					        [#"Row" = 135, #"Column" = 600, #"Percentage" = 0.01],
					        [#"Row" = 200, #"Column" = 307, #"Percentage" = 63.85],
					        [#"Row" = 406, #"Column" = 249, #"Percentage" = 57.66],
					        [#"Row" = 373, #"Column" = 203, #"Percentage" = 52.03],
					        [#"Row" = 221, #"Column" = 597, #"Percentage" = 42.29],
					        [#"Row" = 773, #"Column" = 578, #"Percentage" = 73.08],
					        [#"Row" = 12, #"Column" = 783, #"Percentage" = 58.21],
					        [#"Row" = 861, #"Column" = 166, #"Percentage" = 62.62],
					        [#"Row" = 66, #"Column" = 579, #"Percentage" = 3.0],
					        [#"Row" = 805, #"Column" = 29, #"Percentage" = 0.15],
					        [#"Row" = 554, #"Column" = 275, #"Percentage" = 20.14],
					        [#"Row" = 473, #"Column" = 331, #"Percentage" = 88.89],
					        [#"Row" = 519, #"Column" = 658, #"Percentage" = 8.39],
					        [#"Row" = 716, #"Column" = 666, #"Percentage" = 9.56],
					        [#"Row" = 209, #"Column" = 357, #"Percentage" = 46.21],
					        [#"Row" = 598, #"Column" = 724, #"Percentage" = 52.18],
					        [#"Row" = 576, #"Column" = 759, #"Percentage" = 9.32],
					        [#"Row" = 139, #"Column" = 517, #"Percentage" = 69.59],
					        [#"Row" = 860, #"Column" = 400, #"Percentage" = 89.95],
					        [#"Row" = 854, #"Column" = 884, #"Percentage" = 47.71],
					        [#"Row" = 547, #"Column" = 624, #"Percentage" = 93.45],
					        [#"Row" = 28, #"Column" = 69, #"Percentage" = 99.35],
					        [#"Row" = 920, #"Column" = 886, #"Percentage" = 93.44],
					        [#"Row" = 315, #"Column" = 802, #"Percentage" = 75.83],
					        [#"Row" = 837, #"Column" = 198, #"Percentage" = 65.52],
					        [#"Row" = 792, #"Column" = 361, #"Percentage" = 69.07],
					        [#"Row" = 163, #"Column" = 400, #"Percentage" = 17.45],
					        [#"Row" = 367, #"Column" = 937, #"Percentage" = 36.29],
					        [#"Row" = 129, #"Column" = 609, #"Percentage" = 93.08],
					        [#"Row" = 176, #"Column" = 751, #"Percentage" = 5.49],
					        [#"Row" = 524, #"Column" = 793, #"Percentage" = 83.68],
					        [#"Row" = 897, #"Column" = 831, #"Percentage" = 59.84],
					        [#"Row" = 638, #"Column" = 270, #"Percentage" = 88.12],
					        [#"Row" = 708, #"Column" = 111, #"Percentage" = 98.4],
					        [#"Row" = 46, #"Column" = 648, #"Percentage" = 15.92],
					        [#"Row" = 24, #"Column" = 540, #"Percentage" = 31.25],
					        [#"Row" = 148, #"Column" = 860, #"Percentage" = 99.19],
					        [#"Row" = 433, #"Column" = 372, #"Percentage" = 52.74],
					        [#"Row" = 314, #"Column" = 741, #"Percentage" = 61.96],
					        [#"Row" = 459, #"Column" = 819, #"Percentage" = 77.7],
					        [#"Row" = 19, #"Column" = 294, #"Percentage" = 27.12],
					        [#"Row" = 262, #"Column" = 386, #"Percentage" = 99.57],
					        [#"Row" = 460, #"Column" = 529, #"Percentage" = 15.1],
					        [#"Row" = 121, #"Column" = 174, #"Percentage" = 85.88],
					        [#"Row" = 757, #"Column" = 88, #"Percentage" = 31.42],
					        [#"Row" = 867, #"Column" = 923, #"Percentage" = 2.86],
					        [#"Row" = 491, #"Column" = 61, #"Percentage" = 3.61],
					        [#"Row" = 766, #"Column" = 868, #"Percentage" = 78.1],
					        [#"Row" = 293, #"Column" = 713, #"Percentage" = 23.41],
					        [#"Row" = 417, #"Column" = 331, #"Percentage" = 73.07],
					        [#"Row" = 427, #"Column" = 651, #"Percentage" = 59.87],
					        [#"Row" = 474, #"Column" = 548, #"Percentage" = 17.73],
					        [#"Row" = 386, #"Column" = 204, #"Percentage" = 36.22],
					        [#"Row" = 130, #"Column" = 799, #"Percentage" = 47.74],
					        [#"Row" = 101, #"Column" = 489, #"Percentage" = 23.74],
					        [#"Row" = 505, #"Column" = 986, #"Percentage" = 5.78],
					        [#"Row" = 331, #"Column" = 606, #"Percentage" = 81.07],
					        [#"Row" = 318, #"Column" = 401, #"Percentage" = 53.1],
					        [#"Row" = 913, #"Column" = 782, #"Percentage" = 92.91],
					        [#"Row" = 831, #"Column" = 905, #"Percentage" = 12.79],
					        [#"Row" = 33, #"Column" = 747, #"Percentage" = 22.4],
					        [#"Row" = 375, #"Column" = 12, #"Percentage" = 8.51],
					        [#"Row" = 530, #"Column" = 740, #"Percentage" = 78.54],
					        [#"Row" = 90, #"Column" = 585, #"Percentage" = 94.88],
					        [#"Row" = 80, #"Column" = 775, #"Percentage" = 32.55],
					        [#"Row" = 653, #"Column" = 643, #"Percentage" = 31.92],
					        [#"Row" = 694, #"Column" = 472, #"Percentage" = 1.17],
					        [#"Row" = 155, #"Column" = 281, #"Percentage" = 82.78],
					        [#"Row" = 716, #"Column" = 302, #"Percentage" = 84.97],
					        [#"Row" = 543, #"Column" = 173, #"Percentage" = 27.76],
					        [#"Row" = 177, #"Column" = 597, #"Percentage" = 59.34],
					        [#"Row" = 911, #"Column" = 211, #"Percentage" = 80.56],
					        [#"Row" = 839, #"Column" = 460, #"Percentage" = 52.57],
					        [#"Row" = 426, #"Column" = 691, #"Percentage" = 55.94],
					        [#"Row" = 763, #"Column" = 300, #"Percentage" = 51.03],
					        [#"Row" = 816, #"Column" = 799, #"Percentage" = 3.7],
					        [#"Row" = 474, #"Column" = 118, #"Percentage" = 0.28],
					        [#"Row" = 493, #"Column" = 775, #"Percentage" = 1.4],
					        [#"Row" = 334, #"Column" = 389, #"Percentage" = 4.52],
					        [#"Row" = 544, #"Column" = 285, #"Percentage" = 27.67],
					        [#"Row" = 865, #"Column" = 33, #"Percentage" = 71.58],
					        [#"Row" = 325, #"Column" = 626, #"Percentage" = 83.88],
					        [#"Row" = 113, #"Column" = 911, #"Percentage" = 74.99],
					        [#"Row" = 91, #"Column" = 37, #"Percentage" = 29.63],
					        [#"Row" = 21, #"Column" = 192, #"Percentage" = 26.04],
					        [#"Row" = 226, #"Column" = 764, #"Percentage" = 62.99],
					        [#"Row" = 5, #"Column" = 799, #"Percentage" = 36.38],
					        [#"Row" = 37, #"Column" = 823, #"Percentage" = 12.76],
					        [#"Row" = 682, #"Column" = 132, #"Percentage" = 38.32],
					        [#"Row" = 633, #"Column" = 814, #"Percentage" = 36.6],
					        [#"Row" = 220, #"Column" = 344, #"Percentage" = 8.61],
					        [#"Row" = 247, #"Column" = 187, #"Percentage" = 77.39],
					        [#"Row" = 976, #"Column" = 902, #"Percentage" = 29.75],
					        [#"Row" = 173, #"Column" = 818, #"Percentage" = 40.73],
					        [#"Row" = 773, #"Column" = 706, #"Percentage" = 69.66],
					        [#"Row" = 987, #"Column" = 777, #"Percentage" = 94.17],
					        [#"Row" = 294, #"Column" = 622, #"Percentage" = 65.96],
					        [#"Row" = 522, #"Column" = 12, #"Percentage" = 83.1],
					        [#"Row" = 991, #"Column" = 425, #"Percentage" = 69.0],
					        [#"Row" = 280, #"Column" = 879, #"Percentage" = 16.08],
					        [#"Row" = 750, #"Column" = 256, #"Percentage" = 32.35],
					        [#"Row" = 778, #"Column" = 322, #"Percentage" = 33.09],
					        [#"Row" = 119, #"Column" = 114, #"Percentage" = 13.44],
					        [#"Row" = 883, #"Column" = 444, #"Percentage" = 1.38],
					        [#"Row" = 319, #"Column" = 976, #"Percentage" = 33.4],
					        [#"Row" = 519, #"Column" = 449, #"Percentage" = 84.62],
					        [#"Row" = 389, #"Column" = 598, #"Percentage" = 4.27],
					        [#"Row" = 53, #"Column" = 834, #"Percentage" = 38.46],
					        [#"Row" = 342, #"Column" = 489, #"Percentage" = 37.68],
					        [#"Row" = 511, #"Column" = 743, #"Percentage" = 89.2],
					        [#"Row" = 99, #"Column" = 59, #"Percentage" = 24.71],
					        [#"Row" = 92, #"Column" = 347, #"Percentage" = 68.4],
					        [#"Row" = 864, #"Column" = 963, #"Percentage" = 44.96],
					        [#"Row" = 464, #"Column" = 63, #"Percentage" = 46.49],
					        [#"Row" = 569, #"Column" = 17, #"Percentage" = 67.6],
					        [#"Row" = 436, #"Column" = 158, #"Percentage" = 52.68],
					        [#"Row" = 111, #"Column" = 426, #"Percentage" = 23.02],
					        [#"Row" = 52, #"Column" = 71, #"Percentage" = 75.72],
					        [#"Row" = 568, #"Column" = 131, #"Percentage" = 91.43],
					        [#"Row" = 565, #"Column" = 831, #"Percentage" = 48.36],
					        [#"Row" = 115, #"Column" = 729, #"Percentage" = 99.31],
					        [#"Row" = 602, #"Column" = 607, #"Percentage" = 84.5],
					        [#"Row" = 906, #"Column" = 368, #"Percentage" = 54.56],
					        [#"Row" = 326, #"Column" = 60, #"Percentage" = 58.94],
					        [#"Row" = 882, #"Column" = 216, #"Percentage" = 51.68],
					        [#"Row" = 293, #"Column" = 389, #"Percentage" = 39.93],
					        [#"Row" = 728, #"Column" = 687, #"Percentage" = 68.14],
					        [#"Row" = 25, #"Column" = 18, #"Percentage" = 90.46],
					        [#"Row" = 724, #"Column" = 370, #"Percentage" = 13.47],
					        [#"Row" = 425, #"Column" = 160, #"Percentage" = 5.1],
					        [#"Row" = 574, #"Column" = 595, #"Percentage" = 9.13],
					        [#"Row" = 748, #"Column" = 270, #"Percentage" = 40.1],
					        [#"Row" = 48, #"Column" = 662, #"Percentage" = 2.8],
					        [#"Row" = 913, #"Column" = 497, #"Percentage" = 49.88],
					        [#"Row" = 98, #"Column" = 912, #"Percentage" = 62.01],
					        [#"Row" = 797, #"Column" = 82, #"Percentage" = 20.02],
					        [#"Row" = 209, #"Column" = 259, #"Percentage" = 88.56],
					        [#"Row" = 840, #"Column" = 364, #"Percentage" = 89.52],
					        [#"Row" = 501, #"Column" = 549, #"Percentage" = 23.95],
					        [#"Row" = 977, #"Column" = 394, #"Percentage" = 78.42],
					        [#"Row" = 45, #"Column" = 597, #"Percentage" = 62.13],
					        [#"Row" = 862, #"Column" = 567, #"Percentage" = 1.25],
					        [#"Row" = 137, #"Column" = 492, #"Percentage" = 4.07],
					        [#"Row" = 177, #"Column" = 219, #"Percentage" = 48.6],
					        [#"Row" = 398, #"Column" = 87, #"Percentage" = 44.26],
					        [#"Row" = 489, #"Column" = 102, #"Percentage" = 82.21],
					        [#"Row" = 789, #"Column" = 306, #"Percentage" = 46.06],
					        [#"Row" = 364, #"Column" = 631, #"Percentage" = 83.05],
					        [#"Row" = 289, #"Column" = 803, #"Percentage" = 45.15],
					        [#"Row" = 661, #"Column" = 7, #"Percentage" = 89.63],
					        [#"Row" = 375, #"Column" = 238, #"Percentage" = 58.55],
					        [#"Row" = 899, #"Column" = 763, #"Percentage" = 21.89],
					        [#"Row" = 541, #"Column" = 246, #"Percentage" = 5.36],
					        [#"Row" = 359, #"Column" = 974, #"Percentage" = 25.87],
					        [#"Row" = 333, #"Column" = 315, #"Percentage" = 0.1],
					        [#"Row" = 371, #"Column" = 309, #"Percentage" = 7.42],
					        [#"Row" = 669, #"Column" = 990, #"Percentage" = 80.82],
					        [#"Row" = 615, #"Column" = 635, #"Percentage" = 97.4],
					        [#"Row" = 738, #"Column" = 685, #"Percentage" = 70.19],
					        [#"Row" = 988, #"Column" = 653, #"Percentage" = 83.15],
					        [#"Row" = 918, #"Column" = 659, #"Percentage" = 42.81],
					        [#"Row" = 930, #"Column" = 294, #"Percentage" = 53.99],
					        [#"Row" = 910, #"Column" = 432, #"Percentage" = 11.79],
					        [#"Row" = 424, #"Column" = 978, #"Percentage" = 95.49],
					        [#"Row" = 191, #"Column" = 947, #"Percentage" = 38.47],
					        [#"Row" = 949, #"Column" = 404, #"Percentage" = 91.9],
					        [#"Row" = 6, #"Column" = 63, #"Percentage" = 70.25],
					        [#"Row" = 46, #"Column" = 92, #"Percentage" = 27.15],
					        [#"Row" = 559, #"Column" = 155, #"Percentage" = 23.39],
					        [#"Row" = 394, #"Column" = 773, #"Percentage" = 88.73],
					        [#"Row" = 431, #"Column" = 834, #"Percentage" = 86.58],
					        [#"Row" = 833, #"Column" = 880, #"Percentage" = 25.71],
					        [#"Row" = 299, #"Column" = 593, #"Percentage" = 79.31],
					        [#"Row" = 443, #"Column" = 682, #"Percentage" = 72.7],
					        [#"Row" = 441, #"Column" = 978, #"Percentage" = 15.02],
					        [#"Row" = 622, #"Column" = 21, #"Percentage" = 93.16],
					        [#"Row" = 166, #"Column" = 771, #"Percentage" = 63.3],
					        [#"Row" = 839, #"Column" = 362, #"Percentage" = 57.63],
					        [#"Row" = 721, #"Column" = 700, #"Percentage" = 32.51],
					        [#"Row" = 485, #"Column" = 646, #"Percentage" = 16.39],
					        [#"Row" = 149, #"Column" = 355, #"Percentage" = 17.0],
					        [#"Row" = 221, #"Column" = 9, #"Percentage" = 24.96],
					        [#"Row" = 913, #"Column" = 311, #"Percentage" = 28.66],
					        [#"Row" = 493, #"Column" = 292, #"Percentage" = 39.19],
					        [#"Row" = 717, #"Column" = 401, #"Percentage" = 71.78],
					        [#"Row" = 255, #"Column" = 456, #"Percentage" = 51.01],
					        [#"Row" = 580, #"Column" = 797, #"Percentage" = 6.81],
					        [#"Row" = 616, #"Column" = 837, #"Percentage" = 57.87],
					        [#"Row" = 672, #"Column" = 542, #"Percentage" = 97.31],
					        [#"Row" = 578, #"Column" = 949, #"Percentage" = 51.64],
					        [#"Row" = 620, #"Column" = 673, #"Percentage" = 76.13],
					        [#"Row" = 356, #"Column" = 976, #"Percentage" = 15.02],
					        [#"Row" = 569, #"Column" = 290, #"Percentage" = 6.3],
					        [#"Row" = 506, #"Column" = 372, #"Percentage" = 23.41],
					        [#"Row" = 494, #"Column" = 16, #"Percentage" = 75.28],
					        [#"Row" = 172, #"Column" = 181, #"Percentage" = 31.24],
					        [#"Row" = 471, #"Column" = 723, #"Percentage" = 97.36],
					        [#"Row" = 684, #"Column" = 23, #"Percentage" = 25.03],
					        [#"Row" = 420, #"Column" = 271, #"Percentage" = 94.24],
					        [#"Row" = 681, #"Column" = 902, #"Percentage" = 87.17]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Row", Int64.Type},
					        {"Column", Int64.Type},
					        {"Percentage", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table