table 'Extract_Sheet1 (radial_bar_chart_data)'
	lineageTag: 9c63b9ba-67d9-41af-b142-9170490468f5

	column StoreType
		dataType: string
		lineageTag: 445b0711-2042-490b-859e-38e813005a87
		summarizeBy: none
		sourceColumn: StoreType

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: c3545644-6820-478b-9135-18c9f4f96d2f
		summarizeBy: sum
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	column Ratio
		dataType: double
		formatString: General Number
		lineageTag: 7aa0641d-3b3f-403a-8df8-bdfad15f5485
		summarizeBy: sum
		sourceColumn: Ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Path
		dataType: int64
		formatString: 0
		lineageTag: 6a553075-7daf-4dcc-8f2b-6c3153167992
		summarizeBy: sum
		sourceColumn: Path

		annotation SummarizationSetBy = Automatic

	partition 'Extract_Sheet1 (radial_bar_chart_data)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"StoreType" = "bottom", #"Order" = 629, #"Ratio" = 54.54, #"Path" = 183],
					        [#"StoreType" = "earn", #"Order" = 973, #"Ratio" = 801.45, #"Path" = 51],
					        [#"StoreType" = "missouri", #"Order" = 87, #"Ratio" = 951.04, #"Path" = 640],
					        [#"StoreType" = "arabia", #"Order" = 751, #"Ratio" = 272.72, #"Path" = 795],
					        [#"StoreType" = "gap", #"Order" = 397, #"Ratio" = 872.33, #"Path" = 8],
					        [#"StoreType" = "posted", #"Order" = 882, #"Ratio" = 189.53, #"Path" = 45],
					        [#"StoreType" = "friends", #"Order" = 394, #"Ratio" = 104.95, #"Path" = 610],
					        [#"StoreType" = "secure", #"Order" = 1000, #"Ratio" = 96.42, #"Path" = 951],
					        [#"StoreType" = "flower", #"Order" = 680, #"Ratio" = 855.38, #"Path" = 67],
					        [#"StoreType" = "add", #"Order" = 218, #"Ratio" = 96.9, #"Path" = 313],
					        [#"StoreType" = "transformation", #"Order" = 684, #"Ratio" = 263.93, #"Path" = 216],
					        [#"StoreType" = "commit", #"Order" = 49, #"Ratio" = 480.15, #"Path" = 812],
					        [#"StoreType" = "wonder", #"Order" = 264, #"Ratio" = 9.86, #"Path" = 775],
					        [#"StoreType" = "nhl", #"Order" = 662, #"Ratio" = 889.26, #"Path" = 174],
					        [#"StoreType" = "find", #"Order" = 619, #"Ratio" = 748.09, #"Path" = 725],
					        [#"StoreType" = "asian", #"Order" = 970, #"Ratio" = 944.52, #"Path" = 739],
					        [#"StoreType" = "castle", #"Order" = 1000, #"Ratio" = 887.58, #"Path" = 127],
					        [#"StoreType" = "courses", #"Order" = 872, #"Ratio" = 465.4, #"Path" = 767],
					        [#"StoreType" = "backup", #"Order" = 182, #"Ratio" = 242.01, #"Path" = 991],
					        [#"StoreType" = "planned", #"Order" = 621, #"Ratio" = 330.0, #"Path" = 326],
					        [#"StoreType" = "represented", #"Order" = 576, #"Ratio" = 24.49, #"Path" = 295],
					        [#"StoreType" = "holders", #"Order" = 137, #"Ratio" = 881.76, #"Path" = 705],
					        [#"StoreType" = "copies", #"Order" = 810, #"Ratio" = 675.24, #"Path" = 683],
					        [#"StoreType" = "meters", #"Order" = 494, #"Ratio" = 643.97, #"Path" = 413],
					        [#"StoreType" = "antenna", #"Order" = 722, #"Ratio" = 519.34, #"Path" = 704],
					        [#"StoreType" = "sl", #"Order" = 267, #"Ratio" = 923.71, #"Path" = 690],
					        [#"StoreType" = "los", #"Order" = 71, #"Ratio" = 162.14, #"Path" = 794],
					        [#"StoreType" = "guest", #"Order" = 622, #"Ratio" = 907.15, #"Path" = 573],
					        [#"StoreType" = "th", #"Order" = 852, #"Ratio" = 224.78, #"Path" = 609],
					        [#"StoreType" = "break", #"Order" = 718, #"Ratio" = 475.52, #"Path" = 204],
					        [#"StoreType" = "interactions", #"Order" = 152, #"Ratio" = 474.16, #"Path" = 707],
					        [#"StoreType" = "ec", #"Order" = 238, #"Ratio" = 756.7, #"Path" = 195],
					        [#"StoreType" = "labs", #"Order" = 391, #"Ratio" = 452.12, #"Path" = 832],
					        [#"StoreType" = "acute", #"Order" = 56, #"Ratio" = 654.81, #"Path" = 22],
					        [#"StoreType" = "handheld", #"Order" = 23, #"Ratio" = 991.39, #"Path" = 168],
					        [#"StoreType" = "lenses", #"Order" = 139, #"Ratio" = 944.85, #"Path" = 2],
					        [#"StoreType" = "meets", #"Order" = 458, #"Ratio" = 760.66, #"Path" = 910],
					        [#"StoreType" = "independent", #"Order" = 384, #"Ratio" = 532.32, #"Path" = 114],
					        [#"StoreType" = "flexible", #"Order" = 405, #"Ratio" = 559.74, #"Path" = 362],
					        [#"StoreType" = "specialist", #"Order" = 528, #"Ratio" = 988.33, #"Path" = 435],
					        [#"StoreType" = "filter", #"Order" = 184, #"Ratio" = 600.87, #"Path" = 690],
					        [#"StoreType" = "blade", #"Order" = 959, #"Ratio" = 499.42, #"Path" = 875],
					        [#"StoreType" = "battle", #"Order" = 582, #"Ratio" = 158.6, #"Path" = 975],
					        [#"StoreType" = "persons", #"Order" = 273, #"Ratio" = 375.1, #"Path" = 668],
					        [#"StoreType" = "requires", #"Order" = 798, #"Ratio" = 369.31, #"Path" = 411],
					        [#"StoreType" = "theft", #"Order" = 48, #"Ratio" = 39.26, #"Path" = 301],
					        [#"StoreType" = "began", #"Order" = 832, #"Ratio" = 540.25, #"Path" = 634],
					        [#"StoreType" = "tall", #"Order" = 13, #"Ratio" = 157.28, #"Path" = 773],
					        [#"StoreType" = "bikini", #"Order" = 713, #"Ratio" = 69.24, #"Path" = 13],
					        [#"StoreType" = "del", #"Order" = 845, #"Ratio" = 744.33, #"Path" = 217],
					        [#"StoreType" = "cast", #"Order" = 889, #"Ratio" = 375.08, #"Path" = 486],
					        [#"StoreType" = "increasingly", #"Order" = 546, #"Ratio" = 328.6, #"Path" = 92],
					        [#"StoreType" = "communication", #"Order" = 528, #"Ratio" = 100.94, #"Path" = 149],
					        [#"StoreType" = "dating", #"Order" = 194, #"Ratio" = 504.5, #"Path" = 64],
					        [#"StoreType" = "respect", #"Order" = 691, #"Ratio" = 883.76, #"Path" = 660],
					        [#"StoreType" = "premium", #"Order" = 820, #"Ratio" = 60.7, #"Path" = 434],
					        [#"StoreType" = "due", #"Order" = 873, #"Ratio" = 343.09, #"Path" = 38],
					        [#"StoreType" = "experience", #"Order" = 299, #"Ratio" = 358.88, #"Path" = 711],
					        [#"StoreType" = "pre", #"Order" = 267, #"Ratio" = 553.96, #"Path" = 961],
					        [#"StoreType" = "writer", #"Order" = 368, #"Ratio" = 647.2, #"Path" = 646],
					        [#"StoreType" = "cookies", #"Order" = 97, #"Ratio" = 988.55, #"Path" = 584],
					        [#"StoreType" = "library", #"Order" = 413, #"Ratio" = 1.82, #"Path" = 780],
					        [#"StoreType" = "coal", #"Order" = 690, #"Ratio" = 997.55, #"Path" = 989],
					        [#"StoreType" = "capable", #"Order" = 14, #"Ratio" = 338.84, #"Path" = 75],
					        [#"StoreType" = "piano", #"Order" = 849, #"Ratio" = 569.36, #"Path" = 694],
					        [#"StoreType" = "pleasant", #"Order" = 890, #"Ratio" = 903.39, #"Path" = 530],
					        [#"StoreType" = "finger", #"Order" = 589, #"Ratio" = 840.1, #"Path" = 729],
					        [#"StoreType" = "broad", #"Order" = 987, #"Ratio" = 38.29, #"Path" = 370],
					        [#"StoreType" = "three", #"Order" = 641, #"Ratio" = 963.27, #"Path" = 282],
					        [#"StoreType" = "hb", #"Order" = 717, #"Ratio" = 391.68, #"Path" = 515],
					        [#"StoreType" = "pub", #"Order" = 194, #"Ratio" = 948.76, #"Path" = 284],
					        [#"StoreType" = "tools", #"Order" = 501, #"Ratio" = 570.66, #"Path" = 221],
					        [#"StoreType" = "assume", #"Order" = 858, #"Ratio" = 95.35, #"Path" = 590],
					        [#"StoreType" = "investor", #"Order" = 214, #"Ratio" = 108.29, #"Path" = 62],
					        [#"StoreType" = "core", #"Order" = 392, #"Ratio" = 326.33, #"Path" = 932],
					        [#"StoreType" = "evening", #"Order" = 503, #"Ratio" = 489.75, #"Path" = 290],
					        [#"StoreType" = "involve", #"Order" = 128, #"Ratio" = 781.18, #"Path" = 801],
					        [#"StoreType" = "array", #"Order" = 993, #"Ratio" = 444.73, #"Path" = 476],
					        [#"StoreType" = "utilities", #"Order" = 627, #"Ratio" = 609.94, #"Path" = 25],
					        [#"StoreType" = "compiled", #"Order" = 207, #"Ratio" = 699.6, #"Path" = 187],
					        [#"StoreType" = "parameter", #"Order" = 749, #"Ratio" = 548.2, #"Path" = 754],
					        [#"StoreType" = "portland", #"Order" = 322, #"Ratio" = 566.17, #"Path" = 340],
					        [#"StoreType" = "arrangements", #"Order" = 126, #"Ratio" = 982.05, #"Path" = 983],
					        [#"StoreType" = "refinance", #"Order" = 300, #"Ratio" = 527.08, #"Path" = 770],
					        [#"StoreType" = "christmas", #"Order" = 523, #"Ratio" = 261.07, #"Path" = 926],
					        [#"StoreType" = "test", #"Order" = 57, #"Ratio" = 263.16, #"Path" = 968],
					        [#"StoreType" = "independent", #"Order" = 304, #"Ratio" = 304.94, #"Path" = 626],
					        [#"StoreType" = "protocol", #"Order" = 174, #"Ratio" = 415.03, #"Path" = 856],
					        [#"StoreType" = "anderson", #"Order" = 209, #"Ratio" = 987.19, #"Path" = 649],
					        [#"StoreType" = "dennis", #"Order" = 559, #"Ratio" = 170.42, #"Path" = 934],
					        [#"StoreType" = "anybody", #"Order" = 914, #"Ratio" = 509.08, #"Path" = 161],
					        [#"StoreType" = "enhance", #"Order" = 246, #"Ratio" = 994.03, #"Path" = 22],
					        [#"StoreType" = "poster", #"Order" = 220, #"Ratio" = 421.94, #"Path" = 162],
					        [#"StoreType" = "searches", #"Order" = 235, #"Ratio" = 6.22, #"Path" = 579],
					        [#"StoreType" = "reads", #"Order" = 783, #"Ratio" = 597.94, #"Path" = 620],
					        [#"StoreType" = "pubmed", #"Order" = 560, #"Ratio" = 191.63, #"Path" = 820],
					        [#"StoreType" = "coordination", #"Order" = 575, #"Ratio" = 802.09, #"Path" = 304],
					        [#"StoreType" = "alexander", #"Order" = 364, #"Ratio" = 561.92, #"Path" = 168],
					        [#"StoreType" = "enrollment", #"Order" = 227, #"Ratio" = 208.51, #"Path" = 243],
					        [#"StoreType" = "ship", #"Order" = 878, #"Ratio" = 928.07, #"Path" = 226],
					        [#"StoreType" = "gloves", #"Order" = 193, #"Ratio" = 258.08, #"Path" = 659],
					        [#"StoreType" = "modem", #"Order" = 106, #"Ratio" = 629.45, #"Path" = 962],
					        [#"StoreType" = "rap", #"Order" = 638, #"Ratio" = 947.43, #"Path" = 291],
					        [#"StoreType" = "drive", #"Order" = 965, #"Ratio" = 608.46, #"Path" = 910],
					        [#"StoreType" = "industry", #"Order" = 678, #"Ratio" = 794.32, #"Path" = 373],
					        [#"StoreType" = "experiences", #"Order" = 726, #"Ratio" = 461.18, #"Path" = 728],
					        [#"StoreType" = "deck", #"Order" = 142, #"Ratio" = 157.33, #"Path" = 665],
					        [#"StoreType" = "exception", #"Order" = 931, #"Ratio" = 29.25, #"Path" = 28],
					        [#"StoreType" = "largest", #"Order" = 594, #"Ratio" = 300.07, #"Path" = 388],
					        [#"StoreType" = "biz", #"Order" = 341, #"Ratio" = 989.01, #"Path" = 833],
					        [#"StoreType" = "simple", #"Order" = 58, #"Ratio" = 876.7, #"Path" = 790],
					        [#"StoreType" = "prince", #"Order" = 311, #"Ratio" = 382.82, #"Path" = 529],
					        [#"StoreType" = "start", #"Order" = 486, #"Ratio" = 224.77, #"Path" = 797],
					        [#"StoreType" = "capital", #"Order" = 273, #"Ratio" = 458.45, #"Path" = 755],
					        [#"StoreType" = "cleaning", #"Order" = 833, #"Ratio" = 61.39, #"Path" = 905],
					        [#"StoreType" = "continental", #"Order" = 768, #"Ratio" = 534.48, #"Path" = 287],
					        [#"StoreType" = "expected", #"Order" = 503, #"Ratio" = 640.2, #"Path" = 18],
					        [#"StoreType" = "modification", #"Order" = 286, #"Ratio" = 701.65, #"Path" = 374],
					        [#"StoreType" = "democrats", #"Order" = 74, #"Ratio" = 863.2, #"Path" = 637],
					        [#"StoreType" = "tales", #"Order" = 895, #"Ratio" = 212.39, #"Path" = 906],
					        [#"StoreType" = "sweden", #"Order" = 261, #"Ratio" = 48.12, #"Path" = 943],
					        [#"StoreType" = "browser", #"Order" = 732, #"Ratio" = 859.97, #"Path" = 894],
					        [#"StoreType" = "allocated", #"Order" = 450, #"Ratio" = 912.68, #"Path" = 195],
					        [#"StoreType" = "lewis", #"Order" = 363, #"Ratio" = 278.93, #"Path" = 637],
					        [#"StoreType" = "pleasure", #"Order" = 152, #"Ratio" = 264.31, #"Path" = 323],
					        [#"StoreType" = "blind", #"Order" = 166, #"Ratio" = 651.12, #"Path" = 1000],
					        [#"StoreType" = "jan", #"Order" = 177, #"Ratio" = 214.48, #"Path" = 875],
					        [#"StoreType" = "residents", #"Order" = 933, #"Ratio" = 11.62, #"Path" = 672],
					        [#"StoreType" = "zus", #"Order" = 9, #"Ratio" = 932.85, #"Path" = 332],
					        [#"StoreType" = "take", #"Order" = 447, #"Ratio" = 829.69, #"Path" = 428],
					        [#"StoreType" = "never", #"Order" = 858, #"Ratio" = 928.21, #"Path" = 576],
					        [#"StoreType" = "motorola", #"Order" = 734, #"Ratio" = 143.86, #"Path" = 168],
					        [#"StoreType" = "approved", #"Order" = 214, #"Ratio" = 724.67, #"Path" = 634],
					        [#"StoreType" = "samples", #"Order" = 259, #"Ratio" = 361.11, #"Path" = 523],
					        [#"StoreType" = "morgan", #"Order" = 484, #"Ratio" = 345.33, #"Path" = 900],
					        [#"StoreType" = "sector", #"Order" = 360, #"Ratio" = 873.54, #"Path" = 396],
					        [#"StoreType" = "objectives", #"Order" = 597, #"Ratio" = 415.74, #"Path" = 271],
					        [#"StoreType" = "secondary", #"Order" = 94, #"Ratio" = 4.39, #"Path" = 329],
					        [#"StoreType" = "stem", #"Order" = 848, #"Ratio" = 506.7, #"Path" = 490],
					        [#"StoreType" = "traditional", #"Order" = 965, #"Ratio" = 780.94, #"Path" = 354],
					        [#"StoreType" = "fm", #"Order" = 780, #"Ratio" = 264.87, #"Path" = 786],
					        [#"StoreType" = "stupid", #"Order" = 178, #"Ratio" = 75.94, #"Path" = 416],
					        [#"StoreType" = "colleges", #"Order" = 420, #"Ratio" = 118.74, #"Path" = 1],
					        [#"StoreType" = "wars", #"Order" = 106, #"Ratio" = 460.37, #"Path" = 711],
					        [#"StoreType" = "hero", #"Order" = 201, #"Ratio" = 725.78, #"Path" = 969],
					        [#"StoreType" = "colleges", #"Order" = 439, #"Ratio" = 945.78, #"Path" = 510],
					        [#"StoreType" = "archived", #"Order" = 261, #"Ratio" = 540.61, #"Path" = 376],
					        [#"StoreType" = "polyphonic", #"Order" = 924, #"Ratio" = 337.04, #"Path" = 518],
					        [#"StoreType" = "piano", #"Order" = 450, #"Ratio" = 99.2, #"Path" = 818],
					        [#"StoreType" = "sony", #"Order" = 980, #"Ratio" = 86.46, #"Path" = 836],
					        [#"StoreType" = "temple", #"Order" = 339, #"Ratio" = 9.14, #"Path" = 758],
					        [#"StoreType" = "gender", #"Order" = 158, #"Ratio" = 339.93, #"Path" = 438],
					        [#"StoreType" = "strategic", #"Order" = 145, #"Ratio" = 437.41, #"Path" = 456],
					        [#"StoreType" = "outlook", #"Order" = 568, #"Ratio" = 472.87, #"Path" = 402],
					        [#"StoreType" = "samples", #"Order" = 777, #"Ratio" = 660.89, #"Path" = 77],
					        [#"StoreType" = "sweden", #"Order" = 83, #"Ratio" = 760.5, #"Path" = 180],
					        [#"StoreType" = "relatively", #"Order" = 506, #"Ratio" = 444.49, #"Path" = 606],
					        [#"StoreType" = "bearing", #"Order" = 844, #"Ratio" = 90.0, #"Path" = 617],
					        [#"StoreType" = "penalty", #"Order" = 805, #"Ratio" = 823.24, #"Path" = 650],
					        [#"StoreType" = "ticket", #"Order" = 10, #"Ratio" = 927.15, #"Path" = 287],
					        [#"StoreType" = "requests", #"Order" = 842, #"Ratio" = 768.89, #"Path" = 447],
					        [#"StoreType" = "ncaa", #"Order" = 707, #"Ratio" = 451.44, #"Path" = 760],
					        [#"StoreType" = "comes", #"Order" = 338, #"Ratio" = 43.26, #"Path" = 573],
					        [#"StoreType" = "wealth", #"Order" = 230, #"Ratio" = 422.47, #"Path" = 955],
					        [#"StoreType" = "logos", #"Order" = 448, #"Ratio" = 955.96, #"Path" = 820],
					        [#"StoreType" = "attachment", #"Order" = 660, #"Ratio" = 443.62, #"Path" = 675],
					        [#"StoreType" = "hide", #"Order" = 32, #"Ratio" = 221.13, #"Path" = 405],
					        [#"StoreType" = "scheme", #"Order" = 643, #"Ratio" = 93.35, #"Path" = 846],
					        [#"StoreType" = "buildings", #"Order" = 132, #"Ratio" = 14.31, #"Path" = 63],
					        [#"StoreType" = "icons", #"Order" = 992, #"Ratio" = 176.72, #"Path" = 794],
					        [#"StoreType" = "interactions", #"Order" = 515, #"Ratio" = 450.6, #"Path" = 861],
					        [#"StoreType" = "described", #"Order" = 259, #"Ratio" = 720.13, #"Path" = 373],
					        [#"StoreType" = "lounge", #"Order" = 915, #"Ratio" = 639.3, #"Path" = 912],
					        [#"StoreType" = "fetish", #"Order" = 85, #"Ratio" = 680.76, #"Path" = 345],
					        [#"StoreType" = "tells", #"Order" = 135, #"Ratio" = 413.24, #"Path" = 403],
					        [#"StoreType" = "adobe", #"Order" = 804, #"Ratio" = 203.35, #"Path" = 540],
					        [#"StoreType" = "how", #"Order" = 800, #"Ratio" = 337.6, #"Path" = 253],
					        [#"StoreType" = "lay", #"Order" = 422, #"Ratio" = 195.78, #"Path" = 503],
					        [#"StoreType" = "looked", #"Order" = 397, #"Ratio" = 46.46, #"Path" = 637],
					        [#"StoreType" = "rights", #"Order" = 853, #"Ratio" = 785.34, #"Path" = 795],
					        [#"StoreType" = "simple", #"Order" = 716, #"Ratio" = 168.09, #"Path" = 784],
					        [#"StoreType" = "toward", #"Order" = 395, #"Ratio" = 697.18, #"Path" = 607],
					        [#"StoreType" = "journey", #"Order" = 617, #"Ratio" = 306.98, #"Path" = 801],
					        [#"StoreType" = "calendar", #"Order" = 137, #"Ratio" = 902.93, #"Path" = 623],
					        [#"StoreType" = "fabric", #"Order" = 556, #"Ratio" = 319.2, #"Path" = 85],
					        [#"StoreType" = "climate", #"Order" = 697, #"Ratio" = 565.32, #"Path" = 594],
					        [#"StoreType" = "libraries", #"Order" = 521, #"Ratio" = 102.18, #"Path" = 390],
					        [#"StoreType" = "regulatory", #"Order" = 473, #"Ratio" = 931.94, #"Path" = 527],
					        [#"StoreType" = "sign", #"Order" = 123, #"Ratio" = 803.17, #"Path" = 927],
					        [#"StoreType" = "easily", #"Order" = 556, #"Ratio" = 739.55, #"Path" = 509],
					        [#"StoreType" = "bi", #"Order" = 183, #"Ratio" = 579.83, #"Path" = 82],
					        [#"StoreType" = "analysis", #"Order" = 964, #"Ratio" = 7.33, #"Path" = 909],
					        [#"StoreType" = "louis", #"Order" = 66, #"Ratio" = 875.07, #"Path" = 845],
					        [#"StoreType" = "devil", #"Order" = 50, #"Ratio" = 164.7, #"Path" = 486],
					        [#"StoreType" = "bill", #"Order" = 96, #"Ratio" = 279.53, #"Path" = 266],
					        [#"StoreType" = "legal", #"Order" = 769, #"Ratio" = 361.75, #"Path" = 657],
					        [#"StoreType" = "sacramento", #"Order" = 845, #"Ratio" = 567.9, #"Path" = 96],
					        [#"StoreType" = "pressure", #"Order" = 670, #"Ratio" = 502.57, #"Path" = 16],
					        [#"StoreType" = "orders", #"Order" = 725, #"Ratio" = 27.43, #"Path" = 231],
					        [#"StoreType" = "amazing", #"Order" = 941, #"Ratio" = 507.23, #"Path" = 594],
					        [#"StoreType" = "wales", #"Order" = 563, #"Ratio" = 645.3, #"Path" = 3],
					        [#"StoreType" = "goals", #"Order" = 401, #"Ratio" = 530.76, #"Path" = 925],
					        [#"StoreType" = "drink", #"Order" = 322, #"Ratio" = 157.13, #"Path" = 361],
					        [#"StoreType" = "posting", #"Order" = 545, #"Ratio" = 597.71, #"Path" = 29],
					        [#"StoreType" = "cabinet", #"Order" = 821, #"Ratio" = 150.1, #"Path" = 824],
					        [#"StoreType" = "printable", #"Order" = 772, #"Ratio" = 155.25, #"Path" = 25],
					        [#"StoreType" = "border", #"Order" = 750, #"Ratio" = 235.32, #"Path" = 458],
					        [#"StoreType" = "playing", #"Order" = 285, #"Ratio" = 248.77, #"Path" = 94],
					        [#"StoreType" = "upon", #"Order" = 886, #"Ratio" = 778.38, #"Path" = 927],
					        [#"StoreType" = "democratic", #"Order" = 222, #"Ratio" = 145.68, #"Path" = 519],
					        [#"StoreType" = "itself", #"Order" = 237, #"Ratio" = 763.18, #"Path" = 611],
					        [#"StoreType" = "diameter", #"Order" = 267, #"Ratio" = 840.34, #"Path" = 915],
					        [#"StoreType" = "asian", #"Order" = 330, #"Ratio" = 846.7, #"Path" = 145],
					        [#"StoreType" = "size", #"Order" = 921, #"Ratio" = 418.43, #"Path" = 841],
					        [#"StoreType" = "stereo", #"Order" = 705, #"Ratio" = 956.11, #"Path" = 331],
					        [#"StoreType" = "francis", #"Order" = 780, #"Ratio" = 917.33, #"Path" = 123],
					        [#"StoreType" = "long", #"Order" = 546, #"Ratio" = 774.63, #"Path" = 257],
					        [#"StoreType" = "appear", #"Order" = 308, #"Ratio" = 824.42, #"Path" = 711],
					        [#"StoreType" = "hospital", #"Order" = 858, #"Ratio" = 688.08, #"Path" = 461],
					        [#"StoreType" = "removal", #"Order" = 409, #"Ratio" = 448.94, #"Path" = 300],
					        [#"StoreType" = "storm", #"Order" = 465, #"Ratio" = 821.88, #"Path" = 498],
					        [#"StoreType" = "messaging", #"Order" = 311, #"Ratio" = 421.89, #"Path" = 690],
					        [#"StoreType" = "sheet", #"Order" = 630, #"Ratio" = 946.66, #"Path" = 134],
					        [#"StoreType" = "directory", #"Order" = 570, #"Ratio" = 824.13, #"Path" = 432],
					        [#"StoreType" = "countries", #"Order" = 289, #"Ratio" = 484.83, #"Path" = 151],
					        [#"StoreType" = "japanese", #"Order" = 718, #"Ratio" = 767.55, #"Path" = 569],
					        [#"StoreType" = "ohio", #"Order" = 54, #"Ratio" = 283.35, #"Path" = 467],
					        [#"StoreType" = "hewlett", #"Order" = 119, #"Ratio" = 944.77, #"Path" = 375],
					        [#"StoreType" = "palestinian", #"Order" = 837, #"Ratio" = 346.32, #"Path" = 526],
					        [#"StoreType" = "websites", #"Order" = 357, #"Ratio" = 243.45, #"Path" = 91],
					        [#"StoreType" = "truth", #"Order" = 602, #"Ratio" = 402.72, #"Path" = 139],
					        [#"StoreType" = "effect", #"Order" = 223, #"Ratio" = 532.01, #"Path" = 783],
					        [#"StoreType" = "nose", #"Order" = 424, #"Ratio" = 921.99, #"Path" = 153],
					        [#"StoreType" = "years", #"Order" = 975, #"Ratio" = 973.96, #"Path" = 520],
					        [#"StoreType" = "downloads", #"Order" = 63, #"Ratio" = 733.93, #"Path" = 730],
					        [#"StoreType" = "painted", #"Order" = 970, #"Ratio" = 727.01, #"Path" = 365],
					        [#"StoreType" = "clerk", #"Order" = 530, #"Ratio" = 48.97, #"Path" = 64],
					        [#"StoreType" = "eastern", #"Order" = 94, #"Ratio" = 422.09, #"Path" = 148],
					        [#"StoreType" = "assigned", #"Order" = 470, #"Ratio" = 293.77, #"Path" = 931],
					        [#"StoreType" = "pride", #"Order" = 723, #"Ratio" = 364.02, #"Path" = 824],
					        [#"StoreType" = "nelson", #"Order" = 402, #"Ratio" = 196.08, #"Path" = 640],
					        [#"StoreType" = "wing", #"Order" = 13, #"Ratio" = 606.04, #"Path" = 119],
					        [#"StoreType" = "russian", #"Order" = 325, #"Ratio" = 793.53, #"Path" = 207],
					        [#"StoreType" = "gordon", #"Order" = 634, #"Ratio" = 16.86, #"Path" = 926],
					        [#"StoreType" = "musical", #"Order" = 437, #"Ratio" = 290.17, #"Path" = 404],
					        [#"StoreType" = "consultants", #"Order" = 946, #"Ratio" = 809.74, #"Path" = 579],
					        [#"StoreType" = "writing", #"Order" = 952, #"Ratio" = 283.66, #"Path" = 668],
					        [#"StoreType" = "form", #"Order" = 992, #"Ratio" = 864.11, #"Path" = 669],
					        [#"StoreType" = "records", #"Order" = 361, #"Ratio" = 356.5, #"Path" = 423],
					        [#"StoreType" = "across", #"Order" = 896, #"Ratio" = 2.33, #"Path" = 758],
					        [#"StoreType" = "lift", #"Order" = 278, #"Ratio" = 574.9, #"Path" = 818],
					        [#"StoreType" = "eggs", #"Order" = 767, #"Ratio" = 693.82, #"Path" = 231],
					        [#"StoreType" = "weddings", #"Order" = 989, #"Ratio" = 808.37, #"Path" = 394],
					        [#"StoreType" = "album", #"Order" = 789, #"Ratio" = 871.2, #"Path" = 434],
					        [#"StoreType" = "nurse", #"Order" = 273, #"Ratio" = 593.89, #"Path" = 637],
					        [#"StoreType" = "enjoy", #"Order" = 608, #"Ratio" = 747.58, #"Path" = 777],
					        [#"StoreType" = "cheats", #"Order" = 761, #"Ratio" = 878.14, #"Path" = 524],
					        [#"StoreType" = "agenda", #"Order" = 512, #"Ratio" = 732.7, #"Path" = 211],
					        [#"StoreType" = "byte", #"Order" = 269, #"Ratio" = 368.92, #"Path" = 317],
					        [#"StoreType" = "essential", #"Order" = 621, #"Ratio" = 1.56, #"Path" = 253],
					        [#"StoreType" = "simply", #"Order" = 816, #"Ratio" = 465.99, #"Path" = 501],
					        [#"StoreType" = "cr", #"Order" = 764, #"Ratio" = 679.79, #"Path" = 300],
					        [#"StoreType" = "pocket", #"Order" = 637, #"Ratio" = 369.29, #"Path" = 717],
					        [#"StoreType" = "automobile", #"Order" = 778, #"Ratio" = 320.15, #"Path" = 590],
					        [#"StoreType" = "registered", #"Order" = 521, #"Ratio" = 195.17, #"Path" = 263],
					        [#"StoreType" = "portland", #"Order" = 77, #"Ratio" = 786.38, #"Path" = 567],
					        [#"StoreType" = "whom", #"Order" = 836, #"Ratio" = 36.98, #"Path" = 26],
					        [#"StoreType" = "profits", #"Order" = 279, #"Ratio" = 594.99, #"Path" = 209],
					        [#"StoreType" = "santa", #"Order" = 174, #"Ratio" = 857.74, #"Path" = 418],
					        [#"StoreType" = "lease", #"Order" = 307, #"Ratio" = 420.67, #"Path" = 295],
					        [#"StoreType" = "father", #"Order" = 448, #"Ratio" = 35.9, #"Path" = 373],
					        [#"StoreType" = "double", #"Order" = 384, #"Ratio" = 413.18, #"Path" = 38],
					        [#"StoreType" = "wants", #"Order" = 712, #"Ratio" = 684.03, #"Path" = 279],
					        [#"StoreType" = "richmond", #"Order" = 302, #"Ratio" = 701.88, #"Path" = 322],
					        [#"StoreType" = "establish", #"Order" = 194, #"Ratio" = 932.88, #"Path" = 650],
					        [#"StoreType" = "machines", #"Order" = 492, #"Ratio" = 539.01, #"Path" = 207],
					        [#"StoreType" = "racing", #"Order" = 35, #"Ratio" = 230.24, #"Path" = 663],
					        [#"StoreType" = "odd", #"Order" = 115, #"Ratio" = 389.17, #"Path" = 498],
					        [#"StoreType" = "addresses", #"Order" = 181, #"Ratio" = 147.14, #"Path" = 992],
					        [#"StoreType" = "los", #"Order" = 452, #"Ratio" = 620.15, #"Path" = 303],
					        [#"StoreType" = "biography", #"Order" = 298, #"Ratio" = 559.65, #"Path" = 376],
					        [#"StoreType" = "portland", #"Order" = 290, #"Ratio" = 247.28, #"Path" = 931],
					        [#"StoreType" = "neighborhood", #"Order" = 497, #"Ratio" = 548.03, #"Path" = 835],
					        [#"StoreType" = "dragon", #"Order" = 259, #"Ratio" = 809.43, #"Path" = 316],
					        [#"StoreType" = "rates", #"Order" = 913, #"Ratio" = 640.17, #"Path" = 232],
					        [#"StoreType" = "task", #"Order" = 737, #"Ratio" = 948.11, #"Path" = 62],
					        [#"StoreType" = "phones", #"Order" = 387, #"Ratio" = 608.8, #"Path" = 589],
					        [#"StoreType" = "sitting", #"Order" = 161, #"Ratio" = 692.08, #"Path" = 195],
					        [#"StoreType" = "record", #"Order" = 375, #"Ratio" = 967.5, #"Path" = 681],
					        [#"StoreType" = "statistics", #"Order" = 234, #"Ratio" = 589.18, #"Path" = 243],
					        [#"StoreType" = "accuracy", #"Order" = 958, #"Ratio" = 224.49, #"Path" = 151],
					        [#"StoreType" = "procedures", #"Order" = 469, #"Ratio" = 39.02, #"Path" = 852],
					        [#"StoreType" = "prepared", #"Order" = 86, #"Ratio" = 626.4, #"Path" = 848],
					        [#"StoreType" = "mode", #"Order" = 494, #"Ratio" = 499.48, #"Path" = 778],
					        [#"StoreType" = "singapore", #"Order" = 330, #"Ratio" = 708.81, #"Path" = 489],
					        [#"StoreType" = "native", #"Order" = 390, #"Ratio" = 623.64, #"Path" = 216],
					        [#"StoreType" = "robot", #"Order" = 894, #"Ratio" = 733.87, #"Path" = 83],
					        [#"StoreType" = "happens", #"Order" = 557, #"Ratio" = 272.88, #"Path" = 716],
					        [#"StoreType" = "connection", #"Order" = 207, #"Ratio" = 88.71, #"Path" = 649],
					        [#"StoreType" = "finally", #"Order" = 174, #"Ratio" = 814.52, #"Path" = 992],
					        [#"StoreType" = "hairy", #"Order" = 165, #"Ratio" = 570.54, #"Path" = 932],
					        [#"StoreType" = "monitoring", #"Order" = 163, #"Ratio" = 450.92, #"Path" = 380],
					        [#"StoreType" = "ingredients", #"Order" = 894, #"Ratio" = 577.85, #"Path" = 236],
					        [#"StoreType" = "chair", #"Order" = 698, #"Ratio" = 815.88, #"Path" = 428],
					        [#"StoreType" = "preparation", #"Order" = 903, #"Ratio" = 268.52, #"Path" = 851],
					        [#"StoreType" = "finding", #"Order" = 383, #"Ratio" = 795.52, #"Path" = 999],
					        [#"StoreType" = "hilton", #"Order" = 67, #"Ratio" = 801.22, #"Path" = 305],
					        [#"StoreType" = "sorted", #"Order" = 472, #"Ratio" = 952.57, #"Path" = 41],
					        [#"StoreType" = "september", #"Order" = 397, #"Ratio" = 438.74, #"Path" = 170],
					        [#"StoreType" = "dead", #"Order" = 548, #"Ratio" = 825.35, #"Path" = 764],
					        [#"StoreType" = "deep", #"Order" = 632, #"Ratio" = 372.9, #"Path" = 743],
					        [#"StoreType" = "teens", #"Order" = 876, #"Ratio" = 534.47, #"Path" = 788],
					        [#"StoreType" = "albums", #"Order" = 929, #"Ratio" = 727.87, #"Path" = 643],
					        [#"StoreType" = "dirty", #"Order" = 744, #"Ratio" = 911.37, #"Path" = 157],
					        [#"StoreType" = "wizard", #"Order" = 612, #"Ratio" = 234.36, #"Path" = 164],
					        [#"StoreType" = "upon", #"Order" = 615, #"Ratio" = 995.06, #"Path" = 480],
					        [#"StoreType" = "evil", #"Order" = 644, #"Ratio" = 172.63, #"Path" = 428],
					        [#"StoreType" = "people", #"Order" = 386, #"Ratio" = 580.72, #"Path" = 465],
					        [#"StoreType" = "stainless", #"Order" = 209, #"Ratio" = 635.98, #"Path" = 20],
					        [#"StoreType" = "practices", #"Order" = 952, #"Ratio" = 559.67, #"Path" = 869],
					        [#"StoreType" = "drives", #"Order" = 794, #"Ratio" = 789.57, #"Path" = 615],
					        [#"StoreType" = "script", #"Order" = 397, #"Ratio" = 459.52, #"Path" = 538],
					        [#"StoreType" = "eastern", #"Order" = 421, #"Ratio" = 374.36, #"Path" = 666],
					        [#"StoreType" = "corps", #"Order" = 151, #"Ratio" = 643.35, #"Path" = 671],
					        [#"StoreType" = "fine", #"Order" = 753, #"Ratio" = 628.26, #"Path" = 293],
					        [#"StoreType" = "distribution", #"Order" = 236, #"Ratio" = 210.0, #"Path" = 505],
					        [#"StoreType" = "race", #"Order" = 695, #"Ratio" = 79.11, #"Path" = 977],
					        [#"StoreType" = "thai", #"Order" = 330, #"Ratio" = 91.47, #"Path" = 459],
					        [#"StoreType" = "wise", #"Order" = 520, #"Ratio" = 498.53, #"Path" = 251],
					        [#"StoreType" = "sublime", #"Order" = 553, #"Ratio" = 735.75, #"Path" = 882],
					        [#"StoreType" = "bookmark", #"Order" = 930, #"Ratio" = 477.33, #"Path" = 405],
					        [#"StoreType" = "mc", #"Order" = 824, #"Ratio" = 461.06, #"Path" = 952],
					        [#"StoreType" = "thing", #"Order" = 871, #"Ratio" = 345.47, #"Path" = 244],
					        [#"StoreType" = "licensed", #"Order" = 624, #"Ratio" = 463.71, #"Path" = 308],
					        [#"StoreType" = "incident", #"Order" = 216, #"Ratio" = 249.2, #"Path" = 819],
					        [#"StoreType" = "console", #"Order" = 924, #"Ratio" = 484.93, #"Path" = 733],
					        [#"StoreType" = "life", #"Order" = 950, #"Ratio" = 78.02, #"Path" = 950],
					        [#"StoreType" = "there", #"Order" = 675, #"Ratio" = 508.77, #"Path" = 517],
					        [#"StoreType" = "mlb", #"Order" = 192, #"Ratio" = 890.66, #"Path" = 628],
					        [#"StoreType" = "acoustic", #"Order" = 906, #"Ratio" = 104.05, #"Path" = 197],
					        [#"StoreType" = "exercises", #"Order" = 783, #"Ratio" = 243.78, #"Path" = 637],
					        [#"StoreType" = "enterprise", #"Order" = 373, #"Ratio" = 20.17, #"Path" = 924],
					        [#"StoreType" = "wildlife", #"Order" = 138, #"Ratio" = 338.45, #"Path" = 296],
					        [#"StoreType" = "wrote", #"Order" = 97, #"Ratio" = 216.16, #"Path" = 1000],
					        [#"StoreType" = "obviously", #"Order" = 409, #"Ratio" = 13.16, #"Path" = 370],
					        [#"StoreType" = "certificate", #"Order" = 651, #"Ratio" = 901.77, #"Path" = 671],
					        [#"StoreType" = "hispanic", #"Order" = 910, #"Ratio" = 100.45, #"Path" = 340],
					        [#"StoreType" = "material", #"Order" = 589, #"Ratio" = 608.99, #"Path" = 795],
					        [#"StoreType" = "your", #"Order" = 4, #"Ratio" = 501.57, #"Path" = 303],
					        [#"StoreType" = "african", #"Order" = 953, #"Ratio" = 317.13, #"Path" = 651],
					        [#"StoreType" = "oracle", #"Order" = 855, #"Ratio" = 13.97, #"Path" = 339],
					        [#"StoreType" = "stick", #"Order" = 326, #"Ratio" = 117.33, #"Path" = 62],
					        [#"StoreType" = "specify", #"Order" = 106, #"Ratio" = 895.44, #"Path" = 215],
					        [#"StoreType" = "complex", #"Order" = 308, #"Ratio" = 534.89, #"Path" = 6],
					        [#"StoreType" = "match", #"Order" = 89, #"Ratio" = 133.25, #"Path" = 49],
					        [#"StoreType" = "camping", #"Order" = 378, #"Ratio" = 315.83, #"Path" = 123],
					        [#"StoreType" = "expression", #"Order" = 564, #"Ratio" = 426.13, #"Path" = 931],
					        [#"StoreType" = "somebody", #"Order" = 960, #"Ratio" = 591.28, #"Path" = 859],
					        [#"StoreType" = "nine", #"Order" = 782, #"Ratio" = 885.84, #"Path" = 592],
					        [#"StoreType" = "apache", #"Order" = 784, #"Ratio" = 24.87, #"Path" = 155],
					        [#"StoreType" = "shadow", #"Order" = 642, #"Ratio" = 192.64, #"Path" = 360],
					        [#"StoreType" = "br", #"Order" = 985, #"Ratio" = 535.77, #"Path" = 130],
					        [#"StoreType" = "closer", #"Order" = 601, #"Ratio" = 693.31, #"Path" = 728],
					        [#"StoreType" = "crack", #"Order" = 607, #"Ratio" = 882.36, #"Path" = 234],
					        [#"StoreType" = "sight", #"Order" = 471, #"Ratio" = 182.16, #"Path" = 71],
					        [#"StoreType" = "utility", #"Order" = 68, #"Ratio" = 168.0, #"Path" = 115],
					        [#"StoreType" = "bike", #"Order" = 353, #"Ratio" = 459.82, #"Path" = 841],
					        [#"StoreType" = "shown", #"Order" = 321, #"Ratio" = 890.98, #"Path" = 436],
					        [#"StoreType" = "culture", #"Order" = 145, #"Ratio" = 400.64, #"Path" = 460],
					        [#"StoreType" = "household", #"Order" = 997, #"Ratio" = 322.04, #"Path" = 3],
					        [#"StoreType" = "estimate", #"Order" = 85, #"Ratio" = 681.48, #"Path" = 533],
					        [#"StoreType" = "assumes", #"Order" = 514, #"Ratio" = 324.22, #"Path" = 168],
					        [#"StoreType" = "music", #"Order" = 892, #"Ratio" = 664.66, #"Path" = 134],
					        [#"StoreType" = "medium", #"Order" = 894, #"Ratio" = 482.09, #"Path" = 482],
					        [#"StoreType" = "constant", #"Order" = 588, #"Ratio" = 785.02, #"Path" = 335],
					        [#"StoreType" = "lewis", #"Order" = 262, #"Ratio" = 855.22, #"Path" = 97],
					        [#"StoreType" = "millions", #"Order" = 675, #"Ratio" = 779.68, #"Path" = 892],
					        [#"StoreType" = "tank", #"Order" = 459, #"Ratio" = 117.62, #"Path" = 627],
					        [#"StoreType" = "symbol", #"Order" = 137, #"Ratio" = 506.59, #"Path" = 582],
					        [#"StoreType" = "donation", #"Order" = 259, #"Ratio" = 388.8, #"Path" = 420],
					        [#"StoreType" = "leaders", #"Order" = 884, #"Ratio" = 400.33, #"Path" = 875],
					        [#"StoreType" = "cuts", #"Order" = 206, #"Ratio" = 135.92, #"Path" = 948],
					        [#"StoreType" = "calculated", #"Order" = 405, #"Ratio" = 154.98, #"Path" = 237],
					        [#"StoreType" = "programming", #"Order" = 137, #"Ratio" = 378.57, #"Path" = 2],
					        [#"StoreType" = "socket", #"Order" = 768, #"Ratio" = 456.15, #"Path" = 644],
					        [#"StoreType" = "steel", #"Order" = 190, #"Ratio" = 264.76, #"Path" = 228],
					        [#"StoreType" = "final", #"Order" = 992, #"Ratio" = 495.07, #"Path" = 573],
					        [#"StoreType" = "mercury", #"Order" = 520, #"Ratio" = 979.88, #"Path" = 342],
					        [#"StoreType" = "hewlett", #"Order" = 824, #"Ratio" = 219.19, #"Path" = 312],
					        [#"StoreType" = "ecommerce", #"Order" = 226, #"Ratio" = 119.97, #"Path" = 115],
					        [#"StoreType" = "florist", #"Order" = 498, #"Ratio" = 986.65, #"Path" = 478],
					        [#"StoreType" = "dimension", #"Order" = 541, #"Ratio" = 418.47, #"Path" = 820],
					        [#"StoreType" = "tag", #"Order" = 832, #"Ratio" = 882.96, #"Path" = 736],
					        [#"StoreType" = "sciences", #"Order" = 91, #"Ratio" = 12.39, #"Path" = 467],
					        [#"StoreType" = "resource", #"Order" = 354, #"Ratio" = 225.23, #"Path" = 408],
					        [#"StoreType" = "asp", #"Order" = 826, #"Ratio" = 202.56, #"Path" = 947],
					        [#"StoreType" = "eight", #"Order" = 805, #"Ratio" = 171.7, #"Path" = 832],
					        [#"StoreType" = "andy", #"Order" = 757, #"Ratio" = 20.53, #"Path" = 691],
					        [#"StoreType" = "goto", #"Order" = 145, #"Ratio" = 417.1, #"Path" = 22],
					        [#"StoreType" = "internal", #"Order" = 708, #"Ratio" = 542.46, #"Path" = 808],
					        [#"StoreType" = "employed", #"Order" = 76, #"Ratio" = 239.43, #"Path" = 32],
					        [#"StoreType" = "five", #"Order" = 503, #"Ratio" = 210.07, #"Path" = 68],
					        [#"StoreType" = "pdas", #"Order" = 78, #"Ratio" = 761.71, #"Path" = 208],
					        [#"StoreType" = "keyword", #"Order" = 956, #"Ratio" = 164.44, #"Path" = 45],
					        [#"StoreType" = "tells", #"Order" = 734, #"Ratio" = 319.05, #"Path" = 737],
					        [#"StoreType" = "cooper", #"Order" = 605, #"Ratio" = 627.48, #"Path" = 475],
					        [#"StoreType" = "meal", #"Order" = 260, #"Ratio" = 481.89, #"Path" = 597],
					        [#"StoreType" = "billion", #"Order" = 167, #"Ratio" = 349.29, #"Path" = 773],
					        [#"StoreType" = "documentary", #"Order" = 147, #"Ratio" = 784.97, #"Path" = 402],
					        [#"StoreType" = "effects", #"Order" = 521, #"Ratio" = 712.61, #"Path" = 256],
					        [#"StoreType" = "registration", #"Order" = 173, #"Ratio" = 935.98, #"Path" = 121],
					        [#"StoreType" = "photograph", #"Order" = 79, #"Ratio" = 362.6, #"Path" = 232],
					        [#"StoreType" = "keeping", #"Order" = 671, #"Ratio" = 13.75, #"Path" = 2],
					        [#"StoreType" = "bookmark", #"Order" = 812, #"Ratio" = 428.06, #"Path" = 793],
					        [#"StoreType" = "enrollment", #"Order" = 668, #"Ratio" = 245.58, #"Path" = 581],
					        [#"StoreType" = "lovely", #"Order" = 641, #"Ratio" = 356.82, #"Path" = 344],
					        [#"StoreType" = "next", #"Order" = 940, #"Ratio" = 472.76, #"Path" = 918],
					        [#"StoreType" = "fox", #"Order" = 240, #"Ratio" = 314.14, #"Path" = 688],
					        [#"StoreType" = "mayor", #"Order" = 992, #"Ratio" = 62.01, #"Path" = 795],
					        [#"StoreType" = "southern", #"Order" = 527, #"Ratio" = 94.34, #"Path" = 781],
					        [#"StoreType" = "inventory", #"Order" = 644, #"Ratio" = 17.68, #"Path" = 664],
					        [#"StoreType" = "la", #"Order" = 18, #"Ratio" = 350.83, #"Path" = 115],
					        [#"StoreType" = "honest", #"Order" = 689, #"Ratio" = 282.98, #"Path" = 928],
					        [#"StoreType" = "pure", #"Order" = 693, #"Ratio" = 416.47, #"Path" = 286],
					        [#"StoreType" = "measure", #"Order" = 845, #"Ratio" = 623.1, #"Path" = 512],
					        [#"StoreType" = "types", #"Order" = 181, #"Ratio" = 207.84, #"Path" = 635],
					        [#"StoreType" = "permits", #"Order" = 231, #"Ratio" = 630.84, #"Path" = 138],
					        [#"StoreType" = "ink", #"Order" = 663, #"Ratio" = 390.09, #"Path" = 161],
					        [#"StoreType" = "albums", #"Order" = 39, #"Ratio" = 796.15, #"Path" = 701],
					        [#"StoreType" = "for", #"Order" = 509, #"Ratio" = 350.0, #"Path" = 668],
					        [#"StoreType" = "regions", #"Order" = 999, #"Ratio" = 537.99, #"Path" = 461],
					        [#"StoreType" = "designed", #"Order" = 808, #"Ratio" = 902.32, #"Path" = 794],
					        [#"StoreType" = "mi", #"Order" = 884, #"Ratio" = 735.67, #"Path" = 551],
					        [#"StoreType" = "linear", #"Order" = 655, #"Ratio" = 126.35, #"Path" = 380],
					        [#"StoreType" = "championship", #"Order" = 120, #"Ratio" = 25.94, #"Path" = 463],
					        [#"StoreType" = "ryan", #"Order" = 266, #"Ratio" = 262.34, #"Path" = 961],
					        [#"StoreType" = "ri", #"Order" = 43, #"Ratio" = 506.94, #"Path" = 392],
					        [#"StoreType" = "extensions", #"Order" = 966, #"Ratio" = 227.26, #"Path" = 990],
					        [#"StoreType" = "whereas", #"Order" = 871, #"Ratio" = 589.8, #"Path" = 782],
					        [#"StoreType" = "legislative", #"Order" = 823, #"Ratio" = 841.11, #"Path" = 646],
					        [#"StoreType" = "mount", #"Order" = 871, #"Ratio" = 959.15, #"Path" = 694],
					        [#"StoreType" = "bs", #"Order" = 268, #"Ratio" = 686.68, #"Path" = 846],
					        [#"StoreType" = "turns", #"Order" = 558, #"Ratio" = 831.46, #"Path" = 42],
					        [#"StoreType" = "fantastic", #"Order" = 630, #"Ratio" = 648.49, #"Path" = 860],
					        [#"StoreType" = "chain", #"Order" = 492, #"Ratio" = 873.99, #"Path" = 929],
					        [#"StoreType" = "tagged", #"Order" = 955, #"Ratio" = 684.42, #"Path" = 959],
					        [#"StoreType" = "featuring", #"Order" = 554, #"Ratio" = 264.44, #"Path" = 947],
					        [#"StoreType" = "leisure", #"Order" = 846, #"Ratio" = 212.63, #"Path" = 404],
					        [#"StoreType" = "franchise", #"Order" = 67, #"Ratio" = 371.5, #"Path" = 953],
					        [#"StoreType" = "mit", #"Order" = 837, #"Ratio" = 507.75, #"Path" = 928],
					        [#"StoreType" = "policies", #"Order" = 298, #"Ratio" = 162.42, #"Path" = 165],
					        [#"StoreType" = "ml", #"Order" = 944, #"Ratio" = 561.53, #"Path" = 310],
					        [#"StoreType" = "plastic", #"Order" = 263, #"Ratio" = 954.03, #"Path" = 797],
					        [#"StoreType" = "committees", #"Order" = 984, #"Ratio" = 585.11, #"Path" = 592],
					        [#"StoreType" = "removed", #"Order" = 605, #"Ratio" = 47.66, #"Path" = 204],
					        [#"StoreType" = "lift", #"Order" = 612, #"Ratio" = 855.08, #"Path" = 648],
					        [#"StoreType" = "matching", #"Order" = 345, #"Ratio" = 249.75, #"Path" = 493],
					        [#"StoreType" = "healthcare", #"Order" = 95, #"Ratio" = 116.35, #"Path" = 664],
					        [#"StoreType" = "secret", #"Order" = 877, #"Ratio" = 83.19, #"Path" = 976],
					        [#"StoreType" = "completely", #"Order" = 994, #"Ratio" = 718.04, #"Path" = 501],
					        [#"StoreType" = "wolf", #"Order" = 867, #"Ratio" = 821.04, #"Path" = 758],
					        [#"StoreType" = "somewhere", #"Order" = 596, #"Ratio" = 875.21, #"Path" = 296],
					        [#"StoreType" = "journals", #"Order" = 247, #"Ratio" = 636.36, #"Path" = 734],
					        [#"StoreType" = "melissa", #"Order" = 606, #"Ratio" = 332.55, #"Path" = 690],
					        [#"StoreType" = "alabama", #"Order" = 96, #"Ratio" = 538.47, #"Path" = 855],
					        [#"StoreType" = "proud", #"Order" = 262, #"Ratio" = 805.78, #"Path" = 294],
					        [#"StoreType" = "employer", #"Order" = 520, #"Ratio" = 659.73, #"Path" = 918],
					        [#"StoreType" = "waiting", #"Order" = 256, #"Ratio" = 524.66, #"Path" = 341],
					        [#"StoreType" = "fails", #"Order" = 863, #"Ratio" = 543.96, #"Path" = 809],
					        [#"StoreType" = "determined", #"Order" = 39, #"Ratio" = 745.61, #"Path" = 637],
					        [#"StoreType" = "entirely", #"Order" = 331, #"Ratio" = 943.28, #"Path" = 404],
					        [#"StoreType" = "lee", #"Order" = 183, #"Ratio" = 468.98, #"Path" = 792],
					        [#"StoreType" = "selecting", #"Order" = 874, #"Ratio" = 575.28, #"Path" = 909],
					        [#"StoreType" = "places", #"Order" = 971, #"Ratio" = 564.5, #"Path" = 190],
					        [#"StoreType" = "province", #"Order" = 72, #"Ratio" = 168.14, #"Path" = 657],
					        [#"StoreType" = "manner", #"Order" = 157, #"Ratio" = 350.77, #"Path" = 192],
					        [#"StoreType" = "radiation", #"Order" = 988, #"Ratio" = 44.3, #"Path" = 631],
					        [#"StoreType" = "younger", #"Order" = 931, #"Ratio" = 996.11, #"Path" = 523],
					        [#"StoreType" = "lovely", #"Order" = 369, #"Ratio" = 199.63, #"Path" = 496],
					        [#"StoreType" = "dave", #"Order" = 726, #"Ratio" = 72.2, #"Path" = 494],
					        [#"StoreType" = "expectations", #"Order" = 281, #"Ratio" = 291.94, #"Path" = 595],
					        [#"StoreType" = "mine", #"Order" = 95, #"Ratio" = 218.77, #"Path" = 169],
					        [#"StoreType" = "uses", #"Order" = 495, #"Ratio" = 530.73, #"Path" = 866],
					        [#"StoreType" = "node", #"Order" = 802, #"Ratio" = 267.2, #"Path" = 862],
					        [#"StoreType" = "male", #"Order" = 733, #"Ratio" = 190.88, #"Path" = 948],
					        [#"StoreType" = "individual", #"Order" = 329, #"Ratio" = 82.2, #"Path" = 284],
					        [#"StoreType" = "belgium", #"Order" = 194, #"Ratio" = 118.02, #"Path" = 242],
					        [#"StoreType" = "molecular", #"Order" = 914, #"Ratio" = 871.92, #"Path" = 579],
					        [#"StoreType" = "flickr", #"Order" = 879, #"Ratio" = 816.3, #"Path" = 476],
					        [#"StoreType" = "cnet", #"Order" = 665, #"Ratio" = 68.55, #"Path" = 736],
					        [#"StoreType" = "foreign", #"Order" = 801, #"Ratio" = 648.71, #"Path" = 998],
					        [#"StoreType" = "mx", #"Order" = 852, #"Ratio" = 360.5, #"Path" = 191],
					        [#"StoreType" = "ins", #"Order" = 509, #"Ratio" = 608.54, #"Path" = 160],
					        [#"StoreType" = "shot", #"Order" = 577, #"Ratio" = 948.15, #"Path" = 144],
					        [#"StoreType" = "depending", #"Order" = 459, #"Ratio" = 700.09, #"Path" = 201],
					        [#"StoreType" = "recorder", #"Order" = 7, #"Ratio" = 86.98, #"Path" = 509],
					        [#"StoreType" = "rica", #"Order" = 574, #"Ratio" = 211.77, #"Path" = 488],
					        [#"StoreType" = "arrived", #"Order" = 545, #"Ratio" = 89.23, #"Path" = 637],
					        [#"StoreType" = "judge", #"Order" = 339, #"Ratio" = 375.93, #"Path" = 189],
					        [#"StoreType" = "arcade", #"Order" = 320, #"Ratio" = 100.32, #"Path" = 954]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"StoreType", type text},
					        {"Order", Int64.Type},
					        {"Ratio", type number},
					        {"Path", Int64.Type}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table