table 'Sheet1_Sheet1 (waffle template)'
	lineageTag: f3e44410-87af-43eb-8538-94360264918e

	column Row
		dataType: int64
		formatString: 0
		lineageTag: 7bfc27b0-3abb-4018-b1a8-8c154648842e
		summarizeBy: sum
		sourceColumn: Row

		annotation SummarizationSetBy = Automatic

	column Column
		dataType: int64
		formatString: 0
		lineageTag: 9768a058-4316-4301-9544-7bc6aab49ddd
		summarizeBy: sum
		sourceColumn: Column

		annotation SummarizationSetBy = Automatic

	column Percentage
		dataType: double
		formatString: General Number
		lineageTag: 0a4d4a23-4e7c-40a3-b62f-25efd4c85ed8
		summarizeBy: sum
		sourceColumn: Percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Sheet1_Sheet1 (waffle template)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Row" = 91, #"Column" = 627, #"Percentage" = 30.76],
					        [#"Row" = 171, #"Column" = 608, #"Percentage" = 87.63],
					        [#"Row" = 541, #"Column" = 983, #"Percentage" = 73.22],
					        [#"Row" = 595, #"Column" = 971, #"Percentage" = 17.39],
					        [#"Row" = 859, #"Column" = 393, #"Percentage" = 28.1],
					        [#"Row" = 796, #"Column" = 717, #"Percentage" = 69.5],
					        [#"Row" = 79, #"Column" = 194, #"Percentage" = 48.73],
					        [#"Row" = 881, #"Column" = 660, #"Percentage" = 9.1],
					        [#"Row" = 498, #"Column" = 604, #"Percentage" = 47.73],
					        [#"Row" = 3, #"Column" = 107, #"Percentage" = 38.81],
					        [#"Row" = 800, #"Column" = 814, #"Percentage" = 50.06],
					        [#"Row" = 938, #"Column" = 296, #"Percentage" = 70.35],
					        [#"Row" = 469, #"Column" = 672, #"Percentage" = 0.13],
					        [#"Row" = 172, #"Column" = 813, #"Percentage" = 0.32],
					        [#"Row" = 67, #"Column" = 572, #"Percentage" = 25.25],
					        [#"Row" = 550, #"Column" = 778, #"Percentage" = 49.8],
					        [#"Row" = 763, #"Column" = 226, #"Percentage" = 0.08],
					        [#"Row" = 23, #"Column" = 237, #"Percentage" = 39.25],
					        [#"Row" = 335, #"Column" = 613, #"Percentage" = 8.75],
					        [#"Row" = 196, #"Column" = 235, #"Percentage" = 68.68],
					        [#"Row" = 202, #"Column" = 520, #"Percentage" = 75.72],
					        [#"Row" = 860, #"Column" = 214, #"Percentage" = 57.14],
					        [#"Row" = 911, #"Column" = 607, #"Percentage" = 46.47],
					        [#"Row" = 128, #"Column" = 475, #"Percentage" = 9.64],
					        [#"Row" = 678, #"Column" = 471, #"Percentage" = 15.64],
					        [#"Row" = 409, #"Column" = 179, #"Percentage" = 92.61],
					        [#"Row" = 630, #"Column" = 360, #"Percentage" = 14.53],
					        [#"Row" = 956, #"Column" = 851, #"Percentage" = 79.98],
					        [#"Row" = 935, #"Column" = 664, #"Percentage" = 82.91],
					        [#"Row" = 722, #"Column" = 43, #"Percentage" = 39.65],
					        [#"Row" = 643, #"Column" = 581, #"Percentage" = 81.65],
					        [#"Row" = 53, #"Column" = 925, #"Percentage" = 61.01],
					        [#"Row" = 741, #"Column" = 67, #"Percentage" = 98.92],
					        [#"Row" = 599, #"Column" = 363, #"Percentage" = 46.17],
					        [#"Row" = 197, #"Column" = 353, #"Percentage" = 92.0],
					        [#"Row" = 368, #"Column" = 341, #"Percentage" = 38.48],
					        [#"Row" = 336, #"Column" = 880, #"Percentage" = 38.72],
					        [#"Row" = 334, #"Column" = 282, #"Percentage" = 34.77],
					        [#"Row" = 220, #"Column" = 379, #"Percentage" = 82.77],
					        [#"Row" = 515, #"Column" = 598, #"Percentage" = 50.0],
					        [#"Row" = 88, #"Column" = 650, #"Percentage" = 47.27],
					        [#"Row" = 453, #"Column" = 483, #"Percentage" = 12.67],
					        [#"Row" = 613, #"Column" = 632, #"Percentage" = 68.75],
					        [#"Row" = 315, #"Column" = 697, #"Percentage" = 33.73],
					        [#"Row" = 911, #"Column" = 546, #"Percentage" = 65.46],
					        [#"Row" = 172, #"Column" = 255, #"Percentage" = 91.7],
					        [#"Row" = 186, #"Column" = 189, #"Percentage" = 25.24],
					        [#"Row" = 615, #"Column" = 57, #"Percentage" = 77.71],
					        [#"Row" = 691, #"Column" = 375, #"Percentage" = 33.31],
					        [#"Row" = 346, #"Column" = 955, #"Percentage" = 19.18],
					        [#"Row" = 952, #"Column" = 645, #"Percentage" = 92.19],
					        [#"Row" = 938, #"Column" = 338, #"Percentage" = 32.68],
					        [#"Row" = 844, #"Column" = 404, #"Percentage" = 52.96],
					        [#"Row" = 626, #"Column" = 516, #"Percentage" = 62.8],
					        [#"Row" = 884, #"Column" = 941, #"Percentage" = 82.83],
					        [#"Row" = 654, #"Column" = 700, #"Percentage" = 71.96],
					        [#"Row" = 504, #"Column" = 463, #"Percentage" = 7.86],
					        [#"Row" = 56, #"Column" = 155, #"Percentage" = 58.52],
					        [#"Row" = 71, #"Column" = 448, #"Percentage" = 5.73],
					        [#"Row" = 81, #"Column" = 366, #"Percentage" = 65.56],
					        [#"Row" = 915, #"Column" = 256, #"Percentage" = 70.18],
					        [#"Row" = 102, #"Column" = 193, #"Percentage" = 20.76],
					        [#"Row" = 912, #"Column" = 510, #"Percentage" = 1.51],
					        [#"Row" = 805, #"Column" = 732, #"Percentage" = 66.28],
					        [#"Row" = 940, #"Column" = 238, #"Percentage" = 56.61],
					        [#"Row" = 662, #"Column" = 729, #"Percentage" = 85.81],
					        [#"Row" = 842, #"Column" = 677, #"Percentage" = 75.13],
					        [#"Row" = 789, #"Column" = 240, #"Percentage" = 81.12],
					        [#"Row" = 685, #"Column" = 766, #"Percentage" = 42.54],
					        [#"Row" = 413, #"Column" = 855, #"Percentage" = 2.92],
					        [#"Row" = 599, #"Column" = 764, #"Percentage" = 43.65],
					        [#"Row" = 594, #"Column" = 508, #"Percentage" = 47.98],
					        [#"Row" = 893, #"Column" = 712, #"Percentage" = 63.57],
					        [#"Row" = 154, #"Column" = 374, #"Percentage" = 96.5],
					        [#"Row" = 605, #"Column" = 100, #"Percentage" = 83.15],
					        [#"Row" = 523, #"Column" = 836, #"Percentage" = 4.45],
					        [#"Row" = 633, #"Column" = 999, #"Percentage" = 51.25],
					        [#"Row" = 695, #"Column" = 596, #"Percentage" = 93.22],
					        [#"Row" = 778, #"Column" = 65, #"Percentage" = 34.4],
					        [#"Row" = 585, #"Column" = 692, #"Percentage" = 22.46],
					        [#"Row" = 188, #"Column" = 995, #"Percentage" = 98.0],
					        [#"Row" = 89, #"Column" = 283, #"Percentage" = 52.44],
					        [#"Row" = 618, #"Column" = 991, #"Percentage" = 93.78],
					        [#"Row" = 169, #"Column" = 541, #"Percentage" = 16.54],
					        [#"Row" = 950, #"Column" = 835, #"Percentage" = 5.67],
					        [#"Row" = 976, #"Column" = 541, #"Percentage" = 1.32],
					        [#"Row" = 776, #"Column" = 7, #"Percentage" = 46.21],
					        [#"Row" = 330, #"Column" = 82, #"Percentage" = 13.73],
					        [#"Row" = 710, #"Column" = 793, #"Percentage" = 32.16],
					        [#"Row" = 465, #"Column" = 33, #"Percentage" = 0.97],
					        [#"Row" = 160, #"Column" = 560, #"Percentage" = 51.79],
					        [#"Row" = 161, #"Column" = 929, #"Percentage" = 43.6],
					        [#"Row" = 897, #"Column" = 687, #"Percentage" = 40.62],
					        [#"Row" = 22, #"Column" = 567, #"Percentage" = 84.13],
					        [#"Row" = 338, #"Column" = 399, #"Percentage" = 24.14],
					        [#"Row" = 867, #"Column" = 206, #"Percentage" = 13.59],
					        [#"Row" = 487, #"Column" = 423, #"Percentage" = 52.86],
					        [#"Row" = 197, #"Column" = 2, #"Percentage" = 91.97],
					        [#"Row" = 262, #"Column" = 325, #"Percentage" = 86.87],
					        [#"Row" = 599, #"Column" = 722, #"Percentage" = 97.03],
					        [#"Row" = 500, #"Column" = 517, #"Percentage" = 63.93],
					        [#"Row" = 481, #"Column" = 263, #"Percentage" = 79.06],
					        [#"Row" = 719, #"Column" = 899, #"Percentage" = 29.42],
					        [#"Row" = 442, #"Column" = 724, #"Percentage" = 79.63],
					        [#"Row" = 998, #"Column" = 966, #"Percentage" = 66.48],
					        [#"Row" = 708, #"Column" = 65, #"Percentage" = 12.05],
					        [#"Row" = 229, #"Column" = 954, #"Percentage" = 89.4],
					        [#"Row" = 734, #"Column" = 842, #"Percentage" = 77.4],
					        [#"Row" = 423, #"Column" = 830, #"Percentage" = 5.1],
					        [#"Row" = 676, #"Column" = 775, #"Percentage" = 73.85],
					        [#"Row" = 952, #"Column" = 831, #"Percentage" = 77.86],
					        [#"Row" = 373, #"Column" = 720, #"Percentage" = 11.62],
					        [#"Row" = 27, #"Column" = 628, #"Percentage" = 99.28],
					        [#"Row" = 490, #"Column" = 844, #"Percentage" = 38.32],
					        [#"Row" = 471, #"Column" = 21, #"Percentage" = 69.52],
					        [#"Row" = 116, #"Column" = 639, #"Percentage" = 86.55],
					        [#"Row" = 513, #"Column" = 493, #"Percentage" = 94.99],
					        [#"Row" = 312, #"Column" = 232, #"Percentage" = 56.3],
					        [#"Row" = 13, #"Column" = 284, #"Percentage" = 3.42],
					        [#"Row" = 122, #"Column" = 194, #"Percentage" = 0.39],
					        [#"Row" = 147, #"Column" = 340, #"Percentage" = 1.65],
					        [#"Row" = 207, #"Column" = 505, #"Percentage" = 80.54],
					        [#"Row" = 130, #"Column" = 765, #"Percentage" = 68.35],
					        [#"Row" = 393, #"Column" = 853, #"Percentage" = 39.45],
					        [#"Row" = 945, #"Column" = 91, #"Percentage" = 15.98],
					        [#"Row" = 474, #"Column" = 497, #"Percentage" = 85.86],
					        [#"Row" = 156, #"Column" = 839, #"Percentage" = 32.62],
					        [#"Row" = 821, #"Column" = 252, #"Percentage" = 83.56],
					        [#"Row" = 187, #"Column" = 978, #"Percentage" = 29.71],
					        [#"Row" = 925, #"Column" = 126, #"Percentage" = 20.85],
					        [#"Row" = 505, #"Column" = 857, #"Percentage" = 5.91],
					        [#"Row" = 916, #"Column" = 687, #"Percentage" = 57.02],
					        [#"Row" = 548, #"Column" = 479, #"Percentage" = 82.13],
					        [#"Row" = 315, #"Column" = 401, #"Percentage" = 23.18],
					        [#"Row" = 598, #"Column" = 290, #"Percentage" = 37.07],
					        [#"Row" = 488, #"Column" = 500, #"Percentage" = 65.68],
					        [#"Row" = 426, #"Column" = 234, #"Percentage" = 6.12],
					        [#"Row" = 277, #"Column" = 100, #"Percentage" = 80.87],
					        [#"Row" = 184, #"Column" = 271, #"Percentage" = 95.32],
					        [#"Row" = 408, #"Column" = 738, #"Percentage" = 17.69],
					        [#"Row" = 849, #"Column" = 145, #"Percentage" = 39.34],
					        [#"Row" = 582, #"Column" = 145, #"Percentage" = 70.13],
					        [#"Row" = 426, #"Column" = 944, #"Percentage" = 31.31],
					        [#"Row" = 598, #"Column" = 838, #"Percentage" = 29.13],
					        [#"Row" = 986, #"Column" = 247, #"Percentage" = 10.53],
					        [#"Row" = 517, #"Column" = 77, #"Percentage" = 33.59],
					        [#"Row" = 696, #"Column" = 627, #"Percentage" = 30.42],
					        [#"Row" = 813, #"Column" = 846, #"Percentage" = 85.29],
					        [#"Row" = 116, #"Column" = 158, #"Percentage" = 9.88],
					        [#"Row" = 180, #"Column" = 447, #"Percentage" = 89.3],
					        [#"Row" = 608, #"Column" = 767, #"Percentage" = 34.29],
					        [#"Row" = 592, #"Column" = 109, #"Percentage" = 60.85],
					        [#"Row" = 604, #"Column" = 766, #"Percentage" = 37.62],
					        [#"Row" = 459, #"Column" = 876, #"Percentage" = 67.1],
					        [#"Row" = 257, #"Column" = 341, #"Percentage" = 49.34],
					        [#"Row" = 382, #"Column" = 745, #"Percentage" = 99.4],
					        [#"Row" = 973, #"Column" = 18, #"Percentage" = 23.71],
					        [#"Row" = 225, #"Column" = 76, #"Percentage" = 85.08],
					        [#"Row" = 829, #"Column" = 860, #"Percentage" = 53.67],
					        [#"Row" = 909, #"Column" = 174, #"Percentage" = 51.68],
					        [#"Row" = 100, #"Column" = 617, #"Percentage" = 35.28],
					        [#"Row" = 763, #"Column" = 633, #"Percentage" = 47.13],
					        [#"Row" = 305, #"Column" = 245, #"Percentage" = 53.01],
					        [#"Row" = 406, #"Column" = 135, #"Percentage" = 26.27],
					        [#"Row" = 787, #"Column" = 390, #"Percentage" = 79.29],
					        [#"Row" = 146, #"Column" = 947, #"Percentage" = 71.58],
					        [#"Row" = 762, #"Column" = 566, #"Percentage" = 80.85],
					        [#"Row" = 886, #"Column" = 791, #"Percentage" = 51.62],
					        [#"Row" = 251, #"Column" = 719, #"Percentage" = 50.39],
					        [#"Row" = 360, #"Column" = 149, #"Percentage" = 79.01],
					        [#"Row" = 923, #"Column" = 908, #"Percentage" = 97.02],
					        [#"Row" = 769, #"Column" = 257, #"Percentage" = 99.39],
					        [#"Row" = 58, #"Column" = 86, #"Percentage" = 26.68],
					        [#"Row" = 457, #"Column" = 144, #"Percentage" = 19.08],
					        [#"Row" = 629, #"Column" = 347, #"Percentage" = 38.42],
					        [#"Row" = 242, #"Column" = 915, #"Percentage" = 79.74],
					        [#"Row" = 941, #"Column" = 712, #"Percentage" = 34.24],
					        [#"Row" = 791, #"Column" = 35, #"Percentage" = 95.7],
					        [#"Row" = 473, #"Column" = 273, #"Percentage" = 41.14],
					        [#"Row" = 381, #"Column" = 386, #"Percentage" = 67.95],
					        [#"Row" = 863, #"Column" = 800, #"Percentage" = 58.3],
					        [#"Row" = 24, #"Column" = 141, #"Percentage" = 84.74],
					        [#"Row" = 187, #"Column" = 261, #"Percentage" = 39.35],
					        [#"Row" = 879, #"Column" = 648, #"Percentage" = 78.9],
					        [#"Row" = 742, #"Column" = 455, #"Percentage" = 66.74],
					        [#"Row" = 41, #"Column" = 942, #"Percentage" = 0.57],
					        [#"Row" = 732, #"Column" = 253, #"Percentage" = 39.18],
					        [#"Row" = 857, #"Column" = 954, #"Percentage" = 57.29],
					        [#"Row" = 734, #"Column" = 231, #"Percentage" = 50.5],
					        [#"Row" = 248, #"Column" = 654, #"Percentage" = 55.59],
					        [#"Row" = 752, #"Column" = 708, #"Percentage" = 31.99],
					        [#"Row" = 237, #"Column" = 990, #"Percentage" = 39.98],
					        [#"Row" = 11, #"Column" = 917, #"Percentage" = 14.76],
					        [#"Row" = 877, #"Column" = 568, #"Percentage" = 76.64],
					        [#"Row" = 482, #"Column" = 862, #"Percentage" = 32.49],
					        [#"Row" = 56, #"Column" = 117, #"Percentage" = 31.34],
					        [#"Row" = 497, #"Column" = 503, #"Percentage" = 58.01],
					        [#"Row" = 865, #"Column" = 408, #"Percentage" = 96.39],
					        [#"Row" = 892, #"Column" = 267, #"Percentage" = 0.71],
					        [#"Row" = 98, #"Column" = 484, #"Percentage" = 23.21],
					        [#"Row" = 423, #"Column" = 469, #"Percentage" = 33.39],
					        [#"Row" = 500, #"Column" = 935, #"Percentage" = 25.9],
					        [#"Row" = 774, #"Column" = 989, #"Percentage" = 82.25],
					        [#"Row" = 768, #"Column" = 961, #"Percentage" = 0.56],
					        [#"Row" = 849, #"Column" = 330, #"Percentage" = 81.27],
					        [#"Row" = 472, #"Column" = 537, #"Percentage" = 72.27],
					        [#"Row" = 817, #"Column" = 944, #"Percentage" = 36.5],
					        [#"Row" = 109, #"Column" = 551, #"Percentage" = 56.74],
					        [#"Row" = 771, #"Column" = 487, #"Percentage" = 49.15],
					        [#"Row" = 734, #"Column" = 204, #"Percentage" = 93.22],
					        [#"Row" = 988, #"Column" = 701, #"Percentage" = 4.44],
					        [#"Row" = 50, #"Column" = 669, #"Percentage" = 27.31],
					        [#"Row" = 437, #"Column" = 158, #"Percentage" = 86.61],
					        [#"Row" = 182, #"Column" = 434, #"Percentage" = 49.82],
					        [#"Row" = 681, #"Column" = 517, #"Percentage" = 33.23],
					        [#"Row" = 127, #"Column" = 279, #"Percentage" = 10.39],
					        [#"Row" = 582, #"Column" = 610, #"Percentage" = 10.16],
					        [#"Row" = 518, #"Column" = 816, #"Percentage" = 96.13],
					        [#"Row" = 128, #"Column" = 399, #"Percentage" = 4.46],
					        [#"Row" = 209, #"Column" = 747, #"Percentage" = 72.54],
					        [#"Row" = 458, #"Column" = 995, #"Percentage" = 82.19],
					        [#"Row" = 910, #"Column" = 816, #"Percentage" = 9.71],
					        [#"Row" = 96, #"Column" = 981, #"Percentage" = 82.2],
					        [#"Row" = 734, #"Column" = 423, #"Percentage" = 65.07],
					        [#"Row" = 244, #"Column" = 427, #"Percentage" = 4.67],
					        [#"Row" = 823, #"Column" = 835, #"Percentage" = 93.22],
					        [#"Row" = 469, #"Column" = 227, #"Percentage" = 31.87],
					        [#"Row" = 883, #"Column" = 548, #"Percentage" = 47.63],
					        [#"Row" = 363, #"Column" = 255, #"Percentage" = 81.14],
					        [#"Row" = 426, #"Column" = 824, #"Percentage" = 21.59],
					        [#"Row" = 98, #"Column" = 566, #"Percentage" = 86.24],
					        [#"Row" = 182, #"Column" = 735, #"Percentage" = 31.96],
					        [#"Row" = 107, #"Column" = 378, #"Percentage" = 78.54],
					        [#"Row" = 230, #"Column" = 710, #"Percentage" = 15.37],
					        [#"Row" = 895, #"Column" = 786, #"Percentage" = 52.21],
					        [#"Row" = 506, #"Column" = 352, #"Percentage" = 24.41],
					        [#"Row" = 227, #"Column" = 435, #"Percentage" = 82.86],
					        [#"Row" = 543, #"Column" = 622, #"Percentage" = 96.78],
					        [#"Row" = 781, #"Column" = 102, #"Percentage" = 43.72],
					        [#"Row" = 232, #"Column" = 229, #"Percentage" = 97.98],
					        [#"Row" = 918, #"Column" = 579, #"Percentage" = 73.96],
					        [#"Row" = 799, #"Column" = 656, #"Percentage" = 1.09],
					        [#"Row" = 956, #"Column" = 638, #"Percentage" = 9.66],
					        [#"Row" = 84, #"Column" = 843, #"Percentage" = 26.67],
					        [#"Row" = 702, #"Column" = 456, #"Percentage" = 74.98],
					        [#"Row" = 578, #"Column" = 323, #"Percentage" = 94.78],
					        [#"Row" = 864, #"Column" = 969, #"Percentage" = 88.56],
					        [#"Row" = 956, #"Column" = 191, #"Percentage" = 36.77],
					        [#"Row" = 532, #"Column" = 463, #"Percentage" = 97.9],
					        [#"Row" = 706, #"Column" = 265, #"Percentage" = 59.32],
					        [#"Row" = 844, #"Column" = 15, #"Percentage" = 84.55],
					        [#"Row" = 205, #"Column" = 985, #"Percentage" = 63.76],
					        [#"Row" = 846, #"Column" = 212, #"Percentage" = 47.92],
					        [#"Row" = 641, #"Column" = 954, #"Percentage" = 24.56],
					        [#"Row" = 584, #"Column" = 994, #"Percentage" = 1.67],
					        [#"Row" = 234, #"Column" = 595, #"Percentage" = 45.98],
					        [#"Row" = 464, #"Column" = 114, #"Percentage" = 13.27],
					        [#"Row" = 776, #"Column" = 254, #"Percentage" = 87.31],
					        [#"Row" = 893, #"Column" = 332, #"Percentage" = 98.86],
					        [#"Row" = 848, #"Column" = 119, #"Percentage" = 26.17],
					        [#"Row" = 98, #"Column" = 519, #"Percentage" = 53.63],
					        [#"Row" = 287, #"Column" = 611, #"Percentage" = 88.39],
					        [#"Row" = 23, #"Column" = 154, #"Percentage" = 46.51],
					        [#"Row" = 61, #"Column" = 734, #"Percentage" = 11.01],
					        [#"Row" = 651, #"Column" = 643, #"Percentage" = 47.2],
					        [#"Row" = 200, #"Column" = 487, #"Percentage" = 15.17],
					        [#"Row" = 768, #"Column" = 125, #"Percentage" = 43.58],
					        [#"Row" = 820, #"Column" = 674, #"Percentage" = 10.29],
					        [#"Row" = 524, #"Column" = 705, #"Percentage" = 84.49],
					        [#"Row" = 602, #"Column" = 912, #"Percentage" = 34.55],
					        [#"Row" = 563, #"Column" = 603, #"Percentage" = 99.7],
					        [#"Row" = 866, #"Column" = 36, #"Percentage" = 15.77],
					        [#"Row" = 704, #"Column" = 768, #"Percentage" = 42.47],
					        [#"Row" = 738, #"Column" = 944, #"Percentage" = 37.51],
					        [#"Row" = 110, #"Column" = 198, #"Percentage" = 29.91],
					        [#"Row" = 476, #"Column" = 938, #"Percentage" = 84.28],
					        [#"Row" = 739, #"Column" = 886, #"Percentage" = 63.08],
					        [#"Row" = 231, #"Column" = 863, #"Percentage" = 59.86],
					        [#"Row" = 577, #"Column" = 360, #"Percentage" = 21.06],
					        [#"Row" = 404, #"Column" = 976, #"Percentage" = 44.81],
					        [#"Row" = 596, #"Column" = 729, #"Percentage" = 93.07],
					        [#"Row" = 705, #"Column" = 211, #"Percentage" = 80.0],
					        [#"Row" = 954, #"Column" = 777, #"Percentage" = 72.09],
					        [#"Row" = 553, #"Column" = 326, #"Percentage" = 35.54],
					        [#"Row" = 383, #"Column" = 571, #"Percentage" = 1.64],
					        [#"Row" = 674, #"Column" = 575, #"Percentage" = 96.89],
					        [#"Row" = 151, #"Column" = 902, #"Percentage" = 49.72],
					        [#"Row" = 168, #"Column" = 549, #"Percentage" = 36.59],
					        [#"Row" = 913, #"Column" = 269, #"Percentage" = 43.38],
					        [#"Row" = 738, #"Column" = 658, #"Percentage" = 83.31],
					        [#"Row" = 566, #"Column" = 931, #"Percentage" = 66.22],
					        [#"Row" = 348, #"Column" = 743, #"Percentage" = 18.55],
					        [#"Row" = 668, #"Column" = 285, #"Percentage" = 86.52],
					        [#"Row" = 500, #"Column" = 497, #"Percentage" = 60.7],
					        [#"Row" = 375, #"Column" = 466, #"Percentage" = 21.67],
					        [#"Row" = 316, #"Column" = 788, #"Percentage" = 83.69],
					        [#"Row" = 676, #"Column" = 112, #"Percentage" = 14.56],
					        [#"Row" = 77, #"Column" = 97, #"Percentage" = 15.77],
					        [#"Row" = 886, #"Column" = 695, #"Percentage" = 75.12],
					        [#"Row" = 830, #"Column" = 257, #"Percentage" = 67.71],
					        [#"Row" = 907, #"Column" = 742, #"Percentage" = 81.51],
					        [#"Row" = 912, #"Column" = 207, #"Percentage" = 27.47],
					        [#"Row" = 148, #"Column" = 499, #"Percentage" = 51.45],
					        [#"Row" = 353, #"Column" = 259, #"Percentage" = 35.63],
					        [#"Row" = 502, #"Column" = 189, #"Percentage" = 75.17],
					        [#"Row" = 671, #"Column" = 501, #"Percentage" = 68.48],
					        [#"Row" = 745, #"Column" = 440, #"Percentage" = 99.88],
					        [#"Row" = 483, #"Column" = 481, #"Percentage" = 44.29],
					        [#"Row" = 279, #"Column" = 930, #"Percentage" = 72.14],
					        [#"Row" = 929, #"Column" = 629, #"Percentage" = 62.21],
					        [#"Row" = 33, #"Column" = 606, #"Percentage" = 22.13],
					        [#"Row" = 265, #"Column" = 18, #"Percentage" = 27.83],
					        [#"Row" = 928, #"Column" = 145, #"Percentage" = 82.14],
					        [#"Row" = 375, #"Column" = 802, #"Percentage" = 40.23],
					        [#"Row" = 198, #"Column" = 434, #"Percentage" = 39.63],
					        [#"Row" = 811, #"Column" = 665, #"Percentage" = 100.0],
					        [#"Row" = 885, #"Column" = 814, #"Percentage" = 54.43],
					        [#"Row" = 259, #"Column" = 758, #"Percentage" = 14.84],
					        [#"Row" = 287, #"Column" = 440, #"Percentage" = 32.52],
					        [#"Row" = 965, #"Column" = 296, #"Percentage" = 97.64],
					        [#"Row" = 789, #"Column" = 876, #"Percentage" = 34.28],
					        [#"Row" = 41, #"Column" = 910, #"Percentage" = 71.92],
					        [#"Row" = 578, #"Column" = 192, #"Percentage" = 63.76],
					        [#"Row" = 583, #"Column" = 649, #"Percentage" = 66.29],
					        [#"Row" = 529, #"Column" = 753, #"Percentage" = 14.92],
					        [#"Row" = 143, #"Column" = 748, #"Percentage" = 48.14],
					        [#"Row" = 964, #"Column" = 852, #"Percentage" = 16.17],
					        [#"Row" = 972, #"Column" = 434, #"Percentage" = 38.86],
					        [#"Row" = 743, #"Column" = 857, #"Percentage" = 20.11],
					        [#"Row" = 86, #"Column" = 484, #"Percentage" = 22.27],
					        [#"Row" = 285, #"Column" = 570, #"Percentage" = 33.74],
					        [#"Row" = 627, #"Column" = 809, #"Percentage" = 11.23],
					        [#"Row" = 595, #"Column" = 17, #"Percentage" = 93.77],
					        [#"Row" = 817, #"Column" = 410, #"Percentage" = 28.83],
					        [#"Row" = 629, #"Column" = 917, #"Percentage" = 81.66],
					        [#"Row" = 779, #"Column" = 485, #"Percentage" = 93.84],
					        [#"Row" = 668, #"Column" = 302, #"Percentage" = 48.58],
					        [#"Row" = 274, #"Column" = 987, #"Percentage" = 44.28],
					        [#"Row" = 943, #"Column" = 691, #"Percentage" = 3.74],
					        [#"Row" = 702, #"Column" = 723, #"Percentage" = 8.1],
					        [#"Row" = 555, #"Column" = 440, #"Percentage" = 12.4],
					        [#"Row" = 611, #"Column" = 607, #"Percentage" = 8.12],
					        [#"Row" = 458, #"Column" = 629, #"Percentage" = 99.32],
					        [#"Row" = 585, #"Column" = 8, #"Percentage" = 84.75],
					        [#"Row" = 55, #"Column" = 603, #"Percentage" = 80.26],
					        [#"Row" = 632, #"Column" = 932, #"Percentage" = 44.76],
					        [#"Row" = 851, #"Column" = 248, #"Percentage" = 96.76],
					        [#"Row" = 242, #"Column" = 946, #"Percentage" = 32.67],
					        [#"Row" = 29, #"Column" = 25, #"Percentage" = 25.95],
					        [#"Row" = 829, #"Column" = 302, #"Percentage" = 78.63],
					        [#"Row" = 745, #"Column" = 794, #"Percentage" = 15.13],
					        [#"Row" = 390, #"Column" = 777, #"Percentage" = 86.61],
					        [#"Row" = 922, #"Column" = 233, #"Percentage" = 15.96],
					        [#"Row" = 486, #"Column" = 904, #"Percentage" = 62.89],
					        [#"Row" = 387, #"Column" = 922, #"Percentage" = 20.72],
					        [#"Row" = 196, #"Column" = 316, #"Percentage" = 79.39],
					        [#"Row" = 128, #"Column" = 657, #"Percentage" = 7.58],
					        [#"Row" = 210, #"Column" = 957, #"Percentage" = 34.84],
					        [#"Row" = 897, #"Column" = 871, #"Percentage" = 48.05],
					        [#"Row" = 919, #"Column" = 434, #"Percentage" = 2.51],
					        [#"Row" = 975, #"Column" = 724, #"Percentage" = 44.32],
					        [#"Row" = 132, #"Column" = 617, #"Percentage" = 70.8],
					        [#"Row" = 112, #"Column" = 814, #"Percentage" = 91.4],
					        [#"Row" = 622, #"Column" = 611, #"Percentage" = 31.4],
					        [#"Row" = 323, #"Column" = 117, #"Percentage" = 53.88],
					        [#"Row" = 945, #"Column" = 757, #"Percentage" = 3.57],
					        [#"Row" = 172, #"Column" = 130, #"Percentage" = 99.88],
					        [#"Row" = 170, #"Column" = 757, #"Percentage" = 62.61],
					        [#"Row" = 783, #"Column" = 490, #"Percentage" = 73.32],
					        [#"Row" = 78, #"Column" = 512, #"Percentage" = 78.49],
					        [#"Row" = 816, #"Column" = 202, #"Percentage" = 68.9],
					        [#"Row" = 97, #"Column" = 219, #"Percentage" = 15.99],
					        [#"Row" = 600, #"Column" = 121, #"Percentage" = 41.45],
					        [#"Row" = 301, #"Column" = 276, #"Percentage" = 85.48],
					        [#"Row" = 61, #"Column" = 427, #"Percentage" = 62.8],
					        [#"Row" = 394, #"Column" = 645, #"Percentage" = 45.11],
					        [#"Row" = 150, #"Column" = 412, #"Percentage" = 42.12],
					        [#"Row" = 660, #"Column" = 988, #"Percentage" = 2.17],
					        [#"Row" = 202, #"Column" = 854, #"Percentage" = 33.88],
					        [#"Row" = 848, #"Column" = 871, #"Percentage" = 29.16],
					        [#"Row" = 156, #"Column" = 174, #"Percentage" = 24.02],
					        [#"Row" = 377, #"Column" = 864, #"Percentage" = 19.52],
					        [#"Row" = 997, #"Column" = 98, #"Percentage" = 91.12],
					        [#"Row" = 348, #"Column" = 284, #"Percentage" = 49.77],
					        [#"Row" = 737, #"Column" = 643, #"Percentage" = 48.86],
					        [#"Row" = 190, #"Column" = 423, #"Percentage" = 84.73],
					        [#"Row" = 392, #"Column" = 796, #"Percentage" = 25.23],
					        [#"Row" = 773, #"Column" = 922, #"Percentage" = 6.77],
					        [#"Row" = 533, #"Column" = 302, #"Percentage" = 31.31],
					        [#"Row" = 338, #"Column" = 982, #"Percentage" = 86.87],
					        [#"Row" = 281, #"Column" = 410, #"Percentage" = 53.68],
					        [#"Row" = 605, #"Column" = 485, #"Percentage" = 55.52],
					        [#"Row" = 840, #"Column" = 106, #"Percentage" = 29.74],
					        [#"Row" = 628, #"Column" = 971, #"Percentage" = 17.54],
					        [#"Row" = 741, #"Column" = 915, #"Percentage" = 54.97],
					        [#"Row" = 720, #"Column" = 917, #"Percentage" = 35.71],
					        [#"Row" = 258, #"Column" = 712, #"Percentage" = 59.11],
					        [#"Row" = 717, #"Column" = 218, #"Percentage" = 50.04],
					        [#"Row" = 5, #"Column" = 481, #"Percentage" = 88.18],
					        [#"Row" = 929, #"Column" = 98, #"Percentage" = 45.37],
					        [#"Row" = 939, #"Column" = 605, #"Percentage" = 2.35],
					        [#"Row" = 978, #"Column" = 644, #"Percentage" = 57.86],
					        [#"Row" = 13, #"Column" = 87, #"Percentage" = 69.08],
					        [#"Row" = 649, #"Column" = 599, #"Percentage" = 74.14],
					        [#"Row" = 302, #"Column" = 406, #"Percentage" = 56.96],
					        [#"Row" = 599, #"Column" = 67, #"Percentage" = 31.62],
					        [#"Row" = 313, #"Column" = 883, #"Percentage" = 55.13],
					        [#"Row" = 705, #"Column" = 689, #"Percentage" = 17.53],
					        [#"Row" = 389, #"Column" = 709, #"Percentage" = 67.75],
					        [#"Row" = 983, #"Column" = 307, #"Percentage" = 43.6],
					        [#"Row" = 349, #"Column" = 633, #"Percentage" = 87.92],
					        [#"Row" = 188, #"Column" = 787, #"Percentage" = 45.4],
					        [#"Row" = 509, #"Column" = 894, #"Percentage" = 75.88],
					        [#"Row" = 227, #"Column" = 438, #"Percentage" = 64.23],
					        [#"Row" = 929, #"Column" = 14, #"Percentage" = 90.69],
					        [#"Row" = 565, #"Column" = 763, #"Percentage" = 62.11],
					        [#"Row" = 793, #"Column" = 352, #"Percentage" = 58.38],
					        [#"Row" = 826, #"Column" = 990, #"Percentage" = 8.06],
					        [#"Row" = 11, #"Column" = 768, #"Percentage" = 57.74],
					        [#"Row" = 9, #"Column" = 32, #"Percentage" = 69.74],
					        [#"Row" = 148, #"Column" = 531, #"Percentage" = 52.19],
					        [#"Row" = 189, #"Column" = 942, #"Percentage" = 25.98],
					        [#"Row" = 234, #"Column" = 623, #"Percentage" = 16.27],
					        [#"Row" = 877, #"Column" = 520, #"Percentage" = 50.49],
					        [#"Row" = 306, #"Column" = 984, #"Percentage" = 79.77],
					        [#"Row" = 339, #"Column" = 310, #"Percentage" = 9.67],
					        [#"Row" = 246, #"Column" = 650, #"Percentage" = 23.0],
					        [#"Row" = 963, #"Column" = 265, #"Percentage" = 63.65],
					        [#"Row" = 604, #"Column" = 12, #"Percentage" = 17.77],
					        [#"Row" = 982, #"Column" = 846, #"Percentage" = 72.64],
					        [#"Row" = 944, #"Column" = 147, #"Percentage" = 89.25],
					        [#"Row" = 410, #"Column" = 965, #"Percentage" = 41.0],
					        [#"Row" = 745, #"Column" = 353, #"Percentage" = 45.4],
					        [#"Row" = 897, #"Column" = 727, #"Percentage" = 64.5],
					        [#"Row" = 998, #"Column" = 630, #"Percentage" = 58.45],
					        [#"Row" = 525, #"Column" = 43, #"Percentage" = 50.64],
					        [#"Row" = 110, #"Column" = 595, #"Percentage" = 33.44],
					        [#"Row" = 871, #"Column" = 487, #"Percentage" = 64.81],
					        [#"Row" = 412, #"Column" = 419, #"Percentage" = 65.61],
					        [#"Row" = 51, #"Column" = 272, #"Percentage" = 5.05],
					        [#"Row" = 69, #"Column" = 536, #"Percentage" = 3.47],
					        [#"Row" = 485, #"Column" = 334, #"Percentage" = 87.49],
					        [#"Row" = 571, #"Column" = 483, #"Percentage" = 45.96],
					        [#"Row" = 522, #"Column" = 314, #"Percentage" = 2.66],
					        [#"Row" = 846, #"Column" = 582, #"Percentage" = 72.37],
					        [#"Row" = 996, #"Column" = 912, #"Percentage" = 15.91],
					        [#"Row" = 300, #"Column" = 280, #"Percentage" = 61.46],
					        [#"Row" = 535, #"Column" = 463, #"Percentage" = 6.67],
					        [#"Row" = 638, #"Column" = 376, #"Percentage" = 50.64],
					        [#"Row" = 167, #"Column" = 695, #"Percentage" = 73.87],
					        [#"Row" = 927, #"Column" = 970, #"Percentage" = 63.94],
					        [#"Row" = 911, #"Column" = 335, #"Percentage" = 84.46],
					        [#"Row" = 462, #"Column" = 324, #"Percentage" = 75.06],
					        [#"Row" = 113, #"Column" = 631, #"Percentage" = 73.63],
					        [#"Row" = 976, #"Column" = 628, #"Percentage" = 5.28],
					        [#"Row" = 622, #"Column" = 431, #"Percentage" = 14.83],
					        [#"Row" = 620, #"Column" = 326, #"Percentage" = 58.08],
					        [#"Row" = 923, #"Column" = 666, #"Percentage" = 91.47],
					        [#"Row" = 564, #"Column" = 620, #"Percentage" = 72.94],
					        [#"Row" = 104, #"Column" = 394, #"Percentage" = 55.61],
					        [#"Row" = 697, #"Column" = 404, #"Percentage" = 83.65],
					        [#"Row" = 270, #"Column" = 608, #"Percentage" = 50.59],
					        [#"Row" = 551, #"Column" = 565, #"Percentage" = 92.46],
					        [#"Row" = 504, #"Column" = 455, #"Percentage" = 61.46],
					        [#"Row" = 568, #"Column" = 282, #"Percentage" = 54.58],
					        [#"Row" = 516, #"Column" = 531, #"Percentage" = 2.57],
					        [#"Row" = 481, #"Column" = 646, #"Percentage" = 37.18],
					        [#"Row" = 698, #"Column" = 768, #"Percentage" = 70.05],
					        [#"Row" = 256, #"Column" = 821, #"Percentage" = 0.65],
					        [#"Row" = 324, #"Column" = 912, #"Percentage" = 79.76],
					        [#"Row" = 133, #"Column" = 733, #"Percentage" = 76.2],
					        [#"Row" = 937, #"Column" = 176, #"Percentage" = 94.92],
					        [#"Row" = 852, #"Column" = 863, #"Percentage" = 54.89],
					        [#"Row" = 711, #"Column" = 781, #"Percentage" = 16.87],
					        [#"Row" = 344, #"Column" = 827, #"Percentage" = 21.09],
					        [#"Row" = 522, #"Column" = 63, #"Percentage" = 4.49],
					        [#"Row" = 732, #"Column" = 608, #"Percentage" = 6.77],
					        [#"Row" = 626, #"Column" = 808, #"Percentage" = 80.65],
					        [#"Row" = 730, #"Column" = 894, #"Percentage" = 0.53],
					        [#"Row" = 278, #"Column" = 805, #"Percentage" = 98.99],
					        [#"Row" = 462, #"Column" = 718, #"Percentage" = 39.57],
					        [#"Row" = 213, #"Column" = 461, #"Percentage" = 85.16],
					        [#"Row" = 981, #"Column" = 538, #"Percentage" = 88.02],
					        [#"Row" = 539, #"Column" = 539, #"Percentage" = 31.8],
					        [#"Row" = 276, #"Column" = 677, #"Percentage" = 16.91],
					        [#"Row" = 415, #"Column" = 835, #"Percentage" = 78.78],
					        [#"Row" = 724, #"Column" = 253, #"Percentage" = 25.49],
					        [#"Row" = 539, #"Column" = 529, #"Percentage" = 24.28],
					        [#"Row" = 447, #"Column" = 752, #"Percentage" = 37.66],
					        [#"Row" = 104, #"Column" = 284, #"Percentage" = 78.4],
					        [#"Row" = 379, #"Column" = 67, #"Percentage" = 35.99],
					        [#"Row" = 49, #"Column" = 472, #"Percentage" = 48.35],
					        [#"Row" = 912, #"Column" = 842, #"Percentage" = 94.03],
					        [#"Row" = 492, #"Column" = 542, #"Percentage" = 7.85],
					        [#"Row" = 523, #"Column" = 618, #"Percentage" = 75.01],
					        [#"Row" = 91, #"Column" = 986, #"Percentage" = 51.18],
					        [#"Row" = 198, #"Column" = 166, #"Percentage" = 11.52],
					        [#"Row" = 430, #"Column" = 175, #"Percentage" = 29.39],
					        [#"Row" = 23, #"Column" = 835, #"Percentage" = 10.16],
					        [#"Row" = 99, #"Column" = 27, #"Percentage" = 32.75]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Row", Int64.Type},
					        {"Column", Int64.Type},
					        {"Percentage", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table