table 'Sheet1_Sheet1 (radial_bar_chart_data)'
	lineageTag: 23b8cdcc-86d1-43bb-ae23-72e236505380

	column StoreType
		dataType: string
		lineageTag: 18d549fb-17f1-4c07-bdcf-c6c138eeeb4b
		summarizeBy: none
		sourceColumn: StoreType

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: 8eecc174-5071-492a-b0bb-f76c3e41c77c
		summarizeBy: sum
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	column Ratio
		dataType: double
		formatString: General Number
		lineageTag: bf859bee-d202-4c74-8c4a-8dd4010e2444
		summarizeBy: sum
		sourceColumn: Ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Path
		dataType: int64
		formatString: 0
		lineageTag: 88c2e668-7f56-4a91-88c2-1992ede9f401
		summarizeBy: sum
		sourceColumn: Path

		annotation SummarizationSetBy = Automatic

	partition 'Sheet1_Sheet1 (radial_bar_chart_data)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"StoreType" = "mature", #"Order" = 802, #"Ratio" = 9.07, #"Path" = 858],
					        [#"StoreType" = "talks", #"Order" = 841, #"Ratio" = 967.38, #"Path" = 58],
					        [#"StoreType" = "mystery", #"Order" = 944, #"Ratio" = 156.72, #"Path" = 883],
					        [#"StoreType" = "lease", #"Order" = 90, #"Ratio" = 188.18, #"Path" = 734],
					        [#"StoreType" = "industry", #"Order" = 911, #"Ratio" = 978.12, #"Path" = 888],
					        [#"StoreType" = "walking", #"Order" = 636, #"Ratio" = 374.72, #"Path" = 854],
					        [#"StoreType" = "constant", #"Order" = 911, #"Ratio" = 831.46, #"Path" = 736],
					        [#"StoreType" = "stable", #"Order" = 482, #"Ratio" = 196.65, #"Path" = 527],
					        [#"StoreType" = "himself", #"Order" = 389, #"Ratio" = 352.46, #"Path" = 220],
					        [#"StoreType" = "burning", #"Order" = 378, #"Ratio" = 641.22, #"Path" = 65],
					        [#"StoreType" = "millions", #"Order" = 687, #"Ratio" = 121.11, #"Path" = 793],
					        [#"StoreType" = "along", #"Order" = 956, #"Ratio" = 187.26, #"Path" = 123],
					        [#"StoreType" = "institute", #"Order" = 992, #"Ratio" = 73.54, #"Path" = 290],
					        [#"StoreType" = "getting", #"Order" = 630, #"Ratio" = 462.12, #"Path" = 746],
					        [#"StoreType" = "sponsors", #"Order" = 189, #"Ratio" = 615.38, #"Path" = 85],
					        [#"StoreType" = "prints", #"Order" = 207, #"Ratio" = 394.54, #"Path" = 475],
					        [#"StoreType" = "amazon", #"Order" = 142, #"Ratio" = 450.61, #"Path" = 911],
					        [#"StoreType" = "ian", #"Order" = 295, #"Ratio" = 720.56, #"Path" = 694],
					        [#"StoreType" = "screens", #"Order" = 124, #"Ratio" = 264.72, #"Path" = 391],
					        [#"StoreType" = "parker", #"Order" = 338, #"Ratio" = 846.57, #"Path" = 236],
					        [#"StoreType" = "explain", #"Order" = 493, #"Ratio" = 624.28, #"Path" = 85],
					        [#"StoreType" = "russia", #"Order" = 576, #"Ratio" = 620.66, #"Path" = 395],
					        [#"StoreType" = "expansion", #"Order" = 74, #"Ratio" = 112.82, #"Path" = 984],
					        [#"StoreType" = "kids", #"Order" = 460, #"Ratio" = 679.56, #"Path" = 767],
					        [#"StoreType" = "central", #"Order" = 869, #"Ratio" = 446.42, #"Path" = 913],
					        [#"StoreType" = "suitable", #"Order" = 84, #"Ratio" = 821.4, #"Path" = 863],
					        [#"StoreType" = "wiki", #"Order" = 316, #"Ratio" = 785.8, #"Path" = 889],
					        [#"StoreType" = "biggest", #"Order" = 61, #"Ratio" = 759.49, #"Path" = 124],
					        [#"StoreType" = "sr", #"Order" = 338, #"Ratio" = 140.47, #"Path" = 118],
					        [#"StoreType" = "crisis", #"Order" = 956, #"Ratio" = 229.63, #"Path" = 33],
					        [#"StoreType" = "charity", #"Order" = 199, #"Ratio" = 505.75, #"Path" = 41],
					        [#"StoreType" = "meat", #"Order" = 476, #"Ratio" = 136.9, #"Path" = 698],
					        [#"StoreType" = "actions", #"Order" = 50, #"Ratio" = 651.68, #"Path" = 607],
					        [#"StoreType" = "console", #"Order" = 864, #"Ratio" = 703.72, #"Path" = 326],
					        [#"StoreType" = "blade", #"Order" = 89, #"Ratio" = 268.47, #"Path" = 619],
					        [#"StoreType" = "funeral", #"Order" = 715, #"Ratio" = 24.57, #"Path" = 639],
					        [#"StoreType" = "essay", #"Order" = 243, #"Ratio" = 813.84, #"Path" = 112],
					        [#"StoreType" = "operators", #"Order" = 426, #"Ratio" = 273.33, #"Path" = 962],
					        [#"StoreType" = "album", #"Order" = 967, #"Ratio" = 749.27, #"Path" = 375],
					        [#"StoreType" = "org", #"Order" = 462, #"Ratio" = 706.7, #"Path" = 24],
					        [#"StoreType" = "opening", #"Order" = 399, #"Ratio" = 967.62, #"Path" = 163],
					        [#"StoreType" = "capture", #"Order" = 531, #"Ratio" = 719.01, #"Path" = 300],
					        [#"StoreType" = "arts", #"Order" = 489, #"Ratio" = 174.73, #"Path" = 797],
					        [#"StoreType" = "electronics", #"Order" = 932, #"Ratio" = 117.89, #"Path" = 446],
					        [#"StoreType" = "contacts", #"Order" = 95, #"Ratio" = 624.89, #"Path" = 61],
					        [#"StoreType" = "horse", #"Order" = 535, #"Ratio" = 676.09, #"Path" = 502],
					        [#"StoreType" = "dont", #"Order" = 835, #"Ratio" = 35.86, #"Path" = 403],
					        [#"StoreType" = "advisory", #"Order" = 881, #"Ratio" = 874.25, #"Path" = 777],
					        [#"StoreType" = "boxes", #"Order" = 60, #"Ratio" = 668.56, #"Path" = 819],
					        [#"StoreType" = "that", #"Order" = 901, #"Ratio" = 573.24, #"Path" = 127],
					        [#"StoreType" = "produce", #"Order" = 259, #"Ratio" = 413.61, #"Path" = 289],
					        [#"StoreType" = "permission", #"Order" = 46, #"Ratio" = 624.93, #"Path" = 694],
					        [#"StoreType" = "worship", #"Order" = 898, #"Ratio" = 938.89, #"Path" = 673],
					        [#"StoreType" = "married", #"Order" = 630, #"Ratio" = 281.08, #"Path" = 357],
					        [#"StoreType" = "subsequent", #"Order" = 510, #"Ratio" = 530.19, #"Path" = 732],
					        [#"StoreType" = "bad", #"Order" = 391, #"Ratio" = 597.58, #"Path" = 164],
					        [#"StoreType" = "patch", #"Order" = 306, #"Ratio" = 649.97, #"Path" = 521],
					        [#"StoreType" = "spa", #"Order" = 106, #"Ratio" = 667.29, #"Path" = 292],
					        [#"StoreType" = "noticed", #"Order" = 72, #"Ratio" = 607.71, #"Path" = 272],
					        [#"StoreType" = "expressed", #"Order" = 346, #"Ratio" = 118.09, #"Path" = 234],
					        [#"StoreType" = "howard", #"Order" = 435, #"Ratio" = 920.37, #"Path" = 123],
					        [#"StoreType" = "publish", #"Order" = 207, #"Ratio" = 636.18, #"Path" = 49],
					        [#"StoreType" = "campaign", #"Order" = 596, #"Ratio" = 485.74, #"Path" = 551],
					        [#"StoreType" = "er", #"Order" = 637, #"Ratio" = 582.76, #"Path" = 519],
					        [#"StoreType" = "settlement", #"Order" = 594, #"Ratio" = 126.66, #"Path" = 946],
					        [#"StoreType" = "lesson", #"Order" = 862, #"Ratio" = 786.72, #"Path" = 201],
					        [#"StoreType" = "survival", #"Order" = 437, #"Ratio" = 248.45, #"Path" = 300],
					        [#"StoreType" = "analyst", #"Order" = 85, #"Ratio" = 196.07, #"Path" = 935],
					        [#"StoreType" = "favorite", #"Order" = 413, #"Ratio" = 638.71, #"Path" = 615],
					        [#"StoreType" = "deep", #"Order" = 1, #"Ratio" = 709.63, #"Path" = 131],
					        [#"StoreType" = "ave", #"Order" = 955, #"Ratio" = 159.71, #"Path" = 740],
					        [#"StoreType" = "americans", #"Order" = 70, #"Ratio" = 926.34, #"Path" = 359],
					        [#"StoreType" = "lies", #"Order" = 496, #"Ratio" = 999.25, #"Path" = 751],
					        [#"StoreType" = "anne", #"Order" = 677, #"Ratio" = 558.09, #"Path" = 626],
					        [#"StoreType" = "different", #"Order" = 337, #"Ratio" = 398.91, #"Path" = 123],
					        [#"StoreType" = "proud", #"Order" = 575, #"Ratio" = 728.53, #"Path" = 112],
					        [#"StoreType" = "webmaster", #"Order" = 122, #"Ratio" = 876.31, #"Path" = 415],
					        [#"StoreType" = "beginning", #"Order" = 885, #"Ratio" = 969.76, #"Path" = 866],
					        [#"StoreType" = "ng", #"Order" = 27, #"Ratio" = 705.77, #"Path" = 139],
					        [#"StoreType" = "workforce", #"Order" = 366, #"Ratio" = 279.16, #"Path" = 404],
					        [#"StoreType" = "banking", #"Order" = 437, #"Ratio" = 206.39, #"Path" = 360],
					        [#"StoreType" = "intelligent", #"Order" = 517, #"Ratio" = 104.81, #"Path" = 901],
					        [#"StoreType" = "prepared", #"Order" = 34, #"Ratio" = 86.65, #"Path" = 561],
					        [#"StoreType" = "australia", #"Order" = 476, #"Ratio" = 115.05, #"Path" = 912],
					        [#"StoreType" = "uses", #"Order" = 964, #"Ratio" = 770.35, #"Path" = 926],
					        [#"StoreType" = "married", #"Order" = 812, #"Ratio" = 426.72, #"Path" = 435],
					        [#"StoreType" = "maybe", #"Order" = 324, #"Ratio" = 933.1, #"Path" = 651],
					        [#"StoreType" = "rough", #"Order" = 645, #"Ratio" = 773.87, #"Path" = 11],
					        [#"StoreType" = "step", #"Order" = 703, #"Ratio" = 586.6, #"Path" = 658],
					        [#"StoreType" = "plugin", #"Order" = 173, #"Ratio" = 347.39, #"Path" = 837],
					        [#"StoreType" = "attention", #"Order" = 937, #"Ratio" = 313.84, #"Path" = 311],
					        [#"StoreType" = "sales", #"Order" = 553, #"Ratio" = 484.94, #"Path" = 414],
					        [#"StoreType" = "lecture", #"Order" = 246, #"Ratio" = 238.05, #"Path" = 194],
					        [#"StoreType" = "connect", #"Order" = 321, #"Ratio" = 375.29, #"Path" = 128],
					        [#"StoreType" = "announcements", #"Order" = 145, #"Ratio" = 670.14, #"Path" = 318],
					        [#"StoreType" = "finance", #"Order" = 17, #"Ratio" = 255.62, #"Path" = 154],
					        [#"StoreType" = "ages", #"Order" = 611, #"Ratio" = 252.6, #"Path" = 864],
					        [#"StoreType" = "me", #"Order" = 715, #"Ratio" = 27.39, #"Path" = 626],
					        [#"StoreType" = "stem", #"Order" = 993, #"Ratio" = 845.43, #"Path" = 107],
					        [#"StoreType" = "arizona", #"Order" = 117, #"Ratio" = 486.23, #"Path" = 97],
					        [#"StoreType" = "puerto", #"Order" = 231, #"Ratio" = 883.98, #"Path" = 622],
					        [#"StoreType" = "principles", #"Order" = 151, #"Ratio" = 2.29, #"Path" = 246],
					        [#"StoreType" = "single", #"Order" = 346, #"Ratio" = 770.3, #"Path" = 344],
					        [#"StoreType" = "cemetery", #"Order" = 423, #"Ratio" = 87.63, #"Path" = 241],
					        [#"StoreType" = "embedded", #"Order" = 782, #"Ratio" = 727.21, #"Path" = 939],
					        [#"StoreType" = "toward", #"Order" = 210, #"Ratio" = 342.74, #"Path" = 190],
					        [#"StoreType" = "gr", #"Order" = 219, #"Ratio" = 946.48, #"Path" = 452],
					        [#"StoreType" = "marks", #"Order" = 178, #"Ratio" = 994.25, #"Path" = 129],
					        [#"StoreType" = "limited", #"Order" = 426, #"Ratio" = 961.98, #"Path" = 590],
					        [#"StoreType" = "brokers", #"Order" = 246, #"Ratio" = 998.82, #"Path" = 737],
					        [#"StoreType" = "affiliates", #"Order" = 724, #"Ratio" = 495.69, #"Path" = 350],
					        [#"StoreType" = "algorithm", #"Order" = 913, #"Ratio" = 790.79, #"Path" = 671],
					        [#"StoreType" = "usually", #"Order" = 62, #"Ratio" = 864.67, #"Path" = 163],
					        [#"StoreType" = "political", #"Order" = 598, #"Ratio" = 341.59, #"Path" = 842],
					        [#"StoreType" = "pocket", #"Order" = 751, #"Ratio" = 670.43, #"Path" = 774],
					        [#"StoreType" = "rocks", #"Order" = 283, #"Ratio" = 176.29, #"Path" = 314],
					        [#"StoreType" = "hybrid", #"Order" = 904, #"Ratio" = 827.78, #"Path" = 41],
					        [#"StoreType" = "hide", #"Order" = 605, #"Ratio" = 510.65, #"Path" = 413],
					        [#"StoreType" = "sounds", #"Order" = 326, #"Ratio" = 478.75, #"Path" = 460],
					        [#"StoreType" = "dinner", #"Order" = 473, #"Ratio" = 240.99, #"Path" = 477],
					        [#"StoreType" = "prepared", #"Order" = 179, #"Ratio" = 221.2, #"Path" = 96],
					        [#"StoreType" = "logo", #"Order" = 88, #"Ratio" = 64.2, #"Path" = 675],
					        [#"StoreType" = "medicare", #"Order" = 668, #"Ratio" = 776.08, #"Path" = 942],
					        [#"StoreType" = "reliable", #"Order" = 303, #"Ratio" = 814.12, #"Path" = 355],
					        [#"StoreType" = "level", #"Order" = 810, #"Ratio" = 572.04, #"Path" = 616],
					        [#"StoreType" = "photograph", #"Order" = 645, #"Ratio" = 744.28, #"Path" = 648],
					        [#"StoreType" = "marriott", #"Order" = 163, #"Ratio" = 713.03, #"Path" = 169],
					        [#"StoreType" = "videos", #"Order" = 336, #"Ratio" = 736.09, #"Path" = 333],
					        [#"StoreType" = "tons", #"Order" = 172, #"Ratio" = 194.29, #"Path" = 761],
					        [#"StoreType" = "down", #"Order" = 382, #"Ratio" = 422.06, #"Path" = 462],
					        [#"StoreType" = "ent", #"Order" = 118, #"Ratio" = 441.79, #"Path" = 990],
					        [#"StoreType" = "hat", #"Order" = 239, #"Ratio" = 640.67, #"Path" = 281],
					        [#"StoreType" = "important", #"Order" = 873, #"Ratio" = 452.96, #"Path" = 831],
					        [#"StoreType" = "huge", #"Order" = 184, #"Ratio" = 427.87, #"Path" = 940],
					        [#"StoreType" = "cases", #"Order" = 51, #"Ratio" = 159.34, #"Path" = 177],
					        [#"StoreType" = "steps", #"Order" = 234, #"Ratio" = 467.9, #"Path" = 128],
					        [#"StoreType" = "ya", #"Order" = 121, #"Ratio" = 609.11, #"Path" = 812],
					        [#"StoreType" = "bishop", #"Order" = 440, #"Ratio" = 261.77, #"Path" = 780],
					        [#"StoreType" = "chi", #"Order" = 569, #"Ratio" = 851.83, #"Path" = 401],
					        [#"StoreType" = "was", #"Order" = 876, #"Ratio" = 140.69, #"Path" = 460],
					        [#"StoreType" = "help", #"Order" = 776, #"Ratio" = 445.24, #"Path" = 324],
					        [#"StoreType" = "objects", #"Order" = 892, #"Ratio" = 563.72, #"Path" = 460],
					        [#"StoreType" = "classes", #"Order" = 149, #"Ratio" = 371.52, #"Path" = 918],
					        [#"StoreType" = "counts", #"Order" = 257, #"Ratio" = 455.76, #"Path" = 756],
					        [#"StoreType" = "situation", #"Order" = 314, #"Ratio" = 962.77, #"Path" = 580],
					        [#"StoreType" = "ties", #"Order" = 140, #"Ratio" = 90.1, #"Path" = 683],
					        [#"StoreType" = "throw", #"Order" = 29, #"Ratio" = 794.11, #"Path" = 378],
					        [#"StoreType" = "good", #"Order" = 83, #"Ratio" = 854.36, #"Path" = 720],
					        [#"StoreType" = "near", #"Order" = 749, #"Ratio" = 92.66, #"Path" = 201],
					        [#"StoreType" = "wearing", #"Order" = 457, #"Ratio" = 793.28, #"Path" = 973],
					        [#"StoreType" = "dsl", #"Order" = 774, #"Ratio" = 185.38, #"Path" = 785],
					        [#"StoreType" = "jason", #"Order" = 243, #"Ratio" = 409.15, #"Path" = 98],
					        [#"StoreType" = "raw", #"Order" = 362, #"Ratio" = 484.58, #"Path" = 338],
					        [#"StoreType" = "princess", #"Order" = 242, #"Ratio" = 119.37, #"Path" = 700],
					        [#"StoreType" = "resulting", #"Order" = 621, #"Ratio" = 848.87, #"Path" = 576],
					        [#"StoreType" = "description", #"Order" = 465, #"Ratio" = 150.19, #"Path" = 135],
					        [#"StoreType" = "scan", #"Order" = 555, #"Ratio" = 886.95, #"Path" = 123],
					        [#"StoreType" = "maker", #"Order" = 349, #"Ratio" = 196.45, #"Path" = 125],
					        [#"StoreType" = "nobody", #"Order" = 44, #"Ratio" = 610.12, #"Path" = 186],
					        [#"StoreType" = "adapter", #"Order" = 705, #"Ratio" = 363.03, #"Path" = 376],
					        [#"StoreType" = "webcam", #"Order" = 396, #"Ratio" = 856.59, #"Path" = 593],
					        [#"StoreType" = "eye", #"Order" = 824, #"Ratio" = 678.65, #"Path" = 209],
					        [#"StoreType" = "domain", #"Order" = 692, #"Ratio" = 155.44, #"Path" = 610],
					        [#"StoreType" = "lost", #"Order" = 189, #"Ratio" = 274.43, #"Path" = 257],
					        [#"StoreType" = "remained", #"Order" = 560, #"Ratio" = 545.5, #"Path" = 817],
					        [#"StoreType" = "considerable", #"Order" = 808, #"Ratio" = 893.06, #"Path" = 980],
					        [#"StoreType" = "glasses", #"Order" = 995, #"Ratio" = 440.93, #"Path" = 790],
					        [#"StoreType" = "sign", #"Order" = 694, #"Ratio" = 7.63, #"Path" = 723],
					        [#"StoreType" = "broadcasting", #"Order" = 705, #"Ratio" = 634.28, #"Path" = 752],
					        [#"StoreType" = "cv", #"Order" = 264, #"Ratio" = 222.67, #"Path" = 621],
					        [#"StoreType" = "thru", #"Order" = 216, #"Ratio" = 813.05, #"Path" = 319],
					        [#"StoreType" = "learned", #"Order" = 907, #"Ratio" = 834.62, #"Path" = 120],
					        [#"StoreType" = "weekly", #"Order" = 986, #"Ratio" = 736.06, #"Path" = 421],
					        [#"StoreType" = "company", #"Order" = 189, #"Ratio" = 693.95, #"Path" = 479],
					        [#"StoreType" = "measurement", #"Order" = 645, #"Ratio" = 78.16, #"Path" = 445],
					        [#"StoreType" = "somewhat", #"Order" = 433, #"Ratio" = 276.27, #"Path" = 762],
					        [#"StoreType" = "cookie", #"Order" = 481, #"Ratio" = 992.28, #"Path" = 854],
					        [#"StoreType" = "both", #"Order" = 938, #"Ratio" = 660.68, #"Path" = 441],
					        [#"StoreType" = "describes", #"Order" = 403, #"Ratio" = 346.51, #"Path" = 895],
					        [#"StoreType" = "designer", #"Order" = 718, #"Ratio" = 803.87, #"Path" = 574],
					        [#"StoreType" = "pics", #"Order" = 782, #"Ratio" = 323.19, #"Path" = 325],
					        [#"StoreType" = "cam", #"Order" = 666, #"Ratio" = 750.32, #"Path" = 325],
					        [#"StoreType" = "along", #"Order" = 114, #"Ratio" = 276.83, #"Path" = 385],
					        [#"StoreType" = "discussions", #"Order" = 875, #"Ratio" = 83.7, #"Path" = 666],
					        [#"StoreType" = "ages", #"Order" = 752, #"Ratio" = 646.26, #"Path" = 499],
					        [#"StoreType" = "during", #"Order" = 903, #"Ratio" = 825.89, #"Path" = 175],
					        [#"StoreType" = "naturally", #"Order" = 830, #"Ratio" = 818.6, #"Path" = 154],
					        [#"StoreType" = "prevention", #"Order" = 289, #"Ratio" = 690.95, #"Path" = 896],
					        [#"StoreType" = "management", #"Order" = 961, #"Ratio" = 722.25, #"Path" = 700],
					        [#"StoreType" = "she", #"Order" = 725, #"Ratio" = 548.41, #"Path" = 118],
					        [#"StoreType" = "malaysia", #"Order" = 412, #"Ratio" = 394.09, #"Path" = 130],
					        [#"StoreType" = "away", #"Order" = 844, #"Ratio" = 188.75, #"Path" = 851],
					        [#"StoreType" = "jamaica", #"Order" = 153, #"Ratio" = 757.61, #"Path" = 244],
					        [#"StoreType" = "steve", #"Order" = 129, #"Ratio" = 854.58, #"Path" = 185],
					        [#"StoreType" = "showtimes", #"Order" = 118, #"Ratio" = 449.34, #"Path" = 263],
					        [#"StoreType" = "introduced", #"Order" = 63, #"Ratio" = 841.64, #"Path" = 929],
					        [#"StoreType" = "reached", #"Order" = 907, #"Ratio" = 489.97, #"Path" = 64],
					        [#"StoreType" = "stick", #"Order" = 519, #"Ratio" = 455.13, #"Path" = 826],
					        [#"StoreType" = "every", #"Order" = 725, #"Ratio" = 177.47, #"Path" = 464],
					        [#"StoreType" = "style", #"Order" = 468, #"Ratio" = 835.13, #"Path" = 705],
					        [#"StoreType" = "aims", #"Order" = 861, #"Ratio" = 993.96, #"Path" = 364],
					        [#"StoreType" = "are", #"Order" = 709, #"Ratio" = 3.87, #"Path" = 177],
					        [#"StoreType" = "oregon", #"Order" = 71, #"Ratio" = 425.67, #"Path" = 859],
					        [#"StoreType" = "visa", #"Order" = 296, #"Ratio" = 489.36, #"Path" = 19],
					        [#"StoreType" = "aspects", #"Order" = 468, #"Ratio" = 225.85, #"Path" = 988],
					        [#"StoreType" = "recognized", #"Order" = 758, #"Ratio" = 483.06, #"Path" = 488],
					        [#"StoreType" = "remember", #"Order" = 413, #"Ratio" = 508.55, #"Path" = 839],
					        [#"StoreType" = "parties", #"Order" = 267, #"Ratio" = 361.65, #"Path" = 367],
					        [#"StoreType" = "antiques", #"Order" = 870, #"Ratio" = 599.41, #"Path" = 777],
					        [#"StoreType" = "involved", #"Order" = 386, #"Ratio" = 370.52, #"Path" = 111],
					        [#"StoreType" = "icon", #"Order" = 781, #"Ratio" = 369.56, #"Path" = 587],
					        [#"StoreType" = "poll", #"Order" = 55, #"Ratio" = 102.53, #"Path" = 684],
					        [#"StoreType" = "priced", #"Order" = 782, #"Ratio" = 353.21, #"Path" = 926],
					        [#"StoreType" = "ahead", #"Order" = 759, #"Ratio" = 401.29, #"Path" = 39],
					        [#"StoreType" = "hotel", #"Order" = 304, #"Ratio" = 644.14, #"Path" = 716],
					        [#"StoreType" = "lanka", #"Order" = 157, #"Ratio" = 87.27, #"Path" = 643],
					        [#"StoreType" = "subsection", #"Order" = 280, #"Ratio" = 235.56, #"Path" = 854],
					        [#"StoreType" = "careers", #"Order" = 598, #"Ratio" = 913.82, #"Path" = 221],
					        [#"StoreType" = "creek", #"Order" = 681, #"Ratio" = 529.3, #"Path" = 683],
					        [#"StoreType" = "outer", #"Order" = 439, #"Ratio" = 178.59, #"Path" = 958],
					        [#"StoreType" = "phoenix", #"Order" = 496, #"Ratio" = 588.63, #"Path" = 865],
					        [#"StoreType" = "afternoon", #"Order" = 612, #"Ratio" = 320.46, #"Path" = 213],
					        [#"StoreType" = "additions", #"Order" = 238, #"Ratio" = 206.27, #"Path" = 262],
					        [#"StoreType" = "coach", #"Order" = 967, #"Ratio" = 978.17, #"Path" = 922],
					        [#"StoreType" = "flight", #"Order" = 695, #"Ratio" = 784.42, #"Path" = 499],
					        [#"StoreType" = "guinea", #"Order" = 708, #"Ratio" = 553.69, #"Path" = 619],
					        [#"StoreType" = "info", #"Order" = 180, #"Ratio" = 548.2, #"Path" = 906],
					        [#"StoreType" = "lies", #"Order" = 476, #"Ratio" = 577.75, #"Path" = 254],
					        [#"StoreType" = "normally", #"Order" = 626, #"Ratio" = 186.48, #"Path" = 522],
					        [#"StoreType" = "shares", #"Order" = 137, #"Ratio" = 10.43, #"Path" = 477],
					        [#"StoreType" = "gm", #"Order" = 11, #"Ratio" = 305.18, #"Path" = 472],
					        [#"StoreType" = "promise", #"Order" = 831, #"Ratio" = 602.07, #"Path" = 203],
					        [#"StoreType" = "how", #"Order" = 170, #"Ratio" = 854.62, #"Path" = 780],
					        [#"StoreType" = "amd", #"Order" = 153, #"Ratio" = 559.12, #"Path" = 703],
					        [#"StoreType" = "evidence", #"Order" = 345, #"Ratio" = 509.16, #"Path" = 15],
					        [#"StoreType" = "french", #"Order" = 450, #"Ratio" = 169.26, #"Path" = 636],
					        [#"StoreType" = "graphic", #"Order" = 610, #"Ratio" = 612.7, #"Path" = 294],
					        [#"StoreType" = "sight", #"Order" = 782, #"Ratio" = 10.85, #"Path" = 673],
					        [#"StoreType" = "confidence", #"Order" = 818, #"Ratio" = 75.65, #"Path" = 108],
					        [#"StoreType" = "moved", #"Order" = 501, #"Ratio" = 76.45, #"Path" = 649],
					        [#"StoreType" = "def", #"Order" = 727, #"Ratio" = 245.08, #"Path" = 694],
					        [#"StoreType" = "census", #"Order" = 333, #"Ratio" = 534.1, #"Path" = 920],
					        [#"StoreType" = "lawn", #"Order" = 21, #"Ratio" = 30.14, #"Path" = 579],
					        [#"StoreType" = "apparently", #"Order" = 463, #"Ratio" = 478.8, #"Path" = 349],
					        [#"StoreType" = "evidence", #"Order" = 519, #"Ratio" = 496.87, #"Path" = 150],
					        [#"StoreType" = "customize", #"Order" = 271, #"Ratio" = 881.93, #"Path" = 350],
					        [#"StoreType" = "however", #"Order" = 459, #"Ratio" = 136.83, #"Path" = 4],
					        [#"StoreType" = "paypal", #"Order" = 424, #"Ratio" = 527.46, #"Path" = 162],
					        [#"StoreType" = "gold", #"Order" = 79, #"Ratio" = 573.72, #"Path" = 802],
					        [#"StoreType" = "separate", #"Order" = 955, #"Ratio" = 469.19, #"Path" = 88],
					        [#"StoreType" = "income", #"Order" = 257, #"Ratio" = 808.41, #"Path" = 578],
					        [#"StoreType" = "made", #"Order" = 454, #"Ratio" = 188.94, #"Path" = 660],
					        [#"StoreType" = "experience", #"Order" = 823, #"Ratio" = 86.32, #"Path" = 799],
					        [#"StoreType" = "vector", #"Order" = 732, #"Ratio" = 751.13, #"Path" = 848],
					        [#"StoreType" = "strip", #"Order" = 508, #"Ratio" = 785.87, #"Path" = 512],
					        [#"StoreType" = "nr", #"Order" = 112, #"Ratio" = 922.16, #"Path" = 628],
					        [#"StoreType" = "converter", #"Order" = 459, #"Ratio" = 85.67, #"Path" = 579],
					        [#"StoreType" = "jimmy", #"Order" = 280, #"Ratio" = 940.35, #"Path" = 493],
					        [#"StoreType" = "follows", #"Order" = 579, #"Ratio" = 151.12, #"Path" = 514],
					        [#"StoreType" = "lion", #"Order" = 68, #"Ratio" = 906.98, #"Path" = 515],
					        [#"StoreType" = "installation", #"Order" = 207, #"Ratio" = 318.21, #"Path" = 553],
					        [#"StoreType" = "payday", #"Order" = 212, #"Ratio" = 779.06, #"Path" = 15],
					        [#"StoreType" = "half", #"Order" = 886, #"Ratio" = 875.74, #"Path" = 629],
					        [#"StoreType" = "latin", #"Order" = 729, #"Ratio" = 595.36, #"Path" = 767],
					        [#"StoreType" = "campaign", #"Order" = 603, #"Ratio" = 53.53, #"Path" = 616],
					        [#"StoreType" = "ship", #"Order" = 698, #"Ratio" = 757.21, #"Path" = 720],
					        [#"StoreType" = "california", #"Order" = 872, #"Ratio" = 879.63, #"Path" = 642],
					        [#"StoreType" = "developments", #"Order" = 902, #"Ratio" = 30.29, #"Path" = 52],
					        [#"StoreType" = "virus", #"Order" = 817, #"Ratio" = 798.38, #"Path" = 295],
					        [#"StoreType" = "full", #"Order" = 362, #"Ratio" = 780.27, #"Path" = 120],
					        [#"StoreType" = "shall", #"Order" = 223, #"Ratio" = 935.44, #"Path" = 51],
					        [#"StoreType" = "decisions", #"Order" = 604, #"Ratio" = 786.12, #"Path" = 404],
					        [#"StoreType" = "disk", #"Order" = 490, #"Ratio" = 247.7, #"Path" = 375],
					        [#"StoreType" = "thermal", #"Order" = 582, #"Ratio" = 185.94, #"Path" = 375],
					        [#"StoreType" = "filled", #"Order" = 696, #"Ratio" = 535.01, #"Path" = 750],
					        [#"StoreType" = "impacts", #"Order" = 634, #"Ratio" = 783.09, #"Path" = 518],
					        [#"StoreType" = "gen", #"Order" = 619, #"Ratio" = 762.56, #"Path" = 919],
					        [#"StoreType" = "seo", #"Order" = 719, #"Ratio" = 605.21, #"Path" = 108],
					        [#"StoreType" = "answer", #"Order" = 434, #"Ratio" = 112.75, #"Path" = 377],
					        [#"StoreType" = "coat", #"Order" = 395, #"Ratio" = 539.86, #"Path" = 200],
					        [#"StoreType" = "payable", #"Order" = 523, #"Ratio" = 169.9, #"Path" = 430],
					        [#"StoreType" = "diabetes", #"Order" = 311, #"Ratio" = 426.18, #"Path" = 140],
					        [#"StoreType" = "demand", #"Order" = 309, #"Ratio" = 516.44, #"Path" = 806],
					        [#"StoreType" = "routine", #"Order" = 962, #"Ratio" = 991.4, #"Path" = 620],
					        [#"StoreType" = "description", #"Order" = 365, #"Ratio" = 547.7, #"Path" = 374],
					        [#"StoreType" = "fiscal", #"Order" = 805, #"Ratio" = 497.42, #"Path" = 535],
					        [#"StoreType" = "ring", #"Order" = 266, #"Ratio" = 331.43, #"Path" = 227],
					        [#"StoreType" = "italian", #"Order" = 282, #"Ratio" = 800.08, #"Path" = 749],
					        [#"StoreType" = "responsible", #"Order" = 39, #"Ratio" = 414.11, #"Path" = 837],
					        [#"StoreType" = "certification", #"Order" = 649, #"Ratio" = 714.63, #"Path" = 931],
					        [#"StoreType" = "filed", #"Order" = 5, #"Ratio" = 195.26, #"Path" = 224],
					        [#"StoreType" = "charge", #"Order" = 401, #"Ratio" = 895.84, #"Path" = 197],
					        [#"StoreType" = "difficult", #"Order" = 98, #"Ratio" = 21.8, #"Path" = 653],
					        [#"StoreType" = "observation", #"Order" = 6, #"Ratio" = 977.31, #"Path" = 217],
					        [#"StoreType" = "boats", #"Order" = 122, #"Ratio" = 305.76, #"Path" = 78],
					        [#"StoreType" = "than", #"Order" = 263, #"Ratio" = 189.83, #"Path" = 206],
					        [#"StoreType" = "right", #"Order" = 221, #"Ratio" = 950.66, #"Path" = 115],
					        [#"StoreType" = "traditional", #"Order" = 416, #"Ratio" = 778.04, #"Path" = 826],
					        [#"StoreType" = "rd", #"Order" = 902, #"Ratio" = 158.65, #"Path" = 779],
					        [#"StoreType" = "linear", #"Order" = 434, #"Ratio" = 736.6, #"Path" = 518],
					        [#"StoreType" = "ottawa", #"Order" = 518, #"Ratio" = 330.77, #"Path" = 359],
					        [#"StoreType" = "costa", #"Order" = 672, #"Ratio" = 728.94, #"Path" = 543],
					        [#"StoreType" = "offered", #"Order" = 531, #"Ratio" = 987.43, #"Path" = 750],
					        [#"StoreType" = "par", #"Order" = 431, #"Ratio" = 728.76, #"Path" = 749],
					        [#"StoreType" = "ion", #"Order" = 822, #"Ratio" = 492.94, #"Path" = 913],
					        [#"StoreType" = "available", #"Order" = 188, #"Ratio" = 501.42, #"Path" = 512],
					        [#"StoreType" = "washington", #"Order" = 583, #"Ratio" = 695.01, #"Path" = 481],
					        [#"StoreType" = "tune", #"Order" = 44, #"Ratio" = 404.18, #"Path" = 850],
					        [#"StoreType" = "liberty", #"Order" = 246, #"Ratio" = 574.6, #"Path" = 96],
					        [#"StoreType" = "byte", #"Order" = 655, #"Ratio" = 47.39, #"Path" = 835],
					        [#"StoreType" = "prize", #"Order" = 957, #"Ratio" = 901.07, #"Path" = 462],
					        [#"StoreType" = "collection", #"Order" = 343, #"Ratio" = 489.1, #"Path" = 898],
					        [#"StoreType" = "direction", #"Order" = 795, #"Ratio" = 933.43, #"Path" = 459],
					        [#"StoreType" = "annotation", #"Order" = 587, #"Ratio" = 408.3, #"Path" = 721],
					        [#"StoreType" = "layer", #"Order" = 807, #"Ratio" = 522.57, #"Path" = 635],
					        [#"StoreType" = "arkansas", #"Order" = 81, #"Ratio" = 951.76, #"Path" = 272],
					        [#"StoreType" = "clark", #"Order" = 950, #"Ratio" = 332.62, #"Path" = 880],
					        [#"StoreType" = "speaker", #"Order" = 693, #"Ratio" = 270.09, #"Path" = 293],
					        [#"StoreType" = "computer", #"Order" = 868, #"Ratio" = 335.74, #"Path" = 619],
					        [#"StoreType" = "gm", #"Order" = 524, #"Ratio" = 308.29, #"Path" = 604],
					        [#"StoreType" = "massachusetts", #"Order" = 535, #"Ratio" = 809.45, #"Path" = 879],
					        [#"StoreType" = "initiative", #"Order" = 549, #"Ratio" = 490.99, #"Path" = 418],
					        [#"StoreType" = "feeds", #"Order" = 909, #"Ratio" = 807.79, #"Path" = 937],
					        [#"StoreType" = "half", #"Order" = 242, #"Ratio" = 35.74, #"Path" = 537],
					        [#"StoreType" = "loved", #"Order" = 449, #"Ratio" = 610.22, #"Path" = 20],
					        [#"StoreType" = "publishing", #"Order" = 554, #"Ratio" = 556.32, #"Path" = 117],
					        [#"StoreType" = "identifying", #"Order" = 221, #"Ratio" = 274.3, #"Path" = 928],
					        [#"StoreType" = "partial", #"Order" = 3, #"Ratio" = 77.71, #"Path" = 358],
					        [#"StoreType" = "ads", #"Order" = 395, #"Ratio" = 861.45, #"Path" = 292],
					        [#"StoreType" = "eg", #"Order" = 473, #"Ratio" = 229.36, #"Path" = 817],
					        [#"StoreType" = "sized", #"Order" = 888, #"Ratio" = 63.77, #"Path" = 988],
					        [#"StoreType" = "cassette", #"Order" = 994, #"Ratio" = 243.5, #"Path" = 449],
					        [#"StoreType" = "delaware", #"Order" = 232, #"Ratio" = 190.09, #"Path" = 735],
					        [#"StoreType" = "messages", #"Order" = 708, #"Ratio" = 792.6, #"Path" = 257],
					        [#"StoreType" = "serious", #"Order" = 404, #"Ratio" = 39.5, #"Path" = 480],
					        [#"StoreType" = "strategy", #"Order" = 442, #"Ratio" = 320.64, #"Path" = 587],
					        [#"StoreType" = "like", #"Order" = 277, #"Ratio" = 610.89, #"Path" = 202],
					        [#"StoreType" = "conducted", #"Order" = 659, #"Ratio" = 516.75, #"Path" = 702],
					        [#"StoreType" = "investment", #"Order" = 334, #"Ratio" = 862.27, #"Path" = 42],
					        [#"StoreType" = "attend", #"Order" = 34, #"Ratio" = 322.8, #"Path" = 51],
					        [#"StoreType" = "fail", #"Order" = 212, #"Ratio" = 524.02, #"Path" = 479],
					        [#"StoreType" = "reading", #"Order" = 808, #"Ratio" = 622.32, #"Path" = 674],
					        [#"StoreType" = "charts", #"Order" = 163, #"Ratio" = 975.01, #"Path" = 70],
					        [#"StoreType" = "wisconsin", #"Order" = 983, #"Ratio" = 744.91, #"Path" = 797],
					        [#"StoreType" = "taylor", #"Order" = 681, #"Ratio" = 426.49, #"Path" = 975],
					        [#"StoreType" = "gates", #"Order" = 460, #"Ratio" = 363.76, #"Path" = 69],
					        [#"StoreType" = "closer", #"Order" = 871, #"Ratio" = 112.16, #"Path" = 193],
					        [#"StoreType" = "bargain", #"Order" = 61, #"Ratio" = 876.26, #"Path" = 256],
					        [#"StoreType" = "atom", #"Order" = 231, #"Ratio" = 189.77, #"Path" = 713],
					        [#"StoreType" = "soul", #"Order" = 250, #"Ratio" = 79.58, #"Path" = 38],
					        [#"StoreType" = "prison", #"Order" = 39, #"Ratio" = 594.54, #"Path" = 11],
					        [#"StoreType" = "instruction", #"Order" = 135, #"Ratio" = 15.03, #"Path" = 264],
					        [#"StoreType" = "feature", #"Order" = 862, #"Ratio" = 475.79, #"Path" = 474],
					        [#"StoreType" = "craft", #"Order" = 471, #"Ratio" = 638.85, #"Path" = 970],
					        [#"StoreType" = "consumers", #"Order" = 181, #"Ratio" = 895.8, #"Path" = 583],
					        [#"StoreType" = "students", #"Order" = 944, #"Ratio" = 841.09, #"Path" = 303],
					        [#"StoreType" = "sun", #"Order" = 774, #"Ratio" = 11.36, #"Path" = 586],
					        [#"StoreType" = "prevention", #"Order" = 252, #"Ratio" = 460.28, #"Path" = 97],
					        [#"StoreType" = "actually", #"Order" = 352, #"Ratio" = 354.86, #"Path" = 574],
					        [#"StoreType" = "consultant", #"Order" = 559, #"Ratio" = 788.03, #"Path" = 739],
					        [#"StoreType" = "large", #"Order" = 507, #"Ratio" = 540.02, #"Path" = 937],
					        [#"StoreType" = "facial", #"Order" = 177, #"Ratio" = 253.61, #"Path" = 955],
					        [#"StoreType" = "cut", #"Order" = 399, #"Ratio" = 702.05, #"Path" = 121],
					        [#"StoreType" = "powder", #"Order" = 529, #"Ratio" = 172.28, #"Path" = 707],
					        [#"StoreType" = "whether", #"Order" = 399, #"Ratio" = 119.72, #"Path" = 585],
					        [#"StoreType" = "representation", #"Order" = 379, #"Ratio" = 548.66, #"Path" = 509],
					        [#"StoreType" = "worse", #"Order" = 714, #"Ratio" = 820.7, #"Path" = 555],
					        [#"StoreType" = "likely", #"Order" = 25, #"Ratio" = 133.9, #"Path" = 535],
					        [#"StoreType" = "paper", #"Order" = 939, #"Ratio" = 5.36, #"Path" = 38],
					        [#"StoreType" = "contractor", #"Order" = 785, #"Ratio" = 151.42, #"Path" = 694],
					        [#"StoreType" = "task", #"Order" = 362, #"Ratio" = 268.08, #"Path" = 511],
					        [#"StoreType" = "convert", #"Order" = 511, #"Ratio" = 793.81, #"Path" = 861],
					        [#"StoreType" = "earned", #"Order" = 496, #"Ratio" = 121.76, #"Path" = 972],
					        [#"StoreType" = "serves", #"Order" = 570, #"Ratio" = 426.94, #"Path" = 484],
					        [#"StoreType" = "op", #"Order" = 814, #"Ratio" = 751.47, #"Path" = 587],
					        [#"StoreType" = "landscape", #"Order" = 595, #"Ratio" = 50.3, #"Path" = 611],
					        [#"StoreType" = "hampshire", #"Order" = 611, #"Ratio" = 603.65, #"Path" = 396],
					        [#"StoreType" = "set", #"Order" = 331, #"Ratio" = 337.1, #"Path" = 551],
					        [#"StoreType" = "continues", #"Order" = 243, #"Ratio" = 840.46, #"Path" = 68],
					        [#"StoreType" = "land", #"Order" = 934, #"Ratio" = 989.63, #"Path" = 171],
					        [#"StoreType" = "corn", #"Order" = 513, #"Ratio" = 216.49, #"Path" = 53],
					        [#"StoreType" = "man", #"Order" = 579, #"Ratio" = 306.03, #"Path" = 117],
					        [#"StoreType" = "recently", #"Order" = 323, #"Ratio" = 440.71, #"Path" = 722],
					        [#"StoreType" = "password", #"Order" = 626, #"Ratio" = 987.1, #"Path" = 21],
					        [#"StoreType" = "tales", #"Order" = 698, #"Ratio" = 613.3, #"Path" = 739],
					        [#"StoreType" = "personnel", #"Order" = 24, #"Ratio" = 491.26, #"Path" = 639],
					        [#"StoreType" = "regarding", #"Order" = 119, #"Ratio" = 181.53, #"Path" = 213],
					        [#"StoreType" = "santa", #"Order" = 906, #"Ratio" = 932.13, #"Path" = 766],
					        [#"StoreType" = "sons", #"Order" = 795, #"Ratio" = 252.56, #"Path" = 474],
					        [#"StoreType" = "meters", #"Order" = 392, #"Ratio" = 948.44, #"Path" = 42],
					        [#"StoreType" = "flu", #"Order" = 722, #"Ratio" = 146.1, #"Path" = 872],
					        [#"StoreType" = "selling", #"Order" = 960, #"Ratio" = 117.69, #"Path" = 238],
					        [#"StoreType" = "russell", #"Order" = 643, #"Ratio" = 609.24, #"Path" = 311],
					        [#"StoreType" = "military", #"Order" = 325, #"Ratio" = 690.82, #"Path" = 547],
					        [#"StoreType" = "door", #"Order" = 311, #"Ratio" = 184.19, #"Path" = 190],
					        [#"StoreType" = "goes", #"Order" = 719, #"Ratio" = 982.49, #"Path" = 547],
					        [#"StoreType" = "subscriptions", #"Order" = 148, #"Ratio" = 369.55, #"Path" = 13],
					        [#"StoreType" = "closer", #"Order" = 986, #"Ratio" = 186.92, #"Path" = 72],
					        [#"StoreType" = "coding", #"Order" = 974, #"Ratio" = 934.1, #"Path" = 254],
					        [#"StoreType" = "coupon", #"Order" = 657, #"Ratio" = 554.87, #"Path" = 99],
					        [#"StoreType" = "trial", #"Order" = 970, #"Ratio" = 693.52, #"Path" = 809],
					        [#"StoreType" = "standard", #"Order" = 489, #"Ratio" = 374.01, #"Path" = 53],
					        [#"StoreType" = "recruitment", #"Order" = 994, #"Ratio" = 50.69, #"Path" = 468],
					        [#"StoreType" = "outer", #"Order" = 15, #"Ratio" = 531.94, #"Path" = 837],
					        [#"StoreType" = "trailer", #"Order" = 2, #"Ratio" = 599.77, #"Path" = 863],
					        [#"StoreType" = "estimated", #"Order" = 987, #"Ratio" = 152.94, #"Path" = 555],
					        [#"StoreType" = "extent", #"Order" = 775, #"Ratio" = 835.91, #"Path" = 264],
					        [#"StoreType" = "arrival", #"Order" = 751, #"Ratio" = 646.75, #"Path" = 974],
					        [#"StoreType" = "secretary", #"Order" = 523, #"Ratio" = 292.2, #"Path" = 956],
					        [#"StoreType" = "elements", #"Order" = 936, #"Ratio" = 17.56, #"Path" = 88],
					        [#"StoreType" = "gas", #"Order" = 881, #"Ratio" = 457.31, #"Path" = 516],
					        [#"StoreType" = "mike", #"Order" = 185, #"Ratio" = 685.12, #"Path" = 999],
					        [#"StoreType" = "berkeley", #"Order" = 358, #"Ratio" = 188.41, #"Path" = 375],
					        [#"StoreType" = "indoor", #"Order" = 465, #"Ratio" = 713.72, #"Path" = 907],
					        [#"StoreType" = "password", #"Order" = 97, #"Ratio" = 173.59, #"Path" = 642],
					        [#"StoreType" = "waves", #"Order" = 692, #"Ratio" = 548.36, #"Path" = 858],
					        [#"StoreType" = "processors", #"Order" = 283, #"Ratio" = 272.84, #"Path" = 634],
					        [#"StoreType" = "di", #"Order" = 231, #"Ratio" = 111.63, #"Path" = 249],
					        [#"StoreType" = "anymore", #"Order" = 974, #"Ratio" = 888.63, #"Path" = 647],
					        [#"StoreType" = "implementation", #"Order" = 687, #"Ratio" = 664.44, #"Path" = 336],
					        [#"StoreType" = "political", #"Order" = 511, #"Ratio" = 830.3, #"Path" = 476],
					        [#"StoreType" = "jelsoft", #"Order" = 303, #"Ratio" = 972.35, #"Path" = 940],
					        [#"StoreType" = "cameras", #"Order" = 99, #"Ratio" = 231.54, #"Path" = 11],
					        [#"StoreType" = "toward", #"Order" = 601, #"Ratio" = 357.94, #"Path" = 353],
					        [#"StoreType" = "claims", #"Order" = 439, #"Ratio" = 177.25, #"Path" = 613],
					        [#"StoreType" = "me", #"Order" = 915, #"Ratio" = 35.05, #"Path" = 198],
					        [#"StoreType" = "schools", #"Order" = 328, #"Ratio" = 965.27, #"Path" = 800],
					        [#"StoreType" = "customs", #"Order" = 404, #"Ratio" = 622.05, #"Path" = 691],
					        [#"StoreType" = "carpet", #"Order" = 899, #"Ratio" = 512.72, #"Path" = 861],
					        [#"StoreType" = "requested", #"Order" = 972, #"Ratio" = 956.9, #"Path" = 30],
					        [#"StoreType" = "welcome", #"Order" = 530, #"Ratio" = 388.18, #"Path" = 484],
					        [#"StoreType" = "entire", #"Order" = 816, #"Ratio" = 506.33, #"Path" = 192],
					        [#"StoreType" = "adjustable", #"Order" = 126, #"Ratio" = 94.3, #"Path" = 501],
					        [#"StoreType" = "rfc", #"Order" = 672, #"Ratio" = 553.52, #"Path" = 992],
					        [#"StoreType" = "blogging", #"Order" = 967, #"Ratio" = 869.99, #"Path" = 163],
					        [#"StoreType" = "clinic", #"Order" = 108, #"Ratio" = 860.61, #"Path" = 527],
					        [#"StoreType" = "master", #"Order" = 147, #"Ratio" = 170.56, #"Path" = 328],
					        [#"StoreType" = "traditional", #"Order" = 402, #"Ratio" = 268.53, #"Path" = 44],
					        [#"StoreType" = "following", #"Order" = 996, #"Ratio" = 690.51, #"Path" = 182],
					        [#"StoreType" = "before", #"Order" = 21, #"Ratio" = 883.93, #"Path" = 738],
					        [#"StoreType" = "emails", #"Order" = 186, #"Ratio" = 732.81, #"Path" = 962],
					        [#"StoreType" = "favorite", #"Order" = 647, #"Ratio" = 788.57, #"Path" = 342],
					        [#"StoreType" = "okay", #"Order" = 381, #"Ratio" = 660.45, #"Path" = 315],
					        [#"StoreType" = "deal", #"Order" = 38, #"Ratio" = 41.19, #"Path" = 261],
					        [#"StoreType" = "my", #"Order" = 907, #"Ratio" = 207.41, #"Path" = 964],
					        [#"StoreType" = "pre", #"Order" = 670, #"Ratio" = 252.71, #"Path" = 532],
					        [#"StoreType" = "adapter", #"Order" = 342, #"Ratio" = 762.24, #"Path" = 607],
					        [#"StoreType" = "speaker", #"Order" = 572, #"Ratio" = 206.89, #"Path" = 383],
					        [#"StoreType" = "issues", #"Order" = 574, #"Ratio" = 524.6, #"Path" = 181],
					        [#"StoreType" = "pocket", #"Order" = 882, #"Ratio" = 115.06, #"Path" = 857],
					        [#"StoreType" = "css", #"Order" = 51, #"Ratio" = 536.85, #"Path" = 651],
					        [#"StoreType" = "stop", #"Order" = 953, #"Ratio" = 482.93, #"Path" = 312],
					        [#"StoreType" = "baby", #"Order" = 42, #"Ratio" = 688.25, #"Path" = 614],
					        [#"StoreType" = "nodes", #"Order" = 466, #"Ratio" = 849.93, #"Path" = 232],
					        [#"StoreType" = "couples", #"Order" = 190, #"Ratio" = 961.53, #"Path" = 301],
					        [#"StoreType" = "sing", #"Order" = 635, #"Ratio" = 583.54, #"Path" = 421],
					        [#"StoreType" = "ok", #"Order" = 309, #"Ratio" = 490.07, #"Path" = 271],
					        [#"StoreType" = "passion", #"Order" = 455, #"Ratio" = 100.66, #"Path" = 79],
					        [#"StoreType" = "achievement", #"Order" = 48, #"Ratio" = 641.19, #"Path" = 274],
					        [#"StoreType" = "measuring", #"Order" = 483, #"Ratio" = 827.2, #"Path" = 317],
					        [#"StoreType" = "albert", #"Order" = 477, #"Ratio" = 650.29, #"Path" = 68],
					        [#"StoreType" = "kansas", #"Order" = 798, #"Ratio" = 978.2, #"Path" = 160],
					        [#"StoreType" = "bold", #"Order" = 403, #"Ratio" = 94.31, #"Path" = 160],
					        [#"StoreType" = "domains", #"Order" = 722, #"Ratio" = 265.86, #"Path" = 434],
					        [#"StoreType" = "piece", #"Order" = 657, #"Ratio" = 493.32, #"Path" = 984],
					        [#"StoreType" = "flow", #"Order" = 864, #"Ratio" = 127.91, #"Path" = 327],
					        [#"StoreType" = "contain", #"Order" = 587, #"Ratio" = 997.89, #"Path" = 248],
					        [#"StoreType" = "manufacturing", #"Order" = 333, #"Ratio" = 619.38, #"Path" = 71],
					        [#"StoreType" = "within", #"Order" = 782, #"Ratio" = 308.42, #"Path" = 53],
					        [#"StoreType" = "clearly", #"Order" = 973, #"Ratio" = 376.81, #"Path" = 975],
					        [#"StoreType" = "canyon", #"Order" = 236, #"Ratio" = 276.23, #"Path" = 389],
					        [#"StoreType" = "weak", #"Order" = 691, #"Ratio" = 969.43, #"Path" = 990],
					        [#"StoreType" = "football", #"Order" = 607, #"Ratio" = 970.07, #"Path" = 879],
					        [#"StoreType" = "automation", #"Order" = 650, #"Ratio" = 788.94, #"Path" = 99],
					        [#"StoreType" = "us", #"Order" = 494, #"Ratio" = 247.65, #"Path" = 536],
					        [#"StoreType" = "player", #"Order" = 276, #"Ratio" = 966.22, #"Path" = 542],
					        [#"StoreType" = "friends", #"Order" = 172, #"Ratio" = 743.37, #"Path" = 288],
					        [#"StoreType" = "substances", #"Order" = 707, #"Ratio" = 104.71, #"Path" = 50],
					        [#"StoreType" = "console", #"Order" = 61, #"Ratio" = 457.07, #"Path" = 726],
					        [#"StoreType" = "avoid", #"Order" = 617, #"Ratio" = 462.8, #"Path" = 413],
					        [#"StoreType" = "mobile", #"Order" = 213, #"Ratio" = 823.74, #"Path" = 485],
					        [#"StoreType" = "cambridge", #"Order" = 917, #"Ratio" = 844.22, #"Path" = 966],
					        [#"StoreType" = "match", #"Order" = 852, #"Ratio" = 254.84, #"Path" = 91],
					        [#"StoreType" = "affiliate", #"Order" = 518, #"Ratio" = 855.17, #"Path" = 701],
					        [#"StoreType" = "effort", #"Order" = 460, #"Ratio" = 394.75, #"Path" = 696],
					        [#"StoreType" = "usual", #"Order" = 215, #"Ratio" = 191.38, #"Path" = 804],
					        [#"StoreType" = "lawyers", #"Order" = 320, #"Ratio" = 261.74, #"Path" = 837],
					        [#"StoreType" = "environmental", #"Order" = 582, #"Ratio" = 860.47, #"Path" = 423],
					        [#"StoreType" = "rolling", #"Order" = 415, #"Ratio" = 875.28, #"Path" = 656],
					        [#"StoreType" = "http", #"Order" = 19, #"Ratio" = 835.8, #"Path" = 408],
					        [#"StoreType" = "accounts", #"Order" = 845, #"Ratio" = 376.62, #"Path" = 883],
					        [#"StoreType" = "latest", #"Order" = 671, #"Ratio" = 1.37, #"Path" = 972],
					        [#"StoreType" = "media", #"Order" = 452, #"Ratio" = 861.77, #"Path" = 359],
					        [#"StoreType" = "operators", #"Order" = 290, #"Ratio" = 59.06, #"Path" = 397],
					        [#"StoreType" = "conferences", #"Order" = 763, #"Ratio" = 363.3, #"Path" = 991],
					        [#"StoreType" = "laid", #"Order" = 978, #"Ratio" = 53.63, #"Path" = 1],
					        [#"StoreType" = "shipping", #"Order" = 876, #"Ratio" = 491.47, #"Path" = 982],
					        [#"StoreType" = "bridge", #"Order" = 223, #"Ratio" = 947.5, #"Path" = 766],
					        [#"StoreType" = "roulette", #"Order" = 881, #"Ratio" = 523.63, #"Path" = 105],
					        [#"StoreType" = "mills", #"Order" = 86, #"Ratio" = 923.85, #"Path" = 543]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"StoreType", type text},
					        {"Order", Int64.Type},
					        {"Ratio", type number},
					        {"Path", Int64.Type}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table