table 'HR Dataset'
	lineageTag: b6e79884-cc52-4364-8263-150a40969d91

	measure 'dep calc 3' = SUM('HR Dataset'[dep calc 2])
		formatString: 0
		lineageTag: 1586ad25-ef7f-4294-9984-237ab603c83b

	column Employee_Name
		dataType: string
		lineageTag: 56468102-1e3a-4897-905d-8d10ae2e4dfb
		summarizeBy: none
		sourceColumn: Employee_Name

		annotation SummarizationSetBy = Automatic

	column EmpID
		dataType: int64
		formatString: 0
		lineageTag: 8788c0b2-4b5b-4df6-bb98-c1cbd6ab7121
		summarizeBy: sum
		sourceColumn: EmpID

		annotation SummarizationSetBy = Automatic

	column MarriedID
		dataType: int64
		formatString: 0
		lineageTag: 2a7e4951-828a-49c6-8f25-d512a2ac54ba
		summarizeBy: sum
		sourceColumn: MarriedID

		annotation SummarizationSetBy = Automatic

	column MaritalStatusID
		dataType: int64
		formatString: 0
		lineageTag: 2f137d79-dccd-427a-91b9-dbd958eabad9
		summarizeBy: sum
		sourceColumn: MaritalStatusID

		annotation SummarizationSetBy = Automatic

	column GenderID
		dataType: int64
		formatString: 0
		lineageTag: 10d2d492-52b8-404b-a57c-7a46bd32a104
		summarizeBy: sum
		sourceColumn: GenderID

		annotation SummarizationSetBy = Automatic

	column EmpStatusID
		dataType: int64
		formatString: 0
		lineageTag: 4de1a791-3c75-46f0-9acc-a500a5be045d
		summarizeBy: sum
		sourceColumn: EmpStatusID

		annotation SummarizationSetBy = Automatic

	column DeptID
		dataType: int64
		formatString: 0
		lineageTag: 0cfdfc1f-ae9c-4a39-b9ce-501406509d77
		summarizeBy: sum
		sourceColumn: DeptID

		annotation SummarizationSetBy = Automatic

	column PerfScoreID
		dataType: int64
		formatString: 0
		lineageTag: 135bd96d-19db-4fd3-923e-5c5526a65768
		summarizeBy: sum
		sourceColumn: PerfScoreID

		annotation SummarizationSetBy = Automatic

	column FromDiversityJobFairID
		dataType: int64
		formatString: 0
		lineageTag: ac3ccb6e-8e63-4804-9054-fb21c2bf8c9e
		summarizeBy: sum
		sourceColumn: FromDiversityJobFairID

		annotation SummarizationSetBy = Automatic

	column Salary
		dataType: int64
		formatString: 0
		lineageTag: bca085ba-79c7-4fb1-88bd-acad0311e36a
		summarizeBy: sum
		sourceColumn: Salary

		annotation SummarizationSetBy = Automatic

	column Termd
		dataType: int64
		formatString: 0
		lineageTag: e885ccf9-4203-4d18-8177-e7c3403d8bf2
		summarizeBy: sum
		sourceColumn: Termd

		annotation SummarizationSetBy = Automatic

	column PositionID
		dataType: int64
		formatString: 0
		lineageTag: 0f5b80a0-103f-4047-923e-df416ce8c55f
		summarizeBy: sum
		sourceColumn: PositionID

		annotation SummarizationSetBy = Automatic

	column Position
		dataType: string
		lineageTag: 4f010c56-4b92-406f-82ea-401f6b6626f3
		summarizeBy: none
		sourceColumn: Position

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: cda7e251-88c6-4e0b-b50a-8a29c59e79de
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Zip
		dataType: int64
		formatString: 0
		lineageTag: de3055bf-7a46-4bcc-9377-84223e2be54b
		summarizeBy: sum
		sourceColumn: Zip

		annotation SummarizationSetBy = Automatic

	column DOB
		dataType: datetime
		lineageTag: 6153f0a2-2a06-4f2f-9be2-ad1c995a2cf8
		summarizeBy: none
		sourceColumn: DOB

		annotation SummarizationSetBy = Automatic

	column Sex
		dataType: string
		lineageTag: e753e054-ae1d-4f22-a6e5-3b6014c0670c
		summarizeBy: none
		sourceColumn: Sex

		annotation SummarizationSetBy = Automatic

	column MaritalDesc
		dataType: string
		lineageTag: aa40cc05-b385-4368-8fa5-baaeb42ba940
		summarizeBy: none
		sourceColumn: MaritalDesc

		annotation SummarizationSetBy = Automatic

	column CitizenDesc
		dataType: string
		lineageTag: 13f4614d-f8ce-4be0-932f-756a9411cdfa
		summarizeBy: none
		sourceColumn: CitizenDesc

		annotation SummarizationSetBy = Automatic

	column HispanicLatino
		dataType: string
		lineageTag: 3bd76042-00b1-42bc-9803-a1be5482f10f
		summarizeBy: none
		sourceColumn: HispanicLatino

		annotation SummarizationSetBy = Automatic

	column RaceDesc
		dataType: string
		lineageTag: 5d434578-c19e-4ae4-86bb-ff7222ed812f
		summarizeBy: none
		sourceColumn: RaceDesc

		annotation SummarizationSetBy = Automatic

	column DateofHire
		dataType: datetime
		lineageTag: 5bba0500-17d1-44aa-8419-3c3b9274646e
		summarizeBy: none
		sourceColumn: DateofHire

		annotation SummarizationSetBy = Automatic

	column DateofTermination
		dataType: datetime
		lineageTag: 823424c8-9181-4c96-b7fd-84e2f0f0d484
		summarizeBy: none
		sourceColumn: DateofTermination

		annotation SummarizationSetBy = Automatic

	column TermReason
		dataType: string
		lineageTag: 62c04258-d3d2-4944-b0c2-e708d8a2f85a
		summarizeBy: none
		sourceColumn: TermReason

		annotation SummarizationSetBy = Automatic

	column EmploymentStatus
		dataType: string
		lineageTag: 8a7323c4-ec1d-4fed-89d8-0e2b052b8c1b
		summarizeBy: none
		sourceColumn: EmploymentStatus

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: 376a2646-3672-4065-8608-25ac4310e580
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column ManagerName
		dataType: string
		lineageTag: fc3a8ba4-55e1-41ac-84c8-4d1570aef415
		summarizeBy: none
		sourceColumn: ManagerName

		annotation SummarizationSetBy = Automatic

	column ManagerID
		dataType: int64
		formatString: 0
		lineageTag: 61960c93-7063-46fb-909a-b10b9356d577
		summarizeBy: sum
		sourceColumn: ManagerID

		annotation SummarizationSetBy = Automatic

	column RecruitmentSource
		dataType: string
		lineageTag: e4dfb631-9752-49b8-9141-984b835d4e9a
		summarizeBy: none
		sourceColumn: RecruitmentSource

		annotation SummarizationSetBy = Automatic

	column PerformanceScore
		dataType: string
		lineageTag: d4fd12d8-1ccb-4977-a9b9-4c78bf41e6d6
		summarizeBy: none
		sourceColumn: PerformanceScore

		annotation SummarizationSetBy = Automatic

	column EngagementSurvey
		dataType: double
		formatString: General Number
		lineageTag: 5e939bf4-ace6-4c7d-a70c-1a2481e7b6a9
		summarizeBy: sum
		sourceColumn: EngagementSurvey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EmpSatisfaction
		dataType: int64
		formatString: 0
		lineageTag: a16f2d78-e4df-458c-b0ab-aa902fe6b2eb
		summarizeBy: sum
		sourceColumn: EmpSatisfaction

		annotation SummarizationSetBy = Automatic

	column SpecialProjectsCount
		dataType: int64
		formatString: 0
		lineageTag: d95695e3-ff75-4029-94ac-976f8473d0d4
		summarizeBy: sum
		sourceColumn: SpecialProjectsCount

		annotation SummarizationSetBy = Automatic

	column LastPerformanceReview_Date
		dataType: datetime
		lineageTag: 8f595ac9-e5e9-4176-acbf-2949136314c7
		summarizeBy: none
		sourceColumn: LastPerformanceReview_Date

		annotation SummarizationSetBy = Automatic

	column DaysLateLast30
		dataType: int64
		formatString: 0
		lineageTag: d1d6d57c-67c2-4698-919b-b60773ef07f9
		summarizeBy: sum
		sourceColumn: DaysLateLast30

		annotation SummarizationSetBy = Automatic

	column Absences
		dataType: int64
		formatString: 0
		lineageTag: fc2229fc-95c0-4e98-b9b0-d3941784241d
		summarizeBy: sum
		sourceColumn: Absences

		annotation SummarizationSetBy = Automatic

	column Calculation3 = 'HR Dataset'[TermReason] & FORMAT('HR Dataset'[Termd], "0")
		lineageTag: bf2ab72d-99e4-4256-bc64-264d621d4623
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column calculation3 = "abc"
		lineageTag: 88195ae8-8184-4139-9f3d-49026e2a3bc3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column C_Employee_Status = 'HR Dataset'[EmploymentStatus]
		lineageTag: f7114b52-12b7-4a90-9ba3-236668a6e057
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Calculation1 = 'HR Dataset'[DeptID] + 'HR Dataset'[GenderID]
		formatString: 0
		lineageTag: b69fa3b1-facb-41d0-a0c2-9d5e336cddc5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Calculation2 = 'HR Dataset'[Termd] * 'HR Dataset'[Salary] * 'HR Dataset'[EngagementSurvey]
		lineageTag: 59c53503-63ea-4f45-aa97-54be57f8af38
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'dep calc 1' = 'HR Dataset'[DeptID]
		formatString: 0
		lineageTag: 98d38d45-d9ae-4284-82fe-99ad2fb6b7e0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'dep calc 2' = 'HR Dataset'[dep calc 1] * 'HR Dataset'[MarriedID]
		formatString: 0
		lineageTag: b9ff796e-169b-4d30-9834-a4da73f205e8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'HR Dataset' = m
		mode: import
		source =
				let
					    Source = Csv.Document(
					        File.Contents("https://saastestlatest.blob.core.windows.net/saas-test-reports/HR%20Dataset.csv?se=2025-11-05T10%3A09%3A44Z&sp=r&sv=2025-11-05&sr=b&sig=rFe4gp6Hc8TiYGd3UgSNhWFcq8I%2Bvv8VCF/C8ljXnao%3D"),
					        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
					    ),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Employee_Name", type text}, {"EmpID", Int64.Type}, {"MarriedID", Int64.Type}, {"MaritalStatusID", Int64.Type}, {"GenderID", Int64.Type}, {"EmpStatusID", Int64.Type}, {"DeptID", Int64.Type}, {"PerfScoreID", Int64.Type}, {"FromDiversityJobFairID", Int64.Type}, {"Salary", Int64.Type}, {"Termd", Int64.Type}, {"PositionID", Int64.Type}, {"Position", type text}, {"State", type text}, {"Zip", Int64.Type}, {"DOB", type date}, {"Sex", type text}, {"MaritalDesc", type text}, {"CitizenDesc", type text}, {"HispanicLatino", type text}, {"RaceDesc", type text}, {"DateofHire", type date}, {"DateofTermination", type date}, {"TermReason", type text}, {"EmploymentStatus", type text}, {"Department", type text}, {"ManagerName", type text}, {"ManagerID", Int64.Type}, {"RecruitmentSource", type text}, {"PerformanceScore", type text}, {"EngagementSurvey", type number}, {"EmpSatisfaction", Int64.Type}, {"SpecialProjectsCount", Int64.Type}, {"LastPerformanceReview_Date", type date}, {"DaysLateLast30", Int64.Type}, {"Absences", Int64.Type}})
					in
					    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table