table 'Top Customers'
	lineageTag: 3b3f1cda-bf8b-4c70-aa85-008d30bb56be

	measure 'Top Customers Value' = SELECTEDVALUE('Top Customers'[Top Customers], 5)
		lineageTag: f103c762-8598-424c-9e59-1488af739a23

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Top Customers'
		dataType: double
		formatString: 0
		lineageTag: 518dd6af-a241-4e7c-bdc4-0bd256c4a72b
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Top Customers' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_Id = 93489b2a6ffc49cf91f3e407ca11c658

