table 'HR Dataset'
	lineageTag: 5ceae539-085b-4e65-bd0e-b90c90d06e2d

	measure errored_Measure = SUM('HR Dataset'[Absence])
		lineageTag: c78008f9-6ddb-47cd-b7b2-84a3e0e0e364

	column Employee_Name
		dataType: string
		lineageTag: efeba2f7-8634-4663-93fb-e1f035e74adf
		summarizeBy: none
		sourceColumn: Employee_Name

		annotation SummarizationSetBy = Automatic

	column EmpID
		dataType: int64
		formatString: 0
		lineageTag: 616a5277-2a65-46d9-ab1e-d86c5a31447d
		summarizeBy: count
		sourceColumn: EmpID

		annotation SummarizationSetBy = Automatic

	column MarriedID
		dataType: int64
		formatString: 0
		lineageTag: 9f09ac93-e504-49bf-a31a-9527bbe3b4b1
		summarizeBy: count
		sourceColumn: MarriedID

		annotation SummarizationSetBy = Automatic

	column MaritalStatusID
		dataType: int64
		formatString: 0
		lineageTag: 094ef996-7de5-4995-9d54-034573bcf31e
		summarizeBy: count
		sourceColumn: MaritalStatusID

		annotation SummarizationSetBy = Automatic

	column GenderID
		dataType: int64
		formatString: 0
		lineageTag: b147e5e6-81fb-4707-ac90-42650b4ce03f
		summarizeBy: count
		sourceColumn: GenderID

		annotation SummarizationSetBy = Automatic

	column EmpStatusID
		dataType: int64
		formatString: 0
		lineageTag: 90938291-ab09-4c0b-8927-2d442044cc7c
		summarizeBy: count
		sourceColumn: EmpStatusID

		annotation SummarizationSetBy = Automatic

	column DeptID
		dataType: int64
		formatString: 0
		lineageTag: e83f50e0-a341-4f71-8b64-4038b3373364
		summarizeBy: count
		sourceColumn: DeptID

		annotation SummarizationSetBy = Automatic

	column PerfScoreID
		dataType: int64
		formatString: 0
		lineageTag: 32feb6b4-0844-41de-8cbc-76524981c67d
		summarizeBy: count
		sourceColumn: PerfScoreID

		annotation SummarizationSetBy = Automatic

	column FromDiversityJobFairID
		dataType: int64
		formatString: 0
		lineageTag: bc3d1c64-31b4-4f9d-8c75-f683f4539739
		summarizeBy: count
		sourceColumn: FromDiversityJobFairID

		annotation SummarizationSetBy = Automatic

	column Salary
		dataType: int64
		formatString: 0
		lineageTag: ed45bd52-b8bf-4a8e-8c2d-a7b3df1d9e84
		summarizeBy: sum
		sourceColumn: Salary

		annotation SummarizationSetBy = Automatic

	column Termd
		dataType: int64
		formatString: 0
		lineageTag: ecd1a205-2563-4e1c-b65d-1e8ffc4ae4c4
		summarizeBy: sum
		sourceColumn: Termd

		annotation SummarizationSetBy = Automatic

	column PositionID
		dataType: int64
		formatString: 0
		lineageTag: 572c29c8-73c5-44af-b5ab-c789e7dd7599
		summarizeBy: count
		sourceColumn: PositionID

		annotation SummarizationSetBy = Automatic

	column Position
		dataType: string
		lineageTag: 4927b2c5-481f-4030-8437-42c0effaa540
		summarizeBy: none
		sourceColumn: Position

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: dc069d45-f008-4252-8dd8-a97ea05a79b4
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Zip
		dataType: int64
		formatString: 0
		lineageTag: 6d95db77-fabe-46ff-9c09-2a23eca61d7e
		summarizeBy: sum
		sourceColumn: Zip

		annotation SummarizationSetBy = Automatic

	column DOB
		dataType: dateTime
		formatString: Long Date
		lineageTag: 678db96d-48c9-4178-8b3a-37a7b6e1a6ac
		summarizeBy: none
		sourceColumn: DOB

		variation Variation
			isDefault
			relationship: d3f60c1a-c8bd-4f97-a269-80afbae1b522
			defaultHierarchy: LocalDateTable_d77c5ce2-4f7c-4fd5-ba0a-bf966f7d15ac.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Sex
		dataType: string
		lineageTag: d9b52510-c017-4dea-9dc5-bc8eb2473d40
		summarizeBy: none
		sourceColumn: Sex

		annotation SummarizationSetBy = Automatic

	column MaritalDesc
		dataType: string
		lineageTag: 9d21e5f8-ac63-4ca7-a8d1-b689db54077b
		summarizeBy: none
		sourceColumn: MaritalDesc

		annotation SummarizationSetBy = Automatic

	column CitizenDesc
		dataType: string
		lineageTag: 695b7b04-b3f0-43e0-bfce-f465c6175c90
		summarizeBy: none
		sourceColumn: CitizenDesc

		annotation SummarizationSetBy = Automatic

	column HispanicLatino
		dataType: string
		lineageTag: 7184a5e9-18a9-438e-817c-d14990f7cf68
		summarizeBy: none
		sourceColumn: HispanicLatino

		annotation SummarizationSetBy = Automatic

	column RaceDesc
		dataType: string
		lineageTag: af7a4c56-7d47-489b-873b-6853fe73fc5f
		summarizeBy: none
		sourceColumn: RaceDesc

		annotation SummarizationSetBy = Automatic

	column DateofHire
		dataType: dateTime
		formatString: Long Date
		lineageTag: 332b1939-8433-48ba-9926-74f3ffb11fb7
		summarizeBy: none
		sourceColumn: DateofHire

		variation Variation
			isDefault
			relationship: 5cec2d54-e24b-4b5b-8969-68e566945ee9
			defaultHierarchy: LocalDateTable_52add9af-6567-417f-b6f2-dd9688ebc6bd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DateofTermination
		dataType: dateTime
		formatString: Long Date
		lineageTag: 601a0833-aa53-4551-b5b2-c0f42f8ff9b0
		summarizeBy: none
		sourceColumn: DateofTermination

		variation Variation
			isDefault
			relationship: 9822ec17-b1ac-4e66-999e-50f5b34150f2
			defaultHierarchy: LocalDateTable_3717395e-2d71-4e23-acf5-ae6896359bec.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TermReason
		dataType: string
		lineageTag: d3ca5b71-ca21-47b8-ae56-511d66c1dada
		summarizeBy: none
		sourceColumn: TermReason

		annotation SummarizationSetBy = Automatic

	column EmploymentStatus
		dataType: string
		lineageTag: 38e01e75-808d-441d-b5d8-db0084130788
		summarizeBy: none
		sourceColumn: EmploymentStatus

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: 8f69428b-e4c0-42ae-8d06-80a7abbdcd45
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column ManagerName
		dataType: string
		lineageTag: 28256c08-0dcd-4478-ae4f-4eca1d4097ee
		summarizeBy: none
		sourceColumn: ManagerName

		annotation SummarizationSetBy = Automatic

	column ManagerID
		dataType: int64
		formatString: 0
		lineageTag: 24ab8476-74ef-44a8-be39-f529528ddb2b
		summarizeBy: count
		sourceColumn: ManagerID

		annotation SummarizationSetBy = Automatic

	column RecruitmentSource
		dataType: string
		lineageTag: d8511ef6-6962-4f4c-bc90-89cd96f3d352
		summarizeBy: none
		sourceColumn: RecruitmentSource

		annotation SummarizationSetBy = Automatic

	column PerformanceScore
		dataType: string
		lineageTag: eee30108-3b80-4e56-aa28-f35964032351
		summarizeBy: none
		sourceColumn: PerformanceScore

		annotation SummarizationSetBy = Automatic

	column EngagementSurvey
		dataType: double
		formatString: General Number
		lineageTag: 909f379a-04c7-46b2-9d33-67cbfd81cdff
		summarizeBy: sum
		sourceColumn: EngagementSurvey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EmpSatisfaction
		dataType: int64
		formatString: 0
		lineageTag: d51fe274-c587-4ba9-ade4-01c0091f7a38
		summarizeBy: sum
		sourceColumn: EmpSatisfaction

		annotation SummarizationSetBy = Automatic

	column SpecialProjectsCount
		dataType: int64
		formatString: 0
		lineageTag: 0771d373-e3bb-4b19-ba6c-d295bf7c2773
		summarizeBy: sum
		sourceColumn: SpecialProjectsCount

		annotation SummarizationSetBy = Automatic

	column LastPerformanceReview_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0ee56c9b-5665-4d69-aff7-8c941e3b0df2
		summarizeBy: none
		sourceColumn: LastPerformanceReview_Date

		variation Variation
			isDefault
			relationship: 760b846a-6852-4dde-aaf3-56a1847432ca
			defaultHierarchy: LocalDateTable_7c4164f6-69df-4ce0-a149-8e7e8db6b76f.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column DaysLateLast30
		dataType: int64
		formatString: 0
		lineageTag: 16152514-a9f6-4e57-92cc-8578acf7ebf9
		summarizeBy: sum
		sourceColumn: DaysLateLast30

		annotation SummarizationSetBy = Automatic

	column Absences
		dataType: int64
		formatString: 0
		lineageTag: 4fa2683e-1280-4ac2-8ad7-efb85f7e3954
		summarizeBy: sum
		sourceColumn: Absences

		annotation SummarizationSetBy = Automatic

	partition 'HR Dataset' = m
		mode: import
		source =
				let
					Source = Csv.Document(Web.Contents("https://repoz-my.sharepoint.com/personal/karthikrajan_repoz_ai/Documents/SaaS%20testing%20files/Domain%20Datasets%20-%20Remote%20inters/Human%20resource/HR%20Workbook%20(2)/HR%20Dataset.csv"),[Delimiter=",", Columns=36, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Employee_Name", type text}, {"EmpID", Int64.Type}, {"MarriedID", Int64.Type}, {"MaritalStatusID", Int64.Type}, {"GenderID", Int64.Type}, {"EmpStatusID", Int64.Type}, {"DeptID", Int64.Type}, {"PerfScoreID", Int64.Type}, {"FromDiversityJobFairID", Int64.Type}, {"Salary", Int64.Type}, {"Termd", Int64.Type}, {"PositionID", Int64.Type}, {"Position", type text}, {"State", type text}, {"Zip", Int64.Type}, {"DOB", type date}, {"Sex", type text}, {"MaritalDesc", type text}, {"CitizenDesc", type text}, {"HispanicLatino", type text}, {"RaceDesc", type text}, {"DateofHire", type date}, {"DateofTermination", type date}, {"TermReason", type text}, {"EmploymentStatus", type text}, {"Department", type text}, {"ManagerName", type text}, {"ManagerID", Int64.Type}, {"RecruitmentSource", type text}, {"PerformanceScore", type text}, {"EngagementSurvey", type number}, {"EmpSatisfaction", Int64.Type}, {"SpecialProjectsCount", Int64.Type}, {"LastPerformanceReview_Date", type date}, {"DaysLateLast30", Int64.Type}, {"Absences", Int64.Type}})
					in
					#"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

