table 'Minimum Rating'
	lineageTag: 3fa0b40d-94d7-4889-8718-251ffe73a306

	measure 'Minimum Rating Value' = SELECTEDVALUE('Minimum Rating'[Minimum Rating], 1)
		lineageTag: 919563ee-f458-40ad-aad2-9e4b26eec049

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Minimum Rating'
		dataType: double
		formatString: 0
		lineageTag: 4977dc77-42a9-438c-944c-2f0cf07d8f53
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Minimum Rating' = calculated
		mode: import
		source = GENERATESERIES(1, 5)

	annotation PBI_Id = d1265f2211bc48d386ffbcd654ad64de

