table 'Sheet1+ (Multiple Connections)'
	lineageTag: 9e023dbb-fc70-4a8f-9b5c-e8533e001610

	column 'Customer ID'
		dataType: string
		lineageTag: 58571ea5-94d5-4fbf-8d40-7bc2de83275e
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 7bc81bda-4fdc-49c3-b52b-450366822d56
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: b76345dd-9c45-432d-aa08-cc8bc08539c3
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: bbcd9084-4d0b-4451-b4e0-57e2277e560b
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column 'Signup Date'
		dataType: string
		lineageTag: a399928a-1efb-41ca-bc29-f45816c425d9
		summarizeBy: none
		sourceColumn: 'Signup Date'

		annotation SummarizationSetBy = Automatic

	column 'Feedback ID'
		dataType: int64
		formatString: 0
		lineageTag: dd7fc68e-8b41-403d-9b79-8ca692ac0022
		summarizeBy: sum
		sourceColumn: 'Feedback ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID 1'
		dataType: string
		lineageTag: 128d2510-e7a1-410c-a673-98d4c1408f11
		summarizeBy: none
		sourceColumn: 'Customer ID 1'

		annotation SummarizationSetBy = Automatic

	column 'Feedback Date'
		dataType: datetime
		lineageTag: b46033a7-ad1b-4a2c-8dff-cdfab6cfee48
		summarizeBy: none
		sourceColumn: 'Feedback Date'

		annotation SummarizationSetBy = Automatic

	column Channel
		dataType: string
		lineageTag: 3164c2e6-4454-4fc0-bdf2-52d8ceb8c6cc
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	column 'Feedback Text'
		dataType: string
		lineageTag: c1407a64-0809-4cf4-89d3-689364b2604d
		summarizeBy: none
		sourceColumn: 'Feedback Text'

		annotation SummarizationSetBy = Automatic

	column Sentiment
		dataType: string
		lineageTag: 47599184-afea-484e-b155-142d06707b91
		summarizeBy: none
		sourceColumn: Sentiment

		annotation SummarizationSetBy = Automatic

	column Rating
		dataType: int64
		formatString: 0
		lineageTag: 33775fc8-0122-47b7-9e59-8ee53be33330
		summarizeBy: sum
		sourceColumn: Rating

		annotation SummarizationSetBy = Automatic

	partition 'Sheet1+ (Multiple Connections)' = m
		mode: import
		source =
				let 
					#"Source0" = Table.NestedJoin(#"Sheet1_Sheet1+ (Multiple Connections)", {"Customer ID"}, #"Customer Feedback Sentiment.csv_Sheet1+ (Multiple Connections)", {"Customer ID"}, "Customer Feedback Sentiment.csv_Sheet1+ (Multiple Connections)", JoinKind.Inner),
					#"Expand0" = Table.ExpandTableColumn(#"Source0", "Customer Feedback Sentiment.csv_Sheet1+ (Multiple Connections)", {"Feedback ID", "Customer ID", "Feedback Date", "Channel", "Feedback Text", "Sentiment", "Rating"}, {"Feedback ID", "Customer ID 1", "Feedback Date", "Channel", "Feedback Text", "Sentiment", "Rating"})
					in #"Expand0"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table