table 'Orders+ (Sample - Superstore)_People'
	lineageTag: 751950fe-4c17-4c97-af7a-8929854fe8cc

	column 'Regional Manager'
		dataType: string
		lineageTag: 64e2b907-aa2f-460b-898c-a673608e52c1
		summarizeBy: none
		sourceColumn: 'Regional Manager'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 7a3a3b6d-0ea5-479f-a0ea-76517af6a7f1
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition 'Orders+ (Sample - Superstore)_People' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Regional Manager" = "Vermont", #"Region" = "Rhode Island"],
					        [#"Regional Manager" = "Oregon", #"Region" = "South Dakota"],
					        [#"Regional Manager" = "Oklahoma", #"Region" = "Hawaii"],
					        [#"Regional Manager" = "Pennsylvania", #"Region" = "North Carolina"],
					        [#"Regional Manager" = "Montana", #"Region" = "Utah"],
					        [#"Regional Manager" = "Connecticut", #"Region" = "Minnesota"],
					        [#"Regional Manager" = "Delaware", #"Region" = "Arizona"],
					        [#"Regional Manager" = "Maine", #"Region" = "Indiana"],
					        [#"Regional Manager" = "Delaware", #"Region" = "Utah"],
					        [#"Regional Manager" = "Maryland", #"Region" = "Connecticut"],
					        [#"Regional Manager" = "North Dakota", #"Region" = "Massachusetts"],
					        [#"Regional Manager" = "Tennessee", #"Region" = "Colorado"],
					        [#"Regional Manager" = "Kansas", #"Region" = "New York"],
					        [#"Regional Manager" = "Montana", #"Region" = "Wisconsin"],
					        [#"Regional Manager" = "Utah", #"Region" = "New Mexico"],
					        [#"Regional Manager" = "Ohio", #"Region" = "Minnesota"],
					        [#"Regional Manager" = "Connecticut", #"Region" = "Idaho"],
					        [#"Regional Manager" = "Missouri", #"Region" = "North Dakota"],
					        [#"Regional Manager" = "Hawaii", #"Region" = "New Mexico"],
					        [#"Regional Manager" = "Texas", #"Region" = "Colorado"],
					        [#"Regional Manager" = "Minnesota", #"Region" = "Oregon"],
					        [#"Regional Manager" = "Connecticut", #"Region" = "Indiana"],
					        [#"Regional Manager" = "Georgia", #"Region" = "Florida"],
					        [#"Regional Manager" = "Kansas", #"Region" = "North Carolina"],
					        [#"Regional Manager" = "Iowa", #"Region" = "South Carolina"],
					        [#"Regional Manager" = "Maine", #"Region" = "Massachusetts"],
					        [#"Regional Manager" = "South Carolina", #"Region" = "Oklahoma"],
					        [#"Regional Manager" = "Oklahoma", #"Region" = "Mississippi"],
					        [#"Regional Manager" = "Utah", #"Region" = "Montana"],
					        [#"Regional Manager" = "Arkansas", #"Region" = "Hawaii"],
					        [#"Regional Manager" = "North Carolina", #"Region" = "Vermont"],
					        [#"Regional Manager" = "Missouri", #"Region" = "Arizona"],
					        [#"Regional Manager" = "Kansas", #"Region" = "Florida"],
					        [#"Regional Manager" = "Maryland", #"Region" = "Montana"],
					        [#"Regional Manager" = "Indiana", #"Region" = "Delaware"],
					        [#"Regional Manager" = "Maryland", #"Region" = "Missouri"],
					        [#"Regional Manager" = "Wisconsin", #"Region" = "Ohio"],
					        [#"Regional Manager" = "Indiana", #"Region" = "Oregon"],
					        [#"Regional Manager" = "Florida", #"Region" = "New Jersey"],
					        [#"Regional Manager" = "Georgia", #"Region" = "California"],
					        [#"Regional Manager" = "North Dakota", #"Region" = "North Dakota"],
					        [#"Regional Manager" = "Wyoming", #"Region" = "New Hampshire"],
					        [#"Regional Manager" = "Iowa", #"Region" = "Indiana"],
					        [#"Regional Manager" = "Minnesota", #"Region" = "Illinois"],
					        [#"Regional Manager" = "Oregon", #"Region" = "Minnesota"],
					        [#"Regional Manager" = "New Jersey", #"Region" = "Louisiana"],
					        [#"Regional Manager" = "Colorado", #"Region" = "Florida"],
					        [#"Regional Manager" = "Texas", #"Region" = "Nebraska"],
					        [#"Regional Manager" = "Mississippi", #"Region" = "Delaware"],
					        [#"Regional Manager" = "Oregon", #"Region" = "New York"],
					        [#"Regional Manager" = "Kentucky", #"Region" = "Missouri"],
					        [#"Regional Manager" = "Maryland", #"Region" = "Arizona"],
					        [#"Regional Manager" = "Georgia", #"Region" = "Arizona"],
					        [#"Regional Manager" = "Montana", #"Region" = "Utah"],
					        [#"Regional Manager" = "New York", #"Region" = "Alabama"],
					        [#"Regional Manager" = "South Dakota", #"Region" = "Nebraska"],
					        [#"Regional Manager" = "Tennessee", #"Region" = "California"],
					        [#"Regional Manager" = "Nebraska", #"Region" = "Florida"],
					        [#"Regional Manager" = "Mississippi", #"Region" = "South Carolina"],
					        [#"Regional Manager" = "Nebraska", #"Region" = "North Dakota"],
					        [#"Regional Manager" = "Pennsylvania", #"Region" = "Missouri"],
					        [#"Regional Manager" = "Pennsylvania", #"Region" = "Connecticut"],
					        [#"Regional Manager" = "New Jersey", #"Region" = "North Carolina"],
					        [#"Regional Manager" = "New Mexico", #"Region" = "Iowa"],
					        [#"Regional Manager" = "North Carolina", #"Region" = "Idaho"],
					        [#"Regional Manager" = "Connecticut", #"Region" = "Rhode Island"],
					        [#"Regional Manager" = "Florida", #"Region" = "Illinois"],
					        [#"Regional Manager" = "Hawaii", #"Region" = "Vermont"],
					        [#"Regional Manager" = "Montana", #"Region" = "Delaware"],
					        [#"Regional Manager" = "Colorado", #"Region" = "Louisiana"],
					        [#"Regional Manager" = "West Virginia", #"Region" = "Rhode Island"],
					        [#"Regional Manager" = "Texas", #"Region" = "Georgia"],
					        [#"Regional Manager" = "Arizona", #"Region" = "Delaware"],
					        [#"Regional Manager" = "Nevada", #"Region" = "Florida"],
					        [#"Regional Manager" = "Nevada", #"Region" = "Alabama"],
					        [#"Regional Manager" = "Pennsylvania", #"Region" = "Arizona"],
					        [#"Regional Manager" = "Virginia", #"Region" = "Hawaii"],
					        [#"Regional Manager" = "Maryland", #"Region" = "South Carolina"],
					        [#"Regional Manager" = "Wyoming", #"Region" = "Kansas"],
					        [#"Regional Manager" = "Alabama", #"Region" = "Alaska"],
					        [#"Regional Manager" = "Nebraska", #"Region" = "Delaware"],
					        [#"Regional Manager" = "Nebraska", #"Region" = "Oregon"],
					        [#"Regional Manager" = "Arkansas", #"Region" = "Hawaii"],
					        [#"Regional Manager" = "Tennessee", #"Region" = "Michigan"],
					        [#"Regional Manager" = "New York", #"Region" = "Hawaii"],
					        [#"Regional Manager" = "Kansas", #"Region" = "Hawaii"],
					        [#"Regional Manager" = "Florida", #"Region" = "Alaska"],
					        [#"Regional Manager" = "Vermont", #"Region" = "Virginia"],
					        [#"Regional Manager" = "Nebraska", #"Region" = "Hawaii"],
					        [#"Regional Manager" = "Maine", #"Region" = "Vermont"],
					        [#"Regional Manager" = "Missouri", #"Region" = "Rhode Island"],
					        [#"Regional Manager" = "Nevada", #"Region" = "West Virginia"],
					        [#"Regional Manager" = "Vermont", #"Region" = "New York"],
					        [#"Regional Manager" = "Illinois", #"Region" = "Arkansas"],
					        [#"Regional Manager" = "Hawaii", #"Region" = "New Jersey"],
					        [#"Regional Manager" = "Arkansas", #"Region" = "New York"],
					        [#"Regional Manager" = "Indiana", #"Region" = "Alabama"],
					        [#"Regional Manager" = "Alabama", #"Region" = "Washington"],
					        [#"Regional Manager" = "Virginia", #"Region" = "Michigan"],
					        [#"Regional Manager" = "Arkansas", #"Region" = "New Jersey"],
					        [#"Regional Manager" = "Iowa", #"Region" = "Texas"],
					        [#"Regional Manager" = "Louisiana", #"Region" = "Idaho"],
					        [#"Regional Manager" = "Pennsylvania", #"Region" = "Alabama"],
					        [#"Regional Manager" = "Oklahoma", #"Region" = "Colorado"],
					        [#"Regional Manager" = "West Virginia", #"Region" = "New Jersey"],
					        [#"Regional Manager" = "Georgia", #"Region" = "Illinois"],
					        [#"Regional Manager" = "West Virginia", #"Region" = "Utah"],
					        [#"Regional Manager" = "South Carolina", #"Region" = "Hawaii"],
					        [#"Regional Manager" = "Arkansas", #"Region" = "New Mexico"],
					        [#"Regional Manager" = "Washington", #"Region" = "Maine"],
					        [#"Regional Manager" = "Maine", #"Region" = "Delaware"],
					        [#"Regional Manager" = "Massachusetts", #"Region" = "New Mexico"],
					        [#"Regional Manager" = "New Hampshire", #"Region" = "Arkansas"],
					        [#"Regional Manager" = "Ohio", #"Region" = "Iowa"],
					        [#"Regional Manager" = "Arizona", #"Region" = "Georgia"],
					        [#"Regional Manager" = "Ohio", #"Region" = "Ohio"],
					        [#"Regional Manager" = "Michigan", #"Region" = "Louisiana"],
					        [#"Regional Manager" = "Virginia", #"Region" = "Minnesota"],
					        [#"Regional Manager" = "Kansas", #"Region" = "Utah"],
					        [#"Regional Manager" = "New York", #"Region" = "West Virginia"],
					        [#"Regional Manager" = "Missouri", #"Region" = "Pennsylvania"],
					        [#"Regional Manager" = "Louisiana", #"Region" = "Ohio"],
					        [#"Regional Manager" = "Indiana", #"Region" = "Hawaii"],
					        [#"Regional Manager" = "New York", #"Region" = "Michigan"],
					        [#"Regional Manager" = "Alabama", #"Region" = "New Hampshire"],
					        [#"Regional Manager" = "Oklahoma", #"Region" = "California"],
					        [#"Regional Manager" = "New Hampshire", #"Region" = "Louisiana"],
					        [#"Regional Manager" = "West Virginia", #"Region" = "Illinois"],
					        [#"Regional Manager" = "Idaho", #"Region" = "North Carolina"],
					        [#"Regional Manager" = "Georgia", #"Region" = "Connecticut"],
					        [#"Regional Manager" = "Mississippi", #"Region" = "Washington"],
					        [#"Regional Manager" = "Minnesota", #"Region" = "North Dakota"],
					        [#"Regional Manager" = "North Dakota", #"Region" = "Texas"],
					        [#"Regional Manager" = "Colorado", #"Region" = "Louisiana"],
					        [#"Regional Manager" = "Rhode Island", #"Region" = "Delaware"],
					        [#"Regional Manager" = "South Dakota", #"Region" = "Nebraska"],
					        [#"Regional Manager" = "Pennsylvania", #"Region" = "West Virginia"],
					        [#"Regional Manager" = "North Carolina", #"Region" = "New Jersey"],
					        [#"Regional Manager" = "Nevada", #"Region" = "Washington"],
					        [#"Regional Manager" = "Georgia", #"Region" = "Hawaii"],
					        [#"Regional Manager" = "South Carolina", #"Region" = "South Dakota"],
					        [#"Regional Manager" = "Illinois", #"Region" = "Idaho"],
					        [#"Regional Manager" = "Hawaii", #"Region" = "Georgia"],
					        [#"Regional Manager" = "North Carolina", #"Region" = "South Carolina"],
					        [#"Regional Manager" = "Colorado", #"Region" = "Delaware"],
					        [#"Regional Manager" = "Florida", #"Region" = "Oregon"],
					        [#"Regional Manager" = "Georgia", #"Region" = "Indiana"],
					        [#"Regional Manager" = "New York", #"Region" = "Massachusetts"],
					        [#"Regional Manager" = "Connecticut", #"Region" = "Arkansas"],
					        [#"Regional Manager" = "New Hampshire", #"Region" = "California"],
					        [#"Regional Manager" = "Wisconsin", #"Region" = "Connecticut"],
					        [#"Regional Manager" = "Ohio", #"Region" = "Tennessee"],
					        [#"Regional Manager" = "Kansas", #"Region" = "Virginia"],
					        [#"Regional Manager" = "Connecticut", #"Region" = "Oklahoma"],
					        [#"Regional Manager" = "Nevada", #"Region" = "Illinois"],
					        [#"Regional Manager" = "Wisconsin", #"Region" = "Vermont"],
					        [#"Regional Manager" = "Kansas", #"Region" = "Idaho"],
					        [#"Regional Manager" = "Missouri", #"Region" = "Minnesota"],
					        [#"Regional Manager" = "Utah", #"Region" = "Kentucky"],
					        [#"Regional Manager" = "Tennessee", #"Region" = "Tennessee"],
					        [#"Regional Manager" = "Kansas", #"Region" = "California"],
					        [#"Regional Manager" = "Alaska", #"Region" = "Kansas"],
					        [#"Regional Manager" = "Oregon", #"Region" = "Nebraska"],
					        [#"Regional Manager" = "Massachusetts", #"Region" = "Colorado"],
					        [#"Regional Manager" = "New Jersey", #"Region" = "Mississippi"],
					        [#"Regional Manager" = "Idaho", #"Region" = "New York"],
					        [#"Regional Manager" = "Iowa", #"Region" = "Nevada"],
					        [#"Regional Manager" = "Rhode Island", #"Region" = "Mississippi"],
					        [#"Regional Manager" = "Vermont", #"Region" = "Tennessee"],
					        [#"Regional Manager" = "Pennsylvania", #"Region" = "Virginia"],
					        [#"Regional Manager" = "Arkansas", #"Region" = "Tennessee"],
					        [#"Regional Manager" = "Georgia", #"Region" = "Connecticut"],
					        [#"Regional Manager" = "Nebraska", #"Region" = "Indiana"],
					        [#"Regional Manager" = "South Dakota", #"Region" = "Vermont"],
					        [#"Regional Manager" = "Alabama", #"Region" = "Minnesota"],
					        [#"Regional Manager" = "Oregon", #"Region" = "Nebraska"],
					        [#"Regional Manager" = "North Carolina", #"Region" = "Florida"],
					        [#"Regional Manager" = "Virginia", #"Region" = "South Carolina"],
					        [#"Regional Manager" = "Virginia", #"Region" = "Idaho"],
					        [#"Regional Manager" = "Arkansas", #"Region" = "South Dakota"],
					        [#"Regional Manager" = "Minnesota", #"Region" = "Minnesota"],
					        [#"Regional Manager" = "West Virginia", #"Region" = "Wisconsin"],
					        [#"Regional Manager" = "Kentucky", #"Region" = "Georgia"],
					        [#"Regional Manager" = "Delaware", #"Region" = "Ohio"],
					        [#"Regional Manager" = "South Carolina", #"Region" = "Mississippi"],
					        [#"Regional Manager" = "Kentucky", #"Region" = "North Dakota"],
					        [#"Regional Manager" = "Michigan", #"Region" = "New Mexico"],
					        [#"Regional Manager" = "Utah", #"Region" = "Nebraska"],
					        [#"Regional Manager" = "Connecticut", #"Region" = "West Virginia"],
					        [#"Regional Manager" = "Missouri", #"Region" = "Tennessee"],
					        [#"Regional Manager" = "Texas", #"Region" = "Vermont"],
					        [#"Regional Manager" = "Wyoming", #"Region" = "Connecticut"],
					        [#"Regional Manager" = "Connecticut", #"Region" = "West Virginia"],
					        [#"Regional Manager" = "Washington", #"Region" = "Ohio"],
					        [#"Regional Manager" = "Connecticut", #"Region" = "South Carolina"],
					        [#"Regional Manager" = "Colorado", #"Region" = "Utah"],
					        [#"Regional Manager" = "Delaware", #"Region" = "Kansas"],
					        [#"Regional Manager" = "Connecticut", #"Region" = "New Hampshire"],
					        [#"Regional Manager" = "Vermont", #"Region" = "Oregon"],
					        [#"Regional Manager" = "New Hampshire", #"Region" = "Minnesota"],
					        [#"Regional Manager" = "Texas", #"Region" = "Maryland"],
					        [#"Regional Manager" = "West Virginia", #"Region" = "Wisconsin"],
					        [#"Regional Manager" = "Indiana", #"Region" = "Arizona"],
					        [#"Regional Manager" = "Illinois", #"Region" = "Kentucky"],
					        [#"Regional Manager" = "Montana", #"Region" = "Pennsylvania"],
					        [#"Regional Manager" = "Massachusetts", #"Region" = "Florida"],
					        [#"Regional Manager" = "Kansas", #"Region" = "Montana"],
					        [#"Regional Manager" = "Oklahoma", #"Region" = "Wisconsin"],
					        [#"Regional Manager" = "Nebraska", #"Region" = "Maryland"],
					        [#"Regional Manager" = "New Hampshire", #"Region" = "Kentucky"],
					        [#"Regional Manager" = "Nebraska", #"Region" = "Oklahoma"],
					        [#"Regional Manager" = "North Dakota", #"Region" = "Idaho"],
					        [#"Regional Manager" = "Maryland", #"Region" = "Illinois"],
					        [#"Regional Manager" = "Alabama", #"Region" = "North Carolina"],
					        [#"Regional Manager" = "North Carolina", #"Region" = "Idaho"],
					        [#"Regional Manager" = "Tennessee", #"Region" = "Oregon"],
					        [#"Regional Manager" = "New York", #"Region" = "Florida"],
					        [#"Regional Manager" = "Iowa", #"Region" = "Wisconsin"],
					        [#"Regional Manager" = "Minnesota", #"Region" = "Alabama"],
					        [#"Regional Manager" = "Florida", #"Region" = "Kansas"],
					        [#"Regional Manager" = "Georgia", #"Region" = "New Hampshire"],
					        [#"Regional Manager" = "Arkansas", #"Region" = "Washington"],
					        [#"Regional Manager" = "Arkansas", #"Region" = "Mississippi"],
					        [#"Regional Manager" = "South Carolina", #"Region" = "New York"],
					        [#"Regional Manager" = "Illinois", #"Region" = "Vermont"],
					        [#"Regional Manager" = "Florida", #"Region" = "North Carolina"],
					        [#"Regional Manager" = "Nevada", #"Region" = "South Carolina"],
					        [#"Regional Manager" = "Oklahoma", #"Region" = "Ohio"],
					        [#"Regional Manager" = "Indiana", #"Region" = "North Carolina"],
					        [#"Regional Manager" = "Delaware", #"Region" = "Florida"],
					        [#"Regional Manager" = "Mississippi", #"Region" = "New York"],
					        [#"Regional Manager" = "Hawaii", #"Region" = "Idaho"],
					        [#"Regional Manager" = "Louisiana", #"Region" = "Kentucky"],
					        [#"Regional Manager" = "Delaware", #"Region" = "North Carolina"],
					        [#"Regional Manager" = "West Virginia", #"Region" = "Colorado"],
					        [#"Regional Manager" = "Michigan", #"Region" = "New Hampshire"],
					        [#"Regional Manager" = "North Dakota", #"Region" = "Georgia"],
					        [#"Regional Manager" = "Maine", #"Region" = "Florida"],
					        [#"Regional Manager" = "Wyoming", #"Region" = "Arizona"],
					        [#"Regional Manager" = "Colorado", #"Region" = "Washington"],
					        [#"Regional Manager" = "Texas", #"Region" = "Vermont"],
					        [#"Regional Manager" = "Utah", #"Region" = "Georgia"],
					        [#"Regional Manager" = "Kansas", #"Region" = "Connecticut"],
					        [#"Regional Manager" = "Washington", #"Region" = "Massachusetts"],
					        [#"Regional Manager" = "North Carolina", #"Region" = "Kansas"],
					        [#"Regional Manager" = "South Carolina", #"Region" = "Tennessee"],
					        [#"Regional Manager" = "California", #"Region" = "Alaska"],
					        [#"Regional Manager" = "Minnesota", #"Region" = "Colorado"],
					        [#"Regional Manager" = "New York", #"Region" = "Nevada"],
					        [#"Regional Manager" = "Tennessee", #"Region" = "Washington"],
					        [#"Regional Manager" = "Delaware", #"Region" = "North Dakota"],
					        [#"Regional Manager" = "Oklahoma", #"Region" = "Illinois"],
					        [#"Regional Manager" = "Mississippi", #"Region" = "Virginia"],
					        [#"Regional Manager" = "New York", #"Region" = "Iowa"],
					        [#"Regional Manager" = "Oklahoma", #"Region" = "Oklahoma"],
					        [#"Regional Manager" = "Iowa", #"Region" = "New Jersey"],
					        [#"Regional Manager" = "Illinois", #"Region" = "New Mexico"],
					        [#"Regional Manager" = "Arkansas", #"Region" = "Ohio"],
					        [#"Regional Manager" = "Georgia", #"Region" = "Oklahoma"],
					        [#"Regional Manager" = "Utah", #"Region" = "South Carolina"],
					        [#"Regional Manager" = "Maine", #"Region" = "Minnesota"],
					        [#"Regional Manager" = "Connecticut", #"Region" = "Georgia"],
					        [#"Regional Manager" = "Delaware", #"Region" = "Maine"],
					        [#"Regional Manager" = "Arkansas", #"Region" = "West Virginia"],
					        [#"Regional Manager" = "Arkansas", #"Region" = "Vermont"],
					        [#"Regional Manager" = "Virginia", #"Region" = "Colorado"],
					        [#"Regional Manager" = "North Carolina", #"Region" = "Wyoming"],
					        [#"Regional Manager" = "Alabama", #"Region" = "Louisiana"],
					        [#"Regional Manager" = "Tennessee", #"Region" = "New Jersey"],
					        [#"Regional Manager" = "West Virginia", #"Region" = "North Carolina"],
					        [#"Regional Manager" = "North Carolina", #"Region" = "Arkansas"],
					        [#"Regional Manager" = "Alaska", #"Region" = "Florida"],
					        [#"Regional Manager" = "Illinois", #"Region" = "Alaska"],
					        [#"Regional Manager" = "California", #"Region" = "Maine"],
					        [#"Regional Manager" = "Alaska", #"Region" = "Illinois"],
					        [#"Regional Manager" = "Kansas", #"Region" = "Indiana"],
					        [#"Regional Manager" = "Tennessee", #"Region" = "Nevada"],
					        [#"Regional Manager" = "South Carolina", #"Region" = "Arizona"],
					        [#"Regional Manager" = "Massachusetts", #"Region" = "South Carolina"],
					        [#"Regional Manager" = "Louisiana", #"Region" = "New York"],
					        [#"Regional Manager" = "Wyoming", #"Region" = "Oklahoma"],
					        [#"Regional Manager" = "North Carolina", #"Region" = "Wyoming"],
					        [#"Regional Manager" = "Mississippi", #"Region" = "Virginia"],
					        [#"Regional Manager" = "California", #"Region" = "Hawaii"],
					        [#"Regional Manager" = "California", #"Region" = "Alabama"],
					        [#"Regional Manager" = "Massachusetts", #"Region" = "Kansas"],
					        [#"Regional Manager" = "North Dakota", #"Region" = "Colorado"],
					        [#"Regional Manager" = "Massachusetts", #"Region" = "Massachusetts"],
					        [#"Regional Manager" = "Vermont", #"Region" = "Mississippi"],
					        [#"Regional Manager" = "Texas", #"Region" = "Tennessee"],
					        [#"Regional Manager" = "North Dakota", #"Region" = "Kansas"],
					        [#"Regional Manager" = "Delaware", #"Region" = "Missouri"],
					        [#"Regional Manager" = "Illinois", #"Region" = "Vermont"],
					        [#"Regional Manager" = "Virginia", #"Region" = "Missouri"],
					        [#"Regional Manager" = "Kansas", #"Region" = "North Dakota"],
					        [#"Regional Manager" = "Connecticut", #"Region" = "Tennessee"],
					        [#"Regional Manager" = "California", #"Region" = "Wisconsin"],
					        [#"Regional Manager" = "Wisconsin", #"Region" = "Vermont"],
					        [#"Regional Manager" = "West Virginia", #"Region" = "New York"],
					        [#"Regional Manager" = "Pennsylvania", #"Region" = "Ohio"],
					        [#"Regional Manager" = "Delaware", #"Region" = "Illinois"],
					        [#"Regional Manager" = "Connecticut", #"Region" = "Minnesota"],
					        [#"Regional Manager" = "Pennsylvania", #"Region" = "South Carolina"],
					        [#"Regional Manager" = "Rhode Island", #"Region" = "California"],
					        [#"Regional Manager" = "Oklahoma", #"Region" = "Georgia"],
					        [#"Regional Manager" = "Mississippi", #"Region" = "Utah"],
					        [#"Regional Manager" = "Kentucky", #"Region" = "Vermont"],
					        [#"Regional Manager" = "Utah", #"Region" = "Maine"],
					        [#"Regional Manager" = "Pennsylvania", #"Region" = "Missouri"],
					        [#"Regional Manager" = "Illinois", #"Region" = "California"],
					        [#"Regional Manager" = "Arizona", #"Region" = "New York"],
					        [#"Regional Manager" = "Texas", #"Region" = "South Dakota"],
					        [#"Regional Manager" = "Arkansas", #"Region" = "Minnesota"],
					        [#"Regional Manager" = "Arkansas", #"Region" = "Vermont"],
					        [#"Regional Manager" = "Delaware", #"Region" = "Oregon"],
					        [#"Regional Manager" = "Illinois", #"Region" = "Colorado"],
					        [#"Regional Manager" = "Texas", #"Region" = "Illinois"],
					        [#"Regional Manager" = "South Dakota", #"Region" = "Hawaii"],
					        [#"Regional Manager" = "North Dakota", #"Region" = "Ohio"],
					        [#"Regional Manager" = "New Jersey", #"Region" = "Michigan"],
					        [#"Regional Manager" = "Utah", #"Region" = "Hawaii"],
					        [#"Regional Manager" = "Mississippi", #"Region" = "Alaska"],
					        [#"Regional Manager" = "Minnesota", #"Region" = "Pennsylvania"],
					        [#"Regional Manager" = "Hawaii", #"Region" = "New Jersey"],
					        [#"Regional Manager" = "Nevada", #"Region" = "Colorado"],
					        [#"Regional Manager" = "Maine", #"Region" = "Georgia"],
					        [#"Regional Manager" = "Arkansas", #"Region" = "Ohio"],
					        [#"Regional Manager" = "California", #"Region" = "South Dakota"],
					        [#"Regional Manager" = "Michigan", #"Region" = "Utah"],
					        [#"Regional Manager" = "Washington", #"Region" = "Texas"],
					        [#"Regional Manager" = "Texas", #"Region" = "Oklahoma"],
					        [#"Regional Manager" = "Oregon", #"Region" = "Nebraska"],
					        [#"Regional Manager" = "Alaska", #"Region" = "Massachusetts"],
					        [#"Regional Manager" = "Connecticut", #"Region" = "Georgia"],
					        [#"Regional Manager" = "Vermont", #"Region" = "Illinois"],
					        [#"Regional Manager" = "New York", #"Region" = "Hawaii"],
					        [#"Regional Manager" = "Maine", #"Region" = "Tennessee"],
					        [#"Regional Manager" = "Missouri", #"Region" = "Kansas"],
					        [#"Regional Manager" = "Kentucky", #"Region" = "Indiana"],
					        [#"Regional Manager" = "Texas", #"Region" = "Delaware"],
					        [#"Regional Manager" = "Washington", #"Region" = "Delaware"],
					        [#"Regional Manager" = "New Hampshire", #"Region" = "Montana"],
					        [#"Regional Manager" = "Massachusetts", #"Region" = "Montana"],
					        [#"Regional Manager" = "Hawaii", #"Region" = "Maryland"],
					        [#"Regional Manager" = "Delaware", #"Region" = "Florida"],
					        [#"Regional Manager" = "South Carolina", #"Region" = "North Carolina"],
					        [#"Regional Manager" = "Virginia", #"Region" = "Texas"],
					        [#"Regional Manager" = "Louisiana", #"Region" = "Kentucky"],
					        [#"Regional Manager" = "New Mexico", #"Region" = "Maine"],
					        [#"Regional Manager" = "New Hampshire", #"Region" = "Oregon"],
					        [#"Regional Manager" = "Massachusetts", #"Region" = "New Mexico"],
					        [#"Regional Manager" = "Georgia", #"Region" = "Utah"],
					        [#"Regional Manager" = "Hawaii", #"Region" = "New Hampshire"],
					        [#"Regional Manager" = "Idaho", #"Region" = "Iowa"],
					        [#"Regional Manager" = "Georgia", #"Region" = "New Mexico"],
					        [#"Regional Manager" = "Missouri", #"Region" = "California"],
					        [#"Regional Manager" = "Mississippi", #"Region" = "Nevada"],
					        [#"Regional Manager" = "Mississippi", #"Region" = "California"],
					        [#"Regional Manager" = "New Jersey", #"Region" = "Idaho"],
					        [#"Regional Manager" = "Wisconsin", #"Region" = "West Virginia"],
					        [#"Regional Manager" = "Oregon", #"Region" = "Michigan"],
					        [#"Regional Manager" = "West Virginia", #"Region" = "South Dakota"],
					        [#"Regional Manager" = "Michigan", #"Region" = "Minnesota"],
					        [#"Regional Manager" = "Tennessee", #"Region" = "Virginia"],
					        [#"Regional Manager" = "Nevada", #"Region" = "Georgia"],
					        [#"Regional Manager" = "Alabama", #"Region" = "Wisconsin"],
					        [#"Regional Manager" = "Louisiana", #"Region" = "Nebraska"],
					        [#"Regional Manager" = "Virginia", #"Region" = "Illinois"],
					        [#"Regional Manager" = "Arkansas", #"Region" = "Oklahoma"],
					        [#"Regional Manager" = "Tennessee", #"Region" = "Virginia"],
					        [#"Regional Manager" = "Ohio", #"Region" = "Alabama"],
					        [#"Regional Manager" = "Missouri", #"Region" = "New York"],
					        [#"Regional Manager" = "North Dakota", #"Region" = "Alabama"],
					        [#"Regional Manager" = "Tennessee", #"Region" = "New Jersey"],
					        [#"Regional Manager" = "Arizona", #"Region" = "Arkansas"],
					        [#"Regional Manager" = "New York", #"Region" = "Oklahoma"],
					        [#"Regional Manager" = "Michigan", #"Region" = "Montana"],
					        [#"Regional Manager" = "Tennessee", #"Region" = "Hawaii"],
					        [#"Regional Manager" = "Tennessee", #"Region" = "Maryland"],
					        [#"Regional Manager" = "Minnesota", #"Region" = "Arizona"],
					        [#"Regional Manager" = "Alaska", #"Region" = "Rhode Island"],
					        [#"Regional Manager" = "Louisiana", #"Region" = "Michigan"],
					        [#"Regional Manager" = "New Mexico", #"Region" = "Iowa"],
					        [#"Regional Manager" = "Colorado", #"Region" = "California"],
					        [#"Regional Manager" = "New Hampshire", #"Region" = "Kansas"],
					        [#"Regional Manager" = "Pennsylvania", #"Region" = "Minnesota"],
					        [#"Regional Manager" = "New York", #"Region" = "Pennsylvania"],
					        [#"Regional Manager" = "Minnesota", #"Region" = "New Jersey"],
					        [#"Regional Manager" = "Utah", #"Region" = "Idaho"],
					        [#"Regional Manager" = "Indiana", #"Region" = "Utah"],
					        [#"Regional Manager" = "Maryland", #"Region" = "Idaho"],
					        [#"Regional Manager" = "Michigan", #"Region" = "North Dakota"],
					        [#"Regional Manager" = "Nebraska", #"Region" = "Montana"],
					        [#"Regional Manager" = "West Virginia", #"Region" = "Colorado"],
					        [#"Regional Manager" = "Alaska", #"Region" = "Florida"],
					        [#"Regional Manager" = "Nevada", #"Region" = "Nebraska"],
					        [#"Regional Manager" = "Alabama", #"Region" = "Michigan"],
					        [#"Regional Manager" = "Wisconsin", #"Region" = "Oklahoma"],
					        [#"Regional Manager" = "Minnesota", #"Region" = "New Hampshire"],
					        [#"Regional Manager" = "Kentucky", #"Region" = "North Carolina"],
					        [#"Regional Manager" = "Arizona", #"Region" = "New Hampshire"],
					        [#"Regional Manager" = "South Dakota", #"Region" = "Illinois"],
					        [#"Regional Manager" = "Rhode Island", #"Region" = "Georgia"],
					        [#"Regional Manager" = "Maine", #"Region" = "Connecticut"],
					        [#"Regional Manager" = "West Virginia", #"Region" = "Nebraska"],
					        [#"Regional Manager" = "Pennsylvania", #"Region" = "Michigan"],
					        [#"Regional Manager" = "New York", #"Region" = "Connecticut"],
					        [#"Regional Manager" = "Florida", #"Region" = "New Mexico"],
					        [#"Regional Manager" = "New York", #"Region" = "Minnesota"],
					        [#"Regional Manager" = "New Jersey", #"Region" = "Massachusetts"],
					        [#"Regional Manager" = "Indiana", #"Region" = "Washington"],
					        [#"Regional Manager" = "Virginia", #"Region" = "Georgia"],
					        [#"Regional Manager" = "Missouri", #"Region" = "Maryland"],
					        [#"Regional Manager" = "Virginia", #"Region" = "Minnesota"],
					        [#"Regional Manager" = "Georgia", #"Region" = "Wisconsin"],
					        [#"Regional Manager" = "Texas", #"Region" = "Georgia"],
					        [#"Regional Manager" = "Louisiana", #"Region" = "Oregon"],
					        [#"Regional Manager" = "Kansas", #"Region" = "New Hampshire"],
					        [#"Regional Manager" = "Mississippi", #"Region" = "Alaska"],
					        [#"Regional Manager" = "Vermont", #"Region" = "Arkansas"],
					        [#"Regional Manager" = "Iowa", #"Region" = "Indiana"],
					        [#"Regional Manager" = "Idaho", #"Region" = "Missouri"],
					        [#"Regional Manager" = "Washington", #"Region" = "Kansas"],
					        [#"Regional Manager" = "Tennessee", #"Region" = "Connecticut"],
					        [#"Regional Manager" = "Virginia", #"Region" = "Colorado"],
					        [#"Regional Manager" = "Alaska", #"Region" = "Hawaii"],
					        [#"Regional Manager" = "Wyoming", #"Region" = "Nevada"],
					        [#"Regional Manager" = "Missouri", #"Region" = "Louisiana"],
					        [#"Regional Manager" = "Montana", #"Region" = "Connecticut"],
					        [#"Regional Manager" = "Rhode Island", #"Region" = "Vermont"],
					        [#"Regional Manager" = "Wyoming", #"Region" = "California"],
					        [#"Regional Manager" = "Ohio", #"Region" = "Rhode Island"],
					        [#"Regional Manager" = "Nevada", #"Region" = "Louisiana"],
					        [#"Regional Manager" = "Virginia", #"Region" = "California"],
					        [#"Regional Manager" = "New York", #"Region" = "Illinois"],
					        [#"Regional Manager" = "New Hampshire", #"Region" = "Alaska"],
					        [#"Regional Manager" = "West Virginia", #"Region" = "Hawaii"],
					        [#"Regional Manager" = "Nebraska", #"Region" = "Indiana"],
					        [#"Regional Manager" = "Alabama", #"Region" = "Idaho"],
					        [#"Regional Manager" = "Connecticut", #"Region" = "Iowa"],
					        [#"Regional Manager" = "Delaware", #"Region" = "New Mexico"],
					        [#"Regional Manager" = "Illinois", #"Region" = "Maryland"],
					        [#"Regional Manager" = "Florida", #"Region" = "New Jersey"],
					        [#"Regional Manager" = "Virginia", #"Region" = "California"],
					        [#"Regional Manager" = "Nevada", #"Region" = "Oregon"],
					        [#"Regional Manager" = "Montana", #"Region" = "Texas"],
					        [#"Regional Manager" = "Arizona", #"Region" = "Michigan"],
					        [#"Regional Manager" = "California", #"Region" = "Kansas"],
					        [#"Regional Manager" = "Iowa", #"Region" = "Vermont"],
					        [#"Regional Manager" = "Michigan", #"Region" = "Vermont"],
					        [#"Regional Manager" = "California", #"Region" = "Alaska"],
					        [#"Regional Manager" = "New Hampshire", #"Region" = "Pennsylvania"],
					        [#"Regional Manager" = "Alabama", #"Region" = "New York"],
					        [#"Regional Manager" = "New Jersey", #"Region" = "Massachusetts"],
					        [#"Regional Manager" = "Utah", #"Region" = "New Mexico"],
					        [#"Regional Manager" = "Arizona", #"Region" = "Mississippi"],
					        [#"Regional Manager" = "Connecticut", #"Region" = "Kentucky"],
					        [#"Regional Manager" = "New Mexico", #"Region" = "Tennessee"],
					        [#"Regional Manager" = "Maine", #"Region" = "Nevada"],
					        [#"Regional Manager" = "Massachusetts", #"Region" = "Montana"],
					        [#"Regional Manager" = "Tennessee", #"Region" = "Alabama"],
					        [#"Regional Manager" = "Virginia", #"Region" = "Mississippi"],
					        [#"Regional Manager" = "Florida", #"Region" = "Iowa"],
					        [#"Regional Manager" = "North Carolina", #"Region" = "Tennessee"],
					        [#"Regional Manager" = "Louisiana", #"Region" = "Mississippi"],
					        [#"Regional Manager" = "Illinois", #"Region" = "Washington"],
					        [#"Regional Manager" = "New Hampshire", #"Region" = "Massachusetts"],
					        [#"Regional Manager" = "Oklahoma", #"Region" = "Arizona"],
					        [#"Regional Manager" = "Utah", #"Region" = "Tennessee"],
					        [#"Regional Manager" = "Delaware", #"Region" = "Rhode Island"],
					        [#"Regional Manager" = "Alaska", #"Region" = "Oklahoma"],
					        [#"Regional Manager" = "New Mexico", #"Region" = "Indiana"],
					        [#"Regional Manager" = "South Carolina", #"Region" = "Idaho"],
					        [#"Regional Manager" = "Maryland", #"Region" = "Arkansas"],
					        [#"Regional Manager" = "California", #"Region" = "Ohio"],
					        [#"Regional Manager" = "Virginia", #"Region" = "Wyoming"],
					        [#"Regional Manager" = "Rhode Island", #"Region" = "Louisiana"],
					        [#"Regional Manager" = "Rhode Island", #"Region" = "Colorado"],
					        [#"Regional Manager" = "Illinois", #"Region" = "Ohio"],
					        [#"Regional Manager" = "California", #"Region" = "New York"],
					        [#"Regional Manager" = "Maryland", #"Region" = "Vermont"],
					        [#"Regional Manager" = "Arkansas", #"Region" = "Colorado"],
					        [#"Regional Manager" = "Alabama", #"Region" = "South Dakota"],
					        [#"Regional Manager" = "Alabama", #"Region" = "Mississippi"],
					        [#"Regional Manager" = "Colorado", #"Region" = "Maryland"],
					        [#"Regional Manager" = "Wyoming", #"Region" = "North Dakota"],
					        [#"Regional Manager" = "Wisconsin", #"Region" = "Colorado"],
					        [#"Regional Manager" = "South Dakota", #"Region" = "West Virginia"],
					        [#"Regional Manager" = "Colorado", #"Region" = "Nebraska"],
					        [#"Regional Manager" = "Missouri", #"Region" = "Virginia"],
					        [#"Regional Manager" = "Virginia", #"Region" = "Arkansas"],
					        [#"Regional Manager" = "California", #"Region" = "Nevada"],
					        [#"Regional Manager" = "Minnesota", #"Region" = "Louisiana"],
					        [#"Regional Manager" = "Delaware", #"Region" = "Indiana"],
					        [#"Regional Manager" = "Texas", #"Region" = "Arizona"],
					        [#"Regional Manager" = "Maine", #"Region" = "Louisiana"],
					        [#"Regional Manager" = "Arkansas", #"Region" = "New Mexico"],
					        [#"Regional Manager" = "Texas", #"Region" = "Tennessee"],
					        [#"Regional Manager" = "Missouri", #"Region" = "California"],
					        [#"Regional Manager" = "New Jersey", #"Region" = "North Dakota"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Regional Manager", type text},
					        {"Region", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table