table 'Orders+ (Sample - Superstore)_Returns'
	lineageTag: dd8c8a4e-fc82-413e-89bb-3f41377b8e97

	column Returned
		dataType: string
		lineageTag: 29ed6a75-f7b5-4a8a-980d-beebea6f1ede
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 7652e724-f581-40bf-b9b6-85bf9ebdceef
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	partition 'Orders+ (Sample - Superstore)_Returns' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Returned" = "political", #"Order ID" = 2566],
					        [#"Returned" = "discussion", #"Order ID" = 7442],
					        [#"Returned" = "blonde", #"Order ID" = 6787],
					        [#"Returned" = "show", #"Order ID" = 4661],
					        [#"Returned" = "surrounding", #"Order ID" = 2885],
					        [#"Returned" = "poland", #"Order ID" = 5806],
					        [#"Returned" = "sri", #"Order ID" = 1123],
					        [#"Returned" = "male", #"Order ID" = 3877],
					        [#"Returned" = "your", #"Order ID" = 3074],
					        [#"Returned" = "bags", #"Order ID" = 7221],
					        [#"Returned" = "interface", #"Order ID" = 4750],
					        [#"Returned" = "spyware", #"Order ID" = 9241],
					        [#"Returned" = "bet", #"Order ID" = 9629],
					        [#"Returned" = "parts", #"Order ID" = 4586],
					        [#"Returned" = "right", #"Order ID" = 7817],
					        [#"Returned" = "struct", #"Order ID" = 1854],
					        [#"Returned" = "accommodation", #"Order ID" = 5494],
					        [#"Returned" = "assist", #"Order ID" = 3532],
					        [#"Returned" = "europe", #"Order ID" = 1961],
					        [#"Returned" = "leg", #"Order ID" = 3633],
					        [#"Returned" = "search", #"Order ID" = 2706],
					        [#"Returned" = "headset", #"Order ID" = 5453],
					        [#"Returned" = "worship", #"Order ID" = 9350],
					        [#"Returned" = "operate", #"Order ID" = 7549],
					        [#"Returned" = "holder", #"Order ID" = 6742],
					        [#"Returned" = "prohibited", #"Order ID" = 8627],
					        [#"Returned" = "pics", #"Order ID" = 2941],
					        [#"Returned" = "happening", #"Order ID" = 7689],
					        [#"Returned" = "pharmacy", #"Order ID" = 8275],
					        [#"Returned" = "mitchell", #"Order ID" = 5180],
					        [#"Returned" = "teacher", #"Order ID" = 9940],
					        [#"Returned" = "markets", #"Order ID" = 4679],
					        [#"Returned" = "england", #"Order ID" = 8313],
					        [#"Returned" = "cameras", #"Order ID" = 2329],
					        [#"Returned" = "cpu", #"Order ID" = 7114],
					        [#"Returned" = "scan", #"Order ID" = 8026],
					        [#"Returned" = "billing", #"Order ID" = 9116],
					        [#"Returned" = "antiques", #"Order ID" = 3759],
					        [#"Returned" = "nine", #"Order ID" = 9497],
					        [#"Returned" = "tax", #"Order ID" = 5718],
					        [#"Returned" = "nuclear", #"Order ID" = 2112],
					        [#"Returned" = "yorkshire", #"Order ID" = 2013],
					        [#"Returned" = "bags", #"Order ID" = 8170],
					        [#"Returned" = "announcement", #"Order ID" = 6755],
					        [#"Returned" = "dangerous", #"Order ID" = 3608],
					        [#"Returned" = "announce", #"Order ID" = 9318],
					        [#"Returned" = "her", #"Order ID" = 9796],
					        [#"Returned" = "franklin", #"Order ID" = 5171],
					        [#"Returned" = "handle", #"Order ID" = 6451],
					        [#"Returned" = "delivered", #"Order ID" = 5982],
					        [#"Returned" = "stored", #"Order ID" = 7079],
					        [#"Returned" = "index", #"Order ID" = 4839],
					        [#"Returned" = "shoe", #"Order ID" = 6219],
					        [#"Returned" = "financing", #"Order ID" = 2803],
					        [#"Returned" = "efforts", #"Order ID" = 8878],
					        [#"Returned" = "processors", #"Order ID" = 2406],
					        [#"Returned" = "sleeve", #"Order ID" = 7230],
					        [#"Returned" = "bonus", #"Order ID" = 2226],
					        [#"Returned" = "shift", #"Order ID" = 5097],
					        [#"Returned" = "de", #"Order ID" = 7463],
					        [#"Returned" = "partly", #"Order ID" = 1804],
					        [#"Returned" = "disorders", #"Order ID" = 5384],
					        [#"Returned" = "expand", #"Order ID" = 8465],
					        [#"Returned" = "flowers", #"Order ID" = 1913],
					        [#"Returned" = "av", #"Order ID" = 7977],
					        [#"Returned" = "thinking", #"Order ID" = 7095],
					        [#"Returned" = "opera", #"Order ID" = 5981],
					        [#"Returned" = "cache", #"Order ID" = 5880],
					        [#"Returned" = "worked", #"Order ID" = 9112],
					        [#"Returned" = "level", #"Order ID" = 2728],
					        [#"Returned" = "document", #"Order ID" = 4404],
					        [#"Returned" = "suitable", #"Order ID" = 6319],
					        [#"Returned" = "copy", #"Order ID" = 3759],
					        [#"Returned" = "paris", #"Order ID" = 2742],
					        [#"Returned" = "processors", #"Order ID" = 2153],
					        [#"Returned" = "depth", #"Order ID" = 6955],
					        [#"Returned" = "member", #"Order ID" = 6720],
					        [#"Returned" = "conservation", #"Order ID" = 7675],
					        [#"Returned" = "main", #"Order ID" = 1835],
					        [#"Returned" = "animals", #"Order ID" = 2152],
					        [#"Returned" = "pleased", #"Order ID" = 6051],
					        [#"Returned" = "uniprotkb", #"Order ID" = 8103],
					        [#"Returned" = "continue", #"Order ID" = 9273],
					        [#"Returned" = "mobile", #"Order ID" = 1823],
					        [#"Returned" = "rich", #"Order ID" = 7600],
					        [#"Returned" = "sensor", #"Order ID" = 6479],
					        [#"Returned" = "oxford", #"Order ID" = 1382],
					        [#"Returned" = "brochure", #"Order ID" = 6866],
					        [#"Returned" = "usage", #"Order ID" = 8517],
					        [#"Returned" = "toner", #"Order ID" = 3611],
					        [#"Returned" = "spring", #"Order ID" = 9487],
					        [#"Returned" = "advertising", #"Order ID" = 1235],
					        [#"Returned" = "presents", #"Order ID" = 7032],
					        [#"Returned" = "hide", #"Order ID" = 4657],
					        [#"Returned" = "pine", #"Order ID" = 7592],
					        [#"Returned" = "provisions", #"Order ID" = 7027],
					        [#"Returned" = "greek", #"Order ID" = 6717],
					        [#"Returned" = "sign", #"Order ID" = 6458],
					        [#"Returned" = "acting", #"Order ID" = 9553],
					        [#"Returned" = "guardian", #"Order ID" = 4347],
					        [#"Returned" = "rule", #"Order ID" = 8260],
					        [#"Returned" = "views", #"Order ID" = 3935],
					        [#"Returned" = "stand", #"Order ID" = 2881],
					        [#"Returned" = "relations", #"Order ID" = 8376],
					        [#"Returned" = "fight", #"Order ID" = 1032],
					        [#"Returned" = "representing", #"Order ID" = 2085],
					        [#"Returned" = "treatments", #"Order ID" = 5968],
					        [#"Returned" = "parent", #"Order ID" = 9540],
					        [#"Returned" = "are", #"Order ID" = 6025],
					        [#"Returned" = "performed", #"Order ID" = 6107],
					        [#"Returned" = "below", #"Order ID" = 2493],
					        [#"Returned" = "places", #"Order ID" = 3804],
					        [#"Returned" = "engineer", #"Order ID" = 1706],
					        [#"Returned" = "lb", #"Order ID" = 2951],
					        [#"Returned" = "mine", #"Order ID" = 8506],
					        [#"Returned" = "chamber", #"Order ID" = 3837],
					        [#"Returned" = "wonder", #"Order ID" = 9064],
					        [#"Returned" = "half", #"Order ID" = 1125],
					        [#"Returned" = "pure", #"Order ID" = 7460],
					        [#"Returned" = "huge", #"Order ID" = 6420],
					        [#"Returned" = "moderator", #"Order ID" = 6898],
					        [#"Returned" = "stated", #"Order ID" = 9075],
					        [#"Returned" = "albert", #"Order ID" = 4036],
					        [#"Returned" = "tracks", #"Order ID" = 6473],
					        [#"Returned" = "revenue", #"Order ID" = 6729],
					        [#"Returned" = "disease", #"Order ID" = 6503],
					        [#"Returned" = "this", #"Order ID" = 7187],
					        [#"Returned" = "sean", #"Order ID" = 7229],
					        [#"Returned" = "subscribers", #"Order ID" = 7917],
					        [#"Returned" = "family", #"Order ID" = 6160],
					        [#"Returned" = "weather", #"Order ID" = 8720],
					        [#"Returned" = "ship", #"Order ID" = 3249],
					        [#"Returned" = "wide", #"Order ID" = 2743],
					        [#"Returned" = "blues", #"Order ID" = 9025],
					        [#"Returned" = "weight", #"Order ID" = 7671],
					        [#"Returned" = "packaging", #"Order ID" = 4570],
					        [#"Returned" = "shows", #"Order ID" = 7950],
					        [#"Returned" = "honest", #"Order ID" = 3103],
					        [#"Returned" = "nh", #"Order ID" = 9558],
					        [#"Returned" = "limousines", #"Order ID" = 1369],
					        [#"Returned" = "fed", #"Order ID" = 7698],
					        [#"Returned" = "results", #"Order ID" = 9154],
					        [#"Returned" = "vbulletin", #"Order ID" = 9948],
					        [#"Returned" = "fm", #"Order ID" = 8699],
					        [#"Returned" = "russian", #"Order ID" = 1787],
					        [#"Returned" = "ringtones", #"Order ID" = 7835],
					        [#"Returned" = "upcoming", #"Order ID" = 3317],
					        [#"Returned" = "atlanta", #"Order ID" = 4353],
					        [#"Returned" = "majority", #"Order ID" = 1626],
					        [#"Returned" = "leather", #"Order ID" = 7894],
					        [#"Returned" = "governments", #"Order ID" = 3542],
					        [#"Returned" = "miller", #"Order ID" = 5194],
					        [#"Returned" = "tobacco", #"Order ID" = 2307],
					        [#"Returned" = "illegal", #"Order ID" = 3279],
					        [#"Returned" = "sin", #"Order ID" = 2094],
					        [#"Returned" = "digital", #"Order ID" = 5389],
					        [#"Returned" = "rc", #"Order ID" = 9256],
					        [#"Returned" = "lottery", #"Order ID" = 8781],
					        [#"Returned" = "pink", #"Order ID" = 4212],
					        [#"Returned" = "violence", #"Order ID" = 8347],
					        [#"Returned" = "results", #"Order ID" = 9280],
					        [#"Returned" = "stuff", #"Order ID" = 3733],
					        [#"Returned" = "probably", #"Order ID" = 5284],
					        [#"Returned" = "garage", #"Order ID" = 9054],
					        [#"Returned" = "poll", #"Order ID" = 8159],
					        [#"Returned" = "history", #"Order ID" = 8686],
					        [#"Returned" = "cf", #"Order ID" = 8566],
					        [#"Returned" = "calculator", #"Order ID" = 9557],
					        [#"Returned" = "tune", #"Order ID" = 8785],
					        [#"Returned" = "changed", #"Order ID" = 9623],
					        [#"Returned" = "overseas", #"Order ID" = 2547],
					        [#"Returned" = "rent", #"Order ID" = 2892],
					        [#"Returned" = "there", #"Order ID" = 8254],
					        [#"Returned" = "ron", #"Order ID" = 6103],
					        [#"Returned" = "seed", #"Order ID" = 8272],
					        [#"Returned" = "dynamic", #"Order ID" = 4483],
					        [#"Returned" = "camp", #"Order ID" = 3377],
					        [#"Returned" = "conducted", #"Order ID" = 4081],
					        [#"Returned" = "american", #"Order ID" = 7524],
					        [#"Returned" = "united", #"Order ID" = 9626],
					        [#"Returned" = "brokers", #"Order ID" = 9332],
					        [#"Returned" = "hearing", #"Order ID" = 1695],
					        [#"Returned" = "integer", #"Order ID" = 5728],
					        [#"Returned" = "dispute", #"Order ID" = 5212],
					        [#"Returned" = "modeling", #"Order ID" = 9140],
					        [#"Returned" = "situation", #"Order ID" = 1113],
					        [#"Returned" = "saved", #"Order ID" = 1666],
					        [#"Returned" = "outcomes", #"Order ID" = 6362],
					        [#"Returned" = "container", #"Order ID" = 6338],
					        [#"Returned" = "world", #"Order ID" = 1902],
					        [#"Returned" = "networks", #"Order ID" = 5705],
					        [#"Returned" = "pa", #"Order ID" = 7287],
					        [#"Returned" = "ray", #"Order ID" = 4360],
					        [#"Returned" = "php", #"Order ID" = 6967],
					        [#"Returned" = "sr", #"Order ID" = 2632],
					        [#"Returned" = "franchise", #"Order ID" = 5756],
					        [#"Returned" = "include", #"Order ID" = 9905],
					        [#"Returned" = "nsw", #"Order ID" = 6196],
					        [#"Returned" = "currently", #"Order ID" = 3628],
					        [#"Returned" = "discrimination", #"Order ID" = 4118],
					        [#"Returned" = "roof", #"Order ID" = 2658],
					        [#"Returned" = "lan", #"Order ID" = 3857],
					        [#"Returned" = "hero", #"Order ID" = 2113],
					        [#"Returned" = "where", #"Order ID" = 2421],
					        [#"Returned" = "prevent", #"Order ID" = 6120],
					        [#"Returned" = "leisure", #"Order ID" = 4930],
					        [#"Returned" = "panasonic", #"Order ID" = 2831],
					        [#"Returned" = "camel", #"Order ID" = 4971],
					        [#"Returned" = "bush", #"Order ID" = 3884],
					        [#"Returned" = "fitness", #"Order ID" = 5105],
					        [#"Returned" = "utc", #"Order ID" = 5161],
					        [#"Returned" = "errors", #"Order ID" = 4877],
					        [#"Returned" = "fees", #"Order ID" = 2410],
					        [#"Returned" = "heart", #"Order ID" = 3841],
					        [#"Returned" = "liberty", #"Order ID" = 4225],
					        [#"Returned" = "cartridges", #"Order ID" = 1338],
					        [#"Returned" = "wake", #"Order ID" = 9729],
					        [#"Returned" = "carbon", #"Order ID" = 2169],
					        [#"Returned" = "environments", #"Order ID" = 8090],
					        [#"Returned" = "coat", #"Order ID" = 6803],
					        [#"Returned" = "euro", #"Order ID" = 9619],
					        [#"Returned" = "environments", #"Order ID" = 6406],
					        [#"Returned" = "mary", #"Order ID" = 6277],
					        [#"Returned" = "demand", #"Order ID" = 3234],
					        [#"Returned" = "identifying", #"Order ID" = 6246],
					        [#"Returned" = "dress", #"Order ID" = 6801],
					        [#"Returned" = "nfl", #"Order ID" = 3757],
					        [#"Returned" = "tt", #"Order ID" = 7723],
					        [#"Returned" = "dawn", #"Order ID" = 4796],
					        [#"Returned" = "rom", #"Order ID" = 8509],
					        [#"Returned" = "determined", #"Order ID" = 3828],
					        [#"Returned" = "determination", #"Order ID" = 7047],
					        [#"Returned" = "wilson", #"Order ID" = 8944],
					        [#"Returned" = "intelligence", #"Order ID" = 8917],
					        [#"Returned" = "men", #"Order ID" = 6397],
					        [#"Returned" = "desk", #"Order ID" = 8762],
					        [#"Returned" = "framework", #"Order ID" = 6437],
					        [#"Returned" = "pot", #"Order ID" = 4351],
					        [#"Returned" = "victims", #"Order ID" = 6623],
					        [#"Returned" = "apparel", #"Order ID" = 1780],
					        [#"Returned" = "exists", #"Order ID" = 1463],
					        [#"Returned" = "discharge", #"Order ID" = 8732],
					        [#"Returned" = "solve", #"Order ID" = 2378],
					        [#"Returned" = "ec", #"Order ID" = 5682],
					        [#"Returned" = "anderson", #"Order ID" = 2732],
					        [#"Returned" = "some", #"Order ID" = 9770],
					        [#"Returned" = "flexible", #"Order ID" = 2522],
					        [#"Returned" = "business", #"Order ID" = 9944],
					        [#"Returned" = "slowly", #"Order ID" = 8300],
					        [#"Returned" = "arrangements", #"Order ID" = 7080],
					        [#"Returned" = "criminal", #"Order ID" = 3300],
					        [#"Returned" = "tracks", #"Order ID" = 3753],
					        [#"Returned" = "future", #"Order ID" = 8206],
					        [#"Returned" = "designs", #"Order ID" = 8551],
					        [#"Returned" = "trials", #"Order ID" = 9273],
					        [#"Returned" = "constraints", #"Order ID" = 1543],
					        [#"Returned" = "international", #"Order ID" = 5890],
					        [#"Returned" = "parks", #"Order ID" = 5837],
					        [#"Returned" = "admin", #"Order ID" = 2371],
					        [#"Returned" = "track", #"Order ID" = 5757],
					        [#"Returned" = "websites", #"Order ID" = 2075],
					        [#"Returned" = "rear", #"Order ID" = 4426],
					        [#"Returned" = "plane", #"Order ID" = 7240],
					        [#"Returned" = "genuine", #"Order ID" = 4291],
					        [#"Returned" = "folk", #"Order ID" = 7803],
					        [#"Returned" = "solve", #"Order ID" = 9855],
					        [#"Returned" = "flexibility", #"Order ID" = 5833],
					        [#"Returned" = "friend", #"Order ID" = 5385],
					        [#"Returned" = "challenges", #"Order ID" = 6147],
					        [#"Returned" = "nw", #"Order ID" = 9325],
					        [#"Returned" = "authority", #"Order ID" = 5884],
					        [#"Returned" = "revenues", #"Order ID" = 4679],
					        [#"Returned" = "boost", #"Order ID" = 7467],
					        [#"Returned" = "named", #"Order ID" = 5799],
					        [#"Returned" = "zoo", #"Order ID" = 4973],
					        [#"Returned" = "dc", #"Order ID" = 3485],
					        [#"Returned" = "ultimately", #"Order ID" = 4258],
					        [#"Returned" = "applying", #"Order ID" = 8316],
					        [#"Returned" = "providing", #"Order ID" = 4287],
					        [#"Returned" = "fine", #"Order ID" = 3257],
					        [#"Returned" = "shadow", #"Order ID" = 9625],
					        [#"Returned" = "cinema", #"Order ID" = 1756],
					        [#"Returned" = "virtual", #"Order ID" = 7420],
					        [#"Returned" = "band", #"Order ID" = 3244],
					        [#"Returned" = "per", #"Order ID" = 7376],
					        [#"Returned" = "professional", #"Order ID" = 7855],
					        [#"Returned" = "improve", #"Order ID" = 5986],
					        [#"Returned" = "dollar", #"Order ID" = 6735],
					        [#"Returned" = "austin", #"Order ID" = 7400],
					        [#"Returned" = "amended", #"Order ID" = 2255],
					        [#"Returned" = "exchange", #"Order ID" = 4203],
					        [#"Returned" = "consultation", #"Order ID" = 2733],
					        [#"Returned" = "missouri", #"Order ID" = 4061],
					        [#"Returned" = "rankings", #"Order ID" = 7360],
					        [#"Returned" = "report", #"Order ID" = 3684],
					        [#"Returned" = "percentage", #"Order ID" = 9452],
					        [#"Returned" = "weekly", #"Order ID" = 8319],
					        [#"Returned" = "targets", #"Order ID" = 8896],
					        [#"Returned" = "studied", #"Order ID" = 6866],
					        [#"Returned" = "beginning", #"Order ID" = 6364],
					        [#"Returned" = "diversity", #"Order ID" = 9012],
					        [#"Returned" = "reading", #"Order ID" = 7025],
					        [#"Returned" = "approximately", #"Order ID" = 4675],
					        [#"Returned" = "blocks", #"Order ID" = 8556],
					        [#"Returned" = "armed", #"Order ID" = 5341],
					        [#"Returned" = "sign", #"Order ID" = 7784],
					        [#"Returned" = "themselves", #"Order ID" = 5402],
					        [#"Returned" = "kingdom", #"Order ID" = 8913],
					        [#"Returned" = "attitude", #"Order ID" = 8917],
					        [#"Returned" = "bass", #"Order ID" = 8183],
					        [#"Returned" = "holidays", #"Order ID" = 4725],
					        [#"Returned" = "ethnic", #"Order ID" = 5898],
					        [#"Returned" = "linear", #"Order ID" = 4237],
					        [#"Returned" = "identification", #"Order ID" = 4387],
					        [#"Returned" = "anniversary", #"Order ID" = 8226],
					        [#"Returned" = "sporting", #"Order ID" = 7331],
					        [#"Returned" = "interpretation", #"Order ID" = 7828],
					        [#"Returned" = "largely", #"Order ID" = 7385],
					        [#"Returned" = "taught", #"Order ID" = 3044],
					        [#"Returned" = "winner", #"Order ID" = 9139],
					        [#"Returned" = "sh", #"Order ID" = 8607],
					        [#"Returned" = "facing", #"Order ID" = 2413],
					        [#"Returned" = "well", #"Order ID" = 3441],
					        [#"Returned" = "display", #"Order ID" = 9836],
					        [#"Returned" = "youth", #"Order ID" = 5377],
					        [#"Returned" = "ethernet", #"Order ID" = 2717],
					        [#"Returned" = "austin", #"Order ID" = 2509],
					        [#"Returned" = "sharp", #"Order ID" = 3657],
					        [#"Returned" = "reviews", #"Order ID" = 4772],
					        [#"Returned" = "product", #"Order ID" = 8420],
					        [#"Returned" = "cache", #"Order ID" = 7291],
					        [#"Returned" = "chi", #"Order ID" = 9555],
					        [#"Returned" = "rental", #"Order ID" = 9790],
					        [#"Returned" = "directly", #"Order ID" = 8518],
					        [#"Returned" = "married", #"Order ID" = 8632],
					        [#"Returned" = "stable", #"Order ID" = 8082],
					        [#"Returned" = "bt", #"Order ID" = 2660],
					        [#"Returned" = "florist", #"Order ID" = 4227],
					        [#"Returned" = "cloudy", #"Order ID" = 1871],
					        [#"Returned" = "florist", #"Order ID" = 8139],
					        [#"Returned" = "upon", #"Order ID" = 6421],
					        [#"Returned" = "educational", #"Order ID" = 8067],
					        [#"Returned" = "rocky", #"Order ID" = 5168],
					        [#"Returned" = "soft", #"Order ID" = 8815],
					        [#"Returned" = "jam", #"Order ID" = 3191],
					        [#"Returned" = "can", #"Order ID" = 6481],
					        [#"Returned" = "employment", #"Order ID" = 1487],
					        [#"Returned" = "ads", #"Order ID" = 9209],
					        [#"Returned" = "because", #"Order ID" = 8537],
					        [#"Returned" = "dogs", #"Order ID" = 6830],
					        [#"Returned" = "teachers", #"Order ID" = 7579],
					        [#"Returned" = "vehicle", #"Order ID" = 4873],
					        [#"Returned" = "donations", #"Order ID" = 3089],
					        [#"Returned" = "receiving", #"Order ID" = 6121],
					        [#"Returned" = "ba", #"Order ID" = 1589],
					        [#"Returned" = "june", #"Order ID" = 2879],
					        [#"Returned" = "log", #"Order ID" = 2241],
					        [#"Returned" = "were", #"Order ID" = 2378],
					        [#"Returned" = "franchise", #"Order ID" = 5856],
					        [#"Returned" = "ends", #"Order ID" = 9238],
					        [#"Returned" = "successful", #"Order ID" = 6866],
					        [#"Returned" = "juvenile", #"Order ID" = 9972],
					        [#"Returned" = "watch", #"Order ID" = 6754],
					        [#"Returned" = "frame", #"Order ID" = 4525],
					        [#"Returned" = "famous", #"Order ID" = 6544],
					        [#"Returned" = "adjustment", #"Order ID" = 3170],
					        [#"Returned" = "media", #"Order ID" = 5432],
					        [#"Returned" = "consult", #"Order ID" = 1289],
					        [#"Returned" = "learned", #"Order ID" = 6397],
					        [#"Returned" = "fully", #"Order ID" = 8964],
					        [#"Returned" = "athletics", #"Order ID" = 2057],
					        [#"Returned" = "counter", #"Order ID" = 6708],
					        [#"Returned" = "featured", #"Order ID" = 5905],
					        [#"Returned" = "labor", #"Order ID" = 3809],
					        [#"Returned" = "senior", #"Order ID" = 6597],
					        [#"Returned" = "you", #"Order ID" = 5609],
					        [#"Returned" = "dollars", #"Order ID" = 3777],
					        [#"Returned" = "reader", #"Order ID" = 2950],
					        [#"Returned" = "shock", #"Order ID" = 4708],
					        [#"Returned" = "random", #"Order ID" = 6050],
					        [#"Returned" = "rivers", #"Order ID" = 4422],
					        [#"Returned" = "stood", #"Order ID" = 7232],
					        [#"Returned" = "tell", #"Order ID" = 7026],
					        [#"Returned" = "hiv", #"Order ID" = 9608],
					        [#"Returned" = "jordan", #"Order ID" = 5910],
					        [#"Returned" = "rock", #"Order ID" = 2734],
					        [#"Returned" = "refer", #"Order ID" = 7210],
					        [#"Returned" = "economics", #"Order ID" = 3360],
					        [#"Returned" = "than", #"Order ID" = 5157],
					        [#"Returned" = "calendars", #"Order ID" = 5581],
					        [#"Returned" = "killing", #"Order ID" = 2863],
					        [#"Returned" = "families", #"Order ID" = 7414],
					        [#"Returned" = "august", #"Order ID" = 7366],
					        [#"Returned" = "indicates", #"Order ID" = 8347],
					        [#"Returned" = "controller", #"Order ID" = 7739],
					        [#"Returned" = "anyone", #"Order ID" = 1871],
					        [#"Returned" = "officials", #"Order ID" = 7918],
					        [#"Returned" = "municipal", #"Order ID" = 9764],
					        [#"Returned" = "issue", #"Order ID" = 3238],
					        [#"Returned" = "interfaces", #"Order ID" = 8553],
					        [#"Returned" = "row", #"Order ID" = 2041],
					        [#"Returned" = "hp", #"Order ID" = 4779],
					        [#"Returned" = "marine", #"Order ID" = 4683],
					        [#"Returned" = "australia", #"Order ID" = 4416],
					        [#"Returned" = "combine", #"Order ID" = 5714],
					        [#"Returned" = "columbus", #"Order ID" = 9762],
					        [#"Returned" = "questions", #"Order ID" = 3366],
					        [#"Returned" = "shower", #"Order ID" = 6905],
					        [#"Returned" = "product", #"Order ID" = 6955],
					        [#"Returned" = "ireland", #"Order ID" = 3635],
					        [#"Returned" = "manual", #"Order ID" = 4802],
					        [#"Returned" = "outdoor", #"Order ID" = 8959],
					        [#"Returned" = "responsibilities", #"Order ID" = 7607],
					        [#"Returned" = "verzeichnis", #"Order ID" = 6355],
					        [#"Returned" = "turned", #"Order ID" = 5196],
					        [#"Returned" = "sharon", #"Order ID" = 4036],
					        [#"Returned" = "spending", #"Order ID" = 6761],
					        [#"Returned" = "clip", #"Order ID" = 1165],
					        [#"Returned" = "louis", #"Order ID" = 3843],
					        [#"Returned" = "two", #"Order ID" = 1351],
					        [#"Returned" = "biological", #"Order ID" = 7096],
					        [#"Returned" = "pc", #"Order ID" = 1142],
					        [#"Returned" = "abuse", #"Order ID" = 2499],
					        [#"Returned" = "expert", #"Order ID" = 3350],
					        [#"Returned" = "raw", #"Order ID" = 6782],
					        [#"Returned" = "accounts", #"Order ID" = 4768],
					        [#"Returned" = "mood", #"Order ID" = 2082],
					        [#"Returned" = "vector", #"Order ID" = 3597],
					        [#"Returned" = "oral", #"Order ID" = 6685],
					        [#"Returned" = "noted", #"Order ID" = 1359],
					        [#"Returned" = "full", #"Order ID" = 8746],
					        [#"Returned" = "wear", #"Order ID" = 5559],
					        [#"Returned" = "parents", #"Order ID" = 9288],
					        [#"Returned" = "recipe", #"Order ID" = 1549],
					        [#"Returned" = "relief", #"Order ID" = 5755],
					        [#"Returned" = "rd", #"Order ID" = 8961],
					        [#"Returned" = "yard", #"Order ID" = 6195],
					        [#"Returned" = "putting", #"Order ID" = 7439],
					        [#"Returned" = "layer", #"Order ID" = 7025],
					        [#"Returned" = "stores", #"Order ID" = 8716],
					        [#"Returned" = "ms", #"Order ID" = 1225],
					        [#"Returned" = "providing", #"Order ID" = 8788],
					        [#"Returned" = "babe", #"Order ID" = 1407],
					        [#"Returned" = "spears", #"Order ID" = 5038],
					        [#"Returned" = "korean", #"Order ID" = 7787],
					        [#"Returned" = "compare", #"Order ID" = 5323],
					        [#"Returned" = "seemed", #"Order ID" = 2728],
					        [#"Returned" = "class", #"Order ID" = 1972],
					        [#"Returned" = "pain", #"Order ID" = 5711],
					        [#"Returned" = "os", #"Order ID" = 7125],
					        [#"Returned" = "firm", #"Order ID" = 3252],
					        [#"Returned" = "engineer", #"Order ID" = 7319],
					        [#"Returned" = "properties", #"Order ID" = 1098],
					        [#"Returned" = "establish", #"Order ID" = 7226],
					        [#"Returned" = "unknown", #"Order ID" = 3412],
					        [#"Returned" = "mill", #"Order ID" = 9281],
					        [#"Returned" = "gamma", #"Order ID" = 3613],
					        [#"Returned" = "examination", #"Order ID" = 5412],
					        [#"Returned" = "ph", #"Order ID" = 2664],
					        [#"Returned" = "mail", #"Order ID" = 1471],
					        [#"Returned" = "noted", #"Order ID" = 4239],
					        [#"Returned" = "heat", #"Order ID" = 3226],
					        [#"Returned" = "sleeve", #"Order ID" = 3931],
					        [#"Returned" = "atom", #"Order ID" = 2225],
					        [#"Returned" = "pcs", #"Order ID" = 9705],
					        [#"Returned" = "benefits", #"Order ID" = 5629],
					        [#"Returned" = "receives", #"Order ID" = 1739],
					        [#"Returned" = "framework", #"Order ID" = 7165],
					        [#"Returned" = "confidential", #"Order ID" = 1938],
					        [#"Returned" = "rank", #"Order ID" = 9960],
					        [#"Returned" = "john", #"Order ID" = 2411],
					        [#"Returned" = "poetry", #"Order ID" = 1408],
					        [#"Returned" = "spin", #"Order ID" = 8712],
					        [#"Returned" = "directories", #"Order ID" = 6455],
					        [#"Returned" = "solid", #"Order ID" = 2009],
					        [#"Returned" = "michael", #"Order ID" = 9979],
					        [#"Returned" = "cached", #"Order ID" = 6639],
					        [#"Returned" = "notebooks", #"Order ID" = 8595],
					        [#"Returned" = "representatives", #"Order ID" = 4867],
					        [#"Returned" = "goes", #"Order ID" = 9498],
					        [#"Returned" = "commands", #"Order ID" = 3542],
					        [#"Returned" = "required", #"Order ID" = 5485],
					        [#"Returned" = "everywhere", #"Order ID" = 8707],
					        [#"Returned" = "wrote", #"Order ID" = 4259],
					        [#"Returned" = "used", #"Order ID" = 4548],
					        [#"Returned" = "cars", #"Order ID" = 6759],
					        [#"Returned" = "implementation", #"Order ID" = 7259],
					        [#"Returned" = "allow", #"Order ID" = 6343],
					        [#"Returned" = "trademark", #"Order ID" = 2343],
					        [#"Returned" = "height", #"Order ID" = 8243],
					        [#"Returned" = "transfers", #"Order ID" = 8590],
					        [#"Returned" = "any", #"Order ID" = 9983],
					        [#"Returned" = "shares", #"Order ID" = 5208],
					        [#"Returned" = "professionals", #"Order ID" = 3177],
					        [#"Returned" = "affect", #"Order ID" = 1424],
					        [#"Returned" = "the", #"Order ID" = 5306],
					        [#"Returned" = "balance", #"Order ID" = 1963],
					        [#"Returned" = "suspension", #"Order ID" = 9537],
					        [#"Returned" = "producing", #"Order ID" = 7612],
					        [#"Returned" = "throat", #"Order ID" = 4659]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Returned", type text},
					        {"Order ID", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table