table 'Orders (Sample - Superstore (1))'
	lineageTag: 5fd60c72-3709-4d29-b6aa-4c500e3052d8

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 1f127772-6832-47c4-927a-621cad5b40ed
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 5a7fcd59-e20d-472a-9f81-47651cc3b206
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: datetime
		lineageTag: a204cf90-11f9-48b5-851f-3ceab3cedfb5
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: datetime
		lineageTag: ccd218cf-da8b-4523-a20f-5702562ae22b
		summarizeBy: none
		sourceColumn: 'Ship Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 513fc61b-8277-4498-86a1-1f2a1aa7a87b
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 9bd0e78c-44d7-428a-8328-bc27be156bb7
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: cad2ee72-8253-4f6e-983d-d9a94775234a
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 1cfcde1e-afa1-4a9d-988e-585cadbd543c
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 79251f6a-3c44-4e61-ac5a-a8db4703a35d
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: de024459-2174-4a10-9f10-63e938cf3fd6
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 6063f289-9bfb-4be3-94ae-f72069b91ff4
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 1f6aba0d-5d29-4824-b993-45de7cd54b7d
		summarizeBy: sum
		sourceColumn: 'Postal Code'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: ad2c369e-1b54-4e84-8367-5de1667b0231
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 1e61b14c-ec21-45b0-a066-ab07dd34eac9
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: e0826ca1-060d-40a3-ba54-2656ec4f525a
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: b70b36b4-c440-4fda-be81-dc1c8ca78299
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 9cfd4c3d-f2c7-4dfb-8c95-ff894b1665b5
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: General Number
		lineageTag: 98025657-c441-4b47-8831-90d22a9b3c76
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 2b5cbdaf-bfb6-4041-ab56-3e1009c40bff
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: General Number
		lineageTag: 4ecb91af-c577-404b-b0f3-4445869a0919
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		formatString: General Number
		lineageTag: 671de2a4-bcf5-437c-945a-3a0600d31256
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Calculation1 = IF('Orders (Sample - Superstore (1))'[Category] = "Furniture", "furniture", IF('Orders (Sample - Superstore (1))'[Category] = "Office Supplies", "office supplier", IF('Orders (Sample - Superstore (1))'[Category] = "Technology", "technology", 'Orders (Sample - Superstore (1))'[Category])))
		lineageTag: 7de8b6e2-40c1-4b02-80bd-a7ec1b312b99
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Orders (Sample - Superstore (1))' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Row ID" = 1055, #"Order ID" = 7878, #"Order Date" = #date(2022, 9, 17), #"Ship Date" = #date(2022, 9, 25), #"Ship Mode" = "170.56.75.156", #"Customer ID" = 2577, #"Customer Name" = "Obdulia Soto", #"Segment" = "government", #"Country" = "Jamaica", #"City" = "Northampton", #"State" = "Georgia", #"Postal Code" = 67, #"Region" = "New Jersey", #"Product ID" = 9199, #"Category" = "flickr", #"Sub-Category" = "alarm", #"Product Name" = "Monty Warren", #"Sales" = 907.55, #"Quantity" = 193, #"Discount" = 98.69, #"Profit" = 245.62],
					        [#"Row ID" = 3376, #"Order ID" = 1670, #"Order Date" = #date(2022, 5, 17), #"Ship Date" = #date(2021, 7, 8), #"Ship Mode" = "125.28.33.109", #"Customer ID" = 9513, #"Customer Name" = "Halina Henson", #"Segment" = "memorabilia", #"Country" = "Bosnia & Herzegovina", #"City" = "Glassboro", #"State" = "Alabama", #"Postal Code" = 779, #"Region" = "Nebraska", #"Product ID" = 3782, #"Category" = "tell", #"Sub-Category" = "electronic", #"Product Name" = "Leonardo Zimmerman", #"Sales" = 841.02, #"Quantity" = 690, #"Discount" = 869.55, #"Profit" = 225.77],
					        [#"Row ID" = 7108, #"Order ID" = 8112, #"Order Date" = #date(2023, 3, 20), #"Ship Date" = #date(2021, 4, 7), #"Ship Mode" = "64.35.31.244", #"Customer ID" = 8702, #"Customer Name" = "Karren Mullins", #"Segment" = "simulation", #"Country" = "Spain", #"City" = "Calumet City", #"State" = "North Carolina", #"Postal Code" = 793, #"Region" = "Texas", #"Product ID" = 2263, #"Category" = "director", #"Sub-Category" = "pottery", #"Product Name" = "Vannessa Callahan", #"Sales" = 465.17, #"Quantity" = 796, #"Discount" = 742.14, #"Profit" = 986.75],
					        [#"Row ID" = 6495, #"Order ID" = 4829, #"Order Date" = #date(2021, 5, 25), #"Ship Date" = #date(2022, 4, 10), #"Ship Mode" = "105.91.78.100", #"Customer ID" = 8161, #"Customer Name" = "Agustin Holder", #"Segment" = "our", #"Country" = "French Polynesia", #"City" = "South Jordan", #"State" = "Arizona", #"Postal Code" = 723, #"Region" = "Nebraska", #"Product ID" = 4451, #"Category" = "eye", #"Sub-Category" = "mine", #"Product Name" = "Jacquelynn Hogan", #"Sales" = 862.43, #"Quantity" = 305, #"Discount" = 846.81, #"Profit" = 95.62],
					        [#"Row ID" = 3056, #"Order ID" = 2237, #"Order Date" = #date(2024, 6, 1), #"Ship Date" = #date(2021, 11, 3), #"Ship Mode" = "198.229.5.174", #"Customer ID" = 3536, #"Customer Name" = "Jacob Fisher", #"Segment" = "eye", #"Country" = "Guatemala", #"City" = "St. Cloud", #"State" = "Missouri", #"Postal Code" = 730, #"Region" = "Ohio", #"Product ID" = 7397, #"Category" = "paintings", #"Sub-Category" = "revised", #"Product Name" = "Sung Moran", #"Sales" = 434.91, #"Quantity" = 219, #"Discount" = 483.03, #"Profit" = 54.75]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Row ID", Int64.Type},
					        {"Order ID", type text},
					        {"Order Date", type date},
					        {"Ship Date", type date},
					        {"Ship Mode", type text},
					        {"Customer ID", type text},
					        {"Customer Name", type text},
					        {"Segment", type text},
					        {"Country", type text},
					        {"City", type text},
					        {"State", type text},
					        {"Postal Code", Int64.Type},
					        {"Region", type text},
					        {"Product ID", type text},
					        {"Category", type text},
					        {"Sub-Category", type text},
					        {"Product Name", type text},
					        {"Sales", type number},
					        {"Quantity", Int64.Type},
					        {"Discount", type number},
					        {"Profit", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table