table 'Orders+ ( Sample - Superstore)_Returns'
	lineageTag: 694f9205-4b12-4114-9cbe-a8e7962b7657

	column Returned
		dataType: string
		lineageTag: 3c4d96d2-4b95-4f40-ae40-15b9b780fd70
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: d244e6aa-dd44-425f-9568-c3e617918105
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	partition 'Orders+ ( Sample - Superstore)_Returns' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Returned" = "earn", #"Order ID" = 9887],
					        [#"Returned" = "interior", #"Order ID" = 3716],
					        [#"Returned" = "ns", #"Order ID" = 7441],
					        [#"Returned" = "compiled", #"Order ID" = 7263],
					        [#"Returned" = "strings", #"Order ID" = 8886],
					        [#"Returned" = "arising", #"Order ID" = 5618],
					        [#"Returned" = "textbooks", #"Order ID" = 7439],
					        [#"Returned" = "topics", #"Order ID" = 6416],
					        [#"Returned" = "reputation", #"Order ID" = 4104],
					        [#"Returned" = "windows", #"Order ID" = 3753],
					        [#"Returned" = "lists", #"Order ID" = 6161],
					        [#"Returned" = "expression", #"Order ID" = 1942],
					        [#"Returned" = "physics", #"Order ID" = 4249],
					        [#"Returned" = "rare", #"Order ID" = 5687],
					        [#"Returned" = "enhance", #"Order ID" = 4100],
					        [#"Returned" = "function", #"Order ID" = 6072],
					        [#"Returned" = "top", #"Order ID" = 6128],
					        [#"Returned" = "packet", #"Order ID" = 9018],
					        [#"Returned" = "school", #"Order ID" = 4705],
					        [#"Returned" = "perspective", #"Order ID" = 3675],
					        [#"Returned" = "ns", #"Order ID" = 2733],
					        [#"Returned" = "ron", #"Order ID" = 6157],
					        [#"Returned" = "rat", #"Order ID" = 9005],
					        [#"Returned" = "dollars", #"Order ID" = 4546],
					        [#"Returned" = "arising", #"Order ID" = 5875],
					        [#"Returned" = "nepal", #"Order ID" = 3857],
					        [#"Returned" = "fr", #"Order ID" = 6800],
					        [#"Returned" = "exam", #"Order ID" = 2468],
					        [#"Returned" = "corn", #"Order ID" = 7013],
					        [#"Returned" = "same", #"Order ID" = 1793],
					        [#"Returned" = "ocean", #"Order ID" = 2596],
					        [#"Returned" = "there", #"Order ID" = 7479],
					        [#"Returned" = "recorder", #"Order ID" = 3595],
					        [#"Returned" = "role", #"Order ID" = 7995],
					        [#"Returned" = "health", #"Order ID" = 4335],
					        [#"Returned" = "modify", #"Order ID" = 7489],
					        [#"Returned" = "winds", #"Order ID" = 4854],
					        [#"Returned" = "speaker", #"Order ID" = 7758],
					        [#"Returned" = "jessica", #"Order ID" = 9460],
					        [#"Returned" = "santa", #"Order ID" = 1456],
					        [#"Returned" = "french", #"Order ID" = 1803],
					        [#"Returned" = "latter", #"Order ID" = 3539],
					        [#"Returned" = "comics", #"Order ID" = 1912],
					        [#"Returned" = "jews", #"Order ID" = 5769],
					        [#"Returned" = "view", #"Order ID" = 5666],
					        [#"Returned" = "cent", #"Order ID" = 7296],
					        [#"Returned" = "ds", #"Order ID" = 4828],
					        [#"Returned" = "some", #"Order ID" = 5858],
					        [#"Returned" = "lol", #"Order ID" = 6754],
					        [#"Returned" = "norton", #"Order ID" = 2849],
					        [#"Returned" = "supporting", #"Order ID" = 1911],
					        [#"Returned" = "police", #"Order ID" = 6245],
					        [#"Returned" = "videos", #"Order ID" = 1054],
					        [#"Returned" = "associations", #"Order ID" = 3121],
					        [#"Returned" = "controller", #"Order ID" = 5536],
					        [#"Returned" = "israel", #"Order ID" = 3129],
					        [#"Returned" = "thousand", #"Order ID" = 6687],
					        [#"Returned" = "lan", #"Order ID" = 5602],
					        [#"Returned" = "lewis", #"Order ID" = 5175],
					        [#"Returned" = "nights", #"Order ID" = 3772],
					        [#"Returned" = "alert", #"Order ID" = 3935],
					        [#"Returned" = "bottle", #"Order ID" = 8395],
					        [#"Returned" = "corp", #"Order ID" = 1550],
					        [#"Returned" = "gratis", #"Order ID" = 8432],
					        [#"Returned" = "printable", #"Order ID" = 9152],
					        [#"Returned" = "rank", #"Order ID" = 2428],
					        [#"Returned" = "feeding", #"Order ID" = 4997],
					        [#"Returned" = "sentence", #"Order ID" = 4132],
					        [#"Returned" = "director", #"Order ID" = 9635],
					        [#"Returned" = "lib", #"Order ID" = 8461],
					        [#"Returned" = "belgium", #"Order ID" = 6385],
					        [#"Returned" = "accessible", #"Order ID" = 7209],
					        [#"Returned" = "campaign", #"Order ID" = 8039],
					        [#"Returned" = "suit", #"Order ID" = 8390],
					        [#"Returned" = "loss", #"Order ID" = 2844],
					        [#"Returned" = "paintings", #"Order ID" = 6517],
					        [#"Returned" = "critical", #"Order ID" = 6377],
					        [#"Returned" = "im", #"Order ID" = 3918],
					        [#"Returned" = "never", #"Order ID" = 5132],
					        [#"Returned" = "gray", #"Order ID" = 7843],
					        [#"Returned" = "willing", #"Order ID" = 2551],
					        [#"Returned" = "goto", #"Order ID" = 4863],
					        [#"Returned" = "metabolism", #"Order ID" = 1597],
					        [#"Returned" = "connected", #"Order ID" = 7997],
					        [#"Returned" = "antenna", #"Order ID" = 9376],
					        [#"Returned" = "lock", #"Order ID" = 2031],
					        [#"Returned" = "trend", #"Order ID" = 7499],
					        [#"Returned" = "target", #"Order ID" = 4361],
					        [#"Returned" = "patch", #"Order ID" = 5623],
					        [#"Returned" = "installing", #"Order ID" = 9401],
					        [#"Returned" = "clear", #"Order ID" = 5535],
					        [#"Returned" = "recommendations", #"Order ID" = 9257],
					        [#"Returned" = "speed", #"Order ID" = 9870],
					        [#"Returned" = "rat", #"Order ID" = 8317],
					        [#"Returned" = "chemicals", #"Order ID" = 4261],
					        [#"Returned" = "republic", #"Order ID" = 3438],
					        [#"Returned" = "comprehensive", #"Order ID" = 8096],
					        [#"Returned" = "flat", #"Order ID" = 8672],
					        [#"Returned" = "nz", #"Order ID" = 1308],
					        [#"Returned" = "bristol", #"Order ID" = 9733],
					        [#"Returned" = "note", #"Order ID" = 8688],
					        [#"Returned" = "welcome", #"Order ID" = 1041],
					        [#"Returned" = "approval", #"Order ID" = 5718],
					        [#"Returned" = "rw", #"Order ID" = 7844],
					        [#"Returned" = "juice", #"Order ID" = 3850],
					        [#"Returned" = "exposed", #"Order ID" = 9975],
					        [#"Returned" = "cup", #"Order ID" = 2980],
					        [#"Returned" = "declared", #"Order ID" = 7310],
					        [#"Returned" = "chat", #"Order ID" = 9054],
					        [#"Returned" = "covering", #"Order ID" = 3049],
					        [#"Returned" = "gray", #"Order ID" = 8696],
					        [#"Returned" = "variable", #"Order ID" = 6565],
					        [#"Returned" = "script", #"Order ID" = 4388],
					        [#"Returned" = "bank", #"Order ID" = 1628],
					        [#"Returned" = "throat", #"Order ID" = 8322],
					        [#"Returned" = "alan", #"Order ID" = 1783],
					        [#"Returned" = "certified", #"Order ID" = 2693],
					        [#"Returned" = "temporary", #"Order ID" = 3885],
					        [#"Returned" = "done", #"Order ID" = 5103],
					        [#"Returned" = "built", #"Order ID" = 1882],
					        [#"Returned" = "origin", #"Order ID" = 1348],
					        [#"Returned" = "vehicles", #"Order ID" = 6206],
					        [#"Returned" = "thru", #"Order ID" = 5909],
					        [#"Returned" = "entries", #"Order ID" = 1392],
					        [#"Returned" = "territory", #"Order ID" = 5237],
					        [#"Returned" = "deposit", #"Order ID" = 8223],
					        [#"Returned" = "investigation", #"Order ID" = 6074],
					        [#"Returned" = "disk", #"Order ID" = 5701],
					        [#"Returned" = "divided", #"Order ID" = 2683],
					        [#"Returned" = "lots", #"Order ID" = 9223],
					        [#"Returned" = "pp", #"Order ID" = 7106],
					        [#"Returned" = "logical", #"Order ID" = 1751],
					        [#"Returned" = "whole", #"Order ID" = 5443],
					        [#"Returned" = "alerts", #"Order ID" = 7373],
					        [#"Returned" = "mean", #"Order ID" = 4321],
					        [#"Returned" = "ahead", #"Order ID" = 2500],
					        [#"Returned" = "muslim", #"Order ID" = 2486],
					        [#"Returned" = "india", #"Order ID" = 5633],
					        [#"Returned" = "additions", #"Order ID" = 4623],
					        [#"Returned" = "mar", #"Order ID" = 1554],
					        [#"Returned" = "direction", #"Order ID" = 4363],
					        [#"Returned" = "repeat", #"Order ID" = 4817],
					        [#"Returned" = "import", #"Order ID" = 7538],
					        [#"Returned" = "alliance", #"Order ID" = 2906],
					        [#"Returned" = "ebony", #"Order ID" = 4327],
					        [#"Returned" = "times", #"Order ID" = 6399],
					        [#"Returned" = "disaster", #"Order ID" = 6613],
					        [#"Returned" = "lookup", #"Order ID" = 7070],
					        [#"Returned" = "mexican", #"Order ID" = 4490],
					        [#"Returned" = "solve", #"Order ID" = 3429],
					        [#"Returned" = "billion", #"Order ID" = 2521],
					        [#"Returned" = "currently", #"Order ID" = 6393],
					        [#"Returned" = "impact", #"Order ID" = 6507],
					        [#"Returned" = "waste", #"Order ID" = 2829],
					        [#"Returned" = "distributor", #"Order ID" = 7922],
					        [#"Returned" = "earnings", #"Order ID" = 1036],
					        [#"Returned" = "highlight", #"Order ID" = 4401],
					        [#"Returned" = "birth", #"Order ID" = 5711],
					        [#"Returned" = "ds", #"Order ID" = 3809],
					        [#"Returned" = "forgot", #"Order ID" = 7321],
					        [#"Returned" = "example", #"Order ID" = 3616],
					        [#"Returned" = "bidder", #"Order ID" = 5553],
					        [#"Returned" = "cuba", #"Order ID" = 7127],
					        [#"Returned" = "preliminary", #"Order ID" = 4878],
					        [#"Returned" = "lives", #"Order ID" = 1630],
					        [#"Returned" = "pa", #"Order ID" = 5777],
					        [#"Returned" = "wales", #"Order ID" = 3762],
					        [#"Returned" = "comes", #"Order ID" = 5791],
					        [#"Returned" = "wing", #"Order ID" = 7999],
					        [#"Returned" = "shock", #"Order ID" = 9345],
					        [#"Returned" = "planner", #"Order ID" = 7634],
					        [#"Returned" = "drivers", #"Order ID" = 6585],
					        [#"Returned" = "eating", #"Order ID" = 3544],
					        [#"Returned" = "minimum", #"Order ID" = 6822],
					        [#"Returned" = "gave", #"Order ID" = 3808],
					        [#"Returned" = "designs", #"Order ID" = 7827],
					        [#"Returned" = "request", #"Order ID" = 8150],
					        [#"Returned" = "rpm", #"Order ID" = 5070],
					        [#"Returned" = "differences", #"Order ID" = 7210],
					        [#"Returned" = "accommodation", #"Order ID" = 7329],
					        [#"Returned" = "dragon", #"Order ID" = 9080],
					        [#"Returned" = "reason", #"Order ID" = 9661],
					        [#"Returned" = "thu", #"Order ID" = 2006],
					        [#"Returned" = "connector", #"Order ID" = 8984],
					        [#"Returned" = "author", #"Order ID" = 8623],
					        [#"Returned" = "public", #"Order ID" = 1678],
					        [#"Returned" = "fr", #"Order ID" = 4552],
					        [#"Returned" = "payment", #"Order ID" = 1847],
					        [#"Returned" = "submitted", #"Order ID" = 5408],
					        [#"Returned" = "inspection", #"Order ID" = 5967],
					        [#"Returned" = "avg", #"Order ID" = 1335],
					        [#"Returned" = "famous", #"Order ID" = 7915],
					        [#"Returned" = "micro", #"Order ID" = 2593],
					        [#"Returned" = "grass", #"Order ID" = 8797],
					        [#"Returned" = "receiver", #"Order ID" = 1648],
					        [#"Returned" = "students", #"Order ID" = 4942],
					        [#"Returned" = "cases", #"Order ID" = 6741],
					        [#"Returned" = "limousines", #"Order ID" = 5007],
					        [#"Returned" = "que", #"Order ID" = 7752],
					        [#"Returned" = "climate", #"Order ID" = 6814],
					        [#"Returned" = "memorabilia", #"Order ID" = 5857],
					        [#"Returned" = "cleaner", #"Order ID" = 7063],
					        [#"Returned" = "publishers", #"Order ID" = 8946],
					        [#"Returned" = "expressed", #"Order ID" = 5332],
					        [#"Returned" = "tip", #"Order ID" = 7764],
					        [#"Returned" = "exhibition", #"Order ID" = 7119],
					        [#"Returned" = "afghanistan", #"Order ID" = 4415],
					        [#"Returned" = "commit", #"Order ID" = 6247],
					        [#"Returned" = "mountains", #"Order ID" = 1415],
					        [#"Returned" = "spirit", #"Order ID" = 2556],
					        [#"Returned" = "labels", #"Order ID" = 8031],
					        [#"Returned" = "resume", #"Order ID" = 2327],
					        [#"Returned" = "rivers", #"Order ID" = 1126],
					        [#"Returned" = "cinema", #"Order ID" = 4220],
					        [#"Returned" = "machine", #"Order ID" = 2383],
					        [#"Returned" = "universal", #"Order ID" = 2573],
					        [#"Returned" = "displaying", #"Order ID" = 7516],
					        [#"Returned" = "trademark", #"Order ID" = 4293],
					        [#"Returned" = "logic", #"Order ID" = 3411],
					        [#"Returned" = "chevrolet", #"Order ID" = 2322],
					        [#"Returned" = "biography", #"Order ID" = 6064],
					        [#"Returned" = "grace", #"Order ID" = 1250],
					        [#"Returned" = "need", #"Order ID" = 9212],
					        [#"Returned" = "kingdom", #"Order ID" = 9163],
					        [#"Returned" = "fluid", #"Order ID" = 4652],
					        [#"Returned" = "iraq", #"Order ID" = 4859],
					        [#"Returned" = "types", #"Order ID" = 1817],
					        [#"Returned" = "know", #"Order ID" = 1347],
					        [#"Returned" = "friends", #"Order ID" = 2395],
					        [#"Returned" = "federal", #"Order ID" = 4285],
					        [#"Returned" = "configuration", #"Order ID" = 4148],
					        [#"Returned" = "im", #"Order ID" = 2800],
					        [#"Returned" = "hazardous", #"Order ID" = 3688],
					        [#"Returned" = "specifically", #"Order ID" = 4278],
					        [#"Returned" = "where", #"Order ID" = 2819],
					        [#"Returned" = "committed", #"Order ID" = 1958],
					        [#"Returned" = "jewellery", #"Order ID" = 2393],
					        [#"Returned" = "sm", #"Order ID" = 4823],
					        [#"Returned" = "walk", #"Order ID" = 6604],
					        [#"Returned" = "select", #"Order ID" = 6487],
					        [#"Returned" = "exhibit", #"Order ID" = 7665],
					        [#"Returned" = "ask", #"Order ID" = 5824],
					        [#"Returned" = "zus", #"Order ID" = 8306],
					        [#"Returned" = "centers", #"Order ID" = 4090],
					        [#"Returned" = "wrote", #"Order ID" = 3712],
					        [#"Returned" = "untitled", #"Order ID" = 4472],
					        [#"Returned" = "meat", #"Order ID" = 9294],
					        [#"Returned" = "discussed", #"Order ID" = 7896],
					        [#"Returned" = "myself", #"Order ID" = 7552],
					        [#"Returned" = "plan", #"Order ID" = 5252],
					        [#"Returned" = "ice", #"Order ID" = 1175],
					        [#"Returned" = "cited", #"Order ID" = 7986],
					        [#"Returned" = "auto", #"Order ID" = 8976],
					        [#"Returned" = "coming", #"Order ID" = 2596],
					        [#"Returned" = "people", #"Order ID" = 1808],
					        [#"Returned" = "html", #"Order ID" = 3720],
					        [#"Returned" = "were", #"Order ID" = 4512],
					        [#"Returned" = "command", #"Order ID" = 3119],
					        [#"Returned" = "can", #"Order ID" = 9559],
					        [#"Returned" = "story", #"Order ID" = 3925],
					        [#"Returned" = "condition", #"Order ID" = 1368],
					        [#"Returned" = "vietnam", #"Order ID" = 6720],
					        [#"Returned" = "permits", #"Order ID" = 3489],
					        [#"Returned" = "hospitals", #"Order ID" = 3714],
					        [#"Returned" = "relative", #"Order ID" = 7081],
					        [#"Returned" = "mention", #"Order ID" = 1786],
					        [#"Returned" = "womens", #"Order ID" = 7631],
					        [#"Returned" = "cap", #"Order ID" = 7913],
					        [#"Returned" = "powder", #"Order ID" = 8442],
					        [#"Returned" = "amazing", #"Order ID" = 1764],
					        [#"Returned" = "instead", #"Order ID" = 4717],
					        [#"Returned" = "emissions", #"Order ID" = 5398],
					        [#"Returned" = "wars", #"Order ID" = 3228],
					        [#"Returned" = "desk", #"Order ID" = 4316],
					        [#"Returned" = "transferred", #"Order ID" = 3090],
					        [#"Returned" = "detected", #"Order ID" = 5387],
					        [#"Returned" = "increasingly", #"Order ID" = 7218],
					        [#"Returned" = "feb", #"Order ID" = 6838],
					        [#"Returned" = "feel", #"Order ID" = 4131],
					        [#"Returned" = "members", #"Order ID" = 2670],
					        [#"Returned" = "increasingly", #"Order ID" = 8626],
					        [#"Returned" = "liked", #"Order ID" = 9033],
					        [#"Returned" = "defined", #"Order ID" = 8356],
					        [#"Returned" = "accounts", #"Order ID" = 5640],
					        [#"Returned" = "examined", #"Order ID" = 9589],
					        [#"Returned" = "provisions", #"Order ID" = 5359],
					        [#"Returned" = "suspension", #"Order ID" = 7328],
					        [#"Returned" = "raise", #"Order ID" = 7882],
					        [#"Returned" = "cooking", #"Order ID" = 9432],
					        [#"Returned" = "logical", #"Order ID" = 7620],
					        [#"Returned" = "majority", #"Order ID" = 9836],
					        [#"Returned" = "goto", #"Order ID" = 3003],
					        [#"Returned" = "partners", #"Order ID" = 6925],
					        [#"Returned" = "allow", #"Order ID" = 5821],
					        [#"Returned" = "eligibility", #"Order ID" = 2889],
					        [#"Returned" = "suggested", #"Order ID" = 2321],
					        [#"Returned" = "thou", #"Order ID" = 6582],
					        [#"Returned" = "narrow", #"Order ID" = 2571],
					        [#"Returned" = "headquarters", #"Order ID" = 5413],
					        [#"Returned" = "mid", #"Order ID" = 9906],
					        [#"Returned" = "availability", #"Order ID" = 1057],
					        [#"Returned" = "subscription", #"Order ID" = 7356],
					        [#"Returned" = "convention", #"Order ID" = 9461],
					        [#"Returned" = "sony", #"Order ID" = 1788],
					        [#"Returned" = "assurance", #"Order ID" = 1784],
					        [#"Returned" = "religion", #"Order ID" = 9794],
					        [#"Returned" = "dawn", #"Order ID" = 1287],
					        [#"Returned" = "honor", #"Order ID" = 5191],
					        [#"Returned" = "psp", #"Order ID" = 5407],
					        [#"Returned" = "hate", #"Order ID" = 3978],
					        [#"Returned" = "ice", #"Order ID" = 2775],
					        [#"Returned" = "difficulty", #"Order ID" = 4744],
					        [#"Returned" = "jump", #"Order ID" = 2066],
					        [#"Returned" = "er", #"Order ID" = 5158],
					        [#"Returned" = "children", #"Order ID" = 5168],
					        [#"Returned" = "packet", #"Order ID" = 3650],
					        [#"Returned" = "bt", #"Order ID" = 7404],
					        [#"Returned" = "yard", #"Order ID" = 1837],
					        [#"Returned" = "protection", #"Order ID" = 1807],
					        [#"Returned" = "rugby", #"Order ID" = 4961],
					        [#"Returned" = "exchange", #"Order ID" = 8335],
					        [#"Returned" = "cape", #"Order ID" = 2051],
					        [#"Returned" = "usb", #"Order ID" = 1509],
					        [#"Returned" = "parker", #"Order ID" = 4474],
					        [#"Returned" = "consideration", #"Order ID" = 5452],
					        [#"Returned" = "opposite", #"Order ID" = 3141],
					        [#"Returned" = "specialty", #"Order ID" = 6733],
					        [#"Returned" = "sustainable", #"Order ID" = 3616],
					        [#"Returned" = "guinea", #"Order ID" = 7349],
					        [#"Returned" = "lunch", #"Order ID" = 2902],
					        [#"Returned" = "alpha", #"Order ID" = 8671],
					        [#"Returned" = "toll", #"Order ID" = 1949],
					        [#"Returned" = "donate", #"Order ID" = 1322],
					        [#"Returned" = "radar", #"Order ID" = 8869],
					        [#"Returned" = "muslim", #"Order ID" = 3934],
					        [#"Returned" = "keith", #"Order ID" = 3001],
					        [#"Returned" = "rooms", #"Order ID" = 1010],
					        [#"Returned" = "surrounding", #"Order ID" = 7090],
					        [#"Returned" = "maybe", #"Order ID" = 9199],
					        [#"Returned" = "gcc", #"Order ID" = 3233],
					        [#"Returned" = "occur", #"Order ID" = 5944],
					        [#"Returned" = "commitment", #"Order ID" = 6499],
					        [#"Returned" = "amendments", #"Order ID" = 3435],
					        [#"Returned" = "pour", #"Order ID" = 1094],
					        [#"Returned" = "holder", #"Order ID" = 4611],
					        [#"Returned" = "song", #"Order ID" = 9089],
					        [#"Returned" = "clause", #"Order ID" = 2708],
					        [#"Returned" = "bugs", #"Order ID" = 9591],
					        [#"Returned" = "phones", #"Order ID" = 4727],
					        [#"Returned" = "fits", #"Order ID" = 6086],
					        [#"Returned" = "truck", #"Order ID" = 5293],
					        [#"Returned" = "basket", #"Order ID" = 6505],
					        [#"Returned" = "applications", #"Order ID" = 7558],
					        [#"Returned" = "pioneer", #"Order ID" = 7151],
					        [#"Returned" = "forecast", #"Order ID" = 1192],
					        [#"Returned" = "claim", #"Order ID" = 6627],
					        [#"Returned" = "hundred", #"Order ID" = 7605],
					        [#"Returned" = "heating", #"Order ID" = 3925],
					        [#"Returned" = "iowa", #"Order ID" = 3970],
					        [#"Returned" = "launched", #"Order ID" = 4361],
					        [#"Returned" = "plasma", #"Order ID" = 4785],
					        [#"Returned" = "stages", #"Order ID" = 5163],
					        [#"Returned" = "funded", #"Order ID" = 3951],
					        [#"Returned" = "alarm", #"Order ID" = 7602],
					        [#"Returned" = "massage", #"Order ID" = 2730],
					        [#"Returned" = "export", #"Order ID" = 4635],
					        [#"Returned" = "disclaimer", #"Order ID" = 9530],
					        [#"Returned" = "oil", #"Order ID" = 9048],
					        [#"Returned" = "howard", #"Order ID" = 5913],
					        [#"Returned" = "delta", #"Order ID" = 9733],
					        [#"Returned" = "lisa", #"Order ID" = 8276],
					        [#"Returned" = "happens", #"Order ID" = 4069],
					        [#"Returned" = "bath", #"Order ID" = 4385],
					        [#"Returned" = "critical", #"Order ID" = 8814],
					        [#"Returned" = "mt", #"Order ID" = 1266],
					        [#"Returned" = "wed", #"Order ID" = 8408],
					        [#"Returned" = "nodes", #"Order ID" = 9360],
					        [#"Returned" = "recorder", #"Order ID" = 3554],
					        [#"Returned" = "ill", #"Order ID" = 8687],
					        [#"Returned" = "aka", #"Order ID" = 5529],
					        [#"Returned" = "newsletter", #"Order ID" = 7236],
					        [#"Returned" = "judicial", #"Order ID" = 4444],
					        [#"Returned" = "being", #"Order ID" = 6537],
					        [#"Returned" = "housewares", #"Order ID" = 4844],
					        [#"Returned" = "plants", #"Order ID" = 1114],
					        [#"Returned" = "color", #"Order ID" = 9572],
					        [#"Returned" = "mp", #"Order ID" = 6934],
					        [#"Returned" = "searching", #"Order ID" = 4384],
					        [#"Returned" = "regardless", #"Order ID" = 8275],
					        [#"Returned" = "solve", #"Order ID" = 8743],
					        [#"Returned" = "executive", #"Order ID" = 4914],
					        [#"Returned" = "mon", #"Order ID" = 7189],
					        [#"Returned" = "treat", #"Order ID" = 2768],
					        [#"Returned" = "plasma", #"Order ID" = 5081],
					        [#"Returned" = "difference", #"Order ID" = 2131],
					        [#"Returned" = "brief", #"Order ID" = 6009],
					        [#"Returned" = "sight", #"Order ID" = 3069],
					        [#"Returned" = "emissions", #"Order ID" = 2019],
					        [#"Returned" = "airlines", #"Order ID" = 9489],
					        [#"Returned" = "correctly", #"Order ID" = 8542],
					        [#"Returned" = "mode", #"Order ID" = 8657],
					        [#"Returned" = "position", #"Order ID" = 8028],
					        [#"Returned" = "unusual", #"Order ID" = 6490],
					        [#"Returned" = "along", #"Order ID" = 7258],
					        [#"Returned" = "globe", #"Order ID" = 9596],
					        [#"Returned" = "hiking", #"Order ID" = 4825],
					        [#"Returned" = "portland", #"Order ID" = 1024],
					        [#"Returned" = "heavy", #"Order ID" = 9952],
					        [#"Returned" = "regularly", #"Order ID" = 5284],
					        [#"Returned" = "movie", #"Order ID" = 2870],
					        [#"Returned" = "pot", #"Order ID" = 9331],
					        [#"Returned" = "none", #"Order ID" = 8455],
					        [#"Returned" = "closely", #"Order ID" = 4775],
					        [#"Returned" = "motion", #"Order ID" = 8252],
					        [#"Returned" = "enemy", #"Order ID" = 9986],
					        [#"Returned" = "achieve", #"Order ID" = 4396],
					        [#"Returned" = "furthermore", #"Order ID" = 5883],
					        [#"Returned" = "with", #"Order ID" = 9783],
					        [#"Returned" = "mind", #"Order ID" = 7245],
					        [#"Returned" = "japanese", #"Order ID" = 2236],
					        [#"Returned" = "variety", #"Order ID" = 3815],
					        [#"Returned" = "destinations", #"Order ID" = 1381],
					        [#"Returned" = "train", #"Order ID" = 2567],
					        [#"Returned" = "amy", #"Order ID" = 1822],
					        [#"Returned" = "award", #"Order ID" = 9324],
					        [#"Returned" = "resume", #"Order ID" = 4221],
					        [#"Returned" = "province", #"Order ID" = 7621],
					        [#"Returned" = "ideas", #"Order ID" = 6838],
					        [#"Returned" = "dynamic", #"Order ID" = 6791],
					        [#"Returned" = "cooperative", #"Order ID" = 1276],
					        [#"Returned" = "actors", #"Order ID" = 3780],
					        [#"Returned" = "disaster", #"Order ID" = 2134],
					        [#"Returned" = "mayor", #"Order ID" = 5125],
					        [#"Returned" = "houston", #"Order ID" = 5222],
					        [#"Returned" = "township", #"Order ID" = 8544],
					        [#"Returned" = "el", #"Order ID" = 1858],
					        [#"Returned" = "buyers", #"Order ID" = 3823],
					        [#"Returned" = "regular", #"Order ID" = 1948],
					        [#"Returned" = "miscellaneous", #"Order ID" = 1880],
					        [#"Returned" = "lo", #"Order ID" = 7616],
					        [#"Returned" = "framework", #"Order ID" = 9802],
					        [#"Returned" = "died", #"Order ID" = 9784],
					        [#"Returned" = "pine", #"Order ID" = 4953],
					        [#"Returned" = "runs", #"Order ID" = 7849],
					        [#"Returned" = "workshop", #"Order ID" = 8072],
					        [#"Returned" = "clips", #"Order ID" = 2366],
					        [#"Returned" = "container", #"Order ID" = 5828],
					        [#"Returned" = "norfolk", #"Order ID" = 7095],
					        [#"Returned" = "held", #"Order ID" = 1474],
					        [#"Returned" = "wash", #"Order ID" = 4731],
					        [#"Returned" = "teaching", #"Order ID" = 1608],
					        [#"Returned" = "browse", #"Order ID" = 2654],
					        [#"Returned" = "miscellaneous", #"Order ID" = 3262],
					        [#"Returned" = "ca", #"Order ID" = 4557],
					        [#"Returned" = "promote", #"Order ID" = 5344],
					        [#"Returned" = "limits", #"Order ID" = 3919],
					        [#"Returned" = "environmental", #"Order ID" = 9226],
					        [#"Returned" = "slideshow", #"Order ID" = 4434],
					        [#"Returned" = "legacy", #"Order ID" = 6861],
					        [#"Returned" = "truck", #"Order ID" = 7376],
					        [#"Returned" = "allocated", #"Order ID" = 1666],
					        [#"Returned" = "offset", #"Order ID" = 5811],
					        [#"Returned" = "science", #"Order ID" = 8190],
					        [#"Returned" = "assessment", #"Order ID" = 4043],
					        [#"Returned" = "somebody", #"Order ID" = 3056],
					        [#"Returned" = "dining", #"Order ID" = 5129],
					        [#"Returned" = "hp", #"Order ID" = 8396],
					        [#"Returned" = "everyone", #"Order ID" = 4602],
					        [#"Returned" = "introduce", #"Order ID" = 4625],
					        [#"Returned" = "attempts", #"Order ID" = 9880],
					        [#"Returned" = "singles", #"Order ID" = 3177],
					        [#"Returned" = "college", #"Order ID" = 8213],
					        [#"Returned" = "cartridge", #"Order ID" = 1825],
					        [#"Returned" = "on", #"Order ID" = 8807],
					        [#"Returned" = "gifts", #"Order ID" = 2456],
					        [#"Returned" = "chase", #"Order ID" = 4929],
					        [#"Returned" = "face", #"Order ID" = 6855],
					        [#"Returned" = "provisions", #"Order ID" = 5667],
					        [#"Returned" = "nine", #"Order ID" = 3349],
					        [#"Returned" = "cover", #"Order ID" = 8160],
					        [#"Returned" = "valley", #"Order ID" = 5975],
					        [#"Returned" = "ja", #"Order ID" = 4189],
					        [#"Returned" = "schools", #"Order ID" = 6436],
					        [#"Returned" = "upcoming", #"Order ID" = 1525],
					        [#"Returned" = "unless", #"Order ID" = 6130],
					        [#"Returned" = "bush", #"Order ID" = 1927],
					        [#"Returned" = "riding", #"Order ID" = 4167],
					        [#"Returned" = "ok", #"Order ID" = 7616],
					        [#"Returned" = "ed", #"Order ID" = 2557],
					        [#"Returned" = "emissions", #"Order ID" = 3276],
					        [#"Returned" = "adventure", #"Order ID" = 8552],
					        [#"Returned" = "explore", #"Order ID" = 2894],
					        [#"Returned" = "registered", #"Order ID" = 3376],
					        [#"Returned" = "google", #"Order ID" = 9040],
					        [#"Returned" = "years", #"Order ID" = 9141],
					        [#"Returned" = "illegal", #"Order ID" = 2888],
					        [#"Returned" = "intent", #"Order ID" = 8180],
					        [#"Returned" = "represent", #"Order ID" = 3345],
					        [#"Returned" = "northern", #"Order ID" = 5142],
					        [#"Returned" = "introduce", #"Order ID" = 1713]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Returned", type text},
					        {"Order ID", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table