table 'Top Customers'
	lineageTag: 3cc13491-ced6-4282-81c6-23e765e1c115

	measure 'Top Customers Value' = SELECTEDVALUE('Top Customers'[Top Customers], 5)
		lineageTag: 666986fe-cc4b-41a2-86da-33ba581ecb62

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Top Customers'
		dataType: double
		formatString: 0
		lineageTag: 951db47b-d482-45e1-b0b1-7f881f8452d5
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Top Customers' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_Id = e4d4de7e4987402eae01cb9d05ba72a3

