table 'Orders (Sample - Superstore (1))'
	lineageTag: c5e32d29-ce0b-4eaf-ae96-9f1d8812d2c5

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 2ed8cb12-412a-49be-bf03-2e21ee3f87a5
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 3276a6d6-c327-4b94-a7b4-e477415656b2
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: datetime
		lineageTag: b7db6cc3-6fec-4937-8da2-f0ac79db4e81
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: datetime
		lineageTag: 959f5f19-e7d4-44e3-8d97-f3a61fca5b4a
		summarizeBy: none
		sourceColumn: 'Ship Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 05fbe58c-6ffc-4f80-9963-ede71ec77de3
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 2ce0f389-4549-4762-861f-bfed3635517d
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 618fa2c5-f547-4a3f-ad33-f3ff7e0ee441
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: e804a629-7418-4827-a307-7e088e1a772d
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: d54ddeb7-8d98-4a9a-bdf2-dceaf91c9b68
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: e0bcddb3-c076-4788-86bf-c5b976f3d2a8
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: b59f38d0-0a91-4d70-979c-372d02510bd2
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: a443abf5-3009-48c6-a311-3d3d8b6d850b
		summarizeBy: sum
		sourceColumn: 'Postal Code'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: c3b53097-6603-4055-b067-c7f52a55530c
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 69a38acf-f267-4da1-978a-f913d17c0e65
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 4e3cbc30-fb24-4d8d-ba1c-30a4ccab86fc
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: 1ca3d5db-6dbb-4158-a0e8-3a9e0e4ce5dd
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: db601ead-fead-44c2-b7f2-b035318d6708
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: General Number
		lineageTag: 9a508aeb-68d2-4c7c-ac38-b5b3bbfc1cbe
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: a844c40f-ff1b-4e89-a66d-802203c2950d
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: General Number
		lineageTag: afa56ecd-26a6-4e6a-ba2b-4b2cf4deee0a
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		formatString: General Number
		lineageTag: 918ca3dc-a4ed-4f3d-acf1-1145a00f0ac8
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Calculation1 = SWITCH('Orders (Sample - Superstore (1))'[Category], "Furniture", "furniture", "Office Supplies", "office supplier", "Technology", "technology", 'Orders (Sample - Superstore (1))'[Category])
		lineageTag: 629162bf-cd8c-45fd-a868-59ad8a1da68c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Orders (Sample - Superstore (1))' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Row ID" = 9959, #"Order ID" = 6097, #"Order Date" = #date(2023, 11, 16), #"Ship Date" = #date(2023, 5, 27), #"Ship Mode" = "105.232.92.239", #"Customer ID" = 2457, #"Customer Name" = "Bernardine Stevenson", #"Segment" = "felt", #"Country" = "Rwanda", #"City" = "Petersburg", #"State" = "Maryland", #"Postal Code" = 610, #"Region" = "West Virginia", #"Product ID" = 8164, #"Category" = "possibility", #"Sub-Category" = "pick", #"Product Name" = "Buster Sellers", #"Sales" = 262.7, #"Quantity" = 970, #"Discount" = 388.39, #"Profit" = 643.67],
					        [#"Row ID" = 3506, #"Order ID" = 8897, #"Order Date" = #date(2022, 11, 28), #"Ship Date" = #date(2024, 2, 24), #"Ship Mode" = "240.236.251.82", #"Customer ID" = 2900, #"Customer Name" = "Kelley Myers", #"Segment" = "reproduction", #"Country" = "Czech Republic", #"City" = "Houston", #"State" = "Colorado", #"Postal Code" = 518, #"Region" = "Nevada", #"Product ID" = 6110, #"Category" = "acres", #"Sub-Category" = "records", #"Product Name" = "Belkis Prince", #"Sales" = 600.38, #"Quantity" = 405, #"Discount" = 530.24, #"Profit" = 69.25],
					        [#"Row ID" = 8827, #"Order ID" = 5496, #"Order Date" = #date(2020, 1, 13), #"Ship Date" = #date(2021, 5, 6), #"Ship Mode" = "108.147.186.222", #"Customer ID" = 7979, #"Customer Name" = "Bobby Sawyer", #"Segment" = "available", #"Country" = "Central African Republic", #"City" = "Downey", #"State" = "Washington", #"Postal Code" = 236, #"Region" = "New Mexico", #"Product ID" = 4237, #"Category" = "falling", #"Sub-Category" = "open", #"Product Name" = "Latina Martin", #"Sales" = 307.23, #"Quantity" = 363, #"Discount" = 867.99, #"Profit" = 629.7],
					        [#"Row ID" = 2275, #"Order ID" = 9093, #"Order Date" = #date(2024, 12, 29), #"Ship Date" = #date(2022, 4, 18), #"Ship Mode" = "85.37.11.123", #"Customer ID" = 2100, #"Customer Name" = "Diego Spears", #"Segment" = "modes", #"Country" = "Northern Mariana Islands", #"City" = "Alton", #"State" = "Colorado", #"Postal Code" = 67, #"Region" = "South Carolina", #"Product ID" = 8001, #"Category" = "says", #"Sub-Category" = "credit", #"Product Name" = "Cody Kinney", #"Sales" = 607.43, #"Quantity" = 415, #"Discount" = 539.31, #"Profit" = 721.68],
					        [#"Row ID" = 5804, #"Order ID" = 3866, #"Order Date" = #date(2020, 12, 10), #"Ship Date" = #date(2020, 1, 30), #"Ship Mode" = "166.56.162.100", #"Customer ID" = 4335, #"Customer Name" = "Tyson Chaney", #"Segment" = "gi", #"Country" = "Bahamas", #"City" = "Fremont", #"State" = "Georgia", #"Postal Code" = 651, #"Region" = "Pennsylvania", #"Product ID" = 9913, #"Category" = "influence", #"Sub-Category" = "alabama", #"Product Name" = "Elvina Travis", #"Sales" = 700.74, #"Quantity" = 468, #"Discount" = 460.48, #"Profit" = 851.0]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Row ID", Int64.Type},
					        {"Order ID", type text},
					        {"Order Date", type date},
					        {"Ship Date", type date},
					        {"Ship Mode", type text},
					        {"Customer ID", type text},
					        {"Customer Name", type text},
					        {"Segment", type text},
					        {"Country", type text},
					        {"City", type text},
					        {"State", type text},
					        {"Postal Code", Int64.Type},
					        {"Region", type text},
					        {"Product ID", type text},
					        {"Category", type text},
					        {"Sub-Category", type text},
					        {"Product Name", type text},
					        {"Sales", type number},
					        {"Quantity", Int64.Type},
					        {"Discount", type number},
					        {"Profit", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table