table Quota
	lineageTag: 5499789f-d745-40d0-a000-42494b82290e

	column 'Close Date'
		dataType: datetime
		lineageTag: 2d4e7e29-540c-46fc-a2f5-5233ae4fba50
		summarizeBy: none
		sourceColumn: 'Close Date'

		annotation SummarizationSetBy = Automatic

	column 'Account Owned By'
		dataType: string
		lineageTag: fad0138d-b8f5-49b8-84ac-cdd6e99c0f7f
		summarizeBy: none
		sourceColumn: 'Account Owned By'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: fee32f11-b652-4a23-8f13-ef73708807d9
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column 'Opportunity Type'
		dataType: string
		lineageTag: 6e037a60-d2ca-4bcf-b38a-a0ba4e867003
		summarizeBy: none
		sourceColumn: 'Opportunity Type'

		annotation SummarizationSetBy = Automatic

	column Quota
		dataType: double
		formatString: General Number
		lineageTag: 9d9621b0-ee26-4c46-93fd-e3dc53b59255
		summarizeBy: sum
		sourceColumn: Quota

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Quota = m
		mode: import
		source =
				let
					    Source = Csv.Document(
					        File.Contents("https://saastestlatest.blob.core.windows.net/saas-test-reports/Quota.csv?se=2025-11-01T13%3A26%3A54Z&sp=r&sv=2025-11-05&sr=b&sig=5Et0V5FSmUKuUpnGdoQHEK5FF3zIF5u8PrunqCyxJEY%3D"),
					        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
					    ),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Close Date", type date}, {"Account Owned By", type text}, {"Product Name", type text}, {"Opportunity Type", type text}, {"Quota", type number}})
					in
					    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table