table 'Sample - Superstore_Returns'
	lineageTag: 413819a3-d3f5-4b48-a2af-40f4a1bb9d44

	column Returned
		dataType: string
		lineageTag: b6a24ecc-3a37-4807-bc71-c1e85cf322c2
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: a360b407-1a40-408a-a728-cc44c8a8705d
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	partition 'Sample - Superstore_Returns' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Returned" = "remote", #"Order ID" = 6658],
					        [#"Returned" = "test", #"Order ID" = 5974],
					        [#"Returned" = "italian", #"Order ID" = 1460],
					        [#"Returned" = "os", #"Order ID" = 8183],
					        [#"Returned" = "hall", #"Order ID" = 2271],
					        [#"Returned" = "league", #"Order ID" = 7225],
					        [#"Returned" = "teenage", #"Order ID" = 6599],
					        [#"Returned" = "pittsburgh", #"Order ID" = 5464],
					        [#"Returned" = "church", #"Order ID" = 7997],
					        [#"Returned" = "edited", #"Order ID" = 3698],
					        [#"Returned" = "toy", #"Order ID" = 9112],
					        [#"Returned" = "process", #"Order ID" = 5388],
					        [#"Returned" = "programme", #"Order ID" = 9526],
					        [#"Returned" = "lines", #"Order ID" = 6657],
					        [#"Returned" = "mrs", #"Order ID" = 7458],
					        [#"Returned" = "boys", #"Order ID" = 7946],
					        [#"Returned" = "mins", #"Order ID" = 3028],
					        [#"Returned" = "output", #"Order ID" = 6073],
					        [#"Returned" = "rob", #"Order ID" = 6685],
					        [#"Returned" = "basis", #"Order ID" = 4976],
					        [#"Returned" = "decline", #"Order ID" = 1222],
					        [#"Returned" = "tags", #"Order ID" = 4888],
					        [#"Returned" = "delivered", #"Order ID" = 8775],
					        [#"Returned" = "acrobat", #"Order ID" = 2788],
					        [#"Returned" = "payments", #"Order ID" = 9802],
					        [#"Returned" = "tight", #"Order ID" = 6427],
					        [#"Returned" = "feels", #"Order ID" = 2298],
					        [#"Returned" = "antenna", #"Order ID" = 4461],
					        [#"Returned" = "wine", #"Order ID" = 9130],
					        [#"Returned" = "bikes", #"Order ID" = 8851],
					        [#"Returned" = "buyer", #"Order ID" = 5492],
					        [#"Returned" = "detected", #"Order ID" = 1859],
					        [#"Returned" = "knows", #"Order ID" = 8159],
					        [#"Returned" = "terrorist", #"Order ID" = 8495],
					        [#"Returned" = "responses", #"Order ID" = 3073],
					        [#"Returned" = "telecommunications", #"Order ID" = 3594],
					        [#"Returned" = "sec", #"Order ID" = 7579],
					        [#"Returned" = "med", #"Order ID" = 8675],
					        [#"Returned" = "session", #"Order ID" = 8752],
					        [#"Returned" = "james", #"Order ID" = 1071],
					        [#"Returned" = "suitable", #"Order ID" = 5118],
					        [#"Returned" = "terrorist", #"Order ID" = 8602],
					        [#"Returned" = "development", #"Order ID" = 4012],
					        [#"Returned" = "attempt", #"Order ID" = 6530],
					        [#"Returned" = "reserve", #"Order ID" = 8867],
					        [#"Returned" = "fed", #"Order ID" = 9041],
					        [#"Returned" = "soon", #"Order ID" = 2929],
					        [#"Returned" = "modification", #"Order ID" = 7020],
					        [#"Returned" = "voltage", #"Order ID" = 1938],
					        [#"Returned" = "twiki", #"Order ID" = 2725],
					        [#"Returned" = "status", #"Order ID" = 6777],
					        [#"Returned" = "city", #"Order ID" = 1978],
					        [#"Returned" = "lovely", #"Order ID" = 3799],
					        [#"Returned" = "moscow", #"Order ID" = 5474],
					        [#"Returned" = "nutrition", #"Order ID" = 2845],
					        [#"Returned" = "cook", #"Order ID" = 1995],
					        [#"Returned" = "consequences", #"Order ID" = 6879],
					        [#"Returned" = "maintenance", #"Order ID" = 7090],
					        [#"Returned" = "compare", #"Order ID" = 1994],
					        [#"Returned" = "country", #"Order ID" = 4003],
					        [#"Returned" = "marshall", #"Order ID" = 5513],
					        [#"Returned" = "list", #"Order ID" = 1378],
					        [#"Returned" = "residents", #"Order ID" = 7800],
					        [#"Returned" = "dv", #"Order ID" = 6216],
					        [#"Returned" = "ing", #"Order ID" = 6985],
					        [#"Returned" = "collective", #"Order ID" = 9495],
					        [#"Returned" = "nm", #"Order ID" = 2560],
					        [#"Returned" = "ncaa", #"Order ID" = 1654],
					        [#"Returned" = "herself", #"Order ID" = 7696],
					        [#"Returned" = "cod", #"Order ID" = 2246],
					        [#"Returned" = "tee", #"Order ID" = 1021],
					        [#"Returned" = "important", #"Order ID" = 9095],
					        [#"Returned" = "printers", #"Order ID" = 4760],
					        [#"Returned" = "hunter", #"Order ID" = 2130],
					        [#"Returned" = "tee", #"Order ID" = 7909],
					        [#"Returned" = "boats", #"Order ID" = 3898],
					        [#"Returned" = "reg", #"Order ID" = 7179],
					        [#"Returned" = "express", #"Order ID" = 4619],
					        [#"Returned" = "especially", #"Order ID" = 3849],
					        [#"Returned" = "antiques", #"Order ID" = 6187],
					        [#"Returned" = "reality", #"Order ID" = 8431],
					        [#"Returned" = "egg", #"Order ID" = 1409],
					        [#"Returned" = "zoom", #"Order ID" = 1461],
					        [#"Returned" = "instantly", #"Order ID" = 3213],
					        [#"Returned" = "attempts", #"Order ID" = 6756],
					        [#"Returned" = "parameters", #"Order ID" = 3828],
					        [#"Returned" = "then", #"Order ID" = 7708],
					        [#"Returned" = "steel", #"Order ID" = 1743],
					        [#"Returned" = "identity", #"Order ID" = 7911],
					        [#"Returned" = "asking", #"Order ID" = 9345],
					        [#"Returned" = "tells", #"Order ID" = 3040],
					        [#"Returned" = "universities", #"Order ID" = 9346],
					        [#"Returned" = "wireless", #"Order ID" = 9164],
					        [#"Returned" = "review", #"Order ID" = 6848],
					        [#"Returned" = "opportunity", #"Order ID" = 5006],
					        [#"Returned" = "gnome", #"Order ID" = 6878],
					        [#"Returned" = "farm", #"Order ID" = 2058],
					        [#"Returned" = "restricted", #"Order ID" = 6868],
					        [#"Returned" = "jacksonville", #"Order ID" = 6143],
					        [#"Returned" = "nevada", #"Order ID" = 3170],
					        [#"Returned" = "gives", #"Order ID" = 3694],
					        [#"Returned" = "many", #"Order ID" = 8935],
					        [#"Returned" = "max", #"Order ID" = 4242],
					        [#"Returned" = "mission", #"Order ID" = 6612],
					        [#"Returned" = "legislative", #"Order ID" = 7137],
					        [#"Returned" = "handheld", #"Order ID" = 5169],
					        [#"Returned" = "weight", #"Order ID" = 5128],
					        [#"Returned" = "watching", #"Order ID" = 4590],
					        [#"Returned" = "quiz", #"Order ID" = 5593],
					        [#"Returned" = "except", #"Order ID" = 4507],
					        [#"Returned" = "improvement", #"Order ID" = 6460],
					        [#"Returned" = "tab", #"Order ID" = 1974],
					        [#"Returned" = "report", #"Order ID" = 4568],
					        [#"Returned" = "north", #"Order ID" = 7193],
					        [#"Returned" = "subscription", #"Order ID" = 8134],
					        [#"Returned" = "blind", #"Order ID" = 3536],
					        [#"Returned" = "paint", #"Order ID" = 9934],
					        [#"Returned" = "south", #"Order ID" = 1023],
					        [#"Returned" = "appendix", #"Order ID" = 5604],
					        [#"Returned" = "players", #"Order ID" = 7068],
					        [#"Returned" = "cat", #"Order ID" = 1304],
					        [#"Returned" = "assembly", #"Order ID" = 7581],
					        [#"Returned" = "citizens", #"Order ID" = 1561],
					        [#"Returned" = "pretty", #"Order ID" = 5174],
					        [#"Returned" = "parallel", #"Order ID" = 2786],
					        [#"Returned" = "targets", #"Order ID" = 6201],
					        [#"Returned" = "norton", #"Order ID" = 2486],
					        [#"Returned" = "returned", #"Order ID" = 6780],
					        [#"Returned" = "vi", #"Order ID" = 6968],
					        [#"Returned" = "singing", #"Order ID" = 4542],
					        [#"Returned" = "male", #"Order ID" = 7713],
					        [#"Returned" = "alumni", #"Order ID" = 9826],
					        [#"Returned" = "object", #"Order ID" = 4664],
					        [#"Returned" = "awarded", #"Order ID" = 4465],
					        [#"Returned" = "sampling", #"Order ID" = 8076],
					        [#"Returned" = "ride", #"Order ID" = 9848],
					        [#"Returned" = "guess", #"Order ID" = 6063],
					        [#"Returned" = "proposal", #"Order ID" = 5678],
					        [#"Returned" = "chi", #"Order ID" = 5199],
					        [#"Returned" = "terms", #"Order ID" = 9822],
					        [#"Returned" = "of", #"Order ID" = 2098],
					        [#"Returned" = "jonathan", #"Order ID" = 2639],
					        [#"Returned" = "oct", #"Order ID" = 4909],
					        [#"Returned" = "blogger", #"Order ID" = 2275],
					        [#"Returned" = "jimmy", #"Order ID" = 7695],
					        [#"Returned" = "serious", #"Order ID" = 2349],
					        [#"Returned" = "specific", #"Order ID" = 1312],
					        [#"Returned" = "exposure", #"Order ID" = 3585],
					        [#"Returned" = "anti", #"Order ID" = 5193],
					        [#"Returned" = "processed", #"Order ID" = 7765],
					        [#"Returned" = "breasts", #"Order ID" = 5072],
					        [#"Returned" = "extract", #"Order ID" = 7626],
					        [#"Returned" = "fabric", #"Order ID" = 2578],
					        [#"Returned" = "regulations", #"Order ID" = 5189],
					        [#"Returned" = "johnson", #"Order ID" = 6216],
					        [#"Returned" = "commonwealth", #"Order ID" = 1691],
					        [#"Returned" = "leaders", #"Order ID" = 4790],
					        [#"Returned" = "outcome", #"Order ID" = 2133],
					        [#"Returned" = "src", #"Order ID" = 8509],
					        [#"Returned" = "deutsch", #"Order ID" = 8510],
					        [#"Returned" = "twenty", #"Order ID" = 1393],
					        [#"Returned" = "ourselves", #"Order ID" = 8962],
					        [#"Returned" = "story", #"Order ID" = 4123],
					        [#"Returned" = "specs", #"Order ID" = 3768],
					        [#"Returned" = "acting", #"Order ID" = 4963],
					        [#"Returned" = "weapons", #"Order ID" = 1380],
					        [#"Returned" = "charter", #"Order ID" = 2488],
					        [#"Returned" = "roger", #"Order ID" = 1985],
					        [#"Returned" = "launch", #"Order ID" = 7297],
					        [#"Returned" = "owner", #"Order ID" = 7660],
					        [#"Returned" = "chronic", #"Order ID" = 9495],
					        [#"Returned" = "differences", #"Order ID" = 2848],
					        [#"Returned" = "purchase", #"Order ID" = 9084],
					        [#"Returned" = "trembl", #"Order ID" = 1028],
					        [#"Returned" = "roots", #"Order ID" = 5693],
					        [#"Returned" = "activation", #"Order ID" = 4723],
					        [#"Returned" = "jennifer", #"Order ID" = 3359],
					        [#"Returned" = "partnerships", #"Order ID" = 3317],
					        [#"Returned" = "malaysia", #"Order ID" = 4198],
					        [#"Returned" = "lebanon", #"Order ID" = 7474],
					        [#"Returned" = "guests", #"Order ID" = 4808],
					        [#"Returned" = "map", #"Order ID" = 3048],
					        [#"Returned" = "technology", #"Order ID" = 4361],
					        [#"Returned" = "ford", #"Order ID" = 1378],
					        [#"Returned" = "neutral", #"Order ID" = 4388],
					        [#"Returned" = "direct", #"Order ID" = 1967],
					        [#"Returned" = "evidence", #"Order ID" = 6794],
					        [#"Returned" = "occur", #"Order ID" = 3860],
					        [#"Returned" = "proteins", #"Order ID" = 2073],
					        [#"Returned" = "liable", #"Order ID" = 8813],
					        [#"Returned" = "explorer", #"Order ID" = 1559],
					        [#"Returned" = "supervisor", #"Order ID" = 6086],
					        [#"Returned" = "vacuum", #"Order ID" = 6547],
					        [#"Returned" = "arabia", #"Order ID" = 6697],
					        [#"Returned" = "appreciate", #"Order ID" = 6208],
					        [#"Returned" = "index", #"Order ID" = 3316],
					        [#"Returned" = "icon", #"Order ID" = 7833],
					        [#"Returned" = "sugar", #"Order ID" = 7840],
					        [#"Returned" = "kind", #"Order ID" = 7140],
					        [#"Returned" = "grow", #"Order ID" = 9022],
					        [#"Returned" = "agree", #"Order ID" = 1325],
					        [#"Returned" = "document", #"Order ID" = 2835],
					        [#"Returned" = "catalog", #"Order ID" = 7013],
					        [#"Returned" = "alerts", #"Order ID" = 3337],
					        [#"Returned" = "sleeping", #"Order ID" = 2407],
					        [#"Returned" = "cause", #"Order ID" = 6532],
					        [#"Returned" = "municipal", #"Order ID" = 3626],
					        [#"Returned" = "next", #"Order ID" = 8454],
					        [#"Returned" = "objects", #"Order ID" = 8518],
					        [#"Returned" = "faculty", #"Order ID" = 4811],
					        [#"Returned" = "till", #"Order ID" = 6932],
					        [#"Returned" = "extra", #"Order ID" = 2440],
					        [#"Returned" = "armed", #"Order ID" = 3602],
					        [#"Returned" = "import", #"Order ID" = 5829],
					        [#"Returned" = "titans", #"Order ID" = 9907],
					        [#"Returned" = "cookie", #"Order ID" = 5215],
					        [#"Returned" = "laptops", #"Order ID" = 5294],
					        [#"Returned" = "writers", #"Order ID" = 7764],
					        [#"Returned" = "team", #"Order ID" = 1502],
					        [#"Returned" = "included", #"Order ID" = 6831],
					        [#"Returned" = "brochure", #"Order ID" = 3261],
					        [#"Returned" = "visited", #"Order ID" = 8105],
					        [#"Returned" = "samuel", #"Order ID" = 6316],
					        [#"Returned" = "jimmy", #"Order ID" = 3986],
					        [#"Returned" = "disney", #"Order ID" = 3133],
					        [#"Returned" = "resorts", #"Order ID" = 4690],
					        [#"Returned" = "twelve", #"Order ID" = 4853],
					        [#"Returned" = "valuable", #"Order ID" = 9538],
					        [#"Returned" = "movie", #"Order ID" = 6234],
					        [#"Returned" = "frank", #"Order ID" = 9998],
					        [#"Returned" = "options", #"Order ID" = 7977],
					        [#"Returned" = "strange", #"Order ID" = 8420],
					        [#"Returned" = "donation", #"Order ID" = 2112],
					        [#"Returned" = "listen", #"Order ID" = 4552],
					        [#"Returned" = "su", #"Order ID" = 8538],
					        [#"Returned" = "adult", #"Order ID" = 8276],
					        [#"Returned" = "monitoring", #"Order ID" = 4649],
					        [#"Returned" = "diamond", #"Order ID" = 7401],
					        [#"Returned" = "angel", #"Order ID" = 9111],
					        [#"Returned" = "samuel", #"Order ID" = 4059],
					        [#"Returned" = "diesel", #"Order ID" = 6613],
					        [#"Returned" = "requirement", #"Order ID" = 8647],
					        [#"Returned" = "located", #"Order ID" = 5372],
					        [#"Returned" = "annotation", #"Order ID" = 4147],
					        [#"Returned" = "approaches", #"Order ID" = 4182],
					        [#"Returned" = "anthony", #"Order ID" = 2149],
					        [#"Returned" = "pleasure", #"Order ID" = 6862],
					        [#"Returned" = "offered", #"Order ID" = 4576],
					        [#"Returned" = "recreation", #"Order ID" = 3727],
					        [#"Returned" = "cookie", #"Order ID" = 6304],
					        [#"Returned" = "banner", #"Order ID" = 8663],
					        [#"Returned" = "productions", #"Order ID" = 5162],
					        [#"Returned" = "te", #"Order ID" = 6433],
					        [#"Returned" = "calendars", #"Order ID" = 6322],
					        [#"Returned" = "detected", #"Order ID" = 7006],
					        [#"Returned" = "rs", #"Order ID" = 4265],
					        [#"Returned" = "testimonials", #"Order ID" = 4635],
					        [#"Returned" = "spears", #"Order ID" = 3725],
					        [#"Returned" = "ultimate", #"Order ID" = 8346],
					        [#"Returned" = "lucky", #"Order ID" = 7228],
					        [#"Returned" = "proposed", #"Order ID" = 8069],
					        [#"Returned" = "years", #"Order ID" = 1315],
					        [#"Returned" = "fetish", #"Order ID" = 1836],
					        [#"Returned" = "determined", #"Order ID" = 3223],
					        [#"Returned" = "funded", #"Order ID" = 4492],
					        [#"Returned" = "dealing", #"Order ID" = 1847],
					        [#"Returned" = "boat", #"Order ID" = 5566],
					        [#"Returned" = "partnership", #"Order ID" = 6408],
					        [#"Returned" = "extend", #"Order ID" = 6808],
					        [#"Returned" = "dress", #"Order ID" = 2407],
					        [#"Returned" = "influence", #"Order ID" = 9264],
					        [#"Returned" = "zip", #"Order ID" = 5344],
					        [#"Returned" = "larger", #"Order ID" = 2945],
					        [#"Returned" = "wilson", #"Order ID" = 6686],
					        [#"Returned" = "choosing", #"Order ID" = 7483],
					        [#"Returned" = "founder", #"Order ID" = 9256],
					        [#"Returned" = "non", #"Order ID" = 8639],
					        [#"Returned" = "jim", #"Order ID" = 8620],
					        [#"Returned" = "southeast", #"Order ID" = 7503],
					        [#"Returned" = "stability", #"Order ID" = 1092],
					        [#"Returned" = "emergency", #"Order ID" = 6298],
					        [#"Returned" = "copyright", #"Order ID" = 8919],
					        [#"Returned" = "alliance", #"Order ID" = 6998],
					        [#"Returned" = "conditioning", #"Order ID" = 9078],
					        [#"Returned" = "puerto", #"Order ID" = 2738],
					        [#"Returned" = "sectors", #"Order ID" = 5741],
					        [#"Returned" = "globe", #"Order ID" = 5409],
					        [#"Returned" = "glance", #"Order ID" = 8156],
					        [#"Returned" = "venue", #"Order ID" = 7169],
					        [#"Returned" = "ma", #"Order ID" = 5004],
					        [#"Returned" = "average", #"Order ID" = 1587],
					        [#"Returned" = "lenses", #"Order ID" = 3582],
					        [#"Returned" = "founder", #"Order ID" = 4069],
					        [#"Returned" = "radio", #"Order ID" = 5230],
					        [#"Returned" = "replaced", #"Order ID" = 8873],
					        [#"Returned" = "apparel", #"Order ID" = 6441],
					        [#"Returned" = "september", #"Order ID" = 6852],
					        [#"Returned" = "curriculum", #"Order ID" = 5140],
					        [#"Returned" = "amd", #"Order ID" = 6092],
					        [#"Returned" = "forced", #"Order ID" = 1539],
					        [#"Returned" = "subscribers", #"Order ID" = 7964],
					        [#"Returned" = "bigger", #"Order ID" = 5730],
					        [#"Returned" = "christopher", #"Order ID" = 2797],
					        [#"Returned" = "martin", #"Order ID" = 8814],
					        [#"Returned" = "lecture", #"Order ID" = 2848],
					        [#"Returned" = "affordable", #"Order ID" = 5693],
					        [#"Returned" = "challenge", #"Order ID" = 9509],
					        [#"Returned" = "outer", #"Order ID" = 6852],
					        [#"Returned" = "buttons", #"Order ID" = 4651],
					        [#"Returned" = "elite", #"Order ID" = 9252],
					        [#"Returned" = "reached", #"Order ID" = 7210],
					        [#"Returned" = "enjoyed", #"Order ID" = 4907],
					        [#"Returned" = "titles", #"Order ID" = 5871],
					        [#"Returned" = "acc", #"Order ID" = 1787],
					        [#"Returned" = "mail", #"Order ID" = 8087],
					        [#"Returned" = "rankings", #"Order ID" = 3311],
					        [#"Returned" = "myself", #"Order ID" = 4210],
					        [#"Returned" = "warren", #"Order ID" = 7331],
					        [#"Returned" = "risks", #"Order ID" = 4809],
					        [#"Returned" = "assumed", #"Order ID" = 5456],
					        [#"Returned" = "angel", #"Order ID" = 7463],
					        [#"Returned" = "household", #"Order ID" = 3745],
					        [#"Returned" = "capability", #"Order ID" = 9107],
					        [#"Returned" = "significant", #"Order ID" = 4844],
					        [#"Returned" = "hearing", #"Order ID" = 9729],
					        [#"Returned" = "out", #"Order ID" = 2400],
					        [#"Returned" = "thus", #"Order ID" = 9268],
					        [#"Returned" = "oklahoma", #"Order ID" = 7814],
					        [#"Returned" = "frame", #"Order ID" = 2662],
					        [#"Returned" = "publisher", #"Order ID" = 8917],
					        [#"Returned" = "pregnancy", #"Order ID" = 3664],
					        [#"Returned" = "trim", #"Order ID" = 2378],
					        [#"Returned" = "subscribers", #"Order ID" = 3944],
					        [#"Returned" = "anne", #"Order ID" = 6329],
					        [#"Returned" = "ice", #"Order ID" = 3770],
					        [#"Returned" = "unsubscribe", #"Order ID" = 5412],
					        [#"Returned" = "pain", #"Order ID" = 3967],
					        [#"Returned" = "javascript", #"Order ID" = 7105],
					        [#"Returned" = "teams", #"Order ID" = 5973],
					        [#"Returned" = "dr", #"Order ID" = 3574],
					        [#"Returned" = "america", #"Order ID" = 4054],
					        [#"Returned" = "missing", #"Order ID" = 3929],
					        [#"Returned" = "gift", #"Order ID" = 2480],
					        [#"Returned" = "med", #"Order ID" = 9423],
					        [#"Returned" = "operation", #"Order ID" = 3145],
					        [#"Returned" = "gadgets", #"Order ID" = 8908],
					        [#"Returned" = "favorite", #"Order ID" = 8080],
					        [#"Returned" = "join", #"Order ID" = 1010],
					        [#"Returned" = "chemistry", #"Order ID" = 8842],
					        [#"Returned" = "engaged", #"Order ID" = 3506],
					        [#"Returned" = "supplies", #"Order ID" = 9443],
					        [#"Returned" = "cb", #"Order ID" = 6155],
					        [#"Returned" = "golden", #"Order ID" = 2400],
					        [#"Returned" = "knight", #"Order ID" = 8187],
					        [#"Returned" = "supported", #"Order ID" = 4875],
					        [#"Returned" = "operating", #"Order ID" = 5778],
					        [#"Returned" = "phrase", #"Order ID" = 1933],
					        [#"Returned" = "charged", #"Order ID" = 7511],
					        [#"Returned" = "merchandise", #"Order ID" = 6268],
					        [#"Returned" = "clay", #"Order ID" = 7420],
					        [#"Returned" = "shut", #"Order ID" = 1424],
					        [#"Returned" = "messaging", #"Order ID" = 6757],
					        [#"Returned" = "policies", #"Order ID" = 1588],
					        [#"Returned" = "morgan", #"Order ID" = 1393],
					        [#"Returned" = "discussed", #"Order ID" = 9481],
					        [#"Returned" = "nylon", #"Order ID" = 9549],
					        [#"Returned" = "homes", #"Order ID" = 4969],
					        [#"Returned" = "investor", #"Order ID" = 9838],
					        [#"Returned" = "co", #"Order ID" = 5279],
					        [#"Returned" = "plaza", #"Order ID" = 9185],
					        [#"Returned" = "opposition", #"Order ID" = 3649],
					        [#"Returned" = "switzerland", #"Order ID" = 1234],
					        [#"Returned" = "dvd", #"Order ID" = 5296],
					        [#"Returned" = "russia", #"Order ID" = 5710],
					        [#"Returned" = "supported", #"Order ID" = 2284],
					        [#"Returned" = "loop", #"Order ID" = 9439],
					        [#"Returned" = "battle", #"Order ID" = 9126],
					        [#"Returned" = "episode", #"Order ID" = 5073],
					        [#"Returned" = "assumes", #"Order ID" = 5343],
					        [#"Returned" = "jane", #"Order ID" = 4274],
					        [#"Returned" = "enhanced", #"Order ID" = 6308],
					        [#"Returned" = "mike", #"Order ID" = 6262],
					        [#"Returned" = "containing", #"Order ID" = 5711],
					        [#"Returned" = "sarah", #"Order ID" = 4880],
					        [#"Returned" = "mail", #"Order ID" = 1381],
					        [#"Returned" = "river", #"Order ID" = 8927],
					        [#"Returned" = "satisfaction", #"Order ID" = 1371],
					        [#"Returned" = "thesis", #"Order ID" = 4475],
					        [#"Returned" = "communities", #"Order ID" = 8806],
					        [#"Returned" = "florists", #"Order ID" = 9975],
					        [#"Returned" = "alaska", #"Order ID" = 1119],
					        [#"Returned" = "console", #"Order ID" = 1273],
					        [#"Returned" = "vol", #"Order ID" = 8086],
					        [#"Returned" = "raising", #"Order ID" = 9298],
					        [#"Returned" = "packages", #"Order ID" = 9309],
					        [#"Returned" = "fast", #"Order ID" = 6827],
					        [#"Returned" = "dialogue", #"Order ID" = 9670],
					        [#"Returned" = "branch", #"Order ID" = 4206],
					        [#"Returned" = "perfect", #"Order ID" = 7626],
					        [#"Returned" = "acting", #"Order ID" = 2377],
					        [#"Returned" = "what", #"Order ID" = 4583],
					        [#"Returned" = "starring", #"Order ID" = 5010],
					        [#"Returned" = "bright", #"Order ID" = 7428],
					        [#"Returned" = "alliance", #"Order ID" = 6878],
					        [#"Returned" = "kansas", #"Order ID" = 3023],
					        [#"Returned" = "clearance", #"Order ID" = 5165],
					        [#"Returned" = "dvds", #"Order ID" = 2598],
					        [#"Returned" = "britain", #"Order ID" = 6317],
					        [#"Returned" = "norway", #"Order ID" = 7084],
					        [#"Returned" = "checking", #"Order ID" = 1993],
					        [#"Returned" = "completed", #"Order ID" = 8786],
					        [#"Returned" = "tagged", #"Order ID" = 5510],
					        [#"Returned" = "testing", #"Order ID" = 8929],
					        [#"Returned" = "domains", #"Order ID" = 9481],
					        [#"Returned" = "guarantee", #"Order ID" = 3244],
					        [#"Returned" = "items", #"Order ID" = 5835],
					        [#"Returned" = "comedy", #"Order ID" = 5712],
					        [#"Returned" = "copper", #"Order ID" = 2536],
					        [#"Returned" = "tower", #"Order ID" = 9176],
					        [#"Returned" = "expectations", #"Order ID" = 1030],
					        [#"Returned" = "sending", #"Order ID" = 8973],
					        [#"Returned" = "estate", #"Order ID" = 5289],
					        [#"Returned" = "discussed", #"Order ID" = 8674],
					        [#"Returned" = "relative", #"Order ID" = 5123],
					        [#"Returned" = "nutrition", #"Order ID" = 6899],
					        [#"Returned" = "stage", #"Order ID" = 2328],
					        [#"Returned" = "side", #"Order ID" = 4053],
					        [#"Returned" = "sorry", #"Order ID" = 8169],
					        [#"Returned" = "nevada", #"Order ID" = 7219],
					        [#"Returned" = "tue", #"Order ID" = 9959],
					        [#"Returned" = "larry", #"Order ID" = 7345],
					        [#"Returned" = "penalty", #"Order ID" = 3054],
					        [#"Returned" = "connector", #"Order ID" = 2546],
					        [#"Returned" = "rivers", #"Order ID" = 6694],
					        [#"Returned" = "inclusive", #"Order ID" = 1425],
					        [#"Returned" = "il", #"Order ID" = 1845],
					        [#"Returned" = "compaq", #"Order ID" = 3958],
					        [#"Returned" = "palm", #"Order ID" = 1724],
					        [#"Returned" = "explore", #"Order ID" = 5201],
					        [#"Returned" = "buy", #"Order ID" = 8942],
					        [#"Returned" = "slightly", #"Order ID" = 7933],
					        [#"Returned" = "baker", #"Order ID" = 5657],
					        [#"Returned" = "request", #"Order ID" = 7685],
					        [#"Returned" = "fed", #"Order ID" = 7608],
					        [#"Returned" = "workforce", #"Order ID" = 5775],
					        [#"Returned" = "recently", #"Order ID" = 5301],
					        [#"Returned" = "minor", #"Order ID" = 9727],
					        [#"Returned" = "enhance", #"Order ID" = 2268],
					        [#"Returned" = "day", #"Order ID" = 8012],
					        [#"Returned" = "herald", #"Order ID" = 2026],
					        [#"Returned" = "girl", #"Order ID" = 7550],
					        [#"Returned" = "chart", #"Order ID" = 8955],
					        [#"Returned" = "spiritual", #"Order ID" = 9030],
					        [#"Returned" = "collaboration", #"Order ID" = 4214],
					        [#"Returned" = "holes", #"Order ID" = 2232],
					        [#"Returned" = "its", #"Order ID" = 2870],
					        [#"Returned" = "monday", #"Order ID" = 7085],
					        [#"Returned" = "returning", #"Order ID" = 4028],
					        [#"Returned" = "pride", #"Order ID" = 8572],
					        [#"Returned" = "nike", #"Order ID" = 1222],
					        [#"Returned" = "nation", #"Order ID" = 1553],
					        [#"Returned" = "moderator", #"Order ID" = 3142],
					        [#"Returned" = "thus", #"Order ID" = 5736],
					        [#"Returned" = "reserved", #"Order ID" = 3441],
					        [#"Returned" = "trust", #"Order ID" = 2309],
					        [#"Returned" = "tones", #"Order ID" = 8735],
					        [#"Returned" = "usa", #"Order ID" = 9774],
					        [#"Returned" = "phase", #"Order ID" = 6509],
					        [#"Returned" = "belief", #"Order ID" = 5953],
					        [#"Returned" = "doubt", #"Order ID" = 4229],
					        [#"Returned" = "portable", #"Order ID" = 8317],
					        [#"Returned" = "breakfast", #"Order ID" = 3248],
					        [#"Returned" = "holding", #"Order ID" = 7047],
					        [#"Returned" = "push", #"Order ID" = 4074],
					        [#"Returned" = "oriented", #"Order ID" = 2300],
					        [#"Returned" = "application", #"Order ID" = 3952],
					        [#"Returned" = "normally", #"Order ID" = 8376],
					        [#"Returned" = "counters", #"Order ID" = 9969],
					        [#"Returned" = "so", #"Order ID" = 6993],
					        [#"Returned" = "extra", #"Order ID" = 3464],
					        [#"Returned" = "watches", #"Order ID" = 7449],
					        [#"Returned" = "pour", #"Order ID" = 2375],
					        [#"Returned" = "lewis", #"Order ID" = 7459],
					        [#"Returned" = "career", #"Order ID" = 3322],
					        [#"Returned" = "democracy", #"Order ID" = 8943],
					        [#"Returned" = "passing", #"Order ID" = 8077],
					        [#"Returned" = "felt", #"Order ID" = 6147],
					        [#"Returned" = "denver", #"Order ID" = 9792],
					        [#"Returned" = "received", #"Order ID" = 2617],
					        [#"Returned" = "send", #"Order ID" = 2270],
					        [#"Returned" = "contain", #"Order ID" = 5243],
					        [#"Returned" = "resistant", #"Order ID" = 3745],
					        [#"Returned" = "visitors", #"Order ID" = 2618],
					        [#"Returned" = "complaint", #"Order ID" = 1905],
					        [#"Returned" = "mon", #"Order ID" = 1336],
					        [#"Returned" = "vector", #"Order ID" = 2428],
					        [#"Returned" = "career", #"Order ID" = 7222],
					        [#"Returned" = "our", #"Order ID" = 4802],
					        [#"Returned" = "tech", #"Order ID" = 9514],
					        [#"Returned" = "fix", #"Order ID" = 7305]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Returned", type text},
					        {"Order ID", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table