table 'Extract_Sheet1 (waffle template)'
	lineageTag: 6b6d2b4c-c3a5-445a-87b2-065c81510af2

	column Row
		dataType: int64
		formatString: 0
		lineageTag: b248f78a-fda7-4761-a9f7-1b8c4d6ae3bf
		summarizeBy: sum
		sourceColumn: Row

		annotation SummarizationSetBy = Automatic

	column Column
		dataType: int64
		formatString: 0
		lineageTag: c3e4112e-304f-4a88-96ee-17f0359b455b
		summarizeBy: sum
		sourceColumn: Column

		annotation SummarizationSetBy = Automatic

	column Percentage
		dataType: double
		formatString: General Number
		lineageTag: 1685ed9e-b788-468f-9847-d7c36e12c719
		summarizeBy: sum
		sourceColumn: Percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Extract_Sheet1 (waffle template)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Row" = 184, #"Column" = 167, #"Percentage" = 81.17],
					        [#"Row" = 37, #"Column" = 218, #"Percentage" = 37.75],
					        [#"Row" = 261, #"Column" = 153, #"Percentage" = 39.62],
					        [#"Row" = 685, #"Column" = 545, #"Percentage" = 67.34],
					        [#"Row" = 492, #"Column" = 326, #"Percentage" = 14.34],
					        [#"Row" = 323, #"Column" = 829, #"Percentage" = 46.63],
					        [#"Row" = 948, #"Column" = 275, #"Percentage" = 91.25],
					        [#"Row" = 871, #"Column" = 431, #"Percentage" = 92.45],
					        [#"Row" = 225, #"Column" = 902, #"Percentage" = 68.46],
					        [#"Row" = 260, #"Column" = 985, #"Percentage" = 76.38],
					        [#"Row" = 439, #"Column" = 600, #"Percentage" = 84.47],
					        [#"Row" = 825, #"Column" = 846, #"Percentage" = 57.36],
					        [#"Row" = 983, #"Column" = 117, #"Percentage" = 10.62],
					        [#"Row" = 901, #"Column" = 969, #"Percentage" = 12.42],
					        [#"Row" = 444, #"Column" = 128, #"Percentage" = 91.05],
					        [#"Row" = 112, #"Column" = 427, #"Percentage" = 92.49],
					        [#"Row" = 917, #"Column" = 383, #"Percentage" = 65.52],
					        [#"Row" = 994, #"Column" = 751, #"Percentage" = 44.69],
					        [#"Row" = 136, #"Column" = 192, #"Percentage" = 43.68],
					        [#"Row" = 71, #"Column" = 484, #"Percentage" = 30.71],
					        [#"Row" = 751, #"Column" = 998, #"Percentage" = 6.83],
					        [#"Row" = 451, #"Column" = 503, #"Percentage" = 58.67],
					        [#"Row" = 228, #"Column" = 404, #"Percentage" = 46.06],
					        [#"Row" = 844, #"Column" = 287, #"Percentage" = 8.88],
					        [#"Row" = 626, #"Column" = 692, #"Percentage" = 18.07],
					        [#"Row" = 59, #"Column" = 185, #"Percentage" = 88.38],
					        [#"Row" = 468, #"Column" = 770, #"Percentage" = 10.09],
					        [#"Row" = 784, #"Column" = 238, #"Percentage" = 97.29],
					        [#"Row" = 967, #"Column" = 627, #"Percentage" = 4.81],
					        [#"Row" = 179, #"Column" = 315, #"Percentage" = 3.83],
					        [#"Row" = 374, #"Column" = 563, #"Percentage" = 56.75],
					        [#"Row" = 376, #"Column" = 413, #"Percentage" = 89.43],
					        [#"Row" = 449, #"Column" = 473, #"Percentage" = 91.53],
					        [#"Row" = 762, #"Column" = 400, #"Percentage" = 33.27],
					        [#"Row" = 390, #"Column" = 163, #"Percentage" = 24.28],
					        [#"Row" = 112, #"Column" = 529, #"Percentage" = 14.28],
					        [#"Row" = 421, #"Column" = 820, #"Percentage" = 74.59],
					        [#"Row" = 637, #"Column" = 191, #"Percentage" = 81.49],
					        [#"Row" = 132, #"Column" = 864, #"Percentage" = 15.83],
					        [#"Row" = 90, #"Column" = 288, #"Percentage" = 24.67],
					        [#"Row" = 936, #"Column" = 264, #"Percentage" = 1.25],
					        [#"Row" = 553, #"Column" = 590, #"Percentage" = 15.47],
					        [#"Row" = 279, #"Column" = 700, #"Percentage" = 35.27],
					        [#"Row" = 869, #"Column" = 176, #"Percentage" = 61.44],
					        [#"Row" = 183, #"Column" = 146, #"Percentage" = 30.41],
					        [#"Row" = 616, #"Column" = 147, #"Percentage" = 17.15],
					        [#"Row" = 318, #"Column" = 890, #"Percentage" = 30.09],
					        [#"Row" = 871, #"Column" = 912, #"Percentage" = 57.14],
					        [#"Row" = 721, #"Column" = 653, #"Percentage" = 77.96],
					        [#"Row" = 712, #"Column" = 815, #"Percentage" = 98.68],
					        [#"Row" = 176, #"Column" = 218, #"Percentage" = 64.3],
					        [#"Row" = 584, #"Column" = 290, #"Percentage" = 54.28],
					        [#"Row" = 899, #"Column" = 351, #"Percentage" = 19.95],
					        [#"Row" = 760, #"Column" = 724, #"Percentage" = 42.55],
					        [#"Row" = 262, #"Column" = 101, #"Percentage" = 33.18],
					        [#"Row" = 927, #"Column" = 226, #"Percentage" = 34.6],
					        [#"Row" = 919, #"Column" = 774, #"Percentage" = 17.04],
					        [#"Row" = 552, #"Column" = 850, #"Percentage" = 53.91],
					        [#"Row" = 106, #"Column" = 884, #"Percentage" = 71.34],
					        [#"Row" = 939, #"Column" = 8, #"Percentage" = 18.29],
					        [#"Row" = 980, #"Column" = 704, #"Percentage" = 15.58],
					        [#"Row" = 84, #"Column" = 360, #"Percentage" = 63.57],
					        [#"Row" = 552, #"Column" = 414, #"Percentage" = 57.72],
					        [#"Row" = 241, #"Column" = 988, #"Percentage" = 55.56],
					        [#"Row" = 777, #"Column" = 92, #"Percentage" = 17.92],
					        [#"Row" = 827, #"Column" = 619, #"Percentage" = 81.39],
					        [#"Row" = 881, #"Column" = 530, #"Percentage" = 18.45],
					        [#"Row" = 935, #"Column" = 515, #"Percentage" = 61.07],
					        [#"Row" = 574, #"Column" = 175, #"Percentage" = 15.32],
					        [#"Row" = 562, #"Column" = 444, #"Percentage" = 24.14],
					        [#"Row" = 855, #"Column" = 210, #"Percentage" = 68.5],
					        [#"Row" = 307, #"Column" = 398, #"Percentage" = 70.87],
					        [#"Row" = 258, #"Column" = 253, #"Percentage" = 27.52],
					        [#"Row" = 722, #"Column" = 69, #"Percentage" = 10.04],
					        [#"Row" = 319, #"Column" = 762, #"Percentage" = 59.62],
					        [#"Row" = 496, #"Column" = 664, #"Percentage" = 80.47],
					        [#"Row" = 935, #"Column" = 224, #"Percentage" = 24.49],
					        [#"Row" = 457, #"Column" = 451, #"Percentage" = 73.47],
					        [#"Row" = 252, #"Column" = 247, #"Percentage" = 5.96],
					        [#"Row" = 9, #"Column" = 960, #"Percentage" = 13.06],
					        [#"Row" = 952, #"Column" = 496, #"Percentage" = 50.83],
					        [#"Row" = 197, #"Column" = 723, #"Percentage" = 78.76],
					        [#"Row" = 643, #"Column" = 917, #"Percentage" = 9.93],
					        [#"Row" = 455, #"Column" = 401, #"Percentage" = 62.44],
					        [#"Row" = 445, #"Column" = 21, #"Percentage" = 83.25],
					        [#"Row" = 550, #"Column" = 335, #"Percentage" = 50.62],
					        [#"Row" = 962, #"Column" = 747, #"Percentage" = 58.2],
					        [#"Row" = 876, #"Column" = 26, #"Percentage" = 28.12],
					        [#"Row" = 984, #"Column" = 460, #"Percentage" = 77.64],
					        [#"Row" = 547, #"Column" = 750, #"Percentage" = 95.96],
					        [#"Row" = 599, #"Column" = 420, #"Percentage" = 19.72],
					        [#"Row" = 464, #"Column" = 220, #"Percentage" = 49.28],
					        [#"Row" = 710, #"Column" = 810, #"Percentage" = 21.06],
					        [#"Row" = 674, #"Column" = 873, #"Percentage" = 77.75],
					        [#"Row" = 748, #"Column" = 40, #"Percentage" = 9.18],
					        [#"Row" = 592, #"Column" = 125, #"Percentage" = 22.78],
					        [#"Row" = 892, #"Column" = 310, #"Percentage" = 67.21],
					        [#"Row" = 162, #"Column" = 735, #"Percentage" = 93.04],
					        [#"Row" = 36, #"Column" = 19, #"Percentage" = 99.91],
					        [#"Row" = 782, #"Column" = 81, #"Percentage" = 79.1],
					        [#"Row" = 220, #"Column" = 888, #"Percentage" = 15.28],
					        [#"Row" = 465, #"Column" = 720, #"Percentage" = 88.09],
					        [#"Row" = 508, #"Column" = 515, #"Percentage" = 36.91],
					        [#"Row" = 549, #"Column" = 521, #"Percentage" = 38.96],
					        [#"Row" = 391, #"Column" = 190, #"Percentage" = 65.65],
					        [#"Row" = 982, #"Column" = 493, #"Percentage" = 45.42],
					        [#"Row" = 132, #"Column" = 18, #"Percentage" = 56.13],
					        [#"Row" = 186, #"Column" = 929, #"Percentage" = 59.71],
					        [#"Row" = 618, #"Column" = 859, #"Percentage" = 84.86],
					        [#"Row" = 671, #"Column" = 918, #"Percentage" = 61.76],
					        [#"Row" = 885, #"Column" = 656, #"Percentage" = 73.68],
					        [#"Row" = 670, #"Column" = 787, #"Percentage" = 90.7],
					        [#"Row" = 93, #"Column" = 540, #"Percentage" = 70.96],
					        [#"Row" = 145, #"Column" = 633, #"Percentage" = 57.98],
					        [#"Row" = 473, #"Column" = 348, #"Percentage" = 88.47],
					        [#"Row" = 80, #"Column" = 346, #"Percentage" = 45.89],
					        [#"Row" = 481, #"Column" = 951, #"Percentage" = 18.71],
					        [#"Row" = 751, #"Column" = 436, #"Percentage" = 15.37],
					        [#"Row" = 136, #"Column" = 959, #"Percentage" = 68.52],
					        [#"Row" = 929, #"Column" = 368, #"Percentage" = 35.4],
					        [#"Row" = 456, #"Column" = 929, #"Percentage" = 35.63],
					        [#"Row" = 516, #"Column" = 332, #"Percentage" = 19.54],
					        [#"Row" = 575, #"Column" = 320, #"Percentage" = 40.35],
					        [#"Row" = 509, #"Column" = 544, #"Percentage" = 81.7],
					        [#"Row" = 827, #"Column" = 620, #"Percentage" = 58.57],
					        [#"Row" = 970, #"Column" = 845, #"Percentage" = 47.69],
					        [#"Row" = 646, #"Column" = 890, #"Percentage" = 26.28],
					        [#"Row" = 356, #"Column" = 495, #"Percentage" = 14.74],
					        [#"Row" = 962, #"Column" = 674, #"Percentage" = 24.27],
					        [#"Row" = 708, #"Column" = 54, #"Percentage" = 4.89],
					        [#"Row" = 7, #"Column" = 195, #"Percentage" = 32.0],
					        [#"Row" = 919, #"Column" = 160, #"Percentage" = 59.56],
					        [#"Row" = 5, #"Column" = 356, #"Percentage" = 51.85],
					        [#"Row" = 646, #"Column" = 573, #"Percentage" = 85.16],
					        [#"Row" = 337, #"Column" = 771, #"Percentage" = 24.91],
					        [#"Row" = 319, #"Column" = 185, #"Percentage" = 94.94],
					        [#"Row" = 679, #"Column" = 520, #"Percentage" = 81.92],
					        [#"Row" = 391, #"Column" = 286, #"Percentage" = 76.97],
					        [#"Row" = 790, #"Column" = 930, #"Percentage" = 4.42],
					        [#"Row" = 366, #"Column" = 585, #"Percentage" = 88.43],
					        [#"Row" = 19, #"Column" = 261, #"Percentage" = 23.14],
					        [#"Row" = 141, #"Column" = 181, #"Percentage" = 9.17],
					        [#"Row" = 851, #"Column" = 585, #"Percentage" = 55.88],
					        [#"Row" = 101, #"Column" = 856, #"Percentage" = 76.85],
					        [#"Row" = 400, #"Column" = 598, #"Percentage" = 12.72],
					        [#"Row" = 940, #"Column" = 85, #"Percentage" = 42.53],
					        [#"Row" = 807, #"Column" = 173, #"Percentage" = 6.23],
					        [#"Row" = 913, #"Column" = 938, #"Percentage" = 93.11],
					        [#"Row" = 812, #"Column" = 383, #"Percentage" = 89.31],
					        [#"Row" = 325, #"Column" = 492, #"Percentage" = 46.43],
					        [#"Row" = 970, #"Column" = 561, #"Percentage" = 66.9],
					        [#"Row" = 150, #"Column" = 300, #"Percentage" = 83.87],
					        [#"Row" = 429, #"Column" = 399, #"Percentage" = 91.47],
					        [#"Row" = 71, #"Column" = 130, #"Percentage" = 75.35],
					        [#"Row" = 973, #"Column" = 277, #"Percentage" = 61.57],
					        [#"Row" = 583, #"Column" = 755, #"Percentage" = 11.47],
					        [#"Row" = 747, #"Column" = 781, #"Percentage" = 76.6],
					        [#"Row" = 837, #"Column" = 79, #"Percentage" = 63.31],
					        [#"Row" = 2, #"Column" = 878, #"Percentage" = 64.29],
					        [#"Row" = 573, #"Column" = 949, #"Percentage" = 46.92],
					        [#"Row" = 270, #"Column" = 964, #"Percentage" = 71.66],
					        [#"Row" = 353, #"Column" = 414, #"Percentage" = 71.08],
					        [#"Row" = 49, #"Column" = 891, #"Percentage" = 54.89],
					        [#"Row" = 46, #"Column" = 923, #"Percentage" = 31.09],
					        [#"Row" = 633, #"Column" = 973, #"Percentage" = 65.12],
					        [#"Row" = 421, #"Column" = 422, #"Percentage" = 61.68],
					        [#"Row" = 51, #"Column" = 395, #"Percentage" = 10.98],
					        [#"Row" = 976, #"Column" = 638, #"Percentage" = 32.85],
					        [#"Row" = 437, #"Column" = 606, #"Percentage" = 63.11],
					        [#"Row" = 950, #"Column" = 422, #"Percentage" = 96.69],
					        [#"Row" = 38, #"Column" = 60, #"Percentage" = 0.32],
					        [#"Row" = 385, #"Column" = 82, #"Percentage" = 71.26],
					        [#"Row" = 792, #"Column" = 251, #"Percentage" = 89.01],
					        [#"Row" = 958, #"Column" = 787, #"Percentage" = 43.14],
					        [#"Row" = 586, #"Column" = 842, #"Percentage" = 57.39],
					        [#"Row" = 460, #"Column" = 515, #"Percentage" = 69.85],
					        [#"Row" = 271, #"Column" = 467, #"Percentage" = 42.55],
					        [#"Row" = 943, #"Column" = 341, #"Percentage" = 48.27],
					        [#"Row" = 492, #"Column" = 625, #"Percentage" = 1.53],
					        [#"Row" = 362, #"Column" = 942, #"Percentage" = 12.74],
					        [#"Row" = 995, #"Column" = 444, #"Percentage" = 33.17],
					        [#"Row" = 152, #"Column" = 625, #"Percentage" = 70.46],
					        [#"Row" = 254, #"Column" = 462, #"Percentage" = 34.19],
					        [#"Row" = 870, #"Column" = 476, #"Percentage" = 26.09],
					        [#"Row" = 360, #"Column" = 286, #"Percentage" = 77.93],
					        [#"Row" = 795, #"Column" = 545, #"Percentage" = 40.86],
					        [#"Row" = 710, #"Column" = 172, #"Percentage" = 41.7],
					        [#"Row" = 868, #"Column" = 925, #"Percentage" = 84.83],
					        [#"Row" = 406, #"Column" = 184, #"Percentage" = 22.45],
					        [#"Row" = 774, #"Column" = 274, #"Percentage" = 34.17],
					        [#"Row" = 749, #"Column" = 386, #"Percentage" = 21.81],
					        [#"Row" = 489, #"Column" = 395, #"Percentage" = 78.12],
					        [#"Row" = 741, #"Column" = 383, #"Percentage" = 74.61],
					        [#"Row" = 468, #"Column" = 411, #"Percentage" = 52.98],
					        [#"Row" = 630, #"Column" = 886, #"Percentage" = 31.34],
					        [#"Row" = 852, #"Column" = 227, #"Percentage" = 15.76],
					        [#"Row" = 808, #"Column" = 226, #"Percentage" = 95.34],
					        [#"Row" = 198, #"Column" = 636, #"Percentage" = 78.06],
					        [#"Row" = 703, #"Column" = 642, #"Percentage" = 66.43],
					        [#"Row" = 273, #"Column" = 133, #"Percentage" = 56.11],
					        [#"Row" = 778, #"Column" = 52, #"Percentage" = 14.94],
					        [#"Row" = 514, #"Column" = 995, #"Percentage" = 79.98],
					        [#"Row" = 762, #"Column" = 25, #"Percentage" = 86.55],
					        [#"Row" = 995, #"Column" = 405, #"Percentage" = 82.56],
					        [#"Row" = 184, #"Column" = 797, #"Percentage" = 26.26],
					        [#"Row" = 663, #"Column" = 704, #"Percentage" = 60.41],
					        [#"Row" = 440, #"Column" = 752, #"Percentage" = 40.18],
					        [#"Row" = 665, #"Column" = 517, #"Percentage" = 36.97],
					        [#"Row" = 868, #"Column" = 810, #"Percentage" = 90.83],
					        [#"Row" = 468, #"Column" = 749, #"Percentage" = 20.38],
					        [#"Row" = 557, #"Column" = 820, #"Percentage" = 74.06],
					        [#"Row" = 308, #"Column" = 347, #"Percentage" = 26.93],
					        [#"Row" = 111, #"Column" = 659, #"Percentage" = 67.14],
					        [#"Row" = 465, #"Column" = 154, #"Percentage" = 2.86],
					        [#"Row" = 304, #"Column" = 917, #"Percentage" = 61.05],
					        [#"Row" = 204, #"Column" = 746, #"Percentage" = 34.57],
					        [#"Row" = 169, #"Column" = 864, #"Percentage" = 74.69],
					        [#"Row" = 750, #"Column" = 618, #"Percentage" = 67.53],
					        [#"Row" = 340, #"Column" = 448, #"Percentage" = 5.38],
					        [#"Row" = 906, #"Column" = 858, #"Percentage" = 92.64],
					        [#"Row" = 794, #"Column" = 389, #"Percentage" = 59.96],
					        [#"Row" = 314, #"Column" = 350, #"Percentage" = 1.32],
					        [#"Row" = 991, #"Column" = 230, #"Percentage" = 89.97],
					        [#"Row" = 800, #"Column" = 129, #"Percentage" = 33.29],
					        [#"Row" = 884, #"Column" = 967, #"Percentage" = 95.41],
					        [#"Row" = 628, #"Column" = 926, #"Percentage" = 86.75],
					        [#"Row" = 141, #"Column" = 552, #"Percentage" = 89.06],
					        [#"Row" = 135, #"Column" = 590, #"Percentage" = 25.8],
					        [#"Row" = 374, #"Column" = 706, #"Percentage" = 15.05],
					        [#"Row" = 9, #"Column" = 749, #"Percentage" = 1.56],
					        [#"Row" = 792, #"Column" = 218, #"Percentage" = 51.99],
					        [#"Row" = 427, #"Column" = 871, #"Percentage" = 98.73],
					        [#"Row" = 374, #"Column" = 392, #"Percentage" = 40.19],
					        [#"Row" = 882, #"Column" = 750, #"Percentage" = 22.3],
					        [#"Row" = 42, #"Column" = 742, #"Percentage" = 59.1],
					        [#"Row" = 135, #"Column" = 692, #"Percentage" = 70.89],
					        [#"Row" = 90, #"Column" = 305, #"Percentage" = 56.7],
					        [#"Row" = 461, #"Column" = 775, #"Percentage" = 94.17],
					        [#"Row" = 416, #"Column" = 264, #"Percentage" = 10.8],
					        [#"Row" = 981, #"Column" = 751, #"Percentage" = 95.16],
					        [#"Row" = 89, #"Column" = 380, #"Percentage" = 18.32],
					        [#"Row" = 935, #"Column" = 804, #"Percentage" = 95.65],
					        [#"Row" = 886, #"Column" = 78, #"Percentage" = 34.31],
					        [#"Row" = 512, #"Column" = 925, #"Percentage" = 15.57],
					        [#"Row" = 164, #"Column" = 911, #"Percentage" = 60.98],
					        [#"Row" = 452, #"Column" = 667, #"Percentage" = 35.13],
					        [#"Row" = 850, #"Column" = 967, #"Percentage" = 72.88],
					        [#"Row" = 198, #"Column" = 188, #"Percentage" = 32.41],
					        [#"Row" = 338, #"Column" = 688, #"Percentage" = 42.9],
					        [#"Row" = 764, #"Column" = 359, #"Percentage" = 55.24],
					        [#"Row" = 902, #"Column" = 799, #"Percentage" = 52.32],
					        [#"Row" = 722, #"Column" = 529, #"Percentage" = 41.1],
					        [#"Row" = 872, #"Column" = 354, #"Percentage" = 84.41],
					        [#"Row" = 128, #"Column" = 394, #"Percentage" = 99.53],
					        [#"Row" = 665, #"Column" = 623, #"Percentage" = 89.57],
					        [#"Row" = 269, #"Column" = 783, #"Percentage" = 85.88],
					        [#"Row" = 157, #"Column" = 522, #"Percentage" = 95.02],
					        [#"Row" = 516, #"Column" = 959, #"Percentage" = 88.22],
					        [#"Row" = 522, #"Column" = 532, #"Percentage" = 51.39],
					        [#"Row" = 842, #"Column" = 435, #"Percentage" = 27.68],
					        [#"Row" = 747, #"Column" = 213, #"Percentage" = 95.63],
					        [#"Row" = 70, #"Column" = 784, #"Percentage" = 73.51],
					        [#"Row" = 147, #"Column" = 7, #"Percentage" = 67.86],
					        [#"Row" = 802, #"Column" = 489, #"Percentage" = 28.0],
					        [#"Row" = 377, #"Column" = 458, #"Percentage" = 0.91],
					        [#"Row" = 853, #"Column" = 234, #"Percentage" = 36.5],
					        [#"Row" = 321, #"Column" = 229, #"Percentage" = 74.97],
					        [#"Row" = 51, #"Column" = 806, #"Percentage" = 23.8],
					        [#"Row" = 171, #"Column" = 731, #"Percentage" = 57.65],
					        [#"Row" = 708, #"Column" = 731, #"Percentage" = 69.31],
					        [#"Row" = 768, #"Column" = 37, #"Percentage" = 32.83],
					        [#"Row" = 756, #"Column" = 951, #"Percentage" = 1.53],
					        [#"Row" = 608, #"Column" = 255, #"Percentage" = 92.52],
					        [#"Row" = 598, #"Column" = 123, #"Percentage" = 26.78],
					        [#"Row" = 587, #"Column" = 766, #"Percentage" = 30.37],
					        [#"Row" = 400, #"Column" = 123, #"Percentage" = 80.05],
					        [#"Row" = 966, #"Column" = 114, #"Percentage" = 57.52],
					        [#"Row" = 863, #"Column" = 263, #"Percentage" = 12.24],
					        [#"Row" = 878, #"Column" = 514, #"Percentage" = 28.07],
					        [#"Row" = 275, #"Column" = 20, #"Percentage" = 77.8],
					        [#"Row" = 349, #"Column" = 768, #"Percentage" = 59.91],
					        [#"Row" = 85, #"Column" = 842, #"Percentage" = 99.66],
					        [#"Row" = 698, #"Column" = 8, #"Percentage" = 14.45],
					        [#"Row" = 533, #"Column" = 343, #"Percentage" = 42.41],
					        [#"Row" = 705, #"Column" = 981, #"Percentage" = 51.15],
					        [#"Row" = 349, #"Column" = 914, #"Percentage" = 15.78],
					        [#"Row" = 560, #"Column" = 850, #"Percentage" = 76.79],
					        [#"Row" = 445, #"Column" = 985, #"Percentage" = 96.78],
					        [#"Row" = 243, #"Column" = 705, #"Percentage" = 5.64],
					        [#"Row" = 411, #"Column" = 755, #"Percentage" = 50.06],
					        [#"Row" = 173, #"Column" = 564, #"Percentage" = 87.6],
					        [#"Row" = 581, #"Column" = 782, #"Percentage" = 79.44],
					        [#"Row" = 556, #"Column" = 688, #"Percentage" = 31.01],
					        [#"Row" = 816, #"Column" = 797, #"Percentage" = 1.14],
					        [#"Row" = 591, #"Column" = 25, #"Percentage" = 65.77],
					        [#"Row" = 576, #"Column" = 167, #"Percentage" = 15.32],
					        [#"Row" = 658, #"Column" = 136, #"Percentage" = 50.51],
					        [#"Row" = 177, #"Column" = 603, #"Percentage" = 34.01],
					        [#"Row" = 691, #"Column" = 33, #"Percentage" = 70.97],
					        [#"Row" = 291, #"Column" = 610, #"Percentage" = 82.01],
					        [#"Row" = 970, #"Column" = 793, #"Percentage" = 35.03],
					        [#"Row" = 771, #"Column" = 822, #"Percentage" = 87.98],
					        [#"Row" = 33, #"Column" = 331, #"Percentage" = 66.01],
					        [#"Row" = 402, #"Column" = 608, #"Percentage" = 6.96],
					        [#"Row" = 500, #"Column" = 796, #"Percentage" = 4.94],
					        [#"Row" = 387, #"Column" = 952, #"Percentage" = 53.1],
					        [#"Row" = 863, #"Column" = 201, #"Percentage" = 93.26],
					        [#"Row" = 662, #"Column" = 882, #"Percentage" = 37.02],
					        [#"Row" = 809, #"Column" = 423, #"Percentage" = 0.02],
					        [#"Row" = 489, #"Column" = 646, #"Percentage" = 15.61],
					        [#"Row" = 291, #"Column" = 425, #"Percentage" = 41.08],
					        [#"Row" = 386, #"Column" = 986, #"Percentage" = 30.94],
					        [#"Row" = 785, #"Column" = 551, #"Percentage" = 52.0],
					        [#"Row" = 913, #"Column" = 261, #"Percentage" = 90.64],
					        [#"Row" = 643, #"Column" = 86, #"Percentage" = 77.54],
					        [#"Row" = 501, #"Column" = 455, #"Percentage" = 8.91],
					        [#"Row" = 483, #"Column" = 681, #"Percentage" = 64.54],
					        [#"Row" = 153, #"Column" = 123, #"Percentage" = 27.54],
					        [#"Row" = 335, #"Column" = 298, #"Percentage" = 96.87],
					        [#"Row" = 426, #"Column" = 928, #"Percentage" = 48.83],
					        [#"Row" = 728, #"Column" = 241, #"Percentage" = 71.87],
					        [#"Row" = 595, #"Column" = 121, #"Percentage" = 54.43],
					        [#"Row" = 4, #"Column" = 50, #"Percentage" = 69.5],
					        [#"Row" = 308, #"Column" = 117, #"Percentage" = 78.84],
					        [#"Row" = 554, #"Column" = 297, #"Percentage" = 67.58],
					        [#"Row" = 348, #"Column" = 183, #"Percentage" = 2.19],
					        [#"Row" = 845, #"Column" = 742, #"Percentage" = 48.45],
					        [#"Row" = 801, #"Column" = 139, #"Percentage" = 93.15],
					        [#"Row" = 930, #"Column" = 900, #"Percentage" = 86.53],
					        [#"Row" = 624, #"Column" = 530, #"Percentage" = 6.78],
					        [#"Row" = 494, #"Column" = 334, #"Percentage" = 73.44],
					        [#"Row" = 502, #"Column" = 243, #"Percentage" = 36.46],
					        [#"Row" = 689, #"Column" = 380, #"Percentage" = 35.28],
					        [#"Row" = 746, #"Column" = 38, #"Percentage" = 63.8],
					        [#"Row" = 912, #"Column" = 120, #"Percentage" = 39.84],
					        [#"Row" = 217, #"Column" = 866, #"Percentage" = 22.14],
					        [#"Row" = 180, #"Column" = 149, #"Percentage" = 14.08],
					        [#"Row" = 635, #"Column" = 537, #"Percentage" = 74.34],
					        [#"Row" = 149, #"Column" = 877, #"Percentage" = 59.53],
					        [#"Row" = 891, #"Column" = 891, #"Percentage" = 10.72],
					        [#"Row" = 369, #"Column" = 661, #"Percentage" = 97.14],
					        [#"Row" = 950, #"Column" = 606, #"Percentage" = 59.84],
					        [#"Row" = 81, #"Column" = 256, #"Percentage" = 95.72],
					        [#"Row" = 876, #"Column" = 891, #"Percentage" = 45.6],
					        [#"Row" = 258, #"Column" = 14, #"Percentage" = 35.39],
					        [#"Row" = 806, #"Column" = 395, #"Percentage" = 23.64],
					        [#"Row" = 969, #"Column" = 8, #"Percentage" = 66.97],
					        [#"Row" = 305, #"Column" = 296, #"Percentage" = 4.47],
					        [#"Row" = 226, #"Column" = 69, #"Percentage" = 76.11],
					        [#"Row" = 594, #"Column" = 901, #"Percentage" = 94.62],
					        [#"Row" = 650, #"Column" = 659, #"Percentage" = 11.59],
					        [#"Row" = 49, #"Column" = 125, #"Percentage" = 6.29],
					        [#"Row" = 982, #"Column" = 557, #"Percentage" = 37.27],
					        [#"Row" = 90, #"Column" = 930, #"Percentage" = 61.48],
					        [#"Row" = 261, #"Column" = 311, #"Percentage" = 24.61],
					        [#"Row" = 633, #"Column" = 84, #"Percentage" = 10.24],
					        [#"Row" = 862, #"Column" = 810, #"Percentage" = 36.18],
					        [#"Row" = 433, #"Column" = 162, #"Percentage" = 55.38],
					        [#"Row" = 997, #"Column" = 409, #"Percentage" = 27.53],
					        [#"Row" = 159, #"Column" = 162, #"Percentage" = 20.37],
					        [#"Row" = 428, #"Column" = 58, #"Percentage" = 21.15],
					        [#"Row" = 467, #"Column" = 808, #"Percentage" = 85.01],
					        [#"Row" = 444, #"Column" = 824, #"Percentage" = 65.19],
					        [#"Row" = 815, #"Column" = 630, #"Percentage" = 67.66],
					        [#"Row" = 274, #"Column" = 730, #"Percentage" = 41.71],
					        [#"Row" = 443, #"Column" = 874, #"Percentage" = 50.19],
					        [#"Row" = 440, #"Column" = 658, #"Percentage" = 84.4],
					        [#"Row" = 184, #"Column" = 248, #"Percentage" = 26.67],
					        [#"Row" = 633, #"Column" = 464, #"Percentage" = 34.39],
					        [#"Row" = 725, #"Column" = 910, #"Percentage" = 85.83],
					        [#"Row" = 635, #"Column" = 903, #"Percentage" = 87.93],
					        [#"Row" = 631, #"Column" = 860, #"Percentage" = 58.13],
					        [#"Row" = 13, #"Column" = 71, #"Percentage" = 50.69],
					        [#"Row" = 294, #"Column" = 637, #"Percentage" = 50.57],
					        [#"Row" = 851, #"Column" = 586, #"Percentage" = 70.91],
					        [#"Row" = 975, #"Column" = 635, #"Percentage" = 62.29],
					        [#"Row" = 571, #"Column" = 243, #"Percentage" = 3.95],
					        [#"Row" = 631, #"Column" = 746, #"Percentage" = 29.47],
					        [#"Row" = 186, #"Column" = 540, #"Percentage" = 76.95],
					        [#"Row" = 135, #"Column" = 591, #"Percentage" = 85.48],
					        [#"Row" = 693, #"Column" = 279, #"Percentage" = 49.54],
					        [#"Row" = 45, #"Column" = 271, #"Percentage" = 3.23],
					        [#"Row" = 773, #"Column" = 592, #"Percentage" = 75.6],
					        [#"Row" = 452, #"Column" = 467, #"Percentage" = 62.56],
					        [#"Row" = 659, #"Column" = 219, #"Percentage" = 42.27],
					        [#"Row" = 257, #"Column" = 632, #"Percentage" = 20.79],
					        [#"Row" = 73, #"Column" = 318, #"Percentage" = 81.31],
					        [#"Row" = 850, #"Column" = 570, #"Percentage" = 71.9],
					        [#"Row" = 606, #"Column" = 568, #"Percentage" = 80.83],
					        [#"Row" = 137, #"Column" = 966, #"Percentage" = 85.83],
					        [#"Row" = 903, #"Column" = 138, #"Percentage" = 46.52],
					        [#"Row" = 905, #"Column" = 836, #"Percentage" = 41.04],
					        [#"Row" = 613, #"Column" = 520, #"Percentage" = 77.16],
					        [#"Row" = 837, #"Column" = 841, #"Percentage" = 35.59],
					        [#"Row" = 591, #"Column" = 350, #"Percentage" = 7.84],
					        [#"Row" = 4, #"Column" = 479, #"Percentage" = 36.85],
					        [#"Row" = 831, #"Column" = 271, #"Percentage" = 50.54],
					        [#"Row" = 657, #"Column" = 979, #"Percentage" = 60.41],
					        [#"Row" = 624, #"Column" = 734, #"Percentage" = 0.59],
					        [#"Row" = 585, #"Column" = 377, #"Percentage" = 92.68],
					        [#"Row" = 181, #"Column" = 975, #"Percentage" = 56.06],
					        [#"Row" = 954, #"Column" = 374, #"Percentage" = 44.38],
					        [#"Row" = 839, #"Column" = 257, #"Percentage" = 25.79],
					        [#"Row" = 910, #"Column" = 817, #"Percentage" = 83.63],
					        [#"Row" = 523, #"Column" = 555, #"Percentage" = 53.03],
					        [#"Row" = 24, #"Column" = 760, #"Percentage" = 32.98],
					        [#"Row" = 789, #"Column" = 446, #"Percentage" = 53.08],
					        [#"Row" = 501, #"Column" = 979, #"Percentage" = 39.02],
					        [#"Row" = 832, #"Column" = 332, #"Percentage" = 89.3],
					        [#"Row" = 821, #"Column" = 812, #"Percentage" = 95.63],
					        [#"Row" = 444, #"Column" = 528, #"Percentage" = 54.14],
					        [#"Row" = 180, #"Column" = 600, #"Percentage" = 45.56],
					        [#"Row" = 153, #"Column" = 587, #"Percentage" = 93.97],
					        [#"Row" = 382, #"Column" = 305, #"Percentage" = 78.89],
					        [#"Row" = 695, #"Column" = 360, #"Percentage" = 94.53],
					        [#"Row" = 562, #"Column" = 990, #"Percentage" = 68.75],
					        [#"Row" = 345, #"Column" = 188, #"Percentage" = 23.99],
					        [#"Row" = 5, #"Column" = 324, #"Percentage" = 83.59],
					        [#"Row" = 460, #"Column" = 2, #"Percentage" = 51.29],
					        [#"Row" = 261, #"Column" = 296, #"Percentage" = 7.65],
					        [#"Row" = 587, #"Column" = 601, #"Percentage" = 7.41],
					        [#"Row" = 645, #"Column" = 498, #"Percentage" = 53.73],
					        [#"Row" = 588, #"Column" = 994, #"Percentage" = 7.25],
					        [#"Row" = 306, #"Column" = 204, #"Percentage" = 74.06],
					        [#"Row" = 320, #"Column" = 698, #"Percentage" = 44.86],
					        [#"Row" = 743, #"Column" = 432, #"Percentage" = 15.25],
					        [#"Row" = 711, #"Column" = 985, #"Percentage" = 15.12],
					        [#"Row" = 780, #"Column" = 686, #"Percentage" = 79.67],
					        [#"Row" = 64, #"Column" = 457, #"Percentage" = 57.5],
					        [#"Row" = 658, #"Column" = 569, #"Percentage" = 85.85],
					        [#"Row" = 34, #"Column" = 299, #"Percentage" = 2.16],
					        [#"Row" = 763, #"Column" = 84, #"Percentage" = 34.08],
					        [#"Row" = 815, #"Column" = 110, #"Percentage" = 9.92],
					        [#"Row" = 908, #"Column" = 160, #"Percentage" = 29.42],
					        [#"Row" = 585, #"Column" = 936, #"Percentage" = 67.38],
					        [#"Row" = 102, #"Column" = 476, #"Percentage" = 46.79],
					        [#"Row" = 76, #"Column" = 554, #"Percentage" = 74.18],
					        [#"Row" = 380, #"Column" = 696, #"Percentage" = 48.68],
					        [#"Row" = 914, #"Column" = 398, #"Percentage" = 32.7],
					        [#"Row" = 684, #"Column" = 979, #"Percentage" = 91.94],
					        [#"Row" = 460, #"Column" = 827, #"Percentage" = 95.38],
					        [#"Row" = 190, #"Column" = 672, #"Percentage" = 41.13],
					        [#"Row" = 961, #"Column" = 841, #"Percentage" = 7.19],
					        [#"Row" = 928, #"Column" = 137, #"Percentage" = 70.62],
					        [#"Row" = 225, #"Column" = 682, #"Percentage" = 23.38],
					        [#"Row" = 746, #"Column" = 900, #"Percentage" = 64.08],
					        [#"Row" = 548, #"Column" = 873, #"Percentage" = 70.9],
					        [#"Row" = 4, #"Column" = 800, #"Percentage" = 23.86],
					        [#"Row" = 122, #"Column" = 237, #"Percentage" = 62.44],
					        [#"Row" = 246, #"Column" = 409, #"Percentage" = 77.67],
					        [#"Row" = 740, #"Column" = 544, #"Percentage" = 34.22],
					        [#"Row" = 857, #"Column" = 671, #"Percentage" = 26.41],
					        [#"Row" = 952, #"Column" = 296, #"Percentage" = 6.22],
					        [#"Row" = 16, #"Column" = 623, #"Percentage" = 66.71],
					        [#"Row" = 203, #"Column" = 600, #"Percentage" = 61.55],
					        [#"Row" = 159, #"Column" = 856, #"Percentage" = 71.16],
					        [#"Row" = 99, #"Column" = 421, #"Percentage" = 87.68],
					        [#"Row" = 453, #"Column" = 376, #"Percentage" = 89.58],
					        [#"Row" = 886, #"Column" = 287, #"Percentage" = 73.63],
					        [#"Row" = 64, #"Column" = 997, #"Percentage" = 36.34],
					        [#"Row" = 343, #"Column" = 178, #"Percentage" = 35.31],
					        [#"Row" = 447, #"Column" = 546, #"Percentage" = 5.69],
					        [#"Row" = 726, #"Column" = 521, #"Percentage" = 10.6],
					        [#"Row" = 5, #"Column" = 262, #"Percentage" = 91.69],
					        [#"Row" = 221, #"Column" = 857, #"Percentage" = 64.16],
					        [#"Row" = 180, #"Column" = 660, #"Percentage" = 35.95],
					        [#"Row" = 790, #"Column" = 232, #"Percentage" = 75.89],
					        [#"Row" = 982, #"Column" = 950, #"Percentage" = 35.52],
					        [#"Row" = 749, #"Column" = 56, #"Percentage" = 55.37],
					        [#"Row" = 460, #"Column" = 25, #"Percentage" = 65.56],
					        [#"Row" = 895, #"Column" = 762, #"Percentage" = 68.04],
					        [#"Row" = 924, #"Column" = 833, #"Percentage" = 7.47],
					        [#"Row" = 33, #"Column" = 223, #"Percentage" = 74.83],
					        [#"Row" = 181, #"Column" = 275, #"Percentage" = 75.12],
					        [#"Row" = 668, #"Column" = 699, #"Percentage" = 40.61],
					        [#"Row" = 820, #"Column" = 16, #"Percentage" = 92.59],
					        [#"Row" = 284, #"Column" = 661, #"Percentage" = 28.42],
					        [#"Row" = 618, #"Column" = 487, #"Percentage" = 99.19],
					        [#"Row" = 244, #"Column" = 60, #"Percentage" = 3.3],
					        [#"Row" = 591, #"Column" = 252, #"Percentage" = 53.77],
					        [#"Row" = 138, #"Column" = 277, #"Percentage" = 80.58],
					        [#"Row" = 874, #"Column" = 949, #"Percentage" = 89.49],
					        [#"Row" = 994, #"Column" = 911, #"Percentage" = 39.12],
					        [#"Row" = 169, #"Column" = 598, #"Percentage" = 76.81],
					        [#"Row" = 996, #"Column" = 5, #"Percentage" = 7.24],
					        [#"Row" = 685, #"Column" = 82, #"Percentage" = 44.8],
					        [#"Row" = 449, #"Column" = 71, #"Percentage" = 28.61],
					        [#"Row" = 894, #"Column" = 162, #"Percentage" = 29.3],
					        [#"Row" = 785, #"Column" = 73, #"Percentage" = 65.15],
					        [#"Row" = 907, #"Column" = 503, #"Percentage" = 93.51],
					        [#"Row" = 861, #"Column" = 635, #"Percentage" = 95.32],
					        [#"Row" = 591, #"Column" = 46, #"Percentage" = 73.24],
					        [#"Row" = 806, #"Column" = 706, #"Percentage" = 36.3],
					        [#"Row" = 301, #"Column" = 121, #"Percentage" = 33.6],
					        [#"Row" = 804, #"Column" = 594, #"Percentage" = 77.84],
					        [#"Row" = 262, #"Column" = 745, #"Percentage" = 85.16],
					        [#"Row" = 683, #"Column" = 465, #"Percentage" = 15.56],
					        [#"Row" = 364, #"Column" = 324, #"Percentage" = 68.95],
					        [#"Row" = 364, #"Column" = 100, #"Percentage" = 44.55],
					        [#"Row" = 119, #"Column" = 85, #"Percentage" = 53.01]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Row", Int64.Type},
					        {"Column", Int64.Type},
					        {"Percentage", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table