table 'Extract_Sheet1 (radial_bar_chart_data)'
	lineageTag: 8c32d471-c6cf-46b8-9338-3dd74baa3f96

	column StoreType
		dataType: string
		lineageTag: b7250563-02a8-48af-9d8f-9f56317b1eb4
		summarizeBy: none
		sourceColumn: StoreType

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: e5e12021-c038-45b2-a623-056f9d869747
		summarizeBy: sum
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	column Ratio
		dataType: double
		formatString: General Number
		lineageTag: 994a5a39-3d81-4c73-a0b1-b7673b7e1bed
		summarizeBy: sum
		sourceColumn: Ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Path
		dataType: int64
		formatString: 0
		lineageTag: c9cb66db-9b55-45be-bdfd-7c9cc607cb04
		summarizeBy: sum
		sourceColumn: Path

		annotation SummarizationSetBy = Automatic

	partition 'Extract_Sheet1 (radial_bar_chart_data)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"StoreType" = "cnet", #"Order" = 154, #"Ratio" = 521.25, #"Path" = 737],
					        [#"StoreType" = "descriptions", #"Order" = 158, #"Ratio" = 637.21, #"Path" = 588],
					        [#"StoreType" = "necessarily", #"Order" = 810, #"Ratio" = 350.46, #"Path" = 154],
					        [#"StoreType" = "bath", #"Order" = 812, #"Ratio" = 483.83, #"Path" = 546],
					        [#"StoreType" = "secondary", #"Order" = 533, #"Ratio" = 879.77, #"Path" = 788],
					        [#"StoreType" = "specified", #"Order" = 103, #"Ratio" = 795.01, #"Path" = 633],
					        [#"StoreType" = "specification", #"Order" = 229, #"Ratio" = 894.58, #"Path" = 543],
					        [#"StoreType" = "concern", #"Order" = 179, #"Ratio" = 171.83, #"Path" = 477],
					        [#"StoreType" = "moments", #"Order" = 734, #"Ratio" = 205.25, #"Path" = 499],
					        [#"StoreType" = "sierra", #"Order" = 562, #"Ratio" = 550.52, #"Path" = 285],
					        [#"StoreType" = "nova", #"Order" = 822, #"Ratio" = 593.81, #"Path" = 358],
					        [#"StoreType" = "sleep", #"Order" = 294, #"Ratio" = 346.32, #"Path" = 856],
					        [#"StoreType" = "struggle", #"Order" = 363, #"Ratio" = 44.88, #"Path" = 976],
					        [#"StoreType" = "mice", #"Order" = 774, #"Ratio" = 8.44, #"Path" = 6],
					        [#"StoreType" = "storage", #"Order" = 625, #"Ratio" = 165.03, #"Path" = 658],
					        [#"StoreType" = "zip", #"Order" = 930, #"Ratio" = 449.09, #"Path" = 835],
					        [#"StoreType" = "tool", #"Order" = 875, #"Ratio" = 854.76, #"Path" = 919],
					        [#"StoreType" = "soon", #"Order" = 470, #"Ratio" = 840.77, #"Path" = 363],
					        [#"StoreType" = "electricity", #"Order" = 55, #"Ratio" = 208.01, #"Path" = 751],
					        [#"StoreType" = "gardening", #"Order" = 715, #"Ratio" = 130.78, #"Path" = 493],
					        [#"StoreType" = "clerk", #"Order" = 105, #"Ratio" = 186.58, #"Path" = 684],
					        [#"StoreType" = "yeah", #"Order" = 437, #"Ratio" = 977.21, #"Path" = 215],
					        [#"StoreType" = "entity", #"Order" = 911, #"Ratio" = 197.29, #"Path" = 495],
					        [#"StoreType" = "slowly", #"Order" = 617, #"Ratio" = 227.43, #"Path" = 451],
					        [#"StoreType" = "broke", #"Order" = 834, #"Ratio" = 172.41, #"Path" = 691],
					        [#"StoreType" = "visual", #"Order" = 665, #"Ratio" = 945.3, #"Path" = 268],
					        [#"StoreType" = "pulse", #"Order" = 302, #"Ratio" = 225.34, #"Path" = 871],
					        [#"StoreType" = "cameras", #"Order" = 401, #"Ratio" = 577.09, #"Path" = 732],
					        [#"StoreType" = "engine", #"Order" = 865, #"Ratio" = 562.77, #"Path" = 488],
					        [#"StoreType" = "anywhere", #"Order" = 691, #"Ratio" = 388.22, #"Path" = 263],
					        [#"StoreType" = "president", #"Order" = 297, #"Ratio" = 565.39, #"Path" = 8],
					        [#"StoreType" = "children", #"Order" = 276, #"Ratio" = 694.44, #"Path" = 238],
					        [#"StoreType" = "platinum", #"Order" = 34, #"Ratio" = 327.68, #"Path" = 994],
					        [#"StoreType" = "chicken", #"Order" = 654, #"Ratio" = 34.63, #"Path" = 772],
					        [#"StoreType" = "twelve", #"Order" = 912, #"Ratio" = 206.0, #"Path" = 192],
					        [#"StoreType" = "potential", #"Order" = 217, #"Ratio" = 83.0, #"Path" = 480],
					        [#"StoreType" = "steering", #"Order" = 81, #"Ratio" = 195.02, #"Path" = 822],
					        [#"StoreType" = "basketball", #"Order" = 406, #"Ratio" = 743.3, #"Path" = 424],
					        [#"StoreType" = "accommodations", #"Order" = 572, #"Ratio" = 41.39, #"Path" = 351],
					        [#"StoreType" = "installing", #"Order" = 439, #"Ratio" = 742.37, #"Path" = 1],
					        [#"StoreType" = "attacks", #"Order" = 924, #"Ratio" = 600.26, #"Path" = 359],
					        [#"StoreType" = "revised", #"Order" = 704, #"Ratio" = 347.85, #"Path" = 66],
					        [#"StoreType" = "output", #"Order" = 170, #"Ratio" = 122.77, #"Path" = 310],
					        [#"StoreType" = "talking", #"Order" = 336, #"Ratio" = 902.09, #"Path" = 498],
					        [#"StoreType" = "heads", #"Order" = 794, #"Ratio" = 857.46, #"Path" = 648],
					        [#"StoreType" = "assessment", #"Order" = 804, #"Ratio" = 489.52, #"Path" = 913],
					        [#"StoreType" = "obligations", #"Order" = 901, #"Ratio" = 997.73, #"Path" = 646],
					        [#"StoreType" = "current", #"Order" = 690, #"Ratio" = 756.2, #"Path" = 912],
					        [#"StoreType" = "hip", #"Order" = 5, #"Ratio" = 43.3, #"Path" = 85],
					        [#"StoreType" = "oregon", #"Order" = 537, #"Ratio" = 709.01, #"Path" = 41],
					        [#"StoreType" = "jackson", #"Order" = 405, #"Ratio" = 159.94, #"Path" = 4],
					        [#"StoreType" = "literature", #"Order" = 178, #"Ratio" = 572.37, #"Path" = 330],
					        [#"StoreType" = "miller", #"Order" = 567, #"Ratio" = 7.26, #"Path" = 965],
					        [#"StoreType" = "useful", #"Order" = 235, #"Ratio" = 782.79, #"Path" = 956],
					        [#"StoreType" = "mechanical", #"Order" = 606, #"Ratio" = 901.84, #"Path" = 103],
					        [#"StoreType" = "structure", #"Order" = 665, #"Ratio" = 387.9, #"Path" = 263],
					        [#"StoreType" = "harvard", #"Order" = 699, #"Ratio" = 800.61, #"Path" = 386],
					        [#"StoreType" = "site", #"Order" = 534, #"Ratio" = 842.67, #"Path" = 667],
					        [#"StoreType" = "dev", #"Order" = 126, #"Ratio" = 930.47, #"Path" = 865],
					        [#"StoreType" = "alerts", #"Order" = 267, #"Ratio" = 421.86, #"Path" = 745],
					        [#"StoreType" = "detroit", #"Order" = 772, #"Ratio" = 736.13, #"Path" = 126],
					        [#"StoreType" = "bet", #"Order" = 434, #"Ratio" = 998.18, #"Path" = 373],
					        [#"StoreType" = "obvious", #"Order" = 804, #"Ratio" = 330.02, #"Path" = 63],
					        [#"StoreType" = "political", #"Order" = 998, #"Ratio" = 549.07, #"Path" = 747],
					        [#"StoreType" = "commission", #"Order" = 151, #"Ratio" = 54.31, #"Path" = 932],
					        [#"StoreType" = "study", #"Order" = 737, #"Ratio" = 563.71, #"Path" = 860],
					        [#"StoreType" = "southern", #"Order" = 759, #"Ratio" = 747.45, #"Path" = 94],
					        [#"StoreType" = "vehicle", #"Order" = 165, #"Ratio" = 115.33, #"Path" = 954],
					        [#"StoreType" = "contained", #"Order" = 706, #"Ratio" = 41.89, #"Path" = 373],
					        [#"StoreType" = "residence", #"Order" = 854, #"Ratio" = 576.99, #"Path" = 102],
					        [#"StoreType" = "inc", #"Order" = 198, #"Ratio" = 536.08, #"Path" = 872],
					        [#"StoreType" = "law", #"Order" = 295, #"Ratio" = 326.78, #"Path" = 764],
					        [#"StoreType" = "among", #"Order" = 629, #"Ratio" = 753.6, #"Path" = 501],
					        [#"StoreType" = "cosmetic", #"Order" = 34, #"Ratio" = 518.35, #"Path" = 410],
					        [#"StoreType" = "rich", #"Order" = 883, #"Ratio" = 809.2, #"Path" = 302],
					        [#"StoreType" = "farmer", #"Order" = 953, #"Ratio" = 585.32, #"Path" = 153],
					        [#"StoreType" = "bruce", #"Order" = 85, #"Ratio" = 622.3, #"Path" = 931],
					        [#"StoreType" = "public", #"Order" = 143, #"Ratio" = 555.6, #"Path" = 325],
					        [#"StoreType" = "head", #"Order" = 685, #"Ratio" = 383.17, #"Path" = 379],
					        [#"StoreType" = "instruction", #"Order" = 939, #"Ratio" = 613.17, #"Path" = 719],
					        [#"StoreType" = "fi", #"Order" = 157, #"Ratio" = 832.16, #"Path" = 219],
					        [#"StoreType" = "democratic", #"Order" = 615, #"Ratio" = 604.98, #"Path" = 725],
					        [#"StoreType" = "population", #"Order" = 335, #"Ratio" = 346.52, #"Path" = 283],
					        [#"StoreType" = "bike", #"Order" = 310, #"Ratio" = 399.73, #"Path" = 136],
					        [#"StoreType" = "dry", #"Order" = 477, #"Ratio" = 218.82, #"Path" = 905],
					        [#"StoreType" = "mill", #"Order" = 280, #"Ratio" = 661.84, #"Path" = 601],
					        [#"StoreType" = "telecom", #"Order" = 862, #"Ratio" = 647.61, #"Path" = 810],
					        [#"StoreType" = "furthermore", #"Order" = 547, #"Ratio" = 80.37, #"Path" = 588],
					        [#"StoreType" = "automated", #"Order" = 288, #"Ratio" = 46.01, #"Path" = 261],
					        [#"StoreType" = "earn", #"Order" = 918, #"Ratio" = 272.55, #"Path" = 383],
					        [#"StoreType" = "posted", #"Order" = 606, #"Ratio" = 14.6, #"Path" = 199],
					        [#"StoreType" = "actual", #"Order" = 812, #"Ratio" = 823.17, #"Path" = 380],
					        [#"StoreType" = "pda", #"Order" = 775, #"Ratio" = 148.55, #"Path" = 885],
					        [#"StoreType" = "experienced", #"Order" = 192, #"Ratio" = 564.47, #"Path" = 692],
					        [#"StoreType" = "damage", #"Order" = 599, #"Ratio" = 263.3, #"Path" = 625],
					        [#"StoreType" = "motor", #"Order" = 588, #"Ratio" = 146.62, #"Path" = 912],
					        [#"StoreType" = "sharp", #"Order" = 428, #"Ratio" = 138.61, #"Path" = 962],
					        [#"StoreType" = "yeah", #"Order" = 470, #"Ratio" = 730.66, #"Path" = 657],
					        [#"StoreType" = "owners", #"Order" = 683, #"Ratio" = 148.42, #"Path" = 453],
					        [#"StoreType" = "artist", #"Order" = 659, #"Ratio" = 237.01, #"Path" = 44],
					        [#"StoreType" = "cutting", #"Order" = 68, #"Ratio" = 799.54, #"Path" = 848],
					        [#"StoreType" = "modify", #"Order" = 297, #"Ratio" = 189.17, #"Path" = 146],
					        [#"StoreType" = "singing", #"Order" = 799, #"Ratio" = 523.13, #"Path" = 222],
					        [#"StoreType" = "magazines", #"Order" = 73, #"Ratio" = 599.41, #"Path" = 986],
					        [#"StoreType" = "foreign", #"Order" = 546, #"Ratio" = 710.67, #"Path" = 871],
					        [#"StoreType" = "exposure", #"Order" = 515, #"Ratio" = 512.15, #"Path" = 839],
					        [#"StoreType" = "tickets", #"Order" = 740, #"Ratio" = 662.9, #"Path" = 884],
					        [#"StoreType" = "took", #"Order" = 606, #"Ratio" = 505.11, #"Path" = 247],
					        [#"StoreType" = "jet", #"Order" = 172, #"Ratio" = 506.08, #"Path" = 56],
					        [#"StoreType" = "height", #"Order" = 296, #"Ratio" = 637.32, #"Path" = 629],
					        [#"StoreType" = "jul", #"Order" = 99, #"Ratio" = 809.49, #"Path" = 851],
					        [#"StoreType" = "tank", #"Order" = 861, #"Ratio" = 537.93, #"Path" = 377],
					        [#"StoreType" = "est", #"Order" = 114, #"Ratio" = 345.17, #"Path" = 714],
					        [#"StoreType" = "contribute", #"Order" = 733, #"Ratio" = 381.19, #"Path" = 461],
					        [#"StoreType" = "submit", #"Order" = 611, #"Ratio" = 51.53, #"Path" = 181],
					        [#"StoreType" = "finish", #"Order" = 740, #"Ratio" = 171.08, #"Path" = 960],
					        [#"StoreType" = "producing", #"Order" = 508, #"Ratio" = 650.12, #"Path" = 85],
					        [#"StoreType" = "candy", #"Order" = 441, #"Ratio" = 882.38, #"Path" = 905],
					        [#"StoreType" = "extract", #"Order" = 111, #"Ratio" = 325.45, #"Path" = 668],
					        [#"StoreType" = "bold", #"Order" = 211, #"Ratio" = 980.21, #"Path" = 772],
					        [#"StoreType" = "iii", #"Order" = 47, #"Ratio" = 569.83, #"Path" = 955],
					        [#"StoreType" = "larger", #"Order" = 356, #"Ratio" = 915.39, #"Path" = 923],
					        [#"StoreType" = "limits", #"Order" = 460, #"Ratio" = 857.56, #"Path" = 248],
					        [#"StoreType" = "factor", #"Order" = 534, #"Ratio" = 828.02, #"Path" = 896],
					        [#"StoreType" = "comment", #"Order" = 961, #"Ratio" = 137.22, #"Path" = 580],
					        [#"StoreType" = "channel", #"Order" = 294, #"Ratio" = 428.56, #"Path" = 249],
					        [#"StoreType" = "clients", #"Order" = 586, #"Ratio" = 260.52, #"Path" = 406],
					        [#"StoreType" = "rear", #"Order" = 534, #"Ratio" = 939.6, #"Path" = 599],
					        [#"StoreType" = "tracker", #"Order" = 795, #"Ratio" = 795.7, #"Path" = 637],
					        [#"StoreType" = "pop", #"Order" = 905, #"Ratio" = 437.0, #"Path" = 158],
					        [#"StoreType" = "august", #"Order" = 357, #"Ratio" = 975.06, #"Path" = 329],
					        [#"StoreType" = "doc", #"Order" = 991, #"Ratio" = 311.3, #"Path" = 544],
					        [#"StoreType" = "large", #"Order" = 817, #"Ratio" = 630.79, #"Path" = 275],
					        [#"StoreType" = "any", #"Order" = 189, #"Ratio" = 120.93, #"Path" = 781],
					        [#"StoreType" = "professionals", #"Order" = 983, #"Ratio" = 997.24, #"Path" = 421],
					        [#"StoreType" = "formed", #"Order" = 94, #"Ratio" = 139.98, #"Path" = 421],
					        [#"StoreType" = "establishment", #"Order" = 655, #"Ratio" = 980.42, #"Path" = 641],
					        [#"StoreType" = "develop", #"Order" = 460, #"Ratio" = 105.27, #"Path" = 571],
					        [#"StoreType" = "columns", #"Order" = 842, #"Ratio" = 119.45, #"Path" = 250],
					        [#"StoreType" = "walls", #"Order" = 427, #"Ratio" = 846.32, #"Path" = 142],
					        [#"StoreType" = "household", #"Order" = 791, #"Ratio" = 165.45, #"Path" = 875],
					        [#"StoreType" = "study", #"Order" = 631, #"Ratio" = 538.11, #"Path" = 970],
					        [#"StoreType" = "stones", #"Order" = 103, #"Ratio" = 326.44, #"Path" = 913],
					        [#"StoreType" = "hosting", #"Order" = 799, #"Ratio" = 867.26, #"Path" = 315],
					        [#"StoreType" = "afraid", #"Order" = 144, #"Ratio" = 225.24, #"Path" = 960],
					        [#"StoreType" = "formed", #"Order" = 634, #"Ratio" = 536.4, #"Path" = 498],
					        [#"StoreType" = "obligation", #"Order" = 682, #"Ratio" = 311.69, #"Path" = 474],
					        [#"StoreType" = "bad", #"Order" = 684, #"Ratio" = 36.09, #"Path" = 202],
					        [#"StoreType" = "helpful", #"Order" = 347, #"Ratio" = 281.0, #"Path" = 145],
					        [#"StoreType" = "oakland", #"Order" = 170, #"Ratio" = 279.74, #"Path" = 577],
					        [#"StoreType" = "jackson", #"Order" = 613, #"Ratio" = 981.29, #"Path" = 584],
					        [#"StoreType" = "describes", #"Order" = 601, #"Ratio" = 24.76, #"Path" = 20],
					        [#"StoreType" = "price", #"Order" = 7, #"Ratio" = 957.44, #"Path" = 304],
					        [#"StoreType" = "diversity", #"Order" = 719, #"Ratio" = 263.14, #"Path" = 355],
					        [#"StoreType" = "wife", #"Order" = 706, #"Ratio" = 162.97, #"Path" = 856],
					        [#"StoreType" = "bodies", #"Order" = 661, #"Ratio" = 857.78, #"Path" = 858],
					        [#"StoreType" = "exposure", #"Order" = 420, #"Ratio" = 735.31, #"Path" = 800],
					        [#"StoreType" = "biography", #"Order" = 57, #"Ratio" = 936.59, #"Path" = 907],
					        [#"StoreType" = "veterans", #"Order" = 439, #"Ratio" = 30.73, #"Path" = 176],
					        [#"StoreType" = "independence", #"Order" = 922, #"Ratio" = 321.38, #"Path" = 923],
					        [#"StoreType" = "clinical", #"Order" = 252, #"Ratio" = 985.53, #"Path" = 827],
					        [#"StoreType" = "kinds", #"Order" = 286, #"Ratio" = 961.7, #"Path" = 211],
					        [#"StoreType" = "diagnosis", #"Order" = 467, #"Ratio" = 162.45, #"Path" = 466],
					        [#"StoreType" = "exposed", #"Order" = 470, #"Ratio" = 260.87, #"Path" = 135],
					        [#"StoreType" = "tcp", #"Order" = 91, #"Ratio" = 410.96, #"Path" = 282],
					        [#"StoreType" = "em", #"Order" = 600, #"Ratio" = 918.95, #"Path" = 789],
					        [#"StoreType" = "twice", #"Order" = 879, #"Ratio" = 256.56, #"Path" = 234],
					        [#"StoreType" = "cultures", #"Order" = 143, #"Ratio" = 369.62, #"Path" = 408],
					        [#"StoreType" = "filing", #"Order" = 496, #"Ratio" = 596.71, #"Path" = 489],
					        [#"StoreType" = "thru", #"Order" = 234, #"Ratio" = 466.09, #"Path" = 834],
					        [#"StoreType" = "same", #"Order" = 588, #"Ratio" = 587.05, #"Path" = 535],
					        [#"StoreType" = "draw", #"Order" = 752, #"Ratio" = 100.69, #"Path" = 471],
					        [#"StoreType" = "utah", #"Order" = 120, #"Ratio" = 911.36, #"Path" = 997],
					        [#"StoreType" = "last", #"Order" = 584, #"Ratio" = 561.42, #"Path" = 904],
					        [#"StoreType" = "ip", #"Order" = 958, #"Ratio" = 7.07, #"Path" = 298],
					        [#"StoreType" = "dj", #"Order" = 15, #"Ratio" = 794.15, #"Path" = 835],
					        [#"StoreType" = "discrimination", #"Order" = 301, #"Ratio" = 993.83, #"Path" = 74],
					        [#"StoreType" = "handling", #"Order" = 461, #"Ratio" = 132.87, #"Path" = 296],
					        [#"StoreType" = "cat", #"Order" = 204, #"Ratio" = 348.91, #"Path" = 143],
					        [#"StoreType" = "translation", #"Order" = 208, #"Ratio" = 631.4, #"Path" = 612],
					        [#"StoreType" = "informational", #"Order" = 470, #"Ratio" = 726.46, #"Path" = 580],
					        [#"StoreType" = "willing", #"Order" = 215, #"Ratio" = 893.57, #"Path" = 996],
					        [#"StoreType" = "guarantee", #"Order" = 276, #"Ratio" = 274.11, #"Path" = 813],
					        [#"StoreType" = "peter", #"Order" = 794, #"Ratio" = 691.23, #"Path" = 597],
					        [#"StoreType" = "stand", #"Order" = 126, #"Ratio" = 275.42, #"Path" = 244],
					        [#"StoreType" = "observations", #"Order" = 869, #"Ratio" = 717.81, #"Path" = 218],
					        [#"StoreType" = "translation", #"Order" = 420, #"Ratio" = 1.56, #"Path" = 996],
					        [#"StoreType" = "emphasis", #"Order" = 426, #"Ratio" = 993.57, #"Path" = 761],
					        [#"StoreType" = "committees", #"Order" = 173, #"Ratio" = 441.09, #"Path" = 296],
					        [#"StoreType" = "selection", #"Order" = 153, #"Ratio" = 41.8, #"Path" = 860],
					        [#"StoreType" = "accessible", #"Order" = 348, #"Ratio" = 375.72, #"Path" = 350],
					        [#"StoreType" = "along", #"Order" = 847, #"Ratio" = 73.06, #"Path" = 540],
					        [#"StoreType" = "knife", #"Order" = 72, #"Ratio" = 783.71, #"Path" = 737],
					        [#"StoreType" = "gold", #"Order" = 24, #"Ratio" = 207.85, #"Path" = 631],
					        [#"StoreType" = "powerful", #"Order" = 261, #"Ratio" = 480.45, #"Path" = 648],
					        [#"StoreType" = "ten", #"Order" = 413, #"Ratio" = 626.77, #"Path" = 874],
					        [#"StoreType" = "original", #"Order" = 535, #"Ratio" = 359.99, #"Path" = 631],
					        [#"StoreType" = "researchers", #"Order" = 951, #"Ratio" = 418.31, #"Path" = 529],
					        [#"StoreType" = "locations", #"Order" = 305, #"Ratio" = 77.43, #"Path" = 110],
					        [#"StoreType" = "goods", #"Order" = 730, #"Ratio" = 711.58, #"Path" = 976],
					        [#"StoreType" = "amateur", #"Order" = 519, #"Ratio" = 335.58, #"Path" = 945],
					        [#"StoreType" = "series", #"Order" = 992, #"Ratio" = 58.08, #"Path" = 252],
					        [#"StoreType" = "quickly", #"Order" = 945, #"Ratio" = 288.74, #"Path" = 634],
					        [#"StoreType" = "rural", #"Order" = 449, #"Ratio" = 431.07, #"Path" = 182],
					        [#"StoreType" = "popular", #"Order" = 665, #"Ratio" = 351.9, #"Path" = 903],
					        [#"StoreType" = "honor", #"Order" = 168, #"Ratio" = 784.69, #"Path" = 973],
					        [#"StoreType" = "higher", #"Order" = 149, #"Ratio" = 560.14, #"Path" = 151],
					        [#"StoreType" = "sending", #"Order" = 924, #"Ratio" = 637.27, #"Path" = 977],
					        [#"StoreType" = "length", #"Order" = 876, #"Ratio" = 176.57, #"Path" = 801],
					        [#"StoreType" = "either", #"Order" = 580, #"Ratio" = 749.21, #"Path" = 64],
					        [#"StoreType" = "severe", #"Order" = 765, #"Ratio" = 267.72, #"Path" = 784],
					        [#"StoreType" = "at", #"Order" = 330, #"Ratio" = 354.09, #"Path" = 824],
					        [#"StoreType" = "writers", #"Order" = 567, #"Ratio" = 347.93, #"Path" = 1000],
					        [#"StoreType" = "especially", #"Order" = 89, #"Ratio" = 549.97, #"Path" = 194],
					        [#"StoreType" = "estimate", #"Order" = 489, #"Ratio" = 701.5, #"Path" = 361],
					        [#"StoreType" = "lewis", #"Order" = 913, #"Ratio" = 660.25, #"Path" = 93],
					        [#"StoreType" = "panama", #"Order" = 747, #"Ratio" = 194.17, #"Path" = 618],
					        [#"StoreType" = "select", #"Order" = 1000, #"Ratio" = 844.91, #"Path" = 266],
					        [#"StoreType" = "games", #"Order" = 291, #"Ratio" = 68.91, #"Path" = 284],
					        [#"StoreType" = "console", #"Order" = 381, #"Ratio" = 281.19, #"Path" = 230],
					        [#"StoreType" = "databases", #"Order" = 718, #"Ratio" = 710.74, #"Path" = 418],
					        [#"StoreType" = "cloudy", #"Order" = 840, #"Ratio" = 455.81, #"Path" = 59],
					        [#"StoreType" = "posters", #"Order" = 862, #"Ratio" = 41.19, #"Path" = 512],
					        [#"StoreType" = "experiences", #"Order" = 686, #"Ratio" = 904.14, #"Path" = 695],
					        [#"StoreType" = "fr", #"Order" = 345, #"Ratio" = 825.48, #"Path" = 428],
					        [#"StoreType" = "first", #"Order" = 402, #"Ratio" = 765.09, #"Path" = 759],
					        [#"StoreType" = "appeals", #"Order" = 765, #"Ratio" = 24.88, #"Path" = 494],
					        [#"StoreType" = "stood", #"Order" = 606, #"Ratio" = 916.66, #"Path" = 876],
					        [#"StoreType" = "florist", #"Order" = 348, #"Ratio" = 326.27, #"Path" = 638],
					        [#"StoreType" = "lovely", #"Order" = 947, #"Ratio" = 778.06, #"Path" = 636],
					        [#"StoreType" = "even", #"Order" = 750, #"Ratio" = 416.15, #"Path" = 600],
					        [#"StoreType" = "forgotten", #"Order" = 142, #"Ratio" = 712.31, #"Path" = 771],
					        [#"StoreType" = "objectives", #"Order" = 116, #"Ratio" = 918.43, #"Path" = 988],
					        [#"StoreType" = "required", #"Order" = 88, #"Ratio" = 769.46, #"Path" = 214],
					        [#"StoreType" = "first", #"Order" = 306, #"Ratio" = 930.99, #"Path" = 9],
					        [#"StoreType" = "crystal", #"Order" = 978, #"Ratio" = 346.57, #"Path" = 455],
					        [#"StoreType" = "regard", #"Order" = 263, #"Ratio" = 817.84, #"Path" = 991],
					        [#"StoreType" = "structure", #"Order" = 633, #"Ratio" = 31.16, #"Path" = 87],
					        [#"StoreType" = "electronics", #"Order" = 30, #"Ratio" = 349.23, #"Path" = 401],
					        [#"StoreType" = "nancy", #"Order" = 269, #"Ratio" = 573.97, #"Path" = 462],
					        [#"StoreType" = "ideal", #"Order" = 151, #"Ratio" = 188.24, #"Path" = 438],
					        [#"StoreType" = "available", #"Order" = 125, #"Ratio" = 416.07, #"Path" = 545],
					        [#"StoreType" = "module", #"Order" = 394, #"Ratio" = 435.3, #"Path" = 237],
					        [#"StoreType" = "doc", #"Order" = 150, #"Ratio" = 362.22, #"Path" = 839],
					        [#"StoreType" = "closing", #"Order" = 322, #"Ratio" = 479.5, #"Path" = 242],
					        [#"StoreType" = "concept", #"Order" = 545, #"Ratio" = 396.53, #"Path" = 589],
					        [#"StoreType" = "smooth", #"Order" = 765, #"Ratio" = 718.17, #"Path" = 50],
					        [#"StoreType" = "notice", #"Order" = 302, #"Ratio" = 780.57, #"Path" = 67],
					        [#"StoreType" = "parish", #"Order" = 712, #"Ratio" = 704.4, #"Path" = 658],
					        [#"StoreType" = "exceed", #"Order" = 653, #"Ratio" = 625.64, #"Path" = 917],
					        [#"StoreType" = "whatever", #"Order" = 882, #"Ratio" = 585.85, #"Path" = 747],
					        [#"StoreType" = "fat", #"Order" = 782, #"Ratio" = 365.72, #"Path" = 808],
					        [#"StoreType" = "settlement", #"Order" = 55, #"Ratio" = 251.6, #"Path" = 374],
					        [#"StoreType" = "puts", #"Order" = 487, #"Ratio" = 118.13, #"Path" = 279],
					        [#"StoreType" = "char", #"Order" = 459, #"Ratio" = 746.73, #"Path" = 169],
					        [#"StoreType" = "lifestyle", #"Order" = 375, #"Ratio" = 581.41, #"Path" = 858],
					        [#"StoreType" = "nor", #"Order" = 863, #"Ratio" = 482.65, #"Path" = 388],
					        [#"StoreType" = "pure", #"Order" = 439, #"Ratio" = 345.76, #"Path" = 959],
					        [#"StoreType" = "increasing", #"Order" = 819, #"Ratio" = 265.09, #"Path" = 131],
					        [#"StoreType" = "novel", #"Order" = 97, #"Ratio" = 725.63, #"Path" = 381],
					        [#"StoreType" = "jefferson", #"Order" = 560, #"Ratio" = 77.73, #"Path" = 384],
					        [#"StoreType" = "guns", #"Order" = 597, #"Ratio" = 687.75, #"Path" = 134],
					        [#"StoreType" = "articles", #"Order" = 3, #"Ratio" = 684.73, #"Path" = 741],
					        [#"StoreType" = "part", #"Order" = 538, #"Ratio" = 876.7, #"Path" = 79],
					        [#"StoreType" = "begin", #"Order" = 416, #"Ratio" = 901.35, #"Path" = 44],
					        [#"StoreType" = "africa", #"Order" = 307, #"Ratio" = 846.82, #"Path" = 715],
					        [#"StoreType" = "medical", #"Order" = 568, #"Ratio" = 377.35, #"Path" = 220],
					        [#"StoreType" = "andy", #"Order" = 711, #"Ratio" = 370.28, #"Path" = 180],
					        [#"StoreType" = "resolved", #"Order" = 665, #"Ratio" = 215.64, #"Path" = 236],
					        [#"StoreType" = "enterprises", #"Order" = 570, #"Ratio" = 119.42, #"Path" = 364],
					        [#"StoreType" = "establishing", #"Order" = 536, #"Ratio" = 220.11, #"Path" = 23],
					        [#"StoreType" = "giving", #"Order" = 503, #"Ratio" = 450.84, #"Path" = 174],
					        [#"StoreType" = "tests", #"Order" = 697, #"Ratio" = 100.58, #"Path" = 37],
					        [#"StoreType" = "national", #"Order" = 897, #"Ratio" = 35.5, #"Path" = 791],
					        [#"StoreType" = "keyword", #"Order" = 460, #"Ratio" = 203.16, #"Path" = 680],
					        [#"StoreType" = "designed", #"Order" = 503, #"Ratio" = 201.51, #"Path" = 146],
					        [#"StoreType" = "brad", #"Order" = 420, #"Ratio" = 801.12, #"Path" = 355],
					        [#"StoreType" = "symptoms", #"Order" = 533, #"Ratio" = 264.13, #"Path" = 614],
					        [#"StoreType" = "sacramento", #"Order" = 786, #"Ratio" = 437.39, #"Path" = 975],
					        [#"StoreType" = "publishing", #"Order" = 856, #"Ratio" = 611.36, #"Path" = 422],
					        [#"StoreType" = "dealer", #"Order" = 839, #"Ratio" = 573.18, #"Path" = 992],
					        [#"StoreType" = "guestbook", #"Order" = 96, #"Ratio" = 343.73, #"Path" = 808],
					        [#"StoreType" = "affected", #"Order" = 575, #"Ratio" = 114.42, #"Path" = 970],
					        [#"StoreType" = "analysis", #"Order" = 732, #"Ratio" = 514.61, #"Path" = 116],
					        [#"StoreType" = "requiring", #"Order" = 791, #"Ratio" = 197.47, #"Path" = 770],
					        [#"StoreType" = "everybody", #"Order" = 143, #"Ratio" = 983.22, #"Path" = 115],
					        [#"StoreType" = "rank", #"Order" = 664, #"Ratio" = 857.11, #"Path" = 352],
					        [#"StoreType" = "portland", #"Order" = 954, #"Ratio" = 492.39, #"Path" = 170],
					        [#"StoreType" = "arrival", #"Order" = 893, #"Ratio" = 416.81, #"Path" = 10],
					        [#"StoreType" = "cut", #"Order" = 636, #"Ratio" = 104.15, #"Path" = 459],
					        [#"StoreType" = "governor", #"Order" = 175, #"Ratio" = 533.62, #"Path" = 308],
					        [#"StoreType" = "brothers", #"Order" = 182, #"Ratio" = 290.41, #"Path" = 158],
					        [#"StoreType" = "profiles", #"Order" = 819, #"Ratio" = 130.54, #"Path" = 821],
					        [#"StoreType" = "happened", #"Order" = 225, #"Ratio" = 701.36, #"Path" = 141],
					        [#"StoreType" = "confidence", #"Order" = 568, #"Ratio" = 221.78, #"Path" = 715],
					        [#"StoreType" = "flows", #"Order" = 721, #"Ratio" = 306.38, #"Path" = 667],
					        [#"StoreType" = "egypt", #"Order" = 310, #"Ratio" = 748.33, #"Path" = 720],
					        [#"StoreType" = "roots", #"Order" = 945, #"Ratio" = 343.63, #"Path" = 255],
					        [#"StoreType" = "comfort", #"Order" = 660, #"Ratio" = 522.8, #"Path" = 753],
					        [#"StoreType" = "articles", #"Order" = 471, #"Ratio" = 193.5, #"Path" = 361],
					        [#"StoreType" = "ma", #"Order" = 10, #"Ratio" = 962.9, #"Path" = 112],
					        [#"StoreType" = "interested", #"Order" = 199, #"Ratio" = 89.79, #"Path" = 730],
					        [#"StoreType" = "facility", #"Order" = 474, #"Ratio" = 670.66, #"Path" = 497],
					        [#"StoreType" = "stored", #"Order" = 405, #"Ratio" = 709.21, #"Path" = 983],
					        [#"StoreType" = "treatment", #"Order" = 433, #"Ratio" = 158.85, #"Path" = 984],
					        [#"StoreType" = "opposite", #"Order" = 406, #"Ratio" = 466.9, #"Path" = 88],
					        [#"StoreType" = "fans", #"Order" = 524, #"Ratio" = 124.66, #"Path" = 943],
					        [#"StoreType" = "few", #"Order" = 132, #"Ratio" = 619.81, #"Path" = 741],
					        [#"StoreType" = "permits", #"Order" = 546, #"Ratio" = 144.92, #"Path" = 541],
					        [#"StoreType" = "valentine", #"Order" = 273, #"Ratio" = 73.79, #"Path" = 751],
					        [#"StoreType" = "complex", #"Order" = 126, #"Ratio" = 147.38, #"Path" = 202],
					        [#"StoreType" = "agricultural", #"Order" = 127, #"Ratio" = 30.35, #"Path" = 91],
					        [#"StoreType" = "conventional", #"Order" = 118, #"Ratio" = 365.72, #"Path" = 721],
					        [#"StoreType" = "seller", #"Order" = 144, #"Ratio" = 164.7, #"Path" = 234],
					        [#"StoreType" = "charts", #"Order" = 672, #"Ratio" = 561.96, #"Path" = 7],
					        [#"StoreType" = "opening", #"Order" = 716, #"Ratio" = 680.55, #"Path" = 254],
					        [#"StoreType" = "advertising", #"Order" = 975, #"Ratio" = 970.16, #"Path" = 390],
					        [#"StoreType" = "distinct", #"Order" = 58, #"Ratio" = 598.77, #"Path" = 366],
					        [#"StoreType" = "pleased", #"Order" = 711, #"Ratio" = 504.05, #"Path" = 639],
					        [#"StoreType" = "describes", #"Order" = 610, #"Ratio" = 711.03, #"Path" = 338],
					        [#"StoreType" = "horizontal", #"Order" = 897, #"Ratio" = 110.39, #"Path" = 403],
					        [#"StoreType" = "morris", #"Order" = 242, #"Ratio" = 417.87, #"Path" = 387],
					        [#"StoreType" = "sounds", #"Order" = 765, #"Ratio" = 567.14, #"Path" = 109],
					        [#"StoreType" = "determining", #"Order" = 706, #"Ratio" = 442.25, #"Path" = 3],
					        [#"StoreType" = "drivers", #"Order" = 560, #"Ratio" = 155.78, #"Path" = 991],
					        [#"StoreType" = "compatible", #"Order" = 487, #"Ratio" = 889.51, #"Path" = 474],
					        [#"StoreType" = "sent", #"Order" = 713, #"Ratio" = 387.08, #"Path" = 298],
					        [#"StoreType" = "speech", #"Order" = 266, #"Ratio" = 70.95, #"Path" = 470],
					        [#"StoreType" = "ads", #"Order" = 249, #"Ratio" = 284.54, #"Path" = 377],
					        [#"StoreType" = "funded", #"Order" = 138, #"Ratio" = 969.62, #"Path" = 162],
					        [#"StoreType" = "broadcasting", #"Order" = 123, #"Ratio" = 576.04, #"Path" = 75],
					        [#"StoreType" = "associate", #"Order" = 101, #"Ratio" = 966.62, #"Path" = 226],
					        [#"StoreType" = "questions", #"Order" = 409, #"Ratio" = 639.89, #"Path" = 963],
					        [#"StoreType" = "under", #"Order" = 531, #"Ratio" = 409.03, #"Path" = 41],
					        [#"StoreType" = "relating", #"Order" = 157, #"Ratio" = 185.47, #"Path" = 351],
					        [#"StoreType" = "example", #"Order" = 546, #"Ratio" = 375.34, #"Path" = 527],
					        [#"StoreType" = "narrow", #"Order" = 762, #"Ratio" = 746.72, #"Path" = 876],
					        [#"StoreType" = "licensed", #"Order" = 452, #"Ratio" = 524.86, #"Path" = 685],
					        [#"StoreType" = "pass", #"Order" = 385, #"Ratio" = 735.25, #"Path" = 448],
					        [#"StoreType" = "echo", #"Order" = 197, #"Ratio" = 636.21, #"Path" = 249],
					        [#"StoreType" = "density", #"Order" = 733, #"Ratio" = 630.34, #"Path" = 372],
					        [#"StoreType" = "murray", #"Order" = 588, #"Ratio" = 979.85, #"Path" = 120],
					        [#"StoreType" = "recycling", #"Order" = 179, #"Ratio" = 356.9, #"Path" = 256],
					        [#"StoreType" = "themes", #"Order" = 297, #"Ratio" = 822.46, #"Path" = 841],
					        [#"StoreType" = "matt", #"Order" = 941, #"Ratio" = 110.78, #"Path" = 140],
					        [#"StoreType" = "guides", #"Order" = 135, #"Ratio" = 23.54, #"Path" = 484],
					        [#"StoreType" = "tennessee", #"Order" = 150, #"Ratio" = 596.86, #"Path" = 633],
					        [#"StoreType" = "edinburgh", #"Order" = 601, #"Ratio" = 200.5, #"Path" = 124],
					        [#"StoreType" = "abc", #"Order" = 148, #"Ratio" = 984.49, #"Path" = 113],
					        [#"StoreType" = "panel", #"Order" = 177, #"Ratio" = 232.04, #"Path" = 462],
					        [#"StoreType" = "perfume", #"Order" = 892, #"Ratio" = 702.28, #"Path" = 817],
					        [#"StoreType" = "kernel", #"Order" = 317, #"Ratio" = 478.97, #"Path" = 694],
					        [#"StoreType" = "egypt", #"Order" = 497, #"Ratio" = 829.34, #"Path" = 816],
					        [#"StoreType" = "syntax", #"Order" = 369, #"Ratio" = 121.02, #"Path" = 495],
					        [#"StoreType" = "pda", #"Order" = 614, #"Ratio" = 391.73, #"Path" = 34],
					        [#"StoreType" = "hispanic", #"Order" = 634, #"Ratio" = 833.62, #"Path" = 658],
					        [#"StoreType" = "african", #"Order" = 489, #"Ratio" = 954.69, #"Path" = 968],
					        [#"StoreType" = "apartment", #"Order" = 849, #"Ratio" = 58.76, #"Path" = 360],
					        [#"StoreType" = "texts", #"Order" = 27, #"Ratio" = 9.73, #"Path" = 402],
					        [#"StoreType" = "production", #"Order" = 435, #"Ratio" = 129.8, #"Path" = 628],
					        [#"StoreType" = "victory", #"Order" = 284, #"Ratio" = 342.2, #"Path" = 147],
					        [#"StoreType" = "procedures", #"Order" = 236, #"Ratio" = 201.56, #"Path" = 248],
					        [#"StoreType" = "excellence", #"Order" = 374, #"Ratio" = 27.92, #"Path" = 476],
					        [#"StoreType" = "roger", #"Order" = 629, #"Ratio" = 652.95, #"Path" = 172],
					        [#"StoreType" = "photo", #"Order" = 504, #"Ratio" = 570.45, #"Path" = 486],
					        [#"StoreType" = "iran", #"Order" = 303, #"Ratio" = 638.17, #"Path" = 382],
					        [#"StoreType" = "url", #"Order" = 978, #"Ratio" = 612.36, #"Path" = 701],
					        [#"StoreType" = "employees", #"Order" = 630, #"Ratio" = 435.37, #"Path" = 617],
					        [#"StoreType" = "vat", #"Order" = 309, #"Ratio" = 216.84, #"Path" = 333],
					        [#"StoreType" = "assistant", #"Order" = 812, #"Ratio" = 837.7, #"Path" = 613],
					        [#"StoreType" = "yards", #"Order" = 121, #"Ratio" = 140.69, #"Path" = 233],
					        [#"StoreType" = "transferred", #"Order" = 922, #"Ratio" = 555.77, #"Path" = 234],
					        [#"StoreType" = "highest", #"Order" = 200, #"Ratio" = 347.01, #"Path" = 986],
					        [#"StoreType" = "ages", #"Order" = 425, #"Ratio" = 422.24, #"Path" = 844],
					        [#"StoreType" = "strike", #"Order" = 868, #"Ratio" = 84.43, #"Path" = 429],
					        [#"StoreType" = "concert", #"Order" = 426, #"Ratio" = 942.37, #"Path" = 48],
					        [#"StoreType" = "plaza", #"Order" = 444, #"Ratio" = 267.18, #"Path" = 283],
					        [#"StoreType" = "dec", #"Order" = 101, #"Ratio" = 952.15, #"Path" = 803],
					        [#"StoreType" = "bay", #"Order" = 559, #"Ratio" = 247.87, #"Path" = 259],
					        [#"StoreType" = "catering", #"Order" = 473, #"Ratio" = 629.2, #"Path" = 658],
					        [#"StoreType" = "con", #"Order" = 113, #"Ratio" = 935.66, #"Path" = 309],
					        [#"StoreType" = "protect", #"Order" = 64, #"Ratio" = 889.86, #"Path" = 449],
					        [#"StoreType" = "domestic", #"Order" = 182, #"Ratio" = 737.96, #"Path" = 135],
					        [#"StoreType" = "has", #"Order" = 782, #"Ratio" = 718.28, #"Path" = 216],
					        [#"StoreType" = "died", #"Order" = 341, #"Ratio" = 846.57, #"Path" = 403],
					        [#"StoreType" = "pack", #"Order" = 913, #"Ratio" = 337.16, #"Path" = 302],
					        [#"StoreType" = "negative", #"Order" = 778, #"Ratio" = 622.51, #"Path" = 873],
					        [#"StoreType" = "rule", #"Order" = 419, #"Ratio" = 747.11, #"Path" = 228],
					        [#"StoreType" = "safe", #"Order" = 150, #"Ratio" = 251.69, #"Path" = 713],
					        [#"StoreType" = "mg", #"Order" = 736, #"Ratio" = 979.03, #"Path" = 121],
					        [#"StoreType" = "alliance", #"Order" = 438, #"Ratio" = 610.08, #"Path" = 514],
					        [#"StoreType" = "lists", #"Order" = 685, #"Ratio" = 77.3, #"Path" = 576],
					        [#"StoreType" = "stone", #"Order" = 952, #"Ratio" = 737.3, #"Path" = 147],
					        [#"StoreType" = "missed", #"Order" = 971, #"Ratio" = 119.96, #"Path" = 835],
					        [#"StoreType" = "pierre", #"Order" = 521, #"Ratio" = 520.01, #"Path" = 715],
					        [#"StoreType" = "se", #"Order" = 923, #"Ratio" = 832.21, #"Path" = 781],
					        [#"StoreType" = "mining", #"Order" = 211, #"Ratio" = 119.35, #"Path" = 252],
					        [#"StoreType" = "ps", #"Order" = 861, #"Ratio" = 950.64, #"Path" = 378],
					        [#"StoreType" = "supplied", #"Order" = 164, #"Ratio" = 953.33, #"Path" = 485],
					        [#"StoreType" = "identifying", #"Order" = 80, #"Ratio" = 382.65, #"Path" = 876],
					        [#"StoreType" = "season", #"Order" = 347, #"Ratio" = 270.27, #"Path" = 897],
					        [#"StoreType" = "ports", #"Order" = 8, #"Ratio" = 636.38, #"Path" = 663],
					        [#"StoreType" = "sort", #"Order" = 211, #"Ratio" = 416.18, #"Path" = 601],
					        [#"StoreType" = "cuts", #"Order" = 386, #"Ratio" = 487.07, #"Path" = 636],
					        [#"StoreType" = "arizona", #"Order" = 25, #"Ratio" = 401.25, #"Path" = 598],
					        [#"StoreType" = "ken", #"Order" = 61, #"Ratio" = 974.81, #"Path" = 915],
					        [#"StoreType" = "jamaica", #"Order" = 556, #"Ratio" = 284.29, #"Path" = 848],
					        [#"StoreType" = "dollar", #"Order" = 459, #"Ratio" = 115.46, #"Path" = 325],
					        [#"StoreType" = "guess", #"Order" = 289, #"Ratio" = 675.66, #"Path" = 54],
					        [#"StoreType" = "flickr", #"Order" = 432, #"Ratio" = 640.27, #"Path" = 789],
					        [#"StoreType" = "action", #"Order" = 793, #"Ratio" = 333.24, #"Path" = 403],
					        [#"StoreType" = "proof", #"Order" = 633, #"Ratio" = 411.5, #"Path" = 22],
					        [#"StoreType" = "lighting", #"Order" = 37, #"Ratio" = 367.48, #"Path" = 117],
					        [#"StoreType" = "find", #"Order" = 383, #"Ratio" = 86.85, #"Path" = 136],
					        [#"StoreType" = "lesson", #"Order" = 956, #"Ratio" = 804.82, #"Path" = 230],
					        [#"StoreType" = "sigma", #"Order" = 108, #"Ratio" = 74.46, #"Path" = 414],
					        [#"StoreType" = "hiv", #"Order" = 416, #"Ratio" = 404.57, #"Path" = 951],
					        [#"StoreType" = "berkeley", #"Order" = 310, #"Ratio" = 710.6, #"Path" = 798],
					        [#"StoreType" = "large", #"Order" = 607, #"Ratio" = 976.61, #"Path" = 27],
					        [#"StoreType" = "detailed", #"Order" = 499, #"Ratio" = 150.49, #"Path" = 263],
					        [#"StoreType" = "political", #"Order" = 646, #"Ratio" = 200.29, #"Path" = 510],
					        [#"StoreType" = "government", #"Order" = 475, #"Ratio" = 743.85, #"Path" = 862],
					        [#"StoreType" = "its", #"Order" = 949, #"Ratio" = 702.53, #"Path" = 932],
					        [#"StoreType" = "tropical", #"Order" = 252, #"Ratio" = 837.67, #"Path" = 702],
					        [#"StoreType" = "subsequent", #"Order" = 352, #"Ratio" = 975.54, #"Path" = 143],
					        [#"StoreType" = "losses", #"Order" = 354, #"Ratio" = 153.09, #"Path" = 822],
					        [#"StoreType" = "developing", #"Order" = 610, #"Ratio" = 88.48, #"Path" = 675],
					        [#"StoreType" = "frank", #"Order" = 326, #"Ratio" = 638.66, #"Path" = 563],
					        [#"StoreType" = "cvs", #"Order" = 404, #"Ratio" = 643.34, #"Path" = 758],
					        [#"StoreType" = "accuracy", #"Order" = 685, #"Ratio" = 27.44, #"Path" = 907],
					        [#"StoreType" = "bishop", #"Order" = 657, #"Ratio" = 862.31, #"Path" = 129],
					        [#"StoreType" = "deposit", #"Order" = 888, #"Ratio" = 477.86, #"Path" = 229],
					        [#"StoreType" = "urw", #"Order" = 783, #"Ratio" = 831.58, #"Path" = 871],
					        [#"StoreType" = "reference", #"Order" = 210, #"Ratio" = 113.99, #"Path" = 271],
					        [#"StoreType" = "lie", #"Order" = 220, #"Ratio" = 803.6, #"Path" = 481],
					        [#"StoreType" = "implementing", #"Order" = 300, #"Ratio" = 296.79, #"Path" = 406],
					        [#"StoreType" = "recorded", #"Order" = 685, #"Ratio" = 159.17, #"Path" = 930],
					        [#"StoreType" = "licensed", #"Order" = 405, #"Ratio" = 152.56, #"Path" = 119],
					        [#"StoreType" = "gap", #"Order" = 295, #"Ratio" = 782.89, #"Path" = 114],
					        [#"StoreType" = "antonio", #"Order" = 160, #"Ratio" = 251.14, #"Path" = 584],
					        [#"StoreType" = "scenes", #"Order" = 213, #"Ratio" = 788.43, #"Path" = 262],
					        [#"StoreType" = "honda", #"Order" = 996, #"Ratio" = 788.73, #"Path" = 259],
					        [#"StoreType" = "covered", #"Order" = 454, #"Ratio" = 512.83, #"Path" = 837],
					        [#"StoreType" = "extensions", #"Order" = 533, #"Ratio" = 422.72, #"Path" = 959],
					        [#"StoreType" = "developments", #"Order" = 47, #"Ratio" = 244.64, #"Path" = 562],
					        [#"StoreType" = "phil", #"Order" = 377, #"Ratio" = 351.79, #"Path" = 290],
					        [#"StoreType" = "intent", #"Order" = 284, #"Ratio" = 485.49, #"Path" = 275],
					        [#"StoreType" = "sense", #"Order" = 102, #"Ratio" = 14.19, #"Path" = 160],
					        [#"StoreType" = "modes", #"Order" = 670, #"Ratio" = 668.1, #"Path" = 427],
					        [#"StoreType" = "border", #"Order" = 363, #"Ratio" = 842.84, #"Path" = 129],
					        [#"StoreType" = "okay", #"Order" = 49, #"Ratio" = 580.52, #"Path" = 244],
					        [#"StoreType" = "singing", #"Order" = 353, #"Ratio" = 304.86, #"Path" = 617],
					        [#"StoreType" = "fluid", #"Order" = 999, #"Ratio" = 142.2, #"Path" = 488],
					        [#"StoreType" = "trucks", #"Order" = 964, #"Ratio" = 676.44, #"Path" = 505],
					        [#"StoreType" = "sugar", #"Order" = 300, #"Ratio" = 64.11, #"Path" = 139],
					        [#"StoreType" = "force", #"Order" = 47, #"Ratio" = 709.63, #"Path" = 265],
					        [#"StoreType" = "academic", #"Order" = 623, #"Ratio" = 601.77, #"Path" = 852],
					        [#"StoreType" = "assume", #"Order" = 603, #"Ratio" = 133.5, #"Path" = 634],
					        [#"StoreType" = "stephen", #"Order" = 965, #"Ratio" = 175.92, #"Path" = 636],
					        [#"StoreType" = "patent", #"Order" = 653, #"Ratio" = 346.36, #"Path" = 198],
					        [#"StoreType" = "forum", #"Order" = 802, #"Ratio" = 674.69, #"Path" = 459],
					        [#"StoreType" = "county", #"Order" = 601, #"Ratio" = 702.71, #"Path" = 609],
					        [#"StoreType" = "complexity", #"Order" = 384, #"Ratio" = 418.33, #"Path" = 153],
					        [#"StoreType" = "purposes", #"Order" = 404, #"Ratio" = 304.78, #"Path" = 540],
					        [#"StoreType" = "true", #"Order" = 598, #"Ratio" = 846.21, #"Path" = 314],
					        [#"StoreType" = "noble", #"Order" = 596, #"Ratio" = 581.72, #"Path" = 247],
					        [#"StoreType" = "kansas", #"Order" = 65, #"Ratio" = 281.35, #"Path" = 774],
					        [#"StoreType" = "seasons", #"Order" = 829, #"Ratio" = 645.51, #"Path" = 4],
					        [#"StoreType" = "operate", #"Order" = 778, #"Ratio" = 607.17, #"Path" = 311],
					        [#"StoreType" = "main", #"Order" = 927, #"Ratio" = 396.35, #"Path" = 601],
					        [#"StoreType" = "coal", #"Order" = 438, #"Ratio" = 263.52, #"Path" = 144],
					        [#"StoreType" = "fields", #"Order" = 567, #"Ratio" = 226.41, #"Path" = 181],
					        [#"StoreType" = "germany", #"Order" = 361, #"Ratio" = 731.01, #"Path" = 979],
					        [#"StoreType" = "survival", #"Order" = 8, #"Ratio" = 99.47, #"Path" = 992],
					        [#"StoreType" = "product", #"Order" = 431, #"Ratio" = 148.25, #"Path" = 608],
					        [#"StoreType" = "worked", #"Order" = 721, #"Ratio" = 794.1, #"Path" = 93],
					        [#"StoreType" = "township", #"Order" = 241, #"Ratio" = 250.99, #"Path" = 453],
					        [#"StoreType" = "ends", #"Order" = 216, #"Ratio" = 757.79, #"Path" = 561],
					        [#"StoreType" = "ban", #"Order" = 971, #"Ratio" = 544.82, #"Path" = 791],
					        [#"StoreType" = "alberta", #"Order" = 755, #"Ratio" = 810.25, #"Path" = 378],
					        [#"StoreType" = "organic", #"Order" = 716, #"Ratio" = 531.19, #"Path" = 213],
					        [#"StoreType" = "spiritual", #"Order" = 842, #"Ratio" = 34.36, #"Path" = 826],
					        [#"StoreType" = "unusual", #"Order" = 313, #"Ratio" = 934.14, #"Path" = 650],
					        [#"StoreType" = "advisory", #"Order" = 376, #"Ratio" = 957.71, #"Path" = 681],
					        [#"StoreType" = "surveillance", #"Order" = 619, #"Ratio" = 475.36, #"Path" = 433],
					        [#"StoreType" = "send", #"Order" = 268, #"Ratio" = 417.27, #"Path" = 953],
					        [#"StoreType" = "flower", #"Order" = 684, #"Ratio" = 712.06, #"Path" = 984],
					        [#"StoreType" = "appeared", #"Order" = 889, #"Ratio" = 47.02, #"Path" = 933],
					        [#"StoreType" = "breasts", #"Order" = 172, #"Ratio" = 411.91, #"Path" = 218],
					        [#"StoreType" = "quantum", #"Order" = 299, #"Ratio" = 309.81, #"Path" = 234],
					        [#"StoreType" = "rc", #"Order" = 802, #"Ratio" = 397.31, #"Path" = 802],
					        [#"StoreType" = "feeling", #"Order" = 896, #"Ratio" = 893.54, #"Path" = 810],
					        [#"StoreType" = "detroit", #"Order" = 932, #"Ratio" = 102.74, #"Path" = 114],
					        [#"StoreType" = "suggests", #"Order" = 140, #"Ratio" = 988.81, #"Path" = 320],
					        [#"StoreType" = "kent", #"Order" = 489, #"Ratio" = 77.7, #"Path" = 21],
					        [#"StoreType" = "million", #"Order" = 504, #"Ratio" = 607.32, #"Path" = 6],
					        [#"StoreType" = "karen", #"Order" = 745, #"Ratio" = 534.42, #"Path" = 880],
					        [#"StoreType" = "play", #"Order" = 150, #"Ratio" = 754.84, #"Path" = 506],
					        [#"StoreType" = "significant", #"Order" = 191, #"Ratio" = 728.51, #"Path" = 289],
					        [#"StoreType" = "trained", #"Order" = 880, #"Ratio" = 774.73, #"Path" = 511]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"StoreType", type text},
					        {"Order", Int64.Type},
					        {"Ratio", type number},
					        {"Path", Int64.Type}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table