table 'Sheet1_Sheet1 (radial_bar_chart_data)'
	lineageTag: b9fab46f-76b7-47cc-9f10-0aa41ce69f4f

	column StoreType
		dataType: string
		lineageTag: cf9407e5-f226-4677-8d63-e227c4440356
		summarizeBy: none
		sourceColumn: StoreType

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: 89c2d525-c497-434f-9622-c1d6d934b994
		summarizeBy: sum
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	column Ratio
		dataType: double
		formatString: General Number
		lineageTag: a6e4f9a8-2dff-4f58-a3e3-c7781df86d90
		summarizeBy: sum
		sourceColumn: Ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Path
		dataType: int64
		formatString: 0
		lineageTag: b255e5c1-46b7-4356-afab-8056f0e0e6eb
		summarizeBy: sum
		sourceColumn: Path

		annotation SummarizationSetBy = Automatic

	partition 'Sheet1_Sheet1 (radial_bar_chart_data)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"StoreType" = "method", #"Order" = 643, #"Ratio" = 928.76, #"Path" = 22],
					        [#"StoreType" = "ralph", #"Order" = 31, #"Ratio" = 972.02, #"Path" = 255],
					        [#"StoreType" = "nations", #"Order" = 203, #"Ratio" = 453.8, #"Path" = 970],
					        [#"StoreType" = "ghost", #"Order" = 287, #"Ratio" = 648.03, #"Path" = 846],
					        [#"StoreType" = "wire", #"Order" = 558, #"Ratio" = 226.59, #"Path" = 862],
					        [#"StoreType" = "api", #"Order" = 935, #"Ratio" = 764.42, #"Path" = 430],
					        [#"StoreType" = "robin", #"Order" = 317, #"Ratio" = 104.92, #"Path" = 142],
					        [#"StoreType" = "mechanisms", #"Order" = 439, #"Ratio" = 29.76, #"Path" = 283],
					        [#"StoreType" = "lab", #"Order" = 74, #"Ratio" = 14.09, #"Path" = 582],
					        [#"StoreType" = "valve", #"Order" = 412, #"Ratio" = 836.58, #"Path" = 471],
					        [#"StoreType" = "served", #"Order" = 211, #"Ratio" = 838.56, #"Path" = 343],
					        [#"StoreType" = "poor", #"Order" = 8, #"Ratio" = 695.51, #"Path" = 340],
					        [#"StoreType" = "channel", #"Order" = 383, #"Ratio" = 626.12, #"Path" = 456],
					        [#"StoreType" = "option", #"Order" = 737, #"Ratio" = 456.17, #"Path" = 392],
					        [#"StoreType" = "grow", #"Order" = 352, #"Ratio" = 168.71, #"Path" = 574],
					        [#"StoreType" = "kennedy", #"Order" = 604, #"Ratio" = 608.71, #"Path" = 999],
					        [#"StoreType" = "guidelines", #"Order" = 899, #"Ratio" = 279.23, #"Path" = 490],
					        [#"StoreType" = "gives", #"Order" = 45, #"Ratio" = 730.4, #"Path" = 227],
					        [#"StoreType" = "newsletter", #"Order" = 104, #"Ratio" = 24.64, #"Path" = 80],
					        [#"StoreType" = "vs", #"Order" = 774, #"Ratio" = 170.58, #"Path" = 866],
					        [#"StoreType" = "pr", #"Order" = 345, #"Ratio" = 58.81, #"Path" = 955],
					        [#"StoreType" = "pottery", #"Order" = 316, #"Ratio" = 586.79, #"Path" = 592],
					        [#"StoreType" = "workplace", #"Order" = 169, #"Ratio" = 277.12, #"Path" = 361],
					        [#"StoreType" = "lessons", #"Order" = 717, #"Ratio" = 736.45, #"Path" = 172],
					        [#"StoreType" = "votes", #"Order" = 481, #"Ratio" = 575.41, #"Path" = 952],
					        [#"StoreType" = "bird", #"Order" = 607, #"Ratio" = 520.66, #"Path" = 852],
					        [#"StoreType" = "older", #"Order" = 52, #"Ratio" = 719.5, #"Path" = 376],
					        [#"StoreType" = "remove", #"Order" = 401, #"Ratio" = 547.64, #"Path" = 550],
					        [#"StoreType" = "reach", #"Order" = 359, #"Ratio" = 937.98, #"Path" = 599],
					        [#"StoreType" = "guilty", #"Order" = 83, #"Ratio" = 795.18, #"Path" = 208],
					        [#"StoreType" = "oldest", #"Order" = 189, #"Ratio" = 78.62, #"Path" = 435],
					        [#"StoreType" = "denied", #"Order" = 630, #"Ratio" = 843.77, #"Path" = 427],
					        [#"StoreType" = "drew", #"Order" = 928, #"Ratio" = 924.42, #"Path" = 928],
					        [#"StoreType" = "jury", #"Order" = 479, #"Ratio" = 809.91, #"Path" = 405],
					        [#"StoreType" = "wage", #"Order" = 18, #"Ratio" = 764.96, #"Path" = 308],
					        [#"StoreType" = "ec", #"Order" = 773, #"Ratio" = 990.87, #"Path" = 188],
					        [#"StoreType" = "tables", #"Order" = 107, #"Ratio" = 292.08, #"Path" = 817],
					        [#"StoreType" = "roll", #"Order" = 405, #"Ratio" = 384.96, #"Path" = 903],
					        [#"StoreType" = "basis", #"Order" = 68, #"Ratio" = 516.44, #"Path" = 213],
					        [#"StoreType" = "score", #"Order" = 73, #"Ratio" = 849.71, #"Path" = 895],
					        [#"StoreType" = "consultants", #"Order" = 948, #"Ratio" = 492.27, #"Path" = 771],
					        [#"StoreType" = "crop", #"Order" = 671, #"Ratio" = 401.6, #"Path" = 469],
					        [#"StoreType" = "projection", #"Order" = 731, #"Ratio" = 714.26, #"Path" = 284],
					        [#"StoreType" = "receives", #"Order" = 19, #"Ratio" = 142.49, #"Path" = 641],
					        [#"StoreType" = "diet", #"Order" = 391, #"Ratio" = 928.95, #"Path" = 387],
					        [#"StoreType" = "issues", #"Order" = 106, #"Ratio" = 549.48, #"Path" = 837],
					        [#"StoreType" = "cheap", #"Order" = 59, #"Ratio" = 977.34, #"Path" = 779],
					        [#"StoreType" = "metal", #"Order" = 990, #"Ratio" = 666.48, #"Path" = 252],
					        [#"StoreType" = "iron", #"Order" = 548, #"Ratio" = 817.65, #"Path" = 795],
					        [#"StoreType" = "eligibility", #"Order" = 755, #"Ratio" = 569.8, #"Path" = 564],
					        [#"StoreType" = "ba", #"Order" = 828, #"Ratio" = 39.56, #"Path" = 395],
					        [#"StoreType" = "support", #"Order" = 133, #"Ratio" = 426.16, #"Path" = 732],
					        [#"StoreType" = "sealed", #"Order" = 173, #"Ratio" = 12.97, #"Path" = 26],
					        [#"StoreType" = "carrying", #"Order" = 960, #"Ratio" = 855.07, #"Path" = 415],
					        [#"StoreType" = "magazine", #"Order" = 563, #"Ratio" = 250.16, #"Path" = 472],
					        [#"StoreType" = "sequence", #"Order" = 337, #"Ratio" = 569.41, #"Path" = 127],
					        [#"StoreType" = "loves", #"Order" = 248, #"Ratio" = 499.68, #"Path" = 957],
					        [#"StoreType" = "outstanding", #"Order" = 997, #"Ratio" = 945.97, #"Path" = 665],
					        [#"StoreType" = "brief", #"Order" = 100, #"Ratio" = 189.4, #"Path" = 535],
					        [#"StoreType" = "closed", #"Order" = 660, #"Ratio" = 959.79, #"Path" = 784],
					        [#"StoreType" = "gaming", #"Order" = 206, #"Ratio" = 134.64, #"Path" = 965],
					        [#"StoreType" = "framework", #"Order" = 763, #"Ratio" = 493.64, #"Path" = 363],
					        [#"StoreType" = "beyond", #"Order" = 30, #"Ratio" = 2.48, #"Path" = 557],
					        [#"StoreType" = "supplements", #"Order" = 954, #"Ratio" = 125.89, #"Path" = 23],
					        [#"StoreType" = "hot", #"Order" = 70, #"Ratio" = 287.75, #"Path" = 15],
					        [#"StoreType" = "determination", #"Order" = 124, #"Ratio" = 154.82, #"Path" = 162],
					        [#"StoreType" = "determination", #"Order" = 182, #"Ratio" = 960.47, #"Path" = 987],
					        [#"StoreType" = "bytes", #"Order" = 710, #"Ratio" = 996.01, #"Path" = 864],
					        [#"StoreType" = "alien", #"Order" = 466, #"Ratio" = 981.32, #"Path" = 485],
					        [#"StoreType" = "cad", #"Order" = 282, #"Ratio" = 740.49, #"Path" = 786],
					        [#"StoreType" = "british", #"Order" = 636, #"Ratio" = 271.55, #"Path" = 525],
					        [#"StoreType" = "applies", #"Order" = 59, #"Ratio" = 991.58, #"Path" = 143],
					        [#"StoreType" = "affiliated", #"Order" = 84, #"Ratio" = 182.24, #"Path" = 639],
					        [#"StoreType" = "july", #"Order" = 551, #"Ratio" = 373.28, #"Path" = 760],
					        [#"StoreType" = "vi", #"Order" = 997, #"Ratio" = 753.84, #"Path" = 187],
					        [#"StoreType" = "jp", #"Order" = 148, #"Ratio" = 753.57, #"Path" = 761],
					        [#"StoreType" = "tech", #"Order" = 608, #"Ratio" = 764.0, #"Path" = 245],
					        [#"StoreType" = "submitted", #"Order" = 732, #"Ratio" = 112.04, #"Path" = 640],
					        [#"StoreType" = "users", #"Order" = 689, #"Ratio" = 873.92, #"Path" = 271],
					        [#"StoreType" = "laptops", #"Order" = 248, #"Ratio" = 504.09, #"Path" = 513],
					        [#"StoreType" = "cassette", #"Order" = 613, #"Ratio" = 544.74, #"Path" = 370],
					        [#"StoreType" = "rated", #"Order" = 770, #"Ratio" = 954.49, #"Path" = 908],
					        [#"StoreType" = "grow", #"Order" = 329, #"Ratio" = 101.2, #"Path" = 953],
					        [#"StoreType" = "growing", #"Order" = 192, #"Ratio" = 33.61, #"Path" = 307],
					        [#"StoreType" = "currently", #"Order" = 432, #"Ratio" = 269.94, #"Path" = 545],
					        [#"StoreType" = "terminal", #"Order" = 997, #"Ratio" = 389.88, #"Path" = 837],
					        [#"StoreType" = "km", #"Order" = 851, #"Ratio" = 42.09, #"Path" = 360],
					        [#"StoreType" = "soil", #"Order" = 162, #"Ratio" = 132.26, #"Path" = 300],
					        [#"StoreType" = "instead", #"Order" = 149, #"Ratio" = 926.66, #"Path" = 539],
					        [#"StoreType" = "permitted", #"Order" = 207, #"Ratio" = 353.17, #"Path" = 721],
					        [#"StoreType" = "fairly", #"Order" = 754, #"Ratio" = 933.36, #"Path" = 418],
					        [#"StoreType" = "weak", #"Order" = 200, #"Ratio" = 172.37, #"Path" = 16],
					        [#"StoreType" = "videos", #"Order" = 617, #"Ratio" = 963.23, #"Path" = 355],
					        [#"StoreType" = "finish", #"Order" = 372, #"Ratio" = 4.7, #"Path" = 426],
					        [#"StoreType" = "every", #"Order" = 435, #"Ratio" = 643.35, #"Path" = 932],
					        [#"StoreType" = "everyone", #"Order" = 855, #"Ratio" = 945.51, #"Path" = 478],
					        [#"StoreType" = "dealer", #"Order" = 409, #"Ratio" = 202.22, #"Path" = 609],
					        [#"StoreType" = "pending", #"Order" = 249, #"Ratio" = 862.68, #"Path" = 148],
					        [#"StoreType" = "diet", #"Order" = 522, #"Ratio" = 3.18, #"Path" = 781],
					        [#"StoreType" = "song", #"Order" = 283, #"Ratio" = 150.25, #"Path" = 36],
					        [#"StoreType" = "images", #"Order" = 341, #"Ratio" = 445.88, #"Path" = 361],
					        [#"StoreType" = "monthly", #"Order" = 114, #"Ratio" = 874.93, #"Path" = 582],
					        [#"StoreType" = "took", #"Order" = 220, #"Ratio" = 597.19, #"Path" = 764],
					        [#"StoreType" = "bought", #"Order" = 539, #"Ratio" = 759.12, #"Path" = 42],
					        [#"StoreType" = "outlook", #"Order" = 53, #"Ratio" = 419.15, #"Path" = 52],
					        [#"StoreType" = "admissions", #"Order" = 517, #"Ratio" = 808.28, #"Path" = 661],
					        [#"StoreType" = "az", #"Order" = 980, #"Ratio" = 327.63, #"Path" = 565],
					        [#"StoreType" = "lebanon", #"Order" = 902, #"Ratio" = 664.61, #"Path" = 763],
					        [#"StoreType" = "pdf", #"Order" = 479, #"Ratio" = 937.42, #"Path" = 903],
					        [#"StoreType" = "bring", #"Order" = 9, #"Ratio" = 721.22, #"Path" = 120],
					        [#"StoreType" = "convenient", #"Order" = 430, #"Ratio" = 642.45, #"Path" = 729],
					        [#"StoreType" = "son", #"Order" = 18, #"Ratio" = 259.7, #"Path" = 290],
					        [#"StoreType" = "font", #"Order" = 97, #"Ratio" = 61.22, #"Path" = 510],
					        [#"StoreType" = "price", #"Order" = 817, #"Ratio" = 39.24, #"Path" = 681],
					        [#"StoreType" = "desire", #"Order" = 141, #"Ratio" = 281.89, #"Path" = 408],
					        [#"StoreType" = "show", #"Order" = 963, #"Ratio" = 583.69, #"Path" = 379],
					        [#"StoreType" = "society", #"Order" = 912, #"Ratio" = 478.13, #"Path" = 441],
					        [#"StoreType" = "sri", #"Order" = 112, #"Ratio" = 182.95, #"Path" = 183],
					        [#"StoreType" = "specialist", #"Order" = 570, #"Ratio" = 291.42, #"Path" = 965],
					        [#"StoreType" = "dallas", #"Order" = 512, #"Ratio" = 263.16, #"Path" = 804],
					        [#"StoreType" = "packaging", #"Order" = 245, #"Ratio" = 729.81, #"Path" = 225],
					        [#"StoreType" = "adoption", #"Order" = 62, #"Ratio" = 462.6, #"Path" = 596],
					        [#"StoreType" = "draft", #"Order" = 822, #"Ratio" = 21.73, #"Path" = 98],
					        [#"StoreType" = "sitting", #"Order" = 394, #"Ratio" = 827.92, #"Path" = 262],
					        [#"StoreType" = "fewer", #"Order" = 294, #"Ratio" = 607.57, #"Path" = 683],
					        [#"StoreType" = "attractions", #"Order" = 911, #"Ratio" = 486.65, #"Path" = 337],
					        [#"StoreType" = "chevrolet", #"Order" = 396, #"Ratio" = 304.64, #"Path" = 541],
					        [#"StoreType" = "bodies", #"Order" = 5, #"Ratio" = 749.4, #"Path" = 332],
					        [#"StoreType" = "ie", #"Order" = 347, #"Ratio" = 359.36, #"Path" = 739],
					        [#"StoreType" = "political", #"Order" = 208, #"Ratio" = 398.29, #"Path" = 731],
					        [#"StoreType" = "collectibles", #"Order" = 824, #"Ratio" = 769.41, #"Path" = 489],
					        [#"StoreType" = "rather", #"Order" = 203, #"Ratio" = 797.08, #"Path" = 680],
					        [#"StoreType" = "conflict", #"Order" = 290, #"Ratio" = 18.93, #"Path" = 800],
					        [#"StoreType" = "jeff", #"Order" = 780, #"Ratio" = 627.76, #"Path" = 570],
					        [#"StoreType" = "shoes", #"Order" = 839, #"Ratio" = 560.63, #"Path" = 854],
					        [#"StoreType" = "indicates", #"Order" = 212, #"Ratio" = 538.4, #"Path" = 677],
					        [#"StoreType" = "google", #"Order" = 807, #"Ratio" = 471.09, #"Path" = 497],
					        [#"StoreType" = "cheese", #"Order" = 263, #"Ratio" = 739.09, #"Path" = 104],
					        [#"StoreType" = "laid", #"Order" = 115, #"Ratio" = 837.45, #"Path" = 655],
					        [#"StoreType" = "trek", #"Order" = 387, #"Ratio" = 517.45, #"Path" = 236],
					        [#"StoreType" = "fixed", #"Order" = 322, #"Ratio" = 619.12, #"Path" = 385],
					        [#"StoreType" = "serve", #"Order" = 615, #"Ratio" = 50.64, #"Path" = 832],
					        [#"StoreType" = "photo", #"Order" = 970, #"Ratio" = 217.01, #"Path" = 985],
					        [#"StoreType" = "hundreds", #"Order" = 354, #"Ratio" = 948.25, #"Path" = 736],
					        [#"StoreType" = "dates", #"Order" = 945, #"Ratio" = 519.62, #"Path" = 414],
					        [#"StoreType" = "tin", #"Order" = 512, #"Ratio" = 93.91, #"Path" = 423],
					        [#"StoreType" = "holy", #"Order" = 315, #"Ratio" = 784.86, #"Path" = 798],
					        [#"StoreType" = "infant", #"Order" = 145, #"Ratio" = 131.25, #"Path" = 590],
					        [#"StoreType" = "spin", #"Order" = 63, #"Ratio" = 105.15, #"Path" = 815],
					        [#"StoreType" = "mile", #"Order" = 40, #"Ratio" = 842.71, #"Path" = 413],
					        [#"StoreType" = "destruction", #"Order" = 754, #"Ratio" = 880.02, #"Path" = 920],
					        [#"StoreType" = "drug", #"Order" = 911, #"Ratio" = 349.71, #"Path" = 416],
					        [#"StoreType" = "wants", #"Order" = 740, #"Ratio" = 223.59, #"Path" = 843],
					        [#"StoreType" = "rs", #"Order" = 496, #"Ratio" = 768.53, #"Path" = 191],
					        [#"StoreType" = "twiki", #"Order" = 748, #"Ratio" = 473.68, #"Path" = 115],
					        [#"StoreType" = "saudi", #"Order" = 359, #"Ratio" = 722.66, #"Path" = 75],
					        [#"StoreType" = "finance", #"Order" = 635, #"Ratio" = 412.05, #"Path" = 568],
					        [#"StoreType" = "reviewed", #"Order" = 680, #"Ratio" = 894.76, #"Path" = 83],
					        [#"StoreType" = "sons", #"Order" = 577, #"Ratio" = 92.03, #"Path" = 245],
					        [#"StoreType" = "css", #"Order" = 296, #"Ratio" = 16.06, #"Path" = 100],
					        [#"StoreType" = "bound", #"Order" = 204, #"Ratio" = 732.48, #"Path" = 138],
					        [#"StoreType" = "amsterdam", #"Order" = 987, #"Ratio" = 286.47, #"Path" = 213],
					        [#"StoreType" = "cat", #"Order" = 972, #"Ratio" = 32.81, #"Path" = 532],
					        [#"StoreType" = "satisfaction", #"Order" = 29, #"Ratio" = 953.63, #"Path" = 162],
					        [#"StoreType" = "hero", #"Order" = 666, #"Ratio" = 84.06, #"Path" = 792],
					        [#"StoreType" = "ff", #"Order" = 88, #"Ratio" = 804.56, #"Path" = 231],
					        [#"StoreType" = "graduate", #"Order" = 99, #"Ratio" = 843.4, #"Path" = 789],
					        [#"StoreType" = "converter", #"Order" = 96, #"Ratio" = 545.86, #"Path" = 250],
					        [#"StoreType" = "tube", #"Order" = 14, #"Ratio" = 574.66, #"Path" = 697],
					        [#"StoreType" = "acceptance", #"Order" = 790, #"Ratio" = 933.22, #"Path" = 665],
					        [#"StoreType" = "track", #"Order" = 904, #"Ratio" = 962.28, #"Path" = 557],
					        [#"StoreType" = "career", #"Order" = 797, #"Ratio" = 781.91, #"Path" = 437],
					        [#"StoreType" = "against", #"Order" = 718, #"Ratio" = 791.05, #"Path" = 302],
					        [#"StoreType" = "correctly", #"Order" = 69, #"Ratio" = 434.68, #"Path" = 804],
					        [#"StoreType" = "statistics", #"Order" = 862, #"Ratio" = 141.61, #"Path" = 611],
					        [#"StoreType" = "ah", #"Order" = 506, #"Ratio" = 538.53, #"Path" = 323],
					        [#"StoreType" = "islamic", #"Order" = 760, #"Ratio" = 25.24, #"Path" = 918],
					        [#"StoreType" = "ecommerce", #"Order" = 268, #"Ratio" = 24.1, #"Path" = 817],
					        [#"StoreType" = "decor", #"Order" = 781, #"Ratio" = 334.46, #"Path" = 519],
					        [#"StoreType" = "ohio", #"Order" = 493, #"Ratio" = 163.57, #"Path" = 572],
					        [#"StoreType" = "molecular", #"Order" = 569, #"Ratio" = 331.73, #"Path" = 583],
					        [#"StoreType" = "intel", #"Order" = 649, #"Ratio" = 914.68, #"Path" = 851],
					        [#"StoreType" = "including", #"Order" = 301, #"Ratio" = 1.41, #"Path" = 578],
					        [#"StoreType" = "pricing", #"Order" = 824, #"Ratio" = 384.98, #"Path" = 202],
					        [#"StoreType" = "ethnic", #"Order" = 942, #"Ratio" = 118.14, #"Path" = 62],
					        [#"StoreType" = "dec", #"Order" = 371, #"Ratio" = 29.29, #"Path" = 861],
					        [#"StoreType" = "combined", #"Order" = 53, #"Ratio" = 637.48, #"Path" = 222],
					        [#"StoreType" = "swedish", #"Order" = 396, #"Ratio" = 200.03, #"Path" = 404],
					        [#"StoreType" = "smaller", #"Order" = 638, #"Ratio" = 140.85, #"Path" = 801],
					        [#"StoreType" = "intro", #"Order" = 49, #"Ratio" = 210.33, #"Path" = 706],
					        [#"StoreType" = "suggest", #"Order" = 284, #"Ratio" = 49.04, #"Path" = 658],
					        [#"StoreType" = "teaching", #"Order" = 445, #"Ratio" = 355.04, #"Path" = 662],
					        [#"StoreType" = "attorney", #"Order" = 942, #"Ratio" = 297.8, #"Path" = 158],
					        [#"StoreType" = "further", #"Order" = 489, #"Ratio" = 161.28, #"Path" = 264],
					        [#"StoreType" = "livecam", #"Order" = 332, #"Ratio" = 262.2, #"Path" = 136],
					        [#"StoreType" = "bulgaria", #"Order" = 670, #"Ratio" = 537.02, #"Path" = 366],
					        [#"StoreType" = "iv", #"Order" = 197, #"Ratio" = 82.95, #"Path" = 1],
					        [#"StoreType" = "promise", #"Order" = 369, #"Ratio" = 833.72, #"Path" = 350],
					        [#"StoreType" = "livecam", #"Order" = 993, #"Ratio" = 37.53, #"Path" = 206],
					        [#"StoreType" = "pension", #"Order" = 793, #"Ratio" = 541.62, #"Path" = 965],
					        [#"StoreType" = "proceedings", #"Order" = 236, #"Ratio" = 432.84, #"Path" = 272],
					        [#"StoreType" = "discrimination", #"Order" = 105, #"Ratio" = 498.68, #"Path" = 363],
					        [#"StoreType" = "appointed", #"Order" = 511, #"Ratio" = 38.3, #"Path" = 819],
					        [#"StoreType" = "cache", #"Order" = 692, #"Ratio" = 226.16, #"Path" = 338],
					        [#"StoreType" = "musical", #"Order" = 374, #"Ratio" = 59.35, #"Path" = 451],
					        [#"StoreType" = "secured", #"Order" = 602, #"Ratio" = 154.61, #"Path" = 109],
					        [#"StoreType" = "second", #"Order" = 477, #"Ratio" = 110.05, #"Path" = 228],
					        [#"StoreType" = "ncaa", #"Order" = 910, #"Ratio" = 978.9, #"Path" = 900],
					        [#"StoreType" = "forever", #"Order" = 991, #"Ratio" = 611.52, #"Path" = 390],
					        [#"StoreType" = "db", #"Order" = 939, #"Ratio" = 682.65, #"Path" = 495],
					        [#"StoreType" = "realize", #"Order" = 431, #"Ratio" = 434.33, #"Path" = 125],
					        [#"StoreType" = "abroad", #"Order" = 991, #"Ratio" = 923.27, #"Path" = 806],
					        [#"StoreType" = "window", #"Order" = 524, #"Ratio" = 298.4, #"Path" = 489],
					        [#"StoreType" = "inkjet", #"Order" = 731, #"Ratio" = 10.79, #"Path" = 346],
					        [#"StoreType" = "doubt", #"Order" = 595, #"Ratio" = 792.32, #"Path" = 838],
					        [#"StoreType" = "level", #"Order" = 736, #"Ratio" = 922.09, #"Path" = 761],
					        [#"StoreType" = "ap", #"Order" = 442, #"Ratio" = 270.59, #"Path" = 3],
					        [#"StoreType" = "msn", #"Order" = 553, #"Ratio" = 828.27, #"Path" = 49],
					        [#"StoreType" = "ridge", #"Order" = 142, #"Ratio" = 179.14, #"Path" = 78],
					        [#"StoreType" = "stations", #"Order" = 980, #"Ratio" = 133.77, #"Path" = 518],
					        [#"StoreType" = "yours", #"Order" = 299, #"Ratio" = 983.51, #"Path" = 12],
					        [#"StoreType" = "gps", #"Order" = 850, #"Ratio" = 461.18, #"Path" = 641],
					        [#"StoreType" = "america", #"Order" = 336, #"Ratio" = 46.67, #"Path" = 823],
					        [#"StoreType" = "chain", #"Order" = 871, #"Ratio" = 410.9, #"Path" = 139],
					        [#"StoreType" = "karen", #"Order" = 24, #"Ratio" = 535.86, #"Path" = 701],
					        [#"StoreType" = "dd", #"Order" = 114, #"Ratio" = 773.49, #"Path" = 924],
					        [#"StoreType" = "kiss", #"Order" = 481, #"Ratio" = 577.63, #"Path" = 528],
					        [#"StoreType" = "removal", #"Order" = 596, #"Ratio" = 262.25, #"Path" = 121],
					        [#"StoreType" = "citysearch", #"Order" = 386, #"Ratio" = 810.84, #"Path" = 236],
					        [#"StoreType" = "antenna", #"Order" = 78, #"Ratio" = 987.29, #"Path" = 633],
					        [#"StoreType" = "fiscal", #"Order" = 326, #"Ratio" = 891.03, #"Path" = 220],
					        [#"StoreType" = "mod", #"Order" = 628, #"Ratio" = 554.37, #"Path" = 917],
					        [#"StoreType" = "right", #"Order" = 669, #"Ratio" = 30.8, #"Path" = 10],
					        [#"StoreType" = "francis", #"Order" = 892, #"Ratio" = 468.13, #"Path" = 701],
					        [#"StoreType" = "teachers", #"Order" = 219, #"Ratio" = 84.75, #"Path" = 675],
					        [#"StoreType" = "lift", #"Order" = 695, #"Ratio" = 577.22, #"Path" = 394],
					        [#"StoreType" = "dial", #"Order" = 199, #"Ratio" = 268.62, #"Path" = 508],
					        [#"StoreType" = "establishment", #"Order" = 907, #"Ratio" = 308.28, #"Path" = 953],
					        [#"StoreType" = "breasts", #"Order" = 865, #"Ratio" = 363.21, #"Path" = 497],
					        [#"StoreType" = "begins", #"Order" = 286, #"Ratio" = 341.86, #"Path" = 399],
					        [#"StoreType" = "now", #"Order" = 54, #"Ratio" = 804.14, #"Path" = 120],
					        [#"StoreType" = "belgium", #"Order" = 475, #"Ratio" = 747.78, #"Path" = 752],
					        [#"StoreType" = "scale", #"Order" = 248, #"Ratio" = 716.06, #"Path" = 825],
					        [#"StoreType" = "false", #"Order" = 133, #"Ratio" = 622.82, #"Path" = 902],
					        [#"StoreType" = "areas", #"Order" = 280, #"Ratio" = 694.01, #"Path" = 37],
					        [#"StoreType" = "featured", #"Order" = 810, #"Ratio" = 794.1, #"Path" = 509],
					        [#"StoreType" = "painting", #"Order" = 925, #"Ratio" = 311.26, #"Path" = 545],
					        [#"StoreType" = "handheld", #"Order" = 322, #"Ratio" = 468.35, #"Path" = 443],
					        [#"StoreType" = "woods", #"Order" = 902, #"Ratio" = 195.49, #"Path" = 114],
					        [#"StoreType" = "audit", #"Order" = 823, #"Ratio" = 241.76, #"Path" = 930],
					        [#"StoreType" = "cnet", #"Order" = 482, #"Ratio" = 68.51, #"Path" = 387],
					        [#"StoreType" = "hey", #"Order" = 496, #"Ratio" = 823.42, #"Path" = 839],
					        [#"StoreType" = "certified", #"Order" = 29, #"Ratio" = 923.41, #"Path" = 997],
					        [#"StoreType" = "falls", #"Order" = 554, #"Ratio" = 501.83, #"Path" = 28],
					        [#"StoreType" = "release", #"Order" = 190, #"Ratio" = 27.63, #"Path" = 183],
					        [#"StoreType" = "freedom", #"Order" = 372, #"Ratio" = 76.62, #"Path" = 790],
					        [#"StoreType" = "index", #"Order" = 848, #"Ratio" = 388.87, #"Path" = 792],
					        [#"StoreType" = "clips", #"Order" = 822, #"Ratio" = 672.12, #"Path" = 74],
					        [#"StoreType" = "ut", #"Order" = 260, #"Ratio" = 664.62, #"Path" = 492],
					        [#"StoreType" = "fraud", #"Order" = 336, #"Ratio" = 575.45, #"Path" = 266],
					        [#"StoreType" = "money", #"Order" = 185, #"Ratio" = 631.75, #"Path" = 370],
					        [#"StoreType" = "frame", #"Order" = 555, #"Ratio" = 775.66, #"Path" = 420],
					        [#"StoreType" = "curve", #"Order" = 363, #"Ratio" = 309.71, #"Path" = 655],
					        [#"StoreType" = "advertisement", #"Order" = 71, #"Ratio" = 453.23, #"Path" = 766],
					        [#"StoreType" = "folks", #"Order" = 364, #"Ratio" = 5.99, #"Path" = 643],
					        [#"StoreType" = "seeing", #"Order" = 327, #"Ratio" = 394.3, #"Path" = 896],
					        [#"StoreType" = "skin", #"Order" = 434, #"Ratio" = 610.59, #"Path" = 467],
					        [#"StoreType" = "haven", #"Order" = 381, #"Ratio" = 259.23, #"Path" = 405],
					        [#"StoreType" = "anything", #"Order" = 776, #"Ratio" = 563.26, #"Path" = 513],
					        [#"StoreType" = "taylor", #"Order" = 107, #"Ratio" = 965.21, #"Path" = 709],
					        [#"StoreType" = "rough", #"Order" = 470, #"Ratio" = 744.25, #"Path" = 570],
					        [#"StoreType" = "muscle", #"Order" = 970, #"Ratio" = 400.87, #"Path" = 40],
					        [#"StoreType" = "productions", #"Order" = 806, #"Ratio" = 140.74, #"Path" = 629],
					        [#"StoreType" = "pdf", #"Order" = 392, #"Ratio" = 37.85, #"Path" = 849],
					        [#"StoreType" = "male", #"Order" = 565, #"Ratio" = 165.1, #"Path" = 532],
					        [#"StoreType" = "directly", #"Order" = 31, #"Ratio" = 83.2, #"Path" = 412],
					        [#"StoreType" = "permanent", #"Order" = 476, #"Ratio" = 34.07, #"Path" = 242],
					        [#"StoreType" = "halloween", #"Order" = 433, #"Ratio" = 925.36, #"Path" = 25],
					        [#"StoreType" = "agency", #"Order" = 725, #"Ratio" = 82.33, #"Path" = 369],
					        [#"StoreType" = "dc", #"Order" = 457, #"Ratio" = 759.84, #"Path" = 69],
					        [#"StoreType" = "licensing", #"Order" = 262, #"Ratio" = 582.22, #"Path" = 496],
					        [#"StoreType" = "juan", #"Order" = 688, #"Ratio" = 716.37, #"Path" = 549],
					        [#"StoreType" = "slideshow", #"Order" = 49, #"Ratio" = 190.26, #"Path" = 714],
					        [#"StoreType" = "petition", #"Order" = 421, #"Ratio" = 736.3, #"Path" = 681],
					        [#"StoreType" = "grace", #"Order" = 378, #"Ratio" = 870.86, #"Path" = 207],
					        [#"StoreType" = "differences", #"Order" = 643, #"Ratio" = 961.17, #"Path" = 405],
					        [#"StoreType" = "afternoon", #"Order" = 778, #"Ratio" = 88.59, #"Path" = 95],
					        [#"StoreType" = "forums", #"Order" = 863, #"Ratio" = 290.14, #"Path" = 466],
					        [#"StoreType" = "indicators", #"Order" = 419, #"Ratio" = 607.23, #"Path" = 868],
					        [#"StoreType" = "wine", #"Order" = 201, #"Ratio" = 922.03, #"Path" = 765],
					        [#"StoreType" = "special", #"Order" = 768, #"Ratio" = 209.2, #"Path" = 882],
					        [#"StoreType" = "enemy", #"Order" = 388, #"Ratio" = 194.58, #"Path" = 355],
					        [#"StoreType" = "pics", #"Order" = 331, #"Ratio" = 438.11, #"Path" = 557],
					        [#"StoreType" = "equally", #"Order" = 487, #"Ratio" = 988.6, #"Path" = 87],
					        [#"StoreType" = "bikini", #"Order" = 422, #"Ratio" = 141.27, #"Path" = 421],
					        [#"StoreType" = "minutes", #"Order" = 706, #"Ratio" = 831.66, #"Path" = 806],
					        [#"StoreType" = "digest", #"Order" = 36, #"Ratio" = 10.28, #"Path" = 931],
					        [#"StoreType" = "plc", #"Order" = 353, #"Ratio" = 994.52, #"Path" = 304],
					        [#"StoreType" = "string", #"Order" = 472, #"Ratio" = 932.13, #"Path" = 86],
					        [#"StoreType" = "angeles", #"Order" = 145, #"Ratio" = 191.67, #"Path" = 899],
					        [#"StoreType" = "su", #"Order" = 49, #"Ratio" = 824.66, #"Path" = 682],
					        [#"StoreType" = "edinburgh", #"Order" = 270, #"Ratio" = 749.55, #"Path" = 725],
					        [#"StoreType" = "smoke", #"Order" = 337, #"Ratio" = 182.62, #"Path" = 479],
					        [#"StoreType" = "may", #"Order" = 177, #"Ratio" = 71.77, #"Path" = 396],
					        [#"StoreType" = "appearing", #"Order" = 556, #"Ratio" = 489.22, #"Path" = 228],
					        [#"StoreType" = "division", #"Order" = 524, #"Ratio" = 131.0, #"Path" = 545],
					        [#"StoreType" = "stretch", #"Order" = 510, #"Ratio" = 0.16, #"Path" = 231],
					        [#"StoreType" = "foster", #"Order" = 672, #"Ratio" = 699.41, #"Path" = 607],
					        [#"StoreType" = "informed", #"Order" = 602, #"Ratio" = 821.42, #"Path" = 816],
					        [#"StoreType" = "philadelphia", #"Order" = 159, #"Ratio" = 102.64, #"Path" = 410],
					        [#"StoreType" = "lawyers", #"Order" = 853, #"Ratio" = 629.59, #"Path" = 747],
					        [#"StoreType" = "operational", #"Order" = 82, #"Ratio" = 106.14, #"Path" = 214],
					        [#"StoreType" = "spot", #"Order" = 793, #"Ratio" = 599.15, #"Path" = 378],
					        [#"StoreType" = "bs", #"Order" = 681, #"Ratio" = 452.78, #"Path" = 14],
					        [#"StoreType" = "salt", #"Order" = 862, #"Ratio" = 63.52, #"Path" = 519],
					        [#"StoreType" = "that", #"Order" = 827, #"Ratio" = 10.85, #"Path" = 607],
					        [#"StoreType" = "cuts", #"Order" = 565, #"Ratio" = 988.43, #"Path" = 968],
					        [#"StoreType" = "bidder", #"Order" = 547, #"Ratio" = 673.04, #"Path" = 3],
					        [#"StoreType" = "strength", #"Order" = 279, #"Ratio" = 430.15, #"Path" = 750],
					        [#"StoreType" = "congress", #"Order" = 51, #"Ratio" = 396.74, #"Path" = 180],
					        [#"StoreType" = "em", #"Order" = 523, #"Ratio" = 592.67, #"Path" = 643],
					        [#"StoreType" = "ingredients", #"Order" = 531, #"Ratio" = 979.28, #"Path" = 972],
					        [#"StoreType" = "others", #"Order" = 8, #"Ratio" = 319.96, #"Path" = 731],
					        [#"StoreType" = "heard", #"Order" = 986, #"Ratio" = 764.17, #"Path" = 767],
					        [#"StoreType" = "volunteer", #"Order" = 919, #"Ratio" = 129.09, #"Path" = 963],
					        [#"StoreType" = "orchestra", #"Order" = 710, #"Ratio" = 992.18, #"Path" = 683],
					        [#"StoreType" = "body", #"Order" = 370, #"Ratio" = 635.16, #"Path" = 473],
					        [#"StoreType" = "americans", #"Order" = 401, #"Ratio" = 144.99, #"Path" = 898],
					        [#"StoreType" = "src", #"Order" = 970, #"Ratio" = 748.3, #"Path" = 161],
					        [#"StoreType" = "emotional", #"Order" = 232, #"Ratio" = 877.38, #"Path" = 940],
					        [#"StoreType" = "producing", #"Order" = 412, #"Ratio" = 257.56, #"Path" = 954],
					        [#"StoreType" = "wage", #"Order" = 631, #"Ratio" = 772.51, #"Path" = 873],
					        [#"StoreType" = "higher", #"Order" = 636, #"Ratio" = 772.47, #"Path" = 218],
					        [#"StoreType" = "billing", #"Order" = 691, #"Ratio" = 680.74, #"Path" = 271],
					        [#"StoreType" = "too", #"Order" = 436, #"Ratio" = 712.2, #"Path" = 651],
					        [#"StoreType" = "mens", #"Order" = 42, #"Ratio" = 606.7, #"Path" = 619],
					        [#"StoreType" = "whose", #"Order" = 906, #"Ratio" = 987.67, #"Path" = 967],
					        [#"StoreType" = "medicine", #"Order" = 330, #"Ratio" = 377.79, #"Path" = 992],
					        [#"StoreType" = "margaret", #"Order" = 25, #"Ratio" = 246.6, #"Path" = 197],
					        [#"StoreType" = "identity", #"Order" = 208, #"Ratio" = 984.41, #"Path" = 433],
					        [#"StoreType" = "lawyers", #"Order" = 698, #"Ratio" = 260.89, #"Path" = 985],
					        [#"StoreType" = "male", #"Order" = 711, #"Ratio" = 818.84, #"Path" = 211],
					        [#"StoreType" = "assets", #"Order" = 703, #"Ratio" = 584.79, #"Path" = 871],
					        [#"StoreType" = "circumstances", #"Order" = 30, #"Ratio" = 154.48, #"Path" = 846],
					        [#"StoreType" = "smaller", #"Order" = 403, #"Ratio" = 32.84, #"Path" = 845],
					        [#"StoreType" = "foods", #"Order" = 146, #"Ratio" = 971.16, #"Path" = 346],
					        [#"StoreType" = "mile", #"Order" = 686, #"Ratio" = 340.28, #"Path" = 321],
					        [#"StoreType" = "appear", #"Order" = 61, #"Ratio" = 865.08, #"Path" = 705],
					        [#"StoreType" = "stands", #"Order" = 188, #"Ratio" = 35.21, #"Path" = 151],
					        [#"StoreType" = "shut", #"Order" = 671, #"Ratio" = 29.04, #"Path" = 815],
					        [#"StoreType" = "law", #"Order" = 667, #"Ratio" = 391.08, #"Path" = 365],
					        [#"StoreType" = "singapore", #"Order" = 144, #"Ratio" = 951.99, #"Path" = 996],
					        [#"StoreType" = "chemicals", #"Order" = 104, #"Ratio" = 691.03, #"Path" = 260],
					        [#"StoreType" = "double", #"Order" = 791, #"Ratio" = 968.68, #"Path" = 88],
					        [#"StoreType" = "super", #"Order" = 688, #"Ratio" = 214.15, #"Path" = 783],
					        [#"StoreType" = "api", #"Order" = 652, #"Ratio" = 364.24, #"Path" = 20],
					        [#"StoreType" = "strip", #"Order" = 133, #"Ratio" = 94.81, #"Path" = 1],
					        [#"StoreType" = "however", #"Order" = 650, #"Ratio" = 466.52, #"Path" = 203],
					        [#"StoreType" = "hosts", #"Order" = 833, #"Ratio" = 903.29, #"Path" = 146],
					        [#"StoreType" = "beds", #"Order" = 167, #"Ratio" = 788.99, #"Path" = 473],
					        [#"StoreType" = "measurements", #"Order" = 357, #"Ratio" = 223.32, #"Path" = 196],
					        [#"StoreType" = "deliver", #"Order" = 796, #"Ratio" = 305.11, #"Path" = 906],
					        [#"StoreType" = "keeps", #"Order" = 3, #"Ratio" = 705.11, #"Path" = 676],
					        [#"StoreType" = "ground", #"Order" = 906, #"Ratio" = 463.14, #"Path" = 754],
					        [#"StoreType" = "assessment", #"Order" = 136, #"Ratio" = 855.94, #"Path" = 303],
					        [#"StoreType" = "eg", #"Order" = 916, #"Ratio" = 235.13, #"Path" = 56],
					        [#"StoreType" = "toy", #"Order" = 614, #"Ratio" = 358.36, #"Path" = 587],
					        [#"StoreType" = "believe", #"Order" = 237, #"Ratio" = 307.83, #"Path" = 942],
					        [#"StoreType" = "vi", #"Order" = 42, #"Ratio" = 398.8, #"Path" = 582],
					        [#"StoreType" = "demands", #"Order" = 37, #"Ratio" = 277.8, #"Path" = 422],
					        [#"StoreType" = "bit", #"Order" = 556, #"Ratio" = 942.62, #"Path" = 487],
					        [#"StoreType" = "wave", #"Order" = 33, #"Ratio" = 470.37, #"Path" = 878],
					        [#"StoreType" = "colors", #"Order" = 744, #"Ratio" = 726.78, #"Path" = 787],
					        [#"StoreType" = "bedding", #"Order" = 531, #"Ratio" = 953.94, #"Path" = 768],
					        [#"StoreType" = "ralph", #"Order" = 192, #"Ratio" = 159.66, #"Path" = 875],
					        [#"StoreType" = "oh", #"Order" = 709, #"Ratio" = 516.28, #"Path" = 683],
					        [#"StoreType" = "arcade", #"Order" = 354, #"Ratio" = 359.03, #"Path" = 267],
					        [#"StoreType" = "sms", #"Order" = 796, #"Ratio" = 799.51, #"Path" = 986],
					        [#"StoreType" = "ticket", #"Order" = 48, #"Ratio" = 793.43, #"Path" = 430],
					        [#"StoreType" = "defense", #"Order" = 984, #"Ratio" = 962.9, #"Path" = 479],
					        [#"StoreType" = "founded", #"Order" = 482, #"Ratio" = 303.23, #"Path" = 614],
					        [#"StoreType" = "medium", #"Order" = 265, #"Ratio" = 719.21, #"Path" = 563],
					        [#"StoreType" = "ave", #"Order" = 260, #"Ratio" = 910.19, #"Path" = 283],
					        [#"StoreType" = "seats", #"Order" = 780, #"Ratio" = 996.02, #"Path" = 773],
					        [#"StoreType" = "mountains", #"Order" = 34, #"Ratio" = 87.62, #"Path" = 734],
					        [#"StoreType" = "literary", #"Order" = 209, #"Ratio" = 92.57, #"Path" = 317],
					        [#"StoreType" = "operator", #"Order" = 942, #"Ratio" = 236.5, #"Path" = 771],
					        [#"StoreType" = "effects", #"Order" = 449, #"Ratio" = 243.57, #"Path" = 593],
					        [#"StoreType" = "daughter", #"Order" = 930, #"Ratio" = 171.07, #"Path" = 225],
					        [#"StoreType" = "agencies", #"Order" = 109, #"Ratio" = 378.21, #"Path" = 338],
					        [#"StoreType" = "person", #"Order" = 229, #"Ratio" = 561.24, #"Path" = 509],
					        [#"StoreType" = "holdings", #"Order" = 540, #"Ratio" = 995.33, #"Path" = 881],
					        [#"StoreType" = "advertise", #"Order" = 263, #"Ratio" = 807.85, #"Path" = 23],
					        [#"StoreType" = "basketball", #"Order" = 929, #"Ratio" = 671.61, #"Path" = 818],
					        [#"StoreType" = "electricity", #"Order" = 961, #"Ratio" = 514.59, #"Path" = 409],
					        [#"StoreType" = "catering", #"Order" = 821, #"Ratio" = 436.12, #"Path" = 403],
					        [#"StoreType" = "euro", #"Order" = 847, #"Ratio" = 78.37, #"Path" = 800],
					        [#"StoreType" = "trailer", #"Order" = 765, #"Ratio" = 966.99, #"Path" = 191],
					        [#"StoreType" = "ending", #"Order" = 817, #"Ratio" = 657.19, #"Path" = 898],
					        [#"StoreType" = "globe", #"Order" = 538, #"Ratio" = 37.71, #"Path" = 224],
					        [#"StoreType" = "cables", #"Order" = 145, #"Ratio" = 448.68, #"Path" = 338],
					        [#"StoreType" = "officer", #"Order" = 836, #"Ratio" = 615.18, #"Path" = 610],
					        [#"StoreType" = "notice", #"Order" = 90, #"Ratio" = 864.08, #"Path" = 508],
					        [#"StoreType" = "announced", #"Order" = 872, #"Ratio" = 160.51, #"Path" = 219],
					        [#"StoreType" = "delete", #"Order" = 325, #"Ratio" = 830.89, #"Path" = 601],
					        [#"StoreType" = "suitable", #"Order" = 654, #"Ratio" = 699.35, #"Path" = 277],
					        [#"StoreType" = "extent", #"Order" = 228, #"Ratio" = 283.87, #"Path" = 368],
					        [#"StoreType" = "observation", #"Order" = 419, #"Ratio" = 200.41, #"Path" = 950],
					        [#"StoreType" = "major", #"Order" = 345, #"Ratio" = 927.23, #"Path" = 246],
					        [#"StoreType" = "mine", #"Order" = 368, #"Ratio" = 806.86, #"Path" = 630],
					        [#"StoreType" = "panama", #"Order" = 547, #"Ratio" = 557.33, #"Path" = 92],
					        [#"StoreType" = "forms", #"Order" = 134, #"Ratio" = 673.57, #"Path" = 938],
					        [#"StoreType" = "gone", #"Order" = 45, #"Ratio" = 664.93, #"Path" = 931],
					        [#"StoreType" = "sad", #"Order" = 721, #"Ratio" = 749.71, #"Path" = 891],
					        [#"StoreType" = "ethics", #"Order" = 150, #"Ratio" = 376.15, #"Path" = 714],
					        [#"StoreType" = "species", #"Order" = 736, #"Ratio" = 60.15, #"Path" = 904],
					        [#"StoreType" = "modern", #"Order" = 316, #"Ratio" = 943.08, #"Path" = 719],
					        [#"StoreType" = "mixed", #"Order" = 892, #"Ratio" = 60.47, #"Path" = 119],
					        [#"StoreType" = "meta", #"Order" = 102, #"Ratio" = 560.47, #"Path" = 522],
					        [#"StoreType" = "lodge", #"Order" = 271, #"Ratio" = 31.36, #"Path" = 868],
					        [#"StoreType" = "mistake", #"Order" = 268, #"Ratio" = 660.62, #"Path" = 788],
					        [#"StoreType" = "beam", #"Order" = 369, #"Ratio" = 464.67, #"Path" = 889],
					        [#"StoreType" = "meals", #"Order" = 587, #"Ratio" = 676.1, #"Path" = 979],
					        [#"StoreType" = "leave", #"Order" = 762, #"Ratio" = 383.49, #"Path" = 310],
					        [#"StoreType" = "requirement", #"Order" = 190, #"Ratio" = 530.86, #"Path" = 950],
					        [#"StoreType" = "cookie", #"Order" = 734, #"Ratio" = 140.3, #"Path" = 397],
					        [#"StoreType" = "matter", #"Order" = 860, #"Ratio" = 701.33, #"Path" = 653],
					        [#"StoreType" = "commissioner", #"Order" = 35, #"Ratio" = 550.54, #"Path" = 711],
					        [#"StoreType" = "counties", #"Order" = 942, #"Ratio" = 207.15, #"Path" = 675],
					        [#"StoreType" = "recycling", #"Order" = 169, #"Ratio" = 24.63, #"Path" = 923],
					        [#"StoreType" = "folks", #"Order" = 826, #"Ratio" = 325.26, #"Path" = 977],
					        [#"StoreType" = "third", #"Order" = 800, #"Ratio" = 106.7, #"Path" = 13],
					        [#"StoreType" = "residential", #"Order" = 540, #"Ratio" = 966.22, #"Path" = 586],
					        [#"StoreType" = "resistant", #"Order" = 197, #"Ratio" = 955.61, #"Path" = 491],
					        [#"StoreType" = "planet", #"Order" = 187, #"Ratio" = 660.81, #"Path" = 574],
					        [#"StoreType" = "those", #"Order" = 760, #"Ratio" = 552.28, #"Path" = 407],
					        [#"StoreType" = "matthew", #"Order" = 36, #"Ratio" = 654.12, #"Path" = 380],
					        [#"StoreType" = "degrees", #"Order" = 528, #"Ratio" = 719.72, #"Path" = 177],
					        [#"StoreType" = "underground", #"Order" = 284, #"Ratio" = 418.79, #"Path" = 326],
					        [#"StoreType" = "why", #"Order" = 313, #"Ratio" = 737.03, #"Path" = 859],
					        [#"StoreType" = "give", #"Order" = 813, #"Ratio" = 825.9, #"Path" = 103],
					        [#"StoreType" = "died", #"Order" = 856, #"Ratio" = 690.34, #"Path" = 266],
					        [#"StoreType" = "muscle", #"Order" = 138, #"Ratio" = 833.39, #"Path" = 272],
					        [#"StoreType" = "montana", #"Order" = 28, #"Ratio" = 808.52, #"Path" = 423],
					        [#"StoreType" = "actually", #"Order" = 997, #"Ratio" = 760.06, #"Path" = 380],
					        [#"StoreType" = "public", #"Order" = 157, #"Ratio" = 483.38, #"Path" = 335],
					        [#"StoreType" = "wed", #"Order" = 292, #"Ratio" = 217.9, #"Path" = 5],
					        [#"StoreType" = "each", #"Order" = 772, #"Ratio" = 844.94, #"Path" = 202],
					        [#"StoreType" = "facial", #"Order" = 728, #"Ratio" = 420.63, #"Path" = 521],
					        [#"StoreType" = "medicare", #"Order" = 670, #"Ratio" = 166.94, #"Path" = 779],
					        [#"StoreType" = "dad", #"Order" = 959, #"Ratio" = 666.69, #"Path" = 587],
					        [#"StoreType" = "dry", #"Order" = 806, #"Ratio" = 515.48, #"Path" = 130],
					        [#"StoreType" = "ya", #"Order" = 798, #"Ratio" = 603.02, #"Path" = 753],
					        [#"StoreType" = "companies", #"Order" = 757, #"Ratio" = 918.29, #"Path" = 511],
					        [#"StoreType" = "tasks", #"Order" = 766, #"Ratio" = 508.01, #"Path" = 146],
					        [#"StoreType" = "figures", #"Order" = 926, #"Ratio" = 865.05, #"Path" = 559],
					        [#"StoreType" = "birmingham", #"Order" = 754, #"Ratio" = 380.11, #"Path" = 934],
					        [#"StoreType" = "counties", #"Order" = 542, #"Ratio" = 714.2, #"Path" = 346],
					        [#"StoreType" = "arm", #"Order" = 516, #"Ratio" = 665.58, #"Path" = 724],
					        [#"StoreType" = "screening", #"Order" = 49, #"Ratio" = 771.97, #"Path" = 57],
					        [#"StoreType" = "glory", #"Order" = 574, #"Ratio" = 373.07, #"Path" = 467],
					        [#"StoreType" = "drunk", #"Order" = 237, #"Ratio" = 276.57, #"Path" = 929],
					        [#"StoreType" = "offer", #"Order" = 594, #"Ratio" = 81.36, #"Path" = 413],
					        [#"StoreType" = "animal", #"Order" = 169, #"Ratio" = 755.38, #"Path" = 580],
					        [#"StoreType" = "louis", #"Order" = 369, #"Ratio" = 385.87, #"Path" = 177],
					        [#"StoreType" = "range", #"Order" = 210, #"Ratio" = 425.55, #"Path" = 958],
					        [#"StoreType" = "north", #"Order" = 416, #"Ratio" = 151.5, #"Path" = 944],
					        [#"StoreType" = "schedules", #"Order" = 419, #"Ratio" = 432.97, #"Path" = 485],
					        [#"StoreType" = "double", #"Order" = 165, #"Ratio" = 54.03, #"Path" = 650],
					        [#"StoreType" = "municipal", #"Order" = 505, #"Ratio" = 268.86, #"Path" = 914],
					        [#"StoreType" = "advertisement", #"Order" = 774, #"Ratio" = 418.94, #"Path" = 352],
					        [#"StoreType" = "absolute", #"Order" = 569, #"Ratio" = 336.71, #"Path" = 168],
					        [#"StoreType" = "agencies", #"Order" = 814, #"Ratio" = 164.48, #"Path" = 85],
					        [#"StoreType" = "units", #"Order" = 900, #"Ratio" = 853.97, #"Path" = 58],
					        [#"StoreType" = "countries", #"Order" = 209, #"Ratio" = 665.33, #"Path" = 534],
					        [#"StoreType" = "holy", #"Order" = 435, #"Ratio" = 959.79, #"Path" = 543],
					        [#"StoreType" = "brass", #"Order" = 21, #"Ratio" = 530.06, #"Path" = 596],
					        [#"StoreType" = "portuguese", #"Order" = 603, #"Ratio" = 504.21, #"Path" = 37],
					        [#"StoreType" = "fleet", #"Order" = 962, #"Ratio" = 964.35, #"Path" = 597],
					        [#"StoreType" = "seat", #"Order" = 231, #"Ratio" = 520.06, #"Path" = 493],
					        [#"StoreType" = "each", #"Order" = 105, #"Ratio" = 91.29, #"Path" = 597],
					        [#"StoreType" = "child", #"Order" = 436, #"Ratio" = 6.32, #"Path" = 134],
					        [#"StoreType" = "quiz", #"Order" = 842, #"Ratio" = 77.09, #"Path" = 68],
					        [#"StoreType" = "networks", #"Order" = 917, #"Ratio" = 35.57, #"Path" = 167],
					        [#"StoreType" = "elizabeth", #"Order" = 462, #"Ratio" = 124.03, #"Path" = 705],
					        [#"StoreType" = "quarterly", #"Order" = 811, #"Ratio" = 687.43, #"Path" = 147],
					        [#"StoreType" = "when", #"Order" = 629, #"Ratio" = 979.93, #"Path" = 689],
					        [#"StoreType" = "soil", #"Order" = 706, #"Ratio" = 101.07, #"Path" = 197],
					        [#"StoreType" = "volunteers", #"Order" = 992, #"Ratio" = 689.28, #"Path" = 680],
					        [#"StoreType" = "pm", #"Order" = 984, #"Ratio" = 251.88, #"Path" = 614],
					        [#"StoreType" = "introduction", #"Order" = 127, #"Ratio" = 554.67, #"Path" = 270],
					        [#"StoreType" = "responsibility", #"Order" = 558, #"Ratio" = 145.78, #"Path" = 55],
					        [#"StoreType" = "meaning", #"Order" = 241, #"Ratio" = 49.97, #"Path" = 274],
					        [#"StoreType" = "being", #"Order" = 770, #"Ratio" = 217.72, #"Path" = 379],
					        [#"StoreType" = "totals", #"Order" = 380, #"Ratio" = 360.83, #"Path" = 959],
					        [#"StoreType" = "consult", #"Order" = 528, #"Ratio" = 543.04, #"Path" = 745],
					        [#"StoreType" = "supervisor", #"Order" = 950, #"Ratio" = 327.94, #"Path" = 699],
					        [#"StoreType" = "reference", #"Order" = 167, #"Ratio" = 768.15, #"Path" = 923],
					        [#"StoreType" = "districts", #"Order" = 24, #"Ratio" = 597.18, #"Path" = 289],
					        [#"StoreType" = "swedish", #"Order" = 229, #"Ratio" = 722.38, #"Path" = 437]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"StoreType", type text},
					        {"Order", Int64.Type},
					        {"Ratio", type number},
					        {"Path", Int64.Type}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table