table 'Sheet1_Sheet1 (waffle template)'
	lineageTag: 8afaad73-9a48-4bed-93c0-217f4f73ecaf

	column Row
		dataType: int64
		formatString: 0
		lineageTag: 67ba2676-528a-469f-b6b0-df4b117ab94b
		summarizeBy: sum
		sourceColumn: Row

		annotation SummarizationSetBy = Automatic

	column Column
		dataType: int64
		formatString: 0
		lineageTag: 52fa2e1c-ddc7-4046-af3d-ba177f0446e2
		summarizeBy: sum
		sourceColumn: Column

		annotation SummarizationSetBy = Automatic

	column Percentage
		dataType: double
		formatString: General Number
		lineageTag: 1162585b-d578-4162-a0f7-986d2eec2a01
		summarizeBy: sum
		sourceColumn: Percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Sheet1_Sheet1 (waffle template)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Row" = 296, #"Column" = 873, #"Percentage" = 9.6],
					        [#"Row" = 495, #"Column" = 638, #"Percentage" = 33.33],
					        [#"Row" = 336, #"Column" = 98, #"Percentage" = 92.96],
					        [#"Row" = 35, #"Column" = 276, #"Percentage" = 90.3],
					        [#"Row" = 740, #"Column" = 569, #"Percentage" = 92.57],
					        [#"Row" = 159, #"Column" = 274, #"Percentage" = 64.28],
					        [#"Row" = 38, #"Column" = 183, #"Percentage" = 64.38],
					        [#"Row" = 934, #"Column" = 240, #"Percentage" = 89.01],
					        [#"Row" = 466, #"Column" = 106, #"Percentage" = 69.8],
					        [#"Row" = 839, #"Column" = 730, #"Percentage" = 58.41],
					        [#"Row" = 944, #"Column" = 742, #"Percentage" = 40.31],
					        [#"Row" = 314, #"Column" = 932, #"Percentage" = 43.99],
					        [#"Row" = 307, #"Column" = 245, #"Percentage" = 98.37],
					        [#"Row" = 470, #"Column" = 344, #"Percentage" = 58.82],
					        [#"Row" = 337, #"Column" = 943, #"Percentage" = 38.02],
					        [#"Row" = 738, #"Column" = 152, #"Percentage" = 34.4],
					        [#"Row" = 254, #"Column" = 773, #"Percentage" = 17.41],
					        [#"Row" = 358, #"Column" = 811, #"Percentage" = 89.24],
					        [#"Row" = 98, #"Column" = 208, #"Percentage" = 65.53],
					        [#"Row" = 969, #"Column" = 629, #"Percentage" = 33.94],
					        [#"Row" = 456, #"Column" = 719, #"Percentage" = 85.32],
					        [#"Row" = 701, #"Column" = 855, #"Percentage" = 86.65],
					        [#"Row" = 832, #"Column" = 80, #"Percentage" = 18.63],
					        [#"Row" = 850, #"Column" = 756, #"Percentage" = 28.5],
					        [#"Row" = 448, #"Column" = 343, #"Percentage" = 78.25],
					        [#"Row" = 334, #"Column" = 117, #"Percentage" = 57.08],
					        [#"Row" = 637, #"Column" = 260, #"Percentage" = 76.51],
					        [#"Row" = 885, #"Column" = 928, #"Percentage" = 92.77],
					        [#"Row" = 694, #"Column" = 695, #"Percentage" = 26.06],
					        [#"Row" = 331, #"Column" = 480, #"Percentage" = 77.83],
					        [#"Row" = 402, #"Column" = 720, #"Percentage" = 29.34],
					        [#"Row" = 551, #"Column" = 593, #"Percentage" = 8.85],
					        [#"Row" = 975, #"Column" = 974, #"Percentage" = 85.51],
					        [#"Row" = 743, #"Column" = 505, #"Percentage" = 72.18],
					        [#"Row" = 707, #"Column" = 786, #"Percentage" = 79.46],
					        [#"Row" = 15, #"Column" = 183, #"Percentage" = 61.97],
					        [#"Row" = 77, #"Column" = 434, #"Percentage" = 35.7],
					        [#"Row" = 919, #"Column" = 499, #"Percentage" = 58.81],
					        [#"Row" = 327, #"Column" = 65, #"Percentage" = 92.92],
					        [#"Row" = 105, #"Column" = 780, #"Percentage" = 73.36],
					        [#"Row" = 515, #"Column" = 960, #"Percentage" = 31.63],
					        [#"Row" = 229, #"Column" = 51, #"Percentage" = 44.03],
					        [#"Row" = 490, #"Column" = 325, #"Percentage" = 11.0],
					        [#"Row" = 182, #"Column" = 454, #"Percentage" = 40.16],
					        [#"Row" = 497, #"Column" = 671, #"Percentage" = 33.14],
					        [#"Row" = 730, #"Column" = 855, #"Percentage" = 19.96],
					        [#"Row" = 527, #"Column" = 89, #"Percentage" = 94.56],
					        [#"Row" = 999, #"Column" = 410, #"Percentage" = 54.34],
					        [#"Row" = 251, #"Column" = 767, #"Percentage" = 2.97],
					        [#"Row" = 382, #"Column" = 37, #"Percentage" = 72.54],
					        [#"Row" = 260, #"Column" = 756, #"Percentage" = 46.39],
					        [#"Row" = 371, #"Column" = 824, #"Percentage" = 10.96],
					        [#"Row" = 83, #"Column" = 796, #"Percentage" = 24.01],
					        [#"Row" = 781, #"Column" = 565, #"Percentage" = 82.83],
					        [#"Row" = 732, #"Column" = 784, #"Percentage" = 73.63],
					        [#"Row" = 720, #"Column" = 871, #"Percentage" = 6.58],
					        [#"Row" = 575, #"Column" = 121, #"Percentage" = 10.61],
					        [#"Row" = 118, #"Column" = 85, #"Percentage" = 58.5],
					        [#"Row" = 891, #"Column" = 834, #"Percentage" = 4.59],
					        [#"Row" = 272, #"Column" = 430, #"Percentage" = 29.11],
					        [#"Row" = 369, #"Column" = 77, #"Percentage" = 4.93],
					        [#"Row" = 446, #"Column" = 705, #"Percentage" = 66.97],
					        [#"Row" = 707, #"Column" = 136, #"Percentage" = 41.12],
					        [#"Row" = 481, #"Column" = 263, #"Percentage" = 49.72],
					        [#"Row" = 862, #"Column" = 732, #"Percentage" = 10.86],
					        [#"Row" = 330, #"Column" = 919, #"Percentage" = 40.26],
					        [#"Row" = 606, #"Column" = 618, #"Percentage" = 92.66],
					        [#"Row" = 241, #"Column" = 727, #"Percentage" = 99.4],
					        [#"Row" = 766, #"Column" = 955, #"Percentage" = 74.68],
					        [#"Row" = 833, #"Column" = 645, #"Percentage" = 20.92],
					        [#"Row" = 677, #"Column" = 618, #"Percentage" = 33.76],
					        [#"Row" = 721, #"Column" = 611, #"Percentage" = 57.44],
					        [#"Row" = 789, #"Column" = 802, #"Percentage" = 11.23],
					        [#"Row" = 14, #"Column" = 867, #"Percentage" = 89.96],
					        [#"Row" = 451, #"Column" = 80, #"Percentage" = 84.15],
					        [#"Row" = 731, #"Column" = 110, #"Percentage" = 21.8],
					        [#"Row" = 358, #"Column" = 123, #"Percentage" = 83.46],
					        [#"Row" = 853, #"Column" = 982, #"Percentage" = 12.78],
					        [#"Row" = 918, #"Column" = 714, #"Percentage" = 9.23],
					        [#"Row" = 67, #"Column" = 778, #"Percentage" = 75.46],
					        [#"Row" = 638, #"Column" = 861, #"Percentage" = 47.8],
					        [#"Row" = 627, #"Column" = 923, #"Percentage" = 75.89],
					        [#"Row" = 620, #"Column" = 993, #"Percentage" = 44.95],
					        [#"Row" = 380, #"Column" = 215, #"Percentage" = 19.55],
					        [#"Row" = 776, #"Column" = 452, #"Percentage" = 40.87],
					        [#"Row" = 49, #"Column" = 749, #"Percentage" = 30.43],
					        [#"Row" = 333, #"Column" = 294, #"Percentage" = 65.12],
					        [#"Row" = 907, #"Column" = 577, #"Percentage" = 42.08],
					        [#"Row" = 649, #"Column" = 153, #"Percentage" = 50.48],
					        [#"Row" = 558, #"Column" = 385, #"Percentage" = 49.14],
					        [#"Row" = 93, #"Column" = 581, #"Percentage" = 14.66],
					        [#"Row" = 846, #"Column" = 839, #"Percentage" = 81.13],
					        [#"Row" = 444, #"Column" = 521, #"Percentage" = 95.71],
					        [#"Row" = 722, #"Column" = 486, #"Percentage" = 3.74],
					        [#"Row" = 303, #"Column" = 345, #"Percentage" = 95.74],
					        [#"Row" = 173, #"Column" = 163, #"Percentage" = 49.42],
					        [#"Row" = 713, #"Column" = 624, #"Percentage" = 61.32],
					        [#"Row" = 907, #"Column" = 342, #"Percentage" = 5.51],
					        [#"Row" = 47, #"Column" = 219, #"Percentage" = 92.22],
					        [#"Row" = 233, #"Column" = 615, #"Percentage" = 79.92],
					        [#"Row" = 495, #"Column" = 164, #"Percentage" = 18.54],
					        [#"Row" = 982, #"Column" = 85, #"Percentage" = 14.16],
					        [#"Row" = 399, #"Column" = 896, #"Percentage" = 32.07],
					        [#"Row" = 737, #"Column" = 198, #"Percentage" = 69.4],
					        [#"Row" = 236, #"Column" = 957, #"Percentage" = 88.82],
					        [#"Row" = 348, #"Column" = 387, #"Percentage" = 20.67],
					        [#"Row" = 220, #"Column" = 208, #"Percentage" = 4.35],
					        [#"Row" = 755, #"Column" = 452, #"Percentage" = 74.92],
					        [#"Row" = 689, #"Column" = 59, #"Percentage" = 2.98],
					        [#"Row" = 111, #"Column" = 788, #"Percentage" = 34.21],
					        [#"Row" = 956, #"Column" = 862, #"Percentage" = 61.92],
					        [#"Row" = 442, #"Column" = 971, #"Percentage" = 22.25],
					        [#"Row" = 344, #"Column" = 692, #"Percentage" = 49.4],
					        [#"Row" = 29, #"Column" = 908, #"Percentage" = 61.63],
					        [#"Row" = 873, #"Column" = 561, #"Percentage" = 9.12],
					        [#"Row" = 858, #"Column" = 548, #"Percentage" = 78.68],
					        [#"Row" = 44, #"Column" = 648, #"Percentage" = 32.47],
					        [#"Row" = 921, #"Column" = 568, #"Percentage" = 59.01],
					        [#"Row" = 945, #"Column" = 35, #"Percentage" = 96.34],
					        [#"Row" = 146, #"Column" = 668, #"Percentage" = 1.71],
					        [#"Row" = 52, #"Column" = 785, #"Percentage" = 64.1],
					        [#"Row" = 270, #"Column" = 698, #"Percentage" = 31.45],
					        [#"Row" = 984, #"Column" = 173, #"Percentage" = 19.46],
					        [#"Row" = 653, #"Column" = 634, #"Percentage" = 96.31],
					        [#"Row" = 594, #"Column" = 544, #"Percentage" = 94.94],
					        [#"Row" = 318, #"Column" = 643, #"Percentage" = 35.39],
					        [#"Row" = 261, #"Column" = 364, #"Percentage" = 21.78],
					        [#"Row" = 172, #"Column" = 733, #"Percentage" = 35.88],
					        [#"Row" = 789, #"Column" = 257, #"Percentage" = 68.83],
					        [#"Row" = 141, #"Column" = 640, #"Percentage" = 16.43],
					        [#"Row" = 243, #"Column" = 171, #"Percentage" = 35.88],
					        [#"Row" = 328, #"Column" = 608, #"Percentage" = 35.97],
					        [#"Row" = 836, #"Column" = 640, #"Percentage" = 98.98],
					        [#"Row" = 128, #"Column" = 953, #"Percentage" = 97.47],
					        [#"Row" = 798, #"Column" = 517, #"Percentage" = 22.7],
					        [#"Row" = 477, #"Column" = 581, #"Percentage" = 46.5],
					        [#"Row" = 472, #"Column" = 273, #"Percentage" = 62.59],
					        [#"Row" = 322, #"Column" = 792, #"Percentage" = 33.94],
					        [#"Row" = 529, #"Column" = 650, #"Percentage" = 74.16],
					        [#"Row" = 625, #"Column" = 939, #"Percentage" = 35.12],
					        [#"Row" = 433, #"Column" = 409, #"Percentage" = 36.78],
					        [#"Row" = 719, #"Column" = 854, #"Percentage" = 64.29],
					        [#"Row" = 596, #"Column" = 157, #"Percentage" = 46.72],
					        [#"Row" = 862, #"Column" = 369, #"Percentage" = 45.56],
					        [#"Row" = 698, #"Column" = 812, #"Percentage" = 31.32],
					        [#"Row" = 845, #"Column" = 72, #"Percentage" = 96.24],
					        [#"Row" = 809, #"Column" = 415, #"Percentage" = 12.61],
					        [#"Row" = 859, #"Column" = 591, #"Percentage" = 1.96],
					        [#"Row" = 887, #"Column" = 206, #"Percentage" = 67.52],
					        [#"Row" = 650, #"Column" = 123, #"Percentage" = 9.5],
					        [#"Row" = 792, #"Column" = 544, #"Percentage" = 46.04],
					        [#"Row" = 314, #"Column" = 795, #"Percentage" = 90.95],
					        [#"Row" = 837, #"Column" = 105, #"Percentage" = 4.33],
					        [#"Row" = 429, #"Column" = 965, #"Percentage" = 83.63],
					        [#"Row" = 986, #"Column" = 176, #"Percentage" = 45.38],
					        [#"Row" = 693, #"Column" = 360, #"Percentage" = 41.31],
					        [#"Row" = 978, #"Column" = 134, #"Percentage" = 66.97],
					        [#"Row" = 402, #"Column" = 741, #"Percentage" = 22.01],
					        [#"Row" = 998, #"Column" = 297, #"Percentage" = 58.35],
					        [#"Row" = 869, #"Column" = 179, #"Percentage" = 31.55],
					        [#"Row" = 410, #"Column" = 347, #"Percentage" = 39.87],
					        [#"Row" = 524, #"Column" = 821, #"Percentage" = 50.97],
					        [#"Row" = 231, #"Column" = 22, #"Percentage" = 21.64],
					        [#"Row" = 206, #"Column" = 867, #"Percentage" = 87.78],
					        [#"Row" = 327, #"Column" = 957, #"Percentage" = 48.84],
					        [#"Row" = 75, #"Column" = 736, #"Percentage" = 23.46],
					        [#"Row" = 565, #"Column" = 124, #"Percentage" = 34.7],
					        [#"Row" = 525, #"Column" = 644, #"Percentage" = 49.5],
					        [#"Row" = 779, #"Column" = 81, #"Percentage" = 62.0],
					        [#"Row" = 929, #"Column" = 925, #"Percentage" = 95.46],
					        [#"Row" = 589, #"Column" = 416, #"Percentage" = 56.13],
					        [#"Row" = 834, #"Column" = 57, #"Percentage" = 45.01],
					        [#"Row" = 711, #"Column" = 107, #"Percentage" = 64.46],
					        [#"Row" = 503, #"Column" = 728, #"Percentage" = 96.0],
					        [#"Row" = 617, #"Column" = 281, #"Percentage" = 5.1],
					        [#"Row" = 823, #"Column" = 203, #"Percentage" = 77.43],
					        [#"Row" = 962, #"Column" = 611, #"Percentage" = 28.04],
					        [#"Row" = 701, #"Column" = 791, #"Percentage" = 93.18],
					        [#"Row" = 30, #"Column" = 61, #"Percentage" = 24.98],
					        [#"Row" = 989, #"Column" = 932, #"Percentage" = 39.22],
					        [#"Row" = 470, #"Column" = 775, #"Percentage" = 15.23],
					        [#"Row" = 194, #"Column" = 929, #"Percentage" = 57.74],
					        [#"Row" = 277, #"Column" = 720, #"Percentage" = 36.52],
					        [#"Row" = 259, #"Column" = 899, #"Percentage" = 96.7],
					        [#"Row" = 990, #"Column" = 145, #"Percentage" = 96.33],
					        [#"Row" = 184, #"Column" = 597, #"Percentage" = 43.28],
					        [#"Row" = 121, #"Column" = 304, #"Percentage" = 74.25],
					        [#"Row" = 314, #"Column" = 16, #"Percentage" = 93.18],
					        [#"Row" = 76, #"Column" = 19, #"Percentage" = 22.59],
					        [#"Row" = 964, #"Column" = 827, #"Percentage" = 3.1],
					        [#"Row" = 818, #"Column" = 248, #"Percentage" = 31.94],
					        [#"Row" = 493, #"Column" = 154, #"Percentage" = 63.48],
					        [#"Row" = 862, #"Column" = 91, #"Percentage" = 55.72],
					        [#"Row" = 965, #"Column" = 949, #"Percentage" = 55.65],
					        [#"Row" = 285, #"Column" = 575, #"Percentage" = 25.8],
					        [#"Row" = 792, #"Column" = 173, #"Percentage" = 55.36],
					        [#"Row" = 320, #"Column" = 392, #"Percentage" = 3.44],
					        [#"Row" = 14, #"Column" = 225, #"Percentage" = 98.34],
					        [#"Row" = 176, #"Column" = 391, #"Percentage" = 68.18],
					        [#"Row" = 273, #"Column" = 48, #"Percentage" = 68.47],
					        [#"Row" = 673, #"Column" = 526, #"Percentage" = 33.81],
					        [#"Row" = 655, #"Column" = 598, #"Percentage" = 45.84],
					        [#"Row" = 846, #"Column" = 654, #"Percentage" = 28.21],
					        [#"Row" = 247, #"Column" = 100, #"Percentage" = 50.73],
					        [#"Row" = 846, #"Column" = 280, #"Percentage" = 22.01],
					        [#"Row" = 694, #"Column" = 252, #"Percentage" = 85.34],
					        [#"Row" = 54, #"Column" = 191, #"Percentage" = 16.39],
					        [#"Row" = 934, #"Column" = 583, #"Percentage" = 24.73],
					        [#"Row" = 182, #"Column" = 269, #"Percentage" = 10.0],
					        [#"Row" = 453, #"Column" = 509, #"Percentage" = 62.2],
					        [#"Row" = 898, #"Column" = 20, #"Percentage" = 13.73],
					        [#"Row" = 401, #"Column" = 389, #"Percentage" = 15.81],
					        [#"Row" = 626, #"Column" = 350, #"Percentage" = 85.93],
					        [#"Row" = 821, #"Column" = 732, #"Percentage" = 17.03],
					        [#"Row" = 243, #"Column" = 727, #"Percentage" = 72.8],
					        [#"Row" = 173, #"Column" = 939, #"Percentage" = 79.6],
					        [#"Row" = 131, #"Column" = 202, #"Percentage" = 13.77],
					        [#"Row" = 622, #"Column" = 33, #"Percentage" = 35.45],
					        [#"Row" = 318, #"Column" = 594, #"Percentage" = 4.15],
					        [#"Row" = 436, #"Column" = 361, #"Percentage" = 50.52],
					        [#"Row" = 838, #"Column" = 441, #"Percentage" = 59.61],
					        [#"Row" = 393, #"Column" = 645, #"Percentage" = 75.26],
					        [#"Row" = 359, #"Column" = 50, #"Percentage" = 38.03],
					        [#"Row" = 652, #"Column" = 393, #"Percentage" = 80.44],
					        [#"Row" = 115, #"Column" = 479, #"Percentage" = 56.95],
					        [#"Row" = 859, #"Column" = 81, #"Percentage" = 47.52],
					        [#"Row" = 646, #"Column" = 822, #"Percentage" = 86.81],
					        [#"Row" = 967, #"Column" = 902, #"Percentage" = 27.51],
					        [#"Row" = 129, #"Column" = 403, #"Percentage" = 9.47],
					        [#"Row" = 644, #"Column" = 77, #"Percentage" = 67.48],
					        [#"Row" = 457, #"Column" = 328, #"Percentage" = 96.58],
					        [#"Row" = 918, #"Column" = 15, #"Percentage" = 53.36],
					        [#"Row" = 189, #"Column" = 484, #"Percentage" = 26.76],
					        [#"Row" = 489, #"Column" = 183, #"Percentage" = 53.66],
					        [#"Row" = 703, #"Column" = 29, #"Percentage" = 67.89],
					        [#"Row" = 948, #"Column" = 722, #"Percentage" = 70.87],
					        [#"Row" = 622, #"Column" = 168, #"Percentage" = 11.5],
					        [#"Row" = 335, #"Column" = 210, #"Percentage" = 64.63],
					        [#"Row" = 61, #"Column" = 4, #"Percentage" = 2.34],
					        [#"Row" = 427, #"Column" = 293, #"Percentage" = 39.96],
					        [#"Row" = 346, #"Column" = 273, #"Percentage" = 10.3],
					        [#"Row" = 311, #"Column" = 987, #"Percentage" = 80.73],
					        [#"Row" = 511, #"Column" = 873, #"Percentage" = 53.23],
					        [#"Row" = 277, #"Column" = 889, #"Percentage" = 24.64],
					        [#"Row" = 51, #"Column" = 365, #"Percentage" = 9.71],
					        [#"Row" = 463, #"Column" = 531, #"Percentage" = 69.66],
					        [#"Row" = 483, #"Column" = 79, #"Percentage" = 91.32],
					        [#"Row" = 805, #"Column" = 57, #"Percentage" = 13.26],
					        [#"Row" = 424, #"Column" = 451, #"Percentage" = 24.57],
					        [#"Row" = 119, #"Column" = 487, #"Percentage" = 69.2],
					        [#"Row" = 618, #"Column" = 177, #"Percentage" = 73.61],
					        [#"Row" = 971, #"Column" = 129, #"Percentage" = 24.28],
					        [#"Row" = 272, #"Column" = 1000, #"Percentage" = 35.64],
					        [#"Row" = 423, #"Column" = 771, #"Percentage" = 45.42],
					        [#"Row" = 891, #"Column" = 118, #"Percentage" = 44.85],
					        [#"Row" = 830, #"Column" = 565, #"Percentage" = 7.28],
					        [#"Row" = 520, #"Column" = 664, #"Percentage" = 67.15],
					        [#"Row" = 717, #"Column" = 419, #"Percentage" = 76.32],
					        [#"Row" = 524, #"Column" = 584, #"Percentage" = 79.78],
					        [#"Row" = 586, #"Column" = 534, #"Percentage" = 26.62],
					        [#"Row" = 663, #"Column" = 377, #"Percentage" = 66.62],
					        [#"Row" = 303, #"Column" = 282, #"Percentage" = 3.77],
					        [#"Row" = 398, #"Column" = 497, #"Percentage" = 68.97],
					        [#"Row" = 632, #"Column" = 951, #"Percentage" = 37.14],
					        [#"Row" = 754, #"Column" = 493, #"Percentage" = 96.46],
					        [#"Row" = 662, #"Column" = 436, #"Percentage" = 30.3],
					        [#"Row" = 239, #"Column" = 596, #"Percentage" = 95.03],
					        [#"Row" = 379, #"Column" = 132, #"Percentage" = 85.72],
					        [#"Row" = 389, #"Column" = 147, #"Percentage" = 19.09],
					        [#"Row" = 184, #"Column" = 394, #"Percentage" = 83.21],
					        [#"Row" = 806, #"Column" = 939, #"Percentage" = 80.69],
					        [#"Row" = 492, #"Column" = 348, #"Percentage" = 12.93],
					        [#"Row" = 275, #"Column" = 718, #"Percentage" = 44.25],
					        [#"Row" = 541, #"Column" = 547, #"Percentage" = 61.57],
					        [#"Row" = 552, #"Column" = 14, #"Percentage" = 43.94],
					        [#"Row" = 287, #"Column" = 514, #"Percentage" = 4.98],
					        [#"Row" = 545, #"Column" = 112, #"Percentage" = 50.96],
					        [#"Row" = 378, #"Column" = 275, #"Percentage" = 49.54],
					        [#"Row" = 544, #"Column" = 330, #"Percentage" = 74.54],
					        [#"Row" = 296, #"Column" = 629, #"Percentage" = 78.11],
					        [#"Row" = 764, #"Column" = 349, #"Percentage" = 43.43],
					        [#"Row" = 906, #"Column" = 272, #"Percentage" = 56.08],
					        [#"Row" = 474, #"Column" = 889, #"Percentage" = 20.38],
					        [#"Row" = 829, #"Column" = 973, #"Percentage" = 95.13],
					        [#"Row" = 622, #"Column" = 138, #"Percentage" = 75.05],
					        [#"Row" = 167, #"Column" = 196, #"Percentage" = 32.96],
					        [#"Row" = 688, #"Column" = 939, #"Percentage" = 12.45],
					        [#"Row" = 736, #"Column" = 364, #"Percentage" = 88.94],
					        [#"Row" = 748, #"Column" = 784, #"Percentage" = 3.84],
					        [#"Row" = 977, #"Column" = 194, #"Percentage" = 58.77],
					        [#"Row" = 847, #"Column" = 397, #"Percentage" = 53.81],
					        [#"Row" = 497, #"Column" = 583, #"Percentage" = 1.97],
					        [#"Row" = 683, #"Column" = 415, #"Percentage" = 71.36],
					        [#"Row" = 339, #"Column" = 938, #"Percentage" = 32.21],
					        [#"Row" = 300, #"Column" = 845, #"Percentage" = 78.01],
					        [#"Row" = 739, #"Column" = 197, #"Percentage" = 90.26],
					        [#"Row" = 512, #"Column" = 223, #"Percentage" = 70.23],
					        [#"Row" = 384, #"Column" = 32, #"Percentage" = 63.36],
					        [#"Row" = 590, #"Column" = 228, #"Percentage" = 50.15],
					        [#"Row" = 914, #"Column" = 392, #"Percentage" = 6.01],
					        [#"Row" = 376, #"Column" = 444, #"Percentage" = 74.5],
					        [#"Row" = 247, #"Column" = 793, #"Percentage" = 49.6],
					        [#"Row" = 320, #"Column" = 676, #"Percentage" = 34.83],
					        [#"Row" = 959, #"Column" = 722, #"Percentage" = 50.85],
					        [#"Row" = 359, #"Column" = 600, #"Percentage" = 23.47],
					        [#"Row" = 626, #"Column" = 240, #"Percentage" = 91.76],
					        [#"Row" = 69, #"Column" = 447, #"Percentage" = 45.4],
					        [#"Row" = 310, #"Column" = 70, #"Percentage" = 93.26],
					        [#"Row" = 766, #"Column" = 119, #"Percentage" = 47.17],
					        [#"Row" = 160, #"Column" = 916, #"Percentage" = 65.44],
					        [#"Row" = 237, #"Column" = 265, #"Percentage" = 47.73],
					        [#"Row" = 77, #"Column" = 476, #"Percentage" = 54.89],
					        [#"Row" = 449, #"Column" = 141, #"Percentage" = 40.94],
					        [#"Row" = 607, #"Column" = 142, #"Percentage" = 99.48],
					        [#"Row" = 915, #"Column" = 606, #"Percentage" = 14.1],
					        [#"Row" = 34, #"Column" = 398, #"Percentage" = 45.85],
					        [#"Row" = 71, #"Column" = 376, #"Percentage" = 5.06],
					        [#"Row" = 212, #"Column" = 394, #"Percentage" = 37.09],
					        [#"Row" = 67, #"Column" = 512, #"Percentage" = 92.35],
					        [#"Row" = 937, #"Column" = 188, #"Percentage" = 29.73],
					        [#"Row" = 779, #"Column" = 732, #"Percentage" = 92.63],
					        [#"Row" = 489, #"Column" = 475, #"Percentage" = 45.51],
					        [#"Row" = 553, #"Column" = 473, #"Percentage" = 98.05],
					        [#"Row" = 305, #"Column" = 761, #"Percentage" = 77.16],
					        [#"Row" = 158, #"Column" = 334, #"Percentage" = 90.56],
					        [#"Row" = 417, #"Column" = 612, #"Percentage" = 2.21],
					        [#"Row" = 845, #"Column" = 268, #"Percentage" = 50.78],
					        [#"Row" = 766, #"Column" = 705, #"Percentage" = 89.31],
					        [#"Row" = 800, #"Column" = 980, #"Percentage" = 63.01],
					        [#"Row" = 435, #"Column" = 224, #"Percentage" = 18.51],
					        [#"Row" = 596, #"Column" = 113, #"Percentage" = 15.1],
					        [#"Row" = 314, #"Column" = 372, #"Percentage" = 69.91],
					        [#"Row" = 563, #"Column" = 389, #"Percentage" = 73.4],
					        [#"Row" = 762, #"Column" = 153, #"Percentage" = 42.03],
					        [#"Row" = 719, #"Column" = 748, #"Percentage" = 15.9],
					        [#"Row" = 32, #"Column" = 190, #"Percentage" = 99.53],
					        [#"Row" = 421, #"Column" = 58, #"Percentage" = 0.38],
					        [#"Row" = 87, #"Column" = 6, #"Percentage" = 6.28],
					        [#"Row" = 557, #"Column" = 119, #"Percentage" = 50.92],
					        [#"Row" = 364, #"Column" = 959, #"Percentage" = 99.04],
					        [#"Row" = 647, #"Column" = 490, #"Percentage" = 76.5],
					        [#"Row" = 81, #"Column" = 666, #"Percentage" = 41.63],
					        [#"Row" = 704, #"Column" = 430, #"Percentage" = 99.11],
					        [#"Row" = 215, #"Column" = 131, #"Percentage" = 87.45],
					        [#"Row" = 86, #"Column" = 456, #"Percentage" = 48.27],
					        [#"Row" = 710, #"Column" = 404, #"Percentage" = 78.19],
					        [#"Row" = 168, #"Column" = 762, #"Percentage" = 84.89],
					        [#"Row" = 291, #"Column" = 427, #"Percentage" = 12.94],
					        [#"Row" = 659, #"Column" = 346, #"Percentage" = 66.79],
					        [#"Row" = 54, #"Column" = 670, #"Percentage" = 2.02],
					        [#"Row" = 360, #"Column" = 822, #"Percentage" = 14.58],
					        [#"Row" = 28, #"Column" = 283, #"Percentage" = 22.96],
					        [#"Row" = 517, #"Column" = 966, #"Percentage" = 33.42],
					        [#"Row" = 927, #"Column" = 839, #"Percentage" = 50.04],
					        [#"Row" = 108, #"Column" = 757, #"Percentage" = 81.13],
					        [#"Row" = 575, #"Column" = 313, #"Percentage" = 12.31],
					        [#"Row" = 630, #"Column" = 9, #"Percentage" = 50.26],
					        [#"Row" = 818, #"Column" = 958, #"Percentage" = 64.42],
					        [#"Row" = 323, #"Column" = 911, #"Percentage" = 79.79],
					        [#"Row" = 275, #"Column" = 211, #"Percentage" = 80.23],
					        [#"Row" = 668, #"Column" = 600, #"Percentage" = 0.43],
					        [#"Row" = 466, #"Column" = 946, #"Percentage" = 9.3],
					        [#"Row" = 594, #"Column" = 418, #"Percentage" = 17.01],
					        [#"Row" = 659, #"Column" = 797, #"Percentage" = 8.34],
					        [#"Row" = 935, #"Column" = 292, #"Percentage" = 19.66],
					        [#"Row" = 54, #"Column" = 470, #"Percentage" = 92.32],
					        [#"Row" = 486, #"Column" = 941, #"Percentage" = 77.27],
					        [#"Row" = 476, #"Column" = 532, #"Percentage" = 45.74],
					        [#"Row" = 6, #"Column" = 89, #"Percentage" = 49.35],
					        [#"Row" = 545, #"Column" = 607, #"Percentage" = 18.85],
					        [#"Row" = 35, #"Column" = 167, #"Percentage" = 23.19],
					        [#"Row" = 475, #"Column" = 609, #"Percentage" = 29.28],
					        [#"Row" = 517, #"Column" = 979, #"Percentage" = 80.75],
					        [#"Row" = 559, #"Column" = 742, #"Percentage" = 53.45],
					        [#"Row" = 48, #"Column" = 876, #"Percentage" = 14.25],
					        [#"Row" = 223, #"Column" = 113, #"Percentage" = 55.77],
					        [#"Row" = 882, #"Column" = 679, #"Percentage" = 94.03],
					        [#"Row" = 475, #"Column" = 61, #"Percentage" = 96.92],
					        [#"Row" = 552, #"Column" = 998, #"Percentage" = 75.59],
					        [#"Row" = 160, #"Column" = 885, #"Percentage" = 57.24],
					        [#"Row" = 124, #"Column" = 561, #"Percentage" = 1.39],
					        [#"Row" = 607, #"Column" = 437, #"Percentage" = 9.94],
					        [#"Row" = 262, #"Column" = 520, #"Percentage" = 48.53],
					        [#"Row" = 129, #"Column" = 442, #"Percentage" = 93.27],
					        [#"Row" = 721, #"Column" = 424, #"Percentage" = 93.67],
					        [#"Row" = 202, #"Column" = 920, #"Percentage" = 74.82],
					        [#"Row" = 197, #"Column" = 513, #"Percentage" = 21.92],
					        [#"Row" = 112, #"Column" = 799, #"Percentage" = 39.35],
					        [#"Row" = 661, #"Column" = 936, #"Percentage" = 49.14],
					        [#"Row" = 245, #"Column" = 69, #"Percentage" = 95.34],
					        [#"Row" = 641, #"Column" = 605, #"Percentage" = 60.91],
					        [#"Row" = 642, #"Column" = 383, #"Percentage" = 85.96],
					        [#"Row" = 198, #"Column" = 281, #"Percentage" = 88.21],
					        [#"Row" = 777, #"Column" = 942, #"Percentage" = 47.18],
					        [#"Row" = 768, #"Column" = 800, #"Percentage" = 71.33],
					        [#"Row" = 315, #"Column" = 894, #"Percentage" = 19.53],
					        [#"Row" = 736, #"Column" = 461, #"Percentage" = 16.7],
					        [#"Row" = 133, #"Column" = 673, #"Percentage" = 54.4],
					        [#"Row" = 358, #"Column" = 152, #"Percentage" = 38.36],
					        [#"Row" = 700, #"Column" = 603, #"Percentage" = 10.65],
					        [#"Row" = 906, #"Column" = 690, #"Percentage" = 59.36],
					        [#"Row" = 263, #"Column" = 902, #"Percentage" = 66.04],
					        [#"Row" = 241, #"Column" = 199, #"Percentage" = 75.35],
					        [#"Row" = 62, #"Column" = 606, #"Percentage" = 93.07],
					        [#"Row" = 616, #"Column" = 648, #"Percentage" = 96.6],
					        [#"Row" = 115, #"Column" = 221, #"Percentage" = 65.61],
					        [#"Row" = 84, #"Column" = 314, #"Percentage" = 35.17],
					        [#"Row" = 479, #"Column" = 968, #"Percentage" = 43.82],
					        [#"Row" = 429, #"Column" = 377, #"Percentage" = 22.35],
					        [#"Row" = 845, #"Column" = 136, #"Percentage" = 8.76],
					        [#"Row" = 939, #"Column" = 814, #"Percentage" = 41.17],
					        [#"Row" = 411, #"Column" = 566, #"Percentage" = 65.47],
					        [#"Row" = 517, #"Column" = 51, #"Percentage" = 56.21],
					        [#"Row" = 499, #"Column" = 907, #"Percentage" = 48.98],
					        [#"Row" = 915, #"Column" = 414, #"Percentage" = 15.74],
					        [#"Row" = 739, #"Column" = 700, #"Percentage" = 12.55],
					        [#"Row" = 315, #"Column" = 104, #"Percentage" = 23.02],
					        [#"Row" = 130, #"Column" = 879, #"Percentage" = 44.72],
					        [#"Row" = 7, #"Column" = 865, #"Percentage" = 66.34],
					        [#"Row" = 583, #"Column" = 190, #"Percentage" = 39.9],
					        [#"Row" = 315, #"Column" = 309, #"Percentage" = 81.93],
					        [#"Row" = 817, #"Column" = 498, #"Percentage" = 41.0],
					        [#"Row" = 742, #"Column" = 350, #"Percentage" = 66.59],
					        [#"Row" = 683, #"Column" = 391, #"Percentage" = 58.09],
					        [#"Row" = 531, #"Column" = 442, #"Percentage" = 26.6],
					        [#"Row" = 900, #"Column" = 276, #"Percentage" = 90.29],
					        [#"Row" = 404, #"Column" = 801, #"Percentage" = 85.4],
					        [#"Row" = 458, #"Column" = 666, #"Percentage" = 38.73],
					        [#"Row" = 36, #"Column" = 206, #"Percentage" = 59.75],
					        [#"Row" = 880, #"Column" = 280, #"Percentage" = 59.35],
					        [#"Row" = 131, #"Column" = 501, #"Percentage" = 90.81],
					        [#"Row" = 369, #"Column" = 439, #"Percentage" = 28.06],
					        [#"Row" = 346, #"Column" = 349, #"Percentage" = 21.94],
					        [#"Row" = 81, #"Column" = 61, #"Percentage" = 28.94],
					        [#"Row" = 493, #"Column" = 636, #"Percentage" = 98.37],
					        [#"Row" = 31, #"Column" = 533, #"Percentage" = 99.78],
					        [#"Row" = 353, #"Column" = 496, #"Percentage" = 57.43],
					        [#"Row" = 522, #"Column" = 272, #"Percentage" = 51.57],
					        [#"Row" = 424, #"Column" = 231, #"Percentage" = 47.94],
					        [#"Row" = 244, #"Column" = 703, #"Percentage" = 78.39],
					        [#"Row" = 978, #"Column" = 897, #"Percentage" = 18.78],
					        [#"Row" = 469, #"Column" = 1000, #"Percentage" = 9.34],
					        [#"Row" = 170, #"Column" = 591, #"Percentage" = 85.84],
					        [#"Row" = 30, #"Column" = 975, #"Percentage" = 86.28],
					        [#"Row" = 771, #"Column" = 441, #"Percentage" = 4.16],
					        [#"Row" = 709, #"Column" = 727, #"Percentage" = 6.5],
					        [#"Row" = 888, #"Column" = 819, #"Percentage" = 43.79],
					        [#"Row" = 879, #"Column" = 982, #"Percentage" = 83.74],
					        [#"Row" = 834, #"Column" = 927, #"Percentage" = 68.36],
					        [#"Row" = 261, #"Column" = 289, #"Percentage" = 20.16],
					        [#"Row" = 822, #"Column" = 676, #"Percentage" = 37.11],
					        [#"Row" = 772, #"Column" = 736, #"Percentage" = 88.41],
					        [#"Row" = 876, #"Column" = 654, #"Percentage" = 55.21],
					        [#"Row" = 379, #"Column" = 927, #"Percentage" = 22.95],
					        [#"Row" = 756, #"Column" = 962, #"Percentage" = 74.48],
					        [#"Row" = 877, #"Column" = 596, #"Percentage" = 84.27],
					        [#"Row" = 11, #"Column" = 900, #"Percentage" = 82.78],
					        [#"Row" = 5, #"Column" = 499, #"Percentage" = 87.67],
					        [#"Row" = 608, #"Column" = 203, #"Percentage" = 76.59],
					        [#"Row" = 683, #"Column" = 459, #"Percentage" = 35.26],
					        [#"Row" = 957, #"Column" = 869, #"Percentage" = 22.1],
					        [#"Row" = 390, #"Column" = 349, #"Percentage" = 61.2],
					        [#"Row" = 185, #"Column" = 840, #"Percentage" = 97.51],
					        [#"Row" = 640, #"Column" = 959, #"Percentage" = 23.42],
					        [#"Row" = 305, #"Column" = 606, #"Percentage" = 96.8],
					        [#"Row" = 802, #"Column" = 218, #"Percentage" = 66.65],
					        [#"Row" = 536, #"Column" = 87, #"Percentage" = 38.46],
					        [#"Row" = 281, #"Column" = 705, #"Percentage" = 68.01],
					        [#"Row" = 58, #"Column" = 543, #"Percentage" = 12.21],
					        [#"Row" = 732, #"Column" = 685, #"Percentage" = 93.66],
					        [#"Row" = 856, #"Column" = 887, #"Percentage" = 81.97],
					        [#"Row" = 566, #"Column" = 422, #"Percentage" = 83.65],
					        [#"Row" = 114, #"Column" = 417, #"Percentage" = 4.33],
					        [#"Row" = 358, #"Column" = 117, #"Percentage" = 20.57],
					        [#"Row" = 509, #"Column" = 576, #"Percentage" = 21.86],
					        [#"Row" = 436, #"Column" = 722, #"Percentage" = 60.35],
					        [#"Row" = 288, #"Column" = 520, #"Percentage" = 9.8],
					        [#"Row" = 247, #"Column" = 483, #"Percentage" = 82.56],
					        [#"Row" = 434, #"Column" = 120, #"Percentage" = 20.07],
					        [#"Row" = 640, #"Column" = 824, #"Percentage" = 20.05],
					        [#"Row" = 616, #"Column" = 587, #"Percentage" = 60.75],
					        [#"Row" = 554, #"Column" = 733, #"Percentage" = 70.72],
					        [#"Row" = 895, #"Column" = 397, #"Percentage" = 87.35],
					        [#"Row" = 305, #"Column" = 841, #"Percentage" = 37.4],
					        [#"Row" = 590, #"Column" = 460, #"Percentage" = 97.5],
					        [#"Row" = 654, #"Column" = 663, #"Percentage" = 67.95],
					        [#"Row" = 863, #"Column" = 544, #"Percentage" = 5.35],
					        [#"Row" = 893, #"Column" = 743, #"Percentage" = 82.64],
					        [#"Row" = 975, #"Column" = 412, #"Percentage" = 86.3],
					        [#"Row" = 625, #"Column" = 339, #"Percentage" = 80.43],
					        [#"Row" = 543, #"Column" = 278, #"Percentage" = 17.39],
					        [#"Row" = 312, #"Column" = 910, #"Percentage" = 9.29],
					        [#"Row" = 517, #"Column" = 465, #"Percentage" = 6.66],
					        [#"Row" = 716, #"Column" = 379, #"Percentage" = 15.58],
					        [#"Row" = 572, #"Column" = 976, #"Percentage" = 84.37],
					        [#"Row" = 517, #"Column" = 105, #"Percentage" = 33.2],
					        [#"Row" = 894, #"Column" = 108, #"Percentage" = 45.36],
					        [#"Row" = 711, #"Column" = 792, #"Percentage" = 45.01],
					        [#"Row" = 826, #"Column" = 588, #"Percentage" = 39.15],
					        [#"Row" = 246, #"Column" = 346, #"Percentage" = 45.58]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Row", Int64.Type},
					        {"Column", Int64.Type},
					        {"Percentage", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table