table 'Profit Bin Size'
	lineageTag: 35c73993-cd13-47f8-a1c9-0db70352623c

	measure 'Profit Bin Size Value' = SELECTEDVALUE('Profit Bin Size'[Profit Bin Size], 50)
		lineageTag: 85da38b9-a55c-4808-8c7e-a35245e47fe3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Profit Bin Size'
		dataType: double
		formatString: 0
		lineageTag: bd2beda3-97a3-443e-bd78-39862ae2233d
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Profit Bin Size' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_Id = 8314902a20c6433e952e2cd00803cde6

