table 'Top Customers'
	lineageTag: 8ac1c2bb-b872-43d4-8c1d-39c6be1c540e

	measure 'Top Customers Value' = SELECTEDVALUE('Top Customers'[Top Customers], 5)
		lineageTag: 978fde3c-bd2b-4ac8-a4ca-95e9d8e2848a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Top Customers'
		dataType: double
		formatString: 0
		lineageTag: 6b147727-177e-4710-9e96-f8f5ba499a08
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Top Customers' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_Id = 420e4e4a9c304a5b941731f2f1f3350f

