table customer_support_data_State
	lineageTag: fe1432a8-1197-4e10-a37b-a1305c6df0f5

	column State
		dataType: string
		lineageTag: a271d459-532a-40fe-af63-e56b202c0e3a
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Code
		dataType: string
		lineageTag: af4299b2-0cf7-4341-8cd5-bcea54481306
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	partition customer_support_data_State = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"State" = "Sample_State_1", #"Code" = "Sample_Code_1"],
					        [#"State" = "Sample_State_2", #"Code" = "Sample_Code_2"],
					        [#"State" = "Sample_State_3", #"Code" = "Sample_Code_3"],
					        [#"State" = "Sample_State_4", #"Code" = "Sample_Code_4"],
					        [#"State" = "Sample_State_5", #"Code" = "Sample_Code_5"],
					        [#"State" = "Sample_State_6", #"Code" = "Sample_Code_6"],
					        [#"State" = "Sample_State_7", #"Code" = "Sample_Code_7"],
					        [#"State" = "Sample_State_8", #"Code" = "Sample_Code_8"],
					        [#"State" = "Sample_State_9", #"Code" = "Sample_Code_9"],
					        [#"State" = "Sample_State_10", #"Code" = "Sample_Code_10"],
					        [#"State" = "Sample_State_11", #"Code" = "Sample_Code_11"],
					        [#"State" = "Sample_State_12", #"Code" = "Sample_Code_12"],
					        [#"State" = "Sample_State_13", #"Code" = "Sample_Code_13"],
					        [#"State" = "Sample_State_14", #"Code" = "Sample_Code_14"],
					        [#"State" = "Sample_State_15", #"Code" = "Sample_Code_15"],
					        [#"State" = "Sample_State_16", #"Code" = "Sample_Code_16"],
					        [#"State" = "Sample_State_17", #"Code" = "Sample_Code_17"],
					        [#"State" = "Sample_State_18", #"Code" = "Sample_Code_18"],
					        [#"State" = "Sample_State_19", #"Code" = "Sample_Code_19"],
					        [#"State" = "Sample_State_20", #"Code" = "Sample_Code_20"],
					        [#"State" = "Sample_State_21", #"Code" = "Sample_Code_21"],
					        [#"State" = "Sample_State_22", #"Code" = "Sample_Code_22"],
					        [#"State" = "Sample_State_23", #"Code" = "Sample_Code_23"],
					        [#"State" = "Sample_State_24", #"Code" = "Sample_Code_24"],
					        [#"State" = "Sample_State_25", #"Code" = "Sample_Code_25"],
					        [#"State" = "Sample_State_26", #"Code" = "Sample_Code_26"],
					        [#"State" = "Sample_State_27", #"Code" = "Sample_Code_27"],
					        [#"State" = "Sample_State_28", #"Code" = "Sample_Code_28"],
					        [#"State" = "Sample_State_29", #"Code" = "Sample_Code_29"],
					        [#"State" = "Sample_State_30", #"Code" = "Sample_Code_30"],
					        [#"State" = "Sample_State_31", #"Code" = "Sample_Code_31"],
					        [#"State" = "Sample_State_32", #"Code" = "Sample_Code_32"],
					        [#"State" = "Sample_State_33", #"Code" = "Sample_Code_33"],
					        [#"State" = "Sample_State_34", #"Code" = "Sample_Code_34"],
					        [#"State" = "Sample_State_35", #"Code" = "Sample_Code_35"],
					        [#"State" = "Sample_State_36", #"Code" = "Sample_Code_36"],
					        [#"State" = "Sample_State_37", #"Code" = "Sample_Code_37"],
					        [#"State" = "Sample_State_38", #"Code" = "Sample_Code_38"],
					        [#"State" = "Sample_State_39", #"Code" = "Sample_Code_39"],
					        [#"State" = "Sample_State_40", #"Code" = "Sample_Code_40"],
					        [#"State" = "Sample_State_41", #"Code" = "Sample_Code_41"],
					        [#"State" = "Sample_State_42", #"Code" = "Sample_Code_42"],
					        [#"State" = "Sample_State_43", #"Code" = "Sample_Code_43"],
					        [#"State" = "Sample_State_44", #"Code" = "Sample_Code_44"],
					        [#"State" = "Sample_State_45", #"Code" = "Sample_Code_45"],
					        [#"State" = "Sample_State_46", #"Code" = "Sample_Code_46"],
					        [#"State" = "Sample_State_47", #"Code" = "Sample_Code_47"],
					        [#"State" = "Sample_State_48", #"Code" = "Sample_Code_48"],
					        [#"State" = "Sample_State_49", #"Code" = "Sample_Code_49"],
					        [#"State" = "Sample_State_50", #"Code" = "Sample_Code_50"],
					        [#"State" = "Sample_State_51", #"Code" = "Sample_Code_51"],
					        [#"State" = "Sample_State_52", #"Code" = "Sample_Code_52"],
					        [#"State" = "Sample_State_53", #"Code" = "Sample_Code_53"],
					        [#"State" = "Sample_State_54", #"Code" = "Sample_Code_54"],
					        [#"State" = "Sample_State_55", #"Code" = "Sample_Code_55"],
					        [#"State" = "Sample_State_56", #"Code" = "Sample_Code_56"],
					        [#"State" = "Sample_State_57", #"Code" = "Sample_Code_57"],
					        [#"State" = "Sample_State_58", #"Code" = "Sample_Code_58"],
					        [#"State" = "Sample_State_59", #"Code" = "Sample_Code_59"],
					        [#"State" = "Sample_State_60", #"Code" = "Sample_Code_60"],
					        [#"State" = "Sample_State_61", #"Code" = "Sample_Code_61"],
					        [#"State" = "Sample_State_62", #"Code" = "Sample_Code_62"],
					        [#"State" = "Sample_State_63", #"Code" = "Sample_Code_63"],
					        [#"State" = "Sample_State_64", #"Code" = "Sample_Code_64"],
					        [#"State" = "Sample_State_65", #"Code" = "Sample_Code_65"],
					        [#"State" = "Sample_State_66", #"Code" = "Sample_Code_66"],
					        [#"State" = "Sample_State_67", #"Code" = "Sample_Code_67"],
					        [#"State" = "Sample_State_68", #"Code" = "Sample_Code_68"],
					        [#"State" = "Sample_State_69", #"Code" = "Sample_Code_69"],
					        [#"State" = "Sample_State_70", #"Code" = "Sample_Code_70"],
					        [#"State" = "Sample_State_71", #"Code" = "Sample_Code_71"],
					        [#"State" = "Sample_State_72", #"Code" = "Sample_Code_72"],
					        [#"State" = "Sample_State_73", #"Code" = "Sample_Code_73"],
					        [#"State" = "Sample_State_74", #"Code" = "Sample_Code_74"],
					        [#"State" = "Sample_State_75", #"Code" = "Sample_Code_75"],
					        [#"State" = "Sample_State_76", #"Code" = "Sample_Code_76"],
					        [#"State" = "Sample_State_77", #"Code" = "Sample_Code_77"],
					        [#"State" = "Sample_State_78", #"Code" = "Sample_Code_78"],
					        [#"State" = "Sample_State_79", #"Code" = "Sample_Code_79"],
					        [#"State" = "Sample_State_80", #"Code" = "Sample_Code_80"],
					        [#"State" = "Sample_State_81", #"Code" = "Sample_Code_81"],
					        [#"State" = "Sample_State_82", #"Code" = "Sample_Code_82"],
					        [#"State" = "Sample_State_83", #"Code" = "Sample_Code_83"],
					        [#"State" = "Sample_State_84", #"Code" = "Sample_Code_84"],
					        [#"State" = "Sample_State_85", #"Code" = "Sample_Code_85"],
					        [#"State" = "Sample_State_86", #"Code" = "Sample_Code_86"],
					        [#"State" = "Sample_State_87", #"Code" = "Sample_Code_87"],
					        [#"State" = "Sample_State_88", #"Code" = "Sample_Code_88"],
					        [#"State" = "Sample_State_89", #"Code" = "Sample_Code_89"],
					        [#"State" = "Sample_State_90", #"Code" = "Sample_Code_90"],
					        [#"State" = "Sample_State_91", #"Code" = "Sample_Code_91"],
					        [#"State" = "Sample_State_92", #"Code" = "Sample_Code_92"],
					        [#"State" = "Sample_State_93", #"Code" = "Sample_Code_93"],
					        [#"State" = "Sample_State_94", #"Code" = "Sample_Code_94"],
					        [#"State" = "Sample_State_95", #"Code" = "Sample_Code_95"],
					        [#"State" = "Sample_State_96", #"Code" = "Sample_Code_96"],
					        [#"State" = "Sample_State_97", #"Code" = "Sample_Code_97"],
					        [#"State" = "Sample_State_98", #"Code" = "Sample_Code_98"],
					        [#"State" = "Sample_State_99", #"Code" = "Sample_Code_99"],
					        [#"State" = "Sample_State_100", #"Code" = "Sample_Code_100"],
					        [#"State" = "Sample_State_101", #"Code" = "Sample_Code_101"],
					        [#"State" = "Sample_State_102", #"Code" = "Sample_Code_102"],
					        [#"State" = "Sample_State_103", #"Code" = "Sample_Code_103"],
					        [#"State" = "Sample_State_104", #"Code" = "Sample_Code_104"],
					        [#"State" = "Sample_State_105", #"Code" = "Sample_Code_105"],
					        [#"State" = "Sample_State_106", #"Code" = "Sample_Code_106"],
					        [#"State" = "Sample_State_107", #"Code" = "Sample_Code_107"],
					        [#"State" = "Sample_State_108", #"Code" = "Sample_Code_108"],
					        [#"State" = "Sample_State_109", #"Code" = "Sample_Code_109"],
					        [#"State" = "Sample_State_110", #"Code" = "Sample_Code_110"],
					        [#"State" = "Sample_State_111", #"Code" = "Sample_Code_111"],
					        [#"State" = "Sample_State_112", #"Code" = "Sample_Code_112"],
					        [#"State" = "Sample_State_113", #"Code" = "Sample_Code_113"],
					        [#"State" = "Sample_State_114", #"Code" = "Sample_Code_114"],
					        [#"State" = "Sample_State_115", #"Code" = "Sample_Code_115"],
					        [#"State" = "Sample_State_116", #"Code" = "Sample_Code_116"],
					        [#"State" = "Sample_State_117", #"Code" = "Sample_Code_117"],
					        [#"State" = "Sample_State_118", #"Code" = "Sample_Code_118"],
					        [#"State" = "Sample_State_119", #"Code" = "Sample_Code_119"],
					        [#"State" = "Sample_State_120", #"Code" = "Sample_Code_120"],
					        [#"State" = "Sample_State_121", #"Code" = "Sample_Code_121"],
					        [#"State" = "Sample_State_122", #"Code" = "Sample_Code_122"],
					        [#"State" = "Sample_State_123", #"Code" = "Sample_Code_123"],
					        [#"State" = "Sample_State_124", #"Code" = "Sample_Code_124"],
					        [#"State" = "Sample_State_125", #"Code" = "Sample_Code_125"],
					        [#"State" = "Sample_State_126", #"Code" = "Sample_Code_126"],
					        [#"State" = "Sample_State_127", #"Code" = "Sample_Code_127"],
					        [#"State" = "Sample_State_128", #"Code" = "Sample_Code_128"],
					        [#"State" = "Sample_State_129", #"Code" = "Sample_Code_129"],
					        [#"State" = "Sample_State_130", #"Code" = "Sample_Code_130"],
					        [#"State" = "Sample_State_131", #"Code" = "Sample_Code_131"],
					        [#"State" = "Sample_State_132", #"Code" = "Sample_Code_132"],
					        [#"State" = "Sample_State_133", #"Code" = "Sample_Code_133"],
					        [#"State" = "Sample_State_134", #"Code" = "Sample_Code_134"],
					        [#"State" = "Sample_State_135", #"Code" = "Sample_Code_135"],
					        [#"State" = "Sample_State_136", #"Code" = "Sample_Code_136"],
					        [#"State" = "Sample_State_137", #"Code" = "Sample_Code_137"],
					        [#"State" = "Sample_State_138", #"Code" = "Sample_Code_138"],
					        [#"State" = "Sample_State_139", #"Code" = "Sample_Code_139"],
					        [#"State" = "Sample_State_140", #"Code" = "Sample_Code_140"],
					        [#"State" = "Sample_State_141", #"Code" = "Sample_Code_141"],
					        [#"State" = "Sample_State_142", #"Code" = "Sample_Code_142"],
					        [#"State" = "Sample_State_143", #"Code" = "Sample_Code_143"],
					        [#"State" = "Sample_State_144", #"Code" = "Sample_Code_144"],
					        [#"State" = "Sample_State_145", #"Code" = "Sample_Code_145"],
					        [#"State" = "Sample_State_146", #"Code" = "Sample_Code_146"],
					        [#"State" = "Sample_State_147", #"Code" = "Sample_Code_147"],
					        [#"State" = "Sample_State_148", #"Code" = "Sample_Code_148"],
					        [#"State" = "Sample_State_149", #"Code" = "Sample_Code_149"],
					        [#"State" = "Sample_State_150", #"Code" = "Sample_Code_150"],
					        [#"State" = "Sample_State_151", #"Code" = "Sample_Code_151"],
					        [#"State" = "Sample_State_152", #"Code" = "Sample_Code_152"],
					        [#"State" = "Sample_State_153", #"Code" = "Sample_Code_153"],
					        [#"State" = "Sample_State_154", #"Code" = "Sample_Code_154"],
					        [#"State" = "Sample_State_155", #"Code" = "Sample_Code_155"],
					        [#"State" = "Sample_State_156", #"Code" = "Sample_Code_156"],
					        [#"State" = "Sample_State_157", #"Code" = "Sample_Code_157"],
					        [#"State" = "Sample_State_158", #"Code" = "Sample_Code_158"],
					        [#"State" = "Sample_State_159", #"Code" = "Sample_Code_159"],
					        [#"State" = "Sample_State_160", #"Code" = "Sample_Code_160"],
					        [#"State" = "Sample_State_161", #"Code" = "Sample_Code_161"],
					        [#"State" = "Sample_State_162", #"Code" = "Sample_Code_162"],
					        [#"State" = "Sample_State_163", #"Code" = "Sample_Code_163"],
					        [#"State" = "Sample_State_164", #"Code" = "Sample_Code_164"],
					        [#"State" = "Sample_State_165", #"Code" = "Sample_Code_165"],
					        [#"State" = "Sample_State_166", #"Code" = "Sample_Code_166"],
					        [#"State" = "Sample_State_167", #"Code" = "Sample_Code_167"],
					        [#"State" = "Sample_State_168", #"Code" = "Sample_Code_168"],
					        [#"State" = "Sample_State_169", #"Code" = "Sample_Code_169"],
					        [#"State" = "Sample_State_170", #"Code" = "Sample_Code_170"],
					        [#"State" = "Sample_State_171", #"Code" = "Sample_Code_171"],
					        [#"State" = "Sample_State_172", #"Code" = "Sample_Code_172"],
					        [#"State" = "Sample_State_173", #"Code" = "Sample_Code_173"],
					        [#"State" = "Sample_State_174", #"Code" = "Sample_Code_174"],
					        [#"State" = "Sample_State_175", #"Code" = "Sample_Code_175"],
					        [#"State" = "Sample_State_176", #"Code" = "Sample_Code_176"],
					        [#"State" = "Sample_State_177", #"Code" = "Sample_Code_177"],
					        [#"State" = "Sample_State_178", #"Code" = "Sample_Code_178"],
					        [#"State" = "Sample_State_179", #"Code" = "Sample_Code_179"],
					        [#"State" = "Sample_State_180", #"Code" = "Sample_Code_180"],
					        [#"State" = "Sample_State_181", #"Code" = "Sample_Code_181"],
					        [#"State" = "Sample_State_182", #"Code" = "Sample_Code_182"],
					        [#"State" = "Sample_State_183", #"Code" = "Sample_Code_183"],
					        [#"State" = "Sample_State_184", #"Code" = "Sample_Code_184"],
					        [#"State" = "Sample_State_185", #"Code" = "Sample_Code_185"],
					        [#"State" = "Sample_State_186", #"Code" = "Sample_Code_186"],
					        [#"State" = "Sample_State_187", #"Code" = "Sample_Code_187"],
					        [#"State" = "Sample_State_188", #"Code" = "Sample_Code_188"],
					        [#"State" = "Sample_State_189", #"Code" = "Sample_Code_189"],
					        [#"State" = "Sample_State_190", #"Code" = "Sample_Code_190"],
					        [#"State" = "Sample_State_191", #"Code" = "Sample_Code_191"],
					        [#"State" = "Sample_State_192", #"Code" = "Sample_Code_192"],
					        [#"State" = "Sample_State_193", #"Code" = "Sample_Code_193"],
					        [#"State" = "Sample_State_194", #"Code" = "Sample_Code_194"],
					        [#"State" = "Sample_State_195", #"Code" = "Sample_Code_195"],
					        [#"State" = "Sample_State_196", #"Code" = "Sample_Code_196"],
					        [#"State" = "Sample_State_197", #"Code" = "Sample_Code_197"],
					        [#"State" = "Sample_State_198", #"Code" = "Sample_Code_198"],
					        [#"State" = "Sample_State_199", #"Code" = "Sample_Code_199"],
					        [#"State" = "Sample_State_200", #"Code" = "Sample_Code_200"],
					        [#"State" = "Sample_State_201", #"Code" = "Sample_Code_201"],
					        [#"State" = "Sample_State_202", #"Code" = "Sample_Code_202"],
					        [#"State" = "Sample_State_203", #"Code" = "Sample_Code_203"],
					        [#"State" = "Sample_State_204", #"Code" = "Sample_Code_204"],
					        [#"State" = "Sample_State_205", #"Code" = "Sample_Code_205"],
					        [#"State" = "Sample_State_206", #"Code" = "Sample_Code_206"],
					        [#"State" = "Sample_State_207", #"Code" = "Sample_Code_207"],
					        [#"State" = "Sample_State_208", #"Code" = "Sample_Code_208"],
					        [#"State" = "Sample_State_209", #"Code" = "Sample_Code_209"],
					        [#"State" = "Sample_State_210", #"Code" = "Sample_Code_210"],
					        [#"State" = "Sample_State_211", #"Code" = "Sample_Code_211"],
					        [#"State" = "Sample_State_212", #"Code" = "Sample_Code_212"],
					        [#"State" = "Sample_State_213", #"Code" = "Sample_Code_213"],
					        [#"State" = "Sample_State_214", #"Code" = "Sample_Code_214"],
					        [#"State" = "Sample_State_215", #"Code" = "Sample_Code_215"],
					        [#"State" = "Sample_State_216", #"Code" = "Sample_Code_216"],
					        [#"State" = "Sample_State_217", #"Code" = "Sample_Code_217"],
					        [#"State" = "Sample_State_218", #"Code" = "Sample_Code_218"],
					        [#"State" = "Sample_State_219", #"Code" = "Sample_Code_219"],
					        [#"State" = "Sample_State_220", #"Code" = "Sample_Code_220"],
					        [#"State" = "Sample_State_221", #"Code" = "Sample_Code_221"],
					        [#"State" = "Sample_State_222", #"Code" = "Sample_Code_222"],
					        [#"State" = "Sample_State_223", #"Code" = "Sample_Code_223"],
					        [#"State" = "Sample_State_224", #"Code" = "Sample_Code_224"],
					        [#"State" = "Sample_State_225", #"Code" = "Sample_Code_225"],
					        [#"State" = "Sample_State_226", #"Code" = "Sample_Code_226"],
					        [#"State" = "Sample_State_227", #"Code" = "Sample_Code_227"],
					        [#"State" = "Sample_State_228", #"Code" = "Sample_Code_228"],
					        [#"State" = "Sample_State_229", #"Code" = "Sample_Code_229"],
					        [#"State" = "Sample_State_230", #"Code" = "Sample_Code_230"],
					        [#"State" = "Sample_State_231", #"Code" = "Sample_Code_231"],
					        [#"State" = "Sample_State_232", #"Code" = "Sample_Code_232"],
					        [#"State" = "Sample_State_233", #"Code" = "Sample_Code_233"],
					        [#"State" = "Sample_State_234", #"Code" = "Sample_Code_234"],
					        [#"State" = "Sample_State_235", #"Code" = "Sample_Code_235"],
					        [#"State" = "Sample_State_236", #"Code" = "Sample_Code_236"],
					        [#"State" = "Sample_State_237", #"Code" = "Sample_Code_237"],
					        [#"State" = "Sample_State_238", #"Code" = "Sample_Code_238"],
					        [#"State" = "Sample_State_239", #"Code" = "Sample_Code_239"],
					        [#"State" = "Sample_State_240", #"Code" = "Sample_Code_240"],
					        [#"State" = "Sample_State_241", #"Code" = "Sample_Code_241"],
					        [#"State" = "Sample_State_242", #"Code" = "Sample_Code_242"],
					        [#"State" = "Sample_State_243", #"Code" = "Sample_Code_243"],
					        [#"State" = "Sample_State_244", #"Code" = "Sample_Code_244"],
					        [#"State" = "Sample_State_245", #"Code" = "Sample_Code_245"],
					        [#"State" = "Sample_State_246", #"Code" = "Sample_Code_246"],
					        [#"State" = "Sample_State_247", #"Code" = "Sample_Code_247"],
					        [#"State" = "Sample_State_248", #"Code" = "Sample_Code_248"],
					        [#"State" = "Sample_State_249", #"Code" = "Sample_Code_249"],
					        [#"State" = "Sample_State_250", #"Code" = "Sample_Code_250"],
					        [#"State" = "Sample_State_251", #"Code" = "Sample_Code_251"],
					        [#"State" = "Sample_State_252", #"Code" = "Sample_Code_252"],
					        [#"State" = "Sample_State_253", #"Code" = "Sample_Code_253"],
					        [#"State" = "Sample_State_254", #"Code" = "Sample_Code_254"],
					        [#"State" = "Sample_State_255", #"Code" = "Sample_Code_255"],
					        [#"State" = "Sample_State_256", #"Code" = "Sample_Code_256"],
					        [#"State" = "Sample_State_257", #"Code" = "Sample_Code_257"],
					        [#"State" = "Sample_State_258", #"Code" = "Sample_Code_258"],
					        [#"State" = "Sample_State_259", #"Code" = "Sample_Code_259"],
					        [#"State" = "Sample_State_260", #"Code" = "Sample_Code_260"],
					        [#"State" = "Sample_State_261", #"Code" = "Sample_Code_261"],
					        [#"State" = "Sample_State_262", #"Code" = "Sample_Code_262"],
					        [#"State" = "Sample_State_263", #"Code" = "Sample_Code_263"],
					        [#"State" = "Sample_State_264", #"Code" = "Sample_Code_264"],
					        [#"State" = "Sample_State_265", #"Code" = "Sample_Code_265"],
					        [#"State" = "Sample_State_266", #"Code" = "Sample_Code_266"],
					        [#"State" = "Sample_State_267", #"Code" = "Sample_Code_267"],
					        [#"State" = "Sample_State_268", #"Code" = "Sample_Code_268"],
					        [#"State" = "Sample_State_269", #"Code" = "Sample_Code_269"],
					        [#"State" = "Sample_State_270", #"Code" = "Sample_Code_270"],
					        [#"State" = "Sample_State_271", #"Code" = "Sample_Code_271"],
					        [#"State" = "Sample_State_272", #"Code" = "Sample_Code_272"],
					        [#"State" = "Sample_State_273", #"Code" = "Sample_Code_273"],
					        [#"State" = "Sample_State_274", #"Code" = "Sample_Code_274"],
					        [#"State" = "Sample_State_275", #"Code" = "Sample_Code_275"],
					        [#"State" = "Sample_State_276", #"Code" = "Sample_Code_276"],
					        [#"State" = "Sample_State_277", #"Code" = "Sample_Code_277"],
					        [#"State" = "Sample_State_278", #"Code" = "Sample_Code_278"],
					        [#"State" = "Sample_State_279", #"Code" = "Sample_Code_279"],
					        [#"State" = "Sample_State_280", #"Code" = "Sample_Code_280"],
					        [#"State" = "Sample_State_281", #"Code" = "Sample_Code_281"],
					        [#"State" = "Sample_State_282", #"Code" = "Sample_Code_282"],
					        [#"State" = "Sample_State_283", #"Code" = "Sample_Code_283"],
					        [#"State" = "Sample_State_284", #"Code" = "Sample_Code_284"],
					        [#"State" = "Sample_State_285", #"Code" = "Sample_Code_285"],
					        [#"State" = "Sample_State_286", #"Code" = "Sample_Code_286"],
					        [#"State" = "Sample_State_287", #"Code" = "Sample_Code_287"],
					        [#"State" = "Sample_State_288", #"Code" = "Sample_Code_288"],
					        [#"State" = "Sample_State_289", #"Code" = "Sample_Code_289"],
					        [#"State" = "Sample_State_290", #"Code" = "Sample_Code_290"],
					        [#"State" = "Sample_State_291", #"Code" = "Sample_Code_291"],
					        [#"State" = "Sample_State_292", #"Code" = "Sample_Code_292"],
					        [#"State" = "Sample_State_293", #"Code" = "Sample_Code_293"],
					        [#"State" = "Sample_State_294", #"Code" = "Sample_Code_294"],
					        [#"State" = "Sample_State_295", #"Code" = "Sample_Code_295"],
					        [#"State" = "Sample_State_296", #"Code" = "Sample_Code_296"],
					        [#"State" = "Sample_State_297", #"Code" = "Sample_Code_297"],
					        [#"State" = "Sample_State_298", #"Code" = "Sample_Code_298"],
					        [#"State" = "Sample_State_299", #"Code" = "Sample_Code_299"],
					        [#"State" = "Sample_State_300", #"Code" = "Sample_Code_300"],
					        [#"State" = "Sample_State_301", #"Code" = "Sample_Code_301"],
					        [#"State" = "Sample_State_302", #"Code" = "Sample_Code_302"],
					        [#"State" = "Sample_State_303", #"Code" = "Sample_Code_303"],
					        [#"State" = "Sample_State_304", #"Code" = "Sample_Code_304"],
					        [#"State" = "Sample_State_305", #"Code" = "Sample_Code_305"],
					        [#"State" = "Sample_State_306", #"Code" = "Sample_Code_306"],
					        [#"State" = "Sample_State_307", #"Code" = "Sample_Code_307"],
					        [#"State" = "Sample_State_308", #"Code" = "Sample_Code_308"],
					        [#"State" = "Sample_State_309", #"Code" = "Sample_Code_309"],
					        [#"State" = "Sample_State_310", #"Code" = "Sample_Code_310"],
					        [#"State" = "Sample_State_311", #"Code" = "Sample_Code_311"],
					        [#"State" = "Sample_State_312", #"Code" = "Sample_Code_312"],
					        [#"State" = "Sample_State_313", #"Code" = "Sample_Code_313"],
					        [#"State" = "Sample_State_314", #"Code" = "Sample_Code_314"],
					        [#"State" = "Sample_State_315", #"Code" = "Sample_Code_315"],
					        [#"State" = "Sample_State_316", #"Code" = "Sample_Code_316"],
					        [#"State" = "Sample_State_317", #"Code" = "Sample_Code_317"],
					        [#"State" = "Sample_State_318", #"Code" = "Sample_Code_318"],
					        [#"State" = "Sample_State_319", #"Code" = "Sample_Code_319"],
					        [#"State" = "Sample_State_320", #"Code" = "Sample_Code_320"],
					        [#"State" = "Sample_State_321", #"Code" = "Sample_Code_321"],
					        [#"State" = "Sample_State_322", #"Code" = "Sample_Code_322"],
					        [#"State" = "Sample_State_323", #"Code" = "Sample_Code_323"],
					        [#"State" = "Sample_State_324", #"Code" = "Sample_Code_324"],
					        [#"State" = "Sample_State_325", #"Code" = "Sample_Code_325"],
					        [#"State" = "Sample_State_326", #"Code" = "Sample_Code_326"],
					        [#"State" = "Sample_State_327", #"Code" = "Sample_Code_327"],
					        [#"State" = "Sample_State_328", #"Code" = "Sample_Code_328"],
					        [#"State" = "Sample_State_329", #"Code" = "Sample_Code_329"],
					        [#"State" = "Sample_State_330", #"Code" = "Sample_Code_330"],
					        [#"State" = "Sample_State_331", #"Code" = "Sample_Code_331"],
					        [#"State" = "Sample_State_332", #"Code" = "Sample_Code_332"],
					        [#"State" = "Sample_State_333", #"Code" = "Sample_Code_333"],
					        [#"State" = "Sample_State_334", #"Code" = "Sample_Code_334"],
					        [#"State" = "Sample_State_335", #"Code" = "Sample_Code_335"],
					        [#"State" = "Sample_State_336", #"Code" = "Sample_Code_336"],
					        [#"State" = "Sample_State_337", #"Code" = "Sample_Code_337"],
					        [#"State" = "Sample_State_338", #"Code" = "Sample_Code_338"],
					        [#"State" = "Sample_State_339", #"Code" = "Sample_Code_339"],
					        [#"State" = "Sample_State_340", #"Code" = "Sample_Code_340"],
					        [#"State" = "Sample_State_341", #"Code" = "Sample_Code_341"],
					        [#"State" = "Sample_State_342", #"Code" = "Sample_Code_342"],
					        [#"State" = "Sample_State_343", #"Code" = "Sample_Code_343"],
					        [#"State" = "Sample_State_344", #"Code" = "Sample_Code_344"],
					        [#"State" = "Sample_State_345", #"Code" = "Sample_Code_345"],
					        [#"State" = "Sample_State_346", #"Code" = "Sample_Code_346"],
					        [#"State" = "Sample_State_347", #"Code" = "Sample_Code_347"],
					        [#"State" = "Sample_State_348", #"Code" = "Sample_Code_348"],
					        [#"State" = "Sample_State_349", #"Code" = "Sample_Code_349"],
					        [#"State" = "Sample_State_350", #"Code" = "Sample_Code_350"],
					        [#"State" = "Sample_State_351", #"Code" = "Sample_Code_351"],
					        [#"State" = "Sample_State_352", #"Code" = "Sample_Code_352"],
					        [#"State" = "Sample_State_353", #"Code" = "Sample_Code_353"],
					        [#"State" = "Sample_State_354", #"Code" = "Sample_Code_354"],
					        [#"State" = "Sample_State_355", #"Code" = "Sample_Code_355"],
					        [#"State" = "Sample_State_356", #"Code" = "Sample_Code_356"],
					        [#"State" = "Sample_State_357", #"Code" = "Sample_Code_357"],
					        [#"State" = "Sample_State_358", #"Code" = "Sample_Code_358"],
					        [#"State" = "Sample_State_359", #"Code" = "Sample_Code_359"],
					        [#"State" = "Sample_State_360", #"Code" = "Sample_Code_360"],
					        [#"State" = "Sample_State_361", #"Code" = "Sample_Code_361"],
					        [#"State" = "Sample_State_362", #"Code" = "Sample_Code_362"],
					        [#"State" = "Sample_State_363", #"Code" = "Sample_Code_363"],
					        [#"State" = "Sample_State_364", #"Code" = "Sample_Code_364"],
					        [#"State" = "Sample_State_365", #"Code" = "Sample_Code_365"],
					        [#"State" = "Sample_State_366", #"Code" = "Sample_Code_366"],
					        [#"State" = "Sample_State_367", #"Code" = "Sample_Code_367"],
					        [#"State" = "Sample_State_368", #"Code" = "Sample_Code_368"],
					        [#"State" = "Sample_State_369", #"Code" = "Sample_Code_369"],
					        [#"State" = "Sample_State_370", #"Code" = "Sample_Code_370"],
					        [#"State" = "Sample_State_371", #"Code" = "Sample_Code_371"],
					        [#"State" = "Sample_State_372", #"Code" = "Sample_Code_372"],
					        [#"State" = "Sample_State_373", #"Code" = "Sample_Code_373"],
					        [#"State" = "Sample_State_374", #"Code" = "Sample_Code_374"],
					        [#"State" = "Sample_State_375", #"Code" = "Sample_Code_375"],
					        [#"State" = "Sample_State_376", #"Code" = "Sample_Code_376"],
					        [#"State" = "Sample_State_377", #"Code" = "Sample_Code_377"],
					        [#"State" = "Sample_State_378", #"Code" = "Sample_Code_378"],
					        [#"State" = "Sample_State_379", #"Code" = "Sample_Code_379"],
					        [#"State" = "Sample_State_380", #"Code" = "Sample_Code_380"],
					        [#"State" = "Sample_State_381", #"Code" = "Sample_Code_381"],
					        [#"State" = "Sample_State_382", #"Code" = "Sample_Code_382"],
					        [#"State" = "Sample_State_383", #"Code" = "Sample_Code_383"],
					        [#"State" = "Sample_State_384", #"Code" = "Sample_Code_384"],
					        [#"State" = "Sample_State_385", #"Code" = "Sample_Code_385"],
					        [#"State" = "Sample_State_386", #"Code" = "Sample_Code_386"],
					        [#"State" = "Sample_State_387", #"Code" = "Sample_Code_387"],
					        [#"State" = "Sample_State_388", #"Code" = "Sample_Code_388"],
					        [#"State" = "Sample_State_389", #"Code" = "Sample_Code_389"],
					        [#"State" = "Sample_State_390", #"Code" = "Sample_Code_390"],
					        [#"State" = "Sample_State_391", #"Code" = "Sample_Code_391"],
					        [#"State" = "Sample_State_392", #"Code" = "Sample_Code_392"],
					        [#"State" = "Sample_State_393", #"Code" = "Sample_Code_393"],
					        [#"State" = "Sample_State_394", #"Code" = "Sample_Code_394"],
					        [#"State" = "Sample_State_395", #"Code" = "Sample_Code_395"],
					        [#"State" = "Sample_State_396", #"Code" = "Sample_Code_396"],
					        [#"State" = "Sample_State_397", #"Code" = "Sample_Code_397"],
					        [#"State" = "Sample_State_398", #"Code" = "Sample_Code_398"],
					        [#"State" = "Sample_State_399", #"Code" = "Sample_Code_399"],
					        [#"State" = "Sample_State_400", #"Code" = "Sample_Code_400"],
					        [#"State" = "Sample_State_401", #"Code" = "Sample_Code_401"],
					        [#"State" = "Sample_State_402", #"Code" = "Sample_Code_402"],
					        [#"State" = "Sample_State_403", #"Code" = "Sample_Code_403"],
					        [#"State" = "Sample_State_404", #"Code" = "Sample_Code_404"],
					        [#"State" = "Sample_State_405", #"Code" = "Sample_Code_405"],
					        [#"State" = "Sample_State_406", #"Code" = "Sample_Code_406"],
					        [#"State" = "Sample_State_407", #"Code" = "Sample_Code_407"],
					        [#"State" = "Sample_State_408", #"Code" = "Sample_Code_408"],
					        [#"State" = "Sample_State_409", #"Code" = "Sample_Code_409"],
					        [#"State" = "Sample_State_410", #"Code" = "Sample_Code_410"],
					        [#"State" = "Sample_State_411", #"Code" = "Sample_Code_411"],
					        [#"State" = "Sample_State_412", #"Code" = "Sample_Code_412"],
					        [#"State" = "Sample_State_413", #"Code" = "Sample_Code_413"],
					        [#"State" = "Sample_State_414", #"Code" = "Sample_Code_414"],
					        [#"State" = "Sample_State_415", #"Code" = "Sample_Code_415"],
					        [#"State" = "Sample_State_416", #"Code" = "Sample_Code_416"],
					        [#"State" = "Sample_State_417", #"Code" = "Sample_Code_417"],
					        [#"State" = "Sample_State_418", #"Code" = "Sample_Code_418"],
					        [#"State" = "Sample_State_419", #"Code" = "Sample_Code_419"],
					        [#"State" = "Sample_State_420", #"Code" = "Sample_Code_420"],
					        [#"State" = "Sample_State_421", #"Code" = "Sample_Code_421"],
					        [#"State" = "Sample_State_422", #"Code" = "Sample_Code_422"],
					        [#"State" = "Sample_State_423", #"Code" = "Sample_Code_423"],
					        [#"State" = "Sample_State_424", #"Code" = "Sample_Code_424"],
					        [#"State" = "Sample_State_425", #"Code" = "Sample_Code_425"],
					        [#"State" = "Sample_State_426", #"Code" = "Sample_Code_426"],
					        [#"State" = "Sample_State_427", #"Code" = "Sample_Code_427"],
					        [#"State" = "Sample_State_428", #"Code" = "Sample_Code_428"],
					        [#"State" = "Sample_State_429", #"Code" = "Sample_Code_429"],
					        [#"State" = "Sample_State_430", #"Code" = "Sample_Code_430"],
					        [#"State" = "Sample_State_431", #"Code" = "Sample_Code_431"],
					        [#"State" = "Sample_State_432", #"Code" = "Sample_Code_432"],
					        [#"State" = "Sample_State_433", #"Code" = "Sample_Code_433"],
					        [#"State" = "Sample_State_434", #"Code" = "Sample_Code_434"],
					        [#"State" = "Sample_State_435", #"Code" = "Sample_Code_435"],
					        [#"State" = "Sample_State_436", #"Code" = "Sample_Code_436"],
					        [#"State" = "Sample_State_437", #"Code" = "Sample_Code_437"],
					        [#"State" = "Sample_State_438", #"Code" = "Sample_Code_438"],
					        [#"State" = "Sample_State_439", #"Code" = "Sample_Code_439"],
					        [#"State" = "Sample_State_440", #"Code" = "Sample_Code_440"],
					        [#"State" = "Sample_State_441", #"Code" = "Sample_Code_441"],
					        [#"State" = "Sample_State_442", #"Code" = "Sample_Code_442"],
					        [#"State" = "Sample_State_443", #"Code" = "Sample_Code_443"],
					        [#"State" = "Sample_State_444", #"Code" = "Sample_Code_444"],
					        [#"State" = "Sample_State_445", #"Code" = "Sample_Code_445"],
					        [#"State" = "Sample_State_446", #"Code" = "Sample_Code_446"],
					        [#"State" = "Sample_State_447", #"Code" = "Sample_Code_447"],
					        [#"State" = "Sample_State_448", #"Code" = "Sample_Code_448"],
					        [#"State" = "Sample_State_449", #"Code" = "Sample_Code_449"],
					        [#"State" = "Sample_State_450", #"Code" = "Sample_Code_450"],
					        [#"State" = "Sample_State_451", #"Code" = "Sample_Code_451"],
					        [#"State" = "Sample_State_452", #"Code" = "Sample_Code_452"],
					        [#"State" = "Sample_State_453", #"Code" = "Sample_Code_453"],
					        [#"State" = "Sample_State_454", #"Code" = "Sample_Code_454"],
					        [#"State" = "Sample_State_455", #"Code" = "Sample_Code_455"],
					        [#"State" = "Sample_State_456", #"Code" = "Sample_Code_456"],
					        [#"State" = "Sample_State_457", #"Code" = "Sample_Code_457"],
					        [#"State" = "Sample_State_458", #"Code" = "Sample_Code_458"],
					        [#"State" = "Sample_State_459", #"Code" = "Sample_Code_459"],
					        [#"State" = "Sample_State_460", #"Code" = "Sample_Code_460"],
					        [#"State" = "Sample_State_461", #"Code" = "Sample_Code_461"],
					        [#"State" = "Sample_State_462", #"Code" = "Sample_Code_462"],
					        [#"State" = "Sample_State_463", #"Code" = "Sample_Code_463"],
					        [#"State" = "Sample_State_464", #"Code" = "Sample_Code_464"],
					        [#"State" = "Sample_State_465", #"Code" = "Sample_Code_465"],
					        [#"State" = "Sample_State_466", #"Code" = "Sample_Code_466"],
					        [#"State" = "Sample_State_467", #"Code" = "Sample_Code_467"],
					        [#"State" = "Sample_State_468", #"Code" = "Sample_Code_468"],
					        [#"State" = "Sample_State_469", #"Code" = "Sample_Code_469"],
					        [#"State" = "Sample_State_470", #"Code" = "Sample_Code_470"],
					        [#"State" = "Sample_State_471", #"Code" = "Sample_Code_471"],
					        [#"State" = "Sample_State_472", #"Code" = "Sample_Code_472"],
					        [#"State" = "Sample_State_473", #"Code" = "Sample_Code_473"],
					        [#"State" = "Sample_State_474", #"Code" = "Sample_Code_474"],
					        [#"State" = "Sample_State_475", #"Code" = "Sample_Code_475"],
					        [#"State" = "Sample_State_476", #"Code" = "Sample_Code_476"],
					        [#"State" = "Sample_State_477", #"Code" = "Sample_Code_477"],
					        [#"State" = "Sample_State_478", #"Code" = "Sample_Code_478"],
					        [#"State" = "Sample_State_479", #"Code" = "Sample_Code_479"],
					        [#"State" = "Sample_State_480", #"Code" = "Sample_Code_480"],
					        [#"State" = "Sample_State_481", #"Code" = "Sample_Code_481"],
					        [#"State" = "Sample_State_482", #"Code" = "Sample_Code_482"],
					        [#"State" = "Sample_State_483", #"Code" = "Sample_Code_483"],
					        [#"State" = "Sample_State_484", #"Code" = "Sample_Code_484"],
					        [#"State" = "Sample_State_485", #"Code" = "Sample_Code_485"],
					        [#"State" = "Sample_State_486", #"Code" = "Sample_Code_486"],
					        [#"State" = "Sample_State_487", #"Code" = "Sample_Code_487"],
					        [#"State" = "Sample_State_488", #"Code" = "Sample_Code_488"],
					        [#"State" = "Sample_State_489", #"Code" = "Sample_Code_489"],
					        [#"State" = "Sample_State_490", #"Code" = "Sample_Code_490"],
					        [#"State" = "Sample_State_491", #"Code" = "Sample_Code_491"],
					        [#"State" = "Sample_State_492", #"Code" = "Sample_Code_492"],
					        [#"State" = "Sample_State_493", #"Code" = "Sample_Code_493"],
					        [#"State" = "Sample_State_494", #"Code" = "Sample_Code_494"],
					        [#"State" = "Sample_State_495", #"Code" = "Sample_Code_495"],
					        [#"State" = "Sample_State_496", #"Code" = "Sample_Code_496"],
					        [#"State" = "Sample_State_497", #"Code" = "Sample_Code_497"],
					        [#"State" = "Sample_State_498", #"Code" = "Sample_Code_498"],
					        [#"State" = "Sample_State_499", #"Code" = "Sample_Code_499"],
					        [#"State" = "Sample_State_500", #"Code" = "Sample_Code_500"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"State", type text},
					        {"Code", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table