table 'Profit Bin Size'
	lineageTag: d0482464-25aa-416f-aef6-9f36f7ab5153

	measure 'Profit Bin Size Value' = SELECTEDVALUE('Profit Bin Size'[Profit Bin Size], 50)
		lineageTag: 09b612ee-0dd4-4461-940c-82d3e30dfe45

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Profit Bin Size'
		dataType: double
		formatString: 0
		lineageTag: b9d5e228-6d0c-4968-a196-a6ec1224ac59
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Profit Bin Size' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_Id = 071f04d5c9f141c6ac4a7aad75f3a95f

