table 'Sample - Superstore_Returns'
	lineageTag: d6efc5c2-164d-404b-9c5e-493c4ece0591

	column 'Order ID'
		dataType: string
		lineageTag: b3b8f03e-0101-4536-a5fc-770f58eeac36
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column Returned
		dataType: string
		lineageTag: f5ca06f7-127e-44a6-b602-1e33b9f36fc5
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	partition 'Sample - Superstore_Returns' = m
		mode: import
		source =
				let
					    Source = Csv.Document(
					        File.Contents("https://saastestlatest.blob.core.windows.net/saas-test-reports/Sample%20-%20Superstore_Returns.csv?se=2025-11-05T09%3A55%3A39Z&sp=r&sv=2025-11-05&sr=b&sig=GK9pddksBT3UjW1WCY2nw/FbaykDi6QrLhuUQX47AYo%3D"),
					        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
					    ),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Order ID", type text}, {"Returned", type text}})
					in
					    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table