table 'Orders+ (Sample - Superstore)_Returns'
	lineageTag: 1283645f-1f89-4f1e-a571-dea39f37e929

	column Returned
		dataType: string
		lineageTag: 68bc5d28-0c75-4862-ba71-383e1c133fa3
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: e2f3aa1e-10b8-4736-9430-ce0b97539b03
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	partition 'Orders+ (Sample - Superstore)_Returns' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Returned" = "recovery", #"Order ID" = 2669],
					        [#"Returned" = "call", #"Order ID" = 3522],
					        [#"Returned" = "vbulletin", #"Order ID" = 8868],
					        [#"Returned" = "mike", #"Order ID" = 8099],
					        [#"Returned" = "magnetic", #"Order ID" = 7279],
					        [#"Returned" = "terry", #"Order ID" = 5049],
					        [#"Returned" = "quarterly", #"Order ID" = 5414],
					        [#"Returned" = "map", #"Order ID" = 5962],
					        [#"Returned" = "matters", #"Order ID" = 8484],
					        [#"Returned" = "charlie", #"Order ID" = 7611],
					        [#"Returned" = "shareware", #"Order ID" = 9823],
					        [#"Returned" = "cables", #"Order ID" = 4565],
					        [#"Returned" = "capacity", #"Order ID" = 1116],
					        [#"Returned" = "authority", #"Order ID" = 6699],
					        [#"Returned" = "minority", #"Order ID" = 5474],
					        [#"Returned" = "somebody", #"Order ID" = 2493],
					        [#"Returned" = "crown", #"Order ID" = 3026],
					        [#"Returned" = "pharmacy", #"Order ID" = 6125],
					        [#"Returned" = "seriously", #"Order ID" = 5571],
					        [#"Returned" = "string", #"Order ID" = 3115],
					        [#"Returned" = "editing", #"Order ID" = 9698],
					        [#"Returned" = "mine", #"Order ID" = 7449],
					        [#"Returned" = "grants", #"Order ID" = 4443],
					        [#"Returned" = "loose", #"Order ID" = 7852],
					        [#"Returned" = "announced", #"Order ID" = 9062],
					        [#"Returned" = "leads", #"Order ID" = 6923],
					        [#"Returned" = "suggestions", #"Order ID" = 7994],
					        [#"Returned" = "scores", #"Order ID" = 7865],
					        [#"Returned" = "intervention", #"Order ID" = 7636],
					        [#"Returned" = "genre", #"Order ID" = 3000],
					        [#"Returned" = "secrets", #"Order ID" = 5959],
					        [#"Returned" = "instrument", #"Order ID" = 5762],
					        [#"Returned" = "drum", #"Order ID" = 2878],
					        [#"Returned" = "classes", #"Order ID" = 4728],
					        [#"Returned" = "correction", #"Order ID" = 6750],
					        [#"Returned" = "layout", #"Order ID" = 6700],
					        [#"Returned" = "ones", #"Order ID" = 6543],
					        [#"Returned" = "future", #"Order ID" = 9935],
					        [#"Returned" = "wheels", #"Order ID" = 2711],
					        [#"Returned" = "year", #"Order ID" = 5928],
					        [#"Returned" = "jersey", #"Order ID" = 1217],
					        [#"Returned" = "generally", #"Order ID" = 6789],
					        [#"Returned" = "lat", #"Order ID" = 6377],
					        [#"Returned" = "shell", #"Order ID" = 1711],
					        [#"Returned" = "recreation", #"Order ID" = 8002],
					        [#"Returned" = "accessible", #"Order ID" = 9330],
					        [#"Returned" = "wednesday", #"Order ID" = 5058],
					        [#"Returned" = "crisis", #"Order ID" = 7282],
					        [#"Returned" = "recommended", #"Order ID" = 9040],
					        [#"Returned" = "sounds", #"Order ID" = 5171],
					        [#"Returned" = "instruction", #"Order ID" = 4320],
					        [#"Returned" = "encoding", #"Order ID" = 8713],
					        [#"Returned" = "tracker", #"Order ID" = 7135],
					        [#"Returned" = "program", #"Order ID" = 9344],
					        [#"Returned" = "file", #"Order ID" = 9693],
					        [#"Returned" = "conversion", #"Order ID" = 6932],
					        [#"Returned" = "breaks", #"Order ID" = 2990],
					        [#"Returned" = "kitchen", #"Order ID" = 6130],
					        [#"Returned" = "pan", #"Order ID" = 3141],
					        [#"Returned" = "motorola", #"Order ID" = 4238],
					        [#"Returned" = "changed", #"Order ID" = 2550],
					        [#"Returned" = "intermediate", #"Order ID" = 8099],
					        [#"Returned" = "outside", #"Order ID" = 8721],
					        [#"Returned" = "been", #"Order ID" = 5287],
					        [#"Returned" = "drop", #"Order ID" = 2184],
					        [#"Returned" = "hall", #"Order ID" = 9654],
					        [#"Returned" = "birthday", #"Order ID" = 2074],
					        [#"Returned" = "keep", #"Order ID" = 5948],
					        [#"Returned" = "importance", #"Order ID" = 3611],
					        [#"Returned" = "situations", #"Order ID" = 3792],
					        [#"Returned" = "mercedes", #"Order ID" = 3763],
					        [#"Returned" = "keywords", #"Order ID" = 1920],
					        [#"Returned" = "chairs", #"Order ID" = 1589],
					        [#"Returned" = "entered", #"Order ID" = 1047],
					        [#"Returned" = "feels", #"Order ID" = 5821],
					        [#"Returned" = "covered", #"Order ID" = 4028],
					        [#"Returned" = "communication", #"Order ID" = 7223],
					        [#"Returned" = "independent", #"Order ID" = 8059],
					        [#"Returned" = "installing", #"Order ID" = 1394],
					        [#"Returned" = "cinema", #"Order ID" = 8269],
					        [#"Returned" = "create", #"Order ID" = 3010],
					        [#"Returned" = "bands", #"Order ID" = 4207],
					        [#"Returned" = "employees", #"Order ID" = 9459],
					        [#"Returned" = "denver", #"Order ID" = 4676],
					        [#"Returned" = "coins", #"Order ID" = 7532],
					        [#"Returned" = "rhode", #"Order ID" = 8122],
					        [#"Returned" = "victims", #"Order ID" = 5011],
					        [#"Returned" = "bring", #"Order ID" = 6723],
					        [#"Returned" = "represented", #"Order ID" = 8923],
					        [#"Returned" = "advanced", #"Order ID" = 9181],
					        [#"Returned" = "want", #"Order ID" = 5122],
					        [#"Returned" = "important", #"Order ID" = 2498],
					        [#"Returned" = "breasts", #"Order ID" = 2350],
					        [#"Returned" = "exam", #"Order ID" = 2347],
					        [#"Returned" = "desired", #"Order ID" = 2251],
					        [#"Returned" = "mutual", #"Order ID" = 8882],
					        [#"Returned" = "restoration", #"Order ID" = 6357],
					        [#"Returned" = "toward", #"Order ID" = 8548],
					        [#"Returned" = "camp", #"Order ID" = 6573],
					        [#"Returned" = "cyprus", #"Order ID" = 4896],
					        [#"Returned" = "rescue", #"Order ID" = 4623],
					        [#"Returned" = "est", #"Order ID" = 3961],
					        [#"Returned" = "derived", #"Order ID" = 1449],
					        [#"Returned" = "headset", #"Order ID" = 8512],
					        [#"Returned" = "oh", #"Order ID" = 3756],
					        [#"Returned" = "cotton", #"Order ID" = 2969],
					        [#"Returned" = "con", #"Order ID" = 5336],
					        [#"Returned" = "partners", #"Order ID" = 6906],
					        [#"Returned" = "card", #"Order ID" = 7325],
					        [#"Returned" = "calculate", #"Order ID" = 7382],
					        [#"Returned" = "instructions", #"Order ID" = 1083],
					        [#"Returned" = "semester", #"Order ID" = 3878],
					        [#"Returned" = "colorado", #"Order ID" = 6673],
					        [#"Returned" = "evaluate", #"Order ID" = 4954],
					        [#"Returned" = "kick", #"Order ID" = 3678],
					        [#"Returned" = "beyond", #"Order ID" = 4658],
					        [#"Returned" = "ebony", #"Order ID" = 3763],
					        [#"Returned" = "accurate", #"Order ID" = 1697],
					        [#"Returned" = "forget", #"Order ID" = 4846],
					        [#"Returned" = "skin", #"Order ID" = 3189],
					        [#"Returned" = "mayor", #"Order ID" = 6931],
					        [#"Returned" = "mounted", #"Order ID" = 3542],
					        [#"Returned" = "nov", #"Order ID" = 1792],
					        [#"Returned" = "pine", #"Order ID" = 5373],
					        [#"Returned" = "forgotten", #"Order ID" = 2788],
					        [#"Returned" = "intelligence", #"Order ID" = 9490],
					        [#"Returned" = "aged", #"Order ID" = 2906],
					        [#"Returned" = "hardcover", #"Order ID" = 4501],
					        [#"Returned" = "saudi", #"Order ID" = 9791],
					        [#"Returned" = "rapid", #"Order ID" = 1520],
					        [#"Returned" = "dogs", #"Order ID" = 5027],
					        [#"Returned" = "fun", #"Order ID" = 6759],
					        [#"Returned" = "first", #"Order ID" = 4296],
					        [#"Returned" = "benefit", #"Order ID" = 6045],
					        [#"Returned" = "consolidation", #"Order ID" = 5116],
					        [#"Returned" = "special", #"Order ID" = 7120],
					        [#"Returned" = "medical", #"Order ID" = 6817],
					        [#"Returned" = "cambridge", #"Order ID" = 9335],
					        [#"Returned" = "clock", #"Order ID" = 9468],
					        [#"Returned" = "views", #"Order ID" = 7453],
					        [#"Returned" = "world", #"Order ID" = 1742],
					        [#"Returned" = "upcoming", #"Order ID" = 8553],
					        [#"Returned" = "surgery", #"Order ID" = 7096],
					        [#"Returned" = "electricity", #"Order ID" = 5040],
					        [#"Returned" = "ups", #"Order ID" = 6071],
					        [#"Returned" = "cs", #"Order ID" = 1480],
					        [#"Returned" = "majority", #"Order ID" = 1179],
					        [#"Returned" = "browse", #"Order ID" = 2725],
					        [#"Returned" = "connections", #"Order ID" = 9184],
					        [#"Returned" = "album", #"Order ID" = 1228],
					        [#"Returned" = "into", #"Order ID" = 8339],
					        [#"Returned" = "performed", #"Order ID" = 9547],
					        [#"Returned" = "tight", #"Order ID" = 9795],
					        [#"Returned" = "desktop", #"Order ID" = 9091],
					        [#"Returned" = "nova", #"Order ID" = 3782],
					        [#"Returned" = "rush", #"Order ID" = 9172],
					        [#"Returned" = "francisco", #"Order ID" = 3568],
					        [#"Returned" = "memorabilia", #"Order ID" = 1558],
					        [#"Returned" = "biology", #"Order ID" = 9764],
					        [#"Returned" = "identifying", #"Order ID" = 1065],
					        [#"Returned" = "tobacco", #"Order ID" = 8698],
					        [#"Returned" = "couples", #"Order ID" = 2279],
					        [#"Returned" = "journals", #"Order ID" = 7721],
					        [#"Returned" = "summary", #"Order ID" = 6354],
					        [#"Returned" = "streets", #"Order ID" = 7996],
					        [#"Returned" = "espn", #"Order ID" = 4632],
					        [#"Returned" = "flying", #"Order ID" = 1244],
					        [#"Returned" = "displaying", #"Order ID" = 4489],
					        [#"Returned" = "houston", #"Order ID" = 6958],
					        [#"Returned" = "bear", #"Order ID" = 1718],
					        [#"Returned" = "return", #"Order ID" = 3624],
					        [#"Returned" = "adopt", #"Order ID" = 6669],
					        [#"Returned" = "sep", #"Order ID" = 7056],
					        [#"Returned" = "juvenile", #"Order ID" = 6877],
					        [#"Returned" = "dealing", #"Order ID" = 7371],
					        [#"Returned" = "contemporary", #"Order ID" = 6853],
					        [#"Returned" = "canvas", #"Order ID" = 3298],
					        [#"Returned" = "shoot", #"Order ID" = 3854],
					        [#"Returned" = "hungary", #"Order ID" = 7665],
					        [#"Returned" = "access", #"Order ID" = 2292],
					        [#"Returned" = "instant", #"Order ID" = 3906],
					        [#"Returned" = "attempts", #"Order ID" = 8115],
					        [#"Returned" = "penalty", #"Order ID" = 7556],
					        [#"Returned" = "beta", #"Order ID" = 8569],
					        [#"Returned" = "wyoming", #"Order ID" = 8906],
					        [#"Returned" = "martin", #"Order ID" = 8294],
					        [#"Returned" = "bonus", #"Order ID" = 6564],
					        [#"Returned" = "specialists", #"Order ID" = 1061],
					        [#"Returned" = "accepted", #"Order ID" = 6302],
					        [#"Returned" = "introduced", #"Order ID" = 8941],
					        [#"Returned" = "woods", #"Order ID" = 8897],
					        [#"Returned" = "gross", #"Order ID" = 6290],
					        [#"Returned" = "be", #"Order ID" = 3672],
					        [#"Returned" = "fox", #"Order ID" = 1805],
					        [#"Returned" = "extensive", #"Order ID" = 3474],
					        [#"Returned" = "freeware", #"Order ID" = 6535],
					        [#"Returned" = "joe", #"Order ID" = 4481],
					        [#"Returned" = "visiting", #"Order ID" = 1199],
					        [#"Returned" = "hello", #"Order ID" = 6638],
					        [#"Returned" = "ear", #"Order ID" = 6304],
					        [#"Returned" = "perfectly", #"Order ID" = 2837],
					        [#"Returned" = "parenting", #"Order ID" = 7894],
					        [#"Returned" = "audience", #"Order ID" = 5152],
					        [#"Returned" = "henry", #"Order ID" = 8631],
					        [#"Returned" = "elements", #"Order ID" = 1520],
					        [#"Returned" = "struct", #"Order ID" = 7922],
					        [#"Returned" = "brad", #"Order ID" = 1716],
					        [#"Returned" = "chairs", #"Order ID" = 2792],
					        [#"Returned" = "india", #"Order ID" = 9042],
					        [#"Returned" = "portions", #"Order ID" = 7240],
					        [#"Returned" = "handling", #"Order ID" = 1164],
					        [#"Returned" = "discounts", #"Order ID" = 3341],
					        [#"Returned" = "cluster", #"Order ID" = 8205],
					        [#"Returned" = "polish", #"Order ID" = 4691],
					        [#"Returned" = "bulletin", #"Order ID" = 4271],
					        [#"Returned" = "ce", #"Order ID" = 1311],
					        [#"Returned" = "seat", #"Order ID" = 3581],
					        [#"Returned" = "household", #"Order ID" = 5874],
					        [#"Returned" = "appearance", #"Order ID" = 9212],
					        [#"Returned" = "potentially", #"Order ID" = 9854],
					        [#"Returned" = "hiv", #"Order ID" = 8929],
					        [#"Returned" = "simple", #"Order ID" = 3116],
					        [#"Returned" = "tuesday", #"Order ID" = 9201],
					        [#"Returned" = "links", #"Order ID" = 3057],
					        [#"Returned" = "wireless", #"Order ID" = 4671],
					        [#"Returned" = "estate", #"Order ID" = 9841],
					        [#"Returned" = "jan", #"Order ID" = 1038],
					        [#"Returned" = "ocean", #"Order ID" = 9932],
					        [#"Returned" = "southeast", #"Order ID" = 1034],
					        [#"Returned" = "promoting", #"Order ID" = 4699],
					        [#"Returned" = "national", #"Order ID" = 1685],
					        [#"Returned" = "guard", #"Order ID" = 5150],
					        [#"Returned" = "gathering", #"Order ID" = 1152],
					        [#"Returned" = "christ", #"Order ID" = 5542],
					        [#"Returned" = "meaning", #"Order ID" = 6842],
					        [#"Returned" = "provisions", #"Order ID" = 9172],
					        [#"Returned" = "clubs", #"Order ID" = 9572],
					        [#"Returned" = "jewelry", #"Order ID" = 5165],
					        [#"Returned" = "bio", #"Order ID" = 5590],
					        [#"Returned" = "pregnant", #"Order ID" = 7732],
					        [#"Returned" = "threads", #"Order ID" = 4978],
					        [#"Returned" = "major", #"Order ID" = 3639],
					        [#"Returned" = "contacts", #"Order ID" = 8394],
					        [#"Returned" = "affiliates", #"Order ID" = 8357],
					        [#"Returned" = "premier", #"Order ID" = 1136],
					        [#"Returned" = "flows", #"Order ID" = 4124],
					        [#"Returned" = "republican", #"Order ID" = 6408],
					        [#"Returned" = "jerry", #"Order ID" = 2160],
					        [#"Returned" = "supplies", #"Order ID" = 7138],
					        [#"Returned" = "simply", #"Order ID" = 6309],
					        [#"Returned" = "inquiry", #"Order ID" = 1726],
					        [#"Returned" = "ontario", #"Order ID" = 2214],
					        [#"Returned" = "noble", #"Order ID" = 9225],
					        [#"Returned" = "nhl", #"Order ID" = 3690],
					        [#"Returned" = "tabs", #"Order ID" = 7362],
					        [#"Returned" = "support", #"Order ID" = 9534],
					        [#"Returned" = "ranking", #"Order ID" = 3769],
					        [#"Returned" = "root", #"Order ID" = 9658],
					        [#"Returned" = "urw", #"Order ID" = 1846],
					        [#"Returned" = "regulation", #"Order ID" = 6709],
					        [#"Returned" = "hosted", #"Order ID" = 9038],
					        [#"Returned" = "television", #"Order ID" = 1795],
					        [#"Returned" = "vacations", #"Order ID" = 2007],
					        [#"Returned" = "springs", #"Order ID" = 9475],
					        [#"Returned" = "topic", #"Order ID" = 7212],
					        [#"Returned" = "questions", #"Order ID" = 1607],
					        [#"Returned" = "tiny", #"Order ID" = 3156],
					        [#"Returned" = "vacations", #"Order ID" = 5499],
					        [#"Returned" = "folk", #"Order ID" = 7952],
					        [#"Returned" = "partners", #"Order ID" = 3734],
					        [#"Returned" = "train", #"Order ID" = 4457],
					        [#"Returned" = "biz", #"Order ID" = 4829],
					        [#"Returned" = "than", #"Order ID" = 4641],
					        [#"Returned" = "concerned", #"Order ID" = 4079],
					        [#"Returned" = "experimental", #"Order ID" = 2516],
					        [#"Returned" = "fan", #"Order ID" = 4555],
					        [#"Returned" = "murder", #"Order ID" = 3461],
					        [#"Returned" = "showing", #"Order ID" = 1650],
					        [#"Returned" = "ready", #"Order ID" = 4864],
					        [#"Returned" = "cake", #"Order ID" = 4309],
					        [#"Returned" = "smooth", #"Order ID" = 6593],
					        [#"Returned" = "change", #"Order ID" = 3560],
					        [#"Returned" = "memorabilia", #"Order ID" = 9623],
					        [#"Returned" = "webcam", #"Order ID" = 9688],
					        [#"Returned" = "work", #"Order ID" = 5575],
					        [#"Returned" = "pension", #"Order ID" = 7071],
					        [#"Returned" = "vacations", #"Order ID" = 3343],
					        [#"Returned" = "organic", #"Order ID" = 4397],
					        [#"Returned" = "into", #"Order ID" = 6905],
					        [#"Returned" = "senior", #"Order ID" = 9552],
					        [#"Returned" = "cities", #"Order ID" = 2645],
					        [#"Returned" = "elements", #"Order ID" = 6094],
					        [#"Returned" = "email", #"Order ID" = 2719],
					        [#"Returned" = "issued", #"Order ID" = 3697],
					        [#"Returned" = "proposal", #"Order ID" = 3541],
					        [#"Returned" = "tm", #"Order ID" = 8909],
					        [#"Returned" = "feet", #"Order ID" = 3872],
					        [#"Returned" = "variables", #"Order ID" = 1813],
					        [#"Returned" = "bears", #"Order ID" = 6047],
					        [#"Returned" = "ongoing", #"Order ID" = 2726],
					        [#"Returned" = "michelle", #"Order ID" = 1638],
					        [#"Returned" = "director", #"Order ID" = 9903],
					        [#"Returned" = "reporter", #"Order ID" = 3725],
					        [#"Returned" = "permit", #"Order ID" = 7308],
					        [#"Returned" = "ice", #"Order ID" = 4658],
					        [#"Returned" = "historic", #"Order ID" = 5414],
					        [#"Returned" = "currently", #"Order ID" = 4679],
					        [#"Returned" = "jim", #"Order ID" = 2540],
					        [#"Returned" = "trading", #"Order ID" = 5800],
					        [#"Returned" = "actor", #"Order ID" = 9526],
					        [#"Returned" = "hard", #"Order ID" = 2170],
					        [#"Returned" = "nc", #"Order ID" = 6582],
					        [#"Returned" = "remarks", #"Order ID" = 3227],
					        [#"Returned" = "va", #"Order ID" = 7575],
					        [#"Returned" = "forgot", #"Order ID" = 9743],
					        [#"Returned" = "jokes", #"Order ID" = 4640],
					        [#"Returned" = "motorola", #"Order ID" = 6058],
					        [#"Returned" = "june", #"Order ID" = 4659],
					        [#"Returned" = "conducted", #"Order ID" = 5952],
					        [#"Returned" = "pill", #"Order ID" = 7538],
					        [#"Returned" = "tried", #"Order ID" = 5698],
					        [#"Returned" = "warehouse", #"Order ID" = 9557],
					        [#"Returned" = "secret", #"Order ID" = 4311],
					        [#"Returned" = "registration", #"Order ID" = 8720],
					        [#"Returned" = "kong", #"Order ID" = 7827],
					        [#"Returned" = "en", #"Order ID" = 5207],
					        [#"Returned" = "interactive", #"Order ID" = 4790],
					        [#"Returned" = "named", #"Order ID" = 7020],
					        [#"Returned" = "movies", #"Order ID" = 7357],
					        [#"Returned" = "jan", #"Order ID" = 3411],
					        [#"Returned" = "painted", #"Order ID" = 9445],
					        [#"Returned" = "enter", #"Order ID" = 4520],
					        [#"Returned" = "declared", #"Order ID" = 9614],
					        [#"Returned" = "toolbar", #"Order ID" = 5407],
					        [#"Returned" = "vertical", #"Order ID" = 1195],
					        [#"Returned" = "avenue", #"Order ID" = 2907],
					        [#"Returned" = "compact", #"Order ID" = 4780],
					        [#"Returned" = "subsection", #"Order ID" = 9643],
					        [#"Returned" = "secured", #"Order ID" = 3617],
					        [#"Returned" = "died", #"Order ID" = 6527],
					        [#"Returned" = "listings", #"Order ID" = 5427],
					        [#"Returned" = "loss", #"Order ID" = 5970],
					        [#"Returned" = "president", #"Order ID" = 8139],
					        [#"Returned" = "officials", #"Order ID" = 1316],
					        [#"Returned" = "garage", #"Order ID" = 2620],
					        [#"Returned" = "lawyer", #"Order ID" = 8566],
					        [#"Returned" = "flowers", #"Order ID" = 1148],
					        [#"Returned" = "his", #"Order ID" = 5229],
					        [#"Returned" = "casinos", #"Order ID" = 1150],
					        [#"Returned" = "beef", #"Order ID" = 2383],
					        [#"Returned" = "usd", #"Order ID" = 6395],
					        [#"Returned" = "feedback", #"Order ID" = 8983],
					        [#"Returned" = "replace", #"Order ID" = 3019],
					        [#"Returned" = "laura", #"Order ID" = 4198],
					        [#"Returned" = "gp", #"Order ID" = 2926],
					        [#"Returned" = "airline", #"Order ID" = 6378],
					        [#"Returned" = "elementary", #"Order ID" = 9979],
					        [#"Returned" = "possibly", #"Order ID" = 4564],
					        [#"Returned" = "taiwan", #"Order ID" = 1160],
					        [#"Returned" = "blog", #"Order ID" = 9116],
					        [#"Returned" = "factors", #"Order ID" = 3836],
					        [#"Returned" = "drink", #"Order ID" = 4449],
					        [#"Returned" = "carpet", #"Order ID" = 2367],
					        [#"Returned" = "holes", #"Order ID" = 3568],
					        [#"Returned" = "launched", #"Order ID" = 3503],
					        [#"Returned" = "activity", #"Order ID" = 2393],
					        [#"Returned" = "fans", #"Order ID" = 2631],
					        [#"Returned" = "automotive", #"Order ID" = 5398],
					        [#"Returned" = "tons", #"Order ID" = 3116],
					        [#"Returned" = "wyoming", #"Order ID" = 4823],
					        [#"Returned" = "equity", #"Order ID" = 2418],
					        [#"Returned" = "widely", #"Order ID" = 2828],
					        [#"Returned" = "administrator", #"Order ID" = 3133],
					        [#"Returned" = "developed", #"Order ID" = 2981],
					        [#"Returned" = "dangerous", #"Order ID" = 3212],
					        [#"Returned" = "pharmaceutical", #"Order ID" = 3325],
					        [#"Returned" = "rail", #"Order ID" = 8288],
					        [#"Returned" = "groups", #"Order ID" = 5252],
					        [#"Returned" = "soldiers", #"Order ID" = 9139],
					        [#"Returned" = "charge", #"Order ID" = 7681],
					        [#"Returned" = "screening", #"Order ID" = 9763],
					        [#"Returned" = "submit", #"Order ID" = 9322],
					        [#"Returned" = "stay", #"Order ID" = 5072],
					        [#"Returned" = "cancer", #"Order ID" = 3758],
					        [#"Returned" = "jury", #"Order ID" = 9323],
					        [#"Returned" = "prefer", #"Order ID" = 1793],
					        [#"Returned" = "direct", #"Order ID" = 4699],
					        [#"Returned" = "could", #"Order ID" = 1774],
					        [#"Returned" = "substances", #"Order ID" = 4895],
					        [#"Returned" = "last", #"Order ID" = 6310],
					        [#"Returned" = "intent", #"Order ID" = 8968],
					        [#"Returned" = "legacy", #"Order ID" = 4800],
					        [#"Returned" = "guide", #"Order ID" = 5604],
					        [#"Returned" = "con", #"Order ID" = 1700],
					        [#"Returned" = "please", #"Order ID" = 4228],
					        [#"Returned" = "hispanic", #"Order ID" = 7082],
					        [#"Returned" = "skill", #"Order ID" = 6516],
					        [#"Returned" = "acid", #"Order ID" = 8775],
					        [#"Returned" = "saying", #"Order ID" = 9567],
					        [#"Returned" = "struggle", #"Order ID" = 2528],
					        [#"Returned" = "moreover", #"Order ID" = 1208],
					        [#"Returned" = "amber", #"Order ID" = 7902],
					        [#"Returned" = "examples", #"Order ID" = 6986],
					        [#"Returned" = "stock", #"Order ID" = 7301],
					        [#"Returned" = "zero", #"Order ID" = 8144],
					        [#"Returned" = "documentation", #"Order ID" = 1256],
					        [#"Returned" = "calling", #"Order ID" = 4464],
					        [#"Returned" = "complaint", #"Order ID" = 1088],
					        [#"Returned" = "cent", #"Order ID" = 9646],
					        [#"Returned" = "passion", #"Order ID" = 6574],
					        [#"Returned" = "italy", #"Order ID" = 3706],
					        [#"Returned" = "pg", #"Order ID" = 3359],
					        [#"Returned" = "contract", #"Order ID" = 8300],
					        [#"Returned" = "became", #"Order ID" = 5220],
					        [#"Returned" = "wishlist", #"Order ID" = 1130],
					        [#"Returned" = "theft", #"Order ID" = 4427],
					        [#"Returned" = "editions", #"Order ID" = 2704],
					        [#"Returned" = "ice", #"Order ID" = 2465],
					        [#"Returned" = "taxes", #"Order ID" = 5298],
					        [#"Returned" = "par", #"Order ID" = 2576],
					        [#"Returned" = "addressed", #"Order ID" = 7279],
					        [#"Returned" = "saint", #"Order ID" = 6027],
					        [#"Returned" = "canon", #"Order ID" = 8736],
					        [#"Returned" = "anything", #"Order ID" = 4174],
					        [#"Returned" = "vitamin", #"Order ID" = 5274],
					        [#"Returned" = "guest", #"Order ID" = 3314],
					        [#"Returned" = "judge", #"Order ID" = 4275],
					        [#"Returned" = "weird", #"Order ID" = 7698],
					        [#"Returned" = "dr", #"Order ID" = 3652],
					        [#"Returned" = "advisory", #"Order ID" = 6743],
					        [#"Returned" = "dawn", #"Order ID" = 4876],
					        [#"Returned" = "fit", #"Order ID" = 4780],
					        [#"Returned" = "priorities", #"Order ID" = 1796],
					        [#"Returned" = "upon", #"Order ID" = 3267],
					        [#"Returned" = "funded", #"Order ID" = 9713],
					        [#"Returned" = "directions", #"Order ID" = 4363],
					        [#"Returned" = "too", #"Order ID" = 8848],
					        [#"Returned" = "running", #"Order ID" = 7270],
					        [#"Returned" = "da", #"Order ID" = 4550],
					        [#"Returned" = "shows", #"Order ID" = 2136],
					        [#"Returned" = "oxford", #"Order ID" = 7867],
					        [#"Returned" = "enhance", #"Order ID" = 6167],
					        [#"Returned" = "maintaining", #"Order ID" = 3262],
					        [#"Returned" = "highlight", #"Order ID" = 4026],
					        [#"Returned" = "dark", #"Order ID" = 3292],
					        [#"Returned" = "interfaces", #"Order ID" = 7962],
					        [#"Returned" = "either", #"Order ID" = 8836],
					        [#"Returned" = "powers", #"Order ID" = 6146],
					        [#"Returned" = "extra", #"Order ID" = 8894],
					        [#"Returned" = "cause", #"Order ID" = 8976],
					        [#"Returned" = "consequences", #"Order ID" = 6194],
					        [#"Returned" = "bush", #"Order ID" = 7236],
					        [#"Returned" = "jerry", #"Order ID" = 2658],
					        [#"Returned" = "ban", #"Order ID" = 7265],
					        [#"Returned" = "disabled", #"Order ID" = 9414],
					        [#"Returned" = "vol", #"Order ID" = 3322],
					        [#"Returned" = "town", #"Order ID" = 8553],
					        [#"Returned" = "walter", #"Order ID" = 5242],
					        [#"Returned" = "build", #"Order ID" = 1876],
					        [#"Returned" = "under", #"Order ID" = 4842],
					        [#"Returned" = "activation", #"Order ID" = 8569],
					        [#"Returned" = "anarchist", #"Order ID" = 9869],
					        [#"Returned" = "bodies", #"Order ID" = 5072],
					        [#"Returned" = "london", #"Order ID" = 8607],
					        [#"Returned" = "bible", #"Order ID" = 9350],
					        [#"Returned" = "ent", #"Order ID" = 8557],
					        [#"Returned" = "au", #"Order ID" = 7339],
					        [#"Returned" = "theatre", #"Order ID" = 2184],
					        [#"Returned" = "california", #"Order ID" = 3442],
					        [#"Returned" = "hook", #"Order ID" = 4649],
					        [#"Returned" = "entire", #"Order ID" = 6602],
					        [#"Returned" = "supreme", #"Order ID" = 1101],
					        [#"Returned" = "others", #"Order ID" = 8343],
					        [#"Returned" = "losses", #"Order ID" = 7265],
					        [#"Returned" = "contemporary", #"Order ID" = 4021],
					        [#"Returned" = "scanner", #"Order ID" = 6923],
					        [#"Returned" = "de", #"Order ID" = 6120],
					        [#"Returned" = "partner", #"Order ID" = 4572],
					        [#"Returned" = "hospitals", #"Order ID" = 8807],
					        [#"Returned" = "crisis", #"Order ID" = 6347],
					        [#"Returned" = "period", #"Order ID" = 9387],
					        [#"Returned" = "nine", #"Order ID" = 3280],
					        [#"Returned" = "description", #"Order ID" = 8452],
					        [#"Returned" = "beds", #"Order ID" = 8103],
					        [#"Returned" = "animation", #"Order ID" = 3371],
					        [#"Returned" = "uk", #"Order ID" = 8989],
					        [#"Returned" = "postage", #"Order ID" = 6175],
					        [#"Returned" = "joe", #"Order ID" = 6059],
					        [#"Returned" = "tu", #"Order ID" = 9064],
					        [#"Returned" = "fisher", #"Order ID" = 3379],
					        [#"Returned" = "folder", #"Order ID" = 1475],
					        [#"Returned" = "shopping", #"Order ID" = 7537],
					        [#"Returned" = "timing", #"Order ID" = 6461],
					        [#"Returned" = "experiments", #"Order ID" = 3595],
					        [#"Returned" = "call", #"Order ID" = 2249],
					        [#"Returned" = "rose", #"Order ID" = 5800],
					        [#"Returned" = "ideal", #"Order ID" = 4610],
					        [#"Returned" = "second", #"Order ID" = 4990],
					        [#"Returned" = "asp", #"Order ID" = 3855],
					        [#"Returned" = "nike", #"Order ID" = 9045]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Returned", type text},
					        {"Order ID", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table