table online_tsne
	lineageTag: fb0dd07f-a1ff-454b-aa19-1e1e53d6cb3b

	column F1
		dataType: int64
		formatString: 0
		lineageTag: 97a645e2-c5a5-4326-bd3a-5257678db401
		summarizeBy: sum
		sourceColumn: F1

		annotation SummarizationSetBy = Automatic

	column 0
		dataType: double
		formatString: General Number
		lineageTag: 2d76eb14-3501-49a0-b620-608280bdb3a5
		summarizeBy: sum
		sourceColumn: 0

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 1
		dataType: double
		formatString: General Number
		lineageTag: a020c59d-f27a-4d69-8173-4f3183840f72
		summarizeBy: sum
		sourceColumn: 1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cluster
		dataType: int64
		formatString: 0
		lineageTag: 0481ecc7-ce4f-45b8-b438-fe9ea5c00b01
		summarizeBy: sum
		sourceColumn: Cluster

		annotation SummarizationSetBy = Automatic

	partition online_tsne = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"F1" = 828, #"0" = 785.1, #"1" = 987.26, #"Cluster" = 185],
					        [#"F1" = 849, #"0" = 933.0, #"1" = 856.6, #"Cluster" = 485],
					        [#"F1" = 355, #"0" = 454.22, #"1" = 598.26, #"Cluster" = 270],
					        [#"F1" = 608, #"0" = 758.13, #"1" = 595.9, #"Cluster" = 630],
					        [#"F1" = 396, #"0" = 873.98, #"1" = 772.48, #"Cluster" = 921],
					        [#"F1" = 85, #"0" = 462.6, #"1" = 532.49, #"Cluster" = 500],
					        [#"F1" = 527, #"0" = 363.55, #"1" = 354.47, #"Cluster" = 843],
					        [#"F1" = 70, #"0" = 119.83, #"1" = 661.02, #"Cluster" = 757],
					        [#"F1" = 149, #"0" = 469.11, #"1" = 595.71, #"Cluster" = 636],
					        [#"F1" = 514, #"0" = 243.77, #"1" = 652.36, #"Cluster" = 805],
					        [#"F1" = 566, #"0" = 305.07, #"1" = 617.44, #"Cluster" = 730],
					        [#"F1" = 436, #"0" = 766.9, #"1" = 100.12, #"Cluster" = 620],
					        [#"F1" = 539, #"0" = 787.46, #"1" = 15.06, #"Cluster" = 818],
					        [#"F1" = 58, #"0" = 859.11, #"1" = 740.17, #"Cluster" = 661],
					        [#"F1" = 989, #"0" = 308.77, #"1" = 92.74, #"Cluster" = 630],
					        [#"F1" = 473, #"0" = 242.61, #"1" = 812.54, #"Cluster" = 280],
					        [#"F1" = 201, #"0" = 451.85, #"1" = 883.55, #"Cluster" = 679],
					        [#"F1" = 229, #"0" = 682.71, #"1" = 179.9, #"Cluster" = 973],
					        [#"F1" = 100, #"0" = 577.72, #"1" = 795.77, #"Cluster" = 832],
					        [#"F1" = 335, #"0" = 450.6, #"1" = 890.33, #"Cluster" = 900],
					        [#"F1" = 368, #"0" = 712.01, #"1" = 636.11, #"Cluster" = 803],
					        [#"F1" = 843, #"0" = 41.52, #"1" = 395.72, #"Cluster" = 189],
					        [#"F1" = 351, #"0" = 513.84, #"1" = 497.69, #"Cluster" = 931],
					        [#"F1" = 100, #"0" = 457.6, #"1" = 577.47, #"Cluster" = 552],
					        [#"F1" = 36, #"0" = 929.29, #"1" = 246.26, #"Cluster" = 694],
					        [#"F1" = 360, #"0" = 174.75, #"1" = 688.52, #"Cluster" = 203],
					        [#"F1" = 402, #"0" = 520.21, #"1" = 636.04, #"Cluster" = 3],
					        [#"F1" = 148, #"0" = 314.98, #"1" = 666.0, #"Cluster" = 729],
					        [#"F1" = 592, #"0" = 953.5, #"1" = 499.62, #"Cluster" = 936],
					        [#"F1" = 39, #"0" = 507.51, #"1" = 329.91, #"Cluster" = 328],
					        [#"F1" = 849, #"0" = 765.73, #"1" = 159.3, #"Cluster" = 332],
					        [#"F1" = 278, #"0" = 573.43, #"1" = 444.16, #"Cluster" = 844],
					        [#"F1" = 573, #"0" = 231.96, #"1" = 1.63, #"Cluster" = 516],
					        [#"F1" = 834, #"0" = 526.69, #"1" = 190.33, #"Cluster" = 575],
					        [#"F1" = 783, #"0" = 968.8, #"1" = 385.8, #"Cluster" = 387],
					        [#"F1" = 991, #"0" = 587.01, #"1" = 944.66, #"Cluster" = 130],
					        [#"F1" = 303, #"0" = 807.88, #"1" = 147.25, #"Cluster" = 887],
					        [#"F1" = 865, #"0" = 656.58, #"1" = 534.88, #"Cluster" = 179],
					        [#"F1" = 64, #"0" = 184.63, #"1" = 262.31, #"Cluster" = 105],
					        [#"F1" = 511, #"0" = 664.49, #"1" = 913.11, #"Cluster" = 683],
					        [#"F1" = 289, #"0" = 532.85, #"1" = 608.19, #"Cluster" = 140],
					        [#"F1" = 622, #"0" = 702.36, #"1" = 797.12, #"Cluster" = 13],
					        [#"F1" = 172, #"0" = 323.27, #"1" = 396.32, #"Cluster" = 26],
					        [#"F1" = 24, #"0" = 167.26, #"1" = 164.08, #"Cluster" = 539],
					        [#"F1" = 991, #"0" = 448.48, #"1" = 129.87, #"Cluster" = 766],
					        [#"F1" = 419, #"0" = 560.53, #"1" = 0.2, #"Cluster" = 484],
					        [#"F1" = 477, #"0" = 730.36, #"1" = 411.68, #"Cluster" = 6],
					        [#"F1" = 384, #"0" = 220.39, #"1" = 382.87, #"Cluster" = 668],
					        [#"F1" = 120, #"0" = 52.81, #"1" = 545.79, #"Cluster" = 991],
					        [#"F1" = 644, #"0" = 589.49, #"1" = 721.39, #"Cluster" = 863],
					        [#"F1" = 932, #"0" = 770.53, #"1" = 334.24, #"Cluster" = 460],
					        [#"F1" = 666, #"0" = 304.94, #"1" = 347.63, #"Cluster" = 618],
					        [#"F1" = 559, #"0" = 510.32, #"1" = 460.99, #"Cluster" = 360],
					        [#"F1" = 870, #"0" = 584.67, #"1" = 494.42, #"Cluster" = 744],
					        [#"F1" = 954, #"0" = 570.71, #"1" = 73.61, #"Cluster" = 510],
					        [#"F1" = 679, #"0" = 134.15, #"1" = 510.12, #"Cluster" = 342],
					        [#"F1" = 257, #"0" = 708.42, #"1" = 979.14, #"Cluster" = 828],
					        [#"F1" = 692, #"0" = 591.71, #"1" = 672.26, #"Cluster" = 742],
					        [#"F1" = 219, #"0" = 710.52, #"1" = 665.42, #"Cluster" = 649],
					        [#"F1" = 697, #"0" = 103.25, #"1" = 596.01, #"Cluster" = 880],
					        [#"F1" = 467, #"0" = 783.03, #"1" = 947.43, #"Cluster" = 952],
					        [#"F1" = 495, #"0" = 828.74, #"1" = 256.88, #"Cluster" = 113],
					        [#"F1" = 45, #"0" = 581.43, #"1" = 561.28, #"Cluster" = 913],
					        [#"F1" = 253, #"0" = 292.98, #"1" = 282.02, #"Cluster" = 960],
					        [#"F1" = 977, #"0" = 68.89, #"1" = 963.73, #"Cluster" = 612],
					        [#"F1" = 294, #"0" = 975.11, #"1" = 144.51, #"Cluster" = 31],
					        [#"F1" = 467, #"0" = 520.23, #"1" = 272.41, #"Cluster" = 583],
					        [#"F1" = 671, #"0" = 117.94, #"1" = 504.01, #"Cluster" = 73],
					        [#"F1" = 250, #"0" = 669.04, #"1" = 874.57, #"Cluster" = 43],
					        [#"F1" = 375, #"0" = 702.1, #"1" = 429.47, #"Cluster" = 920],
					        [#"F1" = 792, #"0" = 492.26, #"1" = 695.1, #"Cluster" = 527],
					        [#"F1" = 803, #"0" = 761.36, #"1" = 628.02, #"Cluster" = 513],
					        [#"F1" = 382, #"0" = 323.34, #"1" = 590.37, #"Cluster" = 96],
					        [#"F1" = 693, #"0" = 43.6, #"1" = 44.99, #"Cluster" = 283],
					        [#"F1" = 663, #"0" = 979.69, #"1" = 578.34, #"Cluster" = 875],
					        [#"F1" = 865, #"0" = 902.37, #"1" = 684.28, #"Cluster" = 956],
					        [#"F1" = 603, #"0" = 464.61, #"1" = 941.48, #"Cluster" = 328],
					        [#"F1" = 977, #"0" = 826.14, #"1" = 983.85, #"Cluster" = 205],
					        [#"F1" = 435, #"0" = 362.38, #"1" = 544.02, #"Cluster" = 872],
					        [#"F1" = 726, #"0" = 315.8, #"1" = 622.94, #"Cluster" = 167],
					        [#"F1" = 183, #"0" = 191.4, #"1" = 47.47, #"Cluster" = 159],
					        [#"F1" = 426, #"0" = 715.5, #"1" = 20.19, #"Cluster" = 142],
					        [#"F1" = 646, #"0" = 107.82, #"1" = 288.1, #"Cluster" = 152],
					        [#"F1" = 199, #"0" = 589.43, #"1" = 315.48, #"Cluster" = 331],
					        [#"F1" = 137, #"0" = 230.9, #"1" = 598.59, #"Cluster" = 909],
					        [#"F1" = 789, #"0" = 221.87, #"1" = 306.93, #"Cluster" = 353],
					        [#"F1" = 953, #"0" = 754.72, #"1" = 331.42, #"Cluster" = 626],
					        [#"F1" = 326, #"0" = 151.43, #"1" = 793.85, #"Cluster" = 999],
					        [#"F1" = 337, #"0" = 460.63, #"1" = 568.26, #"Cluster" = 796],
					        [#"F1" = 210, #"0" = 575.27, #"1" = 418.58, #"Cluster" = 957],
					        [#"F1" = 648, #"0" = 113.11, #"1" = 643.81, #"Cluster" = 830],
					        [#"F1" = 880, #"0" = 456.81, #"1" = 871.28, #"Cluster" = 697],
					        [#"F1" = 508, #"0" = 505.46, #"1" = 78.48, #"Cluster" = 335],
					        [#"F1" = 920, #"0" = 217.74, #"1" = 599.55, #"Cluster" = 857],
					        [#"F1" = 537, #"0" = 991.6, #"1" = 184.15, #"Cluster" = 985],
					        [#"F1" = 209, #"0" = 211.32, #"1" = 381.66, #"Cluster" = 637],
					        [#"F1" = 593, #"0" = 409.83, #"1" = 683.29, #"Cluster" = 958],
					        [#"F1" = 331, #"0" = 526.35, #"1" = 857.23, #"Cluster" = 169],
					        [#"F1" = 877, #"0" = 744.35, #"1" = 585.22, #"Cluster" = 660],
					        [#"F1" = 285, #"0" = 493.47, #"1" = 252.97, #"Cluster" = 211],
					        [#"F1" = 720, #"0" = 971.04, #"1" = 416.84, #"Cluster" = 447],
					        [#"F1" = 557, #"0" = 965.09, #"1" = 320.37, #"Cluster" = 332],
					        [#"F1" = 168, #"0" = 48.52, #"1" = 257.78, #"Cluster" = 787],
					        [#"F1" = 599, #"0" = 550.25, #"1" = 800.97, #"Cluster" = 327],
					        [#"F1" = 430, #"0" = 40.52, #"1" = 410.36, #"Cluster" = 904],
					        [#"F1" = 221, #"0" = 957.31, #"1" = 395.43, #"Cluster" = 471],
					        [#"F1" = 940, #"0" = 808.55, #"1" = 123.33, #"Cluster" = 413],
					        [#"F1" = 386, #"0" = 221.85, #"1" = 10.47, #"Cluster" = 183],
					        [#"F1" = 676, #"0" = 213.78, #"1" = 547.99, #"Cluster" = 21],
					        [#"F1" = 86, #"0" = 765.91, #"1" = 267.45, #"Cluster" = 841],
					        [#"F1" = 628, #"0" = 140.1, #"1" = 176.78, #"Cluster" = 43],
					        [#"F1" = 384, #"0" = 501.79, #"1" = 262.74, #"Cluster" = 541],
					        [#"F1" = 651, #"0" = 407.1, #"1" = 833.3, #"Cluster" = 952],
					        [#"F1" = 473, #"0" = 192.2, #"1" = 534.71, #"Cluster" = 525],
					        [#"F1" = 471, #"0" = 845.07, #"1" = 111.45, #"Cluster" = 701],
					        [#"F1" = 270, #"0" = 68.69, #"1" = 13.13, #"Cluster" = 224],
					        [#"F1" = 609, #"0" = 535.47, #"1" = 610.86, #"Cluster" = 39],
					        [#"F1" = 410, #"0" = 541.59, #"1" = 25.6, #"Cluster" = 379],
					        [#"F1" = 551, #"0" = 50.77, #"1" = 976.0, #"Cluster" = 90],
					        [#"F1" = 251, #"0" = 592.52, #"1" = 0.08, #"Cluster" = 990],
					        [#"F1" = 956, #"0" = 951.7, #"1" = 136.46, #"Cluster" = 912],
					        [#"F1" = 281, #"0" = 580.73, #"1" = 714.06, #"Cluster" = 137],
					        [#"F1" = 967, #"0" = 48.18, #"1" = 76.36, #"Cluster" = 6],
					        [#"F1" = 939, #"0" = 151.07, #"1" = 459.28, #"Cluster" = 96],
					        [#"F1" = 145, #"0" = 711.29, #"1" = 244.69, #"Cluster" = 514],
					        [#"F1" = 954, #"0" = 150.16, #"1" = 262.61, #"Cluster" = 926],
					        [#"F1" = 596, #"0" = 20.03, #"1" = 318.17, #"Cluster" = 228],
					        [#"F1" = 804, #"0" = 599.74, #"1" = 593.83, #"Cluster" = 535],
					        [#"F1" = 89, #"0" = 504.98, #"1" = 661.6, #"Cluster" = 528],
					        [#"F1" = 93, #"0" = 728.34, #"1" = 584.23, #"Cluster" = 5],
					        [#"F1" = 502, #"0" = 637.08, #"1" = 700.56, #"Cluster" = 925],
					        [#"F1" = 886, #"0" = 378.74, #"1" = 383.14, #"Cluster" = 750],
					        [#"F1" = 734, #"0" = 934.22, #"1" = 741.3, #"Cluster" = 465],
					        [#"F1" = 356, #"0" = 126.5, #"1" = 220.6, #"Cluster" = 270],
					        [#"F1" = 211, #"0" = 424.11, #"1" = 831.3, #"Cluster" = 918],
					        [#"F1" = 961, #"0" = 949.9, #"1" = 932.68, #"Cluster" = 381],
					        [#"F1" = 480, #"0" = 901.27, #"1" = 250.28, #"Cluster" = 870],
					        [#"F1" = 403, #"0" = 691.13, #"1" = 478.44, #"Cluster" = 140],
					        [#"F1" = 421, #"0" = 570.42, #"1" = 891.3, #"Cluster" = 224],
					        [#"F1" = 735, #"0" = 369.52, #"1" = 973.33, #"Cluster" = 477],
					        [#"F1" = 638, #"0" = 344.1, #"1" = 260.18, #"Cluster" = 247],
					        [#"F1" = 539, #"0" = 687.41, #"1" = 678.44, #"Cluster" = 705],
					        [#"F1" = 345, #"0" = 582.37, #"1" = 732.16, #"Cluster" = 65],
					        [#"F1" = 858, #"0" = 581.85, #"1" = 325.05, #"Cluster" = 478],
					        [#"F1" = 581, #"0" = 787.3, #"1" = 871.92, #"Cluster" = 549],
					        [#"F1" = 996, #"0" = 922.47, #"1" = 164.89, #"Cluster" = 361],
					        [#"F1" = 260, #"0" = 365.44, #"1" = 287.95, #"Cluster" = 492],
					        [#"F1" = 62, #"0" = 595.41, #"1" = 571.63, #"Cluster" = 675],
					        [#"F1" = 434, #"0" = 917.38, #"1" = 954.72, #"Cluster" = 685],
					        [#"F1" = 954, #"0" = 295.35, #"1" = 904.58, #"Cluster" = 144],
					        [#"F1" = 996, #"0" = 223.81, #"1" = 98.36, #"Cluster" = 590],
					        [#"F1" = 1000, #"0" = 275.1, #"1" = 586.92, #"Cluster" = 481],
					        [#"F1" = 548, #"0" = 719.09, #"1" = 586.93, #"Cluster" = 720],
					        [#"F1" = 555, #"0" = 683.67, #"1" = 717.85, #"Cluster" = 862],
					        [#"F1" = 775, #"0" = 361.61, #"1" = 927.22, #"Cluster" = 171],
					        [#"F1" = 999, #"0" = 686.95, #"1" = 231.61, #"Cluster" = 441],
					        [#"F1" = 1, #"0" = 940.78, #"1" = 796.41, #"Cluster" = 132],
					        [#"F1" = 804, #"0" = 580.99, #"1" = 850.23, #"Cluster" = 666],
					        [#"F1" = 580, #"0" = 552.35, #"1" = 111.7, #"Cluster" = 56],
					        [#"F1" = 406, #"0" = 708.29, #"1" = 328.84, #"Cluster" = 541],
					        [#"F1" = 339, #"0" = 583.67, #"1" = 79.81, #"Cluster" = 750],
					        [#"F1" = 205, #"0" = 490.27, #"1" = 628.02, #"Cluster" = 1],
					        [#"F1" = 470, #"0" = 23.56, #"1" = 107.03, #"Cluster" = 779],
					        [#"F1" = 417, #"0" = 419.34, #"1" = 21.91, #"Cluster" = 26],
					        [#"F1" = 183, #"0" = 914.17, #"1" = 262.4, #"Cluster" = 413],
					        [#"F1" = 256, #"0" = 760.37, #"1" = 125.95, #"Cluster" = 134],
					        [#"F1" = 710, #"0" = 632.81, #"1" = 894.47, #"Cluster" = 27],
					        [#"F1" = 519, #"0" = 6.63, #"1" = 890.7, #"Cluster" = 409],
					        [#"F1" = 430, #"0" = 10.42, #"1" = 939.04, #"Cluster" = 796],
					        [#"F1" = 807, #"0" = 840.45, #"1" = 101.8, #"Cluster" = 663],
					        [#"F1" = 855, #"0" = 604.23, #"1" = 699.27, #"Cluster" = 369],
					        [#"F1" = 195, #"0" = 131.39, #"1" = 439.2, #"Cluster" = 614],
					        [#"F1" = 708, #"0" = 183.79, #"1" = 46.78, #"Cluster" = 75],
					        [#"F1" = 825, #"0" = 403.34, #"1" = 125.28, #"Cluster" = 577],
					        [#"F1" = 865, #"0" = 196.76, #"1" = 192.33, #"Cluster" = 534],
					        [#"F1" = 687, #"0" = 304.18, #"1" = 53.27, #"Cluster" = 117],
					        [#"F1" = 311, #"0" = 205.58, #"1" = 157.31, #"Cluster" = 436],
					        [#"F1" = 859, #"0" = 118.17, #"1" = 971.44, #"Cluster" = 422],
					        [#"F1" = 408, #"0" = 777.35, #"1" = 772.35, #"Cluster" = 623],
					        [#"F1" = 218, #"0" = 334.31, #"1" = 193.85, #"Cluster" = 769],
					        [#"F1" = 930, #"0" = 22.69, #"1" = 798.29, #"Cluster" = 257],
					        [#"F1" = 400, #"0" = 129.5, #"1" = 262.84, #"Cluster" = 802],
					        [#"F1" = 892, #"0" = 980.48, #"1" = 921.47, #"Cluster" = 676],
					        [#"F1" = 909, #"0" = 23.65, #"1" = 414.3, #"Cluster" = 117],
					        [#"F1" = 32, #"0" = 710.66, #"1" = 19.89, #"Cluster" = 387],
					        [#"F1" = 287, #"0" = 65.64, #"1" = 391.11, #"Cluster" = 82],
					        [#"F1" = 304, #"0" = 180.83, #"1" = 793.09, #"Cluster" = 955],
					        [#"F1" = 168, #"0" = 158.85, #"1" = 133.52, #"Cluster" = 625],
					        [#"F1" = 445, #"0" = 393.13, #"1" = 7.97, #"Cluster" = 684],
					        [#"F1" = 189, #"0" = 883.29, #"1" = 139.16, #"Cluster" = 551],
					        [#"F1" = 640, #"0" = 516.82, #"1" = 162.43, #"Cluster" = 189],
					        [#"F1" = 502, #"0" = 665.31, #"1" = 824.69, #"Cluster" = 31],
					        [#"F1" = 165, #"0" = 142.75, #"1" = 721.88, #"Cluster" = 439],
					        [#"F1" = 559, #"0" = 754.27, #"1" = 948.64, #"Cluster" = 636],
					        [#"F1" = 533, #"0" = 235.49, #"1" = 151.26, #"Cluster" = 512],
					        [#"F1" = 134, #"0" = 649.76, #"1" = 858.36, #"Cluster" = 935],
					        [#"F1" = 167, #"0" = 863.52, #"1" = 713.94, #"Cluster" = 37],
					        [#"F1" = 427, #"0" = 146.08, #"1" = 63.04, #"Cluster" = 569],
					        [#"F1" = 514, #"0" = 110.03, #"1" = 59.35, #"Cluster" = 744],
					        [#"F1" = 153, #"0" = 543.44, #"1" = 271.27, #"Cluster" = 906],
					        [#"F1" = 336, #"0" = 898.01, #"1" = 940.24, #"Cluster" = 447],
					        [#"F1" = 182, #"0" = 579.36, #"1" = 882.9, #"Cluster" = 120],
					        [#"F1" = 138, #"0" = 504.21, #"1" = 185.25, #"Cluster" = 763],
					        [#"F1" = 617, #"0" = 849.19, #"1" = 808.13, #"Cluster" = 188],
					        [#"F1" = 254, #"0" = 773.82, #"1" = 510.8, #"Cluster" = 696],
					        [#"F1" = 465, #"0" = 687.1, #"1" = 965.88, #"Cluster" = 929],
					        [#"F1" = 813, #"0" = 519.27, #"1" = 64.63, #"Cluster" = 655],
					        [#"F1" = 108, #"0" = 2.16, #"1" = 445.24, #"Cluster" = 166],
					        [#"F1" = 447, #"0" = 927.87, #"1" = 318.6, #"Cluster" = 635],
					        [#"F1" = 442, #"0" = 82.06, #"1" = 242.59, #"Cluster" = 540],
					        [#"F1" = 757, #"0" = 478.54, #"1" = 767.11, #"Cluster" = 291],
					        [#"F1" = 910, #"0" = 723.04, #"1" = 626.25, #"Cluster" = 686],
					        [#"F1" = 429, #"0" = 784.98, #"1" = 148.46, #"Cluster" = 389],
					        [#"F1" = 444, #"0" = 925.07, #"1" = 962.27, #"Cluster" = 591],
					        [#"F1" = 175, #"0" = 428.98, #"1" = 24.12, #"Cluster" = 932],
					        [#"F1" = 684, #"0" = 52.88, #"1" = 774.24, #"Cluster" = 405],
					        [#"F1" = 874, #"0" = 300.97, #"1" = 253.34, #"Cluster" = 718],
					        [#"F1" = 194, #"0" = 961.24, #"1" = 609.55, #"Cluster" = 421],
					        [#"F1" = 777, #"0" = 561.21, #"1" = 296.37, #"Cluster" = 321],
					        [#"F1" = 567, #"0" = 749.12, #"1" = 539.88, #"Cluster" = 213],
					        [#"F1" = 451, #"0" = 67.91, #"1" = 76.01, #"Cluster" = 292],
					        [#"F1" = 554, #"0" = 779.09, #"1" = 966.4, #"Cluster" = 486],
					        [#"F1" = 1, #"0" = 166.94, #"1" = 569.94, #"Cluster" = 264],
					        [#"F1" = 535, #"0" = 767.98, #"1" = 817.95, #"Cluster" = 967],
					        [#"F1" = 866, #"0" = 668.84, #"1" = 126.82, #"Cluster" = 51],
					        [#"F1" = 293, #"0" = 85.02, #"1" = 556.35, #"Cluster" = 768],
					        [#"F1" = 435, #"0" = 461.01, #"1" = 952.2, #"Cluster" = 812],
					        [#"F1" = 38, #"0" = 305.51, #"1" = 538.7, #"Cluster" = 114],
					        [#"F1" = 618, #"0" = 321.0, #"1" = 5.0, #"Cluster" = 583],
					        [#"F1" = 859, #"0" = 489.69, #"1" = 0.32, #"Cluster" = 541],
					        [#"F1" = 289, #"0" = 650.84, #"1" = 221.3, #"Cluster" = 8],
					        [#"F1" = 810, #"0" = 586.29, #"1" = 992.26, #"Cluster" = 596],
					        [#"F1" = 835, #"0" = 436.45, #"1" = 269.87, #"Cluster" = 913],
					        [#"F1" = 378, #"0" = 746.04, #"1" = 402.58, #"Cluster" = 905],
					        [#"F1" = 334, #"0" = 59.66, #"1" = 800.24, #"Cluster" = 929],
					        [#"F1" = 397, #"0" = 775.28, #"1" = 106.36, #"Cluster" = 653],
					        [#"F1" = 181, #"0" = 171.35, #"1" = 660.49, #"Cluster" = 109],
					        [#"F1" = 414, #"0" = 150.11, #"1" = 957.82, #"Cluster" = 489],
					        [#"F1" = 118, #"0" = 744.5, #"1" = 289.11, #"Cluster" = 193],
					        [#"F1" = 396, #"0" = 247.73, #"1" = 406.74, #"Cluster" = 14],
					        [#"F1" = 462, #"0" = 400.27, #"1" = 768.26, #"Cluster" = 350],
					        [#"F1" = 735, #"0" = 625.71, #"1" = 967.5, #"Cluster" = 638],
					        [#"F1" = 830, #"0" = 592.66, #"1" = 346.37, #"Cluster" = 858],
					        [#"F1" = 543, #"0" = 521.0, #"1" = 787.25, #"Cluster" = 583],
					        [#"F1" = 452, #"0" = 508.13, #"1" = 16.17, #"Cluster" = 94],
					        [#"F1" = 253, #"0" = 511.12, #"1" = 315.91, #"Cluster" = 936],
					        [#"F1" = 747, #"0" = 251.29, #"1" = 417.95, #"Cluster" = 818],
					        [#"F1" = 129, #"0" = 569.7, #"1" = 33.33, #"Cluster" = 348],
					        [#"F1" = 127, #"0" = 109.01, #"1" = 343.21, #"Cluster" = 872],
					        [#"F1" = 250, #"0" = 558.24, #"1" = 18.77, #"Cluster" = 572],
					        [#"F1" = 139, #"0" = 819.16, #"1" = 807.14, #"Cluster" = 939],
					        [#"F1" = 513, #"0" = 870.45, #"1" = 755.44, #"Cluster" = 719],
					        [#"F1" = 253, #"0" = 801.09, #"1" = 567.47, #"Cluster" = 177],
					        [#"F1" = 503, #"0" = 755.17, #"1" = 820.58, #"Cluster" = 333],
					        [#"F1" = 305, #"0" = 542.99, #"1" = 464.66, #"Cluster" = 862],
					        [#"F1" = 624, #"0" = 187.16, #"1" = 843.73, #"Cluster" = 94],
					        [#"F1" = 962, #"0" = 232.79, #"1" = 269.96, #"Cluster" = 214],
					        [#"F1" = 668, #"0" = 909.25, #"1" = 54.36, #"Cluster" = 472],
					        [#"F1" = 22, #"0" = 210.76, #"1" = 79.0, #"Cluster" = 284],
					        [#"F1" = 106, #"0" = 351.91, #"1" = 677.4, #"Cluster" = 406],
					        [#"F1" = 571, #"0" = 383.18, #"1" = 405.17, #"Cluster" = 433],
					        [#"F1" = 528, #"0" = 892.1, #"1" = 354.95, #"Cluster" = 825],
					        [#"F1" = 483, #"0" = 539.72, #"1" = 394.19, #"Cluster" = 449],
					        [#"F1" = 92, #"0" = 157.62, #"1" = 798.74, #"Cluster" = 86],
					        [#"F1" = 718, #"0" = 75.69, #"1" = 961.94, #"Cluster" = 999],
					        [#"F1" = 25, #"0" = 175.14, #"1" = 739.34, #"Cluster" = 742],
					        [#"F1" = 997, #"0" = 786.64, #"1" = 374.74, #"Cluster" = 451],
					        [#"F1" = 208, #"0" = 298.49, #"1" = 473.88, #"Cluster" = 520],
					        [#"F1" = 100, #"0" = 12.77, #"1" = 844.34, #"Cluster" = 152],
					        [#"F1" = 470, #"0" = 869.85, #"1" = 618.58, #"Cluster" = 179],
					        [#"F1" = 8, #"0" = 373.56, #"1" = 484.57, #"Cluster" = 837],
					        [#"F1" = 668, #"0" = 421.78, #"1" = 519.83, #"Cluster" = 435],
					        [#"F1" = 775, #"0" = 458.33, #"1" = 58.01, #"Cluster" = 352],
					        [#"F1" = 779, #"0" = 991.77, #"1" = 357.86, #"Cluster" = 681],
					        [#"F1" = 683, #"0" = 357.12, #"1" = 186.76, #"Cluster" = 71],
					        [#"F1" = 453, #"0" = 256.11, #"1" = 287.17, #"Cluster" = 405],
					        [#"F1" = 617, #"0" = 799.11, #"1" = 375.02, #"Cluster" = 248],
					        [#"F1" = 970, #"0" = 673.82, #"1" = 794.26, #"Cluster" = 811],
					        [#"F1" = 467, #"0" = 160.12, #"1" = 857.2, #"Cluster" = 928],
					        [#"F1" = 960, #"0" = 161.06, #"1" = 91.65, #"Cluster" = 522],
					        [#"F1" = 695, #"0" = 17.33, #"1" = 638.03, #"Cluster" = 991],
					        [#"F1" = 678, #"0" = 831.66, #"1" = 776.95, #"Cluster" = 952],
					        [#"F1" = 538, #"0" = 223.27, #"1" = 460.35, #"Cluster" = 95],
					        [#"F1" = 341, #"0" = 565.63, #"1" = 830.97, #"Cluster" = 630],
					        [#"F1" = 238, #"0" = 206.61, #"1" = 707.66, #"Cluster" = 345],
					        [#"F1" = 284, #"0" = 372.77, #"1" = 492.26, #"Cluster" = 860],
					        [#"F1" = 467, #"0" = 63.93, #"1" = 499.63, #"Cluster" = 388],
					        [#"F1" = 119, #"0" = 561.48, #"1" = 32.29, #"Cluster" = 70],
					        [#"F1" = 683, #"0" = 698.67, #"1" = 456.74, #"Cluster" = 371],
					        [#"F1" = 515, #"0" = 975.71, #"1" = 328.73, #"Cluster" = 506],
					        [#"F1" = 397, #"0" = 908.24, #"1" = 537.42, #"Cluster" = 794],
					        [#"F1" = 794, #"0" = 137.07, #"1" = 907.65, #"Cluster" = 912],
					        [#"F1" = 33, #"0" = 125.29, #"1" = 46.94, #"Cluster" = 110],
					        [#"F1" = 313, #"0" = 947.02, #"1" = 51.89, #"Cluster" = 68],
					        [#"F1" = 321, #"0" = 757.41, #"1" = 833.99, #"Cluster" = 52],
					        [#"F1" = 189, #"0" = 48.13, #"1" = 240.56, #"Cluster" = 38],
					        [#"F1" = 373, #"0" = 140.87, #"1" = 96.64, #"Cluster" = 480],
					        [#"F1" = 562, #"0" = 912.86, #"1" = 765.08, #"Cluster" = 860],
					        [#"F1" = 799, #"0" = 551.16, #"1" = 762.44, #"Cluster" = 496],
					        [#"F1" = 986, #"0" = 56.33, #"1" = 749.66, #"Cluster" = 199],
					        [#"F1" = 193, #"0" = 379.03, #"1" = 552.72, #"Cluster" = 911],
					        [#"F1" = 287, #"0" = 824.12, #"1" = 392.63, #"Cluster" = 870],
					        [#"F1" = 467, #"0" = 413.91, #"1" = 621.74, #"Cluster" = 493],
					        [#"F1" = 53, #"0" = 643.68, #"1" = 527.67, #"Cluster" = 24],
					        [#"F1" = 872, #"0" = 256.34, #"1" = 15.18, #"Cluster" = 162],
					        [#"F1" = 772, #"0" = 309.54, #"1" = 303.22, #"Cluster" = 411],
					        [#"F1" = 911, #"0" = 379.07, #"1" = 23.47, #"Cluster" = 384],
					        [#"F1" = 232, #"0" = 86.01, #"1" = 466.53, #"Cluster" = 791],
					        [#"F1" = 396, #"0" = 7.44, #"1" = 739.89, #"Cluster" = 378],
					        [#"F1" = 217, #"0" = 994.49, #"1" = 871.49, #"Cluster" = 619],
					        [#"F1" = 742, #"0" = 419.99, #"1" = 579.26, #"Cluster" = 436],
					        [#"F1" = 587, #"0" = 472.5, #"1" = 864.17, #"Cluster" = 793],
					        [#"F1" = 325, #"0" = 306.0, #"1" = 96.97, #"Cluster" = 894],
					        [#"F1" = 597, #"0" = 723.49, #"1" = 815.54, #"Cluster" = 651],
					        [#"F1" = 943, #"0" = 279.36, #"1" = 277.92, #"Cluster" = 521],
					        [#"F1" = 907, #"0" = 357.11, #"1" = 981.49, #"Cluster" = 880],
					        [#"F1" = 777, #"0" = 361.95, #"1" = 57.81, #"Cluster" = 318],
					        [#"F1" = 938, #"0" = 699.34, #"1" = 81.94, #"Cluster" = 731],
					        [#"F1" = 435, #"0" = 123.81, #"1" = 415.29, #"Cluster" = 542],
					        [#"F1" = 374, #"0" = 407.22, #"1" = 590.32, #"Cluster" = 785],
					        [#"F1" = 984, #"0" = 87.42, #"1" = 633.8, #"Cluster" = 866],
					        [#"F1" = 801, #"0" = 496.36, #"1" = 913.99, #"Cluster" = 943],
					        [#"F1" = 690, #"0" = 22.48, #"1" = 233.05, #"Cluster" = 271],
					        [#"F1" = 518, #"0" = 150.5, #"1" = 206.27, #"Cluster" = 892],
					        [#"F1" = 382, #"0" = 168.3, #"1" = 294.28, #"Cluster" = 639],
					        [#"F1" = 595, #"0" = 655.92, #"1" = 347.78, #"Cluster" = 6],
					        [#"F1" = 810, #"0" = 179.23, #"1" = 234.7, #"Cluster" = 850],
					        [#"F1" = 707, #"0" = 36.63, #"1" = 138.91, #"Cluster" = 325],
					        [#"F1" = 523, #"0" = 743.42, #"1" = 792.17, #"Cluster" = 763],
					        [#"F1" = 166, #"0" = 769.73, #"1" = 248.0, #"Cluster" = 629],
					        [#"F1" = 717, #"0" = 990.15, #"1" = 199.27, #"Cluster" = 35],
					        [#"F1" = 364, #"0" = 856.89, #"1" = 854.17, #"Cluster" = 479],
					        [#"F1" = 13, #"0" = 910.28, #"1" = 30.66, #"Cluster" = 215],
					        [#"F1" = 686, #"0" = 177.09, #"1" = 228.72, #"Cluster" = 867],
					        [#"F1" = 985, #"0" = 699.79, #"1" = 229.31, #"Cluster" = 879],
					        [#"F1" = 47, #"0" = 77.93, #"1" = 605.11, #"Cluster" = 918],
					        [#"F1" = 364, #"0" = 548.06, #"1" = 698.6, #"Cluster" = 511],
					        [#"F1" = 920, #"0" = 934.57, #"1" = 244.14, #"Cluster" = 965],
					        [#"F1" = 640, #"0" = 528.24, #"1" = 706.29, #"Cluster" = 712],
					        [#"F1" = 129, #"0" = 571.44, #"1" = 844.55, #"Cluster" = 519],
					        [#"F1" = 687, #"0" = 164.44, #"1" = 930.89, #"Cluster" = 23],
					        [#"F1" = 768, #"0" = 55.12, #"1" = 388.22, #"Cluster" = 652],
					        [#"F1" = 586, #"0" = 740.42, #"1" = 358.95, #"Cluster" = 425],
					        [#"F1" = 761, #"0" = 42.14, #"1" = 99.42, #"Cluster" = 471],
					        [#"F1" = 327, #"0" = 798.01, #"1" = 532.78, #"Cluster" = 783],
					        [#"F1" = 797, #"0" = 557.09, #"1" = 3.21, #"Cluster" = 565],
					        [#"F1" = 925, #"0" = 653.0, #"1" = 758.47, #"Cluster" = 307],
					        [#"F1" = 344, #"0" = 280.46, #"1" = 627.62, #"Cluster" = 712],
					        [#"F1" = 711, #"0" = 817.18, #"1" = 253.76, #"Cluster" = 909],
					        [#"F1" = 989, #"0" = 634.93, #"1" = 545.38, #"Cluster" = 971],
					        [#"F1" = 142, #"0" = 505.26, #"1" = 225.0, #"Cluster" = 39],
					        [#"F1" = 518, #"0" = 170.51, #"1" = 863.3, #"Cluster" = 542],
					        [#"F1" = 848, #"0" = 802.07, #"1" = 595.12, #"Cluster" = 934],
					        [#"F1" = 593, #"0" = 759.73, #"1" = 177.79, #"Cluster" = 383],
					        [#"F1" = 341, #"0" = 978.26, #"1" = 268.46, #"Cluster" = 915],
					        [#"F1" = 751, #"0" = 945.15, #"1" = 964.29, #"Cluster" = 840],
					        [#"F1" = 184, #"0" = 53.45, #"1" = 57.76, #"Cluster" = 711],
					        [#"F1" = 686, #"0" = 536.68, #"1" = 276.95, #"Cluster" = 359],
					        [#"F1" = 98, #"0" = 532.63, #"1" = 468.57, #"Cluster" = 807],
					        [#"F1" = 1000, #"0" = 728.69, #"1" = 344.75, #"Cluster" = 744],
					        [#"F1" = 8, #"0" = 325.35, #"1" = 288.28, #"Cluster" = 333],
					        [#"F1" = 857, #"0" = 613.9, #"1" = 74.52, #"Cluster" = 764],
					        [#"F1" = 679, #"0" = 738.95, #"1" = 628.61, #"Cluster" = 639],
					        [#"F1" = 940, #"0" = 668.17, #"1" = 825.19, #"Cluster" = 657],
					        [#"F1" = 628, #"0" = 141.65, #"1" = 541.49, #"Cluster" = 977],
					        [#"F1" = 127, #"0" = 789.21, #"1" = 977.5, #"Cluster" = 560],
					        [#"F1" = 619, #"0" = 301.68, #"1" = 61.72, #"Cluster" = 747],
					        [#"F1" = 414, #"0" = 390.25, #"1" = 995.17, #"Cluster" = 938],
					        [#"F1" = 673, #"0" = 258.42, #"1" = 151.55, #"Cluster" = 518],
					        [#"F1" = 356, #"0" = 683.95, #"1" = 784.27, #"Cluster" = 657],
					        [#"F1" = 135, #"0" = 55.19, #"1" = 791.88, #"Cluster" = 552],
					        [#"F1" = 792, #"0" = 56.31, #"1" = 721.85, #"Cluster" = 906],
					        [#"F1" = 389, #"0" = 752.69, #"1" = 0.66, #"Cluster" = 111],
					        [#"F1" = 792, #"0" = 0.33, #"1" = 193.24, #"Cluster" = 550],
					        [#"F1" = 189, #"0" = 708.6, #"1" = 865.24, #"Cluster" = 496],
					        [#"F1" = 143, #"0" = 462.18, #"1" = 5.45, #"Cluster" = 310],
					        [#"F1" = 318, #"0" = 760.16, #"1" = 89.01, #"Cluster" = 538],
					        [#"F1" = 454, #"0" = 265.46, #"1" = 870.31, #"Cluster" = 914],
					        [#"F1" = 317, #"0" = 678.21, #"1" = 603.82, #"Cluster" = 189],
					        [#"F1" = 399, #"0" = 991.7, #"1" = 902.99, #"Cluster" = 867],
					        [#"F1" = 91, #"0" = 294.19, #"1" = 741.06, #"Cluster" = 666],
					        [#"F1" = 594, #"0" = 249.46, #"1" = 421.76, #"Cluster" = 981],
					        [#"F1" = 391, #"0" = 983.57, #"1" = 337.23, #"Cluster" = 730],
					        [#"F1" = 816, #"0" = 489.23, #"1" = 643.63, #"Cluster" = 856],
					        [#"F1" = 353, #"0" = 689.67, #"1" = 765.32, #"Cluster" = 310],
					        [#"F1" = 638, #"0" = 375.95, #"1" = 331.04, #"Cluster" = 553],
					        [#"F1" = 1, #"0" = 710.96, #"1" = 763.42, #"Cluster" = 458],
					        [#"F1" = 257, #"0" = 568.15, #"1" = 186.84, #"Cluster" = 741],
					        [#"F1" = 294, #"0" = 646.82, #"1" = 236.56, #"Cluster" = 508],
					        [#"F1" = 748, #"0" = 616.62, #"1" = 919.46, #"Cluster" = 929],
					        [#"F1" = 798, #"0" = 957.65, #"1" = 408.26, #"Cluster" = 817],
					        [#"F1" = 497, #"0" = 997.45, #"1" = 781.07, #"Cluster" = 213],
					        [#"F1" = 858, #"0" = 666.93, #"1" = 454.49, #"Cluster" = 915],
					        [#"F1" = 888, #"0" = 460.47, #"1" = 647.52, #"Cluster" = 393],
					        [#"F1" = 188, #"0" = 620.28, #"1" = 193.02, #"Cluster" = 181],
					        [#"F1" = 759, #"0" = 405.96, #"1" = 820.35, #"Cluster" = 145],
					        [#"F1" = 242, #"0" = 652.1, #"1" = 368.24, #"Cluster" = 250],
					        [#"F1" = 135, #"0" = 658.52, #"1" = 921.02, #"Cluster" = 855],
					        [#"F1" = 419, #"0" = 218.11, #"1" = 326.0, #"Cluster" = 652],
					        [#"F1" = 863, #"0" = 259.6, #"1" = 858.39, #"Cluster" = 593],
					        [#"F1" = 32, #"0" = 871.65, #"1" = 600.04, #"Cluster" = 132],
					        [#"F1" = 227, #"0" = 999.27, #"1" = 809.78, #"Cluster" = 994],
					        [#"F1" = 17, #"0" = 5.44, #"1" = 71.31, #"Cluster" = 388],
					        [#"F1" = 380, #"0" = 888.92, #"1" = 995.98, #"Cluster" = 315],
					        [#"F1" = 573, #"0" = 228.69, #"1" = 8.9, #"Cluster" = 915],
					        [#"F1" = 682, #"0" = 631.66, #"1" = 659.64, #"Cluster" = 198],
					        [#"F1" = 412, #"0" = 5.29, #"1" = 609.15, #"Cluster" = 681],
					        [#"F1" = 655, #"0" = 50.85, #"1" = 582.22, #"Cluster" = 198],
					        [#"F1" = 794, #"0" = 88.21, #"1" = 13.31, #"Cluster" = 287],
					        [#"F1" = 982, #"0" = 623.06, #"1" = 13.99, #"Cluster" = 321],
					        [#"F1" = 618, #"0" = 736.87, #"1" = 421.02, #"Cluster" = 794],
					        [#"F1" = 672, #"0" = 775.54, #"1" = 106.69, #"Cluster" = 592],
					        [#"F1" = 525, #"0" = 984.31, #"1" = 136.99, #"Cluster" = 198],
					        [#"F1" = 451, #"0" = 906.14, #"1" = 16.54, #"Cluster" = 820],
					        [#"F1" = 717, #"0" = 293.12, #"1" = 235.1, #"Cluster" = 157],
					        [#"F1" = 939, #"0" = 442.94, #"1" = 24.1, #"Cluster" = 678],
					        [#"F1" = 354, #"0" = 516.53, #"1" = 893.71, #"Cluster" = 362],
					        [#"F1" = 791, #"0" = 186.8, #"1" = 694.34, #"Cluster" = 255],
					        [#"F1" = 984, #"0" = 857.81, #"1" = 479.7, #"Cluster" = 619],
					        [#"F1" = 730, #"0" = 642.15, #"1" = 654.52, #"Cluster" = 905],
					        [#"F1" = 370, #"0" = 890.5, #"1" = 783.11, #"Cluster" = 311],
					        [#"F1" = 716, #"0" = 92.96, #"1" = 310.46, #"Cluster" = 765],
					        [#"F1" = 461, #"0" = 685.0, #"1" = 267.62, #"Cluster" = 588],
					        [#"F1" = 330, #"0" = 610.71, #"1" = 567.15, #"Cluster" = 13],
					        [#"F1" = 662, #"0" = 815.25, #"1" = 253.95, #"Cluster" = 283],
					        [#"F1" = 504, #"0" = 30.53, #"1" = 551.77, #"Cluster" = 874],
					        [#"F1" = 319, #"0" = 669.92, #"1" = 225.1, #"Cluster" = 230],
					        [#"F1" = 427, #"0" = 654.54, #"1" = 301.95, #"Cluster" = 488],
					        [#"F1" = 627, #"0" = 695.94, #"1" = 58.8, #"Cluster" = 17],
					        [#"F1" = 759, #"0" = 840.14, #"1" = 868.44, #"Cluster" = 544],
					        [#"F1" = 363, #"0" = 791.34, #"1" = 285.36, #"Cluster" = 271],
					        [#"F1" = 400, #"0" = 955.82, #"1" = 540.47, #"Cluster" = 65],
					        [#"F1" = 522, #"0" = 402.9, #"1" = 741.16, #"Cluster" = 553],
					        [#"F1" = 132, #"0" = 33.65, #"1" = 111.03, #"Cluster" = 177],
					        [#"F1" = 210, #"0" = 248.62, #"1" = 247.21, #"Cluster" = 996],
					        [#"F1" = 584, #"0" = 659.12, #"1" = 797.42, #"Cluster" = 112],
					        [#"F1" = 668, #"0" = 600.52, #"1" = 189.7, #"Cluster" = 123],
					        [#"F1" = 801, #"0" = 932.42, #"1" = 935.82, #"Cluster" = 564],
					        [#"F1" = 971, #"0" = 731.08, #"1" = 354.94, #"Cluster" = 362],
					        [#"F1" = 536, #"0" = 266.04, #"1" = 120.26, #"Cluster" = 202],
					        [#"F1" = 373, #"0" = 759.07, #"1" = 261.56, #"Cluster" = 752],
					        [#"F1" = 751, #"0" = 132.94, #"1" = 120.99, #"Cluster" = 896],
					        [#"F1" = 758, #"0" = 852.09, #"1" = 937.39, #"Cluster" = 748],
					        [#"F1" = 405, #"0" = 617.85, #"1" = 407.49, #"Cluster" = 601],
					        [#"F1" = 642, #"0" = 234.69, #"1" = 338.87, #"Cluster" = 740],
					        [#"F1" = 497, #"0" = 808.94, #"1" = 853.66, #"Cluster" = 221],
					        [#"F1" = 828, #"0" = 137.0, #"1" = 983.41, #"Cluster" = 343],
					        [#"F1" = 55, #"0" = 343.8, #"1" = 704.94, #"Cluster" = 670],
					        [#"F1" = 518, #"0" = 929.55, #"1" = 852.35, #"Cluster" = 820],
					        [#"F1" = 956, #"0" = 501.49, #"1" = 998.7, #"Cluster" = 946],
					        [#"F1" = 884, #"0" = 151.26, #"1" = 849.64, #"Cluster" = 487],
					        [#"F1" = 790, #"0" = 17.52, #"1" = 475.79, #"Cluster" = 116],
					        [#"F1" = 592, #"0" = 255.01, #"1" = 684.89, #"Cluster" = 301],
					        [#"F1" = 610, #"0" = 914.15, #"1" = 798.16, #"Cluster" = 923],
					        [#"F1" = 200, #"0" = 585.22, #"1" = 936.72, #"Cluster" = 979],
					        [#"F1" = 447, #"0" = 24.66, #"1" = 475.23, #"Cluster" = 197],
					        [#"F1" = 512, #"0" = 594.2, #"1" = 438.69, #"Cluster" = 80],
					        [#"F1" = 879, #"0" = 642.18, #"1" = 375.38, #"Cluster" = 60],
					        [#"F1" = 379, #"0" = 267.13, #"1" = 861.26, #"Cluster" = 600],
					        [#"F1" = 403, #"0" = 293.42, #"1" = 445.32, #"Cluster" = 30],
					        [#"F1" = 357, #"0" = 585.65, #"1" = 368.54, #"Cluster" = 297],
					        [#"F1" = 776, #"0" = 668.25, #"1" = 640.65, #"Cluster" = 265],
					        [#"F1" = 128, #"0" = 711.28, #"1" = 212.01, #"Cluster" = 540],
					        [#"F1" = 310, #"0" = 338.89, #"1" = 446.51, #"Cluster" = 633],
					        [#"F1" = 68, #"0" = 990.78, #"1" = 169.26, #"Cluster" = 960],
					        [#"F1" = 764, #"0" = 332.86, #"1" = 387.23, #"Cluster" = 541],
					        [#"F1" = 864, #"0" = 634.86, #"1" = 145.62, #"Cluster" = 84],
					        [#"F1" = 361, #"0" = 230.22, #"1" = 109.76, #"Cluster" = 14],
					        [#"F1" = 832, #"0" = 258.37, #"1" = 943.28, #"Cluster" = 139],
					        [#"F1" = 281, #"0" = 723.97, #"1" = 367.85, #"Cluster" = 116],
					        [#"F1" = 366, #"0" = 476.16, #"1" = 902.73, #"Cluster" = 560],
					        [#"F1" = 276, #"0" = 257.31, #"1" = 36.76, #"Cluster" = 93],
					        [#"F1" = 304, #"0" = 434.51, #"1" = 703.03, #"Cluster" = 7],
					        [#"F1" = 981, #"0" = 133.28, #"1" = 800.22, #"Cluster" = 654],
					        [#"F1" = 18, #"0" = 573.49, #"1" = 165.2, #"Cluster" = 680],
					        [#"F1" = 515, #"0" = 339.21, #"1" = 436.8, #"Cluster" = 142],
					        [#"F1" = 666, #"0" = 197.47, #"1" = 77.32, #"Cluster" = 805],
					        [#"F1" = 899, #"0" = 163.03, #"1" = 377.25, #"Cluster" = 418],
					        [#"F1" = 574, #"0" = 935.03, #"1" = 434.32, #"Cluster" = 701],
					        [#"F1" = 105, #"0" = 723.39, #"1" = 479.19, #"Cluster" = 652],
					        [#"F1" = 246, #"0" = 665.33, #"1" = 821.32, #"Cluster" = 666],
					        [#"F1" = 80, #"0" = 593.85, #"1" = 589.52, #"Cluster" = 909],
					        [#"F1" = 760, #"0" = 480.59, #"1" = 840.24, #"Cluster" = 131],
					        [#"F1" = 847, #"0" = 505.25, #"1" = 189.62, #"Cluster" = 879],
					        [#"F1" = 922, #"0" = 400.43, #"1" = 584.26, #"Cluster" = 639],
					        [#"F1" = 754, #"0" = 881.06, #"1" = 707.04, #"Cluster" = 258],
					        [#"F1" = 35, #"0" = 883.59, #"1" = 611.28, #"Cluster" = 454],
					        [#"F1" = 351, #"0" = 943.99, #"1" = 559.8, #"Cluster" = 425],
					        [#"F1" = 518, #"0" = 834.19, #"1" = 452.83, #"Cluster" = 952],
					        [#"F1" = 388, #"0" = 63.97, #"1" = 45.02, #"Cluster" = 17],
					        [#"F1" = 693, #"0" = 733.24, #"1" = 906.61, #"Cluster" = 233],
					        [#"F1" = 167, #"0" = 258.63, #"1" = 329.37, #"Cluster" = 13],
					        [#"F1" = 257, #"0" = 889.19, #"1" = 338.54, #"Cluster" = 773],
					        [#"F1" = 955, #"0" = 497.16, #"1" = 782.4, #"Cluster" = 598],
					        [#"F1" = 982, #"0" = 541.92, #"1" = 802.64, #"Cluster" = 691],
					        [#"F1" = 161, #"0" = 22.2, #"1" = 709.32, #"Cluster" = 340],
					        [#"F1" = 722, #"0" = 441.52, #"1" = 520.79, #"Cluster" = 858],
					        [#"F1" = 962, #"0" = 438.41, #"1" = 502.03, #"Cluster" = 411],
					        [#"F1" = 570, #"0" = 83.14, #"1" = 910.75, #"Cluster" = 388],
					        [#"F1" = 673, #"0" = 238.17, #"1" = 551.87, #"Cluster" = 264]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"F1", Int64.Type},
					        {"0", type number},
					        {"1", type number},
					        {"Cluster", Int64.Type}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table