table Query1
	lineageTag: 4bb99b51-b4c7-468c-9845-d2957bb79f54

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 86d49d7e-4091-4b7f-b897-e54442bf6fd3
		summarizeBy: sum
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 826c6681-2e71-45cb-a02a-60d7d470a699
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Salary
		dataType: int64
		formatString: 0
		lineageTag: fcdf4b83-2c9c-4da7-a8e0-988b19fec526
		summarizeBy: sum
		sourceColumn: Salary

		annotation SummarizationSetBy = Automatic

	partition Query1 = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [ID = 5749, Name = "Jerold Benjamin", Salary = 603],
					        [ID = 2093, Name = "Alethea Randolph", Salary = 790],
					        [ID = 1474, Name = "Joselyn Hewitt", Salary = 217],
					        [ID = 8582, Name = "Shawana Rowland", Salary = 83],
					        [ID = 5661, Name = "Lavern Alford", Salary = 343]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"ID", Int64.Type},
					        {"Name", type text},
					        {"Salary", Int64.Type}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table