table 'Top Customers'
	lineageTag: 0c80e46e-077d-43a1-a610-4daf7e4daa46

	measure 'Top Customers Value' = SELECTEDVALUE('Top Customers'[Top Customers], 5)
		lineageTag: 6e14c6db-b980-4aaf-b6bb-a2663860223f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Top Customers'
		dataType: double
		formatString: 0
		lineageTag: 50e70c24-505e-49b9-94a3-8ec2a92e1be7
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Top Customers' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_Id = 9733234d433a417fbacf1f7a8be680f4

