table 'Sheet1+ (Multiple Connections)'
	lineageTag: 6ce2e9b6-e8b3-4a50-9e1a-2f8d575fa420

	column 'Campaign ID'
		dataType: string
		lineageTag: 61857f5d-17b0-4d51-87c6-18f29d81ff0f
		summarizeBy: none
		sourceColumn: 'Campaign ID'

		annotation SummarizationSetBy = Automatic

	column 'Campaign Name'
		dataType: string
		lineageTag: 4fa0040c-ae19-4be5-83f8-e65226150fc3
		summarizeBy: none
		sourceColumn: 'Campaign Name'

		annotation SummarizationSetBy = Automatic

	column 'Start Date'
		dataType: string
		lineageTag: d6000cd4-89b6-476d-a794-9520c521e3f5
		summarizeBy: none
		sourceColumn: 'Start Date'

		annotation SummarizationSetBy = Automatic

	column 'End Date'
		dataType: string
		lineageTag: bcbf4bd1-7337-438a-9749-87d1280c86a5
		summarizeBy: none
		sourceColumn: 'End Date'

		annotation SummarizationSetBy = Automatic

	column Platform
		dataType: string
		lineageTag: 4836ac36-2b22-4494-87ef-2849db5c2d18
		summarizeBy: none
		sourceColumn: Platform

		annotation SummarizationSetBy = Automatic

	column Budget
		dataType: int64
		formatString: 0
		lineageTag: c7fed663-7fb8-4942-8fd2-8f523dfc307d
		summarizeBy: sum
		sourceColumn: Budget

		annotation SummarizationSetBy = Automatic

	column Spend
		dataType: int64
		formatString: 0
		lineageTag: 8e80e121-a020-4ede-9b79-cfc05ca171e9
		summarizeBy: sum
		sourceColumn: Spend

		annotation SummarizationSetBy = Automatic

	column Impressions
		dataType: int64
		formatString: 0
		lineageTag: 5273c5ce-b5d1-4519-b584-e25d701a62fb
		summarizeBy: sum
		sourceColumn: Impressions

		annotation SummarizationSetBy = Automatic

	column Clicks
		dataType: int64
		formatString: 0
		lineageTag: 654c4f1e-45b9-4e03-b18c-1ce5efba3877
		summarizeBy: sum
		sourceColumn: Clicks

		annotation SummarizationSetBy = Automatic

	column Conversions
		dataType: int64
		formatString: 0
		lineageTag: 80417089-947c-4320-955a-1a617176b081
		summarizeBy: sum
		sourceColumn: Conversions

		annotation SummarizationSetBy = Automatic

	column 'Campaign ID 1'
		dataType: string
		lineageTag: 5021bc33-60a8-4b84-9408-a875d7ed3b0a
		summarizeBy: none
		sourceColumn: 'Campaign ID 1'

		annotation SummarizationSetBy = Automatic

	column 'Target Audience'
		dataType: string
		lineageTag: 9502cbd3-3965-431f-a6f6-266d571e5695
		summarizeBy: none
		sourceColumn: 'Target Audience'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 22c70c39-7271-409c-b72b-2ca04c79323c
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Audience Size'
		dataType: int64
		formatString: 0
		lineageTag: a5159904-79e6-4e1c-99ee-57ef09a620f8
		summarizeBy: sum
		sourceColumn: 'Audience Size'

		annotation SummarizationSetBy = Automatic

	column 'Gender Focus'
		dataType: string
		lineageTag: 3a9e36b5-e650-4776-ab6f-e882b56ebf60
		summarizeBy: none
		sourceColumn: 'Gender Focus'

		annotation SummarizationSetBy = Automatic

	partition 'Sheet1+ (Multiple Connections)' = m
		mode: import
		source =
				let 
					#"Source0" = Table.NestedJoin(#"Sheet1_Sheet1+ (Multiple Connections)", {"Campaign ID"}, #"campaign_audience_data.csv_Sheet1+ (Multiple Connections)", {"Campaign ID"}, "campaign_audience_data.csv_Sheet1+ (Multiple Connections)", JoinKind.Inner),
					#"Expand0" = Table.ExpandTableColumn(#"Source0", "campaign_audience_data.csv_Sheet1+ (Multiple Connections)", {"Campaign ID", "Target Audience", "Region", "Audience Size", "Gender Focus"}, {"Campaign ID 1", "Target Audience", "Region", "Audience Size", "Gender Focus"})
					in #"Expand0"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table