table 'Min Profit Display'
	lineageTag: 2fdbb37c-58f6-4ea4-bd48-49bfb5d5cb43

	measure 'Min Profit Display Value' = SELECTEDVALUE('Min Profit Display'[Min Profit Display], -500)
		lineageTag: 8e389c19-1c38-45ff-a63a-087ecc0648c0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Min Profit Display'
		dataType: double
		formatString: 0
		lineageTag: 6193caa8-c27b-427d-a053-1774d9e80b52
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Min Profit Display' = calculated
		mode: import
		source = GENERATESERIES(-500, 500)

	annotation PBI_Id = bb641292bf554aa5bee3f511308064dc

