table 'Orders+ (Sample - Superstore)'
	lineageTag: cddc9e8b-8bb8-4c2c-a8a4-ab4e8fdd6a07

	measure 'Profit Visibility' = IF(SUM('Orders+ (Sample - Superstore)'[Profit]) >= SELECTEDVALUE('Min Profit Display'[Display As]), "Show", "Hide")
		lineageTag: 4f8206a2-7468-422d-ad5d-8da0171de34a

	measure 'Total Sales' = SUM('Orders+ (Sample - Superstore)'[Sales])
		formatString: 0
		lineageTag: ec8797fb-90b0-4c85-be6d-c7c71431634c

	measure 'Total Profit' = SUM('Orders+ (Sample - Superstore)'[Profit])
		formatString: 0
		lineageTag: 3521b559-23c5-4ed8-acb5-343b9a706ca5

	measure 'Profit Ratio' = DIVIDE(SUM('Orders+ (Sample - Superstore)'[Profit]), SUM('Orders+ (Sample - Superstore)'[Sales]))
		formatString: 0
		lineageTag: 7e9bf126-5df7-44da-a998-40f5ca03daca

	measure 'Normalized Profit Ratio (%)' = 'Orders+ (Sample - Superstore)'[Profit Ratio] * 100
		formatString: 0
		lineageTag: f3366dc3-8c3b-442e-96b8-99e05a7c6926

	measure 'Sales After Discount' = SUM('Orders+ (Sample - Superstore)'[Sales]) * (1 - AVERAGE('Orders+ (Sample - Superstore)'[Discount]))
		formatString: 0
		lineageTag: 7c5198fa-c704-47f3-97b5-76cec8de792e

	measure 'Customer Total Sales (LOD)' = VAR CustomerTotal = CALCULATE( SUM('Orders+ (Sample - Superstore)'[Sales]), ALLEXCEPT('Orders+ (Sample - Superstore)', 'Orders+ (Sample - Superstore)'[Customer ID]) ) RETURN CustomerTotal
		formatString: 0
		lineageTag: a7955b53-18e9-4599-a0a9-e92370f1a2cf

	measure 'Region Average Profit (LOD)' = VAR RegionAvg = CALCULATE( AVERAGE('Orders+ (Sample - Superstore)'[Profit]), ALLEXCEPT('Orders+ (Sample - Superstore)', 'Orders+ (Sample - Superstore)'[Region]) ) RETURN RegionAvg
		formatString: 0
		lineageTag: 86c7072d-5778-4643-bd10-b02f249ad264

	measure 'Order Level Sales (LOD)' = VAR __result = CALCULATE( SUM('Orders+ (Sample - Superstore)'[Sales]), ALLEXCEPT('Orders+ (Sample - Superstore)', 'Orders+ (Sample - Superstore)'[Order ID]) ) RETURN __result
		formatString: 0
		lineageTag: f448bfa5-a6b5-4ff4-a164-1c8cb965c921

	measure 'Running Sales' = VAR CurrentSales = SUM('Orders+ (Sample - Superstore)'[Sales]) VAR RunningSales = SUMX( FILTER( ALLSELECTED('Orders+ (Sample - Superstore)'), 'Orders+ (Sample - Superstore)'[Sales] <= CurrentSales ), 'Orders+ (Sample - Superstore)'[Sales] ) RETURN RunningSales
		formatString: 0
		lineageTag: d623bb2d-2f4f-4020-93e2-c8462b7cf01c

	measure '% of Total Sales' = DIVIDE( SUM('Orders+ (Sample - Superstore)'[Sales]), CALCULATE( SUM('Orders+ (Sample - Superstore)'[Sales]), ALLSELECTED('Orders+ (Sample - Superstore)') ) )
		formatString: 0
		lineageTag: 893034ad-f6df-42f0-b6e4-359e1fa38294

	measure Calculation2 = VAR result = CALCULATE( MINX( VALUES('Orders+ (Sample - Superstore)'[Order Date]), YEAR('Orders+ (Sample - Superstore)'[Order Date]) ), ALLEXCEPT('Orders+ (Sample - Superstore)', 'Orders+ (Sample - Superstore)'[Customer ID]) ) RETURN result
		formatString: 0
		lineageTag: 2129f630-64c3-4f21-b24e-5ce96204d5af

	measure Calculation3 = VAR CurrentSales = SUM('Orders+ (Sample - Superstore)'[Sales]) VAR WindowTable = TOPN( 3, FILTER( ALLSELECTED('Orders+ (Sample - Superstore)'), 'Orders+ (Sample - Superstore)'[Sales] <= CurrentSales ), 'Orders+ (Sample - Superstore)'[Sales], DESC ) RETURN AVERAGEX(WindowTable, 'Orders+ (Sample - Superstore)'[Sales])
		formatString: 0
		lineageTag: 383da806-379f-42a5-908c-c7177d43d768

	measure Calculation4 = DIVIDE( CALCULATE( SUM('Orders+ (Sample - Superstore)'[Sales]), ALLEXCEPT('Orders+ (Sample - Superstore)', 'Orders+ (Sample - Superstore)'[Customer ID], 'Orders+ (Sample - Superstore)'[Category]) ), CALCULATE( SUM('Orders+ (Sample - Superstore)'[Sales]), ALLEXCEPT('Orders+ (Sample - Superstore)', 'Orders+ (Sample - Superstore)'[Customer ID]) ) )
		formatString: 0
		lineageTag: d58bb56c-82f7-404c-a990-cf1a533262b6

	measure 'Discount Level' = VAR threshold = SELECTEDVALUE('Discount Threshold'[Display As]) VAR discountValue = MAX('Orders+ (Sample - Superstore)'[Discount]) RETURN IF(discountValue > threshold, "High", "Low")
		lineageTag: c82763c9-c683-433c-be9d-32dedca3357b

	measure 'Selected Region Flag' = VAR selectedRegion = SELECTEDVALUE('Select Region'[Display As]) VAR currentRegion = SELECTEDVALUE('Orders+ (Sample - Superstore)'[Region]) RETURN IF(currentRegion = selectedRegion, "Selected", "Other")
		lineageTag: fdf47785-d332-4bb9-bbb8-2ca1144e0d88

	measure Calculation1 = VAR MinYearByCustomer = CALCULATE( MINX('Orders+ (Sample - Superstore)', YEAR('Orders+ (Sample - Superstore)'[Order Date])), ALLEXCEPT('Orders+ (Sample - Superstore)', 'Orders+ (Sample - Superstore)'[Customer ID]) ) RETURN "Joined in " & FORMAT(MinYearByCustomer, "0")
		lineageTag: b03e8315-9698-4e83-91f9-cd750efb0e21

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 2b6bf81b-e24d-4f43-8ceb-99dc3bf99634
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 03a00d2e-a018-43bb-a6a2-9fc1fb60475b
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: datetime
		lineageTag: 87abbcd3-4fd1-4e4b-92fa-1733d30b8b9d
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: datetime
		lineageTag: edac3279-1f69-4690-aa4d-3ae6b4ae6a8f
		summarizeBy: none
		sourceColumn: 'Ship Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 93b5053a-70d3-4d9a-a460-1c2119f175f4
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: c05ad7f0-6d9f-49a4-afd9-fc850c7d1e2f
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: ddb5640b-26d9-42a0-b3da-3db4eab2796a
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 379aee98-cfca-4d68-9224-1acb72f0635a
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Country/Region'
		dataType: string
		lineageTag: 89ea726f-cb04-4c08-ae3f-31deb073b9b6
		summarizeBy: none
		sourceColumn: 'Country/Region'

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 34c30e30-8e3e-41ed-b440-5d53f14506fd
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: ba3a5ad8-d713-4acc-ba96-a0b2a39fa78d
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 2923f523-ccfb-47c0-907b-6a154241df38
		summarizeBy: sum
		sourceColumn: 'Postal Code'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 1eb1610f-4ee5-4848-ac45-ddebd6410d61
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: fc0b53cc-643e-460b-8084-2cc97972867b
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: fbec6e87-6043-4d72-8a74-e7e9bf368879
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: db003912-1be0-4500-91dc-6490040bce9c
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 42d4c614-adda-4443-8967-5bedef38ca58
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: General Number
		lineageTag: 0615eb26-386e-4ca4-b532-7facfa61adf7
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 3d758113-cab8-4c15-9edc-5da16b1bdaf8
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: General Number
		lineageTag: 563a22dd-c70a-4cbc-9ec5-edad8448be69
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		formatString: General Number
		lineageTag: 38180229-47ac-4942-b3a1-02a0be32ac51
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Person
		dataType: string
		lineageTag: 0258f7aa-321f-45e1-9585-8c8f90b48402
		summarizeBy: none
		sourceColumn: Person

		annotation SummarizationSetBy = Automatic

	column 'Region 1'
		dataType: string
		lineageTag: 13d3f435-7f48-47ca-ab24-5f08a3c19742
		summarizeBy: none
		sourceColumn: 'Region 1'

		annotation SummarizationSetBy = Automatic

	column Returned
		dataType: string
		lineageTag: 2631dfe1-18fa-4fc4-acd8-2716a7becbb2
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID 1'
		dataType: string
		lineageTag: 97f39561-827a-438e-a103-dcd24b2c345f
		summarizeBy: none
		sourceColumn: 'Order ID 1'

		annotation SummarizationSetBy = Automatic

	column 'Order Month Name' = FORMAT('Orders+ (Sample - Superstore)'[Order Date], "MMMM")
		lineageTag: b5b214ea-b163-4827-9b26-b5c8c1e52622
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Customer First Name' = VAR fullName = 'Orders+ (Sample - Superstore)'[Customer Name] VAR pos = SEARCH(" ", fullName, 1, 0) RETURN IF(pos = 0, fullName, LEFT(fullName, pos - 1))
		lineageTag: f5bef041-125d-480f-95ce-326521eab17b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Customer Last Name' = VAR fullName = 'Orders+ (Sample - Superstore)'[Customer Name] VAR pos = SEARCH(" ", fullName, 1, 0) RETURN IF(pos = 0, BLANK(), TRIM(MID(fullName, pos + 1, LEN(fullName) - pos)))
		lineageTag: 68edda06-498b-458f-b503-2a44dc3609a3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Profit Band' = IF('Orders+ (Sample - Superstore)'[Profit] > 0, "Profit", "Loss")
		lineageTag: 4cc7123c-64db-49df-a3cf-5e11ea8b4b89
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Category Group' = SWITCH('Orders+ (Sample - Superstore)'[Category], "Furniture", "Home", "Office Supplies", "Office", "Other")
		lineageTag: 21a2b965-1b28-43db-86e9-75b8213b42ec
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Sales Performance Label' = IF( 'Orders+ (Sample - Superstore)'[Profit Band] = "Profit" && 'Orders+ (Sample - Superstore)'[Discount Level] = "High", "Profit with High Discount", 'Orders+ (Sample - Superstore)'[Profit Band] )
		lineageTag: e4265b6f-bb29-4cdf-928b-46b2be11212d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Order Year' = YEAR('Orders+ (Sample - Superstore)'[Order Date])
		formatString: 0
		lineageTag: eb5ee34c-274c-423c-9563-3308bc92245a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Orders+ (Sample - Superstore)' = m
		mode: import
		source =
				let 
					#"Source0" = Table.NestedJoin(#"Orders_Orders+ (Sample - Superstore)", {"Region"}, #"People_Orders+ (Sample - Superstore)", {"Region"}, "People_Orders+ (Sample - Superstore)", JoinKind.Inner),
					#"Expand0" = Table.ExpandTableColumn(#"Source0", "People_Orders+ (Sample - Superstore)", {"Person", "Region"}, {"Person", "Region 1"}),
					#"Source1" = Table.NestedJoin(#"Expand0", {"Order ID"}, #"Returns_Orders+ (Sample - Superstore)", {"Order ID"}, "Returns_Orders+ (Sample - Superstore)", JoinKind.Inner),
					#"Expand1" = Table.ExpandTableColumn(#"Source1", "Returns_Orders+ (Sample - Superstore)", {"Returned", "Order ID"}, {"Returned", "Order ID 1"})
					in #"Expand1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table