table 'People_Orders+ (Sample - Superstore)'
	lineageTag: 298f6055-5fb4-4643-9f09-f656f1629329

	column Person
		dataType: string
		lineageTag: 0d5cd412-a54b-409a-a9dd-82f60361dfe9
		summarizeBy: none
		sourceColumn: Person

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: a7bc8ad7-afc7-4e11-a6ca-4443caa5106f
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition 'People_Orders+ (Sample - Superstore)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Person" = "garage", #"Region" = "Wisconsin"],
					        [#"Person" = "biz", #"Region" = "Rhode Island"],
					        [#"Person" = "howard", #"Region" = "Pennsylvania"],
					        [#"Person" = "rocks", #"Region" = "Maine"],
					        [#"Person" = "babe", #"Region" = "Massachusetts"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Person", type text},
					        {"Region", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table