table 'Returns_Orders+ (Sample - Superstore)'
	lineageTag: 4ce1eda6-4930-4ee3-84d1-a20783e395a6

	column Returned
		dataType: string
		lineageTag: 472684fc-febe-42cf-9a86-07dfe6f162f2
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 28562f18-50ce-4ad1-9d31-a16928271c52
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	partition 'Returns_Orders+ (Sample - Superstore)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"Returned" = "setup", #"Order ID" = 6607],
					        [#"Returned" = "personally", #"Order ID" = 2493],
					        [#"Returned" = "into", #"Order ID" = 2880],
					        [#"Returned" = "sublime", #"Order ID" = 2542],
					        [#"Returned" = "designated", #"Order ID" = 7018]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"Returned", type text},
					        {"Order ID", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table