table 'Custom SQL Query_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)'
	lineageTag: 2b23892e-b673-4796-9363-1a0bb7562c86

	column EFFECTIVE_DATE
		dataType: datetime
		lineageTag: 69097077-b089-4c9f-8236-5c8aab32a6b9
		summarizeBy: none
		sourceColumn: EFFECTIVE_DATE

		annotation SummarizationSetBy = Automatic

	column SECURITY_NAME
		dataType: string
		lineageTag: 9bd5690d-c742-452b-9506-fe4d91500201
		summarizeBy: none
		sourceColumn: SECURITY_NAME

		annotation SummarizationSetBy = Automatic

	column MID_PRICE_INT
		dataType: double
		formatString: General Number
		lineageTag: 67223fdc-ec50-4e93-bb5a-0aab72810868
		summarizeBy: sum
		sourceColumn: MID_PRICE_INT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ASK_PRICE_INT
		dataType: double
		formatString: General Number
		lineageTag: 6e5edecb-2c60-41b8-9066-818bfa6cebbc
		summarizeBy: sum
		sourceColumn: ASK_PRICE_INT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BID_PRICE_INT
		dataType: double
		formatString: General Number
		lineageTag: 4be46078-cf2e-4c00-8d3f-6c64325702b8
		summarizeBy: sum
		sourceColumn: BID_PRICE_INT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VOLCKER_DESK
		dataType: string
		lineageTag: 9b1f4591-895c-4f28-8520-2a2927c26cfb
		summarizeBy: none
		sourceColumn: VOLCKER_DESK

		annotation SummarizationSetBy = Automatic

	column SECURITY_ID
		dataType: string
		lineageTag: 00866283-49b9-4b8b-ae62-0cb41cad6935
		summarizeBy: none
		sourceColumn: SECURITY_ID

		annotation SummarizationSetBy = Automatic

	column SECURITY_MATURITY
		dataType: datetime
		lineageTag: 72880429-044a-44fa-a383-04b74283b386
		summarizeBy: none
		sourceColumn: SECURITY_MATURITY

		annotation SummarizationSetBy = Automatic

	column CURRENCY
		dataType: string
		lineageTag: 958acdb0-79b2-4cae-84f5-3bb4ab46828f
		summarizeBy: none
		sourceColumn: CURRENCY

		annotation SummarizationSetBy = Automatic

	column OBLIGOR_NAME
		dataType: string
		lineageTag: 71cf40ab-6b6f-4d26-91c3-8160751f9b69
		summarizeBy: none
		sourceColumn: OBLIGOR_NAME

		annotation SummarizationSetBy = Automatic

	column IS_CALLABLE
		dataType: string
		lineageTag: 09e5569f-41fb-4962-a691-44e2a8718acf
		summarizeBy: none
		sourceColumn: IS_CALLABLE

		annotation SummarizationSetBy = Automatic

	column FX_CONV_MARKET_DATA_SRC_ID
		dataType: int64
		formatString: 0
		lineageTag: 5a733fba-230c-4d4f-a80c-56bc7245c50d
		summarizeBy: sum
		sourceColumn: FX_CONV_MARKET_DATA_SRC_ID

		annotation SummarizationSetBy = Automatic

	column TO_USD
		dataType: double
		formatString: General Number
		lineageTag: 3f876956-af67-4c8d-8e57-5a12ad537687
		summarizeBy: sum
		sourceColumn: TO_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_CAD
		dataType: double
		formatString: General Number
		lineageTag: 4d466b80-4ab3-4de3-a217-57a0cf14a0f0
		summarizeBy: sum
		sourceColumn: TO_CAD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_EUR
		dataType: double
		formatString: General Number
		lineageTag: 6fc377d0-1218-4305-8bb6-260d19d39f52
		summarizeBy: sum
		sourceColumn: TO_EUR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TO_GBP
		dataType: double
		formatString: General Number
		lineageTag: 44771434-2526-4493-b74d-3595cff9e728
		summarizeBy: sum
		sourceColumn: TO_GBP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SUM(QUANTITY)'
		dataType: double
		formatString: General Number
		lineageTag: fd9cd793-0c23-4942-92c1-46bb69afddb1
		summarizeBy: sum
		sourceColumn: 'SUM(QUANTITY)'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SUM(NOTIONAL_AMOUNT)'
		dataType: double
		formatString: General Number
		lineageTag: 2b528d60-2396-4d4e-a14d-5bf7d65cf76f
		summarizeBy: sum
		sourceColumn: 'SUM(NOTIONAL_AMOUNT)'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Custom SQL Query_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"EFFECTIVE_DATE" = #datetime(2024, 1, 1, 0, 0, 0), #"SECURITY_NAME" = "Sample_SECURITY_NAME_1", #"MID_PRICE_INT" = "Sample_MID_PRICE_INT_1", #"ASK_PRICE_INT" = "Sample_ASK_PRICE_INT_1", #"BID_PRICE_INT" = "Sample_BID_PRICE_INT_1", #"VOLCKER_DESK" = "Sample_VOLCKER_DESK_1", #"SECURITY_ID" = "Sample_SECURITY_ID_1", #"SECURITY_MATURITY" = #datetime(2024, 1, 1, 0, 0, 0), #"CURRENCY" = "Sample_CURRENCY_1", #"OBLIGOR_NAME" = "Sample_OBLIGOR_NAME_1", #"IS_CALLABLE" = "Sample_IS_CALLABLE_1", #"FX_CONV_MARKET_DATA_SRC_ID" = 10, #"TO_USD" = "Sample_TO_USD_1", #"TO_CAD" = "Sample_TO_CAD_1", #"TO_EUR" = "Sample_TO_EUR_1", #"TO_GBP" = "Sample_TO_GBP_1", #"SUM(QUANTITY)" = "Sample_SUM(QUANTITY)_1", #"SUM(NOTIONAL_AMOUNT)" = "Sample_SUM(NOTIONAL_AMOUNT)_1"],
					        [#"EFFECTIVE_DATE" = #datetime(2024, 1, 2, 0, 0, 0), #"SECURITY_NAME" = "Sample_SECURITY_NAME_2", #"MID_PRICE_INT" = "Sample_MID_PRICE_INT_2", #"ASK_PRICE_INT" = "Sample_ASK_PRICE_INT_2", #"BID_PRICE_INT" = "Sample_BID_PRICE_INT_2", #"VOLCKER_DESK" = "Sample_VOLCKER_DESK_2", #"SECURITY_ID" = "Sample_SECURITY_ID_2", #"SECURITY_MATURITY" = #datetime(2024, 1, 2, 0, 0, 0), #"CURRENCY" = "Sample_CURRENCY_2", #"OBLIGOR_NAME" = "Sample_OBLIGOR_NAME_2", #"IS_CALLABLE" = "Sample_IS_CALLABLE_2", #"FX_CONV_MARKET_DATA_SRC_ID" = 20, #"TO_USD" = "Sample_TO_USD_2", #"TO_CAD" = "Sample_TO_CAD_2", #"TO_EUR" = "Sample_TO_EUR_2", #"TO_GBP" = "Sample_TO_GBP_2", #"SUM(QUANTITY)" = "Sample_SUM(QUANTITY)_2", #"SUM(NOTIONAL_AMOUNT)" = "Sample_SUM(NOTIONAL_AMOUNT)_2"],
					        [#"EFFECTIVE_DATE" = #datetime(2024, 1, 3, 0, 0, 0), #"SECURITY_NAME" = "Sample_SECURITY_NAME_3", #"MID_PRICE_INT" = "Sample_MID_PRICE_INT_3", #"ASK_PRICE_INT" = "Sample_ASK_PRICE_INT_3", #"BID_PRICE_INT" = "Sample_BID_PRICE_INT_3", #"VOLCKER_DESK" = "Sample_VOLCKER_DESK_3", #"SECURITY_ID" = "Sample_SECURITY_ID_3", #"SECURITY_MATURITY" = #datetime(2024, 1, 3, 0, 0, 0), #"CURRENCY" = "Sample_CURRENCY_3", #"OBLIGOR_NAME" = "Sample_OBLIGOR_NAME_3", #"IS_CALLABLE" = "Sample_IS_CALLABLE_3", #"FX_CONV_MARKET_DATA_SRC_ID" = 30, #"TO_USD" = "Sample_TO_USD_3", #"TO_CAD" = "Sample_TO_CAD_3", #"TO_EUR" = "Sample_TO_EUR_3", #"TO_GBP" = "Sample_TO_GBP_3", #"SUM(QUANTITY)" = "Sample_SUM(QUANTITY)_3", #"SUM(NOTIONAL_AMOUNT)" = "Sample_SUM(NOTIONAL_AMOUNT)_3"],
					        [#"EFFECTIVE_DATE" = #datetime(2024, 1, 4, 0, 0, 0), #"SECURITY_NAME" = "Sample_SECURITY_NAME_4", #"MID_PRICE_INT" = "Sample_MID_PRICE_INT_4", #"ASK_PRICE_INT" = "Sample_ASK_PRICE_INT_4", #"BID_PRICE_INT" = "Sample_BID_PRICE_INT_4", #"VOLCKER_DESK" = "Sample_VOLCKER_DESK_4", #"SECURITY_ID" = "Sample_SECURITY_ID_4", #"SECURITY_MATURITY" = #datetime(2024, 1, 4, 0, 0, 0), #"CURRENCY" = "Sample_CURRENCY_4", #"OBLIGOR_NAME" = "Sample_OBLIGOR_NAME_4", #"IS_CALLABLE" = "Sample_IS_CALLABLE_4", #"FX_CONV_MARKET_DATA_SRC_ID" = 40, #"TO_USD" = "Sample_TO_USD_4", #"TO_CAD" = "Sample_TO_CAD_4", #"TO_EUR" = "Sample_TO_EUR_4", #"TO_GBP" = "Sample_TO_GBP_4", #"SUM(QUANTITY)" = "Sample_SUM(QUANTITY)_4", #"SUM(NOTIONAL_AMOUNT)" = "Sample_SUM(NOTIONAL_AMOUNT)_4"],
					        [#"EFFECTIVE_DATE" = #datetime(2024, 1, 5, 0, 0, 0), #"SECURITY_NAME" = "Sample_SECURITY_NAME_5", #"MID_PRICE_INT" = "Sample_MID_PRICE_INT_5", #"ASK_PRICE_INT" = "Sample_ASK_PRICE_INT_5", #"BID_PRICE_INT" = "Sample_BID_PRICE_INT_5", #"VOLCKER_DESK" = "Sample_VOLCKER_DESK_5", #"SECURITY_ID" = "Sample_SECURITY_ID_5", #"SECURITY_MATURITY" = #datetime(2024, 1, 5, 0, 0, 0), #"CURRENCY" = "Sample_CURRENCY_5", #"OBLIGOR_NAME" = "Sample_OBLIGOR_NAME_5", #"IS_CALLABLE" = "Sample_IS_CALLABLE_5", #"FX_CONV_MARKET_DATA_SRC_ID" = 50, #"TO_USD" = "Sample_TO_USD_5", #"TO_CAD" = "Sample_TO_CAD_5", #"TO_EUR" = "Sample_TO_EUR_5", #"TO_GBP" = "Sample_TO_GBP_5", #"SUM(QUANTITY)" = "Sample_SUM(QUANTITY)_5", #"SUM(NOTIONAL_AMOUNT)" = "Sample_SUM(NOTIONAL_AMOUNT)_5"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"EFFECTIVE_DATE", type datetime},
					        {"SECURITY_NAME", type text},
					        {"MID_PRICE_INT", type number},
					        {"ASK_PRICE_INT", type number},
					        {"BID_PRICE_INT", type number},
					        {"VOLCKER_DESK", type text},
					        {"SECURITY_ID", type text},
					        {"SECURITY_MATURITY", type datetime},
					        {"CURRENCY", type text},
					        {"OBLIGOR_NAME", type text},
					        {"IS_CALLABLE", type text},
					        {"FX_CONV_MARKET_DATA_SRC_ID", Int64.Type},
					        {"TO_USD", type number},
					        {"TO_CAD", type number},
					        {"TO_EUR", type number},
					        {"TO_GBP", type number},
					        {"SUM(QUANTITY)", type number},
					        {"SUM(NOTIONAL_AMOUNT)", type number}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table