table 'volcker_rpt_inventory_aging_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)'
	lineageTag: 7db75d98-6539-4fa1-855e-24cf6847da84

	column id
		dataType: int64
		formatString: 0
		lineageTag: 3ed4bbe2-0861-436a-925b-0345e34c13e8
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column effective_date
		dataType: datetime
		lineageTag: 332db9a2-2d3d-406c-a15c-9c6739f5b7b8
		summarizeBy: none
		sourceColumn: effective_date

		annotation SummarizationSetBy = Automatic

	column position_id_position
		dataType: string
		lineageTag: b6ec1d4c-8874-489d-8c5b-25792617ab53
		summarizeBy: none
		sourceColumn: position_id_position

		annotation SummarizationSetBy = Automatic

	column product
		dataType: string
		lineageTag: fb860654-8445-4a53-8f84-d95517e3999d
		summarizeBy: none
		sourceColumn: product

		annotation SummarizationSetBy = Automatic

	column volcker_desk_id
		dataType: int64
		formatString: 0
		lineageTag: 4bd8082d-08b0-4dc9-b3f3-ea701259a65f
		summarizeBy: sum
		sourceColumn: volcker_desk_id

		annotation SummarizationSetBy = Automatic

	column counterparty_name
		dataType: string
		lineageTag: e8825d7f-8dc8-4ca5-9e06-a2b8cb674944
		summarizeBy: none
		sourceColumn: counterparty_name

		annotation SummarizationSetBy = Automatic

	column source_system
		dataType: string
		lineageTag: 22c26805-3948-43ab-9cf0-a821be699e61
		summarizeBy: none
		sourceColumn: source_system

		annotation SummarizationSetBy = Automatic

	column aging_report_value
		dataType: double
		formatString: General Number
		lineageTag: 70ba62d2-d736-46f7-b79f-5fc67006c51e
		summarizeBy: sum
		sourceColumn: aging_report_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column age_of_trade
		dataType: int64
		formatString: 0
		lineageTag: 15941418-d8fe-4642-856e-652d4897f32d
		summarizeBy: sum
		sourceColumn: age_of_trade

		annotation SummarizationSetBy = Automatic

	column bucket
		dataType: string
		lineageTag: cd9e57af-d139-4984-887a-6622acce5dbe
		summarizeBy: none
		sourceColumn: bucket

		annotation SummarizationSetBy = Automatic

	column classification
		dataType: string
		lineageTag: bff75407-e7c2-4eab-8314-90bc35c773c1
		summarizeBy: none
		sourceColumn: classification

		annotation SummarizationSetBy = Automatic

	column trade_id
		dataType: string
		lineageTag: 944afafb-d226-4a6a-ac7b-729f5701d7ad
		summarizeBy: none
		sourceColumn: trade_id

		annotation SummarizationSetBy = Automatic

	column aging_report_value_abs
		dataType: double
		formatString: General Number
		lineageTag: c98d2f54-f965-44ad-b345-0448ef631051
		summarizeBy: sum
		sourceColumn: aging_report_value_abs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column file_path
		dataType: string
		lineageTag: f1f358ab-ff53-4954-bce0-c55082f56700
		summarizeBy: none
		sourceColumn: file_path

		annotation SummarizationSetBy = Automatic

	column created_date
		dataType: datetime
		lineageTag: 5a893a88-4b91-40d3-a2eb-7bf33e8196b9
		summarizeBy: none
		sourceColumn: created_date

		annotation SummarizationSetBy = Automatic

	column security_id_position
		dataType: string
		lineageTag: c8aad99c-92a2-4352-a33c-10de121977ab
		summarizeBy: none
		sourceColumn: security_id_position

		annotation SummarizationSetBy = Automatic

	column source_book
		dataType: string
		lineageTag: 40eb4993-96f9-4385-a75c-568cf55717df
		summarizeBy: none
		sourceColumn: source_book

		annotation SummarizationSetBy = Automatic

	column book
		dataType: string
		lineageTag: e9d25248-925d-493d-9f3f-c3c41caf863b
		summarizeBy: none
		sourceColumn: book

		annotation SummarizationSetBy = Automatic

	partition 'volcker_rpt_inventory_aging_Postgres_Volcker_Aging_Deallevel_data_GFIRates (local copy)' = m
		mode: import
		source =
				let
					    Source = Table.FromRecords({
					        [#"id" = 3290, #"effective_date" = #date(2020, 12, 5), #"position_id_position" = "French Polisher", #"product" = "book", #"volcker_desk_id" = 3286, #"counterparty_name" = "Manie George", #"source_system" = "summary", #"aging_report_value" = 521.1, #"age_of_trade" = 96, #"bucket" = "provision", #"classification" = "projection", #"trade_id" = 7871, #"aging_report_value_abs" = 678.87, #"file_path" = "ian", #"created_date" = #datetime(2022, 1, 25, 7, 56, 45), #"security_id_position" = "Traffic Warden", #"source_book" = "biz", #"book" = "password"],
					        [#"id" = 7596, #"effective_date" = #date(2021, 5, 1), #"position_id_position" = "Marketing Agent", #"product" = "relations", #"volcker_desk_id" = 5297, #"counterparty_name" = "Eugene Reilly", #"source_system" = "asking", #"aging_report_value" = 207.09, #"age_of_trade" = 80, #"bucket" = "institutional", #"classification" = "static", #"trade_id" = 8171, #"aging_report_value_abs" = 311.99, #"file_path" = "manage", #"created_date" = #datetime(2024, 1, 13, 15, 7, 27), #"security_id_position" = "Landworker", #"source_book" = "switches", #"book" = "strategic"],
					        [#"id" = 8795, #"effective_date" = #date(2024, 1, 25), #"position_id_position" = "Chaplain", #"product" = "johnson", #"volcker_desk_id" = 6238, #"counterparty_name" = "Maryland Carrillo", #"source_system" = "scottish", #"aging_report_value" = 822.62, #"age_of_trade" = 39, #"bucket" = "therapy", #"classification" = "desired", #"trade_id" = 1304, #"aging_report_value_abs" = 37.49, #"file_path" = "hiv", #"created_date" = #datetime(2023, 1, 30, 21, 26, 54), #"security_id_position" = "Toy Maker", #"source_book" = "merchants", #"book" = "advertisement"],
					        [#"id" = 4524, #"effective_date" = #date(2023, 11, 6), #"position_id_position" = "Technical Author", #"product" = "mall", #"volcker_desk_id" = 4398, #"counterparty_name" = "Maurita Kinney", #"source_system" = "advertisers", #"aging_report_value" = 452.02, #"age_of_trade" = 37, #"bucket" = "spin", #"classification" = "tropical", #"trade_id" = 1284, #"aging_report_value_abs" = 705.87, #"file_path" = "netscape", #"created_date" = #datetime(2022, 2, 8, 17, 11, 14), #"security_id_position" = "Cab Driver", #"source_book" = "lanka", #"book" = "applications"],
					        [#"id" = 3536, #"effective_date" = #date(2021, 4, 7), #"position_id_position" = "Plater", #"product" = "branches", #"volcker_desk_id" = 3210, #"counterparty_name" = "Son Bradford", #"source_system" = "both", #"aging_report_value" = 818.84, #"age_of_trade" = 83, #"bucket" = "keywords", #"classification" = "registration", #"trade_id" = 6750, #"aging_report_value_abs" = 693.31, #"file_path" = "venue", #"created_date" = #datetime(2024, 4, 15, 13, 52, 53), #"security_id_position" = "Loss Assessor", #"source_book" = "songs", #"book" = "situations"]
					    }),
					    Typed = Table.TransformColumnTypes(Source, {
					        {"id", Int64.Type},
					        {"effective_date", type date},
					        {"position_id_position", type text},
					        {"product", type text},
					        {"volcker_desk_id", Int64.Type},
					        {"counterparty_name", type text},
					        {"source_system", type text},
					        {"aging_report_value", type number},
					        {"age_of_trade", Int64.Type},
					        {"bucket", type text},
					        {"classification", type text},
					        {"trade_id", type text},
					        {"aging_report_value_abs", type number},
					        {"file_path", type text},
					        {"created_date", type datetime},
					        {"security_id_position", type text},
					        {"source_book", type text},
					        {"book", type text}
					    })
					in
					    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table