table 'Balance Threshold'
	lineageTag: 1a35ecd9-c476-448b-894b-edbd0e5fb5f2

	measure 'Balance Threshold Value' = SELECTEDVALUE('Balance Threshold'[Balance Threshold], 0.0)
		lineageTag: 46b9e248-564f-4018-bf11-0b3c4db18389

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Threshold'
		dataType: double
		formatString: 0
		lineageTag: c71b07e3-1ad2-4c38-9623-1b26962e54c5
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Balance Threshold' = calculated
		mode: import
		source = GENERATESERIES(0.0, 500000.0, 5000.0)

	annotation PBI_Id = 0c29281c282a44feb4c8c17a98546e7b

